{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsButtonTag","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKBottomControlsView(cpy)settingsButtonTag","roleHeading":"Type Property","title":"settingsButtonTag","navigatorTitle":[{"text":"settingsButtonTag","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"settingsButtonTag"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkbottomcontrolsview\/settingsbuttontag"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkbottomcontrolsview\/settingsbuttontag"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKBottomControlsView\/settingsButtonTag","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"role":"symbol","title":"BottomControlsView","kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BottomControlsView","kind":"identifier"}],"navigatorTitle":[{"text":"BottomControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","abstract":[{"type":"text","text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий."}]},"doc://onevideo.OVKit/documentation/OVKit/OVKBottomControlsView/settingsButtonTag":{"navigatorTitle":[{"kind":"identifier","text":"settingsButtonTag"}],"url":"\/documentation\/ovkit\/ovkbottomcontrolsview\/settingsbuttontag","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKBottomControlsView\/settingsButtonTag","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"settingsButtonTag"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[],"title":"settingsButtonTag"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"settingsButtonTag"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"settingsButtonTag","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"settingsButtonTag","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","value":[{"kind":"identifier","text":"OVKBottomControlsView"}]},{"op":"replace","value":"settingsButtonTag","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKBottomControlsView~1settingsButtonTag\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKBottomControlsView~1settingsButtonTag\/fragments","value":[{"kind":"identifier","text":"settingsButtonTag"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}