{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult\/error(_:)"},"kind":"symbol","metadata":{"title":"ThumbnailProvider.FetchResult.error(_:)","role":"symbol","roleHeading":"Case","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit22ThumbnailProviderErrorO","text":"ThumbnailProviderError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"case","externalID":"s:5OVKit17ThumbnailProviderC11FetchResultO5erroryAeA0bC5ErrorOcAEmF"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit22ThumbnailProviderErrorO","text":"ThumbnailProviderError","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"abstract":[{"type":"text","text":"В процессе загрузки по сети произошла ошибка."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailprovider\/fetchresult\/error(_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/FetchResult/error(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult\/error(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ThumbnailProviderError","preciseIdentifier":"s:5OVKit22ThumbnailProviderErrorO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"ThumbnailProvider.FetchResult.error(_:)","type":"topic","url":"\/documentation\/ovkit\/thumbnailprovider\/fetchresult\/error(_:)","kind":"symbol","abstract":[{"text":"В процессе загрузки по сети произошла ошибка.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"title":"ThumbnailProvider","url":"\/documentation\/ovkit\/thumbnailprovider","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailProvider"}],"kind":"symbol","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/FetchResult":{"url":"\/documentation\/ovkit\/thumbnailprovider\/fetchresult","title":"ThumbnailProvider.FetchResult","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FetchResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FetchResult"}],"kind":"symbol","abstract":[{"type":"text","text":"Результат получения thumbnail."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderError":{"type":"topic","navigatorTitle":[{"text":"ThumbnailProviderError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProviderError","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderError","abstract":[{"type":"text","text":"Ошибка загрузчика thumbnail."}],"url":"\/documentation\/ovkit\/thumbnailprovidererror","role":"symbol","kind":"symbol","title":"ThumbnailProviderError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKThumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title"},{"op":"replace","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments"},{"op":"replace","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle"}]}]}