{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbnail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ThumbnailProviderThumbnail","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:5OVKit17ThumbnailProviderC11FetchResultO9thumbnailyAeA0bcB0CcAEmF","roleHeading":"Case","symbolKind":"case","modules":[{"name":"OVKit"}],"title":"ThumbnailProvider.FetchResult.thumbnail(_:)"},"abstract":[{"type":"text","text":"Изображение, готовое к показу."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult\/thumbnail(_:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailprovider\/fetchresult\/thumbnail(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbnail","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","text":"ThumbnailProviderThumbnail","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","url":"\/documentation\/ovkit\/thumbnailprovider","title":"ThumbnailProvider"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Описание изображения для thumbnail."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","title":"ThumbnailProviderThumbnail"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/FetchResult/thumbnail(_:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult\/thumbnail(_:)","abstract":[{"text":"Изображение, готовое к показу.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","text":"ThumbnailProviderThumbnail"},{"kind":"text","text":")"}],"type":"topic","title":"ThumbnailProvider.FetchResult.thumbnail(_:)","url":"\/documentation\/ovkit\/thumbnailprovider\/fetchresult\/thumbnail(_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/FetchResult":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FetchResult","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FetchResult","kind":"identifier"}],"type":"topic","abstract":[{"text":"Результат получения thumbnail.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult","url":"\/documentation\/ovkit\/thumbnailprovider\/fetchresult","title":"ThumbnailProvider.FetchResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace","value":"OVKThumbnailProvider"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","op":"replace","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle"},{"op":"replace","value":"OVKThumbnailProviderThumbnail","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","value":[{"kind":"identifier","text":"OVKThumbnailProviderThumbnail"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/navigatorTitle","op":"replace","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}]}]}]}