{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"actionButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/actionbutton"]},{"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/actionbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/actionButton","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)actionButton","modules":[{"name":"OVKit"}],"title":"actionButton","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionButton","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoRestrictionButtonType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"type":"topic","title":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","role":"symbol","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoRestrictionType","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/videorestrictiontype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VideoRestrictionButtonType","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestrictionbuttontype","abstract":[],"title":"VideoRestrictionButtonType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionType/actionButton":{"title":"actionButton","required":true,"url":"\/documentation\/ovkit\/ovkvideorestrictiontype\/actionbutton","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"actionButton","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/actionButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"actionButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"actionButton","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<OVKVideoRestrictionButtonType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionButtonType"},{"kind":"text","text":" "},{"text":"actionButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","op":"replace","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"value":"OVKVideoRestrictionButtonType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title"},{"value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments"},{"value":"actionButton","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1actionButton\/title"},{"value":[{"kind":"identifier","text":"actionButton"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1actionButton\/fragments","op":"replace"}]}]}