{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/canPreview","interfaceLanguage":"swift"},"metadata":{"title":"canPreview","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"canPreview","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPreview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)canPreview"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/canpreview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/canpreview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"type":"topic","title":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","role":"symbol","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoRestrictionType","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/videorestrictiontype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionType/canPreview":{"type":"topic","title":"canPreview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/canPreview","role":"symbol","navigatorTitle":[{"text":"canPreview","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPreview"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/ovkit\/ovkvideorestrictiontype\/canpreview","required":true,"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"canPreview"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"canPreview","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPreview"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType"},{"value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments"},{"value":"canPreview","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1canPreview\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1canPreview\/fragments","value":[{"kind":"identifier","text":"canPreview"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}