{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/cardIcon"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)cardIcon","role":"symbol","required":true,"title":"cardIcon","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIcon"},{"text":": [","kind":"text"},{"text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"property","navigatorTitle":[{"text":"cardIcon","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/cardicon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/cardicon"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIcon"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"kind":"symbol","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"type":"topic","title":"VideoRestrictionType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionType"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","url":"\/documentation\/ovkit\/videorestrictiontype"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionType/cardIcon":{"abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/cardIcon","required":true,"type":"topic","title":"cardIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cardIcon","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cardIcon"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkvideorestrictiontype\/cardicon"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"title":"ImageAssetType","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/imageassettype","navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cardIcon"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cardIcon"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<OVKImageAssetType>>"},{"text":" * ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoRestrictionType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1cardIcon\/title","value":"cardIcon","op":"replace"},{"op":"replace","value":[{"text":"cardIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1cardIcon\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"kind":"identifier","text":"OVKImageAssetType"}]}]}]}