{"variants":[{"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/listicon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideorestrictiontype\/listicon"]}],"metadata":{"navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"listIcon","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"required":true,"modules":[{"name":"OVKit"}],"title":"listIcon","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)listIcon"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listIcon","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/listIcon","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAssetType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"title":"ImageAssetType","url":"\/documentation\/ovkit\/imageassettype","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","title":"VideoRestrictionType","url":"\/documentation\/ovkit\/videorestrictiontype","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionType/listIcon":{"title":"listIcon","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listIcon","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier","text":"ImageAssetType"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkvideorestrictiontype\/listicon","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionType\/listIcon","navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"listIcon"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"listIcon","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<OVKImageAssetType>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"listIcon","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"OVKImageAssetType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"kind":"identifier","text":"OVKImageAssetType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","op":"replace","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1listIcon\/title","value":"listIcon"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionType~1listIcon\/fragments","op":"replace","value":[{"text":"listIcon","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}