{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHandlers"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"conformingTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp","text":"T"},{"kind":"text","text":".Type) -> ["},{"text":"T","preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp","kind":"typeIdentifier"},{"text":"] ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"StatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Общий протокол ранее добавленных "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":" для получения.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Искомые хендлеры указанного типа, если ранее они были добавлены."}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/statscollector\/gethandlers(conformingto:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector\/getHandlers(conformingTo:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Получение ранее добавленных "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":", которые наследуются от конкретного протокола."}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getHandlers"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"text":"conformingTo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp","kind":"typeIdentifier","text":"T"},{"text":".Type) -> [","kind":"text"},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp"},{"text":"]","kind":"text"}],"title":"getHandlers(conformingTo:)","extendedModule":"OVKit","role":"symbol","externalID":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"kind":"symbol","title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"url":"\/documentation\/ovkit\/playerview","role":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector/getHandlers(conformingTo:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getHandlers","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"conformingTo"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp"},{"text":".Type) -> [","kind":"text"},{"preciseIdentifier":"s:5OVKit14StatsCollectorPAAE11getHandlers12conformingToSayqd__Gqd__m_tAA0B7HandlerRd__lF1TL_qd__mfp","kind":"typeIdentifier","text":"T"},{"kind":"text","text":"]"}],"title":"getHandlers(conformingTo:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector\/getHandlers(conformingTo:)","url":"\/documentation\/ovkit\/statscollector\/gethandlers(conformingto:)","abstract":[{"type":"text","text":"Получение ранее добавленных "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference","isActive":true},{"type":"text","text":", которые наследуются от конкретного протокола."}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"title":"Video","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/video","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true,"type":"reference"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"или переходах в PiP и fullscreen.","type":"text"}],"title":"StatsCollector","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsCollector"}],"url":"\/documentation\/ovkit\/statscollector"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}]},{"value":"OVKStatsCollector","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}]}]}]}