{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statscollector\/statsqueue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statscollector\/statsqueue"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector\/statsQueue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"}],"externalID":"c:@M@OVKit@objc(pl)OVKStatsCollector(py)statsQueue","role":"symbol","modules":[{"name":"OVKit"}],"title":"statsQueue","required":true,"navigatorTitle":[{"kind":"identifier","text":"statsQueue"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"url":"\/documentation\/ovkit\/statscollector","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsCollector"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"kind":"symbol","title":"StatsCollector"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"role":"symbol","title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/statshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"title":"StatsHandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector/statsQueue":{"title":"statsQueue","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/statscollector\/statsqueue","required":true,"navigatorTitle":[{"kind":"identifier","text":"statsQueue"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector\/statsQueue"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"role":"symbol","url":"\/documentation\/ovkit\/video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"statsQueue","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"statsQueue"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":" ","kind":"text"},{"text":"statsQueue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector~1statsQueue\/title","value":"statsQueue","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector~1statsQueue\/fragments","value":[{"text":"statsQueue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"}]}]}