{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/cellular","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular"}],"symbolKind":"case","title":"AutoQualityPresetTuner.NetworkStatus.cellular","role":"symbol","externalID":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO8cellularyA2EmF","modules":[{"name":"OVKit"}],"roleHeading":"Case"},"abstract":[{"text":"Сеть доступна по WWAN.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/cellular"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner","kind":"symbol","abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoQualityPresetTuner"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"title":"AutoQualityPresetTuner"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","abstract":[{"text":"Статусы доступности сети.","type":"text"}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","title":"AutoQualityPresetTuner.NetworkStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"NetworkStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/cellular":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/cellular","abstract":[{"type":"text","text":"Сеть доступна по WWAN."}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/cellular","title":"AutoQualityPresetTuner.NetworkStatus.cellular","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellular","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","value":"OVKAutoQualityPresetTuner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}