{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"hash(into:)","modules":[{"name":"OVKit","relatedModules":["Swift"]}],"extendedModule":"Swift","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/RawRepresentable-Implementations"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner","kind":"symbol","abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","title":"AutoQualityPresetTuner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoQualityPresetTuner","kind":"identifier"}],"navigatorTitle":[{"text":"AutoQualityPresetTuner","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","abstract":[{"text":"Статусы доступности сети.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"title":"AutoQualityPresetTuner.NetworkStatus"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/RawRepresentable-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/hash(into:)":{"role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/hash(into:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/hash(into:)","title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"OVKAutoQualityPresetTuner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","op":"replace","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}