{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/init(rawvalue:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum"]]},"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(rawValue:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO8rawValueAESgSi_tcfc","symbolKind":"init"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"url":"\/documentation\/ovkit\/autoqualitypresettuner","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","title":"AutoQualityPresetTuner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoQualityPresetTuner"}],"abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkStatus"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","title":"AutoQualityPresetTuner.NetworkStatus","navigatorTitle":[{"kind":"identifier","text":"NetworkStatus"}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","abstract":[{"type":"text","text":"Статусы доступности сети."}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/init(rawValue:)":{"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/init(rawvalue:)","abstract":[],"kind":"symbol","role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","op":"replace","value":"OVKAutoQualityPresetTuner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"op":"replace"}]}]}