{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/notReachable"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Сеть недоступна."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/notreachable"]}],"metadata":{"title":"AutoQualityPresetTuner.NetworkStatus.notReachable","symbolKind":"case","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Case","externalID":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO12notReachableyA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notReachable","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReachable"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"url":"\/documentation\/ovkit\/autoqualitypresettuner","title":"AutoQualityPresetTuner","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoQualityPresetTuner"}],"abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/notReachable":{"abstract":[{"text":"Сеть недоступна.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/notReachable","title":"AutoQualityPresetTuner.NetworkStatus.notReachable","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/notreachable","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notReachable","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"navigatorTitle":[{"text":"NetworkStatus","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","abstract":[{"type":"text","text":"Статусы доступности сети."}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"role":"symbol","title":"AutoQualityPresetTuner.NetworkStatus"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","op":"replace","value":"OVKAutoQualityPresetTuner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","op":"replace","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}