{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifi"}],"symbolKind":"case","role":"symbol","externalID":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO4wifiyA2EmF","roleHeading":"Case","title":"AutoQualityPresetTuner.NetworkStatus.wifi","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Сеть доступна по Wi-Fi.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wifi"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/wifi"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/wifi","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner","title":"AutoQualityPresetTuner","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutoQualityPresetTuner","kind":"identifier"}],"navigatorTitle":[{"text":"AutoQualityPresetTuner","kind":"identifier"}],"abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NetworkStatus"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","abstract":[{"type":"text","text":"Статусы доступности сети."}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","kind":"symbol","title":"AutoQualityPresetTuner.NetworkStatus"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum/wifi":{"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum\/wifi","title":"AutoQualityPresetTuner.NetworkStatus.wifi","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifi"}],"abstract":[{"type":"text","text":"Сеть доступна по Wi-Fi."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum\/wifi"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKAutoQualityPresetTuner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title"},{"op":"replace","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments"},{"value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle"}]}]}