{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Type Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"dataSaving","kind":"identifier"}],"extendedModule":"OVKit","modules":[{"name":"OVKit"}],"externalID":"c:@CM@OVKit@objc(cs)OVKQualityRange(cpy)dataSaving","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSaving","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"}],"title":"dataSaving"},"variants":[{"paths":["\/documentation\/ovkit\/qualityrange\/datasaving"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/qualityrange\/datasaving"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/dataSaving","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Предпочтение отдается более низкому качеству для экономии трафика. Допустимые значения до 480p включительно."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSaving","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"url":"\/documentation\/ovkit\/qualityrange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","type":"topic","title":"QualityRange","role":"symbol","abstract":[{"type":"text","text":"Диапазон качества видео."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityRange","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/dataSaving":{"type":"topic","url":"\/documentation\/ovkit\/qualityrange\/datasaving","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSaving"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/dataSaving","abstract":[{"text":"Предпочтение отдается более низкому качеству для экономии трафика. Допустимые значения до 480p включительно.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSaving"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange"}],"title":"dataSaving"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"dataSaving","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"dataSaving","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKQualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"text":" * ","kind":"text"},{"text":"dataSaving","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"text":"OVKQualityRange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1dataSaving\/title","value":"dataSaving","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1dataSaving\/fragments","value":[{"text":"dataSaving","kind":"identifier"}],"op":"replace"}]}]}