{"metadata":{"role":"symbol","extendedModule":"OVKit","externalID":"c:@CM@OVKit@objc(cs)OVKQualityRange(cpy)full","symbolKind":"property","navigatorTitle":[{"text":"full","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"modules":[{"name":"OVKit"}],"roleHeading":"Type Property","title":"full"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"QualityRange"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Полный диапазон качеств.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/full","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/qualityrange\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/qualityrange\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange/full":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/full","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/qualityrange\/full","navigatorTitle":[{"kind":"identifier","text":"full"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Полный диапазон качеств."}],"title":"full","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"url":"\/documentation\/ovkit\/qualityrange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","title":"QualityRange","role":"symbol","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"full","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"full","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":" * "},{"kind":"identifier","text":"full"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"full","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1full\/title","op":"replace"},{"value":[{"text":"full","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1full\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}]}]}]}