{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrWorseThan:)"},"variants":[{"paths":["\/documentation\/ovkit\/qualityrange\/init(sameorworsethan:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/qualityrange\/init(sameorworsethan:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sameOrWorseThan"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSameOrWorseThan:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@OVKit@objc(cs)OVKQualityRange(im)initWithSameOrWorseThan:","title":"init(sameOrWorseThan:)","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"init"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"sameOrWorseThan","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"highBound"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"type":"topic","kind":"symbol","title":"QualityRange","navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","abstract":[{"type":"text","text":"Диапазон качества видео."}],"url":"\/documentation\/ovkit\/qualityrange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityRange","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/init(sameOrWorseThan:)":{"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/qualityrange\/init(sameorworsethan:)","navigatorTitle":[{"kind":"identifier","text":"initWithSameOrWorseThan:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrWorseThan:)","title":"init(sameOrWorseThan:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sameOrWorseThan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithSameOrWorseThan:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSameOrWorseThan:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSameOrWorseThan:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"highBound"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"kind":"identifier","text":"OVKQualityRange"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"value":"initWithSameOrWorseThan:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrWorseThan:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrWorseThan:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSameOrWorseThan:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}