{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/doubleTap"},"variants":[{"paths":["\/documentation\/ovkit\/statsseekmethod\/doubletap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statsseekmethod\/doubletap"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleTap"}],"externalID":"c:@M@OVKit@E@OVKStatsSeekMethod@OVKStatsSeekMethodDoubleTap","title":"StatsSeekMethod.doubleTap","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKStatsSeekMethodDoubleTap","kind":"identifier"}]},"abstract":[{"type":"text","text":"Способ перемотки двойным нажатием на краях экрана"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doubleTap"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/doubleTap":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Способ перемотки двойным нажатием на краях экрана","type":"text"}],"title":"StatsSeekMethod.doubleTap","navigatorTitle":[{"text":"OVKStatsSeekMethodDoubleTap","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"doubleTap","kind":"identifier"}],"url":"\/documentation\/ovkit\/statsseekmethod\/doubletap","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/doubleTap"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","url":"\/documentation\/ovkit\/statsseekmethod","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsSeekMethod"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Способ перемотки видео, используется для статистики","type":"text"}],"title":"StatsSeekMethod"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKStatsSeekMethodDoubleTap","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKStatsSeekMethodDoubleTap"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKStatsSeekMethodDoubleTap"}]}]},"op":"replace"},{"value":"OVKStatsSeekMethodDoubleTap","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1doubleTap\/title"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethodDoubleTap"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1doubleTap\/fragments","op":"replace"},{"value":"OVKStatsSeekMethod","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]}]}]}