{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/statsseekmethod\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"OVKit"}],"roleHeading":"API Collection"},"kind":"article","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/!=(_:_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/!=(_:_:)":{"kind":"symbol","type":"topic","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/ovkit\/statsseekmethod\/!=(_:_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/!=(_:_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsSeekMethod","kind":"identifier"}],"navigatorTitle":[{"text":"StatsSeekMethod","kind":"identifier"}],"title":"StatsSeekMethod","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKStatsSeekMethod","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle"}]}]}