{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","title":"StatsSeekMethod.goLive","navigatorTitle":[{"kind":"identifier","text":"OVKStatsSeekMethodGoLive"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKStatsSeekMethod@OVKStatsSeekMethodGoLive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"goLive","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/goLive","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Действие перехода к прямому эфиру."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"goLive"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Актуально только при воспроизведении прямой трансляции."}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/statsseekmethod\/golive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statsseekmethod\/golive"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/goLive":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"goLive"}],"url":"\/documentation\/ovkit\/statsseekmethod\/golive","abstract":[{"type":"text","text":"Действие перехода к прямому эфиру."}],"type":"topic","title":"StatsSeekMethod.goLive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/goLive","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKStatsSeekMethodGoLive"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsSeekMethod"}],"role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","type":"topic","title":"StatsSeekMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","abstract":[{"text":"Способ перемотки видео, используется для статистики","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKStatsSeekMethodGoLive","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKStatsSeekMethodGoLive","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKStatsSeekMethodGoLive","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1goLive\/title","value":"OVKStatsSeekMethodGoLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1goLive\/fragments","value":[{"kind":"identifier","text":"OVKStatsSeekMethodGoLive"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title","value":"OVKStatsSeekMethod","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"op":"replace"}]}]}