{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:5OVKit15StatsSeekMethodO8rawValueACSgSi_tcfc","symbolKind":"init","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/init(rawValue:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/statsseekmethod\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/init(rawValue:)":{"abstract":[],"kind":"symbol","role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/init(rawValue:)","url":"\/documentation\/ovkit\/statsseekmethod\/init(rawvalue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsSeekMethod"}],"kind":"symbol","title":"StatsSeekMethod","abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKStatsSeekMethod","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}