{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@OVKit@E@OVKStatsSeekMethod@OVKStatsSeekMethodRemoteCommand","symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","title":"StatsSeekMethod.remoteCommand","navigatorTitle":[{"kind":"identifier","text":"OVKStatsSeekMethodRemoteCommand"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteCommand","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Перемотка через системные медиа-контролы.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/remoteCommand"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteCommand"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Например, в Центре уведомлений или в Пункте управления."}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/statsseekmethod\/remotecommand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statsseekmethod\/remotecommand"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsSeekMethod","kind":"identifier"}],"navigatorTitle":[{"text":"StatsSeekMethod","kind":"identifier"}],"title":"StatsSeekMethod","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/remoteCommand":{"role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod\/remotecommand","kind":"symbol","title":"StatsSeekMethod.remoteCommand","abstract":[{"type":"text","text":"Перемотка через системные медиа-контролы."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/remoteCommand","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteCommand","kind":"identifier"}],"navigatorTitle":[{"text":"OVKStatsSeekMethodRemoteCommand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKStatsSeekMethodRemoteCommand","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethodRemoteCommand"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKStatsSeekMethodRemoteCommand","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKStatsSeekMethod","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title","op":"replace"},{"value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","op":"replace"},{"value":"OVKStatsSeekMethodRemoteCommand","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1remoteCommand\/title","op":"replace"},{"value":[{"text":"OVKStatsSeekMethodRemoteCommand","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1remoteCommand\/fragments","op":"replace"}]}]}