{"metadata":{"externalID":"c:@M@OVKit@E@OVKStatsSeekMethod@OVKStatsSeekMethodTimeline","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"timeline","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","title":"StatsSeekMethod.timeline","navigatorTitle":[{"text":"OVKStatsSeekMethodTimeline","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/timeline"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeline"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsseekmethod\/timeline"]},{"paths":["\/documentation\/ovkit\/statsseekmethod\/timeline"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Способ перемотки протягиванием ползунка на временной шкале"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/timeline":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeline"}],"kind":"symbol","abstract":[{"type":"text","text":"Способ перемотки протягиванием ползунка на временной шкале"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/timeline","url":"\/documentation\/ovkit\/statsseekmethod\/timeline","title":"StatsSeekMethod.timeline","navigatorTitle":[{"kind":"identifier","text":"OVKStatsSeekMethodTimeline"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsSeekMethod"}],"kind":"symbol","title":"StatsSeekMethod","abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKStatsSeekMethodTimeline","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethodTimeline"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKStatsSeekMethodTimeline","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1timeline\/title","value":"OVKStatsSeekMethodTimeline","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1timeline\/fragments","value":[{"text":"OVKStatsSeekMethodTimeline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title","value":"OVKStatsSeekMethod","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"op":"replace"}]}]}