{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKStatsSeekMethodUnknown"}],"externalID":"c:@M@OVKit@E@OVKStatsSeekMethod@OVKStatsSeekMethodUnknown","modules":[{"name":"OVKit"}],"roleHeading":"Case","symbolKind":"case","title":"StatsSeekMethod.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsseekmethod\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statsseekmethod\/unknown"]}],"abstract":[{"type":"text","text":"Неизвестный способ перемотки."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/unknown","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsSeekMethod"}],"role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","type":"topic","title":"StatsSeekMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","abstract":[{"text":"Способ перемотки видео, используется для статистики","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/unknown":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/unknown","url":"\/documentation\/ovkit\/statsseekmethod\/unknown","type":"topic","title":"StatsSeekMethod.unknown","role":"symbol","navigatorTitle":[{"text":"OVKStatsSeekMethodUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"Неизвестный способ перемотки."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKStatsSeekMethodUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKStatsSeekMethodUnknown","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKStatsSeekMethodUnknown","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title","value":"OVKStatsSeekMethod"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1unknown\/title","value":"OVKStatsSeekMethodUnknown"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1unknown\/fragments","value":[{"kind":"identifier","text":"OVKStatsSeekMethodUnknown"}]}]}]}