{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"]]},"kind":"article","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/equatable-implementations"]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/!=(_:_:)":{"url":"\/documentation\/ovkit\/cmaftrackreaderversion\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"role":"symbol","type":"topic","title":"!=(_:_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","role":"symbol","title":"CmafTrackReaderVersion","navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/cmaftrackreaderversion"}},"variantOverrides":[{"patch":[{"value":"OVCmafTrackReaderVersion","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title"},{"value":[{"kind":"identifier","text":"OVCmafTrackReaderVersion"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments"},{"value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}