{"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","externalID":"s:5OVKit22CmafTrackReaderVersionO8rawValueACSgSu_tcfc","role":"symbol","title":"init(rawValue:)","roleHeading":"Initializer","modules":[{"name":"OVKit"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/init(rawValue:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/init(rawValue:)":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/init(rawValue:)","url":"\/documentation\/ovkit\/cmaftrackreaderversion\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","role":"symbol","title":"CmafTrackReaderVersion","navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/cmaftrackreaderversion"}},"variantOverrides":[{"patch":[{"value":"OVCmafTrackReaderVersion","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title"},{"value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments"},{"value":[{"kind":"identifier","text":"OVCmafTrackReaderVersion"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}