{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/unknown"]}],"metadata":{"roleHeading":"Case","title":"CmafTrackReaderVersion.unknown","modules":[{"name":"OVKit"}],"symbolKind":"case","externalID":"c:@M@OVKit@E@OVCmafTrackReaderVersion@OVCmafTrackReaderVersionUnknown","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionUnknown"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"title":"CmafTrackReaderVersion","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion","navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/unknown":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionUnknown"}],"title":"CmafTrackReaderVersion.unknown","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/unknown","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion\/unknown"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVCmafTrackReaderVersionUnknown","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVCmafTrackReaderVersionUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVCmafTrackReaderVersionUnknown","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVCmafTrackReaderVersion","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title"},{"op":"replace","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments"},{"op":"replace","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle"},{"op":"replace","value":"OVCmafTrackReaderVersionUnknown","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1unknown\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersionUnknown"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}