{"variants":[{"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/v2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/v2"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v2","kind":"identifier"}]}]}],"metadata":{"roleHeading":"Case","title":"CmafTrackReaderVersion.v2","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV2"}],"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v2","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVCmafTrackReaderVersion@OVCmafTrackReaderVersionV2"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v2","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/v2":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/cmaftrackreaderversion\/v2","title":"CmafTrackReaderVersion.v2","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v2","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v2","navigatorTitle":[{"text":"OVCmafTrackReaderVersionV2","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"kind":"symbol","title":"CmafTrackReaderVersion","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"url":"\/documentation\/ovkit\/cmaftrackreaderversion","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVCmafTrackReaderVersionV2","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVCmafTrackReaderVersionV2","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV2"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v2\/title","value":"OVCmafTrackReaderVersionV2","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v2\/fragments","value":[{"text":"OVCmafTrackReaderVersionV2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title","value":"OVCmafTrackReaderVersion"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}]}]}]}