{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v3"}],"externalID":"c:@M@OVKit@E@OVCmafTrackReaderVersion@OVCmafTrackReaderVersionV3","roleHeading":"Case","title":"CmafTrackReaderVersion.v3","symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v3"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/v3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cmaftrackreaderversion\/v3"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v3","interfaceLanguage":"swift"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/v3":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v3"}],"title":"CmafTrackReaderVersion.v3","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion\/v3","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v3","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"title":"CmafTrackReaderVersion","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion","navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVCmafTrackReaderVersionV3","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVCmafTrackReaderVersionV3","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v3\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v3\/fragments"},{"op":"replace","value":"OVCmafTrackReaderVersion","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title"},{"op":"replace","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments"},{"op":"replace","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}