{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]]},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"actionButton","kind":"identifier"}],"title":"actionButton","externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction(py)actionButton","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/actionButton"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoRestrictionType.actionButton"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideorestriction\/actionbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideorestriction\/actionbutton"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"actionButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestrictionButtonType"}],"title":"VideoRestrictionButtonType","navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionButtonType"}],"abstract":[],"type":"topic","url":"\/documentation\/ovkit\/videorestrictionbuttontype","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestriction"}],"title":"VideoRestriction","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","role":"symbol","url":"\/documentation\/ovkit\/videorestriction","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestriction/actionButton":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/actionButton","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"actionButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"actionButton","navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"abstract":[],"type":"topic","url":"\/documentation\/ovkit\/ovkvideorestriction\/actionbutton","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"actionButton","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"actionButton"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"id<OVKVideoRestrictionButtonType>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButton"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title","value":"OVKVideoRestrictionButtonType","op":"replace"},{"value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title","value":"OVKVideoRestriction","op":"replace"},{"value":[{"text":"OVKVideoRestriction","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1actionButton\/title","value":"actionButton"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1actionButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"actionButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}