{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cardIcon","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/cardIcon"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoRestrictionType.cardIcon"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/ovkit\/ovkvideorestriction\/cardicon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideorestriction\/cardicon"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction(py)cardIcon","title":"cardIcon","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardIcon"},{"kind":"text","text":": ["},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"cardIcon"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"navigatorTitle":[{"text":"VideoRestriction","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","role":"symbol","title":"VideoRestriction","url":"\/documentation\/ovkit\/videorestriction","type":"topic","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestriction/cardIcon":{"navigatorTitle":[{"text":"cardIcon","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/cardIcon","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/ovkvideorestriction\/cardicon","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"title":"cardIcon"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","url":"\/documentation\/ovkit\/imageassettype","abstract":[],"kind":"symbol","title":"ImageAssetType","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"cardIcon"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cardIcon","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<OVKImageAssetType>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title","op":"replace","value":"OVKVideoRestriction"},{"value":[{"kind":"identifier","text":"OVKVideoRestriction"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1cardIcon\/title","value":"cardIcon","op":"replace"},{"value":[{"kind":"identifier","text":"cardIcon"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1cardIcon\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"text":"OVKImageAssetType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}