{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/listIcon"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideorestriction\/listicon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideorestriction\/listicon"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"listIcon","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"VideoRestrictionType.listIcon","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]]},"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction(py)listIcon","title":"listIcon","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listIcon"},{"kind":"text","text":": ["},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAssetType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"title":"ImageAssetType","url":"\/documentation\/ovkit\/imageassettype","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestriction/listIcon":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestriction\/listIcon","type":"topic","url":"\/documentation\/ovkit\/ovkvideorestriction\/listicon","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"role":"symbol","title":"listIcon","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"listIcon","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"text":"]","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestriction"}],"title":"VideoRestriction","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","role":"symbol","url":"\/documentation\/ovkit\/videorestriction","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"listIcon","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"listIcon"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKImageAssetType>>"},{"text":" * ","kind":"text"},{"text":"listIcon","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"OVKImageAssetType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"text":"OVKImageAssetType","kind":"identifier"}]},{"value":"listIcon","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1listIcon\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestriction~1listIcon\/fragments","value":[{"kind":"identifier","text":"listIcon"}]},{"value":"OVKVideoRestriction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments","value":[{"text":"OVKVideoRestriction","kind":"identifier"}]}]}]}