{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherdatasource\/itemsforprefetcher(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherdatasource\/itemsforprefetcher(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemsForPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","text":"ListPrefetcher"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":"]"}],"modules":[{"name":"OVKit"}],"title":"itemsForPrefetcher(_:)","required":true,"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource(im)itemsForPrefetcher:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"itemsForPrefetcher:"}]},"sections":[],"abstract":[{"type":"text","text":"Метод, возвращающий текущий список для префетчера."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource\/itemsForPrefetcher(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemsForPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","text":"ListPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource/itemsForPrefetcher(_:)":{"title":"itemsForPrefetcher(_:)","abstract":[{"text":"Метод, возвращающий текущий список для префетчера.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource\/itemsForPrefetcher(_:)","navigatorTitle":[{"text":"itemsForPrefetcher:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdatasource\/itemsforprefetcher(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemsForPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ListPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"type":"topic","title":"ListPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/listprefetcher","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource","abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDataSource"}],"title":"ListPrefetcherDataSource","type":"topic","url":"\/documentation\/ovkit\/listprefetcherdatasource","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherDataSource"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"itemsForPrefetcher:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemsForPrefetcher:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKPrefetchItem>>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"itemsForPrefetcher:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","text":"OVKListPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource~1itemsForPrefetcher(_:)\/title","op":"replace","value":"itemsForPrefetcher:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource~1itemsForPrefetcher(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemsForPrefetcher:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","op":"replace","value":"OVKListPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/title","op":"replace","value":"OVKListPrefetcherDataSource"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherDataSource"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherDataSource"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace","value":"OVKPrefetchItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}