{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelection\/activeAudioMediaOption","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","kind":"typeIdentifier","text":"MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Выбранная в данный момент опция аудио.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKMediaSelection(py)activeAudioMediaOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"activeAudioMediaOption"}],"role":"symbol","roleHeading":"Instance Property","title":"activeAudioMediaOption"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkmediaselection\/activeaudiomediaoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmediaselection\/activeaudiomediaoption"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"title":"MediaSelection","kind":"symbol","url":"\/documentation\/ovkit\/mediaselection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MediaSelection"}],"navigatorTitle":[{"text":"MediaSelection","kind":"identifier"}],"abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видеоресурсе."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"},"doc://onevideo.OVKit/documentation/OVKit/OVKMediaSelection/activeAudioMediaOption":{"title":"activeAudioMediaOption","kind":"symbol","url":"\/documentation\/ovkit\/ovkmediaselection\/activeaudiomediaoption","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"}],"navigatorTitle":[{"kind":"identifier","text":"activeAudioMediaOption"}],"abstract":[{"type":"text","text":"Выбранная в данный момент опция аудио."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelection\/activeAudioMediaOption"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"url":"\/documentation\/ovkit\/mediaselectionoption","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MediaSelectionOption"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","navigatorTitle":[{"kind":"identifier","text":"MediaSelectionOption"}],"abstract":[{"text":"Опция медиадорожки.","type":"text"}],"title":"MediaSelectionOption","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"activeAudioMediaOption","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"activeAudioMediaOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","kind":"typeIdentifier","text":"OVKMediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"kind":"text","text":" * "},{"text":"activeAudioMediaOption","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title","value":"OVKMediaSelection"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments","value":[{"kind":"identifier","text":"OVKMediaSelection"}]},{"value":"activeAudioMediaOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelection~1activeAudioMediaOption\/title"},{"value":[{"kind":"identifier","text":"activeAudioMediaOption"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelection~1activeAudioMediaOption\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title","op":"replace","value":"OVKMediaSelectionOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","op":"replace","value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}]}]}]}