{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"]]},"abstract":[{"text":"Все доступные опции аудио.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkmediaselection\/availableaudiomediaoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmediaselection\/availableaudiomediaoptions"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelection\/availableAudioMediaOptions"},"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"availableAudioMediaOptions","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKMediaSelection(py)availableAudioMediaOptions","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableAudioMediaOptions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"text":"availableAudioMediaOptions","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableAudioMediaOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","text":"MediaSelectionOption"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKMediaSelection/availableAudioMediaOptions":{"title":"availableAudioMediaOptions","abstract":[{"type":"text","text":"Все доступные опции аудио."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableAudioMediaOptions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"availableAudioMediaOptions"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelection\/availableAudioMediaOptions","url":"\/documentation\/ovkit\/ovkmediaselection\/availableaudiomediaoptions","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"url":"\/documentation\/ovkit\/mediaselectionoption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MediaSelectionOption","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MediaSelectionOption","kind":"identifier"}],"abstract":[{"type":"text","text":"Опция медиадорожки."}],"title":"MediaSelectionOption","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"url":"\/documentation\/ovkit\/mediaselection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MediaSelection"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaSelection"}],"abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видеоресурсе."}],"title":"MediaSelection","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"availableAudioMediaOptions","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"availableAudioMediaOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<OVKMediaSelectionOption *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"availableAudioMediaOptions","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelection~1availableAudioMediaOptions\/title","value":"availableAudioMediaOptions"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelection~1availableAudioMediaOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"availableAudioMediaOptions"}]},{"value":"OVKMediaSelectionOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","op":"replace","value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title","value":"OVKMediaSelection"},{"value":[{"text":"OVKMediaSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments"}]}]}