{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate","text":"InterstitialStatsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialcontrollerdelegate\/statsdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialControllerDelegate\/statsDelegate"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialControllerDelegate"]]},"metadata":{"required":true,"externalID":"s:5OVKit30InterstitialControllerDelegateP05statsD0AA0b5StatsD0_pSgvp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterstitialStatsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","title":"statsDelegate","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialControllerDelegate/statsDelegate":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate","text":"InterstitialStatsDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialControllerDelegate\/statsDelegate","abstract":[],"title":"statsDelegate","url":"\/documentation\/ovkit\/interstitialcontrollerdelegate\/statsdelegate","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Делегат для статистики прерываний."}],"navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","kind":"symbol","title":"InterstitialStatsDelegate"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialControllerDelegate":{"kind":"symbol","title":"InterstitialControllerDelegate","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialControllerDelegate","abstract":[],"url":"\/documentation\/ovkit\/interstitialcontrollerdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InterstitialControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialControllerDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title","value":"OVKInterstitialStatsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}]}]}]}