{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"s:5OVKit12DurationViewC12normalHeight14CoreFoundation7CGFloatVvp","symbolKind":"property","title":"normalHeight","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/normalHeight","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/durationview\/normalheight"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"abstract":[],"url":"\/documentation\/ovkit\/durationview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DurationView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","title":"DurationView","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/normalHeight":{"title":"normalHeight","url":"\/documentation\/ovkit\/durationview\/normalheight","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/normalHeight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalHeight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DurationView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title"},{"value":[{"text":"DurationView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments"},{"value":[{"kind":"identifier","text":"DurationView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle"}]}]}