{"metadata":{"externalID":"s:5OVKit12DurationViewC21selectedEpisodeHeight14CoreFoundation7CGFloatVvp","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedEpisodeHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"roleHeading":"Instance Property","role":"symbol","title":"selectedEpisodeHeight","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/durationview\/selectedepisodeheight"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/selectedEpisodeHeight","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedEpisodeHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DurationView/selectedEpisodeHeight":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedEpisodeHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","url":"\/documentation\/ovkit\/durationview\/selectedepisodeheight","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/selectedEpisodeHeight","kind":"symbol","title":"selectedEpisodeHeight","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"kind":"symbol","title":"DurationView","url":"\/documentation\/ovkit\/durationview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"}],"navigatorTitle":[{"text":"DurationView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DurationView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title"},{"op":"replace","value":[{"text":"DurationView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments"},{"op":"replace","value":[{"text":"DurationView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}