{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView"]]},"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"setContentCornerRadius(_:)","externalID":"s:5OVKit12DurationViewC22setContentCornerRadiusyy14CoreFoundation7CGFloatVF","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContentCornerRadius"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/setContentCornerRadius(_:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/durationview\/setcontentcornerradius(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContentCornerRadius"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/setContentCornerRadius(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentCornerRadius","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/setContentCornerRadius(_:)","type":"topic","url":"\/documentation\/ovkit\/durationview\/setcontentcornerradius(_:)","role":"symbol","title":"setContentCornerRadius(_:)"},"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","kind":"symbol","title":"DurationView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"}],"url":"\/documentation\/ovkit\/durationview","abstract":[],"role":"symbol","navigatorTitle":[{"text":"DurationView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title","value":"DurationView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments","value":[{"kind":"identifier","text":"DurationView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle","value":[{"kind":"identifier","text":"DurationView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}