{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeCodes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"] { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"text":"Нужно хранить тайм-коды как они пришли в маске","type":"text"}],"kind":"symbol","metadata":{"externalID":"s:5OVKit12DurationViewC9timeCodesSaySiGvp","symbolKind":"property","title":"timeCodes","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeCodes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/timeCodes","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/durationview\/timecodes"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"abstract":[],"url":"\/documentation\/ovkit\/durationview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DurationView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","title":"DurationView","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/timeCodes":{"title":"timeCodes","abstract":[{"type":"text","text":"Нужно хранить тайм-коды как они пришли в маске"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/timeCodes","url":"\/documentation\/ovkit\/durationview\/timecodes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeCodes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title","op":"replace","value":"DurationView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments","op":"replace","value":[{"kind":"identifier","text":"DurationView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle","op":"replace","value":[{"text":"DurationView","kind":"identifier"}]}]}]}