{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLoadableImageView\/initWithCoder:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkloadableimageview\/initwithcoder:"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aDecoder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKLoadableImageView(im)initWithCoder:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method","title":"initWithCoder:"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKLoadableImageView/initWithCoder:":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLoadableImageView\/initWithCoder:","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/ovkloadableimageview\/initwithcoder:","title":"initWithCoder:","kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"kind":"symbol","title":"LoadableImageView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","url":"\/documentation\/ovkit\/loadableimageview","navigatorTitle":[{"kind":"identifier","text":"LoadableImageView"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadableImageView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","value":"OVKLoadableImageView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"kind":"identifier","text":"OVKLoadableImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLoadableImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}