{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)allowsBackgroundPlayback","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"role":"symbol","roleHeading":"Instance Property","title":"allowsBackgroundPlayback"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Разрешить ли воспроизведение видео в фоне."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"],"kind":"mentions"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим игры в фоне также задается для каждого плеера по отдельности ("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","type":"reference","isActive":true},{"type":"text","text":"). Плеер может не играть в фоне, если видео не поддерживает такую возможность."}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Необходимо установить сразу после запуска приложения. По умолчанию "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/environment\/allowsbackgroundplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/allowsbackgroundplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"url":"\/documentation\/ovkit\/backgroundplayback","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","role":"article","abstract":[{"text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"title":"Воспроизведение в фоне","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/Environment/allowsBackgroundPlayback":{"navigatorTitle":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"url":"\/documentation\/ovkit\/environment\/allowsbackgroundplayback","abstract":[{"type":"text","text":"Разрешить ли воспроизведение видео в фоне."}],"title":"allowsBackgroundPlayback","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsBackgroundPlayback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"url":"\/documentation\/ovkit\/environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"type":"topic","title":"Environment","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/backgroundPlaybackPolicy":{"navigatorTitle":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"url":"\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy","abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"title":"backgroundPlaybackPolicy","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","text":"BackgroundPlaybackPolicy"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"allowsBackgroundPlayback","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsBackgroundPlayback"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"allowsBackgroundPlayback","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/fragments"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"op":"replace","value":"backgroundPlaybackPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}