{"kind":"symbol","metadata":{"title":"autoShowDiagnosticsView","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"autoShowDiagnosticsView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)autoShowDiagnosticsView","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoShowDiagnosticsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/autoShowDiagnosticsView"},"abstract":[{"type":"text","text":"Автоматический показ DiagnosticsView на всех плеерах после их создания."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Работает только при включенном ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDiagnosticsView","type":"reference"},{"type":"text","text":". По умолчанию выключено."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/ovkit\/environment\/autoshowdiagnosticsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/autoshowdiagnosticsview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"url":"\/documentation\/ovkit\/environment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"role":"symbol","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableDiagnosticsView":{"abstract":[{"text":"Активирует возможность наблюдать за отладочными данными плеера.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/environment\/enablediagnosticsview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableDiagnosticsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"enableDiagnosticsView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDiagnosticsView","title":"enableDiagnosticsView"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/autoShowDiagnosticsView":{"kind":"symbol","abstract":[{"text":"Автоматический показ DiagnosticsView на всех плеерах после их создания.","type":"text"}],"url":"\/documentation\/ovkit\/environment\/autoshowdiagnosticsview","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"autoShowDiagnosticsView","kind":"identifier"}],"type":"topic","title":"autoShowDiagnosticsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/autoShowDiagnosticsView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"autoShowDiagnosticsView"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"autoShowDiagnosticsView","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"op":"replace","value":"enableDiagnosticsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDiagnosticsView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"enableDiagnosticsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDiagnosticsView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1autoShowDiagnosticsView\/title","value":"autoShowDiagnosticsView"},{"value":[{"text":"autoShowDiagnosticsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1autoShowDiagnosticsView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}