{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"biPlanarPixelFormatNeon","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/biPlanarPixelFormatNeon"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/biplanarpixelformatneon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/biplanarpixelformatneon"]}],"sections":[],"metadata":{"roleHeading":"Type Property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)biPlanarPixelFormatNeon","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"biPlanarPixelFormatNeon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"biPlanarPixelFormatNeon","kind":"identifier"}],"title":"biPlanarPixelFormatNeon","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/Environment/biPlanarPixelFormatNeon":{"abstract":[],"type":"topic","title":"biPlanarPixelFormatNeon","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/biPlanarPixelFormatNeon","url":"\/documentation\/ovkit\/environment\/biplanarpixelformatneon","role":"symbol","navigatorTitle":[{"text":"biPlanarPixelFormatNeon","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biPlanarPixelFormatNeon","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"title":"Environment","url":"\/documentation\/ovkit\/environment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"biPlanarPixelFormatNeon"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"biPlanarPixelFormatNeon","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"biPlanarPixelFormatNeon"},{"kind":"text","text":";"}]}]}},{"value":"biPlanarPixelFormatNeon","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1biPlanarPixelFormatNeon\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1biPlanarPixelFormatNeon\/fragments","value":[{"text":"biPlanarPixelFormatNeon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]}]}]}