{"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"cacheCostLimit"}],"role":"symbol","title":"cacheCostLimit","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)cacheCostLimit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheCostLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/environment\/cachecostlimit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/cachecostlimit"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheCostLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cacheCostLimit","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Environment/cacheCostLimit":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cacheCostLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheCostLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"cacheCostLimit"}],"title":"cacheCostLimit","type":"topic","url":"\/documentation\/ovkit\/environment\/cachecostlimit","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","kind":"symbol","type":"topic","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"role":"symbol","title":"Environment"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cacheCostLimit"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cacheCostLimit","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cacheCostLimit"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cacheCostLimit\/title","op":"replace","value":"cacheCostLimit"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cacheCostLimit\/fragments","op":"replace","value":[{"text":"cacheCostLimit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}