{"kind":"symbol","abstract":[{"text":"Подключение плагина ","type":"text"},{"type":"codeVoice","code":"ChromecastPlugin"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/chromecastplugin"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chromecastPlugin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChromecastPlugin","preciseIdentifier":"s:5OVKit16ChromecastPluginP","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChromecastPlugin"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Необходим для стриминга на chromecast устройства."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/chromecastPlugin"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"chromecastPlugin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChromecastPlugin","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit16ChromecastPluginP"},{"text":"?","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"chromecastPlugin","externalID":"s:5OVKit11EnvironmentC16chromecastPluginAA010ChromecastD0_pSgvpZ"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ChromecastPlugin":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChromecastPlugin"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChromecastPlugin","url":"\/documentation\/ovkit\/chromecastplugin","title":"ChromecastPlugin","role":"symbol","navigatorTitle":[{"text":"ChromecastPlugin","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/chromecastPlugin":{"abstract":[{"text":"Подключение плагина ","type":"text"},{"code":"ChromecastPlugin","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/environment\/chromecastplugin","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chromecastPlugin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit16ChromecastPluginP","text":"ChromecastPlugin","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/chromecastPlugin","title":"chromecastPlugin"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"url":"\/documentation\/ovkit\/environment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"role":"symbol","title":"Environment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"}]}]}