{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafLowLatencyMode"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cmafLowLatencyMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/cmaflowlatencymode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/cmaflowlatencymode"]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)cmafLowLatencyMode","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cmafLowLatencyMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"title":"cmafLowLatencyMode","navigatorTitle":[{"text":"cmafLowLatencyMode","kind":"identifier"}],"roleHeading":"Type Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/cmafLowLatencyMode":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cmafLowLatencyMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafLowLatencyMode","url":"\/documentation\/ovkit\/environment\/cmaflowlatencymode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"cmafLowLatencyMode","kind":"identifier"}],"title":"cmafLowLatencyMode"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"title":"Environment","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"url":"\/documentation\/ovkit\/environment","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"cmafLowLatencyMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cmafLowLatencyMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"cmafLowLatencyMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafLowLatencyMode\/title","value":"cmafLowLatencyMode"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafLowLatencyMode\/fragments","op":"replace","value":[{"text":"cmafLowLatencyMode","kind":"identifier"}]},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}