{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultAdsProviderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OVKitAdsProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKitAdsProvider","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit0A11AdsProviderP"},{"text":".Type?","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Временное свойство на период миграции на API для Interstitials.","type":"text"}]}],"style":"note"}],"kind":"content"}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultAdsProviderType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"OVKitAdsProvider","preciseIdentifier":"s:5OVKit0A11AdsProviderP"},{"text":".Type?","kind":"text"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit11EnvironmentC22defaultAdsProviderTypeAA0adE0_pXpSgvp","title":"defaultAdsProviderType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/defaultadsprovidertype"]}],"abstract":[{"text":"Тип поставщика рекламных контролов по умолчанию.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/defaultAdsProviderType","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"type":"topic","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKitAdsProvider":{"url":"\/documentation\/ovkit\/ovkitadsprovider","navigatorTitle":[{"kind":"identifier","text":"OVKitAdsProvider"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKitAdsProvider","kind":"identifier"}],"abstract":[{"text":"Временный протокол для поставщика рекламных контролов по умолчанию.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKitAdsProvider","kind":"symbol","title":"OVKitAdsProvider","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Environment/defaultAdsProviderType":{"url":"\/documentation\/ovkit\/environment\/defaultadsprovidertype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/defaultAdsProviderType","title":"defaultAdsProviderType","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Тип поставщика рекламных контролов по умолчанию."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultAdsProviderType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit0A11AdsProviderP","text":"OVKitAdsProvider"},{"kind":"text","text":".Type?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","op":"replace"}]}]}