{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRuntimeDebugDiagnostics"},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)enableRuntimeDebugDiagnostics","navigatorTitle":[{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"}],"role":"symbol","roleHeading":"Instance Property","title":"enableRuntimeDebugDiagnostics","symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/enableruntimedebugdiagnostics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/enableruntimedebugdiagnostics"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Включает сбор дополнительных параметров для отладки в реальном времени. По умолчанию включено только для DEBUG."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/enableRuntimeDebugDiagnostics":{"abstract":[{"text":"Включает сбор дополнительных параметров для отладки в реальном времени. По умолчанию включено только для DEBUG.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"enableRuntimeDebugDiagnostics","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRuntimeDebugDiagnostics","url":"\/documentation\/ovkit\/environment\/enableruntimedebugdiagnostics","title":"enableRuntimeDebugDiagnostics","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableRuntimeDebugDiagnostics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"role":"symbol","abstract":[],"title":"Environment","url":"\/documentation\/ovkit\/environment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","type":"topic","navigatorTitle":[{"text":"Environment","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"enableRuntimeDebugDiagnostics"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"enableRuntimeDebugDiagnostics","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRuntimeDebugDiagnostics\/title","op":"replace","value":"enableRuntimeDebugDiagnostics"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRuntimeDebugDiagnostics\/fragments","op":"replace","value":[{"text":"enableRuntimeDebugDiagnostics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}