{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable60fps","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Стоит включать для A11 Bionic чипа и выше. По умолчанию выключено","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"property","title":"enable60fps","modules":[{"name":"OVKit"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable60fps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"enable60fps"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)enable60fps"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Включает возможность играть (если доступно) видео в 60 fps."}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enable60fps","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/enable60fps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/enable60fps"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"role":"symbol","url":"\/documentation\/ovkit\/environment","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","title":"Environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enable60fps":{"role":"symbol","title":"enable60fps","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable60fps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enable60fps","kind":"symbol","abstract":[{"type":"text","text":"Включает возможность играть (если доступно) видео в 60 fps."}],"url":"\/documentation\/ovkit\/environment\/enable60fps","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enable60fps"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"enable60fps","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"enable60fps","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"enable60fps","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"value":"enable60fps","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enable60fps\/title"},{"value":[{"text":"enable60fps","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enable60fps\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}