{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logZeroWatchCoverage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"logZeroWatchCoverage"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"logZeroWatchCoverage","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)logZeroWatchCoverage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logZeroWatchCoverage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/logZeroWatchCoverage"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"abstract":[{"type":"text","text":"Логирование пустых отрезков просмотра, например  "},{"code":"[7 - 7]","type":"codeVoice"},{"type":"text","text":". По умолчанию выключено."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/logzerowatchcoverage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/logzerowatchcoverage"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/logZeroWatchCoverage":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logZeroWatchCoverage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/environment\/logzerowatchcoverage","title":"logZeroWatchCoverage","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/logZeroWatchCoverage","type":"topic","role":"symbol","navigatorTitle":[{"text":"logZeroWatchCoverage","kind":"identifier"}],"abstract":[{"type":"text","text":"Логирование пустых отрезков просмотра, например  "},{"code":"[7 - 7]","type":"codeVoice"},{"type":"text","text":". По умолчанию выключено."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"role":"symbol","abstract":[],"title":"Environment","url":"\/documentation\/ovkit\/environment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","type":"topic","navigatorTitle":[{"text":"Environment","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"logZeroWatchCoverage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"logZeroWatchCoverage","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"logZeroWatchCoverage","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1logZeroWatchCoverage\/title","value":"logZeroWatchCoverage","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1logZeroWatchCoverage\/fragments","value":[{"text":"logZeroWatchCoverage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace"}]}]}