{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"objc_disabledFormats","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/objc_disabledformats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/objc_disabledformats"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)objc_disabledFormats","navigatorTitle":[{"text":"objc_disabledFormats","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objc_disabledFormats"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"objc_disabledFormats","role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/objc_disabledFormats","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Аналог свойства "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disabledFormats","isActive":true},{"text":" для совместимости с Objective-C.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"type":"topic","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/Environment/disabledFormats":{"url":"\/documentation\/ovkit\/environment\/disabledformats","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"disabledFormats","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Набор форматов, которые основной плеер должен игнорировать при выборе формата для воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disabledFormats","title":"disabledFormats","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Environment/objc_disabledFormats":{"url":"\/documentation\/ovkit\/environment\/objc_disabledformats","navigatorTitle":[{"text":"objc_disabledFormats","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"objc_disabledFormats"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Аналог свойства "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disabledFormats","type":"reference","isActive":true},{"text":" для совместимости с Objective-C.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/objc_disabledFormats","title":"objc_disabledFormats","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"objc_disabledFormats","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"objc_disabledFormats","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"objc_disabledFormats"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"objc_disabledFormats","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1objc_disabledFormats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"objc_disabledFormats"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1objc_disabledFormats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}