{"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"}],"role":"symbol","title":"qualityAdaptationPolicyChangedNotification","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)qualityAdaptationPolicyChangedNotification","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier","text":"Notification"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","kind":"typeIdentifier","text":"Name"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/environment\/qualityadaptationpolicychangednotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/qualityadaptationpolicychangednotification"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier","text":"Notification"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Foundation12NotificationV4Namea","kind":"typeIdentifier","text":"Name"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/qualityAdaptationPolicyChangedNotification","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Уведомление отправляется при изменении настроек экономии трафика."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/qualityAdaptationPolicyChangedNotification":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"}],"url":"\/documentation\/ovkit\/environment\/qualityadaptationpolicychangednotification","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/qualityAdaptationPolicyChangedNotification","abstract":[{"type":"text","text":"Уведомление отправляется при изменении настроек экономии трафика."}],"title":"qualityAdaptationPolicyChangedNotification","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","kind":"symbol","type":"topic","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"role":"symbol","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"qualityAdaptationPolicyChangedNotification"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"qualityAdaptationPolicyChangedNotification","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1qualityAdaptationPolicyChangedNotification\/title","op":"replace","value":"qualityAdaptationPolicyChangedNotification"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1qualityAdaptationPolicyChangedNotification\/fragments","op":"replace","value":[{"kind":"identifier","text":"qualityAdaptationPolicyChangedNotification"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}]}]}]}