{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultAdsProviderType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setDefaultAdsProviderType(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/setdefaultadsprovidertype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/setdefaultadsprovidertype(_:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"setDefaultAdsProviderType:"}],"role":"symbol","title":"setDefaultAdsProviderType(_:)","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(im)setDefaultAdsProviderType:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultAdsProviderType"},{"text":"(","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","kind":"symbol","type":"topic","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"role":"symbol","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/Environment/setDefaultAdsProviderType(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultAdsProviderType"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setDefaultAdsProviderType(_:)","url":"\/documentation\/ovkit\/environment\/setdefaultadsprovidertype(_:)","title":"setDefaultAdsProviderType(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDefaultAdsProviderType:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setDefaultAdsProviderType:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setDefaultAdsProviderType:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDefaultAdsProviderType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aClass"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment","op":"replace"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"value":"setDefaultAdsProviderType:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setDefaultAdsProviderType(_:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setDefaultAdsProviderType(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDefaultAdsProviderType:"}]}]}]}