{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showPlayerDebugMenu"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/showplayerdebugmenu"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/showplayerdebugmenu"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/showPlayerDebugMenu","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"title":"showPlayerDebugMenu","roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showPlayerDebugMenu","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"showPlayerDebugMenu"}],"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)showPlayerDebugMenu"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Добавление новых пунктов в меню настроек. По умолчанию выключено.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/showPlayerDebugMenu":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/showPlayerDebugMenu","title":"showPlayerDebugMenu","url":"\/documentation\/ovkit\/environment\/showplayerdebugmenu","kind":"symbol","abstract":[{"text":"Добавление новых пунктов в меню настроек. По умолчанию выключено.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showPlayerDebugMenu","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"showPlayerDebugMenu","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"title":"Environment","url":"\/documentation\/ovkit\/environment","role":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"showPlayerDebugMenu","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"showPlayerDebugMenu","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"showPlayerDebugMenu","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1showPlayerDebugMenu\/title","value":"showPlayerDebugMenu","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1showPlayerDebugMenu\/fragments","value":[{"kind":"identifier","text":"showPlayerDebugMenu"}],"op":"replace"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"kind":"identifier","text":"OVKEnvironment"}]}]}]}