{"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)unlockPictureInPictureAspectRatio","title":"unlockPictureInPictureAspectRatio","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"unlockPictureInPictureAspectRatio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","role":"symbol"},"abstract":[{"text":"Включает произвольное соотношение сторон для внутреннего окна Picture in Picture, отключая","type":"text"},{"text":" ","type":"text"},{"text":"привязку к стандартным размерам (9\/16, 16\/9, 1\/1).","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/environment\/unlockpictureinpictureaspectratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/unlockpictureinpictureaspectratio"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/unlockPictureInPictureAspectRatio"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/unlockPictureInPictureAspectRatio":{"title":"unlockPictureInPictureAspectRatio","navigatorTitle":[{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment\/unlockpictureinpictureaspectratio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/unlockPictureInPictureAspectRatio","abstract":[{"text":"Включает произвольное соотношение сторон для внутреннего окна Picture in Picture, отключая","type":"text"},{"text":" ","type":"text"},{"text":"привязку к стандартным размерам (9\/16, 16\/9, 1\/1).","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"url":"\/documentation\/ovkit\/environment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"role":"symbol","title":"Environment"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"unlockPictureInPictureAspectRatio","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"unlockPictureInPictureAspectRatio"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"unlockPictureInPictureAspectRatio","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1unlockPictureInPictureAspectRatio\/title"},{"value":[{"text":"unlockPictureInPictureAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1unlockPictureInPictureAspectRatio\/fragments"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}