{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/environment\/usequalitypresets"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/usequalitypresets"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useQualityPresets"},"metadata":{"title":"useQualityPresets","navigatorTitle":[{"text":"useQualityPresets","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Type Property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)useQualityPresets","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useQualityPresets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Включает возможность выбирать пресеты качества видео."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useQualityPresets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/useQualityPresets":{"title":"useQualityPresets","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useQualityPresets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Включает возможность выбирать пресеты качества видео."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useQualityPresets","navigatorTitle":[{"text":"useQualityPresets","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/usequalitypresets","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"url":"\/documentation\/ovkit\/environment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"role":"symbol","title":"Environment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"useQualityPresets"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useQualityPresets"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"useQualityPresets"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useQualityPresets\/title","value":"useQualityPresets"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useQualityPresets\/fragments","value":[{"kind":"identifier","text":"useQualityPresets"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"kind":"identifier","text":"OVKEnvironment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}