{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","platforms":[{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}],"navigatorTitle":[{"text":"useSystemPictureInPicture","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)useSystemPictureInPicture","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useSystemPictureInPicture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"useSystemPictureInPicture"},"variants":[{"paths":["\/documentation\/ovkit\/environment\/usesystempictureinpicture"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/environment\/usesystempictureinpicture"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useSystemPictureInPicture","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Включает использование системного окна Picture in Picture везде."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useSystemPictureInPicture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"При включении все методы работы с Picture in Picture будут использовать только системную реализацию, даже внутри приложения. При этом к окну можно по-прежнему обращаться через ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","isActive":true,"type":"reference"},{"text":". По умолчанию значение ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" – в приложении используется Picture in Picture из SDK.”","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"type":"topic","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/pipWindow":{"navigatorTitle":[{"kind":"identifier","text":"pipWindow"}],"url":"\/documentation\/ovkit\/playermanager\/pipwindow","title":"pipWindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","type":"topic","role":"symbol","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipWindow"},{"text":": ","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/useSystemPictureInPicture":{"abstract":[{"type":"text","text":"Включает использование системного окна Picture in Picture везде."}],"navigatorTitle":[{"text":"useSystemPictureInPicture","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useSystemPictureInPicture","type":"topic","kind":"symbol","title":"useSystemPictureInPicture","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useSystemPictureInPicture"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/usesystempictureinpicture"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"15.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"useSystemPictureInPicture","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"useSystemPictureInPicture","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"useSystemPictureInPicture","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"value":"pipWindow","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/title"},{"value":[{"text":"pipWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/fragments"},{"value":"useSystemPictureInPicture","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useSystemPictureInPicture\/title"},{"value":[{"text":"useSystemPictureInPicture","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useSystemPictureInPicture\/fragments"}]}]}