{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"videoProxy"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoProxyProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"videoProxy","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)videoProxy","symbolKind":"property","roleHeading":"Type Property","role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/videoProxy","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment\/videoproxy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/environment\/videoproxy"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoProxy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","text":"VideoProxyProtocol","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/videoProxy":{"navigatorTitle":[{"text":"videoProxy","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/environment\/videoproxy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/videoProxy","title":"videoProxy","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoProxy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoProxyProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoProxyProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/videoproxyprotocol","title":"VideoProxyProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoProxyProtocol"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"title":"Environment","url":"\/documentation\/ovkit\/environment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"videoProxy"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"videoProxy","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)VideoProxyProtocol","text":"id<VideoProxyProtocol>"},{"kind":"text","text":" "},{"text":"videoProxy","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1videoProxy\/title","value":"videoProxy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1videoProxy\/fragments","value":[{"kind":"identifier","text":"videoProxy"}],"op":"replace"},{"op":"replace","value":"VideoProxyProtocol","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"VideoProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/fragments"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}