{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovklistprefetcher\/datasource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovklistprefetcher\/datasource"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcher\/dataSource","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"title":"dataSource","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(py)dataSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSource"},{"text":": ","kind":"text"},{"text":"ListPrefetcherDataSource","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dataSource","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dataSource","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource","text":"ListPrefetcherDataSource","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Источник данных, из которого префетчер получает список ресурсов.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource":{"navigatorTitle":[{"text":"ListPrefetcherDataSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdatasource","kind":"symbol","abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране.","type":"text"}],"type":"topic","title":"ListPrefetcherDataSource","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ListPrefetcherDataSource","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcher/dataSource":{"abstract":[{"type":"text","text":"Источник данных, из которого префетчер получает список ресурсов."}],"type":"topic","navigatorTitle":[{"text":"dataSource","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcher\/dataSource","title":"dataSource","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/ovklistprefetcher\/datasource","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"text":": ","kind":"text"},{"text":"ListPrefetcherDataSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"url":"\/documentation\/ovkit\/listprefetcher","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","title":"ListPrefetcher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"dataSource","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"dataSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKListPrefetcherDataSource>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKListPrefetcherDataSource"},{"kind":"text","text":" "},{"text":"dataSource","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKListPrefetcherDataSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKListPrefetcherDataSource"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/fragments"},{"op":"replace","value":"dataSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcher~1dataSource\/title"},{"value":[{"kind":"identifier","text":"dataSource"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcher~1dataSource\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher","op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"}]}]}