{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer"]]},"variants":[{"paths":["\/documentation\/ovkit\/thumbnailcontainer\/init(frame:thumbnailprovider:chapterprovider:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/init(frame:thumbnailProvider:chapterProvider:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"thumbnailProvider"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":", "},{"text":"chapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider"},{"text":"?)","kind":"text"}],"title":"init(frame:thumbnailProvider:chapterProvider:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit18ThumbnailContainerC5frame17thumbnailProvider07chapterF0ACSo6CGRectV_AA0bF0CAA07ChapterF0CSgtcfc","symbolKind":"init"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"chapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChapterProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer":{"url":"\/documentation\/ovkit\/thumbnailcontainer","navigatorTitle":[{"kind":"identifier","text":"ThumbnailContainer"}],"title":"ThumbnailContainer","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailContainer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer","abstract":[{"text":"Контейнер, который является границами показа ","type":"text"},{"code":"ThumbnailView","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","type":"topic","url":"\/documentation\/ovkit\/thumbnailprovider","title":"ThumbnailProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/init(frame:thumbnailProvider:chapterProvider:)":{"title":"init(frame:thumbnailProvider:chapterProvider:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/init(frame:thumbnailProvider:chapterProvider:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chapterProvider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/ovkit\/thumbnailcontainer\/init(frame:thumbnailprovider:chapterprovider:)","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"url":"\/documentation\/ovkit\/chapterprovider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"title":"ChapterProvider","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/title","value":"ThumbnailContainer","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/fragments","op":"replace","value":[{"text":"ThumbnailContainer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ThumbnailContainer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace","value":"OVKThumbnailProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","op":"replace","value":[{"text":"OVKChapterProvider","kind":"identifier"}]}]}]}