{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailcontainer\/updatecurrenttime(_:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateCurrentTime(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCurrentTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"s:5OVKit18ThumbnailContainerC17updateCurrentTimeyySdF","symbolKind":"method","title":"updateCurrentTime(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/updateCurrentTime(_:)":{"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailcontainer\/updatecurrenttime(_:)","title":"updateCurrentTime(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateCurrentTime(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer":{"navigatorTitle":[{"text":"ThumbnailContainer","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/thumbnailcontainer","title":"ThumbnailContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer","abstract":[{"text":"Контейнер, который является границами показа ","type":"text"},{"code":"ThumbnailView","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailContainer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/title","value":"ThumbnailContainer","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/fragments","value":[{"text":"ThumbnailContainer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailContainer"}],"op":"replace"}]}]}