{"abstract":[{"text":"Обновление горизонтального положения ","type":"text"},{"type":"codeVoice","code":"ThumbnailView"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateRelativeXPosition(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRelativeXPosition"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"x","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Горизонтальная координата "},{"type":"emphasis","inlineContent":[{"type":"text","text":"ручки"}]},{"type":"text","text":", за которой тянется "},{"code":"ThumbnailView","type":"codeVoice"},{"type":"text","text":". Должна находиться в координатах данного "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"name":"x"}]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRelativeXPosition"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"updateRelativeXPosition(_:)","modules":[{"name":"OVKit"}],"symbolKind":"method","externalID":"s:5OVKit18ThumbnailContainerC23updateRelativeXPositionyy14CoreFoundation7CGFloatVF","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailcontainer\/updaterelativexposition(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer":{"navigatorTitle":[{"text":"ThumbnailContainer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer","abstract":[{"type":"text","text":"Контейнер, который является границами показа "},{"type":"codeVoice","code":"ThumbnailView"},{"text":".","type":"text"}],"type":"topic","title":"ThumbnailContainer","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/thumbnailcontainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailContainer"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/updateRelativeXPosition(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateRelativeXPosition(_:)","abstract":[{"text":"Обновление горизонтального положения ","type":"text"},{"type":"codeVoice","code":"ThumbnailView"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailcontainer\/updaterelativexposition(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateRelativeXPosition"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"role":"symbol","title":"updateRelativeXPosition(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"ThumbnailContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/fragments","value":[{"text":"ThumbnailContainer","kind":"identifier"}]},{"value":[{"text":"ThumbnailContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}