{"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction(py)actionButton","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier","text":"VideoRestrictionButtonType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"actionButton","kind":"identifier"}],"title":"actionButton"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"VideoRestrictionType.actionButton","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/actionButton","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestriction\/actionbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestriction\/actionbutton"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier","text":"VideoRestrictionButtonType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestriction","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestriction","kind":"symbol","title":"VideoRestriction","role":"symbol","navigatorTitle":[{"text":"VideoRestriction","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/actionButton":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/actionButton","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier","text":"VideoRestrictionButtonType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"type":"topic","title":"actionButton","kind":"symbol","url":"\/documentation\/ovkit\/videorestriction\/actionbutton"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"title":"VideoRestrictionButtonType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionButtonType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","abstract":[],"url":"\/documentation\/ovkit\/videorestrictionbuttontype","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionButtonType"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"actionButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"actionButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier","text":"id<OVKVideoRestrictionButtonType>"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title","value":"OVKVideoRestriction"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestriction"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/navigatorTitle","value":[{"text":"OVKVideoRestriction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1actionButton\/title","value":"actionButton"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1actionButton\/fragments","value":[{"text":"actionButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title","value":"OVKVideoRestrictionButtonType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments","value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}]}]}]}