{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]]},"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"blur","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"canPlay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"canPreview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"muteInfoLink","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"disclaimerType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"actionButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoRestrictionButton","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"cardIcon"},{"kind":"text","text":": ["},{"text":"ImageAsset","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"listIcon"},{"text":": [","kind":"text"},{"text":"ImageAsset","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset"},{"text":"])","kind":"text"}],"symbolKind":"init","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction(im)initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","title":"init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestriction\/init(title:text:blur:canplay:canpreview:muteinfolink:disclaimertype:actionbutton:cardicon:listicon:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestriction\/init(title:text:blur:canplay:canpreview:muteinfolink:disclaimertype:actionbutton:cardicon:listicon:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"blur","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"canPlay"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"canPreview","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"muteInfoLink","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"disclaimerType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"actionButton","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","kind":"typeIdentifier","text":"VideoRestrictionButton","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"cardIcon"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset","kind":"typeIdentifier","text":"ImageAsset"},{"kind":"text","text":"], "},{"text":"listIcon","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset","text":"ImageAsset","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"blur"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"canPlay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"canPreview","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"muteInfoLink"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disclaimerType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"actionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton","text":"VideoRestrictionButton"},{"text":"?, ","kind":"text"},{"text":"cardIcon","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset","text":"ImageAsset","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"listIcon","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ImageAsset","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset"},{"kind":"text","text":"])"}],"url":"\/documentation\/ovkit\/videorestriction\/init(title:text:blur:canplay:canpreview:muteinfolink:disclaimertype:actionbutton:cardicon:listicon:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","kind":"identifier"}],"type":"topic","title":"init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageAsset"}],"title":"ImageAsset","url":"\/documentation\/ovkit\/imageasset","navigatorTitle":[{"kind":"identifier","text":"ImageAsset"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButton":{"url":"\/documentation\/ovkit\/videorestrictionbutton","type":"topic","navigatorTitle":[{"text":"VideoRestrictionButton","kind":"identifier"}],"title":"VideoRestrictionButton","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestrictionButton"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"navigatorTitle":[{"text":"VideoRestriction","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","role":"symbol","title":"VideoRestriction","url":"\/documentation\/ovkit\/videorestriction","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"text":"blur:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"blur","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlay:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"canPlay"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPreview:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"canPreview"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muteInfoLink:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"muteInfoLink"},{"kind":"text","text":" "},{"text":"disclaimerType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"disclaimerType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"actionButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton","text":"OVKVideoRestrictionButton"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"actionButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIcon:"},{"kind":"text","text":"("},{"text":"NSArray<OVKImageAsset *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardIcon"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listIcon:"},{"kind":"text","text":"("},{"text":"NSArray<OVKImageAsset *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"listIcon"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)\/title","value":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title","value":"OVKImageAsset"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/title","value":"OVKVideoRestrictionButton"},{"op":"replace","value":[{"text":"OVKVideoRestrictionButton","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title","op":"replace","value":"OVKVideoRestriction"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments","value":[{"text":"OVKVideoRestriction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}