{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"metadata":{"symbolKind":"method","title":"didEnterFullscreen()","navigatorTitle":[{"text":"didEnterFullscreen","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)didEnterFullscreen","roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"kind":"text","text":"()"}],"modules":[{"name":"OVKit"}]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didEnterFullscreen()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Произошел переход в полноэкранный режим."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/videostatshandler\/didenterfullscreen()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videostatshandler\/didenterfullscreen()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol","title":"VideoStatsHandler","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler","abstract":[],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/didEnterFullscreen()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/didenterfullscreen()","required":true,"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didEnterFullscreen()","role":"symbol","navigatorTitle":[{"text":"didEnterFullscreen","kind":"identifier"}],"abstract":[{"text":"Произошел переход в полноэкранный режим.","type":"text"}],"title":"didEnterFullscreen()"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"didEnterFullscreen","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","value":"didEnterFullscreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didEnterFullscreen()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didEnterFullscreen"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didEnterFullscreen()\/fragments"}]}]}