{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/failover(backupHost:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)failoverWithBackupHost:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupHost","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"failover(backupHost:)","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"failover"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backupHost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"backupHost","content":[{"inlineContent":[{"text":"Хост, на который произошло переключение.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/failover(backuphost:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/failover(backuphost:)"]}],"abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"url":"\/documentation\/ovkit\/videostatshandler","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/failover(backupHost:)":{"type":"topic","abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/failover(backupHost:)","url":"\/documentation\/ovkit\/videostatshandler\/failover(backuphost:)","title":"failover(backupHost:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"failover"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backupHost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"failoverWithBackupHost:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"failoverWithBackupHost:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"failoverWithBackupHost:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backupHost"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"backupHost","content":[{"type":"paragraph","inlineContent":[{"text":"Хост, на который произошло переключение.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace","value":"OVKVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1failover(backupHost:)\/title","op":"replace","value":"failoverWithBackupHost:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1failover(backupHost:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}