{"metadata":{"navigatorTitle":[{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstBytes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"firstBytes(time:connectionType:connectionReused:)","externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)firstBytesWithTime:connectionType:connectionReused:","roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/firstbytes(time:connectiontype:connectionreused:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/firstbytes(time:connectiontype:connectionreused:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstBytes(time:connectionType:connectionReused:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Событие получения первых данных из плеера."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstBytes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время в миллисекундах. Если значение равно нулю — данные из кэша."}]}],"name":"time"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3)."}]}],"name":"connectionType"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Было ли переиспользовано соединение при запросах."}]}],"name":"connectionReused"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Потраченное время от старта до получения первых данных для проигрывания (за манифестом, либо за сегментом).","type":"text"},{"text":" ","type":"text"},{"text":"Данные из кэша не учитываются.","type":"text"}]}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","title":"VideoStatsHandler","type":"topic","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/firstBytes(time:connectionType:connectionReused:)":{"kind":"symbol","navigatorTitle":[{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstBytes(time:connectionType:connectionReused:)","abstract":[{"type":"text","text":"Событие получения первых данных из плеера."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstBytes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/firstbytes(time:connectiontype:connectionreused:)","type":"topic","title":"firstBytes(time:connectionType:connectionReused:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"firstBytesWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"firstBytesWithTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"connectionType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionReused:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"connectionReused"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Время в миллисекундах. Если значение равно нулю — данные из кэша."}],"type":"paragraph"}],"name":"time"},{"content":[{"inlineContent":[{"text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3).","type":"text"}],"type":"paragraph"}],"name":"connectionType"},{"content":[{"inlineContent":[{"type":"text","text":"Было ли переиспользовано соединение при запросах."}],"type":"paragraph"}],"name":"connectionReused"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstBytes(time:connectionType:connectionReused:)\/title","value":"firstBytesWithTime:connectionType:connectionReused:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstBytes(time:connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"op":"replace"}]}]}