{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Событие получения первого кадра."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstFrame(time:connectionType:connectionReused:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)firstFrameWithTime:connectionType:connectionReused:","modules":[{"name":"OVKit"}],"title":"firstFrame(time:connectionType:connectionReused:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"firstFrameWithTime:connectionType:connectionReused:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"time","content":[{"inlineContent":[{"text":"Время в миллисекундах.","type":"text"}],"type":"paragraph"}]},{"name":"connectionType","content":[{"type":"paragraph","inlineContent":[{"text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3).","type":"text"}]}]},{"name":"connectionReused","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Было ли переиспользовано соединение при запросах."}]}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Потраченное время от старта до отрисовки первого кадра.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/firstframe(time:connectiontype:connectionreused:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/firstframe(time:connectiontype:connectionreused:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/firstFrame(time:connectionType:connectionReused:)":{"navigatorTitle":[{"text":"firstFrameWithTime:connectionType:connectionReused:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/firstframe(time:connectiontype:connectionreused:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstFrame(time:connectionType:connectionReused:)","abstract":[{"type":"text","text":"Событие получения первого кадра."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"firstFrame(time:connectionType:connectionReused:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"firstFrameWithTime:connectionType:connectionReused:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"firstFrameWithTime:connectionType:connectionReused:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"firstFrameWithTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"connectionType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"connectionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionReused:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"connectionReused"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"time","content":[{"inlineContent":[{"text":"Время в миллисекундах.","type":"text"}],"type":"paragraph"}]},{"name":"connectionType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3)."}]}]},{"name":"connectionReused","content":[{"type":"paragraph","inlineContent":[{"text":"Было ли переиспользовано соединение при запросах.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"firstFrameWithTime:connectionType:connectionReused:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstFrame(time:connectionType:connectionReused:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstFrame(time:connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"firstFrameWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}