{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"abstract":[{"text":"Пользователь руками изменил gravity.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/videostatshandler\/gravity(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videostatshandler\/gravity(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)gravity:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"title":"gravity(_:)","navigatorTitle":[{"text":"gravity:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gravity","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","text":"PlayerViewGravity","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/gravity(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"kind":"symbol","title":"PlayerViewGravity","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","url":"\/documentation\/ovkit\/playerviewgravity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewGravity"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerViewGravity"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/gravity(_:)":{"navigatorTitle":[{"kind":"identifier","text":"gravity:"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/gravity(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/ovkit\/videostatshandler\/gravity(_:)","title":"gravity(_:)","abstract":[{"type":"text","text":"Пользователь руками изменил gravity."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"gravity:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"gravity:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"gravity:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"OVKPlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gravity"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerViewGravity","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"gravity:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1gravity(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"gravity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1gravity(_:)\/fragments"}]}]}