{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/playbackerror(_:recoverable:from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/playbackerror(_:recoverable:from:)"]}],"abstract":[{"text":"Произошла ошибка воспроизведения.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"text":"recoverable","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"rawFormat","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Ошибка OVPlayerKit или OVKit.","type":"text"}],"type":"paragraph"}],"name":"error"},{"name":"recoverable","content":[{"inlineContent":[{"type":"text","text":"Плеер не покажет ошибку воспроизведения, а будет предпринимать попытки проиграть другой ресурс из набора "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"rawFormat","content":[{"type":"paragraph","inlineContent":[{"text":"С какого ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"type":"text","text":" произошла ошибка. Уточнение формата, при котором произошла ошибка, т.к. в случае "},{"code":"recoverable","type":"codeVoice"},{"text":" текущий формат в ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat"},{"text":" уже будет новый.","type":"text"}]}]}]}],"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"playbackError:recoverable:from:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recoverable","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)playbackError:recoverable:from:","role":"symbol","roleHeading":"Instance Method","title":"playbackError(_:recoverable:from:)","required":true,"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackError(_:recoverable:from:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/fileFormat":{"abstract":[{"type":"text","text":"Текущий выбранный для проигрывания формат. Может не быть, если воспроизведение еще не началось."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat","title":"fileFormat","type":"topic","url":"\/documentation\/ovkit\/statscontext\/fileformat","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"title":"VideoFileFormat","role":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/playbackError(_:recoverable:from:)":{"required":true,"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackError(_:recoverable:from:)","url":"\/documentation\/ovkit\/videostatshandler\/playbackerror(_:recoverable:from:)","title":"playbackError(_:recoverable:from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"text":"recoverable","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Произошла ошибка воспроизведения."}],"navigatorTitle":[{"kind":"identifier","text":"playbackError:recoverable:from:"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"playbackError:recoverable:from:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"playbackError:recoverable:from:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"playbackError:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverable:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"recoverable","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rawFormat","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"Ошибка OVPlayerKit или OVKit.","type":"text"}]}]},{"name":"recoverable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер не покажет ошибку воспроизведения, а будет предпринимать попытки проиграть другой ресурс из набора "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","isActive":true},{"text":".","type":"text"}]}]},{"name":"rawFormat","content":[{"inlineContent":[{"text":"С какого ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"type":"text","text":" произошла ошибка. Уточнение формата, при котором произошла ошибка, т.к. в случае "},{"code":"recoverable","type":"codeVoice"},{"type":"text","text":" текущий формат в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat","isActive":true,"type":"reference"},{"text":" уже будет новый.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace"},{"op":"replace","value":"playbackError:recoverable:from:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackError(_:recoverable:from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackError(_:recoverable:from:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playbackError:recoverable:from:"}]}]}]}