{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)progressChangedWithTime:","navigatorTitle":[{"kind":"identifier","text":"progressChangedWithTime:"}],"role":"symbol","title":"progressChanged(time:)"},"abstract":[{"type":"text","text":"Текущее время проигрывания изменилось."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"time","content":[{"inlineContent":[{"type":"text","text":"Текущее время плеера."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Обновляется не чаще, чем раз в секунду.","type":"text"}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Можно использовать только для статистики. Для обслуживания бизнес-логики вокруг плеера существует механизм "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Warning","style":"warning"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/videostatshandler\/progresschanged(time:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/progresschanged(time:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/progressChanged(time:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addPeriodicTimeObserver(forInterval:using:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"title":"addPeriodicTimeObserver(forInterval:using:)","type":"topic","url":"\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)","role":"symbol","navigatorTitle":[{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/progressChanged(time:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/progressChanged(time:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"abstract":[{"text":"Текущее время проигрывания изменилось.","type":"text"}],"type":"topic","title":"progressChanged(time:)","url":"\/documentation\/ovkit\/videostatshandler\/progresschanged(time:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"progressChangedWithTime:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"progressChangedWithTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"text":"Текущее время плеера.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"op":"replace","value":"addPeriodicTimeObserverForInterval:using:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/fragments"},{"op":"replace","value":"progressChangedWithTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1progressChanged(time:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1progressChanged(time:)\/fragments"}]}]}