{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/seek(method:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/seek(method:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"title":"seek(method:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seek"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"text":"StatsSeekMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)seekWithMethod:","navigatorTitle":[{"text":"seekWithMethod:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/seek(method:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Пользователь перемотал видео."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seek"},{"kind":"text","text":"("},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"text":"StatsSeekMethod","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsSeekMethod"}],"kind":"symbol","title":"StatsSeekMethod","abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/seek(method:)":{"navigatorTitle":[{"text":"seekWithMethod:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/seek(method:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"seek","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"text":"StatsSeekMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod"},{"kind":"text","text":")"}],"title":"seek(method:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/seek(method:)","type":"topic","abstract":[{"text":"Пользователь перемотал видео.","type":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"seekWithMethod:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"seekWithMethod:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"seekWithMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OVKStatsSeekMethod","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod"},{"kind":"text","text":") "},{"kind":"internalParam","text":"method"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace","value":"OVKVideoStatsHandler"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"value":"OVKStatsSeekMethod","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title"},{"value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]},{"value":"seekWithMethod:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1seek(method:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekWithMethod:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1seek(method:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}