{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/soundOn(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"isOn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/soundon(_:)"]},{"paths":["\/documentation\/ovkit\/videostatshandler\/soundon(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)soundOn:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"soundOn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","title":"soundOn(_:)","navigatorTitle":[{"text":"soundOn:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Изменилось состояние звука."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/soundOn(_:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/soundOn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/videostatshandler\/soundon(_:)","navigatorTitle":[{"kind":"identifier","text":"soundOn:"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Изменилось состояние звука."}],"title":"soundOn(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/videostatshandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"soundOn:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"soundOn:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"soundOn:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isOn","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1soundOn(_:)\/title","value":"soundOn:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"soundOn:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1soundOn(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace"}]}]}