{"abstract":[{"text":"Видео начало играть в плеере, не важно userInitiated или нет.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"fromTime","content":[{"inlineContent":[{"text":"Время с которого начнется \/ продолжится воспроизведение (округлено до целых).","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Вызовется при перезапуске видео пользователем или ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Также, если до этого играло другое видео — метод вызовется.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Если видео до этого было просто на паузе — метод вызван не будет (буден вызван "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"Для трансляций будет использовано текущее время"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler\/start(fromtime:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/start(fromtime:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/start(fromTime:)"},"kind":"symbol","metadata":{"title":"start(fromTime:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"startFromTime:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)startFromTime:","modules":[{"name":"OVKit"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/resume()":{"url":"\/documentation\/ovkit\/videostatshandler\/resume()","title":"resume()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()","abstract":[{"type":"text","text":"Видео было снято с паузы пользователем."}],"navigatorTitle":[{"text":"resume","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/repeated":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"repeated"}],"url":"\/documentation\/ovkit\/video\/repeated","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"repeated","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/start(fromTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/start(fromTime:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"startFromTime:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/start(fromtime:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"title":"start(fromTime:)","abstract":[{"type":"text","text":"Видео начало играть в плеере, не важно userInitiated или нет."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"startFromTime:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startFromTime:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startFromTime:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"fromTime"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"fromTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время с которого начнется \/ продолжится воспроизведение (округлено до целых)."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/title","value":"resume"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resume","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/title","value":"repeated"},{"value":[{"kind":"identifier","text":"repeated"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/fragments"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"startFromTime:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1start(fromTime:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"startFromTime:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1start(fromTime:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}