{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoZoom","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/videostatshandler\/videozoom()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videostatshandler\/videozoom()"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoZoom()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Пользователь активировал зум через жест."}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"videoZoom"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler(im)videoZoom","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoZoom"},{"text":"()","kind":"text"}],"title":"videoZoom()","role":"symbol","modules":[{"name":"OVKit"}],"required":true},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/videoZoom()":{"title":"videoZoom()","type":"topic","abstract":[{"text":"Пользователь активировал зум через жест.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoZoom()","url":"\/documentation\/ovkit\/videostatshandler\/videozoom()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoZoom"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"videoZoom","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"title":"VideoStatsHandler","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videostatshandler"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"videoZoom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"videoZoom","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoZoom"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoZoom()\/title","value":"videoZoom"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoZoom()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoZoom"}]},{"value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"}]}]}