{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","interfaceLanguage":"swift"},"abstract":[{"text":"Набор типов сети, в которых разрешено скачивание видео.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/allowednetworktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/allowednetworktype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedNetworkType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectionMask","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask"}],"title":"allowedNetworkType","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig(py)allowedNetworkType","navigatorTitle":[{"kind":"identifier","text":"allowedNetworkType"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedNetworkType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectionMask","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"К примеру, если выбрать только WiFi, то выполняющиеся загрузки будут автоматически приостанавливаться при переключении на мобильную сеть. А при появлении WiFi сети – автоматически возобновятся. Во время работы ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","type":"reference","isActive":true},{"text":" поддерживаемые типы сети можно изменять на лету при помощи ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"Значение в конфигурации по умолчанию – ","type":"text"},{"code":"wifiAndCellular","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionMask","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","title":"NetworkConnectionMask","type":"topic","url":"\/documentation\/ovkit\/networkconnectionmask","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NetworkConnectionMask","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/allowedNetworkType":{"navigatorTitle":[{"text":"allowedNetworkType","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig\/allowednetworktype","abstract":[{"text":"Набор типов сети, в которых разрешено скачивание видео.","type":"text"}],"title":"allowedNetworkType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedNetworkType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectionMask","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","type":"topic","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"url":"\/documentation\/ovkit\/persistencemanager","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig","abstract":[{"text":"Конфигурация менеджера оффлайн-хранилища.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","title":"PersistenceManagerConfig","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManagerConfig"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/updateAllowedNetworkType(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAllowedNetworkType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Обновление маски типов сети, при которых разрешается загрузка видео."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","title":"updateAllowedNetworkType(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateAllowedNetworkType:"}],"url":"\/documentation\/ovkit\/persistencemanager\/updateallowednetworktype(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowedNetworkType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allowedNetworkType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKNetworkConnectionMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask"},{"text":" * ","kind":"text"},{"text":"allowedNetworkType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"text":"OVKNetworkConnectionMask","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"text":"OVKNetworkConnectionMask","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/title","value":"allowedNetworkType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/fragments","value":[{"text":"allowedNetworkType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title","value":"OVKPersistenceManagerConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments","value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle","value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/title","value":"updateAllowedNetworkType:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateAllowedNetworkType:","kind":"identifier"}]}]}]}