{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:allowednetworktype:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:allowednetworktype:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"libraryRoot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowedNetworkType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionMask","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"libraryRoot","content":[{"type":"paragraph","inlineContent":[{"text":"Путь к библиотеке оффлайн-хранилища. Более подробно описано в свойстве ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","type":"reference"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Набор типов сети, в которых разрешено скачивание видео. Более подробно описано в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"name":"allowedNetworkType"},{"name":"maxConcurrentDownloadsCount","content":[{"inlineContent":[{"text":"Максимальное количество одновременно выполняющихся загрузок. Более подробно описано в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Создание конфигурации."}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryRoot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowedNetworkType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionMask","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","title":"init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig(im)initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryRoot"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowedNetworkType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier","text":"NetworkConnectionMask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)","url":"\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:allowednetworktype:maxconcurrentdownloadscount:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Создание конфигурации."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/maxConcurrentDownloadsCount":{"title":"maxConcurrentDownloadsCount","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","abstract":[{"text":"Максимальное количество одновременно выполняющихся загрузок.","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig\/maxconcurrentdownloadscount","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"title":"PersistenceManagerConfig","url":"\/documentation\/ovkit\/persistencemanagerconfig","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerConfig","kind":"identifier"}],"navigatorTitle":[{"text":"PersistenceManagerConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Конфигурация менеджера оффлайн-хранилища."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/allowedNetworkType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedNetworkType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier","text":"NetworkConnectionMask"}],"title":"allowedNetworkType","url":"\/documentation\/ovkit\/persistencemanagerconfig\/allowednetworktype","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Набор типов сети, в которых разрешено скачивание видео."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowedNetworkType"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/libraryRoot":{"title":"libraryRoot","navigatorTitle":[{"kind":"identifier","text":"libraryRoot"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraryRoot","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","abstract":[{"text":"Корневая директория, в которой располагаются файлы, необходимые для работы ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"title":"PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"type":"topic","navigatorTitle":[{"text":"NetworkConnectionMask","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionMask","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","abstract":[],"url":"\/documentation\/ovkit\/networkconnectionmask","role":"symbol","kind":"symbol","title":"NetworkConnectionMask"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLibraryRoot:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"libraryRoot","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowedNetworkType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKNetworkConnectionMask","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"},{"text":" *) ","kind":"text"},{"text":"allowedNetworkType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Путь к библиотеке оффлайн-хранилища. Более подробно описано в свойстве ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"libraryRoot"},{"name":"allowedNetworkType","content":[{"type":"paragraph","inlineContent":[{"text":"Набор типов сети, в которых разрешено скачивание видео. Более подробно описано в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"name":"maxConcurrentDownloadsCount","content":[{"type":"paragraph","inlineContent":[{"text":"Максимальное количество одновременно выполняющихся загрузок. Более подробно описано в ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","type":"reference"},{"text":".","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)\/title","value":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLibraryRoot:allowedNetworkType:maxConcurrentDownloadsCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/title","value":"maxConcurrentDownloadsCount"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/fragments","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title","value":"OVKPersistenceManagerConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/title","value":"allowedNetworkType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/fragments","value":[{"kind":"identifier","text":"allowedNetworkType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/title","value":"libraryRoot"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/fragments","value":[{"kind":"identifier","text":"libraryRoot"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}