{"abstract":[{"text":"Создание конфигурации.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:maxconcurrentdownloadscount:)"]},{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:maxConcurrentDownloadsCount:)"},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig(im)initWithLibraryRoot:maxConcurrentDownloadsCount:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryRoot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","title":"init(libraryRoot:maxConcurrentDownloadsCount:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"initWithLibraryRoot:maxConcurrentDownloadsCount:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"libraryRoot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Путь к библиотеке оффлайн-хранилища. Более подробно описано в свойстве ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","type":"reference","isActive":true},{"text":".","type":"text"}]}],"name":"libraryRoot"},{"content":[{"inlineContent":[{"type":"text","text":"Максимальное количество одновременно выполняющихся загрузок. Более подробно описано в "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"maxConcurrentDownloadsCount"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"По умолчанию разрешено скачивание в любой сети.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/init(libraryRoot:maxConcurrentDownloadsCount:)":{"url":"\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:maxconcurrentdownloadscount:)","type":"topic","title":"init(libraryRoot:maxConcurrentDownloadsCount:)","abstract":[{"text":"Создание конфигурации.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"libraryRoot","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLibraryRoot:maxConcurrentDownloadsCount:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:maxConcurrentDownloadsCount:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/libraryRoot":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"libraryRoot"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraryRoot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","title":"libraryRoot","role":"symbol","abstract":[{"type":"text","text":"Корневая директория, в которой располагаются файлы, необходимые для работы "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"},{"type":"text","text":"."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","title":"PersistenceManagerConfig","role":"symbol","abstract":[{"type":"text","text":"Конфигурация менеджера оффлайн-хранилища."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","title":"PersistenceManager","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/maxConcurrentDownloadsCount":{"url":"\/documentation\/ovkit\/persistencemanagerconfig\/maxconcurrentdownloadscount","abstract":[{"type":"text","text":"Максимальное количество одновременно выполняющихся загрузок."}],"title":"maxConcurrentDownloadsCount","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithLibraryRoot:maxConcurrentDownloadsCount:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLibraryRoot:maxConcurrentDownloadsCount:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLibraryRoot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"libraryRoot"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"libraryRoot","content":[{"inlineContent":[{"type":"text","text":"Путь к библиотеке оффлайн-хранилища. Более подробно описано в свойстве "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"maxConcurrentDownloadsCount","content":[{"inlineContent":[{"text":"Максимальное количество одновременно выполняющихся загрузок. Более подробно описано в ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:maxConcurrentDownloadsCount:)\/title","value":"initWithLibraryRoot:maxConcurrentDownloadsCount:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:maxConcurrentDownloadsCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLibraryRoot:maxConcurrentDownloadsCount:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/title","value":"libraryRoot","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/fragments","value":[{"kind":"identifier","text":"libraryRoot"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title","value":"OVKPersistenceManagerConfig","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/title","value":"maxConcurrentDownloadsCount","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/fragments","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}],"op":"replace"}]}]}