{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot"},"metadata":{"title":"libraryRoot","navigatorTitle":[{"text":"libraryRoot","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig(py)libraryRoot","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraryRoot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Корневая директория, в которой располагаются файлы, необходимые для работы "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","type":"reference"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraryRoot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Указанный путь переходит в полное владение экземпляра "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","isActive":true},{"type":"text","text":" и может быть им очищен. Поэтому для этой цели нельзя использовать корневые директории ("},{"type":"emphasis","inlineContent":[{"text":"Library","type":"text"}]},{"type":"text","text":", "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Documents"}]},{"type":"text","text":", и т.д.). Директорию рекомендуется создавать внутри "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Library"}]},{"type":"text","text":", либо "},{"type":"emphasis","inlineContent":[{"text":"Application Support","type":"text"}]},{"type":"text","text":", чтобы данные не попадали в iCloud как часть бэкапа."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"В указанном каталоге хранится только список загруженных или еще загружаемых видео с их состоянием и мета-информацией. Хранение проигрываемых файлов видео осуществляется в другом месте."}]}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/libraryRoot":{"url":"\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot","role":"symbol","type":"topic","navigatorTitle":[{"text":"libraryRoot","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraryRoot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Корневая директория, в которой располагаются файлы, необходимые для работы "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","isActive":true},{"type":"text","text":"."}],"title":"libraryRoot","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","title":"PersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerConfig","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManagerConfig","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanagerconfig","title":"PersistenceManagerConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","abstract":[{"text":"Конфигурация менеджера оффлайн-хранилища.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"libraryRoot","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"libraryRoot"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"libraryRoot","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"libraryRoot","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/title"},{"value":[{"kind":"identifier","text":"libraryRoot"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/fragments"},{"value":"OVKPersistenceManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"value":"OVKPersistenceManagerConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title"},{"value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments"},{"value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}