{"kind":"symbol","abstract":[{"type":"text","text":"Максимальное количество одновременно выполняющихся загрузок."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Определяет, сколько задач на скачивание могут выполняться одновременно. Например, если установить значение "},{"code":"1","type":"codeVoice"},{"text":", все загрузки будут выполняться поочерёдно. При значении ","type":"text"},{"type":"codeVoice","code":"NSOperationQueueDefaultMaxConcurrentOperationCount"},{"type":"text","text":" система сама определит оптимальное количество параллельных задач."}]}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/maxconcurrentdownloadscount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagerconfig\/maxconcurrentdownloadscount"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"maxConcurrentDownloadsCount","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig(py)maxConcurrentDownloadsCount","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Конфигурация менеджера оффлайн-хранилища."}],"title":"PersistenceManagerConfig","url":"\/documentation\/ovkit\/persistencemanagerconfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/maxConcurrentDownloadsCount":{"type":"topic","url":"\/documentation\/ovkit\/persistencemanagerconfig\/maxconcurrentdownloadscount","kind":"symbol","abstract":[{"type":"text","text":"Максимальное количество одновременно выполняющихся загрузок."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/maxConcurrentDownloadsCount","navigatorTitle":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}],"title":"maxConcurrentDownloadsCount"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"maxConcurrentDownloadsCount","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title","value":"OVKPersistenceManagerConfig","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle","value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/title","value":"maxConcurrentDownloadsCount","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1maxConcurrentDownloadsCount\/fragments","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}],"op":"replace"}]}]}