{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKInteractiveStatsHandler(im)interactiveMovieStartWithRootInteractiveVideoID:","modules":[{"name":"OVKit"}],"title":"interactiveMovieStart(rootInteractiveVideoID:)","required":true,"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"interactiveMovieStartWithRootInteractiveVideoID:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interactiveMovieStart","kind":"identifier"},{"kind":"text","text":"("},{"text":"rootInteractiveVideoID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method"},"abstract":[{"text":"Начался просмотр интерактивного видео.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/interactiveMovieStart(rootInteractiveVideoID:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactiveMovieStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rootInteractiveVideoID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interactivestatshandler\/interactivemoviestart(rootinteractivevideoid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interactivestatshandler\/interactivemoviestart(rootinteractivevideoid:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"url":"\/documentation\/ovkit\/statscollector","type":"topic","title":"StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler","type":"topic","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":" после добавления нового "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"title":"InteractiveStatsHandler","role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler","navigatorTitle":[{"text":"InteractiveStatsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveStatsHandler","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler/interactiveMovieStart(rootInteractiveVideoID:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/interactiveMovieStart(rootInteractiveVideoID:)","type":"topic","abstract":[{"type":"text","text":"Начался просмотр интерактивного видео."}],"title":"interactiveMovieStart(rootInteractiveVideoID:)","role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler\/interactivemoviestart(rootinteractivevideoid:)","navigatorTitle":[{"text":"interactiveMovieStartWithRootInteractiveVideoID:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactiveMovieStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rootInteractiveVideoID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interactiveMovieStartWithRootInteractiveVideoID:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interactiveMovieStartWithRootInteractiveVideoID:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interactiveMovieStartWithRootInteractiveVideoID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rootInteractiveVideoID","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"OVKStatsCollector","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}]},{"value":"OVKInteractiveStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKInteractiveStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1interactiveMovieStart(rootInteractiveVideoID:)\/title","value":"interactiveMovieStartWithRootInteractiveVideoID:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1interactiveMovieStart(rootInteractiveVideoID:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interactiveMovieStartWithRootInteractiveVideoID:","kind":"identifier"}],"op":"replace"}]}]}