{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"aheadCount","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy(py)aheadCount","title":"aheadCount","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aheadCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"aheadCount","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"languages":["swift"]}]}],"abstract":[{"text":"Количество видеозаписей впереди для префетча.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/aheadCount","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/aheadcount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/aheadcount"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKSimplePrefetchStrategy/aheadCount":{"role":"symbol","title":"aheadCount","abstract":[{"type":"text","text":"Количество видеозаписей впереди для префетча."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/aheadCount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aheadCount"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"aheadCount","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovksimpleprefetchstrategy\/aheadcount"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"title":"SimplePrefetchStrategy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"kind":"symbol","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/simpleprefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"aheadCount","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aheadCount"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"aheadCount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1aheadCount\/title","op":"replace","value":"aheadCount"},{"value":[{"kind":"identifier","text":"aheadCount"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1aheadCount\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title","value":"OVKSimplePrefetchStrategy","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments","value":[{"kind":"identifier","text":"OVKSimplePrefetchStrategy"}],"op":"replace"}]}]}