{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Длительность префетча.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/duration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/duration"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"title":"duration","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy(py)duration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"duration","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/duration"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKSimplePrefetchStrategy/duration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/duration","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"duration","abstract":[{"type":"text","text":"Длительность префетча."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/ovkit\/ovksimpleprefetchstrategy\/duration"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"title":"SimplePrefetchStrategy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"kind":"symbol","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/simpleprefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"duration","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"duration"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"duration","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1duration\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title","value":"OVKSimplePrefetchStrategy"},{"value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments"}]}]}