{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/prefetchreached"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovksimpleprefetchstrategy\/prefetchreached"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"]]},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchReached"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchReached"}],"externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy(py)prefetchReached","symbolKind":"property","role":"symbol","title":"prefetchReached","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchReached","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Префетчить ли видео с нулевым индексом."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/prefetchReached"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"title":"SimplePrefetchStrategy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"kind":"symbol","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/simpleprefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit/OVKSimplePrefetchStrategy/prefetchReached":{"role":"symbol","title":"prefetchReached","abstract":[{"type":"text","text":"Префетчить ли видео с нулевым индексом."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSimplePrefetchStrategy\/prefetchReached","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchReached","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"prefetchReached","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovksimpleprefetchstrategy\/prefetchreached"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"prefetchReached","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"prefetchReached","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"prefetchReached","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKSimplePrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title"},{"op":"replace","value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1prefetchReached\/title","op":"replace","value":"prefetchReached"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSimplePrefetchStrategy~1prefetchReached\/fragments","value":[{"kind":"identifier","text":"prefetchReached"}],"op":"replace"}]}]}