{"metadata":{"title":"addBehavior(_:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"extendedModule":"OVKit","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addBehavior","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ControlsBehavior","preciseIdentifier":"s:5OVKit16ControlsBehaviorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE11addBehavioryyAA0cG0_pF::SYNTHESIZED::c:@M@OVKit@objc(cs)SupplementaryAdControlsView"},"sections":[],"abstract":[{"text":"Добавление поведения на контролы.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/PlayerControlsViewProtocol-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addBehavior","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"behavior"},{"text":": ","kind":"text"},{"text":"ControlsBehavior","preciseIdentifier":"s:5OVKit16ControlsBehaviorP","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"behavior","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Поведение, которое надо добавить."}]}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/addbehavior(_:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/addBehavior(_:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/addBehavior(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/addBehavior(_:)","kind":"symbol","abstract":[{"text":"Добавление поведения на контролы.","type":"text"}],"role":"symbol","title":"addBehavior(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addBehavior"},{"text":"(","kind":"text"},{"text":"ControlsBehavior","preciseIdentifier":"s:5OVKit16ControlsBehaviorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/addbehavior(_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"title":"SupplementaryAdControlsView","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/PlayerControlsViewProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/PlayerControlsViewProtocol-Implementations","abstract":[],"title":"PlayerControlsViewProtocol Implementations","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/playercontrolsviewprotocol-implementations"},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"url":"\/documentation\/ovkit\/controlsbehavior","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","abstract":[{"type":"text","text":"Динамическое поведение контролов."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ControlsBehavior"}],"title":"ControlsBehavior"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SupplementaryAdControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}]}]}]}