{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsvisible"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsVisible","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"title":"controlsVisible","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:5OVKit27SupplementaryAdControlsViewC15controlsVisibleSbvp"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"abstract":[{"text":"Видны ли контролы на экране в данный момент.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"title":"SupplementaryAdControlsView","type":"topic","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlsVisible":{"role":"symbol","abstract":[{"text":"Видны ли контролы на экране в данный момент.","type":"text"}],"kind":"symbol","title":"controlsVisible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsvisible","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsVisible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"OVKSupplementaryAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}]}]}]}