{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsViewDelegate","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"⚠️ Свойство должно быть ","type":"text"},{"inlineContent":[{"text":"weak","type":"text"}],"type":"strong"},{"text":"!","type":"text"}]}],"name":"Warning"}]}],"sections":[],"metadata":{"externalID":"s:5OVKit27SupplementaryAdControlsViewC16controlsDelegateAA0deG0_pSgvp","modules":[{"name":"OVKit"}],"role":"symbol","title":"controlsDelegate","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsViewDelegate","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP"},{"text":")?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsDelegate"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"abstract":[{"text":"Делегат контролов. Устанавливать не нужно","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate","abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsViewDelegate","kind":"identifier"}],"title":"ControlsViewDelegate","navigatorTitle":[{"text":"ControlsViewDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlsDelegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlsDelegate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","kind":"typeIdentifier","text":"ControlsViewDelegate"},{"kind":"text","text":")?"}],"type":"topic","title":"controlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsDelegate","kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsdelegate","abstract":[{"text":"Делегат контролов. Устанавливать не нужно","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","type":"topic","abstract":[{"text":"Представление-обёртка для отображения дополнительных рекламных контролов.","type":"text"}],"title":"SupplementaryAdControlsView","url":"\/documentation\/ovkit\/supplementaryadcontrolsview"}},"variantOverrides":[{"patch":[{"value":"SupplementaryAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}