{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/coverContainerView"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverContainerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Контролы могут предоставить "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":", в который должен быть помещён "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"type":"text","text":". Это может быть полезно, когда есть контролы, которые всегда должны быть доступны для взаимодействия (например, кнопка закрытия полноэкранного режима). По умолчанию свойство имеет значение "},{"code":"nil","type":"codeVoice"},{"type":"text","text":". В этом случае "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"type":"text","text":" добавляется поверх текущих контролов плеера."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Контейнер обязан:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"всегда быть видимым","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"не забирать себе касания, но отдавать их своим subviews"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"растягиваться до размера контролов"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"растягивать свои subview до своего размера"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverContainerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"extendedModule":"OVKit","modules":[{"name":"OVKit"}],"title":"coverContainerView","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE014coverContainerD0So6UIViewCSgvp::SYNTHESIZED::c:@M@OVKit@objc(cs)SupplementaryAdControlsView"},"abstract":[{"type":"text","text":"Контейнер для "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/covercontainerview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","role":"symbol","title":"SupplementaryAdControlsView","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","title":"CoverView","url":"\/documentation\/ovkit\/coverview","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/coverContainerView":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"abstract":[{"text":"Контейнер для ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/coverContainerView","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/covercontainerview","title":"coverContainerView"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"SupplementaryAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}