{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/createInstance()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}]}],"kind":"declarations"}],"metadata":{"externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE14createInstancexyFZ::SYNTHESIZED::c:@M@OVKit@objc(cs)SupplementaryAdControlsView","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"roleHeading":"Type Method","symbolKind":"method","title":"createInstance()","extendedModule":"OVKit"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"PlayerControlsViewProtocol.createInstance()"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/createinstance()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"kind":"symbol","title":"SupplementaryAdControlsView","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/createInstance()":{"role":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/createinstance()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/createInstance()","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"createInstance()","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SupplementaryAdControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title"},{"value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments"},{"value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle"}]}]}