{"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKSupplementaryAdControlsView(im)didMoveToWindow","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":"()"}],"title":"didMoveToWindow()"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didMoveToWindow()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/didmovetowindow()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/didmovetowindow()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"title":"SupplementaryAdControlsView","abstract":[{"text":"Представление-обёртка для отображения дополнительных рекламных контролов.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didMoveToWindow()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didMoveToWindow()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didMoveToWindow()","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didmovetowindow()","role":"symbol","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didMoveToWindow","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"OVKSupplementaryAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdControlsView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSupplementaryAdControlsView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1didMoveToWindow()\/title","value":"didMoveToWindow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1didMoveToWindow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}