{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didTapSupplementaryAdControlsView(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Вызывается при нажатии на контролы рекламного представления.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapSupplementaryAdControlsView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SupplementaryAdView","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"inlineContent":[{"text":"Экземпляр ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","isActive":true,"type":"reference"},{"text":", на котором произошло нажатие.","type":"text"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"extendedModule":"OVKit","role":"symbol","title":"didTapSupplementaryAdControlsView(_:)","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"s:5OVKit27SupplementaryAdControlsViewC06didTapbcdE0yyAA0bcE0CF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapSupplementaryAdControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SupplementaryAdView","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/didtapsupplementaryadcontrolsview(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didTapSupplementaryAdControlsView(_:)":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didtapsupplementaryadcontrolsview(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didTapSupplementaryAdControlsView(_:)","title":"didTapSupplementaryAdControlsView(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapSupplementaryAdControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SupplementaryAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Вызывается при нажатии на контролы рекламного представления.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"title":"SupplementaryAdView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"kind":"symbol","title":"SupplementaryAdControlsView","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"SupplementaryAdView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"kind":"identifier","text":"SupplementaryAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"SupplementaryAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"}]}]}