{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/didupdatepreview(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdatePreview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdatePreview(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdatePreview","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"s:5OVKit27SupplementaryAdControlsViewC16didUpdatePreviewyySo7UIImageCSgF","modules":[{"name":"OVKit"}],"role":"symbol","title":"didUpdatePreview(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"abstract":[{"type":"text","text":"Картинка превью загрузилась впервые или обновилась."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"kind":"symbol","title":"SupplementaryAdControlsView","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"abstract":[{"text":"Представление-обёртка для отображения дополнительных рекламных контролов.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didUpdatePreview(_:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdatePreview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdatePreview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Картинка превью загрузилась впервые или обновилась.","type":"text"}],"type":"topic","title":"didUpdatePreview(_:)","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didupdatepreview(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKSupplementaryAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title"},{"op":"replace","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments"},{"op":"replace","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle"}]}]}