{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hideControls(animated:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hideControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/hidecontrols(animated:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"HideableControls.hideControls(animated:)"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"hideControls(animated:)","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideControls"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:5OVKit27SupplementaryAdControlsViewC04hideD08animatedySb_tF"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"kind":"symbol","title":"SupplementaryAdControlsView","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/hideControls(animated:)":{"kind":"symbol","title":"hideControls(animated:)","type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/hidecontrols(animated:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hideControls(animated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideControls"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"SupplementaryAdControlsView"},{"value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}