{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hoverGesture"},"abstract":[{"type":"text","text":"Необходимо вернуть "},{"type":"codeVoice","code":"UIHoverGestureRecognizer"},{"type":"text","text":"если нужна реакция на движение курсора."}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"s:5OVKit27SupplementaryAdControlsViewC12hoverGestureSo19UIGestureRecognizerCSgvp","title":"hoverGesture","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hoverGesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/hovergesture"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hoverGesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/hoverGesture":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hoverGesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/hovergesture","abstract":[{"type":"text","text":"Необходимо вернуть "},{"type":"codeVoice","code":"UIHoverGestureRecognizer"},{"type":"text","text":"если нужна реакция на движение курсора."}],"title":"hoverGesture","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hoverGesture","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","role":"symbol","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview","type":"topic","title":"SupplementaryAdControlsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","op":"replace","value":"OVKSupplementaryAdControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","op":"replace","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","op":"replace","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}]}]}]}