{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","text":"SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/init(frame:style:showsProgress:)"},"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/init(frame:style:showsprogress:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","text":"SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"text":"showsProgress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","externalID":"s:5OVKit27SupplementaryAdControlsViewC5frame5style13showsProgressACSo6CGRectV_AA0bcE5StyleCSbtcfc","title":"init(frame:style:showsProgress:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"type":"topic","navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"url":"\/documentation\/ovkit\/supplementaryadview","role":"symbol","kind":"symbol","title":"SupplementaryAdView"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/init(frame:style:showsProgress:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/init(frame:style:showsProgress:)","abstract":[],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/init(frame:style:showsprogress:)","role":"symbol","kind":"symbol","title":"init(frame:style:showsProgress:)"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"title":"SupplementaryAdViewStyle","navigatorTitle":[{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","abstract":[{"type":"text","text":"Стиль дополнительного представления для CTA-контрола рекламы - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/supplementaryadviewstyle","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"title":"SupplementaryAdControlsView","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"OVKSupplementaryAdView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"OVKSupplementaryAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdControlsView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"text":"OVKSupplementaryAdControlsView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}