{"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/sizethatfits(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/sizethatfits(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"sizeThatFits(_:)","externalID":"c:@M@OVKit@objc(cs)SupplementaryAdControlsView(im)sizeThatFits:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/sizeThatFits(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeThatFits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}],"type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"kind":"symbol","title":"SupplementaryAdControlsView","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/sizeThatFits(_:)":{"navigatorTitle":[{"text":"sizeThatFits:","kind":"identifier"}],"title":"sizeThatFits(_:)","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/sizethatfits(_:)","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/sizeThatFits(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeThatFits","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sizeThatFits:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"sizeThatFits:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"SupplementaryAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1sizeThatFits(_:)\/title","value":"sizeThatFits:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1sizeThatFits(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sizeThatFits:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}