{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementaryView","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","text":"SupplementaryAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/supplementaryview"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/supplementaryView","interfaceLanguage":"swift"},"metadata":{"externalID":"s:5OVKit27SupplementaryAdControlsViewC013supplementaryE0AA0bcE0Cvp","title":"supplementaryView","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementaryView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SupplementaryAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","role":"symbol","title":"SupplementaryAdControlsView","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdControlsView"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"abstract":[{"type":"text","text":"Представление для CTA-контрола рекламы."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"title":"SupplementaryAdView","url":"\/documentation\/ovkit\/supplementaryadview","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/supplementaryView":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/supplementaryview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/supplementaryView","title":"supplementaryView","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementaryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SupplementaryAdView","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"SupplementaryAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"SupplementaryAdView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"kind":"identifier","text":"SupplementaryAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdView"}]}]}]}