{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview\/visibilityanimationduration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/visibilityAnimationDuration"},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"visibilityAnimationDuration","role":"symbol","symbolKind":"property","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE27visibilityAnimationDurationSdvpZ::SYNTHESIZED::c:@M@OVKit@objc(cs)OVKSupplementaryAdControlsView","extendedModule":"OVKit"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"]]},"abstract":[{"text":"Стандартная длительность анимации скрытия и показа контролов.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visibilityAnimationDuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Имеет значение ","type":"text"},{"code":"0.24","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/visibilityAnimationDuration":{"title":"visibilityAnimationDuration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/visibilityAnimationDuration","role":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/visibilityanimationduration","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"abstract":[{"text":"Стандартная длительность анимации скрытия и показа контролов.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"title":"SupplementaryAdControlsView","type":"topic","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title","value":"OVKSupplementaryAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdControlsView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSupplementaryAdControlsView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}