{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Case","navigatorTitle":[{"text":"OVKPlayerViewGravityFit","kind":"identifier"}],"symbolKind":"case","title":"PlayerViewGravity.fit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKPlayerViewGravity@OVKPlayerViewGravityFit","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerviewgravity\/fit"]},{"paths":["\/documentation\/ovkit\/playerviewgravity\/fit"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fit":{"kind":"symbol","role":"symbol","type":"topic","title":"PlayerViewGravity.fit","navigatorTitle":[{"text":"OVKPlayerViewGravityFit","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit","abstract":[],"url":"\/documentation\/ovkit\/playerviewgravity\/fit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewGravity"}],"role":"symbol","kind":"symbol","title":"PlayerViewGravity","url":"\/documentation\/ovkit\/playerviewgravity","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"OVKPlayerViewGravityFit"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPlayerViewGravityFit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKPlayerViewGravityFit"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPlayerViewGravityFit","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fit\/title"},{"value":[{"text":"OVKPlayerViewGravityFit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fit\/fragments"},{"op":"replace","value":"OVKPlayerViewGravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title"},{"value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle"}]}]}