{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur"},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"OVKPlayerViewGravityFitWithBlur","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKPlayerViewGravity@OVKPlayerViewGravityFitWithBlur","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitWithBlur"}],"title":"PlayerViewGravity.fitWithBlur","role":"symbol"},"abstract":[{"text":"Картинка вписана во вьюпорт плеера, а пустое место заполнено заблюренной версией картинки.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitWithBlur"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим работает не со всеми рендерами."}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/playerviewgravity\/fitwithblur"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerviewgravity\/fitwithblur"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fitWithBlur":{"title":"PlayerViewGravity.fitWithBlur","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitWithBlur","kind":"identifier"}],"abstract":[{"text":"Картинка вписана во вьюпорт плеера, а пустое место заполнено заблюренной версией картинки.","type":"text"}],"navigatorTitle":[{"text":"OVKPlayerViewGravityFitWithBlur","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewgravity\/fitwithblur"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","url":"\/documentation\/ovkit\/playerviewgravity","navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Режим отображения картинки в плеере.","type":"text"}],"type":"topic","title":"PlayerViewGravity"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPlayerViewGravityFitWithBlur","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravityFitWithBlur"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKPlayerViewGravityFitWithBlur","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fitWithBlur\/title","value":"OVKPlayerViewGravityFitWithBlur","op":"replace"},{"value":[{"text":"OVKPlayerViewGravityFitWithBlur","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fitWithBlur\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title","value":"OVKPlayerViewGravity","op":"replace"},{"value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}