{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/action","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"required":true,"title":"action","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"action","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType(py)action","symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType"]]},"abstract":[{"type":"text","text":"Описание действия кнопки."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestrictionbuttontype\/action"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestrictionbuttontype\/action"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","abstract":[{"text":"Модель кнопки для снятия запрета.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"identifier"}],"kind":"symbol","title":"VideoRestrictionButtonType","navigatorTitle":[{"text":"VideoRestrictionButtonType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/videorestrictionbuttontype"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType/action":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/action","type":"topic","navigatorTitle":[{"kind":"identifier","text":"action"}],"url":"\/documentation\/ovkit\/videorestrictionbuttontype\/action","required":true,"role":"symbol","abstract":[{"type":"text","text":"Описание действия кнопки."}],"title":"action"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"action"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"action","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title","value":"OVKVideoRestrictionButtonType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments","value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1action\/fragments","value":[{"text":"action","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}