{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideoadstype\/slot"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideoadstype\/slot"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"slot","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"required":true,"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"slot"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoAdsType(py)slot","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAdsType\/slot","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videoadstype","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoAdsType","kind":"identifier"}],"title":"VideoAdsType","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoAdsType/slot":{"title":"slot","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAdsType\/slot","required":true,"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"slot"}],"url":"\/documentation\/ovkit\/ovkvideoadstype\/slot","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"slot","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"slot"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"OVKVideoAdsType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","op":"replace","value":[{"text":"OVKVideoAdsType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAdsType~1slot\/title","op":"replace","value":"slot"},{"op":"replace","value":[{"kind":"identifier","text":"slot"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAdsType~1slot\/fragments"}]}]}