{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/!=(_:_:)"},"metadata":{"symbolKind":"op","extendedModule":"Swift","title":"!=(_:_:)","modules":[{"relatedModules":["Swift"],"name":"OVKit"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@OVKit@E@FullscreenViewControllerVisualStyle","role":"symbol","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/!=(_:_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/!=(_:_:)","type":"topic","title":"!=(_:_:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","abstract":[{"type":"text","text":"Вид отображения полноэкранного контроллера."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","kind":"symbol","title":"FullscreenViewControllerVisualStyle","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"value":"FullscreenViewControllerVisualStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}