{"metadata":{"modules":[{"name":"OVKit","relatedModules":["Swift"]}],"extendedModule":"Swift","symbolKind":"property","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@OVKit@E@FullscreenViewControllerVisualStyle","title":"hashValue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hashvalue"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hashValue"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"title":"FullscreenViewControllerVisualStyle","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/hashValue":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hashvalue","kind":"symbol","title":"hashValue","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hashValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"FullscreenViewControllerVisualStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","op":"replace"},{"value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","op":"replace"},{"value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","op":"replace"}]}]}