{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@OVKit@E@FullscreenViewControllerVisualStyle","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"OVKit"}],"symbolKind":"method","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"roleHeading":"Instance Method","title":"hash(into:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hash(into:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hash(into:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/hash(into:)":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hash(into:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hash(into:)","kind":"symbol","title":"hash(into:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"type":"topic","title":"FullscreenViewControllerVisualStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"abstract":[{"text":"Вид отображения полноэкранного контроллера.","type":"text"}],"navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"FullscreenViewControllerVisualStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","op":"replace"},{"value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","op":"replace"}]}]}