{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hashValue"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hash(into:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/RawRepresentable-Implementations"},"metadata":{"modules":[{"name":"OVKit"}],"title":"RawRepresentable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rawrepresentable-implementations"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/hashValue":{"role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hashvalue","kind":"symbol","title":"hashValue","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hashValue"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/hash(into:)":{"abstract":[],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/hash(into:)","type":"topic","kind":"symbol","title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/hash(into:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"abstract":[{"type":"text","text":"Вид отображения полноэкранного контроллера."}],"type":"topic","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"role":"symbol","title":"FullscreenViewControllerVisualStyle","kind":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"FullscreenViewControllerVisualStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title"},{"op":"replace","value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle"}]}]}