{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rectangular","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle@FullscreenViewControllerVisualStyleRectangular","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRectangular"}],"title":"FullscreenViewControllerVisualStyle.rectangular","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectangular"}],"role":"symbol"},"abstract":[{"text":"Плеер отображается в прямоугольной области максимально доступного размера.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectangular","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rectangular"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rectangular"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/rectangular":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rectangular","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rectangular"}],"abstract":[{"text":"Плеер отображается в прямоугольной области максимально доступного размера.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rectangular","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRectangular"}],"kind":"symbol","title":"FullscreenViewControllerVisualStyle.rectangular"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"title":"FullscreenViewControllerVisualStyle","kind":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","abstract":[],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"FullscreenViewControllerVisualStyleRectangular","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"FullscreenViewControllerVisualStyleRectangular","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRectangular"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"FullscreenViewControllerVisualStyleRectangular","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rectangular\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rectangular\/fragments","value":[{"text":"FullscreenViewControllerVisualStyleRectangular","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","value":"FullscreenViewControllerVisualStyle"},{"op":"replace","value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments"}]}]}