{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rounded"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle@FullscreenViewControllerVisualStyleRounded","title":"FullscreenViewControllerVisualStyle.rounded","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rounded","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rounded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rounded"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rounded"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"]]},"sections":[],"abstract":[{"text":"Плеер отображается в прямоугольной области со скругленными углами","type":"text"},{"text":" ","type":"text"},{"text":"с размерами, ограниченными максимальной стороной и соотношением сторон плеера.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","title":"FullscreenViewControllerVisualStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","type":"topic","abstract":[{"type":"text","text":"Вид отображения полноэкранного контроллера."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/rounded":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rounded","abstract":[{"text":"Плеер отображается в прямоугольной области со скругленными углами","type":"text"},{"text":" ","type":"text"},{"text":"с размерами, ограниченными максимальной стороной и соотношением сторон плеера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rounded","title":"FullscreenViewControllerVisualStyle.rounded","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rounded"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"FullscreenViewControllerVisualStyleRounded","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","value":"FullscreenViewControllerVisualStyle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rounded\/title","value":"FullscreenViewControllerVisualStyleRounded","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rounded\/fragments","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"op":"replace"}]}]}