{"metadata":{"extendedModule":"Swift","title":"!=(_:_:)","modules":[{"relatedModules":["Swift"],"name":"OVKit"}],"role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@OVKit@E@OVKDownloadSuspendReason","roleHeading":"Operator","symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/Equatable-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/!=(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/downloadsuspendreason\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/!=(_:_:)":{"abstract":[],"kind":"symbol","role":"symbol","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/downloadsuspendreason\/!=(_:_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/!=(_:_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"title":"DownloadSuspendReason","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/downloadsuspendreason","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadSuspendReason"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadSuspendReason"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/ovkit\/downloadsuspendreason\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","value":"OVKDownloadSuspendReason"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle"}]}]}