{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/downloadsuspendreason\/background"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/downloadsuspendreason\/background"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/background","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Загрузка была приостановлена из-за ухода приложения в фон."}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"DownloadSuspendReason.background","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}],"externalID":"c:@M@OVKit@E@OVKDownloadSuspendReason@OVKDownloadSuspendReasonBackground"},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadSuspendReason"}],"title":"DownloadSuspendReason","type":"topic","url":"\/documentation\/ovkit\/downloadsuspendreason","kind":"symbol","abstract":[{"text":"Причина, по которой может произойти приостановка загрузок видеозаписей.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadSuspendReason"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/background":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"OVKDownloadSuspendReasonBackground","kind":"identifier"}],"title":"DownloadSuspendReason.background","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/background","url":"\/documentation\/ovkit\/downloadsuspendreason\/background","abstract":[{"type":"text","text":"Загрузка была приостановлена из-за ухода приложения в фон."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKDownloadSuspendReasonBackground"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","op":"replace","value":"OVKDownloadSuspendReason"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1background\/title","op":"replace","value":"OVKDownloadSuspendReasonBackground"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1background\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}]}]}]}