{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason\/init(rawvalue:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"metadata":{"title":"init(rawValue:)","symbolKind":"init","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"s:5OVKit21DownloadSuspendReasonO8rawValueACSgSu_tcfc"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/init(rawValue:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/downloadsuspendreason\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/init(rawValue:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"url":"\/documentation\/ovkit\/downloadsuspendreason","navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DownloadSuspendReason","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"title":"DownloadSuspendReason","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","value":"OVKDownloadSuspendReason","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}