{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"manualPause","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Загрузка была приостановлена пользователем из кода."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason\/manualpause"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason\/manualpause"]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/manualPause","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"DownloadSuspendReason.manualPause","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manualPause","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"OVKDownloadSuspendReasonManualPause","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKDownloadSuspendReason@OVKDownloadSuspendReasonManualPause"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"url":"\/documentation\/ovkit\/downloadsuspendreason","role":"symbol","type":"topic","navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","kind":"symbol","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"title":"DownloadSuspendReason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadSuspendReason","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/manualPause":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/manualPause","kind":"symbol","url":"\/documentation\/ovkit\/downloadsuspendreason\/manualpause","title":"DownloadSuspendReason.manualPause","abstract":[{"text":"Загрузка была приостановлена пользователем из кода.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualPause"}],"navigatorTitle":[{"text":"OVKDownloadSuspendReasonManualPause","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKDownloadSuspendReasonManualPause"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"OVKDownloadSuspendReasonManualPause","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKDownloadSuspendReasonManualPause"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","value":"OVKDownloadSuspendReason"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments","value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle"},{"value":"OVKDownloadSuspendReasonManualPause","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1manualPause\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1manualPause\/fragments","value":[{"text":"OVKDownloadSuspendReasonManualPause","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}