{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@OVKit@E@OVKDownloadSuspendReason@OVKDownloadSuspendReasonNone","modules":[{"name":"OVKit"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"title":"DownloadSuspendReason.none"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason\/none"]}],"abstract":[{"type":"text","text":"Загрузка "},{"inlineContent":[{"type":"text","text":"не"}],"type":"emphasis"},{"type":"text","text":" приостановлена и выполняется."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadSuspendReason"}],"abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"type":"topic","title":"DownloadSuspendReason","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","url":"\/documentation\/ovkit\/downloadsuspendreason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadSuspendReason","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/none":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none","title":"DownloadSuspendReason.none","abstract":[{"text":"Загрузка ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"не","type":"text"}]},{"text":" приостановлена и выполняется.","type":"text"}],"navigatorTitle":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/downloadsuspendreason\/none","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"OVKDownloadSuspendReasonNone","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKDownloadSuspendReasonNone"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","value":"OVKDownloadSuspendReason"},{"op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/title","op":"replace","value":"OVKDownloadSuspendReasonNone"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/fragments","value":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}