{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/contents","interfaceLanguage":"swift"},"sections":[],"metadata":{"required":true,"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"contents"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contents","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","text":"MenuContents"}],"role":"symbol","title":"contents","externalID":"c:@M@OVKit@objc(pl)OVKMenu(py)contents"},"abstract":[{"text":"Данные для показа меню. Могут изменяться после того, как меню было показано.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkmenu\/contents"]},{"paths":["\/documentation\/ovkit\/ovkmenu\/contents"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contents"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","text":"MenuContents","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKMenu/contents":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/contents","url":"\/documentation\/ovkit\/ovkmenu\/contents","kind":"symbol","navigatorTitle":[{"text":"contents","kind":"identifier"}],"title":"contents","type":"topic","abstract":[{"type":"text","text":"Данные для показа меню. Могут изменяться после того, как меню было показано."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contents"},{"kind":"text","text":": "},{"text":"MenuContents","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MenuContents":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","url":"\/documentation\/ovkit\/menucontents","kind":"symbol","title":"MenuContents","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuContents"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenuContents"}],"abstract":[{"type":"text","text":"Модель содержимого меню"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"abstract":[{"type":"text","text":"Включает в себя содержимое меню и обработчики контроля над его жизненным циклом. На основе содержимого необходимо создать и показать на экране меню в любом виде."}],"title":"Menu","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}],"navigatorTitle":[{"text":"Menu","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","role":"symbol","url":"\/documentation\/ovkit\/menu"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"contents"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"contents"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","kind":"typeIdentifier","text":"OVKMenuContents"},{"kind":"text","text":" * "},{"text":"contents","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"contents","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1contents\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1contents\/fragments","value":[{"text":"contents","kind":"identifier"}],"op":"replace"},{"value":"OVKMenuContents","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/fragments","value":[{"kind":"identifier","text":"OVKMenuContents"}],"op":"replace"},{"value":"OVKMenu","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","op":"replace"},{"value":[{"text":"OVKMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments","op":"replace"}]}]}