{"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKMenu(py)onUpdate","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?"}],"symbolKind":"property","required":true,"navigatorTitle":[{"kind":"identifier","text":"onUpdate"}],"title":"onUpdate","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/onUpdate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Блок, который вызывается при обновлении меню. Вызов происходит с главного потока.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkmenu\/onupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkmenu\/onupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"VoidBlock","kind":"identifier"}],"title":"VoidBlock","navigatorTitle":[{"kind":"identifier","text":"VoidBlock"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/voidblock","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"kind":"symbol","abstract":[{"type":"text","text":"Включает в себя содержимое меню и обработчики контроля над его жизненным циклом. На основе содержимого необходимо создать и показать на экране меню в любом виде."}],"navigatorTitle":[{"text":"Menu","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}],"url":"\/documentation\/ovkit\/menu","type":"topic","title":"Menu","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenu/onUpdate":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUpdate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkmenu\/onupdate","title":"onUpdate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/onUpdate","required":true,"navigatorTitle":[{"kind":"identifier","text":"onUpdate"}],"abstract":[{"text":"Блок, который вызывается при обновлении меню. Вызов происходит с главного потока.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"onUpdate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"onUpdate"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"kind":"text","text":")();"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","value":"OVKMenu","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenu"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1onUpdate\/title","op":"replace","value":"onUpdate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1onUpdate\/fragments","value":[{"kind":"identifier","text":"onUpdate"}],"op":"replace"}]}]}