{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/style"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"style"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","text":"MenuStyle","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","required":true,"externalID":"c:@M@OVKit@objc(pl)OVKMenu(py)style","title":"style"},"abstract":[{"text":"Стиль пунктов меню, который наиболее подходит для отображения. Значение не изменяется при обновлении меню.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","text":"MenuStyle","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkmenu\/style"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmenu\/style"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Menu":{"kind":"symbol","title":"Menu","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","type":"topic","abstract":[{"type":"text","text":"Включает в себя содержимое меню и обработчики контроля над его жизненным циклом. На основе содержимого необходимо создать и показать на экране меню в любом виде."}],"url":"\/documentation\/ovkit\/menu","navigatorTitle":[{"text":"Menu","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MenuStyle","kind":"identifier"}],"url":"\/documentation\/ovkit\/menustyle","kind":"symbol","title":"MenuStyle","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenu/style":{"type":"topic","required":true,"title":"style","abstract":[{"text":"Стиль пунктов меню, который наиболее подходит для отображения. Значение не изменяется при обновлении меню.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenu\/style","kind":"symbol","url":"\/documentation\/ovkit\/ovkmenu\/style","navigatorTitle":[{"text":"style","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","kind":"typeIdentifier","text":"MenuStyle"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"style","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"style","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"OVKMenuStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","value":"OVKMenu"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments","value":[{"text":"OVKMenu","kind":"identifier"}]},{"op":"replace","value":"OVKMenuStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title"},{"value":[{"text":"OVKMenuStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1style\/title","value":"style","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenu~1style\/fragments","value":[{"kind":"identifier","text":"style"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}