{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"abstract":[{"text":"Имя для отображения в меню выбора","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/displayname"]},{"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/displayname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/displayName"},"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"role":"symbol","title":"displayName","externalID":"c:@M@OVKit@objc(cs)OVKSubtitlesOption(py)displayName"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKSubtitlesOption/displayName":{"type":"topic","url":"\/documentation\/ovkit\/ovksubtitlesoption\/displayname","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/displayName","role":"symbol","abstract":[{"type":"text","text":"Имя для отображения в меню выбора"}],"title":"displayName","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SubtitlesOption"}],"navigatorTitle":[{"text":"SubtitlesOption","kind":"identifier"}],"type":"topic","abstract":[{"text":"Дорожка субтитров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","title":"SubtitlesOption","url":"\/documentation\/ovkit\/subtitlesoption","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"displayName"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"displayName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"displayName"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"displayName","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1displayName\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1displayName\/fragments","op":"replace","value":[{"kind":"identifier","text":"displayName"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title","op":"replace","value":"OVKSubtitlesOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace"}]}]}