{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/isAuto"},"abstract":[{"type":"text","text":"Являются ли субтитры автосгенерированными"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAuto"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"isAuto","navigatorTitle":[{"text":"isAuto","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAuto"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKSubtitlesOption(py)isAuto","modules":[{"name":"OVKit"}],"symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/isauto"]},{"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/isauto"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SubtitlesOption","kind":"identifier"}],"abstract":[{"type":"text","text":"Дорожка субтитров."}],"title":"SubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}],"url":"\/documentation\/ovkit\/subtitlesoption","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKSubtitlesOption/isAuto":{"title":"isAuto","navigatorTitle":[{"kind":"identifier","text":"isAuto"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"isAuto","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/isAuto","abstract":[{"type":"text","text":"Являются ли субтитры автосгенерированными"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovksubtitlesoption\/isauto"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"isAuto","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isAuto","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuto"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"OVKSubtitlesOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}]},{"value":"isAuto","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1isAuto\/title"},{"op":"replace","value":[{"text":"isAuto","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1isAuto\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}