{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/languagecode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovksubtitlesoption\/languagecode"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKSubtitlesOption(py)languageCode","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"languageCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","symbolKind":"property","title":"languageCode","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"languageCode","kind":"identifier"}]},"abstract":[{"text":"Ключ локализации, используется для идентификации","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"languageCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/languageCode","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKSubtitlesOption/languageCode":{"title":"languageCode","navigatorTitle":[{"kind":"identifier","text":"languageCode"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"languageCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKSubtitlesOption\/languageCode","abstract":[{"type":"text","text":"Ключ локализации, используется для идентификации"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovksubtitlesoption\/languagecode"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SubtitlesOption","kind":"identifier"}],"abstract":[{"type":"text","text":"Дорожка субтитров."}],"title":"SubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}],"url":"\/documentation\/ovkit\/subtitlesoption","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"languageCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"languageCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"languageCode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"languageCode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1languageCode\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKSubtitlesOption~1languageCode\/fragments","value":[{"kind":"identifier","text":"languageCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title","value":"OVKSubtitlesOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","value":[{"kind":"identifier","text":"OVKSubtitlesOption"}]}]}]}