{"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoTrimInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"autoTrimInterval","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig(py)autoTrimInterval","title":"autoTrimInterval"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/autotriminterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/autotriminterval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/autoTrimInterval","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoTrimInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]}]}],"abstract":[{"text":"Интервал автоматической очистки. Значение по умолчанию - 900 (15 минут).","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/autoTrimInterval":{"type":"topic","title":"autoTrimInterval","role":"symbol","url":"\/documentation\/ovkit\/cachecontainerconfig\/autotriminterval","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/autoTrimInterval","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoTrimInterval"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoTrimInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"abstract":[{"text":"Интервал автоматической очистки. Значение по умолчанию - 900 (15 минут).","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}],"navigatorTitle":[{"text":"CacheContainerConfig","kind":"identifier"}],"type":"topic","title":"CacheContainerConfig","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/cachecontainerconfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"autoTrimInterval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoTrimInterval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autoTrimInterval","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1autoTrimInterval\/title","value":"autoTrimInterval"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1autoTrimInterval\/fragments","op":"replace","value":[{"text":"autoTrimInterval","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title","op":"replace","value":"OVKCacheContainerConfig"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle","op":"replace","value":[{"text":"OVKCacheContainerConfig","kind":"identifier"}]}]}]}