{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/costLimit"},"abstract":[{"text":"Максимальный размер кэша, после достижения которого он начнет удалять старые объекты. Значение по умолчанию - 314572800 (300 Mb).","type":"text"}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"costLimit"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig(py)costLimit","title":"costLimit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"costLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cachecontainerconfig\/costlimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cachecontainerconfig\/costlimit"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"costLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}],"navigatorTitle":[{"text":"CacheContainerConfig","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/cachecontainerconfig","kind":"symbol","title":"CacheContainerConfig"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/costLimit":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/costLimit","role":"symbol","abstract":[{"text":"Максимальный размер кэша, после достижения которого он начнет удалять старые объекты. Значение по умолчанию - 314572800 (300 Mb).","type":"text"}],"navigatorTitle":[{"text":"costLimit","kind":"identifier"}],"url":"\/documentation\/ovkit\/cachecontainerconfig\/costlimit","type":"topic","title":"costLimit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"costLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"costLimit","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"costLimit","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"costLimit","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title","value":"OVKCacheContainerConfig","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1costLimit\/title","op":"replace","value":"costLimit"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1costLimit\/fragments","op":"replace","value":[{"kind":"identifier","text":"costLimit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}