{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/defaultConfig()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfig","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CacheContainerConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig"}],"navigatorTitle":[{"text":"defaultConfig","kind":"identifier"}],"role":"symbol","title":"defaultConfig()","roleHeading":"Type Method","externalID":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig(cm)defaultConfig"},"variants":[{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/defaultconfig()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/defaultconfig()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfig","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CacheContainerConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/defaultConfig()":{"title":"defaultConfig()","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfig","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CacheContainerConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/cachecontainerconfig\/defaultconfig()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/defaultConfig()","role":"symbol","navigatorTitle":[{"text":"defaultConfig","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainerConfig"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheContainerConfig"}],"url":"\/documentation\/ovkit\/cachecontainerconfig","title":"CacheContainerConfig","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultConfig","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","text":"OVKCacheContainerConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1defaultConfig()\/title","value":"defaultConfig"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"defaultConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1defaultConfig()\/fragments"},{"op":"replace","value":"OVKCacheContainerConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}