{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAutoTrimInterval:costLimit:ageLimit:"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"autoTrimInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"costLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ageLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig(im)initWithAutoTrimInterval:costLimit:ageLimit:","roleHeading":"Initializer","modules":[{"name":"OVKit"}],"title":"init(autoTrimInterval:costLimit:ageLimit:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Инициализирует экземпляр класса "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"},{"type":"text","text":" с заданным настройками."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"autoTrimInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":" = 15 * 60, ","kind":"text"},{"text":"costLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" = 300 * 1024 * 1024, ","kind":"text"},{"text":"ageLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":" = 8 * 60)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Интервал автоматической очистки. Значение по умолчанию - 900 (15 минут).","type":"text"}],"type":"paragraph"}],"name":"autoTrimInterval"},{"content":[{"inlineContent":[{"type":"text","text":"Максимальный размер кэша, после достижения которого он начнет удалять старые объекты. Значение по умолчанию - 314572800 (300 Mb)."}],"type":"paragraph"}],"name":"costLimit"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Максимальное время жизни объектов в кэше. Значение по умолчанию - 314572800 (8 часов)."}]}],"name":"ageLimit"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/init(autotriminterval:costlimit:agelimit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cachecontainerconfig\/init(autotriminterval:costlimit:agelimit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/init(autoTrimInterval:costLimit:ageLimit:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/init(autoTrimInterval:costLimit:ageLimit:)":{"url":"\/documentation\/ovkit\/cachecontainerconfig\/init(autotriminterval:costlimit:agelimit:)","navigatorTitle":[{"text":"initWithAutoTrimInterval:costLimit:ageLimit:","kind":"identifier"}],"abstract":[{"type":"text","text":"Инициализирует экземпляр класса "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"},{"type":"text","text":" с заданным настройками."}],"role":"symbol","title":"init(autoTrimInterval:costLimit:ageLimit:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"autoTrimInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"costLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ageLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/init(autoTrimInterval:costLimit:ageLimit:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","role":"symbol","navigatorTitle":[{"text":"CacheContainerConfig","kind":"identifier"}],"title":"CacheContainerConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}],"url":"\/documentation\/ovkit\/cachecontainerconfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithAutoTrimInterval:costLimit:ageLimit:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoTrimInterval:costLimit:ageLimit:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAutoTrimInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoTrimInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"costLimit:"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"costLimit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ageLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"ageLimit","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Интервал автоматической очистки. Значение по умолчанию - 900 (15 минут).","type":"text"}]}],"name":"autoTrimInterval"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Максимальный размер кэша, после достижения которого он начнет удалять старые объекты. Значение по умолчанию - 314572800 (300 Mb)."}]}],"name":"costLimit"},{"content":[{"inlineContent":[{"text":"Максимальное время жизни объектов в кэше. Значение по умолчанию - 314572800 (8 часов).","type":"text"}],"type":"paragraph"}],"name":"ageLimit"}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1init(autoTrimInterval:costLimit:ageLimit:)\/title","op":"replace","value":"initWithAutoTrimInterval:costLimit:ageLimit:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1init(autoTrimInterval:costLimit:ageLimit:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoTrimInterval:costLimit:ageLimit:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title","op":"replace","value":"OVKCacheContainerConfig"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}]}]}]}