{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"withAutoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isActiveWhenAutoplayIsDisabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"withAutoplay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим работы кнопки в режиме по умолчанию, когда доступен "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":"."}]}]},{"name":"isActiveWhenAutoplayIsDisabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Должна ли кнопка иметь режим "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","isActive":true,"type":"reference"},{"type":"text","text":", когда "},{"inlineContent":[{"text":"Autoplay","type":"text"}],"type":"emphasis"},{"type":"text","text":" недоступен, иначе - "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init(withAutoplay:isActiveWhenAutoplayIsDisabled:)"},"metadata":{"symbolKind":"init","title":"init(withAutoplay:isActiveWhenAutoplayIsDisabled:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAutoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isActiveWhenAutoplayIsDisabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(im)initWithAutoplay:isActiveWhenAutoplayIsDisabled:","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"abstract":[{"text":"Создание поведения кнопки.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:isactivewhenautoplayisdisabled:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:isactivewhenautoplayisdisabled:)"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"type":"topic","title":"PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior/init(withAutoplay:isActiveWhenAutoplayIsDisabled:)":{"abstract":[{"type":"text","text":"Создание поведения кнопки."}],"type":"topic","title":"init(withAutoplay:isActiveWhenAutoplayIsDisabled:)","url":"\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:isactivewhenautoplayisdisabled:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAutoplay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","kind":"typeIdentifier","text":"PreviewPlayButtonMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isActiveWhenAutoplayIsDisabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init(withAutoplay:isActiveWhenAutoplayIsDisabled:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/active":{"abstract":[{"type":"text","text":"Кнопка видна и при ее нажатии плеер начинает проигрывание."}],"type":"topic","title":"PreviewPlayButtonMode.active","url":"\/documentation\/ovkit\/previewplaybuttonmode\/active","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeActive"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"abstract":[{"type":"text","text":"Поведение кнопки "},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"type":"topic","title":"PreviewPlayButtonBehavior","url":"\/documentation\/ovkit\/previewplaybuttonbehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/inactive":{"abstract":[{"type":"text","text":"Кнопка видна, но не реагирует на нажатия."}],"type":"topic","title":"PreviewPlayButtonMode.inactive","url":"\/documentation\/ovkit\/previewplaybuttonmode\/inactive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeInactive"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAutoplay:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","text":"OVKPreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"withAutoplay"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActiveWhenAutoplayIsDisabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isActiveWhenAutoplayIsDisabled"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"Режим работы кнопки в режиме по умолчанию, когда доступен ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Autoplay","type":"text"}]},{"text":".","type":"text"}],"type":"paragraph"}],"name":"withAutoplay"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Должна ли кнопка иметь режим ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","type":"reference","isActive":true},{"text":", когда ","type":"text"},{"inlineContent":[{"type":"text","text":"Autoplay"}],"type":"emphasis"},{"text":" недоступен, иначе - ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"isActiveWhenAutoplayIsDisabled"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init(withAutoplay:isActiveWhenAutoplayIsDisabled:)\/title","value":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init(withAutoplay:isActiveWhenAutoplayIsDisabled:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoplay:isActiveWhenAutoplayIsDisabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/title","value":"OVKPreviewPlayButtonModeActive"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/fragments","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeActive"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","value":"OVKPreviewPlayButtonBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}]},{"value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle","op":"replace"},{"op":"replace","value":"OVKPreviewPlayButtonModeInactive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1inactive\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeInactive"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1inactive\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}