{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init(withAutoplay:withoutAutoplay:)"},"abstract":[{"type":"text","text":"Создание поведения кнопки."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"withAutoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withoutAutoplay"},{"text":": ","kind":"text"},{"text":"PreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"withAutoplay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим работы кнопки в режиме по умолчанию, когда доступен "},{"inlineContent":[{"type":"text","text":"Autoplay"}],"type":"emphasis"},{"type":"text","text":"."}]}]},{"name":"withoutAutoplay","content":[{"inlineContent":[{"text":"Режим работы кнопки, когда ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":" недоступен."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:withoutautoplay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:withoutautoplay:)"]}],"metadata":{"symbolKind":"init","role":"symbol","title":"init(withAutoplay:withoutAutoplay:)","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithAutoplay:withoutAutoplay:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(im)initWithAutoplay:withoutAutoplay:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"withAutoplay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withoutAutoplay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior/init(withAutoplay:withoutAutoplay:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAutoplay:withoutAutoplay:"}],"title":"init(withAutoplay:withoutAutoplay:)","kind":"symbol","abstract":[{"type":"text","text":"Создание поведения кнопки."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init(withAutoplay:withoutAutoplay:)","url":"\/documentation\/ovkit\/previewplaybuttonbehavior\/init(withautoplay:withoutautoplay:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAutoplay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withoutAutoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"navigatorTitle":[{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","abstract":[{"text":"Поведение кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Play"}]},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"title":"PreviewPlayButtonBehavior","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/previewplaybuttonbehavior"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"role":"symbol","navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}],"title":"PreviewPlayButtonMode","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}],"kind":"symbol","abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithAutoplay:withoutAutoplay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAutoplay:withoutAutoplay:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAutoplay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","text":"OVKPreviewPlayButtonMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"withAutoplay"},{"text":" ","kind":"text"},{"text":"withoutAutoplay:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"typeIdentifier","text":"OVKPreviewPlayButtonMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"withoutAutoplay"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"withAutoplay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим работы кнопки в режиме по умолчанию, когда доступен "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим работы кнопки, когда "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"text":" недоступен.","type":"text"}]}],"name":"withoutAutoplay"}],"kind":"parameters"},"op":"replace"},{"value":"initWithAutoplay:withoutAutoplay:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init(withAutoplay:withoutAutoplay:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init(withAutoplay:withoutAutoplay:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAutoplay:withoutAutoplay:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","value":"OVKPreviewPlayButtonBehavior"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}]},{"op":"replace","value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}