{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(im)init","modules":[{"name":"OVKit"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"init","title":"init()","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Поведение по умолчанию, когда кнопка видна и активна при любых условиях (режим "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","isActive":true},{"type":"text","text":")."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/init()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init()"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/active":{"type":"topic","abstract":[{"type":"text","text":"Кнопка видна и при ее нажатии плеер начинает проигрывание."}],"kind":"symbol","url":"\/documentation\/ovkit\/previewplaybuttonmode\/active","navigatorTitle":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}],"title":"PreviewPlayButtonMode.active","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"abstract":[{"text":"Поведение кнопки ","type":"text"},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"url":"\/documentation\/ovkit\/previewplaybuttonbehavior","title":"PreviewPlayButtonBehavior","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonBehavior"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior/init()":{"url":"\/documentation\/ovkit\/previewplaybuttonbehavior\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Поведение по умолчанию, когда кнопка видна и активна при любых условиях (режим ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active"},{"text":").","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/init()","kind":"symbol","title":"init()","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/title","value":"OVKPreviewPlayButtonModeActive"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/fragments","value":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","value":"OVKPreviewPlayButtonBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}]}]}