{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"withAutoplay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/withautoplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/withautoplay"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Режим работы кнопки при доступном ","type":"text"},{"inlineContent":[{"text":"Autoplay","type":"text"}],"type":"emphasis"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/withAutoplay","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"withAutoplay","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withAutoplay"}],"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(py)withAutoplay"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"title":"PreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Поведение кнопки ","type":"text"},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"type":"topic","url":"\/documentation\/ovkit\/previewplaybuttonbehavior"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior/withAutoplay":{"kind":"symbol","abstract":[{"type":"text","text":"Режим работы кнопки при доступном "},{"inlineContent":[{"type":"text","text":"Autoplay"}],"type":"emphasis"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/withAutoplay","navigatorTitle":[{"text":"withAutoplay","kind":"identifier"}],"title":"withAutoplay","role":"symbol","url":"\/documentation\/ovkit\/previewplaybuttonbehavior\/withautoplay","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"title":"PreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Режим работы кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/previewplaybuttonmode"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"withAutoplay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"withAutoplay","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","text":"OVKPreviewPlayButtonMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAutoplay"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPreviewPlayButtonBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1withAutoplay\/title","op":"replace","value":"withAutoplay"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1withAutoplay\/fragments","value":[{"kind":"identifier","text":"withAutoplay"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","value":"OVKPreviewPlayButtonMode","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}