{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/withoutAutoplay","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"kind":"symbol","metadata":{"title":"withoutAutoplay","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withoutAutoplay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"withoutAutoplay"}],"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(py)withoutAutoplay"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withoutAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"}]}]}],"abstract":[{"type":"text","text":"Режим работы кнопки при недоступном "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/withoutautoplay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/previewplaybuttonbehavior\/withoutautoplay"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"title":"PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"kind":"symbol","abstract":[{"type":"text","text":"Режим работы кнопки "},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior/withoutAutoplay":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior\/withoutAutoplay","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"withoutAutoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode"}],"title":"withoutAutoplay","type":"topic","url":"\/documentation\/ovkit\/previewplaybuttonbehavior\/withoutautoplay","kind":"symbol","abstract":[{"type":"text","text":"Режим работы кнопки при недоступном "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withoutAutoplay"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"title":"PreviewPlayButtonBehavior","url":"\/documentation\/ovkit\/previewplaybuttonbehavior","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"kind":"symbol","abstract":[{"text":"Поведение кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"withoutAutoplay","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"withoutAutoplay"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","kind":"typeIdentifier","text":"OVKPreviewPlayButtonMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"withoutAutoplay"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle","op":"replace"},{"value":"withoutAutoplay","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1withoutAutoplay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"withoutAutoplay"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior~1withoutAutoplay\/fragments","op":"replace"},{"value":"OVKPreviewPlayButtonBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle","op":"replace"}]}]}