{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetpostviewdata\/ovkit_backgroundimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetpostviewdata\/ovkit_backgroundimage"]}],"abstract":[{"text":"Данные для фонового изображения.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/ovkit_backgroundImage"},"metadata":{"navigatorTitle":[{"text":"ovkit_backgroundImage","kind":"identifier"}],"role":"symbol","symbolKind":"property","required":true,"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_backgroundImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData","text":"MyTargetImageData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetPostViewData(py)ovkit_backgroundImage","title":"ovkit_backgroundImage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_backgroundImage","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData","text":"MyTargetImageData","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"url":"\/documentation\/ovkit\/mytargetpostviewdata","navigatorTitle":[{"kind":"identifier","text":"MyTargetPostViewData"}],"abstract":[{"text":"Данные, которые необходимы для отображения поствью после баннера.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","title":"MyTargetPostViewData","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/ovkit_backgroundImage":{"url":"\/documentation\/ovkit\/mytargetpostviewdata\/ovkit_backgroundimage","role":"symbol","abstract":[{"text":"Данные для фонового изображения.","type":"text"}],"title":"ovkit_backgroundImage","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/ovkit_backgroundImage","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_backgroundImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetImageData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ovkit_backgroundImage"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData":{"abstract":[{"text":"Графические данные.","type":"text"}],"url":"\/documentation\/ovkit\/mytargetimagedata","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetImageData"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetImageData"}],"title":"MyTargetImageData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"ovkit_backgroundImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ovkit_backgroundImage","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetImageData","kind":"typeIdentifier","text":"id<MyTargetImageData>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_backgroundImage"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/title","op":"replace","value":"MyTargetPostViewData"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/navigatorTitle","op":"replace","value":[{"text":"MyTargetPostViewData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1ovkit_backgroundImage\/title","op":"replace","value":"ovkit_backgroundImage"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1ovkit_backgroundImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"ovkit_backgroundImage"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/title","op":"replace","value":"MyTargetImageData"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetImageData"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/navigatorTitle","op":"replace","value":[{"text":"MyTargetImageData","kind":"identifier"}]}]}]}