{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/text","interfaceLanguage":"swift"},"abstract":[{"text":"Заголовок.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetpostviewdata\/text"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetpostviewdata\/text"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"text","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"symbolKind":"property","required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetPostViewData(py)text","title":"text"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"title":"MyTargetPostViewData","type":"topic","url":"\/documentation\/ovkit\/mytargetpostviewdata","kind":"symbol","abstract":[{"text":"Данные, которые необходимы для отображения поствью после баннера.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MyTargetPostViewData","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/text":{"title":"text","url":"\/documentation\/ovkit\/mytargetpostviewdata\/text","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/text","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Заголовок.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"text","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"text"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"text"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MyTargetPostViewData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/navigatorTitle"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1text\/title"},{"op":"replace","value":[{"kind":"identifier","text":"text"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1text\/fragments"}]}]}