{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdsItemBadge\/initWithCoder:"},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKAdsItemBadge(im)initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkadsitembadge\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKAdsItemBadge/initWithCoder:":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdsItemBadge\/initWithCoder:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/ovkadsitembadge\/initwithcoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","title":"AdsItemBadge","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}],"url":"\/documentation\/ovkit\/adsitembadge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdsItemBadge","kind":"identifier"}],"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"OVKAdsItemBadge"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"text":"OVKAdsItemBadge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","value":[{"text":"OVKAdsItemBadge","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}