{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkadsitembadge\/initwithframe:"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKAdsItemBadge(im)initWithFrame:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"role":"symbol","title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdsItemBadge\/initWithFrame:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdsItemBadge/initWithFrame:":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdsItemBadge\/initWithFrame:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkadsitembadge\/initwithframe:","type":"topic","title":"initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"url":"\/documentation\/ovkit\/adsitembadge","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","title":"AdsItemBadge","navigatorTitle":[{"kind":"identifier","text":"AdsItemBadge"}],"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdsItemBadge"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"OVKAdsItemBadge","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"text":"OVKAdsItemBadge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","value":[{"text":"OVKAdsItemBadge","kind":"identifier"}],"op":"replace"}]}]}