{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/animatetodestination()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/animatetodestination()"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/animateToDestination()","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"animateToDestination","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"animateToDestination()","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateToDestination","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition(im)animateToDestination"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"]]},"abstract":[{"text":"Перемещает плеер в место назначения с анимацией.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateToDestination","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Необходимо вызвать в блоке анимации.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewAnimatedTransition","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewanimatedtransition","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","abstract":[{"type":"text","text":"Выполняет анимированный перенос плеера между двумя "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"PlayerViewAnimatedTransition","type":"topic","navigatorTitle":[{"text":"PlayerViewAnimatedTransition","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition/animateToDestination()":{"navigatorTitle":[{"text":"animateToDestination","kind":"identifier"}],"title":"animateToDestination()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/animateToDestination()","role":"symbol","url":"\/documentation\/ovkit\/playerviewanimatedtransition\/animatetodestination()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateToDestination","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Перемещает плеер в место назначения с анимацией.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"animateToDestination","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateToDestination","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"animateToDestination"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/title","value":"OVKPlayerViewAnimatedTransition","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/fragments","value":[{"text":"OVKPlayerViewAnimatedTransition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/navigatorTitle","value":[{"text":"OVKPlayerViewAnimatedTransition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1animateToDestination()\/title","value":"animateToDestination","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1animateToDestination()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateToDestination","kind":"identifier"}],"op":"replace"}]}]}