{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"finishWithCompleted:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition(im)finishWithCompleted:","title":"finish(completed:)","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Завершился ли перенос. Если ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", плеер будет перемещен в ","type":"text"},{"code":"destination","type":"codeVoice"},{"text":", иначе он возвратится обратно в ","type":"text"},{"code":"source","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"completed"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Необходимо вызвать в ","type":"text"},{"code":"completion","type":"codeVoice"},{"text":" анимации.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/finish(completed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/finish(completed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/finish(completed:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Завершение переноса."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition":{"title":"PlayerViewAnimatedTransition","navigatorTitle":[{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"type":"topic","abstract":[{"type":"text","text":"Выполняет анимированный перенос плеера между двумя "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/playerviewanimatedtransition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition/finish(completed:)":{"url":"\/documentation\/ovkit\/playerviewanimatedtransition\/finish(completed:)","navigatorTitle":[{"kind":"identifier","text":"finishWithCompleted:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/finish(completed:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finish","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"finish(completed:)","abstract":[{"text":"Завершение переноса.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"finishWithCompleted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishWithCompleted:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"finishWithCompleted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completed"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"completed","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Завершился ли перенос. Если "},{"type":"codeVoice","code":"true"},{"type":"text","text":", плеер будет перемещен в "},{"type":"codeVoice","code":"destination"},{"type":"text","text":", иначе он возвратится обратно в "},{"type":"codeVoice","code":"source"},{"type":"text","text":"."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/title","value":"OVKPlayerViewAnimatedTransition"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1finish(completed:)\/title","value":"finishWithCompleted:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1finish(completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishWithCompleted:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}