{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Необходимо вызвать до начала анимации и когда ","type":"text"},{"code":"frame","type":"codeVoice"},{"text":" обоих ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":" являются корректными."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Подготовка к переносу."}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition(im)prepare","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"OVKit"}],"title":"prepare()","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"prepare"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/prepare()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/prepare()"]},{"paths":["\/documentation\/ovkit\/playerviewanimatedtransition\/prepare()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerViewAnimatedTransition","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Выполняет анимированный перенос плеера между двумя ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","title":"PlayerViewAnimatedTransition","url":"\/documentation\/ovkit\/playerviewanimatedtransition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerViewAnimatedTransition"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition/prepare()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepare"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Подготовка к переносу.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/prepare()","title":"prepare()","url":"\/documentation\/ovkit\/playerviewanimatedtransition\/prepare()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepare"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"prepare","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"prepare","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"OVKPlayerViewAnimatedTransition","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1prepare()\/title","value":"prepare","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prepare"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1prepare()\/fragments"}]}]}