{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"modules":[{"name":"OVKit"}],"symbolKind":"method","navigatorTitle":[{"text":"bufferStarvation","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)bufferStarvation","roleHeading":"Instance Method","role":"symbol","title":"bufferStarvation()"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/bufferstarvation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/bufferstarvation()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/bufferStarvation()"},"abstract":[{"text":"В буфере закончились данные, произошел stall.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","title":"ModernVideoStatsHandler","role":"symbol","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/bufferStarvation()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/bufferStarvation()","required":true,"kind":"symbol","type":"topic","navigatorTitle":[{"text":"bufferStarvation","kind":"identifier"}],"title":"bufferStarvation()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"В буфере закончились данные, произошел stall.","type":"text"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/bufferstarvation()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bufferStarvation","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bufferStarvation"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKModernVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1bufferStarvation()\/title","op":"replace","value":"bufferStarvation"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1bufferStarvation()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}