{"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/downloadbytes(bytes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/downloadbytes(bytes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadBytes"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Сколько байт было загружено с сервера."}],"type":"paragraph"}],"name":"bytes"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Ситуации, когда метод вызовется:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Видео доиграло до конца;"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер получает новый объект "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference","isActive":true},{"type":"text","text":";"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Освобождается из памяти."}]}]}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/downloadBytes(bytes:)"},"metadata":{"modules":[{"name":"OVKit"}],"title":"downloadBytes(bytes:)","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)downloadBytesWithBytes:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadBytes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"downloadBytesWithBytes:"}],"symbolKind":"method","required":true},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"abstract":[{"text":"Событие скачивания определенного количества байт плеером с сервера.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true,"type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"Video","url":"\/documentation\/ovkit\/video","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/downloadBytes(bytes:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/downloadBytes(bytes:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadBytes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"abstract":[{"type":"text","text":"Событие скачивания определенного количества байт плеером с сервера."}],"title":"downloadBytes(bytes:)","type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/downloadbytes(bytes:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"downloadBytesWithBytes:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"kind":"symbol","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"downloadBytesWithBytes:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"downloadBytesWithBytes:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"downloadBytesWithBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bytes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"bytes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Сколько байт было загружено с сервера."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1downloadBytes(bytes:)\/title","value":"downloadBytesWithBytes:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1downloadBytes(bytes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downloadBytesWithBytes:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}