{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"required":true,"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"manifestRequestWithConnectionDetails:"}],"title":"manifestRequest(connectionDetails:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)manifestRequestWithConnectionDetails:"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"abstract":[{"text":"Сетевой клиент отправил запрос за mpd\/m3u8 манифестом.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestrequest(connectiondetails:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestrequest(connectiondetails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestRequest(connectionDetails:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}]}],"name":"connectionDetails"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Отправляется один раз за сессию непрерывного воспроизведения. Это значит, что после перемотки, ошибки, рестарта проигрывания, и т.п. событие вновь может быть отправлено. При запросе index-манифестов не отправляется."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"title":"NetworkConnectionInfo","url":"\/documentation\/ovkit\/networkconnectioninfo","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionInfo"}],"navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Набор параметров с информацией о сетевом соединении."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestRequest(connectionDetails:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestRequest(connectionDetails:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manifestRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"title":"manifestRequest(connectionDetails:)","type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestrequest(connectiondetails:)","kind":"symbol","abstract":[{"text":"Сетевой клиент отправил запрос за mpd\/m3u8 манифестом.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"manifestRequestWithConnectionDetails:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"reference"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"manifestRequestWithConnectionDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"manifestRequestWithConnectionDetails:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"manifestRequestWithConnectionDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKNetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"connectionDetails","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}],"type":"paragraph"}],"name":"connectionDetails"}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","value":"OVKNetworkConnectionInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestRequest(connectionDetails:)\/title","value":"manifestRequestWithConnectionDetails:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestRequest(connectionDetails:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"manifestRequestWithConnectionDetails:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]}]}]}