{"kind":"symbol","abstract":[{"type":"text","text":"Получен манифест."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manifestReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Информация о текущем соединении с сервером.","type":"text"}]}],"name":"connectionDetails"}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Отправляется один раз за сессию непрерывного воспроизведения. Это значит, что после перемотки, ошибки, рестарта проигрывания, и т.п. событие вновь может быть отправлено.","type":"text"}]}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestreceived(connectiondetails:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestreceived(connectiondetails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestReceived(connectionDetails:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"required":true,"symbolKind":"method","navigatorTitle":[{"text":"manifestReceivedWithConnectionDetails:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"manifestReceived(connectionDetails:)","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)manifestReceivedWithConnectionDetails:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manifestReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","role":"symbol","abstract":[{"type":"text","text":"Набор параметров с информацией о сетевом соединении."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}],"kind":"symbol","title":"NetworkConnectionInfo","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}],"type":"topic","url":"\/documentation\/ovkit\/networkconnectioninfo"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestReceived(connectionDetails:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestReceived(connectionDetails:)","role":"symbol","abstract":[{"type":"text","text":"Получен манифест."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier","text":"NetworkConnectionInfo"},{"kind":"text","text":")"}],"kind":"symbol","title":"manifestReceived(connectionDetails:)","navigatorTitle":[{"kind":"identifier","text":"manifestReceivedWithConnectionDetails:"}],"type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestreceived(connectiondetails:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/modernvideostatshandler","title":"ModernVideoStatsHandler","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"manifestReceivedWithConnectionDetails:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"manifestReceivedWithConnectionDetails:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"manifestReceivedWithConnectionDetails:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","text":"OVKNetworkConnectionInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionDetails"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"connectionDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Информация о текущем соединении с сервером."}]}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","op":"replace","value":"OVKNetworkConnectionInfo"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","op":"replace"},{"value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"manifestReceivedWithConnectionDetails:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestReceived(connectionDetails:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"manifestReceivedWithConnectionDetails:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestReceived(connectionDetails:)\/fragments","op":"replace"},{"value":"OVKModernVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}