{"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)manifestFirstByteWithConnectionDetails:","title":"manifestFirstByte(connectionDetails:)","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"manifestFirstByteWithConnectionDetails:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manifestFirstByte","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol"},"abstract":[{"type":"text","text":"Получен первый байт манифеста (при его наличии)."}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestfirstbyte(connectiondetails:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/manifestfirstbyte(connectiondetails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestFirstByte"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"connectionDetails","content":[{"type":"paragraph","inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Отправляется один раз за сессию непрерывного воспроизведения. Это значит, что после перемотки, ошибки, рестарта проигрывания, и т.п. событие вновь может быть отправлено."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestFirstByte(connectionDetails:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":"."}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestFirstByte(connectionDetails:)":{"title":"manifestFirstByte(connectionDetails:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestFirstByte"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"manifestFirstByteWithConnectionDetails:","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestFirstByte(connectionDetails:)","abstract":[{"type":"text","text":"Получен первый байт манифеста (при его наличии)."}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestfirstbyte(connectiondetails:)","type":"topic","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"title":"NetworkConnectionInfo","navigatorTitle":[{"text":"NetworkConnectionInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"url":"\/documentation\/ovkit\/networkconnectioninfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"manifestFirstByteWithConnectionDetails:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"manifestFirstByteWithConnectionDetails:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"manifestFirstByteWithConnectionDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKNetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionDetails"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"name":"connectionDetails","content":[{"type":"paragraph","inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace","value":"OVKModernVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestFirstByte(connectionDetails:)\/title","value":"manifestFirstByteWithConnectionDetails:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestFirstByte(connectionDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"manifestFirstByteWithConnectionDetails:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","op":"replace","value":"OVKNetworkConnectionInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"}]}]}