{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)mediaFirstByteWithConnectionDetails:","title":"mediaFirstByte(connectionDetails:)","modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaFirstByte","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mediaFirstByteWithConnectionDetails:","kind":"identifier"}],"required":true},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/mediafirstbyte(connectiondetails:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/mediafirstbyte(connectiondetails:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaFirstByte(connectionDetails:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaFirstByte"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}],"type":"paragraph"}],"name":"connectionDetails"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Отправляется один раз за сессию непрерывного воспроизведения. Это значит, что после перемотки, ошибки, рестарта проигрывания, и т.п. событие вновь может быть отправлено."}]}]}],"abstract":[{"type":"text","text":"Получен первый байт медиаданных (файл или медиа-дорожка)."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"NetworkConnectionInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","title":"NetworkConnectionInfo","abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"url":"\/documentation\/ovkit\/networkconnectioninfo"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","title":"ModernVideoStatsHandler","role":"symbol","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/mediaFirstByte(connectionDetails:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaFirstByte","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Получен первый байт медиаданных (файл или медиа-дорожка).","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaFirstByte(connectionDetails:)","navigatorTitle":[{"text":"mediaFirstByteWithConnectionDetails:","kind":"identifier"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/mediafirstbyte(connectiondetails:)","required":true,"title":"mediaFirstByte(connectionDetails:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mediaFirstByteWithConnectionDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaFirstByteWithConnectionDetails:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"mediaFirstByteWithConnectionDetails:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"OVKNetworkConnectionInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionDetails"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}],"type":"paragraph"}],"name":"connectionDetails"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","value":"OVKNetworkConnectionInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaFirstByte(connectionDetails:)\/title","value":"mediaFirstByteWithConnectionDetails:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaFirstByte(connectionDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaFirstByteWithConnectionDetails:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}