{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Клиент отправил первый запрос за медиаданными (файл или медиа-дорожка)."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier","text":"NetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"connectionDetails","content":[{"type":"paragraph","inlineContent":[{"text":"Информация о текущем содединении с сервером.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Отправляется один раз за сессию непрерывного воспроизведения. Это значит, что после перемотки, ошибки, рестарта проигрывания, и т.п. событие вновь может быть отправлено.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/mediarequest(connectiondetails:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/mediarequest(connectiondetails:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"mediaRequest(connectionDetails:)","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)mediaRequestWithConnectionDetails:","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"mediaRequestWithConnectionDetails:","kind":"identifier"}],"required":true,"symbolKind":"method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaRequest(connectionDetails:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/mediaRequest(connectionDetails:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaRequest(connectionDetails:)","abstract":[{"text":"Клиент отправил первый запрос за медиаданными (файл или медиа-дорожка).","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mediaRequestWithConnectionDetails:","kind":"identifier"}],"title":"mediaRequest(connectionDetails:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/mediarequest(connectiondetails:)","type":"topic","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","title":"VideoStatsHandler","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}],"title":"NetworkConnectionInfo","kind":"symbol","role":"symbol","abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionInfo"}],"url":"\/documentation\/ovkit\/networkconnectioninfo"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","kind":"symbol","type":"topic","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"reference"},{"text":".","type":"text"}],"role":"symbol","title":"ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"mediaRequestWithConnectionDetails:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mediaRequestWithConnectionDetails:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"mediaRequestWithConnectionDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKNetworkConnectionInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionDetails"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"connectionDetails","content":[{"inlineContent":[{"type":"text","text":"Информация о текущем содединении с сервером."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaRequest(connectionDetails:)\/title","value":"mediaRequestWithConnectionDetails:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaRequest(connectionDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaRequestWithConnectionDetails:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","op":"replace","value":"OVKNetworkConnectionInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle"},{"value":"OVKModernVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"}]}]}