{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"modeChange","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Режимами воспроизведения считается полноэкранный, Picture in Picture (внешний и внутренний), стриминг на внешнее устройство (AirPlay\/Chromecast)."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/modeChange()"},"abstract":[{"type":"text","text":"Изменился режим воспроизведения."}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/modechange()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/modechange()"]}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)modeChange","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modeChange"},{"text":"()","kind":"text"}],"symbolKind":"method","title":"modeChange()","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modeChange"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"reference"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/modeChange()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/modeChange()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"modeChange","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"title":"modeChange()","url":"\/documentation\/ovkit\/modernvideostatshandler\/modechange()","type":"topic","kind":"symbol","abstract":[{"text":"Изменился режим воспроизведения.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modeChange"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"modeChange"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"modeChange","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"modeChange","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace","value":"OVKModernVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1modeChange()\/title","op":"replace","value":"modeChange"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1modeChange()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"modeChange","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace","value":"OVKVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}