{"kind":"symbol","abstract":[{"type":"text","text":"Пользователь нажал на паузу в плеере."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/pause(currenttime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/pause(currenttime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Текущее время плеера в секундах (округлено до целых).","type":"text"}],"type":"paragraph"}],"name":"currentTime"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Live нельзя ставить на паузу, поэтому для трансляций событие приходить не будет."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/pause(currentTime:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"pauseWithCurrentTime:","kind":"identifier"}],"title":"pause(currentTime:)","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)pauseWithCurrentTime:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":"."}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/pause(currentTime:)":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/pause(currenttime:)","role":"symbol","required":true,"type":"topic","navigatorTitle":[{"text":"pauseWithCurrentTime:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"currentTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[{"text":"Пользователь нажал на паузу в плеере.","type":"text"}],"title":"pause(currentTime:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/pause(currentTime:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"pauseWithCurrentTime:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pauseWithCurrentTime:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pauseWithCurrentTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"currentTime","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Текущее время плеера в секундах (округлено до целых)."}],"type":"paragraph"}],"name":"currentTime"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"OVKModernVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"},{"op":"replace","value":"pauseWithCurrentTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1pause(currentTime:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseWithCurrentTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1pause(currentTime:)\/fragments"},{"op":"replace","value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}