{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackError(_:type:on:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Произошла ошибка воспроизведения."}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/playbackerror(_:type:on:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/playbackerror(_:type:on:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","preciseIdentifier":"c:@M@OVKit@E@OVKErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rawFileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Ошибка воспроизведения. В ","type":"text"},{"type":"codeVoice","code":"userInfo"},{"text":" может быть дополнительная информация по ключам.","type":"text"}]}],"name":"error"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Уровень серьезности ошибки.","type":"text"}]}],"name":"type"},{"content":[{"inlineContent":[{"type":"text","text":"Тип файла, на котором произошла ошибка. Значением является "},{"type":"codeVoice","code":"rawValue"},{"text":" от ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"type":"text","text":". "},{"type":"codeVoice","code":"nil"},{"text":" означает, что в плеере не установлен ресурс.","type":"text"}],"type":"paragraph"}],"name":"rawFileFormat"}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)playbackError:type:on:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKErrorType"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"playbackError:type:on:","kind":"identifier"}],"required":true,"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","title":"playbackError(_:type:on:)"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/playbackError(_:type:on:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackError(_:type:on:)","required":true,"url":"\/documentation\/ovkit\/modernvideostatshandler\/playbackerror(_:type:on:)","title":"playbackError(_:type:on:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"playbackError:type:on:","kind":"identifier"}],"abstract":[{"text":"Произошла ошибка воспроизведения.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","role":"symbol","type":"topic","title":"ModernVideoStatsHandler","kind":"symbol","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"type":"topic","url":"\/documentation\/ovkit\/videofileformat","title":"VideoFileFormat","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","abstract":[{"type":"text","text":"Тип ошибки, определяющий ее важность."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/errortype","title":"ErrorType","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"playbackError:type:on:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playbackError:type:on:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"playbackError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@OVKErrorType","text":"OVKErrorType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"on:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rawFileFormat","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Ошибка воспроизведения. В "},{"type":"codeVoice","code":"userInfo"},{"text":" может быть дополнительная информация по ключам.","type":"text"}],"type":"paragraph"}],"name":"error"},{"content":[{"inlineContent":[{"text":"Уровень серьезности ошибки.","type":"text"}],"type":"paragraph"}],"name":"type"},{"content":[{"inlineContent":[{"type":"text","text":"Тип файла, на котором произошла ошибка. Значением является "},{"code":"rawValue","type":"codeVoice"},{"type":"text","text":" от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","isActive":true,"type":"reference"},{"type":"text","text":". "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что в плеере не установлен ресурс."}],"type":"paragraph"}],"name":"rawFileFormat"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"playbackError:type:on:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackError(_:type:on:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playbackError:type:on:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackError(_:type:on:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace","value":"OVKModernVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","op":"replace","value":"OVKErrorType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","value":[{"kind":"identifier","text":"OVKErrorType"}]},{"value":[{"kind":"identifier","text":"OVKErrorType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","op":"replace"}]}]}