{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/progressChanged(time:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"title":"progressChanged(time:)","navigatorTitle":[{"text":"progressChangedWithTime:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)progressChangedWithTime:","role":"symbol","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"abstract":[{"type":"text","text":"Текущее время проигрывания изменилось."}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/progresschanged(time:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/progresschanged(time:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущее время плеера."}]}]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Обновляется не чаще, чем раз в секунду."}]},{"style":"warning","type":"aside","content":[{"inlineContent":[{"text":"Можно использовать только для статистики. Для обслуживания бизнес-логики вокруг плеера существует механизм ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Warning"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/progressChanged(time:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/progressChanged(time:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/progresschanged(time:)","title":"progressChanged(time:)","kind":"symbol","navigatorTitle":[{"text":"progressChangedWithTime:","kind":"identifier"}],"abstract":[{"text":"Текущее время проигрывания изменилось.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addPeriodicTimeObserver(forInterval:using:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","role":"symbol","abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"navigatorTitle":[{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)","type":"topic","title":"addPeriodicTimeObserver(forInterval:using:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","role":"symbol","type":"topic","title":"ModernVideoStatsHandler","kind":"symbol","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"progressChangedWithTime:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"progressChangedWithTime:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"progressChangedWithTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"time"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"time","content":[{"inlineContent":[{"text":"Текущее время плеера.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"progressChangedWithTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1progressChanged(time:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1progressChanged(time:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/title","value":"addPeriodicTimeObserverForInterval:using:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}