{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)reachedEnd","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reachedEnd","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reachedEnd","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","title":"reachedEnd()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reachedEnd"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Будет вызван до ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)"},{"type":"text","text":"."}]}],"kind":"content"}],"abstract":[{"text":"Видео было досмотрено до конца.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/reachedEnd()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/reachedend()"]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/reachedend()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","kind":"symbol","title":"VideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler","navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"title":"ModernVideoStatsHandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/stop(currentTime:stallTime:)":{"kind":"symbol","title":"stop(currentTime:stallTime:)","type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/stop(currenttime:stalltime:)","abstract":[{"type":"text","text":"Видео закончили смотреть."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stallTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/reachedEnd()":{"role":"symbol","abstract":[{"type":"text","text":"Видео было досмотрено до конца."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reachedEnd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"reachedEnd"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/reachedEnd()","url":"\/documentation\/ovkit\/modernvideostatshandler\/reachedend()","kind":"symbol","title":"reachedEnd()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"reachedEnd","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"reachedEnd","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reachedEnd","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace","value":"OVKVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace","value":"OVKModernVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/title","op":"replace","value":"stopWithCurrentTime:stallTime:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1reachedEnd()\/title","op":"replace","value":"reachedEnd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1reachedEnd()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reachedEnd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}