{"abstract":[{"type":"text","text":"Пользователь начал перемотку перемещением таймлайна, что привело к приостановке воспроизведения."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekStarted()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekStarted","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"seekStarted","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)seekStarted","required":true,"title":"seekStarted()"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekStarted","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"После совершения перемотки будет вызван метод "},{"type":"codeVoice","code":"seek(method:)"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/seekstarted()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/seekstarted()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","title":"ModernVideoStatsHandler","role":"symbol","abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/seekStarted()":{"title":"seekStarted()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekStarted()","url":"\/documentation\/ovkit\/modernvideostatshandler\/seekstarted()","role":"symbol","navigatorTitle":[{"text":"seekStarted","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Пользователь начал перемотку перемещением таймлайна, что привело к приостановке воспроизведения."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekStarted","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"seekStarted","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekStarted"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"seekStarted","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"OVKModernVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"},{"value":"seekStarted","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekStarted()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"seekStarted","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekStarted()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}