{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stallTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)stopWithCurrentTime:stallTime:","roleHeading":"Instance Method","title":"stop(currentTime:stallTime:)","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Видео закончили смотреть.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"stallTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"currentTime","content":[{"inlineContent":[{"text":"Текущее время плеера в секундах (округлено до целых). Для трансляции 0.","type":"text"}],"type":"paragraph"}]},{"name":"stallTime","content":[{"inlineContent":[{"text":"Если плеер был остановлен во время буфферизации — время в миллисекундах, иначе 0.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Ситуации, когда метод вызовется:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео доиграло до конца;"}]}]},{"content":[{"inlineContent":[{"text":"Плеер получает новый объект ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":";"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Освобождается из памяти."}]}]}]}],"kind":"content"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/stop(currenttime:stalltime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/stop(currenttime:stalltime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype","kind":"symbol","role":"symbol","title":"VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/ovkit\/video","kind":"symbol","title":"Video"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"url":"\/documentation\/ovkit\/modernvideostatshandler","role":"symbol","type":"topic","title":"ModernVideoStatsHandler","kind":"symbol","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/stop(currentTime:stallTime:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stallTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","abstract":[{"text":"Видео закончили смотреть.","type":"text"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/stop(currenttime:stalltime:)","kind":"symbol","title":"stop(currentTime:stallTime:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopWithCurrentTime:stallTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopWithCurrentTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"currentTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"stallTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stallTime","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Текущее время плеера в секундах (округлено до целых). Для трансляции 0."}],"type":"paragraph"}],"name":"currentTime"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Если плеер был остановлен во время буфферизации — время в миллисекундах, иначе 0.","type":"text"}]}],"name":"stallTime"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"},{"op":"replace","value":"stopWithCurrentTime:stallTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/fragments"},{"op":"replace","value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"}]}]}