{"kind":"symbol","abstract":[{"type":"text","text":"Изменилось качество, которое выбрал эстиматор."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","kind":"typeIdentifier","text":"VideoTrackInfo"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Объект с информацией о выбранной эстиматором дорожки видео.","type":"text"}],"type":"paragraph"}],"name":"info"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videotrack(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videotrack(_:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoTrack(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"required":true,"symbolKind":"method","navigatorTitle":[{"text":"videoTrack:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"videoTrack(_:)","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)videoTrack:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoTrackInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoTrackInfo":{"abstract":[{"text":"Информация о выбранной дорожке","type":"text"}],"url":"\/documentation\/ovkit\/videotrackinfo","title":"VideoTrackInfo","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoTrackInfo"}],"navigatorTitle":[{"kind":"identifier","text":"VideoTrackInfo"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"abstract":[{"type":"text","text":"Описание возможных событий на замену "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/modernvideostatshandler","title":"ModernVideoStatsHandler","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoTrack(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoTrack(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"videoTrack:","kind":"identifier"}],"title":"videoTrack(_:)","role":"symbol","abstract":[{"type":"text","text":"Изменилось качество, которое выбрал эстиматор."}],"type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/videotrack(_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"videoTrack:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoTrack:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","text":"OVKVideoTrackInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект с информацией о выбранной эстиматором дорожки видео."}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/title","value":"OVKVideoTrackInfo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/fragments","value":[{"text":"OVKVideoTrackInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoTrackInfo"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoTrack(_:)\/title","value":"videoTrack:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoTrack(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoTrack:","kind":"identifier"}]}]}]}