{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","kind":"typeIdentifier","text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект с информацией о новой дорожке видео."}]}]},{"name":"userInitiated","content":[{"type":"paragraph","inlineContent":[{"text":"Было ли изменение качества инициировано пользователем.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}],"metadata":{"title":"videoQuality(_:userInitiated:)","externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)videoQuality:userInitiated:","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"videoQuality:userInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQuality(_:userInitiated:)"},"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videoquality(_:userinitiated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videoquality(_:userinitiated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoQuality(_:userInitiated:)":{"title":"videoQuality(_:userInitiated:)","type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQuality(_:userInitiated:)","navigatorTitle":[{"text":"videoQuality:userInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoTrackInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/videoquality(_:userinitiated:)","abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"url":"\/documentation\/ovkit\/videostatshandler","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"kind":"symbol","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"ModernVideoStatsHandler","navigatorTitle":[{"text":"ModernVideoStatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoTrackInfo":{"abstract":[{"type":"text","text":"Информация о выбранной дорожке"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoTrackInfo","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"VideoTrackInfo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","title":"VideoTrackInfo","role":"symbol","url":"\/documentation\/ovkit\/videotrackinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"videoQuality:userInitiated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoQuality:userInitiated:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKVideoTrackInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"userInitiated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект с информацией о новой дорожке видео."}]}]},{"name":"userInitiated","content":[{"type":"paragraph","inlineContent":[{"text":"Было ли изменение качества инициировано пользователем.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"videoQuality:userInitiated:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQuality(_:userInitiated:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"videoQuality:userInitiated:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQuality(_:userInitiated:)\/fragments","op":"replace"},{"value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKModernVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKVideoTrackInfo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/title","op":"replace"},{"value":[{"text":"OVKVideoTrackInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/fragments","op":"replace"},{"value":[{"text":"OVKVideoTrackInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}