{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoZoom()"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"videoZoom","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)videoZoom","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoZoom"},{"kind":"text","text":"()"}],"required":true,"title":"videoZoom()","role":"symbol"},"abstract":[{"type":"text","text":"Пользователь активировал зум через жест."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoZoom","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videozoom()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/videozoom()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoZoom()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoZoom","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"videoZoom","kind":"identifier"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/videozoom()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoZoom()","title":"videoZoom()","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Пользователь активировал зум через жест."}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"videoZoom","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"videoZoom","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"videoZoom"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"op":"replace","value":"videoZoom","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoZoom()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoZoom","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoZoom()\/fragments"},{"op":"replace","value":"OVKModernVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title"},{"op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle"}]}]}