{"abstract":[{"text":"Изменилась видимость приложения с плеером на экране.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isInBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Находится ли приложение в фоновом состоянии.","type":"text"}]}],"name":"isInBackground"}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/visibility(isInBackground:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/modernvideostatshandler\/visibility(isinbackground:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler\/visibility(isinbackground:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"]]},"sections":[],"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler(im)visibilityWithIsInBackground:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isInBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"visibility(isInBackground:)","symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"visibilityWithIsInBackground:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"title":"ModernVideoStatsHandler","url":"\/documentation\/ovkit\/modernvideostatshandler","navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/visibility(isInBackground:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"kind":"text","text":"("},{"text":"isInBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"visibilityWithIsInBackground:","kind":"identifier"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/visibility(isinbackground:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/visibility(isInBackground:)","type":"topic","title":"visibility(isInBackground:)","role":"symbol","abstract":[{"text":"Изменилась видимость приложения с плеером на экране.","type":"text"}],"kind":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"visibilityWithIsInBackground:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"visibilityWithIsInBackground:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"visibilityWithIsInBackground:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isInBackground"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"isInBackground","content":[{"inlineContent":[{"text":"Находится ли приложение в фоновом состоянии.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1visibility(isInBackground:)\/title","value":"visibilityWithIsInBackground:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1visibility(isInBackground:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"visibilityWithIsInBackground:"}],"op":"replace"}]}]}