{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay(withExternalControls:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withExternalControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"externalID":"s:5OVKit18DefaultAdsProviderC8autoplay20withExternalControlsACXDSb_tFZ","symbolKind":"method","title":"autoplay(withExternalControls:)","roleHeading":"Type Method","role":"symbol"},"variants":[{"paths":["\/documentation\/ovkit\/defaultadsprovider\/autoplay(withexternalcontrols:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Провайдер рекламы для обычного представления плеера."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withExternalControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"withExternalControls","content":[{"inlineContent":[{"text":"Флаг, указывающий на необходимость отображения внешних контролов.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"AdsProvider","type":"codeVoice"},{"text":" новый экземпляр провайдера рекламы.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"title":"DefaultAdsProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","url":"\/documentation\/ovkit\/defaultadsprovider","abstract":[{"type":"text","text":"Провайдер рекламы."}]},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/autoplay(withExternalControls:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay(withExternalControls:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withExternalControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/defaultadsprovider\/autoplay(withexternalcontrols:)","type":"topic","title":"autoplay(withExternalControls:)","kind":"symbol","abstract":[{"type":"text","text":"Провайдер рекламы для обычного представления плеера."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","op":"replace","value":"OVKDefaultAdsProvider"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDefaultAdsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","value":[{"text":"OVKDefaultAdsProvider","kind":"identifier"}]}]}]}