{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplay","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"AdsProvider"},{"type":"text","text":" новый экземпляр провайдера рекламы."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Провайдер рекламы для обычного представления плеера."}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit18DefaultAdsProviderC8autoplayACXDyFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplay","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"autoplay()","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay()"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/defaultadsprovider\/autoplay()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/autoplay()":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoplay"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}],"title":"autoplay()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay()","url":"\/documentation\/ovkit\/defaultadsprovider\/autoplay()","role":"symbol","abstract":[{"text":"Провайдер рекламы для обычного представления плеера.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"abstract":[{"text":"Провайдер рекламы.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"type":"topic","kind":"symbol","title":"DefaultAdsProvider","url":"\/documentation\/ovkit\/defaultadsprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","value":"DefaultAdsProvider"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","op":"replace","value":[{"text":"DefaultAdsProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","op":"replace","value":[{"text":"DefaultAdsProvider","kind":"identifier"}]}]}]}