{"metadata":{"modules":[{"name":"OVKit"}],"title":"init(supplementedAdControlsType:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"supplementedAdControlsType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","kind":"typeIdentifier","text":"SupplementedAdControlsView"},{"kind":"text","text":".Type)"}],"externalID":"s:5OVKit18DefaultAdsProviderC26supplementedAdControlsTypeAcA012SupplementedfG4ViewCm_tcfc","roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/init(supplementedAdControlsType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Базовый инициализатор провайдера рекламы."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/defaultadsprovider\/init(supplementedadcontrolstype:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"supplementedAdControlsType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","kind":"typeIdentifier","text":"SupplementedAdControlsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"},{"kind":"text","text":".Type)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"supplementedAdControlsType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"PlayerControlsViewProtocol.Type","type":"codeVoice"},{"text":" тип контролов для рекламы с поддержкой ","type":"text"},{"code":"Supplementary View","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","kind":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"kind":"symbol","title":"DefaultAdsProvider","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"abstract":[{"type":"text","text":"Провайдер рекламы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"type":"topic","url":"\/documentation\/ovkit\/defaultadsprovider"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/init(supplementedAdControlsType:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/init(supplementedAdControlsType:)","abstract":[{"type":"text","text":"Базовый инициализатор провайдера рекламы."}],"title":"init(supplementedAdControlsType:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"supplementedAdControlsType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","text":"SupplementedAdControlsView","kind":"typeIdentifier"},{"text":".Type)","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/defaultadsprovider\/init(supplementedadcontrolstype:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"OVKSupplementedAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","value":"OVKDefaultAdsProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","value":[{"kind":"identifier","text":"OVKDefaultAdsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKDefaultAdsProvider"}]}]}]}