{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/isEnabled(for:)"},"metadata":{"externalID":"s:5OVKit18DefaultAdsProviderC9isEnabled3forSbAA05VideoC4Type_p_tF","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isEnabled(for:)","modules":[{"name":"OVKit"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"abstract":[{"text":"Метод проверяет, разрешена ли реклама в переданном наборе рекламных параметров ","type":"text"},{"code":"VideoAdsType","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/defaultadsprovider\/isenabled(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ads","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoAdsType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ads","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"VideoAdsType"},{"text":" набор рекламных параметров.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"Bool"},{"text":", возвращает ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", если реклама разрешена.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"type":"topic","kind":"symbol","abstract":[{"text":"Данные для показа instream рекламы.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdsType"}],"title":"VideoAdsType","role":"symbol","url":"\/documentation\/ovkit\/videoadstype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"kind":"symbol","title":"DefaultAdsProvider","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"abstract":[{"type":"text","text":"Провайдер рекламы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"type":"topic","url":"\/documentation\/ovkit\/defaultadsprovider"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/isEnabled(for:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/isEnabled(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Метод проверяет, разрешена ли реклама в переданном наборе рекламных параметров ","type":"text"},{"code":"VideoAdsType","type":"codeVoice"},{"text":".","type":"text"}],"title":"isEnabled(for:)","type":"topic","url":"\/documentation\/ovkit\/defaultadsprovider\/isenabled(for:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKVideoAdsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title"},{"op":"replace","value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments"},{"op":"replace","value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle"},{"op":"replace","value":"OVKDefaultAdsProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title"},{"op":"replace","value":[{"text":"OVKDefaultAdsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments"},{"op":"replace","value":[{"text":"OVKDefaultAdsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}