{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"sections":[],"abstract":[{"type":"text","text":"Фабричный метод для создания новых рекламных контролов."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeAdControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier","text":"VideoAdsType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasSupplementaryControls"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interactiveAdsPlaying"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inPiP"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit18DefaultAdsProviderC14makeAdControls3for016hasSupplementaryG0011interactiveC7Playing5inPiPAA06PlayerG12ViewProtocol_pAA05VideoC4Type_p_S3btF","roleHeading":"Instance Method","title":"makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/defaultadsprovider\/makeadcontrols(for:hassupplementarycontrols:interactiveadsplaying:inpip:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeAdControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ads","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","text":"VideoAdsType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"},{"text":", ","kind":"text"},{"text":"hasSupplementaryControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interactiveAdsPlaying","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"ads","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"VideoAdsType"},{"type":"text","text":" Рекламные данные."}],"type":"paragraph"}]},{"name":"hasSupplementaryControls","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"Bool"},{"text":" Флаг присутствия дополнительных рекламных контролов.","type":"text"}]}]},{"name":"interactiveAdsPlaying","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"Bool","type":"codeVoice"},{"text":" Флаг проигрывания рекламы интерактивного формата, например, Video Motion или Shoppable.","type":"text"}],"type":"paragraph"}]},{"name":"inPiP","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" Флаг проигрывания в режиме «Картинка в Картинке»."}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"PlayerControlsViewProtocol"},{"type":"text","text":" Новые рекламные контролы плеера."}]}],"kind":"content"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeAdControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier","text":"VideoAdsType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasSupplementaryControls"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interactiveAdsPlaying"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inPiP"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"}],"title":"makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","kind":"symbol","abstract":[{"type":"text","text":"Фабричный метод для создания новых рекламных контролов."}],"url":"\/documentation\/ovkit\/defaultadsprovider\/makeadcontrols(for:hassupplementarycontrols:interactiveadsplaying:inpip:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","title":"PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"title":"VideoAdsType","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VideoAdsType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdsType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videoadstype"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"role":"symbol","title":"DefaultAdsProvider","kind":"symbol","abstract":[{"type":"text","text":"Провайдер рекламы."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"url":"\/documentation\/ovkit\/defaultadsprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKVideoAdsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoAdsType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoAdsType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle","op":"replace"},{"value":"DefaultAdsProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DefaultAdsProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DefaultAdsProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","op":"replace"}]}]}