{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsExternalControls"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"По умолчанию - "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"title":"showsExternalControls","externalID":"s:5OVKit18DefaultAdsProviderC21showsExternalControlsSbvp","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsExternalControls","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/showsExternalControls","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Флаг, указывающий на необходимость отображения внешних контролов.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/defaultadsprovider\/showsexternalcontrols"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/showsExternalControls":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsExternalControls","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Флаг, указывающий на необходимость отображения внешних контролов.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/showsExternalControls","url":"\/documentation\/ovkit\/defaultadsprovider\/showsexternalcontrols","kind":"symbol","role":"symbol","title":"showsExternalControls"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"abstract":[{"type":"text","text":"Провайдер рекламы."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultAdsProvider","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/defaultadsprovider","title":"DefaultAdsProvider","kind":"symbol","navigatorTitle":[{"text":"DefaultAdsProvider","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","value":"OVKDefaultAdsProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","value":[{"text":"OVKDefaultAdsProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","value":[{"text":"OVKDefaultAdsProvider","kind":"identifier"}]}]}]}