{"metadata":{"modules":[{"name":"OVKit"}],"title":"supplementedAdControlsType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementedAdControlsType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","text":"SupplementedAdControlsView"},{"kind":"text","text":".Type"}],"externalID":"s:5OVKit18DefaultAdsProviderC26supplementedAdControlsTypeAA012SupplementedfG4ViewCmvp","roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/supplementedAdControlsType","interfaceLanguage":"swift"},"abstract":[{"text":"Тип контролов для рекламы с поддержкой ","type":"text"},{"type":"codeVoice","code":"Supplementary View"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/defaultadsprovider\/supplementedadcontrolstype"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementedAdControlsType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","text":"SupplementedAdControlsView"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/supplementedAdControlsType":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/supplementedAdControlsType","kind":"symbol","url":"\/documentation\/ovkit\/defaultadsprovider\/supplementedadcontrolstype","abstract":[{"text":"Тип контролов для рекламы с поддержкой ","type":"text"},{"type":"codeVoice","code":"Supplementary View"},{"text":".","type":"text"}],"role":"symbol","title":"supplementedAdControlsType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementedAdControlsType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView","text":"SupplementedAdControlsView","kind":"typeIdentifier"},{"text":".Type","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"kind":"symbol","title":"DefaultAdsProvider","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"abstract":[{"type":"text","text":"Провайдер рекламы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"type":"topic","url":"\/documentation\/ovkit\/defaultadsprovider"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","kind":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview"}},"variantOverrides":[{"patch":[{"value":"OVKDefaultAdsProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDefaultAdsProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDefaultAdsProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","op":"replace"},{"value":"OVKSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}