{"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"VideoType.canPlayInBackground","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/canPlayInBackground","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"canPlayInBackground","kind":"identifier"}],"roleHeading":"Instance Property","title":"canPlayInBackground","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)canPlayInBackground","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayInBackground","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayInBackground"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/canplayinbackground"]},{"paths":["\/documentation\/ovkit\/ovkvideo\/canplayinbackground"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/canPlayInBackground":{"title":"canPlayInBackground","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/canPlayInBackground","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayInBackground"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"navigatorTitle":[{"text":"canPlayInBackground","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkvideo\/canplayinbackground","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"kind":"identifier","text":"Video"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"title":"Video","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"canPlayInBackground","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"canPlayInBackground","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayInBackground"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1canPlayInBackground\/title","value":"canPlayInBackground"},{"value":[{"kind":"identifier","text":"canPlayInBackground"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1canPlayInBackground\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"}]}]}