{"variants":[{"paths":["\/documentation\/ovkit\/ovkvideo\/livestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideo\/livestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"text":"LiveStatus","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"VideoType.liveStatus"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)liveStatus","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"text":"LiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"title":"liveStatus"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/liveStatus":{"title":"liveStatus","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/ovkvideo\/livestatus","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","kind":"typeIdentifier","text":"LiveStatus"}],"navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveStatus"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"kind":"identifier","text":"Video"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"title":"Video","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"kind":"symbol","title":"LiveStatus","url":"\/documentation\/ovkit\/livestatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"liveStatus"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"liveStatus","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"OVKLiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveStatus\/title","value":"liveStatus"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveStatus\/fragments","value":[{"text":"liveStatus","kind":"identifier"}]},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace"}]}]}