{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/livesettings"]},{"paths":["\/documentation\/ovkit\/ovkvideo\/livesettings"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"liveSettings"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"title":"liveSettings","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettings"},{"text":": ","kind":"text"},{"text":"LiveSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)liveSettings"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","text":"LiveSettings"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveSettings","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/video"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/liveSettings":{"url":"\/documentation\/ovkit\/ovkvideo\/livesettings","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveSettings","title":"liveSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","text":"LiveSettings","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"liveSettings","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"navigatorTitle":[{"text":"LiveSettings","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LiveSettings","kind":"identifier"}],"kind":"symbol","title":"LiveSettings","url":"\/documentation\/ovkit\/livesettings"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"liveSettings"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"liveSettings"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","text":"OVKLiveSettings"},{"text":" * ","kind":"text"},{"text":"liveSettings","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveSettings\/title","value":"liveSettings"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveSettings\/fragments","value":[{"kind":"identifier","text":"liveSettings"}]},{"value":"OVKLiveSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","op":"replace"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}