{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveStartTimestamp"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)liveStartTimestamp","title":"liveStartTimestamp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/livestarttimestamp"]},{"paths":["\/documentation\/ovkit\/ovkvideo\/livestarttimestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveStartTimestamp"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoType.liveStartTimestamp"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/liveStartTimestamp":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/ovkvideo\/livestarttimestamp","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/liveStartTimestamp","type":"topic","role":"symbol","title":"liveStartTimestamp","navigatorTitle":[{"text":"liveStartTimestamp","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStartTimestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"kind":"identifier","text":"Video"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"title":"Video","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"liveStartTimestamp","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"liveStartTimestamp","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStartTimestamp"},{"text":";","kind":"text"}]}]}},{"value":"liveStartTimestamp","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveStartTimestamp\/title"},{"value":[{"kind":"identifier","text":"liveStartTimestamp"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1liveStartTimestamp\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]}]}]}