{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/oid","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)oid","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"oid","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"oid","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"oid"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/oid"]},{"paths":["\/documentation\/ovkit\/ovkvideo\/oid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoType.oid"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"oid","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/oid":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"oid","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkvideo\/oid","title":"oid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"oid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/oid","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"oid","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"oid","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"oid"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]},{"op":"replace","value":"oid","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1oid\/title"},{"value":[{"kind":"identifier","text":"oid"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1oid\/fragments"}]}]}