{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/prefetchPreviews"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"metadata":{"role":"symbol","title":"prefetchPreviews","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"prefetchPreviews"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)prefetchPreviews","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchPreviews","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/prefetchpreviews"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideo\/prefetchpreviews"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchPreviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/video"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"title":"ImageAssetType","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/imageassettype","navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/prefetchPreviews":{"abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"title":"prefetchPreviews","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchPreviews"},{"text":": [","kind":"text"},{"text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"prefetchPreviews","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkvideo\/prefetchpreviews","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/prefetchPreviews"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"prefetchPreviews"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefetchPreviews","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<OVKImageAssetType>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"prefetchPreviews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","op":"replace","value":"OVKImageAssetType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","op":"replace","value":[{"text":"OVKImageAssetType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1prefetchPreviews\/title","value":"prefetchPreviews"},{"op":"replace","value":[{"text":"prefetchPreviews","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1prefetchPreviews\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}