{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/prefetchQualityRangeCellular"},"abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/prefetchqualityrangecellular"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideo\/prefetchqualityrangecellular"]}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)prefetchQualityRangeCellular","symbolKind":"property","title":"prefetchQualityRangeCellular","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/video"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/prefetchQualityRangeCellular":{"title":"prefetchQualityRangeCellular","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/prefetchQualityRangeCellular","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/ovkvideo\/prefetchqualityrangecellular"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","title":"QualityRange","url":"\/documentation\/ovkit\/qualityrange","abstract":[{"type":"text","text":"Диапазон качества видео."}],"navigatorTitle":[{"kind":"identifier","text":"QualityRange"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"prefetchQualityRangeCellular"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"OVKQualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"text":" * ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","value":"prefetchQualityRangeCellular","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1prefetchQualityRangeCellular\/title"},{"op":"replace","value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1prefetchQualityRangeCellular\/fragments"},{"value":"OVKQualityRange","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title"},{"value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments"}]}]}