{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"VideoType.previewImages","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"previewImages","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"previewImages","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)previewImages","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewImages"},{"text":": [","kind":"text"},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/previewImages","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImages","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkvideo\/previewimages"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideo\/previewimages"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","url":"\/documentation\/ovkit\/imageassettype","abstract":[],"kind":"symbol","title":"ImageAssetType","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/previewImages":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImages"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier","text":"ImageAssetType"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"previewImages","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkvideo\/previewimages","abstract":[],"title":"previewImages","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/previewImages"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"previewImages","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"previewImages"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<OVKImageAssetType>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"previewImages","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKImageAssetType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title"},{"value":[{"text":"OVKImageAssetType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","op":"replace"},{"value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1previewImages\/title","value":"previewImages"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1previewImages\/fragments","value":[{"text":"previewImages","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}