{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/ovkvideo\/subtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideo\/subtitle"]}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)subtitle","title":"subtitle","navigatorTitle":[{"text":"subtitle","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/subtitle"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"subtitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"VideoType.subtitle","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/subtitle":{"title":"subtitle","role":"symbol","navigatorTitle":[{"text":"subtitle","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkvideo\/subtitle","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/subtitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"subtitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subtitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"subtitle","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"subtitle","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"value":"subtitle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1subtitle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1subtitle\/fragments","value":[{"text":"subtitle","kind":"identifier"}],"op":"replace"}]}]}