{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideo\/timelinethumbs"]},{"paths":["\/documentation\/ovkit\/ovkvideo\/timelinethumbs"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/timelineThumbs","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimelineThumbnailsType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)timelineThumbs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineThumbs"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"TimelineThumbnailsType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}],"role":"symbol","title":"timelineThumbs","modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"VideoType.timelineThumbs","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideo/timelineThumbs":{"url":"\/documentation\/ovkit\/ovkvideo\/timelinethumbs","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideo\/timelineThumbs","title":"timelineThumbs","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timelineThumbs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"TimelineThumbnailsType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/video"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"url":"\/documentation\/ovkit\/timelinethumbnailstype","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TimelineThumbnailsType","kind":"identifier"}],"title":"TimelineThumbnailsType","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"timelineThumbs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"timelineThumbs"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKTimelineThumbnailsType","kind":"typeIdentifier","text":"id<OVKTimelineThumbnailsType>"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineThumbs"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"timelineThumbs","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1timelineThumbs\/title"},{"op":"replace","value":[{"text":"timelineThumbs","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideo~1timelineThumbs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]},{"value":"OVKTimelineThumbnailsType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}],"op":"replace"}]}]}