{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/!=(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/cmaftimelineversion\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion"]]},"kind":"symbol","metadata":{"symbolKind":"op","title":"!=(_:_:)","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Operator","role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@OVKit@E@OVCmafTimeLineVersion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/!=(_:_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/cmaftimelineversion\/!=(_:_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"title":"CmafTimeLineVersion","url":"\/documentation\/ovkit\/cmaftimelineversion","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CmafTimeLineVersion","kind":"identifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVCmafTimeLineVersion","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVCmafTimeLineVersion"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments"},{"op":"replace","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}