{"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"OVKit"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftimelineversion\/equatable-implementations"]}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/!=(_:_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/cmaftimelineversion\/!=(_:_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"title":"CmafTimeLineVersion","url":"\/documentation\/ovkit\/cmaftimelineversion","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CmafTimeLineVersion","kind":"identifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVCmafTimeLineVersion","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title"},{"op":"replace","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments"},{"op":"replace","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle"}]}]}