{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v3"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v3"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v3","kind":"identifier"}],"title":"CmafTimeLineVersion.v3","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVCmafTimeLineVersion@OVCmafTimeLineVersionV3","navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionV3"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v3"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","url":"\/documentation\/ovkit\/cmaftimelineversion","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CmafTimeLineVersion","kind":"identifier"}],"title":"CmafTimeLineVersion","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/v3":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v3","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v3","title":"CmafTimeLineVersion.v3","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/cmaftimelineversion\/v3","navigatorTitle":[{"text":"OVCmafTimeLineVersionV3","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVCmafTimeLineVersionV3","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVCmafTimeLineVersionV3"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVCmafTimeLineVersionV3","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVCmafTimeLineVersion","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title"},{"value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments"},{"value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle"},{"value":"OVCmafTimeLineVersionV3","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v3\/title"},{"value":[{"text":"OVCmafTimeLineVersionV3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v3\/fragments"}]}]}