{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v4"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v4"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v4","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"CmafTimeLineVersion.v4","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionV4"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVCmafTimeLineVersion@OVCmafTimeLineVersionV4","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v4","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/v4":{"navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionV4"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v4","url":"\/documentation\/ovkit\/cmaftimelineversion\/v4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v4"}],"kind":"symbol","abstract":[],"title":"CmafTimeLineVersion.v4","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","url":"\/documentation\/ovkit\/cmaftimelineversion","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CmafTimeLineVersion","kind":"identifier"}],"title":"CmafTimeLineVersion","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVCmafTimeLineVersionV4"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVCmafTimeLineVersionV4"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVCmafTimeLineVersionV4","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v4\/title","value":"OVCmafTimeLineVersionV4"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v4\/fragments","value":[{"kind":"identifier","text":"OVCmafTimeLineVersionV4"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title","value":"OVCmafTimeLineVersion","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments","value":[{"kind":"identifier","text":"OVCmafTimeLineVersion"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"op":"replace"}]}]}