{"variants":[{"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v5"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cmaftimelineversion\/v5"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v5","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v5","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVCmafTimeLineVersion@OVCmafTimeLineVersionV5","title":"CmafTimeLineVersion.v5","navigatorTitle":[{"text":"OVCmafTimeLineVersionV5","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"v5","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/v5":{"type":"topic","url":"\/documentation\/ovkit\/cmaftimelineversion\/v5","navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionV5"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v5"}],"title":"CmafTimeLineVersion.v5","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v5"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"url":"\/documentation\/ovkit\/cmaftimelineversion","kind":"symbol","title":"CmafTimeLineVersion","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","navigatorTitle":[{"text":"CmafTimeLineVersion","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVCmafTimeLineVersionV5"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVCmafTimeLineVersionV5","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVCmafTimeLineVersionV5"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v5\/title","value":"OVCmafTimeLineVersionV5"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v5\/fragments","value":[{"kind":"identifier","text":"OVCmafTimeLineVersionV5"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title","value":"OVCmafTimeLineVersion"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}]}]}]}