{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Разрешить ли воспроизведение на внешних устройствах. Необходимо установить сразу после запуска приложения. По умолчанию ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/allowsExternalPlayback","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsExternalPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowsExternalPlayback","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"allowsExternalPlayback","navigatorTitle":[{"text":"allowsExternalPlayback","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)allowsExternalPlayback","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/allowsexternalplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/allowsexternalplayback"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/allowsExternalPlayback":{"title":"allowsExternalPlayback","role":"symbol","navigatorTitle":[{"text":"allowsExternalPlayback","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkenvironment\/allowsexternalplayback","kind":"symbol","abstract":[{"text":"Разрешить ли воспроизведение на внешних устройствах. Необходимо установить сразу после запуска приложения. По умолчанию ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/allowsExternalPlayback","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsExternalPlayback","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"allowsExternalPlayback"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"allowsExternalPlayback"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"allowsExternalPlayback","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":"allowsExternalPlayback","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1allowsExternalPlayback\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1allowsExternalPlayback\/fragments","value":[{"text":"allowsExternalPlayback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}