{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsBackgroundPlayback"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим игры в фоне также задается для каждого плеера по отдельности ("},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","isActive":true},{"type":"text","text":"). Плеер может не играть в фоне, если видео не поддерживает такую возможность."}]}]},{"inlineContent":[{"type":"text","text":"Необходимо установить сразу после запуска приложения. По умолчанию "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/allowsBackgroundPlayback","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/allowsbackgroundplayback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/allowsbackgroundplayback"]}],"abstract":[{"text":"Разрешить ли воспроизведение видео в фоне.","type":"text"}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)allowsBackgroundPlayback","modules":[{"name":"OVKit"}],"title":"allowsBackgroundPlayback","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"allowsBackgroundPlayback","kind":"identifier"}]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/environment","title":"Environment","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/allowsBackgroundPlayback":{"url":"\/documentation\/ovkit\/ovkenvironment\/allowsbackgroundplayback","type":"topic","kind":"symbol","title":"allowsBackgroundPlayback","abstract":[{"type":"text","text":"Разрешить ли воспроизведение видео в фоне."}],"navigatorTitle":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowsBackgroundPlayback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/allowsBackgroundPlayback"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/backgroundPlaybackPolicy":{"abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"backgroundPlaybackPolicy","kind":"identifier"}],"title":"backgroundPlaybackPolicy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"backgroundPlaybackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","text":"BackgroundPlaybackPolicy","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"allowsBackgroundPlayback","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowsBackgroundPlayback"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"value":"allowsBackgroundPlayback","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1allowsBackgroundPlayback\/title"},{"value":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1allowsBackgroundPlayback\/fragments"},{"op":"replace","value":"backgroundPlaybackPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/fragments","value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"op":"replace"}]}]}