{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Работает только при включенном enableDiagnosticsView.","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)autoShowDiagnosticsView","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"autoShowDiagnosticsView"}],"role":"symbol","roleHeading":"Instance Property","title":"autoShowDiagnosticsView"},"abstract":[{"text":"Автоматический показ DiagnosticsView на всех плеерах после их создания. По умолчанию выключено.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/autoshowdiagnosticsview"]},{"paths":["\/documentation\/ovkit\/ovkenvironment\/autoshowdiagnosticsview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/autoShowDiagnosticsView","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/autoShowDiagnosticsView":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoShowDiagnosticsView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/autoShowDiagnosticsView","navigatorTitle":[{"text":"autoShowDiagnosticsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Автоматический показ DiagnosticsView на всех плеерах после их создания. По умолчанию выключено."}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/ovkenvironment\/autoshowdiagnosticsview","type":"topic","title":"autoShowDiagnosticsView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoShowDiagnosticsView"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"autoShowDiagnosticsView"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autoShowDiagnosticsView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","op":"replace","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace"},{"value":"autoShowDiagnosticsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1autoShowDiagnosticsView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1autoShowDiagnosticsView\/fragments","value":[{"kind":"identifier","text":"autoShowDiagnosticsView"}]}]}]}