{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableRTMP"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/enablertmp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/enablertmp"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableRTMP","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"enableRTMP","roleHeading":"Type Property","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)enableRTMP","navigatorTitle":[{"text":"enableRTMP","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableRTMP","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/enableRTMP":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRTMP"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableRTMP","navigatorTitle":[{"text":"enableRTMP","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkenvironment\/enablertmp","abstract":[],"title":"enableRTMP","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"title":"Environment","url":"\/documentation\/ovkit\/environment","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"enableRTMP","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"enableRTMP","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"enableRTMP","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableRTMP\/title","value":"enableRTMP","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableRTMP\/fragments","value":[{"kind":"identifier","text":"enableRTMP"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]}]}]}