{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"enableDiagnosticsView","kind":"identifier"}],"roleHeading":"Instance Property","title":"enableDiagnosticsView","symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)enableDiagnosticsView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDiagnosticsView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/enablediagnosticsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkenvironment\/enablediagnosticsview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableDiagnosticsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"После включения в меню плеера под шестеренкой появится новый пункт, который добавляет поверх играющего видео оверлей с отладочной информацией. По умолчанию выключено.","type":"text"}]}]}],"abstract":[{"text":"Активирует возможность наблюдать за отладочными данными плеера.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableDiagnosticsView"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/enableDiagnosticsView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDiagnosticsView"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableDiagnosticsView","navigatorTitle":[{"text":"enableDiagnosticsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkenvironment\/enablediagnosticsview","kind":"symbol","title":"enableDiagnosticsView","abstract":[{"type":"text","text":"Активирует возможность наблюдать за отладочными данными плеера."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"title":"Environment","url":"\/documentation\/ovkit\/environment","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"enableDiagnosticsView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"enableDiagnosticsView","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"enableDiagnosticsView","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"enableDiagnosticsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableDiagnosticsView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableDiagnosticsView\/fragments","value":[{"text":"enableDiagnosticsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}]}]}]}