{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableAUv3_v3"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableAUv3_v3","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Type Property","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"enableAUv3_v3","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)enableAUv3_v3","navigatorTitle":[{"text":"enableAUv3_v3","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableAUv3_v3","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/enableauv3_v3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkenvironment\/enableauv3_v3"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/enableAUv3_v3":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableAUv3_v3","abstract":[],"navigatorTitle":[{"text":"enableAUv3_v3","kind":"identifier"}],"kind":"symbol","title":"enableAUv3_v3","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableAUv3_v3"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/ovkenvironment\/enableauv3_v3"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"kind":"symbol","url":"\/documentation\/ovkit\/environment","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Environment"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic","title":"Environment","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"enableAUv3_v3","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"enableAUv3_v3","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableAUv3_v3"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"enableAUv3_v3","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableAUv3_v3\/title"},{"value":[{"text":"enableAUv3_v3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableAUv3_v3\/fragments"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}