{"metadata":{"navigatorTitle":[{"text":"enableAUv3_v2","kind":"identifier"}],"title":"enableAUv3_v2","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableAUv3_v2","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)enableAUv3_v2","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableAUv3_v2"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableAUv3_v2","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/enableauv3_v2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkenvironment\/enableauv3_v2"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"title":"Environment","url":"\/documentation\/ovkit\/environment","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/enableAUv3_v2":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableAUv3_v2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/ovkenvironment\/enableauv3_v2","title":"enableAUv3_v2","navigatorTitle":[{"kind":"identifier","text":"enableAUv3_v2"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/enableAUv3_v2","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"enableAUv3_v2"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"enableAUv3_v2","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableAUv3_v2"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableAUv3_v2\/title","op":"replace","value":"enableAUv3_v2"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1enableAUv3_v2\/fragments","value":[{"text":"enableAUv3_v2","kind":"identifier"}],"op":"replace"}]}]}