{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logZeroWatchCoverage"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/logZeroWatchCoverage","interfaceLanguage":"swift"},"abstract":[{"text":"Логирование пустых отрезков просмотра, например  ","type":"text"},{"code":"[7 - 7]","type":"codeVoice"},{"type":"text","text":". По умолчанию выключено."}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logZeroWatchCoverage"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"logZeroWatchCoverage"}],"title":"logZeroWatchCoverage","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)logZeroWatchCoverage","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/logzerowatchcoverage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/logzerowatchcoverage"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/logZeroWatchCoverage":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logZeroWatchCoverage"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"logZeroWatchCoverage","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/logZeroWatchCoverage","abstract":[{"text":"Логирование пустых отрезков просмотра, например  ","type":"text"},{"code":"[7 - 7]","type":"codeVoice"},{"text":". По умолчанию выключено.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logZeroWatchCoverage"}],"type":"topic","url":"\/documentation\/ovkit\/ovkenvironment\/logzerowatchcoverage","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"logZeroWatchCoverage","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"logZeroWatchCoverage","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"logZeroWatchCoverage","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":"logZeroWatchCoverage","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1logZeroWatchCoverage\/title","op":"replace"},{"value":[{"text":"logZeroWatchCoverage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1logZeroWatchCoverage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}