{"abstract":[{"text":"Идентификатор пользователя приложения.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/userid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkenvironment\/userid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"UrlPathAllowed","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UrlPathAllowed","kind":"attribute","preciseIdentifier":"s:5OVKit14UrlPathAllowedV"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"При выходе  пользователя достаточно установить "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Позволяет использовать несколько раздельных библиотек загруженных видео, если приложение поддерживает многопользовательский режим.","type":"text"},{"type":"text","text":" "},{"text":"Это может быть идентификатор пользователя на клиентском портале или уникальный идентификатор устройства.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"Идентификатор не должен содержать спецсимволов и "},{"inlineContent":[{"text":"должен быть установлен как можно раньше","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Warning","type":"aside","style":"warning"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/userId","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"userId"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"userId","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(py)userId","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property"},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/userId":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/userId","navigatorTitle":[{"text":"userId","kind":"identifier"}],"abstract":[{"text":"Идентификатор пользователя приложения.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/ovkenvironment\/userid","title":"userId","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/UrlPathAllowed":{"navigatorTitle":[{"kind":"identifier","text":"UrlPathAllowed"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UrlPathAllowed"}],"title":"UrlPathAllowed","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UrlPathAllowed","abstract":[],"url":"\/documentation\/ovkit\/urlpathallowed"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"userId","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"userId"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1userId\/title","value":"userId"},{"value":[{"text":"userId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1userId\/fragments"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}