{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"versionOVPlayerKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"versionOVPlayerKit","modules":[{"name":"OVKit"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"versionOVPlayerKit","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"versionOVPlayerKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)versionOVPlayerKit"},"abstract":[{"text":"From OVPlayerKit.h","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkenvironment\/versionovplayerkit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/versionovplayerkit"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/versionOVPlayerKit","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/versionOVPlayerKit":{"type":"topic","url":"\/documentation\/ovkit\/ovkenvironment\/versionovplayerkit","kind":"symbol","title":"versionOVPlayerKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/versionOVPlayerKit","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"versionOVPlayerKit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"versionOVPlayerKit","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"From OVPlayerKit.h"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"title":"Environment","url":"\/documentation\/ovkit\/environment","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"versionOVPlayerKit","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"versionOVPlayerKit"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"versionOVPlayerKit"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"versionOVPlayerKit","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1versionOVPlayerKit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"versionOVPlayerKit"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1versionOVPlayerKit\/fragments"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"}]}]}