{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/videoProxy","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoProxy"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","kind":"typeIdentifier","text":"VideoProxyProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/videoproxy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkenvironment\/videoproxy"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment(cpy)videoProxy","modules":[{"name":"OVKit"}],"title":"videoProxy","role":"symbol","symbolKind":"property","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoProxy"},{"text":": ","kind":"text"},{"text":"VideoProxyProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"videoProxy","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKEnvironment/videoProxy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKEnvironment\/videoProxy","title":"videoProxy","abstract":[],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/ovkenvironment\/videoproxy","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoProxy"},{"text":": ","kind":"text"},{"text":"VideoProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"videoProxy","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol":{"role":"symbol","title":"VideoProxyProtocol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoProxyProtocol"}],"type":"topic","url":"\/documentation\/ovkit\/videoproxyprotocol","navigatorTitle":[{"text":"VideoProxyProtocol","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/environment","title":"Environment","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"videoProxy","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"videoProxy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"id<VideoProxyProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)VideoProxyProtocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoProxy"},{"kind":"text","text":";"}]}]}},{"value":"videoProxy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1videoProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKEnvironment~1videoProxy\/fragments","value":[{"text":"videoProxy","kind":"identifier"}]},{"value":"VideoProxyProtocol","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/title"},{"value":[{"text":"VideoProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/fragments","op":"replace"},{"value":"OVKEnvironment","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}