{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcher\/cancelall()"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"abstract":[{"text":"Отмена предзагрузки всех ресурсов.","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"title":"cancelAll()","externalID":"s:5OVKit10PrefetcherC9cancelAllyyF","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAll"},{"kind":"text","text":"()"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/cancelAll()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAll"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"title":"Prefetcher","role":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"url":"\/documentation\/ovkit\/prefetcher","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/cancelAll()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/cancelAll()","role":"symbol","abstract":[{"text":"Отмена предзагрузки всех ресурсов.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelAll","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"cancelAll()","type":"topic","url":"\/documentation\/ovkit\/prefetcher\/cancelall()"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","op":"replace","value":"OVKPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","op":"replace","value":[{"text":"OVKPrefetcher","kind":"identifier"}]}]}]}