{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cacheContainer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","text":"CacheContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"groupName","content":[{"inlineContent":[{"type":"text","text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь."}],"type":"paragraph"}]},{"name":"cacheContainer","content":[{"inlineContent":[{"type":"text","text":"Кастомный контейнер для кэша. Если не задан, то будет использоваться общий кэш."}],"type":"paragraph"}]},{"name":"controlQueue","content":[{"inlineContent":[{"text":"Любая последовательная очередь.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcher\/init(groupname:cachecontainer:controlqueue:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"metadata":{"externalID":"s:5OVKit10PrefetcherC9groupName14cacheContainer12controlQueueACSSSg_AA05CacheF0CSgSo17OS_dispatch_queueCtcfc","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheContainer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","kind":"typeIdentifier","text":"CacheContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"title":"init(groupName:cacheContainer:controlQueue:)","roleHeading":"Initializer"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/init(groupName:cacheContainer:controlQueue:)","interfaceLanguage":"swift"},"abstract":[{"text":"Создание префетчера.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}],"url":"\/documentation\/ovkit\/prefetcher","title":"Prefetcher","navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Префетчер видеозаписей."}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/init(groupName:cacheContainer:controlQueue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"cacheContainer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","title":"init(groupName:cacheContainer:controlQueue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/init(groupName:cacheContainer:controlQueue:)","url":"\/documentation\/ovkit\/prefetcher\/init(groupname:cachecontainer:controlqueue:)","abstract":[{"text":"Создание префетчера.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"navigatorTitle":[{"text":"CacheContainer","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/cachecontainer","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","title":"CacheContainer"}},"variantOverrides":[{"patch":[{"value":"Prefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title"},{"value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments"},{"value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle"},{"value":"OVKCacheContainer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}