{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol","title":"maxConcurrentDownloadsCount","roleHeading":"Instance Property","externalID":"s:5OVKit10PrefetcherC27maxConcurrentDownloadsCountSivp"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"По умолчанию имеет значение ","type":"text"},{"type":"codeVoice","code":"1"},{"text":".","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/prefetcher\/maxconcurrentdownloadscount"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/maxConcurrentDownloadsCount","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/maxConcurrentDownloadsCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"maxConcurrentDownloadsCount","type":"topic","url":"\/documentation\/ovkit\/prefetcher\/maxconcurrentdownloadscount","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/maxConcurrentDownloadsCount"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Prefetcher"}],"title":"Prefetcher","navigatorTitle":[{"text":"Prefetcher","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Префетчер видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"value":"Prefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","value":[{"text":"Prefetcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}