{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:onFinish:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Начать предзагрузку видео."}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:onFinish:)","externalID":"s:5OVKit10PrefetcherC13prefetchVideo_8duration5after20forcePrefetchPreview20estimatedSurfaceSize9onSuccess0M6FinishyAA0D4Type_p_S2dSgSbSo6CGSizeVSgyycSgys5Error_pSgcSgtF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forcePrefetchPreview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedSurfaceSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"onFinish"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchVideo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"video","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 3.0, ","kind":"text"},{"text":"after","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"time"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"forcePrefetchPreview"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"estimatedSurfaceSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")? = nil, "},{"text":"onFinish","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео для предзагрузки."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Желаемая длительность предзагрузки. Округляется в верхнюю сторону по ближайшей границе сегмента. По умолчанию 3 секунды."}],"type":"paragraph"}],"name":"duration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время, с которого надо начинать предзагрузку. По умолчанию начинается с начала."}]}],"name":"time"},{"name":"forcePrefetchPreview","content":[{"inlineContent":[{"text":"Включает принудительную загрузку превью видео. По умолчанию ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":", но для некоторых видео все равно может загружаться превью."}],"type":"paragraph"}]},{"name":"estimatedSurfaceSize","content":[{"inlineContent":[{"text":"Предполагаемый размер области, в которой будет отображаться видео. Задается в пикселях. По умолчанию не учитывается.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Блок вызывается после успешного завершения предзагрузки.","type":"text"}],"type":"paragraph"}],"name":"onSuccess"},{"content":[{"inlineContent":[{"text":"Блок вызывается после завершения операции предзагрузки с любым исходом или ее отмены. Отсутствие аргумента ","type":"text"},{"code":"Error","type":"codeVoice"},{"type":"text","text":" не гарантирует успешность предзагрузки."}],"type":"paragraph"}],"name":"onFinish"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onsuccess:onfinish:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher","title":"Prefetcher","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Prefetcher","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:onFinish:)":{"title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:onFinish:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:onFinish:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchVideo"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"after","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":"?, ","kind":"text"},{"text":"forcePrefetchPreview","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"estimatedSurfaceSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":"?, "},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"onFinish"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Начать предзагрузку видео."}],"url":"\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onsuccess:onfinish:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","op":"replace","value":"Prefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","op":"replace","value":[{"text":"Prefetcher","kind":"identifier"}]}]}]}