{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prefetchVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"video","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 3.0, ","kind":"text"},{"text":"after","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"forcePrefetchPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"estimatedSurfaceSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео для предзагрузки."}]}]},{"content":[{"inlineContent":[{"text":"Желаемая длительность предзагрузки. Округляется в верхнюю сторону по ближайшей границе сегмента. По умолчанию 3 секунды.","type":"text"}],"type":"paragraph"}],"name":"duration"},{"content":[{"inlineContent":[{"text":"Время, с которого надо начинать предзагрузку. По умолчанию начинается с начала.","type":"text"}],"type":"paragraph"}],"name":"time"},{"name":"forcePrefetchPreview","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Включает принудительную загрузку превью видео. По умолчанию "},{"code":"false","type":"codeVoice"},{"type":"text","text":", но для некоторых видео все равно может загружаться превью."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Предполагаемый размер области, в которой будет отображаться видео. Задается в пикселях. По умолчанию не учитывается."}]}],"name":"estimatedSurfaceSize"},{"name":"successBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок вызовется после успешного завершения предзагрузки."}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onsuccess:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"sections":[],"metadata":{"role":"symbol","title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:)","externalID":"s:5OVKit10PrefetcherC13prefetchVideo_8duration5after20forcePrefetchPreview20estimatedSurfaceSize9onSuccessyAA0D4Type_p_S2dSgSbSo6CGSizeVSgyycSgtF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetchVideo","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"after"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forcePrefetchPreview"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"estimatedSurfaceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Начать предзагрузку видео.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"kind":"symbol","url":"\/documentation\/ovkit\/prefetcher","role":"symbol","navigatorTitle":[{"text":"Prefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"type":"topic","title":"Prefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Prefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:)":{"kind":"symbol","url":"\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onsuccess:)","role":"symbol","title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchVideo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"after","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forcePrefetchPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"estimatedSurfaceSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":"?, ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Начать предзагрузку видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onSuccess:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videotype","title":"VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Prefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"}]}]}