{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:5OVKit10PrefetcherC13prefetchVideo_8duration5after20forcePrefetchPreview20estimatedSurfaceSize8onFinishyAA0D4Type_p_S2dSgSbSo6CGSizeVSgyAC11TaskSummaryVSg_s5Error_pSgtcSgtF","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchVideo"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forcePrefetchPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedSurfaceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onFinish"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"TaskSummary","preciseIdentifier":"s:5OVKit10PrefetcherC11TaskSummaryV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"kind":"symbol","abstract":[{"type":"text","text":"Начать предзагрузку видео."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onFinish:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"video","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":" = 3.0, ","kind":"text"},{"text":"after","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"forcePrefetchPreview","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"estimatedSurfaceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":"? = nil, ","kind":"text"},{"text":"onFinish","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"TaskSummary","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary","preciseIdentifier":"s:5OVKit10PrefetcherC11TaskSummaryV"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео для предзагрузки."}]}]},{"name":"duration","content":[{"inlineContent":[{"text":"Желаемая длительность предзагрузки. Округляется в верхнюю сторону по ближайшей границе сегмента. По умолчанию 3 секунды.","type":"text"}],"type":"paragraph"}]},{"name":"time","content":[{"type":"paragraph","inlineContent":[{"text":"Время, с которого надо начинать предзагрузку. По умолчанию начинается с начала.","type":"text"}]}]},{"name":"forcePrefetchPreview","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Включает принудительную загрузку превью видео. По умолчанию "},{"type":"codeVoice","code":"false"},{"type":"text","text":", но для некоторых видео все равно может загружаться превью."}]}]},{"name":"estimatedSurfaceSize","content":[{"inlineContent":[{"text":"Предполагаемый размер области, в которой будет отображаться видео. Задается в пикселях. По умолчанию не учитывается.","type":"text"}],"type":"paragraph"}]},{"name":"onFinish","content":[{"inlineContent":[{"type":"text","text":"Блок, который будет вызван после завершения операции. Наличие "},{"type":"codeVoice","code":"TaskSummary"},{"type":"text","text":" означает, что операция была выполнена без ошибок. "},{"type":"codeVoice","code":"Error"},{"text":" будет содержать ошибку, если такая возникла во время выполнения. Отсутствие и флага и ошибки обычно означает, что операция была отменена. Комбинация, при которой установлен и флаг и ошибка, является невозможной.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onfinish:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"title":"Prefetcher","role":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"url":"\/documentation\/ovkit\/prefetcher","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onFinish:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onFinish:)","role":"symbol","abstract":[{"type":"text","text":"Начать предзагрузку видео."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forcePrefetchPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedSurfaceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onFinish"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:5OVKit10PrefetcherC11TaskSummaryV","kind":"typeIdentifier","text":"TaskSummary"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"kind":"symbol","title":"prefetchVideo(_:duration:after:forcePrefetchPreview:estimatedSurfaceSize:onFinish:)","type":"topic","url":"\/documentation\/ovkit\/prefetcher\/prefetchvideo(_:duration:after:forceprefetchpreview:estimatedsurfacesize:onfinish:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","role":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/videotype"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaskSummary"}],"navigatorTitle":[{"kind":"identifier","text":"TaskSummary"}],"title":"Prefetcher.TaskSummary","role":"symbol","abstract":[{"text":"Информация об успешном результате выполнения префетча одного ресурса.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher\/tasksummary","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","value":"OVKPrefetcher"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","value":[{"kind":"identifier","text":"OVKPrefetcher"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","value":[{"text":"OVKPrefetcher","kind":"identifier"}]},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}]}]}