{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcher\/tasksummary"]}],"metadata":{"role":"symbol","title":"Prefetcher.TaskSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaskSummary"}],"roleHeading":"Structure","symbolKind":"struct","externalID":"s:5OVKit10PrefetcherC11TaskSummaryV","navigatorTitle":[{"kind":"identifier","text":"TaskSummary"}],"modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher"]]},"abstract":[{"type":"text","text":"Информация об успешном результате выполнения префетча одного ресурса."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaskSummary"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/bytesReceived","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/verified"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"title":"Prefetcher","abstract":[{"type":"text","text":"Префетчер видеозаписей."}],"url":"\/documentation\/ovkit\/prefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary/verified":{"title":"verified","role":"symbol","url":"\/documentation\/ovkit\/prefetcher\/tasksummary\/verified","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verified","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/verified","kind":"symbol","abstract":[{"text":"Все необходимые данные были загружены или проверено их наличие в кэше. ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" означает, что операция была отменена до или во время выполнения.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary","url":"\/documentation\/ovkit\/prefetcher\/tasksummary","title":"Prefetcher.TaskSummary","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaskSummary"}],"navigatorTitle":[{"kind":"identifier","text":"TaskSummary"}],"abstract":[{"type":"text","text":"Информация об успешном результате выполнения префетча одного ресурса."}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary/bytesReceived":{"title":"bytesReceived","role":"symbol","url":"\/documentation\/ovkit\/prefetcher\/tasksummary\/bytesreceived","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesReceived","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/bytesReceived","kind":"symbol","abstract":[{"type":"text","text":"Количество данных, загруженных из сети в ходе работы префетчера над этой задачей."}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","op":"replace","value":"Prefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"Prefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","op":"replace","value":[{"text":"Prefetcher","kind":"identifier"}]}]}]}