{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Пользователь перемотал видео."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didSeek","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"seconds","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":"Плеер, от которого пришло событие."}],"type":"paragraph"}]},{"name":"seconds","content":[{"inlineContent":[{"type":"text","text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didseek:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didseek:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didSeek","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"title":"player(_:didSeek:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)player:didSeek:","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"player:didSeek:"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSeek:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didSeek:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didSeek:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didseek:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSeek:)","title":"player(_:didSeek:)","abstract":[{"text":"Пользователь перемотал видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"title":"PlayerEventListener","kind":"symbol","role":"symbol","abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"url":"\/documentation\/ovkit\/playereventlistener"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"player:didSeek:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"player:didSeek:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"player:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","text":"OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSeek:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"seconds"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, от которого пришло событие.","type":"text"}]}],"name":"playerView"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать.","type":"text"}]}],"name":"seconds"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"player:didSeek:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSeek:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"player:didSeek:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSeek:)\/fragments"},{"op":"replace","value":"OVKPlayerEventListener","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title"},{"op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}