{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"visualQualityChangedByUser","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInitiated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":", состояние которого изменилось.","type":"text"}]}]},{"name":"userInitiated","content":[{"inlineContent":[{"type":"text","text":"Произошло ли изменение в результате переключения пользователем из настроек или из кода."}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Выбранное пользователем качество можно получить через свойство "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality","isActive":true},{"type":"text","text":", а актуальный диапазон автоматического качества - через "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange"},{"text":".","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:visualQualityChangedByUser:)"},"variants":[{"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:visualqualitychangedbyuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:visualqualitychangedbyuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","title":"player(_:visualQualityChangedByUser:)","role":"symbol","navigatorTitle":[{"text":"player:visualQualityChangedByUser:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"visualQualityChangedByUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)player:visualQualityChangedByUser:"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:visualQualityChangedByUser:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"player:visualQualityChangedByUser:","kind":"identifier"}],"title":"player(_:visualQualityChangedByUser:)","type":"topic","url":"\/documentation\/ovkit\/playereventlistener\/player(_:visualqualitychangedbyuser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"text":"visualQualityChangedByUser","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:visualQualityChangedByUser:)","abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/playereventlistener","title":"PlayerEventListener","abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerEventListener"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","abstract":[],"type":"topic","title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectedQuality":{"role":"symbol","navigatorTitle":[{"text":"selectedQuality","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedQuality","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"type":"topic","title":"selectedQuality","kind":"symbol","abstract":[{"type":"text","text":"Качество, выбранное пользователем."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality","url":"\/documentation\/ovkit\/playerview\/selectedquality"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/autoQualityRange":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoQualityRange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"Диапазон, в котором плеер будет играть, если выбрано автоматическое качество.","type":"text"}],"title":"autoQualityRange","navigatorTitle":[{"text":"autoQualityRange","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange","url":"\/documentation\/ovkit\/playerview\/autoqualityrange"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"player:visualQualityChangedByUser:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"player:visualQualityChangedByUser:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"player:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"OVKPlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualQualityChangedByUser:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"userInitiated","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", состояние которого изменилось.","type":"text"}],"type":"paragraph"}]},{"name":"userInitiated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Произошло ли изменение в результате переключения пользователем из настроек или из кода."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:visualQualityChangedByUser:)\/title","value":"player:visualQualityChangedByUser:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:visualQualityChangedByUser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"player:visualQualityChangedByUser:","kind":"identifier"}]},{"value":"OVKPlayerEventListener","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"value":"selectedQuality","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/fragments","value":[{"text":"selectedQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/title","value":"autoQualityRange"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/fragments","value":[{"kind":"identifier","text":"autoQualityRange"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}