{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStall(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playereventlistener\/playerdidstall(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playereventlistener\/playerdidstall(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerDidStall"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"abstract":[{"type":"text","text":"Плеер перешел в состояние "},{"code":"stall","type":"codeVoice"},{"type":"text","text":". Если трансляция, стоит актуализировать статус "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","isActive":true,"type":"reference"},{"text":".","type":"text"}],"metadata":{"title":"playerDidStall(_:)","role":"symbol","navigatorTitle":[{"text":"playerDidStall:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)playerDidStall:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerDidStall"},{"kind":"text","text":"("},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"url":"\/documentation\/ovkit\/playereventlistener","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"title":"PlayerEventListener","role":"symbol","abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStall(_:)":{"title":"playerDidStall(_:)","navigatorTitle":[{"text":"playerDidStall:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerDidStall"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Плеер перешел в состояние "},{"code":"stall","type":"codeVoice"},{"type":"text","text":". Если трансляция, стоит актуализировать статус "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStall(_:)","url":"\/documentation\/ovkit\/playereventlistener\/playerdidstall(_:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"role":"symbol","title":"LiveStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LiveStatus","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","url":"\/documentation\/ovkit\/livestatus","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","url":"\/documentation\/ovkit\/playerview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"playerDidStall:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playerDidStall:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"playerDidStall:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"OVKPlayerEventListener","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStall(_:)\/title","value":"playerDidStall:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStall(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerDidStall:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","op":"replace","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}