{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didsaveplaytimeat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didsaveplaytimeat:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSavePlayTimeAt:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", ","kind":"text"},{"text":"didSavePlayTimeAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, от которого пришло событие."}]}]},{"name":"time","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время, на котором закончилось воспроизведение."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызывается, если включен флаг "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop","isActive":true},{"type":"text","text":", как индикация того,"},{"type":"text","text":" "},{"type":"text","text":"что плеер решил сохранить текущее время воспроизведения для последующего старта с него."}]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)player:didSavePlayTimeAt:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didSavePlayTimeAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"title":"player(_:didSavePlayTimeAt:)","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"player:didSavePlayTimeAt:"}]},"abstract":[{"type":"text","text":"Плеер сохранил просмотренное время видеозаписи."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didSavePlayTimeAt:)":{"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didsaveplaytimeat:)","title":"player(_:didSavePlayTimeAt:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSavePlayTimeAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didSavePlayTimeAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"abstract":[{"text":"Плеер сохранил просмотренное время видеозаписи.","type":"text"}],"navigatorTitle":[{"text":"player:didSavePlayTimeAt:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/savesPlaybackTimeOnStop":{"title":"savesPlaybackTimeOnStop","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop","navigatorTitle":[{"text":"savesPlaybackTimeOnStop","kind":"identifier"}],"type":"topic","abstract":[{"text":"Сохранять время воспроизведения для видео, на котором было остановлено проигрывание.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/playerview\/savesplaybacktimeonstop","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savesPlaybackTimeOnStop","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerEventListener"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerEventListener"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","title":"PlayerEventListener","url":"\/documentation\/ovkit\/playereventlistener","abstract":[{"type":"text","text":"Протокол для получения событий от плеера."}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"player:didSavePlayTimeAt:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didSavePlayTimeAt:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"player:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSavePlayTimeAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"time"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, от которого пришло событие.","type":"text"}]}]},{"name":"time","content":[{"type":"paragraph","inlineContent":[{"text":"Время, на котором закончилось воспроизведение.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSavePlayTimeAt:)\/title","op":"replace","value":"player:didSavePlayTimeAt:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSavePlayTimeAt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:didSavePlayTimeAt:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/title","op":"replace","value":"savesPlaybackTimeOnStop"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/fragments","op":"replace","value":[{"kind":"identifier","text":"savesPlaybackTimeOnStop"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","op":"replace","value":"OVKPlayerEventListener"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}