{"metadata":{"navigatorTitle":[{"text":"player:didMute:userInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didMute","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"title":"player(_:didMute:userInitiated:)","symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)player:didMute:userInitiated:","role":"symbol","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didMute:userInitiated:)"},"abstract":[{"text":"Плеер включил или отключил звук в видео.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didMute"},{"kind":"text","text":" "},{"kind":"internalParam","text":"muted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", статус звука в котором изменился."}],"type":"paragraph"}],"name":"playerView"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" значит, звук был выключен. Иначе - включен.","type":"text"}],"type":"paragraph"}],"name":"muted"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Произошло ли изменение в результате нажатия пользователя на контрол."}]}],"name":"userInitiated"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didmute:userinitiated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playereventlistener\/player(_:didmute:userinitiated:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didMute:userInitiated:)":{"abstract":[{"text":"Плеер включил или отключил звук в видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didMute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didmute:userinitiated:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didMute:userInitiated:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didMute:userInitiated:)","kind":"symbol","role":"symbol","title":"player(_:didMute:userInitiated:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"title":"PlayerEventListener","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"url":"\/documentation\/ovkit\/playereventlistener","navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","kind":"symbol","abstract":[{"type":"text","text":"Протокол для получения событий от плеера."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"title":"PlayerView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"player:didMute:userInitiated:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"player:didMute:userInitiated:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"player:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didMute:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"muted","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"userInitiated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"type":"text","text":", статус звука в котором изменился."}],"type":"paragraph"}]},{"name":"muted","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" значит, звук был выключен. Иначе - включен."}]}]},{"name":"userInitiated","content":[{"inlineContent":[{"type":"text","text":"Произошло ли изменение в результате нажатия пользователя на контрол."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didMute:userInitiated:)\/title","op":"replace","value":"player:didMute:userInitiated:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didMute:userInitiated:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:didMute:userInitiated:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","op":"replace","value":"OVKPlayerEventListener"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]}]}]}