{"metadata":{"title":"playerDidStartPlayingAd(_:)","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerDidStartPlayingAd","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"playerDidStartPlayingAd:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener(im)playerDidStartPlayingAd:","symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStartPlayingAd(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Плеер начал проигрывание рекламного ролика.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStartPlayingAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, от которого пришло событие."}]}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/playereventlistener\/playerdidstartplayingad(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playereventlistener\/playerdidstartplayingad(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"url":"\/documentation\/ovkit\/playereventlistener","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","title":"PlayerEventListener","abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStartPlayingAd(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStartPlayingAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStartPlayingAd"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"playerDidStartPlayingAd:"}],"title":"playerDidStartPlayingAd(_:)","role":"symbol","abstract":[{"type":"text","text":"Плеер начал проигрывание рекламного ролика."}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidstartplayingad(_:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerDidStartPlayingAd:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidStartPlayingAd:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"playerDidStartPlayingAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"inlineContent":[{"text":"Плеер, от которого пришло событие.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","op":"replace","value":"OVKPlayerEventListener"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerEventListener"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStartPlayingAd(_:)\/title","op":"replace","value":"playerDidStartPlayingAd:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStartPlayingAd(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerDidStartPlayingAd:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}