{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menucontents\/actions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menucontents\/actions"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MenuAction","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents\/actions","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"title":"actions","externalID":"c:@M@OVKit@objc(cs)OVKMenuContents(py)actions","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MenuAction","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"actions"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents"]]},"abstract":[{"text":"Набор действий (пунктов меню) включая действие отмены.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuContents/actions":{"role":"symbol","title":"actions","url":"\/documentation\/ovkit\/menucontents\/actions","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"actions"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents\/actions","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction","text":"MenuAction"},{"kind":"text","text":"]"}],"abstract":[{"text":"Набор действий (пунктов меню) включая действие отмены.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MenuContents":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","url":"\/documentation\/ovkit\/menucontents","abstract":[{"type":"text","text":"Модель содержимого меню"}],"navigatorTitle":[{"text":"MenuContents","kind":"identifier"}],"title":"MenuContents","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuContents","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"navigatorTitle":[{"text":"MenuAction","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Абстрактная модель пункта меню, содержащая данные для его показа."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","url":"\/documentation\/ovkit\/menuaction","kind":"symbol","title":"MenuAction","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuAction","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"actions","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"actions"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<OVKMenuAction *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"actions"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"actions","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents~1actions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"actions"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents~1actions\/fragments","op":"replace"},{"value":"OVKMenuContents","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuContents"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuContents"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/navigatorTitle","op":"replace"},{"value":"OVKMenuAction","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuAction"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuAction"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/navigatorTitle","op":"replace"}]}]}