{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loopbehavior\/always"]},{"paths":["\/documentation\/ovkit\/loopbehavior\/always"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@OVKit@E@OVKLoopBehavior@OVKLoopBehaviorAlways","navigatorTitle":[{"kind":"identifier","text":"OVKLoopBehaviorAlways"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"always"}],"title":"LoopBehavior.always","modules":[{"name":"OVKit"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Всегда повторять воспроизведение."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/always"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","navigatorTitle":[{"kind":"identifier","text":"LoopBehavior"}],"url":"\/documentation\/ovkit\/loopbehavior","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoopBehavior"}],"abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"title":"LoopBehavior"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/always":{"navigatorTitle":[{"text":"OVKLoopBehaviorAlways","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/always","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/loopbehavior\/always","title":"LoopBehavior.always","abstract":[{"text":"Всегда повторять воспроизведение.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"always","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"OVKLoopBehaviorAlways","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKLoopBehaviorAlways"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKLoopBehaviorAlways"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"OVKLoopBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title"},{"value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle","op":"replace"},{"value":"OVKLoopBehaviorAlways","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1always\/title"},{"value":[{"text":"OVKLoopBehaviorAlways","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1always\/fragments","op":"replace"}]}]}