{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loopbehavior\/auto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/loopbehavior\/auto"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@OVKit@E@OVKLoopBehavior@OVKLoopBehaviorAuto","roleHeading":"Case","title":"LoopBehavior.auto","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","interfaceLanguage":"swift"},"abstract":[{"text":"Поведение зависит от настройки ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/repeated":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"repeated","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","abstract":[],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/videotype\/repeated","kind":"symbol","title":"repeated"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"url":"\/documentation\/ovkit\/loopbehavior","title":"LoopBehavior","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","navigatorTitle":[{"kind":"identifier","text":"LoopBehavior"}],"abstract":[{"text":"Поведение плеера при завершении видео.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoopBehavior"}]},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/auto":{"url":"\/documentation\/ovkit\/loopbehavior\/auto","title":"LoopBehavior.auto","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKLoopBehaviorAuto"}],"abstract":[{"text":"Поведение зависит от настройки ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKLoopBehaviorAuto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLoopBehaviorAuto"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"repeated","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/title"},{"op":"replace","value":[{"text":"repeated","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/fragments"},{"op":"replace","value":"OVKLoopBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title"},{"op":"replace","value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/title","op":"replace","value":"OVKLoopBehaviorAuto"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKLoopBehaviorAuto"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}