{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/init(rawValue:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Initializer","externalID":"s:5OVKit12LoopBehaviorO8rawValueACSgSi_tcfc","symbolKind":"init","modules":[{"name":"OVKit"}],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loopbehavior\/init(rawvalue:)"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoopBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"LoopBehavior","kind":"identifier"}],"title":"LoopBehavior","role":"symbol","abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"type":"topic","url":"\/documentation\/ovkit\/loopbehavior","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/ovkit\/loopbehavior\/init(rawvalue:)","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/init(rawValue:)","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"value":"OVKLoopBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title","op":"replace"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}