{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loopbehavior\/never"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/loopbehavior\/never"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/never","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"never","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKLoopBehavior@OVKLoopBehaviorNever","modules":[{"name":"OVKit"}],"title":"LoopBehavior.never","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"OVKLoopBehaviorNever","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Никогда не повторять воспроизведение."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"never","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"navigatorTitle":[{"text":"LoopBehavior","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoopBehavior","kind":"identifier"}],"url":"\/documentation\/ovkit\/loopbehavior","type":"topic","abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","title":"LoopBehavior","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/never":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/never","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"never","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/loopbehavior\/never","title":"LoopBehavior.never","navigatorTitle":[{"kind":"identifier","text":"OVKLoopBehaviorNever"}],"abstract":[{"type":"text","text":"Никогда не повторять воспроизведение."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKLoopBehaviorNever","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"OVKLoopBehaviorNever","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLoopBehaviorNever"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title","value":"OVKLoopBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments","value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"op":"replace"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1never\/title","value":"OVKLoopBehaviorNever"},{"value":[{"text":"OVKLoopBehaviorNever","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1never\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}