{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/beginTracking(_:with:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoplayswitch\/begintracking(_:with:)"]},{"paths":["\/documentation\/ovkit\/autoplayswitch\/begintracking(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beginTracking"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)AutoplaySwitch(im)beginTrackingWithTouch:withEvent:","title":"beginTracking(_:with:)","role":"symbol","navigatorTitle":[{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"touch"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch":{"url":"\/documentation\/ovkit\/autoplayswitch","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AutoplaySwitch","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutoplaySwitch","kind":"identifier"}],"title":"AutoplaySwitch","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch/beginTracking(_:with:)":{"url":"\/documentation\/ovkit\/autoplayswitch\/begintracking(_:with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beginTracking"},{"kind":"text","text":"("},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"beginTracking(_:with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/beginTracking(_:with:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"beginTrackingWithTouch:withEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"beginTrackingWithTouch:"},{"kind":"text","text":"("},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"touch"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withEvent:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/title","value":"AutoplaySwitch"},{"value":[{"kind":"identifier","text":"AutoplaySwitch"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/navigatorTitle","value":[{"text":"AutoplaySwitch","kind":"identifier"}]},{"value":"beginTrackingWithTouch:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch~1beginTracking(_:with:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch~1beginTracking(_:with:)\/fragments"}]}]}