{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoplayswitch\/cancel()"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"title":"cancel()","role":"symbol","symbolKind":"method","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit14AutoplaySwitchC6cancelyyF"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/cancel()"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoplaySwitch","kind":"identifier"}],"navigatorTitle":[{"text":"AutoplaySwitch","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/autoplayswitch","title":"AutoplaySwitch"},"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch/cancel()":{"url":"\/documentation\/ovkit\/autoplayswitch\/cancel()","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/cancel()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"role":"symbol","type":"topic","title":"cancel()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/title","value":"AutoplaySwitch"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/fragments","value":[{"kind":"identifier","text":"AutoplaySwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/navigatorTitle","value":[{"kind":"identifier","text":"AutoplaySwitch"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}