{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endTracking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"touch"},{"text":": ","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":"?, ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoplayswitch\/endtracking(_:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/autoplayswitch\/endtracking(_:with:)"]}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)AutoplaySwitch(im)endTrackingWithTouch:withEvent:","title":"endTracking(_:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endTracking","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"endTrackingWithTouch:withEvent:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/endTracking(_:with:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch":{"navigatorTitle":[{"kind":"identifier","text":"AutoplaySwitch"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoplaySwitch"}],"title":"AutoplaySwitch","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/autoplayswitch","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AutoplaySwitch/endTracking(_:with:)":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"endTracking(_:with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoplaySwitch\/endTracking(_:with:)","url":"\/documentation\/ovkit\/autoplayswitch\/endtracking(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endTracking","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":"?, "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"endTrackingWithTouch:withEvent:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"endTrackingWithTouch:withEvent:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"endTrackingWithTouch:withEvent:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"endTrackingWithTouch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":" *) "},{"text":"touch","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEvent:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/title","value":"AutoplaySwitch","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/fragments","value":[{"text":"AutoplaySwitch","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch\/navigatorTitle","value":[{"kind":"identifier","text":"AutoplaySwitch"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch~1endTracking(_:with:)\/title","value":"endTrackingWithTouch:withEvent:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoplaySwitch~1endTracking(_:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"endTrackingWithTouch:withEvent:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}