{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(im)init","symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/init"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewParams/init":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkcoverviewparams\/init","title":"init","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/coverviewparams","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"title":"CoverViewParams"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKCoverViewParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace"}]}]}