{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/livestatus"]},{"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/livestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"LiveStatus"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/liveStatus","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Если есть значение отличное от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","type":"reference","isActive":true},{"text":", ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" должен показывать причины остановки трансляции."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)liveStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"role":"symbol","title":"liveStatus"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/started","abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}],"role":"symbol","title":"LiveStatus.started","navigatorTitle":[{"text":"OVKLiveStatusStarted","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"started"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"title":"LiveStatus","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveStatus"}],"navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","url":"\/documentation\/ovkit\/livestatus","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"type":"topic","title":"CoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewParams/liveStatus":{"kind":"symbol","url":"\/documentation\/ovkit\/ovkcoverviewparams\/livestatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/liveStatus","role":"symbol","abstract":[{"text":"Если есть значение отличное от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" должен показывать причины остановки трансляции."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}],"navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"title":"liveStatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"liveStatus","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"liveStatus","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"OVKLiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"},{"text":" ","kind":"text"},{"text":"liveStatus","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title","op":"replace","value":"OVKLiveStatusStarted"},{"value":[{"kind":"identifier","text":"OVKLiveStatusStarted"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"value":[{"kind":"identifier","text":"OVKLiveStatus"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","op":"replace"},{"op":"replace","value":"OVKCoverViewParams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"liveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1liveStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1liveStatus\/fragments","value":[{"kind":"identifier","text":"liveStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}