{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/restriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/restriction"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)restriction","symbolKind":"property","role":"symbol","title":"restriction","navigatorTitle":[{"text":"restriction","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/restriction","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"abstract":[{"type":"text","text":"Если есть значение, "},{"type":"codeVoice","code":"CoverView"},{"text":" должен быть о снятии ограничений.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewParams/restriction":{"url":"\/documentation\/ovkit\/ovkcoverviewparams\/restriction","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/restriction","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restriction"},{"text":": ","kind":"text"},{"text":"VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"restriction","navigatorTitle":[{"kind":"identifier","text":"restriction"}],"abstract":[{"text":"Если есть значение, ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":" должен быть о снятии ограничений."}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","title":"VideoRestrictionType","url":"\/documentation\/ovkit\/videorestrictiontype","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"url":"\/documentation\/ovkit\/coverviewparams","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewParams"}],"type":"topic","title":"CoverViewParams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"restriction"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"restriction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"id<OVKVideoRestrictionType>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restriction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"restriction","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1restriction\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1restriction\/fragments","value":[{"kind":"identifier","text":"restriction"}],"op":"replace"},{"value":"OVKVideoRestrictionType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}]},{"value":"OVKCoverViewParams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}