{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/startTime","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"role":"symbol","title":"startTime","externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)startTime"},"abstract":[{"type":"text","text":"Будет актуален, если значение "},{"type":"codeVoice","code":"liveStatus"},{"type":"text","text":" равно "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","isActive":true,"type":"reference"},{"text":". Приходит в формате unix timestamp.","type":"text"},{"type":"text","text":" "},{"text":"Если значение равно нулю — время начала трансляции не известно.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/starttime"]},{"paths":["\/documentation\/ovkit\/ovkcoverviewparams\/starttime"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewParams/startTime":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/startTime","navigatorTitle":[{"text":"startTime","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkcoverviewparams\/starttime","abstract":[{"type":"text","text":"Будет актуален, если значение "},{"code":"liveStatus","type":"codeVoice"},{"text":" равно ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming"},{"type":"text","text":". Приходит в формате unix timestamp."},{"type":"text","text":" "},{"type":"text","text":"Если значение равно нулю — время начала трансляции не известно."}],"kind":"symbol","title":"startTime","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"type":"topic","title":"CoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/upcoming":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/upcoming","abstract":[{"type":"text","text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать."}],"role":"symbol","title":"LiveStatus.upcoming","navigatorTitle":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upcoming","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"startTime","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"startTime","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1startTime\/title","value":"startTime","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewParams~1startTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"startTime"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","op":"replace","value":"OVKCoverViewParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/title","value":"OVKLiveStatusUpcoming"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/fragments","value":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"op":"replace"}]}]}