{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadVideo","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"reloadVideo","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate(im)reloadVideo","title":"reloadVideo()","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reloadVideo","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Стоит вызывать только в случае возникновения ошибки воспроизведения или изменения статуса трансляции."}]}],"kind":"content"}],"abstract":[{"text":"Перезагрузка видео.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/reloadVideo()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","required":true,"abstract":[{"text":"Перезагрузка видео.","type":"text"}],"url":"\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()","kind":"symbol","title":"reloadVideo()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reloadVideo"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadVideo","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"role":"symbol","url":"\/documentation\/ovkit\/covercontrolsdelegate","abstract":[{"type":"text","text":"Делегат, через который "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":" могут выполнять действия.","type":"text"}],"title":"CoverControlsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverControlsDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","kind":"symbol","navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"abstract":[],"url":"\/documentation\/ovkit\/coverview","kind":"symbol","title":"CoverView","type":"topic","role":"symbol","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"reloadVideo","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reloadVideo"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"reloadVideo","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"reloadVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reloadVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title","value":"OVKCoverControlsDelegate","op":"replace"},{"op":"replace","value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle","op":"replace"}]}]}