{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/replayVideo()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"replayVideo()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"replayVideo","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate(im)replayVideo","modules":[{"name":"OVKit"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"replayVideo"}]},"abstract":[{"text":"Проиграть видео сначала.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/covercontrolsdelegate\/replayvideo()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/covercontrolsdelegate\/replayvideo()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"replayVideo","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Стоит вызывать только после окончания воспроизведения."}]}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"url":"\/documentation\/ovkit\/coverview","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"title":"CoverView","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/replayVideo()":{"title":"replayVideo()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/replayVideo()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"replayVideo","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Проиграть видео сначала.","type":"text"}],"navigatorTitle":[{"text":"replayVideo","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/covercontrolsdelegate\/replayvideo()","required":true},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverControlsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"CoverControlsDelegate","abstract":[{"text":"Делегат, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"type":"text","text":" могут выполнять действия."}],"type":"topic","url":"\/documentation\/ovkit\/covercontrolsdelegate"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"replayVideo","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"replayVideo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"replayVideo"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"replayVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1replayVideo()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"replayVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1replayVideo()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title","value":"OVKCoverControlsDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle","value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}],"op":"replace"}]}]}