{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkstatshandler\/context"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkstatshandler\/context"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKStatsHandler(py)context","title":"context","navigatorTitle":[{"kind":"identifier","text":"context"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandler\/context","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatsContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Будет установлен после добавления в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"type":"topic","title":"StatsCollector","url":"\/documentation\/ovkit\/statscollector","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"или переходах в PiP и fullscreen."}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKStatsHandler/context":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatsContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"},{"kind":"text","text":"?"}],"type":"topic","title":"context","url":"\/documentation\/ovkit\/ovkstatshandler\/context","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandler\/context","abstract":[{"type":"text","text":"Будет установлен после добавления в "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"context"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandler"}],"type":"topic","title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"type":"text","text":" после добавления нового "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsContext","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext","title":"StatsContext","navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"context","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"context","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"OVKStatsContext","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"},{"text":" * ","kind":"text"},{"text":"context","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandler~1context\/title","value":"context","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandler~1context\/fragments","op":"replace","value":[{"kind":"identifier","text":"context"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"}]}]}