{"abstract":[{"type":"text","text":"Будет установлено после добавления в "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkstatshandler\/statistics"]},{"paths":["\/documentation\/ovkit\/ovkstatshandler\/statistics"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","title":"statistics","required":true,"externalID":"c:@M@OVKit@objc(pl)OVKStatsHandler(py)statistics","modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statistics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","text":"StatsHandlerContext","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"statistics","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandler\/statistics","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"text":"StatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"url":"\/documentation\/ovkit\/statscollector","type":"topic","title":"StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/video","abstract":[],"type":"topic","title":"Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"abstract":[{"text":"Набор свойств, к которому может обращаться ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"StatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerContext","kind":"identifier"}],"navigatorTitle":[{"text":"StatsHandlerContext","kind":"identifier"}],"url":"\/documentation\/ovkit\/statshandlercontext","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKStatsHandler/statistics":{"abstract":[{"type":"text","text":"Будет установлено после добавления в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"statistics","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"statistics"}],"url":"\/documentation\/ovkit\/ovkstatshandler\/statistics","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandler\/statistics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statistics","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","text":"StatsHandlerContext"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"События логирования будут вызваны на специальной background очереди."},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"url":"\/documentation\/ovkit\/statshandler","type":"topic","title":"StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"statistics","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"statistics","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","text":"OVKStatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"statistics","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKStatsHandlerContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandler~1statistics\/title","op":"replace","value":"statistics"},{"value":[{"text":"statistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandler~1statistics\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}