{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/supplementaryadviewstyle\/==(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.==(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Operator","modules":[{"name":"OVKit"}],"extendedModule":"OVKit","externalID":"s:5OVKit24SupplementaryAdViewStyleC2eeoiySbAC_ACtFZ","title":"==(_:_:)","symbolKind":"op","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","text":"SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","text":"SupplementaryAdViewStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/==(_:_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","abstract":[{"text":"Стиль дополнительного представления для CTA-контрола рекламы - ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdViewStyle"}],"navigatorTitle":[{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"type":"topic","title":"SupplementaryAdViewStyle","url":"\/documentation\/ovkit\/supplementaryadviewstyle","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/==(_:_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/==(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier","text":"SupplementaryAdViewStyle"},{"text":", ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadviewstyle\/==(_:_:)","title":"==(_:_:)","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"role":"symbol","url":"\/documentation\/ovkit\/supplementaryadview","kind":"symbol","title":"SupplementaryAdView","abstract":[{"type":"text","text":"Представление для CTA-контрола рекламы."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdView"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdView"}]}},"variantOverrides":[{"patch":[{"value":"OVKSupplementaryAdView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}