{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadviewstyle\/buttoninsets"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/buttonInsets"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"]]},"metadata":{"roleHeading":"Instance Property","title":"buttonInsets","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit24SupplementaryAdViewStyleC12buttonInsetsSo06UIEdgeG0Vvp","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Определяют расстояния от границ кнопки до её содержимого, например, текста или иконки."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Отступы кнопки внутри рекламного представления."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/buttonInsets":{"title":"buttonInsets","role":"symbol","url":"\/documentation\/ovkit\/supplementaryadviewstyle\/buttoninsets","kind":"symbol","abstract":[{"text":"Отступы кнопки внутри рекламного представления.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/buttonInsets","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"topic","title":"SupplementaryAdView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdView"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdView"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"navigatorTitle":[{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","url":"\/documentation\/ovkit\/supplementaryadviewstyle","kind":"symbol","abstract":[{"type":"text","text":"Стиль дополнительного представления для CTA-контрола рекламы - "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"type":"topic","role":"symbol","title":"SupplementaryAdViewStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"SupplementaryAdView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"text":"SupplementaryAdView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdView"}]}]}]}