{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadviewstyle\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"OVKit"}],"role":"collectionGroup"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"]]},"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/!=(_:_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/==(_:_:)"],"anchor":"Operators"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/supplementaryadviewstyle\/!=(_:_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/==(_:_:)":{"role":"symbol","title":"==(_:_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/==(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"==","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/supplementaryadviewstyle\/==(_:_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"url":"\/documentation\/ovkit\/supplementaryadviewstyle","abstract":[{"text":"Стиль дополнительного представления для CTA-контрола рекламы - ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdViewStyle"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","title":"SupplementaryAdViewStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdViewStyle"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"role":"symbol","title":"SupplementaryAdView","type":"topic","navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadview","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"OVKSupplementaryAdView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}