{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Определяет общий размер иконки, так как иконка всегда отображается в форме круга.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/imageRadius"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit24SupplementaryAdViewStyleC11imageRadius14CoreFoundation7CGFloatVvp","symbolKind":"property","title":"imageRadius","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadviewstyle\/imageradius"]}],"abstract":[{"text":"Радиус иконки.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/imageRadius":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/imageRadius","url":"\/documentation\/ovkit\/supplementaryadviewstyle\/imageradius","role":"symbol","kind":"symbol","title":"imageRadius","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"Радиус иконки.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdViewStyle"}],"abstract":[{"type":"text","text":"Стиль дополнительного представления для CTA-контрола рекламы - "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdViewStyle"}],"url":"\/documentation\/ovkit\/supplementaryadviewstyle","title":"SupplementaryAdViewStyle"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementaryAdView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadview","title":"SupplementaryAdView"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"OVKSupplementaryAdView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}