{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/init(edgeInsets:buttonInsets:imageRadius:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buttonInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"OVKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"edgeInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"buttonInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(edgeInsets:buttonInsets:imageRadius:)","externalID":"s:5OVKit24SupplementaryAdViewStyleC10edgeInsets06buttonG011imageRadiusACSo06UIEdgeG0V_AH14CoreFoundation7CGFloatVtcfc"},"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadviewstyle\/init(edgeinsets:buttoninsets:imageradius:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"topic","title":"SupplementaryAdView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdView"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdView"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle/init(edgeInsets:buttonInsets:imageRadius:)":{"url":"\/documentation\/ovkit\/supplementaryadviewstyle\/init(edgeinsets:buttoninsets:imageradius:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buttonInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle\/init(edgeInsets:buttonInsets:imageRadius:)","title":"init(edgeInsets:buttonInsets:imageRadius:)","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"navigatorTitle":[{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","url":"\/documentation\/ovkit\/supplementaryadviewstyle","kind":"symbol","abstract":[{"type":"text","text":"Стиль дополнительного представления для CTA-контрола рекламы - "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdViewStyle","kind":"identifier"}],"type":"topic","role":"symbol","title":"SupplementaryAdViewStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"SupplementaryAdView"},{"value":[{"kind":"identifier","text":"SupplementaryAdView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementaryAdView"}],"op":"replace"}]}]}