{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPreviewPlayButtonBehavior\/withoutAutoplay","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withoutAutoplay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withoutautoplay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withoutautoplay"]}],"abstract":[{"text":"Режим работы кнопки при недоступном ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(py)withoutAutoplay","role":"symbol","title":"withoutAutoplay","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"withoutAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"withoutAutoplay","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"title":"PreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","abstract":[{"text":"Режим работы кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Play"}]},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"navigatorTitle":[{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Поведение кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"url":"\/documentation\/ovkit\/previewplaybuttonbehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"title":"PreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPreviewPlayButtonBehavior/withoutAutoplay":{"title":"withoutAutoplay","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"withoutAutoplay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode"}],"kind":"symbol","navigatorTitle":[{"text":"withoutAutoplay","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withoutautoplay","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPreviewPlayButtonBehavior\/withoutAutoplay","abstract":[{"type":"text","text":"Режим работы кнопки при недоступном "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"withoutAutoplay","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"withoutAutoplay"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"OVKPreviewPlayButtonMode","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"},{"text":" ","kind":"text"},{"text":"withoutAutoplay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPreviewPlayButtonMode","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title"},{"value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments"},{"op":"replace","value":"OVKPreviewPlayButtonBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}]},{"value":"withoutAutoplay","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPreviewPlayButtonBehavior~1withoutAutoplay\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPreviewPlayButtonBehavior~1withoutAutoplay\/fragments","value":[{"text":"withoutAutoplay","kind":"identifier"}]}]}]}