{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPreviewPlayButtonBehavior\/withAutoplay","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"withAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","text":"PreviewPlayButtonMode"}]}]}],"kind":"symbol","abstract":[{"text":"Режим работы кнопки при доступном ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Autoplay"}]},{"type":"text","text":"."}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior(py)withAutoplay","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withAutoplay"}],"title":"withAutoplay","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"withAutoplay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode"}]},"variants":[{"paths":["\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withautoplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withautoplay"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"abstract":[{"type":"text","text":"Поведение кнопки "},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"title":"PreviewPlayButtonBehavior","url":"\/documentation\/ovkit\/previewplaybuttonbehavior","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonBehavior"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPreviewPlayButtonBehavior/withAutoplay":{"abstract":[{"type":"text","text":"Режим работы кнопки при доступном "},{"inlineContent":[{"type":"text","text":"Autoplay"}],"type":"emphasis"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPreviewPlayButtonBehavior\/withAutoplay","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"withAutoplay"}],"title":"withAutoplay","url":"\/documentation\/ovkit\/ovkpreviewplaybuttonbehavior\/withautoplay","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"withAutoplay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","text":"PreviewPlayButtonMode"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","type":"topic","navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}],"abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"title":"PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"withAutoplay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"withAutoplay"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","text":"OVKPreviewPlayButtonMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAutoplay"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","value":"OVKPreviewPlayButtonBehavior","op":"replace"},{"op":"replace","value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPreviewPlayButtonBehavior~1withAutoplay\/title","value":"withAutoplay"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPreviewPlayButtonBehavior~1withAutoplay\/fragments","value":[{"kind":"identifier","text":"withAutoplay"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","value":"OVKPreviewPlayButtonMode"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}