{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableIdleTimer"},{"kind":"text","text":"()"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/disableIdleTimer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Необходимо отключить автоблокировку устройства по таймауту."}],"variants":[{"paths":["\/documentation\/ovkit\/idletimermanager\/disableidletimer()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/idletimermanager\/disableidletimer()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKIdleTimerManager(im)disableIdleTimer","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disableIdleTimer"},{"kind":"text","text":"()"}],"role":"symbol","required":true,"modules":[{"name":"OVKit"}],"symbolKind":"method","navigatorTitle":[{"text":"disableIdleTimer","kind":"identifier"}],"title":"disableIdleTimer()"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager/disableIdleTimer()":{"abstract":[{"text":"Необходимо отключить автоблокировку устройства по таймауту.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableIdleTimer","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"disableIdleTimer"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/disableIdleTimer()","url":"\/documentation\/ovkit\/idletimermanager\/disableidletimer()","type":"topic","required":true,"role":"symbol","title":"disableIdleTimer()"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","url":"\/documentation\/ovkit\/idletimermanager","title":"IdleTimerManager","abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"disableIdleTimer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableIdleTimer"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableIdleTimer"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"disableIdleTimer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1disableIdleTimer()\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1disableIdleTimer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"disableIdleTimer","kind":"identifier"}]},{"value":"OVKIdleTimerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title","op":"replace"},{"value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}]}]}]}