{"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"required":true,"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"enableIdleTimerIfNeeded"}],"role":"symbol","title":"enableIdleTimerIfNeeded()","externalID":"c:@M@OVKit@objc(pl)OVKIdleTimerManager(im)enableIdleTimerIfNeeded","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableIdleTimerIfNeeded"},{"kind":"text","text":"()"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"]]},"variants":[{"paths":["\/documentation\/ovkit\/idletimermanager\/enableidletimerifneeded()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/idletimermanager\/enableidletimerifneeded()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableIdleTimerIfNeeded","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/enableIdleTimerIfNeeded()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Включает автоблокировку устройства по таймауту, если она не требуется для других целей в приложении."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager/enableIdleTimerIfNeeded()":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"enableIdleTimerIfNeeded"}],"url":"\/documentation\/ovkit\/idletimermanager\/enableidletimerifneeded()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/enableIdleTimerIfNeeded()","title":"enableIdleTimerIfNeeded()","abstract":[{"text":"Включает автоблокировку устройства по таймауту, если она не требуется для других целей в приложении.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableIdleTimerIfNeeded"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","url":"\/documentation\/ovkit\/idletimermanager","kind":"symbol","type":"topic","abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"role":"symbol","title":"IdleTimerManager"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"enableIdleTimerIfNeeded","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableIdleTimerIfNeeded","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableIdleTimerIfNeeded","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1enableIdleTimerIfNeeded()\/title","value":"enableIdleTimerIfNeeded","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1enableIdleTimerIfNeeded()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableIdleTimerIfNeeded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title","value":"OVKIdleTimerManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}