{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/additionalText"},"abstract":[{"text":"Дополнительный текст CTA-блока.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/additionaltext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/additionaltext"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"additionalText","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetCallToActionData(py)additionalText","title":"additionalText"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCallToActionData"}],"title":"MyTargetCallToActionData","url":"\/documentation\/ovkit\/mytargetcalltoactiondata","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Данные, которые необходимы для отображения CTA-блока в баннере."}],"role":"symbol","navigatorTitle":[{"text":"MyTargetCallToActionData","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/additionalText":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/additionalText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"required":true,"title":"additionalText","type":"topic","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/additionaltext","kind":"symbol","abstract":[{"type":"text","text":"Дополнительный текст CTA-блока."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalText"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"additionalText"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"additionalText"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"additionalText","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title","op":"replace","value":"MyTargetCallToActionData"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetCallToActionData"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetCallToActionData"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1additionalText\/title","op":"replace","value":"additionalText"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1additionalText\/fragments","op":"replace","value":[{"kind":"identifier","text":"additionalText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}