{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Текст на кнопке CTA.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonText"},"metadata":{"required":true,"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"buttonText","navigatorTitle":[{"text":"buttonText","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetCallToActionData(py)buttonText","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/buttontext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/buttontext"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"title":"MyTargetCallToActionData","role":"symbol","navigatorTitle":[{"text":"MyTargetCallToActionData","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetCallToActionData","kind":"identifier"}],"abstract":[{"text":"Данные, которые необходимы для отображения CTA-блока в баннере.","type":"text"}],"url":"\/documentation\/ovkit\/mytargetcalltoactiondata","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/buttonText":{"required":true,"title":"buttonText","abstract":[{"text":"Текст на кнопке CTA.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/buttontext","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"buttonText","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonText","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"buttonText","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"buttonText","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"buttonText"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title","value":"MyTargetCallToActionData"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments","value":[{"text":"MyTargetCallToActionData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle","value":[{"text":"MyTargetCallToActionData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonText\/title","value":"buttonText"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonText\/fragments","value":[{"text":"buttonText","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}