{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonColor","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetCallToActionData(py)buttonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"buttonColor","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buttonColor"}]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/buttoncolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/buttoncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Цвет кнопки CTA.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCallToActionData"}],"title":"MyTargetCallToActionData","url":"\/documentation\/ovkit\/mytargetcalltoactiondata","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Данные, которые необходимы для отображения CTA-блока в баннере."}],"role":"symbol","navigatorTitle":[{"text":"MyTargetCallToActionData","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/buttonColor":{"title":"buttonColor","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/buttoncolor","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"buttonColor"}],"kind":"symbol","abstract":[{"text":"Цвет кнопки CTA.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"buttonColor","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"buttonColor","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"buttonColor"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MyTargetCallToActionData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments"},{"op":"replace","value":[{"text":"MyTargetCallToActionData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonColor\/title","value":"buttonColor"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonColor\/fragments","value":[{"text":"buttonColor","kind":"identifier"}]}]}]}