{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_icon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetImageData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetCallToActionData(py)ovkit_icon","roleHeading":"Instance Property","navigatorTitle":[{"text":"ovkit_icon","kind":"identifier"}],"modules":[{"name":"OVKit"}],"required":true,"title":"ovkit_icon"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/ovkit_icon"},"abstract":[{"text":"Иконка CTA-блока.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/ovkit_icon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata\/ovkit_icon"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData","text":"MyTargetImageData"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"kind":"symbol","title":"MyTargetCallToActionData","navigatorTitle":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"abstract":[{"text":"Данные, которые необходимы для отображения CTA-блока в баннере.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetCallToActionData","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetcalltoactiondata","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData":{"navigatorTitle":[{"kind":"identifier","text":"MyTargetImageData"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetimagedata","kind":"symbol","abstract":[{"text":"Графические данные.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData","title":"MyTargetImageData","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetImageData"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/ovkit_icon":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_icon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData","text":"MyTargetImageData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/ovkit_icon","kind":"symbol","navigatorTitle":[{"text":"ovkit_icon","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/ovkit_icon","title":"ovkit_icon","abstract":[{"text":"Иконка CTA-блока.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ovkit_icon","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ovkit_icon"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetImageData","text":"id<MyTargetImageData>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_icon"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MyTargetCallToActionData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle","op":"replace"},{"value":"MyTargetImageData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetImageData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetImageData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/navigatorTitle","op":"replace"},{"value":"ovkit_icon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1ovkit_icon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ovkit_icon"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1ovkit_icon\/fragments","op":"replace"}]}]}