{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"baseConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"PrefetcherConfig"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/baseConfig"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/baseconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/baseconfig"]}],"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"baseConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"}],"navigatorTitle":[{"text":"baseConfig","kind":"identifier"}],"title":"baseConfig","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)baseConfig","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PrefetcherConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"role":"symbol","kind":"symbol","title":"PrefetcherConfig","url":"\/documentation\/ovkit\/prefetcherconfig","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"url":"\/documentation\/ovkit\/listprefetcherconfig","title":"ListPrefetcherConfig","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/baseConfig":{"url":"\/documentation\/ovkit\/listprefetcherconfig\/baseconfig","navigatorTitle":[{"kind":"identifier","text":"baseConfig"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"baseConfig","kind":"identifier"},{"kind":"text","text":": "},{"text":"PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","kind":"typeIdentifier"}],"title":"baseConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/baseConfig","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"baseConfig","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"baseConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"OVKPrefetcherConfig"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"baseConfig"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","op":"replace","value":"OVKPrefetcherConfig"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"op":"replace","value":"baseConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1baseConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"baseConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1baseConfig\/fragments"}]}]}