{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Контейнер кеша. Задается в случае, если нужно использовать не общий кеш."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/container"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"container","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CacheContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/container"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/container"]}],"metadata":{"navigatorTitle":[{"text":"container","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"container","symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"container","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?","kind":"text"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)container"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","kind":"symbol","role":"symbol","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherConfig"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"title":"ListPrefetcherConfig","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CacheContainer"}],"title":"CacheContainer","url":"\/documentation\/ovkit\/cachecontainer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainer"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/container":{"url":"\/documentation\/ovkit\/listprefetcherconfig\/container","abstract":[{"text":"Контейнер кеша. Задается в случае, если нужно использовать не общий кеш.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/container","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"container"}],"title":"container","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"container","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"container"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","text":"OVKCacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"container","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","op":"replace"},{"value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","op":"replace"},{"value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle","op":"replace"},{"value":"OVKCacheContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKCacheContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments","op":"replace"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle","op":"replace"},{"value":"container","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1container\/title","op":"replace"},{"value":[{"text":"container","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1container\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}