{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","kind":"typeIdentifier","text":"PrefetcherConfig"},{"kind":"text","text":" = PrefetcherConfig(), "},{"kind":"externalParam","text":"fastCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 5, "},{"kind":"externalParam","text":"slowCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 2, "},{"kind":"externalParam","text":"poorCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 1, "},{"kind":"externalParam","text":"normalBandwidthThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" = 2500000, "},{"kind":"externalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" = 1300000, "},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","kind":"typeIdentifier","text":"CacheContainer"},{"kind":"text","text":"? = nil)"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:container:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:container:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"PrefetcherConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fastCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slowCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"poorCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"normalBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","title":"init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(im)initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:","kind":"identifier"}],"symbolKind":"init"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}],"title":"PrefetcherConfig","kind":"symbol","role":"symbol","abstract":[{"text":"Конфигурация с базовыми опциями работы префетчера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetcherConfig"}],"url":"\/documentation\/ovkit\/prefetcherconfig"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"url":"\/documentation\/ovkit\/listprefetcherconfig","kind":"symbol","title":"ListPrefetcherConfig","navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainer"}],"navigatorTitle":[{"kind":"identifier","text":"CacheContainer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","url":"\/documentation\/ovkit\/cachecontainer","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"CacheContainer"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"baseConfig","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fastCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slowCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"poorCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"normalBandwidthThreshold"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"container"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","kind":"typeIdentifier","text":"CacheContainer"},{"kind":"text","text":"?)"}],"title":"init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)","url":"\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:container:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBaseConfig:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","kind":"typeIdentifier","text":"OVKPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"baseConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"fastCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fastCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"slowCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"slowCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"poorCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalBandwidthThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"normalBandwidthThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorBandwidthThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"container:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","kind":"typeIdentifier","text":"OVKCacheContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"container"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/navigatorTitle"},{"value":"OVKListPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title","op":"replace","value":"OVKCacheContainer"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCacheContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle"},{"op":"replace","value":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}