{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:)"]},{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"PrefetcherConfig"},{"kind":"text","text":", "},{"text":"fastCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"slowCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"poorCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"normalBandwidthThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(im)initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","title":"init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"baseConfig","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PrefetcherConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"},{"kind":"text","text":" = PrefetcherConfig(), "},{"kind":"externalParam","text":"fastCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 5, ","kind":"text"},{"kind":"externalParam","text":"slowCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 2, "},{"text":"poorCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" = 1, "},{"kind":"externalParam","text":"normalBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":" = 2500000, ","kind":"text"},{"text":"poorBandwidthThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" = 1300000)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","type":"topic","role":"symbol","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"kind":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ListPrefetcherConfig","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfig","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"PrefetcherConfig"},{"kind":"text","text":", "},{"text":"fastCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slowCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"poorCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"normalBandwidthThreshold"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"poorBandwidthThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":")","kind":"text"}],"title":"init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"navigatorTitle":[{"text":"PrefetcherConfig","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","url":"\/documentation\/ovkit\/prefetcherconfig","abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrefetcherConfig"}],"title":"PrefetcherConfig"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithBaseConfig:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"OVKPrefetcherConfig"},{"kind":"text","text":" *) "},{"text":"baseConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fastCount:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"fastCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"slowCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"slowCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorCount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"poorCount"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normalBandwidthThreshold:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"internalParam"},{"kind":"text","text":" "},{"text":"poorBandwidthThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"poorBandwidthThreshold"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKListPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"},{"value":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","value":"OVKPrefetcherConfig"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}