{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/normalbandwidththreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/normalbandwidththreshold"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/normalBandwidthThreshold","interfaceLanguage":"swift"},"abstract":[{"text":"Верхняя граница пропускной способности сети среднего качества.","type":"text"},{"text":" ","type":"text"},{"text":"Единицы измерения – ","type":"text"},{"type":"codeVoice","code":"bps"},{"text":", значение по умолчанию – ","type":"text"},{"type":"codeVoice","code":"2500000"},{"text":".","type":"text"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"normalBandwidthThreshold","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)normalBandwidthThreshold"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"title":"ListPrefetcherConfig","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ListPrefetcherConfig","kind":"identifier"}],"navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/normalBandwidthThreshold":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"normalBandwidthThreshold"}],"title":"normalBandwidthThreshold","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/normalBandwidthThreshold","url":"\/documentation\/ovkit\/listprefetcherconfig\/normalbandwidththreshold","abstract":[{"text":"Верхняя граница пропускной способности сети среднего качества.","type":"text"},{"text":" ","type":"text"},{"text":"Единицы измерения – ","type":"text"},{"type":"codeVoice","code":"bps"},{"text":", значение по умолчанию – ","type":"text"},{"type":"codeVoice","code":"2500000"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"normalBandwidthThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"op":"replace","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"},{"op":"replace","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle"},{"op":"replace","value":"normalBandwidthThreshold","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1normalBandwidthThreshold\/title"},{"op":"replace","value":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1normalBandwidthThreshold\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}