{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorCount","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poorCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/poorcount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig\/poorcount"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)poorCount","roleHeading":"Instance Property","role":"symbol","title":"poorCount","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"poorCount"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Количество видео для загрузки наперед при слабом интернете."},{"text":" ","type":"text"},{"type":"text","text":"Значение по умолчанию – "},{"code":"1","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"url":"\/documentation\/ovkit\/listprefetcherconfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ListPrefetcherConfig"}],"kind":"symbol","title":"ListPrefetcherConfig","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/poorCount":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorCount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorCount","type":"topic","role":"symbol","title":"poorCount","navigatorTitle":[{"text":"poorCount","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/poorcount","kind":"symbol","abstract":[{"type":"text","text":"Количество видео для загрузки наперед при слабом интернете."},{"type":"text","text":" "},{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"poorCount","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"poorCount","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poorCount"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle"},{"op":"replace","value":"poorCount","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorCount\/title"},{"value":[{"text":"poorCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorCount\/fragments"}]}]}