{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorBandwidthThreshold","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Верхняя граница пропускной способности сети плохого качества."},{"type":"text","text":" "},{"type":"text","text":"Единицы измерения – "},{"code":"bps","type":"codeVoice"},{"type":"text","text":", значение по умолчанию – "},{"code":"1300000","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"poorBandwidthThreshold","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)poorBandwidthThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/poorbandwidththreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/listprefetcherconfig\/poorbandwidththreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/poorBandwidthThreshold":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorBandwidthThreshold","url":"\/documentation\/ovkit\/listprefetcherconfig\/poorbandwidththreshold","title":"poorBandwidthThreshold","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poorBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"abstract":[{"text":"Верхняя граница пропускной способности сети плохого качества.","type":"text"},{"text":" ","type":"text"},{"text":"Единицы измерения – ","type":"text"},{"code":"bps","type":"codeVoice"},{"text":", значение по умолчанию – ","type":"text"},{"code":"1300000","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"url":"\/documentation\/ovkit\/listprefetcherconfig","title":"ListPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"poorBandwidthThreshold"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"poorBandwidthThreshold"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"poorBandwidthThreshold","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorBandwidthThreshold\/title","value":"poorBandwidthThreshold","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorBandwidthThreshold\/fragments","value":[{"kind":"identifier","text":"poorBandwidthThreshold"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle","op":"replace"}]}]}