{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangecellular"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangecellular"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchQualityRangeCellular"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"prefetchQualityRangeCellular","required":true,"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchQualityRangeCellular","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"}],"navigatorTitle":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPrefetchItem/prefetchQualityRangeCellular":{"title":"prefetchQualityRangeCellular","abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}],"navigatorTitle":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangecellular","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchQualityRangeCellular","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"title":"PrefetchItem","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QualityRange","kind":"identifier"}],"abstract":[{"type":"text","text":"Диапазон качества видео."}],"url":"\/documentation\/ovkit\/qualityrange","kind":"symbol","navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"title":"QualityRange","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"prefetchQualityRangeCellular","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"OVKQualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"text":" * ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchQualityRangeCellular\/title","value":"prefetchQualityRangeCellular"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchQualityRangeCellular\/fragments","value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem"},{"value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange"},{"value":[{"text":"OVKQualityRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments"}]}]}