{"abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchPreviews","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","required":true,"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchPreviews","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"]"}],"title":"prefetchPreviews","navigatorTitle":[{"text":"prefetchPreviews","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchpreviews"]},{"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchpreviews"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPrefetchItem/prefetchPreviews":{"role":"symbol","abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"required":true,"kind":"symbol","title":"prefetchPreviews","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchPreviews","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchPreviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"url":"\/documentation\/ovkit\/ovkprefetchitem\/prefetchpreviews","navigatorTitle":[{"kind":"identifier","text":"prefetchPreviews"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"url":"\/documentation\/ovkit\/prefetchitem","type":"topic","kind":"symbol","role":"symbol","title":"PrefetchItem"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"type":"topic","title":"ImageAssetType","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageAssetType"}],"abstract":[],"url":"\/documentation\/ovkit\/imageassettype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"prefetchPreviews","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"prefetchPreviews","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKImageAssetType>>"},{"text":" * ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"prefetchPreviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchPreviews\/title"},{"value":[{"kind":"identifier","text":"prefetchPreviews"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchPreviews\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","op":"replace","value":"OVKImageAssetType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"text":"OVKImageAssetType","kind":"identifier"}]}]}]}