{"metadata":{"role":"symbol","title":"prefetchQualityRangeWiFi","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeWiFi"},{"kind":"text","text":": "},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchQualityRangeWiFi","navigatorTitle":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}],"required":true,"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangewifi"]},{"paths":["\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangewifi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchQualityRangeWiFi","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","title":"QualityRange","url":"\/documentation\/ovkit\/qualityrange","abstract":[{"type":"text","text":"Диапазон качества видео."}],"navigatorTitle":[{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPrefetchItem/prefetchQualityRangeWiFi":{"abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}],"title":"prefetchQualityRangeWiFi","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchQualityRangeWiFi"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/ovkprefetchitem\/prefetchqualityrangewifi","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetchItem\/prefetchQualityRangeWiFi"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PrefetchItem","kind":"identifier"}],"abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"title":"PrefetchItem","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"prefetchQualityRangeWiFi"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"OVKQualityRange","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKQualityRange"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments"},{"value":"prefetchQualityRangeWiFi","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchQualityRangeWiFi\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetchItem~1prefetchQualityRangeWiFi\/fragments","op":"replace","value":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}]},{"value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"}]}]}