{"kind":"symbol","metadata":{"symbolKind":"property","title":"baseConfig","navigatorTitle":[{"kind":"identifier","text":"baseConfig"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)baseConfig","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"baseConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfig"},{"text":": ","kind":"text"},{"text":"PrefetcherConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/baseConfig"},"variants":[{"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/baseconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/baseconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcherConfig/baseConfig":{"role":"symbol","navigatorTitle":[{"text":"baseConfig","kind":"identifier"}],"title":"baseConfig","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"baseConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","text":"PrefetcherConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/baseConfig","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/ovklistprefetcherconfig\/baseconfig","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PrefetcherConfig","kind":"identifier"}],"title":"PrefetcherConfig","url":"\/documentation\/ovkit\/prefetcherconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"baseConfig"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"baseConfig","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OVKPrefetcherConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseConfig"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1baseConfig\/title","value":"baseConfig","op":"replace"},{"value":[{"text":"baseConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1baseConfig\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","value":"OVKPrefetcherConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments","value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}]}]}]}