{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/fastCount","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fastCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","title":"fastCount","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)fastCount","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"fastCount","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","abstract":[{"type":"text","text":"Количество видео для загрузки наперед при быстром интернете."},{"type":"text","text":" "},{"text":"Значение по умолчанию – ","type":"text"},{"type":"codeVoice","code":"5"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"fastCount","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/fastcount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/fastcount"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcherConfig/fastCount":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/fastCount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fastCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","url":"\/documentation\/ovkit\/ovklistprefetcherconfig\/fastcount","abstract":[{"type":"text","text":"Количество видео для загрузки наперед при быстром интернете."},{"type":"text","text":" "},{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"5"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fastCount"}],"title":"fastCount"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"fastCount"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fastCount"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fastCount"},{"text":";","kind":"text"}]}]}},{"value":"fastCount","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1fastCount\/title"},{"value":[{"kind":"identifier","text":"fastCount"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1fastCount\/fragments"},{"value":"OVKListPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}