{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/normalbandwidththreshold"]},{"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/normalbandwidththreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]}]}],"metadata":{"title":"normalBandwidthThreshold","navigatorTitle":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)normalBandwidthThreshold"},"abstract":[{"text":"Верхняя граница пропускной способности сети среднего качества.","type":"text"},{"text":" ","type":"text"},{"text":"Единицы измерения – ","type":"text"},{"code":"bps","type":"codeVoice"},{"type":"text","text":", значение по умолчанию – "},{"code":"2500000","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/normalBandwidthThreshold"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcherConfig/normalBandwidthThreshold":{"abstract":[{"type":"text","text":"Верхняя граница пропускной способности сети среднего качества."},{"type":"text","text":" "},{"type":"text","text":"Единицы измерения – "},{"code":"bps","type":"codeVoice"},{"type":"text","text":", значение по умолчанию – "},{"code":"2500000","type":"codeVoice"},{"text":".","type":"text"}],"title":"normalBandwidthThreshold","kind":"symbol","navigatorTitle":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/normalBandwidthThreshold","type":"topic","url":"\/documentation\/ovkit\/ovklistprefetcherconfig\/normalbandwidththreshold"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"normalBandwidthThreshold"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"normalBandwidthThreshold","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1normalBandwidthThreshold\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1normalBandwidthThreshold\/fragments","value":[{"text":"normalBandwidthThreshold","kind":"identifier"}],"op":"replace"},{"value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace"}]}]}