{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/poorcount"]},{"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/poorcount"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Количество видео для загрузки наперед при слабом интернете."},{"type":"text","text":" "},{"type":"text","text":"Значение по умолчанию – "},{"code":"1","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"poorCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]}],"metadata":{"title":"poorCount","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"poorCount","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)poorCount","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"poorCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/poorCount","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcherConfig/poorCount":{"title":"poorCount","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/poorCount","role":"symbol","type":"topic","abstract":[{"text":"Количество видео для загрузки наперед при слабом интернете.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"poorCount"}],"url":"\/documentation\/ovkit\/ovklistprefetcherconfig\/poorcount","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poorCount","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","type":"topic","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"poorCount","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"poorCount","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"poorCount","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1poorCount\/title","op":"replace","value":"poorCount"},{"op":"replace","value":[{"text":"poorCount","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1poorCount\/fragments"},{"op":"replace","value":"OVKListPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}