{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/poorbandwidththreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovklistprefetcherconfig\/poorbandwidththreshold"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"poorBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/poorBandwidthThreshold","interfaceLanguage":"swift"},"abstract":[{"text":"Верхняя граница пропускной способности сети плохого качества.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Единицы измерения – "},{"type":"codeVoice","code":"bps"},{"type":"text","text":", значение по умолчанию – "},{"code":"1300000","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"navigatorTitle":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig(py)poorBandwidthThreshold","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"poorBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"title":"poorBandwidthThreshold","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","role":"symbol","navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/listprefetcherconfig","title":"ListPrefetcherConfig"},"doc://onevideo.OVKit/documentation/OVKit/OVKListPrefetcherConfig/poorBandwidthThreshold":{"navigatorTitle":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovklistprefetcherconfig\/poorbandwidththreshold","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKListPrefetcherConfig\/poorBandwidthThreshold","abstract":[{"type":"text","text":"Верхняя граница пропускной способности сети плохого качества."},{"text":" ","type":"text"},{"text":"Единицы измерения – ","type":"text"},{"type":"codeVoice","code":"bps"},{"type":"text","text":", значение по умолчанию – "},{"type":"codeVoice","code":"1300000"},{"type":"text","text":"."}],"kind":"symbol","title":"poorBandwidthThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poorBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"poorBandwidthThreshold"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"poorBandwidthThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poorBandwidthThreshold"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1poorBandwidthThreshold\/title","value":"poorBandwidthThreshold"},{"value":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKListPrefetcherConfig~1poorBandwidthThreshold\/fragments"}]}]}