{"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline\/collectionview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/filmstriptimeline\/collectionview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/collectionView(_:cellForItemAt:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:cellForItemAt:)"},{"type":"text","text":"."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"}],"extendedModule":"OVKit","externalID":"c:@CM@OVKit@objc(cs)FilmStripTimeline(im)collectionView:cellForItemAtIndexPath:","title":"collectionView(_:cellForItemAt:)","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/collectionView(_:cellForItemAt:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/filmstriptimeline\/collectionview(_:cellforitemat:)","role":"symbol","kind":"symbol","abstract":[],"title":"collectionView(_:cellForItemAt:)","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/collectionView(_:cellForItemAt:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"url":"\/documentation\/ovkit\/filmstriptimeline","kind":"symbol","navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline","title":"FilmStripTimeline","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"collectionView:cellForItemAtIndexPath:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1collectionView(_:cellForItemAt:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1collectionView(_:cellForItemAt:)\/fragments"},{"op":"replace","value":"FilmStripTimeline","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FilmStripTimeline"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FilmStripTimeline"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}