{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:timeResolution:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline\/init(thumbnailprovider:timeresolution:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"init","externalID":"s:5OVKit17FilmStripTimelineC17thumbnailProvider14timeResolutionAcA09ThumbnailF0C_Sdtcfc","modules":[{"name":"OVKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeResolution","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(thumbnailProvider:timeResolution:)","roleHeading":"Initializer","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"role":"symbol","kind":"symbol","title":"FilmStripTimeline","abstract":[],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/filmstriptimeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"navigatorTitle":[{"kind":"identifier","text":"ThumbnailProvider"}],"title":"ThumbnailProvider","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"type":"topic","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailprovider"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/init(thumbnailProvider:timeResolution:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:timeResolution:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timeResolution","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(thumbnailProvider:timeResolution:)","url":"\/documentation\/ovkit\/filmstriptimeline\/init(thumbnailprovider:timeresolution:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"FilmStripTimeline","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FilmStripTimeline"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FilmStripTimeline"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle","op":"replace"},{"value":"OVKThumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace"},{"value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","op":"replace"},{"value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}