{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline\/init(thumbnailprovider:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"s:5OVKit17FilmStripTimelineC17thumbnailProviderAcA09ThumbnailF0C_tcfc","symbolKind":"init","role":"symbol","modules":[{"name":"OVKit"}],"title":"init(thumbnailProvider:)"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/init(thumbnailProvider:)":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/filmstriptimeline\/init(thumbnailprovider:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:)","type":"topic","title":"init(thumbnailProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/filmstriptimeline","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"title":"FilmStripTimeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"url":"\/documentation\/ovkit\/thumbnailprovider","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"title":"ThumbnailProvider","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"FilmStripTimeline","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FilmStripTimeline"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments","op":"replace"},{"value":[{"text":"FilmStripTimeline","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle","op":"replace"},{"value":"OVKThumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}