{"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@CM@OVKit@objc(cs)FilmStripTimeline(im)scrollViewDidEndDragging:willDecelerate:","extendedModule":"OVKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDragging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willDecelerate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"scrollViewDidEndDragging:willDecelerate:","kind":"identifier"}],"title":"scrollViewDidEndDragging(_:willDecelerate:)","roleHeading":"Instance Method","role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewDidEndDragging(_:willDecelerate:)"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier","text":"UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decelerate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidenddragging(_:willdecelerate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidenddragging(_:willdecelerate:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDragging(_:willDecelerate:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/filmstriptimeline","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"title":"FilmStripTimeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollViewDidEndDragging(_:willDecelerate:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDragging(_:willDecelerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"title":"scrollViewDidEndDragging(_:willDecelerate:)","type":"topic","url":"\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidenddragging(_:willdecelerate:)","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"scrollViewDidEndDragging:willDecelerate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewDidEndDragging:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier","text":"UIScrollView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDecelerate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"decelerate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title","op":"replace","value":"FilmStripTimeline"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments","op":"replace","value":[{"text":"FilmStripTimeline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle","op":"replace","value":[{"text":"FilmStripTimeline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDragging(_:willDecelerate:)\/title","op":"replace","value":"scrollViewDidEndDragging:willDecelerate:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDragging:willDecelerate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}