{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/stopCallback","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline\/stopcallback"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"sections":[],"metadata":{"title":"stopCallback","role":"symbol","externalID":"s:5OVKit17FilmStripTimelineC12stopCallbackySdcSgvp","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCallback","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"role":"symbol","kind":"symbol","title":"FilmStripTimeline","abstract":[],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/filmstriptimeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/stopCallback":{"url":"\/documentation\/ovkit\/filmstriptimeline\/stopcallback","abstract":[],"kind":"symbol","title":"stopCallback","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/stopCallback"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title","value":"FilmStripTimeline","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments","value":[{"kind":"identifier","text":"FilmStripTimeline"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle","value":[{"kind":"identifier","text":"FilmStripTimeline"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}