{"kind":"article","sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDecelerating(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidScroll(_:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/filmstriptimeline\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UIScrollViewDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"]]},"metadata":{"title":"UIScrollViewDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"OVKit"}],"role":"collectionGroup"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollViewDidEndDecelerating(_:)":{"role":"symbol","url":"\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidenddecelerating(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDecelerating(_:)","title":"scrollViewDidEndDecelerating(_:)","navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollViewDidEndDragging(_:willDecelerate:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDragging(_:willDecelerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"title":"scrollViewDidEndDragging(_:willDecelerate:)","type":"topic","url":"\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidenddragging(_:willdecelerate:)","role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/filmstriptimeline","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"title":"FilmStripTimeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollViewDidScroll(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewDidScroll(_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidScroll(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/filmstriptimeline\/scrollviewdidscroll(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDecelerating(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollViewDidScroll(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"scrollViewDidEndDecelerating:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDecelerating(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDecelerating(_:)\/fragments"},{"value":"scrollViewDidEndDragging:willDecelerate:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDragging(_:willDecelerate:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments"},{"value":"FilmStripTimeline","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title"},{"value":[{"text":"FilmStripTimeline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments"},{"value":[{"text":"FilmStripTimeline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle"},{"value":"scrollViewDidScroll:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidScroll(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1scrollViewDidScroll(_:)\/fragments"}]}]}