{"sections":[],"abstract":[{"text":"Делегат контролов. Устанавливать не нужно","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"controlsDelegate","externalID":"s:5OVKit26SupplementedAdControlsViewC16controlsDelegateAA0deG0_pSgvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ControlsViewDelegate","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"controlsDelegate"},{"text":": ","kind":"text"},{"text":"ControlsViewDelegate","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"⚠️ Свойство должно быть ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"weak"}]},{"text":"!","type":"text"}]}],"style":"warning"}]}],"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/controlsdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/controlsDelegate":{"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/controlsdelegate","abstract":[{"type":"text","text":"Делегат контролов. Устанавливать не нужно"}],"role":"symbol","title":"controlsDelegate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","text":"ControlsViewDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsDelegate"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","role":"symbol","abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}],"title":"ControlsViewDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ControlsViewDelegate"}],"navigatorTitle":[{"text":"ControlsViewDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"url":"\/documentation\/ovkit\/supplementedadcontrolsview","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupplementedAdControlsView"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","abstract":[],"role":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"title":"SupplementedAdControlsView"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"SupplementedAdControlsView"},{"value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SupplementedAdControlsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}