{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":", "},{"text":"shouldRecognizeSimultaneouslyWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"otherGestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView(im)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"shouldRecognizeSimultaneouslyWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","abstract":[],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)","role":"symbol","navigatorTitle":[{"text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","type":"topic","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview","abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"title":"SupplementedAdControlsView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gestureRecognizer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":" *) ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldRecognizeSimultaneouslyWithGestureRecognizer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"otherGestureRecognizer","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"OVKSupplementedAdControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]}]}]}