{"metadata":{"title":"handlePlayerTick()","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePlayerTick"},{"kind":"text","text":"()"}],"externalID":"s:5OVKit26SupplementedAdControlsViewC16handlePlayerTickyyF","symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handlePlayerTick()","interfaceLanguage":"swift"},"abstract":[{"text":"Вызывается периодически во время проигрывания видео.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePlayerTick","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/handleplayertick()"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/handlePlayerTick()":{"kind":"symbol","type":"topic","title":"handlePlayerTick()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePlayerTick"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handlePlayerTick()","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/handleplayertick()","abstract":[{"type":"text","text":"Вызывается периодически во время проигрывания видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"kind":"symbol","abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","title":"SupplementedAdControlsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementedAdControlsView"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupplementedAdControlsView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"value":"OVKSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}