{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/layoutSubviews()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","role":"symbol","title":"layoutSubviews()","externalID":"c:@M@OVKit@objc(cs)OVKSupplementedAdControlsView(im)layoutSubviews","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/layoutsubviews()"]},{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"kind":"symbol","abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","title":"SupplementedAdControlsView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementedAdControlsView"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupplementedAdControlsView"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/layoutSubviews()":{"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/layoutsubviews()","title":"layoutSubviews()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/layoutSubviews()","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"layoutSubviews","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"OVKSupplementedAdControlsView"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1layoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]}]}]}