{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/onItemShow(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onItemShow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"s:5OVKit26SupplementedAdControlsViewC10onItemShowyySSF","symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol","title":"onItemShow(_:)","roleHeading":"Instance Method","extendedModule":"OVKit"},"abstract":[{"text":"Вызывается в момент отображения на экране карточки товара","type":"text"},{"text":" ","type":"text"},{"text":"(более чем на 50% площади карточки).","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/onitemshow(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onItemShow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"itemId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/onItemShow(_:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/onItemShow(_:)","abstract":[{"text":"Вызывается в момент отображения на экране карточки товара","type":"text"},{"text":" ","type":"text"},{"text":"(более чем на 50% площади карточки).","type":"text"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/onitemshow(_:)","role":"symbol","title":"onItemShow(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemShow"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","kind":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"OVKSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}