{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/coverContainerView"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/addBehavior(_:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityDuringSeekAnimationDuration"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/createInstance()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/createInstance(frame:)"],"generated":true}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/PlayerControlsViewProtocol-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"OVKit"}],"roleHeading":"API Collection","title":"PlayerControlsViewProtocol Implementations"},"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/playercontrolsviewprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/createInstance()":{"title":"createInstance()","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/createinstance()","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/createInstance()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Создание экземпляра контролов данного типа.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"kind":"symbol","abstract":[{"text":"Рекламные контролы общего назначения.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/addBehavior(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/addBehavior(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addBehavior","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ControlsBehavior","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit16ControlsBehaviorP"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/addbehavior(_:)","type":"topic","title":"addBehavior(_:)","kind":"symbol","abstract":[{"text":"Добавление поведения на контролы.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/coverContainerView":{"title":"coverContainerView","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/covercontainerview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/coverContainerView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverContainerView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Контейнер для ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/createInstance(frame:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/createInstance(frame:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInstance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"title":"createInstance(frame:)","type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/createinstance(frame:)","kind":"symbol","abstract":[{"text":"Создание экземпляра контролов данного типа.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/visibilityDuringSeekAnimationDuration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityDuringSeekAnimationDuration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityDuringSeekAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityduringseekanimationduration","type":"topic","title":"visibilityDuringSeekAnimationDuration","kind":"symbol","abstract":[{"type":"text","text":"Стандартная длительность анимации скрытия и показа контролов во время перемотки."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"title":"CoverView","url":"\/documentation\/ovkit\/coverview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/visibilityAnimationDuration":{"title":"visibilityAnimationDuration","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityanimationduration","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationDuration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","abstract":[{"text":"Стандартная длительность анимации скрытия и показа контролов.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/visibilityAnimationOptions":{"title":"visibilityAnimationOptions","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityanimationoptions","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationOptions","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":".","kind":"text"},{"text":"AnimationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewAnimationOptions"}],"kind":"symbol","abstract":[{"text":"Стандартные параметры анимации показа и скрытия контролов.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"OVKSupplementedAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}