{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldBeHiddenInitially","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/shouldbehiddeninitially"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBeHiddenInitially"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"s:5OVKit26SupplementedAdControlsViewC23shouldBeHiddenInitiallySbvp","role":"symbol","modules":[{"name":"OVKit"}],"title":"shouldBeHiddenInitially","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Должны ли контролы быть скрыты при первом показе."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenInitially"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/shouldBeHiddenInitially":{"type":"topic","abstract":[{"text":"Должны ли контролы быть скрыты при первом показе.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenInitially","kind":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/shouldbehiddeninitially","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenInitially","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"shouldBeHiddenInitially"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"role":"symbol","title":"SupplementedAdControlsView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementedAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"SupplementedAdControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle"}]}]}