{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/tapGesture"},"metadata":{"symbolKind":"property","title":"tapGesture","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit26SupplementedAdControlsViewC10tapGestureSo05UITapG10RecognizerCSgvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapGesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":"?"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapGesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/tapgesture"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Не нужен, если нет показа\/скрытия контролов по тапу.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/tapGesture":{"title":"tapGesture","abstract":[{"text":"Не нужен, если нет показа\/скрытия контролов по тапу.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/tapGesture","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/tapgesture","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapGesture"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier","text":"UITapGestureRecognizer"},{"kind":"text","text":"?"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","type":"topic","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview","abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"title":"SupplementedAdControlsView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKSupplementedAdControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title"},{"value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments"},{"value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle"}]}]}