{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/timelineview"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdTimelineView","text":"AdTimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/timelineView"},"abstract":[{"type":"text","text":"Таймлайн воспроизведения."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdTimelineView","text":"AdTimelineView"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"timelineView","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit26SupplementedAdControlsViewC08timelineE0AA0c8TimelineE0Cvp"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"kind":"symbol","abstract":[{"text":"Рекламные контролы общего назначения.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"url":"\/documentation\/ovkit\/adtimelineview","title":"AdTimelineView","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdTimelineView","kind":"identifier"}],"navigatorTitle":[{"text":"AdTimelineView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Таймлайн воспроизведения для рекламы.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/timelineView":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdTimelineView","text":"AdTimelineView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/timelineView","abstract":[{"type":"text","text":"Таймлайн воспроизведения."}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/timelineview","role":"symbol","kind":"symbol","title":"timelineView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}]},{"value":"OVKAdTimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAdTimelineView"}]}]}]}