{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"skipButton","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"button","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mask","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"name":"button","content":[{"inlineContent":[{"type":"text","text":"Кнопка «Пропустить»."}],"type":"paragraph"}]},{"name":"mask","content":[{"inlineContent":[{"type":"text","text":"Контрольная маска."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"text":" флаг, указывающий на необходимость обновления лайаута по причине изменения состояния кнопки «Пропустить»","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"inlineContent":[{"type":"text","text":"Вызывается при изменениях контрольной маски и при изменении текущего времени плеера. Можно переопределять в наследниках для более точного контроля над состоянием кнопки."}],"type":"paragraph"}],"name":"Note","style":"note","type":"aside"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"s:5OVKit26SupplementedAdControlsViewC6update10skipButton4withSbSo8UIButtonC_AA11ControlMaskCtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"skipButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"update(skipButton:with:)","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Обновляет состояние кнопки «Пропустить» в соответствии с новой контрольной маской."}],"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/update(skipbutton:with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/update(skipButton:with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlMask","kind":"identifier"}],"url":"\/documentation\/ovkit\/controlmask","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","abstract":[{"type":"text","text":"Объект, отражающий внутреннее состояние плеера для отображения в UI."}],"title":"ControlMask","type":"topic","navigatorTitle":[{"text":"ControlMask","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"title":"SupplementedAdControlsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"abstract":[{"text":"Рекламные контролы общего назначения.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/update(skipButton:with:)":{"title":"update(skipButton:with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/update(skipButton:with:)","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/update(skipbutton:with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"skipButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ControlMask","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Обновляет состояние кнопки «Пропустить» в соответствии с новой контрольной маской."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace","value":"OVKSupplementedAdControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace","value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace","value":[{"text":"OVKSupplementedAdControlsView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}