{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visibilityDuringSeekAnimationDuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/PlayerControlsViewProtocol-Implementations"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visibilityDuringSeekAnimationDuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"extendedModule":"OVKit","title":"visibilityDuringSeekAnimationDuration","roleHeading":"Type Property","externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE37visibilityDuringSeekAnimationDurationSdvpZ::SYNTHESIZED::c:@M@OVKit@objc(cs)SupplementedAdControlsView"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityDuringSeekAnimationDuration"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"PlayerControlsViewProtocol.visibilityDuringSeekAnimationDuration","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityduringseekanimationduration"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/PlayerControlsViewProtocol-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/PlayerControlsViewProtocol-Implementations","role":"collectionGroup","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/playercontrolsviewprotocol-implementations","title":"PlayerControlsViewProtocol Implementations","abstract":[],"type":"topic","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"role":"symbol","title":"SupplementedAdControlsView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementedAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/visibilityDuringSeekAnimationDuration":{"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityduringseekanimationduration","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityDuringSeekAnimationDuration","abstract":[],"kind":"symbol","title":"visibilityDuringSeekAnimationDuration","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityDuringSeekAnimationDuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","value":[{"text":"SupplementedAdControlsView","kind":"identifier"}]}]}]}