{"variants":[{"paths":["\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityanimationduration"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationDuration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PlayerControlsViewProtocol.visibilityAnimationDuration"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Type Property","externalID":"s:5OVKit26PlayerControlsViewProtocolPAAE27visibilityAnimationDurationSdvpZ::SYNTHESIZED::c:@M@OVKit@objc(cs)SupplementedAdControlsView","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibilityAnimationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"extendedModule":"OVKit","role":"symbol","title":"visibilityAnimationDuration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"url":"\/documentation\/ovkit\/supplementedadcontrolsview","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","abstract":[],"title":"SupplementedAdControlsView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/visibilityAnimationDuration":{"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/visibilityanimationduration","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/visibilityAnimationDuration","kind":"symbol","title":"visibilityAnimationDuration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityAnimationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SupplementedAdControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title"},{"value":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments"},{"value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle"}]}]}