{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerInfo","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/bannerInfo"},"abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/bannerinfo"]}],"sections":[],"metadata":{"role":"symbol","extendedModule":"OVKit","externalID":"s:5OVKit16InterstitialInfoPAAE06bannerC0AA013AdStatsBannerC0Cvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier","text":"AdStatsBannerInfo"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"bannerInfo"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/bannerInfo":{"abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/interstitialinfo\/bannerinfo","title":"bannerInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/bannerInfo","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"role":"symbol","abstract":[{"type":"text","text":"Информация о прерывании."}],"navigatorTitle":[{"text":"InterstitialInfo","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialInfo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","url":"\/documentation\/ovkit\/interstitialinfo","kind":"symbol","title":"InterstitialInfo"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"kind":"symbol","title":"AdStatsBannerInfo","type":"topic","url":"\/documentation\/ovkit\/adstatsbannerinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title","value":"OVKInterstitialInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]}]}]}