{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialInfo(py)id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"id"},"variants":[{"paths":["\/documentation\/ovkit\/interstitialinfo\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/id"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/id","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Идентификатор."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/id":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/id","url":"\/documentation\/ovkit\/interstitialinfo\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Идентификатор.","type":"text"}],"type":"topic","required":true,"title":"id"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","type":"topic","title":"InterstitialInfo","role":"symbol","abstract":[{"text":"Информация о прерывании.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"id","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1id\/title"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1id\/fragments"},{"value":"OVKInterstitialInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle"}]}]}