{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/name"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"name","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialInfo(py)name","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/name"},"kind":"symbol","abstract":[{"text":"Тип.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/name":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/ovkit\/interstitialinfo\/name","title":"name","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/name","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Тип.","type":"text"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","type":"topic","title":"InterstitialInfo","role":"symbol","abstract":[{"text":"Информация о прерывании.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"name","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"name"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1name\/title"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1name\/fragments"},{"value":"OVKInterstitialInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle"}]}]}