{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startSec","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/startsec"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialinfo\/startsec"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/startSec"},"abstract":[{"text":"Время старта относительно старта видео.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo"]]},"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialInfo(py)startSec","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startSec","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}],"title":"startSec","navigatorTitle":[{"text":"startSec","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/startSec":{"abstract":[{"text":"Время старта относительно старта видео.","type":"text"}],"type":"topic","title":"startSec","url":"\/documentation\/ovkit\/interstitialinfo\/startsec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"startSec"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/startSec","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"role":"symbol","abstract":[{"type":"text","text":"Информация о прерывании."}],"navigatorTitle":[{"text":"InterstitialInfo","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialInfo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","url":"\/documentation\/ovkit\/interstitialinfo","kind":"symbol","title":"InterstitialInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"startSec"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"startSec","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"startSec","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1startSec\/title","op":"replace","value":"startSec"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1startSec\/fragments","value":[{"kind":"identifier","text":"startSec"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title","value":"OVKInterstitialInfo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKInterstitialInfo"}]}]}]}