{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetCustomParams(im)asDictionary","navigatorTitle":[{"text":"asDictionary","kind":"identifier"}],"title":"asDictionary()","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetcustomparams\/asdictionary()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetcustomparams\/asdictionary()"]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams\/asDictionary()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCustomParams":{"url":"\/documentation\/ovkit\/mytargetcustomparams","abstract":[],"type":"topic","title":"MyTargetCustomParams","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCustomParams"}],"navigatorTitle":[{"text":"MyTargetCustomParams","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCustomParams/asDictionary()":{"url":"\/documentation\/ovkit\/mytargetcustomparams\/asdictionary()","kind":"symbol","role":"symbol","title":"asDictionary()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams\/asDictionary()","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"asDictionary"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asDictionary","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"asDictionary"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"asDictionary","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"asDictionary","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"MyTargetCustomParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/title"},{"op":"replace","value":[{"text":"MyTargetCustomParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetCustomParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams~1asDictionary()\/title","value":"asDictionary","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams~1asDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"text":"asDictionary","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}