{"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKQUICManagerProtocol(im)installIntoSessionConfiguration:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installIntoSessionConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSessionConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"installIntoSessionConfiguration:","kind":"identifier"}],"role":"symbol","title":"installIntoSessionConfiguration(_:)","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/quicmanagerprotocol\/installintosessionconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/quicmanagerprotocol\/installintosessionconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/installIntoSessionConfiguration(_:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Устанавливает QUIC в NSURLSessionConfiguration таким образом, что все NSURLSessions"},{"text":" ","type":"text"},{"type":"text","text":"созданные с этой конфигурацией будут использовать QUIC протокол."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"installIntoSessionConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"conf","kind":"internalParam"},{"kind":"text","text":": "},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol/installIntoSessionConfiguration(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/installIntoSessionConfiguration(_:)","role":"symbol","navigatorTitle":[{"text":"installIntoSessionConfiguration:","kind":"identifier"}],"url":"\/documentation\/ovkit\/quicmanagerprotocol\/installintosessionconfiguration(_:)","type":"topic","title":"installIntoSessionConfiguration(_:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"installIntoSessionConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Устанавливает QUIC в NSURLSessionConfiguration таким образом, что все NSURLSessions"},{"type":"text","text":" "},{"type":"text","text":"созданные с этой конфигурацией будут использовать QUIC протокол."}]},"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QUICManagerProtocol","kind":"identifier"}],"title":"QUICManagerProtocol","navigatorTitle":[{"text":"QUICManagerProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol","kind":"symbol","url":"\/documentation\/ovkit\/quicmanagerprotocol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"installIntoSessionConfiguration:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"installIntoSessionConfiguration:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"installIntoSessionConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"NSURLSessionConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conf","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1installIntoSessionConfiguration(_:)\/title","value":"installIntoSessionConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1installIntoSessionConfiguration(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"installIntoSessionConfiguration:","kind":"identifier"}],"op":"replace"},{"value":"OVKQUICManagerProtocol","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/title"},{"value":[{"text":"OVKQUICManagerProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/fragments"},{"value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/navigatorTitle","op":"replace"}]}]}