{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/markRequest(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/quicmanagerprotocol\/markrequest(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/quicmanagerprotocol\/markrequest(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableURLRequest","text":"NSMutableURLRequest"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol"]]},"abstract":[{"type":"text","text":"Помечает NSMutableURLRequest как запрос, который будет использован в QUIC."}],"metadata":{"symbolKind":"method","required":true,"title":"markRequest(_:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKQUICManagerProtocol(im)markRequest:","navigatorTitle":[{"kind":"identifier","text":"markRequest:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableURLRequest","text":"NSMutableURLRequest"},{"kind":"text","text":")"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol/markRequest(_:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/markRequest(_:)","abstract":[{"type":"text","text":"Помечает NSMutableURLRequest как запрос, который будет использован в QUIC."}],"required":true,"type":"topic","title":"markRequest(_:)","url":"\/documentation\/ovkit\/quicmanagerprotocol\/markrequest(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableURLRequest","text":"NSMutableURLRequest"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"markRequest:"}]},"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QUICManagerProtocol"}],"title":"QUICManagerProtocol","url":"\/documentation\/ovkit\/quicmanagerprotocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QUICManagerProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"markRequest:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"markRequest:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"markRequest:"},{"text":"(","kind":"text"},{"text":"NSMutableURLRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableURLRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"markRequest:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1markRequest(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"markRequest:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1markRequest(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/title","value":"OVKQUICManagerProtocol"},{"value":[{"text":"OVKQUICManagerProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/navigatorTitle"}]}]}