{"metadata":{"title":"liveStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"liveStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"}],"required":true,"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)liveStatus","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/livestatus"]},{"paths":["\/documentation\/ovkit\/ovkvideotype\/livestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"LiveStatus","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/liveStatus","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","title":"LiveStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/livestatus","navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/liveStatus":{"title":"liveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/liveStatus","required":true,"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"}],"navigatorTitle":[{"text":"liveStatus","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkvideotype\/livestatus","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/videotype","title":"VideoType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"liveStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"liveStatus"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"OVKLiveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"OVKLiveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1liveStatus\/title","value":"liveStatus","op":"replace"},{"op":"replace","value":[{"text":"liveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1liveStatus\/fragments"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}]}]}]}