{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)repeated","modules":[{"name":"OVKit"}],"title":"repeated","required":true,"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"repeated"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/repeated"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/repeated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/repeated"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/videotype","title":"VideoType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/repeated":{"kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"repeated","kind":"identifier"}],"type":"topic","abstract":[],"title":"repeated","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/repeated","url":"\/documentation\/ovkit\/ovkvideotype\/repeated","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"repeated","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"repeated","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","value":"repeated","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1repeated\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1repeated\/fragments","op":"replace","value":[{"text":"repeated","kind":"identifier"}]}]}]}