{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/replayGain","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayGain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"replayGain"}],"title":"replayGain","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)replayGain","roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"replayGain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/replaygain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/replaygain"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic","title":"VideoType"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/replayGain":{"title":"replayGain","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/replayGain","url":"\/documentation\/ovkit\/ovkvideotype\/replaygain","required":true,"role":"symbol","navigatorTitle":[{"text":"replayGain","kind":"identifier"}],"abstract":[{"text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayGain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"replayGain","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"replayGain"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"replayGain","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1replayGain\/title","value":"replayGain"},{"value":[{"text":"replayGain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1replayGain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}