{"metadata":{"modules":[{"name":"OVKit"}],"required":true,"navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)timelineThumbs","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"TimelineThumbnailsType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"timelineThumbs","symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/timelineThumbs"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimelineThumbnailsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkvideotype\/timelinethumbs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideotype\/timelinethumbs"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnailstype","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","title":"TimelineThumbnailsType","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineThumbnailsType","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/timelineThumbs":{"abstract":[],"navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/timelineThumbs","url":"\/documentation\/ovkit\/ovkvideotype\/timelinethumbs","title":"timelineThumbs","required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimelineThumbnailsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","title":"VideoType","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"timelineThumbs","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"timelineThumbs","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"id<OVKTimelineThumbnailsType>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timelineThumbs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","value":"OVKTimelineThumbnailsType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1timelineThumbs\/title","value":"timelineThumbs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1timelineThumbs\/fragments","value":[{"text":"timelineThumbs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]}]}]}