{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoUrlQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","text":"VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/videourlquery"]},{"paths":["\/documentation\/ovkit\/ovkvideotype\/videourlquery"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"videoUrlQuery","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)videoUrlQuery","roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoUrlQuery"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","kind":"typeIdentifier","text":"VideoURLQuery"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoUrlQuery"}],"role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/videoUrlQuery"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/videotype","title":"VideoType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","title":"VideoURLQuery","navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoURLQuery","kind":"identifier"}],"url":"\/documentation\/ovkit\/videourlquery","abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/videoUrlQuery":{"title":"videoUrlQuery","abstract":[],"required":true,"url":"\/documentation\/ovkit\/ovkvideotype\/videourlquery","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoUrlQuery","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/videoUrlQuery"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"videoUrlQuery","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OVKVideoURLQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"videoUrlQuery"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"value":"OVKVideoURLQuery","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1videoUrlQuery\/title","value":"videoUrlQuery"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1videoUrlQuery\/fragments","value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}