{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/videoCategory","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideotype\/videocategory"]},{"paths":["\/documentation\/ovkit\/ovkvideotype\/videocategory"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"videoCategory","navigatorTitle":[{"kind":"identifier","text":"videoCategory"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)videoCategory","roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoCategory","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","kind":"typeIdentifier","text":"VideoCategory"}],"modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoCategory","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","title":"VideoType","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoType/videoCategory":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoCategory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoCategory","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory"}],"navigatorTitle":[{"kind":"identifier","text":"videoCategory"}],"title":"videoCategory","url":"\/documentation\/ovkit\/ovkvideotype\/videocategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoType\/videoCategory","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"url":"\/documentation\/ovkit\/videocategory","title":"VideoCategory","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoCategory"}],"navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoCategory"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoCategory"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKVideoCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"},{"text":" ","kind":"text"},{"text":"videoCategory","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1videoCategory\/title","value":"videoCategory"},{"value":[{"kind":"identifier","text":"videoCategory"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoType~1videoCategory\/fragments","op":"replace"},{"op":"replace","value":"OVKVideoCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategory"}],"op":"replace"}]}]}