{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/state\/error"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/error","interfaceLanguage":"swift"},"metadata":{"externalID":"s:5OVKit19ThumbnailTeaserViewC5StateO5erroryA2EmF","symbolKind":"case","title":"ThumbnailTeaserView.State.error","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"roleHeading":"Case","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","title":"ThumbnailTeaserView.State","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/thumbnailteaserview\/state","navigatorTitle":[{"kind":"identifier","text":"State"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/error":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/error","abstract":[],"title":"ThumbnailTeaserView.State.error","type":"topic","url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"title":"ThumbnailTeaserView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]}]}]}