{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/image(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/state\/image(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","text":"ThumbnailProviderThumbnail","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit19ThumbnailTeaserViewC5StateO5imageyAeA0b8ProviderB0CcAEmF","roleHeading":"Case","title":"ThumbnailTeaserView.State.image(_:)","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThumbnailProviderThumbnail","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail"},{"kind":"text","text":")"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","abstract":[{"type":"text","text":"Описание изображения для thumbnail."}],"url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","title":"ThumbnailProviderThumbnail","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","title":"ThumbnailTeaserView.State","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/thumbnailteaserview\/state","navigatorTitle":[{"kind":"identifier","text":"State"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/image(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/image(_:)","kind":"symbol","title":"ThumbnailTeaserView.State.image(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/image(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"title":"ThumbnailTeaserView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title","value":"OVKThumbnailProviderThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/navigatorTitle","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]}]}]}