{"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit19ThumbnailTeaserViewC5StateO7loadingyA2EmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"}],"symbolKind":"case","title":"ThumbnailTeaserView.State.loading"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/loading"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loading","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/state\/loading"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/loading":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loading","kind":"identifier"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/loading","title":"ThumbnailTeaserView.State.loading","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/loading","kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"kind":"symbol","title":"ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/state","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"ThumbnailTeaserView.State"}},"variantOverrides":[{"patch":[{"value":"ThumbnailTeaserView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title"},{"value":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments"},{"value":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}