{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol(py)id","modules":[{"name":"OVKit"}],"title":"id","roleHeading":"Instance Property","required":true,"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"id","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/id"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetadsitemprotocol\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetadsitemprotocol\/id"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol":{"kind":"symbol","url":"\/documentation\/ovkit\/mytargetadsitemprotocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"title":"MyTargetAdsItemProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol/id":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/id","type":"topic","title":"id","url":"\/documentation\/ovkit\/mytargetadsitemprotocol\/id","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"id"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"id"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MyTargetAdsItemProtocol","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/fragments"},{"value":"id","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1id\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1id\/fragments","op":"replace","value":[{"kind":"identifier","text":"id"}]}]}]}