{"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier","text":"CoverControlsDelegate"},{"text":"?","kind":"text"}],"title":"coverControlsDelegate","externalID":"c:@M@OVKit@objc(pl)OVKCoverViewType(py)coverControlsDelegate","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"coverControlsDelegate","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Делегат "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":". Устанавливать не нужно"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","text":"CoverControlsDelegate","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"content":[{"inlineContent":[{"text":"⚠️ Свойство должно быть ","type":"text"},{"inlineContent":[{"text":"weak","type":"text"}],"type":"strong"},{"text":"!","type":"text"}],"type":"paragraph"}],"name":"Warning","style":"warning","type":"aside"}]}],"variants":[{"paths":["\/documentation\/ovkit\/ovkcoverviewtype\/covercontrolsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkcoverviewtype\/covercontrolsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewType\/coverControlsDelegate","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverControlsDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Делегат, через который "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"type":"text","text":" могут выполнять действия."}],"title":"CoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","url":"\/documentation\/ovkit\/covercontrolsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoverControlsDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewType/coverControlsDelegate":{"abstract":[{"type":"text","text":"Делегат "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":". Устанавливать не нужно"}],"required":true,"title":"coverControlsDelegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CoverControlsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/ovkcoverviewtype\/covercontrolsdelegate","navigatorTitle":[{"text":"coverControlsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewType\/coverControlsDelegate"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/coverview","kind":"symbol","title":"CoverView","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"navigatorTitle":[{"kind":"identifier","text":"CoverViewType"}],"abstract":[],"title":"CoverViewType","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","kind":"symbol","url":"\/documentation\/ovkit\/coverviewtype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewType"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"coverControlsDelegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"coverControlsDelegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKCoverControlsDelegate","text":"id<OVKCoverControlsDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"OVKCoverControlsDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewType~1coverControlsDelegate\/title","op":"replace","value":"coverControlsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewType~1coverControlsDelegate\/fragments","value":[{"text":"coverControlsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","value":"OVKCoverViewType"},{"value":[{"kind":"identifier","text":"OVKCoverViewType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}