{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Устанавливать не нужно, свойство может быть обновлено в любой момент.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKCoverViewType(py)previewImageFrame","required":true,"title":"previewImageFrame","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewImageFrame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewType\/previewImageFrame","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovkcoverviewtype\/previewimageframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkcoverviewtype\/previewimageframe"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CoverViewType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","kind":"symbol","navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverviewtype","title":"CoverViewType","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewType/previewImageFrame":{"kind":"symbol","url":"\/documentation\/ovkit\/ovkcoverviewtype\/previewimageframe","role":"symbol","navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"title":"previewImageFrame","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewType\/previewImageFrame","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"previewImageFrame","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"previewImageFrame","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageFrame"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","value":"OVKCoverViewType","op":"replace"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"value":"previewImageFrame","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewType~1previewImageFrame\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKCoverViewType~1previewImageFrame\/fragments","op":"replace","value":[{"kind":"identifier","text":"previewImageFrame"}]}]}]}