{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail\/contentRect","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail"]]},"metadata":{"navigatorTitle":[{"text":"contentRect","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail(py)contentRect","role":"symbol","title":"contentRect","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Границы нужного кадра. Необходимо установить в свойство layer.contentsRect у объекта ","type":"text"},{"code":"UIImageView","type":"codeVoice"},{"text":", показывающего кадр.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail\/contentrect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail\/contentrect"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","title":"ThumbnailProviderThumbnail","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"abstract":[{"text":"Описание изображения для thumbnail.","type":"text"}],"navigatorTitle":[{"text":"ThumbnailProviderThumbnail","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail/contentRect":{"navigatorTitle":[{"text":"contentRect","kind":"identifier"}],"abstract":[{"type":"text","text":"Границы нужного кадра. Необходимо установить в свойство layer.contentsRect у объекта "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":", показывающего кадр."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail\/contentRect","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/thumbnailproviderthumbnail\/contentrect","title":"contentRect"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentRect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentRect"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKThumbnailProviderThumbnail","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title"},{"value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments"},{"value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/navigatorTitle"},{"value":"contentRect","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail~1contentRect\/title"},{"value":[{"text":"contentRect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail~1contentRect\/fragments"}]}]}