{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Изображение со множеством кадров."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail\/image","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail"]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"image","navigatorTitle":[{"kind":"identifier","text":"image"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail(py)image","modules":[{"name":"OVKit"}]},"variants":[{"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail\/image"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"abstract":[{"type":"text","text":"Описание изображения для thumbnail."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","title":"ThumbnailProviderThumbnail","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail/image":{"abstract":[{"type":"text","text":"Изображение со множеством кадров."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail\/image","url":"\/documentation\/ovkit\/thumbnailproviderthumbnail\/image","title":"image","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"image","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"image","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"image"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"OVKThumbnailProviderThumbnail","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}]},{"value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail~1image\/title","value":"image"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail~1image\/fragments"}]}]}