{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/coverControlsDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","text":"CoverControlsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"⚠️ Свойство должно быть "},{"type":"strong","inlineContent":[{"type":"text","text":"weak"}]},{"type":"text","text":"!"}],"type":"paragraph"}],"style":"warning","name":"Warning","type":"aside"}]}],"metadata":{"title":"coverControlsDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKRestrictionView(py)coverControlsDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverControlsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"text":"?","kind":"text"}],"modules":[{"name":"OVKit"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/restrictionview\/covercontrolsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/restrictionview\/covercontrolsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Делегат ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":". Устанавливать не нужно","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/coverControlsDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/coverControlsDelegate","url":"\/documentation\/ovkit\/restrictionview\/covercontrolsdelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverControlsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}],"kind":"symbol","title":"coverControlsDelegate","role":"symbol","abstract":[{"type":"text","text":"Делегат "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":". Устанавливать не нужно"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"url":"\/documentation\/ovkit\/coverview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","abstract":[],"title":"CoverView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoverView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionView","kind":"identifier"}],"url":"\/documentation\/ovkit\/restrictionview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","abstract":[{"type":"text","text":"Тип "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"title":"RestrictionView","type":"topic","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"url":"\/documentation\/ovkit\/covercontrolsdelegate","abstract":[{"type":"text","text":"Делегат, через который "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"type":"text","text":" могут выполнять действия."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverControlsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","title":"CoverControlsDelegate","role":"symbol","navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"coverControlsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"coverControlsDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier","text":"id<OVKCoverControlsDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1coverControlsDelegate\/title","value":"coverControlsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1coverControlsDelegate\/fragments","value":[{"kind":"identifier","text":"coverControlsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","value":"OVKRestrictionView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments","value":[{"kind":"identifier","text":"OVKRestrictionView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKRestrictionView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title","value":"OVKCoverControlsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}]}]}]}