{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:5OVKit13CoverViewTypePAAE19darkBackgroundColorSo7UIColorCvp::SYNTHESIZED::c:@M@OVKit@objc(cs)RestrictionView","modules":[{"name":"OVKit"}],"role":"symbol","extendedModule":"OVKit","title":"darkBackgroundColor","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionview\/darkbackgroundcolor"]}],"abstract":[{"text":"Цвет затемнения фона.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/darkBackgroundColor","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/CoverViewType-Implementations":{"url":"\/documentation\/ovkit\/restrictionview\/coverviewtype-implementations","abstract":[],"type":"topic","role":"collectionGroup","title":"CoverViewType Implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/darkBackgroundColor":{"url":"\/documentation\/ovkit\/restrictionview\/darkbackgroundcolor","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/darkBackgroundColor","abstract":[{"text":"Цвет затемнения фона.","type":"text"}],"kind":"symbol","title":"darkBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"abstract":[],"url":"\/documentation\/ovkit\/coverview","kind":"symbol","title":"CoverView","type":"topic","role":"symbol","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"abstract":[{"type":"text","text":"Тип "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.).","type":"text"}],"url":"\/documentation\/ovkit\/restrictionview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"type":"topic","title":"RestrictionView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","value":"RestrictionView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments","value":[{"text":"RestrictionView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","value":[{"kind":"identifier","text":"RestrictionView"}],"op":"replace"}]}]}