{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"params"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"kind":"symbol","abstract":[{"text":"Если ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":" может отрисовать ","type":"text"},{"type":"codeVoice","code":"ControlCoverType"},{"type":"text","text":", нужно обновить view и вернуть "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Если не может — будет запрошена новая "},{"type":"codeVoice","code":"CoverView"},{"text":" или подставлена стандартная.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/restrictionview\/handlecoverwithparams(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/restrictionview\/handlecoverwithparams(_:)"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)RestrictionView(im)handleCoverWithParams:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleCoverWithParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"handleCoverWithParams(_:)","navigatorTitle":[{"kind":"identifier","text":"handleCoverWithParams:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"abstract":[],"url":"\/documentation\/ovkit\/coverview","kind":"symbol","title":"CoverView","type":"topic","role":"symbol","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"abstract":[{"type":"text","text":"Тип "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.).","type":"text"}],"url":"\/documentation\/ovkit\/restrictionview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"type":"topic","title":"RestrictionView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoverViewParams","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverviewparams","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"title":"CoverViewParams"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/handleCoverWithParams(_:)":{"kind":"symbol","title":"handleCoverWithParams(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)","navigatorTitle":[{"text":"handleCoverWithParams:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams"},{"text":"(","kind":"text"},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/restrictionview\/handlecoverwithparams(_:)","abstract":[{"type":"text","text":"Если "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" может отрисовать "},{"code":"ControlCoverType","type":"codeVoice"},{"type":"text","text":", нужно обновить view и вернуть "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Если не может — будет запрошена новая ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" или подставлена стандартная."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"handleCoverWithParams:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"handleCoverWithParams:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleCoverWithParams:"},{"kind":"text","text":"("},{"text":"OVKCoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","value":"RestrictionView"},{"op":"replace","value":[{"text":"RestrictionView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","value":[{"kind":"identifier","text":"RestrictionView"}]},{"value":"OVKCoverViewParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1handleCoverWithParams(_:)\/title","value":"handleCoverWithParams:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1handleCoverWithParams(_:)\/fragments"}]}]}