{"variants":[{"paths":["\/documentation\/ovkit\/restrictionview\/init(frame:params:previewframe:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Создание "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","type":"reference"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","text":"CoverViewParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Frame для самой view.","type":"text"}]}],"name":"frame"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Параметры, из которых собирается наполнение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","isActive":true},{"text":". Из них используется только ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","isActive":true},{"type":"text","text":"."}]}],"name":"params"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame для preview-изображения внутри "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"},{"type":"text","text":". По его границам может выравниваться контент."}]}],"name":"previewFrame"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(frame:params:previewFrame:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"s:5OVKit15RestrictionViewC5frame6params12previewFrameACSgSo6CGRectV_AA05CoverC6ParamsCAItcfc","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":", ","kind":"text"},{"text":"previewFrame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"title":"init(frame:params:previewFrame:)","role":"symbol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/init(frame:params:previewFrame:)":{"url":"\/documentation\/ovkit\/restrictionview\/init(frame:params:previewframe:)","title":"init(frame:params:previewFrame:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(frame:params:previewFrame:)","abstract":[{"type":"text","text":"Создание "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"abstract":[{"type":"text","text":"Тип "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","type":"topic","title":"RestrictionView","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/restrictionview","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RestrictionView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","title":"CoverView","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"url":"\/documentation\/ovkit\/coverview","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverViewParams"}],"navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}],"type":"topic","kind":"symbol","title":"CoverViewParams","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","url":"\/documentation\/ovkit\/coverviewparams","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/restriction":{"type":"topic","abstract":[{"text":"Если есть значение, ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":" должен быть о снятии ограничений.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"restriction"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams\/restriction","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restriction","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoRestrictionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"kind":"text","text":"?"}],"title":"restriction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"RestrictionView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title"},{"value":[{"kind":"identifier","text":"RestrictionView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"value":[{"kind":"identifier","text":"RestrictionView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle"},{"value":"OVKCoverViewParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title"},{"value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/title","value":"restriction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/fragments","value":[{"text":"restriction","kind":"identifier"}],"op":"replace"}]}]}