{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"messageLabel","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"externalID":"s:5OVKit15RestrictionViewC12messageLabelSo7UILabelCSgvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/messageLabel"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionview\/messagelabel"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/messageLabel":{"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/restrictionview\/messagelabel","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"?","kind":"text"}],"title":"messageLabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/messageLabel","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"url":"\/documentation\/ovkit\/coverview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","title":"CoverView","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionView","kind":"identifier"}],"title":"RestrictionView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","type":"topic","url":"\/documentation\/ovkit\/restrictionview","abstract":[{"type":"text","text":"Тип "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"RestrictionView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title"},{"value":[{"kind":"identifier","text":"RestrictionView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","op":"replace","value":[{"text":"RestrictionView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}