{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionview\/previewimageframe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/restrictionview\/previewimageframe"]}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKRestrictionView(py)previewImageFrame","modules":[{"name":"OVKit"}],"title":"previewImageFrame","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewImageFrame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Устанавливать не нужно, свойство может быть обновлено в любой момент."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/previewImageFrame"},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"navigatorTitle":[{"kind":"identifier","text":"RestrictionView"}],"title":"RestrictionView","role":"symbol","abstract":[{"type":"text","text":"Тип "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"type":"topic","url":"\/documentation\/ovkit\/restrictionview","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"kind":"symbol","title":"CoverView","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/coverview"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/previewImageFrame":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/previewImageFrame","role":"symbol","abstract":[{"type":"text","text":"Информация о том, была ли загружена preview в момент показа "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"kind":"symbol","title":"previewImageFrame","navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/restrictionview\/previewimageframe"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"previewImageFrame"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"previewImageFrame","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","op":"replace","value":"OVKRestrictionView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments","op":"replace","value":[{"text":"OVKRestrictionView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKRestrictionView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1previewImageFrame\/title","op":"replace","value":"previewImageFrame"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1previewImageFrame\/fragments","op":"replace","value":[{"text":"previewImageFrame","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}