{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionview\/restriction"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/restriction","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restriction","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoRestrictionType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"externalID":"s:5OVKit15RestrictionViewC11restrictionAA05VideoB4Type_pvp","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"restriction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"restriction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoRestrictionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"}]},"abstract":[{"type":"text","text":"Модель "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"},{"type":"text","text":", которая отображается в данный момент."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionView","kind":"identifier"}],"title":"RestrictionView","navigatorTitle":[{"kind":"identifier","text":"RestrictionView"}],"abstract":[{"text":"Тип ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","url":"\/documentation\/ovkit\/restrictionview"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/restriction":{"url":"\/documentation\/ovkit\/restrictionview\/restriction","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/restriction","abstract":[{"type":"text","text":"Модель "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"},{"type":"text","text":", которая отображается в данный момент."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"restriction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier","text":"VideoRestrictionType"}],"title":"restriction"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"title":"CoverView","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","url":"\/documentation\/ovkit\/coverview","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"type":"topic","title":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","role":"symbol","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoRestrictionType","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/videorestrictiontype","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","value":"RestrictionView","op":"replace"},{"op":"replace","value":[{"text":"RestrictionView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","op":"replace"}]}]}