{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionview\/textcolor"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","externalID":"s:5OVKit13CoverViewTypePAAE9textColorSo7UIColorCvp::SYNTHESIZED::c:@M@OVKit@objc(cs)RestrictionView","roleHeading":"Instance Property","title":"textColor","extendedModule":"OVKit","symbolKind":"property","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/textColor","interfaceLanguage":"swift"},"abstract":[{"text":"Цвет текста.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"abstract":[{"type":"text","text":"Тип "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.).","type":"text"}],"url":"\/documentation\/ovkit\/restrictionview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"type":"topic","title":"RestrictionView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/textColor":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/textColor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"\/documentation\/ovkit\/restrictionview\/textcolor","title":"textColor","abstract":[{"text":"Цвет текста.","type":"text"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/CoverViewType-Implementations":{"url":"\/documentation\/ovkit\/restrictionview\/coverviewtype-implementations","abstract":[],"type":"topic","role":"collectionGroup","title":"CoverViewType Implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"abstract":[],"url":"\/documentation\/ovkit\/coverview","kind":"symbol","title":"CoverView","type":"topic","role":"symbol","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title","op":"replace","value":"RestrictionView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments","op":"replace","value":[{"text":"RestrictionView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RestrictionView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}