{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","title":"titleSize","externalID":"s:5OVKit13CoverViewTypePAAE9titleSize14CoreFoundation7CGFloatVvp::SYNTHESIZED::c:@M@OVKit@objc(cs)RestrictionView","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"roleHeading":"Instance Property","role":"symbol","extendedModule":"OVKit"},"abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}],"variants":[{"paths":["\/documentation\/ovkit\/restrictionview\/titlesize"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/titleSize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/titleSize":{"type":"topic","url":"\/documentation\/ovkit\/restrictionview\/titlesize","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/titleSize","abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}],"kind":"symbol","title":"titleSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"title":"RestrictionView","url":"\/documentation\/ovkit\/restrictionview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionView","kind":"identifier"}],"abstract":[{"type":"text","text":"Тип "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","abstract":[],"type":"topic","title":"CoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverview","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/CoverViewType-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations","url":"\/documentation\/ovkit\/restrictionview\/coverviewtype-implementations","title":"CoverViewType Implementations","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"RestrictionView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments","value":[{"kind":"identifier","text":"RestrictionView"}]},{"value":[{"kind":"identifier","text":"RestrictionView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}