{"variants":[{"paths":["\/documentation\/ovkit\/restrictionview\/updateappearance()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:5OVKit15RestrictionViewC16updateAppearanceyyF","roleHeading":"Instance Method","title":"updateAppearance()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAppearance"},{"kind":"text","text":"()"}],"symbolKind":"method","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/updateAppearance()"},"abstract":[{"type":"text","text":"Обновление визуального состояния "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAppearance"},{"kind":"text","text":"()"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"При наследовании в этом методе можно обновлять визуальную составляющую добавленных view, но не их layout. Не рекомендуется вызывать самостоятельно.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/updateAppearance()":{"url":"\/documentation\/ovkit\/restrictionview\/updateappearance()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAppearance"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","title":"updateAppearance()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/updateAppearance()","abstract":[{"type":"text","text":"Обновление визуального состояния "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","abstract":[{"type":"text","text":"Тип "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"title":"RestrictionView","url":"\/documentation\/ovkit\/restrictionview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"title":"CoverView","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/coverview","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKRestrictionView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title"},{"value":[{"text":"OVKRestrictionView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"value":[{"text":"OVKRestrictionView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/navigatorTitle"}]}]}