{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videoads\/viewtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videoads\/viewtype"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"VideoAdsType.viewType","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/viewType"},"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"viewType","externalID":"c:@M@OVKit@objc(cs)OVKVideoAds(py)viewType","navigatorTitle":[{"text":"viewType","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAds":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds","navigatorTitle":[{"kind":"identifier","text":"VideoAds"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"VideoAds","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"VideoAds","url":"\/documentation\/ovkit\/videoads"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/viewType":{"title":"viewType","type":"topic","navigatorTitle":[{"text":"viewType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videoads\/viewtype","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/viewType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"viewType"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"viewType"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"viewType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"OVKVideoAds","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/title"},{"value":[{"kind":"identifier","text":"OVKVideoAds"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/fragments"},{"op":"replace","value":[{"text":"OVKVideoAds","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/navigatorTitle"},{"value":"viewType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1viewType\/title","op":"replace"},{"value":[{"text":"viewType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1viewType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}