{"variants":[{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/allowfullscreendismissbydevicerotation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/allowfullscreendismissbydevicerotation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)allowFullscreenDismissByDeviceRotation","navigatorTitle":[{"text":"allowFullscreenDismissByDeviceRotation","kind":"identifier"}],"roleHeading":"Instance Property","title":"allowFullscreenDismissByDeviceRotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/allowFullscreenDismissByDeviceRotation"},"abstract":[{"text":"Разрешает автоматический выход из полноэкранного режима плеера при повороте устройства.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowFullscreenDismissByDeviceRotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Активация автоматического выхода зависит от типа устройства и способа исходного переключения в полноэкранный режим, поэтому при включении свойства выход может не происходить. Отключение свойства, напротив, гарантирует, что плеер не будет автоматически выходить из полноэкранного режима. По умолчанию значение "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullscreenContentViewController"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"kind":"symbol","title":"FullscreenContentViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenContentViewController"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/allowFullscreenDismissByDeviceRotation":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/allowFullscreenDismissByDeviceRotation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"}],"abstract":[{"type":"text","text":"Разрешает автоматический выход из полноэкранного режима плеера при повороте устройства."}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/allowfullscreendismissbydevicerotation","kind":"symbol","title":"allowFullscreenDismissByDeviceRotation","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowFullscreenDismissByDeviceRotation","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKFullscreenContentViewController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle"},{"value":"allowFullscreenDismissByDeviceRotation","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1allowFullscreenDismissByDeviceRotation\/title"},{"value":[{"kind":"identifier","text":"allowFullscreenDismissByDeviceRotation"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1allowFullscreenDismissByDeviceRotation\/fragments"}]}]}