{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Отвязывает полноэкранный плеер от места, из которого он был открыт."}],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"detachFromOriginPlayerView()","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(im)detachFromOriginPlayerView","navigatorTitle":[{"kind":"identifier","text":"detachFromOriginPlayerView"}],"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detachFromOriginPlayerView","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detachFromOriginPlayerView","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", из которого был открыт полноэкранный режим."}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Стоит вызывать только у "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":", находящегося в полноэкранном режиме, если у него изменилось видео. Иначе при закрытии полноэкранного режима измененное видео перенесется обратно в исходное "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/detachfromoriginplayerview()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/detachfromoriginplayerview()"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/detachFromOriginPlayerView()","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/detachFromOriginPlayerView()":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/detachfromoriginplayerview()","navigatorTitle":[{"kind":"identifier","text":"detachFromOriginPlayerView"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detachFromOriginPlayerView","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/detachFromOriginPlayerView()","abstract":[{"type":"text","text":"Отвязывает полноэкранный плеер от места, из которого он был открыт."}],"title":"detachFromOriginPlayerView()","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"title":"FullscreenContentViewController","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"detachFromOriginPlayerView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detachFromOriginPlayerView","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"detachFromOriginPlayerView"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":", из которого был открыт полноэкранный режим.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"value":"detachFromOriginPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1detachFromOriginPlayerView()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachFromOriginPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1detachFromOriginPlayerView()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}