{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismissMethod"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenViewControllerDismissMethod","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)dismissMethod","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"dismissMethod"}],"title":"dismissMethod"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod","text":"FullscreenViewControllerDismissMethod","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Это свойство имеет валидное значение сразу после начала закрытия полноэкранного режима (view controller dismiss) и до деинициализации самого view controller."}]}],"kind":"content"}],"sections":[],"abstract":[{"text":"Способ, которым полноэкранный режим начал закрываться.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/dismissmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/dismissmethod"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullscreenContentViewController"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"kind":"symbol","title":"FullscreenContentViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenContentViewController"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FullscreenViewControllerDismissMethod","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerDismissMethod","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Способ закрытия полноэкранного режима."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","title":"FullscreenViewControllerDismissMethod"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/dismissMethod":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismissMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissMethod"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/dismissmethod","abstract":[{"type":"text","text":"Способ, которым полноэкранный режим начал закрываться."}],"kind":"symbol","title":"dismissMethod","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod","text":"FullscreenViewControllerDismissMethod"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dismissMethod"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"dismissMethod"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod","kind":"typeIdentifier","text":"OVKFullscreenViewControllerDismissMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissMethod"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace","value":"OVKFullscreenContentViewController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","op":"replace","value":"OVKFullscreenViewControllerDismissMethod"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismissMethod\/title","op":"replace","value":"dismissMethod"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismissMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"dismissMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}