{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/enableKeyboardObserver"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableKeyboardObserver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Если включить, контролы полноэкранного плеера начнут получать событие "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)"},{"text":" при изменении состояния клавиатуры на экране. По умолчанию выключено.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Включение\/выключение механизма слежения за клавиатурой."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/enablekeyboardobserver"]},{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/enablekeyboardobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableKeyboardObserver","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"enableKeyboardObserver"}],"role":"symbol","title":"enableKeyboardObserver","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)enableKeyboardObserver"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"title":"FullscreenContentViewController","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/keyboardOverlapHeightChanged(to:)":{"title":"keyboardOverlapHeightChanged(to:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)","required":true,"kind":"symbol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/keyboardoverlapheightchanged(to:)","abstract":[{"text":"Изменилась высота клавиатуры над полноэкранным контроллером.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardOverlapHeightChanged"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/enableKeyboardObserver":{"abstract":[{"type":"text","text":"Включение\/выключение механизма слежения за клавиатурой."}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/enableKeyboardObserver","title":"enableKeyboardObserver","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableKeyboardObserver"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/enablekeyboardobserver","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableKeyboardObserver","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"enableKeyboardObserver","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enableKeyboardObserver"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"enableKeyboardObserver","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKFullscreenContentViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace"},{"value":"enableKeyboardObserver","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1enableKeyboardObserver\/title"},{"value":[{"kind":"identifier","text":"enableKeyboardObserver"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1enableKeyboardObserver\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}