{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Жест для скрытия клавиатуры."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideKeyboardGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/hidekeyboardgesturerecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/hidekeyboardgesturerecognizer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/hideKeyboardGestureRecognizer","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"hideKeyboardGestureRecognizer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideKeyboardGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":"?","kind":"text"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)hideKeyboardGestureRecognizer","role":"symbol","navigatorTitle":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","title":"FullscreenContentViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/hideKeyboardGestureRecognizer":{"abstract":[{"text":"Жест для скрытия клавиатуры.","type":"text"}],"navigatorTitle":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/hidekeyboardgesturerecognizer","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/hideKeyboardGestureRecognizer","role":"symbol","kind":"symbol","title":"hideKeyboardGestureRecognizer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideKeyboardGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hideKeyboardGestureRecognizer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hideKeyboardGestureRecognizer"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hideKeyboardGestureRecognizer"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace","value":"OVKFullscreenContentViewController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1hideKeyboardGestureRecognizer\/title","op":"replace","value":"hideKeyboardGestureRecognizer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1hideKeyboardGestureRecognizer\/fragments","op":"replace","value":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}