{"metadata":{"navigatorTitle":[{"text":"interactiveDismissAvailability","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)interactiveDismissAvailability","symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol","title":"interactiveDismissAvailability","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactiveDismissAvailability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability","text":"FullscreenInteractiveDismissAvailability"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/interactiveDismissAvailability","interfaceLanguage":"swift"},"abstract":[{"text":"Доступность закрытия полноэкранного режима свайпом вниз.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/interactivedismissavailability"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/interactivedismissavailability"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactiveDismissAvailability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability","text":"FullscreenInteractiveDismissAvailability"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"По умолчанию значение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/allowedInSupportedOrientations":{"navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Разрешает интерактивное закрытие только в поддерживаемых ориентациях."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedInSupportedOrientations","kind":"identifier"}],"title":"FullscreenInteractiveDismissAvailability.allowedInSupportedOrientations","role":"symbol","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinsupportedorientations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/interactiveDismissAvailability":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/interactiveDismissAvailability","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactiveDismissAvailability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability","text":"FullscreenInteractiveDismissAvailability"}],"abstract":[{"text":"Доступность закрытия полноэкранного режима свайпом вниз.","type":"text"}],"type":"topic","title":"interactiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/interactivedismissavailability","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactiveDismissAvailability"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"type":"topic","role":"symbol","abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","title":"FullscreenInteractiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"title":"FullscreenContentViewController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenContentViewController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenContentViewController"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"interactiveDismissAvailability"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"interactiveDismissAvailability","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability","text":"OVKFullscreenInteractiveDismissAvailability"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactiveDismissAvailability"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/title","value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/fragments","value":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1interactiveDismissAvailability\/title","value":"interactiveDismissAvailability"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1interactiveDismissAvailability\/fragments","value":[{"text":"interactiveDismissAvailability","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","value":"OVKFullscreenInteractiveDismissAvailability"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]}]}]}