{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/keycommands"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/keycommands"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/keyCommands","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyCommands"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIKeyCommand","text":"UIKeyCommand"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"metadata":{"extendedModule":"OVKit","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyCommands","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIKeyCommand","text":"UIKeyCommand","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"keyCommands","roleHeading":"Instance Property","externalID":"c:@CM@OVKit@objc(cs)OVKFullscreenContentViewController(py)keyCommands","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","navigatorTitle":[{"text":"keyCommands","kind":"identifier"}]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/keyCommands":{"kind":"symbol","navigatorTitle":[{"text":"keyCommands","kind":"identifier"}],"title":"keyCommands","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/keycommands","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/keyCommands","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyCommands","kind":"identifier"},{"kind":"text","text":": ["},{"text":"UIKeyCommand","preciseIdentifier":"c:objc(cs)UIKeyCommand","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"title":"FullscreenContentViewController","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"keyCommands"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"keyCommands","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<UIKeyCommand *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"keyCommands","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1keyCommands\/title","value":"keyCommands"},{"value":[{"kind":"identifier","text":"keyCommands"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1keyCommands\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}