{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/FullscreenViewControllerProtocol-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Установка "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSupplementaryViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Контроллер, который устанавливается или "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Выполнять ли анимацию."}],"type":"paragraph"}],"name":"animated"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Можно вызывать до и во время презентации полноэкранного режима. Если установить до презентации, она произойдет сразу с "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController"},{"text":". Завершение презентации с установленным ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","isActive":true},{"type":"text","text":" тоже возможно."}]},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"text":"Если ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","isActive":true},{"type":"text","text":" уже имеется, то при замене на другой ничего не произойдет."}],"type":"paragraph"}],"style":"warning"}]}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/setsupplementaryviewcontroller(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/setsupplementaryviewcontroller(_:animated:)"]}],"metadata":{"role":"symbol","extendedModule":"OVKit","modules":[{"name":"OVKit"}],"externalID":"c:@CM@OVKit@objc(cs)OVKFullscreenContentViewController(im)setSupplementaryViewController:animated:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setSupplementaryViewController","kind":"identifier"},{"text":"((","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setSupplementaryViewController:animated:","kind":"identifier"}],"title":"setSupplementaryViewController(_:animated:)","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"title":"FullscreenContentViewController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenContentViewController"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenContentViewController"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/supplementaryViewController":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supplementaryViewController"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"text":"FullscreenSupplementaryController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","title":"supplementaryViewController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/supplementaryviewcontroller","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"text":"supplementaryViewController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/FullscreenViewControllerProtocol-Implementations":{"title":"FullscreenViewControllerProtocol Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/FullscreenViewControllerProtocol-Implementations","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/fullscreenviewcontrollerprotocol-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/setSupplementaryViewController(_:animated:)":{"navigatorTitle":[{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/setsupplementaryviewcontroller(_:animated:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","abstract":[{"type":"text","text":"Установка "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController"},{"type":"text","text":"."}],"title":"setSupplementaryViewController(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSupplementaryViewController","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" & ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController"},{"kind":"text","text":")?, "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"setSupplementaryViewController:animated:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSupplementaryViewController:animated:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setSupplementaryViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController<OVKFullscreenSupplementaryController>","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenSupplementaryController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKFullscreenContentViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"value":"supplementaryViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/title","op":"replace"},{"value":[{"text":"supplementaryViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/title","value":"setSupplementaryViewController:animated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSupplementaryViewController:animated:","kind":"identifier"}]},{"op":"replace","value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}