{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/swipeDownBehavior"},"abstract":[{"type":"text","text":"Поведение при свайпе вниз в полноэкранном режиме."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeDownBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Применяется только когда жест свайпа доступен в текущей конфигурации UI.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeDownBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"swipeDownBehavior"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)swipeDownBehavior","title":"swipeDownBehavior","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/swipedownbehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/swipedownbehavior"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","type":"topic","kind":"symbol","abstract":[{"text":"Поведение при свайпе в полноэкранном режиме.","type":"text"}],"role":"symbol","title":"FullscreenSwipeGestureBehavior"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/swipeDownBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/swipeDownBehavior","abstract":[{"type":"text","text":"Поведение при свайпе вниз в полноэкранном режиме."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeDownBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"swipeDownBehavior","kind":"identifier"}],"title":"swipeDownBehavior","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/swipedownbehavior","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","kind":"symbol","title":"FullscreenContentViewController","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"swipeDownBehavior","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"swipeDownBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKFullscreenSwipeGestureBehavior","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"},{"text":" ","kind":"text"},{"text":"swipeDownBehavior","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","value":"OVKFullscreenSwipeGestureBehavior","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1swipeDownBehavior\/title","value":"swipeDownBehavior","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1swipeDownBehavior\/fragments","value":[{"text":"swipeDownBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}