{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/gestureRecognizerShouldBegin(_:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/UIGestureRecognizerDelegate-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/uigesturerecognizerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/uigesturerecognizerdelegate-implementations"]}],"kind":"article","metadata":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","modules":[{"name":"OVKit"}],"roleHeading":"API Collection"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FullscreenContentViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenContentViewController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","role":"symbol","kind":"symbol","title":"FullscreenContentViewController"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/gestureRecognizerShouldBegin(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/gestureRecognizerShouldBegin(_:)","abstract":[],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/gesturerecognizershouldbegin(_:)","role":"symbol","kind":"symbol","title":"gestureRecognizerShouldBegin(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/gestureRecognizerShouldBegin(_:)"],"generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace","value":"OVKFullscreenContentViewController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1gestureRecognizerShouldBegin(_:)\/title","op":"replace","value":"gestureRecognizerShouldBegin:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1gestureRecognizerShouldBegin(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]}]}]}