{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewwilltransition(to:with:)"]},{"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewwilltransition(to:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillTransition(to:with:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(im)viewWillTransitionToSize:withTransitionCoordinator:","modules":[{"name":"OVKit"}],"role":"symbol","title":"viewWillTransition(to:with:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"coordinator"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"title":"FullscreenContentViewController","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewWillTransition(to:with:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewwilltransition(to:with:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillTransition(to:with:)","title":"viewWillTransition(to:with:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"viewWillTransitionToSize:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withTransitionCoordinator:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator","text":"id<UIViewControllerTransitionCoordinator>"},{"kind":"text","text":") "},{"text":"coordinator","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace","value":"OVKFullscreenContentViewController"},{"value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle"},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillTransition(to:with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillTransition(to:with:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}