{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visualStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"visualStyle"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"visualStyle","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)visualStyle"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visualStyle","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Стиль плеера в полноэкранном режиме."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/visualstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller\/visualstyle"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/visualStyle","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenContentViewController"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"title":"FullscreenContentViewController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/visualStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/visualStyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/visualstyle","title":"visualStyle","type":"topic","abstract":[{"type":"text","text":"Стиль плеера в полноэкранном режиме."}],"role":"symbol","navigatorTitle":[{"text":"visualStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"title":"FullscreenViewControllerVisualStyle","role":"symbol","abstract":[],"navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"visualStyle","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"visualStyle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"visualStyle"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace","value":"OVKFullscreenContentViewController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1visualStyle\/title","value":"visualStyle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1visualStyle\/fragments","op":"replace","value":[{"text":"visualStyle","kind":"identifier"}]},{"value":"FullscreenViewControllerVisualStyle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title"},{"op":"replace","value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","op":"replace"}]}]}