{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/fadeDuration"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/loadableimageview\/fadeduration"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"fadeDuration","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"s:5OVKit17LoadableImageViewC12fadeDurationSdvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fadeDuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fadeDuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LoadableImageView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","url":"\/documentation\/ovkit\/loadableimageview","title":"LoadableImageView","role":"symbol","navigatorTitle":[{"text":"LoadableImageView","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/fadeDuration":{"title":"fadeDuration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/fadeDuration","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/loadableimageview\/fadeduration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fadeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","value":"OVKLoadableImageView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"text":"OVKLoadableImageView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLoadableImageView"}]}]}]}