{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aDecoder"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/initWithCoder:"},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"initWithCoder:","modules":[{"name":"OVKit"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)LoadableImageView(im)initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/loadableimageview\/initwithcoder:"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"role":"symbol","navigatorTitle":[{"text":"LoadableImageView","kind":"identifier"}],"kind":"symbol","title":"LoadableImageView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoadableImageView","kind":"identifier"}],"url":"\/documentation\/ovkit\/loadableimageview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/initWithCoder:":{"abstract":[],"url":"\/documentation\/ovkit\/loadableimageview\/initwithcoder:","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/initWithCoder:","title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","value":"LoadableImageView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"text":"LoadableImageView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","value":[{"kind":"identifier","text":"LoadableImageView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}