{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:5OVKit17LoadableImageViewC04loadC08variants13preferredSizeySayAA0C9AssetType_pG_So6CGSizeVtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variants","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"preferredSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"loadImage(variants:preferredSize:)","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/loadableimageview\/loadimage(variants:preferredsize:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/loadImage(variants:preferredSize:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"preferredSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"title":"LoadableImageView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoadableImageView"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LoadableImageView"}],"url":"\/documentation\/ovkit\/loadableimageview"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"url":"\/documentation\/ovkit\/imageassettype","title":"ImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Ассет изображения.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAssetType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/loadImage(variants:preferredSize:)":{"url":"\/documentation\/ovkit\/loadableimageview\/loadimage(variants:preferredsize:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variants","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"preferredSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/loadImage(variants:preferredSize:)","title":"loadImage(variants:preferredSize:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKLoadableImageView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title"},{"op":"replace","value":[{"text":"OVKLoadableImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments"},{"op":"replace","value":[{"text":"OVKLoadableImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType"},{"op":"replace","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/navigatorTitle","value":[{"text":"OVKImageAssetType","kind":"identifier"}]}]}]}