{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loadableimageview\/onerror"]}],"metadata":{"externalID":"s:5OVKit17LoadableImageViewC7onErrorys0F0_pSgcSgvp","title":"onError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/onError"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/onError":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/onError","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/loadableimageview\/onerror","kind":"symbol","title":"onError"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"kind":"symbol","title":"LoadableImageView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","url":"\/documentation\/ovkit\/loadableimageview","navigatorTitle":[{"kind":"identifier","text":"LoadableImageView"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadableImageView"}]}},"variantOverrides":[{"patch":[{"value":"OVKLoadableImageView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLoadableImageView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLoadableImageView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}