{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/onUpdate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"metadata":{"title":"onUpdate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUpdate"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?) -> ())?"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"s:5OVKit17LoadableImageViewC8onUpdateySo7UIImageCSgcSgvp","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ())?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/loadableimageview\/onupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoadableImageView","kind":"identifier"}],"url":"\/documentation\/ovkit\/loadableimageview","title":"LoadableImageView","navigatorTitle":[{"text":"LoadableImageView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","role":"symbol","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/onUpdate":{"kind":"symbol","title":"onUpdate","url":"\/documentation\/ovkit\/loadableimageview\/onupdate","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/onUpdate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ())?","kind":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","value":"LoadableImageView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"text":"LoadableImageView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","value":[{"text":"LoadableImageView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}