{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredRenderingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RenderingMode","preciseIdentifier":"c:@E@UIImageRenderingMode"}],"externalID":"s:5OVKit17LoadableImageViewC22preferredRenderingModeSo07UIImagefG0Vvp","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"role":"symbol","title":"preferredRenderingMode","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/loadableimageview\/preferredrenderingmode"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/preferredRenderingMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredRenderingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageRenderingMode","kind":"typeIdentifier","text":"RenderingMode"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/loadableimageview","navigatorTitle":[{"kind":"identifier","text":"LoadableImageView"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoadableImageView"}],"type":"topic","title":"LoadableImageView","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView/preferredRenderingMode":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView\/preferredRenderingMode","role":"symbol","url":"\/documentation\/ovkit\/loadableimageview\/preferredrenderingmode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredRenderingMode"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageRenderingMode","text":"RenderingMode"}],"type":"topic","title":"preferredRenderingMode","kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"value":"LoadableImageView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"text":"LoadableImageView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"LoadableImageView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}