{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"!=(_:_:)","roleHeading":"Operator","extendedModule":"Swift","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:5OVKit25ExternalPlaybackBadgeViewC5StateO","role":"symbol","modules":[{"name":"OVKit","relatedModules":["Swift"]}],"symbolKind":"op"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/Equatable-Implementations"]]},"variants":[{"paths":["\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum/!=(_:_:)":{"role":"symbol","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum/Equatable-Implementations":{"kind":"article","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/Equatable-Implementations","abstract":[],"type":"topic","role":"collectionGroup","title":"Equatable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"State","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","type":"topic","kind":"symbol","title":"ExternalPlaybackBadgeView.State","navigatorTitle":[{"text":"State","kind":"identifier"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExternalPlaybackBadgeView"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview","navigatorTitle":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","abstract":[],"role":"symbol","title":"ExternalPlaybackBadgeView"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/title","value":"ExternalPlaybackBadgeView"},{"value":[{"kind":"identifier","text":"ExternalPlaybackBadgeView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/navigatorTitle","value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}