{"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Case","externalID":"s:5OVKit25ExternalPlaybackBadgeViewC5StateO10connectingyA2EmF","symbolKind":"case","title":"ExternalPlaybackBadgeView.State.connecting"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/connecting","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/connecting"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum":{"type":"topic","kind":"symbol","title":"ExternalPlaybackBadgeView.State","role":"symbol","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView":{"type":"topic","navigatorTitle":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","abstract":[],"role":"symbol","title":"ExternalPlaybackBadgeView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExternalPlaybackBadgeView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum/connecting":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/connecting","type":"topic","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/connecting","title":"ExternalPlaybackBadgeView.State.connecting","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"ExternalPlaybackBadgeView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/title"},{"value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/fragments"},{"value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}