{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/connected"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","externalID":"s:5OVKit25ExternalPlaybackBadgeViewC5StateO9connectedyA2EmF","title":"ExternalPlaybackBadgeView.State.connected","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/connected"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum/connected":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum\/connected","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum\/connected","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[],"title":"ExternalPlaybackBadgeView.State.connected"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView":{"type":"topic","navigatorTitle":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","abstract":[],"role":"symbol","title":"ExternalPlaybackBadgeView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExternalPlaybackBadgeView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum":{"type":"topic","kind":"symbol","title":"ExternalPlaybackBadgeView.State","role":"symbol","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"kind":"identifier","text":"State"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ExternalPlaybackBadgeView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/title"},{"op":"replace","value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ExternalPlaybackBadgeView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}