{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a3s"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"a3s","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/statsprogress\/a3s"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statsprogress\/a3s"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@OVKit@E@OVKStatsProgress@OVKStatsProgressA3s","role":"symbol","title":"StatsProgress.a3s","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"a3s"}],"navigatorTitle":[{"text":"OVKStatsProgressA3s","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/a3s":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"a3s","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a3s","kind":"symbol","url":"\/documentation\/ovkit\/statsprogress\/a3s","role":"symbol","title":"StatsProgress.a3s","navigatorTitle":[{"text":"OVKStatsProgressA3s","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/statsprogress","kind":"symbol","title":"StatsProgress","navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsProgress","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKStatsProgressA3s","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKStatsProgressA3s","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKStatsProgressA3s","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a3s\/title","value":"OVKStatsProgressA3s","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a3s\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgressA3s"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title","value":"OVKStatsProgress","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle","value":[{"text":"OVKStatsProgress","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}