{"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"]]},"kind":"article","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/!=(_:_:)"],"generated":true,"title":"Operators"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsprogress\/equatable-implementations"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/!=(_:_:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statsprogress\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/statsprogress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","abstract":[],"title":"StatsProgress","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsProgress"}],"navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKStatsProgress","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}