{"metadata":{"roleHeading":"Case","title":"StatsProgress.r100p","symbolKind":"case","navigatorTitle":[{"text":"OVKStatsProgressR100p","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKStatsProgress@OVKStatsProgressR100p","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"r100p"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r100p"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsprogress\/r100p"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statsprogress\/r100p"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"r100p"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r100p":{"title":"StatsProgress.r100p","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r100p","navigatorTitle":[{"kind":"identifier","text":"OVKStatsProgressR100p"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statsprogress\/r100p","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"r100p"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/statsprogress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","abstract":[],"title":"StatsProgress","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsProgress"}],"navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKStatsProgressR100p","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgressR100p"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKStatsProgressR100p","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKStatsProgressR100p","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r100p\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgressR100p"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r100p\/fragments"},{"op":"replace","value":"OVKStatsProgress","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle"}]}]}