{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r50p","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"OVKit"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"OVKStatsProgressR50p","kind":"identifier"}],"title":"StatsProgress.r50p","externalID":"c:@M@OVKit@E@OVKStatsProgress@OVKStatsProgressR50p"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsprogress\/r50p"]},{"paths":["\/documentation\/ovkit\/statsprogress\/r50p"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"r50p"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r50p","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r50p":{"url":"\/documentation\/ovkit\/statsprogress\/r50p","role":"symbol","type":"topic","navigatorTitle":[{"text":"OVKStatsProgressR50p","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r50p","kind":"identifier"}],"abstract":[],"title":"StatsProgress.r50p","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r50p"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"title":"StatsProgress","navigatorTitle":[{"kind":"identifier","text":"StatsProgress"}],"url":"\/documentation\/ovkit\/statsprogress","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsProgress"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"OVKStatsProgressR50p","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgressR50p"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKStatsProgressR50p"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r50p\/title","value":"OVKStatsProgressR50p"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r50p\/fragments","value":[{"text":"OVKStatsProgressR50p","kind":"identifier"}]},{"value":"OVKStatsProgress","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}