{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsprogress\/r75p"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statsprogress\/r75p"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r75p"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKStatsProgressR75p"}],"externalID":"c:@M@OVKit@E@OVKStatsProgress@OVKStatsProgressR75p","symbolKind":"case","title":"StatsProgress.r75p","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"r75p","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"r75p"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"abstract":[],"url":"\/documentation\/ovkit\/statsprogress","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsProgress"}],"title":"StatsProgress","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsProgress"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r75p":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"OVKStatsProgressR75p","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r75p","type":"topic","url":"\/documentation\/ovkit\/statsprogress\/r75p","abstract":[],"title":"StatsProgress.r75p","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"r75p"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"OVKStatsProgressR75p","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"OVKStatsProgressR75p"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKStatsProgressR75p"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"OVKStatsProgress","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgress"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"op":"replace","value":"OVKStatsProgressR75p","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r75p\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r75p\/fragments","value":[{"text":"OVKStatsProgressR75p","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}