{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onBannerShouldClose:instreamAd:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerShouldClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MyTargetInstreamAdBanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onBannerShouldClose:instreamAd:","kind":"identifier"}],"title":"onBannerShouldClose(_:instreamAd:)","roleHeading":"Instance Method","role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerShouldClose(_:instreamAd:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannershouldclose(_:instreamad:)"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannershouldclose(_:instreamad:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerShouldClose"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"banner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onBannerShouldClose(_:instreamAd:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerShouldClose(_:instreamAd:)","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBannerShouldClose:instreamAd:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerShouldClose"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","text":"MyTargetInstreamAdBanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannershouldclose(_:instreamad:)","title":"onBannerShouldClose(_:instreamAd:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"type":"topic","title":"MyTargetInstreamAdDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"title":"MyTargetInstreamAdBanner","url":"\/documentation\/ovkit\/mytargetinstreamadbanner","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"MyTargetInstreamAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onBannerShouldClose:instreamAd:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBannerShouldClose:instreamAd:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onBannerShouldClose:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MyTargetInstreamAdBanner>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdBanner"},{"kind":"text","text":") "},{"kind":"internalParam","text":"banner"},{"kind":"text","text":" "},{"kind":"identifier","text":"instreamAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MyTargetInstreamAd>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd"},{"kind":"text","text":") "},{"kind":"internalParam","text":"instreamAd"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerShouldClose(_:instreamAd:)\/title","value":"onBannerShouldClose:instreamAd:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerShouldClose(_:instreamAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBannerShouldClose:instreamAd:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title","value":"MyTargetInstreamAdBanner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"}]}]}