{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onBannerComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"banner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","text":"MyTargetInstreamAdBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"instreamAd"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","text":"MyTargetInstreamAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"onBannerComplete:instreamAd:","kind":"identifier"}],"title":"onBannerComplete(_:instreamAd:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onBannerComplete","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"required":true,"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onBannerComplete:instreamAd:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerComplete(_:instreamAd:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannercomplete(_:instreamad:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannercomplete(_:instreamad:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"abstract":[],"type":"topic","title":"MyTargetInstreamAdDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onBannerComplete(_:instreamAd:)":{"navigatorTitle":[{"kind":"identifier","text":"onBannerComplete:instreamAd:"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerComplete(_:instreamAd:)","title":"onBannerComplete(_:instreamAd:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerComplete"},{"kind":"text","text":"("},{"text":"MyTargetInstreamAdBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannercomplete(_:instreamad:)","required":true,"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","title":"MyTargetInstreamAd","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAd","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"navigatorTitle":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","kind":"symbol","title":"MyTargetInstreamAdBanner","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onBannerComplete:instreamAd:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onBannerComplete:instreamAd:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onBannerComplete:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdBanner","text":"id<MyTargetInstreamAdBanner>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"banner"},{"kind":"text","text":" "},{"text":"instreamAd:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier","text":"id<MyTargetInstreamAd>"},{"text":") ","kind":"text"},{"text":"instreamAd","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","op":"replace","value":"MyTargetInstreamAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerComplete(_:instreamAd:)\/title","value":"onBannerComplete:instreamAd:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerComplete(_:instreamAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBannerComplete:instreamAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title","value":"MyTargetInstreamAdBanner","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments"}]}]}