{"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onBannerStart:instreamAd:"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onBannerStart:instreamAd:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerStart"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdBanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}],"title":"onBannerStart(_:instreamAd:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerStart(_:instreamAd:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannerstart(_:instreamad:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannerstart(_:instreamad:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"banner","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","text":"MyTargetInstreamAdBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAd"}],"title":"MyTargetInstreamAd","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad","role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","type":"topic","navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","abstract":[],"title":"MyTargetInstreamAdDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"title":"MyTargetInstreamAdBanner","url":"\/documentation\/ovkit\/mytargetinstreamadbanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onBannerStart(_:instreamAd:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onBannerStart(_:instreamAd:)","type":"topic","navigatorTitle":[{"text":"onBannerStart:instreamAd:","kind":"identifier"}],"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onbannerstart(_:instreamad:)","abstract":[],"kind":"symbol","title":"onBannerStart(_:instreamAd:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerStart"},{"text":"(","kind":"text"},{"text":"MyTargetInstreamAdBanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"instreamAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onBannerStart:instreamAd:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBannerStart:instreamAd:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onBannerStart:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MyTargetInstreamAdBanner>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdBanner","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"banner","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"instreamAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MyTargetInstreamAd>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"instreamAd","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","op":"replace","value":"MyTargetInstreamAd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","op":"replace","value":"MyTargetInstreamAdDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title","op":"replace","value":"MyTargetInstreamAdBanner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerStart(_:instreamAd:)\/title","op":"replace","value":"onBannerStart:instreamAd:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onBannerStart(_:instreamAd:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBannerStart:instreamAd:"}]}]}]}