{"metadata":{"title":"onError(withReason:instreamAd:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onErrorWithReason:instreamAd:"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onErrorWithReason:instreamAd:","role":"symbol","required":true,"symbolKind":"method","modules":[{"name":"OVKit"}]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onerror(withreason:instreamad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onerror(withreason:instreamad:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withReason","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"},{"text":")","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onError(withReason:instreamAd:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onError(withReason:instreamAd:)":{"title":"onError(withReason:instreamAd:)","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onerror(withreason:instreamad:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onErrorWithReason:instreamAd:","kind":"identifier"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onError(withReason:instreamAd:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[],"kind":"symbol","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"title":"MyTargetInstreamAdDelegate","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onErrorWithReason:instreamAd:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorWithReason:instreamAd:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onErrorWithReason:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"instreamAd:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","text":"id<MyTargetInstreamAd>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"instreamAd","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onError(withReason:instreamAd:)\/title","value":"onErrorWithReason:instreamAd:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorWithReason:instreamAd:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onError(withReason:instreamAd:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]}]}]}