{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onLeaveApplication(with:)"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onleaveapplication(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onleaveapplication(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onLeaveApplicationWith:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLeaveApplication","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}],"required":true,"title":"onLeaveApplication(with:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onLeaveApplicationWith:"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLeaveApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"instreamAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onLeaveApplication(with:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onLeaveApplication(with:)","role":"symbol","abstract":[],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLeaveApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}],"title":"onLeaveApplication(with:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onLeaveApplicationWith:"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onleaveapplication(with:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"kind":"symbol","title":"MyTargetInstreamAdDelegate","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad","title":"MyTargetInstreamAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onLeaveApplicationWith:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLeaveApplicationWith:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLeaveApplicationWith:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier","text":"id<MyTargetInstreamAd>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"instreamAd"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onLeaveApplication(with:)\/title","value":"onLeaveApplicationWith:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onLeaveApplication(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onLeaveApplicationWith:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}]},{"value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle"},{"value":"MyTargetInstreamAd","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}