{"metadata":{"symbolKind":"method","title":"onPostViewStart()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPostViewStart"},{"kind":"text","text":"()"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onPostViewStart","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"onPostViewStart"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPostViewStart","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onPostViewStart()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewstart()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewstart()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onPostViewStart()":{"type":"topic","navigatorTitle":[{"text":"onPostViewStart","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onPostViewStart()","kind":"symbol","title":"onPostViewStart()","role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewstart()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPostViewStart","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"title":"MyTargetInstreamAdDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onPostViewStart"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPostViewStart","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onPostViewStart","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onPostViewStart()\/title","op":"replace","value":"onPostViewStart"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onPostViewStart()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPostViewStart"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle","op":"replace"}]}]}