{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewcomplete()"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewcomplete()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onPostViewComplete()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPostViewComplete"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onPostViewComplete","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPostViewComplete","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onPostViewComplete()","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onPostViewComplete"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","title":"MyTargetInstreamAdDelegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onPostViewComplete()":{"title":"onPostViewComplete()","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onpostviewcomplete()","navigatorTitle":[{"text":"onPostViewComplete","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPostViewComplete","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onPostViewComplete()","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onPostViewComplete"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPostViewComplete"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onPostViewComplete","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate","op":"replace"},{"op":"replace","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle","op":"replace"},{"value":"onPostViewComplete","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onPostViewComplete()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onPostViewComplete","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onPostViewComplete()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}