{"metadata":{"required":true,"title":"onVideoMotionShouldClose(_:instreamAd:)","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onVideoMotionShouldClose:instreamAd:","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onVideoMotionShouldClose","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"onVideoMotionShouldClose:instreamAd:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionShouldClose(_:instreamAd:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionshouldclose(_:instreamad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionshouldclose(_:instreamad:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onVideoMotionShouldClose","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"banner","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"type":"topic","title":"MyTargetInstreamAdDelegate","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onVideoMotionShouldClose(_:instreamAd:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onVideoMotionShouldClose"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":", "},{"text":"instreamAd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"},{"text":")","kind":"text"}],"abstract":[],"title":"onVideoMotionShouldClose(_:instreamAd:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionShouldClose(_:instreamAd:)","required":true,"navigatorTitle":[{"text":"onVideoMotionShouldClose:instreamAd:","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionshouldclose(_:instreamad:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","title":"MyTargetInstreamAdVideoMotionBanner","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad","title":"MyTargetInstreamAd","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"onVideoMotionShouldClose:instreamAd:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"onVideoMotionShouldClose:instreamAd:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onVideoMotionShouldClose:"},{"text":"(","kind":"text"},{"text":"id<MyTargetInstreamAdVideoMotionBanner>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":") "},{"kind":"internalParam","text":"banner"},{"text":" ","kind":"text"},{"text":"instreamAd:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","text":"id<MyTargetInstreamAd>"},{"text":") ","kind":"text"},{"text":"instreamAd","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MyTargetInstreamAdDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionShouldClose(_:instreamAd:)\/title","value":"onVideoMotionShouldClose:instreamAd:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onVideoMotionShouldClose:instreamAd:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionShouldClose(_:instreamAd:)\/fragments","op":"replace"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionBanner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title"},{"value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd"},{"value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}