{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannercomplete(_:instreamad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannercomplete(_:instreamad:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionBannerComplete(_:instreamAd:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVideoMotionBannerComplete"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"banner"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instreamAd"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","title":"onVideoMotionBannerComplete(_:instreamAd:)","navigatorTitle":[{"text":"onVideoMotionBannerComplete:instreamAd:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onVideoMotionBannerComplete:instreamAd:","required":true,"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVideoMotionBannerComplete"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"},{"kind":"text","text":")"}]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onVideoMotionBannerComplete(_:instreamAd:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionBannerComplete(_:instreamAd:)","title":"onVideoMotionBannerComplete(_:instreamAd:)","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannercomplete(_:instreamad:)","navigatorTitle":[{"kind":"identifier","text":"onVideoMotionBannerComplete:instreamAd:"}],"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onVideoMotionBannerComplete","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"kind":"symbol","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"kind":"symbol","role":"symbol","type":"topic","title":"MyTargetInstreamAdVideoMotionBanner","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","title":"MyTargetInstreamAdDelegate","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onVideoMotionBannerComplete:instreamAd:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onVideoMotionBannerComplete:instreamAd:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onVideoMotionBannerComplete:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","text":"id<MyTargetInstreamAdVideoMotionBanner>"},{"text":") ","kind":"text"},{"text":"banner","kind":"internalParam"},{"kind":"text","text":" "},{"text":"instreamAd:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","text":"id<MyTargetInstreamAd>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"instreamAd"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionBannerComplete(_:instreamAd:)\/title","op":"replace","value":"onVideoMotionBannerComplete:instreamAd:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onVideoMotionBannerComplete:instreamAd:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionBannerComplete(_:instreamAd:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}