{"kind":"symbol","sections":[],"metadata":{"role":"symbol","title":"onVideoMotionBannerStart(_:instreamAd:)","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate(im)onVideoMotionBannerStart:instreamAd:","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"text":"onVideoMotionBannerStart:instreamAd:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onVideoMotionBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannerstart(_:instreamad:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannerstart(_:instreamad:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionBannerStart(_:instreamAd:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onVideoMotionBannerStart","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"banner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate/onVideoMotionBannerStart(_:instreamAd:)":{"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate\/onvideomotionbannerstart(_:instreamad:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate\/onVideoMotionBannerStart(_:instreamAd:)","abstract":[],"role":"symbol","type":"topic","title":"onVideoMotionBannerStart(_:instreamAd:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onVideoMotionBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"instreamAd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onVideoMotionBannerStart:instreamAd:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdDelegate":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdDelegate","title":"MyTargetInstreamAdDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdDelegate"}],"url":"\/documentation\/ovkit\/mytargetinstreamaddelegate","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","title":"MyTargetInstreamAdVideoMotionBanner","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAd"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onVideoMotionBannerStart:instreamAd:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onVideoMotionBannerStart:instreamAd:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onVideoMotionBannerStart:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","text":"id<MyTargetInstreamAdVideoMotionBanner>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"banner","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"instreamAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MyTargetInstreamAd>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"instreamAd"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"onVideoMotionBannerStart:instreamAd:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionBannerStart(_:instreamAd:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate~1onVideoMotionBannerStart(_:instreamAd:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onVideoMotionBannerStart:instreamAd:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/title","value":"MyTargetInstreamAdDelegate"},{"value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdDelegate\/navigatorTitle","value":[{"text":"MyTargetInstreamAdDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}