{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/coverControlsDelegate","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"text":"CoverControlsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKCoverViewType(py)coverControlsDelegate","symbolKind":"property","required":true,"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"coverControlsDelegate","navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Делегат ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":". Устанавливать не нужно","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","text":"CoverControlsDelegate"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"style":"warning","name":"Warning","type":"aside","content":[{"inlineContent":[{"text":"⚠️ Свойство должно быть ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"weak"}]},{"text":"!","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/coverviewtype\/covercontrolsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/coverviewtype\/covercontrolsdelegate"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/coverControlsDelegate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverControlsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Делегат "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":". Устанавливать не нужно"}],"navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/coverControlsDelegate","type":"topic","url":"\/documentation\/ovkit\/coverviewtype\/covercontrolsdelegate","kind":"symbol","title":"coverControlsDelegate","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"url":"\/documentation\/ovkit\/covercontrolsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverControlsDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Делегат, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":" могут выполнять действия.","type":"text"}],"kind":"symbol","title":"CoverControlsDelegate","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/coverviewtype","navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","title":"CoverViewType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverViewType"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoverView","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverview","kind":"symbol","type":"topic","title":"CoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"coverControlsDelegate"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"coverControlsDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKCoverControlsDelegate>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"coverControlsDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType~1coverControlsDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType~1coverControlsDelegate\/fragments","value":[{"text":"coverControlsDelegate","kind":"identifier"}],"op":"replace"},{"value":"OVKCoverControlsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments","value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle"},{"op":"replace","value":"OVKCoverViewType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments","value":[{"text":"OVKCoverViewType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}