{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"darkBackgroundColor","externalID":"s:5OVKit13CoverViewTypePAAE19darkBackgroundColorSo7UIColorCvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"extendedModule":"OVKit"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Цвет затемнения фона."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/coverviewtype\/darkbackgroundcolor"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/darkBackgroundColor"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"darkBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","title":"CoverViewType","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewType"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CoverViewType"}],"type":"topic","url":"\/documentation\/ovkit\/coverviewtype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/darkBackgroundColor":{"abstract":[{"type":"text","text":"Цвет затемнения фона."}],"kind":"symbol","url":"\/documentation\/ovkit\/coverviewtype\/darkbackgroundcolor","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/darkBackgroundColor","title":"darkBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKCoverViewType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title"},{"op":"replace","value":[{"text":"OVKCoverViewType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCoverViewType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle"}]}]}