{"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKCoverViewType(im)handleCoverWithParams:","symbolKind":"method","title":"handleCoverWithParams(_:)","navigatorTitle":[{"text":"handleCoverWithParams:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleCoverWithParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true,"modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"abstract":[{"type":"text","text":"Если "},{"code":"CoverView","type":"codeVoice"},{"text":" может отрисовать ","type":"text"},{"type":"codeVoice","code":"ControlCoverType"},{"text":", нужно обновить view и вернуть ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Если не может — будет запрошена новая ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":" или подставлена стандартная."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/coverviewtype\/handlecoverwithparams(_:)"]},{"paths":["\/documentation\/ovkit\/coverviewtype\/handlecoverwithparams(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleCoverWithParams"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/handleCoverWithParams(_:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/handleCoverWithParams(_:)":{"abstract":[{"type":"text","text":"Если "},{"code":"CoverView","type":"codeVoice"},{"text":" может отрисовать ","type":"text"},{"type":"codeVoice","code":"ControlCoverType"},{"type":"text","text":", нужно обновить view и вернуть "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Если не может — будет запрошена новая ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":" или подставлена стандартная.","type":"text"}],"role":"symbol","title":"handleCoverWithParams(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/ovkit\/coverviewtype\/handlecoverwithparams(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams"},{"kind":"text","text":"("},{"text":"CoverViewParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/handleCoverWithParams(_:)","navigatorTitle":[{"text":"handleCoverWithParams:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"navigatorTitle":[{"kind":"identifier","text":"CoverViewType"}],"abstract":[],"title":"CoverViewType","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","kind":"symbol","url":"\/documentation\/ovkit\/coverviewtype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewType"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"url":"\/documentation\/ovkit\/coverviewparams","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewParams"}],"type":"topic","title":"CoverViewParams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"handleCoverWithParams:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"handleCoverWithParams:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"handleCoverWithParams:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","kind":"typeIdentifier","text":"OVKCoverViewParams"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"handleCoverWithParams:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType~1handleCoverWithParams(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType~1handleCoverWithParams(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","op":"replace","value":"OVKCoverViewType"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}