{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"abstract":[{"text":"Цвет иконки.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/iconColor"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"iconColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/coverviewtype\/iconcolor"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"title":"iconColor","extendedModule":"OVKit","role":"symbol","externalID":"s:5OVKit13CoverViewTypePAAE9iconColorSo7UIColorCvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"OVKit"}],"symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverviewtype","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","title":"CoverViewType","abstract":[{"text":"Отображение баннера в плеере поверх воспроизведения.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/iconColor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"text":"Цвет иконки.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/iconColor","url":"\/documentation\/ovkit\/coverviewtype\/iconcolor","kind":"symbol","title":"iconColor","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","op":"replace","value":"OVKCoverViewType"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCoverViewType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle","value":[{"text":"OVKCoverViewType","kind":"identifier"}]}]}]}