{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/textColor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/coverviewtype\/textcolor"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Цвет текста."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"kind":"symbol","metadata":{"extendedModule":"OVKit","externalID":"s:5OVKit13CoverViewTypePAAE9textColorSo7UIColorCvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"textColor","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","abstract":[{"type":"text","text":"Отображение баннера в плеере поверх воспроизведения."}],"url":"\/documentation\/ovkit\/coverviewtype","title":"CoverViewType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CoverViewType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/textColor":{"kind":"symbol","type":"topic","title":"textColor","abstract":[{"type":"text","text":"Цвет текста."}],"url":"\/documentation\/ovkit\/coverviewtype\/textcolor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/textColor"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","value":"OVKCoverViewType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle","value":[{"text":"OVKCoverViewType","kind":"identifier"}]}]}]}