{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/coverviewtype\/titlesize"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/titleSize"},"sections":[],"abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}],"metadata":{"externalID":"s:5OVKit13CoverViewTypePAAE9titleSize14CoreFoundation7CGFloatVvp","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"title":"titleSize","extendedModule":"OVKit","role":"symbol","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"title":"CoverViewType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverViewType"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","type":"topic","url":"\/documentation\/ovkit\/coverviewtype","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverViewType"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType/titleSize":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"titleSize","url":"\/documentation\/ovkit\/coverviewtype\/titlesize","abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType\/titleSize","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKCoverViewType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title"},{"value":[{"kind":"identifier","text":"OVKCoverViewType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}