{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Отмена предзагрузки произвольного элемента.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/cancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/cancel(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)cancel:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"cancel(_:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"cancel:","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","role":"symbol","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Отмена предзагрузки произвольного элемента."}],"type":"topic","title":"cancel(_:)"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"title":"IndexPrefetcher","role":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"cancel:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancel:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"id<OVKPrefetchItem>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace","value":"OVKPrefetchItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/title","op":"replace","value":"cancel:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}