{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"abstract":[{"type":"text","text":"Создание префетчера."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","text":"PrefetchStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"cacheContainer","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":" = .main, ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"strategy","content":[{"inlineContent":[{"type":"text","text":"Стратегия загрузки индекса."}],"type":"paragraph"}]},{"name":"groupName","content":[{"inlineContent":[{"type":"text","text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь."}],"type":"paragraph"}]},{"name":"cacheContainer","content":[{"inlineContent":[{"type":"text","text":"Кастомный контейнер для кэша. Если не задан, то будет использоваться общий кэш."}],"type":"paragraph"}]},{"name":"controlQueue","content":[{"inlineContent":[{"type":"text","text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию "},{"type":"codeVoice","code":".main"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"maxConcurrentDownloadsCount","content":[{"inlineContent":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео. Не может быть меньше "},{"type":"codeVoice","code":"1"},{"type":"text","text":". По умолчанию имеет значение "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:cachecontainer:controlqueue:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:cachecontainer:controlqueue:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:"}],"title":"init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"cacheContainer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"symbolKind":"init"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainer"}],"navigatorTitle":[{"kind":"identifier","text":"CacheContainer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","url":"\/documentation\/ovkit\/cachecontainer","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"CacheContainer"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"role":"symbol","title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","url":"\/documentation\/ovkit\/prefetchstrategy","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}],"role":"symbol","title":"PrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:"}],"title":"init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Создание префетчера."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","text":"CacheContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:cachecontainer:controlqueue:maxconcurrentdownloadscount:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStrategy:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchStrategy","kind":"typeIdentifier","text":"id<OVKPrefetchStrategy>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strategy"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupName"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheContainer:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","kind":"typeIdentifier","text":"OVKCacheContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cacheContainer"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlQueue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"controlQueue"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Стратегия загрузки индекса.","type":"text"}]}],"name":"strategy"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь.","type":"text"}]}],"name":"groupName"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Кастомный контейнер для кэша. Если не задан, то будет использоваться общий кэш.","type":"text"}]}],"name":"cacheContainer"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию ","type":"text"},{"type":"codeVoice","code":".main"},{"text":".","type":"text"}]}],"name":"controlQueue"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Максимальное количество параллельно предзагружаемых видео. Не может быть меньше ","type":"text"},{"type":"codeVoice","code":"1"},{"text":". По умолчанию имеет значение ","type":"text"},{"type":"codeVoice","code":"1"},{"text":".","type":"text"}]}],"name":"maxConcurrentDownloadsCount"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"OVKCacheContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title"},{"op":"replace","value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments"},{"op":"replace","value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle"},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"op":"replace","value":"OVKPrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title"},{"op":"replace","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments"},{"op":"replace","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle"},{"op":"replace","value":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}