{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Создание префетчера."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":" = .main)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Стратегия загрузки индекса.","type":"text"}],"type":"paragraph"}],"name":"strategy"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь."}]}],"name":"groupName"},{"content":[{"inlineContent":[{"text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию ","type":"text"},{"type":"codeVoice","code":".main"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"controlQueue"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithStrategy:groupName:controlQueue:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)initWithStrategy:groupName:controlQueue:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(strategy:groupName:controlQueue:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"type":"topic","title":"IndexPrefetcher","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"title":"PrefetchStrategy","url":"\/documentation\/ovkit\/prefetchstrategy","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:controlQueue:)":{"url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:)","title":"init(strategy:groupName:controlQueue:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","kind":"typeIdentifier","text":"PrefetchStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Создание префетчера."}],"navigatorTitle":[{"text":"initWithStrategy:groupName:controlQueue:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithStrategy:groupName:controlQueue:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithStrategy:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKPrefetchStrategy>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"text":") ","kind":"text"},{"text":"strategy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"groupName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"groupName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"controlQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":") ","kind":"text"},{"text":"controlQueue","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"strategy","content":[{"inlineContent":[{"type":"text","text":"Стратегия загрузки индекса."}],"type":"paragraph"}]},{"name":"groupName","content":[{"type":"paragraph","inlineContent":[{"text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь.","type":"text"}]}]},{"name":"controlQueue","content":[{"inlineContent":[{"text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию ","type":"text"},{"code":".main","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","value":"OVKPrefetchStrategy","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:)\/title","value":"initWithStrategy:groupName:controlQueue:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:"}],"op":"replace"}]}]}