{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Initializer","modules":[{"name":"OVKit"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"}],"title":"init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"abstract":[{"type":"text","text":"Создание префетчера."}],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue","kind":"typeIdentifier"},{"text":" = .main, ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Стратегия загрузки индекса."}],"type":"paragraph"}],"name":"strategy"},{"content":[{"inlineContent":[{"type":"text","text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь."}],"type":"paragraph"}],"name":"groupName"},{"content":[{"inlineContent":[{"type":"text","text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию "},{"type":"codeVoice","code":".main"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"controlQueue"},{"content":[{"inlineContent":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео. Не может быть меньше "},{"type":"codeVoice","code":"1"},{"type":"text","text":". По умолчанию имеет значение "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"maxConcurrentDownloadsCount"}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)":{"kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:maxconcurrentdownloadscount:)","abstract":[{"text":"Создание префетчера.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"}],"title":"init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"title":"PrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","url":"\/documentation\/ovkit\/prefetchstrategy","abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"title":"IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"kind":"symbol","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithStrategy:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"id<OVKPrefetchStrategy>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"strategy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"groupName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"groupName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"controlQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"controlQueue","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Стратегия загрузки индекса.","type":"text"}]}],"name":"strategy"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Название для группировки нескольких префетчеров. Префетчеры с одинаковым именем группы делят между собой одну и ту же очередь.","type":"text"}]}],"name":"groupName"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Очередь, на которой происходит обработка очереди префетчера. Она обязательно должна быть serial! По умолчанию ","type":"text"},{"code":".main","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"controlQueue"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Максимальное количество параллельно предзагружаемых видео. Не может быть меньше ","type":"text"},{"code":"1","type":"codeVoice"},{"text":". По умолчанию имеет значение ","type":"text"},{"code":"1","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"maxConcurrentDownloadsCount"}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)\/title","op":"replace","value":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","op":"replace","value":"OVKPrefetchStrategy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}