{"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)prefetch:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"title":"prefetch(_:)","navigatorTitle":[{"text":"prefetch:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Предзагрузка произвольного элемента отдельно от списка.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"],"kind":"mentions"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcher\/prefetch(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcher\/prefetch(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/prefetch(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefetch:"}],"url":"\/documentation\/ovkit\/indexprefetcher\/prefetch(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","title":"prefetch(_:)","abstract":[{"text":"Предзагрузка произвольного элемента отдельно от списка.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"role":"symbol","title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","url":"\/documentation\/ovkit\/prefetch","type":"topic","kind":"article","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"role":"article","title":"Префетчер"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"prefetch:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"prefetch:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"prefetch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"prefetch:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"prefetch:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/fragments"},{"value":"OVKPrefetchItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"},{"value":"OVKIndexPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}