{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка по его IndexPath."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(at:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcher\/prefetch(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcher\/prefetch(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OVKit"}],"title":"prefetch(at:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(im)prefetchAt:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"prefetchAt:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/prefetch(at:)":{"title":"prefetch(at:)","url":"\/documentation\/ovkit\/indexprefetcher\/prefetch(at:)","abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка по его IndexPath."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(at:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"prefetchAt:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"title":"IndexPrefetcher","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prefetchAt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchAt:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"prefetchAt:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(at:)\/title","value":"prefetchAt:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(at:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchAt:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]}]}]}