{"kind":"symbol","abstract":[{"type":"text","text":"Стратегия работы префетчера."}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"}],"externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(py)strategy","role":"symbol","navigatorTitle":[{"text":"strategy","kind":"identifier"}],"title":"strategy"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/strategy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcher\/strategy"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strategy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/strategy"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"type":"topic","title":"PrefetchStrategy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchStrategy"}],"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PrefetchStrategy"}],"url":"\/documentation\/ovkit\/prefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","title":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/strategy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/strategy","type":"topic","abstract":[{"text":"Стратегия работы префетчера.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"strategy"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"}],"url":"\/documentation\/ovkit\/indexprefetcher\/strategy","title":"strategy","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"strategy"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"strategy","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKPrefetchStrategy>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchStrategy","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"strategy"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","op":"replace"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","op":"replace"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","op":"replace"},{"value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace"},{"value":"strategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1strategy\/title","op":"replace"},{"value":[{"text":"strategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1strategy\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}