{"metadata":{"externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashStreams","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashStreams"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashStreams"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","title":"VideoFileFormat.dashStreams"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashStreams","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"abstract":[{"text":"Ссылка на новый единый дэш манифест с раздельными аудио и видео дорожками, содержащий все кодеки и контейнеры, доступные для ролика.","type":"text"},{"text":" ","type":"text"},{"text":"Может быть несколько Adaptation set как с видео, так и с аудио. Для каждого кодека или контейнера отдельный Adaptation set. Также Adaptation set’ы аудио могут различаться языком\/озвучкой, а Adaptation set’ы видео могут различаться динамическим диапазоном: SDR 8 бит и HDR 10 бит.","type":"text"},{"text":" ","type":"text"},{"text":"Запросы байт-ренж реквестами.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashstreams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashstreams"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashStreams","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashStreams":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashStreams","role":"symbol","abstract":[{"type":"text","text":"Ссылка на новый единый дэш манифест с раздельными аудио и видео дорожками, содержащий все кодеки и контейнеры, доступные для ролика."},{"text":" ","type":"text"},{"text":"Может быть несколько Adaptation set как с видео, так и с аудио. Для каждого кодека или контейнера отдельный Adaptation set. Также Adaptation set’ы аудио могут различаться языком\/озвучкой, а Adaptation set’ы видео могут различаться динамическим диапазоном: SDR 8 бит и HDR 10 бит.","type":"text"},{"text":" ","type":"text"},{"text":"Запросы байт-ренж реквестами.","type":"text"}],"navigatorTitle":[{"text":"OVKVideoFileFormatDashStreams","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/dashstreams","type":"topic","title":"VideoFileFormat.dashStreams","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dashStreams","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"type":"topic","url":"\/documentation\/ovkit\/videofileformat","title":"VideoFileFormat","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoFileFormatDashStreams"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatDashStreams"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatDashStreams"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoFileFormatDashStreams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashStreams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashStreams\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashStreams"}]},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}