{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashSep"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"sections":[],"abstract":[{"text":"Ссылка на раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/dashsep"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/dashsep"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"OVKVideoFileFormatDashSep","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashSep","modules":[{"name":"OVKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashSep"}],"roleHeading":"Case","title":"VideoFileFormat.dashSep","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashSep","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashSep":{"kind":"symbol","url":"\/documentation\/ovkit\/videofileformat\/dashsep","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashSep","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashSep"}],"abstract":[{"type":"text","text":"Ссылка на раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashSep","type":"topic","title":"VideoFileFormat.dashSep"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"title":"VideoFileFormat","role":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"OVKVideoFileFormatDashSep","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashSep"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatDashSep"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashSep\/title","value":"OVKVideoFileFormatDashSep"},{"value":[{"text":"OVKVideoFileFormatDashSep","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashSep\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"}]}]}