{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashHevc","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashHevc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashHevc"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashHevc"}],"symbolKind":"case","modules":[{"name":"OVKit"}],"title":"VideoFileFormat.dashHevc"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashHevc","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"abstract":[{"type":"text","text":"Ссылка на раздельный дэш. Формат mp4+h265+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами."}],"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/dashhevc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/dashhevc"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","type":"topic","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"kind":"symbol","url":"\/documentation\/ovkit\/videofileformat","title":"VideoFileFormat"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashHevc":{"type":"topic","navigatorTitle":[{"text":"OVKVideoFileFormatDashHevc","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashHevc","kind":"identifier"}],"title":"VideoFileFormat.dashHevc","url":"\/documentation\/ovkit\/videofileformat\/dashhevc","abstract":[{"type":"text","text":"Ссылка на раздельный дэш. Формат mp4+h265+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashHevc"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKVideoFileFormatDashHevc"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormatDashHevc","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatDashHevc"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashHevc\/title","op":"replace","value":"OVKVideoFileFormatDashHevc"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashHevc\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormatDashHevc","kind":"identifier"}]}]}]}