{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashOndemand"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashondemand"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashondemand"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashOndemand"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Ссылка на ондеманд раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы посегментно."},{"type":"text","text":" "},{"type":"text","text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу."}],"metadata":{"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashOndemand","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashOndemand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashOndemand"}],"title":"VideoFileFormat.dashOndemand"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashOndemand":{"title":"VideoFileFormat.dashOndemand","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashOndemand"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashOndemand","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/dashondemand","abstract":[{"text":"Ссылка на ондеманд раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы посегментно.","type":"text"},{"text":" ","type":"text"},{"text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashOndemand"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","role":"symbol","url":"\/documentation\/ovkit\/videofileformat","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","title":"VideoFileFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKVideoFileFormatDashOndemand","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashOndemand"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKVideoFileFormatDashOndemand","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKVideoFileFormatDashOndemand","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashOndemand\/title"},{"op":"replace","value":[{"text":"OVKVideoFileFormatDashOndemand","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashOndemand\/fragments"},{"op":"replace","value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}]}]}