{"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/dashlive"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashlive"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLive"},"metadata":{"externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashLive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dashLive"}],"role":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}],"roleHeading":"Case","title":"VideoFileFormat.dashLive","modules":[{"name":"OVKit"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dashLive","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"kind":"symbol","abstract":[{"text":"Ссылка на кастомный (не по стандарту) лайв комбо-дэш. Формат mp4+h264+aac.","type":"text"},{"text":" ","type":"text"},{"text":"Используется свой формат root манифеста и манифеста качества jidx.","type":"text"},{"type":"text","text":" "},{"text":"В каждом mp4 сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoFileFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","title":"VideoFileFormat","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videofileformat","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashLive":{"kind":"symbol","abstract":[{"type":"text","text":"Ссылка на кастомный (не по стандарту) лайв комбо-дэш. Формат mp4+h264+aac."},{"text":" ","type":"text"},{"type":"text","text":"Используется свой формат root манифеста и манифеста качества jidx."},{"type":"text","text":" "},{"text":"В каждом mp4 сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLive","url":"\/documentation\/ovkit\/videofileformat\/dashlive","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dashLive"}],"title":"VideoFileFormat.dashLive","role":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"OVKVideoFileFormatDashLive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLive\/title","value":"OVKVideoFileFormatDashLive","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashLive"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLive\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}