{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/dashwebm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/dashwebm"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashWebm","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebm"},"abstract":[{"text":"Ссылка на раздельный дэш. Формат webm+vp9+opus. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами.","type":"text"}],"metadata":{"modules":[{"name":"OVKit"}],"title":"VideoFileFormat.dashWebm","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashWebm","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebm"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashWebm","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashWebm":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebm","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat\/dashwebm","abstract":[{"text":"Ссылка на раздельный дэш. Формат webm+vp9+opus. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebm"}],"title":"VideoFileFormat.dashWebm","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashWebm"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"kind":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"title":"VideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoFileFormatDashWebm","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKVideoFileFormatDashWebm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebm"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoFileFormatDashWebm","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebm\/title"},{"value":[{"text":"OVKVideoFileFormatDashWebm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebm\/fragments"},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}