{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashCmaf","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"OVKVideoFileFormatDashCmaf","kind":"identifier"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dashCmaf","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"OVKit"}],"title":"VideoFileFormat.dashCmaf","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatDashCmaf"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"abstract":[{"type":"text","text":"Ссылка на ондеманд лайв раздельный дэш. Формат mp4+h264+aac. Запросы посегментно."},{"type":"text","text":" "},{"type":"text","text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу."},{"text":" ","type":"text"},{"type":"text","text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/dashcmaf"]},{"paths":["\/documentation\/ovkit\/videofileformat\/dashcmaf"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashCmaf","interfaceLanguage":"swift"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashCmaf":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatDashCmaf","kind":"identifier"}],"abstract":[{"type":"text","text":"Ссылка на ондеманд лайв раздельный дэш. Формат mp4+h264+aac. Запросы посегментно."},{"text":" ","type":"text"},{"type":"text","text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу."},{"type":"text","text":" "},{"text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом.","type":"text"}],"type":"topic","title":"VideoFileFormat.dashCmaf","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashCmaf","url":"\/documentation\/ovkit\/videofileformat\/dashcmaf","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashCmaf","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoFileFormat"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","type":"topic","kind":"symbol","title":"VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoFileFormatDashCmaf"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashCmaf"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatDashCmaf"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashCmaf\/title","value":"OVKVideoFileFormatDashCmaf"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashCmaf\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormatDashCmaf","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]}]}]}