{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hls"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/hls"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/hls"]}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hls"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatHls","role":"symbol","title":"VideoFileFormat.hls","navigatorTitle":[{"text":"OVKVideoFileFormatHls","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"abstract":[{"text":"Ссылка на hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hls"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hls":{"title":"VideoFileFormat.hls","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHls"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/hls","abstract":[{"type":"text","text":"Ссылка на hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"hls","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hls"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videofileformat","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","title":"VideoFileFormat","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"OVKVideoFileFormatHls","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKVideoFileFormatHls","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatHls"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoFileFormatHls","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hls\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKVideoFileFormatHls","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hls\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]}]}]}