{"abstract":[{"type":"text","text":"Ссылка на hls root playlist. Манифест с раздельными аудио дорожками, новый контейнер у медиаданных - fMP4. Кодеки - h264 и aac, но в будущем могут быть и av1 и vp9."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/hlsfmp4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/hlsfmp4"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsFMP4"},"metadata":{"externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatHlsFMP4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsFMP4"}],"symbolKind":"case","modules":[{"name":"OVKit"}],"title":"VideoFileFormat.hlsFMP4","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"OVKVideoFileFormatHlsFMP4","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hlsFMP4","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"title":"VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsFMP4":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsFMP4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsFMP4"}],"title":"VideoFileFormat.hlsFMP4","type":"topic","url":"\/documentation\/ovkit\/videofileformat\/hlsfmp4","kind":"symbol","abstract":[{"text":"Ссылка на hls root playlist. Манифест с раздельными аудио дорожками, новый контейнер у медиаданных - fMP4. Кодеки - h264 и aac, но в будущем могут быть и av1 и vp9.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHlsFMP4"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoFileFormatHlsFMP4","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKVideoFileFormatHlsFMP4","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatHlsFMP4"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"},{"value":"OVKVideoFileFormatHlsFMP4","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsFMP4\/title"},{"value":[{"text":"OVKVideoFileFormatHlsFMP4","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsFMP4\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}