{"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/hlsliveondemand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/hlsliveondemand"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLiveOndemand","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hlsLiveOndemand"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"metadata":{"title":"VideoFileFormat.hlsLiveOndemand","roleHeading":"Case","navigatorTitle":[{"text":"OVKVideoFileFormatHlsLiveOndemand","kind":"identifier"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"hlsLiveOndemand","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatHlsLiveOndemand","modules":[{"name":"OVKit"}]},"kind":"symbol","sections":[],"abstract":[{"text":"Ссылка на ондеманд лайв hls root playlist. Формат ts+h264+aac. Запросы посегментно.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу."},{"type":"text","text":" "},{"type":"text","text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом качества."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLiveOndemand":{"navigatorTitle":[{"text":"OVKVideoFileFormatHlsLiveOndemand","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLiveOndemand"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLiveOndemand","url":"\/documentation\/ovkit\/videofileformat\/hlsliveondemand","type":"topic","title":"VideoFileFormat.hlsLiveOndemand","abstract":[{"type":"text","text":"Ссылка на ондеманд лайв hls root playlist. Формат ts+h264+aac. Запросы посегментно."},{"type":"text","text":" "},{"type":"text","text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу."},{"text":" ","type":"text"},{"text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом качества.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"type":"topic","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","title":"VideoFileFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"OVKVideoFileFormatHlsLiveOndemand","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKVideoFileFormatHlsLiveOndemand","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLiveOndemand"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoFileFormatHlsLiveOndemand","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLiveOndemand\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLiveOndemand\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLiveOndemand"}],"op":"replace"},{"op":"replace","value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}