{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLive"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLive"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/hlslive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/hlslive"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"OVKVideoFileFormatHlsLive","kind":"identifier"}],"title":"VideoFileFormat.hlsLive","role":"symbol","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatHlsLive","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLive"}],"modules":[{"name":"OVKit"}],"symbolKind":"case"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat","type":"topic","kind":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","title":"VideoFileFormat"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLive":{"navigatorTitle":[{"text":"OVKVideoFileFormatHlsLive","kind":"identifier"}],"title":"VideoFileFormat.hlsLive","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hlsLive","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/hlslive"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKVideoFileFormatHlsLive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLive"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKVideoFileFormatHlsLive","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLive\/title","op":"replace","value":"OVKVideoFileFormatHlsLive"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLive\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}