{"metadata":{"roleHeading":"Case","title":"VideoFileFormat.hlsLivePlayback","symbolKind":"case","navigatorTitle":[{"text":"OVKVideoFileFormatHlsLivePlayback","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatHlsLivePlayback","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"hlsLivePlayback","kind":"identifier"}]},"abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist, вариант для перемотки (playback). В урле нужно подменить параметр "},{"type":"codeVoice","code":"offset_p"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLivePlayback"},"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/hlsliveplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformat\/hlsliveplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLivePlayback"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLivePlayback":{"title":"VideoFileFormat.hlsLivePlayback","abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist, вариант для перемотки (playback). В урле нужно подменить параметр "},{"type":"codeVoice","code":"offset_p"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLivePlayback","navigatorTitle":[{"text":"OVKVideoFileFormatHlsLivePlayback","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/hlsliveplayback","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hlsLivePlayback","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/videofileformat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","role":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"title":"VideoFileFormat"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoFileFormatHlsLivePlayback","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLivePlayback"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKVideoFileFormatHlsLivePlayback","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKVideoFileFormatHlsLivePlayback","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLivePlayback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLivePlayback"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLivePlayback\/fragments"},{"op":"replace","value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"}]}]}