{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mp4_1440"}],"modules":[{"name":"OVKit"}],"title":"VideoFileFormat.mp4_1440","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatMp4_1440","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_1440"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mp4_1440","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1440","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/mp4_1440"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/mp4_1440"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_1440":{"title":"VideoFileFormat.mp4_1440","abstract":[{"text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1440","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_1440"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/mp4_1440","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mp4_1440"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/videofileformat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","role":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"title":"VideoFileFormat"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoFileFormatMp4_1440","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_1440"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_1440"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoFileFormatMp4_1440","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1440\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1440\/fragments","value":[{"text":"OVKVideoFileFormatMp4_1440","kind":"identifier"}],"op":"replace"},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}