{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/videofileformat\/mp4_480"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/mp4_480"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_480","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mp4_480","kind":"identifier"}]}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatMp4_480","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_480"}],"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mp4_480"}],"roleHeading":"Case","title":"VideoFileFormat.mp4_480"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"kind":"symbol","url":"\/documentation\/ovkit\/videofileformat","type":"topic","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"title":"VideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_480":{"role":"symbol","abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"url":"\/documentation\/ovkit\/videofileformat\/mp4_480","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_480","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_480"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mp4_480","kind":"identifier"}],"title":"VideoFileFormat.mp4_480"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKVideoFileFormatMp4_480","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_480"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKVideoFileFormatMp4_480","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_480\/title","value":"OVKVideoFileFormatMp4_480","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_480\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_480"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}