{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/mp4_360"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/mp4_360"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_360","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mp4_360"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"title":"VideoFileFormat.mp4_360","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mp4_360"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatMp4_360","symbolKind":"case","roleHeading":"Case"},"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","title":"VideoFileFormat","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_360":{"abstract":[{"text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mp4_360","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_360","url":"\/documentation\/ovkit\/videofileformat\/mp4_360","title":"VideoFileFormat.mp4_360","role":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"OVKVideoFileFormatMp4_360","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"},{"value":"OVKVideoFileFormatMp4_360","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_360\/title"},{"value":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_360\/fragments"}]}]}