{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RawValue"},{"text":" = ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.RawValue"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/rawvalue-swift.typealias"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawValue-swift.typealias","interfaceLanguage":"swift"},"metadata":{"title":"VideoFileFormat.RawValue","modules":[{"name":"OVKit"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"role":"symbol","externalID":"s:5OVKit15VideoFileFormatO8RawValuea","symbolKind":"typealias"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"type":"topic","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","title":"VideoFileFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/RawValue-swift.typealias":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawValue-swift.typealias","abstract":[],"title":"VideoFileFormat.RawValue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RawValue"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawValue"}],"url":"\/documentation\/ovkit\/videofileformat\/rawvalue-swift.typealias","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}