{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmp"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"VideoFileFormat.rtmp","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatRtmp","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rtmp","kind":"identifier"}],"navigatorTitle":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rtmp","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/rtmp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/rtmp"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Ссылка на rtmp. Формат flv+h264+aac. Есть автокачество, сервер будет пытаться отдавать клиенту максимально возможное под его канал разрешение.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Используется для режима минимальной задержки, поэтому не перематывается."}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/rtmp":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rtmp","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtmp"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatRtmp"}],"role":"symbol","abstract":[{"type":"text","text":"Ссылка на rtmp. Формат flv+h264+aac. Есть автокачество, сервер будет пытаться отдавать клиенту максимально возможное под его канал разрешение."},{"type":"text","text":" "},{"type":"text","text":"Используется для режима минимальной задержки, поэтому не перематывается."}],"title":"VideoFileFormat.rtmp","type":"topic","url":"\/documentation\/ovkit\/videofileformat\/rtmp","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"url":"\/documentation\/ovkit\/videofileformat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","title":"VideoFileFormat","kind":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoFileFormatRtmp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}]}],"kind":"declarations"}},{"value":"OVKVideoFileFormatRtmp","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1rtmp\/title"},{"value":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1rtmp\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}]}]}