{"abstract":[{"text":"Ссылка на локальный mp4 файл или на movpkg каталог (используется для загруженных на устройство HLS видео).","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformat\/source"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat\/source"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"]]},"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"}],"title":"VideoFileFormat.source","externalID":"c:@M@OVKit@E@OVKVideoFileFormat@OVKVideoFileFormatSource"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/source"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/source":{"kind":"symbol","url":"\/documentation\/ovkit\/videofileformat\/source","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/source","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"}],"navigatorTitle":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ссылка на локальный mp4 файл или на movpkg каталог (используется для загруженных на устройство HLS видео).","type":"text"}],"role":"symbol","title":"VideoFileFormat.source"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"url":"\/documentation\/ovkit\/videofileformat","title":"VideoFileFormat","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKVideoFileFormatSource","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatSource"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKVideoFileFormatSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1source\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1source\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}