{"abstract":[{"text":"Создает ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","isActive":true},{"type":"text","text":"."}],"sections":[],"kind":"symbol","metadata":{"title":"init(for:wifiQualityRange:cellularQualityRange:)","navigatorTitle":[{"kind":"identifier","text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"wifiQualityRange"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"text":", ","kind":"text"},{"text":"cellularQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKAutoQualityPresetTuner(im)initWithPlayerViews:wifiQualityRange:cellularQualityRange:","roleHeading":"Initializer","role":"symbol","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/init(for:wifiQualityRange:cellularQualityRange:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithPlayerViews:wifiQualityRange:cellularQualityRange:) "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerViews","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"wifiQualityRange"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"kind":"text","text":", "},{"text":"cellularQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"playerViews","content":[{"inlineContent":[{"text":"Плееры, для которых необходимо менять пресет качества.","type":"text"}],"type":"paragraph"}]},{"name":"wifiQualityRange","content":[{"type":"paragraph","inlineContent":[{"text":"Диапазон авто качества для воспроизведения в WiFi сетях.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Диапазон авто качества для воспроизведения в мобильных сетях."}]}],"name":"cellularQualityRange"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/init(for:wifiqualityrange:cellularqualityrange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/init(for:wifiqualityrange:cellularqualityrange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/init(for:wifiQualityRange:cellularQualityRange:)":{"type":"topic","abstract":[{"type":"text","text":"Создает "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"wifiQualityRange","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":", "},{"text":"cellularQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/init(for:wifiQualityRange:cellularQualityRange:)","url":"\/documentation\/ovkit\/autoqualitypresettuner\/init(for:wifiqualityrange:cellularqualityrange:)","kind":"symbol","role":"symbol","title":"init(for:wifiQualityRange:cellularQualityRange:)"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","abstract":[{"text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети.","type":"text"}],"title":"AutoQualityPresetTuner","type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoQualityPresetTuner"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","abstract":[],"type":"topic","title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"url":"\/documentation\/ovkit\/qualityrange","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityRange"}],"type":"topic","role":"symbol","title":"QualityRange","navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"abstract":[{"type":"text","text":"Диапазон качества видео."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithPlayerViews:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<OVKPlayerView *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"playerViews"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wifiQualityRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"OVKQualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"text":" *) ","kind":"text"},{"text":"wifiQualityRange","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellularQualityRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cellularQualityRange"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"playerViews","content":[{"inlineContent":[{"type":"text","text":"Плееры, для которых необходимо менять пресет качества."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Диапазон авто качества для воспроизведения в WiFi сетях."}]}],"name":"wifiQualityRange"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Диапазон авто качества для воспроизведения в мобильных сетях."}]}],"name":"cellularQualityRange"}]},"op":"replace"},{"value":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1init(for:wifiQualityRange:cellularQualityRange:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1init(for:wifiQualityRange:cellularQualityRange:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","value":"OVKAutoQualityPresetTuner"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"OVKQualityRange","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKQualityRange"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"kind":"identifier","text":"OVKQualityRange"}]}]}]}