{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/networkStatus-swift.property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkStatus"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","text":"NetworkStatus","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.property"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkStatus"},{"kind":"text","text":": "},{"text":"NetworkStatus","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO"}],"navigatorTitle":[{"text":"networkStatus","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKAutoQualityPresetTuner(py)networkStatus","roleHeading":"Instance Property","title":"networkStatus","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/networkStatus-swift.property":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkStatus"},{"kind":"text","text":": "},{"text":"NetworkStatus","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO"}],"navigatorTitle":[{"kind":"identifier","text":"networkStatus"}],"type":"topic","title":"networkStatus","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.property","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/networkStatus-swift.property"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKAutoQualityPresetTunerNetworkStatus":{"url":"\/documentation\/ovkit\/ovkautoqualitypresettunernetworkstatus","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"OVKAutoQualityPresetTunerNetworkStatus"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAutoQualityPresetTunerNetworkStatus","abstract":[{"text":"Статусы доступности сети.","type":"text"}],"title":"OVKAutoQualityPresetTunerNetworkStatus"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Статусы доступности сети."}],"title":"AutoQualityPresetTuner.NetworkStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","navigatorTitle":[{"text":"NetworkStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"url":"\/documentation\/ovkit\/autoqualitypresettuner","kind":"symbol","title":"AutoQualityPresetTuner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","abstract":[{"text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoQualityPresetTuner"}],"navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"networkStatus","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"networkStatus"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKAutoQualityPresetTunerNetworkStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAutoQualityPresetTunerNetworkStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKAutoQualityPresetTunerNetworkStatus"},{"kind":"text","text":" "},{"text":"networkStatus","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1networkStatus-swift.property\/title","op":"replace","value":"networkStatus"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1networkStatus-swift.property\/fragments","value":[{"kind":"identifier","text":"networkStatus"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","value":"OVKAutoQualityPresetTuner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle"}]}]}