{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(updateWifiQualityRange:cellularQualityRange:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"wifiQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellularQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKAutoQualityPresetTuner(im)updateWifiQualityRange:cellularQualityRange:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"wifiQualityRange","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellularQualityRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"role":"symbol","title":"update(wifiQualityRange:cellularQualityRange:)","navigatorTitle":[{"kind":"identifier","text":"updateWifiQualityRange:cellularQualityRange:"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/update(wifiqualityrange:cellularqualityrange:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/autoqualitypresettuner\/update(wifiqualityrange:cellularqualityrange:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/update(wifiQualityRange:cellularQualityRange:)"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"url":"\/documentation\/ovkit\/qualityrange","role":"symbol","type":"topic","title":"QualityRange","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/update(wifiQualityRange:cellularQualityRange:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"wifiQualityRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellularQualityRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/autoqualitypresettuner\/update(wifiqualityrange:cellularqualityrange:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/update(wifiQualityRange:cellularQualityRange:)","role":"symbol","title":"update(wifiQualityRange:cellularQualityRange:)","navigatorTitle":[{"kind":"identifier","text":"updateWifiQualityRange:cellularQualityRange:"}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"type":"topic","url":"\/documentation\/ovkit\/autoqualitypresettuner","title":"AutoQualityPresetTuner","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutoQualityPresetTuner","kind":"identifier"}],"navigatorTitle":[{"text":"AutoQualityPresetTuner","kind":"identifier"}],"abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"updateWifiQualityRange:cellularQualityRange:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateWifiQualityRange:cellularQualityRange:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"updateWifiQualityRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKQualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"text":" *) ","kind":"text"},{"text":"wifiQualityRange","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellularQualityRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKQualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"text":" *) ","kind":"text"},{"text":"cellularQualityRange","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","op":"replace","value":"OVKQualityRange"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","op":"replace","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKQualityRange"}]},{"value":"updateWifiQualityRange:cellularQualityRange:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1update(wifiQualityRange:cellularQualityRange:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"updateWifiQualityRange:cellularQualityRange:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1update(wifiQualityRange:cellularQualityRange:)\/fragments","op":"replace"},{"value":"OVKAutoQualityPresetTuner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAutoQualityPresetTuner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}