{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"]]},"variants":[{"paths":["\/documentation\/ovkit\/persistentitem\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","externalID":"s:5OVKit14PersistentItemC4fromACs7Decoder_p_tKcfc","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/init(from:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/persistentitem\/init(from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/init(from:)","role":"symbol","title":"init(from:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","kind":"symbol","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}