{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistentitem\/selectedmediaoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentitem\/selectedmediaoptions"]}],"metadata":{"navigatorTitle":[{"text":"selectedMediaOptions","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedMediaOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption"},{"text":"]?","kind":"text"}],"title":"selectedMediaOptions","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItem(py)selectedMediaOptions","role":"symbol","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/selectedMediaOptions"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"]]},"abstract":[{"text":"Какие дорожки выбраны для скачивания. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает все доступные аудио- и видеодорожки. Неподдерживаемые будут отфильтрованы при скачивании.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedMediaOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption"},{"text":"]?","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistentitem","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"title":"PersistentItem","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption":{"type":"topic","navigatorTitle":[{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistentmediaselectionoption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption","title":"PersistentMediaSelectionOption","role":"symbol","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/selectedMediaOptions":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/selectedMediaOptions","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistentitem\/selectedmediaoptions","navigatorTitle":[{"kind":"identifier","text":"selectedMediaOptions"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedMediaOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption","text":"PersistentMediaSelectionOption"},{"kind":"text","text":"]?"}],"abstract":[{"text":"Какие дорожки выбраны для скачивания. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает все доступные аудио- и видеодорожки. Неподдерживаемые будут отфильтрованы при скачивании.","type":"text"}],"title":"selectedMediaOptions","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"selectedMediaOptions","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"selectedMediaOptions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<OVKPersistentMediaSelectionOption *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"selectedMediaOptions"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"value":"OVKPersistentMediaSelectionOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/title"},{"value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/fragments"},{"value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/navigatorTitle"},{"value":"selectedMediaOptions","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1selectedMediaOptions\/title"},{"value":[{"text":"selectedMediaOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1selectedMediaOptions\/fragments"}]}]}