{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"contentRect","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/contentrect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/contentrect"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/contentRect","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"contentRect"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"title":"contentRect","externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail(py)contentRect","symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"abstract":[{"type":"text","text":"Границы нужного кадра. Необходимо установить в свойство layer.contentsRect у объекта "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":", показывающего кадр."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"title":"ThumbnailProviderThumbnail","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","abstract":[{"type":"text","text":"Описание изображения для thumbnail."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKThumbnailProviderThumbnail/contentRect":{"url":"\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/contentrect","title":"contentRect","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/contentRect","kind":"symbol","abstract":[{"type":"text","text":"Границы нужного кадра. Необходимо установить в свойство layer.contentsRect у объекта "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":", показывающего кадр."}],"navigatorTitle":[{"kind":"identifier","text":"contentRect"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"contentRect","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"contentRect"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" "},{"text":"contentRect","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title","value":"OVKThumbnailProviderThumbnail","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKThumbnailProviderThumbnail"}]},{"op":"replace","value":"contentRect","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1contentRect\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1contentRect\/fragments","value":[{"kind":"identifier","text":"contentRect"}],"op":"replace"}]}]}