{"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail(py)image","navigatorTitle":[{"kind":"identifier","text":"image"}],"title":"image","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/image","interfaceLanguage":"swift"},"abstract":[{"text":"Изображение со множеством кадров.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/image"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKThumbnailProviderThumbnail/image":{"title":"image","kind":"symbol","url":"\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/image","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/image","type":"topic","abstract":[{"text":"Изображение со множеством кадров.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","title":"ThumbnailProviderThumbnail","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","navigatorTitle":[{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"role":"symbol","abstract":[{"text":"Описание изображения для thumbnail.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"image"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1image\/title","value":"image"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1image\/fragments"},{"op":"replace","value":"OVKThumbnailProviderThumbnail","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title"},{"value":[{"kind":"identifier","text":"OVKThumbnailProviderThumbnail"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}