{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredMode"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":": "},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)audioSessionPreferredMode","title":"audioSessionPreferredMode","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionPreferredMode"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioSessionPreferredMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredmode"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"kind":"symbol","title":"PlayerManager","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManager"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/audioSessionPreferredMode":{"navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredMode"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionPreferredMode","url":"\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredmode","kind":"symbol","title":"audioSessionPreferredMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"audioSessionPreferredMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"audioSessionPreferredMode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionPreferredMode\/title","value":"audioSessionPreferredMode"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionPreferredMode\/fragments","op":"replace","value":[{"text":"audioSessionPreferredMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}