{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)audioSessionPreferredCategory","roleHeading":"Instance Property","symbolKind":"property","title":"audioSessionPreferredCategory","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"}],"navigatorTitle":[{"text":"audioSessionPreferredCategory","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredCategory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Category","preciseIdentifier":"c:@T@AVAudioSessionCategory"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionPreferredCategory","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredcategory"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredcategory"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/audioSessionPreferredCategory":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionPreferredCategory","abstract":[],"navigatorTitle":[{"text":"audioSessionPreferredCategory","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"audioSessionPreferredCategory","url":"\/documentation\/ovkit\/ovkplayermanager\/audiosessionpreferredcategory","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredCategory","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"url":"\/documentation\/ovkit\/playermanager","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerManager","kind":"identifier"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"audioSessionPreferredCategory"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"audioSessionPreferredCategory"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"audioSessionPreferredCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionPreferredCategory\/title"},{"value":[{"kind":"identifier","text":"audioSessionPreferredCategory"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionPreferredCategory\/fragments","op":"replace"},{"op":"replace","value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}