{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionroutesharingpolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/audiosessionroutesharingpolicy"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionRouteSharingPolicy"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"audioSessionRouteSharingPolicy"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionRouteSharingPolicy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"RouteSharingPolicy","kind":"typeIdentifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)audioSessionRouteSharingPolicy","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","title":"audioSessionRouteSharingPolicy"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioSessionRouteSharingPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"RouteSharingPolicy"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/audioSessionRouteSharingPolicy":{"navigatorTitle":[{"kind":"identifier","text":"audioSessionRouteSharingPolicy"}],"role":"symbol","title":"audioSessionRouteSharingPolicy","url":"\/documentation\/ovkit\/ovkplayermanager\/audiosessionroutesharingpolicy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/audioSessionRouteSharingPolicy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioSessionRouteSharingPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"RouteSharingPolicy"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"kind":"symbol","title":"PlayerManager","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"audioSessionRouteSharingPolicy","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"audioSessionRouteSharingPolicy","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"AVAudioSessionRouteSharingPolicy","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionRouteSharingPolicy"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"audioSessionRouteSharingPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionRouteSharingPolicy\/title"},{"op":"replace","value":[{"text":"audioSessionRouteSharingPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1audioSessionRouteSharingPolicy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]}]}]}