{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/delegate"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"PlayerManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"Необходимо установить как можно раньше.","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate","text":"PlayerManagerDelegate"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)delegate","symbolKind":"property","role":"symbol"},"abstract":[{"type":"text","text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","url":"\/documentation\/ovkit\/playermanager","title":"PlayerManager"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/delegate":{"title":"delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerManagerDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkplayermanager\/delegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/delegate","abstract":[{"text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManagerDelegate"}],"kind":"symbol","title":"PlayerManagerDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","abstract":[],"url":"\/documentation\/ovkit\/playermanagerdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerManagerDelegate","text":"id<OVKPlayerManagerDelegate>"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate","op":"replace"},{"value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"}]}]}