{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/idleTimerManager","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idleTimerManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIdleTimerManager","text":"IdleTimerManager","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию содержит готовую реализацию, которая управляет свойством "},{"type":"codeVoice","code":"UIApplication.shared.isIdleTimerDisabled"},{"type":"text","text":". Если это свойство используется в других местах в приложении, необходимо предоставить собственный "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","type":"reference"},{"text":".","type":"text"}]},{"style":"warning","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Необходимо установить как можно раньше.","type":"text"}]}],"type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/idletimermanager"]},{"paths":["\/documentation\/ovkit\/ovkplayermanager\/idletimermanager"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"idleTimerManager","kind":"identifier"}],"title":"idleTimerManager","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idleTimerManager","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIdleTimerManager","kind":"typeIdentifier","text":"IdleTimerManager"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)idleTimerManager"},"references":{"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdleTimerManager","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"type":"topic","title":"IdleTimerManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"url":"\/documentation\/ovkit\/idletimermanager"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/idleTimerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/idleTimerManager","abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"navigatorTitle":[{"text":"idleTimerManager","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"idleTimerManager","url":"\/documentation\/ovkit\/ovkplayermanager\/idletimermanager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"idleTimerManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIdleTimerManager","text":"IdleTimerManager"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"url":"\/documentation\/ovkit\/playermanager","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerManager","kind":"identifier"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"idleTimerManager","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"idleTimerManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"id<OVKIdleTimerManager>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKIdleTimerManager","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idleTimerManager"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title","op":"replace","value":"OVKIdleTimerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1idleTimerManager\/title","op":"replace","value":"idleTimerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1idleTimerManager\/fragments","value":[{"text":"idleTimerManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"}]}]}