{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pipWindow","kind":"identifier"},{"kind":"text","text":": "},{"text":"PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/pipWindow"},"variants":[{"paths":["\/documentation\/ovkit\/ovkplayermanager\/pipwindow"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/pipwindow"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)pipWindow","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"pipWindow","kind":"identifier"}],"title":"pipWindow"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","url":"\/documentation\/ovkit\/playermanager","title":"PlayerManager"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/pipWindow":{"navigatorTitle":[{"text":"pipWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkplayermanager\/pipwindow","kind":"symbol","abstract":[],"type":"topic","title":"pipWindow","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipWindow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/pipWindow","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"kind":"symbol","title":"PiPWindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","abstract":[{"type":"text","text":"Device Orientation для "},{"type":"codeVoice","code":"PlayerManager.shared.pipWindow"},{"text":" можно поддержать","type":"text"},{"type":"text","text":" "},{"type":"text","text":"в методе AppDelegate "},{"type":"codeVoice","code":"application(_:supportedIntefaceOrientationsFor:)"}],"url":"\/documentation\/ovkit\/pipwindow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"pipWindow","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"pipWindow","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"OVKPiPWindow","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1pipWindow\/title","value":"pipWindow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1pipWindow\/fragments","op":"replace","value":[{"kind":"identifier","text":"pipWindow"}]},{"op":"replace","value":"OVKPiPWindow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"text":"OVKPiPWindow","kind":"identifier"}]}]}]}