{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playbackActive","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"К этому относится непосредственное воспроизведение видео, буферизация перед стартом или уже во время воспроизведения."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)playbackActive","modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"playbackActive","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"playbackActive"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/playbackActive","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayermanager\/playbackactive"]},{"paths":["\/documentation\/ovkit\/ovkplayermanager\/playbackactive"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Идет ли в данный момент воспроизведение видео хотя бы одним из плееров, либо хотя бы один плеер собирается воспроизводить видео.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/playbackActive":{"navigatorTitle":[{"text":"playbackActive","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkplayermanager\/playbackactive","kind":"symbol","abstract":[{"text":"Идет ли в данный момент воспроизведение видео хотя бы одним из плееров, либо хотя бы один плеер собирается воспроизводить видео.","type":"text"}],"title":"playbackActive","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackActive","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/playbackActive","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","url":"\/documentation\/ovkit\/playermanager","title":"PlayerManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playbackActive","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"playbackActive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackActive"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1playbackActive\/title","value":"playbackActive"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerManager~1playbackActive\/fragments","value":[{"text":"playbackActive","kind":"identifier"}]},{"value":"OVKPlayerManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"text":"OVKPlayerManager","kind":"identifier"}]}]}]}