{"variants":[{"paths":["\/documentation\/ovkit\/adtimelineview\/init(size:progresscolor:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progressColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"size","content":[{"inlineContent":[{"text":"Начальный размер таймлайна.","type":"text"}],"type":"paragraph"}]},{"name":"progressColor","content":[{"inlineContent":[{"text":"Цвет для отображения прогресса. По умолчанию используется жёлтый.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/init(size:progressColor:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progressColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","externalID":"s:5OVKit14AdTimelineViewC4size13progressColorACSo6CGSizeV_So7UIColorCSgtcfc","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"init","title":"init(size:progressColor:)"},"abstract":[{"text":"Инициализатор таймлайна.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdTimelineView","kind":"identifier"}],"url":"\/documentation\/ovkit\/adtimelineview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","abstract":[{"type":"text","text":"Таймлайн воспроизведения для рекламы."}],"title":"AdTimelineView","type":"topic","navigatorTitle":[{"text":"AdTimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/init(size:progressColor:)":{"title":"init(size:progressColor:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/init(size:progressColor:)","role":"symbol","url":"\/documentation\/ovkit\/adtimelineview\/init(size:progresscolor:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progressColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Инициализатор таймлайна."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title","value":"OVKAdTimelineView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments","value":[{"text":"OVKAdTimelineView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle","value":[{"text":"OVKAdTimelineView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}