{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/adtimelineview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/adtimelineview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKAdTimelineView(im)layoutSubviews","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"role":"symbol","title":"layoutSubviews()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/layoutSubviews()"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"navigatorTitle":[{"kind":"identifier","text":"AdTimelineView"}],"type":"topic","url":"\/documentation\/ovkit\/adtimelineview","abstract":[{"type":"text","text":"Таймлайн воспроизведения для рекламы."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","title":"AdTimelineView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdTimelineView"}]},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/layoutSubviews()":{"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/layoutSubviews()","url":"\/documentation\/ovkit\/adtimelineview\/layoutsubviews()","role":"symbol","kind":"symbol","title":"layoutSubviews()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"layoutSubviews"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title","op":"replace","value":"OVKAdTimelineView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView~1layoutSubviews()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}