{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rounded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"title":"rounded","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:5OVKit14AdTimelineViewC7roundedSbvp","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rounded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/rounded"},"kind":"symbol","abstract":[{"type":"text","text":"Флаг, определяющий визуальное скругление таймлайна по краям ."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adtimelineview\/rounded"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/rounded":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/rounded","title":"rounded","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/adtimelineview\/rounded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rounded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Флаг, определяющий визуальное скругление таймлайна по краям .","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdTimelineView"}],"title":"AdTimelineView","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Таймлайн воспроизведения для рекламы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","url":"\/documentation\/ovkit\/adtimelineview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdTimelineView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title","value":"OVKAdTimelineView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments","op":"replace","value":[{"text":"OVKAdTimelineView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle","value":[{"text":"OVKAdTimelineView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}