{"abstract":[{"text":"Флаг, определяющий визуальное скругление полосы прогресса.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/roundedProgress","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adtimelineview\/roundedprogress"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedProgress"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","externalID":"s:5OVKit14AdTimelineViewC15roundedProgressSbvp","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"roundedProgress"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/roundedProgress":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/roundedProgress","url":"\/documentation\/ovkit\/adtimelineview\/roundedprogress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedProgress"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","title":"roundedProgress","role":"symbol","abstract":[{"text":"Флаг, определяющий визуальное скругление полосы прогресса.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdTimelineView","kind":"identifier"}],"url":"\/documentation\/ovkit\/adtimelineview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","abstract":[{"type":"text","text":"Таймлайн воспроизведения для рекламы."}],"title":"AdTimelineView","type":"topic","navigatorTitle":[{"text":"AdTimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title","value":"OVKAdTimelineView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments","value":[{"text":"OVKAdTimelineView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKAdTimelineView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}