{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRateCache"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideoRateCache(im)init","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRateCache\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkvideoratecache\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRateCache/init":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRateCache\/init","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkvideoratecache\/init"},"doc://onevideo.OVKit/documentation/OVKit/VideoRateCache":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRateCache","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRateCache","kind":"identifier"}],"title":"VideoRateCache","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoRateCache"}],"type":"topic","url":"\/documentation\/ovkit\/videoratecache"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRateCache\/title","value":"OVKVideoRateCache","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoRateCache"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRateCache\/fragments","op":"replace"},{"op":"replace","value":[{"text":"OVKVideoRateCache","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRateCache\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}