{"metadata":{"title":"getThumbnail(for:completion:)","externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProvider(im)getThumbnailFor:completion:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getThumbnailFor:completion:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ThumbnailProviderThumbnail","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/ovkit\/thumbnailprovider\/getthumbnail(for:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/thumbnailprovider\/getthumbnail(for:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Получение thumbnail."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:completion:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","text":"ThumbnailProviderThumbnail"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"text":"Время, для которого вернуть thumbnail.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Блок, который вызывается по окончанию загрузки. Если внутри ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" - при загрузке произошла ошибка. Блок вызывается на главной очереди.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/getThumbnail(for:completion:)":{"kind":"symbol","title":"getThumbnail(for:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getThumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","kind":"typeIdentifier","text":"ThumbnailProviderThumbnail"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"getThumbnailFor:completion:"}],"url":"\/documentation\/ovkit\/thumbnailprovider\/getthumbnail(for:completion:)","abstract":[{"type":"text","text":"Получение thumbnail."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:completion:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"abstract":[{"text":"Описание изображения для thumbnail.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","title":"ThumbnailProviderThumbnail"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","url":"\/documentation\/ovkit\/thumbnailprovider","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"abstract":[{"text":"Класс, который асинхронно получает thumbnail для указанного времени видео.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThumbnailProvider"}],"title":"ThumbnailProvider","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"getThumbnailFor:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getThumbnailFor:completion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"getThumbnailFor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","text":"OVKThumbnailProviderThumbnail","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"text":"Время, для которого вернуть thumbnail.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Блок, который вызывается по окончанию загрузки. Если внутри ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" - при загрузке произошла ошибка. Блок вызывается на главной очереди.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider~1getThumbnail(for:completion:)\/title","value":"getThumbnailFor:completion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider~1getThumbnail(for:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getThumbnailFor:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title","value":"OVKThumbnailProviderThumbnail","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/navigatorTitle","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"op":"replace"}]}]}