{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/anyequatableshoppableadsitemviewprotocol\/itembadgestyle"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"itemBadgeStyle"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","text":"AdsItemBadge","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","text":"Style"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AnyEquatableShoppableAdsItemViewProtocol\/itemBadgeStyle","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ShoppableAdsItemViewProtocol.itemBadgeStyle"},{"text":".","type":"text"}],"metadata":{"externalID":"s:5OVKit40AnyEquatableShoppableAdsItemViewProtocolC14itemBadgeStyleAA0efJ0C0K0Ovp","role":"symbol","symbolKind":"property","title":"itemBadgeStyle","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemBadgeStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"AdsItemBadge","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","kind":"typeIdentifier","text":"Style"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AnyEquatableShoppableAdsItemViewProtocol"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AnyEquatableShoppableAdsItemViewProtocol/itemBadgeStyle":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"itemBadgeStyle"},{"text":": ","kind":"text"},{"text":"AdsItemBadge","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","text":"Style"}],"url":"\/documentation\/ovkit\/anyequatableshoppableadsitemviewprotocol\/itembadgestyle","type":"topic","abstract":[],"title":"itemBadgeStyle","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AnyEquatableShoppableAdsItemViewProtocol\/itemBadgeStyle","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}],"title":"AdsItemBadge.Style","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AnyEquatableShoppableAdsItemViewProtocol":{"url":"\/documentation\/ovkit\/anyequatableshoppableadsitemviewprotocol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnyEquatableShoppableAdsItemViewProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnyEquatableShoppableAdsItemViewProtocol"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AnyEquatableShoppableAdsItemViewProtocol","kind":"symbol","role":"symbol","title":"AnyEquatableShoppableAdsItemViewProtocol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdsItemBadge","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","url":"\/documentation\/ovkit\/adsitembadge","title":"AdsItemBadge","kind":"symbol","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}],"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AdsItemBadge","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"kind":"identifier","text":"AdsItemBadge"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","op":"replace","value":[{"text":"AdsItemBadge","kind":"identifier"}]}]}]}