{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_disclaimer","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","text":"MyTargetInstreamAdVideoMotionDisclaimer"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_disclaimer"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData"]]},"metadata":{"required":true,"role":"symbol","navigatorTitle":[{"text":"ovkit_disclaimer","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_disclaimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","text":"MyTargetInstreamAdVideoMotionDisclaimer"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"ovkit_disclaimer","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData(py)ovkit_disclaimer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_disclaimer"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_disclaimer"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionDisclaimer":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondisclaimer","abstract":[],"title":"MyTargetInstreamAdVideoMotionDisclaimer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData/ovkit_disclaimer":{"kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ovkit_disclaimer"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ovkit_disclaimer","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_disclaimer","abstract":[],"title":"ovkit_disclaimer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_disclaimer"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionData"}],"abstract":[],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata","title":"MyTargetInstreamAdVideoMotionData","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ovkit_disclaimer"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ovkit_disclaimer"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","text":"id<MyTargetInstreamAdVideoMotionDisclaimer>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"ovkit_disclaimer","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer\/title","value":"MyTargetInstreamAdVideoMotionDisclaimer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_disclaimer\/title","value":"ovkit_disclaimer","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ovkit_disclaimer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_disclaimer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/title","value":"MyTargetInstreamAdVideoMotionData"},{"value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/fragments"}]}]}