{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_header","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionHeader","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData(py)ovkit_header","title":"ovkit_header","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ovkit_header"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader"}],"navigatorTitle":[{"text":"ovkit_header","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_header"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_header"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_header"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData":{"title":"MyTargetInstreamAdVideoMotionData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionData"}],"kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData/ovkit_header":{"title":"ovkit_header","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_header","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionHeader","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"ovkit_header","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_header","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_header","required":true,"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader","role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"MyTargetInstreamAdVideoMotionHeader","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionHeader"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ovkit_header"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"ovkit_header","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader","text":"id<MyTargetInstreamAdVideoMotionHeader>"},{"text":" ","kind":"text"},{"text":"ovkit_header","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/title","op":"replace","value":"MyTargetInstreamAdVideoMotionData"},{"value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_header\/title","value":"ovkit_header"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_header\/fragments","value":[{"text":"ovkit_header","kind":"identifier"}]},{"value":"MyTargetInstreamAdVideoMotionHeader","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader\/title"},{"value":[{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}