{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerImage"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovktimelinethumbnailstype\/countperimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovktimelinethumbnailstype\/countperimage"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countPerImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"countPerImage","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType(py)countPerImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countPerImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"countPerImage"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","required":true},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/countPerImage":{"title":"countPerImage","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerImage","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"countPerImage"}],"role":"symbol","kind":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countPerImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/countperimage"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"title":"TimelineThumbnailsType","role":"symbol","navigatorTitle":[{"text":"TimelineThumbnailsType","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TimelineThumbnailsType","kind":"identifier"}],"url":"\/documentation\/ovkit\/timelinethumbnailstype","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"countPerImage"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"countPerImage"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"countPerImage","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"countPerImage","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerImage\/fragments","value":[{"kind":"identifier","text":"countPerImage"}]},{"value":"OVKTimelineThumbnailsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}