{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"downloadFile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preferHLS"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile","text":"VideoFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoFile"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/downloadFile(preferHLS:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"downloadFile"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preferHLS"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoFile","kind":"typeIdentifier","text":"VideoFile"},{"text":"?","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit9VideoTypePAAE12downloadFile9preferHLSAA0bE0CSgSb_tF::SYNTHESIZED::c:@M@OVKit@objc(cs)OVKVideo","title":"downloadFile(preferHLS:)","extendedModule":"OVKit"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/VideoType-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"VideoType.downloadFile(preferHLS:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/downloadfile(preferhls:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFile":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoFile"}],"url":"\/documentation\/ovkit\/videofile","navigatorTitle":[{"text":"VideoFile","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile","type":"topic","abstract":[],"title":"VideoFile"},"doc://onevideo.OVKit/documentation/OVKit/Video/downloadFile(preferHLS:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"downloadFile","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferHLS"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"VideoFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoFile"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/downloadFile(preferHLS:)","url":"\/documentation\/ovkit\/video\/downloadfile(preferhls:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"downloadFile(preferHLS:)"},"doc://onevideo.OVKit/documentation/OVKit/Video/VideoType-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/ovkit\/video\/videotype-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/VideoType-Implementations","type":"topic","abstract":[],"title":"VideoType Implementations"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"url":"\/documentation\/ovkit\/video","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"role":"symbol","title":"Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKVideoFile","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/fragments","value":[{"kind":"identifier","text":"OVKVideoFile"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFile"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"}]}]}