{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/init(id:)"]},{"paths":["\/documentation\/ovkit\/video\/init(id:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Идентификатор видео на ","type":"text"},{"type":"codeVoice","code":"vk.com"},{"type":"text","text":". Должен состоять из двух чисел, разделенных подчеркиванием "},{"type":"codeVoice","code":"_"},{"type":"text","text":"."}]}],"name":"id"}]}],"metadata":{"title":"init(id:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"initWithId:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@OVKit@objc(cs)OVKVideo(im)initWithId:","symbolKind":"init","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(id:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Создание модели видео."},{"text":" ","type":"text"},{"text":"После создания модель необходимо наполнить данными.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Video/init(id:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Создание модели видео."},{"type":"text","text":" "},{"type":"text","text":"После создания модель необходимо наполнить данными."}],"title":"init(id:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(id:)","navigatorTitle":[{"text":"initWithId:","kind":"identifier"}],"url":"\/documentation\/ovkit\/video\/init(id:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"title":"Video","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/video","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithId:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithId:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"id","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"id","content":[{"inlineContent":[{"text":"Идентификатор видео на ","type":"text"},{"type":"codeVoice","code":"vk.com"},{"text":". Должен состоять из двух чисел, разделенных подчеркиванием ","type":"text"},{"code":"_","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1init(id:)\/title","value":"initWithId:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1init(id:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}