{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/isspherical"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/isspherical"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"text":"Является ли видеозапись сферическим 360-видео.","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"isSpherical","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)isSpherical","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSpherical"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isSpherical"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isSpherical"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpherical"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"url":"\/documentation\/ovkit\/video","title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/isSpherical":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isSpherical","role":"symbol","abstract":[{"text":"Является ли видеозапись сферическим 360-видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpherical"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isSpherical","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSpherical"}],"type":"topic","url":"\/documentation\/ovkit\/video\/isspherical"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","role":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/videotype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"isSpherical","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isSpherical","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpherical"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isSpherical\/title","value":"isSpherical"},{"op":"replace","value":[{"kind":"identifier","text":"isSpherical"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isSpherical\/fragments"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}