{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettingsUpdate(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Обновляет состояние прямой трансляции."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/livesettingsupdate(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/livesettingsupdate(with:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettingsUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"title":"liveSettingsUpdate(with:)","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKVideo(im)liveSettingsUpdateWith:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveSettingsUpdateWith:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettingsUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxRewindDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"maxRewindDuration","content":[{"type":"paragraph","inlineContent":[{"text":"Максимальный интервал, на который можно отмотать прямую трансляцию.","type":"text"}]}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/liveSettingsUpdate(with:)":{"url":"\/documentation\/ovkit\/video\/livesettingsupdate(with:)","navigatorTitle":[{"kind":"identifier","text":"liveSettingsUpdateWith:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettingsUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Обновляет состояние прямой трансляции."}],"title":"liveSettingsUpdate(with:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettingsUpdate(with:)"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","title":"Video","type":"topic","abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","role":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"liveSettingsUpdateWith:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"liveSettingsUpdateWith:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"liveSettingsUpdateWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"maxRewindDuration","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"maxRewindDuration","content":[{"type":"paragraph","inlineContent":[{"text":"Максимальный интервал, на который можно отмотать прямую трансляцию.","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettingsUpdate(with:)\/title","value":"liveSettingsUpdateWith:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettingsUpdate(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"liveSettingsUpdateWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}]}]}