{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"liveSettings"}],"title":"liveSettings","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)liveSettings"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettings"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/livesettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/livesettings"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/liveSettings":{"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/video\/livesettings","navigatorTitle":[{"kind":"identifier","text":"liveSettings"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettings","title":"liveSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"liveSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","title":"VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"url":"\/documentation\/ovkit\/videotype","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"url":"\/documentation\/ovkit\/livesettings","title":"LiveSettings","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveSettings","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"LiveSettings","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"type":"topic","kind":"symbol","title":"Video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/video","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"liveSettings"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"liveSettings","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKLiveSettings","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"},{"text":" * ","kind":"text"},{"text":"liveSettings","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettings\/title","op":"replace","value":"liveSettings"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"liveSettings"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","op":"replace","value":"OVKLiveSettings"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKLiveSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLiveSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}]}]}]}