{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"liveSpectators","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"liveSpectators","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)liveSpectators","navigatorTitle":[{"text":"liveSpectators","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveSpectators"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"VideoType.liveSpectators","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/livespectators"]},{"paths":["\/documentation\/ovkit\/video\/livespectators"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSpectators","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"type":"topic","title":"Video","kind":"symbol","url":"\/documentation\/ovkit\/video","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},"doc://onevideo.OVKit/documentation/OVKit/Video/liveSpectators":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveSpectators"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSpectators","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveSpectators"}],"type":"topic","title":"liveSpectators","url":"\/documentation\/ovkit\/video\/livespectators","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"liveSpectators","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"liveSpectators"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"liveSpectators","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSpectators\/title","op":"replace","value":"liveSpectators"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSpectators\/fragments","op":"replace","value":[{"text":"liveSpectators","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}