{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"text":"Идентификатор видео в ЕВ.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/video\/ovid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/video\/ovid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"ovId","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)ovId","title":"ovId","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/ovId":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","abstract":[{"type":"text","text":"Идентификатор видео в ЕВ."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"ovId","kind":"identifier"}],"title":"ovId","url":"\/documentation\/ovkit\/video\/ovid","kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"url":"\/documentation\/ovkit\/video","title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","role":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/videotype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ovId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ovId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ovId"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/title","value":"ovId","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/fragments","value":[{"kind":"identifier","text":"ovId"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}]}]}