{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)prefetchQualityRangeWiFi","modules":[{"name":"OVKit"}],"title":"prefetchQualityRangeWiFi","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeWiFi","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/prefetchqualityrangewifi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/prefetchqualityrangewifi"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"title":"QualityRange","navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"type":"topic","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"url":"\/documentation\/ovkit\/qualityrange","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","role":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchQualityRangeWiFi":{"navigatorTitle":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}],"url":"\/documentation\/ovkit\/video\/prefetchqualityrangewifi","abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"type":"topic","title":"prefetchQualityRangeWiFi","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeWiFi","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","title":"Video","type":"topic","abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"prefetchQualityRangeWiFi","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKQualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeWiFi\/title","value":"prefetchQualityRangeWiFi","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeWiFi\/fragments","value":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}