{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"repeated","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"repeated"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)repeated","symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/repeated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/repeated"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"Влияет на автоматический перезапуск после окончания воспроизведения. Более точная настройка поведения также доступна через свойство ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/loopBehavior","isActive":true,"type":"reference"},{"text":" плеера.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"type":"text","text":"Зациклено ли воспроизведение видеозаписи."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/loopBehavior":{"title":"loopBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"LoopBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/loopBehavior","navigatorTitle":[{"kind":"identifier","text":"loopBehavior"}],"kind":"symbol","type":"topic","abstract":[{"text":"Задает поведение плеера при завершении видео.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/playerview\/loopbehavior"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","title":"VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/repeated":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/ovkit\/video\/repeated","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","title":"repeated","abstract":[{"text":"Зациклено ли воспроизведение видеозаписи.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"repeated"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"role":"symbol","url":"\/documentation\/ovkit\/video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"repeated","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"repeated"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"loopBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1loopBehavior\/title","op":"replace"},{"value":[{"text":"loopBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1loopBehavior\/fragments","op":"replace"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"},{"value":"repeated","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/title","op":"replace"},{"value":[{"kind":"identifier","text":"repeated"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/fragments","op":"replace"},{"value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace"}]}]}