{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"type":"text","text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double."}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"replayGain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"role":"symbol","title":"replayGain","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)replayGain","navigatorTitle":[{"text":"replayGain","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"replayGain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/replaygain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/replaygain"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/replayGain"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"kind":"identifier","text":"Video"}],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","title":"Video","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video/replayGain":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replayGain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double.","type":"text"}],"title":"replayGain","url":"\/documentation\/ovkit\/video\/replaygain","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/replayGain","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"replayGain"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"replayGain"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"replayGain","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"replayGain"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1replayGain\/title","op":"replace","value":"replayGain"},{"op":"replace","value":[{"text":"replayGain","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1replayGain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}