{"variants":[{"paths":["\/documentation\/ovkit\/video\/timelinethumbs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/video\/timelinethumbs"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"TimelineThumbnailsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/timelineThumbs","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimelineThumbnailsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)timelineThumbs","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"timelineThumbs","navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}]},"abstract":[{"type":"text","text":"Кадры из видео, отображаемые на таймлайне при перемотке."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","title":"VideoType","type":"topic","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineThumbnailsType"}],"url":"\/documentation\/ovkit\/timelinethumbnailstype","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","abstract":[{"type":"text","text":"Набор картинок, которые показываются на таймлайне при перемотке."}],"title":"TimelineThumbnailsType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"url":"\/documentation\/ovkit\/video","type":"topic","title":"Video","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video/timelineThumbs":{"role":"symbol","abstract":[{"type":"text","text":"Кадры из видео, отображаемые на таймлайне при перемотке."}],"kind":"symbol","title":"timelineThumbs","navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimelineThumbnailsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/video\/timelinethumbs","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/timelineThumbs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timelineThumbs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"timelineThumbs","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKTimelineThumbnailsType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKTimelineThumbnailsType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","value":"OVKTimelineThumbnailsType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/navigatorTitle","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1timelineThumbs\/title","value":"timelineThumbs"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1timelineThumbs\/fragments","value":[{"text":"timelineThumbs","kind":"identifier"}]}]}]}