{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/title"},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)title","title":"title","navigatorTitle":[{"kind":"identifier","text":"title"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/title"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/title"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoType.title"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/title":{"title":"title","navigatorTitle":[{"text":"title","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/video\/title","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/title"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"type":"topic","role":"symbol","kind":"symbol","title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"url":"\/documentation\/ovkit\/video"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"title","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"title"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"title","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1title\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}