{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoAds","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"videoAds","kind":"identifier"}],"symbolKind":"property","title":"videoAds","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)videoAds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoAds","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoAdsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"VideoType.videoAds"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/videoads"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/videoads"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoAds"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier","text":"VideoAdsType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/videoAds":{"url":"\/documentation\/ovkit\/video\/videoads","type":"topic","title":"videoAds","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoAds"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoAds","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","text":"VideoAdsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/video","abstract":[],"type":"topic","title":"Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videoadstype","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoAdsType","kind":"identifier"}],"title":"VideoAdsType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"videoAds"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoAds"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<OVKVideoAdsType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoAdsType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAds"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"videoAds","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoAds\/title"},{"value":[{"text":"videoAds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoAds\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title","value":"OVKVideoAdsType","op":"replace"},{"value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","op":"replace"}]}]}