{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoUrlQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"videoUrlQuery","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)videoUrlQuery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoUrlQuery"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoUrlQuery"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","kind":"typeIdentifier","text":"VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoUrlQuery"},"abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/video\/videourlquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/video\/videourlquery"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/videoUrlQuery":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","text":"VideoURLQuery","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"videoUrlQuery","type":"topic","kind":"symbol","abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoUrlQuery","url":"\/documentation\/ovkit\/video\/videourlquery","role":"symbol","navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"title":"VideoURLQuery","abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videourlquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoURLQuery","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","url":"\/documentation\/ovkit\/videotype","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"videoUrlQuery","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","text":"OVKVideoURLQuery"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoUrlQuery"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"videoUrlQuery","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoUrlQuery\/title"},{"value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoUrlQuery\/fragments"},{"value":"OVKVideoURLQuery","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title"},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/navigatorTitle"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"}]}]}