{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoType.videoCategory"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoCategory"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","kind":"typeIdentifier","text":"VideoCategory","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]]},"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"videoCategory","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideo(py)videoCategory","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","text":"VideoCategory","kind":"typeIdentifier"}],"title":"videoCategory","modules":[{"name":"OVKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/video\/videocategory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/video\/videocategory"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoCategory","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","url":"\/documentation\/ovkit\/video","title":"Video","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"abstract":[],"url":"\/documentation\/ovkit\/videocategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoCategory"}],"navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"type":"topic","title":"VideoCategory","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video/videoCategory":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoCategory","navigatorTitle":[{"text":"videoCategory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/video\/videocategory","role":"symbol","title":"videoCategory","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoCategory","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","kind":"typeIdentifier","text":"VideoCategory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"videoCategory"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"videoCategory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","text":"OVKVideoCategory","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCategory"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"},{"op":"replace","value":"OVKVideoCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategory"}],"op":"replace"},{"value":[{"text":"OVKVideoCategory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoCategory\/title","value":"videoCategory","op":"replace"},{"value":[{"kind":"identifier","text":"videoCategory"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoCategory\/fragments"}]}]}