{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/audioTrackSelection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"MenuKind.audioTrackSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrackSelection"}],"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindAudioTrackSelection","navigatorTitle":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"abstract":[{"text":"Меню выбора аудиодорожки.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrackSelection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/audiotrackselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind\/audiotrackselection"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"abstract":[{"type":"text","text":"Вид меню."}],"type":"topic","title":"MenuKind","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","kind":"symbol","url":"\/documentation\/ovkit\/menukind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"navigatorTitle":[{"text":"MenuKind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/audioTrackSelection":{"navigatorTitle":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"title":"MenuKind.audioTrackSelection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/audioTrackSelection","role":"symbol","url":"\/documentation\/ovkit\/menukind\/audiotrackselection","abstract":[{"type":"text","text":"Меню выбора аудиодорожки."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrackSelection","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKMenuKindAudioTrackSelection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuKindAudioTrackSelection"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title"},{"op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenuKind"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle"},{"op":"replace","value":"OVKMenuKindAudioTrackSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1audioTrackSelection\/title"},{"op":"replace","value":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1audioTrackSelection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}