{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindDataSavingOptions","symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","title":"MenuKind.dataSavingOptions","navigatorTitle":[{"text":"OVKMenuKindDataSavingOptions","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSavingOptions","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Меню опций включения режима экономии трафика."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/dataSavingOptions"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSavingOptions","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/datasavingoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind\/datasavingoptions"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"type":"topic","url":"\/documentation\/ovkit\/menukind","kind":"symbol","abstract":[{"type":"text","text":"Вид меню."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"title":"MenuKind"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/dataSavingOptions":{"role":"symbol","url":"\/documentation\/ovkit\/menukind\/datasavingoptions","kind":"symbol","title":"MenuKind.dataSavingOptions","abstract":[{"type":"text","text":"Меню опций включения режима экономии трафика."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/dataSavingOptions","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSavingOptions"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindDataSavingOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKMenuKindDataSavingOptions","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKMenuKindDataSavingOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKMenuKindDataSavingOptions"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKMenuKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title"},{"value":[{"kind":"identifier","text":"OVKMenuKind"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1dataSavingOptions\/title","op":"replace","value":"OVKMenuKindDataSavingOptions"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1dataSavingOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindDataSavingOptions"}]}]}]}