{"variants":[{"paths":["\/documentation\/ovkit\/menukind\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"title":"init(rawValue:)","role":"symbol","externalID":"s:5OVKit8MenuKindO8rawValueACSgSi_tcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"kind":"symbol","title":"MenuKind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"abstract":[{"text":"Вид меню.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/menukind"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/init(rawValue:)":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/init(rawValue:)","url":"\/documentation\/ovkit\/menukind\/init(rawvalue:)"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title"},{"op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments"},{"op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}