{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/other"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindOther","modules":[{"name":"OVKit"}],"title":"MenuKind.other","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindOther"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/menukind\/other"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menukind\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Меню выбора устройства для внешнего проигрывания.","type":"text"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"kind":"symbol","title":"MenuKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"url":"\/documentation\/ovkit\/menukind","role":"symbol","abstract":[{"text":"Вид меню.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/other":{"title":"MenuKind.other","url":"\/documentation\/ovkit\/menukind\/other","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/other","abstract":[{"type":"text","text":"Меню выбора устройства для внешнего проигрывания."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindOther"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuKindOther"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindOther"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuKindOther"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","value":"OVKMenuKind"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","value":[{"text":"OVKMenuKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuKind"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1other\/title","value":"OVKMenuKindOther"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1other\/fragments","value":[{"kind":"identifier","text":"OVKMenuKindOther"}]}]}]}