{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackSettings"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/playbacksettings"]},{"paths":["\/documentation\/ovkit\/menukind\/playbacksettings"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackSettings","kind":"identifier"}]}]}],"kind":"symbol","abstract":[{"text":"Главное меню, где собраны основные настройки воспроизведения.","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindPlaybackSettings"}],"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindPlaybackSettings","symbolKind":"case","title":"MenuKind.playbackSettings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSettings"}],"modules":[{"name":"OVKit"}]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"type":"topic","role":"symbol","title":"MenuKind","kind":"symbol","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"url":"\/documentation\/ovkit\/menukind","abstract":[{"text":"Вид меню.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MenuKind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/playbackSettings":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackSettings","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSettings"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/menukind\/playbacksettings","role":"symbol","navigatorTitle":[{"text":"OVKMenuKindPlaybackSettings","kind":"identifier"}],"abstract":[{"text":"Главное меню, где собраны основные настройки воспроизведения.","type":"text"}],"title":"MenuKind.playbackSettings"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKMenuKindPlaybackSettings","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKMenuKindPlaybackSettings","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKMenuKindPlaybackSettings","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackSettings\/title","value":"OVKMenuKindPlaybackSettings","op":"replace"},{"value":[{"text":"OVKMenuKindPlaybackSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackSettings\/fragments"}]}]}