{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackRateSelection","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Меню выбора скорости воспроизведения.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/menukind\/playbackrateselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menukind\/playbackrateselection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRateSelection"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindPlaybackRateSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRateSelection"}],"title":"MenuKind.playbackRateSelection","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindPlaybackRateSelection"}],"roleHeading":"Case","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind/playbackRateSelection":{"role":"symbol","url":"\/documentation\/ovkit\/menukind\/playbackrateselection","kind":"symbol","title":"MenuKind.playbackRateSelection","abstract":[{"type":"text","text":"Меню выбора скорости воспроизведения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackRateSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindPlaybackRateSelection"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"type":"topic","url":"\/documentation\/ovkit\/menukind","kind":"symbol","abstract":[{"type":"text","text":"Вид меню."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"title":"MenuKind"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuKindPlaybackRateSelection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKMenuKindPlaybackRateSelection","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKMenuKindPlaybackRateSelection","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackRateSelection\/title","op":"replace","value":"OVKMenuKindPlaybackRateSelection"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackRateSelection\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindPlaybackRateSelection"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace","value":"OVKMenuKind"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","op":"replace","value":[{"text":"OVKMenuKind","kind":"identifier"}]}]}]}