{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityPresetSelection"}],"roleHeading":"Case","title":"MenuKind.qualityPresetSelection","externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindQualityPresetSelection","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindQualityPresetSelection"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"variants":[{"paths":["\/documentation\/ovkit\/menukind\/qualitypresetselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menukind\/qualitypresetselection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"qualityPresetSelection","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/qualityPresetSelection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Меню выбора пресета автоматического качества воспроизведения."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind/qualityPresetSelection":{"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindQualityPresetSelection"}],"title":"MenuKind.qualityPresetSelection","kind":"symbol","role":"symbol","abstract":[{"text":"Меню выбора пресета автоматического качества воспроизведения.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/qualityPresetSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityPresetSelection"}],"url":"\/documentation\/ovkit\/menukind\/qualitypresetselection"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuKind"}],"abstract":[{"text":"Вид меню.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","url":"\/documentation\/ovkit\/menukind","title":"MenuKind","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MenuKind"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuKindQualityPresetSelection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindQualityPresetSelection"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuKindQualityPresetSelection"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1qualityPresetSelection\/title","op":"replace","value":"OVKMenuKindQualityPresetSelection"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1qualityPresetSelection\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindQualityPresetSelection"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace","value":"OVKMenuKind"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKind"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKMenuKind"}]}]}]}