{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"OVKit"}],"role":"collectionGroup"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"sections":[],"kind":"article","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/rawrepresentable-implementations"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/hashValue":{"url":"\/documentation\/ovkit\/menukind\/hashvalue","title":"hashValue","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/hashValue","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/hash(into:)":{"role":"symbol","type":"topic","abstract":[],"title":"hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"url":"\/documentation\/ovkit\/menukind\/hash(into:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"abstract":[{"type":"text","text":"Вид меню."}],"url":"\/documentation\/ovkit\/menukind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","title":"MenuKind","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenuKind"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenuKind"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle"}]}]}