{"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindScreencastDeviceSelection","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screencastDeviceSelection"}],"modules":[{"name":"OVKit"}],"roleHeading":"Case","title":"MenuKind.screencastDeviceSelection"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screencastDeviceSelection"}]}]}],"abstract":[{"text":"Меню выбора устройства для внешнего проигрывания.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/screencastDeviceSelection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/screencastdeviceselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind\/screencastdeviceselection"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/screencastDeviceSelection":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}],"url":"\/documentation\/ovkit\/menukind\/screencastdeviceselection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screencastDeviceSelection"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/screencastDeviceSelection","title":"MenuKind.screencastDeviceSelection","role":"symbol","abstract":[{"text":"Меню выбора устройства для внешнего проигрывания.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"type":"topic","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"title":"MenuKind","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MenuKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","role":"symbol","url":"\/documentation\/ovkit\/menukind","abstract":[{"type":"text","text":"Вид меню."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKMenuKindScreencastDeviceSelection"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1screencastDeviceSelection\/title","value":"OVKMenuKindScreencastDeviceSelection"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1screencastDeviceSelection\/fragments","value":[{"text":"OVKMenuKindScreencastDeviceSelection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","value":"OVKMenuKind"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","value":[{"text":"OVKMenuKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","value":[{"text":"OVKMenuKind","kind":"identifier"}]}]}]}