{"metadata":{"navigatorTitle":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"specificQualitySelection","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindSpecificQualitySelection","title":"MenuKind.specificQualitySelection","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"specificQualitySelection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind\/specificqualityselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind\/specificqualityselection"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/specificQualitySelection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Меню выбора качества из конкретного набора значений.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind/specificQualitySelection":{"url":"\/documentation\/ovkit\/menukind\/specificqualityselection","navigatorTitle":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/specificQualitySelection","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"specificQualitySelection","kind":"identifier"}],"type":"topic","title":"MenuKind.specificQualitySelection","abstract":[{"text":"Меню выбора качества из конкретного набора значений.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","abstract":[{"text":"Вид меню.","type":"text"}],"title":"MenuKind","url":"\/documentation\/ovkit\/menukind","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKMenuKindSpecificQualitySelection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuKindSpecificQualitySelection"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1specificQualitySelection\/title","value":"OVKMenuKindSpecificQualitySelection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1specificQualitySelection\/fragments","value":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}],"op":"replace"},{"value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","op":"replace"}]}]}