{"abstract":[{"text":"Меню выбора дорожки субтитров.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitlesSelection"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/subtitlesSelection"},"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"MenuKind.subtitlesSelection","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"subtitlesSelection","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKMenuKind@OVKMenuKindSubtitlesSelection","navigatorTitle":[{"text":"OVKMenuKindSubtitlesSelection","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/menukind\/subtitlesselection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind\/subtitlesselection"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind/subtitlesSelection":{"abstract":[{"type":"text","text":"Меню выбора дорожки субтитров."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitlesSelection","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/subtitlesSelection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindSubtitlesSelection"}],"type":"topic","url":"\/documentation\/ovkit\/menukind\/subtitlesselection","title":"MenuKind.subtitlesSelection","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","role":"symbol","type":"topic","kind":"symbol","title":"MenuKind","url":"\/documentation\/ovkit\/menukind","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuKind"}],"abstract":[{"type":"text","text":"Вид меню."}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"OVKMenuKindSubtitlesSelection","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKMenuKindSubtitlesSelection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuKindSubtitlesSelection"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1subtitlesSelection\/title","value":"OVKMenuKindSubtitlesSelection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1subtitlesSelection\/fragments","op":"replace","value":[{"text":"OVKMenuKindSubtitlesSelection","kind":"identifier"}]},{"value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","value":[{"kind":"identifier","text":"OVKMenuKind"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuKind"}],"op":"replace"}]}]}