{"abstract":[{"text":"Причина, по которой загрузка приостановлена в данное время.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/downloadSuspendReason"},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(py)downloadSuspendReason","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"downloadSuspendReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason","text":"DownloadSuspendReason"}],"title":"downloadSuspendReason","navigatorTitle":[{"text":"downloadSuspendReason","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"downloadSuspendReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason","text":"DownloadSuspendReason"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Если загрузка разрешена, значением является ","type":"text"},{"type":"codeVoice","code":"none"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/downloadsuspendreason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/downloadsuspendreason"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadSuspendReason","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadsuspendreason","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"kind":"symbol","title":"DownloadSuspendReason","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistenceManager/downloadSuspendReason":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"downloadSuspendReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DownloadSuspendReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason"}],"abstract":[{"text":"Причина, по которой загрузка приостановлена в данное время.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/downloadSuspendReason","type":"topic","kind":"symbol","navigatorTitle":[{"text":"downloadSuspendReason","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkpersistencemanager\/downloadsuspendreason","title":"downloadSuspendReason","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","type":"topic","title":"PersistenceManager","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManager"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"downloadSuspendReason","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"downloadSuspendReason","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason","text":"OVKDownloadSuspendReason","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"downloadSuspendReason","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","op":"replace","value":"OVKDownloadSuspendReason"},{"value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1downloadSuspendReason\/title","value":"downloadSuspendReason","op":"replace"},{"value":[{"text":"downloadSuspendReason","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1downloadSuspendReason\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}