{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isManuallySuspended","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/ismanuallysuspended"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/ismanuallysuspended"]}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isManuallySuspended"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isManuallySuspended","kind":"identifier"}],"title":"isManuallySuspended","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(py)isManuallySuspended"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"abstract":[{"type":"text","text":"Позволяет вручную приостановить и возобновить процесс загрузки видео."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/isManuallySuspended","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","type":"topic","title":"PersistenceManager","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManager"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistenceManager/isManuallySuspended":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isManuallySuspended","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Позволяет вручную приостановить и возобновить процесс загрузки видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/isManuallySuspended","type":"topic","kind":"symbol","navigatorTitle":[{"text":"isManuallySuspended","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkpersistencemanager\/ismanuallysuspended","title":"isManuallySuspended","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isManuallySuspended"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isManuallySuspended","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isManuallySuspended","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1isManuallySuspended\/title","value":"isManuallySuspended"},{"op":"replace","value":[{"text":"isManuallySuspended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1isManuallySuspended\/fragments"}]}]}