{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/items"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpersistencemanager\/items"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/items"},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"items","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":"]"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(py)items","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","title":"items"},"abstract":[{"type":"text","text":"Список моделей, которые в настоящее время загружаются, либо уже загружены."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Доступ к этому свойству может занять продолжительное время!","type":"text"}]}],"name":"Warning"}]}],"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistenceManager/items":{"abstract":[{"type":"text","text":"Список моделей, которые в настоящее время загружаются, либо уже загружены."}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkpersistencemanager\/items","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistenceManager\/items","navigatorTitle":[{"text":"items","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":"]","kind":"text"}],"role":"symbol","title":"items"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PersistentItem","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"items","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"items"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSArray<OVKPersistentItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"items","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"items","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1items\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistenceManager~1items\/fragments","op":"replace","value":[{"text":"items","kind":"identifier"}]},{"value":"OVKPersistentItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"value":"OVKPersistenceManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"}]}]}