{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"text":"?","kind":"text"}],"externalID":"s:5OVKit27SeekPreviewBehaviorExtendedC12controlsViewAA014PlayerControlsG8Protocol_pSgvp","title":"controlsView","symbolKind":"property"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/controlsView","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"text":"?","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"style":"warning","name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Свойство должно быть weak!","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended\/controlsview"]}],"abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/controlsView":{"abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/controlsView","type":"topic","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/controlsview","title":"controlsView"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","kind":"symbol","title":"SeekPreviewBehaviorExtended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol","title":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SeekPreviewBehaviorExtended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments","op":"replace"},{"value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}