{"metadata":{"externalID":"s:5OVKit27SeekPreviewBehaviorExtendedC16continueTracking5touchySo7UITouchC_tF","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"continueTracking(touch:)","symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TimelineUIControlDelegate.continueTracking(touch:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/continueTracking(touch:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended\/continuetracking(touch:)"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","kind":"symbol","title":"SeekPreviewBehaviorExtended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/continueTracking(touch:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"title":"continueTracking(touch:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/continueTracking(touch:)","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/continuetracking(touch:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"touch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SeekPreviewBehaviorExtended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments"},{"op":"replace","value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle"}]}]}