{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:5OVKit27SeekPreviewBehaviorExtendedC12timelineView010previewAndE15TimelineAllowed11layoutSetup011onNeedStartbC00nobC6ToTime0no3EndbC0AcA0jG0C_SbycySo6UIViewCcyycySdcySdSg_Sbtctcfc","roleHeading":"Initializer","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewAndExtendedTimelineAllowed","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layoutSetup","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedStartSeekPreview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedSeekPreviewToTime","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedEndSeekPreview","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"]]},"abstract":[{"text":"Создание поведения.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewAndExtendedTimelineAllowed","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layoutSetup"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedStartSeekPreview"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedSeekPreviewToTime"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedEndSeekPreview"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"timelineView","content":[{"type":"paragraph","inlineContent":[{"text":"Вью таймлайна, который будет использоваться для слежения за состоянием перемотки.","type":"text"}]}]},{"name":"previewAndExtendedTimelineAllowed","content":[{"type":"paragraph","inlineContent":[{"text":"Блок, который получает флаг, указывающий, нужно ли начинать показывать превью поиска и давать возможность вытянуть точную перемотку. Если передать ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", то поведение будет показывать только текущее время и названия глав.","type":"text"}]}]},{"name":"layoutSetup","content":[{"inlineContent":[{"type":"text","text":"Блок настройки лейаута. В момент вызова блок должен разместить UIView поведения. Допускается как autolayout, так и фреймы."}],"type":"paragraph"}]},{"name":"onNeedStartSeekPreview","content":[{"type":"paragraph","inlineContent":[{"text":"Блок, который вызывается при необходимости приостановить воспроизведение для режима точного поиска.","type":"text"}]}]},{"name":"onNeedSeekPreviewToTime","content":[{"inlineContent":[{"text":"Блок, который вызывается при необходимости выполнить предварительный (без старта воспроизведения) seek до времени, на которое сейчас перемотал пользователь.","type":"text"}],"type":"paragraph"}]},{"name":"onNeedEndSeekPreview","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который вызывается при необходимости выйти из режима точного поиска. Не вызовется, если поведение не переходило в режим точного поиска."}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended\/init(timelineview:previewandextendedtimelineallowed:layoutsetup:onneedstartseekpreview:onneedseekpreviewtotime:onneedendseekpreview:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"title":"TimelineView","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)":{"abstract":[{"type":"text","text":"Создание поведения."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewAndExtendedTimelineAllowed","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layoutSetup","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedStartSeekPreview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedSeekPreviewToTime","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onNeedEndSeekPreview","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)","type":"topic","role":"symbol","title":"init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/init(timelineview:previewandextendedtimelineallowed:layoutsetup:onneedstartseekpreview:onneedseekpreviewtotime:onneedendseekpreview:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoidBlock","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","url":"\/documentation\/ovkit\/voidblock","title":"VoidBlock","type":"topic","role":"symbol","navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","kind":"symbol","title":"SeekPreviewBehaviorExtended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","op":"replace"},{"value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TimelineView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","op":"replace"},{"value":"SeekPreviewBehaviorExtended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title","op":"replace"},{"value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments","op":"replace"},{"value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle","op":"replace"}]}]}