{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowingPrecisionSeek"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:5OVKit27SeekPreviewBehaviorExtendedC018isShowingPrecisionB0Sbvp","role":"symbol","title":"isShowingPrecisionSeek"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isShowingPrecisionSeek"},"kind":"symbol","abstract":[{"text":"Показывается ли в данный момент точная перемотка.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended\/isshowingprecisionseek"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isShowingPrecisionSeek","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"title":"SeekPreviewBehaviorExtended","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/isShowingPrecisionSeek":{"type":"topic","title":"isShowingPrecisionSeek","abstract":[{"text":"Показывается ли в данный момент точная перемотка.","type":"text"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/isshowingprecisionseek","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isShowingPrecisionSeek","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowingPrecisionSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SeekPreviewBehaviorExtended","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title"},{"value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments"},{"value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle"}]}]}