{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeBehaviour","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:5OVKit27SeekPreviewBehaviorExtendedC15removeBehaviouryyF","title":"removeBehaviour()"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/removeBehaviour()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Убрать поведение с контролов (без отключения самого поведения)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended\/removebehaviour()"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeBehaviour"},{"kind":"text","text":"()"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"role":"symbol","title":"SeekPreviewBehaviorExtended"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/removeBehaviour()":{"kind":"symbol","title":"removeBehaviour()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeBehaviour","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/removebehaviour()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/removeBehaviour()","abstract":[{"text":"Убрать поведение с контролов (без отключения самого поведения).","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SeekPreviewBehaviorExtended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}