{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/enableKeyboardObserver","interfaceLanguage":"swift"},"metadata":{"title":"enableKeyboardObserver","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableKeyboardObserver"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","navigatorTitle":[{"text":"enableKeyboardObserver","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)enableKeyboardObserver","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Включение\/выключение механизма слежения за клавиатурой."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableKeyboardObserver"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Если включить, контролы полноэкранного плеера начнут получать событие "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)","isActive":true},{"type":"text","text":" при изменении состояния клавиатуры на экране. По умолчанию выключено."}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/enablekeyboardobserver"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/enablekeyboardobserver"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/enableKeyboardObserver":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableKeyboardObserver","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/enablekeyboardobserver","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/enableKeyboardObserver","abstract":[{"type":"text","text":"Включение\/выключение механизма слежения за клавиатурой."}],"role":"symbol","type":"topic","title":"enableKeyboardObserver","navigatorTitle":[{"text":"enableKeyboardObserver","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/keyboardOverlapHeightChanged(to:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardOverlapHeightChanged"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/keyboardoverlapheightchanged(to:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)","abstract":[{"type":"text","text":"Изменилась высота клавиатуры над полноэкранным контроллером."}],"role":"symbol","type":"topic","title":"keyboardOverlapHeightChanged(to:)","required":true,"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"enableKeyboardObserver","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"enableKeyboardObserver","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableKeyboardObserver"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController"},{"value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1enableKeyboardObserver\/title","value":"enableKeyboardObserver","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"enableKeyboardObserver"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1enableKeyboardObserver\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}