{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/hideKeyboardGestureRecognizer","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideKeyboardGestureRecognizer"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Жест для скрытия клавиатуры."}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/hidekeyboardgesturerecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/hidekeyboardgesturerecognizer"]}],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"hideKeyboardGestureRecognizer"}],"role":"symbol","roleHeading":"Instance Property","title":"hideKeyboardGestureRecognizer","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideKeyboardGestureRecognizer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier","text":"UITapGestureRecognizer"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)hideKeyboardGestureRecognizer"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/hideKeyboardGestureRecognizer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/hideKeyboardGestureRecognizer","navigatorTitle":[{"kind":"identifier","text":"hideKeyboardGestureRecognizer"}],"role":"symbol","type":"topic","title":"hideKeyboardGestureRecognizer","abstract":[{"type":"text","text":"Жест для скрытия клавиатуры."}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/hidekeyboardgesturerecognizer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideKeyboardGestureRecognizer"},{"kind":"text","text":": "},{"text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hideKeyboardGestureRecognizer","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hideKeyboardGestureRecognizer"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hideKeyboardGestureRecognizer"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1hideKeyboardGestureRecognizer\/title","op":"replace","value":"hideKeyboardGestureRecognizer"},{"op":"replace","value":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1hideKeyboardGestureRecognizer\/fragments"}]}]}