{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredstatusbarstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredstatusbarstyle"]}],"kind":"symbol","metadata":{"title":"preferredStatusBarStyle","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredStatusBarStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)preferredStatusBarStyle","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/preferredStatusBarStyle","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/preferredStatusBarStyle":{"title":"preferredStatusBarStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredstatusbarstyle","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/preferredStatusBarStyle","abstract":[],"navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"preferredStatusBarStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"preferredStatusBarStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1preferredStatusBarStyle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1preferredStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}