{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/prefershomeindicatorautohidden"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/prefershomeindicatorautohidden"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)prefersHomeIndicatorAutoHidden","symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol","title":"prefersHomeIndicatorAutoHidden","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/prefersHomeIndicatorAutoHidden","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/prefersHomeIndicatorAutoHidden":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"}],"url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/prefershomeindicatorautohidden","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/prefersHomeIndicatorAutoHidden","role":"symbol","title":"prefersHomeIndicatorAutoHidden","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"prefersHomeIndicatorAutoHidden","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefersHomeIndicatorAutoHidden"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1prefersHomeIndicatorAutoHidden\/title","value":"prefersHomeIndicatorAutoHidden"},{"value":[{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1prefersHomeIndicatorAutoHidden\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}