{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredinterfaceorientationforpresentation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredinterfaceorientationforpresentation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)preferredInterfaceOrientationForPresentation","title":"preferredInterfaceOrientationForPresentation","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"}],"navigatorTitle":[{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientation","kind":"typeIdentifier","text":"UIInterfaceOrientation"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/preferredInterfaceOrientationForPresentation","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/preferredInterfaceOrientationForPresentation":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/preferredInterfaceOrientationForPresentation","role":"symbol","title":"preferredInterfaceOrientationForPresentation","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredInterfaceOrientationForPresentation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation"}],"type":"topic","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/preferredinterfaceorientationforpresentation","navigatorTitle":[{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"preferredInterfaceOrientationForPresentation"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"preferredInterfaceOrientationForPresentation"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"text":" ","kind":"text"},{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"preferredInterfaceOrientationForPresentation","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1preferredInterfaceOrientationForPresentation\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1preferredInterfaceOrientationForPresentation\/fragments","value":[{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"}]},{"op":"replace","value":"OVKFullscreenContentViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}