{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/supplementaryviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/supplementaryviewcontroller"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementaryViewController","kind":"identifier"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"supplementaryViewController","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)supplementaryViewController","title":"supplementaryViewController","symbolKind":"property"},"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"supplementaryViewController","kind":"identifier"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" & ","kind":"text"},{"text":"FullscreenSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","kind":"symbol","title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/supplementaryViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/supplementaryviewcontroller","navigatorTitle":[{"kind":"identifier","text":"supplementaryViewController"}],"kind":"symbol","title":"supplementaryViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supplementaryViewController","kind":"identifier"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"supplementaryViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"supplementaryViewController"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"UIViewController<OVKFullscreenSupplementaryController>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"supplementaryViewController","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"op":"replace","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"op":"replace","value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/title","value":"supplementaryViewController","op":"replace"},{"value":[{"text":"supplementaryViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}