{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/swipeDownBehavior"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)swipeDownBehavior","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeDownBehavior"},{"text":": ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"}],"title":"swipeDownBehavior","navigatorTitle":[{"kind":"identifier","text":"swipeDownBehavior"}]},"abstract":[{"type":"text","text":"Поведение при свайпе вниз в полноэкранном режиме."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/swipedownbehavior"]},{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/swipedownbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeDownBehavior"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior","text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Применяется только когда жест свайпа доступен в текущей конфигурации UI.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/swipeDownBehavior":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeDownBehavior"},{"text":": ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/swipeDownBehavior","navigatorTitle":[{"kind":"identifier","text":"swipeDownBehavior"}],"abstract":[{"text":"Поведение при свайпе вниз в полноэкранном режиме.","type":"text"}],"title":"swipeDownBehavior","type":"topic","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/swipedownbehavior"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"abstract":[{"text":"Поведение при свайпе в полноэкранном режиме.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","kind":"symbol","role":"symbol","type":"topic","title":"FullscreenSwipeGestureBehavior","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"swipeDownBehavior"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"swipeDownBehavior","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","text":"OVKFullscreenSwipeGestureBehavior"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeDownBehavior"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"value":"swipeDownBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1swipeDownBehavior\/title","op":"replace"},{"value":[{"text":"swipeDownBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1swipeDownBehavior\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","value":"OVKFullscreenSwipeGestureBehavior","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}