{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wasPresentedForSupplementaryController","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wasPresentedForSupplementaryController","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)wasPresentedForSupplementaryController","title":"wasPresentedForSupplementaryController","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"wasPresentedForSupplementaryController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/waspresentedforsupplementarycontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/waspresentedforsupplementarycontroller"]}],"abstract":[{"text":"Был ли контроллер презентован одновременно с добавлением ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","isActive":true},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/wasPresentedForSupplementaryController":{"abstract":[{"type":"text","text":"Был ли контроллер презентован одновременно с добавлением "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wasPresentedForSupplementaryController","navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"kind":"symbol","title":"wasPresentedForSupplementaryController","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wasPresentedForSupplementaryController"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/waspresentedforsupplementarycontroller"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/supplementaryViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/supplementaryviewcontroller","navigatorTitle":[{"kind":"identifier","text":"supplementaryViewController"}],"kind":"symbol","title":"supplementaryViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supplementaryViewController","kind":"identifier"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"wasPresentedForSupplementaryController","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"wasPresentedForSupplementaryController"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"wasPresentedForSupplementaryController","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"wasPresentedForSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wasPresentedForSupplementaryController\/title"},{"op":"replace","value":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wasPresentedForSupplementaryController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"op":"replace","value":"supplementaryViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/fragments","op":"replace","value":[{"text":"supplementaryViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}