{"abstract":[{"type":"text","text":"Контроллер, который необходимо обернуть."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/wrapped"]},{"paths":["\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/wrapped"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController(py)wrapped","title":"wrapped","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrapped","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"wrapped"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wrapped","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wrapped","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/wrapped":{"abstract":[{"text":"Контроллер, который необходимо обернуть.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/wrapped","title":"wrapped","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wrapped","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"wrapped","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"kind":"symbol","title":"FullscreenContentViewController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"wrapped"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"wrapped"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","text":"OVKFullscreenContentViewController","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"wrapped","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wrapped\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wrapped\/fragments","value":[{"text":"wrapped","kind":"identifier"}],"op":"replace"},{"value":"OVKFullscreenContentViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","op":"replace"},{"value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}