{"variants":[{"paths":["\/documentation\/ovkit\/label\/attributes(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"attributes(for:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:5OVKit5LabelC10attributes3forSDySo21NSAttributedStringKeyaypGSgSSSg_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> [","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Key","preciseIdentifier":"c:@T@NSAttributedStringKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> [","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":".","kind":"text"},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/attributes(for:)","interfaceLanguage":"swift"},"abstract":[{"text":"Шаблонный метод, конструирующий атрибуты для строки ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Label/text":{"role":"symbol","title":"text","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/label\/text","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Label/attributes(for:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/attributes(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"text":".","kind":"text"},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"attributes(for:)","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/label\/attributes(for:)","abstract":[{"text":"Шаблонный метод, конструирующий атрибуты для строки ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"kind":"symbol","navigatorTitle":[{"text":"Label","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","abstract":[{"type":"text","text":"Текстовый визуальный компонент на основе "},{"code":"UIKit\/UILabel","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"url":"\/documentation\/ovkit\/label","type":"topic","title":"Label","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1text\/title","op":"replace","value":"text"},{"value":[{"text":"text","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1text\/fragments"},{"value":"OVKLabel","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments","op":"replace","value":[{"text":"OVKLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKLabel"}]}]}]}