{"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"drawText(in:)","navigatorTitle":[{"text":"drawTextInRect:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)Label(im)drawTextInRect:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"drawText"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/drawText(in:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/label\/drawtext(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/label\/drawtext(in:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Label/drawText(in:)":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/drawText(in:)","navigatorTitle":[{"text":"drawTextInRect:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"drawText"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/label\/drawtext(in:)","kind":"symbol","title":"drawText(in:)"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"title":"Label","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"navigatorTitle":[{"text":"Label","kind":"identifier"}],"url":"\/documentation\/ovkit\/label","kind":"symbol","role":"symbol","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"type":"codeVoice","code":"UIKit\/UILabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"drawTextInRect:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"drawTextInRect:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawTextInRect:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rect"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"drawTextInRect:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1drawText(in:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawTextInRect:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1drawText(in:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Label"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle"}]}]}