{"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)Label(im)initWithFrame:","title":"initWithFrame:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/ovkit\/label\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithFrame:"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Label":{"title":"Label","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"navigatorTitle":[{"text":"Label","kind":"identifier"}],"url":"\/documentation\/ovkit\/label","kind":"symbol","role":"symbol","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"type":"codeVoice","code":"UIKit\/UILabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Label/initWithFrame:":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/label\/initwithframe:","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"title":"initWithFrame:","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithFrame:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Label","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title"},{"op":"replace","value":[{"text":"Label","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"value":[{"text":"Label","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","op":"replace"}]}]}