{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)Label(im)initWithCoder:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"title":"initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithCoder:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/ovkit\/label\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/Label":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","title":"Label","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/label","abstract":[{"type":"text","text":"Текстовый визуальный компонент на основе "},{"code":"UIKit\/UILabel","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"}],"navigatorTitle":[{"kind":"identifier","text":"Label"}]},"doc://onevideo.OVKit/documentation/OVKit/Label/initWithCoder:":{"abstract":[],"title":"initWithCoder:","role":"symbol","url":"\/documentation\/ovkit\/label\/initwithcoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithCoder:"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"Label"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments","value":[{"text":"Label","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","value":[{"kind":"identifier","text":"Label"}]}]}]}