{"metadata":{"externalID":"c:@M@OVKit@objc(cs)Label(im)sizeThatFits:","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"sizeThatFits:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sizeThatFits","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"symbolKind":"method","title":"sizeThatFits(_:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/sizeThatFits(_:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sizeThatFits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/label\/sizethatfits(_:)"]},{"paths":["\/documentation\/ovkit\/label\/sizethatfits(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"code":"UIKit\/UILabel","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"Label"}],"kind":"symbol","title":"Label","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/label"},"doc://onevideo.OVKit/documentation/OVKit/Label/sizeThatFits(_:)":{"title":"sizeThatFits(_:)","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/label\/sizethatfits(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/sizeThatFits(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"sizeThatFits:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"sizeThatFits:"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","op":"replace","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1sizeThatFits(_:)\/title","value":"sizeThatFits:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeThatFits:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1sizeThatFits(_:)\/fragments"}]}]}