{"abstract":[{"text":"Пользователь досмотрел до определенных участков.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"StatsProgress","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress"},{"text":", ","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"progress","content":[{"inlineContent":[{"type":"text","text":"Участки 3s, 10s, 25p, 50p, 75p, 100p."}],"type":"paragraph"}]},{"name":"bannerInfo","content":[{"inlineContent":[{"type":"text","text":"Информация о рекламном баннере"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerProgress(_:bannerInfo:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/adbannerprogress(_:bannerinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/adbannerprogress(_:bannerinfo:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)adBannerProgress:bannerInfo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBannerProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"StatsProgress","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":")"}],"symbolKind":"method","title":"adBannerProgress(_:bannerInfo:)","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"title":"StatsProgress","url":"\/documentation\/ovkit\/statsprogress","navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsProgress"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"url":"\/documentation\/ovkit\/statshandlerconsole","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":" для отладки, который будет писать события статистики в консоль.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol","title":"StatsHandlerConsole","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"title":"AdStatsBannerInfo","url":"\/documentation\/ovkit\/adstatsbannerinfo","navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adBannerProgress(_:bannerInfo:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBannerProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","text":"StatsProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerProgress(_:bannerInfo:)","url":"\/documentation\/ovkit\/statshandlerconsole\/adbannerprogress(_:bannerinfo:)","type":"topic","title":"adBannerProgress(_:bannerInfo:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}],"abstract":[{"text":"Пользователь досмотрел до определенных участков.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"adBannerProgress:bannerInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"adBannerProgress:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","text":"OVKStatsProgress"},{"kind":"text","text":") "},{"kind":"internalParam","text":"progress"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"OVKAdStatsBannerInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerInfo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Участки 3s, 10s, 25p, 50p, 75p, 100p."}]}],"name":"progress"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Информация о рекламном баннере"}]}],"name":"bannerInfo"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"OVKStatsProgress","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title"},{"value":[{"text":"OVKStatsProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments"},{"value":[{"text":"OVKStatsProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle"},{"value":"OVKStatsHandlerConsole","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle"},{"value":"OVKAdStatsBannerInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title"},{"value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments"},{"value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle"},{"value":"adBannerProgress:bannerInfo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerProgress(_:bannerInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerProgress(_:bannerInfo:)\/fragments"}]}]}