{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adNoBanners(responseTime:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"adNoBanners(responseTime:)","navigatorTitle":[{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)adNoBannersWithResponseTime:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adNoBanners","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"abstract":[{"text":"Рекламный плеер не будет играть рекламу для данного видео.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/adnobanners(responsetime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/adnobanners(responsetime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adNoBanners"},{"kind":"text","text":"("},{"kind":"externalParam","text":"responseTime"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Количество секунд с момента запроса рекламы до получения ответа."}],"type":"paragraph"}],"name":"responseTime"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}],"kind":"symbol","title":"StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adNoBanners(responseTime:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/adnobanners(responsetime:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adNoBanners(responseTime:)","title":"adNoBanners(responseTime:)","navigatorTitle":[{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"abstract":[{"type":"text","text":"Рекламный плеер не будет играть рекламу для данного видео."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adNoBanners"},{"kind":"text","text":"("},{"text":"responseTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsHandlerConsole","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adNoBannersWithResponseTime:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"adNoBannersWithResponseTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"responseTime","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"responseTime","content":[{"type":"paragraph","inlineContent":[{"text":"Количество секунд с момента запроса рекламы до получения ответа.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"adNoBannersWithResponseTime:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adNoBanners(responseTime:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"adNoBannersWithResponseTime:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adNoBanners(responseTime:)\/fragments"},{"value":"OVKStatsHandlerConsole","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}