{"abstract":[{"text":"Запрос на воспроизведение баннера к рекламному плееру.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/adrequestbanner(bannerinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/adrequestbanner(bannerinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adRequestBanner(bannerInfo:)"},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)adRequestBannerWithBannerInfo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","title":"adRequestBanner(bannerInfo:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier","text":"AdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adRequestBanner(bannerInfo:)":{"abstract":[{"text":"Запрос на воспроизведение баннера к рекламному плееру.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRequestBanner","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adRequestBanner(bannerInfo:)","url":"\/documentation\/ovkit\/statshandlerconsole\/adrequestbanner(bannerinfo:)","title":"adRequestBanner(bannerInfo:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsBannerInfo"}],"title":"AdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","url":"\/documentation\/ovkit\/adstatsbannerinfo","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"kind":"symbol","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adRequestBannerWithBannerInfo:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerInfo"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"adRequestBannerWithBannerInfo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adRequestBanner(bannerInfo:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adRequestBanner(bannerInfo:)\/fragments","op":"replace"},{"value":"OVKStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKAdStatsBannerInfo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","op":"replace"},{"value":"OVKStatsHandlerConsole","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}