{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adSkip(bannerInfo:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"bannerInfo","content":[{"inlineContent":[{"type":"text","text":"Информация о рекламном баннере"}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"text":"Пользователь нажал кнопку пропуска рекламы.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)adSkipWithBannerInfo:","navigatorTitle":[{"text":"adSkipWithBannerInfo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"adSkip(bannerInfo:)","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/adskip(bannerinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/adskip(bannerinfo:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"title":"AdStatsBannerInfo","url":"\/documentation\/ovkit\/adstatsbannerinfo","navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adSkip(bannerInfo:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/adskip(bannerinfo:)","navigatorTitle":[{"kind":"identifier","text":"adSkipWithBannerInfo:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":")"}],"abstract":[{"text":"Пользователь нажал кнопку пропуска рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adSkip(bannerInfo:)","kind":"symbol","title":"adSkip(bannerInfo:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"url":"\/documentation\/ovkit\/statshandlerconsole","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":" для отладки, который будет писать события статистики в консоль.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol","title":"StatsHandlerConsole","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adSkipWithBannerInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"adSkipWithBannerInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bannerInfo"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"bannerInfo","content":[{"type":"paragraph","inlineContent":[{"text":"Информация о рекламном баннере","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adSkip(bannerInfo:)\/title","value":"adSkipWithBannerInfo:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adSkip(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]}]}]}