{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didEnterFullscreen()"},"abstract":[{"type":"text","text":"Произошел переход в полноэкранный режим."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/didenterfullscreen()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/didenterfullscreen()"]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)didEnterFullscreen","role":"symbol","title":"didEnterFullscreen()","navigatorTitle":[{"kind":"identifier","text":"didEnterFullscreen"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"kind":"text","text":"()"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"kind":"symbol","title":"StatsHandlerConsole","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/didEnterFullscreen()":{"kind":"symbol","title":"didEnterFullscreen()","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole\/didenterfullscreen()","abstract":[{"type":"text","text":"Произошел переход в полноэкранный режим."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didEnterFullscreen()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEnterFullscreen"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","title":"StatsHandler","type":"topic","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didEnterFullscreen","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didEnterFullscreen"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didEnterFullscreen()\/title","value":"didEnterFullscreen","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didEnterFullscreen()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didEnterFullscreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"}]}]}