{"variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/emptybuffer(time:connectiontype:connectionreused:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/emptybuffer(time:connectiontype:connectionreused:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"emptyBufferWithTime:connectionType:connectionReused:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"emptyBuffer(time:connectionType:connectionReused:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)emptyBufferWithTime:connectionType:connectionReused:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/emptyBuffer(time:connectionType:connectionReused:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"abstract":[{"type":"text","text":"Плеер подгружал данные для дальнейшего воспроизведения."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"time","content":[{"inlineContent":[{"type":"text","text":"Время в миллисекундах, пока плеер буферизировался."}],"type":"paragraph"}]},{"name":"connectionType","content":[{"inlineContent":[{"type":"text","text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3)."}],"type":"paragraph"}]},{"name":"connectionReused","content":[{"inlineContent":[{"type":"text","text":"Было ли переиспользовано соединение при запросах."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Плеер буферизировался, во время проигрывания не успевал загружать данные, на экране был activity indicator.","type":"text"},{"text":" ","type":"text"},{"text":"Не засчитывается если буферизация после старта, перемотки, смены качества пользователем.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/emptyBuffer(time:connectionType:connectionReused:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"emptyBufferWithTime:connectionType:connectionReused:"}],"url":"\/documentation\/ovkit\/statshandlerconsole\/emptybuffer(time:connectiontype:connectionreused:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/emptyBuffer(time:connectionType:connectionReused:)","title":"emptyBuffer(time:connectionType:connectionReused:)","role":"symbol","abstract":[{"type":"text","text":"Плеер подгружал данные для дальнейшего воспроизведения."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","title":"StatsHandler","type":"topic","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"kind":"symbol","title":"StatsHandlerConsole","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"emptyBufferWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"emptyBufferWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"emptyBufferWithTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"time"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connectionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionReused:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"connectionReused"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Время в миллисекундах, пока плеер буферизировался.","type":"text"}]}],"name":"time"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Протокол, по которому идут запросы за видео к серверу (http1 \/ http2 \/ http3).","type":"text"}]}],"name":"connectionType"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Было ли переиспользовано соединение при запросах.","type":"text"}]}],"name":"connectionReused"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1emptyBuffer(time:connectionType:connectionReused:)\/title","value":"emptyBufferWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1emptyBuffer(time:connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"emptyBufferWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}