{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/failover(backupHost:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupHost","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"backupHost","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Хост, на который произошло переключение."}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/failover(backuphost:)"]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/failover(backuphost:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failover"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backupHost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)failoverWithBackupHost:","role":"symbol","title":"failover(backupHost:)","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","kind":"symbol","type":"topic","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"role":"symbol","title":"StatsHandlerConsole"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/failover(backupHost:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupHost","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/failover(backupHost:)","abstract":[{"text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок.","type":"text"}],"url":"\/documentation\/ovkit\/statshandlerconsole\/failover(backuphost:)","title":"failover(backupHost:)","kind":"symbol","navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","kind":"symbol","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"StatsHandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"failoverWithBackupHost:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"backupHost","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"backupHost","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Хост, на который произошло переключение."}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"OVKStatsHandlerConsole","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1failover(backupHost:)\/title","value":"failoverWithBackupHost:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1failover(backupHost:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace","value":"OVKStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}