{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/init(consolePrefix:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"consolePrefix","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)initWithConsolePrefix:","symbolKind":"init","title":"init(consolePrefix:)","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConsolePrefix:"}]},"variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/init(consoleprefix:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/init(consoleprefix:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Создание хендлера."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"consolePrefix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"consolePrefix","content":[{"inlineContent":[{"text":"Текстовый префикс, который будет выводиться в консоль перед каждым событием. ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает отсутствие префикса."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/init(consolePrefix:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/init(consolePrefix:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"consolePrefix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"title":"init(consolePrefix:)","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole\/init(consoleprefix:)","kind":"symbol","abstract":[{"type":"text","text":"Создание хендлера."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConsolePrefix:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"kind":"symbol","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithConsolePrefix:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConsolePrefix:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConsolePrefix:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"consolePrefix"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"consolePrefix","content":[{"inlineContent":[{"type":"text","text":"Текстовый префикс, который будет выводиться в консоль перед каждым событием. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает отсутствие префикса."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"initWithConsolePrefix:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1init(consolePrefix:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConsolePrefix:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1init(consolePrefix:)\/fragments"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"OVKStatsHandlerConsole","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}