{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)progressChangedWithTime:","roleHeading":"Instance Method","title":"progressChanged(time:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"progressChangedWithTime:"}]},"abstract":[{"type":"text","text":"Текущее время проигрывания изменилось."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Текущее время плеера."}],"type":"paragraph"}],"name":"time"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Обновляется не чаще, чем раз в секунду."}]},{"style":"warning","type":"aside","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Можно использовать только для статистики. Для обслуживания бизнес-логики вокруг плеера существует механизм ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)"},{"text":".","type":"text"}]}]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/progresschanged(time:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/progresschanged(time:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/progressChanged(time:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/progressChanged(time:)":{"kind":"symbol","title":"progressChanged(time:)","url":"\/documentation\/ovkit\/statshandlerconsole\/progresschanged(time:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/progressChanged(time:)","navigatorTitle":[{"text":"progressChangedWithTime:","kind":"identifier"}],"abstract":[{"text":"Текущее время проигрывания изменилось.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsHandlerConsole","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addPeriodicTimeObserver(forInterval:using:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","role":"symbol","abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"navigatorTitle":[{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)","type":"topic","title":"addPeriodicTimeObserver(forInterval:using:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}],"kind":"symbol","title":"StatsHandler"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"progressChangedWithTime:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"progressChangedWithTime:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущее время плеера."}]}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1progressChanged(time:)\/title","op":"replace","value":"progressChangedWithTime:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1progressChanged(time:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"progressChangedWithTime:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","op":"replace","value":"OVKStatsHandlerConsole"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","op":"replace","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/title","value":"addPeriodicTimeObserverForInterval:using:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"}]}]}