{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Время с которого начнется \/ продолжится воспроизведение (округлено до целых).","type":"text"}]}],"name":"fromTime"}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Вызовется при перезапуске видео пользователем или ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Также, если до этого играло другое видео — метод вызовется."},{"type":"text","text":" "},{"type":"text","text":"Если видео до этого было просто на паузе — метод вызван не будет (буден вызван "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()","isActive":true},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"Для трансляций будет использовано текущее время"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"startFromTime:"}],"title":"start(fromTime:)","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)startFromTime:","symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"abstract":[{"type":"text","text":"Видео начало играть в плеере, не важно userInitiated или нет."}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/start(fromtime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/start(fromtime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/start(fromTime:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/repeated":{"url":"\/documentation\/ovkit\/video\/repeated","role":"symbol","type":"topic","navigatorTitle":[{"text":"repeated","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"repeated","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/start(fromTime:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/start(fromtime:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"startFromTime:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"abstract":[{"text":"Видео начало играть в плеере, не важно userInitiated или нет.","type":"text"}],"title":"start(fromTime:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/start(fromTime:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole","title":"StatsHandlerConsole","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}],"navigatorTitle":[{"text":"StatsHandlerConsole","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"type":"topic","title":"StatsHandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/statshandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/resume()":{"type":"topic","role":"symbol","title":"resume()","abstract":[{"text":"Видео было снято с паузы пользователем.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"resume","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/resume()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startFromTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startFromTime:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"startFromTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fromTime"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"fromTime","content":[{"inlineContent":[{"text":"Время с которого начнется \/ продолжится воспроизведение (округлено до целых).","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/title","value":"repeated","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/fragments","value":[{"text":"repeated","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1start(fromTime:)\/title","value":"startFromTime:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1start(fromTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startFromTime:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"op":"replace","value":"resume","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resume"}],"op":"replace"}]}]}