{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Будет установлено после добавления в ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","kind":"typeIdentifier","text":"StatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/statshandlerconsole\/statistics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statshandlerconsole\/statistics"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext"},{"kind":"text","text":"?"}],"title":"statistics","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(py)statistics","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"statistics"}],"symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/statistics","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","url":"\/documentation\/ovkit\/video","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"Video"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"title":"StatsCollector","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","kind":"symbol","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerContext"}],"url":"\/documentation\/ovkit\/statshandlercontext","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","title":"StatsHandlerContext","abstract":[{"text":"Набор свойств, к которому может обращаться ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerContext"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/statistics":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","kind":"typeIdentifier","text":"StatsHandlerContext"},{"kind":"text","text":"?"}],"abstract":[{"text":"Будет установлено после добавления в ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/statistics","url":"\/documentation\/ovkit\/statshandlerconsole\/statistics","title":"statistics","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"statistics"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}],"navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","kind":"symbol","type":"topic","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"role":"symbol","title":"StatsHandlerConsole"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"statistics","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"statistics","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKStatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"statistics","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","op":"replace","value":"OVKStatsCollector"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"OVKStatsHandlerContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title"},{"value":[{"text":"OVKStatsHandlerContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments"},{"value":[{"text":"OVKStatsHandlerContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/navigatorTitle"},{"value":"statistics","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1statistics\/title"},{"value":[{"text":"statistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1statistics\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"OVKStatsHandlerConsole","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle"}]}]}