{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Объект с информацией о новой дорожке видео."}],"type":"paragraph"}],"name":"info"},{"content":[{"inlineContent":[{"type":"text","text":"Было ли изменение качества инициировано пользователем."}],"type":"paragraph"}],"name":"userInitiated"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoQuality(_:userInitiated:)"},"abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/videoquality(_:userinitiated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/videoquality(_:userinitiated:)"]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)videoQuality:userInitiated:","title":"videoQuality(_:userInitiated:)","navigatorTitle":[{"text":"videoQuality:userInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","text":"VideoTrackInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","title":"StatsHandler","type":"topic","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoTrackInfo":{"role":"symbol","abstract":[{"type":"text","text":"Информация о выбранной дорожке"}],"navigatorTitle":[{"kind":"identifier","text":"VideoTrackInfo"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoTrackInfo"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","url":"\/documentation\/ovkit\/videotrackinfo","kind":"symbol","title":"VideoTrackInfo"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/videoQuality(_:userInitiated:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoQuality(_:userInitiated:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/videoquality(_:userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"videoQuality:userInitiated:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","kind":"typeIdentifier","text":"VideoTrackInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Изменилось качество проигрывания."}],"title":"videoQuality(_:userInitiated:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"kind":"symbol","title":"StatsHandlerConsole","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"videoQuality:userInitiated:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"videoQuality:userInitiated:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"videoQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoTrackInfo","text":"OVKVideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"userInitiated","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Объект с информацией о новой дорожке видео.","type":"text"}]}],"name":"info"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Было ли изменение качества инициировано пользователем.","type":"text"}]}],"name":"userInitiated"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"OVKVideoTrackInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/title"},{"value":[{"text":"OVKVideoTrackInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/fragments"},{"value":[{"text":"OVKVideoTrackInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoTrackInfo\/navigatorTitle"},{"value":"videoQuality:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoQuality(_:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"videoQuality:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoQuality(_:userInitiated:)\/fragments"},{"value":"OVKStatsHandlerConsole","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments"},{"value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle"}]}]}