{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole(im)watchCoverageFromTime:toTime:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"watchCoverage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","title":"watchCoverage(fromTime:toTime:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchCoverage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Время в секундах откуда пользователь начал смотреть (округлено до целых)."}],"type":"paragraph"}],"name":"fromTime"},{"content":[{"inlineContent":[{"type":"text","text":"Время в секундах где пользователь закончил смотреть (округлено до целых)."}],"type":"paragraph"}],"name":"toTime"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Могут приходить перед перемоткой или после окончания воспроизведения видео.","type":"text"},{"text":" ","type":"text"},{"text":"Для трансляций используется текущее время.","type":"text"}]}]}],"abstract":[{"text":"Непрерывно просмотренные отрезки видео.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/watchCoverage(fromTime:toTime:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/watchcoverage(fromtime:totime:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole\/watchcoverage(fromtime:totime:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","title":"StatsHandler","type":"topic","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/watchCoverage(fromTime:toTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/watchCoverage(fromTime:toTime:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/watchcoverage(fromtime:totime:)","navigatorTitle":[{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchCoverage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Непрерывно просмотренные отрезки видео."}],"title":"watchCoverage(fromTime:toTime:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"kind":"symbol","title":"StatsHandlerConsole","type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"watchCoverageFromTime:toTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"watchCoverageFromTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fromTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"toTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"toTime"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Время в секундах откуда пользователь начал смотреть (округлено до целых).","type":"text"}]}],"name":"fromTime"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Время в секундах где пользователь закончил смотреть (округлено до целых).","type":"text"}]}],"name":"toTime"}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1watchCoverage(fromTime:toTime:)\/title","value":"watchCoverageFromTime:toTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1watchCoverage(fromTime:toTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}]}]}]}