{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdInteractive"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoMotion","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"banner"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdInteractive\/videoMotion(banner:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adinteractive\/videomotion(banner:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:5OVKit13AdInteractiveO11videoMotionyAcA016MyTargetInstreamb5VideoE6Banner_p_tcACmF","modules":[{"name":"OVKit"}],"roleHeading":"Case","role":"symbol","title":"AdInteractive.videoMotion(banner:)","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"videoMotion","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"banner"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":")","kind":"text"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdInteractive":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdInteractive"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdInteractive","url":"\/documentation\/ovkit\/adinteractive","title":"AdInteractive","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdInteractive"}]},"doc://onevideo.OVKit/documentation/OVKit/AdInteractive/videoMotion(banner:)":{"url":"\/documentation\/ovkit\/adinteractive\/videomotion(banner:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoMotion","kind":"identifier"},{"kind":"text","text":"("},{"text":"banner","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdInteractive\/videoMotion(banner:)","type":"topic","title":"AdInteractive.videoMotion(banner:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","title":"MyTargetInstreamAdVideoMotionBanner","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MyTargetInstreamAdVideoMotionBanner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","op":"replace"},{"value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle"}]}]}