{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Direction","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Direction"}],"modules":[{"name":"OVKit"}],"symbolKind":"enum","title":"FastRewindView.Direction","roleHeading":"Enumeration","role":"symbol","externalID":"s:5OVKit14FastRewindViewC9DirectionO","navigatorTitle":[{"text":"Direction","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/ovkit\/fastrewindview\/direction-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/left","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/right"],"anchor":"Enumeration-Cases"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/Equatable-Implementations"]}],"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView":{"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FastRewindView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FastRewindView","kind":"identifier"}],"title":"FastRewindView","type":"topic","url":"\/documentation\/ovkit\/fastrewindview"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum/left":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"kind":"symbol","abstract":[],"title":"FastRewindView.Direction.left","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/left","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum\/left","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum/right":{"url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum\/right","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/right","title":"FastRewindView.Direction.right","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum/Equatable-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/Equatable-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum":{"url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Direction","kind":"identifier"}],"title":"FastRewindView.Direction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","navigatorTitle":[{"text":"Direction","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/title","op":"replace","value":"FastRewindView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/fragments","value":[{"text":"FastRewindView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/navigatorTitle","value":[{"text":"FastRewindView","kind":"identifier"}]}]}]}