{"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(in:direction:stepSeconds:)","externalID":"s:5OVKit14FastRewindViewC2in9direction11stepSecondsACSo6CGRectV_AC9DirectionOSitcfc","modules":[{"name":"OVKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"text":"FastRewindView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"text":".","kind":"text"},{"text":"Direction","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO"},{"text":", ","kind":"text"},{"text":"stepSeconds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bounds"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"text":"FastRewindView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO","text":"Direction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"stepSeconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fastrewindview\/init(in:direction:stepseconds:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/init(in:direction:stepSeconds:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/init(in:direction:stepSeconds:)":{"abstract":[],"role":"symbol","title":"init(in:direction:stepSeconds:)","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/fastrewindview\/init(in:direction:stepseconds:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"direction","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FastRewindView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"kind":"text","text":"."},{"text":"Direction","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stepSeconds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/init(in:direction:stepSeconds:)"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Direction"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"Direction","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","title":"FastRewindView.Direction"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","navigatorTitle":[{"kind":"identifier","text":"FastRewindView"}],"url":"\/documentation\/ovkit\/fastrewindview","type":"topic","title":"FastRewindView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FastRewindView"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"FastRewindView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/fragments","value":[{"kind":"identifier","text":"FastRewindView"}],"op":"replace"},{"value":[{"text":"FastRewindView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}