{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fastrewindview\/willhandle(point:in:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willHandle"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bounds","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","kind":"typeIdentifier","text":"FastRewindView"},{"text":".","kind":"text"},{"text":"Direction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/willHandle(point:in:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView"]]},"sections":[],"metadata":{"symbolKind":"method","externalID":"s:5OVKit14FastRewindViewC10willHandle5point2inAC9DirectionOSgSo7CGPointV_So6CGRectVtFZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willHandle"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView","text":"FastRewindView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO","kind":"typeIdentifier","text":"Direction"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"OVKit"}],"title":"willHandle(point:in:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/willHandle(point:in:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willHandle"},{"kind":"text","text":"("},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"text":"FastRewindView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Direction","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO"},{"text":"?","kind":"text"}],"kind":"symbol","title":"willHandle(point:in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/willHandle(point:in:)","url":"\/documentation\/ovkit\/fastrewindview\/willhandle(point:in:)","type":"topic","role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"Direction"}],"type":"topic","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum","title":"FastRewindView.Direction","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Direction"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FastRewindView"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","url":"\/documentation\/ovkit\/fastrewindview","title":"FastRewindView","navigatorTitle":[{"kind":"identifier","text":"FastRewindView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/title","op":"replace","value":"FastRewindView"},{"op":"replace","value":[{"text":"FastRewindView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/fragments"},{"value":[{"text":"FastRewindView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/navigatorTitle"}]}]}