{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"⚠️ Свойство должно быть "},{"inlineContent":[{"text":"weak","type":"text"}],"type":"strong"},{"type":"text","text":"!"}]}],"type":"aside","style":"warning","name":"Warning"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcomingcoverview\/covercontrolsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/upcomingcoverview\/covercontrolsdelegate"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"abstract":[{"text":"Делегат ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":". Устанавливать не нужно","type":"text"}],"sections":[],"metadata":{"title":"coverControlsDelegate","navigatorTitle":[{"text":"coverControlsDelegate","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coverControlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverControlsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKUpcomingCoverView(py)coverControlsDelegate"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/coverControlsDelegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"title":"CoverView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/coverview","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"url":"\/documentation\/ovkit\/upcomingcoverview","navigatorTitle":[{"kind":"identifier","text":"UpcomingCoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"type":"topic","title":"UpcomingCoverView","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverControlsDelegate"}],"abstract":[{"text":"Делегат, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":" могут выполнять действия.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","type":"topic","title":"CoverControlsDelegate","role":"symbol","navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/covercontrolsdelegate"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/coverControlsDelegate":{"title":"coverControlsDelegate","navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}],"type":"topic","abstract":[{"text":"Делегат ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":". Устанавливать не нужно","type":"text"}],"url":"\/documentation\/ovkit\/upcomingcoverview\/covercontrolsdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CoverControlsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/coverControlsDelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"coverControlsDelegate"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"coverControlsDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"text":"id<OVKCoverControlsDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKCoverControlsDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKUpcomingCoverView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title","value":"OVKCoverControlsDelegate"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle","value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1coverControlsDelegate\/title","value":"coverControlsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1coverControlsDelegate\/fragments","value":[{"text":"coverControlsDelegate","kind":"identifier"}]}]}]}