{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/didEndTransitioning()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@OVKit@objc(cs)OVKUpcomingCoverView(im)didEndTransitioning","symbolKind":"method","title":"didEndTransitioning()","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEndTransitioning"}]},"variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview\/didendtransitioning()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/upcomingcoverview\/didendtransitioning()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Плеер закончил переезд на новую "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndTransitioning"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"url":"\/documentation\/ovkit\/upcomingcoverview","title":"UpcomingCoverView","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"navigatorTitle":[{"kind":"identifier","text":"UpcomingCoverView"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","url":"\/documentation\/ovkit\/playerview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"kind":"symbol","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/didEndTransitioning()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/didEndTransitioning()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didEndTransitioning()","type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/didendtransitioning()","kind":"symbol","abstract":[{"text":"Плеер закончил переезд на новую ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"didEndTransitioning","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didEndTransitioning"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didEndTransitioning"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","op":"replace","value":"OVKUpcomingCoverView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1didEndTransitioning()\/title","op":"replace","value":"didEndTransitioning"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1didEndTransitioning()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didEndTransitioning"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}