{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(frame:previewFrame:params:)","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","externalID":"s:5OVKit17UpcomingCoverViewC5frame12previewFrame6paramsACSgSo6CGRectV_AiA0cD6ParamsCtcfc","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/init(frame:previewFrame:params:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcomingcoverview\/init(frame:previewframe:params:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/init(frame:previewFrame:params:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/init(frame:previewframe:params:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/init(frame:previewFrame:params:)","role":"symbol","abstract":[],"title":"init(frame:previewFrame:params:)"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"title":"CoverViewParams","abstract":[{"type":"text","text":"Параметры для сборки "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/coverviewparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoverViewParams","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"type":"topic","title":"UpcomingCoverView","url":"\/documentation\/ovkit\/upcomingcoverview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UpcomingCoverView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"title":"CoverView","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/coverview","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","op":"replace","value":"OVKCoverViewParams"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","op":"replace","value":"OVKUpcomingCoverView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}