{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview\/params"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"params","symbolKind":"property","externalID":"s:5OVKit17UpcomingCoverViewC6paramsAA0cD6ParamsCvp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"params","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/params"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"params","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"kind":"symbol","title":"CoverView","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/coverview"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","abstract":[{"text":"Параметры для сборки ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","type":"topic","url":"\/documentation\/ovkit\/coverviewparams","title":"CoverViewParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoverViewParams","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"role":"symbol","url":"\/documentation\/ovkit\/upcomingcoverview","kind":"symbol","title":"UpcomingCoverView","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingCoverView","kind":"identifier"}],"navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/params":{"type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/params","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier","text":"CoverViewParams"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/params","title":"params"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","value":"OVKUpcomingCoverView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}