{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/previewImageFrame","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"previewImageFrame","navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKUpcomingCoverView(py)previewImageFrame","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview\/previewimageframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/upcomingcoverview\/previewimageframe"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Устанавливать не нужно, свойство может быть обновлено в любой момент."}]}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","title":"UpcomingCoverView","url":"\/documentation\/ovkit\/upcomingcoverview","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/previewImageFrame":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/previewImageFrame","role":"symbol","abstract":[{"type":"text","text":"Информация о том, была ли загружена preview в момент показа "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"url":"\/documentation\/ovkit\/upcomingcoverview\/previewimageframe","type":"topic","title":"previewImageFrame","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"previewImageFrame","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"previewImageFrame"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","value":"OVKUpcomingCoverView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1previewImageFrame\/title","op":"replace","value":"previewImageFrame"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1previewImageFrame\/fragments","op":"replace","value":[{"kind":"identifier","text":"previewImageFrame"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}