{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/smallLayout"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"title":"smallLayout","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smallLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:5OVKit17UpcomingCoverViewC11smallLayoutSbvp"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcomingcoverview\/smalllayout"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/smallLayout":{"url":"\/documentation\/ovkit\/upcomingcoverview\/smalllayout","title":"smallLayout","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/smallLayout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smallLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"url":"\/documentation\/ovkit\/upcomingcoverview","title":"UpcomingCoverView","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingCoverView","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","value":"OVKUpcomingCoverView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}