{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UpcomingLiveTimeContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKUpcomingLiveTimeContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeContainer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UpcomingLiveTimeContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKUpcomingLiveTimeContainer"}],"title":"timeContainer","symbolKind":"property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit17UpcomingCoverViewC13timeContainerAA0b8LiveTimeF0Cvp","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/timeContainer","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview\/timecontainer"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/timeContainer":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKUpcomingLiveTimeContainer","text":"UpcomingLiveTimeContainer"}],"url":"\/documentation\/ovkit\/upcomingcoverview\/timecontainer","title":"timeContainer","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/timeContainer","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"url":"\/documentation\/ovkit\/upcomingcoverview","navigatorTitle":[{"kind":"identifier","text":"UpcomingCoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"type":"topic","title":"UpcomingCoverView","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"url":"\/documentation\/ovkit\/upcominglivetimecontainer","title":"UpcomingLiveTimeContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer","type":"topic","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","value":"OVKUpcomingCoverView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/title","value":"OVKUpcomingLiveTimeContainer","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/fragments","value":[{"text":"OVKUpcomingLiveTimeContainer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/navigatorTitle","value":[{"text":"OVKUpcomingLiveTimeContainer","kind":"identifier"}],"op":"replace"}]}]}