{"abstract":[{"text":"Размер заголовка заглушки, по умолчанию 16pt.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleSize","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview\/titlesize"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:5OVKit13CoverViewTypePAAE9titleSize14CoreFoundation7CGFloatVvp::SYNTHESIZED::c:@M@OVKit@objc(cs)OVKUpcomingCoverView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"extendedModule":"OVKit","title":"titleSize","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/titleSize":{"abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleSize","kind":"symbol","title":"titleSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","url":"\/documentation\/ovkit\/upcomingcoverview\/titlesize"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"title":"UpcomingCoverView","url":"\/documentation\/ovkit\/upcomingcoverview","navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingCoverView","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","value":"OVKUpcomingCoverView"},{"value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","op":"replace"}]}]}