{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"externalID":"s:5OVKit17UpcomingCoverViewC10titleLabelSo7UILabelCvp"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcomingcoverview\/titlelabel"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleLabel","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/titleLabel":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"title":"titleLabel","url":"\/documentation\/ovkit\/upcomingcoverview\/titlelabel","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"url":"\/documentation\/ovkit\/upcomingcoverview","title":"UpcomingCoverView","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"navigatorTitle":[{"kind":"identifier","text":"UpcomingCoverView"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","op":"replace","value":"OVKUpcomingCoverView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","op":"replace","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","op":"replace","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}