{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:didValidateItem:error:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Закончилась проверка целостности записи в оффлайн библиотеке."}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:didvalidateitem:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:didvalidateitem:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"persistenceManager(_:didValidateItem:error:)","navigatorTitle":[{"kind":"identifier","text":"persistenceManager:didValidateItem:error:"}],"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener(im)persistenceManager:didValidateItem:error:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didValidateItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","text":"PersistenceManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager"},{"text":", ","kind":"text"},{"text":"didValidateItem","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Менеджер, от которого пришло событие."}],"type":"paragraph"}],"name":"manager"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Запись, для которой проводилась проверка."}]}],"name":"item"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Если в результате проверки вернулся ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" – значит проверка прошла успешно.","type":"text"}]}],"name":"error"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:didValidateItem:error:)":{"navigatorTitle":[{"kind":"identifier","text":"persistenceManager:didValidateItem:error:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:didValidateItem:error:)","abstract":[{"type":"text","text":"Закончилась проверка целостности записи в оффлайн библиотеке."}],"url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:didvalidateitem:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didValidateItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"required":true,"role":"symbol","title":"persistenceManager(_:didValidateItem:error:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener":{"url":"\/documentation\/ovkit\/persistencemanagerlistener","title":"PersistenceManagerListener","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerListener"}],"abstract":[{"type":"text","text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео."}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerListener"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","title":"PersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistentItem","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","title":"PersistentItem","type":"topic","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"url":"\/documentation\/ovkit\/persistentitem","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"persistenceManager:didValidateItem:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"persistenceManager:didValidateItem:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"persistenceManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","text":"OVKPersistenceManager","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didValidateItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"OVKPersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Менеджер, от которого пришло событие."}]}]},{"name":"item","content":[{"inlineContent":[{"type":"text","text":"Запись, для которой проводилась проверка."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"Если в результате проверки вернулся "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" – значит проверка прошла успешно."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:didValidateItem:error:)\/title","value":"persistenceManager:didValidateItem:error:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:didValidateItem:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"persistenceManager:didValidateItem:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/title","value":"OVKPersistenceManagerListener"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/fragments","value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/navigatorTitle","value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","value":[{"text":"OVKPersistentItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}