{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener(im)persistenceManager:removed:","title":"persistenceManager(_:removed:)","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"persistenceManager:removed:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"removed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PersistenceManager","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"},{"text":", ","kind":"text"},{"text":"removed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Менеджер, от которого пришло событие."}]}]},{"name":"item","content":[{"inlineContent":[{"text":"Удаленная запись.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:removed:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:removed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:removed:)"]}],"abstract":[{"text":"Из оффлайн библиотеки была удалена запись.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistentItem","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","title":"PersistentItem","type":"topic","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"url":"\/documentation\/ovkit\/persistentitem","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","title":"PersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:removed:)":{"title":"persistenceManager(_:removed:)","required":true,"url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:removed:)","navigatorTitle":[{"kind":"identifier","text":"persistenceManager:removed:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistenceManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager"},{"text":", ","kind":"text"},{"text":"removed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:removed:)","abstract":[{"type":"text","text":"Из оффлайн библиотеки была удалена запись."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener":{"url":"\/documentation\/ovkit\/persistencemanagerlistener","title":"PersistenceManagerListener","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerListener"}],"abstract":[{"type":"text","text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео."}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerListener"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"persistenceManager:removed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"persistenceManager:removed:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"persistenceManager:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPersistenceManager","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manager"},{"text":" ","kind":"text"},{"text":"removed:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"OVKPersistentItem"},{"kind":"text","text":" *) "},{"text":"item","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Менеджер, от которого пришло событие."}]}],"name":"manager"},{"content":[{"inlineContent":[{"type":"text","text":"Удаленная запись."}],"type":"paragraph"}],"name":"item"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"value":"persistenceManager:removed:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:removed:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"persistenceManager:removed:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:removed:)\/fragments"},{"op":"replace","value":"OVKPersistenceManagerListener","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerListener"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerListener"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}