{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"insets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler\/didUpdate(insets:)"},"abstract":[{"text":"Изменилось значение инсетов.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovinsetshandler\/didupdate(insets:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovinsetshandler\/didupdate(insets:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"didUpdateWithInsets:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"insets"},{"kind":"text","text":": "},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","required":true,"externalID":"c:@M@OVKit@objc(pl)OVInsetsHandler(im)didUpdateWithInsets:","title":"didUpdate(insets:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVInsetsHandler/didUpdate(insets:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didUpdateWithInsets:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"insets"},{"kind":"text","text":": "},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler\/didUpdate(insets:)","abstract":[{"text":"Изменилось значение инсетов.","type":"text"}],"url":"\/documentation\/ovkit\/ovinsetshandler\/didupdate(insets:)","required":true,"kind":"symbol","role":"symbol","title":"didUpdate(insets:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVInsetsHandler":{"title":"OVInsetsHandler","navigatorTitle":[{"text":"OVInsetsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVInsetsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler","abstract":[{"type":"text","text":"Протокол наблюдателя за инсетами."}],"url":"\/documentation\/ovkit\/ovinsetshandler","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didUpdateWithInsets:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didUpdateWithInsets:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didUpdateWithInsets:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":") ","kind":"text"},{"text":"insets","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler~1didUpdate(insets:)\/title","op":"replace","value":"didUpdateWithInsets:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler~1didUpdate(insets:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateWithInsets:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/title","op":"replace","value":"OVInsetsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVInsetsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVInsetsHandler","kind":"identifier"}]}]}]}