{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/autoplaySetting(of:changedTo:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"autoplaySettingOf:changedTo:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoplaySetting"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"changedTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate(im)autoplaySettingOf:changedTo:","title":"autoplaySetting(of:changedTo:)","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Настройка автовоспроизведения следующего видео была изменена пользователем.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"autoplaySetting","kind":"identifier"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", ","kind":"text"},{"text":"changedTo","kind":"externalParam"},{"kind":"text","text":" "},{"text":"autoplay","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, в котором была изменена настройка автовоспроизведения."}]}]},{"name":"autoplay","content":[{"type":"paragraph","inlineContent":[{"text":"Новое значение параметра автовоспроизведения.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerqueuedelegate\/autoplaysetting(of:changedto:)"]},{"paths":["\/documentation\/ovkit\/playerqueuedelegate\/autoplaysetting(of:changedto:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate/autoplaySetting(of:changedTo:)":{"navigatorTitle":[{"text":"autoplaySettingOf:changedTo:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Настройка автовоспроизведения следующего видео была изменена пользователем."}],"url":"\/documentation\/ovkit\/playerqueuedelegate\/autoplaysetting(of:changedto:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/autoplaySetting(of:changedTo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoplaySetting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changedTo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"autoplaySetting(of:changedTo:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","role":"symbol","kind":"symbol","title":"PlayerQueueDelegate","url":"\/documentation\/ovkit\/playerqueuedelegate","abstract":[{"type":"text","text":"Протокол для поддержки плеером очереди воспроизведения."}],"navigatorTitle":[{"text":"PlayerQueueDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerQueueDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"autoplaySettingOf:changedTo:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"autoplaySettingOf:changedTo:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"autoplaySettingOf:"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"kind":"text","text":" *) "},{"text":"playerView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changedTo:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoplay"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, в котором была изменена настройка автовоспроизведения.","type":"text"}]}]},{"name":"autoplay","content":[{"type":"paragraph","inlineContent":[{"text":"Новое значение параметра автовоспроизведения.","type":"text"}]}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1autoplaySetting(of:changedTo:)\/title","op":"replace","value":"autoplaySettingOf:changedTo:"},{"value":[{"text":"- ","kind":"text"},{"text":"autoplaySettingOf:changedTo:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1autoplaySetting(of:changedTo:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/title","value":"OVKPlayerQueueDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerQueueDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/navigatorTitle","value":[{"text":"OVKPlayerQueueDelegate","kind":"identifier"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}