{"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"changeToPreviousVideoIn:"}],"title":"changeToPreviousVideo(in:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate(im)changeToPreviousVideoIn:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"changeToPreviousVideo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/changeToPreviousVideo(in:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"changeToPreviousVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, в котором необходимо переключить видео.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Необходимо изменить "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},{"type":"text","text":" у плеера, переданного в параметре, на предыдущее видео в очереди воспроизведения, если такое имеется."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate"]]},"kind":"symbol","abstract":[{"type":"text","text":"Переключение на предыдущее видео в очереди воспроизведения."}],"variants":[{"paths":["\/documentation\/ovkit\/playerqueuedelegate\/changetopreviousvideo(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerqueuedelegate\/changetopreviousvideo(in:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerQueueDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","url":"\/documentation\/ovkit\/playerqueuedelegate","role":"symbol","type":"topic","abstract":[{"text":"Протокол для поддержки плеером очереди воспроизведения.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerQueueDelegate"}],"title":"PlayerQueueDelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate/changeToPreviousVideo(in:)":{"role":"symbol","abstract":[{"text":"Переключение на предыдущее видео в очереди воспроизведения.","type":"text"}],"kind":"symbol","title":"changeToPreviousVideo(in:)","type":"topic","url":"\/documentation\/ovkit\/playerqueuedelegate\/changetopreviousvideo(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"changeToPreviousVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/changeToPreviousVideo(in:)","navigatorTitle":[{"text":"changeToPreviousVideoIn:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"role":"symbol","kind":"symbol","abstract":[{"text":"Не устанавливать nil: останавливать проигрывание необходимо через ","type":"text"},{"type":"codeVoice","code":"stop()"},{"type":"text","text":" или "},{"code":"prepareForReuse()","type":"codeVoice"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/video","title":"video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"video"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"changeToPreviousVideoIn:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"changeToPreviousVideoIn:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"changeToPreviousVideoIn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/title","value":"OVKPlayerQueueDelegate"},{"value":[{"kind":"identifier","text":"OVKPlayerQueueDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/fragments"},{"value":"changeToPreviousVideoIn:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1changeToPreviousVideo(in:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1changeToPreviousVideo(in:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"changeToPreviousVideoIn:"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"op":"replace","value":"video","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","value":[{"text":"video","kind":"identifier"}]}]}]}