{"metadata":{"role":"symbol","navigatorTitle":[{"text":"changeToNextVideoIn:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate(im)changeToNextVideoIn:","title":"changeToNextVideo(in:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"changeToNextVideo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeToNextVideo"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, в котором необходимо переключить видео.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Необходимо сменить ресурс (лучше всего использовать ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/changeVideo(to:)"},{"type":"text","text":") у плеера, переданного в параметре, на следующее видео в очереди воспроизведения, если такое имеется."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerqueuedelegate\/changetonextvideo(in:)"]},{"paths":["\/documentation\/ovkit\/playerqueuedelegate\/changetonextvideo(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Переключение на следующее видео в очереди воспроизведения."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/changeToNextVideo(in:)"},"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"abstract":[],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate":{"kind":"symbol","role":"symbol","abstract":[{"text":"Протокол для поддержки плеером очереди воспроизведения.","type":"text"}],"title":"PlayerQueueDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerQueueDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerqueuedelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","navigatorTitle":[{"text":"PlayerQueueDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate/changeToNextVideo(in:)":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerqueuedelegate\/changetonextvideo(in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/changeToNextVideo(in:)","title":"changeToNextVideo(in:)","abstract":[{"text":"Переключение на следующее видео в очереди воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeToNextVideo"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"changeToNextVideoIn:"}],"kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/changeVideo(to:)":{"kind":"symbol","abstract":[{"text":"Смена видео в плеере.","type":"text"}],"navigatorTitle":[{"text":"changeVideoTo:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/changeVideo(to:)","title":"changeVideo(to:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playerview\/changevideo(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"changeVideo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"changeToNextVideoIn:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"changeToNextVideoIn:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"changeToNextVideoIn:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"name":"playerView","content":[{"inlineContent":[{"text":"Плеер, в котором необходимо переключить видео.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/title","value":"OVKPlayerQueueDelegate"},{"op":"replace","value":[{"text":"OVKPlayerQueueDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerQueueDelegate"}],"op":"replace"},{"value":"changeToNextVideoIn:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1changeToNextVideo(in:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1changeToNextVideo(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeToNextVideoIn:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1changeVideo(to:)\/title","value":"changeVideoTo:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1changeVideo(to:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeVideoTo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}