{"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","navigatorTitle":[{"text":"nextVideoFor:","kind":"identifier"}],"roleHeading":"Instance Method","title":"nextVideo(for:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate(im)nextVideoFor:","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextVideo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Есть ли следующее видео в очереди воспроизведения."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerqueuedelegate\/nextvideo(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerqueuedelegate\/nextvideo(for:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nextVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},{"text":"?","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, который готовится переключаться на следующее видео в очереди."}]}],"name":"playerView"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"Следующее видео в очереди воспроизведения."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/nextVideo(for:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate":{"abstract":[{"type":"text","text":"Протокол для поддержки плеером очереди воспроизведения."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerQueueDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerQueueDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","url":"\/documentation\/ovkit\/playerqueuedelegate","type":"topic","title":"PlayerQueueDelegate","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","title":"VideoType","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate/nextVideo(for:)":{"role":"symbol","navigatorTitle":[{"text":"nextVideoFor:","kind":"identifier"}],"title":"nextVideo(for:)","abstract":[{"type":"text","text":"Есть ли следующее видео в очереди воспроизведения."}],"type":"topic","url":"\/documentation\/ovkit\/playerqueuedelegate\/nextvideo(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextVideo"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":"?","kind":"text"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate\/nextVideo(for:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"nextVideoFor:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nextVideoFor:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType","text":"id<OVKVideoType>"},{"text":") ","kind":"text"},{"text":"nextVideoFor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":" *) "},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"op":"replace","value":"OVKPlayerQueueDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/fragments","op":"replace","value":[{"text":"OVKPlayerQueueDelegate","kind":"identifier"}]},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1nextVideo(for:)\/title","op":"replace","value":"nextVideoFor:"},{"value":[{"text":"- ","kind":"text"},{"text":"nextVideoFor:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate~1nextVideo(for:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}