{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hide","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer(im)hide","roleHeading":"Instance Method","title":"hide()","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"hide","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/hide()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/hide()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/hide()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hide","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/hide()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"hide"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/hide()","abstract":[],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/hide()","kind":"symbol","title":"hide()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer","role":"symbol","type":"topic","title":"MyTargetInstreamAdPostViewPlayer","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hide","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"hide","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"hide"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"hide","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1hide()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"hide","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1hide()\/fragments"},{"op":"replace","value":"MyTargetInstreamAdPostViewPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}