{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate","text":"MyTargetInstreamAdPostViewPlayerDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Must be a weak property.","type":"text"}]}],"type":"aside","style":"warning"}]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/ovkit_delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer"]]},"metadata":{"modules":[{"name":"OVKit"}],"required":true,"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate","text":"MyTargetInstreamAdPostViewPlayerDelegate"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer(py)ovkit_delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ovkit_delegate"}],"title":"ovkit_delegate","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/ovkit_delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/ovkit_delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/ovkit_delegate":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/ovkit_delegate","navigatorTitle":[{"kind":"identifier","text":"ovkit_delegate"}],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/ovkit_delegate","title":"ovkit_delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate","kind":"typeIdentifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"title":"MyTargetInstreamAdPostViewPlayer","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate","title":"MyTargetInstreamAdPostViewPlayerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ovkit_delegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ovkit_delegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MyTargetInstreamAdPostViewPlayerDelegate>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ovkit_delegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1ovkit_delegate\/title"},{"value":[{"text":"ovkit_delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1ovkit_delegate\/fragments"},{"value":"MyTargetInstreamAdPostViewPlayer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle"},{"value":"MyTargetInstreamAdPostViewPlayerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/title"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/fragments"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}