{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","text":"MyTargetPostViewData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/show(postview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/show(postview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"postView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetPostViewData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"show(postView:)","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer(im)showWithPostView:","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"showWithPostView:","kind":"identifier"}],"required":true,"symbolKind":"method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/show(postView:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/show(postView:)":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"showWithPostView:","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/show(postview:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/show(postView:)","title":"show(postView:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"postView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetPostViewData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"MyTargetInstreamAdPostViewPlayer"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyTargetPostViewData"}],"url":"\/documentation\/ovkit\/mytargetpostviewdata","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","title":"MyTargetPostViewData","abstract":[{"type":"text","text":"Данные, которые необходимы для отображения поствью после баннера."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"showWithPostView:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showWithPostView:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showWithPostView:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetPostViewData","text":"id<MyTargetPostViewData>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"showWithPostView:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1show(postView:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1show(postView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showWithPostView:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title","value":"MyTargetInstreamAdPostViewPlayer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/title","value":"MyTargetPostViewData"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/fragments","value":[{"text":"MyTargetPostViewData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"op":"replace"}]}]}