{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/update(progress:duration:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/update(progress:duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/update(progress:duration:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method","title":"update(progress:duration:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer(im)updateWithProgress:duration:","navigatorTitle":[{"text":"updateWithProgress:duration:","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/update(progress:duration:)":{"navigatorTitle":[{"text":"updateWithProgress:duration:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/update(progress:duration:)","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/update(progress:duration:)","type":"topic","kind":"symbol","required":true,"title":"update(progress:duration:)"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"title":"MyTargetInstreamAdPostViewPlayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"updateWithProgress:duration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateWithProgress:duration:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateWithProgress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"progress"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1update(progress:duration:)\/title","value":"updateWithProgress:duration:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1update(progress:duration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateWithProgress:duration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title","value":"MyTargetInstreamAdPostViewPlayer","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle","value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}