{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"metadata":{"role":"symbol","symbolKind":"op","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","roleHeading":"Operator","extendedModule":"Swift","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:5OVKit14FastRewindViewC9DirectionO","modules":[{"relatedModules":["Swift"],"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/!=(_:_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fastrewindview\/direction-swift.enum\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum/!=(_:_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","type":"topic","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum","kind":"symbol","title":"FastRewindView.Direction","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Direction"}],"navigatorTitle":[{"kind":"identifier","text":"Direction"}]},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView":{"role":"symbol","url":"\/documentation\/ovkit\/fastrewindview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastRewindView"}],"navigatorTitle":[{"text":"FastRewindView","kind":"identifier"}],"title":"FastRewindView","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/title","value":"FastRewindView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/fragments","value":[{"kind":"identifier","text":"FastRewindView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/navigatorTitle","value":[{"kind":"identifier","text":"FastRewindView"}]}]}]}