{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/focusedIndexPathForIndexPrefetcher(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate"]]},"kind":"symbol","metadata":{"title":"focusedIndexPathForIndexPrefetcher(_:)","required":true,"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"IndexPrefetcher"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":"?"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"}],"externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate(im)focusedIndexPathForIndexPrefetcher:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Префетчер, который работает с текущим индексом."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", который находится в фокусе."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Запрашивается после вызова "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"reference","isActive":true},{"type":"text","text":". Если вернуть "},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":", он будет использован вместо переденного в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"reference","isActive":true},{"type":"text","text":"."}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/focusedindexpathforindexprefetcher(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/focusedindexpathforindexprefetcher(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/reached(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reached","kind":"identifier"},{"kind":"text","text":"("},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"reached(_:)","type":"topic","url":"\/documentation\/ovkit\/indexprefetcher\/reached(_:)","kind":"symbol","abstract":[{"type":"text","text":"Предзагрузка элементов списка после текущей позиции."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reached:"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcherDelegate"}],"title":"IndexPrefetcherDelegate","type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdelegate","kind":"symbol","abstract":[{"type":"text","text":"Протокол, через который "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/focusedIndexPathForIndexPrefetcher(_:)":{"title":"focusedIndexPathForIndexPrefetcher(_:)","url":"\/documentation\/ovkit\/indexprefetcherdelegate\/focusedindexpathforindexprefetcher(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/focusedIndexPathForIndexPrefetcher(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"focusedIndexPathForIndexPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"IndexPrefetcher"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"}],"kind":"symbol","abstract":[{"type":"text","text":"Запрашивается после вызова "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","isActive":true},{"type":"text","text":". Если вернуть "},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":", он будет использован вместо переденного в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"reference","isActive":true},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"title":"IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"kind":"symbol","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"focusedIndexPathForIndexPrefetcher:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"OVKIndexPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"text":"Префетчер, который работает с текущим индексом.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", который находится в фокусе."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"reached:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reached:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/fragments"},{"value":"OVKIndexPrefetcherDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/navigatorTitle"},{"value":"focusedIndexPathForIndexPrefetcher:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1focusedIndexPathForIndexPrefetcher(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1focusedIndexPathForIndexPrefetcher(_:)\/fragments"},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}