{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemPrefetchDidFail"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Префетчер, который совершил операцию."}]}],"name":"prefetcher"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ресурс, в ходе загрузки которого произошла ошибка."}]}],"name":"item"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ошибка, возникшая при выполнении операции."}]}],"name":"error"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Сообщает об ошибке во время выполнения операции."}],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:itemprefetchdidfail:witherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:itemprefetchdidfail:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate(im)indexPrefetcher:itemPrefetchDidFail:withError:","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:itemPrefetchDidFail:withError:"}],"roleHeading":"Instance Method","title":"indexPrefetcher(_:itemPrefetchDidFail:withError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"itemPrefetchDidFail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:itemPrefetchDidFail:withError:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"title":"PrefetchItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"type":"topic","url":"\/documentation\/ovkit\/indexprefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"title":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate":{"role":"symbol","title":"IndexPrefetcherDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","abstract":[{"type":"text","text":"Протокол, через который "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcherDelegate"}],"url":"\/documentation\/ovkit\/indexprefetcherdelegate","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/indexPrefetcher(_:itemPrefetchDidFail:withError:)":{"role":"symbol","kind":"symbol","title":"indexPrefetcher(_:itemPrefetchDidFail:withError:)","url":"\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:itemprefetchdidfail:witherror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemPrefetchDidFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:itemPrefetchDidFail:withError:"}],"type":"topic","abstract":[{"text":"Сообщает об ошибке во время выполнения операции.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:itemPrefetchDidFail:withError:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"indexPrefetcher:itemPrefetchDidFail:withError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:itemPrefetchDidFail:withError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"indexPrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"OVKIndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"itemPrefetchDidFail:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Префетчер, который совершил операцию."}]}],"name":"prefetcher"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ресурс, в ходе загрузки которого произошла ошибка."}]}],"name":"item"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ошибка, возникшая при выполнении операции."}]}],"name":"error"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/title","value":"OVKIndexPrefetcherDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/navigatorTitle","value":[{"text":"OVKIndexPrefetcherDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:itemPrefetchDidFail:withError:)\/title","value":"indexPrefetcher:itemPrefetchDidFail:withError:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:itemPrefetchDidFail:withError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:itemPrefetchDidFail:withError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}