{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didCancelItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Сообщает об отмене операции."}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate(im)indexPrefetcher:didCancelItem:","required":true,"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:didCancelItem:"}],"title":"indexPrefetcher(_:didCancelItem:)","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCancelItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"text":", ","kind":"text"},{"text":"didCancelItem","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"item"},{"text":": ","kind":"text"},{"text":"PrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Префетчер, который совершил операцию.","type":"text"}]}],"name":"prefetcher"},{"name":"item","content":[{"type":"paragraph","inlineContent":[{"text":"Ресурс, загрузка которого была отменена.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Операция может быть отменена вручную вызовом ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","type":"reference","isActive":true},{"text":" или ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(at:)","isActive":true},{"type":"text","text":". Кроме того, при обновлении текущей позиции в индексе ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)"},{"type":"text","text":") может отменяться загрузка ресурсов, стоящих на более ранних позициях."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:didcancelitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:didcancelitem:)"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"title":"IndexPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndexPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/indexprefetcher","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate":{"abstract":[{"text":"Протокол, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndexPrefetcherDelegate"}],"navigatorTitle":[{"text":"IndexPrefetcherDelegate","kind":"identifier"}],"kind":"symbol","title":"IndexPrefetcherDelegate","type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdelegate"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":")"}],"abstract":[{"text":"Отмена предзагрузки произвольного элемента.","type":"text"}],"navigatorTitle":[{"text":"cancel:","kind":"identifier"}],"role":"symbol","title":"cancel(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(_:)","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/reached(_:)":{"title":"reached(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reached","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/indexprefetcher\/reached(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"topic","abstract":[{"text":"Предзагрузка элементов списка после текущей позиции.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"reached:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/indexPrefetcher(_:didCancelItem:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCancelItem"},{"text":": ","kind":"text"},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"indexPrefetcher:didCancelItem:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didCancelItem:)","role":"symbol","title":"indexPrefetcher(_:didCancelItem:)","url":"\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:didcancelitem:)","abstract":[{"type":"text","text":"Сообщает об отмене операции."}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(at:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(at:)","role":"symbol","title":"cancel(at:)","type":"topic","navigatorTitle":[{"text":"cancelAt:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(at:)","abstract":[{"type":"text","text":"Отмена предзагрузки произвольного элемента по его IndexPath."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"indexPrefetcher:didCancelItem:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:didCancelItem:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"OVKIndexPrefetcher"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"prefetcher"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCancelItem:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"prefetcher","content":[{"inlineContent":[{"text":"Префетчер, который совершил операцию.","type":"text"}],"type":"paragraph"}]},{"name":"item","content":[{"inlineContent":[{"type":"text","text":"Ресурс, загрузка которого была отменена."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/title","value":"OVKIndexPrefetcherDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}]},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/navigatorTitle"},{"value":"cancel:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cancel:","kind":"identifier"}]},{"op":"replace","value":"reached:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"reached:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didCancelItem:)\/title","value":"indexPrefetcher:didCancelItem:"},{"value":[{"kind":"text","text":"- "},{"text":"indexPrefetcher:didCancelItem:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didCancelItem:)\/fragments"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(at:)\/title","value":"cancelAt:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelAt:"}]}]}]}