{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKImageAsset(py)imageUrl","symbolKind":"property","title":"imageUrl","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageUrl"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/imageasset\/imageurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/imageasset\/imageurl"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ImageAssetType.imageUrl"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"kind":"symbol","title":"ImageAsset","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/imageasset","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/imageUrl":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/ovkit\/imageasset\/imageurl","role":"symbol","type":"topic","navigatorTitle":[{"text":"imageUrl","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl","kind":"symbol","title":"imageUrl"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"imageUrl","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"imageUrl","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"OVKImageAsset","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKImageAsset"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle","op":"replace"},{"value":"imageUrl","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl\/title","op":"replace"},{"value":[{"kind":"identifier","text":"imageUrl"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl\/fragments","op":"replace"}]}]}