{"metadata":{"modules":[{"name":"OVKit"}],"title":"imageUrl(for:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKImageAsset(im)imageUrlFor:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"imageUrlFor:"}],"role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Получение URL на изображение для заданного размера."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl(for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/imageasset\/imageurl(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/imageasset\/imageurl(for:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/imageUrl(for:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl(for:)","abstract":[{"text":"Получение URL на изображение для заданного размера.","type":"text"}],"url":"\/documentation\/ovkit\/imageasset\/imageurl(for:)","role":"symbol","type":"topic","title":"imageUrl(for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"imageUrlFor:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"title":"ImageAsset","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","type":"topic","navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/imageasset","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageUrlFor:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageUrlFor:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageUrlFor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"imageUrlFor:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl(for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageUrlFor:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl(for:)\/fragments"},{"op":"replace","value":"OVKImageAsset","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title"},{"op":"replace","value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKImageAsset"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}