{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"]]},"metadata":{"roleHeading":"Initializer","title":"init(url:forSize:)","role":"symbol","navigatorTitle":[{"text":"initWithUrl:forSize:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKImageAsset(im)initWithUrl:forSize:","modules":[{"name":"OVKit"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"symbolKind":"init"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/imageasset\/init(url:forsize:)"]},{"paths":["\/documentation\/ovkit\/imageasset\/init(url:forsize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(url:forSize:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/init(url:forSize:)":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/imageasset\/init(url:forsize:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(url:forSize:)","navigatorTitle":[{"text":"initWithUrl:forSize:","kind":"identifier"}],"abstract":[],"title":"init(url:forSize:)"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAsset"}],"role":"symbol","kind":"symbol","title":"ImageAsset","url":"\/documentation\/ovkit\/imageasset","navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithUrl:forSize:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithUrl:forSize:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUrl:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forSize:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1init(url:forSize:)\/title","op":"replace","value":"initWithUrl:forSize:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUrl:forSize:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1init(url:forSize:)\/fragments","op":"replace"},{"value":"OVKImageAsset","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments"},{"value":[{"kind":"identifier","text":"OVKImageAsset"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle"}]}]}