{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Является ли URL на ассет универсальным для любого размера.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isBase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/imageasset\/isbase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/imageasset\/isbase"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"isBase","kind":"identifier"}],"title":"isBase","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKImageAsset(py)isBase","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isBase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isBase","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/isBase":{"navigatorTitle":[{"kind":"identifier","text":"isBase"}],"title":"isBase","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Является ли URL на ассет универсальным для любого размера."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isBase","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/imageasset\/isbase"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","url":"\/documentation\/ovkit\/imageasset","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"ImageAsset"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isBase","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"isBase","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isBase","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"isBase","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isBase\/title","op":"replace"},{"value":[{"text":"isBase","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isBase\/fragments","op":"replace"},{"value":"OVKImageAsset","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title","op":"replace"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","op":"replace"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}