{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isEqual(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKImageAsset(im)isEqual:","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/imageasset\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/imageasset\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/imageasset\/isequal(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isEqual(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageAsset","kind":"identifier"}],"title":"ImageAsset","url":"\/documentation\/ovkit\/imageasset","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title","value":"OVKImageAsset","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","value":[{"kind":"identifier","text":"OVKImageAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle","value":[{"kind":"identifier","text":"OVKImageAsset"}],"op":"replace"}]}]}