{"abstract":[{"type":"text","text":"Видео-ресурс для предзагрузки."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchResource","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchResource","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchResource","title":"prefetchResource","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchResource"},{"kind":"text","text":": "},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"}],"role":"symbol","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"prefetchResource","kind":"identifier"}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchresource"]},{"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchresource"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchResource":{"role":"symbol","abstract":[{"type":"text","text":"Видео-ресурс для предзагрузки."}],"url":"\/documentation\/ovkit\/prefetchitem\/prefetchresource","required":true,"navigatorTitle":[{"text":"prefetchResource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchResource","title":"prefetchResource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prefetchResource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"abstract":[],"title":"VideoType"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","title":"PrefetchItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"type":"topic","url":"\/documentation\/ovkit\/prefetchitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"prefetchResource","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"prefetchResource","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<OVKVideoType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"text":" ","kind":"text"},{"text":"prefetchResource","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchResource\/title","value":"prefetchResource"},{"value":[{"text":"prefetchResource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchResource\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}