{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"prefetchPreviews","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchPreviews","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"]"}],"title":"prefetchPreviews","externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchPreviews","required":true},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"variants":[{"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchpreviews"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchpreviews"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchPreviews":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","url":"\/documentation\/ovkit\/prefetchitem\/prefetchpreviews","role":"symbol","abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"navigatorTitle":[{"text":"prefetchPreviews","kind":"identifier"}],"type":"topic","title":"prefetchPreviews","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"required":true,"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"title":"ImageAssetType","url":"\/documentation\/ovkit\/imageassettype","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageAssetType"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"prefetchPreviews"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"prefetchPreviews","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKImageAssetType>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"prefetchPreviews"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace","value":"OVKPrefetchItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/title","value":"prefetchPreviews"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/fragments","value":[{"kind":"identifier","text":"prefetchPreviews"}]},{"value":"OVKImageAssetType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}