{"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchQualityRangeWiFi","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeWiFi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"required":true,"title":"prefetchQualityRangeWiFi","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangewifi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangewifi"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeWiFi","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"QualityRange","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"abstract":[{"type":"text","text":"Диапазон качества видео."}],"url":"\/documentation\/ovkit\/qualityrange","kind":"symbol","title":"QualityRange","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchQualityRangeWiFi":{"title":"prefetchQualityRangeWiFi","abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeWiFi","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangewifi","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"prefetchQualityRangeWiFi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"OVKQualityRange"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prefetchQualityRangeWiFi"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeWiFi\/title","value":"prefetchQualityRangeWiFi"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeWiFi\/fragments","value":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}]}]}]}