{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","role":"symbol","required":true,"navigatorTitle":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"prefetchQualityRangeCellular","externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchQualityRangeCellular","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeCellular","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QualityRange","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangecellular"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangecellular"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeCellular","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"url":"\/documentation\/ovkit\/qualityrange","role":"symbol","type":"topic","title":"QualityRange","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchQualityRangeCellular":{"abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangecellular","title":"prefetchQualityRangeCellular","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeCellular"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","title":"PrefetchItem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"prefetchQualityRangeCellular","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","value":"OVKQualityRange","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace"},{"value":[{"text":"OVKQualityRange","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","op":"replace"},{"value":"prefetchQualityRangeCellular","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeCellular\/title","op":"replace"},{"value":[{"text":"prefetchQualityRangeCellular","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeCellular\/fragments","op":"replace"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"}]}]}