{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchthumbnails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/prefetchitem\/prefetchthumbnails"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]]},"metadata":{"symbolKind":"property","required":true,"title":"prefetchThumbnails","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem(py)prefetchThumbnails","role":"symbol","navigatorTitle":[{"text":"prefetchThumbnails","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchThumbnails","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"sections":[],"abstract":[{"type":"text","text":"Набор вариантов thumbnails для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchThumbnails"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchThumbnails"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"typeIdentifier","text":"ImageAssetType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchThumbnails":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchThumbnails","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/prefetchitem\/prefetchthumbnails","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchThumbnails","role":"symbol","abstract":[{"text":"Набор вариантов thumbnails для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchThumbnails"}],"required":true,"title":"prefetchThumbnails"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"title":"ImageAssetType","abstract":[{"text":"Ассет изображения.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","navigatorTitle":[{"text":"ImageAssetType","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/imageassettype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageAssetType"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"prefetchThumbnails","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"prefetchThumbnails"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKImageAssetType>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prefetchThumbnails"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"prefetchThumbnails","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchThumbnails\/title"},{"value":[{"text":"prefetchThumbnails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchThumbnails\/fragments"},{"value":"OVKPrefetchItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"},{"value":"OVKImageAssetType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title"},{"value":[{"text":"OVKImageAssetType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments"},{"value":[{"text":"OVKImageAssetType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/navigatorTitle"}]}]}