{"metadata":{"extendedModule":"Swift","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Operator","title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@OVKit@E@OVKValidationState","role":"symbol","modules":[{"name":"OVKit","relatedModules":["Swift"]}],"symbolKind":"op"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/validationstate\/!=(_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/!=(_:_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/ValidationState":{"url":"\/documentation\/ovkit\/validationstate","navigatorTitle":[{"kind":"identifier","text":"ValidationState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationState"}],"type":"topic","title":"ValidationState","abstract":[{"text":"Состояние проверки ресурса в оффлайн-хранилище.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/!=(_:_:)","type":"topic","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/ovkit\/validationstate\/!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKValidationState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/fragments","value":[{"kind":"identifier","text":"OVKValidationState"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}