{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState"]]},"abstract":[{"text":"Статус проверки неизвестен.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/none","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/validationstate\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/validationstate\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"OVKValidationStateNone","kind":"identifier"}],"title":"ValidationState.none","role":"symbol","externalID":"c:@M@OVKit@E@OVKValidationState@OVKValidationStateNone","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"case"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ValidationState/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"ValidationState.none","url":"\/documentation\/ovkit\/validationstate\/none","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKValidationStateNone"}],"abstract":[{"type":"text","text":"Статус проверки неизвестен."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/none"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationState","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState","url":"\/documentation\/ovkit\/validationstate","kind":"symbol","type":"topic","abstract":[{"text":"Состояние проверки ресурса в оффлайн-хранилище.","type":"text"}],"role":"symbol","title":"ValidationState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKValidationStateNone"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKValidationStateNone","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"OVKValidationStateNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1none\/title","op":"replace","value":"OVKValidationStateNone"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1none\/fragments","op":"replace","value":[{"text":"OVKValidationStateNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/title","op":"replace","value":"OVKValidationState"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/fragments","op":"replace","value":[{"text":"OVKValidationState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/navigatorTitle","op":"replace","value":[{"text":"OVKValidationState","kind":"identifier"}]}]}]}