{"abstract":[{"text":"Выполняется проверка.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/processing"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/validationstate\/processing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/validationstate\/processing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"ValidationState.processing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processing"}],"symbolKind":"case","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKValidationStateProcessing"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKValidationState@OVKValidationStateProcessing","roleHeading":"Case"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ValidationState/processing":{"abstract":[{"type":"text","text":"Выполняется проверка."}],"kind":"symbol","url":"\/documentation\/ovkit\/validationstate\/processing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processing"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKValidationStateProcessing"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/processing","title":"ValidationState.processing"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ValidationState":{"navigatorTitle":[{"text":"ValidationState","kind":"identifier"}],"title":"ValidationState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationState","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Состояние проверки ресурса в оффлайн-хранилище."}],"url":"\/documentation\/ovkit\/validationstate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"OVKValidationStateProcessing","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKValidationStateProcessing"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKValidationStateProcessing","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1processing\/title","value":"OVKValidationStateProcessing","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1processing\/fragments","value":[{"kind":"identifier","text":"OVKValidationStateProcessing"}],"op":"replace"},{"value":"OVKValidationState","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/title"},{"value":[{"text":"OVKValidationState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/navigatorTitle","value":[{"text":"OVKValidationState","kind":"identifier"}],"op":"replace"}]}]}