{"metadata":{"title":"chapters","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType"},{"kind":"text","text":"]"}],"externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider(py)chapters","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"chapters","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/chapters","interfaceLanguage":"swift"},"abstract":[{"text":"Список всех эпизодов в видео.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/chapterprovider\/chapters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/chapterprovider\/chapters"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType"},{"kind":"text","text":"]"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Отсортирован по времени начала эпизода.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","url":"\/documentation\/ovkit\/chapterprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"title":"ChapterProvider","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"title":"VideoChapterType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoChapterType"}],"abstract":[{"text":"Модель одного эпизода, на которые может быть поделена видеозапись.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapterType"}],"url":"\/documentation\/ovkit\/videochaptertype","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/chapters":{"kind":"symbol","title":"chapters","navigatorTitle":[{"text":"chapters","kind":"identifier"}],"abstract":[{"type":"text","text":"Список всех эпизодов в видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/chapters","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/chapterprovider\/chapters","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"chapters"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"chapters"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<OVKVideoChapterType>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKChapterProvider"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","value":"OVKVideoChapterType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments","value":[{"kind":"identifier","text":"OVKVideoChapterType"}]},{"value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1chapters\/title","value":"chapters"},{"value":[{"text":"chapters","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1chapters\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}