{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"foundChapterForSeekTime","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"seekTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","kind":"typeIdentifier","text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/foundChapterForSeekTime(_:)"},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","title":"foundChapterForSeekTime(_:)","externalID":"s:5OVKit15ChapterProviderC05foundB11ForSeekTimeyAA05VideoB4Type_pSgSdF","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"foundChapterForSeekTime","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"abstract":[{"type":"text","text":"Быстрый поиск эпизода по заданному времени."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/chapterprovider\/foundchapterforseektime(_:)"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videochaptertype","navigatorTitle":[{"text":"VideoChapterType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoChapterType","kind":"identifier"}],"title":"VideoChapterType","abstract":[{"type":"text","text":"Модель одного эпизода, на которые может быть поделена видеозапись."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/foundChapterForSeekTime(_:)":{"url":"\/documentation\/ovkit\/chapterprovider\/foundchapterforseektime(_:)","abstract":[{"text":"Быстрый поиск эпизода по заданному времени.","type":"text"}],"title":"foundChapterForSeekTime(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"foundChapterForSeekTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/foundChapterForSeekTime(_:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"url":"\/documentation\/ovkit\/chapterprovider","type":"topic","title":"ChapterProvider","abstract":[{"text":"Отвечает за разбивку видео на эпизоды по таймкодам.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKVideoChapterType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/navigatorTitle","op":"replace"},{"value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","op":"replace"}]}]}