{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/init(video:)"},"abstract":[{"type":"text","text":"Создание провайдера."}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider(im)initWithVideo:","title":"init(video:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVideo:"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"init","roleHeading":"Initializer"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/chapterprovider\/init(video:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/chapterprovider\/init(video:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"video","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","text":"VideoType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Видео, для которого происходит получение эпизодов."}],"type":"paragraph"}],"name":"video"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/init(video:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"video","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Создание провайдера."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/init(video:)","url":"\/documentation\/ovkit\/chapterprovider\/init(video:)","role":"symbol","title":"init(video:)","navigatorTitle":[{"text":"initWithVideo:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype","kind":"symbol","role":"symbol","title":"VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChapterProvider"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/chapterprovider","title":"ChapterProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithVideo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideo:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithVideo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType","text":"id<OVKVideoType>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"video","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Видео, для которого происходит получение эпизодов."}],"type":"paragraph"}],"name":"video"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"initWithVideo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1init(video:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithVideo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1init(video:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace"}]}]}