{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"variants":[{"paths":["\/documentation\/ovkit\/chapterprovider\/position(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/position(for:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoChapterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?"}],"symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","title":"position(for:)","externalID":"s:5OVKit15ChapterProviderC8position3forSiSgAA05VideoB4Type_p_tF"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"chapter","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoChapterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","title":"ChapterProvider","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"url":"\/documentation\/ovkit\/chapterprovider","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/position(for:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/chapterprovider\/position(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","title":"position(for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/position(for:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"title":"VideoChapterType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","navigatorTitle":[{"kind":"identifier","text":"VideoChapterType"}],"type":"topic","kind":"symbol","abstract":[{"text":"Модель одного эпизода, на которые может быть поделена видеозапись.","type":"text"}],"url":"\/documentation\/ovkit\/videochaptertype","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapterType"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKChapterProvider"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","op":"replace","value":"OVKVideoChapterType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments","value":[{"kind":"identifier","text":"OVKVideoChapterType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoChapterType"}]}]}]}