{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"updatePlayerTime(_:)","navigatorTitle":[{"text":"updatePlayerTime:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider(im)updatePlayerTime:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updatePlayerTime","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/chapterprovider\/updateplayertime(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/chapterprovider\/updateplayertime(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePlayerTime"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"currentTime","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/updatePlayerTime(_:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"url":"\/documentation\/ovkit\/chapterprovider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"title":"ChapterProvider","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/updatePlayerTime(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updatePlayerTime","kind":"identifier"},{"kind":"text","text":"("},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/chapterprovider\/updateplayertime(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/updatePlayerTime(_:)","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"updatePlayerTime:"}],"title":"updatePlayerTime(_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updatePlayerTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"updatePlayerTime:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"updatePlayerTime:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"currentTime"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace","value":"OVKChapterProvider"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","op":"replace","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1updatePlayerTime(_:)\/title","value":"updatePlayerTime:"},{"value":[{"text":"- ","kind":"text"},{"text":"updatePlayerTime:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1updatePlayerTime(_:)\/fragments","op":"replace"}]}]}