{"metadata":{"roleHeading":"Instance Method","title":"initWithFrame:","symbolKind":"method","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKLabel(im)initWithFrame:","modules":[{"name":"OVKit"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLabel\/initWithFrame:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovklabel\/initwithframe:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKLabel/initWithFrame:":{"title":"initWithFrame:","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLabel\/initWithFrame:","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/ovklabel\/initwithframe:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/label","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","role":"symbol","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"code":"UIKit\/UILabel","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Label"}],"title":"Label"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"OVKLabel"},{"value":[{"text":"OVKLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"value":[{"text":"OVKLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle"}]}]}