{"variants":[{"paths":["\/documentation\/ovkit\/ovklabel\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKLabel(im)initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"symbolKind":"method","modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLabel\/initWithCoder:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKLabel/initWithCoder:":{"title":"initWithCoder:","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLabel\/initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/ovklabel\/initwithcoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/label","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","role":"symbol","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"code":"UIKit\/UILabel","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Label"}],"title":"Label"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"OVKLabel","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments","value":[{"kind":"identifier","text":"OVKLabel"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLabel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}