{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)VideoProxyProtocol(py)activeProxy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeProxy"}],"title":"activeProxy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"required":true},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/activeProxy","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeProxy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videoproxyprotocol\/activeproxy"]},{"paths":["\/documentation\/ovkit\/videoproxyprotocol\/activeproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol/activeProxy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/activeProxy","kind":"symbol","type":"topic","abstract":[],"required":true,"role":"symbol","url":"\/documentation\/ovkit\/videoproxyprotocol\/activeproxy","title":"activeProxy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"activeProxy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"activeProxy"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoProxyProtocol"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoProxyProtocol"}],"kind":"symbol","type":"topic","title":"VideoProxyProtocol","url":"\/documentation\/ovkit\/videoproxyprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"activeProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"activeProxy"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"activeProxy","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1activeProxy\/title","op":"replace","value":"activeProxy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1activeProxy\/fragments","op":"replace","value":[{"kind":"identifier","text":"activeProxy"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/title","value":"VideoProxyProtocol","op":"replace"},{"value":[{"text":"VideoProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/fragments"}]}]}