{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/modifyRequest(_:)"},"kind":"symbol","metadata":{"required":true,"title":"modifyRequest(_:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modifyRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":") -> ","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"}],"symbolKind":"method","navigatorTitle":[{"text":"modifyRequest:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)VideoProxyProtocol(im)modifyRequest:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/videoproxyprotocol\/modifyrequest(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videoproxyprotocol\/modifyrequest(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol":{"title":"VideoProxyProtocol","url":"\/documentation\/ovkit\/videoproxyprotocol","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"VideoProxyProtocol"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol/modifyRequest(_:)":{"title":"modifyRequest(_:)","url":"\/documentation\/ovkit\/videoproxyprotocol\/modifyrequest(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/modifyRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"}],"navigatorTitle":[{"kind":"identifier","text":"modifyRequest:"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"modifyRequest:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyRequest:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"modifyRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"request"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/title","op":"replace","value":"VideoProxyProtocol"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"VideoProxyProtocol"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VideoProxyProtocol"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1modifyRequest(_:)\/title","op":"replace","value":"modifyRequest:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1modifyRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyRequest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}