{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menu\/contents"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menu\/contents"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKMenu(py)contents","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MenuContents","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents"}],"required":true,"title":"contents","navigatorTitle":[{"kind":"identifier","text":"contents"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contents"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","text":"MenuContents"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"sections":[],"abstract":[{"type":"text","text":"Данные для показа меню. Могут изменяться после того, как меню было показано."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/contents","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MenuContents":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuContents"}],"navigatorTitle":[{"kind":"identifier","text":"MenuContents"}],"url":"\/documentation\/ovkit\/menucontents","abstract":[{"type":"text","text":"Модель содержимого меню"}],"role":"symbol","title":"MenuContents","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Menu/contents":{"abstract":[{"text":"Данные для показа меню. Могут изменяться после того, как меню было показано.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/ovkit\/menu\/contents","title":"contents","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contents","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","text":"MenuContents","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"contents","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/contents","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"title":"Menu","abstract":[{"type":"text","text":"Модель, описывающая UI для построения меню плеера."}],"url":"\/documentation\/ovkit\/menu","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","navigatorTitle":[{"kind":"identifier","text":"Menu"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Menu"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contents"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"contents","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents","text":"OVKMenuContents","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"contents","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/title","value":"OVKMenuContents"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/fragments","value":[{"text":"OVKMenuContents","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuContents"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1contents\/title","value":"contents"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1contents\/fragments","value":[{"kind":"identifier","text":"contents"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","value":"OVKMenu"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments","value":[{"kind":"identifier","text":"OVKMenu"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenu"}]}]}]}