{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()"},"abstract":[{"type":"text","text":"Необходимо вызвать сразу после скрытия меню с экрана"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menu\/diddismiss()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menu\/diddismiss()"]}],"metadata":{"title":"didDismiss()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didDismiss"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKMenu(im)didDismiss","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"()"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/Menu":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","url":"\/documentation\/ovkit\/menu","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}],"navigatorTitle":[{"text":"Menu","kind":"identifier"}],"kind":"symbol","title":"Menu","role":"symbol","abstract":[{"type":"text","text":"Модель, описывающая UI для построения меню плеера."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Menu/didDismiss()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()","title":"didDismiss()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"didDismiss","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismiss","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/menu\/diddismiss()","abstract":[{"text":"Необходимо вызвать сразу после скрытия меню с экрана","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"didDismiss","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"didDismiss","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didDismiss","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKMenu","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title"},{"value":[{"text":"OVKMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments"},{"value":[{"text":"OVKMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/navigatorTitle"},{"value":"didDismiss","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didDismiss()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didDismiss","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didDismiss()\/fragments"}]}]}