{"abstract":[{"text":"Необходимо вызвать сразу после появления меню на экране.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menu\/didpresent()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menu\/didpresent()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresent"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKMenu(im)didPresent","modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didPresent","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didPresent"}],"required":true,"title":"didPresent()","roleHeading":"Instance Method","role":"symbol"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","title":"Menu","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Menu","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Включает в себя содержимое меню и обработчики контроля над его жизненным циклом. На основе содержимого необходимо создать и показать на экране меню в любом виде.","type":"text"}],"url":"\/documentation\/ovkit\/menu","navigatorTitle":[{"kind":"identifier","text":"Menu"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/didPresent()":{"required":true,"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()","title":"didPresent()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didPresent"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[{"text":"Необходимо вызвать сразу после появления меню на экране.","type":"text"}],"url":"\/documentation\/ovkit\/menu\/didpresent()","navigatorTitle":[{"kind":"identifier","text":"didPresent"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didPresent"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didPresent","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"didPresent","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"OVKMenu","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments","value":[{"kind":"identifier","text":"OVKMenu"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didPresent()\/title","value":"didPresent","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didPresent","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didPresent()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}