{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"style"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","text":"MenuStyle"}],"required":true,"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKMenu(py)style","title":"style","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"text":"MenuStyle","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menu\/style"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menu\/style"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/style","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Стиль пунктов меню, который наиболее подходит для отображения. Значение не изменяется при обновлении меню."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"navigatorTitle":[{"text":"Menu","kind":"identifier"}],"url":"\/documentation\/ovkit\/menu","abstract":[{"text":"Модель, описывающая UI для построения меню плеера.","type":"text"}],"title":"Menu","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Menu"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/style":{"url":"\/documentation\/ovkit\/menu\/style","navigatorTitle":[{"text":"style","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/style","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MenuStyle","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","kind":"typeIdentifier"}],"type":"topic","title":"style","required":true,"abstract":[{"text":"Стиль пунктов меню, который наиболее подходит для отображения. Значение не изменяется при обновлении меню.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"url":"\/documentation\/ovkit\/menustyle","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"type":"topic","title":"MenuStyle","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"style","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","text":"OVKMenuStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title","op":"replace","value":"OVKMenu"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenu"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/navigatorTitle","op":"replace","value":[{"text":"OVKMenu","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1style\/title","op":"replace","value":"style"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1style\/fragments","op":"replace","value":[{"kind":"identifier","text":"style"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","value":"OVKMenuStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","value":[{"text":"OVKMenuStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuStyle"}]}]}]}