{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:5OVKit19RouteChangeStrategyO8rawValueACSgSu_tcfc","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"OVKit"}],"title":"init(rawValue:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/init(rawvalue:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/routechangestrategy\/init(rawvalue:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RouteChangeStrategy","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/routechangestrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","role":"symbol","abstract":[{"text":"Определяет поведения плеера при смене output route.","type":"text"}],"navigatorTitle":[{"text":"RouteChangeStrategy","kind":"identifier"}],"title":"RouteChangeStrategy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"RouteChangeStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title"},{"op":"replace","value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments"},{"op":"replace","value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle"}]}]}