{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/pause"},"abstract":[{"text":"Происходит пауза в воспроизведении.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/pause"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/pause"]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@E@RouteChangeStrategy@RouteChangeStrategyPause","symbolKind":"case","navigatorTitle":[{"text":"RouteChangeStrategyPause","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Case","title":"RouteChangeStrategy.pause"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/pause":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategyPause"}],"url":"\/documentation\/ovkit\/routechangestrategy\/pause","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/pause","title":"RouteChangeStrategy.pause","role":"symbol","abstract":[{"text":"Происходит пауза в воспроизведении.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"kind":"symbol","title":"RouteChangeStrategy","type":"topic","url":"\/documentation\/ovkit\/routechangestrategy","abstract":[{"type":"text","text":"Определяет поведения плеера при смене output route."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategy"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteChangeStrategy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"RouteChangeStrategyPause","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"RouteChangeStrategyPause","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"RouteChangeStrategyPause","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1pause\/title","value":"RouteChangeStrategyPause"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1pause\/fragments","value":[{"text":"RouteChangeStrategyPause","kind":"identifier"}]},{"value":"RouteChangeStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title","op":"replace"},{"value":[{"kind":"identifier","text":"RouteChangeStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"RouteChangeStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle","op":"replace"}]}]}