{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/routechangestrategy\/play"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/play"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"]]},"abstract":[{"text":"Воспроизведение продолжается.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"}],"title":"RouteChangeStrategy.play","symbolKind":"case","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@RouteChangeStrategy@RouteChangeStrategyPlay","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"RouteChangeStrategyPlay","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/play","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/play":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/play","title":"RouteChangeStrategy.play","url":"\/documentation\/ovkit\/routechangestrategy\/play","abstract":[{"text":"Воспроизведение продолжается.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RouteChangeStrategyPlay","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"url":"\/documentation\/ovkit\/routechangestrategy","navigatorTitle":[{"text":"RouteChangeStrategy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteChangeStrategy"}],"type":"topic","title":"RouteChangeStrategy","abstract":[{"text":"Определяет поведения плеера при смене output route.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"RouteChangeStrategyPlay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RouteChangeStrategyPlay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"RouteChangeStrategyPlay","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1play\/title","value":"RouteChangeStrategyPlay"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1play\/fragments","value":[{"kind":"identifier","text":"RouteChangeStrategyPlay"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title","value":"RouteChangeStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments","value":[{"kind":"identifier","text":"RouteChangeStrategy"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle","value":[{"kind":"identifier","text":"RouteChangeStrategy"}]}]}]}