{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/routechangestrategy\/unknown"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"]]},"sections":[],"metadata":{"title":"RouteChangeStrategy.unknown","navigatorTitle":[{"text":"RouteChangeStrategyUnknown","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@RouteChangeStrategy@RouteChangeStrategyUnknown"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/unknown"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/unknown":{"title":"RouteChangeStrategy.unknown","navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategyUnknown"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/routechangestrategy\/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/unknown","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"url":"\/documentation\/ovkit\/routechangestrategy","navigatorTitle":[{"text":"RouteChangeStrategy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteChangeStrategy"}],"type":"topic","title":"RouteChangeStrategy","abstract":[{"text":"Определяет поведения плеера при смене output route.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"RouteChangeStrategyUnknown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"RouteChangeStrategyUnknown","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"RouteChangeStrategyUnknown"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1unknown\/title","op":"replace","value":"RouteChangeStrategyUnknown"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1unknown\/fragments","op":"replace","value":[{"text":"RouteChangeStrategyUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title","op":"replace","value":"RouteChangeStrategy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments","op":"replace","value":[{"text":"RouteChangeStrategy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle","op":"replace","value":[{"text":"RouteChangeStrategy","kind":"identifier"}]}]}]}