{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudio"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueAudio","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy"]]},"abstract":[{"text":"Продолжение проигрывания аудио.","type":"text"}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAudio"}],"externalID":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy@OVKBackgroundPlaybackPolicyContinueAudio","navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudio"}],"title":"BackgroundPlaybackPolicy.continueAudio","roleHeading":"Case","role":"symbol","symbolKind":"case"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/continueAudio":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudio"}],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudio","abstract":[{"type":"text","text":"Продолжение проигрывания аудио."}],"title":"BackgroundPlaybackPolicy.continueAudio","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAudio"}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","role":"symbol","abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"title":"BackgroundPlaybackPolicy"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"kind":"article","role":"article","type":"topic","abstract":[{"type":"text","text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","url":"\/documentation\/ovkit\/backgroundplayback","title":"Воспроизведение в фоне"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKBackgroundPlaybackPolicyContinueAudio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudio"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKBackgroundPlaybackPolicyContinueAudio","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/title","op":"replace","value":"OVKBackgroundPlaybackPolicyContinueAudio"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/fragments","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudio"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","value":"OVKBackgroundPlaybackPolicy","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}