{"metadata":{"roleHeading":"API Collection","modules":[{"name":"OVKit"}],"role":"collectionGroup","title":"Equatable Implementations"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/equatable-implementations"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"title":"BackgroundPlaybackPolicy","type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/!=(_:_:)","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","op":"replace","value":"OVKBackgroundPlaybackPolicy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}]}]}]}