{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","title":"hash(into:)","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit","relatedModules":["Swift"]}],"symbolKind":"method","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"extendedModule":"Swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/RawRepresentable-Implementations"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"navigatorTitle":[{"text":"BackgroundPlaybackPolicy","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BackgroundPlaybackPolicy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","kind":"symbol","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","title":"BackgroundPlaybackPolicy","abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/hash(into:)":{"kind":"symbol","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/hash(into:)","type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/hash(into:)","abstract":[],"title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","value":"OVKBackgroundPlaybackPolicy","op":"replace"},{"value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle","value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}