{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy@OVKBackgroundPlaybackPolicyPause","symbolKind":"case","navigatorTitle":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"modules":[{"name":"OVKit"}],"roleHeading":"Case","title":"BackgroundPlaybackPolicy.pause"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"languages":["swift"]}]}],"abstract":[{"text":"Приостановка воспроизведения.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/pause"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy\/pause"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"role":"symbol","abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","kind":"symbol","title":"BackgroundPlaybackPolicy"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/pause":{"role":"symbol","abstract":[{"text":"Приостановка воспроизведения.","type":"text"}],"navigatorTitle":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/pause","kind":"symbol","title":"BackgroundPlaybackPolicy.pause"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKBackgroundPlaybackPolicyPause","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyPause"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyPause"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKBackgroundPlaybackPolicy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title"},{"value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments"},{"value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/title","value":"OVKBackgroundPlaybackPolicyPause"},{"value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyPause"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/fragments"}]}]}