{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/name","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Тип баннера (preroll \/ midroll \/ postroll)","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkadstatsbannerinfo\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkadstatsbannerinfo\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo(py)name","roleHeading":"Instance Property","title":"name","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsBannerInfo"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdStatsBannerInfo"}],"kind":"symbol","url":"\/documentation\/ovkit\/adstatsbannerinfo","title":"AdStatsBannerInfo","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/name":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/name","role":"symbol","kind":"symbol","type":"topic","title":"name","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/name","abstract":[{"type":"text","text":"Тип баннера (preroll \/ midroll \/ postroll)"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"name"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"name","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1name\/title","op":"replace","value":"name"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1name\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}