{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Подтип баннера (video\/shoppable\/motion)","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkadstatsbannerinfo\/subtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkadstatsbannerinfo\/subtype"]}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"subtype","externalID":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo(py)subtype","navigatorTitle":[{"text":"subtype","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"subtype","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/subtype","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/subtype":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"subtype","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"subtype","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/subtype","kind":"symbol","title":"subtype","type":"topic","abstract":[{"text":"Подтип баннера (video\/shoppable\/motion)","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/subtype"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"navigatorTitle":[{"kind":"identifier","text":"AdStatsBannerInfo"}],"url":"\/documentation\/ovkit\/adstatsbannerinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdStatsBannerInfo"}],"type":"topic","abstract":[],"kind":"symbol","title":"AdStatsBannerInfo","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subtype"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"subtype","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"subtype","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"subtype","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1subtype\/title","op":"replace"},{"op":"replace","value":[{"text":"subtype","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1subtype\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}],"op":"replace"}]}]}