{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"makeCustomCoverViewWith","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"params"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","kind":"typeIdentifier","text":"CoverView","preciseIdentifier":"s:5OVKit9CoverViewa"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"playerView","content":[{"inlineContent":[{"text":"Плеер, для которого нужно создать ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"params","content":[{"inlineContent":[{"type":"text","text":"Параметры, на основе которых нужно собрать "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Фрейм, поверх которого будет показан собранный ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"text":".","type":"text"}]}],"name":"frame"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Фрейм превью изображения.","type":"text"}]}],"name":"previewFrame"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Если вернуть ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", будет создан ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":" по умолчанию.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"В определенные моменты времени плееру может понадобиться показать дополнительный UI поверх воспроизведения. Одни из примеров:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Еще не начавшаяся прямая трансляция с отсчетом до ее начала"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Дополнительные контролы при завершении видео"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Сообщение об ошибке"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Баннер запрета воспроизведения (restriction)"}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"В первую очередь ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" вызовет данный метод, в котором есть возможность собрать пользовательскую реализацию ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":". Это нужно делать на основе переданных ","type":"text"},{"code":"params","type":"codeVoice"},{"text":", они описывают ситуацию, с которой столкнулся плеер. Если данный метод не реализован или возвращает ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", то ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" покажет встроенную реализацию.","type":"text"}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerviewdelegate\/playerview(_:makecustomcoverviewwith:frame:previewframe:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerviewdelegate\/playerview(_:makecustomcoverviewwith:frame:previewframe:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Создание "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"type":"text","text":" для показа в плеере поверх воспроизведения."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate(im)playerView:makeCustomCoverViewWith:frame:previewFrame:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"makeCustomCoverViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9CoverViewa","text":"CoverView"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"playerView:makeCustomCoverViewWith:frame:previewFrame:"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)":{"type":"topic","navigatorTitle":[{"text":"playerView:makeCustomCoverViewWith:frame:previewFrame:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:makecustomcoverviewwith:frame:previewframe:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"makeCustomCoverViewWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CoverView","preciseIdentifier":"s:5OVKit9CoverViewa","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","title":"playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","role":"symbol","abstract":[{"text":"Создание ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":" для показа в плеере поверх воспроизведения.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","title":"CoverViewParams","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","url":"\/documentation\/ovkit\/coverviewparams","abstract":[{"text":"Параметры для сборки ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewParams"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","title":"CoverView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","url":"\/documentation\/ovkit\/coverview","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate":{"role":"symbol","abstract":[{"text":"Делегат ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" по вопросам отображения в UI.","type":"text"}],"navigatorTitle":[{"text":"PlayerViewDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate","url":"\/documentation\/ovkit\/playerviewdelegate","kind":"symbol","title":"PlayerViewDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"playerView:makeCustomCoverViewWith:frame:previewFrame:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:makeCustomCoverViewWith:frame:previewFrame:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIView<OVKCoverViewType>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIView@M@OVKit@objc(pl)OVKCoverViewType"},{"text":" *) ","kind":"text"},{"text":"playerView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"makeCustomCoverViewWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKCoverViewParams","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"frame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"previewFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"previewFrame","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, для которого нужно создать ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"text":"Параметры, на основе которых нужно собрать ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}]}]},{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"text":"Фрейм, поверх которого будет показан собранный ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}]}]},{"name":"previewFrame","content":[{"type":"paragraph","inlineContent":[{"text":"Фрейм превью изображения.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"Если вернуть ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", будет создан ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"text":" по умолчанию.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:makeCustomCoverViewWith:frame:previewFrame:)\/title","value":"playerView:makeCustomCoverViewWith:frame:previewFrame:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:makeCustomCoverViewWith:frame:previewFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:makeCustomCoverViewWith:frame:previewFrame:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/title","value":"OVKPlayerViewDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerViewDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}