{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerViewNeedsToShowUnmuteRestriction"},{"text":"()","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"playerViewNeedsToShowUnmuteRestriction()","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate(im)playerViewNeedsToShowUnmuteRestriction","roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewNeedsToShowUnmuteRestriction()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerViewNeedsToShowUnmuteRestriction"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerviewdelegate\/playerviewneedstoshowunmuterestriction()"]},{"paths":["\/documentation\/ovkit\/playerviewdelegate\/playerviewneedstoshowunmuterestriction()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate":{"url":"\/documentation\/ovkit\/playerviewdelegate","type":"topic","navigatorTitle":[{"text":"PlayerViewDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewDelegate"}],"kind":"symbol","title":"PlayerViewDelegate","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerViewNeedsToShowUnmuteRestriction()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerviewneedstoshowunmuterestriction()","title":"playerViewNeedsToShowUnmuteRestriction()","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewNeedsToShowUnmuteRestriction()","role":"symbol","navigatorTitle":[{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerViewNeedsToShowUnmuteRestriction"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/title","value":"OVKPlayerViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerViewDelegate"}],"op":"replace"},{"value":"playerViewNeedsToShowUnmuteRestriction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewNeedsToShowUnmuteRestriction()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewNeedsToShowUnmuteRestriction()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}