{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"action"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","title":"action","externalID":"c:@M@OVKit@objc(cs)OVKMenuAction(py)action","roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/ovkmenuaction\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmenuaction\/action"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/action","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenuAction/action":{"kind":"symbol","title":"action","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/action","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"action"}],"url":"\/documentation\/ovkit\/ovkmenuaction\/action"},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"kind":"symbol","title":"MenuAction","abstract":[{"text":"Абстрактная модель пункта меню, содержащая данные для его показа. По смыслу соответствует ","type":"text"},{"code":"UIAlertAction","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuAction"}],"navigatorTitle":[{"kind":"identifier","text":"MenuAction"}],"url":"\/documentation\/ovkit\/menuaction"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","title":"VoidBlock","url":"\/documentation\/ovkit\/voidblock","navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"VoidBlock","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"action","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"action"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"action"},{"kind":"text","text":")();"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"action","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1action\/title","op":"replace"},{"value":[{"kind":"identifier","text":"action"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1action\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","op":"replace","value":"OVKMenuAction"},{"op":"replace","value":[{"text":"OVKMenuAction","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments"}]}]}