{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/selected","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkmenuaction\/selected"]},{"paths":["\/documentation\/ovkit\/ovkmenuaction\/selected"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"selected"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@OVKit@objc(cs)OVKMenuAction(py)selected","title":"selected"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenuAction/selected":{"kind":"symbol","title":"selected","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/selected","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"selected"}],"url":"\/documentation\/ovkit\/ovkmenuaction\/selected"},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"kind":"symbol","title":"MenuAction","abstract":[{"text":"Абстрактная модель пункта меню, содержащая данные для его показа. По смыслу соответствует ","type":"text"},{"code":"UIAlertAction","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuAction"}],"navigatorTitle":[{"kind":"identifier","text":"MenuAction"}],"url":"\/documentation\/ovkit\/menuaction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"selected","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"selected","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selected"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"selected","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1selected\/title","op":"replace"},{"op":"replace","value":[{"text":"selected","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1selected\/fragments"},{"value":"OVKMenuAction","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuAction"}]}]}]}