{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkmenuaction\/style"]},{"paths":["\/documentation\/ovkit\/ovkmenuaction\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/style"},"kind":"symbol","sections":[],"metadata":{"title":"style","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIAlertAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAlertAction"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIAlertActionStyle","kind":"typeIdentifier","text":"Style"}],"symbolKind":"property","navigatorTitle":[{"text":"style","kind":"identifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKMenuAction(py)style","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIAlertAction","text":"UIAlertAction","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAlertActionStyle","text":"Style"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"kind":"symbol","title":"MenuAction","abstract":[{"text":"Абстрактная модель пункта меню, содержащая данные для его показа. По смыслу соответствует ","type":"text"},{"code":"UIAlertAction","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuAction"}],"navigatorTitle":[{"kind":"identifier","text":"MenuAction"}],"url":"\/documentation\/ovkit\/menuaction"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenuAction/style":{"kind":"symbol","title":"style","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuAction\/style","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIAlertAction","kind":"typeIdentifier","text":"UIAlertAction"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAlertActionStyle","text":"Style"}],"navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/ovkit\/ovkmenuaction\/style"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"style","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UIAlertActionStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAlertActionStyle"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKMenuAction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title"},{"value":[{"kind":"identifier","text":"OVKMenuAction"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","op":"replace"},{"value":"style","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1style\/title"},{"value":[{"kind":"identifier","text":"style"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuAction~1style\/fragments","op":"replace"}]}]}