{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/buffersettings\/init(maxbuffersize:mindurationforqualityincrease:maxdurationforqualitydecrease:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/buffersettings\/init(maxbuffersize:mindurationforqualityincrease:maxdurationforqualitydecrease:)"]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKBufferSettings(im)initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minDurationForQualityIncrease"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxDurationForQualityDecrease"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"role":"symbol","title":"init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)","navigatorTitle":[{"text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"maxBufferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxDurationForQualityDecrease","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BufferSettings","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/buffersettings","title":"BufferSettings","kind":"symbol","navigatorTitle":[{"text":"BufferSettings","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)","abstract":[],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/buffersettings\/init(maxbuffersize:mindurationforqualityincrease:maxdurationforqualitydecrease:)","title":"init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)","navigatorTitle":[{"text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxBufferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"maxDurationForQualityDecrease","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMaxBufferSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxBufferSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"minDurationForQualityIncrease:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minDurationForQualityIncrease"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDurationForQualityDecrease:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxDurationForQualityDecrease"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/title","value":"OVKBufferSettings","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/fragments","value":[{"kind":"identifier","text":"OVKBufferSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/navigatorTitle","value":[{"kind":"identifier","text":"OVKBufferSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)\/title","value":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","kind":"identifier"}],"op":"replace"}]}]}