{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"maxBufferSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings"]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"maxBufferSize","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxBufferSize"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"maxBufferSize","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKBufferSettings(py)maxBufferSize"},"variants":[{"paths":["\/documentation\/ovkit\/buffersettings\/maxbuffersize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/buffersettings\/maxbuffersize"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxBufferSize"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings":{"url":"\/documentation\/ovkit\/buffersettings","navigatorTitle":[{"text":"BufferSettings","kind":"identifier"}],"title":"BufferSettings","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BufferSettings","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/maxBufferSize":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBufferSize"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"maxBufferSize","kind":"identifier"}],"title":"maxBufferSize","url":"\/documentation\/ovkit\/buffersettings\/maxbuffersize","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxBufferSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"maxBufferSize","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maxBufferSize","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"text":"maxBufferSize","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"OVKBufferSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/fragments","value":[{"kind":"identifier","text":"OVKBufferSettings"}],"op":"replace"},{"value":[{"text":"OVKBufferSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxBufferSize\/title","value":"maxBufferSize","op":"replace"},{"value":[{"text":"maxBufferSize","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxBufferSize\/fragments","op":"replace"}]}]}