{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/buffersettings\/mindurationforqualityincrease"]},{"paths":["\/documentation\/ovkit\/buffersettings\/mindurationforqualityincrease"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/minDurationForQualityIncrease"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"minDurationForQualityIncrease"}],"externalID":"c:@M@OVKit@objc(cs)OVKBufferSettings(py)minDurationForQualityIncrease","title":"minDurationForQualityIncrease","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/minDurationForQualityIncrease":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minDurationForQualityIncrease"}],"title":"minDurationForQualityIncrease","url":"\/documentation\/ovkit\/buffersettings\/mindurationforqualityincrease","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/minDurationForQualityIncrease"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings":{"url":"\/documentation\/ovkit\/buffersettings","navigatorTitle":[{"text":"BufferSettings","kind":"identifier"}],"title":"BufferSettings","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BufferSettings","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"minDurationForQualityIncrease","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"minDurationForQualityIncrease","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"minDurationForQualityIncrease"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"minDurationForQualityIncrease","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1minDurationForQualityIncrease\/title"},{"value":[{"kind":"identifier","text":"minDurationForQualityIncrease"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1minDurationForQualityIncrease\/fragments"},{"value":"OVKBufferSettings","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/title"},{"op":"replace","value":[{"text":"OVKBufferSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/navigatorTitle","value":[{"text":"OVKBufferSettings","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}