{"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind"]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"ActionKind","roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@OVKit@E@OVKMenuActionKind","navigatorTitle":[{"kind":"identifier","text":"ActionKind"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/audioTrackSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/cancel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/debugMenu","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/diagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/playbackRateSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityOptionSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityPresetSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/subtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/trafficSaving"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKMenuActionKind) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionKind"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Можно использовать для изменения порядка пунктов меню или их выборочного исключения."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind/subtitles":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindSubtitles"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/subtitles","abstract":[{"type":"text","text":"Пункт меню, отвечающий за управление субтитрами."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"}],"url":"\/documentation\/ovkit\/actionkind\/subtitles","type":"topic","title":"ActionKind.subtitles","role":"symbol"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/other":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind\/other","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/other","abstract":[{"type":"text","text":"Зарезервированный кейс для кастомных пунктов меню, не входящих в стандартный набор."}],"title":"ActionKind.other","type":"topic","navigatorTitle":[{"text":"OVKMenuActionKindOther","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/audioTrackSelection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrackSelection"}],"url":"\/documentation\/ovkit\/actionkind\/audiotrackselection","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/audioTrackSelection","abstract":[{"text":"Пункт меню, отвечающий за выбор аудиодорожки.","type":"text"}],"title":"ActionKind.audioTrackSelection","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindAudioTrackSelection"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/cancel":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind\/cancel","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/cancel","abstract":[{"type":"text","text":"Кнопка отмены."}],"title":"ActionKind.cancel","type":"topic","navigatorTitle":[{"text":"OVKMenuActionKindCancel","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/qualityPresetSelection":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityPresetSelection","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind\/qualitypresetselection","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityPresetSelection","abstract":[{"type":"text","text":"Пункт меню, отвечающий за выбор предустановки качества (например, “Авто”, “Высокое”, “Экономия трафика”)."}],"title":"ActionKind.qualityPresetSelection","type":"topic","navigatorTitle":[{"text":"OVKMenuActionKindQualityPresetSelection","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/Equatable-Implementations","abstract":[],"url":"\/documentation\/ovkit\/actionkind\/equatable-implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/diagnosticsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/diagnosticsView","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindDiagnosticsView"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"diagnosticsView","kind":"identifier"}],"title":"ActionKind.diagnosticsView","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/actionkind\/diagnosticsview","abstract":[{"type":"text","text":"Пункт меню, управляющий видимостью окна диагностической информации."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/actionkind\/init(rawvalue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/init(rawValue:)"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/trafficSaving":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindTrafficSaving"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/trafficSaving","abstract":[{"type":"text","text":"Пункт меню, отвечающий за режим экономии трафика."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trafficSaving"}],"url":"\/documentation\/ovkit\/actionkind\/trafficsaving","type":"topic","title":"ActionKind.trafficSaving","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/ovkit\/actionkind\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"role":"symbol","title":"ActionKind","type":"topic","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/playbackRateSelection":{"role":"symbol","title":"ActionKind.playbackRateSelection","type":"topic","navigatorTitle":[{"text":"OVKMenuActionKindPlaybackRateSelection","kind":"identifier"}],"abstract":[{"type":"text","text":"Пункт меню, отвечающий за изменение скорости воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/playbackRateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRateSelection","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind\/playbackrateselection","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/debugMenu":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/debugMenu","title":"ActionKind.debugMenu","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugMenu","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind\/debugmenu","abstract":[{"type":"text","text":"Показ меню для разработчиков."}]},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/qualityOptionSelection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityOptionSelection"}],"url":"\/documentation\/ovkit\/actionkind\/qualityoptionselection","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityOptionSelection","abstract":[{"type":"text","text":"Пункт меню, отвечающий за выбор качества (разрешения) видео."}],"title":"ActionKind.qualityOptionSelection","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindQualityOptionSelection"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"OVKMenuActionKind","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/audioTrackSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/cancel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/debugMenu","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/diagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/playbackRateSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityOptionSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityPresetSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/subtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/trafficSaving"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKMenuActionKind","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1subtitles\/title","value":"OVKMenuActionKindSubtitles","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1subtitles\/fragments","value":[{"text":"OVKMenuActionKindSubtitles","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1other\/title","value":"OVKMenuActionKindOther","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1other\/fragments","value":[{"text":"OVKMenuActionKindOther","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1audioTrackSelection\/title","value":"OVKMenuActionKindAudioTrackSelection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1audioTrackSelection\/fragments","value":[{"text":"OVKMenuActionKindAudioTrackSelection","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1cancel\/title","value":"OVKMenuActionKindCancel"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1cancel\/fragments","value":[{"text":"OVKMenuActionKindCancel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityPresetSelection\/title","value":"OVKMenuActionKindQualityPresetSelection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityPresetSelection\/fragments","value":[{"text":"OVKMenuActionKindQualityPresetSelection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1diagnosticsView\/title","value":"OVKMenuActionKindDiagnosticsView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1diagnosticsView\/fragments","value":[{"text":"OVKMenuActionKindDiagnosticsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1trafficSaving\/title","value":"OVKMenuActionKindTrafficSaving","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1trafficSaving\/fragments","value":[{"text":"OVKMenuActionKindTrafficSaving","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","value":"OVKMenuActionKind","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1playbackRateSelection\/title","value":"OVKMenuActionKindPlaybackRateSelection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1playbackRateSelection\/fragments","value":[{"text":"OVKMenuActionKindPlaybackRateSelection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1debugMenu\/title","value":"OVKMenuActionKindDebugMenu","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1debugMenu\/fragments","value":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityOptionSelection\/title","value":"OVKMenuActionKindQualityOptionSelection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityOptionSelection\/fragments","value":[{"text":"OVKMenuActionKindQualityOptionSelection","kind":"identifier"}],"op":"replace"}]}]}