{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdsItemBadge","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ovk_text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ovk_textLabel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/style-swift.property"],"generated":true},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum"],"anchor":"Enumerations","title":"Enumerations"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ShoppableAdsItemViewBadgeStyled-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"],"kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/adsitembadge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/adsitembadge"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"text":"Текстовая метка для товара из рекламного баннера.","type":"text"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)AdsItemBadge","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdsItemBadge"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"AdsItemBadge","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/initWithFrame:":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/adsitembadge\/initwithframe:","title":"initWithFrame:","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/initWithFrame:","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","kind":"symbol","title":"AdsItemBadge.Style","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/style-swift.property":{"kind":"symbol","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.property","title":"style","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/style-swift.property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","text":"Style"}],"abstract":[{"type":"text","text":"Стиль метки."}]},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/LabeledView":{"kind":"symbol","title":"LabeledView","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LabeledView"}],"navigatorTitle":[{"text":"LabeledView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","url":"\/documentation\/ovkit\/labeledview","type":"topic","abstract":[{"text":"Протокол представления, содержащего текст.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/ovk_text":{"url":"\/documentation\/ovkit\/adsitembadge\/ovk_text","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ovk_text","title":"ovk_text","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ovk_text","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/documentation/OVKit/ShoppableAdsItemViewBadgeStyled":{"kind":"symbol","url":"\/documentation\/ovkit\/shoppableadsitemviewbadgestyled","title":"ShoppableAdsItemViewBadgeStyled","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ShoppableAdsItemViewBadgeStyled"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ShoppableAdsItemViewBadgeStyled","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UILetterformAwareAdjusting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","type":"unresolvable","title":"UIKit.UILetterformAwareAdjusting"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"abstract":[{"type":"text","text":"Текстовый визуальный компонент на основе "},{"type":"codeVoice","code":"UIKit\/UILabel"},{"text":".","type":"text"}],"kind":"symbol","title":"Label","type":"topic","url":"\/documentation\/ovkit\/label","role":"symbol","navigatorTitle":[{"text":"Label","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)UIContentSizeCategoryAdjusting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/ovk_textLabel":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ovk_textLabel","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ovk_textLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"title":"ovk_textLabel","url":"\/documentation\/ovkit\/adsitembadge\/ovk_textlabel"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/ShoppableAdsItemViewBadgeStyled-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/ShoppableAdsItemViewBadgeStyled-Implementations","url":"\/documentation\/ovkit\/adsitembadge\/shoppableadsitemviewbadgestyled-implementations","title":"ShoppableAdsItemViewBadgeStyled Implementations","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"url":"\/documentation\/ovkit\/adsitembadge","kind":"symbol","title":"AdsItemBadge","navigatorTitle":[{"kind":"identifier","text":"AdsItemBadge"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdsItemBadge","kind":"identifier"}],"abstract":[{"text":"Текстовая метка для товара из рекламного баннера.","type":"text"}]},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/initWithCoder:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/initWithCoder:","url":"\/documentation\/ovkit\/adsitembadge\/initwithcoder:","title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AdsItemBadge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"AdsItemBadge","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AdsItemBadge","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/initWithCoder:","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/initWithFrame:"],"generated":true}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdsItemBadge"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)Label","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","text":"Label"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"value":[{"kind":"identifier","text":"Label"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"AdsItemBadge","op":"replace"},{"value":[{"kind":"identifier","text":"AdsItemBadge"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","value":[{"text":"AdsItemBadge","kind":"identifier"}]}]}]}