{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]},{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]}],"seeAlsoSections":[{"anchor":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"],"generated":true,"title":"Статистика"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKAdStatsHandler) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","text":"StatsHandler","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adstatshandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatshandler"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerProgress(_:bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerStart(bannerInfo:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adLoadRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adNoBanners(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adRequestBanner(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adSkip(bannerInfo:)"]}],"abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"metadata":{"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler","title":"AdStatsHandler","navigatorTitle":[{"text":"AdStatsHandler","kind":"identifier"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsHandler","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adSkip(bannerInfo:)":{"role":"symbol","abstract":[{"text":"Пользователь нажал кнопку пропуска рекламы.","type":"text"}],"title":"adSkip(bannerInfo:)","kind":"symbol","navigatorTitle":[{"text":"adSkipWithBannerInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adskip(bannerinfo:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adSkip(bannerInfo:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"url":"\/documentation\/ovkit\/statshandlerconsole","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","title":"StatsHandlerConsole","role":"symbol","navigatorTitle":[{"text":"StatsHandlerConsole","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adLoadRequest()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adLoadRequest","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adloadrequest()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adLoadRequest()","abstract":[{"text":"Попросили рекламный плеер загрузить данные для instream video.","type":"text"}],"title":"adLoadRequest()","type":"topic","navigatorTitle":[{"text":"adLoadRequest","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adBannerStart(bannerInfo:duration:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adbannerstart(bannerinfo:duration:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerStart(bannerInfo:duration:)","abstract":[{"text":"Запустился рекламный баннер.","type":"text"}],"title":"adBannerStart(bannerInfo:duration:)","type":"topic","navigatorTitle":[{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","title":"StatsHandler","role":"symbol","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adRequestBanner(bannerInfo:)":{"role":"symbol","abstract":[{"text":"Запрос на воспроизведение баннера к рекламному плееру.","type":"text"}],"kind":"symbol","title":"adRequestBanner(bannerInfo:)","navigatorTitle":[{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRequestBanner","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adrequestbanner(bannerinfo:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adRequestBanner(bannerInfo:)"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adNoBanners(responseTime:)":{"navigatorTitle":[{"text":"adNoBannersWithResponseTime:","kind":"identifier"}],"title":"adNoBanners(responseTime:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adNoBanners(responseTime:)","role":"symbol","url":"\/documentation\/ovkit\/adstatshandler\/adnobanners(responsetime:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adNoBanners","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"abstract":[{"text":"Рекламный плеер не будет играть рекламу для данного видео.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"role":"symbol","title":"TimespentStatsHandler","type":"topic","navigatorTitle":[{"text":"TimespentStatsHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Принимает события начала и остановки просмотра видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/timespentstatshandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adFailed(reason:)":{"role":"symbol","title":"adFailed(reason:)","type":"topic","navigatorTitle":[{"text":"adFailedWithReason:","kind":"identifier"}],"abstract":[{"text":"Ошибка воспроизведения рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adFailed(reason:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adfailed(reason:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"url":"\/documentation\/ovkit\/statscollector","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Не привязан к ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true,"type":"reference"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"или переходах в PiP и fullscreen.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","title":"StatsCollector","role":"symbol","navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","title":"VideoStatsHandler","type":"topic","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"url":"\/documentation\/ovkit\/video","type":"topic","title":"Video","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adBannerProgress(_:bannerInfo:)":{"role":"symbol","abstract":[{"type":"text","text":"Пользователь досмотрел до определенных участков."}],"kind":"symbol","title":"adBannerProgress(_:bannerInfo:)","navigatorTitle":[{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StatsProgress","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adbannerprogress(_:bannerinfo:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerProgress(_:bannerInfo:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"role":"symbol","title":"StatsContext","type":"topic","navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"url":"\/documentation\/ovkit\/statscontext","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"url":"\/documentation\/ovkit\/adstatshandler","abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","title":"AdStatsHandler","role":"symbol","navigatorTitle":[{"text":"AdStatsHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKAdStatsHandler","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerProgress(_:bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerStart(bannerInfo:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adLoadRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adNoBanners(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adRequestBanner(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adSkip(bannerInfo:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"],"generated":true,"title":"Статистика"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKAdStatsHandler"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","text":"OVKStatsHandler"},{"kind":"text","text":">"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adSkip(bannerInfo:)\/title","value":"adSkipWithBannerInfo:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adSkip(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adLoadRequest()\/title","value":"adLoadRequest","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adLoadRequest()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adLoadRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerStart(bannerInfo:duration:)\/title","value":"adBannerStartWithBannerInfo:duration:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerStart(bannerInfo:duration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adRequestBanner(bannerInfo:)\/title","value":"adRequestBannerWithBannerInfo:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adRequestBanner(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adNoBanners(responseTime:)\/title","value":"adNoBannersWithResponseTime:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adNoBanners(responseTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title","value":"OVKTimespentStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKTimespentStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle","value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adFailed(reason:)\/title","value":"adFailedWithReason:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adFailed(reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adFailedWithReason:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"value":"adBannerProgress:bannerInfo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerProgress(_:bannerInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerProgress(_:bannerInfo:)\/fragments"},{"value":"OVKStatsContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","value":"OVKAdStatsHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]}]}]}