{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsBannerInfo"}],"navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"title":"AdStatsBannerInfo","roleHeading":"Class","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","symbolKind":"class","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/startSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/subtype"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/ovkit\/adstatsbannerinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatsbannerinfo"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKAdStatsBannerInfo) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdStatsBannerInfo","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/description":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/description","role":"symbol","type":"topic","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/description"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsBannerInfo"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdStatsBannerInfo"}],"kind":"symbol","url":"\/documentation\/ovkit\/adstatsbannerinfo","title":"AdStatsBannerInfo","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/id":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/id","role":"symbol","kind":"symbol","type":"topic","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/id","abstract":[{"text":"Идентификатор баннер из MTRGInstreamAdBanner","type":"text"}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/subtype":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/subtype","role":"symbol","type":"topic","kind":"symbol","title":"subtype","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"subtype","kind":"identifier"}],"abstract":[{"text":"Подтип баннера (video\/shoppable\/motion)","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/subtype"},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/name":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/name","role":"symbol","kind":"symbol","type":"topic","title":"name","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/name","abstract":[{"type":"text","text":"Тип баннера (preroll \/ midroll \/ postroll)"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKAdStatsBannerInfo/startSec":{"url":"\/documentation\/ovkit\/ovkadstatsbannerinfo\/startsec","role":"symbol","type":"topic","kind":"symbol","title":"startSec","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"startSec","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startSec"}],"abstract":[{"text":"Время начала баннера (в секундах)","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/startSec"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"OVKAdStatsBannerInfo","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/startSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKAdStatsBannerInfo\/subtype"],"title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKAdStatsBannerInfo"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"description","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1description\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo"},{"value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"value":"subtype","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1subtype\/title"},{"value":[{"kind":"identifier","text":"subtype"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1subtype\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1name\/title","value":"name","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"value":"startSec","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1startSec\/title"},{"op":"replace","value":[{"text":"startSec","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKAdStatsBannerInfo~1startSec\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}