{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","title":"AdTimelineView","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKAdTimelineView","navigatorTitle":[{"text":"AdTimelineView","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdTimelineView"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKAdTimelineView) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdTimelineView"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adtimelineview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adtimelineview"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/init(size:progressColor:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/progressColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/rounded","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/roundedProgress"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/layoutSubviews()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"text":"Таймлайн воспроизведения для рекламы.","type":"text"}],"references":{"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdTimelineView"}],"title":"AdTimelineView","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Таймлайн воспроизведения для рекламы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView","url":"\/documentation\/ovkit\/adtimelineview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdTimelineView"}]},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIView"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/rounded":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/rounded","title":"rounded","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/adtimelineview\/rounded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rounded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Флаг, определяющий визуальное скругление таймлайна по краям .","type":"text"}]},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIUtilities.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/init(size:progressColor:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/init(size:progressColor:)","title":"init(size:progressColor:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/adtimelineview\/init(size:progresscolor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progressColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Инициализатор таймлайна.","type":"text"}]},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/layoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"title":"layoutSubviews()","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/layoutSubviews()","url":"\/documentation\/ovkit\/adtimelineview\/layoutsubviews()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/progressColor":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/progressColor","abstract":[{"type":"text","text":"Цвет полосы прогресса."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"title":"progressColor","url":"\/documentation\/ovkit\/adtimelineview\/progresscolor","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AdTimelineView/roundedProgress":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/roundedProgress","title":"roundedProgress","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/adtimelineview\/roundedprogress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roundedProgress","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Флаг, определяющий визуальное скругление полосы прогресса.","type":"text"}]},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKAdTimelineView","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdTimelineView\/layoutSubviews()"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKAdTimelineView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKAdTimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAdTimelineView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView\/navigatorTitle"},{"op":"replace","value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView~1layoutSubviews()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdTimelineView~1layoutSubviews()\/fragments"}]}]}