{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKAudioCompressorParameters) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioCompressorParameters"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioCompressorParameters"}],"title":"AudioCompressorParameters","symbolKind":"class","modules":[{"name":"OVKit"}],"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)OVKAudioCompressorParameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioCompressorParameters"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/attackTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/headRoom","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/releaseTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/threshold"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/audiocompressorparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiocompressorparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/threshold":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/threshold","type":"topic","title":"threshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"threshold"}],"url":"\/documentation\/ovkit\/audiocompressorparameters\/threshold"},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/headRoom":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headRoom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/ovkit\/audiocompressorparameters\/headroom","title":"headRoom","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/headRoom","type":"topic","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"headRoom"}]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/releaseTime":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"releaseTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/ovkit\/audiocompressorparameters\/releasetime","abstract":[],"title":"releaseTime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/releaseTime","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"releaseTime","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/attackTime":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attackTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/audiocompressorparameters\/attacktime","title":"attackTime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/attackTime","type":"topic","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"attackTime","kind":"identifier"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/audiocompressorparameters\/init()","title":"init()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/init()","type":"topic","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioCompressorParameters"}],"url":"\/documentation\/ovkit\/audiocompressorparameters","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters","type":"topic","title":"AudioCompressorParameters","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioCompressorParameters"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKAudioCompressorParameters","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/attackTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/headRoom","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/releaseTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/threshold"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/init()"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKAudioCompressorParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"threshold","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1threshold\/title"},{"value":[{"kind":"identifier","text":"threshold"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1threshold\/fragments"},{"value":"headRoom","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1headRoom\/title"},{"value":[{"kind":"identifier","text":"headRoom"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1headRoom\/fragments"},{"value":"releaseTime","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1releaseTime\/title"},{"value":[{"kind":"identifier","text":"releaseTime"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1releaseTime\/fragments"},{"value":"attackTime","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1attackTime\/title"},{"value":[{"kind":"identifier","text":"attackTime"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1attackTime\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1init()\/fragments"},{"value":"OVKAudioCompressorParameters","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/title"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/fragments"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/navigatorTitle"}]}]}