{"kind":"symbol","metadata":{"symbolKind":"protocol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"AudioManager"}],"role":"symbol","title":"AudioManager","externalID":"c:@M@OVKit@objc(pl)OVKAudioManager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioManager","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"seeAlsoSections":[{"title":"Сервисы","anchor":"Сервисы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKAudioManager) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioManager","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart"],"kind":"mentions"},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Необходимо использовать в случае, если помимо видеоплееров в приложении есть другие клиенты "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" (музыкальный плеер, запись видео, звуки элементов интерфейса). Класс, реализующий "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager"},{"type":"text","text":", должен консультироваться с "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},{"type":"text","text":" для получения информации о предпочитаемой категории, опций и режима работы "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":"."}]}],"kind":"content"}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/configureWithCompletion(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/detach()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/willActivateCommandCenter()"],"generated":true}],"variants":[{"paths":["\/documentation\/ovkit\/audiomanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiomanager"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Протокол, позволяющий настраивать поведение "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" при работе плееров."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","kind":"symbol","type":"topic","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"role":"symbol","title":"PersistenceManager"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","url":"\/documentation\/ovkit\/quickstart","kind":"article","type":"topic","abstract":[{"text":"Руководство для первого подключения ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":" к проекту. Эти шаги необходимо выполнить перед началом работы.","type":"text"}],"role":"article","title":"Быстрый старт"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","url":"\/documentation\/ovkit\/playermanager","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager/detach()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detach","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"detach","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/detach()","url":"\/documentation\/ovkit\/audiomanager\/detach()","kind":"symbol","type":"topic","abstract":[{"text":"Метод вызывает ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},{"text":" при окончании проигрывания видеоплееров.","type":"text"}],"role":"symbol","title":"detach()","required":true},"doc://onevideo.OVKit/documentation/OVKit/AudioManager/willActivateCommandCenter()":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"willActivateCommandCenter"}],"url":"\/documentation\/ovkit\/audiomanager\/willactivatecommandcenter()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/willActivateCommandCenter()","title":"willActivateCommandCenter()","abstract":[{"type":"text","text":"Метод вызывается сразу перед тем, как видеоплеер установит обработчики действий на "},{"type":"codeVoice","code":"MPRemoteCommandCenter"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willActivateCommandCenter"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"navigatorTitle":[{"kind":"identifier","text":"AudioManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","url":"\/documentation\/ovkit\/audiomanager","kind":"symbol","type":"topic","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"text":" при работе плееров.","type":"text"}],"role":"symbol","title":"AudioManager"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","url":"\/documentation\/ovkit\/idletimermanager","kind":"symbol","type":"topic","abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"role":"symbol","title":"IdleTimerManager"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","kind":"symbol","type":"topic","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"role":"symbol","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager/configureWithCompletion(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureWithCompletion","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"configureWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/configureWithCompletion(_:)","url":"\/documentation\/ovkit\/audiomanager\/configurewithcompletion(_:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Метод вызывает "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","isActive":true},{"type":"text","text":" перед началом проигрывания или перед включением звука."}],"role":"symbol","title":"configureWithCompletion(_:)","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"OVKAudioManager"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAudioManager"}]},{"value":[{"kind":"identifier","text":"OVKAudioManager"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/configureWithCompletion(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/detach()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/willActivateCommandCenter()"],"generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Сервисы","title":"Сервисы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKAudioManager"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"value":"OVKPlayerManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1detach()\/title","value":"detach","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1detach()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detach"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1willActivateCommandCenter()\/title","value":"willActivateCommandCenter","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willActivateCommandCenter"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1willActivateCommandCenter()\/fragments"},{"value":"OVKAudioManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title"},{"value":[{"kind":"identifier","text":"OVKAudioManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments"},{"value":[{"kind":"identifier","text":"OVKAudioManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle"},{"value":"OVKIdleTimerManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"op":"replace","value":"configureWithCompletion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1configureWithCompletion(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"configureWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1configureWithCompletion(_:)\/fragments"}]}]}