{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType","role":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"title":"AudioOutputType"},"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/HDMI","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/airplay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/bluetooth","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/carAudio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/displayPort","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/headphones","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/lineOut","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/speaker","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/usbAudio"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKAudioOutputType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/airplay":{"navigatorTitle":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"url":"\/documentation\/ovkit\/audiooutputtype\/airplay","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/airplay","type":"topic","title":"AudioOutputType.airplay","role":"symbol","kind":"symbol","abstract":[{"text":"AirPlay-устройство.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airplay","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/carAudio":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/carAudio","kind":"symbol","type":"topic","title":"AudioOutputType.carAudio","url":"\/documentation\/ovkit\/audiooutputtype\/caraudio","abstract":[{"type":"text","text":"Динамики в машине при подключении через CarPlay."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carAudio"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeCarAudio"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/other":{"type":"topic","title":"AudioOutputType.other","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/other","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"abstract":[{"text":"Другой неизвестный выход.","type":"text"}],"navigatorTitle":[{"text":"OVKAudioOutputTypeOther","kind":"identifier"}],"url":"\/documentation\/ovkit\/audiooutputtype\/other"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/lineOut":{"kind":"symbol","abstract":[{"type":"text","text":"Линейный выход."}],"url":"\/documentation\/ovkit\/audiooutputtype\/lineout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineOut"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/lineOut","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeLineOut"}],"title":"AudioOutputType.lineOut"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/headphones":{"abstract":[{"text":"Проводные наушники или гарнитура.","type":"text"}],"title":"AudioOutputType.headphones","url":"\/documentation\/ovkit\/audiooutputtype\/headphones","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"headphones"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/headphones","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeHeadphones"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/ovkit\/audiooutputtype\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/init(rawValue:)"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/speaker":{"url":"\/documentation\/ovkit\/audiooutputtype\/speaker","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeSpeaker"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/speaker","abstract":[{"text":"Основной динамик устройства, громкоговоритель.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speaker","kind":"identifier"}],"title":"AudioOutputType.speaker"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/bluetooth":{"abstract":[{"text":"Bluetooth устройство (наушники, колонки, гарнитура).","type":"text"}],"title":"AudioOutputType.bluetooth","url":"\/documentation\/ovkit\/audiooutputtype\/bluetooth","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/bluetooth","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/displayPort":{"abstract":[{"text":"Display Port.","type":"text"}],"title":"AudioOutputType.displayPort","url":"\/documentation\/ovkit\/audiooutputtype\/displayport","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayPort"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/displayPort","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeDisplayPort"}],"kind":"symbol"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","url":"\/documentation\/ovkit\/audiooutputtype\/equatable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/ovkit\/audiooutputtype\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/HDMI":{"abstract":[{"text":"HDMI.","type":"text"}],"title":"AudioOutputType.HDMI","url":"\/documentation\/ovkit\/audiooutputtype\/hdmi","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HDMI"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/HDMI","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeHDMI"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/usbAudio":{"abstract":[{"type":"text","text":"USB Audio выход."}],"navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeUsbAudio"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/usbAudio","type":"topic","kind":"symbol","title":"AudioOutputType.usbAudio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"usbAudio"}],"role":"symbol","url":"\/documentation\/ovkit\/audiooutputtype\/usbaudio"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOutputType"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","kind":"symbol","title":"AudioOutputType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"role":"symbol","url":"\/documentation\/ovkit\/audiooutputtype"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"OVKAudioOutputType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/HDMI","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/airplay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/bluetooth","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/carAudio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/displayPort","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/headphones","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/lineOut","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/speaker","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/usbAudio"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKAudioOutputType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1airplay\/title","value":"OVKAudioOutputTypeAirplay","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1airplay\/fragments","value":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1carAudio\/title","value":"OVKAudioOutputTypeCarAudio","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1carAudio\/fragments","value":[{"text":"OVKAudioOutputTypeCarAudio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1other\/title","value":"OVKAudioOutputTypeOther","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1other\/fragments","value":[{"text":"OVKAudioOutputTypeOther","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1lineOut\/title","value":"OVKAudioOutputTypeLineOut","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1lineOut\/fragments","value":[{"text":"OVKAudioOutputTypeLineOut","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1headphones\/title","value":"OVKAudioOutputTypeHeadphones","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1headphones\/fragments","value":[{"text":"OVKAudioOutputTypeHeadphones","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1speaker\/title","value":"OVKAudioOutputTypeSpeaker","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1speaker\/fragments","value":[{"text":"OVKAudioOutputTypeSpeaker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1bluetooth\/title","value":"OVKAudioOutputTypeBluetooth","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1bluetooth\/fragments","value":[{"text":"OVKAudioOutputTypeBluetooth","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1displayPort\/title","value":"OVKAudioOutputTypeDisplayPort","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1displayPort\/fragments","value":[{"text":"OVKAudioOutputTypeDisplayPort","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1HDMI\/title","value":"OVKAudioOutputTypeHDMI","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1HDMI\/fragments","value":[{"text":"OVKAudioOutputTypeHDMI","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1usbAudio\/title","value":"OVKAudioOutputTypeUsbAudio","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1usbAudio\/fragments","value":[{"text":"OVKAudioOutputTypeUsbAudio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"}]}]}