{"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutoQualityPresetTuner","kind":"identifier"}],"role":"symbol","title":"AutoQualityPresetTuner","externalID":"c:@M@OVKit@objc(cs)OVKAutoQualityPresetTuner","modules":[{"name":"OVKit"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/init(for:wifiQualityRange:cellularQualityRange:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/enabled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/networkStatus-swift.property"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/add(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/remove(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/update(wifiQualityRange:cellularQualityRange:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKAutoQualityPresetTuner) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoQualityPresetTuner","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Сразу после создания "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","isActive":true,"type":"reference"},{"type":"text","text":" не начинает мониторинг типа сети, для этого нужно вызывать метод "},{"type":"codeVoice","code":"start()"},{"text":". Далее механизм реагирует на изменение типа сети на устройстве и изменяет параметр ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange"},{"type":"text","text":" у плееров из списка отслеживания. Для первого запуска плеера нужный "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange"},{"type":"text","text":" необходимо установить самостоятельно."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"При добавлении нового "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":" в список для отслеживания методом "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/add(_:)"},{"type":"text","text":", обновленный "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"type":"text","text":" применится к нему только при следующем изменении типа сети."}]},{"inlineContent":[{"text":"При деинициализации ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"},{"type":"text","text":" слежение за типом сети прекращается."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/autoqualitypresettuner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/autoqualitypresettuner"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/update(wifiQualityRange:cellularQualityRange:)":{"navigatorTitle":[{"kind":"identifier","text":"updateWifiQualityRange:cellularQualityRange:"}],"title":"update(wifiQualityRange:cellularQualityRange:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"text":"wifiQualityRange","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellularQualityRange"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ovkit\/autoqualitypresettuner\/update(wifiqualityrange:cellularqualityrange:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/update(wifiQualityRange:cellularQualityRange:)","type":"topic"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/NetworkStatus-swift.enum":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Статусы доступности сети."}],"title":"AutoQualityPresetTuner.NetworkStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NetworkStatus","kind":"identifier"}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.enum","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/NetworkStatus-swift.enum","navigatorTitle":[{"text":"NetworkStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/networkStatus-swift.property":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkStatus"},{"kind":"text","text":": "},{"text":"NetworkStatus","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22AutoQualityPresetTunerC13NetworkStatusO"}],"navigatorTitle":[{"kind":"identifier","text":"networkStatus"}],"type":"topic","title":"networkStatus","url":"\/documentation\/ovkit\/autoqualitypresettuner\/networkstatus-swift.property","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/networkStatus-swift.property"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/autoQualityRange":{"kind":"symbol","abstract":[{"text":"Диапазон, в котором плеер будет играть, если выбрано автоматическое качество.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/autoqualityrange","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoQualityRange"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange","navigatorTitle":[{"text":"autoQualityRange","kind":"identifier"}],"type":"topic","role":"symbol","title":"autoQualityRange"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner":{"url":"\/documentation\/ovkit\/autoqualitypresettuner","kind":"symbol","title":"AutoQualityPresetTuner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","abstract":[{"text":"Помогает автоматически менять диапазон авто качества, если обнаружено изменение типа сети.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoQualityPresetTuner"}],"navigatorTitle":[{"kind":"identifier","text":"AutoQualityPresetTuner"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"type":"topic","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"url":"\/documentation\/ovkit\/qualityrange","title":"QualityRange","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"abstract":[],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/remove(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Удаление плеера из списка для автоматического переключения."}],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/remove(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/remove(_:)","navigatorTitle":[{"kind":"identifier","text":"remove:"}],"type":"topic","role":"symbol","title":"remove(_:)"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/add(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addPlayerView:"}],"title":"add(_:)","abstract":[{"type":"text","text":"Добавление плеера в список для автоматического переключения."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/autoqualitypresettuner\/add(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/add(_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/init(for:wifiQualityRange:cellularQualityRange:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"wifiQualityRange"},{"text":": ","kind":"text"},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellularQualityRange","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Создает ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/init(for:wifiQualityRange:cellularQualityRange:)","title":"init(for:wifiQualityRange:cellularQualityRange:)","url":"\/documentation\/ovkit\/autoqualitypresettuner\/init(for:wifiqualityrange:cellularqualityrange:)"},"doc://onevideo.OVKit/documentation/OVKit/AutoQualityPresetTuner/enabled":{"kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/autoqualitypresettuner\/enabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/enabled","navigatorTitle":[{"text":"enabled","kind":"identifier"}],"type":"topic","role":"symbol","title":"enabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKAutoQualityPresetTuner"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/enabled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/networkStatus-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/add(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/init(for:wifiQualityRange:cellularQualityRange:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/remove(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AutoQualityPresetTuner\/update(wifiQualityRange:cellularQualityRange:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"OVKAutoQualityPresetTuner","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"updateWifiQualityRange:cellularQualityRange:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1update(wifiQualityRange:cellularQualityRange:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateWifiQualityRange:cellularQualityRange:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1update(wifiQualityRange:cellularQualityRange:)\/fragments"},{"value":"networkStatus","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1networkStatus-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1networkStatus-swift.property\/fragments","value":[{"kind":"identifier","text":"networkStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/title","value":"autoQualityRange"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/fragments","value":[{"kind":"identifier","text":"autoQualityRange"}],"op":"replace"},{"value":"OVKAutoQualityPresetTuner","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/fragments","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner\/navigatorTitle","value":[{"text":"OVKAutoQualityPresetTuner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","op":"replace","value":"OVKQualityRange"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKQualityRange"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","value":"remove:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1remove(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1remove(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remove:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1add(_:)\/title","value":"addPlayerView:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addPlayerView:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1init(for:wifiQualityRange:cellularQualityRange:)\/title","value":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPlayerViews:wifiQualityRange:cellularQualityRange:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1init(for:wifiQualityRange:cellularQualityRange:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1enabled\/title","value":"enabled"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AutoQualityPresetTuner~1enabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"enabled"}]}]}]}