{"variants":[{"paths":["\/documentation\/ovkit\/backgroundplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/backgroundplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"text":"Чтобы включить возможность воспроизведения видео в фоне, необходимо выполнить следующие условия:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Приложение должно поддерживать "},{"type":"codeVoice","code":"Background mode"},{"type":"text","text":" для воспроизведения музыки в фоне."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","isActive":true,"type":"reference"},{"text":" должен быть включен.","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","type":"reference","isActive":true},{"text":" должен иметь значение ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","type":"reference","isActive":true},{"text":" или ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudioAndVideo","type":"reference","isActive":true},{"text":" на соответствующем ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"Во время проигрывания такого ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в системе появятся контролы медиацентра (","type":"text"},{"code":"MPRemoteCommandCenter","type":"codeVoice"},{"text":"), а при сворачивании приложения звук продолжит играть.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Поддерживается возможность изменить состояние ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","isActive":true,"type":"reference"},{"text":" во время воспроизведения видео. А при переходах с одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" на другой (с использованием ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","isActive":true,"type":"reference"},{"text":") новое значение опции ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","isActive":true,"type":"reference"},{"text":" автоматически применится в конце перехода.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"Фоновое воспроизведение может быть недоступно из-за параметров отдельно взятого видео.","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"},{"inlineContent":[{"text":"При воспроизведении в свернутом режиме только звука (","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","isActive":true,"type":"reference"},{"text":") видеодорожка не загружается. Из-за этого при разворачивании приложения некоторое время картинка может быть статичной – в это время происходит загрузка видеодорожки.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Article","role":"article","title":"Воспроизведение в фоне","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"seeAlsoSections":[{"title":"Концепты","anchor":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/continueAudioAndVideo":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudioAndVideo","navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAudioAndVideo"}],"title":"BackgroundPlaybackPolicy.continueAudioAndVideo","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudioandvideo","abstract":[{"type":"text","text":"Продолжение проигрывания видео в Picture in picture (если доступно), либо только аудио."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"title":"Статистика","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","role":"article","url":"\/documentation\/ovkit\/statistics","kind":"article","abstract":[{"text":"Сбор статистики воспроизведения видео.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"title":"Контролы плеера","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","role":"article","url":"\/documentation\/ovkit\/controls","kind":"article","abstract":[{"type":"text","text":"Кастомизация внешнего вида плеера."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"kind":"article","url":"\/documentation\/ovkit\/extras","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","abstract":[{"type":"text","text":"Дополнительные возможности."}],"title":"Разное","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"title":"Переходы между плеерами","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","role":"article","url":"\/documentation\/ovkit\/transitions","kind":"article","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" в другой.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"title":"Полноэкранный режим","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","role":"article","url":"\/documentation\/ovkit\/fullscreen","kind":"article","abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"kind":"article","url":"\/documentation\/ovkit\/plugins","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","abstract":[{"type":"text","text":"Динамически подключаемые модули для расширения функциональности."}],"title":"Плагины","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"title":"createAnimatedTransition(to:in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","role":"symbol","url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnimatedTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/continueAudio":{"role":"symbol","abstract":[{"text":"Продолжение проигрывания аудио.","type":"text"}],"kind":"symbol","title":"BackgroundPlaybackPolicy.continueAudio","navigatorTitle":[{"text":"OVKBackgroundPlaybackPolicyContinueAudio","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAudio"}],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudio","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/allowsBackgroundPlayback":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","title":"allowsBackgroundPlayback","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"allowsBackgroundPlayback","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/environment\/allowsbackgroundplayback","abstract":[{"text":"Разрешить ли воспроизведение видео в фоне.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/backgroundPlaybackPolicy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","url":"\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundPlaybackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BackgroundPlaybackPolicy","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"backgroundPlaybackPolicy","kind":"identifier"}],"kind":"symbol","title":"backgroundPlaybackPolicy","role":"symbol","abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"title":"Префетчер","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","role":"article","url":"\/documentation\/ovkit\/prefetch","kind":"article","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"anchor":"Концепты"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudioAndVideo\/title","value":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudioAndVideo\/fragments","value":[{"text":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","value":"createAnimatedTransitionTo:in:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/title","value":"OVKBackgroundPlaybackPolicyContinueAudio"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/fragments","value":[{"text":"OVKBackgroundPlaybackPolicyContinueAudio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/title","value":"allowsBackgroundPlayback"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/fragments","value":[{"text":"allowsBackgroundPlayback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/title","value":"backgroundPlaybackPolicy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/fragments","value":[{"text":"backgroundPlaybackPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}]}]}