{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships","type":"conformsTo"}],"sections":[],"abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKBackgroundPlaybackPolicy) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/backgroundplaybackpolicy"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"title":"BackgroundPlaybackPolicy","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BackgroundPlaybackPolicy","kind":"identifier"}],"symbolKind":"enum"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudioAndVideo","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/continueAudio":{"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudio","abstract":[{"text":"Продолжение проигрывания аудио.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueAudio","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","title":"BackgroundPlaybackPolicy.continueAudio"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/RawRepresentable-Implementations":{"type":"topic","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/rawrepresentable-implementations","role":"collectionGroup","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/continueAudioAndVideo":{"kind":"symbol","title":"BackgroundPlaybackPolicy.continueAudioAndVideo","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"continueAudioAndVideo"}],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/continueaudioandvideo","abstract":[{"type":"text","text":"Продолжение проигрывания видео в Picture in picture (если доступно), либо только аудио."}],"navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudioAndVideo"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/init(rawValue:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/init(rawvalue:)"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/Equatable-Implementations","role":"collectionGroup","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/pause":{"type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/pause","abstract":[{"text":"Приостановка воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"BackgroundPlaybackPolicy.pause","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause","navigatorTitle":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy","title":"BackgroundPlaybackPolicy","navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"OVKBackgroundPlaybackPolicy","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/continueAudioAndVideo","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/title","value":"OVKBackgroundPlaybackPolicyContinueAudio","op":"replace"},{"op":"replace","value":[{"text":"OVKBackgroundPlaybackPolicyContinueAudio","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudioAndVideo\/title","value":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1continueAudioAndVideo\/fragments","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyContinueAudioAndVideo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/title","op":"replace","value":"OVKBackgroundPlaybackPolicyPause"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/fragments","op":"replace","value":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}]},{"value":"OVKBackgroundPlaybackPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}