{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKBroadcastManager) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BroadcastManager","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/broadcastmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/broadcastmanager"]}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/broadcastProviders","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/currentDevice","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/discoveryInProgress","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/externalPlayer"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/addListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/configure(providers:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/connectToDiscoveredDevice(_:isAirPlay:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/disconnectFromCurrentDevice()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/removeListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/startDiscovery()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/stopDiscovery()"],"generated":true},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/shared"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastManager"}],"roleHeading":"Class","title":"BroadcastManager","externalID":"c:@M@OVKit@objc(cs)OVKBroadcastManager","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"BroadcastManager"}],"symbolKind":"class"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastManager"}],"abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","url":"\/documentation\/ovkit\/broadcastmanager","kind":"symbol","title":"BroadcastManager","navigatorTitle":[{"kind":"identifier","text":"BroadcastManager"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/externalPlayer":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalPlayer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit15BroadcastPlayerP","kind":"typeIdentifier","text":"BroadcastPlayer"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/externalPlayer","abstract":[],"url":"\/documentation\/ovkit\/broadcastmanager\/externalplayer","title":"externalPlayer","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/addListener(_:)":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/broadcastmanager\/addlistener(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/addListener(_:)","title":"addListener(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit24BroadcastManagerListenerP","text":"BroadcastManagerListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/currentDevice":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BroadcastDevice","preciseIdentifier":"s:5OVKit15BroadcastDeviceP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/currentDevice","url":"\/documentation\/ovkit\/broadcastmanager\/currentdevice","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"currentDevice"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/configure(providers:)":{"navigatorTitle":[{"kind":"identifier","text":"configureWithProviders:"}],"title":"configure(providers:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/configure(providers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"providers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s9AnyObjecta","kind":"typeIdentifier","text":"AnyObject"},{"kind":"text","text":"])"}],"url":"\/documentation\/ovkit\/broadcastmanager\/configure(providers:)"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/removeListener(_:)":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/removeListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BroadcastManagerListener","preciseIdentifier":"s:5OVKit24BroadcastManagerListenerP"},{"kind":"text","text":")"}],"title":"removeListener(_:)","type":"topic","url":"\/documentation\/ovkit\/broadcastmanager\/removelistener(_:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/discoveryInProgress":{"title":"discoveryInProgress","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/discoveryInProgress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoveryInProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/broadcastmanager\/discoveryinprogress"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/broadcastProviders":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"broadcastProviders","kind":"identifier"},{"text":": [","kind":"text"},{"text":"BroadcastServiceProvider","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24BroadcastServiceProviderP"},{"text":"]","kind":"text"}],"title":"broadcastProviders","url":"\/documentation\/ovkit\/broadcastmanager\/broadcastproviders","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/broadcastProviders"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/stopDiscovery()":{"title":"stopDiscovery()","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/stopDiscovery()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopDiscovery","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/broadcastmanager\/stopdiscovery()"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/disconnectFromCurrentDevice()":{"navigatorTitle":[{"kind":"identifier","text":"disconnectFromCurrentDevice"}],"title":"disconnectFromCurrentDevice()","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/disconnectFromCurrentDevice()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnectFromCurrentDevice"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/broadcastmanager\/disconnectfromcurrentdevice()"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/startDiscovery()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDiscovery","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startDiscovery()","url":"\/documentation\/ovkit\/broadcastmanager\/startdiscovery()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Запускает поиск устройств без подписки на обновления.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/startDiscovery()"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/shared":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBroadcastManager","text":"BroadcastManager"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/shared","url":"\/documentation\/ovkit\/broadcastmanager\/shared","kind":"symbol","title":"shared","navigatorTitle":[{"kind":"identifier","text":"shared"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/connectToDiscoveredDevice(_:isAirPlay:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectToDiscoveredDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BroadcastDevice","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit15BroadcastDeviceP"},{"text":", ","kind":"text"},{"text":"isAirPlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/connectToDiscoveredDevice(_:isAirPlay:)","url":"\/documentation\/ovkit\/broadcastmanager\/connecttodiscovereddevice(_:isairplay:)","kind":"symbol","title":"connectToDiscoveredDevice(_:isAirPlay:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKBroadcastManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/configure(providers:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/disconnectFromCurrentDevice()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/shared"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKBroadcastManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1configure(providers:)\/title","value":"configureWithProviders:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1configure(providers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"configureWithProviders:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1disconnectFromCurrentDevice()\/title","value":"disconnectFromCurrentDevice"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1disconnectFromCurrentDevice()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disconnectFromCurrentDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]}]}]}