{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/buffersettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/buffersettings"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings"},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Class","title":"BufferSettings","externalID":"c:@M@OVKit@objc(cs)OVKBufferSettings","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"BufferSettings"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferSettings"}]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxBufferSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxDurationForQualityDecrease","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/minDurationForQualityIncrease"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKBufferSettings) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BufferSettings","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/maxDurationForQualityDecrease":{"url":"\/documentation\/ovkit\/buffersettings\/maxdurationforqualitydecrease","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDurationForQualityDecrease"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxDurationForQualityDecrease","title":"maxDurationForQualityDecrease","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxDurationForQualityDecrease"}]},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings":{"title":"BufferSettings","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BufferSettings"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BufferSettings"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings","role":"symbol","url":"\/documentation\/ovkit\/buffersettings","type":"topic"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)":{"title":"init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxBufferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"minDurationForQualityIncrease","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"maxDurationForQualityDecrease","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)","role":"symbol","url":"\/documentation\/ovkit\/buffersettings\/init(maxbuffersize:mindurationforqualityincrease:maxdurationforqualitydecrease:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/minDurationForQualityIncrease":{"type":"topic","title":"minDurationForQualityIncrease","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/minDurationForQualityIncrease","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minDurationForQualityIncrease"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minDurationForQualityIncrease"}],"url":"\/documentation\/ovkit\/buffersettings\/mindurationforqualityincrease","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BufferSettings/maxBufferSize":{"kind":"symbol","role":"symbol","title":"maxBufferSize","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxBufferSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"maxBufferSize","kind":"identifier"}],"url":"\/documentation\/ovkit\/buffersettings\/maxbuffersize","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxBufferSize","type":"topic"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"OVKBufferSettings"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKBufferSettings","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKBufferSettings"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxBufferSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/maxDurationForQualityDecrease","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/minDurationForQualityIncrease"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BufferSettings\/init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKBufferSettings","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxDurationForQualityDecrease\/title","op":"replace","value":"maxDurationForQualityDecrease"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxDurationForQualityDecrease\/fragments","op":"replace","value":[{"text":"maxDurationForQualityDecrease","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/title","op":"replace","value":"OVKBufferSettings"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/fragments","op":"replace","value":[{"text":"OVKBufferSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKBufferSettings"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)\/title","op":"replace","value":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1init(maxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxBufferSize:minDurationForQualityIncrease:maxDurationForQualityDecrease:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1minDurationForQualityIncrease\/title","op":"replace","value":"minDurationForQualityIncrease"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1minDurationForQualityIncrease\/fragments","op":"replace","value":[{"kind":"identifier","text":"minDurationForQualityIncrease"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxBufferSize\/title","op":"replace","value":"maxBufferSize"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BufferSettings~1maxBufferSize\/fragments","op":"replace","value":[{"text":"maxBufferSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}