{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKBugReportDiagnosticsData) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BugReportDiagnosticsData","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata"]},{"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BugReportDiagnosticsData"}],"modules":[{"name":"OVKit"}],"title":"BugReportDiagnosticsData","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData","role":"symbol","navigatorTitle":[{"text":"BugReportDiagnosticsData","kind":"identifier"}]},"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/isSensitive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vpn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vsid"],"generated":true}],"abstract":[{"type":"text","text":"Описание состояния плеера для диагностики."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"references":{"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/vpn":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vpn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"text":"vpn","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Активен ли в данный момент VPN на устройстве."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vpn","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/vpn","title":"vpn"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/isSensitive":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSensitive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSensitive"}],"type":"topic","abstract":[{"type":"text","text":"Является ли информация в "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","isActive":true},{"type":"text","text":" приватной."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/isSensitive","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/issensitive","title":"isSensitive"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/playerState":{"title":"playerState","abstract":[{"type":"text","text":"Строка с описанием состояния плеера. Может содержать переносы строки."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","navigatorTitle":[{"text":"playerState","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/playerstate","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/vsid":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vsid","type":"topic","title":"vsid","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"vsid","kind":"identifier"}],"url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/vsid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vsid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Текущий VSID."}]},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","type":"topic","title":"BugReportDiagnosticsData","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BugReportDiagnosticsData","kind":"identifier"}],"url":"\/documentation\/ovkit\/bugreportdiagnosticsdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BugReportDiagnosticsData","kind":"identifier"}],"abstract":[{"type":"text","text":"Описание состояния плеера для диагностики."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"OVKBugReportDiagnosticsData","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/isSensitive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vpn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vsid"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKBugReportDiagnosticsData","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vpn\/title","value":"vpn","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vpn\/fragments","value":[{"text":"vpn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1isSensitive\/title","value":"isSensitive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1isSensitive\/fragments","value":[{"text":"isSensitive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1playerState\/title","value":"playerState","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1playerState\/fragments","value":[{"text":"playerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vsid\/title","value":"vsid","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vsid\/fragments","value":[{"text":"vsid","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/title","value":"OVKBugReportDiagnosticsData","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/fragments","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/navigatorTitle","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"op":"replace"}]}]}