{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKCacheContainer) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainer"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/init(customIdentifier:config:)"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/cacheSize()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/clearCache()"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/cachecontainer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cachecontainer"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKCacheContainer","title":"CacheContainer","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"CacheContainer"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainer"}],"symbolKind":"class"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainer/clearCache()":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearCache","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/clearCache()","abstract":[],"title":"clearCache()","url":"\/documentation\/ovkit\/cachecontainer\/clearcache()","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"type":"topic"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"url":"\/documentation\/ovkit\/cachecontainer","type":"topic","title":"CacheContainer","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainer","kind":"identifier"}],"navigatorTitle":[{"text":"CacheContainer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer/cacheSize()":{"kind":"symbol","title":"cacheSize()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/cacheSize()","abstract":[],"url":"\/documentation\/ovkit\/cachecontainer\/cachesize()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheSize"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheSize"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer/init(customIdentifier:config:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/init(customIdentifier:config:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/cachecontainer\/init(customidentifier:config:)","navigatorTitle":[{"text":"initWithCustomIdentifier:config:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"customIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CacheContainerConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Инициализирует экземпляр класса "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","type":"reference","isActive":true},{"type":"text","text":" с заданным идентификатором. Может возвращать "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", если поддержка контейнеров не включена на уровне SDK или использован некорректный идентификатор."}],"title":"init(customIdentifier:config:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKCacheContainer","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/cacheSize()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/clearCache()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/init(customIdentifier:config:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKCacheContainer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clearCache","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1clearCache()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"clearCache","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1clearCache()\/fragments","op":"replace"},{"value":"OVKCacheContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title","op":"replace"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments","op":"replace"},{"value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle","op":"replace"},{"value":"cacheSize","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1cacheSize()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cacheSize","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1cacheSize()\/fragments","op":"replace"},{"value":"initWithCustomIdentifier:config:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1init(customIdentifier:config:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCustomIdentifier:config:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1init(customIdentifier:config:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}