{"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKCacheContainerConfig) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cachecontainerconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cachecontainerconfig"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/init(autoTrimInterval:costLimit:ageLimit:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/ageLimit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/autoTrimInterval","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/costLimit"],"title":"Instance Properties","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/defaultConfig()"],"title":"Type Methods","generated":true}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}],"roleHeading":"Class","title":"CacheContainerConfig","externalID":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"CacheContainerConfig","kind":"identifier"}],"symbolKind":"class"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/ageLimit":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ageLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"ageLimit","url":"\/documentation\/ovkit\/cachecontainerconfig\/agelimit","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ageLimit","kind":"identifier"}],"abstract":[{"text":"Максимальное время жизни объектов в кэше. Значение по умолчанию - 314572800 (8 часов).","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/ageLimit"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/costLimit":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"costLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"costLimit","url":"\/documentation\/ovkit\/cachecontainerconfig\/costlimit","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"costLimit","kind":"identifier"}],"abstract":[{"text":"Максимальный размер кэша, после достижения которого он начнет удалять старые объекты. Значение по умолчанию - 314572800 (300 Mb).","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/costLimit"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheContainerConfig"}],"navigatorTitle":[{"kind":"identifier","text":"CacheContainerConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","url":"\/documentation\/ovkit\/cachecontainerconfig","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"CacheContainerConfig"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/autoTrimInterval":{"navigatorTitle":[{"kind":"identifier","text":"autoTrimInterval"}],"title":"autoTrimInterval","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Интервал автоматической очистки. Значение по умолчанию - 900 (15 минут)."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/autoTrimInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoTrimInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"url":"\/documentation\/ovkit\/cachecontainerconfig\/autotriminterval"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/init(autoTrimInterval:costLimit:ageLimit:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"autoTrimInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"costLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"ageLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"title":"init(autoTrimInterval:costLimit:ageLimit:)","url":"\/documentation\/ovkit\/cachecontainerconfig\/init(autotriminterval:costlimit:agelimit:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithAutoTrimInterval:costLimit:ageLimit:","kind":"identifier"}],"abstract":[{"text":"Инициализирует экземпляр класса ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","isActive":true,"type":"reference"},{"text":" с заданным настройками.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/init(autoTrimInterval:costLimit:ageLimit:)"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig/defaultConfig()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","kind":"typeIdentifier","text":"CacheContainerConfig"}],"title":"defaultConfig()","url":"\/documentation\/ovkit\/cachecontainerconfig\/defaultconfig()","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultConfig"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/defaultConfig()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKCacheContainerConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKCacheContainerConfig","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKCacheContainerConfig","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/ageLimit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/autoTrimInterval","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/costLimit"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/init(autoTrimInterval:costLimit:ageLimit:)"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig\/defaultConfig()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKCacheContainerConfig","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1ageLimit\/title","value":"ageLimit"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1ageLimit\/fragments","value":[{"text":"ageLimit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1costLimit\/title","value":"costLimit"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1costLimit\/fragments","value":[{"text":"costLimit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title","value":"OVKCacheContainerConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments","value":[{"text":"OVKCacheContainerConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle","value":[{"text":"OVKCacheContainerConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1autoTrimInterval\/title","value":"autoTrimInterval"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1autoTrimInterval\/fragments","value":[{"text":"autoTrimInterval","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1init(autoTrimInterval:costLimit:ageLimit:)\/title","value":"initWithAutoTrimInterval:costLimit:ageLimit:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1init(autoTrimInterval:costLimit:ageLimit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAutoTrimInterval:costLimit:ageLimit:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1defaultConfig()\/title","value":"defaultConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig~1defaultConfig()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultConfig","kind":"identifier"}]}]}]}