{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/currentChapter","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/playerTime"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/foundChapterForSeekTime(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKChapterProvider) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider","role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"title":"ChapterProvider","roleHeading":"Class","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/chapterprovider"]},{"paths":["\/documentation\/ovkit\/chapterprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Отвечает за разбивку видео на эпизоды по таймкодам.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/chapters":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"chapters","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Список всех эпизодов в видео. Отсортирован по времени начала эпизода."}],"title":"chapters","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/chapters","url":"\/documentation\/ovkit\/chapterprovider\/chapters","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"chapters","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier","text":"VideoChapterType"},{"text":"]","kind":"text"}]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/foundChapterForSeekTime(_:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"foundChapterForSeekTime(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/foundChapterForSeekTime(_:)","url":"\/documentation\/ovkit\/chapterprovider\/foundchapterforseektime(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"foundChapterForSeekTime"},{"text":"(","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier","text":"VideoChapterType"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/currentChapter":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentChapter"}],"type":"topic","abstract":[{"type":"text","text":"Эпизод, который воспроизводится плеером в данный момент. Свойство поддерживает KVO."}],"title":"currentChapter","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/currentChapter","url":"\/documentation\/ovkit\/chapterprovider\/currentchapter","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentChapter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider/playerTime":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerTime"}],"type":"topic","abstract":[{"type":"text","text":"Время, для которого происходит поиск эпизода."}],"title":"playerTime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/playerTime","url":"\/documentation\/ovkit\/chapterprovider\/playertime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"type":"topic","title":"ChapterProvider","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/chapterprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"OVKChapterProvider","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"OVKChapterProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/currentChapter","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider\/playerTime"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKChapterProvider"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1chapters\/title","value":"chapters"},{"value":[{"text":"chapters","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1chapters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1currentChapter\/title","value":"currentChapter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1currentChapter\/fragments","value":[{"kind":"identifier","text":"currentChapter"}]},{"value":"playerTime","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1playerTime\/title"},{"op":"replace","value":[{"text":"playerTime","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider~1playerTime\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace","value":"OVKChapterProvider"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}