{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVCmafTimeLineVersion) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTimeLineVersion","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/cmaftimelineversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cmaftimelineversion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v5"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@E@OVCmafTimeLineVersion","title":"CmafTimeLineVersion","navigatorTitle":[{"kind":"identifier","text":"CmafTimeLineVersion"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTimeLineVersion"}],"modules":[{"name":"OVKit"}],"symbolKind":"enum","roleHeading":"Enumeration"},"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/RawRepresentable-Implementations":{"url":"\/documentation\/ovkit\/cmaftimelineversion\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/RawRepresentable-Implementations","kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/unknown":{"title":"CmafTimeLineVersion.unknown","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","url":"\/documentation\/ovkit\/cmaftimelineversion\/unknown","navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionUnknown"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/unknown"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/Equatable-Implementations":{"url":"\/documentation\/ovkit\/cmaftimelineversion\/equatable-implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","title":"Equatable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/v5":{"url":"\/documentation\/ovkit\/cmaftimelineversion\/v5","navigatorTitle":[{"kind":"identifier","text":"OVCmafTimeLineVersionV5"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v5","abstract":[],"title":"CmafTimeLineVersion.v5","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v5"}],"kind":"symbol"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTimeLineVersion"}],"type":"topic","url":"\/documentation\/ovkit\/cmaftimelineversion","navigatorTitle":[{"kind":"identifier","text":"CmafTimeLineVersion"}],"title":"CmafTimeLineVersion"},"doc://onevideo.OVKit/documentation/OVKit/CmafTimeLineVersion/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/init(rawValue:)","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/cmaftimelineversion\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"OVCmafTimeLineVersion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTimeLineVersion\/v5"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVCmafTimeLineVersion"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"OVCmafTimeLineVersionUnknown","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1unknown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVCmafTimeLineVersionUnknown"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1unknown\/fragments","op":"replace"},{"value":"OVCmafTimeLineVersionV5","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v5\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVCmafTimeLineVersionV5"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion~1v5\/fragments","op":"replace"},{"value":"OVCmafTimeLineVersion","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/title","op":"replace"},{"value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/fragments","op":"replace"},{"value":[{"text":"OVCmafTimeLineVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTimeLineVersion\/navigatorTitle","op":"replace"}]}]}