{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVCmafTrackReaderVersion) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@OVKit@E@OVCmafTrackReaderVersion","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"title":"CmafTrackReaderVersion","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CmafTrackReaderVersion","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cmaftrackreaderversion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cmaftrackreaderversion"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v3"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/unknown":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionUnknown"}],"title":"CmafTrackReaderVersion.unknown","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/unknown","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion\/unknown"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/init(rawValue:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/init(rawValue:)","type":"topic","url":"\/documentation\/ovkit\/cmaftrackreaderversion\/init(rawvalue:)","title":"init(rawValue:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion":{"title":"CmafTrackReaderVersion","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion","navigatorTitle":[{"kind":"identifier","text":"CmafTrackReaderVersion"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CmafTrackReaderVersion"}]},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/v3":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"v3"}],"title":"CmafTrackReaderVersion.v3","abstract":[],"url":"\/documentation\/ovkit\/cmaftrackreaderversion\/v3","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v3","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVCmafTrackReaderVersionV3"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","url":"\/documentation\/ovkit\/cmaftrackreaderversion\/equatable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/Equatable-Implementations","kind":"article"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/CmafTrackReaderVersion/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/ovkit\/cmaftrackreaderversion\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/RawRepresentable-Implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"OVCmafTrackReaderVersion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersion"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CmafTrackReaderVersion\/v3"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVCmafTrackReaderVersion"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1unknown\/title","value":"OVCmafTrackReaderVersionUnknown","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1unknown\/fragments","value":[{"text":"OVCmafTrackReaderVersionUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/title","value":"OVCmafTrackReaderVersion","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/fragments","value":[{"text":"OVCmafTrackReaderVersion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion\/navigatorTitle","value":[{"kind":"identifier","text":"OVCmafTrackReaderVersion"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v3\/title","value":"OVCmafTrackReaderVersionV3","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CmafTrackReaderVersion~1v3\/fragments","value":[{"text":"OVCmafTrackReaderVersionV3","kind":"identifier"}],"op":"replace"}]}]}