{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Кастомизация внешнего вида плеера."}],"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Контролы – это элементы управления воспроизведением в плеере. Например: кнопка плей\/пауза, таймлайн для перемотки, кнопка стриминга на внешнее устройство, и т.д. OVKit дает возможность создавать полностью свои контролы или собирать их из готовых UI-компонентов модуля "},{"type":"codeVoice","code":"OVKitUIComponents"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Контролы представляют из себя ","type":"text"},{"code":"UIView","type":"codeVoice"},{"type":"text","text":", соответствующее протоколу "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"reference","isActive":true},{"type":"text","text":". Внутри него можно добавлять любые необходимые UI элементы, но есть ряд правил, которые необходимо соблюдать:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Нельзя изменять параметры самой view контролов (в особенности ","type":"text"},{"type":"codeVoice","code":"isHidden"},{"text":", ","type":"text"},{"type":"codeVoice","code":"alpha"},{"text":", ","type":"text"},{"type":"codeVoice","code":"frame"},{"text":")","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Нельзя трогать view-иерархию на уровне контролов и выше (то есть нельзя посылать контролам ","type":"text"},{"type":"codeVoice","code":"removeFromSuperview"},{"text":")","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Контролы должны всегда отражать текущее состояние своей контрольной маски","type":"text"}],"type":"paragraph"}]}]},{"type":"aside","content":[{"inlineContent":[{"text":"При создании своей ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" контролов необходимо разместить на ней логотип, который находится в библиотеке ресурсов ","type":"text"},{"type":"codeVoice","code":"OVKResources"},{"text":": ","type":"text"},{"type":"codeVoice","code":"UIImage.ovk_vkLogo24"}],"type":"paragraph"}],"style":"important","name":"Important"},{"type":"paragraph","inlineContent":[{"text":"Контролы для обычных ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" устанавливаются один раз при инициализации. Контролы для внутреннего Picture in Picture определяются в методе ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","isActive":true,"type":"reference"},{"text":". Для полноэкранного режима – в методе ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","isActive":true,"type":"reference"},{"text":", они должны реализовывать протокол ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"anchor":"%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-UI","level":3,"type":"heading","text":"Обновление UI"},{"inlineContent":[{"text":"Главным элементом для описания визуального состояния контролов является ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","type":"reference","isActive":true},{"text":" (контрольная маска или просто маска). Она состоит из набора контролов. Наличие контрола в маске означает, что в данный момент плеер имеет возможность совершить это действие, либо что плеер в данный момент имеет определенное состояние. Также у контролов могут быть дополнительные значения. Пример контролов:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Наличие контрола "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/sound","isActive":true},{"type":"text","text":" означает саму возможность включать\/отключать звук в плеере – значит можно показывать кнопку mute. Текущее состояние звука (включен\/выключен) будет описано уже в значении контрола. Если воспроизводится видео, которое не имеет звука, то этого контрола в маске не будет и кнопку mute показывать не нужно."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Наличие контрола ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/live"},{"text":" означает, что плеер в данный момент воспроизводит прямую трансляцию.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Наличие контрола ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/fullscreen","isActive":true,"type":"reference"},{"text":" означает, что данному плееру разрешено перейти в полноэкранный режим. В этом случае можно показать кнопку разворота в полноэкранный режим.","type":"text"}]}]}]},{"inlineContent":[{"type":"text","text":"Когда внутренее состояние плеера меняется, он обновляет маску у контролов. Поэтому нужно следить за этими изменениями и изменять UI соответственно им. Значение "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" контрольной маски означает, что плеер находится в остановленном состоянии. В этом случае рекомендуется скрывать все UI элементы."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Хорошей практикой является декларативное описание UI контролов, когда видимость и состояние каждого компонента (кнопка, таймлайн) обновляется при каждом изменении маски и каких-то внешних факторов.","type":"text"}]}],"type":"aside","style":"note","name":"Note"},{"inlineContent":[{"type":"text","text":"Настройка UI простейших контролов может выглядеть следующим образом:"}],"type":"paragraph"},{"code":["var controlMask: ControlMask? {","    didSet {","        guard let mask = controlMask else {","            \/\/ Скрываем все контролы в остановленном состоянии","            playPauseButton.isHidden = true","            timelineView.isHidden = true","            soundButton.isHidden = true","            return","        }","        ","        \/\/ Настройка отображения кнопки play\/pause","        if let pause = mask.getControl(.pause), case .pause(let paused) = pause {","            playPauseButton.appearance = paused ? .play : .pause","            playPauseButton.isHidden = false","        } else {","            playPauseButton.isHidden = true","        }","        ","        \/\/ Настройка отображения таймлайна","        if let timelineValues = mask.timelineValues, timelineValues.duration > 0 {","            timelineView.update(progress: timelineValues.currentTime, duration: timelineValues.duration)","            timelineView.isHidden = false","        } else {","            timelineView.isHidden = true","        }","        ","        \/\/ Настройка отображения кнопки mute","        if let sound = mask.getControl(.sound), case .sound(let enabled, _) = sound {","            soundButton.appearance = enabled ? .soundOn : .soundOff","            soundButton.isHidden = false","        } else {","            soundButton.isHidden = true","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Не все изменения внутреннего состояния плеера приводят к изменению свойства ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/controlMask","isActive":true,"type":"reference"},{"text":". Очень частые события наподобие изменения текущей позиции воспроизведения (","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/handlePlayerTick()","isActive":true,"type":"reference"},{"text":") передаются в обход установки этого свойства, вместо этого их надо получать через методы протокола ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","isActive":true,"type":"reference"},{"text":". При этом в самой маске значения этих полей все равно остаются всегда актуальными. Разница лишь в том, что само свойство ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/controlMask","isActive":true,"type":"reference"},{"text":" не изменяется. Пример реализации:","type":"text"}]},{"code":["\/\/ Вызывается во время проигрывания несколько раз в секунду.","func handlePlayerTick() {","    guard let mask = controlMask, !mask.hasControl(.live), !timelineView.isHidden else { return }","    ","    if let values = mask.timelineValues {","        timelineView.update(progress: values.currentTime, duration: values.duration)","    }","}"],"type":"codeListing","syntax":"swift"},{"text":"Скрытие и показ контролов","anchor":"%D0%A1%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BE%D0%B2","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Как было указано выше, видимость самой view контролов нельзя изменять из них самих. Такое правило нужно, потому что OVKit сам занимается скрытием и показом view контролов целиком. Обычно это происходит при транзишенах.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Контролы сами могут описывать свои предпочтения по логике скрытия и показа самих себя через свойства протокола ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","type":"reference","isActive":true},{"text":". Работа с этими свойствами очень похожа на свойство ","type":"text"},{"code":"prefersStatusBarHidden","type":"codeVoice"},{"text":" и ему подобные у ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":". OVKit время от времени опрашивает контролы об их предпочтениях в логике скрытия и показа. Чтобы обновить ее незамедлительно, можно использовать метод ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/updateControlsHidingState()","type":"reference","isActive":true},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Плавное скрытие и показ контролов выполняются за счет одновременного изменения ","type":"text"},{"type":"codeVoice","code":"alpha"},{"text":" всех отдельных компонентов (таймлайна, кнопок).","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"В зависимости от конечного дизайна могут быть исключения, когда даже на ","type":"text"},{"inlineContent":[{"text":"скрытых","type":"text"}],"type":"emphasis"},{"text":" контролах должны показываться какие-то UI элементы.","type":"text"}]}],"style":"tip","type":"aside","name":"Tip"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Доступность отдельных UI элементов в зависимости от наличия контролов в маске удобнее всего регулировать через установку "},{"type":"codeVoice","code":"isHidden"},{"type":"text","text":" этих компонентов. Таким образом, контролы могут изменять набор доступных пользователю UI элементов и одновременно обеспечивать их плавный показ и скрытие."}]},{"type":"heading","text":"Управление плеером","level":3,"anchor":"%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80%D0%BE%D0%BC"},{"inlineContent":[{"type":"text","text":"Контролы из маски выполняют и обратную функцию – позволяют управлять плеером. Для этого у делегата контролов есть метод "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleControl(_:)","type":"reference","isActive":true},{"type":"text","text":". В него необходимо передать контрол из маски, который нужно активировать. Важно передавать именно экземпляр контрола из маски, чтобы избежать рассинхрона состояний плеера и view контролов."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Например, так может выглядеть обработка нажатии кнопки mute:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func handleSoundButton() {","    if let sound = self.controlMask?.getControl(.sound) {","        \/\/ значение изменять не нужно, передаем как есть","        self.controlsDelegate?.handleControl(sound)","    }","}"]},{"inlineContent":[{"text":"Перемотка видео работает уже через другой метод делегата:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func handleSeekButton(_ seekTime: Double) {","    self.controlsDelegate?.seekToTime(floor(seekTime), method: .doubleTap)","}",""]}],"kind":"content"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"title":"Контролы плеера","roleHeading":"Article","role":"article"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controls"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/controls"]}],"seeAlsoSections":[{"generated":true,"title":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"anchor":"Концепты"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","title":"PlayerControlsViewProtocol","role":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/hideablecontrols","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HideableControls","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HideableControls","kind":"identifier"}],"type":"topic","title":"HideableControls","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol/controlMask":{"title":"controlMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/controlMask","type":"topic","kind":"symbol","abstract":[{"text":"Актуальная на данный момент контрольная маска.","type":"text"}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol\/controlmask","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol":{"abstract":[{"text":"Протокол для контролов, которые могут использоваться в полноэкранном режиме проигрывания.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerFullscreenControlsViewProtocol"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol","title":"PlayerFullscreenControlsViewProtocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerFullscreenControlsViewProtocol"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ControlCode/live":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/live","title":"ControlCode.live","url":"\/documentation\/ovkit\/controlcode\/live","type":"topic","abstract":[{"type":"text","text":"Воспроизводит ли плеер прямую трансляцию."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"kind":"article","abstract":[{"text":"Динамически подключаемые модули для расширения функциональности.","type":"text"}],"url":"\/documentation\/ovkit\/plugins","role":"collectionGroup","type":"topic","title":"Плагины","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pictureInPictureControls(with:)":{"abstract":[{"text":"Контролы для использования в режиме “Картинка в Картинке”.","type":"text"}],"role":"symbol","required":true,"url":"\/documentation\/ovkit\/playermanagerdelegate\/pictureinpicturecontrols(with:)","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControlsWith:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","title":"pictureInPictureControls(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"abstract":[{"text":"Сбор статистики воспроизведения видео.","type":"text"}],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","url":"\/documentation\/ovkit\/statistics","title":"Статистика","role":"article","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"type":"topic","role":"article","title":"Префетчер","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"kind":"article","url":"\/documentation\/ovkit\/prefetch","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","abstract":[{"type":"text","text":"Непрерывный перенос воспроизведения из одного "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в другой."}],"url":"\/documentation\/ovkit\/transitions","role":"article","title":"Переходы между плеерами"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"type":"topic","role":"article","title":"Воспроизведение в фоне","abstract":[{"type":"text","text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"kind":"article","url":"\/documentation\/ovkit\/backgroundplayback","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/updateControlsHidingState()":{"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Обновление статуса автоскрытия контролов."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/updateControlsHidingState()","title":"updateControlsHidingState()","url":"\/documentation\/ovkit\/controlsviewdelegate\/updatecontrolshidingstate()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateControlsHidingState","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenControls(for:originPlayerView:)":{"type":"topic","role":"symbol","title":"fullscreenControls(for:originPlayerView:)","abstract":[{"type":"text","text":"Определить для возможности использования собственных контролов в полноэкранном режиме."}],"kind":"symbol","navigatorTitle":[{"text":"fullscreenControlsFor:originPlayerView:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"originPlayerView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)"},"doc://onevideo.OVKit/documentation/OVKit/ControlCode/sound":{"type":"topic","role":"symbol","title":"ControlCode.sound","abstract":[{"type":"text","text":"Возможность включать\/выключать звук в плеере и его состояние."}],"kind":"symbol","url":"\/documentation\/ovkit\/controlcode\/sound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sound","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/sound"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ControlCode/fullscreen":{"type":"topic","role":"symbol","title":"ControlCode.fullscreen","abstract":[{"type":"text","text":"Можно ли разворачивать плеер в полноэкранный режим."}],"kind":"symbol","url":"\/documentation\/ovkit\/controlcode\/fullscreen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCode\/fullscreen"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"title":"Разное","url":"\/documentation\/ovkit\/extras","role":"article","type":"topic","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","abstract":[{"text":"Дополнительные возможности.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol/handlePlayerTick()":{"required":true,"title":"handlePlayerTick()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePlayerTick","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Вызывается периодически во время проигрывания видео."}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol\/handleplayertick()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/handlePlayerTick()","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/handleControl(_:)":{"type":"topic","role":"symbol","title":"handleControl(_:)","abstract":[{"type":"text","text":"Вызывается при взаимодействии пользователя с контролом."}],"kind":"symbol","url":"\/documentation\/ovkit\/controlsviewdelegate\/handlecontrol(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleControl"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12ControlValueO","text":"ControlValue"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleControl(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"title":"ControlMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","navigatorTitle":[{"text":"ControlMask","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Объект, отражающий внутреннее состояние плеера для отображения в UI."}],"kind":"symbol","url":"\/documentation\/ovkit\/controlmask","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlMask","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"title":"Полноэкранный режим","role":"article","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"url":"\/documentation\/ovkit\/fullscreen","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Концепты","title":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"]}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/title","value":"pictureInPictureControlsWith:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureControlsWith:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/title","value":"fullscreenControlsFor:originPlayerView:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}