{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlsbehavior"]}],"metadata":{"externalID":"s:5OVKit16ControlsBehaviorP","navigatorTitle":[{"text":"ControlsBehavior","kind":"identifier"}],"symbolKind":"protocol","title":"ControlsBehavior","roleHeading":"Protocol","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ControlsBehavior","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior\/controlsView"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HintBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ZoomBehavior"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Динамическое поведение контролов.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"text":"Например, быстрая перемотка двойным тапом или долгим тапом. Добавить поведение на контролы можно при помощи метода ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/addBehavior(_:)","type":"reference","isActive":true},{"text":". Одно и то же поведение можно добавлять только один раз. Рекомендуется делать это в инициализаторе контролов.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","kind":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","title":"DoubleTapSeekBehavior","type":"topic","role":"symbol","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior/controlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior\/controlsView","type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/controlsbehavior\/controlsview","title":"controlsView","role":"symbol","abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ZoomBehavior":{"title":"ZoomBehavior","kind":"symbol","navigatorTitle":[{"text":"ZoomBehavior","kind":"identifier"}],"url":"\/documentation\/ovkit\/zoombehavior","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ZoomBehavior","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZoomBehavior","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"role":"symbol","navigatorTitle":[{"text":"ControlsBehavior","kind":"identifier"}],"kind":"symbol","title":"ControlsBehavior","abstract":[{"type":"text","text":"Динамическое поведение контролов."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"}],"url":"\/documentation\/ovkit\/controlsbehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/HintBehavior":{"abstract":[{"type":"text","text":"Подсказка, которая исчезает через некоторое время после появления."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HintBehavior","role":"symbol","navigatorTitle":[{"text":"HintBehavior","kind":"identifier"}],"type":"topic","title":"HintBehavior","url":"\/documentation\/ovkit\/hintbehavior","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HintBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Перемотка видео нажатием и удержанием.","type":"text"}],"url":"\/documentation\/ovkit\/holdtoseekbehavior","title":"HoldToSeekBehavior","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol/addBehavior(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/addBehavior(_:)","kind":"symbol","title":"addBehavior(_:)","url":"\/documentation\/ovkit\/playercontrolsviewprotocol\/addbehavior(_:)","abstract":[{"type":"text","text":"Добавление поведения на контролы."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addBehavior"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit16ControlsBehaviorP","kind":"typeIdentifier","text":"ControlsBehavior"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","value":"DoubleTapSeekBehavior","op":"replace"},{"value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title","value":"HoldToSeekBehavior","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments","op":"replace","value":[{"text":"HoldToSeekBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/navigatorTitle","value":[{"text":"HoldToSeekBehavior","kind":"identifier"}]}]}]}