{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlsviewdelegate"]}],"metadata":{"symbolKind":"protocol","title":"ControlsViewDelegate","navigatorTitle":[{"text":"ControlsViewDelegate","kind":"identifier"}],"role":"symbol","externalID":"s:5OVKit20ControlsViewDelegateP","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlsViewDelegate"}],"modules":[{"name":"OVKit"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/chapterProvider","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/playerTickInterval","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/thumbnailProvider"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/didReplaceControlsView()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/dismissFullscreenViewController()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleControl(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleShoppableAction(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleVideoMotionAction(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentScreencastMenu(onShowRoutePicker:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentSettingsMenu()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/seekToTime(_:method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/updateControlsHidingState()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/visibilityDidChangeTo(visible:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlsViewDelegate"},{"text":" : ","kind":"text"},{"text":"CoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/didReplaceControlsView()":{"type":"topic","title":"didReplaceControlsView()","required":true,"abstract":[{"type":"text","text":"Сообщает делегату, что плеер изменил контролы."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/didReplaceControlsView()","url":"\/documentation\/ovkit\/controlsviewdelegate\/didreplacecontrolsview()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didReplaceControlsView","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/updateControlsHidingState()":{"title":"updateControlsHidingState()","abstract":[{"text":"Обновление статуса автоскрытия контролов.","type":"text"}],"url":"\/documentation\/ovkit\/controlsviewdelegate\/updatecontrolshidingstate()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateControlsHidingState"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/updateControlsHidingState()","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/presentSettingsMenu()":{"title":"presentSettingsMenu()","kind":"symbol","abstract":[{"type":"text","text":"Показать меню настроек плеера."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentSettingsMenu","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/presentsettingsmenu()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentSettingsMenu()"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"kind":"symbol","url":"\/documentation\/ovkit\/covercontrolsdelegate","navigatorTitle":[{"kind":"identifier","text":"CoverControlsDelegate"}],"type":"topic","title":"CoverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CoverControlsDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Делегат, через который "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":" могут выполнять действия."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"type":"topic","role":"symbol","title":"ThumbnailProvider","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThumbnailProvider"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"url":"\/documentation\/ovkit\/thumbnailprovider"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/handleShoppableAction(_:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Обработка событий Shoppable рекламы.","type":"text"}],"title":"handleShoppableAction(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleShoppableAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ShoppableAction","preciseIdentifier":"s:5OVKit15ShoppableActionO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleShoppableAction(_:)","url":"\/documentation\/ovkit\/controlsviewdelegate\/handleshoppableaction(_:)","required":true,"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/presentScreencastMenu(onShowRoutePicker:)":{"required":true,"kind":"symbol","title":"presentScreencastMenu(onShowRoutePicker:)","abstract":[{"type":"text","text":"Показать меню трансляции видео на другие устройства."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentScreencastMenu"},{"text":"(","kind":"text"},{"text":"onShowRoutePicker","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier","text":"VoidBlock"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentScreencastMenu(onShowRoutePicker:)","role":"symbol","url":"\/documentation\/ovkit\/controlsviewdelegate\/presentscreencastmenu(onshowroutepicker:)"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/playerTickInterval":{"title":"playerTickInterval","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/controlsviewdelegate\/playertickinterval","kind":"symbol","abstract":[{"text":"Интервал, с которым обновляется текущее время проигрывания.","type":"text"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerTickInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/playerTickInterval"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","url":"\/documentation\/ovkit\/coverview","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"type":"topic","title":"CoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverView"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/seekToTime(_:method:)":{"title":"seekToTime(_:method:)","kind":"symbol","abstract":[{"type":"text","text":"Выполнение перемотки на заданное время."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekToTime"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","text":"StatsSeekMethod"},{"kind":"text","text":"?)"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/seektotime(_:method:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/seekToTime(_:method:)"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}],"type":"topic","title":"ChapterProvider","url":"\/documentation\/ovkit\/chapterprovider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/visibilityDidChangeTo(visible:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/visibilityDidChangeTo(visible:)","required":true,"title":"visibilityDidChangeTo(visible:)","url":"\/documentation\/ovkit\/controlsviewdelegate\/visibilitydidchangeto(visible:)","abstract":[{"text":"Изменилась видимость контролов.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visibilityDidChangeTo"},{"kind":"text","text":"("},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/handleVideoMotionAction(_:)":{"title":"handleVideoMotionAction(_:)","kind":"symbol","abstract":[{"type":"text","text":"Обработка событий Video Motion рекламы."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleVideoMotionAction"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"VideoMotionAction","preciseIdentifier":"s:5OVKit17VideoMotionActionO"},{"text":")","kind":"text"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/handlevideomotionaction(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleVideoMotionAction(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/chapterProvider":{"role":"symbol","title":"chapterProvider","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","isActive":true},{"text":" для текущего видео.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/chapterprovider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"chapterProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChapterProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"kind":"text","text":"?"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/chapterProvider","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/handleControl(_:)":{"abstract":[{"type":"text","text":"Вызывается при взаимодействии пользователя с контролом."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleControl","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit12ControlValueO","text":"ControlValue","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"url":"\/documentation\/ovkit\/controlsviewdelegate\/handlecontrol(_:)","kind":"symbol","title":"handleControl(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/handleControl(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","title":"ControlsViewDelegate","url":"\/documentation\/ovkit\/controlsviewdelegate","abstract":[{"text":"Делегат, через который контролы могут выполнять действия.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ControlsViewDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ControlsViewDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/dismissFullscreenViewController()":{"title":"dismissFullscreenViewController()","kind":"symbol","abstract":[{"type":"text","text":"Закрыть полноэкранный режим, если текущее "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в нём находится."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismissFullscreenViewController"},{"kind":"text","text":"()"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/dismissfullscreenviewcontroller()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/dismissFullscreenViewController()"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/thumbnailProvider":{"kind":"symbol","title":"thumbnailProvider","url":"\/documentation\/ovkit\/controlsviewdelegate\/thumbnailprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/thumbnailProvider","required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"thumbnailProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":"?"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider"},{"text":" для текущего видео.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":"OVKCoverControlsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider"},{"value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments"},{"value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"text":"OVKChapterProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}