{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/contentDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/countdownTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/errorMessage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/recovering","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/startTime"],"title":"Instance Properties"}],"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams","role":"symbol","roleHeading":"Class","title":"CoverViewParams","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"symbolKind":"class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"},"variants":[{"paths":["\/documentation\/ovkit\/coverviewparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/coverviewparams"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKCoverViewParams) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoverViewParams","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/liveStatus":{"navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"abstract":[{"type":"text","text":"Если есть значение отличное от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started"},{"text":", ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" должен показывать причины остановки трансляции."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"}],"type":"topic","kind":"symbol","title":"liveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/liveStatus","url":"\/documentation\/ovkit\/coverviewparams\/livestatus","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/startTime":{"kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams\/starttime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"startTime"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/startTime","role":"symbol","abstract":[{"type":"text","text":"Будет актуален, если значение "},{"code":"liveStatus","type":"codeVoice"},{"type":"text","text":" равно "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","isActive":true},{"type":"text","text":". Приходит в формате unix timestamp."},{"text":" ","type":"text"},{"type":"text","text":"Если значение равно нулю — время начала трансляции не известно."}],"title":"startTime","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKCoverViewParams/init":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/init","kind":"symbol","role":"symbol","type":"topic","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/ovkit\/ovkcoverviewparams\/init","abstract":[]},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/finished":{"navigatorTitle":[{"kind":"identifier","text":"finished"}],"abstract":[{"type":"text","text":"Плеер закончил воспроизведение видео."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","title":"finished","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/finished","url":"\/documentation\/ovkit\/coverviewparams\/finished","role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/isLive":{"navigatorTitle":[{"text":"isLive","kind":"identifier"}],"abstract":[{"type":"text","text":"Является ли проигрываемое видео прямой трансляцией."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isLive","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams\/islive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/isLive","title":"isLive","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/contentDuration":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentDuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"role":"symbol","title":"contentDuration","url":"\/documentation\/ovkit\/coverviewparams\/contentduration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/contentDuration","navigatorTitle":[{"text":"contentDuration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Длительность видео. Актуально только для контролов ленты."},{"text":" ","type":"text"},{"type":"text","text":"Если значение равно нулю — длительность неизвестна."}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"started"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","role":"symbol","abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"OVKLiveStatusStarted","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/started","title":"LiveStatus.started"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","title":"CoverViewParams","url":"\/documentation\/ovkit\/coverviewparams","navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CoverViewParams","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/restriction":{"type":"topic","title":"restriction","url":"\/documentation\/ovkit\/coverviewparams\/restriction","navigatorTitle":[{"text":"restriction","kind":"identifier"}],"abstract":[{"type":"text","text":"Если есть значение, "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":" должен быть о снятии ограничений."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"restriction","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/recovering":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recovering","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/coverviewparams\/recovering","title":"recovering","kind":"symbol","role":"symbol","abstract":[{"text":"Стоит ли показать activity indicator.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/recovering","navigatorTitle":[{"kind":"identifier","text":"recovering"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/countdownTime":{"title":"countdownTime","url":"\/documentation\/ovkit\/coverviewparams\/countdowntime","abstract":[{"text":"Количество секунд до старта трансляции, актуально для ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/countdownTime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countdownTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/errorMessage":{"navigatorTitle":[{"kind":"identifier","text":"errorMessage"}],"abstract":[{"type":"text","text":"Если есть значение, "},{"code":"CoverView","type":"codeVoice"},{"text":" должен сообщать об ошибке воспроизведения.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","title":"errorMessage","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/errorMessage","url":"\/documentation\/ovkit\/coverviewparams\/errormessage","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/upcoming":{"type":"topic","url":"\/documentation\/ovkit\/livestatus\/upcoming","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upcoming","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","role":"symbol","abstract":[{"type":"text","text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать."}],"title":"LiveStatus.upcoming","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"OVKCoverViewParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/contentDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/errorMessage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/recovering","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/startTime"],"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKCoverViewParams\/init"],"title":"Instance Methods"}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKCoverViewParams","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1liveStatus\/title","value":"liveStatus"},{"value":[{"kind":"identifier","text":"liveStatus"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1liveStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1startTime\/title","op":"replace","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1startTime\/fragments","value":[{"text":"startTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1finished\/title","op":"replace","value":"finished"},{"value":[{"text":"finished","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1finished\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1isLive\/title","value":"isLive","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1isLive\/fragments","value":[{"kind":"identifier","text":"isLive"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1contentDuration\/title","value":"contentDuration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1contentDuration\/fragments","value":[{"kind":"identifier","text":"contentDuration"}],"op":"replace"},{"op":"replace","value":"OVKLiveStatusStarted","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusStarted"}]},{"value":"OVKCoverViewParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKCoverViewParams"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments"},{"value":"restriction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/fragments","value":[{"text":"restriction","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"recovering","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1recovering\/title"},{"op":"replace","value":[{"kind":"identifier","text":"recovering"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1recovering\/fragments"},{"value":"errorMessage","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1errorMessage\/title"},{"op":"replace","value":[{"text":"errorMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1errorMessage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/title","value":"OVKLiveStatusUpcoming"},{"value":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/fragments"}]}]}