{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherited By","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"],"type":"inheritedBy","kind":"relationships"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/replayVideo()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/startVideo()"],"anchor":"Instance-Methods","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","abstract":[{"text":"Делегат, через который ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"text":" могут выполнять действия.","type":"text"}],"metadata":{"title":"CoverControlsDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverControlsDelegate"}],"externalID":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","roleHeading":"Protocol","modules":[{"name":"OVKit"}],"symbolKind":"protocol","navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKCoverControlsDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverControlsDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/covercontrolsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/covercontrolsdelegate"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/reloadVideo()":{"url":"\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()","title":"reloadVideo()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadVideo"},{"kind":"text","text":"()"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"reloadVideo"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Перезагрузка видео."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"url":"\/documentation\/ovkit\/coverview","title":"CoverView","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate","abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsViewDelegate","kind":"identifier"}],"title":"ControlsViewDelegate","navigatorTitle":[{"text":"ControlsViewDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/replayVideo()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayVideo","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"replayVideo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/replayVideo()","url":"\/documentation\/ovkit\/covercontrolsdelegate\/replayvideo()","abstract":[{"type":"text","text":"Проиграть видео сначала."}],"required":true,"title":"replayVideo()","type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate":{"navigatorTitle":[{"text":"CoverControlsDelegate","kind":"identifier"}],"title":"CoverControlsDelegate","url":"\/documentation\/ovkit\/covercontrolsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverControlsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Делегат, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"text":" могут выполнять действия.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/startVideo()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startVideo","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"startVideo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/startVideo()","url":"\/documentation\/ovkit\/covercontrolsdelegate\/startvideo()","abstract":[{"type":"text","text":"Старт видео."}],"required":true,"title":"startVideo()","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKCoverControlsDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/replayVideo()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/startVideo()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKCoverControlsDelegate","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"reloadVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/fragments"},{"value":"replayVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1replayVideo()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replayVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1replayVideo()\/fragments"},{"value":"OVKCoverControlsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/title"},{"value":[{"kind":"identifier","text":"OVKCoverControlsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/fragments"},{"value":[{"text":"OVKCoverControlsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate\/navigatorTitle"},{"value":"startVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1startVideo()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1startVideo()\/fragments"}]}]}