{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer"},"abstract":[{"text":"Первые шаги после интеграции.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"},{"type":"codeListing","code":["let playerView = PlayerView(frame: .zero, gravity: .fit, customControls: FeedControlsView(frame: .zero, style: .feed))","playerView.delegate = self","playerView.viewDelegate = self  \/\/ опционально"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Можно использовать доступные реализации контролов, которые используются ВКонтакте или создавать свои, см. "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","type":"reference","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Необходимо управлять свойством ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","type":"reference","isActive":true},{"text":", отвечающим за автоплей. Обновляя это свойство, при уходе с экрана плеер ставит проигрывание на автопаузу и возобновляет проигрывание, когда возвращается на экран.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"В плеере есть понятия автопауза и пауза. Автопауза — это невозможность играть видео: плеер не на экране, другое видео проигрывается в PiP, приложение ушло в фон. Если проигрываемое видео было поставлено на автопаузу, после устранения причин автопаузы видео начнет играть само.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Пауза - действие совершенное пользователем: нажатие на контролы и вызовы из кода с флагом ","type":"text"},{"code":"userInitiated","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"aside","name":"Tip","content":[{"inlineContent":[{"text":"Пауза имеет более высокий приоритет (т.к. действие пользователя) и затирает все причины автопаузы.","type":"text"}],"type":"paragraph"}],"style":"tip"},{"type":"heading","anchor":"%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-Video","level":2,"text":"Установка Video"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Для проигрывания нужно установить любой инстанс объекта видео, реализующий протокол "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true}]},{"type":"codeListing","code":["playerView.video = Video(id: \"1\")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Также можно использовать класс ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference","isActive":true},{"text":", который нужно наполнить ссылками для проигрывания и предпросмотра или используя возможности ","type":"text"},{"code":"ApiSession","type":"codeVoice"},{"text":": ","type":"text"},{"code":"ApiSession\/fetch(videoIds:completion:)","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Чтобы запустить проигрывание, необходимо вызвать "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)"},{"type":"text","text":". Где "},{"code":"userInitiated","type":"codeVoice"},{"type":"text","text":" говорит о том, какого рода старт:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Автоплей: не сработает если плеер не на экране (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen"},{"text":");","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ручной старт: пользователь явно инициировал проигрывание видео."}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Остановить и продолжить воспроизведение можно через свойство ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","isActive":true},{"text":", которое имеет приоритет над ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Метод ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()"},{"text":" останавливает проигрывание и освобождает ресурсы плеера.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Чтобы получать события от плеера, необходимо реализовать протокол "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Видео можно сразу открыть в fullscreen представлении, передав ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference","isActive":true},{"text":" и контроллер, с которого нужно презентовать: ","type":"text"},{"code":"PlayerView\/showFullscreen(_:on:fromTime:playerViewSetupBlock:completion:)","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PlayerView"},{"type":"text","text":" поддерживает анимированное изменение размера:"}]},{"type":"codeListing","code":["UIView.animate(withDuration: 1.0, delay: 0.0, options: .curveEaseInOut) {","  playerView.frame = newFrame","  playerView.layoutIfNeeded()","} completion: { _ in }"],"syntax":"swift"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/createplayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/createplayer"]}],"metadata":{"roleHeading":"Article","title":"Создание плеера","role":"article","modules":[{"name":"OVKit"}]},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Начало работы","anchor":"Начало-работы","generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"type":"topic","url":"\/documentation\/ovkit\/prefetch","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","role":"article","kind":"article","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"title":"Префетчер"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"url":"\/documentation\/ovkit\/backgroundplayback","type":"topic","role":"article","kind":"article","title":"Воспроизведение в фоне","abstract":[{"code":"OVKit","type":"codeVoice"},{"text":" поддерживает воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}],"title":"Полноэкранный режим","kind":"article","type":"topic","url":"\/documentation\/ovkit\/fullscreen","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/video","title":"Video","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},"doc://onevideo.OVKit/documentation/OVKit/gRPC":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","abstract":[],"title":"gRPC","type":"topic","kind":"article","url":"\/documentation\/ovkit\/grpc","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"url":"\/documentation\/ovkit\/playerview\/paused","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","title":"paused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"paused"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Пауза пользователем: userInitiated действие, отключает автопроигрывание при "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Актуально только после начала проигрывания"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/stop()":{"url":"\/documentation\/ovkit\/playerview\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"stop()","abstract":[{"text":"Остановка и очистка плеера","type":"text"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","kind":"article","title":"Быстрый старт","type":"topic","abstract":[{"type":"text","text":"Руководство для первого подключения "},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":" к проекту. Эти шаги необходимо выполнить перед началом работы."}],"url":"\/documentation\/ovkit\/quickstart"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"url":"\/documentation\/ovkit\/extras","abstract":[{"text":"Дополнительные возможности ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","title":"Дополнительно","role":"article","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"title":"play(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"playWithUserInitiated:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"url":"\/documentation\/ovkit\/plugins","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","kind":"article","abstract":[{"text":"Плагины позволяют расширить функциональность ","type":"text"},{"type":"codeVoice","code":"OVKit"},{"text":".","type":"text"}],"type":"topic","title":"Плагины"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","abstract":[],"title":"Контролы плеера","kind":"article","type":"topic","url":"\/documentation\/ovkit\/controls","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"url":"\/documentation\/ovkit\/videotype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/playerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate","navigatorTitle":[{"text":"PlayerDelegate","kind":"identifier"}],"type":"topic","title":"PlayerDelegate","role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"role":"symbol","abstract":[{"text":"Отвечает за видимость плеера на экране.","type":"text"},{"text":" ","type":"text"},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"text":" ","type":"text"},{"text":"Это свойство может изменится, если вызван ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","isActive":true,"type":"reference"},{"text":" со значением ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"title":"playerViewOnScreen","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","navigatorTitle":[{"text":"playerViewOnScreen","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","abstract":[{"text":"SDK поддерживает сбор статистики по воспроизведению видео.","type":"text"}],"title":"Статистика","kind":"article","type":"topic","url":"\/documentation\/ovkit\/statistics","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Начало работы","anchor":"Начало-работы","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace"},{"value":"paused","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","op":"replace"},{"value":[{"text":"paused","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","op":"replace"},{"value":"stop","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/fragments","op":"replace"},{"value":"playWithUserInitiated:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithUserInitiated:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","op":"replace"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"},{"value":"OVKPlayerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/title","op":"replace"},{"value":[{"text":"OVKPlayerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/navigatorTitle","op":"replace"},{"value":"playerViewOnScreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"playerViewOnScreen"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","op":"replace"}]}]}