{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultAdsProvider","kind":"identifier"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)DefaultAdsProvider","navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"title":"DefaultAdsProvider"},"abstract":[{"text":"Провайдер рекламы.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/defaultadsprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/defaultadsprovider"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultAdsProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект, отвечающий за предоставление рекламных ресурсов для различных состояний "},{"type":"codeVoice","code":"PlayerView"},{"type":"text","text":"."}]}]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/discover()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/fullscreen()"],"title":"Type Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/fullscreen()":{"url":"\/documentation\/ovkit\/defaultadsprovider\/fullscreen()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/fullscreen()","abstract":[{"type":"text","text":"Провайдер рекламы для полноэкранного представления плеера."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreen","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol","title":"fullscreen()","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/AdsProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdsProvider","kind":"identifier"}],"abstract":[{"text":"Протокол поставщика рекламных контролов.","type":"text"}],"navigatorTitle":[{"text":"AdsProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AdsProvider","url":"\/documentation\/ovkit\/adsprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider","role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeAdControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoAdsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"text":", ","kind":"text"},{"text":"hasSupplementaryControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"interactiveAdsPlaying","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"inPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","abstract":[{"type":"text","text":"Фабричный метод для создания новых рекламных контролов."}],"title":"makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","type":"topic","url":"\/documentation\/ovkit\/defaultadsprovider\/makeadcontrols(for:hassupplementarycontrols:interactiveadsplaying:inpip:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/autoplay()":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoplay"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}],"title":"autoplay()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/autoplay()","url":"\/documentation\/ovkit\/defaultadsprovider\/autoplay()","role":"symbol","abstract":[{"text":"Провайдер рекламы для обычного представления плеера.","type":"text"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"}],"abstract":[{"text":"Провайдер рекламы.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultAdsProvider"}],"type":"topic","kind":"symbol","title":"DefaultAdsProvider","url":"\/documentation\/ovkit\/defaultadsprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider","role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DefaultAdsProvider/discover()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DefaultAdsProvider\/discover()","kind":"symbol","title":"discover()","abstract":[{"text":"Провайдер рекламы для представления плеера в рекомендациях.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discover","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/defaultadsprovider\/discover()"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DefaultAdsProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DefaultAdsProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DefaultAdsProvider","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAdsProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/title","value":"DefaultAdsProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/fragments","value":[{"kind":"identifier","text":"DefaultAdsProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DefaultAdsProvider\/navigatorTitle","value":[{"text":"DefaultAdsProvider","kind":"identifier"}],"op":"replace"}]}]}