{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/init(customStepInterval:shouldBegin:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/controlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/customStepInterval","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/isEnabled"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekBackward()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekForward()"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations"],"generated":true}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"roleHeading":"Class","title":"DoubleTapSeekBehavior","externalID":"c:@M@OVKit@objc(cs)DoubleTapSeekBehavior","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Перемотка видео двойным тапом.","type":"text"}],"references":{"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable","title":"UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/controlsView":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"controlsView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"controlsView","url":"\/documentation\/ovkit\/doubletapseekbehavior\/controlsview","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/controlsView","abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/seekBackward()":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekBackward()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekBackward"},{"text":"()","kind":"text"}],"title":"seekBackward()","kind":"symbol","abstract":[{"text":"Эмуляция жеста быстрой перемотки назад.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"seekBackward"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/seekbackward()"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/UIGestureRecognizerDelegate-Implementations":{"url":"\/documentation\/ovkit\/doubletapseekbehavior\/uigesturerecognizerdelegate-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations","type":"topic","kind":"article","abstract":[],"title":"UIGestureRecognizerDelegate Implementations","role":"collectionGroup"},"doc://onevideo.OVKit/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"navigatorTitle":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","title":"DoubleTapSeekBehavior","kind":"symbol","abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"url":"\/documentation\/ovkit\/doubletapseekbehavior","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/seekForward()":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekForward()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekForward"},{"text":"()","kind":"text"}],"title":"seekForward()","kind":"symbol","abstract":[{"type":"text","text":"Эмуляция жеста быстрой перемотки вперёд."}],"navigatorTitle":[{"text":"seekForward","kind":"identifier"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/seekforward()"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/isEnabled":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEnabled","url":"\/documentation\/ovkit\/doubletapseekbehavior\/isenabled","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/isEnabled","abstract":[{"text":"Активен ли жест быстрой перемотки.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/init(customStepInterval:shouldBegin:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/init(customStepInterval:shouldBegin:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customStepInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"shouldBegin"},{"text":": () -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(customStepInterval:shouldBegin:)","kind":"symbol","abstract":[{"text":"Создание поведения.","type":"text"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/init(customstepinterval:shouldbegin:)"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"}],"title":"ControlsBehavior","kind":"symbol","abstract":[{"text":"Динамическое поведение контролов.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ControlsBehavior"}],"url":"\/documentation\/ovkit\/controlsbehavior"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/customStepInterval":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customStepInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?"}],"title":"customStepInterval","url":"\/documentation\/ovkit\/doubletapseekbehavior\/customstepinterval","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/customStepInterval","abstract":[{"text":"Пользовательский интервал перемотки.","type":"text"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DoubleTapSeekBehavior","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekBackward()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekForward()"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations"],"generated":true}]},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DoubleTapSeekBehavior","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"seekBackward","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekBackward()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"seekBackward","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekBackward()\/fragments"},{"value":"DoubleTapSeekBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","op":"replace"},{"value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekForward()\/title","op":"replace","value":"seekForward"},{"value":[{"kind":"text","text":"- "},{"text":"seekForward","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekForward()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}