{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadSuspendReason"}],"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKDownloadSuspendReason","navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"title":"DownloadSuspendReason","roleHeading":"Enumeration","symbolKind":"enum"},"kind":"symbol","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/background","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/manualPause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/unsuitableNetwork"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKDownloadSuspendReason) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DownloadSuspendReason","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/downloadsuspendreason"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason"},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/ovkit\/downloadsuspendreason\/rawrepresentable-implementations"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/manualPause":{"title":"DownloadSuspendReason.manualPause","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/manualPause","abstract":[{"text":"Загрузка была приостановлена пользователем из кода.","type":"text"}],"navigatorTitle":[{"text":"OVKDownloadSuspendReasonManualPause","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/downloadsuspendreason\/manualpause","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualPause"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/none":{"abstract":[{"type":"text","text":"Загрузка "},{"type":"emphasis","inlineContent":[{"type":"text","text":"не"}]},{"text":" приостановлена и выполняется.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none","title":"DownloadSuspendReason.none","url":"\/documentation\/ovkit\/downloadsuspendreason\/none","type":"topic","navigatorTitle":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"url":"\/documentation\/ovkit\/downloadsuspendreason","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DownloadSuspendReason","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","kind":"symbol","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"title":"DownloadSuspendReason","navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/ovkit\/downloadsuspendreason\/equatable-implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/unsuitableNetwork":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/unsuitableNetwork","type":"topic","kind":"symbol","abstract":[{"text":"Загрузка была приостановлена в связи с отсутствием разрешенного типа сети.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsuitableNetwork"}],"title":"DownloadSuspendReason.unsuitableNetwork","url":"\/documentation\/ovkit\/downloadsuspendreason\/unsuitablenetwork","navigatorTitle":[{"text":"OVKDownloadSuspendReasonUnsuitableNetwork","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/init(rawValue:)":{"url":"\/documentation\/ovkit\/downloadsuspendreason\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/background":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/background","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadsuspendreason\/background","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}],"title":"DownloadSuspendReason.background","type":"topic","abstract":[{"text":"Загрузка была приостановлена из-за ухода приложения в фон.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKDownloadSuspendReason"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/background","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/manualPause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/unsuitableNetwork"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OVKDownloadSuspendReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"OVKDownloadSuspendReasonManualPause","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1manualPause\/title"},{"value":[{"kind":"identifier","text":"OVKDownloadSuspendReasonManualPause"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1manualPause\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/title","value":"OVKDownloadSuspendReasonNone"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/fragments","op":"replace","value":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title","value":"OVKDownloadSuspendReason","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments"},{"value":[{"kind":"identifier","text":"OVKDownloadSuspendReason"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle"},{"value":"OVKDownloadSuspendReasonUnsuitableNetwork","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1unsuitableNetwork\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1unsuitableNetwork\/fragments","value":[{"text":"OVKDownloadSuspendReasonUnsuitableNetwork","kind":"identifier"}],"op":"replace"},{"value":"OVKDownloadSuspendReasonBackground","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1background\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1background\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadSuspendReasonBackground"}]}]}]}