{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/downloadstate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/downloadstate"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/created","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/downloading","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/error","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/pending","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/suspended"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKDownloadState) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DownloadState","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DownloadState","kind":"identifier"}],"role":"symbol","title":"DownloadState","externalID":"c:@M@OVKit@E@OVKDownloadState","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"DownloadState","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/suspended":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/suspended","url":"\/documentation\/ovkit\/downloadstate\/suspended","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suspended","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DownloadState.suspended","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}]},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/downloading":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/downloading","url":"\/documentation\/ovkit\/downloadstate\/downloading","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"downloading","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DownloadState.downloading","navigatorTitle":[{"text":"OVKDownloadStateDownloading","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/pending":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/pending","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStatePending"}],"title":"DownloadState.pending","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadstate\/pending"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/error":{"navigatorTitle":[{"text":"OVKDownloadStateError","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadstate\/error","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"type":"topic","title":"DownloadState.error","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/downloadstate\/init(rawvalue:)"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/finished":{"title":"DownloadState.finished","url":"\/documentation\/ovkit\/downloadstate\/finished","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/finished","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"finished","kind":"identifier"}],"navigatorTitle":[{"text":"OVKDownloadStateFinished","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/downloadstate\/rawrepresentable-implementations","type":"topic","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"url":"\/documentation\/ovkit\/downloadstate","abstract":[],"title":"DownloadState","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/Equatable-Implementations","url":"\/documentation\/ovkit\/downloadstate\/equatable-implementations","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","title":"Equatable Implementations"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/created":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"created","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadstate\/created","title":"DownloadState.created","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/created","role":"symbol","navigatorTitle":[{"text":"OVKDownloadStateCreated","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"OVKDownloadState"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/created","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/downloading","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/error","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/pending","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/suspended"],"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OVKDownloadState","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1suspended\/title","value":"OVKDownloadStateSuspended","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1suspended\/fragments","value":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1downloading\/title","op":"replace","value":"OVKDownloadStateDownloading"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1downloading\/fragments","value":[{"text":"OVKDownloadStateDownloading","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1pending\/title","op":"replace","value":"OVKDownloadStatePending"},{"op":"replace","value":[{"text":"OVKDownloadStatePending","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1pending\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1error\/title","value":"OVKDownloadStateError","op":"replace"},{"op":"replace","value":[{"text":"OVKDownloadStateError","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1error\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1finished\/title","op":"replace","value":"OVKDownloadStateFinished"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1finished\/fragments","value":[{"kind":"identifier","text":"OVKDownloadStateFinished"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","value":[{"kind":"identifier","text":"OVKDownloadState"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1created\/title","value":"OVKDownloadStateCreated"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1created\/fragments","value":[{"text":"OVKDownloadStateCreated","kind":"identifier"}]}]}]}