{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DurationView"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DurationView"}],"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)DurationView","modules":[{"name":"OVKit"}],"title":"DurationView"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DurationView"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/durationview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/durationview"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/normalHeight","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/selectedEpisodeHeight","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/timeCodes"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/setContentCornerRadius(_:)"],"anchor":"Instance-Methods"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DurationView/normalHeight":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/normalHeight","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/durationview\/normalheight","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"normalHeight"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","kind":"symbol","title":"DurationView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"}],"url":"\/documentation\/ovkit\/durationview","abstract":[],"role":"symbol","navigatorTitle":[{"text":"DurationView","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/setContentCornerRadius(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentCornerRadius","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/setContentCornerRadius(_:)","type":"topic","url":"\/documentation\/ovkit\/durationview\/setcontentcornerradius(_:)","role":"symbol","title":"setContentCornerRadius(_:)"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/selectedEpisodeHeight":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedEpisodeHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","url":"\/documentation\/ovkit\/durationview\/selectedepisodeheight","abstract":[],"title":"selectedEpisodeHeight","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/selectedEpisodeHeight"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/timeCodes":{"abstract":[{"type":"text","text":"Нужно хранить тайм-коды как они пришли в маске"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeCodes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/timeCodes","url":"\/documentation\/ovkit\/durationview\/timecodes","type":"topic","title":"timeCodes","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DurationView/layoutSubviews()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/layoutSubviews()","abstract":[],"url":"\/documentation\/ovkit\/durationview\/layoutsubviews()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"type":"topic","title":"layoutSubviews()"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DurationView","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DurationView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DurationView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView\/layoutSubviews()"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DurationView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DurationView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DurationView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments","op":"replace"},{"value":[{"text":"DurationView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle","op":"replace"},{"value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView~1layoutSubviews()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView~1layoutSubviews()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}