{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKEnvironment","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"navigatorTitle":[{"text":"Environment","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"OVKit"}],"title":"Environment"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsExternalPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/autoShowDiagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cacheCostLimit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cheatCodes","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDiagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableQualityAdaptationPolicy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRuntimeDebugDiagnostics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/logZeroWatchCoverage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/myTargetPlugin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/userId"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setMyTargetPlugin(_:)"],"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/av1ChromaShift","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/biPlanarPixelFormatNeon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/chromecastPlugin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAbrHarmonicCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAutoDisableLowLatencyTimeThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafLowLatencyMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/deviceId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disableCmafAudioStall","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enable60fps","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashCmaf","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashStallManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableNewHeaderParser","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enablePixelBufferPool","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRTMP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableVideo360","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/hdr","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/planarPixelFormat","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/qualityAdaptationPolicyChangedNotification","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/quicManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/shared","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/showPlayerDebugMenu","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKResources","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVPlayerKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/videoProxy"],"anchor":"Type-Properties","title":"Type Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setChromecastPlugin(_:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/environment"]},{"paths":["\/documentation\/ovkit\/environment"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"anchor":"Сервисы","title":"Сервисы","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKEnvironment) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment/av1ChromaShift":{"title":"av1ChromaShift","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/environment\/av1chromashift","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"av1ChromaShift","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/av1ChromaShift","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"av1ChromaShift"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Environment/versionOVKResources":{"title":"versionOVKResources","abstract":[{"text":"Current versionOVKResources = “2.74”","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/versionovkresources","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionOVKResources"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKResources","type":"topic","kind":"symbol","navigatorTitle":[{"text":"versionOVKResources","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/deviceId":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"deviceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/deviceId","url":"\/documentation\/ovkit\/environment\/deviceid","abstract":[{"text":"Уникальный идентификатор устройства, который не меняется до переустановки приложения.","type":"text"}],"role":"symbol","title":"deviceId"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"title":"AudioManager","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" при работе плееров."}],"role":"symbol","url":"\/documentation\/ovkit\/audiomanager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AudioManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/cmafAutoDisableLowLatencyTimeThreshold":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cmafAutoDisableLowLatencyTimeThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAutoDisableLowLatencyTimeThreshold","url":"\/documentation\/ovkit\/environment\/cmafautodisablelowlatencytimethreshold","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cmafAutoDisableLowLatencyTimeThreshold"}],"title":"cmafAutoDisableLowLatencyTimeThreshold"},"doc://onevideo.OVKit/documentation/OVKit/Environment/autoShowDiagnosticsView":{"title":"autoShowDiagnosticsView","abstract":[{"text":"Автоматический показ DiagnosticsView на всех плеерах после их создания. По умолчанию выключено.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/autoshowdiagnosticsview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoShowDiagnosticsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/autoShowDiagnosticsView","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoShowDiagnosticsView"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/versionOVKit":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionOVKit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKit","url":"\/documentation\/ovkit\/environment\/versionovkit","abstract":[{"type":"text","text":"Current versionOVKit = “5.36”"}],"role":"symbol","navigatorTitle":[{"text":"versionOVKit","kind":"identifier"}],"title":"versionOVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","role":"symbol","title":"PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistenceManager","kind":"identifier"}],"navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/allowsExternalPlayback":{"title":"allowsExternalPlayback","abstract":[{"text":"Разрешить ли воспроизведение на внешних устройствах. Необходимо установить сразу после запуска приложения. По умолчанию ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/allowsexternalplayback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowsExternalPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsExternalPlayback","type":"topic","kind":"symbol","navigatorTitle":[{"text":"allowsExternalPlayback","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/enablePixelBufferPool":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enablePixelBufferPool"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enablePixelBufferPool","url":"\/documentation\/ovkit\/environment\/enablepixelbufferpool","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enablePixelBufferPool"}],"title":"enablePixelBufferPool"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/Environment/planarPixelFormat":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"planarPixelFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/planarPixelFormat","url":"\/documentation\/ovkit\/environment\/planarpixelformat","abstract":[],"role":"symbol","navigatorTitle":[{"text":"planarPixelFormat","kind":"identifier"}],"title":"planarPixelFormat"},"doc://onevideo.OVKit/documentation/OVKit/Environment/setMyTargetPlugin(_:)":{"type":"topic","url":"\/documentation\/ovkit\/environment\/setmytargetplugin(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMyTargetPlugin"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Подключение плагина "},{"type":"codeVoice","code":"MyTarget"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setMyTargetPlugin(_:)","title":"setMyTargetPlugin(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setMyTargetPlugin:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/hdr":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hdr","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/hdr","url":"\/documentation\/ovkit\/environment\/hdr","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hdr"}],"title":"hdr"},"doc://onevideo.OVKit/documentation/OVKit/Environment/userId":{"type":"topic","url":"\/documentation\/ovkit\/environment\/userid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Идентификатор пользователя приложения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/userId","title":"userId","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"userId","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/biPlanarPixelFormatNeon":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"biPlanarPixelFormatNeon","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/biPlanarPixelFormatNeon","url":"\/documentation\/ovkit\/environment\/biplanarpixelformatneon","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"biPlanarPixelFormatNeon"}],"title":"biPlanarPixelFormatNeon"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableRTMP":{"type":"topic","url":"\/documentation\/ovkit\/environment\/enablertmp","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableRTMP","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRTMP","title":"enableRTMP","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"enableRTMP","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/videoProxy":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoProxy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)VideoProxyProtocol","text":"VideoProxyProtocol"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/videoProxy","url":"\/documentation\/ovkit\/environment\/videoproxy","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoProxy"}],"title":"videoProxy"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Environment/chromecastPlugin":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chromecastPlugin"},{"text":": ","kind":"text"},{"text":"ChromecastPlugin","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit16ChromecastPluginP"},{"text":"?","kind":"text"}],"title":"chromecastPlugin","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/chromecastPlugin","abstract":[{"type":"text","text":"Подключение плагина "},{"code":"ChromecastPlugin","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/environment\/chromecastplugin","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/quicManager":{"type":"topic","url":"\/documentation\/ovkit\/environment\/quicmanager","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"quicManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKQUICManagerProtocol","text":"QUICManagerProtocol"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/quicManager","title":"quicManager","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"quicManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableVideo360":{"navigatorTitle":[{"kind":"identifier","text":"enableVideo360"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableVideo360","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"enableVideo360","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableVideo360","abstract":[],"url":"\/documentation\/ovkit\/environment\/enablevideo360","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/shared":{"type":"topic","url":"\/documentation\/ovkit\/environment\/shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKEnvironment","text":"Environment","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/shared","title":"shared","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"url":"\/documentation\/ovkit\/playermanager","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/cmafAbrHarmonicCount":{"type":"topic","url":"\/documentation\/ovkit\/environment\/cmafabrharmoniccount","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cmafAbrHarmonicCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAbrHarmonicCount","title":"cmafAbrHarmonicCount","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cmafAbrHarmonicCount"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableDiagnosticsView":{"navigatorTitle":[{"text":"enableDiagnosticsView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableDiagnosticsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"enableDiagnosticsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDiagnosticsView","abstract":[{"type":"text","text":"Активирует возможность наблюдать за отладочными данными плеера."}],"url":"\/documentation\/ovkit\/environment\/enablediagnosticsview","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/cheatCodes":{"type":"topic","url":"\/documentation\/ovkit\/environment\/cheatcodes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cheatCodes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Значение нужно уметь устанавливать динамически в рамках одной сборки (получать из апи)."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cheatCodes","title":"cheatCodes","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cheatCodes"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"navigatorTitle":[{"kind":"identifier","text":"Environment"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Environment","kind":"identifier"}],"title":"Environment","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[],"url":"\/documentation\/ovkit\/environment","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Environment/logZeroWatchCoverage":{"navigatorTitle":[{"kind":"identifier","text":"logZeroWatchCoverage"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logZeroWatchCoverage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"logZeroWatchCoverage","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/logZeroWatchCoverage","abstract":[{"text":"Логирование пустых отрезков просмотра, например  ","type":"text"},{"type":"codeVoice","code":"[7 - 7]"},{"type":"text","text":". По умолчанию выключено."}],"url":"\/documentation\/ovkit\/environment\/logzerowatchcoverage","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableQualityAdaptationPolicy":{"type":"topic","url":"\/documentation\/ovkit\/environment\/enablequalityadaptationpolicy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableQualityAdaptationPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Включение\/выключение режима экономии трафика."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableQualityAdaptationPolicy","title":"enableQualityAdaptationPolicy","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"enableQualityAdaptationPolicy","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/allowsBackgroundPlayback":{"navigatorTitle":[{"kind":"identifier","text":"allowsBackgroundPlayback"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsBackgroundPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"allowsBackgroundPlayback","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","abstract":[{"type":"text","text":"Разрешить ли воспроизведение видео в фоне."}],"url":"\/documentation\/ovkit\/environment\/allowsbackgroundplayback","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/Environment/versionOVPlayerKit":{"navigatorTitle":[{"kind":"identifier","text":"versionOVPlayerKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"versionOVPlayerKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"versionOVPlayerKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVPlayerKit","abstract":[{"type":"text","text":"From OVPlayerKit.h"}],"url":"\/documentation\/ovkit\/environment\/versionovplayerkit","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableNewHeaderParser":{"type":"topic","url":"\/documentation\/ovkit\/environment\/enablenewheaderparser","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"enableNewHeaderParser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableNewHeaderParser","title":"enableNewHeaderParser","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"enableNewHeaderParser","kind":"identifier"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableRuntimeDebugDiagnostics":{"type":"topic","url":"\/documentation\/ovkit\/environment\/enableruntimedebugdiagnostics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableRuntimeDebugDiagnostics","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Включает сбор дополнительных параметров для отладки в реальном времени. По умолчанию включено только для DEBUG."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRuntimeDebugDiagnostics","title":"enableRuntimeDebugDiagnostics","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/Environment/setChromecastPlugin(_:)":{"type":"topic","url":"\/documentation\/ovkit\/environment\/setchromecastplugin(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setChromecastPlugin","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Подключение плагина "},{"type":"codeVoice","code":"ChromecastPlugin"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setChromecastPlugin(_:)","title":"setChromecastPlugin(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setChromecastPlugin:"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableDashStallManager":{"navigatorTitle":[{"text":"enableDashStallManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableDashStallManager","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"enableDashStallManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashStallManager","abstract":[],"url":"\/documentation\/ovkit\/environment\/enabledashstallmanager","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/disableCmafAudioStall":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableCmafAudioStall","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disableCmafAudioStall","url":"\/documentation\/ovkit\/environment\/disablecmafaudiostall","abstract":[],"role":"symbol","navigatorTitle":[{"text":"disableCmafAudioStall","kind":"identifier"}],"title":"disableCmafAudioStall"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enable60fps":{"navigatorTitle":[{"text":"enable60fps","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enable60fps","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"enable60fps","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enable60fps","abstract":[{"type":"text","text":"Включает возможность играть (если доступно) видео в 60 fps."}],"url":"\/documentation\/ovkit\/environment\/enable60fps","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/showPlayerDebugMenu":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showPlayerDebugMenu","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/showPlayerDebugMenu","url":"\/documentation\/ovkit\/environment\/showplayerdebugmenu","abstract":[{"type":"text","text":"Добавление новых пунктов в меню настроек. По умолчанию выключено."}],"role":"symbol","navigatorTitle":[{"text":"showPlayerDebugMenu","kind":"identifier"}],"title":"showPlayerDebugMenu"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableDashCmaf":{"navigatorTitle":[{"text":"enableDashCmaf","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"enableDashCmaf","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"enableDashCmaf","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashCmaf","abstract":[],"url":"\/documentation\/ovkit\/environment\/enabledashcmaf","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/myTargetPlugin":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"myTargetPlugin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit14MyTargetPluginP","text":"MyTargetPlugin","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/myTargetPlugin","url":"\/documentation\/ovkit\/environment\/mytargetplugin","abstract":[{"text":"Подключение плагина ","type":"text"},{"type":"codeVoice","code":"MyTarget"},{"type":"text","text":"."}],"role":"symbol","title":"myTargetPlugin"},"doc://onevideo.OVKit/documentation/OVKit/Environment/qualityAdaptationPolicyChangedNotification":{"navigatorTitle":[{"text":"qualityAdaptationPolicyChangedNotification","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"qualityAdaptationPolicyChangedNotification","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":"."},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"title":"qualityAdaptationPolicyChangedNotification","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/qualityAdaptationPolicyChangedNotification","abstract":[{"type":"text","text":"Уведомление отправляется при изменении настроек экономии трафика."}],"url":"\/documentation\/ovkit\/environment\/qualityadaptationpolicychangednotification","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Environment/cmafLowLatencyMode":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cmafLowLatencyMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafLowLatencyMode","url":"\/documentation\/ovkit\/environment\/cmaflowlatencymode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"cmafLowLatencyMode","kind":"identifier"}],"title":"cmafLowLatencyMode"},"doc://onevideo.OVKit/documentation/OVKit/Environment/cacheCostLimit":{"navigatorTitle":[{"kind":"identifier","text":"cacheCostLimit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cacheCostLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"cacheCostLimit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cacheCostLimit","abstract":[],"url":"\/documentation\/ovkit\/environment\/cachecostlimit","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKEnvironment","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsBackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/allowsExternalPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/autoShowDiagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cacheCostLimit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cheatCodes","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDiagnosticsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableQualityAdaptationPolicy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRuntimeDebugDiagnostics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/logZeroWatchCoverage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/userId"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setMyTargetPlugin(_:)"],"generated":true},{"title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/av1ChromaShift","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/biPlanarPixelFormatNeon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAbrHarmonicCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafAutoDisableLowLatencyTimeThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/cmafLowLatencyMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/disableCmafAudioStall","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enable60fps","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashCmaf","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableDashStallManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableNewHeaderParser","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enablePixelBufferPool","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableRTMP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableVideo360","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/hdr","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/planarPixelFormat","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/qualityAdaptationPolicyChangedNotification","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/quicManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/shared","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/showPlayerDebugMenu","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKResources","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/versionOVPlayerKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/videoProxy"],"generated":true,"anchor":"Type-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/setChromecastPlugin(_:)"],"anchor":"Type-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"title":"Сервисы","generated":true,"anchor":"Сервисы"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKEnvironment"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1av1ChromaShift\/title","op":"replace","value":"av1ChromaShift"},{"value":[{"text":"av1ChromaShift","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1av1ChromaShift\/fragments"},{"op":"replace","value":"versionOVKResources","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVKResources\/title"},{"value":[{"text":"versionOVKResources","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVKResources\/fragments"},{"value":"OVKAudioManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","value":[{"text":"OVKAudioManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","value":[{"text":"OVKAudioManager","kind":"identifier"}],"op":"replace"},{"value":"cmafAutoDisableLowLatencyTimeThreshold","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafAutoDisableLowLatencyTimeThreshold\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafAutoDisableLowLatencyTimeThreshold\/fragments","value":[{"text":"cmafAutoDisableLowLatencyTimeThreshold","kind":"identifier"}]},{"value":"autoShowDiagnosticsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1autoShowDiagnosticsView\/title","op":"replace"},{"value":[{"text":"autoShowDiagnosticsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1autoShowDiagnosticsView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVKit\/title","value":"versionOVKit"},{"value":[{"kind":"identifier","text":"versionOVKit"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVKit\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsExternalPlayback\/title","value":"allowsExternalPlayback","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsExternalPlayback\/fragments","value":[{"text":"allowsExternalPlayback","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enablePixelBufferPool\/title","value":"enablePixelBufferPool"},{"value":[{"text":"enablePixelBufferPool","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enablePixelBufferPool\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1planarPixelFormat\/title","value":"planarPixelFormat"},{"value":[{"kind":"identifier","text":"planarPixelFormat"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1planarPixelFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setMyTargetPlugin(_:)\/title","value":"setMyTargetPlugin:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setMyTargetPlugin(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMyTargetPlugin:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"hdr","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1hdr\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1hdr\/fragments","value":[{"text":"hdr","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1userId\/title","value":"userId"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1userId\/fragments","value":[{"text":"userId","kind":"identifier"}],"op":"replace"},{"value":"biPlanarPixelFormatNeon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1biPlanarPixelFormatNeon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"biPlanarPixelFormatNeon"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1biPlanarPixelFormatNeon\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRTMP\/title","op":"replace","value":"enableRTMP"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRTMP\/fragments","value":[{"kind":"identifier","text":"enableRTMP"}],"op":"replace"},{"op":"replace","value":"videoProxy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1videoProxy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"videoProxy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1videoProxy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1quicManager\/title","value":"quicManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1quicManager\/fragments","value":[{"text":"quicManager","kind":"identifier"}]},{"value":"enableVideo360","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableVideo360\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableVideo360\/fragments","value":[{"kind":"identifier","text":"enableVideo360"}]},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1shared\/title"},{"op":"replace","value":[{"kind":"identifier","text":"shared"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1shared\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace"},{"value":"cmafAbrHarmonicCount","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafAbrHarmonicCount\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafAbrHarmonicCount\/fragments","op":"replace","value":[{"text":"cmafAbrHarmonicCount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDiagnosticsView\/title","value":"enableDiagnosticsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDiagnosticsView\/fragments","op":"replace","value":[{"kind":"identifier","text":"enableDiagnosticsView"}]},{"op":"replace","value":"cheatCodes","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cheatCodes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cheatCodes"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cheatCodes\/fragments"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"kind":"identifier","text":"OVKEnvironment"}],"op":"replace"},{"value":[{"text":"OVKEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1logZeroWatchCoverage\/title","value":"logZeroWatchCoverage","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1logZeroWatchCoverage\/fragments","op":"replace","value":[{"kind":"identifier","text":"logZeroWatchCoverage"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableQualityAdaptationPolicy\/title","value":"enableQualityAdaptationPolicy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableQualityAdaptationPolicy\/fragments","op":"replace","value":[{"text":"enableQualityAdaptationPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/title","value":"allowsBackgroundPlayback"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1allowsBackgroundPlayback\/fragments","value":[{"text":"allowsBackgroundPlayback","kind":"identifier"}]},{"value":"versionOVPlayerKit","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVPlayerKit\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1versionOVPlayerKit\/fragments","value":[{"kind":"identifier","text":"versionOVPlayerKit"}],"op":"replace"},{"value":"enableNewHeaderParser","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableNewHeaderParser\/title"},{"value":[{"kind":"identifier","text":"enableNewHeaderParser"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableNewHeaderParser\/fragments","op":"replace"},{"op":"replace","value":"enableRuntimeDebugDiagnostics","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRuntimeDebugDiagnostics\/title"},{"op":"replace","value":[{"kind":"identifier","text":"enableRuntimeDebugDiagnostics"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableRuntimeDebugDiagnostics\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setChromecastPlugin(_:)\/title","value":"setChromecastPlugin:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setChromecastPlugin:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1setChromecastPlugin(_:)\/fragments"},{"op":"replace","value":"enableDashStallManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDashStallManager\/title"},{"value":[{"kind":"identifier","text":"enableDashStallManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDashStallManager\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1disableCmafAudioStall\/title","op":"replace","value":"disableCmafAudioStall"},{"value":[{"text":"disableCmafAudioStall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1disableCmafAudioStall\/fragments"},{"op":"replace","value":"enable60fps","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enable60fps\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enable60fps\/fragments","value":[{"kind":"identifier","text":"enable60fps"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1showPlayerDebugMenu\/title","op":"replace","value":"showPlayerDebugMenu"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1showPlayerDebugMenu\/fragments","value":[{"text":"showPlayerDebugMenu","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"enableDashCmaf","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDashCmaf\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableDashCmaf\/fragments","op":"replace","value":[{"kind":"identifier","text":"enableDashCmaf"}]},{"op":"replace","value":"qualityAdaptationPolicyChangedNotification","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1qualityAdaptationPolicyChangedNotification\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1qualityAdaptationPolicyChangedNotification\/fragments","value":[{"text":"qualityAdaptationPolicyChangedNotification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafLowLatencyMode\/title","value":"cmafLowLatencyMode","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cmafLowLatencyMode\/fragments","value":[{"text":"cmafLowLatencyMode","kind":"identifier"}],"op":"replace"},{"value":"cacheCostLimit","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cacheCostLimit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cacheCostLimit"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1cacheCostLimit\/fragments","op":"replace"}]}]}