{"abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)ErrorCoverView","navigatorTitle":[{"text":"ErrorCoverView","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"ErrorCoverView","role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCoverView"}]},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/init(frame:previewFrame:params:)"],"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/actionButtonTitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/errorMessageTitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/params","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/previewImageFrame"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleActionButton()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/willStartTransitioning()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/CoverViewType-Implementations"],"generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/errorcoverview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/errorcoverview"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCoverView","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Состоит из текста и кнопки, которые можно переопределить."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"references":{"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/previewImageFrame":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previewImageFrame"}],"url":"\/documentation\/ovkit\/errorcoverview\/previewimageframe","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/previewImageFrame","title":"previewImageFrame","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Информация о том, была ли загружена preview в момент показа "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/params":{"url":"\/documentation\/ovkit\/errorcoverview\/params","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"params","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/params","abstract":[],"title":"params","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIView"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/reloadVideo()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","kind":"symbol","navigatorTitle":[{"text":"reloadVideo","kind":"identifier"}],"role":"symbol","title":"reloadVideo()","abstract":[{"type":"text","text":"Перезагрузка видео."}],"url":"\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reloadVideo"},{"kind":"text","text":"()"}],"required":true},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/handleActionButton()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleActionButton()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleActionButton"}],"role":"symbol","title":"handleActionButton()","abstract":[{"type":"text","text":"Нажатию на кнопку действия. По умолчанию "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","isActive":true,"type":"reference"}],"url":"\/documentation\/ovkit\/errorcoverview\/handleactionbutton()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleActionButton"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/didEndTransitioning()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/didEndTransitioning()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didEndTransitioning"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didEndTransitioning"}],"title":"didEndTransitioning()","url":"\/documentation\/ovkit\/errorcoverview\/didendtransitioning()","kind":"symbol","type":"topic","abstract":[{"text":"Плеер закончил переезд на новую ","type":"text"},{"type":"codeVoice","code":"PlayerView"}]},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","abstract":[{"type":"text","text":"Ковер для показа ошибки воспроизведения."}],"type":"topic","title":"ErrorCoverView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCoverView"}],"url":"\/documentation\/ovkit\/errorcoverview"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/errorMessageTitle":{"abstract":[{"type":"text","text":"Текст сообщения об ошибке. По умолчанию "},{"code":"ovk_playback_error","type":"codeVoice"}],"title":"errorMessageTitle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/errorMessageTitle","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/errorcoverview\/errormessagetitle","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorMessageTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/coverControlsDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/coverControlsDelegate","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/errorcoverview\/covercontrolsdelegate","abstract":[{"text":"Делегат ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":". Устанавливать не нужно"}],"title":"coverControlsDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","text":"CoverControlsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"coverControlsDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/init(frame:previewFrame:params:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/init(frame:previewFrame:params:)","title":"init(frame:previewFrame:params:)","url":"\/documentation\/ovkit\/errorcoverview\/init(frame:previewframe:params:)","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"previewFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/handleCoverWithParams(_:)":{"title":"handleCoverWithParams(_:)","type":"topic","abstract":[{"type":"text","text":"Если "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" может отрисовать "},{"code":"ControlCoverType","type":"codeVoice"},{"text":", нужно обновить view и вернуть ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Если не может — будет запрошена новая "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":" или подставлена стандартная."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleCoverWithParams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/errorcoverview\/handlecoverwithparams(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleCoverWithParams(_:)","navigatorTitle":[{"kind":"identifier","text":"handleCoverWithParams:"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/actionButtonTitle":{"title":"actionButtonTitle","abstract":[{"text":"Текст для кнопки действия. По умолчанию  ","type":"text"},{"type":"codeVoice","code":"ovk_retry"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"actionButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/ovkit\/errorcoverview\/actionbuttontitle","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/actionButtonTitle","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/layoutSubviews()":{"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/errorcoverview\/layoutsubviews()","title":"layoutSubviews()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/init(coder:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/init(coder:)","url":"\/documentation\/ovkit\/errorcoverview\/init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"title":"init(coder:)"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/willStartTransitioning()":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willStartTransitioning","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/willStartTransitioning()","url":"\/documentation\/ovkit\/errorcoverview\/willstarttransitioning()","navigatorTitle":[{"text":"willStartTransitioning","kind":"identifier"}],"abstract":[{"code":"CoverView","type":"codeVoice"},{"text":" начал перемещаться в другое место на другой ","type":"text"},{"code":"PlayerView","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Здесь стоит скрыть UI элементы оставив только затемнение.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Если не реализовать метод, "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" будет полностью скрыт перед перемещением."}],"title":"willStartTransitioning()"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewType"}],"navigatorTitle":[{"kind":"identifier","text":"CoverViewType"}],"abstract":[],"url":"\/documentation\/ovkit\/coverviewtype","title":"CoverViewType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/CoverViewType-Implementations":{"url":"\/documentation\/ovkit\/errorcoverview\/coverviewtype-implementations","title":"CoverViewType Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/CoverViewType-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCoverView","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCoverView"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ErrorCoverView"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/previewImageFrame"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleActionButton()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/willStartTransitioning()"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCoverView"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1previewImageFrame\/title","value":"previewImageFrame","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1previewImageFrame\/fragments","value":[{"text":"previewImageFrame","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"reloadVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reloadVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/fragments"},{"value":"handleActionButton","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleActionButton()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleActionButton"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleActionButton()\/fragments"},{"op":"replace","value":"didEndTransitioning","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1didEndTransitioning()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1didEndTransitioning()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didEndTransitioning","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","value":"ErrorCoverView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","value":[{"kind":"identifier","text":"ErrorCoverView"}],"op":"replace"},{"value":[{"text":"ErrorCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle","op":"replace"},{"op":"replace","value":"coverControlsDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1coverControlsDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1coverControlsDelegate\/fragments","value":[{"kind":"identifier","text":"coverControlsDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleCoverWithParams(_:)\/title","value":"handleCoverWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleCoverWithParams(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleCoverWithParams:","kind":"identifier"}]},{"op":"replace","value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1layoutSubviews()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1layoutSubviews()\/fragments","op":"replace"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1init(coder:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","value":"willStartTransitioning","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1willStartTransitioning()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1willStartTransitioning()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willStartTransitioning","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","op":"replace","value":"OVKCoverViewType"},{"value":[{"kind":"identifier","text":"OVKCoverViewType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}