{"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKErrorType","title":"ErrorType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKErrorType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"languages":["swift"]}]}],"abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"sections":[],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"},"variants":[{"paths":["\/documentation\/ovkit\/errortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/errortype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/fatal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/informative","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/recoverable"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorType/init(rawValue:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/ovkit\/errortype\/init(rawvalue:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"title":"ErrorType","url":"\/documentation\/ovkit\/errortype","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/errortype\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/informative":{"kind":"symbol","title":"ErrorType.informative","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/informative","abstract":[{"type":"text","text":"Ошибка не влияет непосредственно на процесс воспроизведения, а сам процесс никак не прерывается."}],"url":"\/documentation\/ovkit\/errortype\/informative","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKErrorTypeInformative"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"informative"}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/recoverable":{"kind":"symbol","title":"ErrorType.recoverable","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/recoverable","url":"\/documentation\/ovkit\/errortype\/recoverable","abstract":[{"type":"text","text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше, но есть ссылки на запасные ресурсы и будет предпринята попытка их проиграть."}],"role":"symbol","navigatorTitle":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverable"}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/Equatable-Implementations","url":"\/documentation\/ovkit\/errortype\/equatable-implementations","kind":"article","title":"Equatable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/fatal":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"url":"\/documentation\/ovkit\/errortype\/fatal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/fatal","title":"ErrorType.fatal","role":"symbol","abstract":[{"type":"text","text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше. Ссылок на запасные ресурсы больше нет, пользователю в UI показывается ошибка воспроизведения."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKErrorType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/fatal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/informative","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/recoverable"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKErrorType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKErrorType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","op":"replace"},{"value":"OVKErrorTypeInformative","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1informative\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorTypeInformative"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1informative\/fragments","op":"replace"},{"value":"OVKErrorTypeRecoverable","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1recoverable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorTypeRecoverable"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1recoverable\/fragments","op":"replace"},{"value":"OVKErrorTypeFatal","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1fatal\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1fatal\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}