{"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"},"metadata":{"title":"Разное","modules":[{"name":"OVKit"}],"roleHeading":"Article","role":"article"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Дополнительные возможности."}],"seeAlsoSections":[{"title":"Концепты","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"anchor":"Концепты"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/extras"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/extras"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Picture in Picture","type":"heading","anchor":"Picture-in-Picture"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер по умолчанию поддерживает переход в режим “Картинка в картинке”. Чтобы плавающее окно могло поворачиваться за остальным приложением, необходимо поддержать Device Orientation в AppDelegate:"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {","    window! === PlayerManager.shared.pipWindow ? .allButUpsideDown : .portrait","}"]},{"anchor":"%D0%AD%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D0%B8%D1%8F-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0","level":2,"type":"heading","text":"Экономия трафика"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Режим экономии трафика позволяет загружать меньше данных по сети за счет уменьшения максимального качества видео. Режим можно включить через меню настроек плеера, однако он не будет сохраняться между запусками приложения."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Чтобы это сделать, необходимо при запуске приложения установить свойство "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableQualityAdaptationPolicy"},{"type":"text","text":", а при выходе из приложения сохранять его."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","url":"\/documentation\/ovkit\/fullscreen","kind":"article","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"title":"Полноэкранный режим","role":"article"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/plugins","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","title":"Плагины","abstract":[{"text":"Динамически подключаемые модули для расширения функциональности.","type":"text"}],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"type":"topic","kind":"article","url":"\/documentation\/ovkit\/prefetch","title":"Префетчер","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"url":"\/documentation\/ovkit\/controls","type":"topic","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","abstract":[{"text":"Кастомизация внешнего вида плеера.","type":"text"}],"role":"article","title":"Контролы плеера"},"doc://onevideo.OVKit/documentation/OVKit/Environment/enableQualityAdaptationPolicy":{"title":"enableQualityAdaptationPolicy","url":"\/documentation\/ovkit\/environment\/enablequalityadaptationpolicy","abstract":[{"text":"Включение\/выключение режима экономии трафика.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/enableQualityAdaptationPolicy","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableQualityAdaptationPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"enableQualityAdaptationPolicy","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"title":"Переходы между плеерами","url":"\/documentation\/ovkit\/transitions","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/statistics","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","title":"Статистика","abstract":[{"text":"Сбор статистики воспроизведения видео.","type":"text"}],"role":"article"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"role":"article","title":"Воспроизведение в фоне","url":"\/documentation\/ovkit\/backgroundplayback","type":"topic","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","abstract":[{"text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"title":"Концепты","anchor":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"enableQualityAdaptationPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableQualityAdaptationPolicy\/title","op":"replace"},{"value":[{"kind":"identifier","text":"enableQualityAdaptationPolicy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1enableQualityAdaptationPolicy\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}