{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/init(in:direction:stepSeconds:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/direction-swift.property","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/onRewind","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/stepSeconds"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/startAnimation(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/stopInteraction()"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/willHandle(point:in:)"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum"],"title":"Enumerations"}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fastrewindview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fastrewindview"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastRewindView"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OVKit"}],"title":"FastRewindView","roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)FastRewindView","symbolKind":"class","navigatorTitle":[{"text":"FastRewindView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FastRewindView","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/willHandle(point:in:)":{"abstract":[],"url":"\/documentation\/ovkit\/fastrewindview\/willhandle(point:in:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willHandle","kind":"identifier"},{"kind":"text","text":"("},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"FastRewindView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO","text":"Direction","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"willHandle(point:in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/willHandle(point:in:)","type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView":{"abstract":[],"url":"\/documentation\/ovkit\/fastrewindview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FastRewindView","kind":"identifier"}],"title":"FastRewindView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView","type":"topic","kind":"symbol","navigatorTitle":[{"text":"FastRewindView","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(cs)UIView":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIView","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/startAnimation(from:)":{"title":"startAnimation(from:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/fastrewindview\/startanimation(from:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/startAnimation(from:)","abstract":[]},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/stepSeconds":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stepSeconds","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","url":"\/documentation\/ovkit\/fastrewindview\/stepseconds","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/stepSeconds","abstract":[],"type":"topic","title":"stepSeconds"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/onRewind":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRewind","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"FastRewindView","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/fastrewindview\/onrewind","role":"symbol","title":"onRewind","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/onRewind"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/Direction-swift.enum":{"abstract":[],"url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Direction"}],"title":"FastRewindView.Direction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/Direction-swift.enum","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Direction"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/direction-swift.property":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/direction-swift.property","title":"direction","url":"\/documentation\/ovkit\/fastrewindview\/direction-swift.property","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"text":": ","kind":"text"},{"text":"FastRewindView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Direction","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/init(in:direction:stepSeconds:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"init(in:direction:stepSeconds:)","type":"topic","url":"\/documentation\/ovkit\/fastrewindview\/init(in:direction:stepseconds:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"direction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)FastRewindView","text":"FastRewindView"},{"text":".","kind":"text"},{"text":"Direction","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit14FastRewindViewC9DirectionO"},{"text":", ","kind":"text"},{"text":"stepSeconds","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/init(in:direction:stepSeconds:)"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/documentation/OVKit/FastRewindView/stopInteraction()":{"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FastRewindView\/stopInteraction()","title":"stopInteraction()","kind":"symbol","url":"\/documentation\/ovkit\/fastrewindview\/stopinteraction()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopInteraction"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"FastRewindView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"FastRewindView"}]},{"value":[{"kind":"identifier","text":"FastRewindView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FastRewindView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/title","value":"FastRewindView","op":"replace"},{"value":[{"kind":"identifier","text":"FastRewindView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FastRewindView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}