{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/frame","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollCallback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/stopCallback"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollToProgress(_:)"],"anchor":"Instance-Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UICollectionViewDataSource-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UIScrollViewDelegate-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UICollectionView"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDataSource","doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDataSourceTranslating","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/objc(pl)UIScrollViewDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/filmstriptimeline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/filmstriptimeline"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)FilmStripTimeline","roleHeading":"Class","title":"FilmStripTimeline","symbolKind":"class"},"references":{"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline","kind":"symbol","title":"FilmStripTimeline","role":"symbol","navigatorTitle":[{"text":"FilmStripTimeline","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/ovkit\/filmstriptimeline","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/stopCallback":{"abstract":[],"title":"stopCallback","url":"\/documentation\/ovkit\/filmstriptimeline\/stopcallback","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCallback"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/stopCallback","role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/init(thumbnailProvider:)":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","kind":"typeIdentifier","text":"ThumbnailProvider"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/init(thumbnailProvider:)","type":"topic","title":"init(thumbnailProvider:)","url":"\/documentation\/ovkit\/filmstriptimeline\/init(thumbnailprovider:)"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UIDataSourceTranslating":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDataSourceTranslating","title":"UIKit.UIDataSourceTranslating"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","title":"Swift.Copyable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(cs)UICollectionView":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UICollectionView","title":"UICollectionView"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/UIScrollViewDelegate-Implementations":{"title":"UIScrollViewDelegate Implementations","url":"\/documentation\/ovkit\/filmstriptimeline\/uiscrollviewdelegate-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UIScrollViewDelegate-Implementations","role":"collectionGroup","abstract":[],"kind":"article"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollToProgress(_:)":{"role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollToProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/filmstriptimeline\/scrolltoprogress(_:)","title":"scrollToProgress(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollToProgress(_:)"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/UICollectionViewDataSource-Implementations":{"title":"UICollectionViewDataSource Implementations","url":"\/documentation\/ovkit\/filmstriptimeline\/uicollectionviewdatasource-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UICollectionViewDataSource-Implementations","role":"collectionGroup","abstract":[],"kind":"article"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(pl)UIFocusItemScrollableContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemScrollableContainer","type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/frame":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"title":"frame","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/frame","navigatorTitle":[{"text":"frame","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/filmstriptimeline\/frame"},"doc://onevideo.OVKit/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDataSource","title":"UICollectionViewDataSource"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UISpringLoadedInteractionSupporting","title":"UIKit.UISpringLoadedInteractionSupporting"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/FilmStripTimeline/scrollCallback":{"url":"\/documentation\/ovkit\/filmstriptimeline\/scrollcallback","title":"scrollCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollCallback"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/scrollCallback","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDelegate","title":"UICollectionViewDelegate"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"FilmStripTimeline"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"FilmStripTimeline","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"FilmStripTimeline"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/frame"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UICollectionViewDataSource-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FilmStripTimeline\/UIScrollViewDelegate-Implementations"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UICollectionView"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDataSource","doc:\/\/onevideo.OVKit\/objc(pl)UICollectionViewDelegate"],"title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FilmStripTimeline","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/title","value":"FilmStripTimeline"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/fragments","value":[{"kind":"identifier","text":"FilmStripTimeline"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline\/navigatorTitle","value":[{"text":"FilmStripTimeline","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1frame\/title","value":"frame"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FilmStripTimeline~1frame\/fragments","value":[{"text":"frame","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}