{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом."}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"]}],"metadata":{"title":"FullscreenInteractiveDismissAvailability","navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInAllOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/disabled"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKFullscreenInteractiveDismissAvailability) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/disabled":{"title":"FullscreenInteractiveDismissAvailability.disabled","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/disabled","navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityDisabled","kind":"identifier"}],"type":"topic","abstract":[{"text":"Выключает механику интерактивного закрытия.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/disabled","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/equatable-implementations","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/rawrepresentable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","title":"FullscreenInteractiveDismissAvailability","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/allowedInSupportedOrientations":{"abstract":[{"text":"Разрешает интерактивное закрытие только в поддерживаемых ориентациях.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinsupportedorientations","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedInSupportedOrientations","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}],"type":"topic","title":"FullscreenInteractiveDismissAvailability.allowedInSupportedOrientations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/init(rawValue:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/allowedInAllOrientations":{"title":"FullscreenInteractiveDismissAvailability.allowedInAllOrientations","navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedInAllOrientations","kind":"identifier"}],"abstract":[{"type":"text","text":"Разрешает интерактивное закрытие в любой ориентации на любом устройстве."}],"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinallorientations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInAllOrientations","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OVKFullscreenInteractiveDismissAvailability"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInAllOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/disabled"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1disabled\/title","op":"replace","value":"OVKFullscreenInteractiveDismissAvailabilityDisabled"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1disabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityDisabled"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","op":"replace","value":"OVKFullscreenInteractiveDismissAvailability"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments","op":"replace","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/title","op":"replace","value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/fragments","op":"replace","value":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInAllOrientations\/title","op":"replace","value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInAllOrientations\/fragments","op":"replace","value":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations","kind":"identifier"}]}]}]}