{"kind":"symbol","abstract":[{"text":"Способ закрытия полноэкранного режима.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"externalID":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod","role":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerDismissMethod","kind":"identifier"}],"title":"FullscreenViewControllerDismissMethod"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/deviceRotation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/swipe"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKFullscreenViewControllerDismissMethod) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/equatable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/swipe":{"navigatorTitle":[{"text":"OVKFullscreenViewControllerDismissMethodSwipe","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/swipe","title":"FullscreenViewControllerDismissMethod.swipe","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/swipe","type":"topic","role":"symbol","abstract":[{"text":"Свайпом по экрану.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipe","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/other":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/other","kind":"symbol","type":"topic","title":"FullscreenViewControllerDismissMethod.other","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/other","abstract":[{"text":"Другой способ (обычно нажатие на кнопку или из кода).","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodOther"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"abstract":[{"text":"Способ закрытия полноэкранного режима.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","kind":"symbol","title":"FullscreenViewControllerDismissMethod","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/init(rawValue:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/deviceRotation":{"navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodDeviceRotation"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/devicerotation","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/deviceRotation","type":"topic","title":"FullscreenViewControllerDismissMethod.deviceRotation","role":"symbol","kind":"symbol","abstract":[{"text":"Поворотом устройства (обычно из ландшафта в портрет).","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceRotation"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OVKFullscreenViewControllerDismissMethod"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/deviceRotation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/swipe"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1swipe\/title","value":"OVKFullscreenViewControllerDismissMethodSwipe"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1swipe\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodSwipe"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1other\/title","value":"OVKFullscreenViewControllerDismissMethodOther","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1other\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodOther"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","value":"OVKFullscreenViewControllerDismissMethod","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1deviceRotation\/title","value":"OVKFullscreenViewControllerDismissMethodDeviceRotation","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1deviceRotation\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodDeviceRotation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}