{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"externalID":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","title":"FullscreenViewControllerVisualStyle","symbolKind":"enum","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}]},"abstract":[{"text":"Вид отображения полноэкранного контроллера.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rectangular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rounded"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"kind":"symbol","type":"topic","title":"FullscreenViewControllerVisualStyle","abstract":[{"type":"text","text":"Вид отображения полноэкранного контроллера."}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/rounded":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rounded","abstract":[{"type":"text","text":"Плеер отображается в прямоугольной области со скругленными углами"},{"text":" ","type":"text"},{"type":"text","text":"с размерами, ограниченными максимальной стороной и соотношением сторон плеера."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rounded","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenViewControllerVisualStyleRounded","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rounded","title":"FullscreenViewControllerVisualStyle.rounded","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/Equatable-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/rectangular":{"kind":"symbol","type":"topic","title":"FullscreenViewControllerVisualStyle.rectangular","abstract":[{"text":"Плеер отображается в прямоугольной области максимально доступного размера.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/rectangular","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectangular","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rectangular","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRectangular"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle\/init(rawvalue:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/init(rawValue:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"FullscreenViewControllerVisualStyle","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rectangular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle\/rounded"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","value":"FullscreenViewControllerVisualStyle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","value":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rounded\/title","value":"FullscreenViewControllerVisualStyleRounded","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyleRounded"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rounded\/fragments"},{"op":"replace","value":"FullscreenViewControllerVisualStyleRectangular","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rectangular\/title"},{"op":"replace","value":[{"text":"FullscreenViewControllerVisualStyleRectangular","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle~1rectangular\/fragments"}]}]}