{"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIContentContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/objc(pl)UIStateRestoring","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreencontentviewcontroller"]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"FullscreenContentViewController","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}]},"sections":[],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/allowFullscreenDismissByDeviceRotation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/contentView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismissMethod","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/enableKeyboardObserver","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/hideKeyboardGestureRecognizer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/interactiveDismissAvailability","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/keyCommands","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredInterfaceOrientationForPresentation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredStatusBarStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersHomeIndicatorAutoHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersStatusBarHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/shouldAutorotate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supportedInterfaceOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/swipeDownBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/visualStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wrapped"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/detachFromOriginPlayerView()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/didMove(toParent:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismiss(animated:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/loadView()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setNeedsUIAppearanceUpdate()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/traitCollectionDidChange(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidAppear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidDisappear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidLoad()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewIsAppearing(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillDisappear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillTransition(to:with:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/FullscreenViewControllerProtocol-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/UIGestureRecognizerDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKFullscreenContentViewController) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"},"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/UIGestureRecognizerDelegate-Implementations","abstract":[],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/uigesturerecognizerdelegate-implementations","kind":"article"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/prefersStatusBarHidden":{"role":"symbol","abstract":[],"kind":"symbol","title":"prefersStatusBarHidden","navigatorTitle":[{"kind":"identifier","text":"prefersStatusBarHidden"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersStatusBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/prefersstatusbarhidden","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersStatusBarHidden","type":"topic"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/playerView":{"navigatorTitle":[{"text":"playerView","kind":"identifier"}],"title":"playerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/playerview","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"}],"abstract":[{"text":"Плеер, играющий в полноэкранном режиме.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/interactiveDismissAvailability":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/interactiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/interactivedismissavailability","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interactiveDismissAvailability","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenInteractiveDismissAvailability","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability"}],"navigatorTitle":[{"text":"interactiveDismissAvailability","kind":"identifier"}],"kind":"symbol","title":"interactiveDismissAvailability","role":"symbol","abstract":[{"type":"text","text":"Доступность закрытия полноэкранного режима свайпом вниз."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","type":"topic","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidAppear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewdidappear(_:)","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/shouldAutorotate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/shouldAutorotate","title":"shouldAutorotate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldAutorotate"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAutorotate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/shouldautorotate","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/enableKeyboardObserver":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/enableKeyboardObserver","navigatorTitle":[{"text":"enableKeyboardObserver","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableKeyboardObserver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"enableKeyboardObserver","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/enablekeyboardobserver","abstract":[{"text":"Включение\/выключение механизма слежения за клавиатурой.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/swipeDownBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/swipeDownBehavior","navigatorTitle":[{"text":"swipeDownBehavior","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeDownBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior","text":"FullscreenSwipeGestureBehavior","kind":"typeIdentifier"}],"title":"swipeDownBehavior","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/swipedownbehavior","abstract":[{"type":"text","text":"Поведение при свайпе вниз в полноэкранном режиме."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/dismiss(animated:completion:)":{"role":"symbol","title":"dismiss(animated:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismiss(animated:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/dismiss(animated:completion:)","kind":"symbol"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/visualStyle":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/visualstyle","abstract":[{"type":"text","text":"Стиль плеера в полноэкранном режиме."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visualStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/visualStyle","title":"visualStyle","role":"symbol","navigatorTitle":[{"text":"visualStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/hideKeyboardGestureRecognizer":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/hidekeyboardgesturerecognizer","abstract":[{"type":"text","text":"Жест для скрытия клавиатуры."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideKeyboardGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/hideKeyboardGestureRecognizer","title":"hideKeyboardGestureRecognizer","role":"symbol","navigatorTitle":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"title":"FullscreenViewControllerProtocol","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/keyCommands":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/keyCommands","navigatorTitle":[{"text":"keyCommands","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyCommands","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIKeyCommand","text":"UIKeyCommand","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"keyCommands","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/keycommands","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/s8CopyableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewWillTransition(to:with:)":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewwilltransition(to:with:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillTransition(to:with:)","title":"viewWillTransition(to:with:)","role":"symbol","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/supportedInterfaceOrientations":{"abstract":[],"title":"supportedInterfaceOrientations","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedInterfaceOrientations","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/supportedinterfaceorientations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supportedInterfaceOrientations"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewIsAppearing(_:)":{"navigatorTitle":[{"text":"viewIsAppearing:","kind":"identifier"}],"title":"viewIsAppearing(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewIsAppearing(_:)","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewisappearing(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewIsAppearing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewWillDisappear(_:)":{"abstract":[],"title":"viewWillDisappear(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewwilldisappear(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillDisappear(_:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/loadView()":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/loadview()","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadView","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/loadView()","title":"loadView()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadView"}]},"doc://onevideo.OVKit/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIViewController"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"title":"FullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/contentView":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/contentview","type":"topic","abstract":[{"type":"text","text":"View для полноэкранного контроллера."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenContentView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentView","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/contentView","title":"contentView","role":"symbol","navigatorTitle":[{"text":"contentView","kind":"identifier"}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/traitCollectionDidChange(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/traitcollectiondidchange(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/traitCollectionDidChange(_:)","abstract":[],"title":"traitCollectionDidChange(_:)","type":"topic","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/FullscreenViewControllerProtocol-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/FullscreenViewControllerProtocol-Implementations","title":"FullscreenViewControllerProtocol Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/fullscreenviewcontrollerprotocol-implementations","abstract":[]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/detachFromOriginPlayerView()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachFromOriginPlayerView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/detachfromoriginplayerview()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/detachFromOriginPlayerView()","abstract":[{"text":"Отвязывает полноэкранный плеер от места, из которого он был открыт.","type":"text"}],"title":"detachFromOriginPlayerView()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detachFromOriginPlayerView"}]},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewDidLoad()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewdidload()","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/allowFullscreenDismissByDeviceRotation":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/allowfullscreendismissbydevicerotation","abstract":[{"type":"text","text":"Разрешает автоматический выход из полноэкранного режима плеера при повороте устройства."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowFullscreenDismissByDeviceRotation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/allowFullscreenDismissByDeviceRotation","title":"allowFullscreenDismissByDeviceRotation","role":"symbol","navigatorTitle":[{"text":"allowFullscreenDismissByDeviceRotation","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/setNeedsUIAppearanceUpdate()":{"role":"symbol","title":"setNeedsUIAppearanceUpdate()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setNeedsUIAppearanceUpdate()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNeedsUIAppearanceUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/setneedsuiappearanceupdate()","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/wrapped":{"role":"symbol","title":"wrapped","type":"topic","navigatorTitle":[{"text":"wrapped","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wrapped","abstract":[{"text":"Контроллер, который необходимо обернуть.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrapped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/wrapped","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/preferredStatusBarStyle":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/preferredstatusbarstyle","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier","text":"UIStatusBarStyle"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredStatusBarStyle","title":"preferredStatusBarStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/preferredInterfaceOrientationForPresentation":{"role":"symbol","title":"preferredInterfaceOrientationForPresentation","type":"topic","navigatorTitle":[{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredInterfaceOrientationForPresentation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredInterfaceOrientationForPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/preferredinterfaceorientationforpresentation","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/viewDidDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"title":"viewDidDisappear(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidDisappear(_:)","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/viewdiddisappear(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/supplementaryViewController":{"navigatorTitle":[{"text":"supplementaryViewController","kind":"identifier"}],"title":"supplementaryViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/supplementaryviewcontroller","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementaryViewController","kind":"identifier"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/wasPresentedForSupplementaryController":{"navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"title":"wasPresentedForSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/waspresentedforsupplementarycontroller","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wasPresentedForSupplementaryController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Был ли контроллер презентован одновременно с добавлением ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/dismissMethod":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/dismissmethod","abstract":[{"type":"text","text":"Способ, которым полноэкранный режим начал закрываться."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod","text":"FullscreenViewControllerDismissMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismissMethod","title":"dismissMethod","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dismissMethod"}]},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/didMove(toParent:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toParent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/didmove(toparent:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/didMove(toParent:)","abstract":[],"title":"didMove(toParent:)","type":"topic","navigatorTitle":[{"text":"didMoveToParentViewController:","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/prefersHomeIndicatorAutoHidden":{"navigatorTitle":[{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"}],"title":"prefersHomeIndicatorAutoHidden","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersHomeIndicatorAutoHidden","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/prefershomeindicatorautohidden","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"type":"topic"},"doc://onevideo.OVKit/s16SendableMetatypeP":{"identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKFullscreenContentViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/allowFullscreenDismissByDeviceRotation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/contentView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismissMethod","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/enableKeyboardObserver","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/hideKeyboardGestureRecognizer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/interactiveDismissAvailability","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/keyCommands","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredInterfaceOrientationForPresentation","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/preferredStatusBarStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersHomeIndicatorAutoHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/prefersStatusBarHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/shouldAutorotate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supportedInterfaceOrientations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/swipeDownBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/visualStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wrapped"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/detachFromOriginPlayerView()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/didMove(toParent:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/dismiss(animated:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/loadView()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/traitCollectionDidChange(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidAppear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidDisappear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewDidLoad()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewIsAppearing(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillDisappear(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/FullscreenViewControllerProtocol-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/UIGestureRecognizerDelegate-Implementations"],"title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIViewController"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKFullscreenContentViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1prefersStatusBarHidden\/title","value":"prefersStatusBarHidden"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1prefersStatusBarHidden\/fragments","value":[{"text":"prefersStatusBarHidden","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/title","value":"playerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/fragments","value":[{"text":"playerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1interactiveDismissAvailability\/title","value":"interactiveDismissAvailability"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1interactiveDismissAvailability\/fragments","value":[{"text":"interactiveDismissAvailability","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1shouldAutorotate\/title","value":"shouldAutorotate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1shouldAutorotate\/fragments","value":[{"text":"shouldAutorotate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1enableKeyboardObserver\/title","value":"enableKeyboardObserver"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1enableKeyboardObserver\/fragments","value":[{"text":"enableKeyboardObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1swipeDownBehavior\/title","value":"swipeDownBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1swipeDownBehavior\/fragments","value":[{"text":"swipeDownBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismiss(animated:completion:)\/title","value":"dismissViewControllerAnimated:completion:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismiss(animated:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismissViewControllerAnimated:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1visualStyle\/title","value":"visualStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1visualStyle\/fragments","value":[{"text":"visualStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1hideKeyboardGestureRecognizer\/title","value":"hideKeyboardGestureRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1hideKeyboardGestureRecognizer\/fragments","value":[{"text":"hideKeyboardGestureRecognizer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title","value":"OVKFullscreenViewControllerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","value":[{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle","value":[{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1keyCommands\/title","value":"keyCommands"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1keyCommands\/fragments","value":[{"text":"keyCommands","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillTransition(to:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supportedInterfaceOrientations\/title","value":"supportedInterfaceOrientations"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supportedInterfaceOrientations\/fragments","value":[{"text":"supportedInterfaceOrientations","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewIsAppearing(_:)\/title","value":"viewIsAppearing:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewIsAppearing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewIsAppearing:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1loadView()\/title","value":"loadView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1loadView()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title","value":"OVKFullscreenContentViewController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1contentView\/title","value":"contentView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1contentView\/fragments","value":[{"text":"contentView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1detachFromOriginPlayerView()\/title","value":"detachFromOriginPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1detachFromOriginPlayerView()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detachFromOriginPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1allowFullscreenDismissByDeviceRotation\/title","value":"allowFullscreenDismissByDeviceRotation"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1allowFullscreenDismissByDeviceRotation\/fragments","value":[{"text":"allowFullscreenDismissByDeviceRotation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wrapped\/title","value":"wrapped"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wrapped\/fragments","value":[{"text":"wrapped","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1preferredStatusBarStyle\/fragments","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1preferredInterfaceOrientationForPresentation\/title","value":"preferredInterfaceOrientationForPresentation"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1preferredInterfaceOrientationForPresentation\/fragments","value":[{"text":"preferredInterfaceOrientationForPresentation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1viewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/title","value":"supplementaryViewController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/fragments","value":[{"text":"supplementaryViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/title","value":"wasPresentedForSupplementaryController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/fragments","value":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismissMethod\/title","value":"dismissMethod"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1dismissMethod\/fragments","value":[{"text":"dismissMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1didMove(toParent:)\/title","value":"didMoveToParentViewController:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1didMove(toParent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToParentViewController:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1prefersHomeIndicatorAutoHidden\/title","value":"prefersHomeIndicatorAutoHidden"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1prefersHomeIndicatorAutoHidden\/fragments","value":[{"text":"prefersHomeIndicatorAutoHidden","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}