{"seeAlsoSections":[{"title":"Начало работы","generated":true,"anchor":"Начало-работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"]}],"abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"Полноэкранный режим","role":"article","roleHeading":"Article","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreen"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreen"]}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"inlineContent":[{"text":"Контролы плеера в полноэкранном режиме необходимо задать через делегат менеджера плееров ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)"},{"text":". Эти контролы должны реализовывать протокол ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol","type":"reference"},{"type":"text","text":", который является небольшим расширением базового протокола контролов "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"level":2,"text":"Обертка полноэкранного контроллера","anchor":"%D0%9E%D0%B1%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80%D0%B0","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Некоторые приложения требуют, чтобы все показываемые контроллеры наследовались от одного базового класса. По умолчанию OVKit показывает наследника "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":". Это можно изменить, вернув в методе "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","type":"reference"},{"text":" экземпляр контроллера-обертки необходимого класса. Возвращаемый контроллер обязан реализовывать протокол ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Контроллер-обертка "},{"type":"strong","inlineContent":[{"type":"text","text":"обязан добавить"}]},{"type":"text","text":" контент полноэкранного контроллера ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped"},{"type":"text","text":") как child view controller перед показом на экране и управлять его layout, растянув на максимальный размер. Контроллер-обертка "},{"type":"strong","inlineContent":[{"text":"обязан сообщать","type":"text"}]},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped","isActive":true},{"type":"text","text":" о всех событиях своего жизненного цикла и предпочтениях внешнего вида, которые не проксируются стандартными механизмами UIKit. Контроллер-обертка должен реализовывать только ту логику, которая необходима для функционирования навигации внутри приложения. На него не стоит добавлять дополнительные "},{"code":"UIView","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Пример настройки контроллера-обертки:","type":"text"}]},{"syntax":"objc","code":["#pragma mark - Life Cycle","","- (void)viewDidLoad {","    [super viewDidLoad];","    ","    [self addChildViewController:self.wrapped];","    [self.view addSubview:self.wrapped.view];","    [self.wrapped didMoveToParentViewController:self];","}","","- (void)viewWillLayoutSubviews {","    [super viewWillLayoutSubviews];","    ","    self.wrapped.view.frame = self.view.bounds;","}","","#pragma mark - Appearance","","- (BOOL)prefersStatusBarHidden {","    return self.wrapped.prefersStatusBarHidden;","}","","- (UIStatusBarAnimation)preferredStatusBarUpdateAnimation {","    return self.wrapped.preferredStatusBarUpdateAnimation;","}","","- (UIStatusBarStyle)preferredStatusBarStyle {","    return self.wrapped.preferredStatusBarStyle;","}","","- (BOOL)prefersHomeIndicatorAutoHidden {","    return self.wrapped.prefersHomeIndicatorAutoHidden;","}","","- (UIInterfaceOrientationMask)supportedInterfaceOrientations {","    return self.wrapped.supportedInterfaceOrientations;","}","","- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {","    return self.wrapped.preferredInterfaceOrientationForPresentation;","}","","- (BOOL)shouldAutorotate {","    return self.wrapped.shouldAutorotate;","}","","- (OVKPlayerView *)playerView {","    return self.wrapped.playerView;","}","","- (void)setSupplementaryViewController:(UIViewController<OVKFullscreenSupplementaryController> * _Nullable)controller animated:(BOOL)animated {","    [self.wrapped setSupplementaryViewController:controller animated:animated];","}","","- (enum FullscreenViewControllerVisualStyle)visualStyle {","    return self.wrapped.visualStyle;","}","","- (void)setVisualStyle:(enum FullscreenViewControllerVisualStyle)visualStyle {","    self.wrapped.visualStyle = visualStyle;","}"],"type":"codeListing"}]}],"kind":"article","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"abstract":[],"role":"article","type":"topic","title":"Создание Контролов","url":"\/documentation\/ovkit\/controls","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol","title":"PlayerFullscreenControlsViewProtocol","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Протокол для контролов, которые могут использоваться в полноэкранном режиме проигрывания."}],"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"kind":"article","abstract":[{"type":"text","text":"Руководство для первого подключения "},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":" к проекту. Эти шаги необходимо выполнить перед началом работы."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","role":"article","title":"Быстрый старт","url":"\/documentation\/ovkit\/quickstart"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowFullscreen:)":{"abstract":[{"text":"Плеер был показан в полноэкранном режиме.","type":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerView:willShowFullscreen:"}],"title":"playerView(_:willShowFullscreen:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"willShowFullscreen","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"text":"?","kind":"text"}],"role":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenControls(for:originPlayerView:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenControls","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"text":"?, ","kind":"text"},{"text":"originPlayerView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"abstract":[{"text":"Определить для возможности использования собственных контролов в полноэкранном режиме.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","role":"symbol","kind":"symbol","title":"fullscreenControls(for:originPlayerView:)","navigatorTitle":[{"text":"fullscreenControlsFor:originPlayerView:","kind":"identifier"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"kind":"article","url":"\/documentation\/ovkit\/extras","abstract":[{"type":"text","text":"Дополнительные возможности "},{"type":"codeVoice","code":"OVKit"},{"text":".","type":"text"}],"type":"topic","title":"Дополнительно","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"abstract":[{"type":"codeVoice","code":"OVKit"},{"type":"text","text":" поддерживает воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"role":"article","type":"topic","title":"Воспроизведение в фоне","url":"\/documentation\/ovkit\/backgroundplayback","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","abstract":[{"type":"text","text":"Контроллер, который используется для полноэкранного просмотра."}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","type":"topic","kind":"symbol","title":"FullscreenViewControllerProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenViewControllerProtocol"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/wrapped":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/wrapped","navigatorTitle":[{"text":"wrapped","kind":"identifier"}],"abstract":[{"type":"text","text":"Контроллер, который необходимо обернуть."}],"title":"wrapped","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped","required":true,"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"kind":"article","url":"\/documentation\/ovkit\/statistics","abstract":[{"type":"text","text":"SDK поддерживает сбор статистики по воспроизведению видео."}],"type":"topic","title":"Статистика","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"abstract":[{"text":"Плагины позволяют расширить функциональность ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"article","url":"\/documentation\/ovkit\/plugins","title":"Плагины","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","kind":"symbol","abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","title":"PlayerControlsViewProtocol"},"doc://onevideo.OVKit/documentation/OVKit/gRPC":{"title":"gRPC","abstract":[],"role":"article","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","url":"\/documentation\/ovkit\/grpc","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"kind":"article","url":"\/documentation\/ovkit\/prefetch","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"type":"topic","title":"Префетчер","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"abstract":[{"text":"Первые шаги после интеграции.","type":"text"}],"role":"article","type":"topic","title":"Создание плеера","url":"\/documentation\/ovkit\/createplayer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"generated":true,"title":"Начало работы","anchor":"Начало-работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"]}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/title","op":"replace","value":"playerView:willShowFullscreen:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowFullscreen:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/title","op":"replace","value":"fullscreenControlsFor:originPlayerView:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title","value":"OVKFullscreenViewControllerProtocol","op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1wrapped\/title","value":"wrapped"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1wrapped\/fragments","value":[{"kind":"identifier","text":"wrapped"}]}]}]}