{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol"]},{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/playerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/visualStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/setSupplementaryViewController(_:animated:)"],"title":"Instance Methods","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKFullscreenViewControllerProtocol) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"Это может быть любой клиентский контроллер. Он обязан:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Проксировать все свойства и методы во "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Добавить себе ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped"},{"text":" как child после загрузки view.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Проксировать методы поведения и appearance "},{"type":"codeVoice","code":"UIViewController"},{"text":" во ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped","isActive":true},{"text":" (такие как ","type":"text"},{"code":"shouldAutorotate","type":"codeVoice"},{"type":"text","text":" и т.д.)."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol","symbolKind":"protocol","title":"FullscreenViewControllerProtocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/setSupplementaryViewController(_:animated:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/setSupplementaryViewController(_:animated:)","role":"symbol","title":"setSupplementaryViewController(_:animated:)","abstract":[{"type":"text","text":"Метод обернутого контроллера: "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","isActive":true},{"text":".","type":"text"}],"required":true,"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/setsupplementaryviewcontroller(_:animated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSupplementaryViewController"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController"},{"text":")?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSupplementaryViewController:animated:"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"title":"FullscreenContentViewController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenContentViewController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/playerView":{"kind":"symbol","title":"playerView","abstract":[{"text":"Плеер, играющий в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"text":"playerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView","role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/playerview","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/setSupplementaryViewController(_:animated:)":{"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/setsupplementaryviewcontroller(_:animated:)","title":"setSupplementaryViewController(_:animated:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Установка "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSupplementaryViewController"},{"text":"((","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/wrapped":{"type":"topic","required":true,"abstract":[{"text":"Контроллер, который необходимо обернуть.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped","title":"wrapped","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/wrapped","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"wrapped","kind":"identifier"},{"kind":"text","text":": "},{"text":"FullscreenContentViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"}],"navigatorTitle":[{"kind":"identifier","text":"wrapped"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/visualStyle":{"required":true,"abstract":[{"text":"Стиль отображения для ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" внутри контроллера"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/visualStyle","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/visualstyle","title":"visualStyle","navigatorTitle":[{"text":"visualStyle","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"role":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"title":"FullscreenViewControllerProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"type":"topic","abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/playerView":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/playerview","navigatorTitle":[{"text":"playerView","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","required":true,"title":"playerView","abstract":[{"type":"text","text":"Свойство обернутого контроллера: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/playerView"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"OVKFullscreenViewControllerProtocol","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}]},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/playerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/visualStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/wrapped"],"title":"Instance Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/setSupplementaryViewController(_:animated:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1setSupplementaryViewController(_:animated:)\/title","value":"setSupplementaryViewController:animated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1setSupplementaryViewController(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setSupplementaryViewController:animated:","kind":"identifier"}]},{"op":"replace","value":"OVKFullscreenContentViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/title","value":"playerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/fragments","value":[{"text":"playerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/title","op":"replace","value":"setSupplementaryViewController:animated:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setSupplementaryViewController:animated:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1wrapped\/title","value":"wrapped","op":"replace"},{"value":[{"text":"wrapped","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1wrapped\/fragments"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"visualStyle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1visualStyle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1visualStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"visualStyle"}]},{"value":"OVKFullscreenViewControllerProtocol","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title"},{"value":[{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle"},{"value":"playerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1playerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1playerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"playerView"}]}]}]}