{"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"symbolKind":"protocol","title":"FullscreenSupplementaryController","roleHeading":"Protocol","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKFullscreenSupplementaryController) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"text":"При установке он автоматически добавляется как child view controller на ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","isActive":true},{"text":", на котором сдвигается плеер, чтобы освободить место. Когда показан ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":", полноэкранный режим работы все еще активен.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Положение зависит от ориентации устройства. В портретной он находится снизу под видео. В ландшафтной - справа. Высоту или ширину (в зависимости от ориентации) можно настраивать при помощи свойств "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredSideBySideWidth","isActive":true},{"type":"text","text":" и "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredBottomSheetHeight","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"При анимации ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" всегда появляется снизу экрана."}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller"]},{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetMargin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetPlayerAspectRatio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customControlsSafeInsets","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/dismissGestureRecognizer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/hidesPlayerControls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredBottomSheetHeight","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredSideBySideWidth","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/providesCloseButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/sideBySideMargin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/supplementaryType"],"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customSupplementaryViewInsets(sideBySide:)"],"generated":true}],"sections":[],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"title":"FullscreenController","role":"symbol","navigatorTitle":[{"text":"FullscreenController","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenController","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","type":"topic","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/hidesPlayerControls":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/hidesplayercontrols","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/hidesPlayerControls","abstract":[{"text":"Нужно ли скрывать контролы плеера, когда он показывается одновременно с ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":".","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"hidesPlayerControls"}],"title":"hidesPlayerControls","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidesPlayerControls","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/supplementaryType":{"title":"supplementaryType","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"supplementaryType"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"supplementaryType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SupplementaryControllerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKSupplementaryControllerType"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/supplementarytype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/supplementaryType","type":"topic","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/providesCloseButton":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/providesclosebutton","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/providesCloseButton","abstract":[{"text":"Находится ли на контроллере кнопка закрытия полноэкранного режима плеера.","type":"text"}],"required":true,"navigatorTitle":[{"text":"providesCloseButton","kind":"identifier"}],"title":"providesCloseButton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providesCloseButton","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/bottomSheetPlayerAspectRatio":{"title":"bottomSheetPlayerAspectRatio","role":"symbol","navigatorTitle":[{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetplayeraspectratio","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetPlayerAspectRatio","type":"topic","abstract":[{"type":"text","text":"Принудительно устанавливает соотношение сторон плеера, когда он отображается над "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":"."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/preferredSideBySideWidth":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/preferredsidebysidewidth","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredSideBySideWidth","abstract":[{"type":"text","text":"Ширина, которую контроллер должен занимать при показе справа от плеера."}],"required":true,"navigatorTitle":[{"text":"preferredSideBySideWidth","kind":"identifier"}],"title":"preferredSideBySideWidth","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"preferredSideBySideWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/preferredBottomSheetHeight":{"title":"preferredBottomSheetHeight","role":"symbol","required":true,"navigatorTitle":[{"text":"preferredBottomSheetHeight","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBottomSheetHeight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/preferredbottomsheetheight","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredBottomSheetHeight","type":"topic","abstract":[{"text":"Высота, которую контроллер должен занимать при показе снизу плеера.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"title":"FullscreenSupplementaryController","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/customSupplementaryViewInsets(sideBySide:)":{"title":"customSupplementaryViewInsets(sideBySide:)","role":"symbol","navigatorTitle":[{"text":"customSupplementaryViewInsetsWithSideBySide:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customSupplementaryViewInsets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sideBySide","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/customsupplementaryviewinsets(sidebyside:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customSupplementaryViewInsets(sideBySide:)","type":"topic","abstract":[{"type":"text","text":"Переопределение инсетов, которые действуют на общую область отображения плеера и "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":". "},{"code":"nil","type":"codeVoice"},{"text":" означает наследование инсетов от safe area.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/wasPresentedForSupplementaryController":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/waspresentedforsupplementarycontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","abstract":[{"text":"Был ли контроллер презентован одновременно с добавлением ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"title":"wasPresentedForSupplementaryController","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"wasPresentedForSupplementaryController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/sideBySideMargin":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/sidebysidemargin","type":"topic","title":"sideBySideMargin","required":true,"abstract":[{"type":"text","text":"Расстояние между плеером и "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"type":"text","text":" при показе справа от плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/sideBySideMargin","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sideBySideMargin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sideBySideMargin"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/dismissGestureRecognizer":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/dismissgesturerecognizer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/dismissGestureRecognizer","abstract":[{"text":"Жест, который дает возможность скрыть ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":" свайпом вниз. В зависимости от значения свойства ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController"},{"type":"text","text":" срабатывание жеста приведет либо к закрытию только "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" ("},{"type":"codeVoice","code":"false"},{"text":"), либо к интерактивному дисмиссу всего контроллера с полноэкранным плеером (","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":")."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"dismissGestureRecognizer"}],"title":"dismissGestureRecognizer","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":"?"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/customControlsSafeInsets":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/customcontrolssafeinsets","type":"topic","title":"customControlsSafeInsets","required":true,"abstract":[{"type":"text","text":"Переопределение инсетов, которые действуют на контролы плеера во время показа "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customControlsSafeInsets","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customControlsSafeInsets","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"customControlsSafeInsets"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/bottomSheetMargin":{"kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetmargin","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetMargin","abstract":[{"text":"Расстояние между плеером и ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" при показе снизу плеера."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"bottomSheetMargin"}],"title":"bottomSheetMargin","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bottomSheetMargin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetMargin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetPlayerAspectRatio","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customControlsSafeInsets","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/dismissGestureRecognizer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/hidesPlayerControls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredBottomSheetHeight","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/preferredSideBySideWidth","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/providesCloseButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/sideBySideMargin","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/supplementaryType"]},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customSupplementaryViewInsets(sideBySide:)"],"title":"Instance Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hidesPlayerControls","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1hidesPlayerControls\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1hidesPlayerControls\/fragments","value":[{"kind":"identifier","text":"hidesPlayerControls"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1supplementaryType\/title","value":"supplementaryType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1supplementaryType\/fragments","value":[{"text":"supplementaryType","kind":"identifier"}],"op":"replace"},{"value":"providesCloseButton","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1providesCloseButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1providesCloseButton\/fragments","value":[{"text":"providesCloseButton","kind":"identifier"}]},{"value":"bottomSheetPlayerAspectRatio","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/title"},{"value":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/fragments"},{"value":"preferredSideBySideWidth","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1preferredSideBySideWidth\/title"},{"value":[{"text":"preferredSideBySideWidth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1preferredSideBySideWidth\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1preferredBottomSheetHeight\/title","value":"preferredBottomSheetHeight","op":"replace"},{"value":[{"text":"preferredBottomSheetHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1preferredBottomSheetHeight\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customSupplementaryViewInsets(sideBySide:)\/title","value":"customSupplementaryViewInsetsWithSideBySide:"},{"value":[{"text":"- ","kind":"text"},{"text":"customSupplementaryViewInsetsWithSideBySide:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customSupplementaryViewInsets(sideBySide:)\/fragments"},{"value":"wasPresentedForSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"wasPresentedForSupplementaryController"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/fragments"},{"op":"replace","value":"sideBySideMargin","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1sideBySideMargin\/title"},{"value":[{"kind":"identifier","text":"sideBySideMargin"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1sideBySideMargin\/fragments","op":"replace"},{"value":"dismissGestureRecognizer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1dismissGestureRecognizer\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1dismissGestureRecognizer\/fragments","op":"replace","value":[{"kind":"identifier","text":"dismissGestureRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customControlsSafeInsets\/title","value":"customControlsSafeInsets"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customControlsSafeInsets\/fragments","value":[{"text":"customControlsSafeInsets","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetMargin\/title","op":"replace","value":"bottomSheetMargin"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetMargin\/fragments","value":[{"text":"bottomSheetMargin","kind":"identifier"}]}]}]}