{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo","kind":"relationships"}],"sections":[],"abstract":[{"text":"Поведение при свайпе в полноэкранном режиме.","type":"text"}],"metadata":{"symbolKind":"enum","modules":[{"name":"OVKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSwipeGestureBehavior"}],"role":"symbol","title":"FullscreenSwipeGestureBehavior","externalID":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior","roleHeading":"Enumeration"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKFullscreenSwipeGestureBehavior) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/dismissFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/minimizeToPictureInPicture"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/Equatable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/equatable-implementations"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/rawrepresentable-implementations"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/init(rawValue:)","type":"topic","title":"init(rawValue:)","role":"symbol","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/init(rawvalue:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"title":"FullscreenSwipeGestureBehavior","navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Поведение при свайпе в полноэкранном режиме."}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/dismissFullscreen":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissFullscreen","kind":"identifier"}],"abstract":[{"text":"Закрытие полноэкранного режима.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/dismissFullscreen","type":"topic","title":"FullscreenSwipeGestureBehavior.dismissFullscreen","role":"symbol","navigatorTitle":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/dismissfullscreen"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/minimizeToPictureInPicture":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPictureInPicture","kind":"identifier"}],"abstract":[{"text":"Переход сразу в режим Picture In Picture.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/minimizeToPictureInPicture","type":"topic","title":"FullscreenSwipeGestureBehavior.minimizeToPictureInPicture","role":"symbol","navigatorTitle":[{"text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/minimizetopictureinpicture"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehavior"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/dismissFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/minimizeToPictureInPicture"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1dismissFullscreen\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1dismissFullscreen\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1minimizeToPictureInPicture\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1minimizeToPictureInPicture\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","kind":"identifier"}]}]}]}