{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"abstract":[{"text":"Рекламные контролы для Fullscreen.","type":"text"},{"type":"text","text":" "},{"text":"В отличии от базовых ","type":"text"},{"code":"AdControlsView","type":"codeVoice"},{"text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementedadcontrolsview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreensupplementedadcontrolsview"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"title":"FullscreenSupplementedAdControlsView","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)FullscreenSupplementedAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView\/layoutSubviews()"],"anchor":"Instance-Methods","generated":true}],"references":{"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"role":"symbol","title":"SupplementedAdControlsView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementedAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"role":"symbol","abstract":[{"type":"text","text":"Рекламные контролы для Fullscreen."},{"type":"text","text":" "},{"text":"В отличии от базовых ","type":"text"},{"type":"codeVoice","code":"AdControlsView"},{"type":"text","text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров."}],"navigatorTitle":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview","title":"FullscreenSupplementedAdControlsView"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView/layoutSubviews()":{"url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview\/layoutsubviews()","title":"layoutSubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView\/layoutSubviews()","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HideableControls","kind":"identifier"}],"url":"\/documentation\/ovkit\/hideablecontrols","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","navigatorTitle":[{"kind":"identifier","text":"HideableControls"}],"title":"HideableControls","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"type":"topic","abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","title":"PlayerControlsViewProtocol","kind":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerControlsViewProtocol"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionViewDelegate"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate","title":"MyTargetInstreamAdVideoMotionViewDelegate","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"FullscreenSupplementedAdControlsView","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView\/layoutSubviews()"],"title":"Instance Methods","generated":true}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementedAdControlsView","text":"SupplementedAdControlsView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SupplementedAdControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title"},{"value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","value":[{"text":"SupplementedAdControlsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/title","op":"replace","value":"FullscreenSupplementedAdControlsView"},{"value":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/fragments"},{"value":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]}]}]}