{"metadata":{"title":"gRPC","roleHeading":"Article","role":"article","modules":[{"name":"OVKit"}]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC"},"seeAlsoSections":[{"generated":true,"anchor":"Начало-работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Начало работы"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/grpc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/grpc"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"movie_id"},{"type":"text","text":" из шины стоит установить и в "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoId"},{"type":"text","text":" и в "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId"},{"type":"text","text":"."}]},{"type":"heading","level":3,"anchor":"%D0%9C%D0%B0%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3-%D1%83%D1%80%D0%BB%D0%BE%D0%B2-%D0%B8%D0%B7-%D1%88%D0%B8%D0%BD%D1%8B-%D0%B2-files","text":"Маппинг урлов из шины в `files`"},{"type":"table","header":"row","rows":[[[{"inlineContent":[{"type":"text","text":"gRPC"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Video object"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_low"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"mp4_360"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_medium","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"mp4_480"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_high","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"mp4_720","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_fullhd","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"mp4_1080"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_ultrahd"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"mp4_1440"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_quadhd","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"mp4_2160","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_dash","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"dashSep","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_live_playback_dash"}],"type":"paragraph"}],[{"inlineContent":[{"text":"dashLivePlayback","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_live_dash"}],"type":"paragraph"}],[{"inlineContent":[{"text":"если нет url_live_playback_dash ","type":"text"},{"text":" dashLivePlayback","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"url_hls","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"hls"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_live_playback_hls"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"hlsLive"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"url_live_hls"}],"type":"paragraph"}],[{"inlineContent":[{"text":"если нет url_live_playback_hls ","type":"text"},{"text":" hlsLive","type":"text"}],"type":"paragraph"}]]]},{"type":"heading","level":3,"anchor":"%D0%9C%D0%B0%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0-%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BB%D1%8F%D1%86%D0%B8%D0%B8-%D0%B2-videoliveStatus","text":"Маппинг статуса трансляции в `video.liveStatus`:"},{"type":"table","header":"row","rows":[[[{"inlineContent":[{"text":"gRPC","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Video object","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"STATUS_UNDEF"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"upcoming"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"STATUS_OK","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"finished","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"ONLINE"}],"type":"paragraph"}],[{"inlineContent":[{"text":"started","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"OFFLINE"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"waiting"}],"type":"paragraph"}]]]},{"type":"heading","level":3,"anchor":"%D0%9C%D0%B0%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3-thumbnail-%D0%B2-previewImages","text":"Маппинг `thumbnail` в `previewImages`"},{"type":"table","header":"row","rows":[[[{"inlineContent":[{"text":"gRPC","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Video object"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"SMALL","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"128 x 72"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"STANDARD"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"240 x 135"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"MEDIUM"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"480 x 270"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"FULL","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"720 x 405"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"HIGH"}],"type":"paragraph"}],[{"inlineContent":[{"text":"960 x 540","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"HD"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"1280 x 720"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"HD_NO_CROP"}],"type":"paragraph"}],[{"inlineContent":[{"text":"1280 x 720","type":"text"}],"type":"paragraph"}]]]}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","abstract":[{"code":"OVKit","type":"codeVoice"},{"text":" поддерживает воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"role":"article","kind":"article","title":"Воспроизведение в фоне","type":"topic","url":"\/documentation\/ovkit\/backgroundplayback"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"url":"\/documentation\/ovkit\/plugins","title":"Плагины","kind":"article","role":"collectionGroup","abstract":[{"type":"text","text":"Плагины позволяют расширить функциональность "},{"type":"codeVoice","code":"OVKit"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"role":"article","title":"Контролы плеера","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","type":"topic","url":"\/documentation\/ovkit\/controls","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"url":"\/documentation\/ovkit\/prefetch","title":"Префетчер","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"kind":"article","role":"article","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"},"doc://onevideo.OVKit/documentation/OVKit/Video/ovId":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video\/ovid","title":"ovId","navigatorTitle":[{"text":"ovId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"role":"article","kind":"article","type":"topic","title":"Быстрый старт","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","abstract":[{"text":"Руководство для первого подключения ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":" к проекту. Эти шаги необходимо выполнить перед началом работы.","type":"text"}],"url":"\/documentation\/ovkit\/quickstart"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"kind":"article","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","title":"Полноэкранный режим","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"url":"\/documentation\/ovkit\/fullscreen","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Video/videoId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"videoId","abstract":[],"type":"topic","navigatorTitle":[{"text":"videoId","kind":"identifier"}],"url":"\/documentation\/ovkit\/video\/videoid","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoId","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","kind":"article","url":"\/documentation\/ovkit\/createplayer","title":"Создание плеера","role":"article","abstract":[{"type":"text","text":"Первые шаги после интеграции."}]},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","title":"Дополнительно","role":"article","type":"topic","url":"\/documentation\/ovkit\/extras","abstract":[{"type":"text","text":"Дополнительные возможности "},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"abstract":[{"text":"SDK поддерживает сбор статистики по воспроизведению видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","title":"Статистика","type":"topic","url":"\/documentation\/ovkit\/statistics","kind":"article","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Начало-работы","title":"Начало работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"generated":true}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/title","op":"replace","value":"ovId"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/fragments","op":"replace","value":[{"text":"ovId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoId\/title","op":"replace","value":"videoId"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoId\/fragments","op":"replace","value":[{"kind":"identifier","text":"videoId"}]}]}]}