{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"title":"HoldToSeekBehavior","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)HoldToSeekBehavior","modules":[{"name":"OVKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Перемотка видео нажатием и удержанием."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/init(externalTrackable:shouldBegin:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/controlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/isEnabled"]},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/ovkit\/holdtoseekbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/holdtoseekbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/controlsView":{"kind":"symbol","url":"\/documentation\/ovkit\/holdtoseekbehavior\/controlsview","abstract":[{"type":"text","text":"Контролы, на которые добавляется поведение."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/controlsView","title":"controlsView","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"controlsView"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations","title":"UIGestureRecognizerDelegate Implementations","url":"\/documentation\/ovkit\/holdtoseekbehavior\/uigesturerecognizerdelegate-implementations","type":"topic","abstract":[],"kind":"article"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"navigatorTitle":[{"text":"HoldToSeekBehavior","kind":"identifier"}],"abstract":[{"text":"Перемотка видео нажатием и удержанием.","type":"text"}],"type":"topic","title":"HoldToSeekBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","kind":"symbol","url":"\/documentation\/ovkit\/holdtoseekbehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/init(externalTrackable:shouldBegin:)":{"abstract":[{"type":"text","text":"Создание поведения."}],"title":"init(externalTrackable:shouldBegin:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/init(externalTrackable:shouldBegin:)","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/holdtoseekbehavior\/init(externaltrackable:shouldbegin:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"externalTrackable"},{"kind":"text","text":": "},{"text":"ExternalTrackable","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit17ExternalTrackableP"},{"text":"?, ","kind":"text"},{"text":"shouldBegin","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/isEnabled":{"abstract":[{"text":"Активен ли жест перемотки.","type":"text"}],"type":"topic","title":"isEnabled","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/isEnabled","url":"\/documentation\/ovkit\/holdtoseekbehavior\/isenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIGestureRecognizerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"abstract":[{"text":"Динамическое поведение контролов.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ControlsBehavior","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","title":"ControlsBehavior","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ControlsBehavior","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/controlsbehavior"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"HoldToSeekBehavior","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"HoldToSeekBehavior","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations"],"title":"Default Implementations"}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"title":"Conforms To","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title","value":"HoldToSeekBehavior"},{"value":[{"text":"HoldToSeekBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}