{"sections":[],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"После отпускания скорость возвращается к той, которая была до срабатывания жеста.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtochangeratebehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/holdtochangeratebehavior"]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/controlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gesture","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/isEnabled"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/changeRateAvailable(for:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/UIGestureRecognizerDelegate-Implementations"],"generated":true}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)HoldToChangeRateBehavior","title":"HoldToChangeRateBehavior","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"role":"symbol","symbolKind":"class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)":{"title":"init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)","abstract":[{"type":"text","text":"Создание поведения."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shouldBeginWithRate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"layoutSetup","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onStart","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/init(shouldbeginwithrate:layoutsetup:onstart:onend:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)","role":"symbol"},"doc://onevideo.OVKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/gesture":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gesture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gesture","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/gesture","title":"gesture","abstract":[]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"url":"\/documentation\/ovkit\/controlsbehavior","kind":"symbol","title":"ControlsBehavior","role":"symbol","navigatorTitle":[{"text":"ControlsBehavior","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"}],"abstract":[{"text":"Динамическое поведение контролов.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/UIGestureRecognizerDelegate-Implementations","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/uigesturerecognizerdelegate-implementations"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/isEnabled":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEnabled","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/isenabled","abstract":[{"text":"Активен ли жест перемотки.","type":"text"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior","abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"type":"topic","title":"HoldToChangeRateBehavior"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/changeRateAvailable(for:)":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/changeRateAvailable(for:)","title":"changeRateAvailable(for:)","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/changerateavailable(for:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRateAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/controlsView":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior\/controlsview","abstract":[{"type":"text","text":"Контролы, на которые добавляется поведение."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/controlsView","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"kind":"text","text":"?"}],"type":"topic","title":"controlsView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HoldToChangeRateBehavior"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/UIGestureRecognizerDelegate-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title","value":"HoldToChangeRateBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]}]}]}