{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKIdleTimerManager","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"modules":[{"name":"OVKit"}],"roleHeading":"Protocol","title":"IdleTimerManager"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKIdleTimerManager) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart"]},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"В "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"},{"type":"text","text":" поступают события от всех "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", когда меняется их статус воспроизведения."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"generated":true,"title":"Сервисы","anchor":"Сервисы"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/idletimermanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/idletimermanager"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/disableIdleTimer()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/enableIdleTimerIfNeeded()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","title":"PersistenceManager","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/audiomanager","navigatorTitle":[{"kind":"identifier","text":"AudioManager"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"title":"AudioManager","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"text":" при работе плееров.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"role":"article","abstract":[{"text":"Руководство для первого подключения ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":" к проекту. Эти шаги необходимо выполнить перед началом работы.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","url":"\/documentation\/ovkit\/quickstart","kind":"article","title":"Быстрый старт"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"kind":"symbol","title":"Environment","type":"topic","url":"\/documentation\/ovkit\/environment","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager/enableIdleTimerIfNeeded()":{"kind":"symbol","title":"enableIdleTimerIfNeeded()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/enableIdleTimerIfNeeded()","url":"\/documentation\/ovkit\/idletimermanager\/enableidletimerifneeded()","abstract":[{"type":"text","text":"Включает автоблокировку устройства по таймауту, если она не требуется для других целей в приложении."}],"role":"symbol","navigatorTitle":[{"text":"enableIdleTimerIfNeeded","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableIdleTimerIfNeeded"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"type":"topic","title":"IdleTimerManager","url":"\/documentation\/ovkit\/idletimermanager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager/disableIdleTimer()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/disableIdleTimer()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/idletimermanager\/disableidletimer()","navigatorTitle":[{"kind":"identifier","text":"disableIdleTimer"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableIdleTimer"},{"kind":"text","text":"()"}],"title":"disableIdleTimer()","abstract":[{"type":"text","text":"Отключает автоблокировку устройства по таймауту."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playermanager","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"title":"PlayerManager","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKIdleTimerManager","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/disableIdleTimer()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager\/enableIdleTimerIfNeeded()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"generated":true,"title":"Сервисы","anchor":"Сервисы"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKIdleTimerManager","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"op":"replace","value":"OVKAudioManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKEnvironment"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"enableIdleTimerIfNeeded","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1enableIdleTimerIfNeeded()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableIdleTimerIfNeeded","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1enableIdleTimerIfNeeded()\/fragments"},{"op":"replace","value":"OVKIdleTimerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title"},{"op":"replace","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments"},{"op":"replace","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle"},{"op":"replace","value":"disableIdleTimer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1disableIdleTimer()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableIdleTimer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager~1disableIdleTimer()\/fragments"},{"op":"replace","value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle"}]}]}