{"sections":[],"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageView"}],"role":"symbol","title":"ImageView","roleHeading":"Class","navigatorTitle":[{"text":"ImageView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)ImageView","modules":[{"name":"OVKit"}]},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"]},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(frame:image:highlightedImage:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/contentMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/tintColor"]},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/layoutSubviews()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"abstract":[{"text":"Обертка над ","type":"text"},{"code":"UIImageView","type":"codeVoice"},{"text":", которая умеет анимировать ","type":"text"},{"code":"UIView.ContentMode","type":"codeVoice"},{"text":" за счет перемещения ","type":"text"},{"type":"codeVoice","code":"imageView"},{"type":"text","text":" внутри рамок."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageView","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"text":"Нужно использовать в качестве базового класса вместо ","type":"text"},{"code":"UIImageView","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/imageview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/imageview"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageView":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView","title":"ImageView","abstract":[{"text":"Обертка над ","type":"text"},{"code":"UIImageView","type":"codeVoice"},{"type":"text","text":", которая умеет анимировать "},{"type":"codeVoice","code":"UIView.ContentMode"},{"text":" за счет перемещения ","type":"text"},{"type":"codeVoice","code":"imageView"},{"type":"text","text":" внутри рамок."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageView"}],"navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/ovkit\/imageview","type":"topic"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/contentMode":{"url":"\/documentation\/ovkit\/imageview\/contentmode","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"ContentMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/contentMode","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"role":"symbol","title":"contentMode"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/layoutSubviews()":{"url":"\/documentation\/ovkit\/imageview\/layoutsubviews()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/layoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"role":"symbol","title":"layoutSubviews()"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/init(coder:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/imageview\/init(coder:)","kind":"symbol","title":"init(coder:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(coder:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/init(frame:image:highlightedImage:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(frame:image:highlightedImage:)","title":"init(frame:image:highlightedImage:)","url":"\/documentation\/ovkit\/imageview\/init(frame:image:highlightedimage:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"highlightedImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIView"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/LoadableImageView":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"LoadableImageView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LoadableImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView","title":"LoadableImageView","kind":"symbol","url":"\/documentation\/ovkit\/loadableimageview"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/tintColor":{"url":"\/documentation\/ovkit\/imageview\/tintcolor","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tintColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/tintColor","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"role":"symbol","title":"tintColor"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImageView"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ImageView","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImageView"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/contentMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/tintColor"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/layoutSubviews()"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoadableImageView"],"title":"Inherited By"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ImageView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/title"},{"value":[{"kind":"identifier","text":"ImageView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/fragments"},{"value":[{"text":"ImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/navigatorTitle","op":"replace"},{"value":"contentMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1contentMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1contentMode\/fragments","value":[{"kind":"identifier","text":"contentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1layoutSubviews()\/title","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1init(coder:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/title","op":"replace","value":"LoadableImageView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/fragments","value":[{"text":"LoadableImageView","kind":"identifier"}]},{"op":"replace","value":[{"text":"LoadableImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoadableImageView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1tintColor\/title","value":"tintColor"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1tintColor\/fragments","value":[{"kind":"identifier","text":"tintColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}