{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","interfaceLanguage":"swift"},"abstract":[{"text":"Ассет изображения.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"kind":"relationships"},{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/ovkit\/imageassettype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/imageassettype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/isBase","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/size"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl(for:)"],"anchor":"Instance-Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"title":"ImageAssetType","symbolKind":"protocol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKImageAssetType","navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKImageAssetType) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageAsset"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset","type":"topic","title":"ImageAsset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageAsset"}],"url":"\/documentation\/ovkit\/imageasset"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType/size":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"url":"\/documentation\/ovkit\/imageassettype\/size","abstract":[{"text":"Размер изображения в пикселях.","type":"text"}],"type":"topic","title":"size","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/size","required":true,"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"url":"\/documentation\/ovkit\/imageassettype","navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","title":"ImageAssetType","abstract":[{"text":"Ассет изображения.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType/isBase":{"url":"\/documentation\/ovkit\/imageassettype\/isbase","required":true,"navigatorTitle":[{"kind":"identifier","text":"isBase"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","abstract":[{"type":"text","text":"Является ли URL на ассет универсальным для любого размера."}],"title":"isBase","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/isBase"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType/imageUrl":{"title":"imageUrl","navigatorTitle":[{"kind":"identifier","text":"imageUrl"}],"type":"topic","abstract":[{"text":"URL на изображение размера ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/size","isActive":true},{"type":"text","text":" или базовый URL на универсальный ассет."}],"url":"\/documentation\/ovkit\/imageassettype\/imageurl","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType/imageUrl(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl(for:)","title":"imageUrl(for:)","type":"topic","url":"\/documentation\/ovkit\/imageassettype\/imageurl(for:)","abstract":[{"text":"Получение URL на изображение для заданного размера.","type":"text"}],"role":"symbol","kind":"symbol","required":true,"navigatorTitle":[{"text":"imageUrlFor:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKImageAssetType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/isBase","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/size"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType\/imageUrl(for:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"],"type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKImageAssetType","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title","value":"OVKImageAsset"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","value":[{"kind":"identifier","text":"OVKImageAsset"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle","value":[{"kind":"identifier","text":"OVKImageAsset"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1size\/title","value":"size"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1size\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1isBase\/title","value":"isBase","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1isBase\/fragments","value":[{"kind":"identifier","text":"isBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1imageUrl\/title","value":"imageUrl","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1imageUrl\/fragments","value":[{"kind":"identifier","text":"imageUrl"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1imageUrl(for:)\/title","value":"imageUrlFor:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType~1imageUrl(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageUrlFor:"}],"op":"replace"}]}]}