{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKImageAsset) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"},"variants":[{"paths":["\/documentation\/ovkit\/imageasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/imageasset"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"title":"ImageAsset","externalID":"c:@M@OVKit@objc(cs)OVKImageAsset","modules":[{"name":"OVKit"}]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(url:forSize:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/size"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isEqual(_:)"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/imageUrl":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/imageasset\/imageurl","abstract":[],"title":"imageUrl","navigatorTitle":[{"text":"imageUrl","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","title":"ImageAssetType","navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","url":"\/documentation\/ovkit\/imageassettype"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/description":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/imageasset\/description","abstract":[],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/description"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/isEqual(_:)":{"url":"\/documentation\/ovkit\/imageasset\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isEqual(_:)","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isEqual(_:)"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/Se":{"identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"title":"ImageAsset","navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"url":"\/documentation\/ovkit\/imageasset","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/init(from:)":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"init(from:)","url":"\/documentation\/ovkit\/imageasset\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(from:)"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/init(url:forSize:)":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/imageasset\/init(url:forsize:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(url:forSize:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithUrl:forSize:"}],"title":"init(url:forSize:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/ImageAsset/size":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/size","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"title":"size","role":"symbol","url":"\/documentation\/ovkit\/imageasset\/size"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKImageAsset","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKImageAsset","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKImageAsset"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/imageUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/size"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/init(url:forSize:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAsset\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKImageAsset"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl\/title","op":"replace","value":"imageUrl"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1imageUrl\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageUrl"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","op":"replace","value":"OVKImageAssetType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","op":"replace","value":[{"text":"OVKImageAssetType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKImageAssetType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/title","op":"replace","value":"OVKImageAsset"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/fragments","op":"replace","value":[{"text":"OVKImageAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKImageAsset"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1init(url:forSize:)\/title","op":"replace","value":"initWithUrl:forSize:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1init(url:forSize:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUrl:forSize:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1size\/title","op":"replace","value":"size"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAsset~1size\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}