{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:getItemForIndexPath:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:nextIndexPathOfIndexPath:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKIndexPrefetcherDataSource) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IndexPrefetcherDataSource","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Обычно им является модель данных, которая содержит индекс видеозаписей на экране.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource"},"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"navigatorTitle":[{"text":"IndexPrefetcherDataSource","kind":"identifier"}],"roleHeading":"Protocol","title":"IndexPrefetcherDataSource","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource":{"role":"symbol","title":"IndexPrefetcherDataSource","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"abstract":[{"type":"text","text":"Протокол, определяющий источник данных для префетчера списка."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"url":"\/documentation\/ovkit\/indexprefetcherdatasource","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource/indexPrefetcher(_:getItemForIndexPath:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:getItemForIndexPath:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"getItemForIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"indexPrefetcher:getItemForIndexPath:","kind":"identifier"}],"title":"indexPrefetcher(_:getItemForIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:getitemforindexpath:)","abstract":[{"text":"Вызывается для получения ресурса.","type":"text"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource/indexPrefetcher(_:nextIndexPathOfIndexPath:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:nextIndexPathOfIndexPath:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nextIndexPathOfIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"indexPrefetcher:nextIndexPathOfIndexPath:","kind":"identifier"}],"title":"indexPrefetcher(_:nextIndexPathOfIndexPath:)","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:nextindexpathofindexpath:)","abstract":[{"type":"text","text":"Вызывается для получения ресурса."}],"required":true},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKIndexPrefetcherDataSource","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcherDataSource"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDataSource"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:getItemForIndexPath:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:nextIndexPathOfIndexPath:)"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/title","value":"OVKIndexPrefetcherDataSource","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/fragments","value":[{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/navigatorTitle","value":[{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:getItemForIndexPath:)\/title","value":"indexPrefetcher:getItemForIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:getItemForIndexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:getItemForIndexPath:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:nextIndexPathOfIndexPath:)\/title","value":"indexPrefetcher:nextIndexPathOfIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:nextIndexPathOfIndexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:nextIndexPathOfIndexPath:","kind":"identifier"}],"op":"replace"}]}]}