{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/indexprefetcherdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcherdelegate"]}],"metadata":{"navigatorTitle":[{"text":"IndexPrefetcherDelegate","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcherDelegate","kind":"identifier"}],"title":"IndexPrefetcherDelegate","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate","role":"symbol","roleHeading":"Protocol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/focusedIndexPathForIndexPrefetcher(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didCancelItem:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didPrefetchItem:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:itemPrefetchDidFail:withError:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"text":"Протокол, через который ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"text":" сообщает о наступлении событий в ходе своей работы.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKIndexPrefetcherDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcherDelegate","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/indexPrefetcher(_:itemPrefetchDidFail:withError:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:itemPrefetchDidFail:withError:"}],"url":"\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:itemprefetchdidfail:witherror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemPrefetchDidFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:itemPrefetchDidFail:withError:)","title":"indexPrefetcher(_:itemPrefetchDidFail:withError:)","role":"symbol","abstract":[{"text":"Сообщает об ошибке во время выполнения операции.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate":{"abstract":[{"type":"text","text":"Протокол, через который "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdelegate","title":"IndexPrefetcherDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcherDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/indexPrefetcher(_:didCancelItem:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:didCancelItem:"}],"url":"\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:didcancelitem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCancelItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didCancelItem:)","title":"indexPrefetcher(_:didCancelItem:)","role":"symbol","abstract":[{"text":"Сообщает об отмене операции.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"url":"\/documentation\/ovkit\/indexprefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"title":"IndexPrefetcher","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/reached(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/indexprefetcher\/reached(_:)","navigatorTitle":[{"text":"reached:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reached","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"reached(_:)","abstract":[{"text":"Предзагрузка элементов списка после текущей позиции.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/indexPrefetcher(_:didPrefetchItem:)":{"abstract":[{"text":"Сообщает об успешном выполнении операции.","type":"text"}],"type":"topic","title":"indexPrefetcher(_:didPrefetchItem:)","url":"\/documentation\/ovkit\/indexprefetcherdelegate\/indexprefetcher(_:didprefetchitem:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPrefetchItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:didPrefetchItem:"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didPrefetchItem:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate/focusedIndexPathForIndexPrefetcher(_:)":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/focusedIndexPathForIndexPrefetcher(_:)","abstract":[{"text":"Запрашивается после вызова ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","isActive":true},{"text":". Если вернуть ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"text":", он будет использован вместо переденного в ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","isActive":true},{"text":".","type":"text"}],"title":"focusedIndexPathForIndexPrefetcher(_:)","url":"\/documentation\/ovkit\/indexprefetcherdelegate\/focusedindexpathforindexprefetcher(_:)","navigatorTitle":[{"kind":"identifier","text":"focusedIndexPathForIndexPrefetcher:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKIndexPrefetcherDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OVKIndexPrefetcherDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/focusedIndexPathForIndexPrefetcher(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didCancelItem:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:didPrefetchItem:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate\/indexPrefetcher(_:itemPrefetchDidFail:withError:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKIndexPrefetcherDelegate"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"indexPrefetcher:itemPrefetchDidFail:withError:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:itemPrefetchDidFail:withError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:itemPrefetchDidFail:withError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:itemPrefetchDidFail:withError:)\/fragments"},{"value":"OVKIndexPrefetcherDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/title"},{"value":[{"text":"OVKIndexPrefetcherDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/fragments"},{"value":[{"text":"OVKIndexPrefetcherDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/navigatorTitle"},{"value":"indexPrefetcher:didCancelItem:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didCancelItem:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:didCancelItem:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didCancelItem:)\/fragments"},{"value":"OVKIndexPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"value":"reached:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"reached:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/fragments"},{"value":"indexPrefetcher:didPrefetchItem:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didPrefetchItem:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:didPrefetchItem:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1indexPrefetcher(_:didPrefetchItem:)\/fragments"},{"value":"focusedIndexPathForIndexPrefetcher:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1focusedIndexPathForIndexPrefetcher(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"focusedIndexPathForIndexPrefetcher:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate~1focusedIndexPathForIndexPrefetcher(_:)\/fragments"}]}]}