{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"title":"IndexPrefetcher","roleHeading":"Class","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/indexprefetcher"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/indexprefetcher"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/autoCancel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/controlQueue","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/dataSource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/strategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/throttleInterval"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(at:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(at:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/stop()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKIndexPrefetcher) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"languages":["swift"]}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch"],"kind":"mentions"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Осуществляет предзагрузку элементов в индексированных моделях (например, ленте видео). Для этого необходимо установить "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/dataSource","type":"reference","isActive":true},{"type":"text","text":", который позволит префетчеру получить содержимое индекса через "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":". Помимо списков, этот префетчер можно использовать и для предзагрузки произвольных видео."}]},{"inlineContent":[{"text":"Отмена предзагрузки означает прерывание процесса предзагрузки, если он выполняется в данный момент. Уже предзагруженные данные при этом не удаляются.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Префетчер не блокирует очередь, с которой вызываются его методы.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"Все методы должны вызываться с "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/controlQueue","type":"reference","isActive":true},{"type":"text","text":". Обращение к "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/delegate"},{"type":"text","text":" и "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/dataSource"},{"type":"text","text":" будет также происходить на этой очереди."}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"anchor":"Предзагрузка","title":"Предзагрузка"}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"type":"topic","title":"PrefetchStrategy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchStrategy"}],"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PrefetchStrategy"}],"url":"\/documentation\/ovkit\/prefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/strategy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/strategy","type":"topic","abstract":[{"text":"Стратегия работы префетчера.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"strategy"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"}],"url":"\/documentation\/ovkit\/indexprefetcher\/strategy","title":"strategy","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"type":"topic","title":"PrefetchItem","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"url":"\/documentation\/ovkit\/prefetchitem"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/stop()":{"url":"\/documentation\/ovkit\/indexprefetcher\/stop()","title":"stop()","kind":"symbol","abstract":[{"text":"Остановка предзагрузки у всех элементов, если она выполняется в данный момент.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/stop()","navigatorTitle":[{"kind":"identifier","text":"stop"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/prefetch(at:)":{"abstract":[{"text":"Предзагрузка произвольного элемента отдельно от списка по его IndexPath.","type":"text"}],"navigatorTitle":[{"text":"prefetchAt:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(at:)","kind":"symbol","title":"prefetch(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/indexprefetcher\/prefetch(at:)"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:controlQueue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:)","navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:"}],"abstract":[{"text":"Создание префетчера.","type":"text"}],"url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:)","kind":"symbol","title":"init(strategy:groupName:controlQueue:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/delegate":{"url":"\/documentation\/ovkit\/indexprefetcher\/delegate","title":"delegate","kind":"symbol","abstract":[{"type":"text","text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate","text":"IndexPrefetcherDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(_:)":{"abstract":[{"text":"Отмена предзагрузки произвольного элемента.","type":"text"}],"title":"cancel(_:)","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/dataSource":{"url":"\/documentation\/ovkit\/indexprefetcher\/datasource","title":"dataSource","kind":"symbol","abstract":[{"text":"Источник данных, из которого префетчер получает список ресурсов.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSource","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPrefetcherDataSource","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/dataSource","navigatorTitle":[{"text":"dataSource","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","title":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/reached(_:)":{"url":"\/documentation\/ovkit\/indexprefetcher\/reached(_:)","navigatorTitle":[{"kind":"identifier","text":"reached:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reached"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}],"abstract":[{"text":"Предзагрузка элементов списка после текущей позиции.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","kind":"symbol","title":"reached(_:)","role":"symbol"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","type":"topic","kind":"symbol","title":"init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:cachecontainer:controlqueue:maxconcurrentdownloadscount:)","abstract":[{"text":"Создание префетчера.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetchStrategy","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"kind":"text","text":", "},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"cacheContainer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","text":"CacheContainer","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controlQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(at:)":{"title":"cancel(at:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(at:)","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(at:)","abstract":[{"type":"text","text":"Отмена предзагрузки произвольного элемента по его IndexPath."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelAt:"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/prefetch(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","kind":"symbol","type":"topic","title":"prefetch(_:)","abstract":[{"text":"Предзагрузка произвольного элемента отдельно от списка.","type":"text"}],"url":"\/documentation\/ovkit\/indexprefetcher\/prefetch(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetch:"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/throttleInterval":{"url":"\/documentation\/ovkit\/indexprefetcher\/throttleinterval","navigatorTitle":[{"kind":"identifier","text":"throttleInterval"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"throttleInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"abstract":[{"text":"Интервал времени, который пройдет от момента вызова ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","type":"reference","isActive":true},{"text":" до начала предзагрузки и отмены элементов.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/throttleInterval","kind":"symbol","title":"throttleInterval","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/autoCancel":{"url":"\/documentation\/ovkit\/indexprefetcher\/autocancel","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoCancel"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/autoCancel","abstract":[{"text":"Автоматическая отмена загрузки ресурсов, которые не попадают в набор индексов от стратегии.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoCancel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"autoCancel"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"url":"\/documentation\/ovkit\/prefetch","type":"topic","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","title":"Префетчер","kind":"article","role":"article"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:)":{"title":"init(strategy:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:)","type":"topic","url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:)","abstract":[{"text":"Создание префетчера.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStrategy:"}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"url":"\/documentation\/ovkit\/prefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","type":"topic","title":"Prefetcher","role":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/controlQueue":{"title":"controlQueue","abstract":[{"type":"text","text":"Очередь, на которой происходит управление префетчером."}],"url":"\/documentation\/ovkit\/indexprefetcher\/controlqueue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlQueue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/controlQueue","role":"symbol","navigatorTitle":[{"text":"controlQueue","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","url":"\/documentation\/ovkit\/indexprefetcher\/init(strategy:groupname:controlqueue:maxconcurrentdownloadscount:)","navigatorTitle":[{"text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strategy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"controlQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Создание префетчера."}],"type":"topic","title":"init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKIndexPrefetcher"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/autoCancel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/controlQueue","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/dataSource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/strategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/throttleInterval"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(at:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(at:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/reached(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/stop()"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Предзагрузка","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"anchor":"Предзагрузка"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKIndexPrefetcher","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","value":"OVKPrefetchStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1strategy\/title","value":"strategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1strategy\/fragments","value":[{"kind":"identifier","text":"strategy"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(at:)\/title","value":"prefetchAt:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:)\/title","value":"initWithStrategy:groupName:controlQueue:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrategy:groupName:controlQueue:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/title","value":"cancel:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1dataSource\/title","value":"dataSource"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1dataSource\/fragments","value":[{"kind":"identifier","text":"dataSource"}]},{"value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace"},{"value":"reached:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"reached:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1reached(_:)\/fragments","op":"replace"},{"value":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:cacheContainer:controlQueue:maxConcurrentDownloadsCount:)\/fragments","op":"replace"},{"value":"cancelAt:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(at:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cancelAt:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(at:)\/fragments","op":"replace"},{"value":"prefetch:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"prefetch:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/fragments","op":"replace"},{"value":"throttleInterval","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1throttleInterval\/title","op":"replace"},{"value":[{"text":"throttleInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1throttleInterval\/fragments","op":"replace"},{"value":"autoCancel","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1autoCancel\/title","op":"replace"},{"value":[{"text":"autoCancel","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1autoCancel\/fragments","op":"replace"},{"value":"initWithStrategy:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrategy:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:)\/fragments","op":"replace"},{"value":"OVKPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","op":"replace"},{"value":[{"text":"OVKPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","op":"replace"},{"value":"controlQueue","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1controlQueue\/title","op":"replace"},{"value":[{"text":"controlQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1controlQueue\/fragments","op":"replace"},{"value":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrategy:groupName:controlQueue:maxConcurrentDownloadsCount:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1init(strategy:groupName:controlQueue:maxConcurrentDownloadsCount:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}