{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"type":"inheritsFrom"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interactivestatshandler"]},{"paths":["\/documentation\/ovkit\/interactivestatshandler"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKInteractiveStatsHandler","role":"symbol","roleHeading":"Protocol","title":"InteractiveStatsHandler","navigatorTitle":[{"text":"InteractiveStatsHandler","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveStatsHandler","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKInteractiveStatsHandler) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveStatsHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","text":"StatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler","interfaceLanguage":"swift"},"abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":" после добавления нового "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/interactiveMovieStart(rootInteractiveVideoID:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/nextMovie(movieId:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/playerInterfaceClick(source:)"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/video","abstract":[],"type":"topic","title":"Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler","type":"topic","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":" после добавления нового "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"title":"InteractiveStatsHandler","role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler","navigatorTitle":[{"text":"InteractiveStatsHandler","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveStatsHandler","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler/playerInterfaceClick(source:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/playerInterfaceClick(source:)","type":"topic","title":"playerInterfaceClick(source:)","abstract":[{"text":"Взаимодействие пользователя с элементами интерфейса интерактивного плеера","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler\/playerinterfaceclick(source:)","navigatorTitle":[{"text":"playerInterfaceClickWithSource:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerInterfaceClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKInteractiveInterfaceClickSource","text":"InteractiveInterfaceClickSource"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"url":"\/documentation\/ovkit\/statscollector","type":"topic","title":"StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler/interactiveMovieStart(rootInteractiveVideoID:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/interactiveMovieStart(rootInteractiveVideoID:)","type":"topic","abstract":[{"type":"text","text":"Начался просмотр интерактивного видео."}],"title":"interactiveMovieStart(rootInteractiveVideoID:)","role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler\/interactivemoviestart(rootinteractivevideoid:)","navigatorTitle":[{"text":"interactiveMovieStartWithRootInteractiveVideoID:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interactiveMovieStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rootInteractiveVideoID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"События логирования будут вызваны на специальной background очереди."},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"url":"\/documentation\/ovkit\/statshandler","type":"topic","title":"StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveStatsHandler/nextMovie(movieId:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/nextMovie(movieId:)","type":"topic","title":"nextMovie(movieId:)","abstract":[{"text":"В плеере начинает проигрываться следующая глава.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/interactivestatshandler\/nextmovie(movieid:)","navigatorTitle":[{"text":"nextMovieWithMovieId:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextMovie"},{"kind":"text","text":"("},{"kind":"externalParam","text":"movieId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"OVKInteractiveStatsHandler","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKInteractiveStatsHandler"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInteractiveStatsHandler"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/interactiveMovieStart(rootInteractiveVideoID:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/nextMovie(movieId:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveStatsHandler\/playerInterfaceClick(source:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"OVKInteractiveStatsHandler","kind":"identifier"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"typeIdentifier","text":"OVKStatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","value":"OVKInteractiveStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler\/fragments","value":[{"text":"OVKInteractiveStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1playerInterfaceClick(source:)\/title","value":"playerInterfaceClickWithSource:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1playerInterfaceClick(source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerInterfaceClickWithSource:"}]},{"value":"OVKStatsCollector","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"value":"interactiveMovieStartWithRootInteractiveVideoID:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1interactiveMovieStart(rootInteractiveVideoID:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1interactiveMovieStart(rootInteractiveVideoID:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interactiveMovieStartWithRootInteractiveVideoID:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace","value":"OVKStatsHandler"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1nextMovie(movieId:)\/title","value":"nextMovieWithMovieId:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"nextMovieWithMovieId:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveStatsHandler~1nextMovie(movieId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}