{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"InterstitialStatsDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialStatsDelegate"}],"modules":[{"name":"OVKit"}],"roleHeading":"Protocol","title":"InterstitialStatsDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKInterstitialStatsDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialStatsDelegate"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Делегат для статистики прерываний."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate"]}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialComplete(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialEmpty(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialLoad()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialProgress(info:playTime:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialRequest(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialSkip(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialStart(info:duration:)"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialComplete(info:)":{"role":"symbol","abstract":[{"type":"text","text":"Уведомляет о завершении воспроизведения прерывания."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","text":"InterstitialInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialCompleteWithInfo:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialComplete(info:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialcomplete(info:)","kind":"symbol","title":"logInterstitialComplete(info:)"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Делегат для статистики прерываний."}],"navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","kind":"symbol","title":"InterstitialStatsDelegate"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialStart(info:duration:)":{"role":"symbol","abstract":[{"type":"text","text":"Уведомляет о начале воспроизведения прерывания."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialStartWithInfo:duration:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialStart(info:duration:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialstart(info:duration:)","kind":"symbol","title":"logInterstitialStart(info:duration:)"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialProgress(info:playTime:duration:)":{"url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialprogress(info:playtime:duration:)","type":"topic","title":"logInterstitialProgress(info:playTime:duration:)","abstract":[{"type":"text","text":"Уведомляет о прогрессе воспроизведения прерывания."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"playTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialProgressWithInfo:playTime:duration:"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialProgress(info:playTime:duration:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialLoad()":{"role":"symbol","abstract":[{"text":"Уведомляет о начале загрузки прерываний.","type":"text"}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialLoad"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialLoad"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialLoad()","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialload()","kind":"symbol","title":"logInterstitialLoad()"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialSkip(info:)":{"abstract":[{"text":"Уведомляет о пропуске прерывания.","type":"text"}],"type":"topic","title":"logInterstitialSkip(info:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialskip(info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","kind":"typeIdentifier","text":"InterstitialInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialSkip(info:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialRequest(info:)":{"role":"symbol","abstract":[{"type":"text","text":"Уведомляет о запросе конкретного прерывания."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InterstitialInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"logInterstitialRequestWithInfo:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialRequest(info:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialrequest(info:)","kind":"symbol","title":"logInterstitialRequest(info:)"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialFailed(reason:)":{"role":"symbol","abstract":[{"type":"text","text":"Уведомляет о неудачной попытке загрузки прерываний."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logInterstitialFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialFailedWithReason:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialFailed(reason:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialfailed(reason:)","kind":"symbol","title":"logInterstitialFailed(reason:)"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialEmpty(responseTime:)":{"role":"symbol","abstract":[{"text":"Уведомляет о получении пустого ответа при запросе прерываний.","type":"text"}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialEmpty"},{"kind":"text","text":"("},{"kind":"externalParam","text":"responseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialEmpty(responseTime:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialempty(responsetime:)","kind":"symbol","title":"logInterstitialEmpty(responseTime:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKInterstitialStatsDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialComplete(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialEmpty(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialLoad()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialProgress(info:playTime:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialRequest(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialSkip(info:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialStart(info:duration:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"logInterstitialCompleteWithInfo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialComplete(info:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialCompleteWithInfo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialComplete(info:)\/fragments","op":"replace"},{"value":"OVKInterstitialStatsDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle","op":"replace"},{"value":"logInterstitialStartWithInfo:duration:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialStart(info:duration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialStartWithInfo:duration:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialStart(info:duration:)\/fragments","op":"replace"},{"value":"logInterstitialProgressWithInfo:playTime:duration:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialProgress(info:playTime:duration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialProgressWithInfo:playTime:duration:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialProgress(info:playTime:duration:)\/fragments","op":"replace"},{"value":"logInterstitialLoad","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialLoad()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialLoad"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialLoad()\/fragments","op":"replace"},{"value":"logInterstitialSkipWithInfo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialSkip(info:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialSkip(info:)\/fragments","op":"replace"},{"value":"logInterstitialRequestWithInfo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialRequest(info:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialRequestWithInfo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialRequest(info:)\/fragments","op":"replace"},{"value":"logInterstitialFailedWithReason:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialFailed(reason:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialFailedWithReason:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialFailed(reason:)\/fragments","op":"replace"},{"value":"logInterstitialEmptyWithResponseTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialEmpty(responseTime:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialEmpty(responseTime:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}