{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Информация о прерывании."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKInterstitialInfo) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialInfo","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/interstitialinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interstitialinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialInfo","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"InterstitialInfo","navigatorTitle":[{"text":"InterstitialInfo","kind":"identifier"}],"symbolKind":"protocol"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/bannerInfo","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/startSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/subtype"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","abstract":[{"type":"text","text":"Информация о прерывании."}],"title":"InterstitialInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/subtype":{"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"subtype","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/subtype","abstract":[{"type":"text","text":"Подтип."}],"url":"\/documentation\/ovkit\/interstitialinfo\/subtype","title":"subtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtype"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/name":{"role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/name","abstract":[{"text":"Тип.","type":"text"}],"url":"\/documentation\/ovkit\/interstitialinfo\/name","kind":"symbol","title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/bannerInfo":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/interstitialinfo\/bannerinfo","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/bannerInfo","title":"bannerInfo","abstract":[{"text":"Описание рекламного баннера.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier","text":"AdStatsBannerInfo"}]},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/id":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/id","url":"\/documentation\/ovkit\/interstitialinfo\/id","kind":"symbol","type":"topic","abstract":[{"text":"Идентификатор.","type":"text"}],"role":"symbol","title":"id","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo/startSec":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startSec","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"startSec","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/startSec","url":"\/documentation\/ovkit\/interstitialinfo\/startsec","type":"topic","kind":"symbol","abstract":[{"text":"Время старта относительно старта видео.","type":"text"}],"role":"symbol","title":"startSec","required":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKInterstitialInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/startSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo\/subtype"],"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"OVKInterstitialInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKInterstitialInfo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"op":"replace","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments"},{"op":"replace","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1subtype\/title","value":"subtype","op":"replace"},{"op":"replace","value":[{"text":"subtype","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1subtype\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1id\/title","op":"replace","value":"id"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1startSec\/title","value":"startSec","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo~1startSec\/fragments","value":[{"text":"startSec","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}