{"topicSections":[{"title":"Associated Types","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/ControllerType"],"anchor":"Associated-Types"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeController(for:options:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeControlsView(for:)"],"anchor":"Instance-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialProvider","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"Этот протокол необходимо реализовать для предоставления вашему ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" ","type":"text"},{"text":"конкретного экземпляра ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController"},{"text":", обычно соответствующего","type":"text"},{"text":" ","type":"text"},{"text":"месту размещения плеера и свойствам его ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},{"text":".","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"Типы управляемых контроллеров могут различаться, что делает этот протокол гибким","type":"text"},{"text":" ","type":"text"},{"text":"и многократно используемым для различных реализаций контроллеров.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"InterstitialProvider"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialProvider"}],"title":"InterstitialProvider","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit20InterstitialProviderP","role":"symbol","roleHeading":"Protocol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Дженерик-протокол поставщика контроллеров промежуточных прерываний (рекламы)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialprovider"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialController":{"kind":"symbol","title":"InterstitialController","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController","abstract":[{"text":"Протокол контроллера прерываний.","type":"text"}],"url":"\/documentation\/ovkit\/interstitialcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InterstitialController"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialController"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider/makeController(for:options:)":{"type":"topic","url":"\/documentation\/ovkit\/interstitialprovider\/makecontroller(for:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20InterstitialProviderP14ControllerTypeQa","text":"ControllerType"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeController(for:options:)","title":"makeController(for:options:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Создаёт контроллер прерываний "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController"},{"type":"text","text":" "},{"type":"text","text":"для переданного "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider/makeControlsView(for:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeControlsView(for:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/interstitialprovider\/makecontrolsview(for:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeControlsView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20InterstitialProviderP14ControllerTypeQa","text":"ControllerType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Создаёт контролы управления для переданного контроллера прерываний."}],"title":"makeControlsView(for:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/interstitialprovider","navigatorTitle":[{"kind":"identifier","text":"InterstitialProvider"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialProvider"}],"title":"InterstitialProvider","abstract":[{"text":"Дженерик-протокол поставщика контроллеров промежуточных прерываний (рекламы).","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider/ControllerType":{"type":"topic","url":"\/documentation\/ovkit\/interstitialprovider\/controllertype","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControllerType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22InterstitialControllerP","text":"InterstitialController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/ControllerType","title":"ControllerType","required":true,"role":"symbol","abstract":[{"type":"text","text":"Тип контроллера, который будет управлять этим поставщиком."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}]}]}