{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Текстовый визуальный компонент на основе "},{"type":"codeVoice","code":"UIKit\/UILabel"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/label"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/label"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UILabel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/bounds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/intrinsicContentSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/paragraphStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/textInsets"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/attributes(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/drawText(in:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/sizeThatFits(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)Label","title":"Label","symbolKind":"class","navigatorTitle":[{"text":"Label","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/oldpricelabel","title":"OldPriceLabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Label/initWithCoder:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithCoder:","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/label\/initwithcoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","role":"symbol","title":"initWithCoder:"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)UILetterformAwareAdjusting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","title":"UIKit.UILetterformAwareAdjusting"},"doc://onevideo.OVKit/documentation/OVKit/Label":{"kind":"symbol","abstract":[{"text":"Текстовый визуальный компонент на основе ","type":"text"},{"type":"codeVoice","code":"UIKit\/UILabel"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/ovkit\/label","title":"Label","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Label"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/Label/paragraphStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/paragraphStyle","type":"topic","kind":"symbol","title":"paragraphStyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paragraphStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSParagraphStyle","text":"NSParagraphStyle","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/label\/paragraphstyle","abstract":[{"text":"Стиль параграфа.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Label/intrinsicContentSize":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/intrinsicContentSize","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"type":"topic","kind":"symbol","title":"intrinsicContentSize","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/label\/intrinsiccontentsize","abstract":[]},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/documentation/OVKit/Label/text":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text","url":"\/documentation\/ovkit\/label\/text","kind":"symbol","navigatorTitle":[{"text":"text","kind":"identifier"}],"role":"symbol","abstract":[],"title":"text"},"doc://onevideo.OVKit/documentation/OVKit/Label/textInsets":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textInsets","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"role":"symbol","title":"textInsets","url":"\/documentation\/ovkit\/label\/textinsets","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/textInsets","abstract":[{"type":"text","text":"Отступы текста от краёв компонента."}],"type":"topic"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/objc(cs)UILabel":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UILabel","title":"UILabel"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/adsitembadge","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdsItemBadge","kind":"identifier"}],"title":"AdsItemBadge","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge"},"doc://onevideo.OVKit/documentation/OVKit/Label/drawText(in:)":{"title":"drawText(in:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/drawText(in:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"drawText","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"drawTextInRect:","kind":"identifier"}],"url":"\/documentation\/ovkit\/label\/drawtext(in:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Label/bounds":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/label\/bounds","title":"bounds","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"bounds"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/bounds"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Label/sizeThatFits(_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sizeThatFits","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"type":"topic","abstract":[],"title":"sizeThatFits(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/sizeThatFits(_:)","url":"\/documentation\/ovkit\/label\/sizethatfits(_:)"},"doc://onevideo.OVKit/documentation/OVKit/Label/attributes(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> [","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"type":"topic","url":"\/documentation\/ovkit\/label\/attributes(for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/attributes(for:)","kind":"symbol","role":"symbol","title":"attributes(for:)","abstract":[{"type":"text","text":"Шаблонный метод, конструирующий атрибуты для строки "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/objc(pl)UIContentSizeCategoryAdjusting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","title":"UIKit.UIContentSizeCategoryAdjusting","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Label/initWithFrame:":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithFrame:","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/ovkit\/label\/initwithframe:"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"Label","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"Label"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Label"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/bounds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/intrinsicContentSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/text"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/drawText(in:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithCoder:","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/initWithFrame:","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label\/sizeThatFits(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UILabel"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Label"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","value":"OldPriceLabel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","value":[{"kind":"identifier","text":"OldPriceLabel"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","op":"replace","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1intrinsicContentSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1text\/fragments","value":[{"text":"text","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"AdsItemBadge","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"text":"AdsItemBadge","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"drawTextInRect:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1drawText(in:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1drawText(in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"drawTextInRect:","kind":"identifier"}],"op":"replace"},{"value":"bounds","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1bounds\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]},{"value":"sizeThatFits:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1sizeThatFits(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeThatFits:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label~1sizeThatFits(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}