{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Протокол представления, содержащего текст."}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LabeledView"}],"title":"LabeledView","externalID":"s:5OVKit11LabeledViewP","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LabeledView"}],"roleHeading":"Protocol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LabeledView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/labeledview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView\/ovk_text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView\/ovk_textLabel"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"],"type":"conformingTypes","title":"Conforming Types"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LabeledView/ovk_text":{"required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView\/ovk_text","url":"\/documentation\/ovkit\/labeledview\/ovk_text","title":"ovk_text","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovk_text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/LabeledView/ovk_textLabel":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView\/ovk_textLabel","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovk_textLabel"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/labeledview\/ovk_textlabel","role":"symbol","abstract":[],"kind":"symbol","title":"ovk_textLabel"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}],"url":"\/documentation\/ovkit\/adsitembadge","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdsItemBadge"}],"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"kind":"symbol","type":"topic","title":"AdsItemBadge"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"url":"\/documentation\/ovkit\/oldpricelabel","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OldPriceLabel"}],"title":"OldPriceLabel","navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"},"doc://onevideo.OVKit/objc(cs)UIView":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIKit.UIView","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LabeledView":{"abstract":[{"type":"text","text":"Протокол представления, содержащего текст."}],"title":"LabeledView","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","navigatorTitle":[{"text":"LabeledView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LabeledView","kind":"identifier"}],"url":"\/documentation\/ovkit\/labeledview"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"AdsItemBadge"},{"value":[{"text":"AdsItemBadge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments"},{"value":[{"kind":"identifier","text":"AdsItemBadge"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle"},{"op":"replace","value":"OldPriceLabel","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title"},{"op":"replace","value":[{"text":"OldPriceLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments"},{"value":[{"kind":"identifier","text":"OldPriceLabel"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}