{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKLegacyPrefetchStrategy) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LegacyPrefetchStrategy"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy"},"abstract":[{"text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","type":"reference","isActive":true},{"text":".","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"title":"LegacyPrefetchStrategy","symbolKind":"class","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKLegacyPrefetchStrategy","navigatorTitle":[{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"roleHeading":"Class"},"variants":[{"paths":["\/documentation\/ovkit\/legacyprefetchstrategy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/legacyprefetchstrategy"]}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/init(config:)"],"title":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/config"],"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)"],"title":"Instance Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/config":{"title":"config","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/config","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/config","abstract":[{"type":"text","text":"Конфигурация от старого префетчера.."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"config"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)","abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"IndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchCountAhead","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PrefetchStrategy","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","kind":"symbol","url":"\/documentation\/ovkit\/prefetchstrategy","navigatorTitle":[{"kind":"identifier","text":"PrefetchStrategy"}],"title":"PrefetchStrategy"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/init(config:)":{"title":"init(config:)","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/init(config:)","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/init(config:)","abstract":[{"type":"text","text":"Создание стратегии."}],"kind":"symbol","navigatorTitle":[{"text":"initWithConfig:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"text":"ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"title":"LegacyPrefetchStrategy","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","url":"\/documentation\/ovkit\/legacyprefetchstrategy","abstract":[{"type":"text","text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","isActive":true},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LegacyPrefetchStrategy"}]},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"title":"ListPrefetcher","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"kind":"symbol","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ListPrefetcher","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)","abstract":[{"type":"text","text":"Получение длительности префетча для видеозаписи."}],"kind":"symbol","navigatorTitle":[{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"prefetchDurationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inBatchSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKLegacyPrefetchStrategy"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"OVKLegacyPrefetchStrategy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}]},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/config"],"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/init(config:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"config","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1config\/title"},{"op":"replace","value":[{"text":"config","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1config\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"},{"value":[{"kind":"text","text":"- "},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","op":"replace","value":"OVKPrefetchStrategy"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1init(config:)\/title","value":"initWithConfig:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1init(config:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfig:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title","value":"OVKLegacyPrefetchStrategy"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments"},{"op":"replace","value":"OVKListPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcher"}]},{"value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}