{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","interfaceLanguage":"swift"},"abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherconfig"]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/baseConfig","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/container","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/fastCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/normalBandwidthThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorBandwidthThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/slowCount"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/config()"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ListPrefetcherConfig","kind":"identifier"}],"navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"role":"symbol","title":"ListPrefetcherConfig","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","roleHeading":"Class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKListPrefetcherConfig) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"При инициализации автоматически проставляются параметры по умолчанию, если не указать иное."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/baseConfig":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/baseConfig","title":"baseConfig","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/listprefetcherconfig\/baseconfig","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"baseConfig"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/config()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/config()","title":"config()","type":"topic","abstract":[{"type":"text","text":"Создание конфигурации по умолчанию."}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/config()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"config"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/fastCount":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"fastCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/fastcount","abstract":[{"text":"Количество видео для загрузки наперед при быстром интернете.","type":"text"},{"type":"text","text":" "},{"text":"Значение по умолчанию – ","type":"text"},{"type":"codeVoice","code":"5"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/fastCount","type":"topic","title":"fastCount","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fastCount"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/slowCount":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"slowCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Количество видео для загрузки наперед при среднем интернете."},{"type":"text","text":" "},{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"2"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/slowCount","type":"topic","title":"slowCount","role":"symbol","navigatorTitle":[{"text":"slowCount","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/slowcount"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/poorBandwidthThreshold":{"url":"\/documentation\/ovkit\/listprefetcherconfig\/poorbandwidththreshold","navigatorTitle":[{"text":"poorBandwidthThreshold","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorBandwidthThreshold","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poorBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","title":"poorBandwidthThreshold","abstract":[{"type":"text","text":"Верхняя граница пропускной способности сети плохого качества."},{"type":"text","text":" "},{"type":"text","text":"Единицы измерения – "},{"type":"codeVoice","code":"bps"},{"type":"text","text":", значение по умолчанию – "},{"type":"codeVoice","code":"1300000"},{"type":"text","text":"."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)":{"url":"\/documentation\/ovkit\/listprefetcherconfig\/init(baseconfig:fastcount:slowcount:poorcount:normalbandwidththreshold:poorbandwidththreshold:container:)","navigatorTitle":[{"text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetcherConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig"},{"text":", ","kind":"text"},{"text":"fastCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"slowCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"poorCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"poorBandwidthThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"container","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?)","kind":"text"}],"type":"topic","title":"init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/container":{"url":"\/documentation\/ovkit\/listprefetcherconfig\/container","navigatorTitle":[{"kind":"identifier","text":"container"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"container"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Контейнер кеша. Задается в случае, если нужно использовать не общий кеш."}],"title":"container","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/container"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"url":"\/documentation\/ovkit\/listprefetcherconfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}],"title":"ListPrefetcherConfig","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/normalBandwidthThreshold":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/normalbandwidththreshold","title":"normalBandwidthThreshold","abstract":[{"type":"text","text":"Верхняя граница пропускной способности сети среднего качества."},{"type":"text","text":" "},{"type":"text","text":"Единицы измерения – "},{"type":"codeVoice","code":"bps"},{"type":"text","text":", значение по умолчанию – "},{"type":"codeVoice","code":"2500000"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/normalBandwidthThreshold","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"normalBandwidthThreshold","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig/poorCount":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poorCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/ovkit\/listprefetcherconfig\/poorcount","title":"poorCount","abstract":[{"type":"text","text":"Количество видео для загрузки наперед при слабом интернете."},{"type":"text","text":" "},{"type":"text","text":"Значение по умолчанию – "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorCount","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"poorCount","kind":"identifier"}]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKListPrefetcherConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/baseConfig","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/container","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/fastCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/normalBandwidthThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorBandwidthThreshold","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/poorCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/slowCount"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig\/config()"],"generated":true,"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKListPrefetcherConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1baseConfig\/title","value":"baseConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1baseConfig\/fragments","value":[{"text":"baseConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1config()\/title","value":"config"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1config()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"config","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1fastCount\/title","value":"fastCount"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1fastCount\/fragments","value":[{"text":"fastCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1slowCount\/title","value":"slowCount"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1slowCount\/fragments","value":[{"text":"slowCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorBandwidthThreshold\/title","value":"poorBandwidthThreshold"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorBandwidthThreshold\/fragments","value":[{"kind":"identifier","text":"poorBandwidthThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)\/title","value":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1init(baseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfig:fastCount:slowCount:poorCount:normalBandwidthThreshold:poorBandwidthThreshold:container:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1container\/title","value":"container"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1container\/fragments","value":[{"kind":"identifier","text":"container"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1normalBandwidthThreshold\/title","value":"normalBandwidthThreshold"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1normalBandwidthThreshold\/fragments","value":[{"kind":"identifier","text":"normalBandwidthThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorCount\/title","value":"poorCount"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig~1poorCount\/fragments","value":[{"kind":"identifier","text":"poorCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}