{"metadata":{"symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherDataSource"}],"role":"symbol","title":"ListPrefetcherDataSource","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDataSource"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource\/itemsForPrefetcher(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKListPrefetcherDataSource) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDataSource"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherdatasource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherdatasource"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource/itemsForPrefetcher(_:)":{"url":"\/documentation\/ovkit\/listprefetcherdatasource\/itemsforprefetcher(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource\/itemsForPrefetcher(_:)","abstract":[{"type":"text","text":"Метод, возвращающий текущий список для префетчера."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemsForPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier","text":"ListPrefetcher"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":"]"}],"title":"itemsForPrefetcher(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"itemsForPrefetcher:"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource":{"type":"topic","abstract":[{"type":"text","text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране."}],"title":"ListPrefetcherDataSource","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherDataSource","kind":"identifier"}],"navigatorTitle":[{"text":"ListPrefetcherDataSource","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcherdatasource","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKListPrefetcherDataSource"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherDataSource"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKListPrefetcherDataSource"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource\/itemsForPrefetcher(_:)"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKListPrefetcherDataSource","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"itemsForPrefetcher:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource~1itemsForPrefetcher(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"itemsForPrefetcher:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource~1itemsForPrefetcher(_:)\/fragments"},{"op":"replace","value":"OVKListPrefetcherDataSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/title"},{"op":"replace","value":[{"text":"OVKListPrefetcherDataSource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/fragments"},{"op":"replace","value":[{"text":"OVKListPrefetcherDataSource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}