{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcher"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},"metadata":{"platforms":[{"name":"Swift","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"100000.0","message":"Рекомендуется использовать IndexPrefetcher"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher","role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"title":"ListPrefetcher"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKListPrefetcher) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Осуществляет предзагрузку элементов в списках (например, ленте видео). Для этого необходимо установить "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","type":"reference","isActive":true},{"type":"text","text":", который позволит префетчеру получить содержимое списка. Помимо списков, этот префетчер можно использовать и для предзагрузки произвольных видео."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Отмена предзагрузки означает прерывание процесса предзагрузки, если оно выполняется в данный момент. Уже предзагруженные данные при этом не удаляются."}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"Все методы должны вызываться с главного потока."}],"type":"paragraph"}],"name":"Warning","type":"aside","style":"warning"}],"kind":"content"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/init(with:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/delegate"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/cancel(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:shouldPrefetchPreview:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetchItems(startingAt:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/stop()"],"generated":true,"anchor":"Instance-Methods"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Рекомендуется использовать IndexPrefetcher","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/cancel(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":")"}],"role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"type":"topic","abstract":[{"type":"text","text":"Отмена предзагрузки произвольного элемента."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/cancel(_:)","url":"\/documentation\/ovkit\/listprefetcher\/cancel(_:)","title":"cancel(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/prefetch(_:)":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:)","abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/prefetch(_:)","title":"prefetch(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetch:"}]},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"type":"topic","title":"ListPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/listprefetcher","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/delegate":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/delegate","abstract":[{"type":"text","text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListPrefetcherDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/delegate","title":"delegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/prefetchItems(startingAt:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startingAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/prefetchitems(startingat:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetchItems(startingAt:)","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Предзагрузка элементов списка после текущей позиции."}],"navigatorTitle":[{"kind":"identifier","text":"prefetchItemsWithStartingAt:"}],"title":"prefetchItems(startingAt:)"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/prefetch(_:shouldPrefetchPreview:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldPrefetchPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/prefetch(_:shouldprefetchpreview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:shouldPrefetchPreview:)","role":"symbol","deprecated":true,"abstract":[{"text":"Предзагрузка произвольного элемента отдельно от списка.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prefetch:shouldPrefetchPreview:"}],"title":"prefetch(_:shouldPrefetchPreview:)"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/dataSource":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","abstract":[{"type":"text","text":"Источник данных, из которого префетчер получает список ресурсов."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListPrefetcherDataSource","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource"},{"kind":"text","text":"?"}],"type":"topic","title":"dataSource","kind":"symbol","url":"\/documentation\/ovkit\/listprefetcher\/datasource","navigatorTitle":[{"kind":"identifier","text":"dataSource"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/init(with:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig"},{"kind":"text","text":")"}],"role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/init(with:)","url":"\/documentation\/ovkit\/listprefetcher\/init(with:)","title":"init(with:)"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/stop()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/stop()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/stop()","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Остановка предзагрузки у всех элементов, если она выполняется в данный момент."}],"navigatorTitle":[{"text":"stop","kind":"identifier"}],"title":"stop()"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKListPrefetcher","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/delegate"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/cancel(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/init(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:shouldPrefetchPreview:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetchItems(startingAt:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/stop()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKListPrefetcher"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[],"op":"replace","path":"\/deprecationSummary"},{"value":"cancel:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1cancel(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1cancel(_:)\/fragments"},{"value":"prefetch:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetch:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:)\/fragments"},{"value":"OVKListPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1delegate\/fragments"},{"value":"prefetchItemsWithStartingAt:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetchItems(startingAt:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchItemsWithStartingAt:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetchItems(startingAt:)\/fragments"},{"value":"prefetch:shouldPrefetchPreview:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:shouldPrefetchPreview:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetch:shouldPrefetchPreview:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:shouldPrefetchPreview:)\/fragments"},{"value":"dataSource","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1dataSource\/title"},{"value":[{"kind":"identifier","text":"dataSource"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1dataSource\/fragments"},{"value":"initWith:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1init(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWith:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1init(with:)\/fragments"},{"value":"stop","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1stop()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1stop()\/fragments"}]}]}