{"metadata":{"role":"symbol","navigatorTitle":[{"text":"ListPrefetcherDelegate","kind":"identifier"}],"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate","symbolKind":"protocol","title":"ListPrefetcherDelegate"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKListPrefetcherDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Протокол, через который ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherdelegate"]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didFailToPrefetchItem:withError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)"],"title":"Instance Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","title":"PrefetchItem"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"role":"symbol","deprecated":true,"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","kind":"symbol","title":"ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","abstract":[{"type":"text","text":"Протокол, через который "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"title":"ListPrefetcherDelegate","url":"\/documentation\/ovkit\/listprefetcherdelegate","navigatorTitle":[{"text":"ListPrefetcherDelegate","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier","text":"ListPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPrefetchItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalBytesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)","abstract":[{"type":"text","text":"Сообщает об успешном префетче конкретного "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true},{"type":"text","text":"."}],"title":"listPrefetcher(_:didPrefetchItem:totalBytesReceived:)","url":"\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:totalbytesreceived:)","navigatorTitle":[{"kind":"identifier","text":"listPrefetcher:didPrefetchItem:totalBytesReceived:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate/listPrefetcher(_:didFailToPrefetchItem:withError:)":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier","text":"ListPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPrefetchItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didFailToPrefetchItem:withError:)","abstract":[{"type":"text","text":"Сообщает об ошибке префетчинга конкретного "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true},{"type":"text","text":"."}],"title":"listPrefetcher(_:didFailToPrefetchItem:withError:)","url":"\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didfailtoprefetchitem:witherror:)","navigatorTitle":[{"kind":"identifier","text":"listPrefetcher:didFailToPrefetchItem:withError:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKListPrefetcherDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didFailToPrefetchItem:withError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKListPrefetcherDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/title","value":"OVKListPrefetcherDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:totalBytesReceived:)\/title","value":"listPrefetcher:didPrefetchItem:totalBytesReceived:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:totalBytesReceived:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPrefetcher:didPrefetchItem:totalBytesReceived:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didFailToPrefetchItem:withError:)\/title","value":"listPrefetcher:didFailToPrefetchItem:withError:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didFailToPrefetchItem:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPrefetcher:didFailToPrefetchItem:withError:"}],"op":"replace"}]}]}