{"metadata":{"navigatorTitle":[{"text":"LiveSettings","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"LiveSettings","externalID":"c:@M@OVKit@objc(cs)OVKLiveSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveSettings"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/ovkit\/livesettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/livesettings"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKLiveSettings) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveSettings","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/init(endless:maxRewindDuration:playbackDuration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/init(from:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/endless","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/playbackDuration"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"references":{"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/endless":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/endless","kind":"symbol","title":"endless","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endless","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/livesettings\/endless","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/maxRewindDuration":{"kind":"symbol","title":"maxRewindDuration","role":"symbol","abstract":[{"type":"text","text":"Максимальное время перемотки в секундах"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxRewindDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration","url":"\/documentation\/ovkit\/livesettings\/maxrewindduration"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/init(from:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/ovkit\/livesettings\/init(from:)","title":"init(from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/init(from:)","kind":"symbol","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/hash":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/ovkit\/livesettings\/hash","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/hash","title":"hash"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/playbackDuration":{"url":"\/documentation\/ovkit\/livesettings\/playbackduration","title":"playbackDuration","abstract":[{"text":"Сколько секунд прошло с начала стрима","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/playbackDuration","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/init(endless:maxRewindDuration:playbackDuration:)":{"title":"init(endless:maxRewindDuration:playbackDuration:)","url":"\/documentation\/ovkit\/livesettings\/init(endless:maxrewindduration:playbackduration:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"endless"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxRewindDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playbackDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/init(endless:maxRewindDuration:playbackDuration:)","navigatorTitle":[{"text":"initWithEndless:maxRewindDuration:playbackDuration:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/canRewind":{"url":"\/documentation\/ovkit\/livesettings\/canrewind","abstract":[],"title":"canRewind","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canRewind","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/isEqual(_:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/isEqual(_:)","url":"\/documentation\/ovkit\/livesettings\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","type":"topic"},"doc://onevideo.OVKit/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveSettings"}],"navigatorTitle":[{"kind":"identifier","text":"LiveSettings"}],"kind":"symbol","type":"topic","abstract":[],"title":"LiveSettings","role":"symbol","url":"\/documentation\/ovkit\/livesettings"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKLiveSettings","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLiveSettings"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLiveSettings"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/hash"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/init(endless:maxRewindDuration:playbackDuration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKLiveSettings"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1hash\/fragments","op":"replace"},{"value":"initWithEndless:maxRewindDuration:playbackDuration:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1init(endless:maxRewindDuration:playbackDuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithEndless:maxRewindDuration:playbackDuration:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1init(endless:maxRewindDuration:playbackDuration:)\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings~1isEqual(_:)\/fragments","op":"replace"},{"value":"OVKLiveSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLiveSettings"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments","op":"replace"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}