{"abstract":[{"text":"Статус прямой трансляции.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/failed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/postlive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/removed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/waiting"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/rawValue-swift.property"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawValue-swift.typealias"],"title":"Type Aliases","generated":true,"anchor":"Type-Aliases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"sections":[],"metadata":{"title":"LiveStatus","roleHeading":"Enumeration","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveStatus"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKLiveStatus","modules":[{"name":"OVKit"}],"symbolKind":"enum"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKLiveStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/livestatus"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/description":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/description","url":"\/documentation\/ovkit\/livestatus\/description","title":"description","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/finished":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/finished","title":"LiveStatus.finished","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/finished","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusFinished"}],"abstract":[{"type":"text","text":"Live завершен стримером. Трансляция ушла в нарезку, длительность видео и ссылки на запись не доступны."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/init(rawvalue:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/RawRepresentable-Implementations":{"url":"\/documentation\/ovkit\/livestatus\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","abstract":[],"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawRepresentable-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/init(from:)":{"type":"topic","role":"symbol","title":"init(from:)","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/init(from:)"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"abstract":[{"type":"text","text":"Статус прямой трансляции."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","title":"LiveStatus","url":"\/documentation\/ovkit\/livestatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/rawValue-swift.property":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/rawvalue-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","title":"rawValue","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/rawValue-swift.property"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/waiting":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"}],"navigatorTitle":[{"text":"OVKLiveStatusWaiting","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/waiting","title":"LiveStatus.waiting","url":"\/documentation\/ovkit\/livestatus\/waiting","type":"topic","abstract":[{"type":"text","text":"Стример не завершил Live, но по каким-то причинам нет видеопотока."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/postlive":{"title":"LiveStatus.postlive","navigatorTitle":[{"text":"OVKLiveStatusPostlive","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/postlive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postlive","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/postlive","abstract":[{"type":"text","text":"Live завершился и стал записью трансляции, доступны длительность и ссылки на запись."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/unknown":{"title":"LiveStatus.unknown","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/unknown","navigatorTitle":[{"text":"OVKLiveStatusUnknown","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Статус не определен или видео не является \/ не было трансляцией.","type":"text"}],"url":"\/documentation\/ovkit\/livestatus\/unknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/upcoming":{"abstract":[{"text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","title":"LiveStatus.upcoming","url":"\/documentation\/ovkit\/livestatus\/upcoming","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upcoming","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/RawValue-swift.typealias":{"url":"\/documentation\/ovkit\/livestatus\/rawvalue-swift.typealias","role":"symbol","type":"topic","navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"abstract":[],"title":"LiveStatus.RawValue","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawValue-swift.typealias"},"doc://onevideo.OVKit/Se":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/Se","title":"Swift.Decodable"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/failed":{"abstract":[{"type":"text","text":"Ошибка стриминга."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/failed","url":"\/documentation\/ovkit\/livestatus\/failed","title":"LiveStatus.failed","role":"symbol","navigatorTitle":[{"text":"OVKLiveStatusFailed","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","title":"LiveStatus.started","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/started","navigatorTitle":[{"text":"OVKLiveStatusStarted","kind":"identifier"}],"abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/Equatable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/Equatable-Implementations","url":"\/documentation\/ovkit\/livestatus\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/removed":{"kind":"symbol","abstract":[{"text":"Live был удален.","type":"text"}],"url":"\/documentation\/ovkit\/livestatus\/removed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"removed"}],"role":"symbol","navigatorTitle":[{"text":"OVKLiveStatusRemoved","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/removed","title":"LiveStatus.removed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKLiveStatus","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatus"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/failed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/finished","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/postlive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/removed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/unknown","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/waiting"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKLiveStatus"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKLiveStatusFinished","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1finished\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusFinished"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1finished\/fragments"},{"op":"replace","value":"OVKLiveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatus"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatus"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle"},{"op":"replace","value":"OVKLiveStatusWaiting","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1waiting\/title"},{"op":"replace","value":[{"text":"OVKLiveStatusWaiting","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1waiting\/fragments"},{"op":"replace","value":"OVKLiveStatusPostlive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1postlive\/title"},{"op":"replace","value":[{"text":"OVKLiveStatusPostlive","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1postlive\/fragments"},{"op":"replace","value":"OVKLiveStatusUnknown","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1unknown\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusUnknown"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1unknown\/fragments"},{"op":"replace","value":"OVKLiveStatusUpcoming","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/fragments"},{"op":"replace","value":"OVKLiveStatusFailed","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1failed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusFailed"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1failed\/fragments"},{"op":"replace","value":"OVKLiveStatusStarted","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title"},{"op":"replace","value":[{"text":"OVKLiveStatusStarted","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments"},{"op":"replace","value":"OVKLiveStatusRemoved","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1removed\/title"},{"op":"replace","value":[{"text":"OVKLiveStatusRemoved","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1removed\/fragments"}]}]}