{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@OVKit@E@OVKLoopBehavior","modules":[{"name":"OVKit"}],"title":"LoopBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoopBehavior","kind":"identifier"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"LoopBehavior"}]},"variants":[{"paths":["\/documentation\/ovkit\/loopbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/loopbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/always","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/never"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKLoopBehavior) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoopBehavior","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"title":"LoopBehavior","url":"\/documentation\/ovkit\/loopbehavior","navigatorTitle":[{"kind":"identifier","text":"LoopBehavior"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoopBehavior"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/always":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/always","kind":"symbol","type":"topic","title":"LoopBehavior.always","abstract":[{"text":"Всегда повторять воспроизведение.","type":"text"}],"url":"\/documentation\/ovkit\/loopbehavior\/always","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKLoopBehaviorAlways"}]},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","url":"\/documentation\/ovkit\/loopbehavior\/equatable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/never":{"abstract":[{"type":"text","text":"Никогда не повторять воспроизведение."}],"title":"LoopBehavior.never","url":"\/documentation\/ovkit\/loopbehavior\/never","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"never","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/never","role":"symbol","navigatorTitle":[{"text":"OVKLoopBehaviorNever","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/RawRepresentable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/ovkit\/loopbehavior\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/init(rawValue:)":{"url":"\/documentation\/ovkit\/loopbehavior\/init(rawvalue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/init(rawValue:)","type":"topic","title":"init(rawValue:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/auto":{"abstract":[{"type":"text","text":"Поведение зависит от настройки "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","type":"topic","kind":"symbol","title":"LoopBehavior.auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/loopbehavior\/auto"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/repeated":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"repeated"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","kind":"symbol","title":"repeated","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"repeated","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/ovkit\/videotype\/repeated"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKLoopBehavior","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKLoopBehavior"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/always","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/never"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKLoopBehavior","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKLoopBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle"},{"value":"OVKLoopBehaviorAlways","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1always\/title"},{"value":[{"text":"OVKLoopBehaviorAlways","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1always\/fragments"},{"value":"OVKLoopBehaviorNever","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1never\/title"},{"value":[{"text":"OVKLoopBehaviorNever","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1never\/fragments"},{"value":"OVKLoopBehaviorAuto","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/title"},{"value":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/fragments"},{"value":"repeated","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/title"},{"value":[{"text":"repeated","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}