{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mediaselectionoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mediaselectionoption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKMediaSelectionOption) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/isOriginal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/language","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/optionId"],"generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo"}],"abstract":[{"type":"text","text":"Опция медиадорожки."}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"externalID":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","navigatorTitle":[{"kind":"identifier","text":"MediaSelectionOption"}],"title":"MediaSelectionOption","roleHeading":"Class","symbolKind":"class","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption/optionId":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/optionId","type":"topic","navigatorTitle":[{"kind":"identifier","text":"optionId"}],"url":"\/documentation\/ovkit\/mediaselectionoption\/optionid","abstract":[{"type":"text","text":"Идентификатор опции."}],"title":"optionId","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption/isOriginal":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/isOriginal","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOriginal"}],"url":"\/documentation\/ovkit\/mediaselectionoption\/isoriginal","abstract":[{"type":"text","text":"Указывает, что контент этой опции на языке оригинала."}],"title":"isOriginal","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOriginal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption/name":{"title":"name","abstract":[{"type":"text","text":"Название опции для отображения в UI."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mediaselectionoption\/name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption/language":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/language","type":"topic","navigatorTitle":[{"kind":"identifier","text":"language"}],"url":"\/documentation\/ovkit\/mediaselectionoption\/language","abstract":[{"type":"text","text":"Язык контента медиадорожки."}],"title":"language","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"title":"MediaSelectionOption","abstract":[{"type":"text","text":"Опция медиадорожки."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","navigatorTitle":[{"text":"MediaSelectionOption","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mediaselectionoption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaSelectionOption","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"OVKMediaSelectionOption","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/isOriginal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/language","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/name","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption\/optionId"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKMediaSelectionOption","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"optionId","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1optionId\/title","op":"replace"},{"value":[{"text":"optionId","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1optionId\/fragments","op":"replace"},{"value":"isOriginal","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1isOriginal\/title","op":"replace"},{"value":[{"text":"isOriginal","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1isOriginal\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1name\/title","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1name\/fragments","op":"replace"},{"value":"language","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1language\/title","op":"replace"},{"value":[{"text":"language","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption~1language\/fragments","op":"replace"},{"value":"OVKMediaSelectionOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title","op":"replace"},{"value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","op":"replace"},{"value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}