{"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Набор медиадорожек, находящихся в видеоресурсе.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKMediaSelection) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelection"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Позволяет переключаться между медиадорожками. Например, можно сменить озвучку видео."}]},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","isActive":true},{"type":"text","text":" является валидным только для играющего в момент его получения ресурса. При смене видео он перестанет работать."}]}],"style":"warning"}]}],"variants":[{"paths":["\/documentation\/ovkit\/mediaselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mediaselection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelection"}],"navigatorTitle":[{"kind":"identifier","text":"MediaSelection"}],"externalID":"c:@M@OVKit@objc(cs)OVKMediaSelection","role":"symbol","title":"MediaSelection","modules":[{"name":"OVKit"}]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/activeAudioMediaOption","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/availableAudioMediaOptions"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MediaSelection/activeAudioMediaOption":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"activeAudioMediaOption","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/activeAudioMediaOption","url":"\/documentation\/ovkit\/mediaselection\/activeaudiomediaoption","kind":"symbol","type":"topic","abstract":[{"text":"Выбранная в данный момент опция аудио.","type":"text"}],"role":"symbol","title":"activeAudioMediaOption"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection/availableAudioMediaOptions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableAudioMediaOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"availableAudioMediaOptions","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/availableAudioMediaOptions","url":"\/documentation\/ovkit\/mediaselection\/availableaudiomediaoptions","kind":"symbol","type":"topic","abstract":[{"text":"Все доступные опции аудио.","type":"text"}],"role":"symbol","title":"availableAudioMediaOptions"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaSelection","kind":"identifier"}],"navigatorTitle":[{"text":"MediaSelection","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","url":"\/documentation\/ovkit\/mediaselection","kind":"symbol","type":"topic","abstract":[{"text":"Набор медиадорожек, находящихся в видеоресурсе.","type":"text"}],"role":"symbol","title":"MediaSelection"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"OVKMediaSelection","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"OVKMediaSelection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKMediaSelection"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/activeAudioMediaOption","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/availableAudioMediaOptions"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKMediaSelection"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1activeAudioMediaOption\/title","op":"replace","value":"activeAudioMediaOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1activeAudioMediaOption\/fragments","op":"replace","value":[{"text":"activeAudioMediaOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1availableAudioMediaOptions\/title","op":"replace","value":"availableAudioMediaOptions"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1availableAudioMediaOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"availableAudioMediaOptions"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title","op":"replace","value":"OVKMediaSelection"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments","op":"replace","value":[{"text":"OVKMediaSelection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/navigatorTitle","op":"replace","value":[{"text":"OVKMediaSelection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}