{"abstract":[{"text":"Вид меню.","type":"text"}],"metadata":{"modules":[{"name":"OVKit"}],"title":"MenuKind","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKMenuKind","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKMenuKind) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Можно использовать для кастомизации при отображении UI."}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menukind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menukind"]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/audioTrackSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/dataSavingOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackRateSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackSettings","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/qualityPresetSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/screencastDeviceSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/specificQualitySelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/subtitlesSelection"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuKind/playbackRateSelection":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindPlaybackRateSelection"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackRateSelection","url":"\/documentation\/ovkit\/menukind\/playbackrateselection","title":"MenuKind.playbackRateSelection","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRateSelection","kind":"identifier"}],"abstract":[{"type":"text","text":"Меню выбора скорости воспроизведения."}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuKind","kind":"identifier"}],"url":"\/documentation\/ovkit\/menukind","title":"MenuKind","abstract":[{"text":"Вид меню.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MenuKind","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/other":{"abstract":[{"text":"Меню выбора устройства для внешнего проигрывания.","type":"text"}],"url":"\/documentation\/ovkit\/menukind\/other","role":"symbol","title":"MenuKind.other","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindOther"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/init(rawValue:)":{"kind":"symbol","role":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/menukind\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/init(rawValue:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/screencastDeviceSelection":{"abstract":[{"type":"text","text":"Меню выбора устройства для внешнего проигрывания."}],"kind":"symbol","role":"symbol","title":"MenuKind.screencastDeviceSelection","url":"\/documentation\/ovkit\/menukind\/screencastdeviceselection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/screencastDeviceSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screencastDeviceSelection"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/qualityPresetSelection":{"type":"topic","abstract":[{"text":"Меню выбора пресета автоматического качества воспроизведения.","type":"text"}],"kind":"symbol","title":"MenuKind.qualityPresetSelection","navigatorTitle":[{"text":"OVKMenuKindQualityPresetSelection","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityPresetSelection","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/qualityPresetSelection","url":"\/documentation\/ovkit\/menukind\/qualitypresetselection"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/Equatable-Implementations":{"abstract":[],"type":"topic","kind":"article","url":"\/documentation\/ovkit\/menukind\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/playbackSettings":{"type":"topic","url":"\/documentation\/ovkit\/menukind\/playbacksettings","title":"MenuKind.playbackSettings","abstract":[{"text":"Главное меню, где собраны основные настройки воспроизведения.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackSettings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSettings"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindPlaybackSettings"}]},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/specificQualitySelection":{"abstract":[{"type":"text","text":"Меню выбора качества из конкретного набора значений."}],"navigatorTitle":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"specificQualitySelection","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/menukind\/specificqualityselection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/specificQualitySelection","title":"MenuKind.specificQualitySelection","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/audioTrackSelection":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrackSelection","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/audioTrackSelection","role":"symbol","abstract":[{"type":"text","text":"Меню выбора аудиодорожки."}],"type":"topic","url":"\/documentation\/ovkit\/menukind\/audiotrackselection","title":"MenuKind.audioTrackSelection","navigatorTitle":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/subtitlesSelection":{"navigatorTitle":[{"text":"OVKMenuKindSubtitlesSelection","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/menukind\/subtitlesselection","abstract":[{"text":"Меню выбора дорожки субтитров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/subtitlesSelection","title":"MenuKind.subtitlesSelection","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitlesSelection","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/RawRepresentable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/ovkit\/menukind\/rawrepresentable-implementations","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MenuKind/dataSavingOptions":{"abstract":[{"type":"text","text":"Меню опций включения режима экономии трафика."}],"url":"\/documentation\/ovkit\/menukind\/datasavingoptions","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuKindDataSavingOptions"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSavingOptions"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/dataSavingOptions","type":"topic","role":"symbol","title":"MenuKind.dataSavingOptions"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKMenuKind","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/audioTrackSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/dataSavingOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/other","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackRateSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/playbackSettings","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/qualityPresetSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/screencastDeviceSelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/specificQualitySelection","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuKind\/subtitlesSelection"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKMenuKind","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKMenuKindPlaybackRateSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackRateSelection\/title","op":"replace"},{"value":[{"text":"OVKMenuKindPlaybackRateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackRateSelection\/fragments","op":"replace"},{"value":"OVKMenuKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/title","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/fragments","op":"replace"},{"value":[{"text":"OVKMenuKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind\/navigatorTitle","op":"replace"},{"value":"OVKMenuKindOther","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1other\/title","op":"replace"},{"value":[{"text":"OVKMenuKindOther","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1other\/fragments","op":"replace"},{"value":"OVKMenuKindScreencastDeviceSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1screencastDeviceSelection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuKindScreencastDeviceSelection"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1screencastDeviceSelection\/fragments","op":"replace"},{"value":"OVKMenuKindQualityPresetSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1qualityPresetSelection\/title","op":"replace"},{"value":[{"text":"OVKMenuKindQualityPresetSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1qualityPresetSelection\/fragments","op":"replace"},{"value":"OVKMenuKindPlaybackSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackSettings\/title","op":"replace"},{"value":[{"text":"OVKMenuKindPlaybackSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1playbackSettings\/fragments","op":"replace"},{"value":"OVKMenuKindSpecificQualitySelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1specificQualitySelection\/title","op":"replace"},{"value":[{"text":"OVKMenuKindSpecificQualitySelection","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1specificQualitySelection\/fragments","op":"replace"},{"value":"OVKMenuKindAudioTrackSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1audioTrackSelection\/title","op":"replace"},{"value":[{"text":"OVKMenuKindAudioTrackSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1audioTrackSelection\/fragments","op":"replace"},{"value":"OVKMenuKindSubtitlesSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1subtitlesSelection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuKindSubtitlesSelection"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1subtitlesSelection\/fragments","op":"replace"},{"value":"OVKMenuKindDataSavingOptions","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1dataSavingOptions\/title","op":"replace"},{"value":[{"text":"OVKMenuKindDataSavingOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuKind~1dataSavingOptions\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}