{"metadata":{"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"title":"MenuStyle","externalID":"c:@M@OVKit@E@OVKMenuStyle","navigatorTitle":[{"kind":"identifier","text":"MenuStyle"}],"modules":[{"name":"OVKit"}]},"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships","title":"Conforms To"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageSubtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageTitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionCompact","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionMultiline"],"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKMenuStyle) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MenuStyle","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Стиль меню, в котором требуется отображать его пункты."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle"]},{"paths":["\/documentation\/ovkit\/menustyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/ovkit\/menustyle\/init(rawvalue:)"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuStyle"}],"url":"\/documentation\/ovkit\/menustyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","kind":"symbol","title":"MenuStyle","abstract":[{"type":"text","text":"Стиль меню, в котором требуется отображать его пункты."}],"role":"symbol","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/imageTitle":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageTitle","navigatorTitle":[{"text":"OVKMenuStyleImageTitle","kind":"identifier"}],"title":"MenuStyle.imageTitle","abstract":[{"text":"Пункты меню с иконкой и названием.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageTitle","kind":"identifier"}],"url":"\/documentation\/ovkit\/menustyle\/imagetitle"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/selectionMultiline":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionMultiline","kind":"identifier"}],"url":"\/documentation\/ovkit\/menustyle\/selectionmultiline","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleSelectionMultiline"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionMultiline","title":"MenuStyle.selectionMultiline","role":"symbol","abstract":[{"text":"Пункты меню с возможностью выбора, названием и многострочным описанием.","type":"text"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/Equatable-Implementations":{"url":"\/documentation\/ovkit\/menustyle\/equatable-implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/selectionCompact":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionCompact","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectionCompact"}],"title":"MenuStyle.selectionCompact","abstract":[{"type":"text","text":"Пункты меню с возможностью выбора, названием и однострочным описанием."}],"url":"\/documentation\/ovkit\/menustyle\/selectioncompact","navigatorTitle":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/imageSubtitle":{"url":"\/documentation\/ovkit\/menustyle\/imagesubtitle","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSubtitle"}],"title":"MenuStyle.imageSubtitle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleImageSubtitle"}],"type":"topic","abstract":[{"type":"text","text":"Пункты меню с иконкой, названием и описанием."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageSubtitle"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/menustyle\/rawrepresentable-implementations","kind":"article","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"OVKMenuStyle","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMenuStyle"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuStyle"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageSubtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageTitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionCompact","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionMultiline"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","value":"OVKMenuStyle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyle"}]},{"value":[{"text":"OVKMenuStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageTitle\/title","value":"OVKMenuStyleImageTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageTitle\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyleImageTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionMultiline\/title","value":"OVKMenuStyleSelectionMultiline"},{"value":[{"kind":"identifier","text":"OVKMenuStyleSelectionMultiline"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionMultiline\/fragments"},{"value":"OVKMenuStyleSelectionCompact","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionCompact\/title"},{"value":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionCompact\/fragments","op":"replace"},{"value":"OVKMenuStyleImageSubtitle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageSubtitle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageSubtitle\/fragments","op":"replace","value":[{"text":"OVKMenuStyleImageSubtitle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}