{"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Menu"}],"externalID":"c:@M@OVKit@objc(pl)OVKMenu","navigatorTitle":[{"kind":"identifier","text":"Menu"}],"title":"Menu","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol"},"abstract":[{"type":"text","text":"Модель, описывающая UI для построения меню плеера."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/menu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menu"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKMenu) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Menu"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Включает в себя содержимое меню и обработчики контроля над его жизненным циклом. На основе содержимого необходимо создать и показать на экране меню в любом виде. Для правильного представления важно использовать все предоставленные свойства."}]},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Меню может изменять свое содержимое уже после показа. Для отслеживания этих обновлений можно установить обработчик ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/onUpdate","type":"reference","isActive":true},{"text":". Кроме того, нужно обязательно сообщать о показе или скрытии меню при помощи вызовов ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()"},{"text":" и ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()"},{"type":"text","text":"."}]}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/contents","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/kind","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/onUpdate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/style"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()"],"anchor":"Instance-Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Menu/kind":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/kind","abstract":[{"type":"text","text":"Вид меню."}],"required":true,"title":"kind","url":"\/documentation\/ovkit\/menu\/kind","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"kind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Menu/didDismiss()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()","type":"topic","navigatorTitle":[{"text":"didDismiss","kind":"identifier"}],"required":true,"url":"\/documentation\/ovkit\/menu\/diddismiss()","abstract":[{"type":"text","text":"Необходимо вызвать сразу после скрытия меню с экрана"}],"kind":"symbol","title":"didDismiss()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismiss","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/onUpdate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/onUpdate","type":"topic","navigatorTitle":[{"text":"onUpdate","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Блок, который вызывается при обновлении меню. Вызов происходит с главного потока."}],"url":"\/documentation\/ovkit\/menu\/onupdate","title":"onUpdate","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","title":"Menu","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Menu","kind":"identifier"}],"url":"\/documentation\/ovkit\/menu","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}],"abstract":[{"text":"Модель, описывающая UI для построения меню плеера.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/style":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/style","type":"topic","navigatorTitle":[{"text":"style","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Стиль пунктов меню, который наиболее подходит для отображения. Значение не изменяется при обновлении меню."}],"url":"\/documentation\/ovkit\/menu\/style","title":"style","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"MenuStyle","preciseIdentifier":"c:@M@OVKit@E@OVKMenuStyle","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/didPresent()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didPresent"}],"required":true,"url":"\/documentation\/ovkit\/menu\/didpresent()","abstract":[{"text":"Необходимо вызвать сразу после появления меню на экране.","type":"text"}],"kind":"symbol","title":"didPresent()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPresent","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Menu/contents":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/contents","type":"topic","navigatorTitle":[{"text":"contents","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Данные для показа меню. Могут изменяться после того, как меню было показано."}],"url":"\/documentation\/ovkit\/menu\/contents","title":"contents","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contents","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MenuContents","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuContents"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKMenu","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenu"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenu"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/contents","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/kind","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/onUpdate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/style"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didDismiss()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu\/didPresent()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKMenu"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1kind\/title","value":"kind","op":"replace"},{"op":"replace","value":[{"text":"kind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1kind\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didDismiss()\/title","op":"replace","value":"didDismiss"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismiss"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didDismiss()\/fragments"},{"op":"replace","value":"onUpdate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1onUpdate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"onUpdate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1onUpdate\/fragments"},{"op":"replace","value":"OVKMenu","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title"},{"op":"replace","value":[{"text":"OVKMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenu"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/navigatorTitle"},{"op":"replace","value":"style","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1style\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1style\/fragments","op":"replace","value":[{"kind":"identifier","text":"style"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didPresent()\/title","op":"replace","value":"didPresent"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1didPresent()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPresent"}]},{"value":"contents","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1contents\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu~1contents\/fragments","op":"replace","value":[{"kind":"identifier","text":"contents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}