{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKModernVideoStatsHandler) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","text":"StatsHandler","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Набор событий и параметров еще не финализирован."}]}],"name":"Warning","style":"warning","type":"aside"}],"kind":"content"}],"abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"reference"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioOutput(type:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/bufferStarvation()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/changeFileFormat(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/downloadBytes(bytes:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/firstFrameRendered()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestFirstByte(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestReceived(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestRequest(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaFirstByte(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaRequest(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/modeChange()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackError(_:type:on:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackStarted(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playerReadyToPlay(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resetSession()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/retry(connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekFinished(to:method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekStarted()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/soundOn(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQuality()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQualityChangeRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoTrack(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/viewport(size:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/visibility(isInBackground:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/volume(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/watchCoverage(fromTime:toTime:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/modernvideostatshandler"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler"},"kind":"symbol","metadata":{"symbolKind":"protocol","title":"ModernVideoStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModernVideoStatsHandler","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKModernVideoStatsHandler","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"kind":"relationships","type":"inheritsFrom"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/resetSession()":{"abstract":[{"text":"Текущая сессия проигрывания закончилась, изменился vsid.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/resetsession()","title":"resetSession()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetSession","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resetSession","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resetSession()","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/audioTrack(label:language:)":{"abstract":[{"text":"Пользователь сменил аудиодорожку.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/audiotrack(label:language:)","title":"audioTrack(label:language:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"audioTrackWithLabel:language:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioTrack(label:language:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/start(fromTime:)":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/start(fromtime:)","abstract":[{"type":"text","text":"Видео начало играть в плеере, не важно userInitiated или нет."}],"title":"start(fromTime:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"startFromTime:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/start(fromTime:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/visibility(isInBackground:)":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/visibility(isinbackground:)","abstract":[{"type":"text","text":"Изменилась видимость приложения с плеером на экране."}],"title":"visibility(isInBackground:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isInBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"visibilityWithIsInBackground:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/visibility(isInBackground:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/watchCoverage(fromTime:toTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/watchCoverage(fromTime:toTime:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/watchcoverage(fromtime:totime:)","navigatorTitle":[{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchCoverage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"abstract":[{"text":"Непрерывно просмотренные отрезки видео.","type":"text"}],"title":"watchCoverage(fromTime:toTime:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/mediaFirstByte(connectionDetails:)":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/mediafirstbyte(connectiondetails:)","abstract":[{"type":"text","text":"Получен первый байт медиаданных (файл или медиа-дорожка)."}],"title":"mediaFirstByte(connectionDetails:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaFirstByte","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mediaFirstByteWithConnectionDetails:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaFirstByte(connectionDetails:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/bufferStarvation()":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/bufferstarvation()","abstract":[{"type":"text","text":"В буфере закончились данные, произошел stall."}],"title":"bufferStarvation()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bufferStarvation","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"bufferStarvation","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/bufferStarvation()","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/playbackSpeed(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"playbackSpeed:"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/playbackspeed(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playbackSpeed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackSpeed(_:)","title":"playbackSpeed(_:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Пользователь изменил скорость воспроизведения видео."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/didEnterFullscreen()":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didEnterFullscreen()","abstract":[{"text":"Произошел переход в полноэкранный режим.","type":"text"}],"title":"didEnterFullscreen()","url":"\/documentation\/ovkit\/modernvideostatshandler\/didenterfullscreen()","navigatorTitle":[{"text":"didEnterFullscreen","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/pause(currentTime:)":{"role":"symbol","abstract":[{"type":"text","text":"Пользователь нажал на паузу в плеере."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pauseWithCurrentTime:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/pause(currentTime:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/pause(currenttime:)","kind":"symbol","title":"pause(currentTime:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/changeFileFormat(_:)":{"kind":"symbol","title":"changeFileFormat(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/changeFileFormat(_:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/changefileformat(_:)","abstract":[{"type":"text","text":"Изменился текущий проигрываемый тип файла ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat"},{"type":"text","text":")."}],"role":"symbol","navigatorTitle":[{"text":"changeFileFormat:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeFileFormat","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/downloadBytes(bytes:)":{"role":"symbol","abstract":[{"type":"text","text":"Событие скачивания определенного количества байт плеером с сервера."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadBytes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"downloadBytesWithBytes:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/downloadBytes(bytes:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/downloadbytes(bytes:)","kind":"symbol","title":"downloadBytes(bytes:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/viewport(size:)":{"role":"symbol","abstract":[{"type":"text","text":"Изменился размер вью плеера на экране."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewport","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewportWithSize:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/viewport(size:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/viewport(size:)","kind":"symbol","title":"viewport(size:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoZoom()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoZoom()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/videozoom()","navigatorTitle":[{"text":"videoZoom","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoZoom","kind":"identifier"},{"text":"()","kind":"text"}],"title":"videoZoom()","abstract":[{"text":"Пользователь активировал зум через жест.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestRequest(connectionDetails:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestRequest(connectionDetails:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestrequest(connectiondetails:)","navigatorTitle":[{"kind":"identifier","text":"manifestRequestWithConnectionDetails:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkConnectionInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo"},{"kind":"text","text":")"}],"title":"manifestRequest(connectionDetails:)","abstract":[{"type":"text","text":"Сетевой клиент отправил запрос за mpd\/m3u8 манифестом."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/playbackError(_:type:on:)":{"role":"symbol","abstract":[{"text":"Произошла ошибка воспроизведения.","type":"text"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ErrorType","preciseIdentifier":"c:@M@OVKit@E@OVKErrorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"playbackError:type:on:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackError(_:type:on:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/playbackerror(_:type:on:)","kind":"symbol","title":"playbackError(_:type:on:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","kind":"symbol","title":"VideoStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestReceived(connectionDetails:)":{"role":"symbol","abstract":[{"type":"text","text":"Получен манифест."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manifestReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"manifestReceivedWithConnectionDetails:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestReceived(connectionDetails:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestreceived(connectiondetails:)","kind":"symbol","title":"manifestReceived(connectionDetails:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"kind":"symbol","title":"StatsCollector","type":"topic","url":"\/documentation\/ovkit\/statscollector","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Не привязан к ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/audioOutput(type:)":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/audiooutput(type:)","type":"topic","title":"audioOutput(type:)","abstract":[{"text":"Изменился аудио выход, на который выводится звук плеера.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioOutputType","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"audioOutputWithType:"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioOutput(type:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/didCloseFullscreen()":{"role":"symbol","abstract":[{"text":"Произошел выход из полноэкранного режима.","type":"text"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didCloseFullscreen","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didCloseFullscreen()","url":"\/documentation\/ovkit\/modernvideostatshandler\/didclosefullscreen()","kind":"symbol","title":"didCloseFullscreen()"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/stop(currentTime:stallTime:)":{"kind":"symbol","title":"stop(currentTime:stallTime:)","type":"topic","url":"\/documentation\/ovkit\/modernvideostatshandler\/stop(currenttime:stalltime:)","abstract":[{"type":"text","text":"Видео закончили смотреть."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopWithCurrentTime:stallTime:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stallTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/resume()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resume()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/resume()","navigatorTitle":[{"text":"resume","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"title":"resume()","abstract":[{"type":"text","text":"Видео было снято с паузы пользователем."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/volume(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Изменилась громкость плеера."}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"volume:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/volume(_:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/volume(_:)","kind":"symbol","title":"volume(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/mediaRequest(connectionDetails:)":{"kind":"symbol","title":"mediaRequest(connectionDetails:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaRequest(connectionDetails:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/mediarequest(connectiondetails:)","abstract":[{"type":"text","text":"Клиент отправил первый запрос за медиаданными (файл или медиа-дорожка)."}],"role":"symbol","navigatorTitle":[{"text":"mediaRequestWithConnectionDetails:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaRequest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"connectionDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","kind":"typeIdentifier","text":"NetworkConnectionInfo"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/manifestFirstByte(connectionDetails:)":{"role":"symbol","abstract":[{"text":"Получен первый байт манифеста (при его наличии).","type":"text"}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"manifestFirstByte"},{"kind":"text","text":"("},{"text":"connectionDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","text":"NetworkConnectionInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"manifestFirstByteWithConnectionDetails:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestFirstByte(connectionDetails:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/manifestfirstbyte(connectiondetails:)","kind":"symbol","title":"manifestFirstByte(connectionDetails:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/seekFinished(to:method:)":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","text":"StatsSeekMethod"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekFinished(to:method:)","abstract":[{"text":"Произошла перемотка.","type":"text"}],"title":"seekFinished(to:method:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/seekfinished(to:method:)","navigatorTitle":[{"kind":"identifier","text":"seekFinishedTo:method:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/retry(connectionType:connectionReused:)":{"role":"symbol","abstract":[{"text":"Произошла попытка повтора воспроизведения того же самого ресурса после ошибки.","type":"text"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"retryWithConnectionType:connectionReused:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/retry(connectionType:connectionReused:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/retry(connectiontype:connectionreused:)","kind":"symbol","title":"retry(connectionType:connectionReused:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/modeChange()":{"role":"symbol","abstract":[{"type":"text","text":"Изменился режим воспроизведения."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modeChange"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"modeChange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/modeChange()","url":"\/documentation\/ovkit\/modernvideostatshandler\/modechange()","kind":"symbol","title":"modeChange()"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler","navigatorTitle":[{"kind":"identifier","text":"ModernVideoStatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModernVideoStatsHandler"}],"abstract":[{"text":"Описание возможных событий на замену ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":".","type":"text"}],"title":"ModernVideoStatsHandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoTrack(_:)":{"role":"symbol","abstract":[{"text":"Изменилось качество, которое выбрал эстиматор.","type":"text"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoTrack","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","text":"VideoTrackInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoTrack:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoTrack(_:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/videotrack(_:)","kind":"symbol","title":"videoTrack(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/reachedEnd()":{"role":"symbol","abstract":[{"type":"text","text":"Видео было досмотрено до конца."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reachedEnd"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"reachedEnd"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/reachedEnd()","url":"\/documentation\/ovkit\/modernvideostatshandler\/reachedend()","kind":"symbol","title":"reachedEnd()"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/gravity(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Пользователь руками изменил gravity."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"gravity:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/gravity(_:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/gravity(_:)","kind":"symbol","title":"gravity(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/progressChanged(time:)":{"role":"symbol","abstract":[{"type":"text","text":"Текущее время проигрывания изменилось."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"progressChangedWithTime:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/progressChanged(time:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/progresschanged(time:)","kind":"symbol","title":"progressChanged(time:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/playbackStarted(with:)":{"abstract":[{"text":"Плеер начал проигрывание видео.","type":"text"}],"type":"topic","title":"playbackStarted(with:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/playbackstarted(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"playbackStartedWith:"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackStarted(with:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoQualityChangeRequest()":{"kind":"symbol","title":"videoQualityChangeRequest()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQualityChangeRequest()","abstract":[{"type":"text","text":"Плеер попросили выбрать качество воспроизведения."}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/videoqualitychangerequest()","role":"symbol","navigatorTitle":[{"text":"videoQualityChangeRequest","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQualityChangeRequest","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/soundOn(_:userInitiated:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"soundOn:userInitiated:"}],"url":"\/documentation\/ovkit\/modernvideostatshandler\/soundon(_:userinitiated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/soundOn(_:userInitiated:)","title":"soundOn(_:userInitiated:)","required":true,"role":"symbol","abstract":[{"text":"Изменилось состояние звука.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/failover(backupHost:)":{"role":"symbol","abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"failover","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backupHost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/failover(backupHost:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/failover(backuphost:)","kind":"symbol","title":"failover(backupHost:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","title":"StatsHandler","type":"topic","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/fileFormat":{"role":"symbol","abstract":[{"text":"Текущий выбранный для проигрывания формат. Может не быть, если воспроизведение еще не началось.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat","url":"\/documentation\/ovkit\/statscontext\/fileformat","kind":"symbol","title":"fileFormat"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/subtitles(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/subtitles(_:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/modernvideostatshandler\/subtitles(_:)","navigatorTitle":[{"text":"subtitles:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitles"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Пользователь включил, отключил или изменил язык субтитров.","type":"text"}],"title":"subtitles(_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/videoQuality()":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/videoquality()","abstract":[{"type":"text","text":"Изменилось качество картинки, воспроизводимой в данный момент."}],"title":"videoQuality()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"videoQuality","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQuality()","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/firstFrameRendered()":{"url":"\/documentation\/ovkit\/modernvideostatshandler\/firstframerendered()","abstract":[{"text":"Первый кадр видео декодирован и отрендерен.","type":"text"}],"title":"firstFrameRendered()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstFrameRendered"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"firstFrameRendered"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/firstFrameRendered()","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/playerReadyToPlay(with:)":{"role":"symbol","abstract":[{"type":"text","text":"Сигнализирует о том, что плеер получил достаточный размер буфера и готов играть."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerReadyToPlay"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"playerReadyToPlayWith:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playerReadyToPlay(with:)","url":"\/documentation\/ovkit\/modernvideostatshandler\/playerreadytoplay(with:)","kind":"symbol","title":"playerReadyToPlay(with:)"},"doc://onevideo.OVKit/documentation/OVKit/ModernVideoStatsHandler/seekStarted()":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekStarted"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekStarted()","abstract":[{"text":"Пользователь начал перемотку перемещением таймлайна, что привело к приостановке воспроизведения.","type":"text"}],"title":"seekStarted()","url":"\/documentation\/ovkit\/modernvideostatshandler\/seekstarted()","navigatorTitle":[{"kind":"identifier","text":"seekStarted"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKModernVideoStatsHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKModernVideoStatsHandler"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioOutput(type:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/bufferStarvation()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/changeFileFormat(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/downloadBytes(bytes:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/firstFrameRendered()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestFirstByte(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestReceived(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/manifestRequest(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaFirstByte(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/mediaRequest(connectionDetails:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/modeChange()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackError(_:type:on:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playbackStarted(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/playerReadyToPlay(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resetSession()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/retry(connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekFinished(to:method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/seekStarted()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/soundOn(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQuality()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoQualityChangeRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoTrack(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/viewport(size:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/visibility(isInBackground:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/volume(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ModernVideoStatsHandler\/watchCoverage(fromTime:toTime:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"OVKModernVideoStatsHandler","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","text":"OVKStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"typeIdentifier"},{"kind":"text","text":">"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1resetSession()\/title","value":"resetSession"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1resetSession()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetSession"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1audioTrack(label:language:)\/title","value":"audioTrackWithLabel:language:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1audioTrack(label:language:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"audioTrackWithLabel:language:","kind":"identifier"}]},{"value":"startFromTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1start(fromTime:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startFromTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1start(fromTime:)\/fragments","op":"replace"},{"value":"visibilityWithIsInBackground:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1visibility(isInBackground:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"visibilityWithIsInBackground:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1visibility(isInBackground:)\/fragments","op":"replace"},{"value":"watchCoverageFromTime:toTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1watchCoverage(fromTime:toTime:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1watchCoverage(fromTime:toTime:)\/fragments"},{"value":"mediaFirstByteWithConnectionDetails:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaFirstByte(connectionDetails:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mediaFirstByteWithConnectionDetails:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaFirstByte(connectionDetails:)\/fragments"},{"op":"replace","value":"bufferStarvation","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1bufferStarvation()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bufferStarvation"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1bufferStarvation()\/fragments"},{"op":"replace","value":"playbackSpeed:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackSpeed(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playbackSpeed:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackSpeed(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1didEnterFullscreen()\/title","value":"didEnterFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1didEnterFullscreen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"}]},{"op":"replace","value":"pauseWithCurrentTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1pause(currentTime:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1pause(currentTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pauseWithCurrentTime:","kind":"identifier"}],"op":"replace"},{"value":"changeFileFormat:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1changeFileFormat(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeFileFormat:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1changeFileFormat(_:)\/fragments"},{"value":"downloadBytesWithBytes:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1downloadBytes(bytes:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downloadBytesWithBytes:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1downloadBytes(bytes:)\/fragments"},{"value":"viewportWithSize:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1viewport(size:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewportWithSize:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1viewport(size:)\/fragments"},{"value":"videoZoom","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoZoom()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoZoom()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoZoom","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"manifestRequestWithConnectionDetails:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestRequest(connectionDetails:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"manifestRequestWithConnectionDetails:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestRequest(connectionDetails:)\/fragments"},{"value":"playbackError:type:on:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackError(_:type:on:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playbackError:type:on:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackError(_:type:on:)\/fragments"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"manifestReceivedWithConnectionDetails:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestReceived(connectionDetails:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestReceived(connectionDetails:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"manifestReceivedWithConnectionDetails:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle"},{"op":"replace","value":"audioOutputWithType:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1audioOutput(type:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"audioOutputWithType:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1audioOutput(type:)\/fragments"},{"op":"replace","value":"didCloseFullscreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1didCloseFullscreen()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didCloseFullscreen","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1didCloseFullscreen()\/fragments"},{"op":"replace","value":"stopWithCurrentTime:stallTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1stop(currentTime:stallTime:)\/fragments"},{"value":"resume","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1resume()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"resume","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1resume()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1volume(_:)\/title","value":"volume:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1volume(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"volume:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaRequest(connectionDetails:)\/title","value":"mediaRequestWithConnectionDetails:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1mediaRequest(connectionDetails:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mediaRequestWithConnectionDetails:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestFirstByte(connectionDetails:)\/title","value":"manifestFirstByteWithConnectionDetails:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1manifestFirstByte(connectionDetails:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"manifestFirstByteWithConnectionDetails:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekFinished(to:method:)\/title","value":"seekFinishedTo:method:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekFinished(to:method:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"seekFinishedTo:method:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1retry(connectionType:connectionReused:)\/title","value":"retryWithConnectionType:connectionReused:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1retry(connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"retryWithConnectionType:connectionReused:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"modeChange","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1modeChange()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1modeChange()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"modeChange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/title","value":"OVKModernVideoStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/fragments","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler\/navigatorTitle","value":[{"text":"OVKModernVideoStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoTrack(_:)\/title","value":"videoTrack:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoTrack(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoTrack:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1reachedEnd()\/title","value":"reachedEnd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1reachedEnd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reachedEnd","kind":"identifier"}],"op":"replace"},{"value":"gravity:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1gravity(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gravity:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1gravity(_:)\/fragments"},{"value":"progressChangedWithTime:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1progressChanged(time:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"progressChangedWithTime:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1progressChanged(time:)\/fragments"},{"value":"playbackStartedWith:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackStarted(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playbackStartedWith:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playbackStarted(with:)\/fragments"},{"value":"videoQualityChangeRequest","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQualityChangeRequest()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"videoQualityChangeRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQualityChangeRequest()\/fragments"},{"op":"replace","value":"soundOn:userInitiated:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1soundOn(_:userInitiated:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"soundOn:userInitiated:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1soundOn(_:userInitiated:)\/fragments"},{"op":"replace","value":"failoverWithBackupHost:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1failover(backupHost:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"failoverWithBackupHost:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1failover(backupHost:)\/fragments"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"subtitles:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1subtitles(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subtitles:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1subtitles(_:)\/fragments"},{"value":"videoQuality","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQuality()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoQuality"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1videoQuality()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1firstFrameRendered()\/title","value":"firstFrameRendered"},{"value":[{"kind":"text","text":"- "},{"text":"firstFrameRendered","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1firstFrameRendered()\/fragments"},{"value":"playerReadyToPlayWith:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playerReadyToPlay(with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerReadyToPlayWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1playerReadyToPlay(with:)\/fragments"},{"value":"seekStarted","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekStarted()\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ModernVideoStatsHandler~1seekStarted()\/fragments","value":[{"kind":"text","text":"- "},{"text":"seekStarted","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}