{"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner\/bannerId"],"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetbanner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetbanner"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetBanner"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetBanner","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"OVKit"}],"title":"MyTargetBanner","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetBanner","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetBanner","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetBanner/bannerId":{"navigatorTitle":[{"kind":"identifier","text":"bannerId"}],"abstract":[],"title":"bannerId","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner\/bannerId","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/mytargetbanner\/bannerid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner","title":"MyTargetInstreamAdBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetBanner":{"navigatorTitle":[{"text":"MyTargetBanner","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/mytargetbanner","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetBanner","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","title":"MyTargetBanner"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","title":"MyTargetInstreamAdVideoMotionBanner","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"MyTargetBanner","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MyTargetBanner","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MyTargetBanner","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner\/bannerId"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritedBy","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner"],"kind":"relationships","title":"Inherited By"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetBanner"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner~1bannerId\/title","value":"bannerId"},{"value":[{"kind":"identifier","text":"bannerId"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner~1bannerId\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title","value":"MyTargetInstreamAdBanner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}]},{"value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/title","value":"MyTargetBanner","op":"replace"},{"value":[{"text":"MyTargetBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/navigatorTitle","value":[{"text":"MyTargetBanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}