{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData"},"abstract":[{"type":"text","text":"Данные, которые необходимы для отображения поствью после баннера."}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/mytargetpostviewdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetpostviewdata"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/overlayViewColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/ovkit_backgroundImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/text"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"symbolKind":"protocol","title":"MyTargetPostViewData","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)MyTargetPostViewData","role":"symbol","navigatorTitle":[{"text":"MyTargetPostViewData","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/ovkit_backgroundImage":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_backgroundImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetImageData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/mytargetpostviewdata\/ovkit_backgroundimage","title":"ovkit_backgroundImage","abstract":[{"text":"Данные для фонового изображения.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/ovkit_backgroundImage","role":"symbol","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"ovkit_backgroundImage"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/text":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"Заголовок.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/text","type":"topic","title":"text","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/ovkit\/mytargetpostviewdata\/text"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/overlayViewColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overlayViewColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"abstract":[{"text":"Цвет затемнения.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/overlayViewColor","type":"topic","title":"overlayViewColor","required":true,"role":"symbol","navigatorTitle":[{"text":"overlayViewColor","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetpostviewdata\/overlayviewcolor"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","title":"MyTargetPostViewData","url":"\/documentation\/ovkit\/mytargetpostviewdata","abstract":[{"text":"Данные, которые необходимы для отображения поствью после баннера.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetPostViewData"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData/duration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/duration","title":"duration","url":"\/documentation\/ovkit\/mytargetpostviewdata\/duration","abstract":[{"type":"text","text":"Длительность отображения."}],"type":"topic","role":"symbol","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"duration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MyTargetPostViewData","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/overlayViewColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/ovkit_backgroundImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData\/text"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetPostViewData"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ovkit_backgroundImage","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1ovkit_backgroundImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ovkit_backgroundImage"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1ovkit_backgroundImage\/fragments"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1text\/title"},{"op":"replace","value":[{"kind":"identifier","text":"text"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1text\/fragments"},{"op":"replace","value":"overlayViewColor","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1overlayViewColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"overlayViewColor"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1overlayViewColor\/fragments"},{"op":"replace","value":"MyTargetPostViewData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetPostViewData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/navigatorTitle"},{"op":"replace","value":"duration","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1duration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"duration"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData~1duration\/fragments"}]}]}