{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner"]}],"kind":"symbol","metadata":{"title":"MyTargetInstreamAdBanner","roleHeading":"Protocol","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"symbolKind":"protocol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner"],"type":"inheritsFrom"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/adChoicesImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/advertisingLabel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowClose","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowCloseDelay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowPause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ctaText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasAdChoices","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasShoppable","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_shoppableAdsItems","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/size"],"title":"Instance Properties","anchor":"Instance-Properties"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdBanner"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetBanner","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","text":"MyTargetBanner"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/allowCloseDelay":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowCloseDelay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowCloseDelay","navigatorTitle":[{"kind":"identifier","text":"allowCloseDelay"}],"title":"allowCloseDelay","type":"topic","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/allowclosedelay","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/adChoicesImage":{"title":"adChoicesImage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"adChoicesImage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/adchoicesimage","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adChoicesImage"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/adChoicesImage","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/advertisingLabel":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertisingLabel"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/advertisingLabel","navigatorTitle":[{"text":"advertisingLabel","kind":"identifier"}],"title":"advertisingLabel","type":"topic","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/advertisinglabel","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","title":"MyTargetInstreamAdBanner","url":"\/documentation\/ovkit\/mytargetinstreamadbanner"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/ovkit_shoppableAdsItems":{"title":"ovkit_shoppableAdsItems","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ovkit_shoppableAdsItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol","text":"MyTargetShoppableAdsItemProtocol"},{"kind":"text","text":"]?"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_shoppableadsitems","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ovkit_shoppableAdsItems"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_shoppableAdsItems","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetBanner":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetBanner"}],"url":"\/documentation\/ovkit\/mytargetbanner","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","title":"MyTargetBanner","navigatorTitle":[{"kind":"identifier","text":"MyTargetBanner"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/size":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/size","navigatorTitle":[{"text":"size","kind":"identifier"}],"title":"size","type":"topic","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/size","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/hasAdChoices":{"title":"hasAdChoices","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAdChoices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/hasadchoices","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasAdChoices"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasAdChoices","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/duration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/duration","navigatorTitle":[{"text":"duration","kind":"identifier"}],"title":"duration","type":"topic","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/duration","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/allowClose":{"title":"allowClose","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowClose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/allowclose","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowClose"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowClose","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/allowPause":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowPause","navigatorTitle":[{"text":"allowPause","kind":"identifier"}],"title":"allowPause","type":"topic","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/allowpause","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/ctaText":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ctaText"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ctaText","navigatorTitle":[{"text":"ctaText","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/ctatext","title":"ctaText","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/hasShoppable":{"title":"hasShoppable","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasShoppable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/hasshoppable","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasShoppable"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasShoppable","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MyTargetInstreamAdBanner","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/adChoicesImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/advertisingLabel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowClose","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowCloseDelay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/allowPause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ctaText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasAdChoices","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/hasShoppable","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_shoppableAdsItems","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/size"],"anchor":"Instance-Properties"}]},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdBanner","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","kind":"typeIdentifier","text":"MyTargetBanner"},{"text":">","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowCloseDelay\/title","value":"allowCloseDelay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowCloseDelay\/fragments","value":[{"text":"allowCloseDelay","kind":"identifier"}]},{"value":"adChoicesImage","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1adChoicesImage\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"adChoicesImage"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1adChoicesImage\/fragments"},{"value":"advertisingLabel","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1advertisingLabel\/title"},{"value":[{"kind":"identifier","text":"advertisingLabel"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1advertisingLabel\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title","value":"MyTargetInstreamAdBanner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_shoppableAdsItems\/title","value":"ovkit_shoppableAdsItems","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_shoppableAdsItems\/fragments","op":"replace","value":[{"text":"ovkit_shoppableAdsItems","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/title","op":"replace","value":"MyTargetBanner"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/fragments","value":[{"kind":"identifier","text":"MyTargetBanner"}]},{"op":"replace","value":[{"text":"MyTargetBanner","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1size\/title","value":"size","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","value":"hasAdChoices","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1hasAdChoices\/title"},{"value":[{"text":"hasAdChoices","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1hasAdChoices\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1duration\/title","op":"replace","value":"duration"},{"op":"replace","value":[{"text":"duration","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1duration\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowClose\/title","op":"replace","value":"allowClose"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowClose\/fragments","value":[{"text":"allowClose","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowPause\/title","op":"replace","value":"allowPause"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1allowPause\/fragments","value":[{"kind":"identifier","text":"allowPause"}]},{"value":"ctaText","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ctaText\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ctaText\/fragments","value":[{"text":"ctaText","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1hasShoppable\/title","value":"hasShoppable"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1hasShoppable\/fragments","value":[{"kind":"identifier","text":"hasShoppable"}]}]}]}