{"metadata":{"roleHeading":"Protocol","title":"MyTargetShoppableAdsItemProtocol","symbolKind":"protocol","navigatorTitle":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MyTargetAdsItemProtocol","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/picture","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/url"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"title":"MyTargetShoppableAdsItemProtocol","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"title":"MyTargetAdsItemProtocol","url":"\/documentation\/ovkit\/mytargetadsitemprotocol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol/text":{"title":"text","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/text","navigatorTitle":[{"text":"text","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/text","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol/url":{"title":"url","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/url","navigatorTitle":[{"text":"url","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/url","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol/picture":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/picture","abstract":[],"required":true,"type":"topic","title":"picture","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/picture","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"picture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"picture"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MyTargetShoppableAdsItemProtocol","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/picture","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/url"]}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"text":"MyTargetAdsItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/title","op":"replace","value":"MyTargetShoppableAdsItemProtocol"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/fragments","op":"replace","value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/navigatorTitle","op":"replace","value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/title","op":"replace","value":"MyTargetAdsItemProtocol"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/fragments","op":"replace","value":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}]},{"value":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/navigatorTitle","op":"replace"},{"value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1text\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1text\/fragments","value":[{"kind":"identifier","text":"text"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1url\/title","value":"url","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"url"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1url\/fragments"},{"value":"picture","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1picture\/title"},{"op":"replace","value":[{"kind":"identifier","text":"picture"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1picture\/fragments"}]}]}