{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewHide()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewShow(postView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewUpdate(progress:duration:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","title":"MyTargetInstreamAdPostViewPlayerDelegate"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewHide()":{"navigatorTitle":[{"kind":"identifier","text":"onPostViewHide"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewHide"},{"kind":"text","text":"()"}],"abstract":[],"title":"onPostViewHide()","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewhide()","required":true,"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewHide()","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewShow(postView:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewShow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postView"},{"kind":"text","text":": "},{"text":"MyTargetPostViewData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onPostViewShowWithPostView:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewShow(postView:)","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewshow(postview:)","type":"topic","title":"onPostViewShow(postView:)","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewUpdate(progress:duration:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onPostViewUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewupdate(progress:duration:)","title":"onPostViewUpdate(progress:duration:)","kind":"symbol","navigatorTitle":[{"text":"onPostViewUpdateWithProgress:duration:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewUpdate(progress:duration:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate","kind":"symbol","title":"MyTargetInstreamAdPostViewPlayerDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MyTargetInstreamAdPostViewPlayerDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewHide()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewShow(postView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewUpdate(progress:duration:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewHide()\/title","value":"onPostViewHide","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewHide()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPostViewHide","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewShow(postView:)\/title","value":"onPostViewShowWithPostView:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewShow(postView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPostViewShowWithPostView:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewUpdate(progress:duration:)\/title","value":"onPostViewUpdateWithProgress:duration:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewUpdate(progress:duration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPostViewUpdateWithProgress:duration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/title","value":"MyTargetInstreamAdPostViewPlayerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/fragments","value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}