{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer","kind":"typeIdentifier","text":"MyTargetSimplePlayer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetSimplePlayer"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"MyTargetInstreamAdVideoMotionPlayer","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"role":"symbol","modules":[{"name":"OVKit"}]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/banner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/closeOnFinish","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/ovkit_delegate"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/play(videoMotionBanner:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/stop()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/banner":{"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/banner","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/banner","required":true,"abstract":[],"title":"banner","navigatorTitle":[{"kind":"identifier","text":"banner"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"banner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/closeOnFinish":{"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/closeonfinish","navigatorTitle":[{"kind":"identifier","text":"closeOnFinish"}],"kind":"symbol","required":true,"abstract":[],"title":"closeOnFinish","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/closeOnFinish","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeOnFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/stop()":{"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/stop()","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/stop()","required":true,"abstract":[],"title":"stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/play(videoMotionBanner:)":{"title":"play(videoMotionBanner:)","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/play(videomotionbanner:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"videoMotionBanner","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playWithVideoMotionBanner:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/play(videoMotionBanner:)","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","title":"MyTargetInstreamAdVideoMotionPlayer","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/ovkit_delegate":{"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/ovkit_delegate","navigatorTitle":[{"kind":"identifier","text":"ovkit_delegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/ovkit_delegate","required":true,"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[],"title":"ovkit_delegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer":{"kind":"symbol","abstract":[],"title":"MyTargetSimplePlayer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetSimplePlayer","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetsimpleplayer","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/banner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/closeOnFinish","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/ovkit_delegate"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/play(videoMotionBanner:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/stop()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer","text":"MyTargetSimplePlayer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetSimplePlayer"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"banner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1banner\/title"},{"op":"replace","value":[{"text":"banner","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1banner\/fragments"},{"op":"replace","value":"closeOnFinish","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1closeOnFinish\/title"},{"op":"replace","value":[{"text":"closeOnFinish","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1closeOnFinish\/fragments"},{"op":"replace","value":"stop","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1stop()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1stop()\/fragments"},{"op":"replace","value":"playWithVideoMotionBanner:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1play(videoMotionBanner:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playWithVideoMotionBanner:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1play(videoMotionBanner:)\/fragments"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle"},{"op":"replace","value":"ovkit_delegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1ovkit_delegate\/title"},{"op":"replace","value":[{"text":"ovkit_delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1ovkit_delegate\/fragments"},{"op":"replace","value":"MyTargetSimplePlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/title"},{"op":"replace","value":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/fragments"},{"op":"replace","value":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}