{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer\/text"]}],"sections":[],"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}],"title":"MyTargetInstreamAdVideoMotionDisclaimer","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondisclaimer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondisclaimer"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionDisclaimer/text":{"title":"text","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondisclaimer\/text","navigatorTitle":[{"kind":"identifier","text":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer\/text"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionDisclaimer":{"title":"MyTargetInstreamAdVideoMotionDisclaimer","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondisclaimer","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionDisclaimer"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MyTargetInstreamAdVideoMotionDisclaimer","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionDisclaimer\/text"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer~1text\/title","op":"replace"},{"value":[{"text":"text","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer~1text\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer\/title","value":"MyTargetInstreamAdVideoMotionDisclaimer","op":"replace"},{"value":[{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer\/fragments","op":"replace"},{"value":[{"text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionDisclaimer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}