{"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionData","roleHeading":"Protocol","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_disclaimer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_header","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_items"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData","type":"topic","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata","title":"MyTargetInstreamAdVideoMotionData","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData/ovkit_items":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_items","type":"topic","abstract":[],"navigatorTitle":[{"text":"ovkit_items","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_items","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionItem","text":"MyTargetInstreamAdVideoMotionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_items","title":"ovkit_items","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData/ovkit_disclaimer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_disclaimer","type":"topic","abstract":[],"navigatorTitle":[{"text":"ovkit_disclaimer","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_disclaimer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionDisclaimer","text":"MyTargetInstreamAdVideoMotionDisclaimer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_disclaimer","title":"ovkit_disclaimer","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData/ovkit_header":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_header","type":"topic","abstract":[],"navigatorTitle":[{"text":"ovkit_header","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_header","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader","text":"MyTargetInstreamAdVideoMotionHeader","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata\/ovkit_header","title":"ovkit_header","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionData","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_disclaimer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_header","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData\/ovkit_items"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionData"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/fragments"},{"op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/navigatorTitle"},{"op":"replace","value":"ovkit_items","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_items\/title"},{"op":"replace","value":[{"text":"ovkit_items","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_items\/fragments"},{"op":"replace","value":"ovkit_disclaimer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_disclaimer\/title"},{"op":"replace","value":[{"text":"ovkit_disclaimer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_disclaimer\/fragments"},{"op":"replace","value":"ovkit_header","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_header\/title"},{"op":"replace","value":[{"text":"ovkit_header","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData~1ovkit_header\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}