{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionitem"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionitem"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/ctaText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/currency","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/image","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/text"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"},{"kind":"text","text":" : "},{"text":"MyTargetAdsItemProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionItem","roleHeading":"Protocol","modules":[{"name":"OVKit"}],"title":"MyTargetInstreamAdVideoMotionItem","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionItem"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"],"type":"inheritsFrom"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem":{"title":"MyTargetInstreamAdVideoMotionItem","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionItem"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem/currency":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/currency","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem\/currency","title":"currency","required":true,"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"currency","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem/text":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/text","title":"text","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem\/text","type":"topic","navigatorTitle":[{"text":"text","kind":"identifier"}],"required":true,"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem/ctaText":{"title":"ctaText","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ctaText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/ctaText","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem\/ctatext","navigatorTitle":[{"text":"ctaText","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol":{"kind":"symbol","url":"\/documentation\/ovkit\/mytargetadsitemprotocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"title":"MyTargetAdsItemProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem/image":{"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem\/image","kind":"symbol","type":"topic","title":"image","navigatorTitle":[{"kind":"identifier","text":"image"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/image","abstract":[],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MyTargetInstreamAdVideoMotionItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionItem"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/ctaText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/currency","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/image","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem\/text"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol","text":"MyTargetAdsItemProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MyTargetInstreamAdVideoMotionItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1currency\/title","value":"currency","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1currency\/fragments","op":"replace","value":[{"kind":"identifier","text":"currency"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1text\/title","value":"text"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1text\/fragments","value":[{"kind":"identifier","text":"text"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1ctaText\/title","value":"ctaText","op":"replace"},{"op":"replace","value":[{"text":"ctaText","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1ctaText\/fragments"},{"op":"replace","value":"MyTargetAdsItemProtocol","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/fragments","value":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem~1image\/fragments","op":"replace","value":[{"text":"image","kind":"identifier"}]}]}]}