{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionHeader"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionHeader","title":"MyTargetInstreamAdVideoMotionHeader","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionHeader"}]},"kind":"symbol","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/adDisclaimerText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/ageRestrictionText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/icon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/linkText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/title"],"anchor":"Instance-Properties"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionheader"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionheader"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader":{"abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionHeader","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader/title":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader\/title","title":"title"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader/linkText":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"linkText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"linkText"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/linkText","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader\/linktext","type":"topic","required":true,"role":"symbol","title":"linkText"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader/adDisclaimerText":{"navigatorTitle":[{"kind":"identifier","text":"adDisclaimerText"}],"title":"adDisclaimerText","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/adDisclaimerText","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader\/addisclaimertext","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"adDisclaimerText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"required":true,"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader/icon":{"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader\/icon","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/icon","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"icon","kind":"identifier"}],"title":"icon","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionHeader/ageRestrictionText":{"abstract":[],"title":"ageRestrictionText","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionheader\/agerestrictiontext","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ageRestrictionText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/ageRestrictionText","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ageRestrictionText"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MyTargetInstreamAdVideoMotionHeader"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionHeader"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/adDisclaimerText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/ageRestrictionText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/icon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/linkText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionHeader\/title"],"generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MyTargetInstreamAdVideoMotionHeader","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader\/title"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionHeader"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader\/navigatorTitle","value":[{"text":"MyTargetInstreamAdVideoMotionHeader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1title\/title","value":"title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1linkText\/title","op":"replace","value":"linkText"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1linkText\/fragments","value":[{"kind":"identifier","text":"linkText"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1adDisclaimerText\/title","value":"adDisclaimerText","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1adDisclaimerText\/fragments","op":"replace","value":[{"text":"adDisclaimerText","kind":"identifier"}]},{"value":"icon","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1icon\/title"},{"value":[{"text":"icon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1icon\/fragments"},{"value":"ageRestrictionText","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1ageRestrictionText\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionHeader~1ageRestrictionText\/fragments","op":"replace","value":[{"text":"ageRestrictionText","kind":"identifier"}]}]}]}