{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetCallToActionData","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCallToActionData"}],"modules":[{"name":"OVKit"}],"roleHeading":"Protocol","title":"MyTargetCallToActionData"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCallToActionData"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Данные, которые необходимы для отображения CTA-блока в баннере."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetcalltoactiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/additionalText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonTextColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/ovkit_icon"],"anchor":"Instance-Properties","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/buttonText":{"role":"symbol","abstract":[{"type":"text","text":"Текст на кнопке CTA."}],"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"buttonText","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonText","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/buttontext","kind":"symbol","title":"buttonText"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/ovkit_icon":{"abstract":[{"text":"Иконка CTA-блока.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/ovkit_icon","title":"ovkit_icon","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_icon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetImageData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetImageData"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"ovkit_icon","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/ovkit_icon","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"kind":"symbol","title":"MyTargetCallToActionData","type":"topic","url":"\/documentation\/ovkit\/mytargetcalltoactiondata","abstract":[{"type":"text","text":"Данные, которые необходимы для отображения CTA-блока в баннере."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetCallToActionData"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/buttonColor":{"role":"symbol","abstract":[{"type":"text","text":"Цвет кнопки CTA."}],"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"buttonColor","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonColor","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/buttoncolor","kind":"symbol","title":"buttonColor"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/buttonTextColor":{"url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/buttontextcolor","abstract":[{"text":"Цвет текста на кнопке CTA.","type":"text"}],"title":"buttonTextColor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"buttonTextColor"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonTextColor","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData/additionalText":{"role":"symbol","abstract":[{"type":"text","text":"Дополнительный текст CTA-блока."}],"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"additionalText","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/additionalText","url":"\/documentation\/ovkit\/mytargetcalltoactiondata\/additionaltext","kind":"symbol","title":"additionalText"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MyTargetCallToActionData","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/additionalText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonText","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/buttonTextColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData\/ovkit_icon"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetCallToActionData","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"buttonText","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"buttonText"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonText\/fragments","op":"replace"},{"value":"ovkit_icon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1ovkit_icon\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1ovkit_icon\/fragments","value":[{"kind":"identifier","text":"ovkit_icon"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title","value":"MyTargetCallToActionData"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments","value":[{"text":"MyTargetCallToActionData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetCallToActionData"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonColor\/title","value":"buttonColor"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonColor\/fragments","value":[{"kind":"identifier","text":"buttonColor"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonTextColor\/title","value":"buttonTextColor"},{"value":[{"kind":"identifier","text":"buttonTextColor"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1buttonTextColor\/fragments","op":"replace"},{"value":"additionalText","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1additionalText\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData~1additionalText\/fragments","value":[{"kind":"identifier","text":"additionalText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}