{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol"],"title":"Inherited By"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetadsitemprotocol"]},{"paths":["\/documentation\/ovkit\/mytargetadsitemprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/oldPrice","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/price"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"role":"symbol","title":"MyTargetAdsItemProtocol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetAdsItemProtocol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol","url":"\/documentation\/ovkit\/mytargetadsitemprotocol","abstract":[],"title":"MyTargetAdsItemProtocol","role":"symbol","navigatorTitle":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol/price":{"role":"symbol","title":"price","abstract":[],"url":"\/documentation\/ovkit\/mytargetadsitemprotocol\/price","required":true,"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/price","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"price","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"price"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol/oldPrice":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","required":true,"title":"oldPrice","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/oldPrice","url":"\/documentation\/ovkit\/mytargetadsitemprotocol\/oldprice","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"oldPrice","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"oldPrice"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionItem":{"abstract":[],"kind":"symbol","title":"MyTargetInstreamAdVideoMotionItem","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol":{"type":"topic","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol","title":"MyTargetShoppableAdsItemProtocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","navigatorTitle":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetAdsItemProtocol/id":{"role":"symbol","title":"id","abstract":[],"url":"\/documentation\/ovkit\/mytargetadsitemprotocol\/id","required":true,"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/id","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MyTargetAdsItemProtocol","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetAdsItemProtocol"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/id","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/oldPrice","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetAdsItemProtocol\/price"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionItem","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetAdsItemProtocol"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/title","value":"MyTargetAdsItemProtocol","op":"replace"},{"value":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/fragments"},{"value":[{"text":"MyTargetAdsItemProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol\/navigatorTitle"},{"op":"replace","value":"price","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1price\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1price\/fragments","value":[{"text":"price","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1oldPrice\/title","value":"oldPrice"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1oldPrice\/fragments","value":[{"kind":"identifier","text":"oldPrice"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem\/title","value":"MyTargetInstreamAdVideoMotionItem","op":"replace"},{"value":[{"text":"MyTargetInstreamAdVideoMotionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionItem\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/title","value":"MyTargetShoppableAdsItemProtocol","op":"replace"},{"value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/navigatorTitle","op":"replace"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1id\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetAdsItemProtocol~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}