{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayer"]}],"metadata":{"roleHeading":"Protocol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","title":"MyTargetInstreamAdPostViewPlayer","symbolKind":"protocol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/ovkit_delegate"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/hide()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/show(postView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/update(progress:duration:)"],"title":"Instance Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/show(postView:)":{"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/show(postview:)","navigatorTitle":[{"text":"showWithPostView:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"postView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetPostViewData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData"},{"text":")","kind":"text"}],"kind":"symbol","title":"show(postView:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/show(postView:)","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/update(progress:duration:)":{"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/update(progress:duration:)","title":"update(progress:duration:)","abstract":[],"navigatorTitle":[{"text":"updateWithProgress:duration:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/update(progress:duration:)","type":"topic","role":"symbol","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/hide()":{"navigatorTitle":[{"kind":"identifier","text":"hide"}],"title":"hide()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/hide()","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/hide()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hide","kind":"identifier"},{"kind":"text","text":"()"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer","title":"MyTargetInstreamAdPostViewPlayer","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer/ovkit_delegate":{"navigatorTitle":[{"text":"ovkit_delegate","kind":"identifier"}],"title":"ovkit_delegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/ovkit_delegate","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer\/ovkit_delegate","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate"},{"kind":"text","text":"?"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MyTargetInstreamAdPostViewPlayer"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}]},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/ovkit_delegate"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/hide()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/show(postView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer\/update(progress:duration:)"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1show(postView:)\/title","value":"showWithPostView:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showWithPostView:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1show(postView:)\/fragments"},{"value":"updateWithProgress:duration:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1update(progress:duration:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateWithProgress:duration:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1update(progress:duration:)\/fragments"},{"op":"replace","value":"hide","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1hide()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hide"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1hide()\/fragments"},{"value":"MyTargetInstreamAdPostViewPlayer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}]},{"value":"ovkit_delegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1ovkit_delegate\/title"},{"value":[{"text":"ovkit_delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer~1ovkit_delegate\/fragments"}]}]}