{"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetBanner","kind":"typeIdentifier","text":"MyTargetBanner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/adChoicesImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowClose","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowCloseDelay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/hasAdChoices","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/ovkit_videoMotionData"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionBanner","role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","symbolKind":"protocol"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/duration":{"kind":"symbol","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"navigatorTitle":[{"kind":"identifier","text":"duration"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/duration","type":"topic","title":"duration","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/duration"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/allowClose":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowClose","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowClose","title":"allowClose","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/allowclose","type":"topic","kind":"symbol","navigatorTitle":[{"text":"allowClose","kind":"identifier"}],"required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/ovkit_videoMotionData":{"kind":"symbol","title":"ovkit_videoMotionData","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/ovkit_videoMotionData","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_videoMotionData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData"}],"abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/ovkit_videomotiondata","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ovkit_videoMotionData"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetBanner":{"url":"\/documentation\/ovkit\/mytargetbanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","type":"topic","title":"MyTargetBanner","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetBanner"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MyTargetBanner"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/hasAdChoices":{"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/hasAdChoices","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAdChoices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/hasadchoices","navigatorTitle":[{"kind":"identifier","text":"hasAdChoices"}],"title":"hasAdChoices"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionBanner","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/allowCloseDelay":{"title":"allowCloseDelay","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowCloseDelay","kind":"symbol","abstract":[],"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowCloseDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"allowCloseDelay"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/allowclosedelay"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/adChoicesImage":{"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/adchoicesimage","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adChoicesImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"adChoicesImage","navigatorTitle":[{"text":"adChoicesImage","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/adChoicesImage"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"MyTargetInstreamAdVideoMotionBanner"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/adChoicesImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowClose","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/allowCloseDelay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/hasAdChoices","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/ovkit_videoMotionData"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetBanner","text":"MyTargetBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetBanner"},{"kind":"text","text":">"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1duration\/title","op":"replace","value":"duration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1duration\/fragments","op":"replace","value":[{"kind":"identifier","text":"duration"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1allowClose\/title","op":"replace","value":"allowClose"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1allowClose\/fragments","op":"replace","value":[{"text":"allowClose","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1ovkit_videoMotionData\/title","op":"replace","value":"ovkit_videoMotionData"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1ovkit_videoMotionData\/fragments","op":"replace","value":[{"text":"ovkit_videoMotionData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/title","op":"replace","value":"MyTargetBanner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/fragments","op":"replace","value":[{"text":"MyTargetBanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetBanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetBanner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1hasAdChoices\/title","op":"replace","value":"hasAdChoices"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1hasAdChoices\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasAdChoices"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","op":"replace","value":"MyTargetInstreamAdVideoMotionBanner"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1allowCloseDelay\/title","op":"replace","value":"allowCloseDelay"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1allowCloseDelay\/fragments","op":"replace","value":[{"text":"allowCloseDelay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1adChoicesImage\/title","op":"replace","value":"adChoicesImage"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1adChoicesImage\/fragments","op":"replace","value":[{"text":"adChoicesImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}