{"kind":"symbol","relationshipsSections":[{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetSimplePlayer","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/currentTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/paused"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/play()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/stop()"],"generated":true,"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/mytargetsimpleplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetsimpleplayer"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetSimplePlayer","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetSimplePlayer","role":"symbol","title":"MyTargetSimplePlayer","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer/paused":{"navigatorTitle":[{"text":"paused","kind":"identifier"}],"title":"paused","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/paused","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/mytargetsimpleplayer\/paused"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer/stop()":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"stop","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetsimpleplayer\/stop()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/stop()","abstract":[],"title":"stop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer/play()":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"play","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetsimpleplayer\/play()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/play()","abstract":[],"title":"play()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer/duration":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"duration","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetsimpleplayer\/duration","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/duration","abstract":[],"title":"duration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer/currentTime":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"currentTime"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/currentTime","url":"\/documentation\/ovkit\/mytargetsimpleplayer\/currenttime","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"currentTime","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionPlayer","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetSimplePlayer":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetSimplePlayer"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetSimplePlayer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer","url":"\/documentation\/ovkit\/mytargetsimpleplayer","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"MyTargetSimplePlayer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MyTargetSimplePlayer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MyTargetSimplePlayer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/currentTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/paused"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/play()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetSimplePlayer\/stop()"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"],"type":"inheritedBy"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetSimplePlayer"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1paused\/title","op":"replace","value":"paused"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1paused\/fragments","value":[{"text":"paused","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1stop()\/title","op":"replace","value":"stop"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stop"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1stop()\/fragments"},{"value":"play","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1play()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"play"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1play()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1duration\/title","op":"replace","value":"duration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1duration\/fragments","op":"replace","value":[{"kind":"identifier","text":"duration"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1currentTime\/title","op":"replace","value":"currentTime"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer~1currentTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"currentTime"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title","op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/title","value":"MyTargetSimplePlayer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetSimplePlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetSimplePlayer\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetSimplePlayer"}]}]}]}