{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerComplete()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerShow()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onCloseByUser()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onError(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onHeaderClick()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemClick(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemShow(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate","title":"MyTargetInstreamAdVideoMotionPlayerDelegate","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onCloseByUser()":{"required":true,"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onCloseByUser()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCloseByUser"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onCloseByUser"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onclosebyuser()","type":"topic","title":"onCloseByUser()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onBannerShow()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerShow","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerShow()","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"onBannerShow","kind":"identifier"}],"required":true,"title":"onBannerShow()","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onbannershow()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onHeaderClick()":{"required":true,"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onHeaderClick()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onHeaderClick"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onHeaderClick"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onheaderclick()","type":"topic","title":"onHeaderClick()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onItemShow(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onItemShow:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemShow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"onItemShow(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemShow(_:)","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onitemshow(_:)","type":"topic","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate","title":"MyTargetInstreamAdVideoMotionPlayerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onBannerComplete()":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onbannercomplete()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerComplete()","abstract":[],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerComplete"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"onBannerComplete"}],"kind":"symbol","title":"onBannerComplete()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onItemClick(_:)":{"title":"onItemClick(_:)","navigatorTitle":[{"kind":"identifier","text":"onItemClick:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemClick(_:)","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onitemclick(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","role":"symbol","required":true,"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onError(_:)":{"role":"symbol","title":"onError(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onError(_:)","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onerror(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"required":true,"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MyTargetInstreamAdVideoMotionPlayerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerComplete()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerShow()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onCloseByUser()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onError(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onHeaderClick()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemClick(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemShow(_:)"],"generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onCloseByUser()\/title","value":"onCloseByUser"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onCloseByUser()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCloseByUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerShow()\/title","value":"onBannerShow"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerShow()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onBannerShow"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onHeaderClick()\/title","value":"onHeaderClick"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onHeaderClick()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onHeaderClick","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemShow(_:)\/title","value":"onItemShow:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemShow(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onItemShow:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/title","value":"MyTargetInstreamAdVideoMotionPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerComplete()\/title","value":"onBannerComplete"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerComplete()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onBannerComplete","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemClick(_:)\/title","value":"onItemClick:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemClick(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onItemClick:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onError(_:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}