{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetImageData","kind":"identifier"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData"},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/data","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/image","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/url","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/useCache"]}],"abstract":[{"text":"Графические данные.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/mytargetimagedata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetimagedata"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetImageData","modules":[{"name":"OVKit"}],"symbolKind":"protocol","title":"MyTargetImageData","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetImageData","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"MyTargetImageData","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData/image":{"url":"\/documentation\/ovkit\/mytargetimagedata\/image","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic","abstract":[{"type":"text","text":"Изображение."}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/image","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData/data":{"navigatorTitle":[{"text":"data","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetimagedata\/data","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/data","title":"data","role":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData":{"abstract":[{"text":"Графические данные.","type":"text"}],"url":"\/documentation\/ovkit\/mytargetimagedata","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetImageData"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetImageData"}],"title":"MyTargetImageData"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData/size":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mytargetimagedata\/size","title":"size","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/size","abstract":[],"required":true,"navigatorTitle":[{"text":"size","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData/url":{"abstract":[{"type":"text","text":"Ссылка на оригинальное изображение."}],"required":true,"kind":"symbol","title":"url","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/url","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/ovkit\/mytargetimagedata\/url"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetImageData/useCache":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"useCache"}],"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetimagedata\/usecache","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/useCache","title":"useCache","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MyTargetImageData","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MyTargetImageData","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MyTargetImageData","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/data","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/image","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/url","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetImageData\/useCache"],"title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetImageData"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"image","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1image\/fragments"},{"op":"replace","value":"data","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1data\/title"},{"op":"replace","value":[{"text":"data","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1data\/fragments"},{"op":"replace","value":"MyTargetImageData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/title"},{"op":"replace","value":[{"text":"MyTargetImageData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/fragments"},{"op":"replace","value":[{"text":"MyTargetImageData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData\/navigatorTitle"},{"op":"replace","value":"size","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1size\/title"},{"op":"replace","value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1size\/fragments"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1url\/title"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1url\/fragments"},{"op":"replace","value":"useCache","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1useCache\/title"},{"op":"replace","value":[{"kind":"identifier","text":"useCache"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetImageData~1useCache\/fragments"}]}]}