{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/init(slotId:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/adPlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/loadingTimeout","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/midpoints","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_customParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_postViewPlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_videoMotionPlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppablePresented","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoSectionNames","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/volume"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/configureMidpoints(forVideoDuration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleAdChoicesClick(with:sourceView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleClick(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/load()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/pause()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemClick(forIdentifier:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemShow(forIdentifier:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skip()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skipBanner()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startMidroll(withPoint:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPostroll()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPreroll()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/stop()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/useDefaultPlayer()"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad"]}],"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAd"}],"symbolKind":"protocol","title":"MyTargetInstreamAd","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"title":"MyTargetInstreamAd","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamad","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/load()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"load"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/load()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/load()","navigatorTitle":[{"text":"load","kind":"identifier"}],"title":"load()","type":"topic","kind":"symbol","abstract":[],"required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/startPostroll()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startPostroll","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"startPostroll"}],"title":"startPostroll()","url":"\/documentation\/ovkit\/mytargetinstreamad\/startpostroll()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPostroll()","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/shoppableView":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shoppableView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/shoppableview","title":"shoppableView","abstract":[],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"shoppableView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableView","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/handleClick(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleClick"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"handleClickWithController:"}],"title":"handleClick(with:)","url":"\/documentation\/ovkit\/mytargetinstreamad\/handleclick(with:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleClick(with:)","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_postViewPlayer":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_postViewPlayer","title":"ovkit_postViewPlayer","url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_postviewplayer","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_postViewPlayer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"ovkit_postViewPlayer"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_delegate":{"navigatorTitle":[{"kind":"identifier","text":"ovkit_delegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdDelegate","text":"MyTargetInstreamAdDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","required":true,"title":"ovkit_delegate","url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_delegate","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/shoppablePresented":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shoppablePresented"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/shoppablepresented","title":"shoppablePresented","abstract":[],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"shoppablePresented"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppablePresented","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/skipBanner()":{"title":"skipBanner()","navigatorTitle":[{"text":"skipBanner","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skipBanner()","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad\/skipbanner()","required":true,"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipBanner"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/volume":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"volume"}],"title":"volume","url":"\/documentation\/ovkit\/mytargetinstreamad\/volume","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/volume","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/startPreroll()":{"url":"\/documentation\/ovkit\/mytargetinstreamad\/startpreroll()","kind":"symbol","abstract":[],"type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPreroll","kind":"identifier"},{"kind":"text","text":"()"}],"title":"startPreroll()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPreroll()","navigatorTitle":[{"text":"startPreroll","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/resume()":{"navigatorTitle":[{"text":"resume","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/resume()","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad\/resume()","title":"resume()","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/videoSectionNames":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoSectionNames"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/videosectionnames","title":"videoSectionNames","abstract":[],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"videoSectionNames"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoSectionNames","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/loadingTimeout":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadingTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/loadingTimeout","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadingTimeout"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/loadingtimeout","required":true,"title":"loadingTimeout"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/stop()":{"kind":"symbol","type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/stop()","url":"\/documentation\/ovkit\/mytargetinstreamad\/stop()","role":"symbol","navigatorTitle":[{"text":"stop","kind":"identifier"}],"title":"stop()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stop","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_customParams":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ovkit_customParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCustomParams","text":"MyTargetCustomParams"}],"abstract":[],"navigatorTitle":[{"text":"ovkit_customParams","kind":"identifier"}],"title":"ovkit_customParams","url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_customparams","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_customParams","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/videoQuality":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoQuality","title":"videoQuality","url":"\/documentation\/ovkit\/mytargetinstreamad\/videoquality","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"videoQuality"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/startMidroll(withPoint:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startMidroll"},{"kind":"text","text":"("},{"text":"withPoint","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"startMidrollWithPoint:"}],"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamad\/startmidroll(withpoint:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startMidroll(withPoint:)","title":"startMidroll(withPoint:)","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/skip()":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"skip"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad\/skip()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skip()","type":"topic","abstract":[],"navigatorTitle":[{"text":"skip","kind":"identifier"}],"title":"skip()","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_videoMotionPlayer":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_videoMotionPlayer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer","text":"MyTargetInstreamAdVideoMotionPlayer"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_videomotionplayer","title":"ovkit_videoMotionPlayer","abstract":[],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"ovkit_videoMotionPlayer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_videoMotionPlayer","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/midpoints":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"midpoints"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","required":true,"title":"midpoints","navigatorTitle":[{"kind":"identifier","text":"midpoints"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/midpoints","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/midpoints"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/shoppableAdsItemClick(forIdentifier:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemClick(forIdentifier:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shoppableAdsItemClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/shoppableadsitemclick(foridentifier:)","title":"shoppableAdsItemClick(forIdentifier:)","navigatorTitle":[{"text":"shoppableAdsItemClickForIdentifier:","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/pause()":{"title":"pause()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/pause()","kind":"symbol","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamad\/pause()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pause"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/shoppableAdsItemShow(forIdentifier:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shoppableAdsItemShow"},{"text":"(","kind":"text"},{"text":"forIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"shoppableAdsItemShowForIdentifier:"}],"title":"shoppableAdsItemShow(forIdentifier:)","url":"\/documentation\/ovkit\/mytargetinstreamad\/shoppableadsitemshow(foridentifier:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemShow(forIdentifier:)","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/init(slotId:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"slotId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/init(slotid:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/init(slotId:)","navigatorTitle":[{"text":"initWithSlotId:","kind":"identifier"}],"title":"init(slotId:)","type":"topic","kind":"symbol","abstract":[],"required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/adPlayerView":{"abstract":[],"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamad\/adplayerview","navigatorTitle":[{"kind":"identifier","text":"adPlayerView"}],"kind":"symbol","title":"adPlayerView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adPlayerView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/adPlayerView"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/useDefaultPlayer()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"useDefaultPlayer","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/usedefaultplayer()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/useDefaultPlayer()","navigatorTitle":[{"text":"useDefaultPlayer","kind":"identifier"}],"title":"useDefaultPlayer()","kind":"symbol","type":"topic","abstract":[],"required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/configureMidpoints(forVideoDuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureMidpoints","kind":"identifier"},{"kind":"text","text":"("},{"text":"forVideoDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/configuremidpoints(forvideoduration:)","title":"configureMidpoints(forVideoDuration:)","abstract":[],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"configureMidpointsForVideoDuration:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/configureMidpoints(forVideoDuration:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/handleAdChoicesClick(with:sourceView:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleAdChoicesClick"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sourceView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"handleAdChoicesClickWithController:sourceView:"}],"title":"handleAdChoicesClick(with:sourceView:)","url":"\/documentation\/ovkit\/mytargetinstreamad\/handleadchoicesclick(with:sourceview:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleAdChoicesClick(with:sourceView:)","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MyTargetInstreamAd"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/adPlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/loadingTimeout","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/midpoints","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_customParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_postViewPlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_videoMotionPlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppablePresented","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoSectionNames","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/volume"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/configureMidpoints(forVideoDuration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleAdChoicesClick(with:sourceView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/handleClick(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/init(slotId:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/load()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/pause()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemClick(forIdentifier:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemShow(forIdentifier:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skip()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skipBanner()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startMidroll(withPoint:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPostroll()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/startPreroll()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/stop()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/useDefaultPlayer()"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","op":"replace","value":"MyTargetInstreamAd"},{"value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1load()\/title","op":"replace","value":"load"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1load()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"load","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startPostroll()\/title","op":"replace","value":"startPostroll"},{"value":[{"text":"- ","kind":"text"},{"text":"startPostroll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startPostroll()\/fragments"},{"op":"replace","value":"shoppableView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableView\/fragments","value":[{"kind":"identifier","text":"shoppableView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1handleClick(with:)\/title","value":"handleClickWithController:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1handleClick(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleClickWithController:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_postViewPlayer\/title","value":"ovkit_postViewPlayer","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_postViewPlayer\/fragments","value":[{"text":"ovkit_postViewPlayer","kind":"identifier"}],"op":"replace"},{"value":"ovkit_delegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_delegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_delegate\/fragments","value":[{"kind":"identifier","text":"ovkit_delegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppablePresented\/title","value":"shoppablePresented","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppablePresented\/fragments","value":[{"text":"shoppablePresented","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skipBanner()\/title","value":"skipBanner"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skipBanner()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"skipBanner","kind":"identifier"}]},{"value":"volume","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1volume\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1volume\/fragments","value":[{"text":"volume","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startPreroll()\/title","value":"startPreroll"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startPreroll()\/fragments","value":[{"kind":"text","text":"- "},{"text":"startPreroll","kind":"identifier"}],"op":"replace"},{"value":"resume","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1resume()\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resume","kind":"identifier"}]},{"op":"replace","value":"videoSectionNames","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoSectionNames\/title"},{"value":[{"kind":"identifier","text":"videoSectionNames"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoSectionNames\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1loadingTimeout\/title","value":"loadingTimeout","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1loadingTimeout\/fragments","value":[{"kind":"identifier","text":"loadingTimeout"}],"op":"replace"},{"op":"replace","value":"stop","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1stop()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"stop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1stop()\/fragments"},{"value":"ovkit_customParams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_customParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_customParams\/fragments","value":[{"text":"ovkit_customParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoQuality\/title","value":"videoQuality","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoQuality\/fragments","op":"replace","value":[{"text":"videoQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startMidroll(withPoint:)\/title","value":"startMidrollWithPoint:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1startMidroll(withPoint:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startMidrollWithPoint:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skip()\/title","value":"skip","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"skip"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skip()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_videoMotionPlayer\/title","op":"replace","value":"ovkit_videoMotionPlayer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_videoMotionPlayer\/fragments","value":[{"text":"ovkit_videoMotionPlayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1midpoints\/title","value":"midpoints"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1midpoints\/fragments","op":"replace","value":[{"text":"midpoints","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemClick(forIdentifier:)\/title","value":"shoppableAdsItemClickForIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemClick(forIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shoppableAdsItemClickForIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1pause()\/title","value":"pause"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1pause()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pause"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemShow(forIdentifier:)\/title","op":"replace","value":"shoppableAdsItemShowForIdentifier:"},{"value":[{"text":"- ","kind":"text"},{"text":"shoppableAdsItemShowForIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemShow(forIdentifier:)\/fragments","op":"replace"},{"value":"initWithSlotId:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1init(slotId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1init(slotId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSlotId:","kind":"identifier"}]},{"value":"adPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1adPlayerView\/title"},{"value":[{"text":"adPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1adPlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1useDefaultPlayer()\/title","value":"useDefaultPlayer","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"useDefaultPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1useDefaultPlayer()\/fragments","op":"replace"},{"op":"replace","value":"configureMidpointsForVideoDuration:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1configureMidpoints(forVideoDuration:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1configureMidpoints(forVideoDuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureMidpointsForVideoDuration:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1handleAdChoicesClick(with:sourceView:)\/title","value":"handleAdChoicesClickWithController:sourceView:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1handleAdChoicesClick(with:sourceView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleAdChoicesClickWithController:sourceView:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}