{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/interactWithBanner()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onAdChoicesClick(sender:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onBannerSkip()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onClose()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onError(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onHeaderClick()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onItemClick(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onItemShow(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"title":"MyTargetInstreamAdVideoMotionViewDelegate","roleHeading":"Protocol","symbolKind":"protocol","externalID":"s:5OVKit41MyTargetInstreamAdVideoMotionViewDelegateP"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate"},"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"],"type":"conformingTypes"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"role":"symbol","title":"SupplementedAdControlsView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementedAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/DiscoverSupplementedAdControlsView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","url":"\/documentation\/ovkit\/discoversupplementedadcontrolsview","abstract":[{"text":"Рекламные контролы для отображения в рекомендациях.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"В отличии от базовых рекламных контролов "},{"type":"codeVoice","code":"SupplementedAdControlsView"},{"type":"text","text":" таймлайн отодвинут от границы плеера."}],"navigatorTitle":[{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"title":"DiscoverSupplementedAdControlsView","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onError(_:)":{"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onerror(_:)","type":"topic","title":"onError(_:)","role":"symbol","abstract":[{"type":"text","text":"Вызывается в момент возникновения внутренней ошибки в представлении."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onError(_:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onBannerSkip()":{"title":"onBannerSkip()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBannerSkip"},{"text":"()","kind":"text"}],"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onbannerskip()","abstract":[{"text":"Вызывается в момент нажатия на активную кнопку «Пропустить».","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onBannerSkip()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onItemShow(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onItemShow","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Вызывается в момент отображения на экране карточки товара","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(более чем на 50% площади карточки)."}],"kind":"symbol","required":true,"title":"onItemShow(_:)","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onitemshow(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onItemShow(_:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/interactWithBanner()":{"role":"symbol","required":true,"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"interactWithBanner","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/interactWithBanner()","title":"interactWithBanner()","abstract":[{"type":"text","text":"Вызывает в момент любого касания пользователя."}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/interactwithbanner()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionViewDelegate"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate","title":"MyTargetInstreamAdVideoMotionViewDelegate","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onItemClick(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onItemClick(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemClick"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onitemclick(_:)","title":"onItemClick(_:)","abstract":[{"text":"Вызывается в момент нажатия на карточку товара.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onHeaderClick()":{"title":"onHeaderClick()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onHeaderClick","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onheaderclick()","abstract":[{"text":"Вызывается в момент нажатия на шапку баннера.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onHeaderClick()"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onAdChoicesClick(sender:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onAdChoicesClick(sender:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onAdChoicesClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onadchoicesclick(sender:)","title":"onAdChoicesClick(sender:)","abstract":[{"text":"Вызывается в момент нажатия на кнопку информации о рекламе.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate/onClose()":{"required":true,"type":"topic","abstract":[{"type":"text","text":"Вызывается в момент нажатия кнопки “Закрыть плеер”."}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate\/onclose()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onClose","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","title":"onClose()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate\/onClose()"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"role":"symbol","abstract":[{"type":"text","text":"Рекламные контролы для Fullscreen."},{"type":"text","text":" "},{"text":"В отличии от базовых ","type":"text"},{"type":"codeVoice","code":"AdControlsView"},{"type":"text","text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров."}],"navigatorTitle":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview","title":"FullscreenSupplementedAdControlsView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","value":"SupplementedAdControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","value":[{"text":"SupplementedAdControlsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/title","value":"DiscoverSupplementedAdControlsView"},{"op":"replace","value":[{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/navigatorTitle","value":[{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/title","op":"replace","value":"FullscreenSupplementedAdControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/fragments","value":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}]}]}]}