{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/contains(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/cellularOnly()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiAndCellular()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiOnly()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKNetworkConnectionMask) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}]}]}],"metadata":{"role":"symbol","symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionMask"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}],"modules":[{"name":"OVKit"}],"roleHeading":"Class","title":"NetworkConnectionMask"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnectionmask"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnectionmask"]}],"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/wifiAndCellular()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiAndCellular()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/networkconnectionmask\/wifiandcellular()","navigatorTitle":[{"kind":"identifier","text":"wifiAndCellular"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiAndCellular"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"wifiAndCellular()","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/networkconnectionmask","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionMask"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}],"title":"NetworkConnectionMask","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/wifiOnly()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"wifiOnly"}],"url":"\/documentation\/ovkit\/networkconnectionmask\/wifionly()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiOnly"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiOnly()","title":"wifiOnly()","role":"symbol","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/contains(_:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contains:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKNetworkConnection","text":"NetworkConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/contains(_:)","url":"\/documentation\/ovkit\/networkconnectionmask\/contains(_:)","kind":"symbol","title":"contains(_:)"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/cellularOnly()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/cellularOnly()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/networkconnectionmask\/cellularonly()","navigatorTitle":[{"kind":"identifier","text":"cellularOnly"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellularOnly"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"cellularOnly()","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"OVKNetworkConnectionMask","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/contains(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/cellularOnly()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiAndCellular()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiOnly()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKNetworkConnectionMask"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiAndCellular()\/title","value":"wifiAndCellular","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiAndCellular()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"wifiAndCellular"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiOnly()\/title","value":"wifiOnly","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiOnly()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"wifiOnly"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1contains(_:)\/title","value":"contains:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1contains(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contains:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1cellularOnly()\/title","value":"cellularOnly","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1cellularOnly()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cellularOnly"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}