{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnection"]},{"paths":["\/documentation\/ovkit\/networkconnection"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKNetworkConnection) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnection"}]}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/cellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/wifi"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","title":"NetworkConnection","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKNetworkConnection","navigatorTitle":[{"text":"NetworkConnection","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NetworkConnection","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"title":"NetworkConnection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NetworkConnection"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnection"}],"url":"\/documentation\/ovkit\/networkconnection","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/wifi":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/wifi","navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionWifi"}],"type":"topic","url":"\/documentation\/ovkit\/networkconnection\/wifi","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifi"}],"title":"NetworkConnection.wifi","abstract":[],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/init(rawValue:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/networkconnection\/init(rawvalue:)","kind":"symbol"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/cellular":{"title":"NetworkConnection.cellular","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/cellular","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionCellular"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cellular","kind":"identifier"}],"url":"\/documentation\/ovkit\/networkconnection\/cellular","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/RawRepresentable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/ovkit\/networkconnection\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/none":{"title":"NetworkConnection.none","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/none","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"url":"\/documentation\/ovkit\/networkconnection\/none","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/Equatable-Implementations","type":"topic","url":"\/documentation\/ovkit\/networkconnection\/equatable-implementations","title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKNetworkConnection","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"OVKNetworkConnection","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKNetworkConnection","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/cellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/wifi"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKNetworkConnection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","value":"OVKNetworkConnection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]},{"value":[{"text":"OVKNetworkConnection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle"},{"value":"OVKNetworkConnectionWifi","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1wifi\/title"},{"value":[{"text":"OVKNetworkConnectionWifi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1wifi\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1cellular\/title","value":"OVKNetworkConnectionCellular","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1cellular\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionCellular"}],"op":"replace"},{"value":"OVKNetworkConnectionNone","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1none\/title"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}