{"variants":[{"paths":["\/documentation\/ovkit\/networkconnectioninfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/networkconnectioninfo"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","interfaceLanguage":"swift"},"abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}],"externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionInfo"}],"title":"NetworkConnectionInfo","role":"symbol","modules":[{"name":"OVKit"}]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/dnsLookupDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/reused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/rtt","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tcpHandshakeDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tlsHandshakeDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/type"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKNetworkConnectionInfo) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/tcpHandshakeDuration":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tcpHandshakeDuration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tcpHandshakeDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"text":"Время, затраченное на установку TCP-соединения. ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что время неизвестно."}],"type":"topic","title":"tcpHandshakeDuration","url":"\/documentation\/ovkit\/networkconnectioninfo\/tcphandshakeduration","role":"symbol","navigatorTitle":[{"text":"tcpHandshakeDuration","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"title":"NetworkConnectionInfo","url":"\/documentation\/ovkit\/networkconnectioninfo","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Набор параметров с информацией о сетевом соединении."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/reused":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/reused","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/networkconnectioninfo\/reused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"reused","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"Было ли переиспользовано соединение при загрузке элемента."}],"title":"reused","navigatorTitle":[{"text":"reused","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/dnsLookupDuration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/dnsLookupDuration","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/networkconnectioninfo\/dnslookupduration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dnsLookupDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Время, потраченное на резолв хоста ссылки, с которой идет проигрывание. ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что время неизвестно."}],"title":"dnsLookupDuration","navigatorTitle":[{"kind":"identifier","text":"dnsLookupDuration"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/rtt":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/rtt","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/networkconnectioninfo\/rtt","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rtt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"RTT или близкое к нему значение."}],"title":"rtt","navigatorTitle":[{"kind":"identifier","text":"rtt"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/type":{"title":"type","url":"\/documentation\/ovkit\/networkconnectioninfo\/type","abstract":[{"text":"Протокол, по которому идут запросы за видео к серверу.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/tlsHandshakeDuration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tlsHandshakeDuration","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/networkconnectioninfo\/tlshandshakeduration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tlsHandshakeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"Время, затраченное на установку  TLS-соединения. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что время неизвестно.","type":"text"}],"title":"tlsHandshakeDuration","navigatorTitle":[{"kind":"identifier","text":"tlsHandshakeDuration"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"OVKNetworkConnectionInfo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/dnsLookupDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/reused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/rtt","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tcpHandshakeDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tlsHandshakeDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/type"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKNetworkConnectionInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tcpHandshakeDuration\/title","value":"tcpHandshakeDuration","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tcpHandshakeDuration\/fragments","value":[{"kind":"identifier","text":"tcpHandshakeDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","value":"OVKNetworkConnectionInfo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1reused\/title","value":"reused","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1reused\/fragments","value":[{"kind":"identifier","text":"reused"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1dnsLookupDuration\/title","value":"dnsLookupDuration","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1dnsLookupDuration\/fragments","value":[{"kind":"identifier","text":"dnsLookupDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1rtt\/title","value":"rtt","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1rtt\/fragments","op":"replace","value":[{"text":"rtt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tlsHandshakeDuration\/title","op":"replace","value":"tlsHandshakeDuration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tlsHandshakeDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"tlsHandshakeDuration"}]}]}]}