{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_textLabel"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/attributes(for:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKOldPriceLabel) ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/oldpricelabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/oldpricelabel"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKOldPriceLabel","title":"OldPriceLabel"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKOldPriceLabel/initWithFrame:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithFrame:","abstract":[],"url":"\/documentation\/ovkit\/ovkoldpricelabel\/initwithframe:","role":"symbol","kind":"symbol","title":"initWithFrame:"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/LabeledView":{"title":"LabeledView","url":"\/documentation\/ovkit\/labeledview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LabeledView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabeledView"}],"navigatorTitle":[{"text":"LabeledView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол представления, содержащего текст."}]},"doc://onevideo.OVKit/objc(pl)NSCoding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIContentSizeCategoryAdjusting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIContentSizeCategoryAdjusting","title":"UIKit.UIContentSizeCategoryAdjusting","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIUtilities.UICoordinateSpace","type":"unresolvable"},"doc://onevideo.OVKit/s16SendableMetatypeP":{"identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/ovk_text":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovk_text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_text","abstract":[],"url":"\/documentation\/ovkit\/oldpricelabel\/ovk_text","role":"symbol","kind":"symbol","title":"ovk_text"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/OVKOldPriceLabel/initWithCoder:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithCoder:","abstract":[],"url":"\/documentation\/ovkit\/ovkoldpricelabel\/initwithcoder:","role":"symbol","kind":"symbol","title":"initWithCoder:"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILetterformAwareAdjusting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILetterformAwareAdjusting","title":"UIKit.UILetterformAwareAdjusting","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OldPriceLabel"}],"url":"\/documentation\/ovkit\/oldpricelabel","type":"topic","title":"OldPriceLabel","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OldPriceLabel"}]},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/ovk_textLabel":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_textLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovk_textLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"title":"ovk_textLabel","url":"\/documentation\/ovkit\/oldpricelabel\/ovk_textlabel","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/attributes(for:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> [","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey","text":"Key"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"kind":"symbol","role":"symbol","title":"attributes(for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/attributes(for:)","url":"\/documentation\/ovkit\/oldpricelabel\/attributes(for:)","abstract":[{"text":"Шаблонный метод, конструирующий атрибуты для строки ","type":"text"},{"type":"codeVoice","code":"text"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/Label":{"title":"Label","url":"\/documentation\/ovkit\/label","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"navigatorTitle":[{"text":"Label","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Текстовый визуальный компонент на основе "},{"type":"codeVoice","code":"UIKit\/UILabel"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKOldPriceLabel"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKOldPriceLabel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKOldPriceLabel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithCoder:","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithFrame:"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKOldPriceLabel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"OVKLabel","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLabel","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Label"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","value":"OVKOldPriceLabel"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","value":[{"kind":"identifier","text":"OVKOldPriceLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle","value":[{"kind":"identifier","text":"OVKOldPriceLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/title","value":"OVKLabel"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/fragments","value":[{"kind":"identifier","text":"OVKLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Label\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLabel"}]}]}]}