{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler\/didUpdate(insets:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)OVInsetsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVInsetsHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVInsetsHandler"}],"title":"OVInsetsHandler","roleHeading":"Protocol","role":"symbol"},"abstract":[{"text":"Протокол наблюдателя за инсетами.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVInsetsHandler"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovinsetshandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovinsetshandler"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"],"title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVInsetsHandler":{"url":"\/documentation\/ovkit\/ovinsetshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler","navigatorTitle":[{"text":"OVInsetsHandler","kind":"identifier"}],"abstract":[{"text":"Протокол наблюдателя за инсетами.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVInsetsHandler","kind":"identifier"}],"title":"OVInsetsHandler","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVInsetsHandler/didUpdate(insets:)":{"url":"\/documentation\/ovkit\/ovinsetshandler\/didupdate(insets:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler\/didUpdate(insets:)","navigatorTitle":[{"kind":"identifier","text":"didUpdateWithInsets:"}],"abstract":[{"type":"text","text":"Изменилось значение инсетов."}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdate"},{"text":"(","kind":"text"},{"text":"insets","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"text":")","kind":"text"}],"title":"didUpdate(insets:)","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"type":"topic","title":"PiPWindow","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PiPWindow"}],"abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVInsetsHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVInsetsHandler","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVInsetsHandler","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler\/didUpdate(insets:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVInsetsHandler","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/title","value":"OVInsetsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/fragments","value":[{"text":"OVInsetsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler\/navigatorTitle","value":[{"text":"OVInsetsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler~1didUpdate(insets:)\/title","value":"didUpdateWithInsets:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVInsetsHandler~1didUpdate(insets:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didUpdateWithInsets:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"text":"OVKPiPWindow","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","value":[{"text":"OVKPiPWindow","kind":"identifier"}]}]}]}