{"metadata":{"symbolKind":"class","modules":[{"name":"OVKit"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKeyboardObserver"}],"externalID":"c:@M@OVKit@objc(cs)OVKeyboardObserver","role":"symbol","title":"OVKeyboardObserver","navigatorTitle":[{"text":"OVKeyboardObserver","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkeyboardobserver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkeyboardobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKeyboardObserver","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKeyboardObserver"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKeyboardObserver\/currentInsets"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/OVKeyboardObserver":{"url":"\/documentation\/ovkit\/ovkeyboardobserver","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKeyboardObserver","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKeyboardObserver"}],"navigatorTitle":[{"kind":"identifier","text":"OVKeyboardObserver"}],"title":"OVKeyboardObserver","kind":"symbol","abstract":[],"type":"topic"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/OVKeyboardObserver/currentInsets":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKeyboardObserver\/currentInsets","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"title":"currentInsets","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/ovkeyboardobserver\/currentinsets"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKeyboardObserver","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKeyboardObserver"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OVKeyboardObserver","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKeyboardObserver"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKeyboardObserver","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKeyboardObserver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKeyboardObserver"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKeyboardObserver\/fragments"},{"op":"replace","value":[{"text":"OVKeyboardObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKeyboardObserver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}