{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerviewhost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkplayerviewhost"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost\/hostDelegate"],"generated":true}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHost","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHost","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHost","kind":"identifier"}],"navigatorTitle":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"protocol","title":"OVKPlayerViewHost"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHost":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHost"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewHost"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/ovkplayerviewhost","kind":"symbol","title":"OVKPlayerViewHost"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHost/hostDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate","text":"OVKPlayerViewHostDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/ovkplayerviewhost\/hostdelegate","abstract":[],"title":"hostDelegate","navigatorTitle":[{"kind":"identifier","text":"hostDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost\/hostDelegate","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKPlayerViewHost","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost\/hostDelegate"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHost"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/title","value":"OVKPlayerViewHost","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/fragments","value":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/navigatorTitle","value":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost~1hostDelegate\/title","value":"hostDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost~1hostDelegate\/fragments","value":[{"text":"hostDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}