{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate","title":"OVKPlayerViewHostDelegate","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}]}]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidAppear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidDisappear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillAppear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDeinit()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDisappear()"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostDidAppear()":{"title":"playerViewHostDidAppear()","abstract":[],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdidappear()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostDidAppear"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidAppear()","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewHostDidAppear"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostWillDisappear()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostWillDisappear"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"playerViewHostWillDisappear"}],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwilldisappear()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDisappear()","type":"topic","title":"playerViewHostWillDisappear()","role":"symbol","abstract":[],"kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostDidDisappear()":{"abstract":[],"navigatorTitle":[{"text":"playerViewHostDidDisappear","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidDisappear()","type":"topic","kind":"symbol","title":"playerViewHostDidDisappear()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostDidDisappear","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdiddisappear()"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostWillAppear()":{"type":"topic","title":"playerViewHostWillAppear()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillAppear()","required":true,"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerViewHostWillAppear","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"playerViewHostWillAppear","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwillappear()"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostWillDeinit()":{"abstract":[],"title":"playerViewHostWillDeinit()","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwilldeinit()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostWillDeinit"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDeinit()","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewHostWillDeinit"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"type":"topic","title":"OVKPlayerViewHostDelegate","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKPlayerViewHostDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidAppear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidDisappear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillAppear()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDeinit()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDisappear()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidAppear()\/title","value":"playerViewHostDidAppear","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidAppear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostDidAppear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDisappear()\/title","value":"playerViewHostWillDisappear","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDisappear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostWillDisappear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidDisappear()\/title","value":"playerViewHostDidDisappear","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidDisappear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostDidDisappear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillAppear()\/title","value":"playerViewHostWillAppear","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillAppear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostWillAppear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDeinit()\/title","value":"playerViewHostWillDeinit","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDeinit()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostWillDeinit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title","value":"OVKPlayerViewHostDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"op":"replace"}]}]}