{"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/persistencemanagerconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagerconfig"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:allowedNetworkType:)"],"title":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot"],"title":"Instance Properties"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerConfig","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig","title":"PersistenceManagerConfig"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKPersistenceManagerConfig) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerConfig","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","type":"topic","title":"PersistenceManager","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManager"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"url":"\/documentation\/ovkit\/persistencemanagerconfig","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}],"title":"PersistenceManagerConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManagerConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/allowedNetworkType":{"role":"symbol","url":"\/documentation\/ovkit\/persistencemanagerconfig\/allowednetworktype","type":"topic","abstract":[{"text":"Набор типов сети, в которых разрешено скачивание видео.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowedNetworkType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","title":"allowedNetworkType","navigatorTitle":[{"text":"allowedNetworkType","kind":"identifier"}]},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/init(libraryRoot:)":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:)","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryRoot"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:)","title":"init(libraryRoot:)","navigatorTitle":[{"kind":"identifier","text":"initWithLibraryRoot:"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/libraryRoot":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/persistencemanagerconfig\/libraryroot","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"libraryRoot"}],"title":"libraryRoot","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraryRoot"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot","abstract":[{"text":"Корневая директория, в которой располагаются файлы, необходимые для работы ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig/init(libraryRoot:allowedNetworkType:)":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/persistencemanagerconfig\/init(libraryroot:allowednetworktype:)","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryRoot"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowedNetworkType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:allowedNetworkType:)","title":"init(libraryRoot:allowedNetworkType:)","navigatorTitle":[{"text":"initWithLibraryRoot:allowedNetworkType:","kind":"identifier"}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"OVKPersistenceManagerConfig"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}]},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerConfig"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/allowedNetworkType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/libraryRoot"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig\/init(libraryRoot:allowedNetworkType:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKPersistenceManagerConfig"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKPersistenceManagerConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title"},{"value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/title","value":"allowedNetworkType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1allowedNetworkType\/fragments","op":"replace","value":[{"text":"allowedNetworkType","kind":"identifier"}]},{"value":"initWithLibraryRoot:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLibraryRoot:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:)\/fragments"},{"op":"replace","value":"libraryRoot","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/title"},{"op":"replace","value":[{"kind":"identifier","text":"libraryRoot"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1libraryRoot\/fragments"},{"op":"replace","value":"initWithLibraryRoot:allowedNetworkType:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:allowedNetworkType:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig~1init(libraryRoot:allowedNetworkType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLibraryRoot:allowedNetworkType:","kind":"identifier"}],"op":"replace"}]}]}