{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Состояние "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference","isActive":true},{"type":"text","text":" применительно к оффлайн проигрыванию."}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"PersistentItemState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKPersistentItemState) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistentitemstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistentitemstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloadState","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/progress"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/isEqual(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/created()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloading(progress:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error(_:progress:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/finished()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/pending()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/suspended(progress:)"],"anchor":"Type-Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/finished()":{"url":"\/documentation\/ovkit\/persistentitemstate\/finished()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/finished()","type":"topic","title":"finished()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"finished"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finished"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/suspended(progress:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/suspended(progress:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suspended","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/persistentitemstate\/suspended(progress:)","abstract":[],"type":"topic","navigatorTitle":[{"text":"suspendedWithProgress:","kind":"identifier"}],"role":"symbol","title":"suspended(progress:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/error":{"url":"\/documentation\/ovkit\/persistentitemstate\/error","title":"error","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error","kind":"symbol","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"error","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/error(_:progress:)":{"kind":"symbol","title":"error(_:progress:)","url":"\/documentation\/ovkit\/persistentitemstate\/error(_:progress:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"error:progress:"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error(_:progress:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/isEqual(_:)","url":"\/documentation\/ovkit\/persistentitemstate\/isequal(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/progress":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/progress","type":"topic","abstract":[],"role":"symbol","title":"progress","url":"\/documentation\/ovkit\/persistentitemstate\/progress","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"progress","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/downloading(progress:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloading","kind":"identifier"},{"text":"(","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/persistentitemstate\/downloading(progress:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloading(progress:)","abstract":[],"navigatorTitle":[{"text":"downloadingWithProgress:","kind":"identifier"}],"kind":"symbol","title":"downloading(progress:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"role":"symbol","navigatorTitle":[{"text":"PersistentItemState","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItemState","kind":"identifier"}],"title":"PersistentItemState","kind":"symbol","abstract":[{"type":"text","text":"Состояние "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference","isActive":true},{"type":"text","text":" применительно к оффлайн проигрыванию."}],"url":"\/documentation\/ovkit\/persistentitemstate","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/created()":{"title":"created()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/created()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"created"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitemstate\/created()"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/pending()":{"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/persistentitemstate\/pending()","navigatorTitle":[{"text":"pending","kind":"identifier"}],"kind":"symbol","title":"pending()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/pending()"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"title":"PersistentItem","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/persistentitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/downloadState":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/persistentitemstate\/downloadstate","navigatorTitle":[{"text":"downloadState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloadState","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","text":"DownloadState","kind":"typeIdentifier"}],"abstract":[],"title":"downloadState","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKPersistentItemState","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItemState"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItemState"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloadState","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/progress"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/created()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloading(progress:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error(_:progress:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/finished()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/pending()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/suspended(progress:)"],"anchor":"Type-Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPersistentItemState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"finished","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1finished()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"finished"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1finished()\/fragments"},{"op":"replace","value":"suspendedWithProgress:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1suspended(progress:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"suspendedWithProgress:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1suspended(progress:)\/fragments"},{"op":"replace","value":"error","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error\/title"},{"op":"replace","value":[{"text":"error","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error\/fragments"},{"op":"replace","value":"error:progress:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error(_:progress:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:progress:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error(_:progress:)\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1isEqual(_:)\/fragments"},{"op":"replace","value":"progress","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1progress\/title"},{"op":"replace","value":[{"text":"progress","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1progress\/fragments"},{"op":"replace","value":"downloadingWithProgress:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloading(progress:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"downloadingWithProgress:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloading(progress:)\/fragments"},{"op":"replace","value":"OVKPersistentItemState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title"},{"op":"replace","value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments"},{"op":"replace","value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle"},{"op":"replace","value":"created","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1created()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"created"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1created()\/fragments"},{"op":"replace","value":"pending","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1pending()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pending"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1pending()\/fragments"},{"op":"replace","value":"OVKPersistentItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"op":"replace","value":"downloadState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloadState\/title"},{"op":"replace","value":[{"text":"downloadState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloadState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}