{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"PersistentMediaSelectionOption"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption","symbolKind":"class","modules":[{"name":"OVKit"}],"role":"symbol","title":"PersistentMediaSelectionOption","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SE","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistentmediaselectionoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentmediaselectionoption"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/init(from:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/codecs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/displayName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/isOriginal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/language","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/optionId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/trackType"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPersistentMediaSelectionOption) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/displayName":{"title":"displayName","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/persistentmediaselectionoption\/displayname","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/displayName","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"displayName","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/init(from:)":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","title":"init(from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/init(from:)","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/optionId":{"title":"optionId","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/optionid","abstract":[],"navigatorTitle":[{"text":"optionId","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/optionId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/language":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"language","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/language","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"language","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/language","title":"language","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/trackType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/trackType","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/tracktype","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"title":"trackType","navigatorTitle":[{"text":"trackType","kind":"identifier"}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption","url":"\/documentation\/ovkit\/persistentmediaselectionoption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentMediaSelectionOption"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PersistentMediaSelectionOption"}],"title":"PersistentMediaSelectionOption","role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/onevideo.OVKit\/SE"},"doc://onevideo.OVKit/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/onevideo.OVKit\/Se"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/isOriginal":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/isOriginal","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/isoriginal","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOriginal","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[],"title":"isOriginal","navigatorTitle":[{"text":"isOriginal","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/codecs":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/codecs","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/codecs","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codecs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","abstract":[],"title":"codecs","navigatorTitle":[{"text":"codecs","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKPersistentMediaSelectionOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/codecs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/displayName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/isOriginal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/language","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/optionId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/trackType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1displayName\/title","value":"displayName"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1displayName\/fragments","value":[{"text":"displayName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1optionId\/title","value":"optionId"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1optionId\/fragments","value":[{"text":"optionId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1language\/title","value":"language"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1language\/fragments","value":[{"text":"language","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1trackType\/title","value":"trackType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1trackType\/fragments","value":[{"text":"trackType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/title","value":"OVKPersistentMediaSelectionOption"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/fragments","value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/navigatorTitle","op":"replace","value":[{"text":"OVKPersistentMediaSelectionOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1isOriginal\/title","op":"replace","value":"isOriginal"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1isOriginal\/fragments","op":"replace","value":[{"kind":"identifier","text":"isOriginal"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1codecs\/title","op":"replace","value":"codecs"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1codecs\/fragments","op":"replace","value":[{"text":"codecs","kind":"identifier"}]}]}]}