{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"OVKit"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerError"}],"title":"PersistenceManagerError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerError"}],"externalID":"c:@M@OVKit@E@OVKPersistenceManagerError"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Ошибка сервиса для оффлайн хранения видеозаписей."}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/corruptLibrary","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/diskWrite","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/interrupted","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/invalidResource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notEnoughDiskSpace","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/unknown"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Error-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Hashable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/LocalizedError-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagererror"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/10Foundation14LocalizedErrorP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/s5ErrorP","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKPersistenceManagerError) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerError"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/ovkit\/persistencemanagererror\/init(rawvalue:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/Hashable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Hashable-Implementations","title":"Hashable Implementations","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/hashable-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/interrupted":{"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanagererror\/interrupted","abstract":[{"type":"text","text":"Загрузка была прервана перезапуском приложения"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/interrupted","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}],"title":"PersistenceManagerError.interrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/diskWrite":{"title":"PersistenceManagerError.diskWrite","url":"\/documentation\/ovkit\/persistencemanagererror\/diskwrite","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/diskWrite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskWrite"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorDiskWrite"}],"kind":"symbol","abstract":[{"type":"text","text":"Ошибка при сохранении библиотеки на диск"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/Error-Implementations":{"kind":"article","url":"\/documentation\/ovkit\/persistencemanagererror\/error-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Error-Implementations","title":"Error Implementations"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/LocalizedError-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/LocalizedError-Implementations","title":"LocalizedError Implementations","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/localizederror-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerError"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerError"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","abstract":[{"type":"text","text":"Ошибка сервиса для оффлайн хранения видеозаписей."}],"url":"\/documentation\/ovkit\/persistencemanagererror","role":"symbol","kind":"symbol","title":"PersistenceManagerError"},"doc://onevideo.OVKit/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://onevideo.OVKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","title":"Swift.Copyable"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/corruptLibrary":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/corruptLibrary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"corruptLibrary"}],"title":"PersistenceManagerError.corruptLibrary","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/corruptlibrary","kind":"symbol","abstract":[{"type":"text","text":"Библиотека повреждена или неудачно завершилась миграция"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorCorruptLibrary"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s5ErrorP"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/RawRepresentable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/rawrepresentable-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/unknown":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorUnknown"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/unknown","abstract":[{"text":"Неизвестная ошибка","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagererror\/unknown","role":"symbol","kind":"symbol","title":"PersistenceManagerError.unknown"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/notEnoughDiskSpace":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notEnoughDiskSpace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notEnoughDiskSpace"}],"title":"PersistenceManagerError.notEnoughDiskSpace","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/notenoughdiskspace","kind":"symbol","abstract":[{"type":"text","text":"Недостаточно памяти для загрузки видео"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorNotEnoughDiskSpace"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/invalidResource":{"title":"PersistenceManagerError.invalidResource","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidResource"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/invalidResource","abstract":[{"type":"text","text":"Не удается загрузить ресурс, либо он поврежден"}],"url":"\/documentation\/ovkit\/persistencemanagererror\/invalidresource","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/equatable-implementations","kind":"article","abstract":[],"role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"OVKPersistenceManagerError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/corruptLibrary","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/diskWrite","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/interrupted","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/invalidResource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notEnoughDiskSpace","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/unknown"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPersistenceManagerError"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1interrupted\/title","value":"OVKPersistenceManagerErrorInterrupted","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1interrupted\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1diskWrite\/title","value":"OVKPersistenceManagerErrorDiskWrite","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1diskWrite\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorDiskWrite"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","value":"OVKPersistenceManagerError","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1corruptLibrary\/title","value":"OVKPersistenceManagerErrorCorruptLibrary","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1corruptLibrary\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorCorruptLibrary"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1unknown\/title","value":"OVKPersistenceManagerErrorUnknown","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1unknown\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorUnknown"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notEnoughDiskSpace\/title","value":"OVKPersistenceManagerErrorNotEnoughDiskSpace","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notEnoughDiskSpace\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorNotEnoughDiskSpace"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1invalidResource\/title","value":"OVKPersistenceManagerErrorInvalidResource","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1invalidResource\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}