{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKPersistenceManagerListener) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManagerListener"}]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:added:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:didFailWithError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:removed:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:updatedStatusOf:)"],"title":"Instance Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagerlistener"]},{"paths":["\/documentation\/ovkit\/persistencemanagerlistener"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"protocol","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManagerListener","kind":"identifier"}],"title":"PersistenceManagerListener","externalID":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerListener","kind":"identifier"}],"roleHeading":"Protocol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","interfaceLanguage":"swift"},"abstract":[{"text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:updatedStatusOf:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"updatedStatusOf"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"persistenceManager:updatedStatusOf:"}],"url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:updatedstatusof:)","required":true,"kind":"symbol","title":"persistenceManager(_:updatedStatusOf:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:updatedStatusOf:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener":{"kind":"symbol","abstract":[{"text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео.","type":"text"}],"title":"PersistenceManagerListener","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManagerListener"}],"navigatorTitle":[{"text":"PersistenceManagerListener","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagerlistener"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:added:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"persistenceManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager"},{"text":", ","kind":"text"},{"text":"added","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"persistenceManager:added:","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:added:)","required":true,"kind":"symbol","type":"topic","title":"persistenceManager(_:added:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:added:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:removed:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"persistenceManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager","text":"PersistenceManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"removed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"persistenceManager:removed:"}],"url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:removed:)","required":true,"kind":"symbol","title":"persistenceManager(_:removed:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:removed:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener/persistenceManager(_:didFailWithError:)":{"role":"symbol","kind":"symbol","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"persistenceManager"},{"text":"(","kind":"text"},{"text":"PersistenceManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManager"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:didFailWithError:)","title":"persistenceManager(_:didFailWithError:)","url":"\/documentation\/ovkit\/persistencemanagerlistener\/persistencemanager(_:didfailwitherror:)","abstract":[],"navigatorTitle":[{"text":"persistenceManager:didFailWithError:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"OVKPersistenceManagerListener","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:added:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:didFailWithError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:removed:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener\/persistenceManager(_:updatedStatusOf:)"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPersistenceManagerListener","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:updatedStatusOf:)\/title","op":"replace","value":"persistenceManager:updatedStatusOf:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:updatedStatusOf:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"persistenceManager:updatedStatusOf:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/title","value":"OVKPersistenceManagerListener"},{"op":"replace","value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:added:)\/title","op":"replace","value":"persistenceManager:added:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:added:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"persistenceManager:added:","kind":"identifier"}]},{"value":"persistenceManager:removed:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:removed:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:removed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"persistenceManager:removed:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:didFailWithError:)\/title","value":"persistenceManager:didFailWithError:"},{"value":[{"text":"- ","kind":"text"},{"text":"persistenceManager:didFailWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener~1persistenceManager(_:didFailWithError:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}