{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"],"title":"Сервисы","generated":true,"anchor":"Сервисы"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager","role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"PersistenceManager"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPersistenceManager) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"Для инициализации необходимо указать URL каталога, в котором будет храниться информация о загруженных видео. Есть возможность использования несколько раздельных библиотек загруженных видео, если приложение поддерживает многопользовательский режим. Для этого необходимо установить параметр "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/userId","isActive":true},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"text":"до момента","type":"text"}]},{"type":"text","text":" инициализации "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Необходимо удерживать ссылку на объект этого класса во время его работы."}],"type":"paragraph"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/init(with:listenerQueue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadSuspendReason","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/isManuallySuspended","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/items"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/addListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateAvailableDiskSpace(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateLibraryDiskSize(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteItem(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteVideo(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearAllData()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearUserLibrary()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates(filteredWithBlock:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/hasVideo(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/imageData(of:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/removeListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/resumeDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/retryDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/state(of:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/suspendDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/video(of:forLocalPlayback:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/enableBackgroundNetworkServiceType()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/handleBackgroundSession(identifier:completionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/warmup()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/calculateAvailableDiskSpace(_:)":{"title":"calculateAvailableDiskSpace(_:)","url":"\/documentation\/ovkit\/persistencemanager\/calculateavailablediskspace(_:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Подсчет свободного места на диске, доступного для загрузки видео. Результат указан в байтах."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateAvailableDiskSpace(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateAvailableDiskSpace","kind":"identifier"},{"text":"((","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"calculateAvailableDiskSpace:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"title":"PersistenceManager","type":"topic","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/hasVideo(_:)":{"abstract":[{"type":"text","text":"Содержится ли переданное видео среди загруженных или загружаемых."}],"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/hasvideo(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/hasVideo(_:)","title":"hasVideo(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"hasVideo:"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/clearUserLibrary()":{"navigatorTitle":[{"text":"clearUserLibrary","kind":"identifier"}],"abstract":[{"text":"Удаляет все загруженные видео для текущего пользователя.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearUserLibrary","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearUserLibrary()","kind":"symbol","title":"clearUserLibrary()","type":"topic","url":"\/documentation\/ovkit\/persistencemanager\/clearuserlibrary()","role":"symbol"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/warmup()":{"url":"\/documentation\/ovkit\/persistencemanager\/warmup()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/warmup()","abstract":[{"text":"Прогрев менеджера и актуализация background сессий.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"warmup"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warmup"},{"kind":"text","text":"()"}],"title":"warmup()","role":"symbol","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/isManuallySuspended":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isManuallySuspended"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"isManuallySuspended","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/isManuallySuspended","navigatorTitle":[{"kind":"identifier","text":"isManuallySuspended"}],"url":"\/documentation\/ovkit\/persistencemanager\/ismanuallysuspended","kind":"symbol","abstract":[{"text":"Позволяет вручную приостановить и возобновить процесс загрузки видео.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/init(with:listenerQueue:)":{"url":"\/documentation\/ovkit\/persistencemanager\/init(with:listenerqueue:)","abstract":[{"text":"Создание менеджера.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistenceManagerConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig"},{"text":", ","kind":"text"},{"text":"listenerQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/init(with:listenerQueue:)","type":"topic","title":"init(with:listenerQueue:)","kind":"symbol","navigatorTitle":[{"text":"initWith:listenerQueue:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/state(of:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"stateOf:"}],"url":"\/documentation\/ovkit\/persistencemanager\/state(of:)","title":"state(of:)","abstract":[{"type":"text","text":"Получение статуса загрузки модели "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/state(of:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/getItemsWithStates()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates()","abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"navigatorTitle":[{"kind":"identifier","text":"getItemsWithStates"}],"kind":"symbol","title":"getItemsWithStates()","type":"topic","url":"\/documentation\/ovkit\/persistencemanager\/getitemswithstates()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/cancelOrDeleteItem(_:)":{"url":"\/documentation\/ovkit\/persistencemanager\/cancelordeleteitem(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteItem(_:)","title":"cancelOrDeleteItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelOrDeleteItem"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelOrDeleteItem:"}],"abstract":[{"type":"text","text":"Удаление модели из загруженных."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/resumeDownload(_:)":{"abstract":[{"type":"text","text":"Возобновляет загрузку модели."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/resumeDownload(_:)","url":"\/documentation\/ovkit\/persistencemanager\/resumedownload(_:)","type":"topic","title":"resumeDownload(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeDownload","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"resumeDownload:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/imageData(of:)":{"abstract":[{"text":"Получение изображения для переданного варианта превью.","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanager\/imagedata(of:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistentItemPreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/imageData(of:)","title":"imageData(of:)","kind":"symbol","navigatorTitle":[{"text":"imageDataOf:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/calculateLibraryDiskSize(_:)":{"navigatorTitle":[{"text":"calculateLibraryDiskSize:","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanager\/calculatelibrarydisksize(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateLibraryDiskSize(_:)","title":"calculateLibraryDiskSize(_:)","kind":"symbol","abstract":[{"type":"text","text":"Подсчет места на диске, которое занимают загруженные видео."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculateLibraryDiskSize","kind":"identifier"},{"text":"((","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/removeListener(_:)":{"title":"removeListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PersistenceManagerListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Удаление наблюдателя за изменением статуса списка загруженных видео."}],"url":"\/documentation\/ovkit\/persistencemanager\/removelistener(_:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeListener:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/removeListener(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)":{"title":"downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","url":"\/documentation\/ovkit\/persistencemanager\/downloadvideo(_:inquality:usehls:onlysound:userdata:estimatedsizeondisk:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useHLS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlySound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"estimatedSizeOnDisk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","abstract":[{"type":"text","text":"Загрузка видео с заданным качеством."}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/handleBackgroundSession(identifier:completionHandler:)":{"navigatorTitle":[{"text":"handleBackgroundSessionWithIdentifier:completionHandler:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/handleBackgroundSession(identifier:completionHandler:)","kind":"symbol","abstract":[{"text":"Поддержка событий background сессии для HLS видео.","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanager\/handlebackgroundsession(identifier:completionhandler:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleBackgroundSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"handleBackgroundSession(identifier:completionHandler:)"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/suspendDownload(_:)":{"url":"\/documentation\/ovkit\/persistencemanager\/suspenddownload(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/suspendDownload(_:)","abstract":[{"text":"Приостанавливает загрузку модели.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"suspendDownload:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspendDownload"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":")"}],"title":"suspendDownload(_:)","role":"symbol","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","kind":"symbol","url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/retryDownload(_:)":{"navigatorTitle":[{"kind":"identifier","text":"retryDownload:"}],"abstract":[{"type":"text","text":"Повтор загрузки модели."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/retryDownload(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryDownload"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":")"}],"title":"retryDownload(_:)","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/retrydownload(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/items":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Список моделей, которые в настоящее время загружаются, либо уже загружены."}],"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/items","type":"topic","title":"items","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/items","navigatorTitle":[{"kind":"identifier","text":"items"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/cancelOrDeleteVideo(_:)":{"title":"cancelOrDeleteVideo(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteVideo(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelOrDeleteVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"cancelOrDeleteVideo:","kind":"identifier"}],"abstract":[{"type":"text","text":"Удаление видео из загруженных."}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/persistencemanager\/cancelordeletevideo(_:)"},"doc://onevideo.OVKit/documentation/OVKit/Environment/userId":{"navigatorTitle":[{"text":"userId","kind":"identifier"}],"url":"\/documentation\/ovkit\/environment\/userid","abstract":[{"type":"text","text":"Идентификатор пользователя приложения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/userId","title":"userId","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"title":"PersistentItem","navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","url":"\/documentation\/ovkit\/persistentitem"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","type":"topic","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" при работе плееров.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AudioManager"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"kind":"symbol","url":"\/documentation\/ovkit\/audiomanager","title":"AudioManager"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/clearAllData()":{"url":"\/documentation\/ovkit\/persistencemanager\/clearalldata()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearAllData()","kind":"symbol","abstract":[{"type":"text","text":"Удаляет все загруженные видео всех пользователей."}],"role":"symbol","type":"topic","title":"clearAllData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearAllData"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearAllData"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/addListener(_:)":{"role":"symbol","title":"addListener(_:)","url":"\/documentation\/ovkit\/persistencemanager\/addlistener(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/addListener(_:)","navigatorTitle":[{"text":"addListener:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Добавление наблюдателя за изменением статуса списка загруженных видео.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistenceManagerListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"title":"IdleTimerManager","navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}],"url":"\/documentation\/ovkit\/idletimermanager","role":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/updateAllowedNetworkType(_:)":{"url":"\/documentation\/ovkit\/persistencemanager\/updateallowednetworktype(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAllowedNetworkType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"updateAllowedNetworkType:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Обновление маски типов сети, при которых разрешается загрузка видео."}],"role":"symbol","title":"updateAllowedNetworkType(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/downloadSuspendReason":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadSuspendReason"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason","kind":"typeIdentifier","text":"DownloadSuspendReason"}],"title":"downloadSuspendReason","type":"topic","abstract":[{"text":"Причина, по которой загрузка приостановлена в данное время.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"downloadSuspendReason"}],"url":"\/documentation\/ovkit\/persistencemanager\/downloadsuspendreason","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadSuspendReason"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/enableBackgroundNetworkServiceType()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"},{"text":"()","kind":"text"}],"title":"enableBackgroundNetworkServiceType()","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"enableBackgroundNetworkServiceType","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanager\/enablebackgroundnetworkservicetype()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/enableBackgroundNetworkServiceType()"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/video(of:forLocalPlayback:)":{"title":"video(of:forLocalPlayback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forLocalPlayback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Video","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideo","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"videoOf:forLocalPlayback:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/video(of:forlocalplayback:)","abstract":[{"type":"text","text":"Получение "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},{"type":"text","text":" из модели "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/video(of:forLocalPlayback:)","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/getItemsWithStates(filteredWithBlock:)":{"title":"getItemsWithStates(filteredWithBlock:)","abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates(filteredWithBlock:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filteredWithBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"getItemsWithStatesWithFilteredWithBlock:"}],"url":"\/documentation\/ovkit\/persistencemanager\/getitemswithstates(filteredwithblock:)"},"doc://onevideo.OVKit/documentation/OVKit/Environment":{"url":"\/documentation\/ovkit\/environment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Environment","kind":"identifier"}],"navigatorTitle":[{"text":"Environment","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","abstract":[{"text":"Набор параметров окружения для настройки работы SDK.","type":"text"}],"title":"Environment","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"role":"symbol","url":"\/documentation\/ovkit\/video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"topic","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKPersistenceManager","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadSuspendReason","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/isManuallySuspended","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/items"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/addListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateAvailableDiskSpace(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateLibraryDiskSize(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteItem(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/cancelOrDeleteVideo(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearAllData()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/clearUserLibrary()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates(filteredWithBlock:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/hasVideo(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/imageData(of:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/init(with:listenerQueue:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/removeListener(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/resumeDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/retryDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/state(of:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/suspendDownload(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/video(of:forLocalPlayback:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/enableBackgroundNetworkServiceType()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/handleBackgroundSession(identifier:completionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/warmup()"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"],"title":"Сервисы","anchor":"Сервисы","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPersistenceManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"calculateAvailableDiskSpace:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateAvailableDiskSpace(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateAvailableDiskSpace:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateAvailableDiskSpace(_:)\/fragments"},{"op":"replace","value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"op":"replace","value":"hasVideo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1hasVideo(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasVideo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1hasVideo(_:)\/fragments"},{"op":"replace","value":"clearUserLibrary","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1clearUserLibrary()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clearUserLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1clearUserLibrary()\/fragments"},{"op":"replace","value":"warmup","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1warmup()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"warmup"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1warmup()\/fragments"},{"op":"replace","value":"isManuallySuspended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1isManuallySuspended\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isManuallySuspended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1isManuallySuspended\/fragments"},{"op":"replace","value":"initWith:listenerQueue:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1init(with:listenerQueue:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWith:listenerQueue:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1init(with:listenerQueue:)\/fragments"},{"op":"replace","value":"stateOf:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1state(of:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stateOf:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1state(of:)\/fragments"},{"op":"replace","value":"getItemsWithStates","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getItemsWithStates"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates()\/fragments"},{"op":"replace","value":"cancelOrDeleteItem:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1cancelOrDeleteItem(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelOrDeleteItem:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1cancelOrDeleteItem(_:)\/fragments"},{"op":"replace","value":"resumeDownload:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1resumeDownload(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resumeDownload:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1resumeDownload(_:)\/fragments"},{"op":"replace","value":"imageDataOf:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1imageData(of:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageDataOf:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1imageData(of:)\/fragments"},{"op":"replace","value":"calculateLibraryDiskSize:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateLibraryDiskSize(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calculateLibraryDiskSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateLibraryDiskSize(_:)\/fragments"},{"op":"replace","value":"removeListener:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1removeListener(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1removeListener(_:)\/fragments"},{"op":"replace","value":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)\/fragments"},{"op":"replace","value":"handleBackgroundSessionWithIdentifier:completionHandler:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1handleBackgroundSession(identifier:completionHandler:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleBackgroundSessionWithIdentifier:completionHandler:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1handleBackgroundSession(identifier:completionHandler:)\/fragments"},{"op":"replace","value":"suspendDownload:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1suspendDownload(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"suspendDownload:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1suspendDownload(_:)\/fragments"},{"op":"replace","value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle"},{"op":"replace","value":"retryDownload:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1retryDownload(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"retryDownload:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1retryDownload(_:)\/fragments"},{"op":"replace","value":"items","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1items\/title"},{"op":"replace","value":[{"kind":"identifier","text":"items"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1items\/fragments"},{"op":"replace","value":"cancelOrDeleteVideo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1cancelOrDeleteVideo(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cancelOrDeleteVideo:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1cancelOrDeleteVideo(_:)\/fragments"},{"op":"replace","value":"userId","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1userId\/title"},{"op":"replace","value":[{"text":"userId","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1userId\/fragments"},{"op":"replace","value":"OVKPersistentItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"op":"replace","value":"OVKAudioManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title"},{"op":"replace","value":[{"text":"OVKAudioManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments"},{"op":"replace","value":[{"text":"OVKAudioManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle"},{"op":"replace","value":"clearAllData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1clearAllData()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearAllData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1clearAllData()\/fragments"},{"op":"replace","value":"addListener:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1addListener(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addListener:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1addListener(_:)\/fragments"},{"op":"replace","value":"OVKIdleTimerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIdleTimerManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle"},{"op":"replace","value":"updateAllowedNetworkType:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateAllowedNetworkType:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/fragments"},{"op":"replace","value":"downloadSuspendReason","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadSuspendReason\/title"},{"op":"replace","value":[{"text":"downloadSuspendReason","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadSuspendReason\/fragments"},{"op":"replace","value":"enableBackgroundNetworkServiceType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1enableBackgroundNetworkServiceType()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1enableBackgroundNetworkServiceType()\/fragments"},{"op":"replace","value":"videoOf:forLocalPlayback:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1video(of:forLocalPlayback:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoOf:forLocalPlayback:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1video(of:forLocalPlayback:)\/fragments"},{"op":"replace","value":"getItemsWithStatesWithFilteredWithBlock:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates(filteredWithBlock:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getItemsWithStatesWithFilteredWithBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates(filteredWithBlock:)\/fragments"},{"op":"replace","value":"OVKEnvironment","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments"},{"op":"replace","value":[{"text":"OVKEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle"},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"}]}]}