{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SE","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/estimatedSizeOnDisk","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/identifier","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/previews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/quality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/remoteUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/selectedMediaOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/userData"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/isEqual(_:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"OVKit"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItem","title":"PersistentItem"},"abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKPersistentItem) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistentItem","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/persistentitem"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentitem"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/title":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/title","title":"title","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/ovkit\/persistentitem\/title","type":"topic","navigatorTitle":[{"text":"title","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/Se":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/Se","title":"Swift.Decodable"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/init(from:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/init(from:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/ovkit\/persistentitem\/init(from:)","abstract":[],"title":"init(from:)"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/remoteUrl":{"type":"topic","title":"remoteUrl","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/remoteUrl","url":"\/documentation\/ovkit\/persistentitem\/remoteurl","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"remoteUrl"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"url":"\/documentation\/ovkit\/persistentitem","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","kind":"symbol","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"title":"PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/estimatedSizeOnDisk":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/estimatedSizeOnDisk","title":"estimatedSizeOnDisk","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estimatedSizeOnDisk"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/ovkit\/persistentitem\/estimatedsizeondisk","type":"topic","navigatorTitle":[{"text":"estimatedSizeOnDisk","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"В байтах. ‘0’ значит, что еще неизвестно"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/selectedMediaOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"selectedMediaOptions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption","text":"PersistentMediaSelectionOption"},{"text":"]?","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitem\/selectedmediaoptions","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/selectedMediaOptions","abstract":[{"text":"Какие дорожки выбраны для скачивания. ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает все доступные аудио- и видеодорожки. Неподдерживаемые будут отфильтрованы при скачивании."}],"type":"topic","title":"selectedMediaOptions","navigatorTitle":[{"text":"selectedMediaOptions","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/quality":{"url":"\/documentation\/ovkit\/persistentitem\/quality","type":"topic","title":"quality","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/quality","navigatorTitle":[{"text":"quality","kind":"identifier"}],"abstract":[{"type":"text","text":"Значение из OVVisualQuality"}],"kind":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/userData":{"type":"topic","url":"\/documentation\/ovkit\/persistentitem\/userdata","role":"symbol","navigatorTitle":[{"text":"userData","kind":"identifier"}],"kind":"symbol","title":"userData","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/userData","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userData"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/hash":{"url":"\/documentation\/ovkit\/persistentitem\/hash","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","title":"hash","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/hash","kind":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/isEqual(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/persistentitem\/isequal(_:)","abstract":[],"title":"isEqual(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/previews":{"navigatorTitle":[{"kind":"identifier","text":"previews"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/previews","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"previews"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"PersistentItemPreview"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/persistentitem\/previews","abstract":[],"title":"previews"},"doc://onevideo.OVKit/SE":{"identifier":"doc:\/\/onevideo.OVKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem/identifier":{"url":"\/documentation\/ovkit\/persistentitem\/identifier","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/identifier","kind":"symbol","abstract":[],"title":"identifier"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKPersistentItem"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/estimatedSizeOnDisk","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/identifier","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/previews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/quality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/remoteUrl","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/selectedMediaOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/userData"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKPersistentItem"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1title\/title","value":"title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"value":"remoteUrl","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1remoteUrl\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1remoteUrl\/fragments","value":[{"kind":"identifier","text":"remoteUrl"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"kind":"identifier","text":"OVKPersistentItem"}]},{"op":"replace","value":"estimatedSizeOnDisk","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1estimatedSizeOnDisk\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1estimatedSizeOnDisk\/fragments","op":"replace","value":[{"text":"estimatedSizeOnDisk","kind":"identifier"}]},{"value":"selectedMediaOptions","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1selectedMediaOptions\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1selectedMediaOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"selectedMediaOptions"}]},{"value":"quality","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1quality\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1quality\/fragments","value":[{"text":"quality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1userData\/title","value":"userData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1userData\/fragments","value":[{"text":"userData","kind":"identifier"}]},{"value":"hash","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1hash\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1previews\/title","op":"replace","value":"previews"},{"value":[{"text":"previews","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1previews\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1identifier\/title","op":"replace","value":"identifier"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem~1identifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}