{"abstract":[{"type":"text","text":"Окно внутреннего Picture in Picture."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIWindow"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPiPWindow","role":"symbol","title":"PiPWindow"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPiPWindow) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Ориентацию окна для "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow"},{"type":"text","text":" можно поддержать в методе "},{"code":"AppDelegate","type":"codeVoice"},{"type":"text","text":" "},{"code":"application(_:supportedIntefaceOrientationsFor:)","type":"codeVoice"},{"type":"text","text":"."}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/corner","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdate(insets:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdateCoordinateSpace()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/moveToCorner(_:initialVelocity:animated:completion:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/pipwindow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/pipwindow"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/playerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView","kind":"symbol","title":"playerView","url":"\/documentation\/ovkit\/pipwindow\/playerview","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"}],"navigatorTitle":[{"kind":"identifier","text":"playerView"}],"type":"topic","abstract":[{"type":"text","text":"Плеер, который отвечает за воспроизведение видео в окне."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/pipWindow":{"title":"pipWindow","type":"topic","url":"\/documentation\/ovkit\/playermanager\/pipwindow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pipWindow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier","text":"PiPWindow"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pipWindow"}],"role":"symbol","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/moveToCorner(_:initialVelocity:animated:completion:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToCorner"},{"kind":"text","text":"("},{"preciseIdentifier":"s:5OVKit12StickyCornerO","kind":"typeIdentifier","text":"StickyCorner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialVelocity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Переместить окно.","type":"text"}],"url":"\/documentation\/ovkit\/pipwindow\/movetocorner(_:initialvelocity:animated:completion:)","title":"moveToCorner(_:initialVelocity:animated:completion:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/moveToCorner(_:initialVelocity:animated:completion:)"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/maximizeToFullscreen()":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreen"},{"kind":"text","text":"()"}],"abstract":[{"text":"Развернуть окно в полноэкранный режим.","type":"text"}],"url":"\/documentation\/ovkit\/pipwindow\/maximizetofullscreen()","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreen"}],"title":"maximizeToFullscreen()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen()"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/didUpdate(insets:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"insets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Изменилось значение инсетов."}],"url":"\/documentation\/ovkit\/pipwindow\/didupdate(insets:)","title":"didUpdate(insets:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdate(insets:)"},"doc://onevideo.OVKit/objc(cs)UIWindow":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIWindow","title":"UIWindow"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/OVInsetsHandler":{"abstract":[{"text":"Протокол наблюдателя за инсетами.","type":"text"}],"title":"OVInsetsHandler","navigatorTitle":[{"text":"OVInsetsHandler","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/ovinsetshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVInsetsHandler","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVInsetsHandler","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/pipwindow","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","title":"PiPWindow"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/corner":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Угол, в котором в данный момент находится окно."}],"title":"corner","kind":"symbol","url":"\/documentation\/ovkit\/pipwindow\/corner","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StickyCorner","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12StickyCornerO"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/corner"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/didUpdateCoordinateSpace()":{"url":"\/documentation\/ovkit\/pipwindow\/didupdatecoordinatespace()","type":"topic","abstract":[{"type":"text","text":"Сигнал об изменении размеров экрана или сцены."}],"role":"symbol","title":"didUpdateCoordinateSpace()","kind":"symbol","navigatorTitle":[{"text":"didUpdateCoordinateSpace","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateCoordinateSpace","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdateCoordinateSpace()"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPiPWindow","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdateCoordinateSpace()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIWindow"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPiPWindow"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/title"},{"value":[{"text":"playerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/fragments"},{"value":"pipWindow","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/title"},{"value":[{"kind":"identifier","text":"pipWindow"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/fragments"},{"value":"maximizeToFullscreen","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen()\/fragments"},{"value":"OVKPiPWindow","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"},{"value":"didUpdateCoordinateSpace","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdateCoordinateSpace()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didUpdateCoordinateSpace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdateCoordinateSpace()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}