{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionRouteSharingPolicy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/currentPlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/externalDeviceIsConnected","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/idleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/masterVolume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipIsPlaying","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/playbackActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/routeChangeStrategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/soundActive"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/cleanupAllPlayers()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/closePiP()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/deactivateCommandCenter()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/presentBroadcastMenu(for:onShowRoutePicker:)"]},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/shared"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/objc_savedPlayTime(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/savedPlayTime(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)"]}],"sections":[],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","role":"symbol"},"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"seeAlsoSections":[{"title":"Сервисы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"anchor":"Сервисы","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPlayerManager) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart"]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Имеет следующие функции:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Ставит на паузу плеер при начале игры другого."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Посылает запросы на конфигурацию "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"При необходимости обеспечивает прерывание текущего плеера посредством паузы или отключения звука."}],"type":"paragraph"}]}],"type":"unorderedList"},{"style":"warning","content":[{"inlineContent":[{"type":"text","text":"Для корректной работы OVKit необходимо реализовать "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","name":"Warning"},{"type":"heading","anchor":"%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-AVAudioSession","text":"Настройка AVAudioSession","level":3},{"inlineContent":[{"text":"Для использования плееров в приложении с другими клиентами ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" необходимо как можно раньше установить "},{"code":"AudioManager","type":"codeVoice"},{"text":" вызовом метода ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)","type":"reference","isActive":true},{"text":". Если этого не сделать, ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","type":"reference","isActive":true},{"type":"text","text":" сам предоставит базовую реализацию, которая будет конфигурировать и активировать "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":", но не будет деактивировать её после окончания проигрывания всех плееров."}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager"]},{"paths":["\/documentation\/ovkit\/playermanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Environment":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","url":"\/documentation\/ovkit\/environment","navigatorTitle":[{"text":"Environment","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Набор параметров окружения для настройки работы SDK."}],"type":"topic","title":"Environment"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionRouteSharingPolicy":{"type":"topic","title":"audioSessionRouteSharingPolicy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionRouteSharingPolicy","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionRouteSharingPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"RouteSharingPolicy"}],"abstract":[{"text":"Политика роутинга ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":", которая в данный момент требуется менеджеру.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"audioSessionRouteSharingPolicy"}],"url":"\/documentation\/ovkit\/playermanager\/audiosessionroutesharingpolicy"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"url":"\/documentation\/ovkit\/quickstart","title":"Быстрый старт","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","type":"topic","role":"article","kind":"article","abstract":[{"text":"Руководство для первого подключения ","type":"text"},{"type":"codeVoice","code":"OVKit"},{"text":" к проекту. Эти шаги необходимо выполнить перед началом работы.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/presentBroadcastMenu(for:onShowRoutePicker:)":{"url":"\/documentation\/ovkit\/playermanager\/presentbroadcastmenu(for:onshowroutepicker:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentBroadcastMenu"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onShowRoutePicker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Показать меню выбора устройства для стриминга."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/presentBroadcastMenu(for:onShowRoutePicker:)","kind":"symbol","title":"presentBroadcastMenu(for:onShowRoutePicker:)","role":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/delegate":{"role":"symbol","url":"\/documentation\/ovkit\/playermanager\/delegate","title":"delegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/currentPlayerView":{"title":"currentPlayerView","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/currentPlayerView","type":"topic","url":"\/documentation\/ovkit\/playermanager\/currentplayerview","abstract":[{"text":"Текущий ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", в котором воспроизводится видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentPlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/cleanupAllPlayers()":{"url":"\/documentation\/ovkit\/playermanager\/cleanupallplayers()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/cleanupAllPlayers()","navigatorTitle":[{"text":"cleanupAllPlayers","kind":"identifier"}],"abstract":[{"text":"Останавливает и очищает все плееры, а также закрывает окно Picture in Picture.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanupAllPlayers","kind":"identifier"},{"text":"()","kind":"text"}],"title":"cleanupAllPlayers()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/shared":{"title":"shared","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/shared","type":"topic","url":"\/documentation\/ovkit\/playermanager\/shared","abstract":[{"text":"Ссылка на общий инстанс менеджера.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerManager","text":"PlayerManager"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/soundActive":{"url":"\/documentation\/ovkit\/playermanager\/soundactive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/soundActive","navigatorTitle":[{"kind":"identifier","text":"soundActive"}],"abstract":[{"type":"text","text":"Включен ли звук хотя бы на одном из текущих плееров (неважно, идет воспроизведение или нет)."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"soundActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"soundActive","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"url":"\/documentation\/ovkit\/persistencemanager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredCategory":{"title":"audioSessionPreferredCategory","url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredcategory","navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredCategory"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Категория ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":", которая в данный момент требуется менеджеру.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredCategory"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/routeChangeStrategy":{"url":"\/documentation\/ovkit\/playermanager\/routechangestrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/routeChangeStrategy","navigatorTitle":[{"kind":"identifier","text":"routeChangeStrategy"}],"abstract":[{"text":"Служит для определения поведения плеера при смене output route.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeChangeStrategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RouteChangeStrategy","preciseIdentifier":"c:@M@OVKit@E@RouteChangeStrategy"}],"title":"routeChangeStrategy","role":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/masterVolume":{"navigatorTitle":[{"kind":"identifier","text":"masterVolume"}],"url":"\/documentation\/ovkit\/playermanager\/mastervolume","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/masterVolume","title":"masterVolume","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Общая громкость (всех плееров)."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masterVolume","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","title":"PlayerManager","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredOptions":{"title":"audioSessionPreferredOptions","url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredoptions","navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredOptions"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Опции ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":", которые в данный момент требуются менеджеру.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/pipIsPlaying":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipIsPlaying","type":"topic","kind":"symbol","title":"pipIsPlaying","url":"\/documentation\/ovkit\/playermanager\/pipisplaying","abstract":[{"text":"Происходит ли в данный момент воспроизведение во внутреннем окне Picture in Picture.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pipIsPlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pipIsPlaying"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/setup(with:)":{"url":"\/documentation\/ovkit\/playermanager\/setup(with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)","navigatorTitle":[{"text":"setupWith:","kind":"identifier"}],"abstract":[{"text":"Привязывает контроллер ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" к сервису.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioManager","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKAudioManager"},{"kind":"text","text":")"}],"title":"setup(with:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/objc_savedPlayTime(for:)":{"title":"objc_savedPlayTime(for:)","abstract":[{"text":"Обертка метода ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/savedPlayTime(for:)"},{"text":", совместимая с Objective-C.","type":"text"}],"url":"\/documentation\/ovkit\/playermanager\/objc_savedplaytime(for:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"objc_savedPlayTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/objc_savedPlayTime(for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"objc_savedPlayTimeFor:"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"url":"\/documentation\/ovkit\/audiomanager","navigatorTitle":[{"text":"AudioManager","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioManager","kind":"identifier"}],"abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"text":" при работе плееров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","title":"AudioManager","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/deactivateCommandCenter()":{"title":"deactivateCommandCenter()","abstract":[{"text":"Отключить текущий плеер от системного центра управления.","type":"text"}],"url":"\/documentation\/ovkit\/playermanager\/deactivatecommandcenter()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deactivateCommandCenter","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/deactivateCommandCenter()","role":"symbol","navigatorTitle":[{"text":"deactivateCommandCenter","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/externalDeviceIsConnected":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalDeviceIsConnected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"externalDeviceIsConnected","url":"\/documentation\/ovkit\/playermanager\/externaldeviceisconnected","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/externalDeviceIsConnected","type":"topic","role":"symbol","navigatorTitle":[{"text":"externalDeviceIsConnected","kind":"identifier"}],"abstract":[{"text":"Подключено ли в данный момент устройство для стриминга видео на него.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/closePiP()":{"role":"symbol","url":"\/documentation\/ovkit\/playermanager\/closepip()","title":"closePiP()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/closePiP()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"closePiP"}],"type":"topic","abstract":[{"text":"Закрывает внутреннее окно Picture in Picture.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closePiP"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredMode":{"title":"audioSessionPreferredMode","url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredmode","navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredMode"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Режим "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":", который в данный момент требуется менеджеру."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"navigatorTitle":[{"kind":"identifier","text":"IdleTimerManager"}],"url":"\/documentation\/ovkit\/idletimermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","type":"topic","title":"IdleTimerManager","role":"symbol","kind":"symbol","abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdleTimerManager"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/pipWindow":{"navigatorTitle":[{"kind":"identifier","text":"pipWindow"}],"url":"\/documentation\/ovkit\/playermanager\/pipwindow","title":"pipWindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","type":"topic","role":"symbol","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipWindow"},{"text":": ","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/playbackActive":{"url":"\/documentation\/ovkit\/playermanager\/playbackactive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/playbackActive","navigatorTitle":[{"text":"playbackActive","kind":"identifier"}],"abstract":[{"text":"Идет ли в данный момент воспроизведение видео хотя бы одним из плееров, либо хотя бы один плеер собирается воспроизводить видео.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playbackActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"playbackActive","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerManager/init":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/init","type":"topic","kind":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkplayermanager\/init"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/savedPlayTime(for:)":{"type":"topic","title":"savedPlayTime(for:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/savedPlayTime(for:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savedPlayTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Сохраненное время воспроизведения для данного видео."}],"url":"\/documentation\/ovkit\/playermanager\/savedplaytime(for:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/idleTimerManager":{"navigatorTitle":[{"text":"idleTimerManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager\/idletimermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/idleTimerManager","type":"topic","title":"idleTimerManager","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Служит для запрета автоблокировки устройства во время проигрывания видео."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idleTimerManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IdleTimerManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIdleTimerManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"OVKPlayerManager","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionRouteSharingPolicy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/currentPlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/externalDeviceIsConnected","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/idleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/masterVolume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipIsPlaying","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/playbackActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/routeChangeStrategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/soundActive"],"generated":true,"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerManager\/init","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/cleanupAllPlayers()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/closePiP()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/deactivateCommandCenter()"]},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/shared"],"anchor":"Type-Properties","title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/objc_savedPlayTime(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)"],"anchor":"Type-Methods","title":"Type Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Сервисы","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"],"anchor":"Сервисы"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/title","value":"OVKEnvironment"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/fragments","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment\/navigatorTitle","value":[{"text":"OVKEnvironment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionRouteSharingPolicy\/title","value":"audioSessionRouteSharingPolicy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionRouteSharingPolicy\/fragments","value":[{"text":"audioSessionRouteSharingPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1currentPlayerView\/title","value":"currentPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1currentPlayerView\/fragments","value":[{"text":"currentPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1cleanupAllPlayers()\/title","value":"cleanupAllPlayers"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1cleanupAllPlayers()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cleanupAllPlayers"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"soundActive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1soundActive\/title","op":"replace"},{"value":[{"text":"soundActive","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1soundActive\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace"},{"value":"audioSessionPreferredCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredCategory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"audioSessionPreferredCategory"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredCategory\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1routeChangeStrategy\/title","value":"routeChangeStrategy"},{"value":[{"kind":"identifier","text":"routeChangeStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1routeChangeStrategy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1masterVolume\/title","value":"masterVolume"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1masterVolume\/fragments","value":[{"text":"masterVolume","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","op":"replace"},{"value":"audioSessionPreferredOptions","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"audioSessionPreferredOptions"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipIsPlaying\/title","value":"pipIsPlaying"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipIsPlaying\/fragments","value":[{"text":"pipIsPlaying","kind":"identifier"}]},{"value":"setupWith:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1setup(with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1setup(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setupWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1objc_savedPlayTime(for:)\/title","value":"objc_savedPlayTimeFor:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"objc_savedPlayTimeFor:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1objc_savedPlayTime(for:)\/fragments","op":"replace"},{"value":"OVKAudioManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","op":"replace"},{"value":[{"text":"OVKAudioManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAudioManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","op":"replace"},{"value":"deactivateCommandCenter","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1deactivateCommandCenter()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deactivateCommandCenter"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1deactivateCommandCenter()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1externalDeviceIsConnected\/title","value":"externalDeviceIsConnected","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1externalDeviceIsConnected\/fragments","value":[{"text":"externalDeviceIsConnected","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1closePiP()\/title","value":"closePiP","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1closePiP()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"closePiP","kind":"identifier"}],"op":"replace"},{"value":"audioSessionPreferredMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/title","op":"replace"},{"value":[{"text":"audioSessionPreferredMode","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/fragments","op":"replace"},{"value":"OVKIdleTimerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title","op":"replace"},{"value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments","op":"replace"},{"value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle","op":"replace"},{"value":"pipWindow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/title","op":"replace"},{"value":[{"kind":"identifier","text":"pipWindow"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/fragments","op":"replace"},{"value":"playbackActive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1playbackActive\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1playbackActive\/fragments","value":[{"text":"playbackActive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1idleTimerManager\/title","value":"idleTimerManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1idleTimerManager\/fragments","value":[{"text":"idleTimerManager","kind":"identifier"}],"op":"replace"}]}]}