{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/customSafeInsets","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/splitMode"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekBackwards()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekForward()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekToStart()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/togglePause()"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"],"type":"inheritsFrom","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol"},"variants":[{"paths":["\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"metadata":{"roleHeading":"Protocol","externalID":"s:5OVKit36PlayerFullscreenControlsViewProtocolP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"symbolKind":"protocol","navigatorTitle":[{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"title":"PlayerFullscreenControlsViewProtocol","modules":[{"name":"OVKit"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Протокол для контролов, которые могут использоваться в полноэкранном режиме проигрывания."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/customSafeInsets":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/customsafeinsets","title":"customSafeInsets","abstract":[{"type":"text","text":"Cтатичные инсеты, которые, которые должны учитывать основные контролы."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customSafeInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/customSafeInsets"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol","title":"PlayerFullscreenControlsViewProtocol","abstract":[{"type":"text","text":"Протокол для контролов, которые могут использоваться в полноэкранном режиме проигрывания."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol","role":"symbol","kind":"symbol","title":"PlayerControlsViewProtocol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/splitMode":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/splitMode","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/splitmode","abstract":[{"text":"Режим контролов, когда они показываются одновременно с ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"text":".","type":"text"}],"title":"splitMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"splitMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HideableControls"}],"title":"HideableControls","navigatorTitle":[{"kind":"identifier","text":"HideableControls"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","url":"\/documentation\/ovkit\/hideablecontrols","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/togglePause()":{"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/togglepause()","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Команда переключения состояния паузы.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"togglePause"},{"kind":"text","text":"()"}],"required":true,"title":"togglePause()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/togglePause()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/fastSeekForward()":{"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/fastseekforward()","title":"fastSeekForward()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fastSeekForward"},{"kind":"text","text":"()"}],"role":"symbol","required":true,"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekForward()","abstract":[{"type":"text","text":"Команда быстрой перемотки вперед."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/keyboardOverlapHeightChanged(to:)":{"type":"topic","abstract":[{"type":"text","text":"Изменилась высота клавиатуры над полноэкранным контроллером."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardOverlapHeightChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/keyboardoverlapheightchanged(to:)","required":true,"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/keyboardOverlapHeightChanged(to:)","title":"keyboardOverlapHeightChanged(to:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/fastSeekBackwards()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekBackwards()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fastSeekBackwards","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/fastseekbackwards()","title":"fastSeekBackwards()","abstract":[{"text":"Команда быстрой перемотки назад.","type":"text"}],"type":"topic","kind":"symbol","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol/fastSeekToStart()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fastSeekToStart","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Команда быстрой перемотки в начало."}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol\/fastseektostart()","type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol\/fastSeekToStart()","title":"fastSeekToStart()"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"title":"FullscreenSupplementaryController","navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}