{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKPlayerMediaSelectionDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:didSelect:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:optionSelectionChanged:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerDidLoadMediaSelection(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerPreferredSubtitlesOption(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerSubtitlesPrepared(_:)"],"generated":true,"title":"Instance Methods"}],"metadata":{"role":"symbol","title":"PlayerMediaSelectionDelegate","externalID":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/player(_:didSelect:userInitiated:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Уведомление о том, что была выбрана медиа дорожка."}],"type":"topic","url":"\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:didselect:userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"player:didSelect:userInitiated:"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:didSelect:userInitiated:)","title":"player(_:didSelect:userInitiated:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/playerSubtitlesPrepared(_:)":{"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/playersubtitlesprepared(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerSubtitlesPrepared(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerSubtitlesPrepared","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"playerSubtitlesPrepared(_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"playerSubtitlesPrepared:","kind":"identifier"}],"abstract":[{"text":"Дорожки субтитров подготовлены.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/playerDidLoadMediaSelection(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerDidLoadMediaSelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerDidLoadMediaSelection(_:)","title":"playerDidLoadMediaSelection(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"playerDidLoadMediaSelection:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Загружен набор аудио\/видео дорожек.","type":"text"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/playerdidloadmediaselection(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/player(_:optionSelectionChanged:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionSelectionChanged"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:optionSelectionChanged:)","title":"player(_:optionSelectionChanged:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:optionSelectionChanged:"}],"role":"symbol","abstract":[{"text":"Уведомление о том, что текущая дорожка субтитров была изменена или выключена.","type":"text"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:optionselectionchanged:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/playerPreferredSubtitlesOption(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerPreferredSubtitlesOption","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":") -> ","kind":"text"},{"text":"SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerPreferredSubtitlesOption(_:)","title":"playerPreferredSubtitlesOption(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"playerPreferredSubtitlesOption:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Предпочитаемая опция субтитров.","type":"text"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/playerpreferredsubtitlesoption(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"abstract":[{"text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","title":"PlayerMediaSelectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPlayerMediaSelectionDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:didSelect:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:optionSelectionChanged:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerDidLoadMediaSelection(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerPreferredSubtitlesOption(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerSubtitlesPrepared(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerMediaSelectionDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:didSelect:userInitiated:)\/title","value":"player:didSelect:userInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:didSelect:userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:didSelect:userInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerSubtitlesPrepared(_:)\/title","value":"playerSubtitlesPrepared:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerSubtitlesPrepared(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerSubtitlesPrepared:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerDidLoadMediaSelection(_:)\/title","value":"playerDidLoadMediaSelection:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerDidLoadMediaSelection(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidLoadMediaSelection:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:optionSelectionChanged:)\/title","value":"player:optionSelectionChanged:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:optionSelectionChanged:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"player:optionSelectionChanged:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerPreferredSubtitlesOption(_:)\/title","value":"playerPreferredSubtitlesOption:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerPreferredSubtitlesOption(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerPreferredSubtitlesOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title","value":"OVKPlayerMediaSelectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments","value":[{"text":"OVKPlayerMediaSelectionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}