{"kind":"symbol","metadata":{"symbolKind":"protocol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"PlayerEventListener"}],"role":"symbol","title":"PlayerEventListener","externalID":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerEventListener"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate"],"type":"inheritedBy"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKPlayerEventListener) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"Является родителем для "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate","type":"reference"},{"type":"text","text":". В отличии от "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate","type":"reference"},{"type":"text","text":" слушателей может быть много. Добавить можно через "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addEventListener(_:)","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didFailWithError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didMute:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didPause:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSavePlayTimeAt:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSeek:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:playbackRateChanged:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:progressChanged:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:visualQualityChangedByUser:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidBecomeReadyToPlay(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinish(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinishPlayingAd(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRecover(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRestart(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStall(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStartPlayingAd(_:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playereventlistener"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playereventlistener"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Протокол для получения событий от плеера."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStart(_:userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidStart:userInitiated:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidstart(_:userinitiated:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","title":"playerDidStart(_:userInitiated:)","abstract":[{"text":"Плеер начал работу: качать и проигрывать.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStartPlayingAd(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidStartPlayingAd:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidstartplayingad(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStartPlayingAd(_:)","title":"playerDidStartPlayingAd(_:)","abstract":[{"text":"Плеер начал проигрывание рекламного ролика.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStartPlayingAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:playbackRateChanged:userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:playbackRateChanged:userInitiated:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:playbackratechanged:userinitiated:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:playbackRateChanged:userInitiated:)","title":"player(_:playbackRateChanged:userInitiated:)","abstract":[{"text":"Изменилась скорость воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playbackRateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"url":"\/documentation\/ovkit\/livestatus","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","title":"LiveStatus","abstract":[{"text":"Статус прямой трансляции.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveStatus"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerDelegate":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerDelegate"}],"url":"\/documentation\/ovkit\/playerdelegate","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate","title":"PlayerDelegate","abstract":[{"text":"Основной делегат ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didPause:userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didPause:userInitiated:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didpause:userinitiated:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didPause:userInitiated:)","title":"player(_:didPause:userInitiated:)","abstract":[{"text":"Плеер начал или остановил воспроизведение.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didSeek:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didSeek:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didseek:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSeek:)","title":"player(_:didSeek:)","abstract":[{"text":"Пользователь перемотал видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didMute:userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didMute:userInitiated:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didmute:userinitiated:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didMute:userInitiated:)","title":"player(_:didMute:userInitiated:)","abstract":[{"text":"Изменилось состояние звука.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didMute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addEventListener(_:)":{"navigatorTitle":[{"text":"addEventListener:","kind":"identifier"}],"title":"addEventListener(_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Добавить слушателя событий воспроизведения.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addEventListener(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","text":"PlayerEventListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/playerview\/addeventlistener(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didSavePlayTimeAt:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:didSavePlayTimeAt:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didsaveplaytimeat:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSavePlayTimeAt:)","title":"player(_:didSavePlayTimeAt:)","abstract":[{"text":"Плеер сохранил просмотренное время видеозаписи.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSavePlayTimeAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidBecomeReadyToPlay(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidBecomeReadyToPlay:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidbecomereadytoplay(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidBecomeReadyToPlay(_:)","title":"playerDidBecomeReadyToPlay(_:)","abstract":[{"text":"Плеер загрузил достаточно данных и готов к воспроизведению.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidBecomeReadyToPlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidRestart(_:userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidRestart:userInitiated:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidrestart(_:userinitiated:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRestart(_:userInitiated:)","title":"playerDidRestart(_:userInitiated:)","abstract":[{"text":"Плеер начал заново воспроизводить видео, если ","type":"text"},{"code":"Video.repeated","type":"codeVoice"},{"text":" или пользователь нажал кнопку повторить.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidRestart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:didFailWithError:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didFailWithError:)","abstract":[{"text":"Произошла ошибка воспроизведения.","type":"text"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:didfailwitherror:)","kind":"symbol","title":"player(_:didFailWithError:)","navigatorTitle":[{"kind":"identifier","text":"player:didFailWithError:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStall(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidStall:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidstall(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStall(_:)","title":"playerDidStall(_:)","abstract":[{"text":"У плеера закончились данные в буфере, идет загрузка. Если трансляция, стоит актуализировать статус ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStall"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/delegate":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/ovkit\/playerview\/delegate","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate","title":"delegate","abstract":[{"text":"Делегат плеера по вопросам жизненного цикла воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerDelegate","text":"PlayerDelegate"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidFinish(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidFinish:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidfinish(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinish(_:)","title":"playerDidFinish(_:)","abstract":[{"text":"Плеер закончил воспроизведение видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:progressChanged:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:progressChanged:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:progresschanged:)","role":"symbol","deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:progressChanged:)","title":"player(_:progressChanged:)","abstract":[{"text":"Изменился прогресс воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progressChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidRecover(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidRecover:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidrecover(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRecover(_:)","title":"playerDidRecover(_:)","abstract":[{"text":"Плеер загрузил достаточно данных и возобновил воспроизведение.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidRecover"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/player(_:visualQualityChangedByUser:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"player:visualQualityChangedByUser:"}],"url":"\/documentation\/ovkit\/playereventlistener\/player(_:visualqualitychangedbyuser:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:visualQualityChangedByUser:)","title":"player(_:visualQualityChangedByUser:)","abstract":[{"text":"Изменилось качество воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"visualQualityChangedByUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidFinishPlayingAd(_:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidFinishPlayingAd:"}],"url":"\/documentation\/ovkit\/playereventlistener\/playerdidfinishplayingad(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinishPlayingAd(_:)","title":"playerDidFinishPlayingAd(_:)","abstract":[{"text":"Плеер закончил проигрывание рекламного ролика.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidFinishPlayingAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"title":"PlayerEventListener","kind":"symbol","role":"symbol","abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"url":"\/documentation\/ovkit\/playereventlistener"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKPlayerEventListener","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didFailWithError:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didMute:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didPause:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSavePlayTimeAt:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:didSeek:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:playbackRateChanged:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:progressChanged:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/player(_:visualQualityChangedByUser:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidBecomeReadyToPlay(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinish(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidFinishPlayingAd(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRecover(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidRestart(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStall(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStartPlayingAd(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerEventListener","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/title","value":"playerDidStart:userInitiated:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerDidStart:userInitiated:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStartPlayingAd(_:)\/title","value":"playerDidStartPlayingAd:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStartPlayingAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidStartPlayingAd:"}],"op":"replace"},{"value":"player:playbackRateChanged:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:playbackRateChanged:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:playbackRateChanged:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:playbackRateChanged:userInitiated:)\/fragments"},{"value":"OVKLiveStatus","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle"},{"value":"OVKPlayerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/title"},{"value":[{"text":"OVKPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/fragments"},{"value":[{"text":"OVKPlayerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"player:didPause:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didPause:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didPause:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didPause:userInitiated:)\/fragments"},{"value":"player:didSeek:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSeek:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didSeek:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSeek:)\/fragments"},{"value":"player:didMute:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didMute:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didMute:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didMute:userInitiated:)\/fragments"},{"value":"addEventListener:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addEventListener(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addEventListener:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addEventListener(_:)\/fragments"},{"value":"player:didSavePlayTimeAt:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSavePlayTimeAt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didSavePlayTimeAt:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didSavePlayTimeAt:)\/fragments"},{"value":"playerDidBecomeReadyToPlay:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidBecomeReadyToPlay(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidBecomeReadyToPlay:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidBecomeReadyToPlay(_:)\/fragments"},{"value":"playerDidRestart:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidRestart(_:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidRestart:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidRestart(_:userInitiated:)\/fragments"},{"value":"player:didFailWithError:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didFailWithError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didFailWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:didFailWithError:)\/fragments"},{"value":"playerDidStall:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStall(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidStall:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStall(_:)\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/fragments"},{"value":"playerDidFinish:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidFinish(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidFinish:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidFinish(_:)\/fragments"},{"value":"player:progressChanged:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:progressChanged:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:progressChanged:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:progressChanged:)\/fragments"},{"value":"playerDidRecover:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidRecover(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidRecover:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidRecover(_:)\/fragments"},{"value":"player:visualQualityChangedByUser:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:visualQualityChangedByUser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:visualQualityChangedByUser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1player(_:visualQualityChangedByUser:)\/fragments"},{"value":"playerDidFinishPlayingAd:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidFinishPlayingAd(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerDidFinishPlayingAd:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidFinishPlayingAd(_:)\/fragments"},{"value":"OVKPlayerEventListener","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title"},{"value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments"},{"value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle"}]}]}