{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPlayerViewDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/playerviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerControlsVisibilityChanged(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:canBeUsedForTransitionFrom:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didChangeSupplementaryControllerTo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didLoadChaptersWithChapterProvider:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:hostAdSupplementaryControlsView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:showChaptersWithChapterProvider:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewDidEndTransitioning(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewNeedsToShowUnmuteRestriction()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewRemoveAdSupplementaryControlsView(_:)"],"title":"Instance Methods","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate","modules":[{"name":"OVKit"}],"title":"PlayerViewDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"PlayerViewDelegate","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:didLoadChaptersWithChapterProvider:)":{"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:didloadchapterswithchapterprovider:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"didLoadChaptersWithChapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChapterProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerView:didLoadChaptersWithChapterProvider:","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didLoadChaptersWithChapterProvider:)","title":"playerView(_:didLoadChaptersWithChapterProvider:)","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate":{"kind":"symbol","title":"PlayerViewDelegate","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerViewDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)":{"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:makecustomcoverviewwith:frame:previewframe:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","abstract":[],"title":"playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"makeCustomCoverViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9CoverViewa","text":"CoverView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"playerView:makeCustomCoverViewWith:frame:previewFrame:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:showChaptersWithChapterProvider:)":{"type":"topic","navigatorTitle":[{"text":"playerView:showChaptersWithChapterProvider:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:showchapterswithchapterprovider:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:showChaptersWithChapterProvider:)","abstract":[],"kind":"symbol","title":"playerView(_:showChaptersWithChapterProvider:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showChaptersWithChapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerViewRemoveAdSupplementaryControlsView(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewRemoveAdSupplementaryControlsView(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewRemoveAdSupplementaryControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playerViewRemoveAdSupplementaryControlsView:"}],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerviewremoveadsupplementarycontrolsview(_:)","kind":"symbol","title":"playerViewRemoveAdSupplementaryControlsView(_:)","abstract":[],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerViewNeedsToShowUnmuteRestriction()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"},{"text":"()","kind":"text"}],"title":"playerViewNeedsToShowUnmuteRestriction()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewNeedsToShowUnmuteRestriction()","abstract":[],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerviewneedstoshowunmuterestriction()","type":"topic","role":"symbol","navigatorTitle":[{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:hostAdSupplementaryControlsView:)":{"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:hostadsupplementarycontrolsview:)","role":"symbol","title":"playerView(_:hostAdSupplementaryControlsView:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"hostAdSupplementaryControlsView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:hostAdSupplementaryControlsView:)","navigatorTitle":[{"kind":"identifier","text":"playerView:hostAdSupplementaryControlsView:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:canBeUsedForTransitionFrom:)":{"abstract":[],"title":"playerView(_:canBeUsedForTransitionFrom:)","navigatorTitle":[{"kind":"identifier","text":"playerView:canBeUsedForTransitionFrom:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canBeUsedForTransitionFrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:canbeusedfortransitionfrom:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:canBeUsedForTransitionFrom:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerView(_:didChangeSupplementaryControllerTo:)":{"url":"\/documentation\/ovkit\/playerviewdelegate\/playerview(_:didchangesupplementarycontrollerto:)","title":"playerView(_:didChangeSupplementaryControllerTo:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didChangeSupplementaryControllerTo:)","navigatorTitle":[{"text":"playerView:didChangeSupplementaryControllerTo:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeSupplementaryControllerTo","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"FullscreenSupplementaryController","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerViewDidEndTransitioning(_:)":{"type":"topic","url":"\/documentation\/ovkit\/playerviewdelegate\/playerviewdidendtransitioning(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewDidEndTransitioning(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewDidEndTransitioning:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewDidEndTransitioning"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"kind":"symbol","title":"playerViewDidEndTransitioning(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate/playerControlsVisibilityChanged(to:)":{"url":"\/documentation\/ovkit\/playerviewdelegate\/playercontrolsvisibilitychanged(to:)","abstract":[{"text":"Изменилась видимость контролов плеера.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerControlsVisibilityChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","kind":"symbol","title":"playerControlsVisibilityChanged(to:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerControlsVisibilityChanged(to:)","navigatorTitle":[{"kind":"identifier","text":"playerControlsVisibilityChangedTo:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPlayerViewDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKPlayerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerViewDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerControlsVisibilityChanged(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:canBeUsedForTransitionFrom:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didChangeSupplementaryControllerTo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:didLoadChaptersWithChapterProvider:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:hostAdSupplementaryControlsView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:makeCustomCoverViewWith:frame:previewFrame:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerView(_:showChaptersWithChapterProvider:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewDidEndTransitioning(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewNeedsToShowUnmuteRestriction()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate\/playerViewRemoveAdSupplementaryControlsView(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewDelegate"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playerView:didLoadChaptersWithChapterProvider:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:didLoadChaptersWithChapterProvider:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerView:didLoadChaptersWithChapterProvider:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:didLoadChaptersWithChapterProvider:)\/fragments"},{"value":"OVKPlayerViewDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/title"},{"value":[{"text":"OVKPlayerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/fragments"},{"value":[{"text":"OVKPlayerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/navigatorTitle"},{"value":"playerView:makeCustomCoverViewWith:frame:previewFrame:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:makeCustomCoverViewWith:frame:previewFrame:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:makeCustomCoverViewWith:frame:previewFrame:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:makeCustomCoverViewWith:frame:previewFrame:)\/fragments"},{"value":"playerView:showChaptersWithChapterProvider:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:showChaptersWithChapterProvider:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:showChaptersWithChapterProvider:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:showChaptersWithChapterProvider:)\/fragments"},{"value":"playerViewRemoveAdSupplementaryControlsView:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewRemoveAdSupplementaryControlsView(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewRemoveAdSupplementaryControlsView:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewRemoveAdSupplementaryControlsView(_:)\/fragments"},{"value":"playerViewNeedsToShowUnmuteRestriction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewNeedsToShowUnmuteRestriction()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerViewNeedsToShowUnmuteRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewNeedsToShowUnmuteRestriction()\/fragments"},{"value":"playerView:hostAdSupplementaryControlsView:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:hostAdSupplementaryControlsView:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:hostAdSupplementaryControlsView:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:hostAdSupplementaryControlsView:)\/fragments"},{"value":"playerView:canBeUsedForTransitionFrom:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:canBeUsedForTransitionFrom:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:canBeUsedForTransitionFrom:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:canBeUsedForTransitionFrom:)\/fragments"},{"value":"playerView:didChangeSupplementaryControllerTo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:didChangeSupplementaryControllerTo:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:didChangeSupplementaryControllerTo:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerView(_:didChangeSupplementaryControllerTo:)\/fragments"},{"value":"playerViewDidEndTransitioning:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewDidEndTransitioning(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewDidEndTransitioning:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerViewDidEndTransitioning(_:)\/fragments"},{"value":"playerControlsVisibilityChangedTo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerControlsVisibilityChanged(to:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerControlsVisibilityChangedTo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate~1playerControlsVisibilityChanged(to:)\/fragments"}]}]}