{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/playermanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKPlayerManagerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManagerDelegate"}],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions"]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"Для корректной работы SDK приложению необходимо реализовать все не опциональные методы этого делегата.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/makeStatHandlers(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipScreenInsets(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindowDidClose(_:into:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:presentMenu:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/sendBugReportWithDiagnosticsData(_:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/systemPictureInPictureWillStop(in:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/topViewController()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/videoSessionIdentifier(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/willUpdateNowPlayingInfo(_:video:)"],"title":"Instance Methods"}],"abstract":[{"type":"text","text":"Делегат менеджера плееров."}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate","navigatorTitle":[{"kind":"identifier","text":"PlayerManagerDelegate"}],"title":"PlayerManagerDelegate","roleHeading":"Protocol","symbolKind":"protocol","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenControls(for:originPlayerView:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenControls"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","role":"symbol","abstract":[{"text":"Определить для возможности использования собственных контролов в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}],"required":true,"title":"fullscreenControls(for:originPlayerView:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/videoSessionIdentifier(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"videoSessionIdentifier","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/videosessionidentifier(for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/videoSessionIdentifier(for:)","role":"symbol","abstract":[{"text":"Идентификатор (VSID) сессии проигрывания.","type":"text"}],"navigatorTitle":[{"text":"videoSessionIdentifierFor:","kind":"identifier"}],"title":"videoSessionIdentifier(for:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowPiP:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willShowPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowpip:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","role":"symbol","abstract":[{"type":"text","text":"Был создан внутренний Picture in Picture плеер, необходимо установить "},{"type":"codeVoice","code":"pip.playerView.delegate"},{"type":"text","text":". Но не стоит поручать это какому-нибудь "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":", жизненный цикл которого может быть меньше, чем у окна Picture in Picture."}],"navigatorTitle":[{"text":"playerView:willShowPiP:","kind":"identifier"}],"required":true,"title":"playerView(_:willShowPiP:)"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/quickstart","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","role":"article","abstract":[{"type":"text","text":"Руководство для первого подключения "},{"type":"codeVoice","code":"OVKit"},{"type":"text","text":" к проекту. Эти шаги необходимо выполнить перед началом работы."}],"title":"Быстрый старт"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipScreenInsets(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipScreenInsets","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/pipscreeninsets(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipScreenInsets(_:)","role":"symbol","abstract":[{"type":"text","text":"Отступы от краев экрана для PiP."}],"navigatorTitle":[{"text":"pipScreenInsets:","kind":"identifier"}],"required":true,"title":"pipScreenInsets(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pictureInPictureControls(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/pictureinpicturecontrols(with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","role":"symbol","abstract":[{"type":"text","text":"Контролы для использования в режиме “Картинка в Картинке”."}],"navigatorTitle":[{"text":"pictureInPictureControlsWith:","kind":"identifier"}],"required":true,"title":"pictureInPictureControls(with:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenController(_:didCloseInto:interactive:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"interactive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:interactive:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","role":"symbol","abstract":[{"type":"text","text":"Полноэкранный плеер был закрыт."}],"navigatorTitle":[{"text":"fullscreenController:didCloseInto:interactive:","kind":"identifier"}],"title":"fullscreenController(_:didCloseInto:interactive:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/sendBugReportWithDiagnosticsData(_:from:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendBugReportWithDiagnosticsData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData","text":"BugReportDiagnosticsData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/sendbugreportwithdiagnosticsdata(_:from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/sendBugReportWithDiagnosticsData(_:from:)","role":"symbol","abstract":[{"type":"text","text":"Отправка багрепорта клиентом."}],"navigatorTitle":[{"text":"sendBugReportWithDiagnosticsData:from:","kind":"identifier"}],"title":"sendBugReportWithDiagnosticsData(_:from:)"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/transitions","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","role":"article","abstract":[{"type":"text","text":"Непрерывный перенос воспроизведения из одного "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в другой."}],"title":"Переходы между плеерами"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipWindowDidClose(_:into:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindowDidClose","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/pipwindowdidclose(_:into:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindowDidClose(_:into:)","role":"symbol","abstract":[{"type":"text","text":"Окно Picture in Picture с плеером было закрыто."}],"navigatorTitle":[{"text":"pipWindowDidClose:into:","kind":"identifier"}],"title":"pipWindowDidClose(_:into:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/willUpdateNowPlayingInfo(_:video:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willUpdateNowPlayingInfo","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"video","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/willupdatenowplayinginfo(_:video:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/willUpdateNowPlayingInfo(_:video:)","role":"symbol","abstract":[{"type":"text","text":"Вызывается перед обновлением плеером словаря "},{"type":"codeVoice","code":"MPNowPlayingInfoCenter.nowPlayingInfo"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"willUpdateNowPlayingInfo:video:","kind":"identifier"}],"title":"willUpdateNowPlayingInfo(_:video:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/systemPictureInPictureWillStop(in:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPictureInPictureWillStop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CALayer","text":"CALayer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/systempictureinpicturewillstop(in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/systemPictureInPictureWillStop(in:)","role":"symbol","abstract":[{"type":"text","text":"Событие о закрытии системного Picture in Picture."}],"navigatorTitle":[{"text":"systemPictureInPictureWillStopIn:","kind":"identifier"}],"title":"systemPictureInPictureWillStop(in:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/topViewController()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/topviewcontroller()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/topViewController()","role":"symbol","abstract":[{"type":"text","text":"Верхний в иерархии "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":", с которого будет совершена навигация."}],"navigatorTitle":[{"text":"topViewController","kind":"identifier"}],"required":true,"title":"topViewController()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowFullscreen:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"willShowFullscreen","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","role":"symbol","abstract":[{"type":"text","text":"Плеер был показан в полноэкранном режиме."}],"navigatorTitle":[{"text":"playerView:willShowFullscreen:","kind":"identifier"}],"required":true,"title":"playerView(_:willShowFullscreen:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"restoreUserInterfaceForPipMaximizeWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/pipwindow(_:restoreuserinterfaceforpipmaximizewithcompletionhandler:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)","role":"symbol","abstract":[{"type":"text","text":"Возможность подготовить UI к разворачиванию окна Picture in Picture."}],"navigatorTitle":[{"text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"}],"required":true,"title":"pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","role":"symbol","abstract":[{"type":"text","text":"Делегат менеджера плееров."}],"navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"title":"PlayerManagerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:presentMenu:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presentMenu","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKMenu","text":"Menu","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:presentmenu:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:presentMenu:)","role":"symbol","abstract":[{"type":"text","text":"Просит делегата показать меню в виде Action Sheet."}],"navigatorTitle":[{"text":"playerView:presentMenu:","kind":"identifier"}],"required":true,"title":"playerView(_:presentMenu:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/makeStatHandlers(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeStatHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","text":"StatsHandler","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate\/makestathandlers(for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/makeStatHandlers(for:)","role":"symbol","abstract":[{"type":"text","text":"Метод для централизованной настройки статистики  в "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"makeStatHandlersFor:","kind":"identifier"}],"title":"makeStatHandlers(for:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"OVKPlayerManagerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/makeStatHandlers(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipScreenInsets(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindowDidClose(_:into:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:presentMenu:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/sendBugReportWithDiagnosticsData(_:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/systemPictureInPictureWillStop(in:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/topViewController()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/videoSessionIdentifier(for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/willUpdateNowPlayingInfo(_:video:)"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/title","value":"fullscreenControlsFor:originPlayerView:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1videoSessionIdentifier(for:)\/title","value":"videoSessionIdentifierFor:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1videoSessionIdentifier(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoSessionIdentifierFor:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/title","value":"playerView:willShowPiP:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowPiP:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipScreenInsets(_:)\/title","value":"pipScreenInsets:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipScreenInsets(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pipScreenInsets:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/title","value":"pictureInPictureControlsWith:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pictureInPictureControlsWith:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/title","value":"fullscreenController:didCloseInto:interactive:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenController:didCloseInto:interactive:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1sendBugReportWithDiagnosticsData(_:from:)\/title","value":"sendBugReportWithDiagnosticsData:from:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1sendBugReportWithDiagnosticsData(_:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendBugReportWithDiagnosticsData:from:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindowDidClose(_:into:)\/title","value":"pipWindowDidClose:into:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindowDidClose(_:into:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pipWindowDidClose:into:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1willUpdateNowPlayingInfo(_:video:)\/title","value":"willUpdateNowPlayingInfo:video:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1willUpdateNowPlayingInfo(_:video:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willUpdateNowPlayingInfo:video:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1systemPictureInPictureWillStop(in:)\/title","value":"systemPictureInPictureWillStopIn:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1systemPictureInPictureWillStop(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"systemPictureInPictureWillStopIn:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1topViewController()\/title","value":"topViewController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1topViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"topViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/title","value":"playerView:willShowFullscreen:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowFullscreen:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)\/title","value":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:presentMenu:)\/title","value":"playerView:presentMenu:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:presentMenu:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:presentMenu:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1makeStatHandlers(for:)\/title","value":"makeStatHandlersFor:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1makeStatHandlers(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeStatHandlersFor:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}