{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"]}],"kind":"symbol","abstract":[{"text":"Режим отображения картинки в плеере.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/playerviewgravity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerviewgravity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/init(rawValue:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/isFit"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPlayerViewGravity) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"OVKit"}],"title":"PlayerViewGravity","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewGravity"}],"externalID":"c:@M@OVKit@E@OVKPlayerViewGravity"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/isFit":{"abstract":[{"type":"text","text":"Является ли режим "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit","isActive":true,"type":"reference"},{"text":" или ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/ovkit\/playerviewgravity\/isfit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/isFit","title":"isFit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/ovkit\/playerviewgravity\/rawrepresentable-implementations","role":"collectionGroup","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fit":{"abstract":[{"type":"text","text":"Картинка вписана во вьюпорт плеера, она не обрезается."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fit","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit","url":"\/documentation\/ovkit\/playerviewgravity\/fit","title":"PlayerViewGravity.fit","role":"symbol","navigatorTitle":[{"text":"OVKPlayerViewGravityFit","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/init(rawValue:)":{"url":"\/documentation\/ovkit\/playerviewgravity\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"navigatorTitle":[{"kind":"identifier","text":"PlayerViewGravity"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","abstract":[{"text":"Режим отображения картинки в плеере.","type":"text"}],"url":"\/documentation\/ovkit\/playerviewgravity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewGravity"}],"role":"symbol","title":"PlayerViewGravity"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fitWithBlur":{"navigatorTitle":[{"text":"OVKPlayerViewGravityFitWithBlur","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur","abstract":[{"text":"Картинка вписана во вьюпорт плеера, а пустое место заполнено заблюренной версией картинки.","type":"text"}],"url":"\/documentation\/ovkit\/playerviewgravity\/fitwithblur","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitWithBlur","kind":"identifier"}],"role":"symbol","title":"PlayerViewGravity.fitWithBlur"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/ovkit\/playerviewgravity\/equatable-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fill":{"abstract":[{"type":"text","text":"Картинка растянута на весь вьюпорт плеера с сохранением пропорций."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill","url":"\/documentation\/ovkit\/playerviewgravity\/fill","title":"PlayerViewGravity.fill","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewGravityFill"}],"type":"topic"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/description":{"type":"topic","role":"symbol","title":"description","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/playerviewgravity\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OVKPlayerViewGravity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fitWithBlur"],"anchor":"Enumeration-Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OVKPlayerViewGravity"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fit\/title","op":"replace","value":"OVKPlayerViewGravityFit"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fit\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewGravityFit"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title","op":"replace","value":"OVKPlayerViewGravity"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","op":"replace","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fitWithBlur\/title","op":"replace","value":"OVKPlayerViewGravityFitWithBlur"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fitWithBlur\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewGravityFitWithBlur"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/title","value":"OVKPlayerViewGravityFill"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/fragments","value":[{"text":"OVKPlayerViewGravityFill","kind":"identifier"}]}]}]}