{"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerDelegate"}],"title":"PlayerDelegate","externalID":"c:@M@OVKit@objc(pl)OVKPlayerDelegate","roleHeading":"Protocol","symbolKind":"protocol"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:reloadVideoWithCompletionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:unlockRestrictedVideo:withCompletionHandler:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/playerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPlayerDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","text":"PlayerEventListener","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PlayerDelegate"}],"kind":"symbol","type":"topic","title":"PlayerDelegate","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate","url":"\/documentation\/ovkit\/playerdelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerDelegate/player(_:reloadVideoWithCompletionHandler:)":{"title":"player(_:reloadVideoWithCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reloadVideoWithCompletionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/ovkit\/playerdelegate\/player(_:reloadvideowithcompletionhandler:)","navigatorTitle":[{"kind":"identifier","text":"player:reloadVideoWithCompletionHandler:"}],"type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:reloadVideoWithCompletionHandler:)","abstract":[{"text":"Вызывается при нажатии пользователем кнопки “Повторить”, когда возникла ошибка воспроизведения.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerDelegate/player(_:unlockRestrictedVideo:withCompletionHandler:)":{"required":true,"url":"\/documentation\/ovkit\/playerdelegate\/player(_:unlockrestrictedvideo:withcompletionhandler:)","navigatorTitle":[{"kind":"identifier","text":"player:unlockRestrictedVideo:withCompletionHandler:"}],"kind":"symbol","title":"player(_:unlockRestrictedVideo:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unlockRestrictedVideo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"allowedDisclaimerTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"expirationDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:unlockRestrictedVideo:withCompletionHandler:)","type":"topic","abstract":[{"type":"text","text":"Плеер запрашивает разблокировку restriction."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"url":"\/documentation\/ovkit\/playereventlistener","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerEventListener"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerEventListener"}],"abstract":[{"text":"Протокол для получения событий от плеера.","type":"text"}],"title":"PlayerEventListener"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKPlayerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPlayerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPlayerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:reloadVideoWithCompletionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerDelegate\/player(_:unlockRestrictedVideo:withCompletionHandler:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","text":"OVKPlayerEventListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener"},{"text":">","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/title","value":"OVKPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/fragments","value":[{"text":"OVKPlayerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate~1player(_:reloadVideoWithCompletionHandler:)\/title","value":"player:reloadVideoWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate~1player(_:reloadVideoWithCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:reloadVideoWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate~1player(_:unlockRestrictedVideo:withCompletionHandler:)\/title","value":"player:unlockRestrictedVideo:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerDelegate~1player(_:unlockRestrictedVideo:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:unlockRestrictedVideo:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","value":"OVKPlayerEventListener"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}