{"variants":[{"paths":["\/documentation\/ovkit\/plugins"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/plugins"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Концепты","anchor":"Концепты"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Динамически подключаемые модули для расширения функциональности."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin"],"title":"Плагины","anchor":"Плагины"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Плагины позволяют расширить функциональность "},{"type":"codeVoice","code":"OVKit"},{"type":"text","text":" и могут подключаться опционально. Версии используемых плагинов должны совпадать с версией "},{"type":"strong","inlineContent":[{"type":"text","text":"OVKit"}]},{"type":"text","text":"."}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","title":"Плагины","role":"collectionGroup","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"title":"Статистика","kind":"article","role":"article","abstract":[{"type":"text","text":"Сбор статистики воспроизведения видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","url":"\/documentation\/ovkit\/statistics"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"role":"article","abstract":[{"type":"text","text":"Дополнительные возможности."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","url":"\/documentation\/ovkit\/extras","kind":"article","title":"Разное","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"title":"Воспроизведение в фоне","url":"\/documentation\/ovkit\/backgroundplayback","kind":"article","type":"topic","role":"article","abstract":[{"type":"text","text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/transitions","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","title":"Переходы между плеерами","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" в другой.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin":{"role":"article","abstract":[{"text":"Плагин для проигрывания рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin","url":"\/documentation\/ovkit\/mytargetplugin","kind":"article","title":"MyTarget","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","url":"\/documentation\/ovkit\/prefetch","type":"topic","kind":"article","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"role":"article","title":"Префетчер"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/controls","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","abstract":[{"text":"Кастомизация внешнего вида плеера.","type":"text"}],"title":"Контролы плеера"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","url":"\/documentation\/ovkit\/fullscreen","kind":"article","type":"topic","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"role":"article","title":"Полноэкранный режим"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Плагины","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin"],"title":"Плагины"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Концепты","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Концепты"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]}]}]}