{"seeAlsoSections":[{"title":"Начало работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"inlineContent":[{"text":"Видео можно предзагружать еще до создания плеера. Для этого используется ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference"},{"text":", который поддерживает только DASH ресурсы.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Внутри "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"type":"text","text":" находится очередь, в которую помещаются объекты протокола "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true,"type":"reference"},{"type":"text","text":". Данный протокол описывает видео и параметры его предзагрузки."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Предзагрузка может происходить одновременно с проигрыванием других видео, но при этом она имеет более низкий приоритет. При очень низкой скорости сети предзагрузка автоматически приостанавливается, если параллельно играет хотя бы один плеер. Потом так же автоматически возобновляется, если плеер перестал использовать сеть для загрузки или состояние сети улучшилось."}]},{"name":"Tip","content":[{"inlineContent":[{"text":"Видео можно начинать проигрывать плеером, даже если предзагрузка еще не завершилась.","type":"text"}],"type":"paragraph"}],"style":"tip","type":"aside"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Добавление в очередь производится методом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","isActive":true},{"text":". Предзагрузка начинается автоматически после добавления в очередь.","type":"text"}]},{"code":["\/\/ К примеру, модели видео из ленты","let prefetchItems: [PrefetchItem] = ...     ","for item in prefetchItems {","    \/\/ Добавление в очередь","    prefetcher.prefetchItem(item)","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Удаление из очереди или отмена уже выполняющейся операции производится методом "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)"},{"text":". Аргументом должен быть тот же самый ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true},{"type":"text","text":", который был использован для добавления в очередь."}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["prefetcher.cancel(someItemToCancel)"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Article","title":"Префетчер","role":"article","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/prefetch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetch"]}],"kind":"article","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","kind":"article","abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}],"title":"Полноэкранный режим","url":"\/documentation\/ovkit\/fullscreen","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/cancel(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/cancel(_:)","navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"abstract":[{"text":"Отмена предзагрузки произвольного элемента.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/indexprefetcher\/cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"cancel(_:)"},"doc://onevideo.OVKit/documentation/OVKit/QuickStart":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","abstract":[{"text":"Руководство для первого подключения ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":" к проекту. Эти шаги необходимо выполнить перед началом работы."}],"kind":"article","title":"Быстрый старт","url":"\/documentation\/ovkit\/quickstart","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/gRPC":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","kind":"article","title":"gRPC","abstract":[],"url":"\/documentation\/ovkit\/grpc","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","kind":"article","abstract":[{"type":"text","text":"SDK поддерживает сбор статистики по воспроизведению видео."}],"title":"Статистика","url":"\/documentation\/ovkit\/statistics","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","kind":"article","abstract":[{"text":"Первые шаги после интеграции.","type":"text"}],"title":"Создание плеера","url":"\/documentation\/ovkit\/createplayer","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher/prefetch(_:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher\/prefetch(_:)","navigatorTitle":[{"text":"prefetch:","kind":"identifier"}],"url":"\/documentation\/ovkit\/indexprefetcher\/prefetch(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":")"}],"title":"prefetch(_:)","abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка."}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"title":"Создание Контролов","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","url":"\/documentation\/ovkit\/controls","role":"article","abstract":[],"type":"topic","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","kind":"article","title":"Дополнительно","abstract":[{"type":"text","text":"Дополнительные возможности "},{"code":"OVKit","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/extras","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","kind":"article","abstract":[{"code":"OVKit","type":"codeVoice"},{"text":" поддерживает воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"title":"Воспроизведение в фоне","url":"\/documentation\/ovkit\/backgroundplayback","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","kind":"article","abstract":[{"type":"text","text":"Плагины позволяют расширить функциональность "},{"code":"OVKit","type":"codeVoice"},{"text":".","type":"text"}],"title":"Плагины","url":"\/documentation\/ovkit\/plugins","type":"topic","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","role":"symbol","title":"IndexPrefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"replace","value":[{"generated":true,"title":"Начало работы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/title","value":"cancel:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cancel:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/title","value":"prefetch:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher~1prefetch(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prefetch:"}],"op":"replace"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}