{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKPrefetchStrategy) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PrefetchStrategy","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Позволяет настроить количество видеозаписей и их длительность префетча."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/ovkit\/prefetchstrategy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/prefetchstrategy"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","title":"PrefetchStrategy","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"sections":[],"abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"],"title":"Conforming Types","type":"conformingTypes"}],"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"],"generated":true,"title":"Предзагрузка","anchor":"Предзагрузка"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"navigatorTitle":[{"kind":"identifier","text":"Prefetcher"}],"url":"\/documentation\/ovkit\/prefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","type":"topic","title":"Prefetcher","role":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"type":"topic","title":"PrefetchItem","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"url":"\/documentation\/ovkit\/prefetchitem"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchDurationOf"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inBatchSize"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"url":"\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","type":"topic","title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","abstract":[],"kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"type":"topic","title":"ListPrefetcher","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"deprecated":true,"url":"\/documentation\/ovkit\/listprefetcher"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","title":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","required":true,"role":"symbol","abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchCountAhead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"}],"url":"\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"type":"topic","title":"PrefetchStrategy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchStrategy"}],"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PrefetchStrategy"}],"url":"\/documentation\/ovkit\/prefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"navigatorTitle":[{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"url":"\/documentation\/ovkit\/legacyprefetchstrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","type":"topic","title":"LegacyPrefetchStrategy","role":"symbol","abstract":[{"text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LegacyPrefetchStrategy","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"type":"topic","title":"SimplePrefetchStrategy","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"abstract":[{"text":"Стратегия, которая отвечает константными значениями.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SimplePrefetchStrategy"}],"url":"\/documentation\/ovkit\/simpleprefetchstrategy"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPrefetchStrategy","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)"],"generated":true}]},{"value":[{"title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"],"type":"conformingTypes","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"anchor":"Предзагрузка","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"],"generated":true,"title":"Предзагрузка"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPrefetchStrategy","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","op":"replace"},{"value":[{"text":"OVKPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","op":"replace"},{"value":"OVKPrefetchItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchItem"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title","value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","value":"OVKPrefetchStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title","value":"OVKLegacyPrefetchStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments","value":[{"text":"OVKLegacyPrefetchStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/navigatorTitle","value":[{"text":"OVKLegacyPrefetchStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title","value":"OVKSimplePrefetchStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments","value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/navigatorTitle","value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}