{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPrefetcherConfig) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"При инициализации автоматически проставляются параметры по умолчанию, если не указать иное."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcherconfig"]},{"paths":["\/documentation\/ovkit\/prefetcherconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","title":"PrefetcherConfig","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"PrefetcherConfig","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/maxConcurrentDownloadsCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/parallelPrefetchBandwidthThreshold"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/config()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"kind":"symbol","abstract":[{"text":"Конфигурация с базовыми опциями работы префетчера.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/parallelPrefetchBandwidthThreshold":{"navigatorTitle":[{"kind":"identifier","text":"parallelPrefetchBandwidthThreshold"}],"url":"\/documentation\/ovkit\/prefetcherconfig\/parallelprefetchbandwidththreshold","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/parallelPrefetchBandwidthThreshold","type":"topic","title":"parallelPrefetchBandwidthThreshold","role":"symbol","abstract":[{"text":"Нижняя граница пропускной способности сети для параллельной работы плеера и префетчера.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parallelPrefetchBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/maxConcurrentDownloadsCount":{"url":"\/documentation\/ovkit\/prefetcherconfig\/maxconcurrentdownloadscount","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"text":"Максимальное количество параллельно предзагружаемых видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/maxConcurrentDownloadsCount","kind":"symbol","title":"maxConcurrentDownloadsCount","role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"url":"\/documentation\/ovkit\/prefetcherconfig","navigatorTitle":[{"text":"PrefetcherConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}],"abstract":[{"text":"Конфигурация с базовыми опциями работы префетчера.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","kind":"symbol","title":"PrefetcherConfig","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:"}],"url":"\/documentation\/ovkit\/prefetcherconfig\/init(parallelprefetchbandwidththreshold:maxconcurrentdownloadscount:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)","type":"topic","title":"init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parallelPrefetchBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/config()":{"navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/ovkit\/prefetcherconfig\/config()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/config()","type":"topic","title":"config()","role":"symbol","abstract":[{"text":"Создание конфигурации по умолчанию.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKPrefetcherConfig","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/maxConcurrentDownloadsCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/parallelPrefetchBandwidthThreshold"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/config()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPrefetcherConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"parallelPrefetchBandwidthThreshold","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1parallelPrefetchBandwidthThreshold\/title"},{"value":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1parallelPrefetchBandwidthThreshold\/fragments"},{"value":"maxConcurrentDownloadsCount","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1maxConcurrentDownloadsCount\/title"},{"value":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1maxConcurrentDownloadsCount\/fragments"},{"value":"OVKPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title"},{"value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"},{"value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/navigatorTitle"},{"value":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)\/fragments"},{"value":"config","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1config()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"config","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1config()\/fragments"}]}]}