{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKPrefetchItem) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrefetchItem"}]}],"kind":"declarations"}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchMinTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeCellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeWiFi","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchResource"],"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"],"kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"generated":true,"title":"Префетчер","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"anchor":"Префетчер"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"},"metadata":{"symbolKind":"protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchItem","roleHeading":"Protocol","title":"PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/prefetchitem"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetchitem"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchResource":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchResource","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchResource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"}],"navigatorTitle":[{"text":"prefetchResource","kind":"identifier"}],"title":"prefetchResource","type":"topic","required":true,"abstract":[{"type":"text","text":"Видео-ресурс для предзагрузки."}],"url":"\/documentation\/ovkit\/prefetchitem\/prefetchresource"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videotype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"type":"topic","title":"Video","kind":"symbol","url":"\/documentation\/ovkit\/video","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchPreviews":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchPreviews","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier","text":"ImageAssetType"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchPreviews"}],"url":"\/documentation\/ovkit\/prefetchitem\/prefetchpreviews","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"kind":"symbol","title":"prefetchPreviews","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchQualityRangeCellular":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeCellular","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"kind":"text","text":": "},{"text":"QualityRange","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"title":"prefetchQualityRangeCellular","type":"topic","required":true,"abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}],"url":"\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangecellular"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"kind":"symbol","title":"PrefetchStrategy","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/prefetchstrategy","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"title":"IndexPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndexPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/indexprefetcher","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchQualityRangeWiFi":{"navigatorTitle":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/prefetchitem\/prefetchqualityrangewifi","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeWiFi","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefetchQualityRangeWiFi","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","kind":"typeIdentifier"}],"title":"prefetchQualityRangeWiFi","abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchMinTime":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchMinTime"}],"title":"prefetchMinTime","url":"\/documentation\/ovkit\/prefetchitem\/prefetchmintime","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchMinTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchMinTime","type":"topic","abstract":[{"text":"Минимальная длительность участка предзагрузки.","type":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKPrefetchItem"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchMinTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeCellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchQualityRangeWiFi","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchResource"],"title":"Instance Properties"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Префетчер","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"anchor":"Префетчер","generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"OVKPrefetchItem","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"prefetchResource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchResource\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchResource\/fragments","value":[{"text":"prefetchResource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}]},{"value":"prefetchPreviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/title","op":"replace"},{"value":[{"kind":"identifier","text":"prefetchPreviews"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/fragments"},{"op":"replace","value":"prefetchQualityRangeCellular","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeCellular\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeCellular\/fragments","value":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"op":"replace"},{"value":"OVKPrefetchStrategy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle"},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeWiFi\/title","op":"replace","value":"prefetchQualityRangeWiFi"},{"op":"replace","value":[{"text":"prefetchQualityRangeWiFi","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchQualityRangeWiFi\/fragments"},{"value":"prefetchMinTime","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchMinTime\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchMinTime\/fragments","value":[{"kind":"identifier","text":"prefetchMinTime"}]}]}]}