{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode"]},{"paths":["\/documentation\/ovkit\/previewplaybuttonmode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKPreviewPlayButtonMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"identifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/RawRepresentable-Implementations"]}],"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKPreviewPlayButtonMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"PreviewPlayButtonMode"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"title":"PreviewPlayButtonMode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","abstract":[{"text":"Режим работы кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"Play"}]},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"PreviewPlayButtonMode","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/active":{"navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeActive"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Кнопка видна и при ее нажатии плеер начинает проигрывание."}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/active","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"}],"title":"PreviewPlayButtonMode.active","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/hidden":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hidden","abstract":[{"text":"Кнопка скрыта.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidden"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/hidden","navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeHidden"}],"type":"topic","title":"PreviewPlayButtonMode.hidden"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/ovkit\/previewplaybuttonmode\/rawrepresentable-implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/Equatable-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/ovkit\/previewplaybuttonmode\/equatable-implementations"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/inactive":{"navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeInactive"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Кнопка видна, но не реагирует на нажатия. Подходит для случая, когда используется собственный обработчик нажатия на ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/inactive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}],"title":"PreviewPlayButtonMode.inactive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/init(rawValue:)":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/init(rawValue:)"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKPreviewPlayButtonMode"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/inactive"]}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPreviewPlayButtonMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/title","op":"replace","value":"OVKPreviewPlayButtonModeActive"},{"value":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/fragments","op":"replace"},{"value":"OVKPreviewPlayButtonModeHidden","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1hidden\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1hidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeHidden"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","value":"OVKPreviewPlayButtonModeInactive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1inactive\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1inactive\/fragments","value":[{"text":"OVKPreviewPlayButtonModeInactive","kind":"identifier"}]}]}]}