{"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(exact:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(from:to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrBetterThan:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrWorseThan:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/isEqual(_:)"],"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/qualityrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/qualityrange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKQualityRange) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityRange","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Может не иметь одной из границ."}]}]}],"kind":"symbol","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"QualityRange"}],"externalID":"c:@M@OVKit@objc(cs)OVKQualityRange","title":"QualityRange","symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QualityRange","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/init(sameOrWorseThan:)":{"navigatorTitle":[{"text":"initWithSameOrWorseThan:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrWorseThan:)","title":"init(sameOrWorseThan:)","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/qualityrange\/init(sameorworsethan:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sameOrWorseThan","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/init(sameOrBetterThan:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrBetterThan:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sameOrBetterThan"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(sameOrBetterThan:)","navigatorTitle":[{"kind":"identifier","text":"initWithSameOrBetterThan:"}],"url":"\/documentation\/ovkit\/qualityrange\/init(sameorbetterthan:)"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/init(from:to:)":{"navigatorTitle":[{"kind":"identifier","text":"initFrom:to:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(from:to:)","role":"symbol","url":"\/documentation\/ovkit\/qualityrange\/init(from:to:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"title":"init(from:to:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"role":"symbol","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","type":"topic","url":"\/documentation\/ovkit\/qualityrange","title":"QualityRange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"QualityRange","kind":"identifier"}],"navigatorTitle":[{"text":"QualityRange","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/init(exact:)":{"type":"topic","title":"init(exact:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"exact","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithExact:"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(exact:)","url":"\/documentation\/ovkit\/qualityrange\/init(exact:)"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange/isEqual(_:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/ovkit\/qualityrange\/isequal(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"OVKQualityRange","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKQualityRange","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(exact:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(from:to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrBetterThan:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/init(sameOrWorseThan:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange\/isEqual(_:)"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKQualityRange","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"initWithSameOrWorseThan:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrWorseThan:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSameOrWorseThan:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrWorseThan:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrBetterThan:)\/title","value":"initWithSameOrBetterThan:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(sameOrBetterThan:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSameOrBetterThan:","kind":"identifier"}]},{"value":"initFrom:to:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(from:to:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initFrom:to:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(from:to:)\/fragments"},{"value":"OVKQualityRange","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"kind":"identifier","text":"OVKQualityRange"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"value":"initWithExact:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(exact:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1init(exact:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithExact:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]}]}]}