{"kind":"article","seeAlsoSections":[{"anchor":"Начало-работы","title":"Начало работы","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"]}],"primaryContentSections":[{"content":[{"anchor":"%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B5%D1%81%D1%81%D0%B8%D0%B8","text":"Настройка сессии","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Есть два способа настроить сессию:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Если получен отдельный ключ статистики и есть прямой доступ к получению видео объектов, не нужно настраивать "},{"type":"codeVoice","code":"ApiSession"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Достаточно просто настраивать ","type":"text"},{"code":"userId","type":"codeVoice"},{"type":"text","text":". После каждого обновления "},{"code":"userId","type":"codeVoice"},{"type":"text","text":" нужно обновлять окружение статистики."}],"type":"paragraph"}]}]},{"type":"codeListing","code":["Environment.shared.userId = <user_id>","Environment.setupStatistics(appKey: <stats_app_key>, tokenProvider: <stats_token_provider>)"],"syntax":"swift"},{"type":"orderedList","start":2,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"В общем случае нужно один раз на старте настроить сессию "},{"type":"codeVoice","code":"ApiSession"},{"type":"text","text":":"}]}]}]},{"code":["ApiSession.setup(clientId: <app_client_id>, secret: <app_secret>)"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Далее перед проигрыванием видео нужно установить идентификатор пользователя. Это может быть идентификатор пользователя на клиентском портале или уникальный идентификатор устройства. Обязательный параметр."},{"type":"text","text":" "},{"text":"При смене пользователя достаточно только установить новый ","type":"text"},{"code":"userId","type":"codeVoice"},{"text":", дополнительно настраивать ","type":"text"},{"code":"ApiSession","type":"codeVoice"},{"text":" не нужно.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["Environment.shared.userId = <user_id>"]},{"level":2,"type":"heading","text":"Кэш плееров","anchor":"%D0%9A%D1%8D%D1%88-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80%D0%BE%D0%B2"},{"inlineContent":[{"text":"При необходимости очистить кэш","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["OVPlayer.cache().purgeDisk()"]},{"text":"Логи плеера:","anchor":"%D0%9B%D0%BE%D0%B3%D0%B8-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80%D0%B0","level":2,"type":"heading"},{"type":"codeListing","code":["OVLogger.setLogPrefix(\"[OV]\")","OVLogger.setLogHandler { message in }","OVLogger.setFileLogHandler { message in }","OVLogger.setLogCriticalErrorHandler { error in }","OVLogger.setDiagnosticsReportHandler { report in } \/\/ См. Диагностика"],"syntax":"swift"},{"type":"heading","level":2,"text":"Аудиосессия","anchor":"%D0%90%D1%83%D0%B4%D0%B8%D0%BE%D1%81%D0%B5%D1%81%D1%81%D0%B8%D1%8F"},{"type":"paragraph","inlineContent":[{"text":"По умолчанию плеер умеет настраивать ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":" сам. Если в приложении есть другие сущности, использующие аудио сессию (музыкальный плеер, запись видео, звуки элементов интерфейса), можно интегрировать другой менеджер по работе с аудио соотвествующий протоколу "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager"},{"type":"text","text":":"}]},{"code":["PlayerManager.setup(with:)"],"type":"codeListing","syntax":"swift"},{"text":"Делегат менеджера плеера","level":2,"type":"heading","anchor":"%D0%94%D0%B5%D0%BB%D0%B5%D0%B3%D0%B0%D1%82-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80%D0%B0"},{"inlineContent":[{"text":"Для корректной работы плеера, необходимо в одном месте реализовать протокол ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","code":["PlayerManager.shared.delegate = self"],"syntax":"swift"},{"level":2,"type":"heading","anchor":"Idle-Timer","text":"Idle Timer"},{"type":"paragraph","inlineContent":[{"text":"В ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","type":"reference"},{"text":" установлен класс, отвечающий за работу с ","type":"text"},{"type":"codeVoice","code":"UIApplication.shared.isIdleTimerDisabled"},{"text":". Но можно установить свой, реализующий протокол ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager","isActive":true},{"type":"text","text":":"}]},{"code":["PlayerManager.shared.idleTimerManager = <external_idle_timer_manager>"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/quickstart"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/quickstart"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QuickStart"},"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"OVKit"}],"title":"Быстрый старт"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"abstract":[{"type":"text","text":"Руководство для первого подключения "},{"type":"codeVoice","code":"OVKit"},{"text":" к проекту. Эти шаги необходимо выполнить перед началом работы.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"url":"\/documentation\/ovkit\/prefetch","type":"topic","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","title":"Префетчер","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"url":"\/documentation\/ovkit\/extras","type":"topic","abstract":[{"type":"text","text":"Дополнительные возможности "},{"code":"OVKit","type":"codeVoice"},{"text":".","type":"text"}],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","title":"Дополнительно","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"url":"\/documentation\/ovkit\/createplayer","type":"topic","abstract":[{"type":"text","text":"Первые шаги после интеграции."}],"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","title":"Создание плеера","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"role":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},"doc://onevideo.OVKit/documentation/OVKit/IdleTimerManager":{"url":"\/documentation\/ovkit\/idletimermanager","role":"symbol","abstract":[{"text":"Служит для запрета автоблокировки устройства во время проигрывания видео.","type":"text"}],"title":"IdleTimerManager","navigatorTitle":[{"text":"IdleTimerManager","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdleTimerManager","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IdleTimerManager"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"title":"Статистика","type":"topic","abstract":[{"text":"SDK поддерживает сбор статистики по воспроизведению видео.","type":"text"}],"url":"\/documentation\/ovkit\/statistics","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","kind":"article","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","abstract":[],"url":"\/documentation\/ovkit\/playermanagerdelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerManagerDelegate"}],"title":"PlayerManagerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/gRPC":{"url":"\/documentation\/ovkit\/grpc","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","abstract":[],"role":"article","kind":"article","title":"gRPC","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"abstract":[{"code":"OVKit","type":"codeVoice"},{"type":"text","text":" поддерживает воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","type":"topic","title":"Воспроизведение в фоне","role":"article","url":"\/documentation\/ovkit\/backgroundplayback","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AudioManager","kind":"identifier"}],"navigatorTitle":[{"text":"AudioManager","kind":"identifier"}],"type":"topic","title":"AudioManager","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" при работе плееров.","type":"text"}],"url":"\/documentation\/ovkit\/audiomanager","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"title":"Полноэкранный режим","kind":"article","role":"article","url":"\/documentation\/ovkit\/fullscreen","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"kind":"article","abstract":[{"text":"Плагины позволяют расширить функциональность ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/plugins","title":"Плагины","type":"topic","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"kind":"article","title":"Создание Контролов","role":"article","url":"\/documentation\/ovkit\/controls","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/gRPC","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras"],"title":"Начало работы","anchor":"Начало-работы"}],"op":"replace"},{"op":"replace","value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle"},{"value":"OVKIdleTimerManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/title"},{"op":"replace","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/fragments"},{"op":"replace","value":[{"text":"OVKIdleTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IdleTimerManager\/navigatorTitle"},{"value":"OVKPlayerManagerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","op":"replace","value":"OVKAudioManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","value":[{"text":"OVKAudioManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAudioManager"}]}]}]}