{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKQUICManagerProtocol) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QUICManagerProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/installIntoSessionConfiguration(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/markRequest(_:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/ovkit\/quicmanagerprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/quicmanagerprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"QUICManagerProtocol"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKQUICManagerProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QUICManagerProtocol","kind":"identifier"}],"roleHeading":"Protocol","title":"QUICManagerProtocol","role":"symbol","symbolKind":"protocol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol/markRequest(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/markRequest(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"markRequest:"}],"required":true,"url":"\/documentation\/ovkit\/quicmanagerprotocol\/markrequest(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableURLRequest","preciseIdentifier":"c:objc(cs)NSMutableURLRequest"},{"kind":"text","text":")"}],"title":"markRequest(_:)","abstract":[{"text":"Помечает NSMutableURLRequest как запрос, который будет использован в QUIC.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol/installIntoSessionConfiguration(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/installIntoSessionConfiguration(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"installIntoSessionConfiguration:"}],"required":true,"url":"\/documentation\/ovkit\/quicmanagerprotocol\/installintosessionconfiguration(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"installIntoSessionConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"kind":"text","text":")"}],"title":"installIntoSessionConfiguration(_:)","abstract":[{"text":"Устанавливает QUIC в NSURLSessionConfiguration таким образом, что все NSURLSessions","type":"text"},{"text":" ","type":"text"},{"text":"созданные с этой конфигурацией будут использовать QUIC протокол.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/QUICManagerProtocol":{"navigatorTitle":[{"kind":"identifier","text":"QUICManagerProtocol"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol","url":"\/documentation\/ovkit\/quicmanagerprotocol","role":"symbol","title":"QUICManagerProtocol","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QUICManagerProtocol","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKQUICManagerProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/installIntoSessionConfiguration(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QUICManagerProtocol\/markRequest(_:)"],"anchor":"Instance-Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKQUICManagerProtocol","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1markRequest(_:)\/title","value":"markRequest:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1markRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1installIntoSessionConfiguration(_:)\/title","value":"installIntoSessionConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol~1installIntoSessionConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"installIntoSessionConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/title","value":"OVKQUICManagerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/fragments","value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QUICManagerProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"OVKQUICManagerProtocol"}]}]}]}