{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)RestrictionView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RestrictionView"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"RestrictionView","kind":"identifier"}],"title":"RestrictionView"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionView"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","isActive":true,"type":"reference"},{"text":" предоставляет базовую функциональность заглушки для таких случаев. Информация о запрете берется из ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"},{"text":", который находится в ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","isActive":true},{"text":". Кроме возможного размытия фона, поддерживается отображение следующей информации о запрете:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Title"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Иконка"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Action button, нажатие по которой снимает запрет"}]}]}]},{"inlineContent":[{"text":"При наследовании необходимо учитывать, что наполнение ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","isActive":true},{"type":"text","text":" контентом происходит в двух местах: в инициализаторе "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(frame:params:previewFrame:)"},{"text":" и в ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)","type":"reference"},{"text":". Последний метод вызывается, если плеер решает обновить состояние уже находящегося на экране ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(frame:params:previewFrame:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/actionButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/contentView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/messageLabel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/onUnlock","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/previewImageFrame","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/restriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/swapView(_:with:in:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/updateAppearance()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/willStartTransitioning()"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"abstract":[{"text":"Тип ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/restrictionview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/restrictionview"]}],"references":{"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/CoverViewType-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/CoverViewType-Implementations","abstract":[],"kind":"article","title":"CoverViewType Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/ovkit\/restrictionview\/coverviewtype-implementations"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/restriction":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"restriction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier","text":"VideoRestrictionType"}],"kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/restriction","role":"symbol","title":"restriction","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/restriction","abstract":[{"type":"text","text":"Модель "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"},{"type":"text","text":", которая отображается в данный момент."}]},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/init(coder:)":{"title":"init(coder:)","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/init(coder:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/onUnlock":{"title":"onUnlock","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/onunlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/onUnlock","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onUnlock","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"Вызывается при нажатии на кнопку разблокировки restriction, если она есть.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewType"}],"navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","url":"\/documentation\/ovkit\/coverviewtype","type":"topic","title":"CoverViewType","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/handleCoverWithParams(_:)":{"title":"handleCoverWithParams(_:)","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/handlecoverwithparams(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleCoverWithParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleCoverWithParams:"}],"abstract":[{"text":"Если ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":" может отрисовать ","type":"text"},{"type":"codeVoice","code":"ControlCoverType"},{"text":", нужно обновить view и вернуть ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Если не может — будет запрошена новая ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":" или подставлена стандартная.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/willStartTransitioning()":{"title":"willStartTransitioning()","url":"\/documentation\/ovkit\/restrictionview\/willstarttransitioning()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/willStartTransitioning()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willStartTransitioning","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"text":"willStartTransitioning","kind":"identifier"}],"abstract":[{"code":"CoverView","type":"codeVoice"},{"text":" начал перемещаться в другое место на другой ","type":"text"},{"type":"codeVoice","code":"PlayerView"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Здесь стоит скрыть UI элементы оставив только затемнение.","type":"text"},{"type":"text","text":" "},{"text":"Если не реализовать метод, ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" будет полностью скрыт перед перемещением."}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/coverControlsDelegate":{"kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/covercontrolsdelegate","navigatorTitle":[{"text":"coverControlsDelegate","kind":"identifier"}],"type":"topic","title":"coverControlsDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/coverControlsDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coverControlsDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","text":"CoverControlsDelegate"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"Делегат ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":". Устанавливать не нужно","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/actionButton":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/restrictionview\/actionbutton","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButton"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/actionButton","title":"actionButton"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView":{"kind":"symbol","url":"\/documentation\/ovkit\/restrictionview","navigatorTitle":[{"kind":"identifier","text":"RestrictionView"}],"type":"topic","title":"RestrictionView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RestrictionView"}],"role":"symbol","abstract":[{"type":"text","text":"Тип "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":", который показывается, если видео нельзя проиграть по каким-то причинам (приватность, удаление, неприятный контент, и т.п.)."}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/init(frame:params:previewFrame:)":{"title":"init(frame:params:previewFrame:)","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/init(frame:params:previewframe:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(frame:params:previewFrame:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams"},{"text":", ","kind":"text"},{"text":"previewFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Создание "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/titleLabel":{"title":"titleLabel","url":"\/documentation\/ovkit\/restrictionview\/titlelabel","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/titleLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleLabel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/contentView":{"title":"contentView","url":"\/documentation\/ovkit\/restrictionview\/contentview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/contentView","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"type":"topic","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","url":"\/documentation\/ovkit\/videorestrictiontype","role":"symbol","title":"VideoRestrictionType","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/layoutSubviews()":{"title":"layoutSubviews()","url":"\/documentation\/ovkit\/restrictionview\/layoutsubviews()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","url":"\/documentation\/ovkit\/coverviewparams","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"type":"topic","title":"CoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/messageLabel":{"title":"messageLabel","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/messagelabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/messageLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"messageLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"?","kind":"text"}],"type":"topic","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/didEndTransitioning()":{"title":"didEndTransitioning()","url":"\/documentation\/ovkit\/restrictionview\/didendtransitioning()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/didEndTransitioning()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didEndTransitioning"}],"abstract":[{"type":"text","text":"Плеер закончил переезд на новую "},{"type":"codeVoice","code":"PlayerView"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/swapView(_:with:in:)":{"title":"swapView(_:with:in:)","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/swapview(_:with:in:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/swapView(_:with:in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swapView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/previewImageFrame":{"title":"previewImageFrame","url":"\/documentation\/ovkit\/restrictionview\/previewimageframe","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/previewImageFrame","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewImageFrame"}],"abstract":[{"type":"text","text":"Информация о том, была ли загружена preview в момент показа "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","url":"\/documentation\/ovkit\/coverview","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"type":"topic","title":"CoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverView"}],"role":"symbol","abstract":[]},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionView/updateAppearance()":{"title":"updateAppearance()","kind":"symbol","url":"\/documentation\/ovkit\/restrictionview\/updateappearance()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/updateAppearance()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAppearance","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Обновление визуального состояния ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"RestrictionView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"RestrictionView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RestrictionView"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/previewImageFrame"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionView\/willStartTransitioning()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"],"kind":"relationships","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"RestrictionView","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","value":"OVKCoverViewType"},{"value":[{"text":"OVKCoverViewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1handleCoverWithParams(_:)\/title","value":"handleCoverWithParams:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1handleCoverWithParams(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1willStartTransitioning()\/title","value":"willStartTransitioning"},{"value":[{"text":"- ","kind":"text"},{"text":"willStartTransitioning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1willStartTransitioning()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1coverControlsDelegate\/title","value":"coverControlsDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1coverControlsDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"coverControlsDelegate"}]},{"value":"RestrictionView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/title"},{"value":[{"text":"RestrictionView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"value":"didEndTransitioning","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1didEndTransitioning()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1didEndTransitioning()\/fragments"},{"value":"previewImageFrame","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1previewImageFrame\/title"},{"value":[{"kind":"identifier","text":"previewImageFrame"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionView~1previewImageFrame\/fragments","op":"replace"}]}]}