{"variants":[{"paths":["\/documentation\/ovkit\/restrictionmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/restrictionmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"RestrictionManager","externalID":"c:@M@OVKit@objc(cs)OVKRestrictionManager","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionManager","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"RestrictionManager"}]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/isAllowedToPlay(_:userAllowed:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/unlockIfPossible(_:from:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/shared"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKRestrictionManager) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionManager","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager/unlockIfPossible(_:from:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unlockIfPossible:from:"}],"url":"\/documentation\/ovkit\/restrictionmanager\/unlockifpossible(_:from:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlockIfPossible"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/unlockIfPossible(_:from:)","abstract":[{"type":"text","text":"Попытка разблокировать видео."}],"title":"unlockIfPossible(_:from:)"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager/isAllowedToPlay(_:userAllowed:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/isAllowedToPlay(_:userAllowed:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/restrictionmanager\/isallowedtoplay(_:userallowed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllowedToPlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"Разрешено ли проигрывание "},{"type":"codeVoice","code":"video"},{"type":"text","text":" с учетом политики запрета."}],"title":"isAllowedToPlay(_:userAllowed:)","navigatorTitle":[{"kind":"identifier","text":"isAllowedToPlay:userAllowed:"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager/shared":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RestrictionManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/ovkit\/restrictionmanager\/shared","title":"shared","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/shared"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/OVKRestrictionManager/init":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/ovkit\/ovkrestrictionmanager\/init","abstract":[],"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager":{"navigatorTitle":[{"kind":"identifier","text":"RestrictionManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","url":"\/documentation\/ovkit\/restrictionmanager","role":"symbol","kind":"symbol","title":"RestrictionManager","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestrictionManager"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKRestrictionManager","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKRestrictionManager","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"OVKRestrictionManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/init","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/isAllowedToPlay(_:userAllowed:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/unlockIfPossible(_:from:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/shared"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKRestrictionManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"unlockIfPossible:from:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1unlockIfPossible(_:from:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"unlockIfPossible:from:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1unlockIfPossible(_:from:)\/fragments","op":"replace"},{"value":"isAllowedToPlay:userAllowed:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1isAllowedToPlay(_:userAllowed:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isAllowedToPlay:userAllowed:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1isAllowedToPlay(_:userAllowed:)\/fragments","op":"replace"},{"value":"shared","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1shared\/title","op":"replace"},{"value":[{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1shared\/fragments","op":"replace"},{"value":"OVKRestrictionManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/title","op":"replace"},{"value":[{"text":"OVKRestrictionManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/fragments","op":"replace"},{"value":[{"text":"OVKRestrictionManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/navigatorTitle","op":"replace"}]}]}