{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Определяет поведения плеера при смене output route.","type":"text"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships"}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RouteChangeStrategy","kind":"identifier"}],"externalID":"c:@M@OVKit@E@RouteChangeStrategy","role":"symbol","navigatorTitle":[{"text":"RouteChangeStrategy","kind":"identifier"}],"title":"RouteChangeStrategy"},"variants":[{"paths":["\/documentation\/ovkit\/routechangestrategy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/routechangestrategy"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/pause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/play","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/unknown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RouteChangeStrategy"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/unknown":{"abstract":[],"title":"RouteChangeStrategy.unknown","url":"\/documentation\/ovkit\/routechangestrategy\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/unknown","role":"symbol","navigatorTitle":[{"text":"RouteChangeStrategyUnknown","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/pause":{"title":"RouteChangeStrategy.pause","url":"\/documentation\/ovkit\/routechangestrategy\/pause","navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategyPause"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Происходит пауза в воспроизведении.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/pause"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"title":"RouteChangeStrategy","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteChangeStrategy"}],"abstract":[{"type":"text","text":"Определяет поведения плеера при смене output route."}],"navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategy"}],"url":"\/documentation\/ovkit\/routechangestrategy"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/play":{"title":"RouteChangeStrategy.play","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/play","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"}],"abstract":[{"type":"text","text":"Воспроизведение продолжается."}],"navigatorTitle":[{"kind":"identifier","text":"RouteChangeStrategyPlay"}],"url":"\/documentation\/ovkit\/routechangestrategy\/play"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/RawRepresentable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/ovkit\/routechangestrategy\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/Equatable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/ovkit\/routechangestrategy\/equatable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy/init(rawValue:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/init(rawValue:)","url":"\/documentation\/ovkit\/routechangestrategy\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"RouteChangeStrategy","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/pause","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/play","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy\/unknown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RouteChangeStrategy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"RouteChangeStrategyUnknown","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1unknown\/title","op":"replace"},{"value":[{"text":"RouteChangeStrategyUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1unknown\/fragments","op":"replace"},{"value":"RouteChangeStrategyPause","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1pause\/title","op":"replace"},{"value":[{"text":"RouteChangeStrategyPause","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1pause\/fragments","op":"replace"},{"value":"RouteChangeStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title","op":"replace"},{"value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle","value":[{"text":"RouteChangeStrategy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1play\/title","value":"RouteChangeStrategyPlay","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy~1play\/fragments","value":[{"kind":"identifier","text":"RouteChangeStrategyPlay"}],"op":"replace"}]}]}