{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)SeekPreviewCombinedView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewCombinedView"}],"navigatorTitle":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"roleHeading":"Class","title":"SeekPreviewCombinedView","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/closeBlock","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/extendedTimelineDefaultHeight","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/fakeTimelineView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/playBlock","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineScrolled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineStopped","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/visibleHeight"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateFullscreenThumbnails(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updatePrecisionTimeline(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateTimeAndChapters(timelineView:)"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview"]}],"references":{"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/layoutSubviews()":{"abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/layoutsubviews()","role":"symbol","title":"layoutSubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/layoutSubviews()","type":"topic","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"abstract":[],"kind":"symbol","title":"SeekPreviewCombinedView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewcombinedview","navigatorTitle":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/precisionTimelineStopped":{"abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/precisiontimelinestopped","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineStopped","title":"precisionTimelineStopped","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionTimelineStopped","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/closeBlock":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeBlock","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/closeBlock","kind":"symbol","title":"closeBlock","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/closeblock"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/visibleHeight":{"abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/visibleheight","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/visibleHeight","title":"visibleHeight","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibleHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/updateTimeAndChapters(timelineView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateTimeAndChapters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateTimeAndChapters(timelineView:)","kind":"symbol","title":"updateTimeAndChapters(timelineView:)","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/updatetimeandchapters(timelineview:)"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/init(coder:)":{"title":"init(coder:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(coder:)","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/init(coder:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/precisionTimelineScrolled":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionTimelineScrolled","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"precisionTimelineScrolled","type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/precisiontimelinescrolled","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineScrolled","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/updatePrecisionTimeline(_:)":{"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePrecisionTimeline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"updatePrecisionTimeline(_:)","type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/updateprecisiontimeline(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updatePrecisionTimeline(_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/playBlock":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playBlock","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"playBlock","type":"topic","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/playblock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/playBlock","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/init(controlsview:canshowpreviews:canextendtimeline:initialtimelineframe:)","title":"init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controlsView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canShowPreviews","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canExtendTimeline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialTimelineFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/extendedTimelineDefaultHeight":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/extendedtimelinedefaultheight","title":"extendedTimelineDefaultHeight","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/extendedTimelineDefaultHeight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendedTimelineDefaultHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/updateFullscreenThumbnails(time:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateFullscreenThumbnails","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/updatefullscreenthumbnails(time:)","title":"updateFullscreenThumbnails(time:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateFullscreenThumbnails(time:)"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/fakeTimelineView":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fakeTimelineView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier"}],"kind":"symbol","title":"fakeTimelineView","abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/faketimelineview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/fakeTimelineView","type":"topic"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SeekPreviewCombinedView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/layoutSubviews()"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title","value":"SeekPreviewCombinedView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments","value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}