{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/controlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isEnabled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isShowingPrecisionSeek"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/beginTracking(touch:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/continueTracking(touch:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/endTracking(touch:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/removeBehaviour()"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/seekpreviewbehaviorextended"]}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"role":"symbol","symbolKind":"class","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"externalID":"c:@M@OVKit@objc(cs)SeekPreviewBehaviorExtended","title":"SeekPreviewBehaviorExtended","roleHeading":"Class"},"references":{"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/ControlsBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsBehavior","type":"topic","abstract":[{"text":"Динамическое поведение контролов.","type":"text"}],"kind":"symbol","role":"symbol","title":"ControlsBehavior","url":"\/documentation\/ovkit\/controlsbehavior","navigatorTitle":[{"text":"ControlsBehavior","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ControlsBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/isActive":{"abstract":[{"type":"text","text":"Влияет ли поведение на внешний вид контролов в текущий момент."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/isactive","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isActive","type":"topic","kind":"symbol","role":"symbol","title":"isActive"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/isShowingPrecisionSeek":{"type":"topic","title":"isShowingPrecisionSeek","abstract":[{"text":"Показывается ли в данный момент точная перемотка.","type":"text"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/isshowingprecisionseek","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isShowingPrecisionSeek","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShowingPrecisionSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineUIControlDelegate":{"url":"\/documentation\/ovkit\/timelineuicontroldelegate","type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate","navigatorTitle":[{"text":"TimelineUIControlDelegate","kind":"identifier"}],"title":"TimelineUIControlDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineUIControlDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIGestureRecognizerDelegate","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/beginTracking(touch:)":{"role":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/begintracking(touch:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/beginTracking(touch:)","type":"topic","abstract":[],"title":"beginTracking(touch:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"title":"SeekPreviewBehaviorExtended","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)":{"abstract":[{"type":"text","text":"Создание поведения."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewAndExtendedTimelineAllowed"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layoutSetup"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedStartSeekPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedSeekPreviewToTime"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onNeedEndSeekPreview"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/init(timelineView:previewAndExtendedTimelineAllowed:layoutSetup:onNeedStartSeekPreview:onNeedSeekPreviewToTime:onNeedEndSeekPreview:)","kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/init(timelineview:previewandextendedtimelineallowed:layoutsetup:onneedstartseekpreview:onneedseekpreviewtotime:onneedendseekpreview:)"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/endTracking(touch:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/endTracking(touch:)","abstract":[],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/endtracking(touch:)","title":"endTracking(touch:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/continueTracking(touch:)":{"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/continuetracking(touch:)","title":"continueTracking(touch:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/continueTracking(touch:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"touch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/removeBehaviour()":{"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/removebehaviour()","title":"removeBehaviour()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeBehaviour"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/removeBehaviour()","abstract":[{"text":"Убрать поведение с контролов (без отключения самого поведения).","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/controlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/controlsView","type":"topic","abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/controlsview","kind":"symbol","title":"controlsView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended/isEnabled":{"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended\/isenabled","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended\/isEnabled","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Включено ли поведение."}],"title":"isEnabled","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SeekPreviewBehaviorExtended","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewBehaviorExtended"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SeekPreviewBehaviorExtended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments"},{"op":"replace","value":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle"}]}]}