{"variants":[{"paths":["\/documentation\/ovkit\/shoppableadsitemviewbadgestyled"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppableAdsItemViewBadgeStyled"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Discount"]}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled\/badgeStyle"],"anchor":"Instance-Properties"}],"metadata":{"symbolKind":"protocol","externalID":"s:5OVKit31ShoppableAdsItemViewBadgeStyledP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ShoppableAdsItemViewBadgeStyled","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"OVKit"}],"role":"symbol","title":"ShoppableAdsItemViewBadgeStyled","navigatorTitle":[{"text":"ShoppableAdsItemViewBadgeStyled","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"url":"\/documentation\/ovkit\/adsitembadge","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","title":"AdsItemBadge","navigatorTitle":[{"kind":"identifier","text":"AdsItemBadge"}],"abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdsItemBadge"}]},"doc://onevideo.OVKit/documentation/OVKit/Discount":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Discount","role":"symbol","abstract":[{"type":"text","text":"Представление скидки"}],"navigatorTitle":[{"kind":"identifier","text":"Discount"}],"url":"\/documentation\/ovkit\/discount","type":"topic","title":"Discount","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Discount"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ShoppableAdsItemViewBadgeStyled":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ShoppableAdsItemViewBadgeStyled"}],"url":"\/documentation\/ovkit\/shoppableadsitemviewbadgestyled","type":"topic","title":"ShoppableAdsItemViewBadgeStyled","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppableAdsItemViewBadgeStyled"}]},"doc://onevideo.OVKit/documentation/OVKit/ShoppableAdsItemViewBadgeStyled/badgeStyle":{"url":"\/documentation\/ovkit\/shoppableadsitemviewbadgestyled\/badgestyle","kind":"symbol","title":"badgeStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewBadgeStyled\/badgeStyle","abstract":[{"type":"text","text":"Стиль визуальной метки товара."}],"role":"symbol","type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdsItemBadge","text":"AdsItemBadge","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","text":"Style","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKAdsItemBadge","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title"},{"value":[{"kind":"identifier","text":"OVKAdsItemBadge"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments"},{"value":[{"kind":"identifier","text":"OVKAdsItemBadge"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle"}]}]}