{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init(aheadCount:duration:prefetchReached:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/aheadCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/prefetchReached"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/simpleprefetchstrategy"]},{"paths":["\/documentation\/ovkit\/simpleprefetchstrategy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKSimplePrefetchStrategy) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"title":"SimplePrefetchStrategy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SimplePrefetchStrategy","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy","symbolKind":"class","roleHeading":"Class"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/duration":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","navigatorTitle":[{"text":"duration","kind":"identifier"}],"title":"duration","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/duration","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/duration","abstract":[{"type":"text","text":"Длительность префетча."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"title":"SimplePrefetchStrategy","url":"\/documentation\/ovkit\/simpleprefetchstrategy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"type":"topic","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"title":"PrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"url":"\/documentation\/ovkit\/prefetchstrategy","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/init(aheadCount:duration:prefetchReached:)":{"navigatorTitle":[{"text":"initWithAheadCount:duration:prefetchReached:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"aheadCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"prefetchReached","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"init(aheadCount:duration:prefetchReached:)","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/init(aheadcount:duration:prefetchreached:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init(aheadCount:duration:prefetchReached:)","role":"symbol","abstract":[{"type":"text","text":"Создание стратегии."}]},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchCountAhead"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","abstract":[{"type":"text","text":"Получение количества видеозаписей для префетча."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/init()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init()","abstract":[{"text":"Создание стратегии с параметрами по умолчанию.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/aheadCount":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"aheadCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"aheadCount"}],"title":"aheadCount","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/aheadcount","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/aheadCount","abstract":[{"text":"Количество видеозаписей впереди для префетча.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchDurationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"abstract":[{"type":"text","text":"Получение длительности префетча для видеозаписи."}],"type":"topic","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/prefetchReached":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/prefetchReached","type":"topic","abstract":[{"type":"text","text":"Префетчить ли видео с нулевым индексом."}],"kind":"symbol","title":"prefetchReached","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/prefetchreached","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchReached","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"prefetchReached","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"OVKSimplePrefetchStrategy"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKSimplePrefetchStrategy"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/aheadCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/prefetchReached"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init(aheadCount:duration:prefetchReached:)"],"anchor":"Instance-Methods"}]},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"OVKSimplePrefetchStrategy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"value":"duration","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1duration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title","value":"OVKSimplePrefetchStrategy"},{"value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKSimplePrefetchStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","op":"replace","value":"OVKPrefetchStrategy"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init(aheadCount:duration:prefetchReached:)\/title","value":"initWithAheadCount:duration:prefetchReached:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init(aheadCount:duration:prefetchReached:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAheadCount:duration:prefetchReached:"}]},{"op":"replace","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments"},{"value":"init","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init()\/fragments","op":"replace"},{"value":"aheadCount","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1aheadCount\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1aheadCount\/fragments","value":[{"kind":"identifier","text":"aheadCount"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title","value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1prefetchReached\/title","value":"prefetchReached"},{"value":[{"text":"prefetchReached","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1prefetchReached\/fragments","op":"replace"}]}]}