{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/init(consolePrefix:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/statistics"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerProgress(_:bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerStart(bannerInfo:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adLoadRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adNoBanners(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adRequestBanner(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adSkip(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/emptyBuffer(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstBytes(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstFrame(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackError(_:recoverable:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playerReady(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/seek(method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoQuality(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/watchCoverage(fromTime:toTime:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"class","title":"StatsHandlerConsole","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerConsole","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"StatsHandlerConsole","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlerconsole"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlerconsole"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","interfaceLanguage":"swift"},"abstract":[{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" для отладки, который будет писать события статистики в консоль.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKStatsHandlerConsole) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerConsole"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adBannerProgress(_:bannerInfo:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/adbannerprogress(_:bannerinfo:)","role":"symbol","type":"topic","title":"adBannerProgress(_:bannerInfo:)","kind":"symbol","abstract":[{"text":"Пользователь досмотрел до определенных участков.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerProgress(_:bannerInfo:)","navigatorTitle":[{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerProgress","kind":"identifier"},{"kind":"text","text":"("},{"text":"StatsProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress"},{"text":", ","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","role":"article","abstract":[{"type":"text","text":"Сбор статистики воспроизведения видео."}],"url":"\/documentation\/ovkit\/statistics","type":"topic","title":"Статистика"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsHandlerConsole","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"text","text":"или переходах в PiP и fullscreen."}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector","type":"topic","title":"StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsCollector"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/firstBytes(time:connectionType:connectionReused:)":{"abstract":[{"text":"Событие получения первых данных из плеера.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstBytes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/firstbytes(time:connectiontype:connectionreused:)","title":"firstBytes(time:connectionType:connectionReused:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"firstBytesWithTime:connectionType:connectionReused:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstBytes(time:connectionType:connectionReused:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/init(consolePrefix:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/init(consoleprefix:)","role":"symbol","type":"topic","title":"init(consolePrefix:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/init(consolePrefix:)","abstract":[{"type":"text","text":"Создание хендлера."}],"navigatorTitle":[{"text":"initWithConsolePrefix:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"consolePrefix","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/watchCoverage(fromTime:toTime:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/watchcoverage(fromtime:totime:)","role":"symbol","type":"topic","title":"watchCoverage(fromTime:toTime:)","kind":"symbol","abstract":[{"type":"text","text":"Непрерывно просмотренные отрезки видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/watchCoverage(fromTime:toTime:)","navigatorTitle":[{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"watchCoverage"},{"kind":"text","text":"("},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/audioTrack(label:language:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/audiotrack(label:language:)","role":"symbol","type":"topic","title":"audioTrack(label:language:)","kind":"symbol","abstract":[{"text":"Пользователь сменил аудиодорожку.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/audioTrack(label:language:)","navigatorTitle":[{"text":"audioTrackWithLabel:language:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/start(fromTime:)":{"type":"topic","url":"\/documentation\/ovkit\/statshandlerconsole\/start(fromtime:)","title":"start(fromTime:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"startFromTime:"}],"abstract":[{"text":"Видео начало играть в плеере, не важно userInitiated или нет.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/start(fromTime:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/firstFrame(time:connectionType:connectionReused:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstFrame(time:connectionType:connectionReused:)","role":"symbol","abstract":[{"type":"text","text":"Событие получения первого кадра."}],"navigatorTitle":[{"text":"firstFrameWithTime:connectionType:connectionReused:","kind":"identifier"}],"url":"\/documentation\/ovkit\/statshandlerconsole\/firstframe(time:connectiontype:connectionreused:)","type":"topic","title":"firstFrame(time:connectionType:connectionReused:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/progressChanged(time:)":{"kind":"symbol","title":"progressChanged(time:)","url":"\/documentation\/ovkit\/statshandlerconsole\/progresschanged(time:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/progressChanged(time:)","navigatorTitle":[{"text":"progressChangedWithTime:","kind":"identifier"}],"abstract":[{"text":"Текущее время проигрывания изменилось.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/gravity(_:)":{"abstract":[{"type":"text","text":"Пользователь руками изменил gravity."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gravity"},{"kind":"text","text":"("},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/gravity(_:)","title":"gravity(_:)","kind":"symbol","navigatorTitle":[{"text":"gravity:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/gravity(_:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adFailed(reason:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/adfailed(reason:)","role":"symbol","type":"topic","title":"adFailed(reason:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adFailed(reason:)","abstract":[{"text":"Ошибка воспроизведения рекламы.","type":"text"}],"navigatorTitle":[{"text":"adFailedWithReason:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/playerReady(time:connectionType:connectionReused:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/playerready(time:connectiontype:connectionreused:)","role":"symbol","type":"topic","title":"playerReady(time:connectionType:connectionReused:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playerReady(time:connectionType:connectionReused:)","abstract":[{"text":"Плеер готов играть.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playerReadyWithTime:connectionType:connectionReused:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerReady","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/statistics":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/statistics","role":"symbol","abstract":[{"text":"Будет установлено после добавления в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"statistics","kind":"identifier"}],"url":"\/documentation\/ovkit\/statshandlerconsole\/statistics","type":"topic","title":"statistics","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statistics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsHandlerContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adBannerStart(bannerInfo:duration:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Запустился рекламный баннер.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerStart(bannerInfo:duration:)","url":"\/documentation\/ovkit\/statshandlerconsole\/adbannerstart(bannerinfo:duration:)","kind":"symbol","role":"symbol","title":"adBannerStart(bannerInfo:duration:)","navigatorTitle":[{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/playbackSpeed(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackSpeed(_:)","url":"\/documentation\/ovkit\/statshandlerconsole\/playbackspeed(_:)","title":"playbackSpeed(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSpeed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"playbackSpeed:"}],"abstract":[{"type":"text","text":"Пользователь изменил скорость воспроизведения видео."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/playbackError(_:recoverable:from:)":{"abstract":[{"type":"text","text":"Произошла ошибка воспроизведения."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recoverable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/playbackerror(_:recoverable:from:)","title":"playbackError(_:recoverable:from:)","kind":"symbol","navigatorTitle":[{"text":"playbackError:recoverable:from:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackError(_:recoverable:from:)"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/stop(currentTime:stallTime:)":{"kind":"symbol","title":"stop(currentTime:stallTime:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/stop(currentTime:stallTime:)","url":"\/documentation\/ovkit\/statshandlerconsole\/stop(currenttime:stalltime:)","navigatorTitle":[{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}],"abstract":[{"text":"Видео закончили смотреть.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stallTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/adstatshandler","title":"AdStatsHandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"abstract":[{"type":"text","text":"Принимает события, связанные с воспроизведением рекламы."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adLoadRequest()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adLoadRequest()","abstract":[{"type":"text","text":"Попросили рекламный плеер загрузить данные для instream video."}],"role":"symbol","type":"topic","kind":"symbol","title":"adLoadRequest()","url":"\/documentation\/ovkit\/statshandlerconsole\/adloadrequest()","navigatorTitle":[{"text":"adLoadRequest","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adLoadRequest","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/reachedEnd()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reachedEnd"},{"kind":"text","text":"()"}],"abstract":[{"text":"Видео было досмотрено до конца.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/reachedEnd()","url":"\/documentation\/ovkit\/statshandlerconsole\/reachedend()","role":"symbol","title":"reachedEnd()","navigatorTitle":[{"kind":"identifier","text":"reachedEnd"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adSkip(bannerInfo:)":{"kind":"symbol","title":"adSkip(bannerInfo:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adSkip(bannerInfo:)","url":"\/documentation\/ovkit\/statshandlerconsole\/adskip(bannerinfo:)","navigatorTitle":[{"kind":"identifier","text":"adSkipWithBannerInfo:"}],"abstract":[{"type":"text","text":"Пользователь нажал кнопку пропуска рекламы."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/didCloseFullscreen()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Произошел выход из полноэкранного режима."}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/statshandlerconsole\/didclosefullscreen()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didCloseFullscreen()","role":"symbol","title":"didCloseFullscreen()","navigatorTitle":[{"text":"didCloseFullscreen","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/failover(backupHost:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/failover(backuphost:)","role":"symbol","type":"topic","title":"failover(backupHost:)","kind":"symbol","abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/failover(backupHost:)","navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupHost","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/resume()":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/resume()","title":"resume()","url":"\/documentation\/ovkit\/statshandlerconsole\/resume()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Видео было снято с паузы пользователем."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resume","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/videoZoom()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoZoom"},{"kind":"text","text":"()"}],"abstract":[{"text":"Video zoom","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoZoom()","url":"\/documentation\/ovkit\/statshandlerconsole\/videozoom()","role":"symbol","title":"videoZoom()","navigatorTitle":[{"kind":"identifier","text":"videoZoom"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adRequestBanner(bannerInfo:)":{"kind":"symbol","title":"adRequestBanner(bannerInfo:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adRequestBanner(bannerInfo:)","url":"\/documentation\/ovkit\/statshandlerconsole\/adrequestbanner(bannerinfo:)","navigatorTitle":[{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}],"abstract":[{"type":"text","text":"Запрос на воспроизведение баннера к рекламному плееру."}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRequestBanner","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/emptyBuffer(time:connectionType:connectionReused:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"connectionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"text":"Плеер подгружал данные для дальнейшего воспроизведения.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/emptyBuffer(time:connectionType:connectionReused:)","url":"\/documentation\/ovkit\/statshandlerconsole\/emptybuffer(time:connectiontype:connectionreused:)","kind":"symbol","role":"symbol","title":"emptyBuffer(time:connectionType:connectionReused:)","navigatorTitle":[{"kind":"identifier","text":"emptyBufferWithTime:connectionType:connectionReused:"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/subtitles(_:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/subtitles(_:)","role":"symbol","type":"topic","title":"subtitles(_:)","kind":"symbol","abstract":[{"text":"Пользователь включил, отключил или изменил язык субтитров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/subtitles(_:)","navigatorTitle":[{"text":"subtitles:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/videoQuality(_:userInitiated:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoQuality(_:userInitiated:)","url":"\/documentation\/ovkit\/statshandlerconsole\/videoquality(_:userinitiated:)","title":"videoQuality(_:userInitiated:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"videoQuality:userInitiated:","kind":"identifier"}],"abstract":[{"text":"Изменилось качество проигрывания.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/adNoBanners(responseTime:)":{"url":"\/documentation\/ovkit\/statshandlerconsole\/adnobanners(responsetime:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adNoBanners(responseTime:)","title":"adNoBanners(responseTime:)","navigatorTitle":[{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"abstract":[{"type":"text","text":"Рекламный плеер не будет играть рекламу для данного видео."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adNoBanners"},{"kind":"text","text":"("},{"text":"responseTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","url":"\/documentation\/ovkit\/statshandler","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}],"kind":"symbol","title":"StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/pause(currentTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/pause(currentTime:)","url":"\/documentation\/ovkit\/statshandlerconsole\/pause(currenttime:)","title":"pause(currentTime:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pauseWithCurrentTime:","kind":"identifier"}],"abstract":[{"type":"text","text":"Пользователь нажал на паузу в плеере."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/didEnterFullscreen()":{"type":"topic","title":"didEnterFullscreen()","url":"\/documentation\/ovkit\/statshandlerconsole\/didenterfullscreen()","abstract":[{"type":"text","text":"Произошел переход в полноэкранный режим."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didEnterFullscreen()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didEnterFullscreen","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEnterFullscreen"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole/seek(method:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seek","kind":"identifier"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","text":"StatsSeekMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Пользователь перемотал видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/seek(method:)","url":"\/documentation\/ovkit\/statshandlerconsole\/seek(method:)","kind":"symbol","role":"symbol","title":"seek(method:)","navigatorTitle":[{"text":"seekWithMethod:","kind":"identifier"}]},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"OVKStatsHandlerConsole"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/statistics"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerProgress(_:bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adBannerStart(bannerInfo:duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adFailed(reason:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adLoadRequest()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adNoBanners(responseTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adRequestBanner(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/adSkip(bannerInfo:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/emptyBuffer(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstBytes(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/firstFrame(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/init(consolePrefix:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackError(_:recoverable:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/playerReady(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/seek(method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoQuality(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole\/watchCoverage(fromTime:toTime:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKStatsHandlerConsole","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"adBannerProgress:bannerInfo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerProgress(_:bannerInfo:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerProgress(_:bannerInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1firstBytes(time:connectionType:connectionReused:)\/title","value":"firstBytesWithTime:connectionType:connectionReused:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1firstBytes(time:connectionType:connectionReused:)\/fragments"},{"op":"replace","value":"initWithConsolePrefix:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1init(consolePrefix:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConsolePrefix:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1init(consolePrefix:)\/fragments"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"watchCoverageFromTime:toTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1watchCoverage(fromTime:toTime:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1watchCoverage(fromTime:toTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"watchCoverageFromTime:toTime:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1audioTrack(label:language:)\/title","value":"audioTrackWithLabel:language:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1audioTrack(label:language:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioTrackWithLabel:language:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1start(fromTime:)\/title","value":"startFromTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1start(fromTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startFromTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1firstFrame(time:connectionType:connectionReused:)\/title","value":"firstFrameWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1firstFrame(time:connectionType:connectionReused:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"firstFrameWithTime:connectionType:connectionReused:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1progressChanged(time:)\/title","value":"progressChangedWithTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1progressChanged(time:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"progressChangedWithTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1gravity(_:)\/title","value":"gravity:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1gravity(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gravity:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adFailed(reason:)\/title","value":"adFailedWithReason:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adFailed(reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adFailedWithReason:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playerReady(time:connectionType:connectionReused:)\/title","value":"playerReadyWithTime:connectionType:connectionReused:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playerReady(time:connectionType:connectionReused:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerReadyWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1statistics\/title","op":"replace","value":"statistics"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1statistics\/fragments","op":"replace","value":[{"kind":"identifier","text":"statistics"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerStart(bannerInfo:duration:)\/title","op":"replace","value":"adBannerStartWithBannerInfo:duration:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adBannerStart(bannerInfo:duration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playbackSpeed(_:)\/title","op":"replace","value":"playbackSpeed:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playbackSpeed(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playbackSpeed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playbackError(_:recoverable:from:)\/title","value":"playbackError:recoverable:from:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1playbackError(_:recoverable:from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playbackError:recoverable:from:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1stop(currentTime:stallTime:)\/title","value":"stopWithCurrentTime:stallTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1stop(currentTime:stallTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","value":"OVKAdStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adLoadRequest()\/title","value":"adLoadRequest"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adLoadRequest()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adLoadRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1reachedEnd()\/title","value":"reachedEnd"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1reachedEnd()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reachedEnd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adSkip(bannerInfo:)\/title","value":"adSkipWithBannerInfo:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adSkip(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didCloseFullscreen()\/title","value":"didCloseFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didCloseFullscreen()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCloseFullscreen"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1failover(backupHost:)\/title","value":"failoverWithBackupHost:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1failover(backupHost:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1resume()\/title","value":"resume"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1resume()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resume","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoZoom()\/title","value":"videoZoom"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoZoom()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoZoom"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adRequestBanner(bannerInfo:)\/title","value":"adRequestBannerWithBannerInfo:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adRequestBanner(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1emptyBuffer(time:connectionType:connectionReused:)\/title","value":"emptyBufferWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1emptyBuffer(time:connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"emptyBufferWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1subtitles(_:)\/title","value":"subtitles:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1subtitles(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subtitles:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoQuality(_:userInitiated:)\/title","value":"videoQuality:userInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1videoQuality(_:userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoQuality:userInitiated:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adNoBanners(responseTime:)\/title","value":"adNoBannersWithResponseTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1adNoBanners(responseTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adNoBannersWithResponseTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1pause(currentTime:)\/title","value":"pauseWithCurrentTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1pause(currentTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseWithCurrentTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didEnterFullscreen()\/title","value":"didEnterFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1didEnterFullscreen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1seek(method:)\/title","value":"seekWithMethod:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole~1seek(method:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekWithMethod:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}