{"metadata":{"roleHeading":"Class","title":"StatsContext","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}]},"abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"},"seeAlsoSections":[{"generated":true,"title":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"],"anchor":"Статистика"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKStatsContext) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/statscontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"generated":true,"title":"Structures","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct"],"anchor":"Structures"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioCodec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioLanguage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioOutput","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/autoplay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/bufferDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/clipsItemPosition","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/clipsSessionId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/currentTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadBitrate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/estimatedBandwidth","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/estimatedRtt","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/hdr","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInExternalPip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInPip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isLivePlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isOpenedInFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/liveLatency-swift.property","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/oneLogCustomParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/place","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackSpeed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playingURL","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/screencastType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/subtitlesLanguage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/totalDroppedFramesCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/totalRenderedFramesCount","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userCustomParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/video","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoCodec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/viewportSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/vsid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/watchCycleCount"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/generateVSID()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/playbackSpeed":{"title":"playbackSpeed","abstract":[{"type":"text","text":"Скорость воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackSpeed","navigatorTitle":[{"kind":"identifier","text":"playbackSpeed"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/playbackspeed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/liveLatency-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveLatency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12StatsContextC11LiveLatencyV","text":"LiveLatency"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.property","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/liveLatency-swift.property","role":"symbol","abstract":[{"text":"Данные о задержке потока воспроизведения до автора трансляции.","type":"text"}],"title":"liveLatency"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/userCustomParams":{"title":"userCustomParams","abstract":[{"type":"text","text":"Пользовательский набор параметров для использования в собственных реализациях "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":". По умолчанию пустой словарь."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userCustomParams","navigatorTitle":[{"kind":"identifier","text":"userCustomParams"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/usercustomparams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCustomParams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/videoQuality":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoQuality","abstract":[{"text":"Выбранное пользователем качество видео. Например, ","type":"text"},{"type":"codeVoice","code":"\"auto\""},{"type":"text","text":", "},{"type":"codeVoice","code":"\"480\""},{"type":"text","text":", "},{"type":"codeVoice","code":"\"720\""},{"text":" и т.д.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"videoQuality","kind":"symbol","url":"\/documentation\/ovkit\/statscontext\/videoquality","navigatorTitle":[{"kind":"identifier","text":"videoQuality"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/viewportSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewportSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/statscontext\/viewportsize","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/viewportSize","role":"symbol","abstract":[{"type":"text","text":"Размер, который занимает поверхность плеера на экране, в пикселях."}],"navigatorTitle":[{"kind":"identifier","text":"viewportSize"}],"title":"viewportSize"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isInExternalPip":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInExternalPip","abstract":[{"text":"Происходит ли воспроизведение в системном режиме Картинка в Картинке вне приложения.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInExternalPip"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext\/isinexternalpip","title":"isInExternalPip","kind":"symbol","navigatorTitle":[{"text":"isInExternalPip","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/volume":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/volume","title":"volume","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"volume","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext\/volume","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Громкость воспроизведения звука, когда он включен ("},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","isActive":true},{"type":"text","text":" == true)."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/downloadBitrate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Общий битрейт дорожек в "},{"type":"emphasis","inlineContent":[{"text":"bps","type":"text"}]},{"type":"text","text":", которые в данный момент выбраны для загрузки."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadBitrate","url":"\/documentation\/ovkit\/statscontext\/downloadbitrate","title":"downloadBitrate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/gravity":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/gravity","title":"gravity","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"gravity","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext\/gravity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Режим отображения картинки."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext","kind":"symbol","title":"StatsContext","navigatorTitle":[{"kind":"identifier","text":"StatsContext"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/clipsItemPosition":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clipsItemPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/statscontext\/clipsitemposition","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/clipsItemPosition","role":"symbol","abstract":[{"type":"text","text":"Clip Item Position"}],"title":"clipsItemPosition"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/userQuality":{"title":"userQuality","abstract":[{"text":"Качество, выбранное пользователем в UI.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userQuality","navigatorTitle":[{"kind":"identifier","text":"userQuality"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/userquality","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/estimatedRtt":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/estimatedRtt","title":"estimatedRtt","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/estimatedrtt","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"estimatedRtt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Приблизительная оценка RTT."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isInPip":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInPip","abstract":[{"type":"text","text":"Происходит ли воспроизведение в режиме Картинка в Картинке."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext\/isinpip","kind":"symbol","title":"isInPip","navigatorTitle":[{"kind":"identifier","text":"isInPip"}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/video":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"}],"title":"video","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/video","abstract":[{"type":"text","text":"Видео, которое проигрывается."}],"url":"\/documentation\/ovkit\/statscontext\/video","role":"symbol","navigatorTitle":[{"text":"video","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/hdr":{"url":"\/documentation\/ovkit\/statscontext\/hdr","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hdr"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hdr"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","kind":"symbol","title":"hdr","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/hdr","abstract":[{"text":"Выбрана ли для воспроизведения видео дорожка в HDR.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/totalRenderedFramesCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalRenderedFramesCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"totalRenderedFramesCount","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/totalRenderedFramesCount","abstract":[{"text":"Общее количество отрендеренных за сессию кадров видео.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/statscontext\/totalrenderedframescount","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/audioLanguage":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioLanguage","title":"audioLanguage","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"audioLanguage","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext\/audiolanguage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioLanguage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Языковой код выбранной аудио дорожки, если значение известно."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statshandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}],"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/soundOn":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","title":"soundOn","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"soundOn"}],"url":"\/documentation\/ovkit\/statscontext\/soundon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Включен ли звук в видео (изменяемое значение)."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/subtitlesLanguage":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitlesLanguage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"subtitlesLanguage","type":"topic","kind":"symbol","abstract":[{"text":"Языковой код выбранных в данный момент субтитров. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что субтитры отключены.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/subtitlesLanguage","url":"\/documentation\/ovkit\/statscontext\/subtitleslanguage","role":"symbol","navigatorTitle":[{"text":"subtitlesLanguage","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/watchCycleCount":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchCycleCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"watchCycleCount","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/watchCycleCount","kind":"symbol","abstract":[{"type":"text","text":"Количество циклов полного просмотра ролика."}],"url":"\/documentation\/ovkit\/statscontext\/watchcyclecount","role":"symbol"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/audioCodec":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"audioCodec","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/statscontext\/audiocodec","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioCodec","role":"symbol","abstract":[{"type":"text","text":"Выбранный в данный момент плеером аудио кодек."}],"title":"audioCodec"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/oneLogCustomParams":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"oneLogCustomParams","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"oneLogCustomParams"}],"type":"topic","abstract":[{"type":"text","text":"Пользовательский набор параметров для отправки в One Log статистику. По умолчанию пустой словарь."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/oneLogCustomParams","url":"\/documentation\/ovkit\/statscontext\/onelogcustomparams","title":"oneLogCustomParams"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct","abstract":[{"text":"Данные о задержке потока воспроизведения до автора трансляции.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveLatency"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct","kind":"symbol","title":"StatsContext.LiveLatency","navigatorTitle":[{"kind":"identifier","text":"LiveLatency"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/totalDroppedFramesCount":{"url":"\/documentation\/ovkit\/statscontext\/totaldroppedframescount","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDroppedFramesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","title":"totalDroppedFramesCount","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/totalDroppedFramesCount","abstract":[{"type":"text","text":"Общее количество дропнутых за сессию кадров видео."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isOpenedInFullscreen":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isOpenedInFullscreen","title":"isOpenedInFullscreen","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isOpenedInFullscreen"}],"url":"\/documentation\/ovkit\/statscontext\/isopenedinfullscreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOpenedInFullscreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Происходит ли воспроизведение в полноэкранном режиме."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/playingURL":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playingURL","type":"topic","url":"\/documentation\/ovkit\/statscontext\/playingurl","abstract":[{"type":"text","text":"Текущий проигрываемый URL."}],"title":"playingURL","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/vsid":{"url":"\/documentation\/ovkit\/statscontext\/vsid","role":"symbol","navigatorTitle":[{"text":"vsid","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vsid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"vsid","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/vsid","abstract":[{"type":"text","text":"Идентификатор сессии просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/bufferDuration":{"url":"\/documentation\/ovkit\/statscontext\/bufferduration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bufferDuration"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"type":"topic","kind":"symbol","title":"bufferDuration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/bufferDuration","abstract":[{"type":"text","text":"Размер буфера, из которого плеер проигрывает медиа."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/clipsSessionId":{"url":"\/documentation\/ovkit\/statscontext\/clipssessionid","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clipsSessionId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"clipsSessionId","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/clipsSessionId","abstract":[{"type":"text","text":"Clip Session Id"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isLivePlayback":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLivePlayback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Является ли воспроизведение действительно прямой трансляций."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isLivePlayback","url":"\/documentation\/ovkit\/statscontext\/isliveplayback","title":"isLivePlayback"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/videoCodec":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoCodec","abstract":[{"type":"text","text":"Выбранный в данный момент плеером видео кодек."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"videoCodec","kind":"symbol","url":"\/documentation\/ovkit\/statscontext\/videocodec"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isInBackground":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInBackground","abstract":[{"text":"Происходит ли воспроизведение в фоновом режиме.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInBackground","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext\/isinbackground","kind":"symbol","title":"isInBackground","navigatorTitle":[{"text":"isInBackground","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/fileFormat":{"title":"fileFormat","abstract":[{"text":"Текущий выбранный для проигрывания формат. Может не быть, если воспроизведение еще не началось.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/fileFormat","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/fileformat","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fileFormat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":"?"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/place":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/place","abstract":[{"type":"text","text":"Место в приложении, где воспроизводится видео."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"place","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"place","url":"\/documentation\/ovkit\/statscontext\/place","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"place"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"title":"StatsCollector","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscollector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/audioOutput":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioOutput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioOutputType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType"}],"role":"symbol","navigatorTitle":[{"text":"audioOutput","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioOutput","url":"\/documentation\/ovkit\/statscontext\/audiooutput","title":"audioOutput"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/adstatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","role":"symbol","abstract":[{"type":"text","text":"Принимает события, связанные с воспроизведением рекламы."}],"navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"title":"AdStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/screencastType":{"title":"screencastType","abstract":[{"text":"Тип внешнего устройства, на котором осуществляется проигрывание. Значение ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает, что внешних устройств не подключено.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/screencastType","navigatorTitle":[{"text":"screencastType","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/screencasttype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screencastType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/autoplay":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoplay"}],"type":"topic","abstract":[{"type":"text","text":"Началось ли проигрывание автоматически."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/autoplay","url":"\/documentation\/ovkit\/statscontext\/autoplay","title":"autoplay"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/estimatedBandwidth":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/estimatedBandwidth","type":"topic","url":"\/documentation\/ovkit\/statscontext\/estimatedbandwidth","abstract":[{"text":"Текущая измеренная плеером скорость скачивания в ","type":"text"},{"inlineContent":[{"text":"bps","type":"text"}],"type":"emphasis"},{"text":".","type":"text"}],"title":"estimatedBandwidth","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimatedBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/generateVSID()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateVSID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/generateVSID()","url":"\/documentation\/ovkit\/statscontext\/generatevsid()","title":"generateVSID()"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/currentTime":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/currentTime","title":"currentTime","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"currentTime","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext\/currenttime","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Текущее время проигрывания. Не актуально для трансляций."}]},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TimespentStatsHandler","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Принимает события начала и остановки просмотра видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","url":"\/documentation\/ovkit\/timespentstatshandler","title":"TimespentStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/downloadQuality":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"downloadQuality"}],"type":"topic","abstract":[{"type":"text","text":"Качество, выбранное для загрузки в данный момент (адаптивным алгоритмом, если Авто)."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadQuality","url":"\/documentation\/ovkit\/statscontext\/downloadquality","title":"downloadQuality"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/playbackQuality":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackQuality"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"playbackQuality","type":"topic","kind":"symbol","abstract":[{"text":"Воспроизводимое в данный момент разрешение.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackQuality","url":"\/documentation\/ovkit\/statscontext\/playbackquality","role":"symbol","navigatorTitle":[{"text":"playbackQuality","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKStatsContext","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioLanguage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioOutput","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/autoplay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/bufferDuration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/currentTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/hdr","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInExternalPip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInPip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isOpenedInFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/oneLogCustomParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/place","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackSpeed","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/screencastType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/subtitlesLanguage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userCustomParams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/video","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoQuality","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/viewportSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/vsid"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"],"anchor":"Статистика"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKStatsContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playbackSpeed","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackSpeed\/title"},{"value":[{"text":"playbackSpeed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackSpeed\/fragments"},{"value":"userCustomParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userCustomParams\/title"},{"value":[{"text":"userCustomParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userCustomParams\/fragments"},{"value":"videoQuality","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1videoQuality\/title"},{"value":[{"text":"videoQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1videoQuality\/fragments"},{"value":"viewportSize","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1viewportSize\/title"},{"value":[{"text":"viewportSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1viewportSize\/fragments"},{"value":"isInExternalPip","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInExternalPip\/title"},{"value":[{"kind":"identifier","text":"isInExternalPip"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInExternalPip\/fragments"},{"value":"volume","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1volume\/title"},{"value":[{"kind":"identifier","text":"volume"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1volume\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"gravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1gravity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"gravity"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1gravity\/fragments","op":"replace"},{"value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","op":"replace"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"},{"value":"userQuality","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userQuality\/title"},{"value":[{"text":"userQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userQuality\/fragments"},{"value":"isInPip","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInPip\/title"},{"value":[{"text":"isInPip","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInPip\/fragments"},{"value":"video","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1video\/title"},{"value":[{"text":"video","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1video\/fragments"},{"value":"hdr","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1hdr\/title"},{"value":[{"text":"hdr","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1hdr\/fragments"},{"value":"audioLanguage","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioLanguage\/title"},{"value":[{"text":"audioLanguage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioLanguage\/fragments"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle"},{"value":"OVKVideoStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"value":"soundOn","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1soundOn\/title"},{"value":[{"kind":"identifier","text":"soundOn"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1soundOn\/fragments"},{"value":"subtitlesLanguage","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1subtitlesLanguage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"subtitlesLanguage"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1subtitlesLanguage\/fragments","op":"replace"},{"value":"oneLogCustomParams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1oneLogCustomParams\/title","op":"replace"},{"value":[{"text":"oneLogCustomParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1oneLogCustomParams\/fragments","op":"replace"},{"value":"isOpenedInFullscreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isOpenedInFullscreen\/title","op":"replace"},{"value":[{"text":"isOpenedInFullscreen","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isOpenedInFullscreen\/fragments","op":"replace"},{"value":"vsid","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1vsid\/title","op":"replace"},{"value":[{"text":"vsid","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1vsid\/fragments","op":"replace"},{"value":"bufferDuration","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1bufferDuration\/title","op":"replace"},{"value":[{"text":"bufferDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1bufferDuration\/fragments","op":"replace"},{"value":"isInBackground","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInBackground\/title","op":"replace"},{"value":[{"text":"isInBackground","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInBackground\/fragments","op":"replace"},{"value":"place","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1place\/title","op":"replace"},{"value":[{"text":"place","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1place\/fragments","op":"replace"},{"value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","op":"replace"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace"},{"value":"audioOutput","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioOutput\/title","op":"replace"},{"value":[{"text":"audioOutput","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioOutput\/fragments","op":"replace"},{"value":"OVKAdStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKAdStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKAdStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","op":"replace"},{"value":"screencastType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1screencastType\/title","op":"replace"},{"value":[{"text":"screencastType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1screencastType\/fragments","op":"replace"},{"value":"autoplay","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1autoplay\/title","op":"replace"},{"value":[{"text":"autoplay","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1autoplay\/fragments","op":"replace"},{"value":"currentTime","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1currentTime\/title","op":"replace"},{"value":[{"text":"currentTime","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1currentTime\/fragments","op":"replace"},{"value":"OVKTimespentStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace"},{"value":"downloadQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1downloadQuality\/title","op":"replace"},{"value":[{"text":"downloadQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1downloadQuality\/fragments","op":"replace"},{"value":"playbackQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackQuality\/title","op":"replace"},{"value":[{"text":"playbackQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackQuality\/fragments","op":"replace"}]}]}