{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKStatsSeekMethod) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StatsSeekMethod","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@E@OVKStatsSeekMethod","title":"StatsSeekMethod","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StatsSeekMethod","kind":"identifier"}],"navigatorTitle":[{"text":"StatsSeekMethod","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/doubleTap","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/timeline"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/init(rawValue:)"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statsseekmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statsseekmethod"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/init(rawValue:)","url":"\/documentation\/ovkit\/statsseekmethod\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"abstract":[{"type":"text","text":"Способ перемотки видео, используется для статистики"}],"navigatorTitle":[{"text":"StatsSeekMethod","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsSeekMethod"}],"title":"StatsSeekMethod","role":"symbol","url":"\/documentation\/ovkit\/statsseekmethod","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ovkit\/statsseekmethod\/rawrepresentable-implementations","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/timeline":{"url":"\/documentation\/ovkit\/statsseekmethod\/timeline","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/timeline","title":"StatsSeekMethod.timeline","kind":"symbol","navigatorTitle":[{"text":"OVKStatsSeekMethodTimeline","kind":"identifier"}],"type":"topic","abstract":[{"text":"Способ перемотки протягиванием ползунка на временной шкале","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeline"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/Equatable-Implementations","kind":"article","url":"\/documentation\/ovkit\/statsseekmethod\/equatable-implementations"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod/doubleTap":{"type":"topic","title":"StatsSeekMethod.doubleTap","abstract":[{"type":"text","text":"Способ перемотки двойным нажатием на краях экрана"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/doubleTap","kind":"symbol","url":"\/documentation\/ovkit\/statsseekmethod\/doubletap","navigatorTitle":[{"text":"OVKStatsSeekMethodDoubleTap","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doubleTap"}]},"doc://onevideo.OVKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"OVKStatsSeekMethod","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/doubleTap","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod\/timeline"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OVKStatsSeekMethod","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"OVKStatsSeekMethod","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"kind":"identifier","text":"OVKStatsSeekMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1timeline\/title","value":"OVKStatsSeekMethodTimeline"},{"value":[{"text":"OVKStatsSeekMethodTimeline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1timeline\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1doubleTap\/title","value":"OVKStatsSeekMethodDoubleTap","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsSeekMethodDoubleTap"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod~1doubleTap\/fragments"}]}]}