{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statistics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statistics"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Article","role":"article","title":"Статистика"},"sections":[],"abstract":[{"text":"Сбор статистики воспроизведения видео.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics"},"kind":"article","seeAlsoSections":[{"title":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"generated":true,"anchor":"Концепты"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"После установки "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","isActive":true},{"text":" можно подписаться на события статистики, добавив реализацию протокола ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["playerView.statsCollector?.append(handler:)"],"type":"codeListing"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Набор хендлеров сбрасывается после каждой смены ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},{"text":".","type":"text"}]}],"name":"Warning","style":"warning","type":"aside"},{"inlineContent":[{"type":"text","text":"В качестве альтернативы можно использовать метод "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/makeStatHandlers(for:)","isActive":true},{"type":"text","text":" у делегата менеджера плееров. Он вызывается при каждой смене видео в любом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Для отладки статистики можно добавлять "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"},{"type":"text","text":", который будет выводить события статистики в консоль."}]},{"type":"heading","level":2,"anchor":"%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0-OneLog-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8","text":"Отправка OneLog статистики"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Порядок действий для поддержки отправки:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Получить ключи приложения для отправки статистики и для анонимной API сессии."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Подключить к проекту модуль "},{"type":"codeVoice","code":"OVKitStatistics"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Как можно раньше настроить сессию для отправки:","type":"text"}]}]}],"type":"orderedList"},{"code":["OKApiSession.setup(appKey: <key>, userId: <id>, tokenProvider: <provider>)"],"type":"codeListing","syntax":"swift"},{"type":"orderedList","start":4,"items":[{"content":[{"inlineContent":[{"text":"Добавить на ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" хендлер ","type":"text"},{"code":"StatsHandlerOneLog","type":"codeVoice"},{"type":"text","text":" любым из вышеперечисленных способов:"}],"type":"paragraph"}]}]},{"code":["let handler = StatsHandlerOneLog.makeHandlerForVideo(video)"],"type":"codeListing","syntax":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"title":"Воспроизведение в фоне","type":"topic","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","role":"article","abstract":[{"text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"url":"\/documentation\/ovkit\/backgroundplayback"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"url":"\/documentation\/ovkit\/prefetch","type":"topic","abstract":[{"type":"text","text":"Предзагрузка видео еще до начала воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","title":"Префетчер","kind":"article","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"url":"\/documentation\/ovkit\/controls","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","title":"Контролы плеера","type":"topic","role":"article","kind":"article","abstract":[{"text":"Кастомизация внешнего вида плеера.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"url":"\/documentation\/ovkit\/statshandlerconsole","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerConsole"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":" для отладки, который будет писать события статистики в консоль.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","kind":"symbol","title":"StatsHandlerConsole","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","url":"\/documentation\/ovkit\/extras","role":"article","kind":"article","abstract":[{"text":"Дополнительные возможности.","type":"text"}],"type":"topic","title":"Разное"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","url":"\/documentation\/ovkit\/plugins","role":"collectionGroup","kind":"article","abstract":[{"type":"text","text":"Динамически подключаемые модули для расширения функциональности."}],"type":"topic","title":"Плагины"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"url":"\/documentation\/ovkit\/transitions","type":"topic","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","title":"Переходы между плеерами","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/makeStatHandlers(for:)":{"url":"\/documentation\/ovkit\/playermanagerdelegate\/makestathandlers(for:)","navigatorTitle":[{"text":"makeStatHandlersFor:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeStatHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"StatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Метод для централизованной настройки статистики  в "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/makeStatHandlers(for:)","title":"makeStatHandlers(for:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"url":"\/documentation\/ovkit\/fullscreen","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","title":"Полноэкранный режим","type":"topic","role":"article","kind":"article","abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"title":"video","url":"\/documentation\/ovkit\/playerview\/video","navigatorTitle":[{"kind":"identifier","text":"video"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Модель видеозаписи для воспроизведения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"title":"Концепты","generated":true}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","value":"OVKStatsHandlerConsole","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerConsole"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1makeStatHandlers(for:)\/title","value":"makeStatHandlersFor:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1makeStatHandlers(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeStatHandlersFor:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title","value":"video","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","value":[{"kind":"identifier","text":"video"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"op":"replace"}]}]}