{"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKStatsHandlerContext) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandlerContext"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","title":"StatsHandlerContext","symbolKind":"class","roleHeading":"Class","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerContext"}],"navigatorTitle":[{"text":"StatsHandlerContext","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/collector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/context"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/statshandlercontext"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlercontext"]}],"sections":[],"abstract":[{"text":"Набор свойств, к которому может обращаться ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","url":"\/documentation\/ovkit\/statshandlercontext","role":"symbol","abstract":[{"type":"text","text":"Набор свойств, к которому может обращаться "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"StatsHandlerContext","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerContext"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandlerContext"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKStatsHandlerContext/collector":{"title":"collector","type":"topic","abstract":[{"type":"text","text":"Сборщик событий текущей сессии проигрывания."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsCollector","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"collector"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/collector","kind":"symbol","url":"\/documentation\/ovkit\/ovkstatshandlercontext\/collector"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"StatsCollector","kind":"identifier"}],"type":"topic","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Не привязан к ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"kind":"symbol","title":"StatsCollector","role":"symbol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/OVKStatsHandlerContext/context":{"title":"context","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","kind":"typeIdentifier","text":"StatsContext"}],"kind":"symbol","navigatorTitle":[{"text":"context","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/ovkstatshandlercontext\/context","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/context","abstract":[{"type":"text","text":"Контекст текущей сессии проигрывания."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","title":"StatsHandler","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":" после добавления нового ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKStatsHandlerContext","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKStatsHandlerContext","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/collector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/context"]}]},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKStatsHandlerContext","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"OVKStatsHandlerContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments","op":"replace","value":[{"text":"OVKStatsHandlerContext","kind":"identifier"}]},{"op":"replace","value":"collector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1collector\/title"},{"value":[{"kind":"identifier","text":"collector"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1collector\/fragments"},{"value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}]},{"value":"context","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1context\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1context\/fragments","value":[{"kind":"identifier","text":"context"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}