{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"]}],"metadata":{"symbolKind":"enum","role":"symbol","navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKStatsProgress","title":"StatsProgress","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsProgress"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/statsprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statsprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKStatsProgress) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsProgress"}],"platforms":["iOS"]}]}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a10s","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a3s","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r100p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r25p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r50p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r75p"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/a10s":{"kind":"symbol","title":"StatsProgress.a10s","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a10s","url":"\/documentation\/ovkit\/statsprogress\/a10s","navigatorTitle":[{"text":"OVKStatsProgressA10s","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"a10s","kind":"identifier"}]},"doc://onevideo.OVKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/RawRepresentable-Implementations":{"abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/statsprogress\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r50p":{"kind":"symbol","title":"StatsProgress.r50p","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r50p","url":"\/documentation\/ovkit\/statsprogress\/r50p","navigatorTitle":[{"kind":"identifier","text":"OVKStatsProgressR50p"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"r50p"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/a3s":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"a3s","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a3s","kind":"symbol","url":"\/documentation\/ovkit\/statsprogress\/a3s","role":"symbol","title":"StatsProgress.a3s","navigatorTitle":[{"text":"OVKStatsProgressA3s","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/init(rawValue:)","url":"\/documentation\/ovkit\/statsprogress\/init(rawvalue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/Equatable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/Equatable-Implementations","kind":"article","url":"\/documentation\/ovkit\/statsprogress\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r25p":{"kind":"symbol","title":"StatsProgress.r25p","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r25p","url":"\/documentation\/ovkit\/statsprogress\/r25p","navigatorTitle":[{"text":"OVKStatsProgressR25p","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r25p","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/statsprogress","kind":"symbol","title":"StatsProgress","navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsProgress","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r100p":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r100p","role":"symbol","abstract":[],"navigatorTitle":[{"text":"OVKStatsProgressR100p","kind":"identifier"}],"url":"\/documentation\/ovkit\/statsprogress\/r100p","type":"topic","title":"StatsProgress.r100p","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r100p","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress/r75p":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"r75p","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r75p","url":"\/documentation\/ovkit\/statsprogress\/r75p","kind":"symbol","role":"symbol","title":"StatsProgress.r75p","navigatorTitle":[{"text":"OVKStatsProgressR75p","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OVKStatsProgress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a10s","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/a3s","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r100p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r25p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r50p","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress\/r75p"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKStatsProgress"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a10s\/title","value":"OVKStatsProgressA10s"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a10s\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgressA10s"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r50p\/title","value":"OVKStatsProgressR50p"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r50p\/fragments","value":[{"text":"OVKStatsProgressR50p","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a3s\/title","value":"OVKStatsProgressA3s"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1a3s\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgressA3s"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r25p\/title","value":"OVKStatsProgressR25p"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r25p\/fragments","value":[{"kind":"identifier","text":"OVKStatsProgressR25p"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title","value":"OVKStatsProgress"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle","value":[{"text":"OVKStatsProgress","kind":"identifier"}]},{"value":"OVKStatsProgressR100p","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r100p\/title"},{"value":[{"kind":"identifier","text":"OVKStatsProgressR100p"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r100p\/fragments"},{"value":"OVKStatsProgressR75p","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r75p\/title"},{"value":[{"text":"OVKStatsProgressR75p","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress~1r75p\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}