{"abstract":[{"text":"Дорожка субтитров.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKSubtitlesOption) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/subtitlesoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/subtitlesoption"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/displayName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/isAuto","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/languageCode"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}],"symbolKind":"class","title":"SubtitlesOption","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Class","navigatorTitle":[{"text":"SubtitlesOption","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption/displayName":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/displayName","title":"displayName","type":"topic","url":"\/documentation\/ovkit\/subtitlesoption\/displayname","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displayName"}],"abstract":[{"type":"text","text":"Имя для отображения в меню выбора"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption/isAuto":{"abstract":[{"text":"Являются ли субтитры автосгенерированными","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isAuto"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/isAuto","kind":"symbol","title":"isAuto","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAuto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/ovkit\/subtitlesoption\/isauto"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"title":"SubtitlesOption","url":"\/documentation\/ovkit\/subtitlesoption","navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubtitlesOption"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Дорожка субтитров.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption/languageCode":{"url":"\/documentation\/ovkit\/subtitlesoption\/languagecode","navigatorTitle":[{"kind":"identifier","text":"languageCode"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"languageCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Ключ локализации, используется для идентификации","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/languageCode","kind":"symbol","title":"languageCode","role":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKSubtitlesOption","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/displayName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/isAuto","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption\/languageCode"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKSubtitlesOption"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"displayName","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1displayName\/title"},{"value":[{"text":"displayName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1displayName\/fragments"},{"value":"isAuto","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1isAuto\/title"},{"value":[{"text":"isAuto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1isAuto\/fragments"},{"value":"OVKSubtitlesOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title"},{"value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments"},{"value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/navigatorTitle"},{"value":"languageCode","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1languageCode\/title"},{"value":[{"text":"languageCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption~1languageCode\/fragments"}]}]}