{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/init(frame:style:showsProgress:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/intrinsicContentSize"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/sizeThatFits(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKSupplementaryAdView","symbolKind":"class","title":"SupplementaryAdView","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdView"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/supplementaryadview"]}],"kind":"symbol","abstract":[{"type":"text","text":"Представление для CTA-контрола рекламы."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKSupplementaryAdView) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView/sizeThatFits(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/sizeThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"sizeThatFits(_:)","type":"topic","url":"\/documentation\/ovkit\/supplementaryadview\/sizethatfits(_:)","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}]},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIUtilities.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView/intrinsicContentSize":{"title":"intrinsicContentSize","url":"\/documentation\/ovkit\/supplementaryadview\/intrinsiccontentsize","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem"},"doc://onevideo.OVKit/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView/layoutSubviews()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"title":"layoutSubviews()","type":"topic","url":"\/documentation\/ovkit\/supplementaryadview\/layoutsubviews()","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"type":"topic","navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"url":"\/documentation\/ovkit\/supplementaryadview","role":"symbol","kind":"symbol","title":"SupplementaryAdView"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView/init(frame:style:showsProgress:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/init(frame:style:showsProgress:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier","text":"SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsProgress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"title":"init(frame:style:showsProgress:)","url":"\/documentation\/ovkit\/supplementaryadview\/init(frame:style:showsprogress:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"OVKSupplementaryAdView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/intrinsicContentSize"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/sizeThatFits(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKSupplementaryAdView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1sizeThatFits(_:)\/title","op":"replace","value":"sizeThatFits:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1sizeThatFits(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sizeThatFits:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1intrinsicContentSize\/fragments","op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView~1layoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"value":"OVKSupplementaryAdView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","op":"replace"}]}]}