{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView"},"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/init(frame:style:showsProgress:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/autohideMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlMask","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsContainer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsVisible","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hidingEnabled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hoverGesture","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/intrinsicContentSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/shouldBeHiddenDuringTransition","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/shouldBeHiddenInitially","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/supplementaryView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/tapGesture"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didMoveToWindow()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdateGravity()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdatePreview(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/handlePlayerTick()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/handleSubtitlesCaptionUpdate()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hideControls(animated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/prepareForReuse()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/showControls(animated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/sizeThatFits(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/PlayerControlsViewProtocol-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/SupplementaryAdViewDelegate-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/supplementaryadcontrolsview"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Представление-обёртка для отображения дополнительных рекламных контролов.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"class","title":"SupplementaryAdControlsView","role":"symbol","roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)SupplementaryAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdControlsView"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewDelegate":{"url":"\/documentation\/ovkit\/supplementaryadviewdelegate","navigatorTitle":[{"text":"SupplementaryAdViewDelegate","kind":"identifier"}],"title":"SupplementaryAdViewDelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SupplementaryAdViewDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate","abstract":[{"text":"Протокол делегата для ","type":"text"},{"type":"codeVoice","code":"SupplementaryAdView"},{"type":"text","text":"."}],"type":"topic"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"HideableControls","kind":"identifier"}],"url":"\/documentation\/ovkit\/hideablecontrols","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","navigatorTitle":[{"kind":"identifier","text":"HideableControls"}],"title":"HideableControls","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/showControls(animated:)":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/showControls(animated:)","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/showcontrols(animated:)","title":"showControls(animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didMoveToWindow()":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didmovetowindow()","abstract":[],"role":"symbol","kind":"symbol","title":"didMoveToWindow()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didMoveToWindow()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"type":"topic"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlsVisible":{"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsvisible","abstract":[{"text":"Видны ли контролы на экране в данный момент.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlsVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsVisible","title":"controlsVisible"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"type":"topic","abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","title":"PlayerControlsViewProtocol","kind":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerControlsViewProtocol"}]},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/prepareForReuse()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/prepareforreuse()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/prepareForReuse()","title":"prepareForReuse()","type":"topic","kind":"symbol","abstract":[{"text":"Вызывается перед уходом View в реюз.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"url":"\/documentation\/ovkit\/controlmask","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ControlMask","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","abstract":[],"navigatorTitle":[{"text":"ControlMask","kind":"identifier"}],"title":"ControlMask","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/PlayerControlsViewProtocol-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/playercontrolsviewprotocol-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/PlayerControlsViewProtocol-Implementations","title":"PlayerControlsViewProtocol Implementations","type":"topic","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/SupplementaryAdViewDelegate-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/SupplementaryAdViewDelegate-Implementations","kind":"article","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/supplementaryadviewdelegate-implementations","title":"SupplementaryAdViewDelegate Implementations","type":"topic","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/hoverGesture":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/hovergesture","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hoverGesture","abstract":[{"type":"text","text":"Необходимо вернуть "},{"type":"codeVoice","code":"UIHoverGestureRecognizer"},{"text":"если нужна реакция на движение курсора.","type":"text"}],"kind":"symbol","title":"hoverGesture","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hoverGesture"},{"kind":"text","text":": "},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://onevideo.OVKit/s8CopyableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/hideControls(animated:)":{"kind":"symbol","title":"hideControls(animated:)","type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/hidecontrols(animated:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hideControls(animated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideControls"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlsDelegate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","text":"ControlsViewDelegate"},{"kind":"text","text":")?"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsDelegate","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlsdelegate","title":"controlsDelegate","kind":"symbol","abstract":[{"type":"text","text":"Делегат контролов. Устанавливать не нужно"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView","abstract":[{"type":"text","text":"Представление-обёртка для отображения дополнительных рекламных контролов."}],"kind":"symbol","title":"SupplementaryAdControlsView","navigatorTitle":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/intrinsicContentSize":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"title":"intrinsicContentSize","type":"topic","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/intrinsiccontentsize","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/intrinsicContentSize","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/supplementaryView":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/supplementaryView","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/supplementaryview","title":"supplementaryView","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supplementaryView"},{"kind":"text","text":": "},{"text":"SupplementaryAdView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)SupplementaryAdView"}],"abstract":[]},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/handleSubtitlesCaptionUpdate()":{"title":"handleSubtitlesCaptionUpdate()","abstract":[{"type":"text","text":"Вызывается когда изменилась активная строка субтитров."},{"text":" ","type":"text"},{"text":"В ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","isActive":true,"type":"reference"},{"text":" будет уже обновленный ","type":"text"},{"type":"codeVoice","code":"caption"},{"text":", или отсутствовать (нужно скрыть текст).","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/handleSubtitlesCaptionUpdate()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleSubtitlesCaptionUpdate"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/handlesubtitlescaptionupdate()","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/shouldBeHiddenDuringTransition":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/shouldbehiddenduringtransition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldBeHiddenDuringTransition"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/shouldBeHiddenDuringTransition","title":"shouldBeHiddenDuringTransition","role":"symbol","kind":"symbol","abstract":[{"text":"Должны ли контролы скрываться во время переходов между ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":". Рекомендуется возвращать "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/handlePlayerTick()":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePlayerTick"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/handlePlayerTick()","title":"handlePlayerTick()","abstract":[{"type":"text","text":"Вызывается периодически во время проигрывания видео."}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/handleplayertick()"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/hidingEnabled":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/hidingenabled","type":"topic","kind":"symbol","role":"symbol","title":"hidingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidingEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Работает ли в данный момент механизм скрытия контролов по тапу при наличии "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/tapGesture","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/hidingEnabled"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/shouldBeHiddenInitially":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/shouldBeHiddenInitially","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldBeHiddenInitially","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/shouldbehiddeninitially","title":"shouldBeHiddenInitially","abstract":[{"text":"Должны ли контролы быть скрыты при первом показе.","type":"text"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/tapGesture":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/tapgesture","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/tapGesture","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tapGesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer"},{"kind":"text","text":"?"}],"title":"tapGesture","abstract":[{"type":"text","text":"Не нужен, если нет показа\/скрытия контролов по тапу."}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlMask":{"kind":"symbol","type":"topic","title":"controlMask","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlmask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlMask","role":"symbol","abstract":[{"text":"Актуальная на данный момент контрольная маска.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"controlMask"},{"kind":"text","text":": "},{"text":"ControlMask","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/autohideMode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autohideMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HideableControlsMode","preciseIdentifier":"s:5OVKit20HideableControlsModeO"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/autohideMode","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/autohidemode","title":"autohideMode","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Режим автоскрытия контролов."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/controlsContainer":{"kind":"symbol","type":"topic","title":"controlsContainer","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/controlscontainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/controlsContainer","role":"symbol","abstract":[{"text":"Контейнер, в котором находятся контролы. Устанавливать не нужно","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsContainer","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:5OVKit21ControlsViewContainerP","text":"ControlsViewContainer","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://onevideo.OVKit/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/layoutSubviews()":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/layoutSubviews()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"type":"topic","title":"layoutSubviews()","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/layoutsubviews()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/init(frame:style:showsProgress:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SupplementaryAdViewStyle","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC"},{"text":", ","kind":"text"},{"text":"showsProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/init(frame:style:showsprogress:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/init(frame:style:showsProgress:)","role":"symbol","abstract":[],"title":"init(frame:style:showsProgress:)"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didUpdateGravity()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateGravity"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Режим масштабирования изменился.","type":"text"}],"kind":"symbol","title":"didUpdateGravity()","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didupdategravity()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdateGravity()"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/didUpdatePreview(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didUpdatePreview(_:)","type":"topic","title":"didUpdatePreview(_:)","url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/didupdatepreview(_:)","kind":"symbol","abstract":[{"type":"text","text":"Картинка превью загрузилась впервые или обновилась."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdatePreview"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdControlsView/sizeThatFits(_:)":{"url":"\/documentation\/ovkit\/supplementaryadcontrolsview\/sizethatfits(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/sizeThatFits(_:)","abstract":[],"kind":"symbol","title":"sizeThatFits(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sizeThatFits","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SupplementaryAdControlsView","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SupplementaryAdControlsView"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/intrinsicContentSize"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/didMoveToWindow()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdControlsView\/sizeThatFits(_:)"],"generated":true}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdControlsView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1didMoveToWindow()\/title","value":"didMoveToWindow"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1didMoveToWindow()\/fragments","op":"replace"},{"op":"replace","value":"SupplementaryAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/fragments","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView\/navigatorTitle","value":[{"text":"SupplementaryAdControlsView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"value":"sizeThatFits:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1sizeThatFits(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdControlsView~1sizeThatFits(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sizeThatFits:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}