{"metadata":{"title":"SupplementedAdControlsView","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)SupplementedAdControlsView","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementedAdControlsView"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/supplementedadcontrolsview"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/autohideMode","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlMask","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsContainer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsVisible","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hidingEnabled","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hoverGesture","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenDuringTransition","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenInitially","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/tapGesture"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didBeginTransitionAnimation(duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didFinishTransition()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didUpdateGravity()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didUpdatePreview(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handlePlayerTick()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handleSubtitlesCaptionUpdate()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hideControls(animated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/prepareForReuse()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/showControls(animated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/willBeginTransition(to:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/MyTargetInstreamAdVideoMotionViewDelegate-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/PlayerControlsViewProtocol-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"references":{"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView":{"title":"FullscreenSupplementedAdControlsView","url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы для Fullscreen."},{"type":"text","text":" "},{"type":"text","text":"В отличии от базовых "},{"code":"AdControlsView","type":"codeVoice"},{"type":"text","text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров."}],"navigatorTitle":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/controlMask":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlMask","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/controlmask","abstract":[{"type":"text","text":"Актуальная на данный момент контрольная маска."}],"title":"controlMask","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlMask"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit11ControlMaskC","kind":"typeIdentifier","text":"ControlMask"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/shouldBeHiddenDuringTransition":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenDuringTransition","title":"shouldBeHiddenDuringTransition","kind":"symbol","abstract":[{"text":"Должны ли контролы скрываться во время переходов между ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":". Рекомендуется возвращать ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenDuringTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/shouldbehiddenduringtransition"},"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"title":"ControlMask","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","url":"\/documentation\/ovkit\/controlmask","navigatorTitle":[{"kind":"identifier","text":"ControlMask"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlMask"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/hideControls(animated:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hideControls(animated:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"hideControls(animated:)","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/hidecontrols(animated:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/layoutSubviews()":{"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/layoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"kind":"symbol","title":"layoutSubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/layoutSubviews()","abstract":[],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/autohideMode":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/autohideMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autohideMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit20HideableControlsModeO","kind":"typeIdentifier","text":"HideableControlsMode"}],"kind":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/autohidemode","abstract":[{"type":"text","text":"Режим автоскрытия контролов."}],"title":"autohideMode","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/didBeginTransitionAnimation(duration:)":{"abstract":[{"text":"Начало анимации переноса плеера в другое ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didBeginTransitionAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"didBeginTransitionAnimation(duration:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didBeginTransitionAnimation(duration:)","kind":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/didbegintransitionanimation(duration:)","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"title":"PlayerView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable","title":"UIGestureRecognizerDelegate"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/hidingEnabled":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Работает ли в данный момент механизм скрытия контролов по тапу при наличии ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/tapGesture","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/hidingenabled","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hidingEnabled","title":"hidingEnabled"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/controlsDelegate":{"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/controlsdelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ControlsViewDelegate","preciseIdentifier":"s:5OVKit20ControlsViewDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"controlsDelegate","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsDelegate","kind":"symbol","abstract":[{"type":"text","text":"Делегат контролов. Устанавливать не нужно"}]},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/shouldBeHiddenInitially":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenInitially","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/shouldBeHiddenInitially","kind":"symbol","type":"topic","title":"shouldBeHiddenInitially","abstract":[{"type":"text","text":"Должны ли контролы быть скрыты при первом показе."}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/shouldbehiddeninitially","role":"symbol"},"doc://onevideo.OVKit/objc(cs)UIView":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/showControls(animated:)":{"abstract":[],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/showcontrols(animated:)","title":"showControls(animated:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/showControls(animated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"topic","title":"PlayerControlsViewProtocol","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/didUpdateGravity()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didUpdateGravity()","title":"didUpdateGravity()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateGravity"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[{"text":"Режим масштабирования изменился.","type":"text"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/didupdategravity()","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"type":"topic","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","kind":"symbol","abstract":[],"title":"SupplementedAdControlsView","url":"\/documentation\/ovkit\/supplementedadcontrolsview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/s8CopyableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransitionableControls","kind":"identifier"}],"title":"TransitionableControls","navigatorTitle":[{"text":"TransitionableControls","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","url":"\/documentation\/ovkit\/transitionablecontrols","abstract":[{"text":"Протокол для контролов, поддерживающих анимированный перенос между ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/tapGesture":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/tapGesture","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/tapgesture","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tapGesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"tapGesture","abstract":[{"text":"Не нужен, если нет показа\/скрытия контролов по тапу.","type":"text"}]},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/controlsContainer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsContainer","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/controlscontainer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Контейнер, в котором находятся контролы. Устанавливать не нужно"}],"title":"controlsContainer","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsContainer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ControlsViewContainer","preciseIdentifier":"s:5OVKit21ControlsViewContainerP","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/DiscoverSupplementedAdControlsView":{"navigatorTitle":[{"kind":"identifier","text":"DiscoverSupplementedAdControlsView"}],"type":"topic","title":"DiscoverSupplementedAdControlsView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscoverSupplementedAdControlsView"}],"kind":"symbol","abstract":[{"type":"text","text":"Рекламные контролы для отображения в рекомендациях."},{"type":"text","text":" "},{"type":"text","text":"В отличии от базовых рекламных контролов "},{"type":"codeVoice","code":"SupplementedAdControlsView"},{"type":"text","text":" таймлайн отодвинут от границы плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","url":"\/documentation\/ovkit\/discoversupplementedadcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionViewDelegate":{"title":"MyTargetInstreamAdVideoMotionViewDelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionViewDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionviewdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionViewDelegate","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/handlePlayerTick()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handlePlayerTick()","title":"handlePlayerTick()","abstract":[{"type":"text","text":"Вызывается периодически во время проигрывания видео."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePlayerTick","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/handleplayertick()","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HideableControls"}],"navigatorTitle":[{"kind":"identifier","text":"HideableControls"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","url":"\/documentation\/ovkit\/hideablecontrols","title":"HideableControls"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/MyTargetInstreamAdVideoMotionViewDelegate-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/MyTargetInstreamAdVideoMotionViewDelegate-Implementations","title":"MyTargetInstreamAdVideoMotionViewDelegate Implementations","kind":"article","abstract":[],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/mytargetinstreamadvideomotionviewdelegate-implementations","type":"topic","role":"collectionGroup"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/handleSubtitlesCaptionUpdate()":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/handleSubtitlesCaptionUpdate()","title":"handleSubtitlesCaptionUpdate()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleSubtitlesCaptionUpdate"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/handlesubtitlescaptionupdate()","abstract":[{"text":"Вызывается когда изменилась активная строка субтитров.","type":"text"},{"text":" ","type":"text"},{"text":"В ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask"},{"text":" будет уже обновленный ","type":"text"},{"code":"caption","type":"codeVoice"},{"text":", или отсутствовать (нужно скрыть текст).","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","role":"symbol","navigatorTitle":[{"text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldRecognizeSimultaneouslyWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/hoverGesture":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hoverGesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/hoverGesture","abstract":[{"type":"text","text":"Необходимо вернуть "},{"type":"codeVoice","code":"UIHoverGestureRecognizer"},{"type":"text","text":"если нужна реакция на движение курсора."}],"title":"hoverGesture","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/hovergesture","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/didFinishTransition()":{"title":"didFinishTransition()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didFinishTransition()","abstract":[{"type":"text","text":"Завершение переноса плеера в другое "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/didfinishtransition()","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishTransition"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/didUpdatePreview(_:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/didUpdatePreview(_:)","role":"symbol","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/didupdatepreview(_:)","abstract":[{"text":"Картинка превью загрузилась впервые или обновилась.","type":"text"}],"kind":"symbol","title":"didUpdatePreview(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdatePreview"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?)"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/willBeginTransition(to:)":{"role":"symbol","abstract":[{"type":"text","text":"Начало переноса плеера в другое "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","title":"willBeginTransition(to:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBeginTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/ovkit\/supplementedadcontrolsview\/willbegintransition(to:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/willBeginTransition(to:)"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/PlayerControlsViewProtocol-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/PlayerControlsViewProtocol-Implementations","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/playercontrolsviewprotocol-implementations","title":"PlayerControlsViewProtocol Implementations","kind":"article","role":"collectionGroup"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/controlsVisible":{"title":"controlsVisible","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/controlsvisible","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/controlsVisible","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Видны ли контролы на экране в данный момент."}]},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView/prepareForReuse()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/prepareForReuse()","abstract":[{"text":"Вызывается перед уходом View в реюз.","type":"text"}],"title":"prepareForReuse()","url":"\/documentation\/ovkit\/supplementedadcontrolsview\/prepareforreuse()","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SupplementedAdControlsView","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView\/layoutSubviews()"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)UIGestureRecognizerDelegate"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementedAdControlsView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"FullscreenSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/title","op":"replace"},{"value":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/navigatorTitle","op":"replace"},{"value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1layoutSubviews()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1layoutSubviews()\/fragments","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"SupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace"},{"value":"DiscoverSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DiscoverSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DiscoverSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/navigatorTitle","op":"replace"},{"value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/fragments","op":"replace"}]}]}