{"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:roundStyle:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/containerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/imageTransform","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/imageView"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/updateCurrentTime(_:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Enumerations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/RoundStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State"],"generated":true,"anchor":"Enumerations"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)ThumbnailTeaserView","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"symbolKind":"class","title":"ThumbnailTeaserView","role":"symbol","roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview"]}],"references":{"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/init(thumbnailProvider:roundStyle:)":{"title":"init(thumbnailProvider:roundStyle:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/thumbnailteaserview\/init(thumbnailprovider:roundstyle:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"roundStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoundStyle","preciseIdentifier":"s:5OVKit19ThumbnailTeaserViewC10RoundStyleO"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:roundStyle:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/imageView":{"title":"imageView","url":"\/documentation\/ovkit\/thumbnailteaserview\/imageview","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/imageView","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/RoundStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoundStyle","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/RoundStyle","navigatorTitle":[{"text":"RoundStyle","kind":"identifier"}],"title":"ThumbnailTeaserView.RoundStyle","kind":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview\/roundstyle","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/state","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"ThumbnailTeaserView.State"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"kind":"symbol","title":"ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/gravity":{"title":"gravity","url":"\/documentation\/ovkit\/thumbnailteaserview\/gravity","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/gravity","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/init(coder:)":{"abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(coder:)","title":"init(coder:)","url":"\/documentation\/ovkit\/thumbnailteaserview\/init(coder:)","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/updateCurrentTime(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/updateCurrentTime(_:)","role":"symbol","abstract":[],"kind":"symbol","title":"updateCurrentTime(_:)","url":"\/documentation\/ovkit\/thumbnailteaserview\/updatecurrenttime(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/imageTransform":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"imageTransform","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageTransform","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGAffineTransform","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/imagetransform","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/imageTransform"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/layoutSubviews()":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"abstract":[],"title":"layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/layoutsubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/layoutSubviews()"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/containerView":{"title":"containerView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/containerview","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/containerView"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ThumbnailTeaserView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(coder:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"}]}]}