{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/thumbnailcontainer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/thumbnailcontainer"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/init(frame:thumbnailProvider:chapterProvider:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateCurrentTime(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateRelativeXPosition(_:)"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/defaultInsets"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)ThumbnailContainer","title":"ThumbnailContainer","modules":[{"name":"OVKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThumbnailContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailContainer"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailContainer","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"ThumbnailView"},{"type":"text","text":" перемещается внутри контейнера и автоматически ресайзится, чтобы не обрезать свое содержимое."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Контейнер, который является границами показа "},{"type":"codeVoice","code":"ThumbnailView"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailContainer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer","abstract":[{"text":"Контейнер, который является границами показа ","type":"text"},{"code":"ThumbnailView","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailcontainer","navigatorTitle":[{"kind":"identifier","text":"ThumbnailContainer"}],"title":"ThumbnailContainer","type":"topic","role":"symbol"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/init(frame:thumbnailProvider:chapterProvider:)":{"url":"\/documentation\/ovkit\/thumbnailcontainer\/init(frame:thumbnailprovider:chapterprovider:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/init(frame:thumbnailProvider:chapterProvider:)","role":"symbol","abstract":[],"title":"init(frame:thumbnailProvider:chapterProvider:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider"},{"text":", ","kind":"text"},{"text":"chapterProvider","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/updateCurrentTime(_:)":{"type":"topic","title":"updateCurrentTime(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateCurrentTime(_:)","url":"\/documentation\/ovkit\/thumbnailcontainer\/updatecurrenttime(_:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/updateRelativeXPosition(_:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/updateRelativeXPosition(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRelativeXPosition"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/thumbnailcontainer\/updaterelativexposition(_:)","title":"updateRelativeXPosition(_:)","role":"symbol","abstract":[{"text":"Обновление горизонтального положения ","type":"text"},{"code":"ThumbnailView","type":"codeVoice"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView","title":"UIView"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/defaultInsets":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/defaultInsets","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/thumbnailcontainer\/defaultinsets","title":"defaultInsets","role":"symbol","abstract":[{"type":"text","text":"Стандартные инсеты для показа контейнера."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailContainer/layoutSubviews()":{"type":"topic","title":"layoutSubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/layoutSubviews()","url":"\/documentation\/ovkit\/thumbnailcontainer\/layoutsubviews()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ThumbnailContainer","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"ThumbnailContainer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailContainer"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailContainer\/layoutSubviews()"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ThumbnailContainer","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/title","value":"ThumbnailContainer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/fragments","value":[{"text":"ThumbnailContainer","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ThumbnailContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer\/navigatorTitle","op":"replace"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer~1layoutSubviews()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailContainer~1layoutSubviews()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}