{"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","title":"ThumbnailProviderThumbnail","navigatorTitle":[{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Описание изображения для thumbnail."}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/contentRect","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/image"],"title":"Instance Properties"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/thumbnailproviderthumbnail"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKThumbnailProviderThumbnail) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProviderThumbnail":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProviderThumbnail","title":"ThumbnailProviderThumbnail","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThumbnailProviderThumbnail","kind":"identifier"}],"url":"\/documentation\/ovkit\/thumbnailproviderthumbnail","navigatorTitle":[{"kind":"identifier","text":"ThumbnailProviderThumbnail"}],"role":"symbol","abstract":[{"text":"Описание изображения для thumbnail.","type":"text"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKThumbnailProviderThumbnail/image":{"title":"image","kind":"symbol","url":"\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/image","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/image","type":"topic","abstract":[{"text":"Изображение со множеством кадров.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/OVKThumbnailProviderThumbnail/contentRect":{"abstract":[{"type":"text","text":"Границы нужного кадра. Необходимо установить в свойство layer.contentsRect у объекта "},{"type":"codeVoice","code":"UIImageView"},{"text":", показывающего кадр.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkthumbnailproviderthumbnail\/contentrect","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"contentRect","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/contentRect","kind":"symbol","title":"contentRect"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKThumbnailProviderThumbnail"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKThumbnailProviderThumbnail"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKThumbnailProviderThumbnail"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/contentRect","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKThumbnailProviderThumbnail\/image"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/title","value":"OVKThumbnailProviderThumbnail"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProviderThumbnail\/fragments","op":"replace","value":[{"text":"OVKThumbnailProviderThumbnail","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1image\/title","value":"image"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1image\/fragments"},{"value":"contentRect","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1contentRect\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKThumbnailProviderThumbnail~1contentRect\/fragments","value":[{"text":"contentRect","kind":"identifier"}]}]}]}