{"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/canGetImages","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/duration","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/videoSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:loadAllThumbnails:handler:)"]},{"title":"Enumerations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult"]}],"abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKThumbnailProvider) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Изображения загружаются из сети и кэшируются до получения "},{"type":"codeVoice","code":"memory warning"},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/thumbnailprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/thumbnailprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ThumbnailProvider"}],"modules":[{"name":"OVKit"}],"title":"ThumbnailProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThumbnailProvider","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"role":"symbol","kind":"symbol","type":"topic","title":"ThumbnailProvider","url":"\/documentation\/ovkit\/thumbnailprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/canGetImages":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/canGetImages","url":"\/documentation\/ovkit\/thumbnailprovider\/cangetimages","role":"symbol","abstract":[{"text":"Может ли в данный момент времени осуществляться получение изображений.","type":"text"}],"type":"topic","title":"canGetImages","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canGetImages"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/duration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/duration","url":"\/documentation\/ovkit\/thumbnailprovider\/duration","role":"symbol","abstract":[{"type":"text","text":"Длительность видео."}],"type":"topic","title":"duration","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/getThumbnail(for:completion:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:completion:)","url":"\/documentation\/ovkit\/thumbnailprovider\/getthumbnail(for:completion:)","role":"symbol","abstract":[{"text":"Получение thumbnail.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getThumbnailFor:completion:"}],"type":"topic","title":"getThumbnail(for:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getThumbnail"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail","text":"ThumbnailProviderThumbnail"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/FetchResult":{"title":"ThumbnailProvider.FetchResult","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/FetchResult","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FetchResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Результат получения thumbnail."}],"navigatorTitle":[{"kind":"identifier","text":"FetchResult"}],"url":"\/documentation\/ovkit\/thumbnailprovider\/fetchresult","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/getThumbnail(for:loadAllThumbnails:handler:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:loadAllThumbnails:handler:)","url":"\/documentation\/ovkit\/thumbnailprovider\/getthumbnail(for:loadallthumbnails:handler:)","role":"symbol","abstract":[{"type":"text","text":"Получение thumbnail."}],"type":"topic","title":"getThumbnail(for:loadAllThumbnails:handler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getThumbnail"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"loadAllThumbnails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit17ThumbnailProviderC11FetchResultO","text":"FetchResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider/videoSize":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/videoSize","url":"\/documentation\/ovkit\/thumbnailprovider\/videosize","role":"symbol","abstract":[{"text":"Размер видео.","type":"text"}],"type":"topic","title":"videoSize","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"kind":"symbol"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"OVKThumbnailProvider","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider\/getThumbnail(for:completion:)"],"title":"Instance Methods"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"OVKThumbnailProvider","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider","op":"replace"},{"op":"replace","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments"},{"value":"getThumbnailFor:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider~1getThumbnail(for:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider~1getThumbnail(for:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getThumbnailFor:completion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}