{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineView"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Как наследник "},{"type":"codeVoice","code":"UIControl"},{"type":"text","text":" может посылать "},{"type":"codeVoice","code":"Action"},{"type":"text","text":" после взаимодействия пользователя:"}],"type":"paragraph"},{"inlineContent":[{"code":"UIControl.Event.valueChanged","type":"codeVoice"},{"text":" - пользователь закончил перематывать. ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/currentTime","type":"reference"},{"text":" изменилось, нужно сказать плееру перемотать.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"code":"UIControl.Event.editingDidBegin","type":"codeVoice"},{"type":"text","text":" - пользователь начал перематывать (тащить ползунок)."}],"type":"paragraph"},{"inlineContent":[{"type":"codeVoice","code":"UIControl.Event.editingDidEnd"},{"text":" - пользователь закончил перематывать (тащить ползунок).","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"codeVoice","code":"UIControl.Event.editingChanged"},{"text":" - ивент периодически посылается во время перемотки перетаскиванием.","type":"text"}],"type":"paragraph"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIControl"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalTrackable","doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"TimelineView","externalID":"c:@M@OVKit@objc(cs)TimelineView","roleHeading":"Class"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelineview"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/init(frame:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityValue","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/animatesProgress","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/currentTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/defaultThumbSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/delegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/frame","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isAnyTrackingActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isExternalTracking","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isLiveAppearance","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/maxSeekTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/preloadTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/relativeTracking","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/rewindedLiveAppearanceProgressColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/seekTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbCenter","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/trackingThumbSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/verticalExtendedInsets"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityDecrement()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityIncrement()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/beginTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/cancelTracking(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/continueTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/copyStateTo(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/endExternalUpdate()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/endTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/gestureRecognizerShouldBegin(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/handleExternalUpdate(to:useLargeThumb:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/hideAndContinueTracking()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/point(inside:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/update(progress:duration:preload:timeCodes:animated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateCurrentTimeCode(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateTimeCodes(_:)"],"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/kThumbSizeNormal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/kThumbSizeSmall"],"anchor":"Type-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/ExternalTrackable-Implementations"],"anchor":"Default-Implementations"}],"references":{"doc://onevideo.OVKit/s8SendableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/isAnyTrackingActive":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/timelineview\/isanytrackingactive","title":"isAnyTrackingActive","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnyTrackingActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isAnyTrackingActive","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/point(inside:with:)":{"type":"topic","title":"point(inside:with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/point(inside:with:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"point"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inside"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pointInside:withEvent:"}],"url":"\/documentation\/ovkit\/timelineview\/point(inside:with:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/trackingThumbSize":{"url":"\/documentation\/ovkit\/timelineview\/trackingthumbsize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackingThumbSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"type":"topic","title":"trackingThumbSize","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/trackingThumbSize","abstract":[{"text":"Размер ползунка в состоянии перемотки.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/handleExternalUpdate(to:useLargeThumb:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/handleExternalUpdate(to:useLargeThumb:)","url":"\/documentation\/ovkit\/timelineview\/handleexternalupdate(to:uselargethumb:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleExternalUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"useLargeThumb","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"text":"Обновление состояния таймлайна снаружи.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"handleExternalUpdate(to:useLargeThumb:)"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/init(frame:)":{"role":"symbol","title":"init(frame:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/init(frame:)","url":"\/documentation\/ovkit\/timelineview\/init(frame:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/gestureRecognizerShouldBegin(_:)":{"navigatorTitle":[{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/gestureRecognizerShouldBegin(_:)","role":"symbol","title":"gestureRecognizerShouldBegin(_:)","url":"\/documentation\/ovkit\/timelineview\/gesturerecognizershouldbegin(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ExternalTrackable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExternalTrackable","kind":"identifier"}],"kind":"symbol","title":"ExternalTrackable","url":"\/documentation\/ovkit\/externaltrackable","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalTrackable","abstract":[{"text":"Позволяет выполнять tracking как в ","type":"text"},{"type":"codeVoice","code":"UIControl"},{"text":", но по командам извне.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"ExternalTrackable","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/preloadTime":{"kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/preloadtime","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Для обычных видео: количество секунд предзагрузки. Для трансляций не актуально."}],"title":"preloadTime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/preloadTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preloadTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/isExternalTracking":{"abstract":[],"title":"isExternalTracking","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExternalTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/timelineview\/isexternaltracking","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isExternalTracking"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/currentTime":{"abstract":[{"type":"text","text":"Для обычных видео: текущее время воспроизведения в секундах. Для трансляций: количество секунд, на сколько отмотал пользователь."}],"kind":"symbol","type":"topic","title":"currentTime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/currentTime","url":"\/documentation\/ovkit\/timelineview\/currenttime","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityValue":{"title":"accessibilityValue","role":"symbol","url":"\/documentation\/ovkit\/timelineview\/accessibilityvalue","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityValue"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/beginTracking(_:with:)":{"title":"beginTracking(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginTracking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/begintracking(_:with:)","navigatorTitle":[{"kind":"identifier","text":"beginTrackingWithTouch:withEvent:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/beginTracking(_:with:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/durationTime":{"type":"topic","abstract":[{"type":"text","text":"Для обычных видео: длительность видео в секундах. Для трансляций: время, на которое можно перемотать."}],"title":"durationTime","url":"\/documentation\/ovkit\/timelineview\/durationtime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/isLiveAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isLiveAppearance","role":"symbol","kind":"symbol","title":"isLiveAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLiveAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/timelineview\/isliveappearance","abstract":[{"text":"Свойство, влияющее на цвет полосы прогресса.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/objc(pl)UIContextMenuInteractionDelegate":{"title":"UIKit.UIContextMenuInteractionDelegate","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIContextMenuInteractionDelegate"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/cancelTracking(with:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelTrackingWithEvent:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/cancelTracking(with:)","abstract":[],"title":"cancelTracking(with:)","url":"\/documentation\/ovkit\/timelineview\/canceltracking(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/relativeTracking":{"title":"relativeTracking","abstract":[{"text":"Если активировать, то перемотку можно будет выполнять свайпом по любому месту таймлайна.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/relativeTracking","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeTracking","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/ovkit\/timelineview\/relativetracking"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/frame":{"abstract":[],"type":"topic","title":"frame","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"frame","kind":"identifier"}],"url":"\/documentation\/ovkit\/timelineview\/frame","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/frame","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineView"}],"abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}],"url":"\/documentation\/ovkit\/timelineview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","title":"TimelineView","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/update(progress:duration:preload:timeCodes:animated:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/update(progress:duration:preload:timeCodes:animated:)","role":"symbol","abstract":[{"type":"text","text":"Обновление значений таймлайна."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeCodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/timelineview\/update(progress:duration:preload:timecodes:animated:)","title":"update(progress:duration:preload:timeCodes:animated:)"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/kThumbSizeNormal":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kThumbSizeNormal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/kthumbsizenormal","abstract":[],"title":"kThumbSizeNormal","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/kThumbSizeNormal"},"doc://onevideo.OVKit/s7CVarArgP":{"identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/updateCurrentTimeCode(_:)":{"abstract":[{"type":"text","text":"Обновление текущей подсвеченной главы."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCurrentTimeCode"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateCurrentTimeCode(_:)","title":"updateCurrentTimeCode(_:)","url":"\/documentation\/ovkit\/timelineview\/updatecurrenttimecode(_:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/isHidden":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isHidden","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/timelineview\/ishidden","title":"isHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/endTracking(_:with:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/endTracking(_:with:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"endTrackingWithTouch:withEvent:"}],"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/timelineview\/endtracking(_:with:)","title":"endTracking(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTracking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}]},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/animatesProgress":{"abstract":[{"type":"text","text":"Активна ли анимация при ползунка при воспроизведении."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatesProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/timelineview\/animatesprogress","title":"animatesProgress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/animatesProgress","type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/updateTimeCodes(_:)":{"abstract":[{"type":"text","text":"Обновление списка глав."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTimeCodes"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/ovkit\/timelineview\/updatetimecodes(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateTimeCodes(_:)","type":"topic","title":"updateTimeCodes(_:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityIncrement()":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityIncrement"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityIncrement()","kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/accessibilityincrement()","title":"accessibilityIncrement()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityIncrement"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/kThumbSizeSmall":{"type":"topic","url":"\/documentation\/ovkit\/timelineview\/kthumbsizesmall","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/kThumbSizeSmall","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kThumbSizeSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"kThumbSizeSmall","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/thumbCenter":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbCenter","role":"symbol","url":"\/documentation\/ovkit\/timelineview\/thumbcenter","abstract":[{"text":"Точка, в которой находится центр ползунка. В координатной системе ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"reference"},{"text":".","type":"text"}],"title":"thumbCenter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/ExternalTrackable-Implementations":{"kind":"article","url":"\/documentation\/ovkit\/timelineview\/externaltrackable-implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/ExternalTrackable-Implementations","role":"collectionGroup","type":"topic","title":"ExternalTrackable Implementations"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/maxSeekTime":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/maxSeekTime","url":"\/documentation\/ovkit\/timelineview\/maxseektime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSeekTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?"}],"abstract":[{"text":"Время в секундах, до которого может перемотать пользователь.","type":"text"},{"text":" ","type":"text"},{"text":"Если текущее время ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/currentTime"},{"text":" больше, то ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/maxSeekTime"},{"text":" игнорируется.","type":"text"}],"title":"maxSeekTime","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/hideAndContinueTracking()":{"type":"topic","url":"\/documentation\/ovkit\/timelineview\/hideandcontinuetracking()","role":"symbol","title":"hideAndContinueTracking()","kind":"symbol","abstract":[{"text":"Скрытие таймлайна без прерывания трекинга перемещения.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideAndContinueTracking"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/hideAndContinueTracking()"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(cs)UIControl":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIControl","title":"UIControl"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/defaultThumbSize":{"abstract":[{"type":"text","text":"Размер ползунка в обычном состоянии."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/defaultThumbSize","kind":"symbol","title":"defaultThumbSize","url":"\/documentation\/ovkit\/timelineview\/defaultthumbsize","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThumbSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/verticalExtendedInsets":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/verticalExtendedInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalExtendedInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?"}],"title":"verticalExtendedInsets","abstract":[{"type":"text","text":"Дополнительный отступ по вертикали, увеличивающий область касаний элемента."},{"type":"text","text":" "},{"type":"text","text":"Можно использовать, когда высота таймлайна слишком мала для надежного распознавания касаний."}],"type":"topic","url":"\/documentation\/ovkit\/timelineview\/verticalextendedinsets","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/endExternalUpdate()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/endExternalUpdate()","url":"\/documentation\/ovkit\/timelineview\/endexternalupdate()","title":"endExternalUpdate()","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endExternalUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/copyStateTo(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyStateTo"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier","text":"TimelineView"},{"kind":"text","text":")"}],"title":"copyStateTo(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/copyStateTo(_:)","url":"\/documentation\/ovkit\/timelineview\/copystateto(_:)","kind":"symbol","abstract":[{"type":"text","text":"Копирование состояния (текущее время, продолжительность, прелоад, таймкоды) в другой объект таймлайна."}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/continueTracking(_:with:)":{"role":"symbol","navigatorTitle":[{"text":"continueTrackingWithTouch:withEvent:","kind":"identifier"}],"title":"continueTracking(_:with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/continueTracking(_:with:)","url":"\/documentation\/ovkit\/timelineview\/continuetracking(_:with:)","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueTracking"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/thumbView":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbView","url":"\/documentation\/ovkit\/timelineview\/thumbview","kind":"symbol","title":"thumbView"},"doc://onevideo.OVKit/s8CopyableP":{"identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/durationView":{"title":"durationView","abstract":[],"url":"\/documentation\/ovkit\/timelineview\/durationview","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DurationView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)DurationView"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationView"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/delegate":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/delegate","abstract":[{"type":"text","text":"Делегат для получения событий взаимодействия с таймлайном"}],"url":"\/documentation\/ovkit\/timelineview\/delegate","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit25TimelineUIControlDelegateP","text":"TimelineUIControlDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/rewindedLiveAppearanceProgressColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rewindedLiveAppearanceProgressColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/rewindedLiveAppearanceProgressColor","role":"symbol","type":"topic","title":"rewindedLiveAppearanceProgressColor","abstract":[{"type":"text","text":"Цвет полосы прогресса при перемотке live-трансляции."}],"kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/rewindedliveappearanceprogresscolor"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/seekTime":{"kind":"symbol","title":"seekTime","role":"symbol","abstract":[{"text":"Актуален во время pan gesture","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/seekTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/timelineview\/seektime"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityDecrement()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDecrement"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityDecrement"}],"title":"accessibilityDecrement()","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityDecrement()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/timelineview\/accessibilitydecrement()"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"TimelineView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"TimelineView"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"TimelineView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityValue","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/frame","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/isHidden"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityDecrement()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityIncrement()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/beginTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/cancelTracking(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/continueTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/endTracking(_:with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/gestureRecognizerShouldBegin(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/init(frame:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/point(inside:with:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIControl"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","value":"pointInside:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1point(inside:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pointInside:withEvent:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1point(inside:with:)\/fragments"},{"op":"replace","value":"initWithFrame:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1init(frame:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1init(frame:)\/fragments"},{"op":"replace","value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1gestureRecognizerShouldBegin(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1gestureRecognizerShouldBegin(_:)\/fragments"},{"op":"replace","value":"accessibilityValue","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityValue\/title"},{"op":"replace","value":[{"text":"accessibilityValue","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityValue\/fragments"},{"op":"replace","value":"beginTrackingWithTouch:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1beginTracking(_:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginTrackingWithTouch:withEvent:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1beginTracking(_:with:)\/fragments"},{"op":"replace","value":"cancelTrackingWithEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1cancelTracking(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cancelTrackingWithEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1cancelTracking(with:)\/fragments"},{"op":"replace","value":"frame","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1frame\/title"},{"op":"replace","value":[{"kind":"identifier","text":"frame"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1frame\/fragments"},{"op":"replace","value":"TimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle"},{"op":"replace","value":"hidden","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1isHidden\/title"},{"op":"replace","value":[{"text":"hidden","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1isHidden\/fragments"},{"op":"replace","value":"endTrackingWithTouch:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1endTracking(_:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endTrackingWithTouch:withEvent:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1endTracking(_:with:)\/fragments"},{"op":"replace","value":"accessibilityIncrement","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityIncrement()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityIncrement","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityIncrement()\/fragments"},{"op":"replace","value":"continueTrackingWithTouch:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1continueTracking(_:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continueTrackingWithTouch:withEvent:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1continueTracking(_:with:)\/fragments"},{"op":"replace","value":"accessibilityDecrement","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityDecrement()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityDecrement","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityDecrement()\/fragments"}]}]}