{"kind":"symbol","metadata":{"symbolKind":"protocol","externalID":"s:5OVKit25TimelineUIControlDelegateP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineUIControlDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TimelineUIControlDelegate"}],"title":"TimelineUIControlDelegate","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Protocol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended"],"title":"Conforming Types","type":"conformingTypes"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/beginTracking(touch:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/continueTracking(touch:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/endTracking(touch:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineUIControlDelegate","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineuicontroldelegate"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineUIControlDelegate/continueTracking(touch:)":{"required":true,"abstract":[],"url":"\/documentation\/ovkit\/timelineuicontroldelegate\/continuetracking(touch:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"continueTracking(touch:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/continueTracking(touch:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineUIControlDelegate/beginTracking(touch:)":{"kind":"symbol","title":"beginTracking(touch:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginTracking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"touch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"required":true,"url":"\/documentation\/ovkit\/timelineuicontroldelegate\/begintracking(touch:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/beginTracking(touch:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineUIControlDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineUIControlDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"TimelineUIControlDelegate","kind":"identifier"}],"title":"TimelineUIControlDelegate","url":"\/documentation\/ovkit\/timelineuicontroldelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewBehaviorExtended":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewBehaviorExtended","navigatorTitle":[{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewbehaviorextended","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewBehaviorExtended","kind":"identifier"}],"role":"symbol","title":"SeekPreviewBehaviorExtended"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineUIControlDelegate/endTracking(touch:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineUIControlDelegate\/endTracking(touch:)","type":"topic","url":"\/documentation\/ovkit\/timelineuicontroldelegate\/endtracking(touch:)","title":"endTracking(touch:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTracking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"touch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":"?)"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/title","value":"SeekPreviewBehaviorExtended","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/fragments","value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewBehaviorExtended\/navigatorTitle","value":[{"kind":"identifier","text":"SeekPreviewBehaviorExtended"}],"op":"replace"}]}]}