{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"seeAlsoSections":[{"anchor":"Статистика","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"],"title":"Статистика"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKTimespentStatsHandler) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"StatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Просмотром считается состояние, когда плеер показывает движущуюся картинку и\/или воспроизводит звук. Состояние буферизации не является проигрыванием."}]},{"type":"aside","style":"note","name":"Info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"События будут вызваны на специальной background очереди. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":" после добавления нового "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timespentstatshandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timespentstatshandler"]}],"abstract":[{"text":"Принимает события начала и остановки просмотра видео.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"TimespentStatsHandler","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)OVKTimespentStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"TimespentStatsHandler","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"protocol"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/resetTimespentSession()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/startTimespent()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/stopTimespent()"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"title":"Inherits From","type":"inheritsFrom"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"kind":"symbol","title":"StatsHandler","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"События логирования будут вызваны на специальной background очереди."},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}]},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler/stopTimespent()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/stopTimespent()","url":"\/documentation\/ovkit\/timespentstatshandler\/stoptimespent()","abstract":[{"type":"text","text":"Проигрывание остановилось."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTimespent","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"stopTimespent","kind":"identifier"}],"role":"symbol","type":"topic","title":"stopTimespent()"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/video","title":"Video","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","title":"PlayerView","url":"\/documentation\/ovkit\/playerview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"title":"StatsCollector","url":"\/documentation\/ovkit\/statscollector","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsCollector"}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","role":"symbol","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","kind":"symbol","title":"TimespentStatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimespentStatsHandler"}],"type":"topic","url":"\/documentation\/ovkit\/timespentstatshandler","role":"symbol","abstract":[{"type":"text","text":"Принимает события начала и остановки просмотра видео."}],"navigatorTitle":[{"kind":"identifier","text":"TimespentStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"url":"\/documentation\/ovkit\/statscontext","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","type":"topic","title":"StatsContext","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"StatsContext","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler/startTimespent()":{"abstract":[{"text":"Проигрывание началось.","type":"text"}],"type":"topic","title":"startTimespent()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/startTimespent()","role":"symbol","navigatorTitle":[{"text":"startTimespent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTimespent","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/timespentstatshandler\/starttimespent()"},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler/resetTimespentSession()":{"type":"topic","url":"\/documentation\/ovkit\/timespentstatshandler\/resettimespentsession()","abstract":[{"text":"Закончилась сессия последовательного просмотра.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"resetTimespentSession","kind":"identifier"}],"role":"symbol","title":"resetTimespentSession()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetTimespentSession","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/resetTimespentSession()"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKTimespentStatsHandler","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKTimespentStatsHandler"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/resetTimespentSession()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/startTimespent()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/stopTimespent()"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"anchor":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler"],"title":"Статистика","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKTimespentStatsHandler","kind":"identifier"},{"text":" <","kind":"text"},{"text":"OVKStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","op":"replace"},{"value":"stopTimespent","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1stopTimespent()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"stopTimespent","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1stopTimespent()\/fragments","op":"replace"},{"value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace"},{"value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","op":"replace"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsCollector"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace"},{"value":"OVKTimespentStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title","op":"replace"},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments","op":"replace"},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","op":"replace"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","op":"replace"},{"value":"startTimespent","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1startTimespent()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startTimespent","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1startTimespent()\/fragments","op":"replace"},{"value":"resetTimespentSession","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1resetTimespentSession()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetTimespentSession"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1resetTimespentSession()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}