{"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/init(frame:chapterProvider:bottomMinY:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/chapterLabel","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/timeLabel"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/updateCurrentTime(timelineView:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timeandchaptercontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timeandchaptercontainer"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndChapterContainer","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)TimeAndChapterContainer","role":"symbol","title":"TimeAndChapterContainer","modules":[{"name":"OVKit"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeAndChapterContainer"}],"navigatorTitle":[{"text":"TimeAndChapterContainer","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/updateCurrentTime(timelineView:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCurrentTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timelineView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier","text":"TimelineView"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/timeandchaptercontainer\/updatecurrenttime(timelineview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/updateCurrentTime(timelineView:)","role":"symbol","kind":"symbol","title":"updateCurrentTime(timelineView:)","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/init(frame:chapterProvider:bottomMinY:)":{"role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/timeandchaptercontainer\/init(frame:chapterprovider:bottomminy:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chapterProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomMinY"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(frame:chapterProvider:bottomMinY:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/init(frame:chapterProvider:bottomMinY:)","type":"topic"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/timeLabel":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/timeLabel","url":"\/documentation\/ovkit\/timeandchaptercontainer\/timelabel","title":"timeLabel"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/chapterLabel":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/chapterLabel","title":"chapterLabel","type":"topic","url":"\/documentation\/ovkit\/timeandchaptercontainer\/chapterlabel","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapterLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer":{"url":"\/documentation\/ovkit\/timeandchaptercontainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndChapterContainer","kind":"identifier"}],"title":"TimeAndChapterContainer","abstract":[],"navigatorTitle":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/layoutSubviews()":{"url":"\/documentation\/ovkit\/timeandchaptercontainer\/layoutsubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/layoutSubviews()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"title":"layoutSubviews()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TimeAndChapterContainer","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"TimeAndChapterContainer"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/layoutSubviews()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndChapterContainer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TimeAndChapterContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/title","op":"replace"},{"value":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TimeAndChapterContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/navigatorTitle","op":"replace"},{"value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer~1layoutSubviews()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer~1layoutSubviews()\/fragments","op":"replace"}]}]}