{"metadata":{"role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimelineThumbnailsType"}],"symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","title":"TimelineThumbnailsType","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKTimelineThumbnailsType) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TimelineThumbnailsType","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/timelinethumbnailstype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timelinethumbnailstype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerRow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countTotal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/frameSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/urls"],"title":"Instance Properties"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnails"}],"url":"\/documentation\/ovkit\/timelinethumbnails","kind":"symbol","role":"symbol","title":"TimelineThumbnails","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TimelineThumbnails","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/frameSize":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/framesize","required":true,"kind":"symbol","type":"topic","title":"frameSize","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/frameSize","navigatorTitle":[{"kind":"identifier","text":"frameSize"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/countPerRow":{"kind":"symbol","title":"countPerRow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerRow","type":"topic","url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/countperrow","abstract":[],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"countPerRow"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"navigatorTitle":[{"text":"countPerRow","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/countPerImage":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"countPerImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/countperimage","required":true,"kind":"symbol","title":"countPerImage","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerImage","navigatorTitle":[{"text":"countPerImage","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/countTotal":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/counttotal","required":true,"kind":"symbol","type":"topic","title":"countTotal","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countTotal","navigatorTitle":[{"kind":"identifier","text":"countTotal"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnailsType/urls":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/ovktimelinethumbnailstype\/urls","required":true,"kind":"symbol","title":"urls","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/urls","navigatorTitle":[{"text":"urls","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnailstype","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","title":"TimelineThumbnailsType","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineThumbnailsType","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"OVKTimelineThumbnailsType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}]},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countPerRow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/countTotal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/frameSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnailsType\/urls"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"],"title":"Conforming Types","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"OVKTimelineThumbnailsType","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title","op":"replace","value":"OVKTimelineThumbnails"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments","value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}]},{"value":"frameSize","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1frameSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1frameSize\/fragments","value":[{"text":"frameSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerRow\/title","op":"replace","value":"countPerRow"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerRow\/fragments","op":"replace","value":[{"kind":"identifier","text":"countPerRow"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerImage\/title","value":"countPerImage"},{"value":[{"text":"countPerImage","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countPerImage\/fragments","op":"replace"},{"value":"countTotal","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countTotal\/title"},{"value":[{"text":"countTotal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1countTotal\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1urls\/title","op":"replace","value":"urls"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnailsType~1urls\/fragments","value":[{"kind":"identifier","text":"urls"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","value":"OVKTimelineThumbnailsType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","op":"replace","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]}]}]}