{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"},"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"TimelineThumbnails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineThumbnails","kind":"identifier"}],"title":"TimelineThumbnails","roleHeading":"Class","symbolKind":"class"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(frameSize:countPerRow:countPerImage:countTotal:links:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(from:)"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerRow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countTotal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/frameSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/urls"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/isEqual(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKTimelineThumbnails) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimelineThumbnails"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelinethumbnails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelinethumbnails"]}],"references":{"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/isEqual(_:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/isEqual(_:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/isequal(_:)","title":"isEqual(_:)","role":"symbol"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/countTotal":{"kind":"symbol","navigatorTitle":[{"text":"countTotal","kind":"identifier"}],"type":"topic","abstract":[],"title":"countTotal","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countTotal","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/counttotal"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/Se":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/Se","title":"Swift.Decodable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/init(from:)":{"kind":"symbol","type":"topic","abstract":[],"title":"init(from:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/init(from:)"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnails"}],"url":"\/documentation\/ovkit\/timelinethumbnails","kind":"symbol","role":"symbol","title":"TimelineThumbnails","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TimelineThumbnails","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/urls":{"kind":"symbol","navigatorTitle":[{"text":"urls","kind":"identifier"}],"type":"topic","abstract":[],"title":"urls","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/urls","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urls"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/urls"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/countPerRow":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"countPerRow"}],"kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnails\/countperrow","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerRow","title":"countPerRow","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"countPerRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/init(frameSize:countPerRow:countPerImage:countTotal:links:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrameSize:countPerRow:countPerImage:countTotal:links:"}],"type":"topic","abstract":[],"title":"init(frameSize:countPerRow:countPerImage:countTotal:links:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(frameSize:countPerRow:countPerImage:countTotal:links:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frameSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"countPerRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"countPerImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"countTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"links","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"])","kind":"text"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/init(framesize:countperrow:countperimage:counttotal:links:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/description":{"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","abstract":[],"title":"description","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/description"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnailstype","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","title":"TimelineThumbnailsType","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineThumbnailsType","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/frameSize":{"kind":"symbol","navigatorTitle":[{"text":"frameSize","kind":"identifier"}],"type":"topic","abstract":[],"title":"frameSize","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/frameSize","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/framesize"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/countPerImage":{"kind":"symbol","navigatorTitle":[{"text":"countPerImage","kind":"identifier"}],"type":"topic","abstract":[],"title":"countPerImage","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countPerImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/countperimage"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKTimelineThumbnails"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerImage","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countPerRow","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countTotal","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/frameSize","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/urls"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(frameSize:countPerRow:countPerImage:countTotal:links:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKTimelineThumbnails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"countTotal","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countTotal\/title","op":"replace"},{"op":"replace","value":[{"text":"countTotal","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countTotal\/fragments"},{"value":"OVKTimelineThumbnails","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1urls\/title","value":"urls","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1urls\/fragments","op":"replace","value":[{"kind":"identifier","text":"urls"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countPerRow\/title","value":"countPerRow","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countPerRow\/fragments","value":[{"kind":"identifier","text":"countPerRow"}]},{"value":"initWithFrameSize:countPerRow:countPerImage:countTotal:links:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1init(frameSize:countPerRow:countPerImage:countTotal:links:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1init(frameSize:countPerRow:countPerImage:countTotal:links:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrameSize:countPerRow:countPerImage:countTotal:links:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"value":"OVKTimelineThumbnailsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1frameSize\/title","value":"frameSize","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1frameSize\/fragments","value":[{"text":"frameSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countPerImage\/title","value":"countPerImage","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countPerImage\/fragments","op":"replace","value":[{"text":"countPerImage","kind":"identifier"}]}]}]}