{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"],["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в другой.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"Переходы чаще всего используются при навигации в приложении. Например, если есть экран ленты с видеозаписями, а по нажатию открывается экран детального просмотра выбранного видео. В таком сценарии имеются два ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":": один в ленте с контролами и поведением для ленты, а второй – на экране детального просмотра, с более функциональными контролами.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" является как бы “доком” для контейнера с воспроизведением. Когда контейнер воспроизведения переходит в “док”, он применяет к себе настройки этого “дока”: контролы, поведение при сворачивании приложения, политику проигрывания на внешних устройствах, и т.п. Чтобы понять, какие настройки плеера применятся после перехода в него контейнера, можно изучить документацию свойств ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Переход можно сделать без анимации, с заранее заданной анимацией или с интерактивной анимацией. Мгновенный переход без анимации выполняется методом ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)"},{"text":".","type":"text"}],"type":"paragraph"},{"anchor":"%D0%90%D0%BD%D0%B8%D0%BC%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D0%BE%D0%B2","level":3,"text":"Анимация переходов","type":"heading"},{"inlineContent":[{"text":"Для начала анимированного перехода понадобится создать вспомогательный объект-аниматор ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"},{"text":". Его создает плеер, ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"из","type":"text"}]},{"text":" которого осуществляется переход: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"},{"text":". Создание этого объекта само по себе не начинает процесс перехода, он начнется только после вызова ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/prepare()"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"После этого переход можно выполнить с заготовленной анимацией или интерактивно. Важно, чтобы в итоге он был завершен или отменен. Более подробно процесс описан в документации к ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"},{"text":".","type":"text"}],"type":"paragraph"},{"name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Во время анимированного перехода нельзя изменять свойства участвующих в нем плееров. Для проверки состояния перехода плеера существует свойство ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isTransitioning","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"type":"aside","style":"warning"},{"anchor":"%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D1%8B","level":3,"text":"Стандартные переходы","type":"heading"},{"inlineContent":[{"text":"Открытие ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen"},{"text":" или внутреннего окна Picture in Picture также являются переходами. Все, что было описано выше, относится к обычным плеерам, созданным пользователем. Применение этих методов инстансам ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", полученных из SDK (полноэкранное ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView"},{"text":" или оконное ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView"},{"text":"), приведет к неопределенному поведению.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Стандартные переходы происходят:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"при переводе плеера в полноэкранный режим – "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","type":"reference","isActive":true},{"type":"text","text":";"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"при сворачивании в окно Picture in Picture – "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP()","type":"reference","isActive":true},{"type":"text","text":";"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"при переходе из полноэкранного режима в Picture in Picture и наоборот;"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"при выходе из одного из этих режимов."}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"Любой стандартный переход можно отследить через методы ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"},{"text":":","type":"text"}],"type":"paragraph"},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Из \\ В","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Обычный","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Полноэкранный","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Picture in Picture","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Обычный","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Пользовательский код","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","isActive":true,"type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","isActive":true,"type":"reference"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Полноэкранный","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","isActive":true,"type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"text":"–","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","isActive":true,"type":"reference"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Picture in Picture","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindowDidClose(_:into:)","isActive":true,"type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","isActive":true,"type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"text":"–","type":"text"}]}]]],"type":"table"}],"kind":"content"}],"metadata":{"roleHeading":"Article","role":"article","title":"Переходы между плеерами","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/transitions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/transitions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","seeAlsoSections":[{"generated":true,"title":"Концепты","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"anchor":"Концепты"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/Extras":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","url":"\/documentation\/ovkit\/extras","type":"topic","role":"article","abstract":[{"text":"Дополнительные возможности.","type":"text"}],"title":"Разное","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isTransitioning":{"title":"isTransitioning","navigatorTitle":[{"text":"isTransitioning","kind":"identifier"}],"type":"topic","abstract":[{"text":"Находится ли данный ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в состоянии анимированного перехода из или в другой плеер.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/istransitioning","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTransitioning","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isTransitioning","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP()":{"url":"\/documentation\/ovkit\/playerview\/minimizetopip()","navigatorTitle":[{"text":"minimizeToPiP","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimizeToPiP"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[{"text":"Свернуть плеер в Picture in Picture.","type":"text"}],"title":"minimizeToPiP()","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP()"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"url":"\/documentation\/ovkit\/fullscreen","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","role":"article","abstract":[{"text":"Кастомизация полноэкранного просмотра.","type":"text"}],"title":"Полноэкранный режим","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"abstract":[{"type":"text","text":"Сбор статистики воспроизведения видео."}],"kind":"article","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","title":"Статистика","role":"article","url":"\/documentation\/ovkit\/statistics"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"title":"createAnimatedTransition(to:in:)","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":" в место назначения."}],"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnimatedTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"PlayerViewAnimatedTransition","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowFullscreen:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"willShowFullscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":"?"}],"abstract":[{"text":"Плеер был показан в полноэкранном режиме.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","title":"playerView(_:willShowFullscreen:)","required":true,"role":"symbol","navigatorTitle":[{"text":"playerView:willShowFullscreen:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/playerView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/pipwindow\/playerview","title":"playerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView","type":"topic","abstract":[{"type":"text","text":"Плеер, который отвечает за воспроизведение видео в окне."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"playerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"url":"\/documentation\/ovkit\/plugins","abstract":[{"text":"Динамически подключаемые модули для расширения функциональности.","type":"text"}],"title":"Плагины","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition":{"title":"PlayerViewAnimatedTransition","navigatorTitle":[{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"type":"topic","abstract":[{"type":"text","text":"Выполняет анимированный перенос плеера между двумя "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/playerviewanimatedtransition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","title":"Контролы плеера","type":"topic","abstract":[{"type":"text","text":"Кастомизация внешнего вида плеера."}],"url":"\/documentation\/ovkit\/controls","role":"article","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreen"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"kind":"symbol","abstract":[{"text":"Разворачивание плеера в полноэкранный режим.","type":"text"}],"title":"maximizeToFullscreen(completion:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","title":"PlayerManagerDelegate","abstract":[{"type":"text","text":"Делегат менеджера плееров."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"url":"\/documentation\/ovkit\/backgroundplayback","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","role":"article","abstract":[{"text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии.","type":"text"}],"title":"Воспроизведение в фоне","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenController(_:didCloseInto:interactive:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCloseInto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"interactive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Полноэкранный плеер был закрыт."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","title":"fullscreenController(_:didCloseInto:interactive:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fullscreenController:didCloseInto:interactive:"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:interactive:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/playerView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"}],"abstract":[{"type":"text","text":"Плеер, играющий в полноэкранном режиме."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/playerView","title":"playerView","role":"symbol","navigatorTitle":[{"text":"playerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipWindowDidClose(_:into:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindowDidClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":", ","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?)","kind":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/pipwindowdidclose(_:into:)","title":"pipWindowDidClose(_:into:)","abstract":[{"type":"text","text":"Окно Picture in Picture с плеером было закрыто."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindowDidClose(_:into:)","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"pipWindowDidClose:into:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition/prepare()":{"title":"prepare()","navigatorTitle":[{"kind":"identifier","text":"prepare"}],"type":"topic","abstract":[{"type":"text","text":"Подготовка к переносу."}],"url":"\/documentation\/ovkit\/playerviewanimatedtransition\/prepare()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition\/prepare()","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowPiP:)":{"url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowpip:)","navigatorTitle":[{"text":"playerView:willShowPiP:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"text":"willShowPiP","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow"},{"text":")","kind":"text"}],"type":"topic","title":"playerView(_:willShowPiP:)","required":true,"abstract":[{"text":"Был создан внутренний Picture in Picture плеер, необходимо установить ","type":"text"},{"code":"pip.playerView.delegate","type":"codeVoice"},{"text":". Но не стоит поручать это какому-нибудь ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":", жизненный цикл которого может быть меньше, чем у окна Picture in Picture.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetch":{"url":"\/documentation\/ovkit\/prefetch","abstract":[{"text":"Предзагрузка видео еще до начала воспроизведения.","type":"text"}],"title":"Префетчер","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","role":"article","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"url":"\/documentation\/ovkit\/playerview\/transition(to:)","navigatorTitle":[{"text":"transitionTo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Переход плеера в другое ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":" без анимации."}],"title":"transition(to:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetch","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Extras","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins"],"generated":true,"anchor":"Концепты","title":"Концепты"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isTransitioning\/title","value":"isTransitioning","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isTransitioning\/fragments","value":[{"kind":"identifier","text":"isTransitioning"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP()\/title","value":"minimizeToPiP","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minimizeToPiP"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","value":"createAnimatedTransitionTo:in:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/title","value":"playerView:willShowFullscreen:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowFullscreen:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/title","value":"playerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/fragments","value":[{"kind":"identifier","text":"playerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/title","value":"OVKPlayerViewAnimatedTransition","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/fragments","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title","value":"maximizeToFullscreenWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/title","value":"fullscreenController:didCloseInto:interactive:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenController:didCloseInto:interactive:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/title","value":"playerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1playerView\/fragments","value":[{"kind":"identifier","text":"playerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindowDidClose(_:into:)\/title","value":"pipWindowDidClose:into:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindowDidClose(_:into:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pipWindowDidClose:into:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1prepare()\/title","value":"prepare","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition~1prepare()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepare"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/title","value":"playerView:willShowPiP:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowPiP:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title","value":"transitionTo:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionTo:"}],"op":"replace"}]}]}