{"kind":"symbol","relationshipsSections":[{"type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView"],"title":"Conforming Types","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TransitionableControls"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"s:5OVKit22TransitionableControlsP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionableControls"}],"title":"TransitionableControls","role":"symbol","modules":[{"name":"OVKit"}]},"abstract":[{"type":"text","text":"Протокол для контролов, поддерживающих анимированный перенос между "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/ovkit\/transitionablecontrols"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didBeginTransitionAnimation(duration:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didFinishTransition()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/willBeginTransition(to:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionableControls"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/DiscoverSupplementedAdControlsView":{"title":"DiscoverSupplementedAdControlsView","kind":"symbol","navigatorTitle":[{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы для отображения в рекомендациях."},{"type":"text","text":" "},{"type":"text","text":"В отличии от базовых рекламных контролов "},{"type":"codeVoice","code":"SupplementedAdControlsView"},{"type":"text","text":" таймлайн отодвинут от границы плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DiscoverSupplementedAdControlsView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DiscoverSupplementedAdControlsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/discoversupplementedadcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/didFinishTransition()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFinishTransition","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"kind":"symbol","url":"\/documentation\/ovkit\/transitionablecontrols\/didfinishtransition()","title":"didFinishTransition()","abstract":[{"type":"text","text":"Завершение переноса плеера в другое "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didFinishTransition()"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/didBeginTransitionAnimation(duration:)":{"required":true,"title":"didBeginTransitionAnimation(duration:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didBeginTransitionAnimation(duration:)","abstract":[{"type":"text","text":"Начало анимации переноса плеера в другое "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/transitionablecontrols\/didbegintransitionanimation(duration:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBeginTransitionAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls":{"type":"topic","title":"TransitionableControls","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","url":"\/documentation\/ovkit\/transitionablecontrols","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionableControls"}],"abstract":[{"text":"Протокол для контролов, поддерживающих анимированный перенос между ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"TransitionableControls","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"abstract":[{"text":"Рекламные контролы для Fullscreen.","type":"text"},{"text":" ","type":"text"},{"text":"В отличии от базовых ","type":"text"},{"type":"codeVoice","code":"SupplementedAdControlsView"},{"text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementedAdControlsView"}],"url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview","title":"FullscreenSupplementedAdControlsView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/willBeginTransition(to:)":{"required":true,"title":"willBeginTransition(to:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/willBeginTransition(to:)","abstract":[{"type":"text","text":"Начало переноса плеера в другое "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/transitionablecontrols\/willbegintransition(to:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBeginTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementedAdControlsView":{"title":"SupplementedAdControlsView","kind":"symbol","navigatorTitle":[{"text":"SupplementedAdControlsView","kind":"identifier"}],"abstract":[{"type":"text","text":"Рекламные контролы общего назначения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementedAdControlsView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementedAdControlsView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/supplementedadcontrolsview"}},"variantOverrides":[{"patch":[{"value":"OVKDiscoverSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDiscoverSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"text":"OVKDiscoverSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DiscoverSupplementedAdControlsView\/navigatorTitle","op":"replace"},{"value":"OVKFullscreenSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/title","op":"replace"},{"value":[{"text":"OVKFullscreenSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementedAdControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/navigatorTitle","op":"replace"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/title","op":"replace","value":"OVKSupplementedAdControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementedAdControlsView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKSupplementedAdControlsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}