{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/s8SendableP","doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer","doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer","doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment","doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKUpcomingCoverView) "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpcomingCoverView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingCoverView","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKUpcomingCoverView","title":"UpcomingCoverView","symbolKind":"class","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Class","navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/ovkit\/upcomingcoverview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/upcomingcoverview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/init(frame:previewFrame:params:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/hasTimer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/isHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/isOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/params","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/previewImageFrame","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/smallLayout","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/timeContainer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleLabel"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/updateAppearance()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willMove(toWindow:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willStartTransitioning()"],"generated":true,"title":"Instance Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/CoverViewType-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","references":{"doc://onevideo.OVKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/willStartTransitioning()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"willStartTransitioning"}],"type":"topic","title":"willStartTransitioning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willStartTransitioning"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willStartTransitioning()","url":"\/documentation\/ovkit\/upcomingcoverview\/willstarttransitioning()","abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true,"type":"reference"},{"text":" начал перемещаться в другое место на другой ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/layoutSubviews()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"url":"\/documentation\/ovkit\/upcomingcoverview\/layoutsubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/layoutSubviews()","role":"symbol"},"doc://onevideo.OVKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UITraitEnvironment"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/hasTimer":{"title":"hasTimer","url":"\/documentation\/ovkit\/upcomingcoverview\/hastimer","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasTimer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/hasTimer","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/titleLabel":{"kind":"symbol","type":"topic","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/titleLabel","url":"\/documentation\/ovkit\/upcomingcoverview\/titlelabel","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIDynamicItem"},"doc://onevideo.OVKit/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)CALayerDelegate"},"doc://onevideo.OVKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/didEndTransitioning()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/didEndTransitioning()","role":"symbol","abstract":[{"type":"text","text":"Плеер закончил переезд на новую "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didEndTransitioning"},{"kind":"text","text":"()"}],"kind":"symbol","title":"didEndTransitioning()","navigatorTitle":[{"kind":"identifier","text":"didEndTransitioning"}],"type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/didendtransitioning()"},"doc://onevideo.OVKit/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)UIView"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/isOnScreen":{"role":"symbol","url":"\/documentation\/ovkit\/upcomingcoverview\/isonscreen","kind":"symbol","title":"isOnScreen","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/isOnScreen","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType","abstract":[{"type":"text","text":"Отображение баннера в плеере поверх воспроизведения."}],"url":"\/documentation\/ovkit\/coverviewtype","title":"CoverViewType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CoverViewType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CoverViewType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/willMove(toWindow:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"title":"willMove(toWindow:)","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/willmove(towindow:)","kind":"symbol"},"doc://onevideo.OVKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearanceContainer"},"doc://onevideo.OVKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/params":{"type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/params","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier","text":"CoverViewParams"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/params","title":"params"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/isHidden":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"type":"topic","title":"isHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/isHidden","url":"\/documentation\/ovkit\/upcomingcoverview\/ishidden","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/smallLayout":{"role":"symbol","url":"\/documentation\/ovkit\/upcomingcoverview\/smalllayout","kind":"symbol","title":"smallLayout","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/smallLayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UICoordinateSpace","title":"UIUtilities.UICoordinateSpace"},"doc://onevideo.OVKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIFocusItemContainer"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView":{"role":"symbol","url":"\/documentation\/ovkit\/upcomingcoverview","kind":"symbol","title":"UpcomingCoverView","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpcomingCoverView","kind":"identifier"}],"navigatorTitle":[{"text":"UpcomingCoverView","kind":"identifier"}]},"doc://onevideo.OVKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/coverControlsDelegate":{"title":"coverControlsDelegate","url":"\/documentation\/ovkit\/upcomingcoverview\/covercontrolsdelegate","abstract":[{"type":"text","text":"Делегат "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":". Устанавливать не нужно"}],"navigatorTitle":[{"kind":"identifier","text":"coverControlsDelegate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverControlsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKCoverControlsDelegate","kind":"typeIdentifier","text":"CoverControlsDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/coverControlsDelegate","role":"symbol","type":"topic"},"doc://onevideo.OVKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://onevideo.OVKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/onevideo.OVKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://onevideo.OVKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/previewImageFrame":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"previewImageFrame"}],"title":"previewImageFrame","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/previewImageFrame","url":"\/documentation\/ovkit\/upcomingcoverview\/previewimageframe","abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"code":"CoverView","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s8SendableP","title":"Swift.Sendable"},"doc://onevideo.OVKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://onevideo.OVKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/init(frame:previewFrame:params:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/init(frame:previewFrame:params:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"previewFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(frame:previewFrame:params:)","type":"topic","url":"\/documentation\/ovkit\/upcomingcoverview\/init(frame:previewframe:params:)"},"doc://onevideo.OVKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://onevideo.OVKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"kind":"symbol","title":"CoverView","navigatorTitle":[{"text":"CoverView","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/coverview"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/timeContainer":{"abstract":[],"url":"\/documentation\/ovkit\/upcomingcoverview\/timecontainer","title":"timeContainer","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeContainer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKUpcomingLiveTimeContainer","text":"UpcomingLiveTimeContainer","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/timeContainer","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/handleCoverWithParams(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleCoverWithParams:"}],"type":"topic","title":"handleCoverWithParams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleCoverWithParams"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier","text":"CoverViewParams"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Обновить UI под изменившееся состояние."}],"url":"\/documentation\/ovkit\/upcomingcoverview\/handlecoverwithparams(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/handleCoverWithParams(_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/CoverViewType-Implementations":{"url":"\/documentation\/ovkit\/upcomingcoverview\/coverviewtype-implementations","abstract":[],"title":"CoverViewType Implementations","kind":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/CoverViewType-Implementations","role":"collectionGroup","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/UpcomingCoverView/updateAppearance()":{"kind":"symbol","title":"updateAppearance()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAppearance","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/updateAppearance()","url":"\/documentation\/ovkit\/upcomingcoverview\/updateappearance()","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"OVKUpcomingCoverView","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/coverControlsDelegate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/isHidden","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/previewImageFrame"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/didEndTransitioning()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/handleCoverWithParams(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/layoutSubviews()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willMove(toWindow:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingCoverView\/willStartTransitioning()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)UIView"],"title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewType"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKUpcomingCoverView"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1willStartTransitioning()\/title","value":"willStartTransitioning"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1willStartTransitioning()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willStartTransitioning","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1layoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1didEndTransitioning()\/title","op":"replace","value":"didEndTransitioning"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1didEndTransitioning()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/title","value":"OVKCoverViewType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/fragments","value":[{"kind":"identifier","text":"OVKCoverViewType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1willMove(toWindow:)\/title","op":"replace","value":"willMoveToWindow:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1willMove(toWindow:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willMoveToWindow:"}]},{"value":"hidden","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1isHidden\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1isHidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"hidden"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/title","op":"replace","value":"OVKUpcomingCoverView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/fragments","value":[{"kind":"identifier","text":"OVKUpcomingCoverView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView\/navigatorTitle","value":[{"text":"OVKUpcomingCoverView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1coverControlsDelegate\/title","value":"coverControlsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1coverControlsDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"coverControlsDelegate"}]},{"value":"previewImageFrame","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1previewImageFrame\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1previewImageFrame\/fragments","value":[{"kind":"identifier","text":"previewImageFrame"}],"op":"replace"},{"op":"replace","value":"handleCoverWithParams:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1handleCoverWithParams(_:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingCoverView~1handleCoverWithParams(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleCoverWithParams:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}