{"metadata":{"role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationState"}],"modules":[{"name":"OVKit"}],"title":"ValidationState","navigatorTitle":[{"kind":"identifier","text":"ValidationState"}],"symbolKind":"enum"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/processing"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/CustomDebugStringConvertible-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/CustomStringConvertible-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState"},"abstract":[{"type":"text","text":"Состояние проверки ресурса в оффлайн-хранилище."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKValidationState) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationState"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/s8CopyableP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/validationstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/validationstate"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ValidationState/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/ovkit\/validationstate\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/processing":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"navigatorTitle":[{"text":"OVKValidationStateProcessing","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/processing","url":"\/documentation\/ovkit\/validationstate\/processing","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Выполняется проверка."}],"role":"symbol","title":"ValidationState.processing"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/onevideo.OVKit\/SY"},"doc://onevideo.OVKit/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/onevideo.OVKit\/s8CopyableP"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationState","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState","url":"\/documentation\/ovkit\/validationstate","kind":"symbol","type":"topic","abstract":[{"text":"Состояние проверки ресурса в оффлайн-хранилище.","type":"text"}],"role":"symbol","title":"ValidationState"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/CustomStringConvertible-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/CustomStringConvertible-Implementations","abstract":[],"url":"\/documentation\/ovkit\/validationstate\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/CustomDebugStringConvertible-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/CustomDebugStringConvertible-Implementations","abstract":[],"url":"\/documentation\/ovkit\/validationstate\/customdebugstringconvertible-implementations","title":"CustomDebugStringConvertible Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/init(rawValue:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/init(rawValue:)","abstract":[],"url":"\/documentation\/ovkit\/validationstate\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/Equatable-Implementations","abstract":[],"url":"\/documentation\/ovkit\/validationstate\/equatable-implementations","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ValidationState/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"ValidationState.none","url":"\/documentation\/ovkit\/validationstate\/none","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKValidationStateNone"}],"abstract":[{"type":"text","text":"Статус проверки неизвестен."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/none"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"OVKValidationState"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKValidationState"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKValidationState"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/none","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValidationState\/processing"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OVKValidationState","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1processing\/title","op":"replace","value":"OVKValidationStateProcessing"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1processing\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKValidationStateProcessing"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/title","op":"replace","value":"OVKValidationState"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKValidationState"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKValidationState"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1none\/title","op":"replace","value":"OVKValidationStateNone"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ValidationState~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKValidationStateNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}