{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestrictiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestrictiontype"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","interfaceLanguage":"swift"},"abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKVideoRestrictionType) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","modules":[{"name":"OVKit"}],"role":"symbol","title":"VideoRestrictionType","roleHeading":"Protocol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/actionButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/blur","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPlay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPreview","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/cardIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/disclaimerType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/listIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/muteInfoLink","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/title"]}],"kind":"symbol","sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"]},{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/text":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/text","abstract":[{"text":"Текст баннера.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"title":"text","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/text","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestriction"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","url":"\/documentation\/ovkit\/videorestriction","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"VideoRestriction"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/listIcon":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/listIcon","abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listIcon","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"title":"listIcon","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/listicon","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/cardIcon":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/cardIcon","abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ImageAssetType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"cardIcon","kind":"identifier"}],"title":"cardIcon","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/cardicon","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/disclaimerType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/disclaimerType","abstract":[{"text":"Идентификатор типа запрещающего баннера.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disclaimerType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"disclaimerType","kind":"identifier"}],"title":"disclaimerType","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/disclaimertype","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/canPlay":{"navigatorTitle":[{"text":"canPlay","kind":"identifier"}],"title":"canPlay","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Можно ли запускать воспроизведение."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPlay","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/videorestrictiontype\/canplay"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/title":{"navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title","kind":"symbol","role":"symbol","abstract":[{"text":"Заголовок баннера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/title","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/videorestrictiontype\/title"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/actionButton":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/actionButton","url":"\/documentation\/ovkit\/videorestrictiontype\/actionbutton","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Модель кнопки для снятия запрета."}],"role":"symbol","title":"actionButton","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/blur":{"abstract":[{"text":"Нужно ли блюрить превью изображение на ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/blur","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"blur"}],"title":"blur","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/blur","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/canPreview":{"navigatorTitle":[{"kind":"identifier","text":"canPreview"}],"title":"canPreview","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Можно ли показывать превью изображение на "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPreview","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/videorestrictiontype\/canpreview"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/muteInfoLink":{"abstract":[{"text":"Ссылка на информацию о том, почему в данном видео нельзя воспроизвести звук.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/muteInfoLink","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteInfoLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"muteInfoLink"}],"title":"muteInfoLink","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/muteinfolink","role":"symbol","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionType"}],"navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","url":"\/documentation\/ovkit\/videorestrictiontype","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Модель баннера, запрещающего просмотр."}],"role":"symbol","title":"VideoRestrictionType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"OVKVideoRestrictionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/actionButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/blur","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPlay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/canPreview","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/cardIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/disclaimerType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/listIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/muteInfoLink","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/title"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"],"type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoRestrictionType"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1text\/title","op":"replace","value":"text"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1text\/fragments","op":"replace","value":[{"kind":"identifier","text":"text"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title","op":"replace","value":"OVKVideoRestriction"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestriction"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestriction"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1listIcon\/title","op":"replace","value":"listIcon"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1listIcon\/fragments","op":"replace","value":[{"kind":"identifier","text":"listIcon"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1cardIcon\/title","op":"replace","value":"cardIcon"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1cardIcon\/fragments","op":"replace","value":[{"kind":"identifier","text":"cardIcon"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1disclaimerType\/title","op":"replace","value":"disclaimerType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1disclaimerType\/fragments","op":"replace","value":[{"kind":"identifier","text":"disclaimerType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1canPlay\/title","op":"replace","value":"canPlay"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1canPlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"canPlay"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1title\/title","op":"replace","value":"title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1title\/fragments","op":"replace","value":[{"kind":"identifier","text":"title"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1actionButton\/title","op":"replace","value":"actionButton"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1actionButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"actionButton"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1blur\/title","op":"replace","value":"blur"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1blur\/fragments","op":"replace","value":[{"kind":"identifier","text":"blur"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1canPreview\/title","op":"replace","value":"canPreview"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1canPreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"canPreview"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1muteInfoLink\/title","op":"replace","value":"muteInfoLink"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1muteInfoLink\/fragments","op":"replace","value":[{"kind":"identifier","text":"muteInfoLink"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","op":"replace","value":"OVKVideoRestrictionType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}]}]}]}