{"sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashCmaf","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashHevc","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLivePlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashSep","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashStreams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebm","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebmAv1","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLiveOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLivePlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsStreams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1080","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1440","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_2160","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_240","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_360","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_480","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_720","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rtmp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/source"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/init(rawValue:)"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rawValue-swift.property"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawValue-swift.typealias"],"anchor":"Type-Aliases","generated":true,"title":"Type Aliases"},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/defaultFileFormatPriorities","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsForcedFileFormatPriorities"]},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"VideoFileFormat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoFileFormat"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKVideoFileFormat","navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/s12CaseIterableP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKVideoFileFormat) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/videofileformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformat"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashHevc":{"url":"\/documentation\/ovkit\/videofileformat\/dashhevc","kind":"symbol","title":"VideoFileFormat.dashHevc","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashHevc"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashHevc","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dashHevc","kind":"identifier"}],"abstract":[{"text":"Ссылка на раздельный дэш. Формат mp4+h265+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","title":"VideoFileFormat","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"url":"\/documentation\/ovkit\/videofileformat"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_1080":{"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"navigatorTitle":[{"text":"OVKVideoFileFormatMp4_1080","kind":"identifier"}],"title":"VideoFileFormat.mp4_1080","url":"\/documentation\/ovkit\/videofileformat\/mp4_1080","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1080","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mp4_1080"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsForcedFileFormatPriorities":{"title":"hlsForcedFileFormatPriorities","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hlsForcedFileFormatPriorities","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":"]","kind":"text"}],"url":"\/documentation\/ovkit\/videofileformat\/hlsforcedfileformatpriorities","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsForcedFileFormatPriorities","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hls":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hls","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHls"}],"title":"VideoFileFormat.hls","url":"\/documentation\/ovkit\/videofileformat\/hls","abstract":[{"type":"text","text":"Ссылка на hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hls"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_240":{"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"title":"VideoFileFormat.mp4_240","url":"\/documentation\/ovkit\/videofileformat\/mp4_240","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mp4_240","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_240","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_240"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashStreams":{"abstract":[{"type":"text","text":"Ссылка на новый единый дэш манифест с раздельными аудио и видео дорожками, содержащий все кодеки и контейнеры, доступные для ролика."},{"type":"text","text":" "},{"type":"text","text":"Может быть несколько Adaptation set как с видео, так и с аудио. Для каждого кодека или контейнера отдельный Adaptation set. Также Adaptation set’ы аудио могут различаться языком\/озвучкой, а Adaptation set’ы видео могут различаться динамическим диапазоном: SDR 8 бит и HDR 10 бит."},{"type":"text","text":" "},{"type":"text","text":"Запросы байт-ренж реквестами."}],"title":"VideoFileFormat.dashStreams","role":"symbol","type":"topic","navigatorTitle":[{"text":"OVKVideoFileFormatDashStreams","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/dashstreams","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashStreams","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashStreams","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/ovkit\/videofileformat\/equatable-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/Equatable-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashLive":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashLive","kind":"identifier"}],"title":"VideoFileFormat.dashLive","navigatorTitle":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLive","url":"\/documentation\/ovkit\/videofileformat\/dashlive","role":"symbol","type":"topic","abstract":[{"text":"Ссылка на кастомный (не по стандарту) лайв комбо-дэш. Формат mp4+h264+aac.","type":"text"},{"text":" ","type":"text"},{"text":"Используется свой формат root манифеста и манифеста качества jidx.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"В каждом mp4 сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_480":{"role":"symbol","kind":"symbol","abstract":[{"text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original.","type":"text"}],"title":"VideoFileFormat.mp4_480","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_480","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mp4_480","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/mp4_480","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_480"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsOndemand":{"title":"VideoFileFormat.hlsOndemand","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"hlsOndemand","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/hlsondemand","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsOndemand","abstract":[{"type":"text","text":"Ссылка на ондеманд hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."},{"type":"text","text":" "},{"text":"Ондеманд значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHlsOndemand"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLiveOndemand":{"navigatorTitle":[{"text":"OVKVideoFileFormatHlsLiveOndemand","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/hlsliveondemand","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLiveOndemand","abstract":[{"type":"text","text":"Ссылка на ондеманд лайв hls root playlist. Формат ts+h264+aac. Запросы посегментно."},{"text":" ","type":"text"},{"text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом качества."}],"type":"topic","kind":"symbol","title":"VideoFileFormat.hlsLiveOndemand","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLiveOndemand"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/source":{"url":"\/documentation\/ovkit\/videofileformat\/source","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/source","type":"topic","navigatorTitle":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}],"role":"symbol","title":"VideoFileFormat.source","kind":"symbol","abstract":[{"text":"Ссылка на локальный mp4 файл или на movpkg каталог (используется для загруженных на устройство HLS видео).","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLivePlayback":{"abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist, вариант для перемотки (playback). В урле нужно подменить параметр "},{"code":"offset_p","type":"codeVoice"},{"type":"text","text":"."}],"title":"VideoFileFormat.hlsLivePlayback","url":"\/documentation\/ovkit\/videofileformat\/hlsliveplayback","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"hlsLivePlayback","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLivePlayback","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLivePlayback"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_360":{"title":"VideoFileFormat.mp4_360","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mp4_360"}],"url":"\/documentation\/ovkit\/videofileformat\/mp4_360","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_360","abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatMp4_360","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/init(rawValue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/ovkit\/videofileformat\/init(rawvalue:)","title":"init(rawValue:)"},"doc://onevideo.OVKit/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s12CaseIterableP"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/RawValue-swift.typealias":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawValue-swift.typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RawValue","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"kind":"symbol","title":"VideoFileFormat.RawValue","url":"\/documentation\/ovkit\/videofileformat\/rawvalue-swift.typealias"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/defaultFileFormatPriorities":{"abstract":[],"title":"defaultFileFormatPriorities","url":"\/documentation\/ovkit\/videofileformat\/defaultfileformatpriorities","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultFileFormatPriorities","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/defaultFileFormatPriorities","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/rawValue-swift.property":{"title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/ovkit\/videofileformat\/rawvalue-swift.property","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rawValue-swift.property","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashSep":{"type":"topic","role":"symbol","abstract":[{"text":"Ссылка на раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashSep"}],"title":"VideoFileFormat.dashSep","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashSep"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashSep","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat\/dashsep"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashLivePlayback":{"navigatorTitle":[{"text":"OVKVideoFileFormatDashLivePlayback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dashLivePlayback","kind":"identifier"}],"abstract":[{"type":"text","text":"Ссылка на кастомный (не по стандарту) лайв комбо-дэш, вариант для перемотки (playback). В урле нужно подменить параметр "},{"type":"codeVoice","code":"offset_p"},{"text":".","type":"text"}],"kind":"symbol","title":"VideoFileFormat.dashLivePlayback","url":"\/documentation\/ovkit\/videofileformat\/dashliveplayback","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLivePlayback","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_1440":{"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"navigatorTitle":[{"text":"OVKVideoFileFormatMp4_1440","kind":"identifier"}],"title":"VideoFileFormat.mp4_1440","url":"\/documentation\/ovkit\/videofileformat\/mp4_1440","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1440","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mp4_1440"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_2160":{"abstract":[{"type":"text","text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original."}],"title":"VideoFileFormat.mp4_2160","url":"\/documentation\/ovkit\/videofileformat\/mp4_2160","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mp4_2160"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_2160","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_2160"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashCmaf":{"title":"VideoFileFormat.dashCmaf","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dashCmaf","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/dashcmaf","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashCmaf","abstract":[{"type":"text","text":"Ссылка на ондеманд лайв раздельный дэш. Формат mp4+h264+aac. Запросы посегментно."},{"type":"text","text":" "},{"text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Перемотка осуществляется путем приписывания query параметра offset к запросу за манифестом."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashCmaf"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashWebmAv1":{"abstract":[{"type":"text","text":"Ссылка на раздельный дэш. Формат webm+vp9+opus. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами."}],"title":"VideoFileFormat.dashWebmAv1","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebmAv1","url":"\/documentation\/ovkit\/videofileformat\/dashwebmav1","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dashWebmAv1"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebmAv1"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsStreams":{"abstract":[{"type":"text","text":"Ссылка на новый единый hls манифест с раздельными аудио дорожками, содержащий все кодеки и контейнеры, доступные для ролика."}],"title":"VideoFileFormat.hlsStreams","url":"\/documentation\/ovkit\/videofileformat\/hlsstreams","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hlsStreams","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsStreams","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatHlsStreams"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/rtmp":{"abstract":[{"type":"text","text":"Ссылка на rtmp. Формат flv+h264+aac. Есть автокачество, сервер будет пытаться отдавать клиенту максимально возможное под его канал разрешение."},{"type":"text","text":" "},{"text":"Используется для режима минимальной задержки, поэтому не перематывается.","type":"text"}],"url":"\/documentation\/ovkit\/videofileformat\/rtmp","role":"symbol","title":"VideoFileFormat.rtmp","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtmp"}],"navigatorTitle":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rtmp"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashWebm":{"kind":"symbol","abstract":[{"type":"text","text":"Ссылка на раздельный дэш. Формат webm+vp9+opus. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы байт-ренж реквестами."}],"navigatorTitle":[{"text":"OVKVideoFileFormatDashWebm","kind":"identifier"}],"title":"VideoFileFormat.dashWebm","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebm","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashWebm"}],"role":"symbol","url":"\/documentation\/ovkit\/videofileformat\/dashwebm"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/videofileformat\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/mp4_720":{"kind":"symbol","title":"VideoFileFormat.mp4_720","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mp4_720"}],"navigatorTitle":[{"text":"OVKVideoFileFormatMp4_720","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformat\/mp4_720","abstract":[{"text":"Ссылки на интерлив mp4 файлы, по качествам 240, 360, 480, 720, 1080, 1440, 2160. Качества обычно соответствуют, кроме случая original или primary original.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_720"},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/SY":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SY","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/hlsLive":{"role":"symbol","navigatorTitle":[{"text":"OVKVideoFileFormatHlsLive","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsLive"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLive","title":"VideoFileFormat.hlsLive","url":"\/documentation\/ovkit\/videofileformat\/hlslive","abstract":[{"type":"text","text":"Ссылка на лайв hls root playlist. Формат ts+h264+aac. В каждом ts сегменте максимум одна видео и одна аудио дорожка. Запросы посегментно."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat/dashOndemand":{"kind":"symbol","abstract":[{"type":"text","text":"Ссылка на ондеманд раздельный дэш. Формат mp4+h264+aac. Максимум два adaptation set, один с видео файлами, другой с аудио. Запросы посегментно."},{"text":" ","type":"text"},{"text":"Ondemand значит, что сегменты верхнего качества готовы сразу, сегменты нижнего качества будут готовиться по запросу.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dashOndemand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoFileFormatDashOndemand"}],"title":"VideoFileFormat.dashOndemand","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashOndemand","url":"\/documentation\/ovkit\/videofileformat\/dashondemand","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"OVKVideoFileFormat","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashCmaf","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashHevc","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashLivePlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashSep","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashStreams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebm","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/dashWebmAv1","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLiveOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsLivePlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsOndemand","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/hlsStreams","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1080","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_1440","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_2160","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_240","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_360","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_480","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/mp4_720","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/rtmp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat\/source"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKVideoFileFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashHevc\/title","op":"replace","value":"OVKVideoFileFormatDashHevc"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashHevc\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashHevc"}]},{"value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1080\/title","value":"OVKVideoFileFormatMp4_1080"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_1080"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1080\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hls\/title","value":"OVKVideoFileFormatHls"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hls\/fragments","value":[{"text":"OVKVideoFileFormatHls","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_240\/title","value":"OVKVideoFileFormatMp4_240","op":"replace"},{"value":[{"text":"OVKVideoFileFormatMp4_240","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_240\/fragments"},{"value":"OVKVideoFileFormatDashStreams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashStreams\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKVideoFileFormatDashStreams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashStreams\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLive\/title","op":"replace","value":"OVKVideoFileFormatDashLive"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLive\/fragments","op":"replace","value":[{"text":"OVKVideoFileFormatDashLive","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_480\/title","op":"replace","value":"OVKVideoFileFormatMp4_480"},{"value":[{"text":"OVKVideoFileFormatMp4_480","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_480\/fragments","op":"replace"},{"value":"OVKVideoFileFormatHlsOndemand","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsOndemand\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsOndemand\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsOndemand"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLiveOndemand\/title","value":"OVKVideoFileFormatHlsLiveOndemand"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLiveOndemand\/fragments","value":[{"text":"OVKVideoFileFormatHlsLiveOndemand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1source\/title","value":"OVKVideoFileFormatSource","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1source\/fragments","value":[{"text":"OVKVideoFileFormatSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLivePlayback\/title","value":"OVKVideoFileFormatHlsLivePlayback","op":"replace"},{"op":"replace","value":[{"text":"OVKVideoFileFormatHlsLivePlayback","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLivePlayback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_360\/title","value":"OVKVideoFileFormatMp4_360"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_360"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_360\/fragments"},{"value":"OVKVideoFileFormatDashSep","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashSep\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashSep\/fragments","value":[{"text":"OVKVideoFileFormatDashSep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLivePlayback\/title","op":"replace","value":"OVKVideoFileFormatDashLivePlayback"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatDashLivePlayback"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashLivePlayback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1440\/title","value":"OVKVideoFileFormatMp4_1440","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_1440\/fragments","value":[{"text":"OVKVideoFileFormatMp4_1440","kind":"identifier"}]},{"value":"OVKVideoFileFormatMp4_2160","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_2160\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_2160\/fragments","value":[{"text":"OVKVideoFileFormatMp4_2160","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashCmaf\/title","value":"OVKVideoFileFormatDashCmaf","op":"replace"},{"value":[{"text":"OVKVideoFileFormatDashCmaf","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashCmaf\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebmAv1\/title","value":"OVKVideoFileFormatDashWebmAv1","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebmAv1\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebmAv1"}],"op":"replace"},{"value":"OVKVideoFileFormatHlsStreams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsStreams\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsStreams\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsStreams"}]},{"op":"replace","value":"OVKVideoFileFormatRtmp","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1rtmp\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1rtmp\/fragments","value":[{"text":"OVKVideoFileFormatRtmp","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebm\/title","value":"OVKVideoFileFormatDashWebm","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatDashWebm"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashWebm\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_720\/title","value":"OVKVideoFileFormatMp4_720"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1mp4_720\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatMp4_720"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLive\/title","value":"OVKVideoFileFormatHlsLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1hlsLive\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatHlsLive"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashOndemand\/title","value":"OVKVideoFileFormatDashOndemand","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat~1dashOndemand\/fragments","value":[{"text":"OVKVideoFileFormatDashOndemand","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}