{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"seeAlsoSections":[{"title":"Воспроизведение","anchor":"Воспроизведение","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideoType) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/authorName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/canPlayInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/durationSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/endlessLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/failoverHost","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/forceSubtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/haveVideoFiles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/iid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isDownloaded","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isExplicit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isGif","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isMobileLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isRecord","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isSpherical","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveRewindMaxSeconds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSpectators","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStartTimestamp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/oid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/ovId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/prefetchFile","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/previewImages","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/replayGain","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/rewindableLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/subtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/timelineThumbs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoAds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoUrlQuery","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/viewedDuration"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/downloadFile(preferHLS:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSettingsUpdate(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/setVideoURL(_:for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoURL(_:)"]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoType","roleHeading":"Protocol","role":"symbol","title":"VideoType","symbolKind":"protocol","modules":[{"name":"OVKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoType","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/size":{"title":"size","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/size","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype\/size","kind":"symbol","abstract":[],"required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoURL(_:)":{"navigatorTitle":[{"text":"videoURL:","kind":"identifier"}],"title":"videoURL(_:)","abstract":[],"url":"\/documentation\/ovkit\/videotype\/videourl(_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoURL(_:)","kind":"symbol","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/durationSec":{"url":"\/documentation\/ovkit\/videotype\/durationsec","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/durationSec","title":"durationSec","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationSec","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","required":true,"navigatorTitle":[{"text":"durationSec","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/setVideoURL(_:for:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVideoURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videotype\/setvideourl(_:for:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/setVideoURL(_:for:)","required":true,"title":"setVideoURL(_:for:)","navigatorTitle":[{"text":"setVideoURL:for:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/rewindableLive":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/rewindableLive","abstract":[],"url":"\/documentation\/ovkit\/videotype\/rewindablelive","role":"symbol","navigatorTitle":[{"text":"rewindableLive","kind":"identifier"}],"title":"rewindableLive","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewindableLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoId":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/videotype\/videoid","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoId","navigatorTitle":[{"text":"videoId","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"required":true,"title":"videoId"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/ovId":{"title":"ovId","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/videotype\/ovid","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/ovId","navigatorTitle":[{"kind":"identifier","text":"ovId"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/iid":{"role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/iid","navigatorTitle":[{"kind":"identifier","text":"iid"}],"url":"\/documentation\/ovkit\/videotype\/iid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"iid","type":"topic","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","title":"VideoType","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videotype","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/replayGain":{"url":"\/documentation\/ovkit\/videotype\/replaygain","kind":"symbol","required":true,"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayGain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/replayGain","navigatorTitle":[{"text":"replayGain","kind":"identifier"}],"title":"replayGain","abstract":[{"text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/prefetchFile":{"url":"\/documentation\/ovkit\/videotype\/prefetchfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchFile"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoFile","kind":"typeIdentifier","text":"VideoFile"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/prefetchFile","type":"topic","kind":"symbol","abstract":[],"title":"prefetchFile"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveStatus":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","kind":"typeIdentifier"}],"title":"liveStatus","navigatorTitle":[{"text":"liveStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStatus","url":"\/documentation\/ovkit\/videotype\/livestatus","type":"topic","abstract":[]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveSpectators":{"abstract":[],"title":"liveSpectators","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSpectators","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videotype\/livespectators","kind":"symbol","navigatorTitle":[{"text":"liveSpectators","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSpectators"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoRestriction":{"navigatorTitle":[{"text":"videoRestriction","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","required":true,"url":"\/documentation\/ovkit\/videotype\/videorestriction","role":"symbol","kind":"symbol","type":"topic","title":"videoRestriction","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoRestriction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isExplicit":{"abstract":[],"type":"topic","url":"\/documentation\/ovkit\/videotype\/isexplicit","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExplicit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isExplicit","kind":"identifier"}],"title":"isExplicit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isExplicit","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoType/title":{"title":"title","url":"\/documentation\/ovkit\/videotype\/title","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/title","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/chapters":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/chapters","kind":"symbol","url":"\/documentation\/ovkit\/videotype\/chapters","navigatorTitle":[{"text":"chapters","kind":"identifier"}],"title":"chapters","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"required":true,"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isDownloaded":{"navigatorTitle":[{"kind":"identifier","text":"isDownloaded"}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype\/isdownloaded","title":"isDownloaded","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isDownloaded","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDownloaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"title":"PrefetchItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"title":"PlayerView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/failoverHost":{"kind":"symbol","navigatorTitle":[{"text":"failoverHost","kind":"identifier"}],"required":true,"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/failoverHost","url":"\/documentation\/ovkit\/videotype\/failoverhost","title":"failoverHost","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failoverHost","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/viewedDuration":{"role":"symbol","navigatorTitle":[{"text":"viewedDuration","kind":"identifier"}],"title":"viewedDuration","abstract":[{"text":"Момент времени, до которого пользователь досмотрел видео на другом устройстве. Значением является TimeInterval.","type":"text"}],"required":true,"type":"topic","url":"\/documentation\/ovkit\/videotype\/viewedduration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewedDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/viewedDuration","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/authorName":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","title":"authorName","required":true,"navigatorTitle":[{"text":"authorName","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/authorName","abstract":[],"url":"\/documentation\/ovkit\/videotype\/authorname"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/repeated":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"repeated"}],"title":"repeated","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","url":"\/documentation\/ovkit\/videotype\/repeated","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/timelineThumbs":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timelineThumbs","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","text":"TimelineThumbnailsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/timelineThumbs","required":true,"type":"topic","title":"timelineThumbs","url":"\/documentation\/ovkit\/videotype\/timelinethumbs","navigatorTitle":[{"text":"timelineThumbs","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoAds":{"title":"videoAds","kind":"symbol","required":true,"url":"\/documentation\/ovkit\/videotype\/videoads","role":"symbol","navigatorTitle":[{"text":"videoAds","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoAds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoAdsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isMobileLive":{"title":"isMobileLive","navigatorTitle":[{"text":"isMobileLive","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMobileLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/videotype\/ismobilelive","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isMobileLive","type":"topic","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoType/previewImages":{"navigatorTitle":[{"kind":"identifier","text":"previewImages"}],"url":"\/documentation\/ovkit\/videotype\/previewimages","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"type":"topic","title":"previewImages","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/previewImages"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveStartTimestamp":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStartTimestamp","required":true,"title":"liveStartTimestamp","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/videotype\/livestarttimestamp","navigatorTitle":[{"text":"liveStartTimestamp","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveRewindMaxSeconds":{"required":true,"type":"topic","navigatorTitle":[{"text":"liveRewindMaxSeconds","kind":"identifier"}],"kind":"symbol","title":"liveRewindMaxSeconds","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveRewindMaxSeconds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveRewindMaxSeconds","url":"\/documentation\/ovkit\/videotype\/liverewindmaxseconds"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/downloadFile(preferHLS:)":{"url":"\/documentation\/ovkit\/videotype\/downloadfile(preferhls:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferHLS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoFile","text":"VideoFile"},{"kind":"text","text":"?"}],"title":"downloadFile(preferHLS:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/downloadFile(preferHLS:)","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isLive":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isLive","title":"isLive","required":true,"kind":"symbol","url":"\/documentation\/ovkit\/videotype\/islive","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Отложенная \/ идущая \/ прерванная трансляция. live status: upcoming, started, waiting.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"isLive","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/subtitle":{"required":true,"title":"subtitle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"url":"\/documentation\/ovkit\/videotype\/subtitle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitle"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/subtitle"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","url":"\/documentation\/ovkit\/video","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"kind":"symbol","type":"topic","title":"Video","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/endlessLive":{"kind":"symbol","navigatorTitle":[{"text":"endlessLive","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/videotype\/endlesslive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endlessLive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"endlessLive","type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/endlessLive","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isSpherical":{"abstract":[{"type":"text","text":"true когда видео сферическое"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isSpherical","url":"\/documentation\/ovkit\/videotype\/isspherical","navigatorTitle":[{"text":"isSpherical","kind":"identifier"}],"kind":"symbol","required":true,"title":"isSpherical","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpherical","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoUrlQuery":{"url":"\/documentation\/ovkit\/videotype\/videourlquery","required":true,"type":"topic","navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoUrlQuery","title":"videoUrlQuery","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoURLQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"text":"?","kind":"text"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/haveVideoFiles":{"url":"\/documentation\/ovkit\/videotype\/havevideofiles","required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/haveVideoFiles","role":"symbol","title":"haveVideoFiles","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"haveVideoFiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"haveVideoFiles"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isGif":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isGif","type":"topic","required":true,"navigatorTitle":[{"text":"isGif","kind":"identifier"}],"title":"isGif","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/videotype\/isgif","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isGif","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isRecord":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecord"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isRecord","type":"topic","abstract":[{"text":"Записанный стрим или обычное видео live status: postlive, unknown.","type":"text"}],"url":"\/documentation\/ovkit\/videotype\/isrecord","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isRecord","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/canPlayInBackground":{"required":true,"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/canPlayInBackground","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"canPlayInBackground","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/videotype\/canplayinbackground","navigatorTitle":[{"kind":"identifier","text":"canPlayInBackground"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/forceSubtitles":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/forceSubtitles","required":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"forceSubtitles"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceSubtitles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/videotype\/forcesubtitles","title":"forceSubtitles"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoCategory":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoCategory","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoCategory","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoCategory","preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory"}],"url":"\/documentation\/ovkit\/videotype\/videocategory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoCategory"}],"role":"symbol","abstract":[],"title":"videoCategory","required":true},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveSettingsUpdate(with:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSettingsUpdate(with:)","url":"\/documentation\/ovkit\/videotype\/livesettingsupdate(with:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettingsUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"liveSettingsUpdate(with:)","navigatorTitle":[{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/oid":{"required":true,"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/oid","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"oid"}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype\/oid","abstract":[],"title":"oid"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKVideoType","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/authorName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/canPlayInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/durationSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/endlessLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/failoverHost","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/forceSubtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/haveVideoFiles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/iid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isDownloaded","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isExplicit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isGif","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isMobileLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isSpherical","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveRewindMaxSeconds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSpectators","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStartTimestamp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/oid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/ovId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/previewImages","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/replayGain","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/rewindableLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/subtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/timelineThumbs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoAds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoUrlQuery","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/viewedDuration"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSettingsUpdate(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/setVideoURL(_:for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoURL(_:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"]},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Воспроизведение","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"],"title":"Воспроизведение","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoType"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","kind":"typeIdentifier","text":"OVKPrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"size","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1size\/title"},{"op":"replace","value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1size\/fragments"},{"op":"replace","value":"videoURL:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoURL(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoURL:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoURL(_:)\/fragments"},{"op":"replace","value":"durationSec","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1durationSec\/title"},{"op":"replace","value":[{"text":"durationSec","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1durationSec\/fragments"},{"op":"replace","value":"setVideoURL:for:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1setVideoURL(_:for:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoURL:for:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1setVideoURL(_:for:)\/fragments"},{"op":"replace","value":"rewindableLive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1rewindableLive\/title"},{"op":"replace","value":[{"text":"rewindableLive","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1rewindableLive\/fragments"},{"op":"replace","value":"videoId","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"videoId"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoId\/fragments"},{"op":"replace","value":"ovId","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1ovId\/title"},{"op":"replace","value":[{"text":"ovId","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1ovId\/fragments"},{"op":"replace","value":"iid","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1iid\/title"},{"op":"replace","value":[{"kind":"identifier","text":"iid"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1iid\/fragments"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1replayGain\/title","value":"replayGain","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1replayGain\/fragments","value":[{"text":"replayGain","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStatus\/title","value":"liveStatus","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStatus\/fragments","value":[{"kind":"identifier","text":"liveStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSpectators\/title","value":"liveSpectators","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSpectators\/fragments","value":[{"kind":"identifier","text":"liveSpectators"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/title","value":"videoRestriction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/fragments","value":[{"kind":"identifier","text":"videoRestriction"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isExplicit\/title","value":"isExplicit","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isExplicit\/fragments","value":[{"kind":"identifier","text":"isExplicit"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1title\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1chapters\/title","value":"chapters","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1chapters\/fragments","value":[{"text":"chapters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isDownloaded\/title","value":"isDownloaded","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isDownloaded\/fragments","value":[{"text":"isDownloaded","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1failoverHost\/title","value":"failoverHost","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1failoverHost\/fragments","value":[{"text":"failoverHost","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1viewedDuration\/title","value":"viewedDuration","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1viewedDuration\/fragments","value":[{"kind":"identifier","text":"viewedDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1authorName\/title","value":"authorName","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1authorName\/fragments","value":[{"text":"authorName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/title","value":"repeated","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/fragments","value":[{"text":"repeated","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1timelineThumbs\/title","value":"timelineThumbs","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1timelineThumbs\/fragments","value":[{"kind":"identifier","text":"timelineThumbs"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoAds\/title","value":"videoAds","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoAds\/fragments","value":[{"text":"videoAds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isMobileLive\/title","value":"isMobileLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isMobileLive\/fragments","value":[{"kind":"identifier","text":"isMobileLive"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1previewImages\/title","value":"previewImages","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1previewImages\/fragments","value":[{"text":"previewImages","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStartTimestamp\/title","value":"liveStartTimestamp","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStartTimestamp\/fragments","value":[{"kind":"identifier","text":"liveStartTimestamp"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveRewindMaxSeconds\/title","value":"liveRewindMaxSeconds","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveRewindMaxSeconds\/fragments","value":[{"text":"liveRewindMaxSeconds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isLive\/title","value":"isLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isLive\/fragments","value":[{"text":"isLive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1subtitle\/title","value":"subtitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1subtitle\/fragments","value":[{"text":"subtitle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1endlessLive\/title","value":"endlessLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1endlessLive\/fragments","value":[{"text":"endlessLive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isSpherical\/title","value":"isSpherical","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isSpherical\/fragments","value":[{"kind":"identifier","text":"isSpherical"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoUrlQuery\/title","value":"videoUrlQuery","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoUrlQuery\/fragments","value":[{"text":"videoUrlQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1haveVideoFiles\/title","value":"haveVideoFiles","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1haveVideoFiles\/fragments","value":[{"kind":"identifier","text":"haveVideoFiles"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isGif\/title","value":"isGif","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isGif\/fragments","value":[{"text":"isGif","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1canPlayInBackground\/title","value":"canPlayInBackground","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1canPlayInBackground\/fragments","value":[{"kind":"identifier","text":"canPlayInBackground"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1forceSubtitles\/title","value":"forceSubtitles","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1forceSubtitles\/fragments","value":[{"kind":"identifier","text":"forceSubtitles"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoCategory\/title","value":"videoCategory","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoCategory\/fragments","value":[{"kind":"identifier","text":"videoCategory"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSettingsUpdate(with:)\/title","value":"liveSettingsUpdateWith:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSettingsUpdate(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1oid\/title","value":"oid","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1oid\/fragments","value":[{"text":"oid","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}