{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},"metadata":{"symbolKind":"class","title":"Video","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Воспроизведение","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"],"anchor":"Воспроизведение"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideo) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}]}],"kind":"declarations"},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer"],"kind":"mentions"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(id:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/authorName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/canPlayInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/durationSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/endlessLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/failoverHost","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/files","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/forceSubtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/haveVideoFiles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/iid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isDownloaded","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isExplicit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isGif","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isMobileLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isSpherical","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveRewindMaxSeconds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettings","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSpectators","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStartTimestamp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/oid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchMinTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchPreviews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeCellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeWiFi","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchResource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchThumbnails","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/previewImages","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/replayGain","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/rewindableLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/subtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/timelineThumbs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoAds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoRestriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoUrlQuery","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/viewedDuration"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isEqual(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettingsUpdate(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/setVideoURL(_:for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoURL(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/VideoType-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"],"kind":"relationships"}],"abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"reference"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Video/hash":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/hash","type":"topic","title":"hash","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/ovkit\/video\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/Video/videoRestriction":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoRestriction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoRestrictionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"text":"?","kind":"text"}],"title":"videoRestriction","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoRestriction","kind":"symbol","abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}],"url":"\/documentation\/ovkit\/video\/videorestriction","role":"symbol","navigatorTitle":[{"text":"videoRestriction","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/authorName":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/authorName","title":"authorName","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"authorName"}],"url":"\/documentation\/ovkit\/video\/authorname","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"Автор видеозаписи.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/videoAds":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","text":"VideoAdsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/videoads","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoAds","role":"symbol","abstract":[{"type":"text","text":"Модель с данными для показа in-stream рекламы."}],"navigatorTitle":[{"text":"videoAds","kind":"identifier"}],"title":"videoAds"},"doc://onevideo.OVKit/documentation/OVKit/Video/liveSettings":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKLiveSettings","text":"LiveSettings","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"liveSettings","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettings","url":"\/documentation\/ovkit\/video\/livesettings","title":"liveSettings"},"doc://onevideo.OVKit/documentation/OVKit/Video/VideoType-Implementations":{"title":"VideoType Implementations","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/VideoType-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/ovkit\/video\/videotype-implementations","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/init(id:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(id:)","title":"init(id:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithId:"}],"url":"\/documentation\/ovkit\/video\/init(id:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Создание модели видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/chapters":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/chapters","type":"topic","title":"chapters","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"chapters"}],"url":"\/documentation\/ovkit\/video\/chapters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Список эпизодов, на которые поделена видеозапись."}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/Video/haveVideoFiles":{"title":"haveVideoFiles","abstract":[{"text":"Содержатся ли в модели ссылки на видео ресурсы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/haveVideoFiles","navigatorTitle":[{"kind":"identifier","text":"haveVideoFiles"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/havevideofiles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"haveVideoFiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchQualityRangeCellular":{"url":"\/documentation\/ovkit\/video\/prefetchqualityrangecellular","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeCellular"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"}],"type":"topic","title":"prefetchQualityRangeCellular","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeCellular","abstract":[{"type":"text","text":"Диапазон качества предзагрузки, если устройство находится в сотовой сети. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/liveSettingsUpdate(with:)":{"title":"liveSettingsUpdate(with:)","abstract":[{"type":"text","text":"Обновляет состояние прямой трансляции."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettingsUpdate(with:)","navigatorTitle":[{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/livesettingsupdate(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettingsUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/isDownloaded":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDownloaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/isdownloaded","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isDownloaded","role":"symbol","abstract":[{"text":"Является ли видеозапись полученной из оффлайн хранилища.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isDownloaded"}],"title":"isDownloaded"},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchQualityRangeWiFi":{"title":"prefetchQualityRangeWiFi","abstract":[{"text":"Диапазон качества предзагрузки, если устройство находится в сети WiFi. В пределах диапазона качество выбирается, исходя из качества сети в момент предзагрузки.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeWiFi","navigatorTitle":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/prefetchqualityrangewifi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchQualityRangeWiFi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchPreviews":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchPreviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/prefetchpreviews","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchPreviews","role":"symbol","abstract":[{"text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchPreviews"}],"title":"prefetchPreviews"},"doc://onevideo.OVKit/documentation/OVKit/Video/forceSubtitles":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forceSubtitles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/forcesubtitles","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/forceSubtitles","role":"symbol","abstract":[{"type":"text","text":"Нужно ли автоматически включать субтитры в начале воспроизведения."}],"navigatorTitle":[{"kind":"identifier","text":"forceSubtitles"}],"title":"forceSubtitles"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/Video/previewImages":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImages"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier","text":"ImageAssetType"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/previewimages","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/previewImages","role":"symbol","abstract":[{"text":"Набор ассетов изображений для показа в качестве превью.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"previewImages"}],"title":"previewImages"},"doc://onevideo.OVKit/documentation/OVKit/Video/isEqual(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isEqual(_:)","url":"\/documentation\/ovkit\/video\/isequal(_:)","title":"isEqual(_:)"},"doc://onevideo.OVKit/documentation/OVKit/Video/isSpherical":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isSpherical","type":"topic","title":"isSpherical","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSpherical"}],"url":"\/documentation\/ovkit\/video\/isspherical","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpherical"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Является ли видеозапись сферическим 360-видео.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/iid":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/iid","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iid"}],"abstract":[{"type":"text","text":"Item ID видеозаписи у конкретного автора из VK."}],"url":"\/documentation\/ovkit\/video\/iid","title":"iid","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChapterProvider"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/chapterprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","role":"symbol","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"title":"ChapterProvider"},"doc://onevideo.OVKit/documentation/OVKit/Video/videoUrlQuery":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","text":"VideoURLQuery","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"videoUrlQuery","type":"topic","kind":"symbol","abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoUrlQuery","url":"\/documentation\/ovkit\/video\/videourlquery","role":"symbol","navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}]},"doc://onevideo.OVKit/Se":{"identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://onevideo.OVKit/documentation/OVKit/Video/failoverHost":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failoverHost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"failoverHost","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Резервный host, на который плеер должен переключиться в случае сетевой ошибки."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/failoverHost","url":"\/documentation\/ovkit\/video\/failoverhost","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"failoverHost"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/isLive":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isLive","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isLive","abstract":[{"type":"text","text":"Является ли видеозапись прямой трансляцией."}],"kind":"symbol","url":"\/documentation\/ovkit\/video\/islive","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isLive"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/canPlayInBackground":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/canplayinbackground","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/canPlayInBackground","role":"symbol","abstract":[{"type":"text","text":"Можно ли воспроизводить видеозапись в фоне."}],"navigatorTitle":[{"kind":"identifier","text":"canPlayInBackground"}],"title":"canPlayInBackground"},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/Video/subtitle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/subtitle","type":"topic","title":"subtitle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitle"}],"url":"\/documentation\/ovkit\/video\/subtitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Описание видеозаписи."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/init(from:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(from:)","title":"init(from:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/Video/size":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/size","title":"size","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/ovkit\/video\/size","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"Размер видео дорожки в пикселях."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/liveStatus":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}],"title":"liveStatus","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStatus","abstract":[{"type":"text","text":"Статус прямой трансляции."}],"kind":"symbol","url":"\/documentation\/ovkit\/video\/livestatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveStatus"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/repeated":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/repeated","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"repeated"}],"title":"repeated"},"doc://onevideo.OVKit/documentation/OVKit/Video/isGif":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isGif","title":"isGif","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isGif"}],"url":"\/documentation\/ovkit\/video\/isgif","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGif"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Для GIF нужно еще руками поставить "},{"code":"repeated = true","type":"codeVoice"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/rewindableLive":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/rewindableLive","abstract":[{"type":"text","text":"Доступность перемотки прямой трансляции назад."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rewindableLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/ovkit\/video\/rewindablelive","title":"rewindableLive","kind":"symbol","navigatorTitle":[{"text":"rewindableLive","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/liveSpectators":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSpectators","title":"liveSpectators","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveSpectators"}],"url":"\/documentation\/ovkit\/video\/livespectators","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSpectators"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"abstract":[{"type":"text","text":"Количество зрителей прямой трансляции."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/replayGain":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/replayGain","title":"replayGain","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"replayGain"}],"url":"\/documentation\/ovkit\/video\/replaygain","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"replayGain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Уровень\/коэффициент звука, позволяет выравнивать громкость на уровне соседних видео. Значением является Double."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/oid":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/oid","abstract":[{"type":"text","text":"Owner ID видеозаписи из VK."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","title":"oid","url":"\/documentation\/ovkit\/video\/oid","kind":"symbol","navigatorTitle":[{"text":"oid","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/videoURL(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoURL"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/videourl(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoURL(_:)","role":"symbol","abstract":[{"text":"Возвращает URL на ресурс заданного формата.","type":"text"}],"navigatorTitle":[{"text":"videoURL:","kind":"identifier"}],"title":"videoURL(_:)"},"doc://onevideo.OVKit/documentation/OVKit/Video/isMobileLive":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMobileLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isMobileLive"}],"type":"topic","abstract":[{"type":"text","text":"Является ли видеозапись прямой трансляцией с мобильного устройства."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isMobileLive","url":"\/documentation\/ovkit\/video\/ismobilelive","title":"isMobileLive"},"doc://onevideo.OVKit/documentation/OVKit/Video/videoCategory":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoCategory","abstract":[{"text":"Тип видеозаписи.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCategory"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoCategory","kind":"typeIdentifier","text":"VideoCategory"}],"type":"topic","url":"\/documentation\/ovkit\/video\/videocategory","kind":"symbol","title":"videoCategory","navigatorTitle":[{"kind":"identifier","text":"videoCategory"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/isExplicit":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExplicit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/video\/isexplicit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isExplicit","role":"symbol","abstract":[{"type":"text","text":"Присутствует ли в видео ненормативная лексика."}],"navigatorTitle":[{"text":"isExplicit","kind":"identifier"}],"title":"isExplicit"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","url":"\/documentation\/ovkit\/videotype","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/files":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/files","title":"files","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/files","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"files"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","url":"\/documentation\/ovkit\/thumbnailprovider","title":"ThumbnailProvider"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/timelineThumbs":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/timelineThumbs","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timelineThumbs"}],"url":"\/documentation\/ovkit\/video\/timelinethumbs","abstract":[{"text":"Кадры из видео, отображаемые на таймлайне при перемотке.","type":"text"}],"title":"timelineThumbs","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timelineThumbs"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType","kind":"typeIdentifier","text":"TimelineThumbnailsType"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/ovId":{"title":"ovId","abstract":[{"type":"text","text":"Идентификатор видео в ЕВ."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","navigatorTitle":[{"kind":"identifier","text":"ovId"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/ovid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/title":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/title","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/ovkit\/video\/title","abstract":[{"text":"Название видеозаписи.","type":"text"}],"kind":"symbol","title":"title","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/durationSec":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/durationSec","type":"topic","title":"durationSec","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"durationSec"}],"url":"\/documentation\/ovkit\/video\/durationsec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"text":"Длительность видеозаписи.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/setVideoURL(_:for:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/setVideoURL(_:for:)","title":"setVideoURL(_:for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setVideoURL:for:"}],"url":"\/documentation\/ovkit\/video\/setvideourl(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoURL"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Устанавливает URL на ресурс заданного формата."}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/Video/endlessLive":{"title":"endlessLive","abstract":[{"type":"text","text":"Является ли видеозапись бесконечной прямой трансляцией."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/endlessLive","navigatorTitle":[{"kind":"identifier","text":"endlessLive"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/endlesslive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endlessLive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"title":"Создание плеера","abstract":[{"type":"text","text":"Первые шаги после интеграции."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","kind":"article","role":"article","url":"\/documentation\/ovkit\/createplayer","type":"topic"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/Video/liveStartTimestamp":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStartTimestamp","title":"liveStartTimestamp","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"liveStartTimestamp","kind":"identifier"}],"url":"\/documentation\/ovkit\/video\/livestarttimestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Время начала прямой трансляции."}]},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchMinTime":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchMinTime","title":"prefetchMinTime","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchMinTime"}],"url":"\/documentation\/ovkit\/video\/prefetchmintime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchMinTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"abstract":[{"type":"text","text":"Минимальная длительность участка предзагрузки."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchThumbnails":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchThumbnails","title":"prefetchThumbnails","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchThumbnails"}],"url":"\/documentation\/ovkit\/video\/prefetchthumbnails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchThumbnails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Набор вариантов thumbnails для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/prefetchResource":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchResource","title":"prefetchResource","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchResource"}],"url":"\/documentation\/ovkit\/video\/prefetchresource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchResource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"}],"abstract":[{"type":"text","text":"Видео-ресурс для предзагрузки."}]},"doc://onevideo.OVKit/documentation/OVKit/Video/liveRewindMaxSeconds":{"title":"liveRewindMaxSeconds","abstract":[{"text":"Интервал, на который возможна перемотка прямой трансляции назад.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveRewindMaxSeconds","navigatorTitle":[{"text":"liveRewindMaxSeconds","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video\/liverewindmaxseconds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveRewindMaxSeconds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video/viewedDuration":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/viewedDuration","abstract":[{"type":"text","text":"Момент времени, до которого пользователь досмотрел видео на другом устройстве."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewedDuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"title":"viewedDuration","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/video\/viewedduration","navigatorTitle":[{"text":"viewedDuration","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video/videoId":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoId","abstract":[{"text":"Уникальный идентификатор видео.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"videoId","kind":"symbol","url":"\/documentation\/ovkit\/video\/videoid","navigatorTitle":[{"text":"videoId","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"kind":"identifier","text":"Video"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"OVKVideo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/authorName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/canPlayInBackground","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/chapters","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/durationSec","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/endlessLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/failoverHost","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/forceSubtitles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/haveVideoFiles","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/iid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isDownloaded","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isExplicit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isGif","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isMobileLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isSpherical","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveRewindMaxSeconds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettings","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSpectators","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStartTimestamp","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveStatus","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/oid","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/ovId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchMinTime","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchPreviews","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeCellular","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchQualityRangeWiFi","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchResource","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/prefetchThumbnails","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/previewImages","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/repeated","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/replayGain","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/rewindableLive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/size","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/subtitle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/timelineThumbs","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/title","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoAds","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoCategory","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoId","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoRestriction","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoUrlQuery","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/viewedDuration"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/init(id:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/isEqual(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/liveSettingsUpdate(with:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/setVideoURL(_:for:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video\/videoURL(_:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Воспроизведение","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"],"anchor":"Воспроизведение","generated":true}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1hash\/fragments"},{"value":"videoRestriction","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoRestriction\/title"},{"value":[{"text":"videoRestriction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoRestriction\/fragments"},{"value":"authorName","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1authorName\/title"},{"value":[{"text":"authorName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1authorName\/fragments"},{"value":"videoAds","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoAds\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoAds\/fragments","value":[{"kind":"identifier","text":"videoAds"}],"op":"replace"},{"value":"liveSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettings\/fragments","value":[{"kind":"identifier","text":"liveSettings"}],"op":"replace"},{"value":"initWithId:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1init(id:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1init(id:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1chapters\/title","value":"chapters","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1chapters\/fragments","value":[{"text":"chapters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1haveVideoFiles\/title","value":"haveVideoFiles","op":"replace"},{"value":[{"kind":"identifier","text":"haveVideoFiles"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1haveVideoFiles\/fragments"},{"value":"prefetchQualityRangeCellular","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeCellular\/title"},{"value":[{"kind":"identifier","text":"prefetchQualityRangeCellular"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeCellular\/fragments"},{"value":"liveSettingsUpdateWith:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettingsUpdate(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"liveSettingsUpdateWith:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSettingsUpdate(with:)\/fragments"},{"value":"isDownloaded","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isDownloaded\/title"},{"value":[{"kind":"identifier","text":"isDownloaded"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isDownloaded\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeWiFi\/title","value":"prefetchQualityRangeWiFi","op":"replace"},{"value":[{"kind":"identifier","text":"prefetchQualityRangeWiFi"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchQualityRangeWiFi\/fragments","op":"replace"},{"value":"prefetchPreviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchPreviews\/title","op":"replace"},{"value":[{"kind":"identifier","text":"prefetchPreviews"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchPreviews\/fragments","op":"replace"},{"value":"forceSubtitles","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1forceSubtitles\/title","op":"replace"},{"value":[{"kind":"identifier","text":"forceSubtitles"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1forceSubtitles\/fragments","op":"replace"},{"value":"previewImages","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1previewImages\/title","op":"replace"},{"value":[{"kind":"identifier","text":"previewImages"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1previewImages\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isEqual(_:)\/fragments","op":"replace"},{"value":"isSpherical","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isSpherical\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isSpherical"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isSpherical\/fragments","op":"replace"},{"value":"iid","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1iid\/title","op":"replace"},{"value":[{"kind":"identifier","text":"iid"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1iid\/fragments","op":"replace"},{"value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","op":"replace"},{"value":[{"text":"OVKChapterProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle"},{"value":"videoUrlQuery","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoUrlQuery\/title"},{"value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoUrlQuery\/fragments"},{"value":"failoverHost","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1failoverHost\/title"},{"value":[{"kind":"identifier","text":"failoverHost"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1failoverHost\/fragments"},{"value":"isLive","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isLive\/title"},{"value":[{"kind":"identifier","text":"isLive"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isLive\/fragments"},{"value":"canPlayInBackground","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1canPlayInBackground\/title"},{"value":[{"kind":"identifier","text":"canPlayInBackground"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1canPlayInBackground\/fragments"},{"value":"subtitle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1subtitle\/title"},{"value":[{"text":"subtitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1subtitle\/fragments"},{"value":"size","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1size\/title"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1size\/fragments"},{"value":"liveStatus","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveStatus\/title"},{"value":[{"kind":"identifier","text":"liveStatus"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveStatus\/fragments"},{"value":"repeated","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/title"},{"value":[{"text":"repeated","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1repeated\/fragments"},{"value":"isGif","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isGif\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isGif"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isGif\/fragments","op":"replace"},{"value":"rewindableLive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1rewindableLive\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1rewindableLive\/fragments","value":[{"text":"rewindableLive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSpectators\/title","value":"liveSpectators","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveSpectators\/fragments","value":[{"text":"liveSpectators","kind":"identifier"}],"op":"replace"},{"value":"replayGain","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1replayGain\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1replayGain\/fragments","value":[{"text":"replayGain","kind":"identifier"}],"op":"replace"},{"value":"oid","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1oid\/title"},{"value":[{"kind":"identifier","text":"oid"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1oid\/fragments","op":"replace"},{"value":"videoURL:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoURL(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoURL:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoURL(_:)\/fragments","op":"replace"},{"value":"isMobileLive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isMobileLive\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isMobileLive"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isMobileLive\/fragments","op":"replace"},{"value":"videoCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoCategory\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoCategory\/fragments","value":[{"text":"videoCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isExplicit\/title","value":"isExplicit","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1isExplicit\/fragments","value":[{"kind":"identifier","text":"isExplicit"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1timelineThumbs\/title","value":"timelineThumbs","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1timelineThumbs\/fragments","value":[{"kind":"identifier","text":"timelineThumbs"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/title","value":"ovId","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1ovId\/fragments","value":[{"kind":"identifier","text":"ovId"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1title\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1durationSec\/title","value":"durationSec","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1durationSec\/fragments","value":[{"kind":"identifier","text":"durationSec"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1setVideoURL(_:for:)\/title","value":"setVideoURL:for:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1setVideoURL(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoURL:for:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1endlessLive\/title","value":"endlessLive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1endlessLive\/fragments","value":[{"kind":"identifier","text":"endlessLive"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveStartTimestamp\/title","value":"liveStartTimestamp","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveStartTimestamp\/fragments","value":[{"kind":"identifier","text":"liveStartTimestamp"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchMinTime\/title","value":"prefetchMinTime","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchMinTime\/fragments","value":[{"text":"prefetchMinTime","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchThumbnails\/title","value":"prefetchThumbnails","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchThumbnails\/fragments","value":[{"kind":"identifier","text":"prefetchThumbnails"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchResource\/title","value":"prefetchResource","op":"replace"},{"value":[{"kind":"identifier","text":"prefetchResource"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1prefetchResource\/fragments"},{"value":"liveRewindMaxSeconds","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveRewindMaxSeconds\/title"},{"value":[{"kind":"identifier","text":"liveRewindMaxSeconds"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1liveRewindMaxSeconds\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1viewedDuration\/title","value":"viewedDuration","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1viewedDuration\/fragments","value":[{"text":"viewedDuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoId\/title","value":"videoId","op":"replace"},{"value":[{"text":"videoId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video~1videoId\/fragments"},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}