{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/action","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/title"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"protocol","title":"VideoRestrictionButtonType","externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"VideoRestrictionButtonType","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestrictionbuttontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestrictionbuttontype"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType"},"abstract":[{"text":"Модель кнопки для снятия запрета.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKVideoRestrictionButtonType) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionButtonType"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton"],"type":"conformingTypes"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButton":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videorestrictionbutton","title":"VideoRestrictionButton","kind":"symbol","navigatorTitle":[{"text":"VideoRestrictionButton","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButton","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType/title":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/title","abstract":[{"type":"text","text":"Текст на кнопке."}],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videorestrictionbuttontype\/title","kind":"symbol","title":"title","required":true,"navigatorTitle":[{"kind":"identifier","text":"title"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","role":"symbol","abstract":[{"text":"Модель кнопки для снятия запрета.","type":"text"}],"navigatorTitle":[{"text":"VideoRestrictionButtonType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestrictionbuttontype","type":"topic","title":"VideoRestrictionButtonType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType/action":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/action","abstract":[{"text":"Описание действия кнопки.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"action","url":"\/documentation\/ovkit\/videorestrictionbuttontype\/action","required":true,"navigatorTitle":[{"kind":"identifier","text":"action"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"OVKVideoRestrictionButtonType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/action","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType\/title"],"anchor":"Instance-Properties","title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKVideoRestrictionButtonType","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/title","value":"OVKVideoRestrictionButton","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/navigatorTitle","value":[{"text":"OVKVideoRestrictionButton","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1title\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title","value":"OVKVideoRestrictionButtonType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments","value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/navigatorTitle","value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1action\/title","value":"action","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType~1action\/fragments","value":[{"text":"action","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}