{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(OVKVideoChapterType) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoChapterType"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter"],"type":"conformingTypes"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoChapterType","roleHeading":"Protocol","symbolKind":"protocol","title":"VideoChapterType","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapterType"}],"navigatorTitle":[{"text":"VideoChapterType","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videochaptertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videochaptertype"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/time"],"title":"Instance Properties"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"title":"VideoChapterType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoChapterType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videochaptertype","navigatorTitle":[{"text":"VideoChapterType","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType/time":{"role":"symbol","required":true,"title":"time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"time","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"time"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/time","url":"\/documentation\/ovkit\/videochaptertype\/time"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter":{"title":"VideoChapter","navigatorTitle":[{"text":"VideoChapter","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/videochapter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"VideoChapter","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType/text":{"abstract":[],"role":"symbol","title":"text","required":true,"navigatorTitle":[{"kind":"identifier","text":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/text","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/ovkit\/videochaptertype\/text"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoChapterType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType\/time"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter"],"kind":"relationships","type":"conformingTypes"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"OVKVideoChapterType","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","op":"replace","value":"OVKVideoChapterType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType~1time\/title","value":"time","op":"replace"},{"value":[{"text":"time","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType~1time\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/title","value":"OVKVideoChapter"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapter"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType~1text\/title","value":"text"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType~1text\/fragments","value":[{"text":"text","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}