{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videoproxyprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videoproxyprotocol"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"VideoProxyProtocol","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)VideoProxyProtocol","navigatorTitle":[{"text":"VideoProxyProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoProxyProtocol","kind":"identifier"}],"symbolKind":"protocol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/activeProxy"],"title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/handle(_:completionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/modifyRequest(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoProxyProtocol","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol/activeProxy":{"kind":"symbol","abstract":[],"type":"topic","title":"activeProxy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/activeProxy","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeProxy","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/videoproxyprotocol\/activeproxy","navigatorTitle":[{"text":"activeProxy","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol/modifyRequest(_:)":{"kind":"symbol","type":"topic","role":"symbol","title":"modifyRequest(_:)","navigatorTitle":[{"kind":"identifier","text":"modifyRequest:"}],"required":true,"abstract":[],"url":"\/documentation\/ovkit\/videoproxyprotocol\/modifyrequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modifyRequest"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation10URLRequestV","kind":"typeIdentifier","text":"URLRequest"},{"text":") -> ","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/modifyRequest(_:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol","url":"\/documentation\/ovkit\/videoproxyprotocol","abstract":[],"title":"VideoProxyProtocol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoProxyProtocol"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoProxyProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoProxyProtocol/handle(_:completionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/handle(_:completionHandler:)","url":"\/documentation\/ovkit\/videoproxyprotocol\/handle(_:completionhandler:)","navigatorTitle":[{"text":"handle:completionHandler:","kind":"identifier"}],"type":"topic","required":true,"role":"symbol","title":"handle(_:completionHandler:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"VideoProxyProtocol"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"VideoProxyProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"VideoProxyProtocol"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/activeProxy"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/handle(_:completionHandler:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoProxyProtocol\/modifyRequest(_:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"VideoProxyProtocol","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"activeProxy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1activeProxy\/title","op":"replace"},{"value":[{"kind":"identifier","text":"activeProxy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1activeProxy\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1modifyRequest(_:)\/title","value":"modifyRequest:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"modifyRequest:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1modifyRequest(_:)\/fragments","op":"replace"},{"op":"replace","value":"VideoProxyProtocol","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"VideoProxyProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/fragments","op":"replace"},{"value":[{"text":"VideoProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1handle(_:completionHandler:)\/title","op":"replace","value":"handle:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"handle:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoProxyProtocol~1handle(_:completionHandler:)\/fragments"}]}]}