{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/SY"],"title":"Conforms To"}],"abstract":[{"type":"text","text":"Тип видеозаписи."}],"metadata":{"symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"modules":[{"name":"OVKit"}],"roleHeading":"Enumeration","externalID":"c:@M@OVKit@E@OVKVideoCategory","title":"VideoCategory","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoCategory","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/videocategory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videocategory"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideoCategory) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCategory"}],"platforms":["iOS"]}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/clip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/music","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/story","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/video"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/Equatable-Implementations","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/clip":{"url":"\/documentation\/ovkit\/videocategory\/clip","role":"symbol","type":"topic","title":"VideoCategory.clip","kind":"symbol","abstract":[{"text":"Клип – короткое видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/clip","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryClip"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/ovkit\/videocategory\/init(rawvalue:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/Se":{"identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/Equatable-Implementations":{"url":"\/documentation\/ovkit\/videocategory\/equatable-implementations","role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/Equatable-Implementations"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/music":{"url":"\/documentation\/ovkit\/videocategory\/music","kind":"symbol","title":"VideoCategory.music","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/music","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryMusic"}],"abstract":[{"type":"text","text":"Музыкальное видео."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"music"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/story":{"url":"\/documentation\/ovkit\/videocategory\/story","role":"symbol","type":"topic","title":"VideoCategory.story","kind":"symbol","abstract":[{"text":"Видео-история.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/story","navigatorTitle":[{"text":"OVKVideoCategoryStory","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"story","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/videocategory\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://onevideo.OVKit/SY":{"identifier":"doc:\/\/onevideo.OVKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"url":"\/documentation\/ovkit\/videocategory","role":"symbol","type":"topic","title":"VideoCategory","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","abstract":[{"text":"Тип видеозаписи.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCategory"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/init(from:)":{"kind":"symbol","url":"\/documentation\/ovkit\/videocategory\/init(from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/init(from:)","title":"init(from:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/video":{"url":"\/documentation\/ovkit\/videocategory\/video","role":"symbol","type":"topic","title":"VideoCategory.video","kind":"symbol","abstract":[{"type":"text","text":"Обычное видео или прямая трансляция."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/video","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"video","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoCategory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKVideoCategory","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKVideoCategory","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/clip","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/music","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/story","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/video"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKVideoCategory","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1clip\/title","value":"OVKVideoCategoryClip"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1clip\/fragments","value":[{"text":"OVKVideoCategoryClip","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1music\/title","value":"OVKVideoCategoryMusic"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1music\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategoryMusic"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1story\/title","value":"OVKVideoCategoryStory"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1story\/fragments","value":[{"text":"OVKVideoCategoryStory","kind":"identifier"}]},{"value":"OVKVideoCategory","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title"},{"value":[{"kind":"identifier","text":"OVKVideoCategory"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments"},{"value":[{"text":"OVKVideoCategory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/navigatorTitle"},{"value":"OVKVideoCategoryVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1video\/title"},{"value":[{"text":"OVKVideoCategoryVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1video\/fragments"}]}]}