{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/videofileformatobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videofileformatobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"VideoFileFormatObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormatObjC","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@OVKit@objc(cs)OVKVideoFileFormatObjC","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormatObjC"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideoFileFormatObjC) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormatObjC"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/enumerateCases(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/rawValue(of:)"],"anchor":"Type-Methods"}],"references":{"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC/rawValue(of:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/rawValue(of:)","navigatorTitle":[{"kind":"identifier","text":"rawValueOf:"}],"abstract":[],"url":"\/documentation\/ovkit\/videofileformatobjc\/rawvalue(of:)","title":"rawValue(of:)","role":"symbol","type":"topic"},"doc://onevideo.OVKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoFileFormatObjC/init":{"abstract":[],"url":"\/documentation\/ovkit\/ovkvideofileformatobjc\/init","title":"init","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoFileFormatObjC\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC":{"abstract":[],"url":"\/documentation\/ovkit\/videofileformatobjc","title":"VideoFileFormatObjC","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormatObjC","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"VideoFileFormatObjC","kind":"identifier"}]},"doc://onevideo.OVKit/SH":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH","title":"Swift.Hashable"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC/enumerateCases(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"enumerateCases:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformatobjc\/enumeratecases(_:)","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/enumerateCases(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumerateCases","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ValueBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit10ValueBlocka"},{"text":"<","kind":"text"},{"text":"VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":">)","kind":"text"}],"title":"enumerateCases(_:)"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoFileFormatObjC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"OVKVideoFileFormatObjC","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoFileFormatObjC\/init"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/enumerateCases(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/rawValue(of:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoFileFormatObjC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1rawValue(of:)\/title","value":"rawValueOf:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1rawValue(of:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"rawValueOf:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/title","value":"OVKVideoFileFormatObjC"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1enumerateCases(_:)\/title","value":"enumerateCases:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1enumerateCases(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enumerateCases:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}