{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"VideoRestriction","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoRestriction","title":"VideoRestriction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","modules":[{"name":"OVKit"}]},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/actionButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/blur","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPlay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPreview","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/cardIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/disclaimerType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/listIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/muteInfoLink","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/title"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/isEqual(_:)"],"anchor":"Instance-Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestriction"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(OVKVideoRestriction) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/muteInfoLink":{"navigatorTitle":[{"kind":"identifier","text":"muteInfoLink"}],"url":"\/documentation\/ovkit\/videorestriction\/muteinfolink","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/muteInfoLink","type":"topic","title":"muteInfoLink","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Ссылка на информацию о том, почему в данном видео нельзя воспроизвести звук."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteInfoLink"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/title":{"navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/ovkit\/videorestriction\/title","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/title","type":"topic","title":"title","role":"symbol","abstract":[{"text":"Заголовок баннера.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/canPreview":{"navigatorTitle":[{"kind":"identifier","text":"canPreview"}],"url":"\/documentation\/ovkit\/videorestriction\/canpreview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPreview","type":"topic","title":"canPreview","role":"symbol","abstract":[{"text":"Можно ли показывать превью изображение на ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:"}],"url":"\/documentation\/ovkit\/videorestriction\/init(title:text:blur:canplay:canpreview:muteinfolink:disclaimertype:actionbutton:cardicon:listicon:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","type":"topic","title":"init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"blur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"canPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"muteInfoLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"disclaimerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton","text":"VideoRestrictionButton"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cardIcon"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset","text":"ImageAsset"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"listIcon"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKImageAsset","text":"ImageAsset"},{"kind":"text","text":"])"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/text":{"navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/ovkit\/videorestriction\/text","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/text","type":"topic","title":"text","role":"symbol","abstract":[{"text":"Текст баннера.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/actionButton":{"navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"url":"\/documentation\/ovkit\/videorestriction\/actionbutton","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/actionButton","type":"topic","title":"actionButton","role":"symbol","abstract":[{"text":"Модель кнопки для снятия запрета.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/description":{"url":"\/documentation\/ovkit\/videorestriction\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/description","kind":"symbol","title":"description","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/cardIcon":{"url":"\/documentation\/ovkit\/videorestriction\/cardicon","navigatorTitle":[{"kind":"identifier","text":"cardIcon"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIcon"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/cardIcon","kind":"symbol","title":"cardIcon","role":"symbol"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/Se":{"identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/isEqual(_:)":{"url":"\/documentation\/ovkit\/videorestriction\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/isEqual(_:)","kind":"symbol","title":"isEqual(_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/canPlay":{"url":"\/documentation\/ovkit\/videorestriction\/canplay","navigatorTitle":[{"kind":"identifier","text":"canPlay"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Можно ли запускать воспроизведение.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPlay","kind":"symbol","title":"canPlay","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/listIcon":{"navigatorTitle":[{"text":"listIcon","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestriction\/listicon","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/listIcon","type":"topic","title":"listIcon","role":"symbol","abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"listIcon"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/init(from:)":{"url":"\/documentation\/ovkit\/videorestriction\/init(from:)","title":"init(from:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(from:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/blur":{"navigatorTitle":[{"text":"blur","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestriction\/blur","title":"blur","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/blur","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Нужно ли блюрить превью изображение на "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blur","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestrictiontype","title":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction/disclaimerType":{"navigatorTitle":[{"text":"disclaimerType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videorestriction\/disclaimertype","title":"disclaimerType","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/disclaimerType","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Идентификатор типа запрещающего баннера."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disclaimerType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestriction":{"url":"\/documentation\/ovkit\/videorestriction","navigatorTitle":[{"kind":"identifier","text":"VideoRestriction"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestriction"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction","kind":"symbol","title":"VideoRestriction","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKVideoRestriction","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKVideoRestriction","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"OVKVideoRestriction","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/actionButton","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/blur","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPlay","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/canPreview","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/cardIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/disclaimerType","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/listIcon","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/muteInfoLink","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/title"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestriction\/isEqual(_:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoRestriction"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"muteInfoLink","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1muteInfoLink\/title"},{"op":"replace","value":[{"text":"muteInfoLink","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1muteInfoLink\/fragments"},{"op":"replace","value":"title","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1title\/title"},{"op":"replace","value":[{"text":"title","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1title\/fragments"},{"op":"replace","value":"canPreview","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1canPreview\/title"},{"op":"replace","value":[{"text":"canPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1canPreview\/fragments"},{"op":"replace","value":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTitle:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1init(title:text:blur:canPlay:canPreview:muteInfoLink:disclaimerType:actionButton:cardIcon:listIcon:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1text\/title"},{"op":"replace","value":[{"text":"text","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1text\/fragments"},{"op":"replace","value":"actionButton","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1actionButton\/title"},{"op":"replace","value":[{"text":"actionButton","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1actionButton\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1description\/fragments"},{"op":"replace","value":"cardIcon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1cardIcon\/title"},{"op":"replace","value":[{"text":"cardIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1cardIcon\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1isEqual(_:)\/fragments"},{"op":"replace","value":"canPlay","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1canPlay\/title"},{"op":"replace","value":[{"text":"canPlay","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1canPlay\/fragments"},{"op":"replace","value":"listIcon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1listIcon\/title"},{"op":"replace","value":[{"text":"listIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1listIcon\/fragments"},{"op":"replace","value":"blur","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1blur\/title"},{"op":"replace","value":[{"text":"blur","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1blur\/fragments"},{"op":"replace","value":"OVKVideoRestrictionType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title"},{"op":"replace","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments"},{"op":"replace","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle"},{"value":"disclaimerType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1disclaimerType\/title","op":"replace"},{"op":"replace","value":[{"text":"disclaimerType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction~1disclaimerType\/fragments"},{"op":"replace","value":"OVKVideoRestriction","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/title"},{"op":"replace","value":[{"text":"OVKVideoRestriction","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/fragments"},{"value":[{"text":"OVKVideoRestriction","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestriction\/navigatorTitle","op":"replace"}]}]}