{"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/init(slot:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/adSections","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/fromFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/params","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/sitezone","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/slot","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/timeout","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/viewType"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/isEqual(_:)"]},{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/all","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/midroll","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/postroll","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/preroll"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds"},"metadata":{"roleHeading":"Class","title":"VideoAds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAds"}],"symbolKind":"class","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKVideoAds","navigatorTitle":[{"text":"VideoAds","kind":"identifier"}]},"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideoAds) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAds"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"variants":[{"paths":["\/documentation\/ovkit\/videoads"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videoads"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAds/postroll":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postroll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"postroll","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/postroll","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videoads\/postroll","navigatorTitle":[{"text":"postroll","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/init(from:)":{"title":"init(from:)","url":"\/documentation\/ovkit\/videoads\/init(from:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/init(from:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/viewType":{"kind":"symbol","title":"viewType","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/viewType","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/videoads\/viewtype","navigatorTitle":[{"kind":"identifier","text":"viewType"}]},"doc://onevideo.OVKit/objc(cs)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/sitezone":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/sitezone","type":"topic","title":"sitezone","url":"\/documentation\/ovkit\/videoads\/sitezone","navigatorTitle":[{"text":"sitezone","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sitezone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/all":{"role":"symbol","url":"\/documentation\/ovkit\/videoads\/all","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/all","navigatorTitle":[{"text":"all","kind":"identifier"}],"title":"all","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/onevideo.OVKit\/Se"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/isEqual(_:)":{"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/isEqual(_:)","url":"\/documentation\/ovkit\/videoads\/isequal(_:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/init(slot:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSlot:"}],"role":"symbol","title":"init(slot:)","abstract":[],"url":"\/documentation\/ovkit\/videoads\/init(slot:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/init(slot:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/preroll":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preroll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"preroll","kind":"identifier"}],"title":"preroll","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/preroll","url":"\/documentation\/ovkit\/videoads\/preroll","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/midroll":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"midroll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"midroll"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/midroll","url":"\/documentation\/ovkit\/videoads\/midroll","title":"midroll","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdsType"}],"url":"\/documentation\/ovkit\/videoadstype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","abstract":[],"role":"symbol","title":"VideoAdsType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/timeout":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/timeout","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"type":"topic","title":"timeout","url":"\/documentation\/ovkit\/videoads\/timeout","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"timeout"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoAds":{"title":"VideoAds","navigatorTitle":[{"text":"VideoAds","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds","url":"\/documentation\/ovkit\/videoads","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAds","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/slot":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/slot","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"slot"}],"title":"slot","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/videoads\/slot"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/adSections":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSections","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"adSections","navigatorTitle":[{"text":"adSections","kind":"identifier"}],"url":"\/documentation\/ovkit\/videoads\/adsections","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/adSections"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/fromFullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/fromFullscreen","navigatorTitle":[{"kind":"identifier","text":"fromFullscreen"}],"url":"\/documentation\/ovkit\/videoads\/fromfullscreen","abstract":[],"kind":"symbol","type":"topic","title":"fromFullscreen","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromFullscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds/params":{"url":"\/documentation\/ovkit\/videoads\/params","navigatorTitle":[{"text":"params","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"params","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/params","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"params","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://onevideo.OVKit/SH":{"identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://onevideo.OVKit/SQ":{"identifier":"doc:\/\/onevideo.OVKit\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoAds","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKVideoAds"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoAds"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/adSections","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/fromFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/params","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/sitezone","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/slot","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/timeout","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/viewType"]},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/init(slot:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/all","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/midroll","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/postroll","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds\/preroll"],"anchor":"Type-Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoAds"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"postroll","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1postroll\/title"},{"value":[{"text":"postroll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1postroll\/fragments"},{"value":"viewType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1viewType\/title"},{"value":[{"text":"viewType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1viewType\/fragments"},{"value":"sitezone","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1sitezone\/title"},{"value":[{"kind":"identifier","text":"sitezone"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1sitezone\/fragments"},{"value":"all","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1all\/title"},{"value":[{"text":"all","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1all\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1isEqual(_:)\/fragments"},{"value":"initWithSlot:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1init(slot:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSlot:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1init(slot:)\/fragments"},{"value":"preroll","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1preroll\/title"},{"value":[{"text":"preroll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1preroll\/fragments"},{"value":"midroll","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1midroll\/title"},{"value":[{"text":"midroll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1midroll\/fragments"},{"value":"OVKVideoAdsType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title"},{"value":[{"kind":"identifier","text":"OVKVideoAdsType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments"},{"value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle"},{"value":"timeout","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1timeout\/title"},{"value":[{"kind":"identifier","text":"timeout"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1timeout\/fragments"},{"value":"OVKVideoAds","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/title"},{"value":[{"text":"OVKVideoAds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/fragments"},{"value":[{"text":"OVKVideoAds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/navigatorTitle"},{"value":"slot","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1slot\/title"},{"value":[{"kind":"identifier","text":"slot"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1slot\/fragments"},{"value":"adSections","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1adSections\/title"},{"value":[{"text":"adSections","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1adSections\/fragments"},{"value":"fromFullscreen","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1fromFullscreen\/title"},{"value":[{"text":"fromFullscreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1fromFullscreen\/fragments"},{"value":"params","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1params\/title"},{"value":[{"text":"params","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds~1params\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}