{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(OVKVideoStatsHandler) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoStatsHandler","kind":"identifier"},{"kind":"text","text":" : "},{"text":"StatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"}]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/downloadBytes(bytes:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/emptyBuffer(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstBytes(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstFrame(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/modeChange()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackError(_:recoverable:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackStarted()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playerReady(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/seek(method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/soundOn(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoQuality(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/viewport(size:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/visibility(isInBackground:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/watchCoverage(fromTime:toTime:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videostatshandler"]},{"paths":["\/documentation\/ovkit\/videostatshandler"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OVKit"}],"title":"VideoStatsHandler","roleHeading":"Protocol","externalID":"c:@M@OVKit@objc(pl)OVKVideoStatsHandler","symbolKind":"protocol","navigatorTitle":[{"text":"VideoStatsHandler","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]},{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]}],"seeAlsoSections":[{"anchor":"Статистика","title":"Статистика","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"],"generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/soundOn(_:userInitiated:)":{"abstract":[{"text":"Изменилось состояние звука.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"soundOn:userInitiated:"}],"url":"\/documentation\/ovkit\/videostatshandler\/soundon(_:userinitiated:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/soundOn(_:userInitiated:)","title":"soundOn(_:userInitiated:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/subtitles(_:)":{"title":"subtitles(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/subtitles(_:)","url":"\/documentation\/ovkit\/videostatshandler\/subtitles(_:)","abstract":[{"type":"text","text":"Пользователь включил, отключил или изменил язык субтитров."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitles:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/seek(method:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/seek(method:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/seek(method:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seek"},{"kind":"text","text":"("},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatsSeekMethod","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Пользователь перемотал видео."}],"title":"seek(method:)","navigatorTitle":[{"text":"seekWithMethod:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/didCloseFullscreen()":{"kind":"symbol","title":"didCloseFullscreen()","navigatorTitle":[{"kind":"identifier","text":"didCloseFullscreen"}],"abstract":[{"type":"text","text":"Произошел выход из полноэкранного режима."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didCloseFullscreen()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCloseFullscreen"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/ovkit\/videostatshandler\/didclosefullscreen()"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"url":"\/documentation\/ovkit\/adstatshandler","abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","kind":"symbol","title":"AdStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","title":"StatsContext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/watchCoverage(fromTime:toTime:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchCoverage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}],"url":"\/documentation\/ovkit\/videostatshandler\/watchcoverage(fromtime:totime:)","title":"watchCoverage(fromTime:toTime:)","abstract":[{"text":"Непрерывно просмотренные отрезки видео.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/watchCoverage(fromTime:toTime:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/start(fromTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/start(fromTime:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/start(fromtime:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Видео начало играть в плеере, не важно userInitiated или нет."}],"title":"start(fromTime:)","navigatorTitle":[{"kind":"identifier","text":"startFromTime:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/videoQuality(_:userInitiated:)":{"navigatorTitle":[{"kind":"identifier","text":"videoQuality:userInitiated:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoQuality(_:userInitiated:)","url":"\/documentation\/ovkit\/videostatshandler\/videoquality(_:userinitiated:)","role":"symbol","kind":"symbol","title":"videoQuality(_:userInitiated:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoTrackInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoTrackInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Изменилось качество проигрывания."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/didEnterFullscreen()":{"role":"symbol","title":"didEnterFullscreen()","url":"\/documentation\/ovkit\/videostatshandler\/didenterfullscreen()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEnterFullscreen"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didEnterFullscreen()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterFullscreen"},{"kind":"text","text":"()"}],"abstract":[{"text":"Произошел переход в полноэкранный режим.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/playbackError(_:recoverable:from:)":{"title":"playbackError(_:recoverable:from:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackError(_:recoverable:from:)","url":"\/documentation\/ovkit\/videostatshandler\/playbackerror(_:recoverable:from:)","abstract":[{"type":"text","text":"Произошла ошибка воспроизведения."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playbackError:recoverable:from:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recoverable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/firstFrame(time:connectionType:connectionReused:)":{"kind":"symbol","title":"firstFrame(time:connectionType:connectionReused:)","navigatorTitle":[{"kind":"identifier","text":"firstFrameWithTime:connectionType:connectionReused:"}],"abstract":[{"text":"Событие получения первого кадра.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstFrame(time:connectionType:connectionReused:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"connectionType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"connectionReused"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/firstframe(time:connectiontype:connectionreused:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/pause(currentTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/pause(currentTime:)","title":"pause(currentTime:)","abstract":[{"type":"text","text":"Пользователь нажал на паузу в плеере."}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"pauseWithCurrentTime:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/pause(currenttime:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/playerReady(time:connectionType:connectionReused:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playerReady(time:connectionType:connectionReused:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/playerready(time:connectiontype:connectionreused:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Плеер готов играть."}],"title":"playerReady(time:connectionType:connectionReused:)","navigatorTitle":[{"kind":"identifier","text":"playerReadyWithTime:connectionType:connectionReused:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/progressChanged(time:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/progressChanged(time:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"abstract":[{"text":"Текущее время проигрывания изменилось.","type":"text"}],"type":"topic","title":"progressChanged(time:)","url":"\/documentation\/ovkit\/videostatshandler\/progresschanged(time:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"progressChangedWithTime:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/visibility(isInBackground:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/visibility(isInBackground:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[],"title":"visibility(isInBackground:)","type":"topic","url":"\/documentation\/ovkit\/videostatshandler\/visibility(isinbackground:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"visibilityWithIsInBackground:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/failover(backupHost:)":{"title":"failover(backupHost:)","abstract":[{"type":"text","text":"Произошло переключение запросов к ресурсу на резервный хост. Это происходит автоматически при получении некоторых сетевых ошибок."}],"url":"\/documentation\/ovkit\/videostatshandler\/failover(backuphost:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/failover(backupHost:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"failoverWithBackupHost:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupHost","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"title":"VideoStatsHandler","url":"\/documentation\/ovkit\/videostatshandler","navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/playbackStarted()":{"kind":"symbol","title":"playbackStarted()","navigatorTitle":[{"text":"playbackStarted","kind":"identifier"}],"abstract":[{"text":"Плеер начал проигрывание видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackStarted()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackStarted","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/playbackstarted()","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/emptyBuffer(time:connectionType:connectionReused:)":{"title":"emptyBuffer(time:connectionType:connectionReused:)","abstract":[{"type":"text","text":"Плеер подгружал данные для дальнейшего воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/emptyBuffer(time:connectionType:connectionReused:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyBuffer"},{"text":"(","kind":"text"},{"text":"time","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"connectionReused","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"emptyBufferWithTime:connectionType:connectionReused:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/emptybuffer(time:connectiontype:connectionreused:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/videoZoom()":{"title":"videoZoom()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoZoom()","url":"\/documentation\/ovkit\/videostatshandler\/videozoom()","abstract":[{"type":"text","text":"Пользователь активировал зум через жест."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoZoom"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoZoom"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","role":"symbol","navigatorTitle":[{"text":"TimespentStatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/timespentstatshandler","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"}],"title":"TimespentStatsHandler","abstract":[{"type":"text","text":"Принимает события начала и остановки просмотра видео."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/stop(currentTime:stallTime:)":{"navigatorTitle":[{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}],"abstract":[{"text":"Видео закончили смотреть.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/stop(currentTime:stallTime:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"currentTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stallTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/stop(currenttime:stalltime:)","title":"stop(currentTime:stallTime:)"},"doc://onevideo.OVKit/documentation/OVKit/Statistics":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/statistics","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Statistics","title":"Статистика","abstract":[{"text":"Сбор статистики воспроизведения видео.","type":"text"}],"role":"article"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerConsole":{"title":"StatsHandlerConsole","url":"\/documentation\/ovkit\/statshandlerconsole","navigatorTitle":[{"text":"StatsHandlerConsole","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":" для отладки, который будет писать события статистики в консоль."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerConsole","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"abstract":[{"type":"text","text":"Стандартная модель, реализующая "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"Video","url":"\/documentation\/ovkit\/video","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/downloadBytes(bytes:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/downloadBytes(bytes:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/downloadbytes(bytes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadBytes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Событие скачивания определенного количества байт плеером с сервера."}],"title":"downloadBytes(bytes:)","navigatorTitle":[{"kind":"identifier","text":"downloadBytesWithBytes:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/gravity(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/gravity(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/gravity(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gravity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Пользователь руками изменил gravity."}],"type":"topic","title":"gravity(_:)","navigatorTitle":[{"kind":"identifier","text":"gravity:"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/audioTrack(label:language:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"audioTrackWithLabel:language:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/audiotrack(label:language:)","title":"audioTrack(label:language:)","abstract":[{"type":"text","text":"Пользователь сменил аудиодорожку."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/audioTrack(label:language:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/viewport(size:)":{"role":"symbol","url":"\/documentation\/ovkit\/videostatshandler\/viewport(size:)","title":"viewport(size:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewportWithSize:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/viewport(size:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Изменился размер вью плеера на экране."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/reachedEnd()":{"navigatorTitle":[{"text":"reachedEnd","kind":"identifier"}],"abstract":[{"text":"Видео было досмотрено до конца.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/reachedEnd()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reachedEnd","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/reachedend()","title":"reachedEnd()"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statscollector","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Не привязан к ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"или переходах в PiP и fullscreen.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","title":"StatsCollector","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/resume()":{"abstract":[{"text":"Видео было снято с паузы пользователем.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()","url":"\/documentation\/ovkit\/videostatshandler\/resume()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"resume","kind":"identifier"}],"title":"resume()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/firstBytes(time:connectionType:connectionReused:)":{"title":"firstBytes(time:connectionType:connectionReused:)","abstract":[{"text":"Событие получения первых данных из плеера.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstBytes(time:connectionType:connectionReused:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstBytes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connectionReused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videostatshandler\/firstbytes(time:connectiontype:connectionreused:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/playbackSpeed(_:)":{"title":"playbackSpeed(_:)","abstract":[{"text":"Пользователь изменил скорость воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/videostatshandler\/playbackspeed(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackSpeed(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"playbackSpeed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackSpeed"},{"text":"(","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler/modeChange()":{"role":"symbol","title":"modeChange()","url":"\/documentation\/ovkit\/videostatshandler\/modechange()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"modeChange","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/modeChange()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modeChange","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Изменился режим воспроизведения.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoStatsHandler"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/audioTrack(label:language:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didCloseFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/didEnterFullscreen()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/downloadBytes(bytes:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/emptyBuffer(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/failover(backupHost:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstBytes(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/firstFrame(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/gravity(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/modeChange()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/pause(currentTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackError(_:recoverable:from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackSpeed(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playbackStarted()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/playerReady(time:connectionType:connectionReused:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/progressChanged(time:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/reachedEnd()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/resume()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/seek(method:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/soundOn(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/start(fromTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/stop(currentTime:stallTime:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/subtitles(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoQuality(_:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/videoZoom()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/viewport(size:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/visibility(isInBackground:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler\/watchCoverage(fromTime:toTime:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"],"type":"inheritsFrom"},{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerConsole"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Статистика","anchor":"Статистика","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"OVKVideoStatsHandler","kind":"identifier"},{"text":" <","kind":"text"},{"text":"OVKStatsHandler","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsHandler","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"soundOn:userInitiated:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1soundOn(_:userInitiated:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"soundOn:userInitiated:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1soundOn(_:userInitiated:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1subtitles(_:)\/title","op":"replace","value":"subtitles:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1subtitles(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subtitles:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1seek(method:)\/title","value":"seekWithMethod:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1seek(method:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"seekWithMethod:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didCloseFullscreen()\/title","value":"didCloseFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didCloseFullscreen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didCloseFullscreen","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","value":"OVKAdStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsContext"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsContext"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1watchCoverage(fromTime:toTime:)\/title","value":"watchCoverageFromTime:toTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1watchCoverage(fromTime:toTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"watchCoverageFromTime:toTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1start(fromTime:)\/title","value":"startFromTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1start(fromTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startFromTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoQuality(_:userInitiated:)\/title","value":"videoQuality:userInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoQuality(_:userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoQuality:userInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didEnterFullscreen()\/title","value":"didEnterFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1didEnterFullscreen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didEnterFullscreen","kind":"identifier"}]},{"op":"replace","value":"playbackError:recoverable:from:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackError(_:recoverable:from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackError(_:recoverable:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playbackError:recoverable:from:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstFrame(time:connectionType:connectionReused:)\/title","value":"firstFrameWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstFrame(time:connectionType:connectionReused:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"firstFrameWithTime:connectionType:connectionReused:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1pause(currentTime:)\/title","value":"pauseWithCurrentTime:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1pause(currentTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseWithCurrentTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playerReady(time:connectionType:connectionReused:)\/title","value":"playerReadyWithTime:connectionType:connectionReused:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playerReady(time:connectionType:connectionReused:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playerReadyWithTime:connectionType:connectionReused:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1progressChanged(time:)\/title","value":"progressChangedWithTime:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"progressChangedWithTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1progressChanged(time:)\/fragments"},{"op":"replace","value":"visibilityWithIsInBackground:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1visibility(isInBackground:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"visibilityWithIsInBackground:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1visibility(isInBackground:)\/fragments"},{"op":"replace","value":"failoverWithBackupHost:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1failover(backupHost:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"failoverWithBackupHost:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1failover(backupHost:)\/fragments"},{"op":"replace","value":"OVKVideoStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle"},{"op":"replace","value":"playbackStarted","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackStarted()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"playbackStarted","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackStarted()\/fragments"},{"op":"replace","value":"emptyBufferWithTime:connectionType:connectionReused:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1emptyBuffer(time:connectionType:connectionReused:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1emptyBuffer(time:connectionType:connectionReused:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emptyBufferWithTime:connectionType:connectionReused:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoZoom()\/title","op":"replace","value":"videoZoom"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1videoZoom()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoZoom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title","op":"replace","value":"OVKTimespentStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments","op":"replace","value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKTimespentStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1stop(currentTime:stallTime:)\/title","op":"replace","value":"stopWithCurrentTime:stallTime:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1stop(currentTime:stallTime:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"stopWithCurrentTime:stallTime:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace","value":"OVKStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/title","op":"replace","value":"OVKStatsHandlerConsole"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/fragments","op":"replace","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerConsole\/navigatorTitle","value":[{"text":"OVKStatsHandlerConsole","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]},{"op":"replace","value":"downloadBytesWithBytes:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1downloadBytes(bytes:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1downloadBytes(bytes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"downloadBytesWithBytes:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1gravity(_:)\/title","value":"gravity:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1gravity(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gravity:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1audioTrack(label:language:)\/title","value":"audioTrackWithLabel:language:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1audioTrack(label:language:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioTrackWithLabel:language:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1viewport(size:)\/title","op":"replace","value":"viewportWithSize:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1viewport(size:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewportWithSize:","kind":"identifier"}]},{"op":"replace","value":"reachedEnd","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1reachedEnd()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1reachedEnd()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"reachedEnd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","op":"replace","value":"OVKStatsCollector"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKStatsCollector"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/title","value":"resume"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1resume()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resume","kind":"identifier"}]},{"op":"replace","value":"firstBytesWithTime:connectionType:connectionReused:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstBytes(time:connectionType:connectionReused:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1firstBytes(time:connectionType:connectionReused:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"firstBytesWithTime:connectionType:connectionReused:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackSpeed(_:)\/title","value":"playbackSpeed:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1playbackSpeed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"playbackSpeed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1modeChange()\/title","value":"modeChange"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler~1modeChange()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"modeChange","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}