{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter"},"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/Se","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"VideoChapter","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Class","externalID":"c:@M@OVKit@objc(cs)OVKVideoChapter","title":"VideoChapter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapter"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videochapter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videochapter"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKVideoChapter) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoChapter","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/init(from:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/init(time:text:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/time"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/isEqual(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"url":"\/documentation\/ovkit\/videochaptertype","role":"symbol","type":"topic","title":"VideoChapterType","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","abstract":[{"text":"Модель одного эпизода, на которые может быть поделена видеозапись.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"VideoChapterType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapterType"}]},"doc://onevideo.OVKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/init(from:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/init(from:)","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/videochapter\/init(from:)","type":"topic","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/description","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/videochapter\/description","kind":"symbol","title":"description"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/time":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"time","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"time"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/time","abstract":[{"text":"Время начала эпизода в секундах.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videochapter\/time","kind":"symbol","title":"time"},"doc://onevideo.OVKit/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/onevideo.OVKit\/Se","type":"unresolvable"},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter":{"url":"\/documentation\/ovkit\/videochapter","title":"VideoChapter","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter","navigatorTitle":[{"kind":"identifier","text":"VideoChapter"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapter"}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/text":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/text","abstract":[{"type":"text","text":"Название эпизода."}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videochapter\/text","kind":"symbol","title":"text"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/hash":{"kind":"symbol","title":"hash","url":"\/documentation\/ovkit\/videochapter\/hash","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/init(time:text:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTime:text:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/init(time:text:)","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videochapter\/init(time:text:)","kind":"symbol","title":"init(time:text:)"},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/onevideo.OVKit\/SH","type":"unresolvable"},"doc://onevideo.OVKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP"},"doc://onevideo.OVKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","type":"unresolvable"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/isEqual(_:)":{"url":"\/documentation\/ovkit\/videochapter\/isequal(_:)","title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKVideoChapter","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapter"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapter"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/description","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/hash","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/text","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/time"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/init(time:text:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/isEqual(_:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKVideoChapter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKVideoChapterType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1description\/fragments"},{"value":"time","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1time\/title"},{"value":[{"text":"time","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1time\/fragments"},{"value":"OVKVideoChapter","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/title"},{"value":[{"text":"OVKVideoChapter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoChapter"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/navigatorTitle"},{"value":"text","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1text\/title"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1text\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1hash\/fragments"},{"value":"initWithTime:text:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1init(time:text:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTime:text:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1init(time:text:)\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1isEqual(_:)\/fragments"}]}]}