{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(OVKVideoURLQuery) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoURLQuery"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit"]]},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/init(customMinQualityParameterName:customMaxQualityParameterName:)"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMaxQualityParameterName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMinQualityParameterName"],"generated":true,"title":"Instance Properties"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","modules":[{"name":"OVKit"}],"symbolKind":"class","roleHeading":"Class","title":"VideoURLQuery","navigatorTitle":[{"kind":"identifier","text":"VideoURLQuery"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoURLQuery","kind":"identifier"}]},"abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/onevideo.OVKit\/objc(pl)NSObject","doc:\/\/onevideo.OVKit\/s7CVarArgP","doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP","doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP","doc:\/\/onevideo.OVKit\/SQ","doc:\/\/onevideo.OVKit\/SH"],"title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"},"variants":[{"paths":["\/documentation\/ovkit\/videourlquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videourlquery"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery/customMaxQualityParameterName":{"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customMaxQualityParameterName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/videourlquery\/custommaxqualityparametername","abstract":[{"type":"text","text":"Переопределение названия параметра в URL на HLS-манифест для максимально доступного качества."}],"type":"topic","title":"customMaxQualityParameterName","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMaxQualityParameterName","navigatorTitle":[{"text":"customMaxQualityParameterName","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery/customMinQualityParameterName":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMinQualityParameterName","role":"symbol","kind":"symbol","title":"customMinQualityParameterName","url":"\/documentation\/ovkit\/videourlquery\/customminqualityparametername","abstract":[{"text":"Переопределение названия параметра в URL на HLS-манифест для минимально доступного качества.","type":"text"}],"navigatorTitle":[{"text":"customMinQualityParameterName","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"customMinQualityParameterName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SH"},"doc://onevideo.OVKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s23CustomStringConvertibleP"},"doc://onevideo.OVKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(pl)NSObject"},"doc://onevideo.OVKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/SQ","title":"Swift.Equatable"},"doc://onevideo.OVKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/onevideo.OVKit\/objc(cs)NSObject","title":"NSObject"},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoURLQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/videourlquery","abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"title":"VideoURLQuery","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","navigatorTitle":[{"kind":"identifier","text":"VideoURLQuery"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery/init(customMinQualityParameterName:customMaxQualityParameterName:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/init(customMinQualityParameterName:customMaxQualityParameterName:)","role":"symbol","kind":"symbol","title":"init(customMinQualityParameterName:customMaxQualityParameterName:)","url":"\/documentation\/ovkit\/videourlquery\/init(customminqualityparametername:custommaxqualityparametername:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"customMinQualityParameterName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"customMaxQualityParameterName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://onevideo.OVKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/onevideo.OVKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoURLQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"OVKVideoURLQuery","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"OVKVideoURLQuery","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMaxQualityParameterName","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMinQualityParameterName"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/init(customMinQualityParameterName:customMaxQualityParameterName:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKVideoURLQuery","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"customMaxQualityParameterName","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMaxQualityParameterName\/title"},{"value":[{"text":"customMaxQualityParameterName","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMaxQualityParameterName\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMinQualityParameterName\/title","value":"customMinQualityParameterName"},{"value":[{"text":"customMinQualityParameterName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMinQualityParameterName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","value":"OVKVideoURLQuery"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments","op":"replace","value":[{"text":"OVKVideoURLQuery","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/navigatorTitle"},{"op":"replace","value":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1init(customMinQualityParameterName:customMaxQualityParameterName:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1init(customMinQualityParameterName:customMaxQualityParameterName:)\/fragments","op":"replace"}]}]}