{"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)chapters","required":true,"title":"chapters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"chapters","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/chapters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/chapters"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/chapters","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"url":"\/documentation\/ovkit\/videotype","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/chapters":{"required":true,"kind":"symbol","title":"chapters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","text":"VideoChapterType"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/chapters","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"chapters"}],"url":"\/documentation\/ovkit\/videotype\/chapters","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"navigatorTitle":[{"kind":"identifier","text":"VideoChapterType"}],"url":"\/documentation\/ovkit\/videochaptertype","kind":"symbol","title":"VideoChapterType","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoChapterType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"chapters","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"chapters","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<OVKVideoChapterType>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"chapters","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1chapters\/title","value":"chapters","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1chapters\/fragments","value":[{"kind":"identifier","text":"chapters"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","value":"OVKVideoChapterType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"op":"replace"}]}]}