{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isMobileLive"},"abstract":[{"text":"Является ли видеозапись прямой трансляцией с мобильного устройства.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMobileLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/ismobilelive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/ismobilelive"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"isMobileLive","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMobileLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"required":true,"title":"isMobileLive","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)isMobileLive"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","title":"VideoType","type":"topic","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/isMobileLive":{"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isMobileLive","url":"\/documentation\/ovkit\/videotype\/ismobilelive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMobileLive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isMobileLive","kind":"identifier"}],"kind":"symbol","title":"isMobileLive","role":"symbol","abstract":[{"type":"text","text":"Является ли видеозапись прямой трансляцией с мобильного устройства."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isMobileLive"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isMobileLive","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"isMobileLive","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isMobileLive\/title","value":"isMobileLive","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isMobileLive\/fragments","value":[{"kind":"identifier","text":"isMobileLive"}]}]}]}