{"abstract":[{"text":"Является ли видеозапись сферическим 360-видео.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/isspherical"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/isspherical"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isSpherical","interfaceLanguage":"swift"},"metadata":{"required":true,"title":"isSpherical","role":"symbol","navigatorTitle":[{"text":"isSpherical","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)isSpherical","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpherical","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpherical","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/isSpherical":{"navigatorTitle":[{"text":"isSpherical","kind":"identifier"}],"type":"topic","abstract":[{"text":"Является ли видеозапись сферическим 360-видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/isSpherical","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/videotype\/isspherical","title":"isSpherical","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpherical","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","title":"VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isSpherical","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isSpherical"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpherical"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isSpherical","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isSpherical\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isSpherical"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1isSpherical\/fragments","op":"replace"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"}]}]}