{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSettingsUpdate(with:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Обновляет состояние прямой трансляции.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/livesettingsupdate(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/livesettingsupdate(with:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettingsUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxRewindDuration"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Максимальный интервал, на который можно отмотать прямую трансляцию."}],"type":"paragraph"}],"name":"maxRewindDuration"}],"kind":"parameters"}],"metadata":{"required":true,"title":"liveSettingsUpdate(with:)","navigatorTitle":[{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(im)liveSettingsUpdateWith:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSettingsUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveSettingsUpdate(with:)":{"required":true,"title":"liveSettingsUpdate(with:)","navigatorTitle":[{"kind":"identifier","text":"liveSettingsUpdateWith:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSettingsUpdate(with:)","url":"\/documentation\/ovkit\/videotype\/livesettingsupdate(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSettingsUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Обновляет состояние прямой трансляции."}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","title":"VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"liveSettingsUpdateWith:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"liveSettingsUpdateWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxRewindDuration"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"parameters":[{"name":"maxRewindDuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Максимальный интервал, на который можно отмотать прямую трансляцию."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"liveSettingsUpdateWith:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSettingsUpdate(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"liveSettingsUpdateWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSettingsUpdate(with:)\/fragments"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}]}]}