{"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)liveStartTimestamp","navigatorTitle":[{"text":"liveStartTimestamp","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"liveStartTimestamp","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","required":true,"title":"liveStartTimestamp"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStartTimestamp","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"liveStartTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/videotype\/livestarttimestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/livestarttimestamp"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveStartTimestamp":{"title":"liveStartTimestamp","url":"\/documentation\/ovkit\/videotype\/livestarttimestamp","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveStartTimestamp"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"required":true,"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStartTimestamp"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videotype","title":"VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"liveStartTimestamp","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"liveStartTimestamp"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"liveStartTimestamp","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStartTimestamp\/title","value":"liveStartTimestamp"},{"value":[{"text":"liveStartTimestamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStartTimestamp\/fragments"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}]}]}]}