{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"liveRewindMaxSeconds"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveRewindMaxSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"required":true,"title":"liveRewindMaxSeconds","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)liveRewindMaxSeconds","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveRewindMaxSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Для обычных видеозаписей не актуально.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/videotype\/liverewindmaxseconds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videotype\/liverewindmaxseconds"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveRewindMaxSeconds"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"sections":[],"abstract":[{"type":"text","text":"Интервал, на который возможна перемотка прямой трансляции назад."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveRewindMaxSeconds":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveRewindMaxSeconds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Интервал, на который возможна перемотка прямой трансляции назад.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveRewindMaxSeconds","title":"liveRewindMaxSeconds","required":true,"role":"symbol","navigatorTitle":[{"text":"liveRewindMaxSeconds","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype\/liverewindmaxseconds"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","role":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"kind":"symbol","url":"\/documentation\/ovkit\/videotype","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"liveRewindMaxSeconds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"liveRewindMaxSeconds","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveRewindMaxSeconds"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveRewindMaxSeconds\/title","value":"liveRewindMaxSeconds"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveRewindMaxSeconds\/fragments","value":[{"kind":"identifier","text":"liveRewindMaxSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}]}]}]}