{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"liveStatus","kind":"identifier"}],"title":"liveStatus","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)liveStatus","required":true,"modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"text":": ","kind":"text"},{"text":"LiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}]},"variants":[{"paths":["\/documentation\/ovkit\/videotype\/livestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/livestatus"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"liveStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStatus","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"kind":"symbol","title":"LiveStatus","url":"\/documentation\/ovkit\/livestatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveStatus":{"title":"liveStatus","url":"\/documentation\/ovkit\/videotype\/livestatus","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"liveStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"}],"required":true,"navigatorTitle":[{"text":"liveStatus","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveStatus"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic","role":"symbol","title":"VideoType","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"liveStatus"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"liveStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"OVKLiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"OVKLiveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","op":"replace","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"value":"liveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveStatus\/fragments","op":"replace","value":[{"text":"liveStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"}]}]}