{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSpectators"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Для обычных видеозаписей не актуально."}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSpectators","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"metadata":{"navigatorTitle":[{"text":"liveSpectators","kind":"identifier"}],"required":true,"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSpectators","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)liveSpectators","title":"liveSpectators","role":"symbol","symbolKind":"property"},"abstract":[{"type":"text","text":"Количество зрителей прямой трансляции."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/livespectators"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/livespectators"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/liveSpectators":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/liveSpectators","kind":"symbol","navigatorTitle":[{"text":"liveSpectators","kind":"identifier"}],"abstract":[{"type":"text","text":"Количество зрителей прямой трансляции."}],"url":"\/documentation\/ovkit\/videotype\/livespectators","required":true,"role":"symbol","title":"liveSpectators","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveSpectators","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"kind":"symbol","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"liveSpectators","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"liveSpectators"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveSpectators"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"liveSpectators","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSpectators\/title"},{"op":"replace","value":[{"kind":"identifier","text":"liveSpectators"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1liveSpectators\/fragments"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}