{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setVideoURL:for:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(im)setVideoURL:for:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVideoURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"title":"setVideoURL(_:for:)"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/setVideoURL(_:for:)"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVideoURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"variants":[{"paths":["\/documentation\/ovkit\/videotype\/setvideourl(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videotype\/setvideourl(_:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/setVideoURL(_:for:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/setVideoURL(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVideoURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setVideoURL(_:for:)","required":true,"role":"symbol","url":"\/documentation\/ovkit\/videotype\/setvideourl(_:for:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"setVideoURL:for:","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","role":"symbol","url":"\/documentation\/ovkit\/videotype","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat","title":"VideoFileFormat","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setVideoURL:for:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoURL:for:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setVideoURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"for:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"OVKVideoFileFormat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"setVideoURL:for:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1setVideoURL(_:for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setVideoURL:for:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1setVideoURL(_:for:)\/fragments"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"op":"replace","value":"OVKVideoFileFormat","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments"},{"op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}