{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}],"required":true,"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)videoUrlQuery","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","text":"VideoURLQuery","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"videoUrlQuery"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/videourlquery"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/videourlquery"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoUrlQuery","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoURLQuery","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoUrlQuery":{"url":"\/documentation\/ovkit\/videotype\/videourlquery","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoUrlQuery","navigatorTitle":[{"text":"videoUrlQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoURLQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery"},{"text":"?","kind":"text"}],"title":"videoUrlQuery","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"navigatorTitle":[{"kind":"identifier","text":"VideoURLQuery"}],"url":"\/documentation\/ovkit\/videourlquery","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","type":"topic","title":"VideoURLQuery","role":"symbol","abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoURLQuery"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"videoUrlQuery","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKVideoURLQuery","text":"OVKVideoURLQuery","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"videoUrlQuery","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoUrlQuery\/title","value":"videoUrlQuery","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoUrlQuery\/fragments","value":[{"kind":"identifier","text":"videoUrlQuery"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","value":"OVKVideoURLQuery","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments","value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace"}]}]}