{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoAds","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoAds","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","kind":"typeIdentifier","text":"VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoAds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)videoAds","title":"videoAds","role":"symbol","modules":[{"name":"OVKit"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"videoAds"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/videotype\/videoads"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/videoads"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"role":"symbol","title":"VideoAdsType","kind":"symbol","url":"\/documentation\/ovkit\/videoadstype","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdsType","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","kind":"symbol","title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoAds":{"url":"\/documentation\/ovkit\/videotype\/videoads","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoAds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoAds","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"videoAds","abstract":[],"role":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"videoAds","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"videoAds","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"videoAds","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoAdsType","text":"id<OVKVideoAdsType>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoAds"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title","value":"OVKVideoAdsType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoAds\/title","value":"videoAds"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoAds\/fragments","value":[{"kind":"identifier","text":"videoAds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}