{"abstract":[{"type":"text","text":"Модель баннера, запрещающего просмотр."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRestriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"videoRestriction"}],"required":true,"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKVideoType(py)videoRestriction","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRestriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier","text":"VideoRestrictionType"},{"kind":"text","text":"?"}],"title":"videoRestriction"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videotype\/videorestriction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videotype\/videorestriction"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoRestriction":{"url":"\/documentation\/ovkit\/videotype\/videorestriction","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRestriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"videoRestriction"}],"abstract":[{"type":"text","text":"Модель баннера, запрещающего просмотр."}],"role":"symbol","title":"videoRestriction","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"url":"\/documentation\/ovkit\/videorestrictiontype","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Модель баннера, запрещающего просмотр."}],"role":"symbol","title":"VideoRestrictionType"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"kind":"symbol","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"title":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoRestriction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"videoRestriction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKVideoRestrictionType>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"text":" ","kind":"text"},{"text":"videoRestriction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/title","value":"videoRestriction"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/fragments","value":[{"text":"videoRestriction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"text":"OVKVideoType","kind":"identifier"}]}]}]}