{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct"]]},"metadata":{"symbolKind":"property","externalID":"s:5OVKit12StatsContextC11LiveLatencyV28downloadingEncoderIngestDate10Foundation0I0VSgvp","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadingEncoderIngestDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"title":"downloadingEncoderIngestDate","roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Время, когда загружаемый в момент "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate"},{"type":"text","text":" кадр был получен на транскодере."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadingEncoderIngestDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/downloadingencoderingestdate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/downloadingEncoderIngestDate"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct/downloadingEncoderIngestDate":{"url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/downloadingencoderingestdate","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadingEncoderIngestDate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Время, когда загружаемый в момент "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate","type":"reference","isActive":true},{"type":"text","text":" кадр был получен на транскодере."}],"title":"downloadingEncoderIngestDate","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/downloadingEncoderIngestDate"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct":{"title":"StatsContext.LiveLatency","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveLatency"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LiveLatency"}],"abstract":[{"text":"Данные о задержке потока воспроизведения до автора трансляции.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct/sampleDate":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate","title":"sampleDate","url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/sampledate","abstract":[{"text":"Момент времени, когда был произведен сбор данных о задержке.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsContext"}],"abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","title":"StatsContext","role":"symbol","navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscontext"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}