{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/playingEncoderIngestDate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingEncoderIngestDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol","externalID":"s:5OVKit12StatsContextC11LiveLatencyV24playingEncoderIngestDate10Foundation0I0VSgvp","title":"playingEncoderIngestDate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingEncoderIngestDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"abstract":[{"text":"Время, когда проигрываемый в момент ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate","isActive":true,"type":"reference"},{"text":" кадр был получен на транскодере.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/playingencoderingestdate"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct/playingEncoderIngestDate":{"url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/playingencoderingestdate","title":"playingEncoderIngestDate","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/playingEncoderIngestDate","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingEncoderIngestDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Время, когда проигрываемый в момент ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate","isActive":true,"type":"reference"},{"text":" кадр был получен на транскодере.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"title":"StatsContext","url":"\/documentation\/ovkit\/statscontext","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"kind":"symbol","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct/sampleDate":{"url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct\/sampledate","title":"sampleDate","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct\/sampleDate","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sampleDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Момент времени, когда был произведен сбор данных о задержке.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct":{"title":"StatsContext.LiveLatency","url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveLatency","kind":"identifier"}],"navigatorTitle":[{"text":"LiveLatency","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Данные о задержке потока воспроизведения до автора трансляции."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"}]}]}