{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"countTotal","kind":"identifier"}],"required":true,"symbolKind":"property","role":"symbol","title":"countTotal","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType(py)countTotal"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType\/countTotal","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/timelinethumbnailstype\/counttotal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timelinethumbnailstype\/counttotal"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType/countTotal":{"kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnailstype\/counttotal","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType\/countTotal","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"countTotal","kind":"identifier"}],"title":"countTotal","abstract":[],"role":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineThumbnailsType"}],"type":"topic","title":"TimelineThumbnailsType","kind":"symbol","url":"\/documentation\/ovkit\/timelinethumbnailstype","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnailsType"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"countTotal"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"countTotal"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType~1countTotal\/title","op":"replace","value":"countTotal"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType~1countTotal\/fragments","op":"replace","value":[{"kind":"identifier","text":"countTotal"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","op":"replace","value":"OVKTimelineThumbnailsType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","op":"replace","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/navigatorTitle","op":"replace","value":[{"text":"OVKTimelineThumbnailsType","kind":"identifier"}]}]}]}