{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType"]]},"abstract":[{"text":"Набор URL на изображения атласов.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Каждое такое изображение может содержать сетку из фреймов более низкого разрешения.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"urls","navigatorTitle":[{"text":"urls","kind":"identifier"}],"symbolKind":"property","required":true,"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKTimelineThumbnailsType(py)urls"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType\/urls","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/timelinethumbnailstype\/urls"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timelinethumbnailstype\/urls"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType":{"url":"\/documentation\/ovkit\/timelinethumbnailstype","navigatorTitle":[{"text":"TimelineThumbnailsType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineThumbnailsType","kind":"identifier"}],"type":"topic","title":"TimelineThumbnailsType","abstract":[{"type":"text","text":"Набор картинок, которые показываются на таймлайне при перемотке."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnailsType/urls":{"title":"urls","navigatorTitle":[{"kind":"identifier","text":"urls"}],"type":"topic","abstract":[{"type":"text","text":"Набор URL на изображения атласов."}],"url":"\/documentation\/ovkit\/timelinethumbnailstype\/urls","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urls"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnailsType\/urls","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"urls","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"urls"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSURL *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/title","value":"OVKTimelineThumbnailsType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/fragments","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKTimelineThumbnailsType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType~1urls\/title","value":"urls","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnailsType~1urls\/fragments","value":[{"kind":"identifier","text":"urls"}],"op":"replace"}]}]}