{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/prefetcher\/tasksummary\/bytesreceived"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary"]]},"abstract":[{"type":"text","text":"Количество данных, загруженных из сети в ходе работы префетчера над этой задачей."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesReceived","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"title":"bytesReceived","role":"symbol","externalID":"s:5OVKit10PrefetcherC11TaskSummaryV13bytesReceivedSuvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/bytesReceived"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesReceived","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Может включать в себя и размер превью, если массив "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","type":"reference"},{"type":"text","text":" непустой и сценарий подходит для загрузки превью. "},{"type":"codeVoice","code":"0"},{"type":"text","text":" может означать либо что все данные уже находятся в кэше, либо что количество данных неизвестно."}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem/prefetchPreviews":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchPreviews","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem\/prefetchPreviews","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Набор вариантов превью для видео. Если присутствует хоть один вариант, он будет загружен наравне с самим видео-ресурсом."}],"type":"topic","url":"\/documentation\/ovkit\/prefetchitem\/prefetchpreviews","required":true,"navigatorTitle":[{"text":"prefetchPreviews","kind":"identifier"}],"title":"prefetchPreviews"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary":{"navigatorTitle":[{"kind":"identifier","text":"TaskSummary"}],"url":"\/documentation\/ovkit\/prefetcher\/tasksummary","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary","type":"topic","role":"symbol","abstract":[{"text":"Информация об успешном результате выполнения префетча одного ресурса.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaskSummary"}],"kind":"symbol","title":"Prefetcher.TaskSummary"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary/bytesReceived":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/bytesReceived","kind":"symbol","url":"\/documentation\/ovkit\/prefetcher\/tasksummary\/bytesreceived","role":"symbol","type":"topic","title":"bytesReceived","abstract":[{"text":"Количество данных, загруженных из сети в ходе работы префетчера над этой задачей.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"navigatorTitle":[{"text":"Prefetcher","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"title":"Prefetcher","url":"\/documentation\/ovkit\/prefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Prefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/title","value":"prefetchPreviews","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem~1prefetchPreviews\/fragments","value":[{"text":"prefetchPreviews","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","value":"Prefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments","value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"Prefetcher"}],"op":"replace"}]}]}