{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/verified","interfaceLanguage":"swift"},"abstract":[{"text":"Все необходимые данные были загружены или проверено их наличие в кэше. ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" означает, что операция была отменена до или во время выполнения."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verified"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","modules":[{"name":"OVKit"}],"title":"verified","symbolKind":"property","externalID":"s:5OVKit10PrefetcherC11TaskSummaryV8verifiedSbvp","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/prefetcher\/tasksummary\/verified"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary/verified":{"title":"verified","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary\/verified","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verified","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","abstract":[{"text":"Все необходимые данные были загружены или проверено их наличие в кэше. ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" означает, что операция была отменена до или во время выполнения."}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher\/tasksummary\/verified"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher/TaskSummary":{"title":"Prefetcher.TaskSummary","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher\/TaskSummary","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TaskSummary"}],"role":"symbol","abstract":[{"text":"Информация об успешном результате выполнения префетча одного ресурса.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TaskSummary"}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher\/tasksummary"},"doc://onevideo.OVKit/documentation/OVKit/Prefetcher":{"title":"Prefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Prefetcher","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Prefetcher"}],"role":"symbol","abstract":[{"text":"Префетчер видеозаписей.","type":"text"}],"navigatorTitle":[{"text":"Prefetcher","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/prefetcher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/title","value":"Prefetcher","op":"replace"},{"value":[{"text":"Prefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Prefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"Prefetcher"}]}]}]}