{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":" "},{"kind":"internalParam","text":"s"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier","text":"SupplementaryAdViewStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}]}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","text":"SupplementaryAdViewStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsProgress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"title":"init(frame:style:showsProgress:)","role":"symbol","externalID":"s:5OVKit19SupplementaryAdViewC5frame5style13showsProgressACSo6CGRectV_AA0bcD5StyleCSbtcfc","modules":[{"name":"OVKit"}]},"variants":[{"paths":["\/documentation\/ovkit\/supplementaryadview\/init(frame:style:showsprogress:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/init(frame:style:showsProgress:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewStyle":{"url":"\/documentation\/ovkit\/supplementaryadviewstyle","abstract":[{"text":"Стиль дополнительного представления для CTA-контрола рекламы - ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryAdViewStyle"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewStyle","title":"SupplementaryAdViewStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupplementaryAdViewStyle"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView/init(frame:style:showsProgress:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView\/init(frame:style:showsProgress:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SupplementaryAdViewStyle","preciseIdentifier":"s:5OVKit24SupplementaryAdViewStyleC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showsProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(frame:style:showsProgress:)","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/supplementaryadview\/init(frame:style:showsprogress:)","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"role":"symbol","title":"SupplementaryAdView","type":"topic","navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryAdView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadview","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"OVKSupplementaryAdView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}