{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/banner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/banner"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"banner","navigatorTitle":[{"kind":"identifier","text":"banner"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"banner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer(py)banner","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"banner","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/banner","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","title":"MyTargetInstreamAdVideoMotionBanner","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/banner":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/banner","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"banner"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"banner","kind":"identifier"}],"title":"banner","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/banner","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionPlayer","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"banner","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"banner"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<MyTargetInstreamAdVideoMotionBanner>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":" ","kind":"text"},{"text":"banner","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle"},{"op":"replace","value":"banner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1banner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"banner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1banner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title","value":"MyTargetInstreamAdVideoMotionPlayer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}