{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeOnFinish","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/closeonfinish"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/closeonfinish"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/closeOnFinish"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeOnFinish","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","required":true,"title":"closeOnFinish","navigatorTitle":[{"kind":"identifier","text":"closeOnFinish"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer(py)closeOnFinish","symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/closeOnFinish":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/closeOnFinish","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"closeOnFinish","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/closeonfinish","role":"symbol","kind":"symbol","abstract":[],"title":"closeOnFinish","required":true,"navigatorTitle":[{"text":"closeOnFinish","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","kind":"symbol","abstract":[],"title":"MyTargetInstreamAdVideoMotionPlayer","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"closeOnFinish"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"closeOnFinish"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"closeOnFinish","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1closeOnFinish\/title","value":"closeOnFinish","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1closeOnFinish\/fragments","value":[{"kind":"identifier","text":"closeOnFinish"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title","value":"MyTargetInstreamAdVideoMotionPlayer"},{"value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"op":"replace"}]}]}