{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"]]},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"ovkit_delegate"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer(py)ovkit_delegate","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"},{"kind":"text","text":"?"}],"title":"ovkit_delegate"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Warning","type":"aside","style":"warning","content":[{"inlineContent":[{"type":"text","text":"Must be a weak property."}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/ovkit_delegate"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/ovkit_delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/ovkit_delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/ovkit_delegate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate","text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"ovkit_delegate","kind":"identifier"}],"required":true,"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/ovkit_delegate","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/ovkit_delegate","title":"ovkit_delegate"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate","type":"topic","title":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"title":"MyTargetInstreamAdVideoMotionPlayer","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"ovkit_delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ovkit_delegate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"typeIdentifier","text":"id<MyTargetInstreamAdVideoMotionPlayerDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"ovkit_delegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1ovkit_delegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1ovkit_delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ovkit_delegate"}]},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/navigatorTitle"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}