{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/play(videoMotionBanner:)"},"metadata":{"symbolKind":"method","required":true,"title":"play(videoMotionBanner:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer(im)playWithVideoMotionBanner:","navigatorTitle":[{"kind":"identifier","text":"playWithVideoMotionBanner:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"text":"videoMotionBanner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoMotionBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdVideoMotionBanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/play(videomotionbanner:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/play(videomotionbanner:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/play(videoMotionBanner:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"text":"videoMotionBanner","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner","text":"MyTargetInstreamAdVideoMotionBanner","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playWithVideoMotionBanner:"}],"required":true,"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/play(videoMotionBanner:)","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/play(videomotionbanner:)","title":"play(videoMotionBanner:)"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","title":"MyTargetInstreamAdVideoMotionBanner"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"title":"MyTargetInstreamAdVideoMotionPlayer","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"playWithVideoMotionBanner:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithVideoMotionBanner:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"playWithVideoMotionBanner:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MyTargetInstreamAdVideoMotionBanner>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner"},{"text":") ","kind":"text"},{"text":"videoMotionBanner","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1play(videoMotionBanner:)\/title","value":"playWithVideoMotionBanner:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1play(videoMotionBanner:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playWithVideoMotionBanner:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title","value":"MyTargetInstreamAdVideoMotionPlayer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","value":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}