{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OVKit"}],"title":"stop()","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer(im)stop","required":true,"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stop"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/stop()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/stop()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionPlayer","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer/stop()":{"abstract":[],"required":true,"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer\/stop()","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer\/stop()","title":"stop()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"stop","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stop"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"stop","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}]},{"value":"stop","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1stop()\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer~1stop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}