{"abstract":[{"text":"Тип аудио выхода, на который выводится звук плеера.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioOutputType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioOutput","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statscontext\/audiooutput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statscontext\/audiooutput"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)audioOutput","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioOutput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioOutputType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType"}],"title":"audioOutput","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"audioOutput","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"url":"\/documentation\/ovkit\/statscontext","navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","title":"StatsContext","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/audioOutput":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/audioOutput","type":"topic","abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук плеера."}],"navigatorTitle":[{"text":"audioOutput","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioOutput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioOutputType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType"}],"url":"\/documentation\/ovkit\/statscontext\/audiooutput","title":"audioOutput","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOutputType"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","kind":"symbol","title":"AudioOutputType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"role":"symbol","url":"\/documentation\/ovkit\/audiooutputtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"audioOutput","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"audioOutput","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","preciseIdentifier":"c:@M@OVKit@E@OVKAudioOutputType","text":"OVKAudioOutputType"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKStatsContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"},{"op":"replace","value":"audioOutput","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioOutput\/title"},{"op":"replace","value":[{"kind":"identifier","text":"audioOutput"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1audioOutput\/fragments"},{"op":"replace","value":"OVKAudioOutputType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle"}]}]}