{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/customParams"},"abstract":[{"type":"text","text":"Пользовательский набор параметров для отправки в статистику. По умолчанию пустой словарь."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customParams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"symbolKind":"property","role":"symbol","title":"customParams","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)customParams","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"customParams"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/customparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/customparams"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customParams"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"] { get }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsContext","kind":"identifier"}],"title":"StatsContext","navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"type":"topic","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","role":"symbol","url":"\/documentation\/ovkit\/statscontext","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/customParams":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customParams","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/customParams","abstract":[{"type":"text","text":"Пользовательский набор параметров для отправки в статистику. По умолчанию пустой словарь."}],"type":"topic","url":"\/documentation\/ovkit\/statscontext\/customparams","navigatorTitle":[{"text":"customParams","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"customParams"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"customParams","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"customParams","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"text":"customParams","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1customParams\/title","value":"customParams","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1customParams\/fragments","op":"replace","value":[{"text":"customParams","kind":"identifier"}]}]}]}