{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInExternalPip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { get }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInExternalPip","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Происходит ли воспроизведение в системном режиме Картинка в Картинке вне приложения."}],"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/isinexternalpip"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/isinexternalpip"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"isInExternalPip"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInExternalPip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)isInExternalPip","title":"isInExternalPip"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/isInExternalPip":{"type":"topic","navigatorTitle":[{"text":"isInExternalPip","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInExternalPip","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/isInExternalPip","abstract":[{"type":"text","text":"Происходит ли воспроизведение в системном режиме Картинка в Картинке вне приложения."}],"url":"\/documentation\/ovkit\/statscontext\/isinexternalpip","role":"symbol","kind":"symbol","title":"isInExternalPip"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"title":"StatsContext","url":"\/documentation\/ovkit\/statscontext","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"kind":"symbol","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isInExternalPip","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isInExternalPip"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInExternalPip"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isInExternalPip","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInExternalPip\/title"},{"value":[{"kind":"identifier","text":"isInExternalPip"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1isInExternalPip\/fragments"},{"value":"OVKStatsContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}