{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"abstract":[{"text":"Данные о задержке потока воспроизведения до автора трансляции.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveLatency"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct","preciseIdentifier":"s:5OVKit12StatsContextC11LiveLatencyV","text":"LiveLatency","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/liveLatency-swift.property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveLatency"},{"kind":"text","text":": "},{"text":"LiveLatency","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12StatsContextC11LiveLatencyV"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"role":"symbol","title":"liveLatency","externalID":"s:5OVKit12StatsContextC11liveLatencyAC04LiveE0VSgvp","symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/statscontext\/livelatency-swift.property"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/LiveLatency-swift.struct":{"type":"topic","role":"symbol","title":"StatsContext.LiveLatency","abstract":[{"type":"text","text":"Данные о задержке потока воспроизведения до автора трансляции."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveLatency"}],"url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveLatency"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/LiveLatency-swift.struct"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StatsContext","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","url":"\/documentation\/ovkit\/statscontext","title":"StatsContext","role":"symbol","navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/liveLatency-swift.property":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveLatency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LiveLatency","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12StatsContextC11LiveLatencyV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/liveLatency-swift.property","title":"liveLatency","type":"topic","abstract":[{"text":"Данные о задержке потока воспроизведения до автора трансляции.","type":"text"}],"url":"\/documentation\/ovkit\/statscontext\/livelatency-swift.property","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKStatsContext"}]}]}]}