{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Языковой код выбранных в данный момент субтитров. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что субтитры отключены."},{"type":"text","text":" "},{"type":"text","text":"Если автосубтитры - будет добавлен суффикс "},{"type":"codeVoice","code":"_auto"},{"type":"text","text":", например, "},{"type":"codeVoice","code":"ru_auto"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitlesLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"subtitlesLanguage"}],"title":"subtitlesLanguage","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)subtitlesLanguage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitlesLanguage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/subtitleslanguage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/subtitleslanguage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/subtitlesLanguage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"title":"StatsContext"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/subtitlesLanguage":{"navigatorTitle":[{"text":"subtitlesLanguage","kind":"identifier"}],"abstract":[{"text":"Языковой код выбранных в данный момент субтитров. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что субтитры отключены.","type":"text"},{"text":" ","type":"text"},{"text":"Если автосубтитры - будет добавлен суффикс ","type":"text"},{"code":"_auto","type":"codeVoice"},{"text":", например, ","type":"text"},{"code":"ru_auto","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/subtitlesLanguage","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/statscontext\/subtitleslanguage","title":"subtitlesLanguage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitlesLanguage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"subtitlesLanguage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subtitlesLanguage"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"subtitlesLanguage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1subtitlesLanguage\/title","value":"subtitlesLanguage","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1subtitlesLanguage\/fragments","value":[{"text":"subtitlesLanguage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}