{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCustomParams"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"] { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userCustomParams"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/usercustomparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statscontext\/usercustomparams"]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"userCustomParams","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)userCustomParams","symbolKind":"property","title":"userCustomParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userCustomParams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"abstract":[{"type":"text","text":"Пользовательский набор параметров для использования в собственных реализациях "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"type":"text","text":". По умолчанию пустой словарь."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/userCustomParams":{"title":"userCustomParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userCustomParams","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"userCustomParams"}],"type":"topic","abstract":[{"text":"Пользовательский набор параметров для использования в собственных реализациях ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"type":"text","text":". По умолчанию пустой словарь."}],"url":"\/documentation\/ovkit\/statscontext\/usercustomparams","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userCustomParams"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/statshandler","type":"topic","title":"StatsHandler","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"kind":"symbol","url":"\/documentation\/ovkit\/statscontext","navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"title":"StatsContext","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"type":"topic","title":"StatsCollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","role":"symbol","kind":"symbol","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"или переходах в PiP и fullscreen.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"userCustomParams","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"userCustomParams","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"text":"userCustomParams","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"userCustomParams","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userCustomParams\/title"},{"value":[{"text":"userCustomParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userCustomParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","op":"replace","value":"OVKStatsHandler"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace"},{"op":"replace","value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"value":[{"kind":"identifier","text":"OVKStatsCollector"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsCollector"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}