{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Выбранное пользователем качество видео. Например, ","type":"text"},{"type":"codeVoice","code":"\"auto\""},{"text":", ","type":"text"},{"type":"codeVoice","code":"\"480\""},{"text":", ","type":"text"},{"type":"codeVoice","code":"\"720\""},{"text":" и т.д.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"text":"Deprecated в пользу ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userQuality","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackQuality","isActive":true},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadQuality","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"style":"warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/videoquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/videoquality"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"videoQuality","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)videoQuality","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"videoQuality","kind":"identifier"}],"symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoQuality","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/videoQuality":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"videoQuality"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/videoQuality","url":"\/documentation\/ovkit\/statscontext\/videoquality","kind":"symbol","type":"topic","abstract":[{"text":"Выбранное пользователем качество видео. Например, ","type":"text"},{"code":"\"auto\"","type":"codeVoice"},{"text":", ","type":"text"},{"code":"\"480\"","type":"codeVoice"},{"text":", ","type":"text"},{"code":"\"720\"","type":"codeVoice"},{"text":" и т.д.","type":"text"}],"role":"symbol","title":"videoQuality"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/userQuality":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userQuality"}],"url":"\/documentation\/ovkit\/statscontext\/userquality","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/userQuality","abstract":[{"text":"Качество, выбранное пользователем в UI.","type":"text"}],"title":"userQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}],"navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","url":"\/documentation\/ovkit\/statscontext","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"role":"symbol","title":"StatsContext"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/playbackQuality":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"playbackQuality"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/playbackQuality","url":"\/documentation\/ovkit\/statscontext\/playbackquality","kind":"symbol","type":"topic","abstract":[{"text":"Воспроизводимое в данный момент разрешение.","type":"text"}],"role":"symbol","title":"playbackQuality"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/downloadQuality":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadQuality"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"downloadQuality","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/downloadQuality","url":"\/documentation\/ovkit\/statscontext\/downloadquality","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Качество, выбранное для загрузки в данный момент (адаптивным алгоритмом, если Авто)."}],"role":"symbol","title":"downloadQuality"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"videoQuality","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"videoQuality","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"videoQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1videoQuality\/title","op":"replace"},{"value":[{"text":"videoQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1videoQuality\/fragments","op":"replace"},{"value":"userQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userQuality\/title","op":"replace"},{"value":[{"text":"userQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1userQuality\/fragments","op":"replace"},{"value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","op":"replace"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","op":"replace"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","op":"replace"},{"value":"playbackQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackQuality\/title","op":"replace"},{"value":[{"text":"playbackQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1playbackQuality\/fragments","op":"replace"},{"value":"downloadQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1downloadQuality\/title","op":"replace"},{"value":[{"text":"downloadQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1downloadQuality\/fragments","op":"replace"}]}]}