{"variants":[{"paths":["\/documentation\/ovkit\/statscontext\/volume"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/volume"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/volume","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"volume","externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)volume","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"volume","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"abstract":[{"text":"Громкость воспроизведения звука, когда он включен (","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","type":"reference"},{"text":" == true).","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/volume":{"role":"symbol","title":"volume","url":"\/documentation\/ovkit\/statscontext\/volume","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"volume"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/volume","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"abstract":[{"type":"text","text":"Громкость воспроизведения звука, когда он включен ("},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","isActive":true},{"type":"text","text":" == true)."}]},"doc://onevideo.OVKit/documentation/OVKit/StatsContext/soundOn":{"title":"soundOn","url":"\/documentation\/ovkit\/statscontext\/soundon","abstract":[{"type":"text","text":"Включен ли звук в видео (изменяемое значение)."}],"navigatorTitle":[{"text":"soundOn","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/soundOn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"soundOn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statscontext","abstract":[{"text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","title":"StatsContext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"volume"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"volume"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1volume\/title","value":"volume","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1volume\/fragments","value":[{"text":"volume","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1soundOn\/title","value":"soundOn","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1soundOn\/fragments","value":[{"text":"soundOn","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"op":"replace","value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsContext","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}