{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vsid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/statscontext\/vsid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/statscontext\/vsid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/vsid"},"abstract":[{"text":"Идентификатор сессии просмотра.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKStatsContext(py)vsid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vsid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"vsid","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"vsid"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsContext/vsid":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vsid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext\/vsid","abstract":[{"text":"Идентификатор сессии просмотра.","type":"text"}],"title":"vsid","url":"\/documentation\/ovkit\/statscontext\/vsid","navigatorTitle":[{"kind":"identifier","text":"vsid"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"role":"symbol","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsContext"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","url":"\/documentation\/ovkit\/statscontext","kind":"symbol","title":"StatsContext"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"vsid","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"vsid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"vsid"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"vsid","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1vsid\/title"},{"op":"replace","value":[{"text":"vsid","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext~1vsid\/fragments"},{"op":"replace","value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title"},{"op":"replace","value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"op":"replace","value":[{"text":"OVKStatsContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}