{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","kind":"typeIdentifier","text":"DownloadState"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/downloadState","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/downloadstate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/downloadstate"]}],"metadata":{"modules":[{"name":"OVKit"}],"title":"downloadState","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(py)downloadState","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"downloadState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState"}],"navigatorTitle":[{"text":"downloadState","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol","type":"topic","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"title":"PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItemState/downloadState":{"navigatorTitle":[{"kind":"identifier","text":"downloadState"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkpersistentitemstate\/downloadstate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/downloadState","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"downloadState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DownloadState","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","kind":"typeIdentifier"}],"title":"downloadState"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitemstate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Состояние "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"title":"PersistentItemState"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/downloadstate","navigatorTitle":[{"text":"DownloadState","kind":"identifier"}],"title":"DownloadState","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DownloadState","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"downloadState","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"downloadState"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","kind":"typeIdentifier","text":"OVKDownloadState"},{"text":" ","kind":"text"},{"kind":"identifier","text":"downloadState"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","op":"replace"},{"op":"replace","value":"downloadState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1downloadState\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1downloadState\/fragments","value":[{"text":"downloadState","kind":"identifier"}]},{"value":"OVKPersistentItemState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKDownloadState"}]}]}]}