{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/error","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(py)error","title":"error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"error"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/error"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol","type":"topic","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"title":"PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitemstate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Состояние "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"title":"PersistentItemState"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItemState/error":{"navigatorTitle":[{"text":"error","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkpersistentitemstate\/error","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/error","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"error"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"error","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"error","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"error","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"value":"error","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1error\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1error\/fragments","value":[{"kind":"identifier","text":"error"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}