{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/progress","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progress"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(py)progress","navigatorTitle":[{"text":"progress","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"progress","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/progress"]},{"paths":["\/documentation\/ovkit\/ovkpersistentitemstate\/progress"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol","type":"topic","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"title":"PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItemState/progress":{"navigatorTitle":[{"kind":"identifier","text":"progress"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkpersistentitemstate\/progress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemState\/progress","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"title":"progress"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitemstate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Состояние "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"title":"PersistentItemState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"progress","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"progress","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1progress\/title","op":"replace","value":"progress"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemState~1progress\/fragments","value":[{"text":"progress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","op":"replace","value":"OVKPersistentItemState"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","op":"replace","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]}]}]}