{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_cta"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_cta"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner"]]},"metadata":{"navigatorTitle":[{"text":"ovkit_cta","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner(py)ovkit_cta","role":"symbol","roleHeading":"Instance Property","title":"ovkit_cta","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_cta","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCallToActionData","text":"MyTargetCallToActionData","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_cta"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCallToActionData","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","text":"MyTargetCallToActionData"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_cta"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCallToActionData":{"title":"MyTargetCallToActionData","abstract":[{"type":"text","text":"Данные, которые необходимы для отображения CTA-блока в баннере."}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetCallToActionData","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCallToActionData","url":"\/documentation\/ovkit\/mytargetcalltoactiondata","navigatorTitle":[{"text":"MyTargetCallToActionData","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","url":"\/documentation\/ovkit\/mytargetinstreamadbanner","title":"MyTargetInstreamAdBanner","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/ovkit_cta":{"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_cta","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_cta","navigatorTitle":[{"text":"ovkit_cta","kind":"identifier"}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"ovkit_cta","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_cta","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetCallToActionData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCallToActionData","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ovkit_cta","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ovkit_cta","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetCallToActionData","kind":"typeIdentifier","text":"id<MyTargetCallToActionData>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_cta"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MyTargetCallToActionData","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/title"},{"value":[{"text":"MyTargetCallToActionData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetCallToActionData"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCallToActionData\/navigatorTitle"},{"value":"MyTargetInstreamAdBanner","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title"},{"value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments"},{"value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle"},{"value":"ovkit_cta","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_cta\/title"},{"value":[{"text":"ovkit_cta","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_cta\/fragments"}]}]}