{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_shoppableAdsItems","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_shoppableadsitems"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_shoppableadsitems"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_shoppableAdsItems"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MyTargetShoppableAdsItemProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner"]]},"metadata":{"symbolKind":"property","required":true,"title":"ovkit_shoppableAdsItems","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_shoppableAdsItems","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MyTargetShoppableAdsItemProtocol","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"ovkit_shoppableAdsItems"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdBanner(py)ovkit_shoppableAdsItems","roleHeading":"Instance Property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner","kind":"symbol","title":"MyTargetInstreamAdBanner","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdBanner"}],"navigatorTitle":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdBanner/ovkit_shoppableAdsItems":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdBanner\/ovkit_shoppableAdsItems","title":"ovkit_shoppableAdsItems","required":true,"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ovkit_shoppableAdsItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol","text":"MyTargetShoppableAdsItemProtocol","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"ovkit_shoppableAdsItems","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadbanner\/ovkit_shoppableadsitems","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol":{"navigatorTitle":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"type":"topic","url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol","title":"MyTargetShoppableAdsItemProtocol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"ovkit_shoppableAdsItems","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"ovkit_shoppableAdsItems","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<MyTargetShoppableAdsItemProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ovkit_shoppableAdsItems"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"MyTargetInstreamAdBanner","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}]},{"op":"replace","value":[{"text":"MyTargetInstreamAdBanner","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner\/navigatorTitle"},{"value":"ovkit_shoppableAdsItems","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_shoppableAdsItems\/title"},{"op":"replace","value":[{"text":"ovkit_shoppableAdsItems","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdBanner~1ovkit_shoppableAdsItems\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/title","value":"MyTargetShoppableAdsItemProtocol"},{"value":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/navigatorTitle"}]}]}