{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeController(for:options:)"},"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit20InterstitialProviderP14makeController3for7options0E4TypeQzSgAA10PlayerViewC_SDySSypGSgtF","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"makeController"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"ControllerType","preciseIdentifier":"s:5OVKit20InterstitialProviderP14ControllerTypeQa"},{"kind":"text","text":"?"}],"title":"makeController(for:options:)","required":true,"role":"symbol"},"abstract":[{"type":"text","text":"Создаёт контроллер прерываний "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController","isActive":true,"type":"reference"},{"type":"text","text":" "},{"text":"для переданного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/ControllerType","preciseIdentifier":"s:5OVKit20InterstitialProviderP14ControllerTypeQa","text":"ControllerType","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]},{"parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Экземпляр ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", для которого создаётся контроллер.","type":"text"}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"text":"Необязательный словарь, содержащий дополнительные параметры для настройки контроллера. Приоритет параметров над данными из ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","type":"reference","isActive":true},{"text":" определяется","type":"text"},{"text":" ","type":"text"},{"text":"конкретной реализацией поставщика ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Созданный контроллер типа "},{"type":"codeVoice","code":"T: InterstitialController"},{"text":", или ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"если контроллер создать не удалось.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/interstitialprovider\/makecontroller(for:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"title":"video","url":"\/documentation\/ovkit\/playerview\/video","navigatorTitle":[{"kind":"identifier","text":"video"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Модель видеозаписи для воспроизведения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider/makeController(for:options:)":{"url":"\/documentation\/ovkit\/interstitialprovider\/makecontroller(for:options:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/makeController(for:options:)","abstract":[{"text":"Создаёт контроллер прерываний ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"для переданного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20InterstitialProviderP14ControllerTypeQa","text":"ControllerType"},{"kind":"text","text":"?"}],"title":"makeController(for:options:)","required":true,"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialController":{"title":"InterstitialController","url":"\/documentation\/ovkit\/interstitialcontroller","navigatorTitle":[{"text":"InterstitialController","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Протокол контроллера прерываний."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialController"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider":{"url":"\/documentation\/ovkit\/interstitialprovider","navigatorTitle":[{"kind":"identifier","text":"InterstitialProvider"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialProvider"}],"abstract":[{"type":"text","text":"Дженерик-протокол поставщика контроллеров промежуточных прерываний (рекламы)."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider","title":"InterstitialProvider","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialProvider/ControllerType":{"url":"\/documentation\/ovkit\/interstitialprovider\/controllertype","type":"topic","required":true,"fragments":[{"text":"associatedtype","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControllerType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit22InterstitialControllerP","text":"InterstitialController"}],"abstract":[{"text":"Тип контроллера, который будет управлять этим поставщиком.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialProvider\/ControllerType","kind":"symbol","title":"ControllerType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"video","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title","op":"replace"},{"value":[{"kind":"identifier","text":"video"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"}]}]}