{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkchapterprovider\/chapters"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkchapterprovider\/chapters"]}],"abstract":[{"type":"text","text":"Список всех эпизодов в видео. Отсортирован по времени начала эпизода."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chapters"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","text":"VideoChapterType"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKChapterProvider\/chapters"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"chapters"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider(py)chapters","title":"chapters","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"chapters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKChapterProvider/chapters":{"type":"topic","url":"\/documentation\/ovkit\/ovkchapterprovider\/chapters","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"chapters","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"chapters"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKChapterProvider\/chapters","role":"symbol","abstract":[{"type":"text","text":"Список всех эпизодов в видео. Отсортирован по времени начала эпизода."}],"title":"chapters","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}],"role":"symbol","title":"ChapterProvider","url":"\/documentation\/ovkit\/chapterprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"abstract":[{"text":"Отвечает за разбивку видео на эпизоды по таймкодам.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","title":"VideoChapterType","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoChapterType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoChapterType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videochaptertype"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"chapters","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"chapters","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<OVKVideoChapterType>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"chapters","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKChapterProvider~1chapters\/title","op":"replace","value":"chapters"},{"value":[{"kind":"identifier","text":"chapters"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKChapterProvider~1chapters\/fragments","op":"replace"},{"op":"replace","value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"kind":"identifier","text":"OVKChapterProvider"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","op":"replace","value":"OVKVideoChapterType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments","value":[{"text":"OVKVideoChapterType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}