{"abstract":[{"type":"text","text":"Эпизод, который воспроизводится плеером в данный момент. Свойство поддерживает KVO."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentChapter","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","kind":"typeIdentifier","text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKChapterProvider\/currentChapter"},"metadata":{"title":"currentChapter","roleHeading":"Instance Property","navigatorTitle":[{"text":"currentChapter","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentChapter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoChapterType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"text":"?","kind":"text"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKChapterProvider(py)currentChapter","role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkchapterprovider\/currentchapter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkchapterprovider\/currentchapter"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKChapterProvider/currentChapter":{"abstract":[{"type":"text","text":"Эпизод, который воспроизводится плеером в данный момент. Свойство поддерживает KVO."}],"title":"currentChapter","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"currentChapter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoChapterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoChapterType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"currentChapter","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKChapterProvider\/currentChapter","role":"symbol","url":"\/documentation\/ovkit\/ovkchapterprovider\/currentchapter"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChapterProvider","kind":"identifier"}],"type":"topic","title":"ChapterProvider","url":"\/documentation\/ovkit\/chapterprovider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoChapterType":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapterType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoChapterType","kind":"identifier"}],"type":"topic","title":"VideoChapterType","url":"\/documentation\/ovkit\/videochaptertype","navigatorTitle":[{"text":"VideoChapterType","kind":"identifier"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"currentChapter","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"currentChapter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoChapterType","kind":"typeIdentifier","text":"id<OVKVideoChapterType>"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentChapter"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKChapterProvider~1currentChapter\/title","value":"currentChapter"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKChapterProvider~1currentChapter\/fragments","value":[{"text":"currentChapter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","op":"replace","value":"OVKChapterProvider"},{"value":[{"text":"OVKChapterProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/title","value":"OVKVideoChapterType"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapterType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapterType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}