{"metadata":{"title":"AudioOutputType.airplay","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airplay"}],"navigatorTitle":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeAirplay","symbolKind":"case"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/airplay","interfaceLanguage":"swift"},"abstract":[{"text":"AirPlay-устройство.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airplay","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/airplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiooutputtype\/airplay"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/airplay":{"kind":"symbol","navigatorTitle":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"type":"topic","title":"AudioOutputType.airplay","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"airplay","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/airplay","url":"\/documentation\/ovkit\/audiooutputtype\/airplay","abstract":[{"text":"AirPlay-устройство.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"title":"AudioOutputType","role":"symbol","abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"url":"\/documentation\/ovkit\/audiooutputtype","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKAudioOutputTypeAirplay","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputTypeAirplay"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1airplay\/title","value":"OVKAudioOutputTypeAirplay","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1airplay\/fragments","value":[{"text":"OVKAudioOutputTypeAirplay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}