{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bluetooth","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Bluetooth устройство (наушники, колонки, гарнитура).","type":"text"}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"AudioOutputType.bluetooth","externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeBluetooth","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/bluetooth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/bluetooth"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/bluetooth"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"title":"AudioOutputType","role":"symbol","abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"url":"\/documentation\/ovkit\/audiooutputtype","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/bluetooth":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}],"type":"topic","url":"\/documentation\/ovkit\/audiooutputtype\/bluetooth","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/bluetooth","kind":"symbol","title":"AudioOutputType.bluetooth","abstract":[{"type":"text","text":"Bluetooth устройство (наушники, колонки, гарнитура)."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKAudioOutputTypeBluetooth","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKAudioOutputType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","op":"replace"},{"value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","op":"replace"},{"value":"OVKAudioOutputTypeBluetooth","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1bluetooth\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputTypeBluetooth"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1bluetooth\/fragments"}]}]}