{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carAudio"}],"roleHeading":"Case","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeCarAudio"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeCarAudio","title":"AudioOutputType.carAudio","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/caraudio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiooutputtype\/caraudio"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Динамики в машине при подключении через CarPlay.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"carAudio","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/carAudio"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","url":"\/documentation\/ovkit\/audiooutputtype","title":"AudioOutputType","role":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/carAudio":{"type":"topic","role":"symbol","title":"AudioOutputType.carAudio","abstract":[{"text":"Динамики в машине при подключении через CarPlay.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeCarAudio"}],"url":"\/documentation\/ovkit\/audiooutputtype\/caraudio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"carAudio"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/carAudio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKAudioOutputTypeCarAudio","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputTypeCarAudio"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"OVKAudioOutputTypeCarAudio","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1carAudio\/title","value":"OVKAudioOutputTypeCarAudio","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1carAudio\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputTypeCarAudio"}],"op":"replace"}]}]}