{"abstract":[{"type":"text","text":"Display Port."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayPort","kind":"identifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"AudioOutputType.displayPort","navigatorTitle":[{"text":"OVKAudioOutputTypeDisplayPort","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayPort"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeDisplayPort"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/displayPort"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/displayport"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/displayport"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/displayPort":{"url":"\/documentation\/ovkit\/audiooutputtype\/displayport","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/displayPort","title":"AudioOutputType.displayPort","abstract":[{"text":"Display Port.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayPort"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeDisplayPort"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"title":"AudioOutputType","role":"symbol","abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"url":"\/documentation\/ovkit\/audiooutputtype","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKAudioOutputTypeDisplayPort","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputTypeDisplayPort"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKAudioOutputTypeDisplayPort","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKAudioOutputTypeDisplayPort","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1displayPort\/title"},{"op":"replace","value":[{"text":"OVKAudioOutputTypeDisplayPort","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1displayPort\/fragments"},{"op":"replace","value":"OVKAudioOutputType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}