{"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/hdmi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiooutputtype\/hdmi"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/HDMI"},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeHDMI","navigatorTitle":[{"text":"OVKAudioOutputTypeHDMI","kind":"identifier"}],"roleHeading":"Case","title":"AudioOutputType.HDMI","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HDMI","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"OVKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"HDMI.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HDMI","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioOutputType"}],"type":"topic","abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","url":"\/documentation\/ovkit\/audiooutputtype","title":"AudioOutputType"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/HDMI":{"url":"\/documentation\/ovkit\/audiooutputtype\/hdmi","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeHDMI"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HDMI"}],"type":"topic","title":"AudioOutputType.HDMI","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/HDMI","abstract":[{"text":"HDMI.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKAudioOutputTypeHDMI","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKAudioOutputTypeHDMI","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKAudioOutputTypeHDMI","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKAudioOutputType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title"},{"value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments"},{"value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle"},{"value":"OVKAudioOutputTypeHDMI","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1HDMI\/title"},{"value":[{"text":"OVKAudioOutputTypeHDMI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1HDMI\/fragments"}]}]}