{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/headphones"},"sections":[],"metadata":{"navigatorTitle":[{"text":"OVKAudioOutputTypeHeadphones","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeHeadphones","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"headphones"}],"title":"AudioOutputType.headphones","modules":[{"name":"OVKit"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"abstract":[{"text":"Проводные наушники или гарнитура.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/headphones"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/headphones"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"headphones"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/headphones":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/headphones","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"headphones"}],"abstract":[{"text":"Проводные наушники или гарнитура.","type":"text"}],"type":"topic","title":"AudioOutputType.headphones","url":"\/documentation\/ovkit\/audiooutputtype\/headphones","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeHeadphones"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"title":"AudioOutputType","kind":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AudioOutputType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/audiooutputtype"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OVKAudioOutputTypeHeadphones","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKAudioOutputTypeHeadphones","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKAudioOutputTypeHeadphones","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKAudioOutputTypeHeadphones","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1headphones\/title"},{"op":"replace","value":[{"text":"OVKAudioOutputTypeHeadphones","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1headphones\/fragments"},{"op":"replace","value":"OVKAudioOutputType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments"},{"value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}