{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineOut","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/lineout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/lineout"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/lineOut","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"OVKAudioOutputTypeLineOut","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeLineOut","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineOut","kind":"identifier"}],"roleHeading":"Case","title":"AudioOutputType.lineOut","symbolKind":"case","role":"symbol"},"abstract":[{"text":"Линейный выход.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"title":"AudioOutputType","kind":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AudioOutputType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/audiooutputtype"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/lineOut":{"title":"AudioOutputType.lineOut","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/lineOut","abstract":[{"text":"Линейный выход.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineOut"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeLineOut"}],"url":"\/documentation\/ovkit\/audiooutputtype\/lineout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"OVKAudioOutputTypeLineOut","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKAudioOutputTypeLineOut","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKAudioOutputTypeLineOut"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAudioOutputType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1lineOut\/title","op":"replace","value":"OVKAudioOutputTypeLineOut"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1lineOut\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAudioOutputTypeLineOut"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}