{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/other","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"AudioOutputType.other","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeOther","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeOther"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/other"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiooutputtype\/other"]}],"abstract":[{"type":"text","text":"Другой неизвестный выход."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/other":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"title":"AudioOutputType.other","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/other","abstract":[{"type":"text","text":"Другой неизвестный выход."}],"kind":"symbol","url":"\/documentation\/ovkit\/audiooutputtype\/other","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeOther"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioOutputType"}],"type":"topic","abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","url":"\/documentation\/ovkit\/audiooutputtype","title":"AudioOutputType"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKAudioOutputTypeOther","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKAudioOutputTypeOther","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKAudioOutputTypeOther","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1other\/title","value":"OVKAudioOutputTypeOther","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1other\/fragments","value":[{"text":"OVKAudioOutputTypeOther","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"}]}]}