{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/RawRepresentable-Implementations"},"kind":"article","metadata":{"title":"RawRepresentable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/hashValue"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/hash(into:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"title":"AudioOutputType","kind":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AudioOutputType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/audiooutputtype"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/hashValue":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/audiooutputtype\/hashvalue","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/hashValue","title":"hashValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/hash(into:)":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"title":"hash(into:)","role":"symbol","url":"\/documentation\/ovkit\/audiooutputtype\/hash(into:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAudioOutputType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}