{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/speaker"},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"}],"externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeSpeaker","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeSpeaker"}],"title":"AudioOutputType.speaker","roleHeading":"Case","symbolKind":"case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"speaker"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"Основной динамик устройства, громкоговоритель."}],"variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/speaker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiooutputtype\/speaker"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/speaker":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/speaker","type":"topic","navigatorTitle":[{"text":"OVKAudioOutputTypeSpeaker","kind":"identifier"}],"url":"\/documentation\/ovkit\/audiooutputtype\/speaker","abstract":[{"text":"Основной динамик устройства, громкоговоритель.","type":"text"}],"kind":"symbol","title":"AudioOutputType.speaker","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"speaker","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutputType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioOutputType"}],"type":"topic","abstract":[{"type":"text","text":"Тип аудио выхода, на который выводится звук из плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","url":"\/documentation\/ovkit\/audiooutputtype","title":"AudioOutputType"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKAudioOutputTypeSpeaker","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKAudioOutputTypeSpeaker","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"OVKAudioOutputTypeSpeaker","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"OVKAudioOutputTypeSpeaker","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1speaker\/title"},{"value":[{"kind":"identifier","text":"OVKAudioOutputTypeSpeaker"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1speaker\/fragments","op":"replace"},{"value":"OVKAudioOutputType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}],"op":"replace"}]}]}