{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usbAudio"}]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/audiooutputtype\/usbaudio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiooutputtype\/usbaudio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/usbAudio","interfaceLanguage":"swift"},"abstract":[{"text":"USB Audio выход.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"OVKAudioOutputTypeUsbAudio","kind":"identifier"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"usbAudio"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKAudioOutputType@OVKAudioOutputTypeUsbAudio","symbolKind":"case","title":"AudioOutputType.usbAudio"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType/usbAudio":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType\/usbAudio","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/audiooutputtype\/usbaudio","navigatorTitle":[{"kind":"identifier","text":"OVKAudioOutputTypeUsbAudio"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"usbAudio"}],"title":"AudioOutputType.usbAudio","abstract":[{"text":"USB Audio выход.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioOutputType":{"kind":"symbol","title":"AudioOutputType","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioOutputType","url":"\/documentation\/ovkit\/audiooutputtype","abstract":[{"text":"Тип аудио выхода, на который выводится звук из плеера.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AudioOutputType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutputType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKAudioOutputTypeUsbAudio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKAudioOutputTypeUsbAudio","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKAudioOutputTypeUsbAudio"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1usbAudio\/title","value":"OVKAudioOutputTypeUsbAudio"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType~1usbAudio\/fragments","value":[{"text":"OVKAudioOutputTypeUsbAudio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/title","value":"OVKAudioOutputType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/fragments","value":[{"text":"OVKAudioOutputType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioOutputType\/navigatorTitle","value":[{"text":"OVKAudioOutputType","kind":"identifier"}]}]}]}