{"metadata":{"role":"symbol","symbolKind":"case","title":"FullscreenViewControllerDismissMethod.deviceRotation","externalID":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod@OVKFullscreenViewControllerDismissMethodDeviceRotation","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKFullscreenViewControllerDismissMethodDeviceRotation","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"deviceRotation","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/deviceRotation"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"]]},"abstract":[{"type":"text","text":"Поворотом устройства (обычно из ландшафта в портрет)."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/devicerotation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/devicerotation"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceRotation"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/deviceRotation":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/deviceRotation","role":"symbol","abstract":[{"text":"Поворотом устройства (обычно из ландшафта в портрет).","type":"text"}],"navigatorTitle":[{"text":"OVKFullscreenViewControllerDismissMethodDeviceRotation","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/devicerotation","type":"topic","title":"FullscreenViewControllerDismissMethod.deviceRotation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceRotation"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","title":"FullscreenViewControllerDismissMethod","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","kind":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerDismissMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"Способ закрытия полноэкранного режима."}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerDismissMethod","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKFullscreenViewControllerDismissMethodDeviceRotation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKFullscreenViewControllerDismissMethodDeviceRotation","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"OVKFullscreenViewControllerDismissMethodDeviceRotation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1deviceRotation\/title","value":"OVKFullscreenViewControllerDismissMethodDeviceRotation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1deviceRotation\/fragments","value":[{"text":"OVKFullscreenViewControllerDismissMethodDeviceRotation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","value":"OVKFullscreenViewControllerDismissMethod"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments"},{"op":"replace","value":[{"text":"OVKFullscreenViewControllerDismissMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}