{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/Equatable-Implementations"},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/!=(_:_:)"],"anchor":"Operators"}],"sections":[],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"OVKit"}]},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"abstract":[{"text":"Способ закрытия полноэкранного режима.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","kind":"symbol","title":"FullscreenViewControllerDismissMethod","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","value":"OVKFullscreenViewControllerDismissMethod"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}