{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"s:5OVKit37FullscreenViewControllerDismissMethodO8rawValueACSgSi_tcfc","modules":[{"name":"OVKit"}],"symbolKind":"init","role":"symbol","title":"init(rawValue:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/init(rawValue:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","role":"symbol","kind":"symbol","title":"FullscreenViewControllerDismissMethod","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"abstract":[{"text":"Способ закрытия полноэкранного режима.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/init(rawValue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/init(rawValue:)"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","value":"OVKFullscreenViewControllerDismissMethod"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]}]}]}