{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"OVKFullscreenViewControllerDismissMethodOther","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod@OVKFullscreenViewControllerDismissMethodOther","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"title":"FullscreenViewControllerDismissMethod.other"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/other"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/other"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/other"},"sections":[],"abstract":[{"text":"Другой способ (обычно нажатие на кнопку или из кода).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"abstract":[{"text":"Способ закрытия полноэкранного режима.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","kind":"symbol","title":"FullscreenViewControllerDismissMethod","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/other":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/other","kind":"symbol","type":"topic","title":"FullscreenViewControllerDismissMethod.other","url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/other","abstract":[{"text":"Другой способ (обычно нажатие на кнопку или из кода).","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodOther"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKFullscreenViewControllerDismissMethodOther","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKFullscreenViewControllerDismissMethodOther","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodOther"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKFullscreenViewControllerDismissMethod","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title"},{"value":[{"text":"OVKFullscreenViewControllerDismissMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments"},{"value":[{"text":"OVKFullscreenViewControllerDismissMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle"},{"value":"OVKFullscreenViewControllerDismissMethodOther","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1other\/title"},{"value":[{"text":"OVKFullscreenViewControllerDismissMethodOther","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1other\/fragments"}]}]}