{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/swipe"},"metadata":{"modules":[{"name":"OVKit"}],"title":"FullscreenViewControllerDismissMethod.swipe","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodSwipe"}],"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKFullscreenViewControllerDismissMethod@OVKFullscreenViewControllerDismissMethodSwipe","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipe"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/swipe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/swipe"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipe","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Свайпом по экрану."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod/swipe":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod\/swipe","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipe","kind":"identifier"}],"title":"FullscreenViewControllerDismissMethod.swipe","navigatorTitle":[{"text":"OVKFullscreenViewControllerDismissMethodSwipe","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Свайпом по экрану."}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod\/swipe","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerDismissMethod":{"title":"FullscreenViewControllerDismissMethod","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerDismissMethod","kind":"symbol","abstract":[{"type":"text","text":"Способ закрытия полноэкранного режима."}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerdismissmethod","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerDismissMethod"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKFullscreenViewControllerDismissMethodSwipe"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKFullscreenViewControllerDismissMethodSwipe","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodSwipe"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1swipe\/title","op":"replace","value":"OVKFullscreenViewControllerDismissMethodSwipe"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod~1swipe\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethodSwipe"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/title","op":"replace","value":"OVKFullscreenViewControllerDismissMethod"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/fragments","op":"replace","value":[{"text":"OVKFullscreenViewControllerDismissMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerDismissMethod\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerDismissMethod"}]}]}]}