{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/deviceName"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/externalplaybackbadgeview\/devicename"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"deviceName","roleHeading":"Instance Property","externalID":"s:5OVKit25ExternalPlaybackBadgeViewC10deviceNameSSSgvp","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { get }"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView":{"type":"topic","navigatorTitle":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","abstract":[],"role":"symbol","title":"ExternalPlaybackBadgeView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExternalPlaybackBadgeView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/deviceName":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/deviceName","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/externalplaybackbadgeview\/devicename","title":"deviceName","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/title","value":"ExternalPlaybackBadgeView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/fragments","value":[{"kind":"identifier","text":"ExternalPlaybackBadgeView"}]},{"value":[{"kind":"identifier","text":"ExternalPlaybackBadgeView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/navigatorTitle"}]}]}