{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.property"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/state-swift.property","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"kind":"text","text":": "},{"text":"State","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit25ExternalPlaybackBadgeViewC5StateO"},{"text":" { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit25ExternalPlaybackBadgeViewC5StateO","kind":"typeIdentifier","text":"State"}],"title":"state","externalID":"s:5OVKit25ExternalPlaybackBadgeViewC5stateAC5StateOvp","symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView":{"role":"symbol","type":"topic","title":"ExternalPlaybackBadgeView","url":"\/documentation\/ovkit\/externalplaybackbadgeview","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExternalPlaybackBadgeView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExternalPlaybackBadgeView"}]},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/State-swift.enum":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/State-swift.enum","type":"topic","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.enum","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"text":"State","kind":"identifier"}],"title":"ExternalPlaybackBadgeView.State","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ExternalPlaybackBadgeView/state-swift.property":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/externalplaybackbadgeview\/state-swift.property","abstract":[],"title":"state","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ExternalPlaybackBadgeView\/state-swift.property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"},{"kind":"text","text":": "},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit25ExternalPlaybackBadgeViewC5StateO"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/title","value":"ExternalPlaybackBadgeView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/fragments","value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ExternalPlaybackBadgeView\/navigatorTitle","value":[{"text":"ExternalPlaybackBadgeView","kind":"identifier"}]}]}]}