{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isAllowedToPlay","kind":"identifier"},{"kind":"text","text":"("},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userAllowed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","symbolKind":"method","title":"isAllowedToPlay(_:userAllowed:)","externalID":"c:@M@OVKit@objc(cs)OVKRestrictionManager(im)isAllowedToPlay:userAllowed:","roleHeading":"Instance Method","navigatorTitle":[{"text":"isAllowedToPlay:userAllowed:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/restrictionmanager\/isallowedtoplay(_:userallowed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/restrictionmanager\/isallowedtoplay(_:userallowed:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/isAllowedToPlay(_:userAllowed:)"},"abstract":[{"text":"Разрешено ли проигрывание ","type":"text"},{"code":"video","type":"codeVoice"},{"type":"text","text":" с учетом политики запрета."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isAllowedToPlay","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"video"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},{"text":", ","kind":"text"},{"text":"userAllowed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео, которое проверяется на запрет проигрывания."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Когда ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" - разрешает проигрывание, если оно фактически доступно для видео. Например, видео с ","type":"text"},{"type":"codeVoice","code":"canPlay == false"},{"text":" нельзя играть даже после разблокировки.","type":"text"}]}],"name":"userAllowed"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager/isAllowedToPlay(_:userAllowed:)":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/restrictionmanager\/isallowedtoplay(_:userallowed:)","abstract":[{"text":"Разрешено ли проигрывание ","type":"text"},{"code":"video","type":"codeVoice"},{"type":"text","text":" с учетом политики запрета."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAllowedToPlay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"text":"userAllowed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isAllowedToPlay(_:userAllowed:)","navigatorTitle":[{"text":"isAllowedToPlay:userAllowed:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/isAllowedToPlay(_:userAllowed:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestrictionManager"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RestrictionManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/restrictionmanager","title":"RestrictionManager","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","title":"VideoType","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"isAllowedToPlay:userAllowed:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isAllowedToPlay:userAllowed:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isAllowedToPlay:"},{"text":"(","kind":"text"},{"text":"id<OVKVideoType>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"text":") ","kind":"text"},{"text":"video","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userAllowed:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"userAllowed"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"text":"Видео, которое проверяется на запрет проигрывания.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Когда ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" - разрешает проигрывание, если оно фактически доступно для видео. Например, видео с "},{"code":"canPlay == false","type":"codeVoice"},{"type":"text","text":" нельзя играть даже после разблокировки."}],"type":"paragraph"}],"name":"userAllowed"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1isAllowedToPlay(_:userAllowed:)\/title","value":"isAllowedToPlay:userAllowed:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isAllowedToPlay:userAllowed:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1isAllowedToPlay(_:userAllowed:)\/fragments"},{"op":"replace","value":"OVKRestrictionManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/fragments","value":[{"text":"OVKRestrictionManager","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKRestrictionManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/navigatorTitle"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}]}]}