{"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKRestrictionManager(cpy)shared","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"shared","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","text":"RestrictionManager","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/shared","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","text":"RestrictionManager","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/restrictionmanager\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/restrictionmanager\/shared"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager":{"title":"RestrictionManager","navigatorTitle":[{"kind":"identifier","text":"RestrictionManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","kind":"symbol","url":"\/documentation\/ovkit\/restrictionmanager","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RestrictionManager"}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager/shared":{"title":"shared","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","kind":"typeIdentifier","text":"RestrictionManager"}],"type":"topic","navigatorTitle":[{"text":"shared","kind":"identifier"}],"url":"\/documentation\/ovkit\/restrictionmanager\/shared","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager\/shared"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"shared","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","text":"OVKRestrictionManager","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/title","value":"OVKRestrictionManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/fragments","op":"replace","value":[{"text":"OVKRestrictionManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/navigatorTitle","value":[{"text":"OVKRestrictionManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1shared\/title","op":"replace","value":"shared"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager~1shared\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]}]}]}