{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livesettings\/canrewind"]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"canRewind","externalID":"s:5OVKit12LiveSettingsC9canRewindSbvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canRewind"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canRewind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"title":"LiveSettings","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveSettings","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LiveSettings"}],"role":"symbol","url":"\/documentation\/ovkit\/livesettings"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/canRewind":{"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/livesettings\/canrewind","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canRewind"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"canRewind"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","value":"OVKLiveSettings"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments","value":[{"kind":"identifier","text":"OVKLiveSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle","op":"replace","value":[{"text":"OVKLiveSettings","kind":"identifier"}]}]}]}