{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/endless"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/livesettings\/endless"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endless"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"externalID":"s:5OVKit12LiveSettingsC7endlessSbvp","roleHeading":"Instance Property","title":"endless","symbolKind":"property","role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endless"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"url":"\/documentation\/ovkit\/livesettings","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LiveSettings"}],"navigatorTitle":[{"text":"LiveSettings","kind":"identifier"}],"title":"LiveSettings","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/endless":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/livesettings\/endless","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"endless","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"endless","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/endless","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","value":"OVKLiveSettings","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments","op":"replace","value":[{"text":"OVKLiveSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLiveSettings"}],"op":"replace"}]}]}