{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livesettings\/maxrewindduration"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"maxRewindDuration","externalID":"s:5OVKit12LiveSettingsC17maxRewindDurationSdvp","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxRewindDuration"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"role":"symbol"},"abstract":[{"type":"text","text":"Максимальное время перемотки в секундах"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxRewindDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"url":"\/documentation\/ovkit\/livesettings","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LiveSettings"}],"navigatorTitle":[{"text":"LiveSettings","kind":"identifier"}],"title":"LiveSettings","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/maxRewindDuration":{"kind":"symbol","url":"\/documentation\/ovkit\/livesettings\/maxrewindduration","title":"maxRewindDuration","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxRewindDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration","role":"symbol","abstract":[{"text":"Максимальное время перемотки в секундах","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","value":"OVKLiveSettings"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}