{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/playbackDuration"},"variants":[{"paths":["\/documentation\/ovkit\/livesettings\/playbackduration"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings"]]},"sections":[],"abstract":[{"type":"text","text":"Сколько секунд прошло с начала стрима"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"externalID":"s:5OVKit12LiveSettingsC16playbackDurationSdvp","title":"playbackDuration","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/playbackDuration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Сколько секунд прошло с начала стрима"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/playbackDuration","url":"\/documentation\/ovkit\/livesettings\/playbackduration","title":"playbackDuration"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveSettings"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/livesettings","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LiveSettings"}],"title":"LiveSettings"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKLiveSettings","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/title","op":"replace"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/fragments","op":"replace"},{"value":[{"text":"OVKLiveSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveSettings\/navigatorTitle","op":"replace"}]}]}