{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timespentstatshandler\/starttimespent()"]},{"paths":["\/documentation\/ovkit\/timespentstatshandler\/starttimespent()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"]]},"abstract":[{"text":"Проигрывание началось.","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"title":"startTimespent()","externalID":"c:@M@OVKit@objc(pl)OVKTimespentStatsHandler(im)startTimespent","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTimespent"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"startTimespent","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/startTimespent()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startTimespent"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler/startTimespent()":{"role":"symbol","url":"\/documentation\/ovkit\/timespentstatshandler\/starttimespent()","kind":"symbol","title":"startTimespent()","abstract":[{"text":"Проигрывание началось.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/startTimespent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimespent"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"startTimespent"}]},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","abstract":[{"text":"Принимает события начала и остановки просмотра видео.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimespentStatsHandler","kind":"identifier"}],"navigatorTitle":[{"text":"TimespentStatsHandler","kind":"identifier"}],"title":"TimespentStatsHandler","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/timespentstatshandler","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"startTimespent","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startTimespent","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startTimespent"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"startTimespent","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1startTimespent()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1startTimespent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startTimespent"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title","value":"OVKTimespentStatsHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKTimespentStatsHandler"}]},{"value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle"}]}]}