{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"stopTimespent"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTimespent","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","title":"stopTimespent()","externalID":"c:@M@OVKit@objc(pl)OVKTimespentStatsHandler(im)stopTimespent","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTimespent","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/timespentstatshandler\/stoptimespent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timespentstatshandler\/stoptimespent()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/stopTimespent()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler"]]},"sections":[],"abstract":[{"text":"Проигрывание остановилось.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler/stopTimespent()":{"url":"\/documentation\/ovkit\/timespentstatshandler\/stoptimespent()","navigatorTitle":[{"kind":"identifier","text":"stopTimespent"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler\/stopTimespent()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimespent"},{"kind":"text","text":"()"}],"type":"topic","title":"stopTimespent()","abstract":[{"text":"Проигрывание остановилось.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimespentStatsHandler":{"url":"\/documentation\/ovkit\/timespentstatshandler","navigatorTitle":[{"kind":"identifier","text":"TimespentStatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimespentStatsHandler","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimespentStatsHandler"}],"type":"topic","title":"TimespentStatsHandler","abstract":[{"text":"Принимает события начала и остановки просмотра видео.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stopTimespent","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"stopTimespent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopTimespent"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"stopTimespent","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1stopTimespent()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopTimespent","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler~1stopTimespent()\/fragments"},{"op":"replace","value":"OVKTimespentStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/title"},{"op":"replace","value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/fragments"},{"op":"replace","value":[{"text":"OVKTimespentStatsHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimespentStatsHandler\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}