{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ScaleLabel\/sizeThatFits(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sizeThatFits","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ScaleLabel"]]},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeThatFits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"externalID":"c:@M@OVKit@objc(cs)ScaleLabel(im)sizeThatFits:","role":"symbol","title":"sizeThatFits(_:)","symbolKind":"method"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/scalelabel\/sizethatfits(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/scalelabel\/sizethatfits(_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ScaleLabel":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScaleLabel"}],"role":"symbol","title":"ScaleLabel","url":"\/documentation\/ovkit\/scalelabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ScaleLabel","navigatorTitle":[{"kind":"identifier","text":"ScaleLabel"}],"abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ScaleLabel/sizeThatFits(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ScaleLabel\/sizeThatFits(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeThatFits"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"title":"sizeThatFits(_:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sizeThatFits:"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/scalelabel\/sizethatfits(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"sizeThatFits:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeThatFits:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"sizeThatFits:"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ScaleLabel\/title","value":"ScaleLabel"},{"value":[{"text":"ScaleLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ScaleLabel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ScaleLabel~1sizeThatFits(_:)\/title","value":"sizeThatFits:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeThatFits:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ScaleLabel~1sizeThatFits(_:)\/fragments","op":"replace"}]}]}