{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asUpcoming","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"title":"asUpcoming","extendedModule":"OVKit","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"asUpcoming","kind":"identifier"}],"externalID":"c:@CM@OVKit@objc(cs)OVKCoverViewParams(py)asUpcoming","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asUpcoming","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/asUpcoming","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/coverviewparams\/asupcoming"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/coverviewparams\/asupcoming"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CoverView","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverview","title":"CoverView"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"url":"\/documentation\/ovkit\/coverviewparams","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Параметры для сборки "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"type":"text","text":"."}],"role":"symbol","title":"CoverViewParams"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/asUpcoming":{"kind":"symbol","title":"asUpcoming","navigatorTitle":[{"text":"asUpcoming","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/asUpcoming","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asUpcoming","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/ovkit\/coverviewparams\/asupcoming"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"asUpcoming"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"asUpcoming","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"asUpcoming"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","op":"replace","value":"OVKCoverViewParams"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","op":"replace","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","op":"replace","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1asUpcoming\/title","op":"replace","value":"asUpcoming"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1asUpcoming\/fragments","op":"replace","value":[{"text":"asUpcoming","kind":"identifier"}]}]}]}