{"variants":[{"paths":["\/documentation\/ovkit\/coverviewparams\/livestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/coverviewparams\/livestatus"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Если есть значение отличное от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","isActive":true,"type":"reference"},{"type":"text","text":", "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" должен показывать причины остановки трансляции."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"LiveStatus","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/liveStatus","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"}],"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)liveStatus","navigatorTitle":[{"kind":"identifier","text":"liveStatus"}],"title":"liveStatus","role":"symbol","symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","type":"topic","url":"\/documentation\/ovkit\/coverviewparams","abstract":[],"title":"CoverViewParams"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"navigatorTitle":[{"text":"OVKLiveStatusStarted","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/started","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","type":"topic","title":"LiveStatus.started","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"abstract":[{"text":"Live начался, видеопоток идет, должны быть live ссылки в files.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"url":"\/documentation\/ovkit\/livestatus","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","type":"topic","title":"LiveStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/liveStatus":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/liveStatus","kind":"symbol","title":"liveStatus","url":"\/documentation\/ovkit\/coverviewparams\/livestatus","navigatorTitle":[{"text":"liveStatus","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Если есть значение отличное от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","type":"reference","isActive":true},{"text":", ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":" должен показывать причины остановки трансляции."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"liveStatus","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"liveStatus"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"OVKLiveStatus","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"liveStatus","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams","op":"replace"},{"value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title","value":"OVKLiveStatusStarted"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusStarted"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatus"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1liveStatus\/title","value":"liveStatus"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1liveStatus\/fragments","op":"replace","value":[{"text":"liveStatus","kind":"identifier"}]}]}]}