{"variants":[{"paths":["\/documentation\/ovkit\/coverviewparams\/restriction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/coverviewparams\/restriction"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"abstract":[{"type":"text","text":"Если есть значение, "},{"code":"CoverView","type":"codeVoice"},{"type":"text","text":" должен быть о снятии ограничений."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"restriction","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","text":"VideoRestrictionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)restriction","role":"symbol","navigatorTitle":[{"text":"restriction","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"restriction","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoRestrictionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"restriction","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"url":"\/documentation\/ovkit\/coverviewparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoverViewParams"}],"kind":"symbol","role":"symbol","title":"CoverViewParams","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","type":"topic","abstract":[],"navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/restriction":{"navigatorTitle":[{"kind":"identifier","text":"restriction"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/restriction","title":"restriction","type":"topic","abstract":[{"type":"text","text":"Если есть значение, "},{"type":"codeVoice","code":"CoverView"},{"text":" должен быть о снятии ограничений.","type":"text"}],"url":"\/documentation\/ovkit\/coverviewparams\/restriction","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionType","kind":"identifier"}],"title":"VideoRestrictionType","navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"restriction","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"restriction"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<OVKVideoRestrictionType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restriction"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","op":"replace","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCoverViewParams"}]},{"value":"restriction","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1restriction\/fragments","value":[{"text":"restriction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","op":"replace","value":"OVKVideoRestrictionType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}