{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { get }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Приходит в формате unix timestamp. Если значение равно нулю — время начала трансляции не известно.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/startTime","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"externalID":"c:@M@OVKit@objc(cs)OVKCoverViewParams(py)startTime","title":"startTime","symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams"]]},"abstract":[{"type":"text","text":"Будет актуален, если значение "},{"type":"codeVoice","code":"liveStatus"},{"type":"text","text":" равно "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/coverviewparams\/starttime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/coverviewparams\/starttime"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","title":"CoverViewParams","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","url":"\/documentation\/ovkit\/coverviewparams","abstract":[{"text":"Параметры для сборки ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverViewParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverViewParams"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams/startTime":{"kind":"symbol","title":"startTime","type":"topic","url":"\/documentation\/ovkit\/coverviewparams\/starttime","abstract":[{"type":"text","text":"Будет актуален, если значение "},{"code":"liveStatus","type":"codeVoice"},{"text":" равно ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams\/startTime","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","title":"CoverView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","url":"\/documentation\/ovkit\/coverview","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoverView"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/upcoming":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/livestatus\/upcoming","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upcoming"}],"title":"LiveStatus.upcoming","abstract":[{"type":"text","text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"startTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"startTime","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"text":"OVKCoverViewParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1startTime\/title","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams~1startTime\/fragments","value":[{"text":"startTime","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/title","value":"OVKLiveStatusUpcoming"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/fragments","value":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}]}]}]}