{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMinQualityParameterName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"]]},"abstract":[{"type":"text","text":"Переопределение названия параметра в URL на HLS-манифест для минимально доступного качества."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"customMinQualityParameterName","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoURLQuery(py)customMinQualityParameterName","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customMinQualityParameterName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"customMinQualityParameterName","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customMinQualityParameterName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/videourlquery\/customminqualityparametername"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videourlquery\/customminqualityparametername"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery/customMinQualityParameterName":{"abstract":[{"text":"Переопределение названия параметра в URL на HLS-манифест для минимально доступного качества.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customMinQualityParameterName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"customMinQualityParameterName","navigatorTitle":[{"text":"customMinQualityParameterName","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/customMinQualityParameterName","url":"\/documentation\/ovkit\/videourlquery\/customminqualityparametername"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoURLQuery","kind":"identifier"}],"url":"\/documentation\/ovkit\/videourlquery","type":"topic","abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","title":"VideoURLQuery","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"customMinQualityParameterName","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"customMinQualityParameterName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"customMinQualityParameterName","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"customMinQualityParameterName","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMinQualityParameterName\/title"},{"value":[{"text":"customMinQualityParameterName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1customMinQualityParameterName\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","op":"replace","value":"OVKVideoURLQuery"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments","value":[{"kind":"identifier","text":"OVKVideoURLQuery"}]},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}