{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/init(customMinQualityParameterName:customMaxQualityParameterName:)"},"variants":[{"paths":["\/documentation\/ovkit\/videourlquery\/init(customminqualityparametername:custommaxqualityparametername:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videourlquery\/init(customminqualityparametername:custommaxqualityparametername:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customMinQualityParameterName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"customMaxQualityParameterName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"init(customMinQualityParameterName:customMaxQualityParameterName:)","symbolKind":"init","externalID":"c:@M@OVKit@objc(cs)OVKVideoURLQuery(im)initWithCustomMinQualityParameterName:customMaxQualityParameterName:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customMinQualityParameterName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customMaxQualityParameterName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"abstract":[{"text":"Набор дополнительных параметров в URL на видео ресурс.","type":"text"}],"url":"\/documentation\/ovkit\/videourlquery","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoURLQuery"}],"navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}],"title":"VideoURLQuery","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery/init(customMinQualityParameterName:customMaxQualityParameterName:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery\/init(customMinQualityParameterName:customMaxQualityParameterName:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"customMinQualityParameterName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"customMaxQualityParameterName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"title":"init(customMinQualityParameterName:customMaxQualityParameterName:)","role":"symbol","url":"\/documentation\/ovkit\/videourlquery\/init(customminqualityparametername:custommaxqualityparametername:)","navigatorTitle":[{"text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCustomMinQualityParameterName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"customMinQualityParameterName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"customMaxQualityParameterName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"customMaxQualityParameterName"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoURLQuery","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/navigatorTitle","value":[{"text":"OVKVideoURLQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1init(customMinQualityParameterName:customMaxQualityParameterName:)\/title","value":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery~1init(customMinQualityParameterName:customMaxQualityParameterName:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomMinQualityParameterName:customMaxQualityParameterName:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}