{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:)"},"abstract":[{"text":"Полноэкранный плеер был закрыт.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCloseInto"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"fullscreenController","content":[{"inlineContent":[{"type":"text","text":"Полноэкранный контроллер, который закрылся."}],"type":"paragraph"}]},{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":"Плеер, в который вернулось воспроизведение после закрытия. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает, что воспроизведение завершилось."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Метод вызывается при закрытии полноэкранного режима с анимацией, сразу после завершения анимации.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"variants":[{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:)"]}],"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fullscreenController:didCloseInto:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"fullscreenController(_:didCloseInto:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)fullscreenController:didCloseInto:","role":"symbol","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","title":"PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenController(_:didCloseInto:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:)","title":"fullscreenController(_:didCloseInto:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullscreenController","kind":"identifier"},{"kind":"text","text":"("},{"text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Полноэкранный плеер был закрыт.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fullscreenController:didCloseInto:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"FullscreenController","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreencontroller","title":"FullscreenController","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"FullscreenController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"fullscreenController:didCloseInto:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"fullscreenController:didCloseInto:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"fullscreenController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol","text":"UIViewController<OVKFullscreenViewControllerProtocol>"},{"text":" *) ","kind":"text"},{"text":"fullscreenController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didCloseInto:","kind":"identifier"},{"kind":"text","text":"("},{"text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"OVKPlayerManagerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:)\/title","op":"replace","value":"fullscreenController:didCloseInto:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"fullscreenController:didCloseInto:","kind":"identifier"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}]}]}