{"abstract":[{"text":"Полноэкранный плеер был закрыт.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)"},"metadata":{"title":"fullscreenController(_:didCloseInto:interactive:)","navigatorTitle":[{"text":"fullscreenController:didCloseInto:interactive:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)fullscreenController:didCloseInto:interactive:","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?, ","kind":"text"},{"text":"interactive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:interactive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:interactive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fullscreenController"},{"kind":"text","text":": "},{"text":"FullscreenController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?, ","kind":"text"},{"text":"interactive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fullscreenController","content":[{"inlineContent":[{"type":"text","text":"Полноэкранный контроллер, который закрылся."}],"type":"paragraph"}]},{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":"Плеер, в который вернулось воспроизведение после закрытия. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что воспроизведение завершилось."}],"type":"paragraph"}]},{"name":"interactive","content":[{"inlineContent":[{"type":"text","text":"Было ли закрытие совершено с интерактивной анимацией."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Метод вызывается при закрытии полноэкранного режима с анимацией, сразу после завершения анимации.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenController(_:didCloseInto:interactive:)":{"navigatorTitle":[{"text":"fullscreenController:didCloseInto:interactive:","kind":"identifier"}],"title":"fullscreenController(_:didCloseInto:interactive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullscreenController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCloseInto","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"interactive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Полноэкранный плеер был закрыт."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenController(_:didCloseInto:interactive:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontroller(_:didcloseinto:interactive:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","abstract":[],"navigatorTitle":[{"text":"FullscreenController","kind":"identifier"}],"type":"topic","title":"FullscreenController","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/fullscreencontroller"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"kind":"symbol","title":"PlayerManagerDelegate","type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","url":"\/documentation\/ovkit\/playermanagerdelegate","role":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","title":"PlayerView","url":"\/documentation\/ovkit\/playerview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fullscreenController:didCloseInto:interactive:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenController:didCloseInto:interactive:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fullscreenController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController<OVKFullscreenViewControllerProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol"},{"text":" *) ","kind":"text"},{"text":"fullscreenController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCloseInto:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"OVKPlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"interactive:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"interactive","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"fullscreenController","content":[{"inlineContent":[{"text":"Полноэкранный контроллер, который закрылся.","type":"text"}],"type":"paragraph"}]},{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":"Плеер, в который вернулось воспроизведение после закрытия. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает, что воспроизведение завершилось."}],"type":"paragraph"}]},{"name":"interactive","content":[{"inlineContent":[{"text":"Было ли закрытие совершено с интерактивной анимацией.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/title","value":"fullscreenController:didCloseInto:interactive:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenController(_:didCloseInto:interactive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenController:didCloseInto:interactive:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}