{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenControls"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"video","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":"?, ","kind":"text"},{"text":"originPlayerView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Видео, которое открывается в полноэкранном режиме.","type":"text"}],"type":"paragraph"}],"name":"video"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":", из которого открывается полноэкранный режим. Если это ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", значит полноэкранный режим открывается самостоятельно.","type":"text"}],"type":"paragraph"}],"name":"originPlayerView"}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen"]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"name":"Warning","content":[{"inlineContent":[{"text":"Возвращаемое ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" должно реализовывать ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol"},{"text":".","type":"text"}],"type":"paragraph"}],"type":"aside","style":"warning"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","interfaceLanguage":"swift"},"abstract":[{"text":"Определить для возможности использования собственных контролов в полноэкранном режиме.","type":"text"}],"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fullscreenControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":"?, "},{"text":"originPlayerView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"fullscreenControls(for:originPlayerView:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"fullscreenControlsFor:originPlayerView:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)fullscreenControlsFor:originPlayerView:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","url":"\/documentation\/ovkit\/playerview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"kind":"symbol","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"type":"topic","kind":"article","role":"article","title":"Полноэкранный режим","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"url":"\/documentation\/ovkit\/fullscreen"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"title":"PlayerManagerDelegate","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Controls":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Controls","url":"\/documentation\/ovkit\/controls","type":"topic","title":"Контролы плеера","kind":"article","abstract":[{"type":"text","text":"Кастомизация внешнего вида плеера."}],"role":"article"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","url":"\/documentation\/ovkit\/videotype","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/fullscreenControls(for:originPlayerView:)":{"title":"fullscreenControls(for:originPlayerView:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/fullscreencontrols(for:originplayerview:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/fullscreenControls(for:originPlayerView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreenControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originPlayerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}],"kind":"symbol","abstract":[{"type":"text","text":"Определить для возможности использования собственных контролов в полноэкранном режиме."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerFullscreenControlsViewProtocol":{"type":"topic","navigatorTitle":[{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerFullscreenControlsViewProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerFullscreenControlsViewProtocol","abstract":[{"type":"text","text":"Протокол для контролов, которые могут использоваться в полноэкранном режиме проигрывания."}],"url":"\/documentation\/ovkit\/playerfullscreencontrolsviewprotocol","role":"symbol","kind":"symbol","title":"PlayerFullscreenControlsViewProtocol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"fullscreenControlsFor:originPlayerView:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fullscreenControlsFor:originPlayerView:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fullscreenControlsFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<OVKVideoType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"video"},{"kind":"text","text":" "},{"kind":"identifier","text":"originPlayerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"originPlayerView"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"video","content":[{"inlineContent":[{"text":"Видео, которое открывается в полноэкранном режиме.","type":"text"}],"type":"paragraph"}]},{"name":"originPlayerView","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":", из которого открывается полноэкранный режим. Если это ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", значит полноэкранный режим открывается самостоятельно.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"OVKPlayerManagerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"op":"replace","value":"fullscreenControlsFor:originPlayerView:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fullscreenControlsFor:originPlayerView:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1fullscreenControls(for:originPlayerView:)\/fragments"}]}]}