{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"sections":[],"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)pictureInPictureControlsWith:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControls","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"pictureInPictureControlsWith:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"pictureInPictureControls(with:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Контролы для использования в режиме “Картинка в Картинке”."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"CGRect","type":"codeVoice"},{"type":"text","text":" с размерами view."}]}],"name":"frame"}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Возвращаемое "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" должно реализовывать "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"},{"type":"text","text":"."}],"type":"paragraph"}],"style":"warning","name":"Warning","type":"aside"}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pictureinpicturecontrols(with:)"]},{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pictureinpicturecontrols(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"kind":"symbol","title":"PlayerControlsViewProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol","abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerControlsViewProtocol"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","title":"PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pictureInPictureControls(with:)":{"kind":"symbol","title":"pictureInPictureControls(with:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pictureInPictureControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/pictureinpicturecontrols(with:)","abstract":[{"type":"text","text":"Контролы для использования в режиме “Картинка в Картинке”."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pictureInPictureControls(with:)","type":"topic","navigatorTitle":[{"text":"pictureInPictureControlsWith:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pictureInPictureControlsWith:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"pictureInPictureControlsWith:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"text":"pictureInPictureControlsWith:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/title","value":"pictureInPictureControlsWith:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pictureInPictureControlsWith:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pictureInPictureControls(with:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}