{"abstract":[{"type":"text","text":"Отступы от краев экрана для PiP, опрашивается перед показом и при повороте экрана. При показе и скрытии клавиатуры эти отступы автоматически подстраиваются под ее высоту."}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipScreenInsets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":") -> ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"navigatorTitle":[{"text":"pipScreenInsets:","kind":"identifier"}],"symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"title":"pipScreenInsets(_:)","required":true,"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)pipScreenInsets:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipScreenInsets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipScreenInsets(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pipscreeninsets(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pipscreeninsets(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipScreenInsets(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pipScreenInsets"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"role":"symbol","url":"\/documentation\/ovkit\/playermanagerdelegate\/pipscreeninsets(_:)","kind":"symbol","abstract":[{"type":"text","text":"Отступы от краев экрана для PiP, опрашивается перед показом и при повороте экрана. При показе и скрытии клавиатуры эти отступы автоматически подстраиваются под ее высоту."}],"title":"pipScreenInsets(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipScreenInsets(_:)","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"pipScreenInsets:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"role":"symbol","title":"PlayerManagerDelegate","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/playermanagerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pipScreenInsets:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pipScreenInsets:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"kind":"text","text":") "},{"kind":"identifier","text":"pipScreenInsets:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"pipScreenInsets:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipScreenInsets(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pipScreenInsets:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipScreenInsets(_:)\/fragments"},{"op":"replace","value":"OVKPlayerManagerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle"}]}]}