{"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","title":"pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pipWindow","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"restoreUserInterfaceForPipMaximizeWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","required":true,"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pip","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},{"text":", ","kind":"text"},{"text":"restoreUserInterfaceForPipMaximizeWithCompletionHandler","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Окно, которое разворачивается.","type":"text"}],"type":"paragraph"}],"name":"pip"},{"content":[{"inlineContent":[{"type":"text","text":"Вызвать после подготовки UI. Параметром является "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":", в который перенесется воспроизводимое видео. В нем не должно быть ресурса (","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","isActive":true},{"type":"text","text":" "},{"type":"codeVoice","code":"== nil"},{"text":"). Перенос осуществляется мгновенно. Если в параметр передать ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", произойдет переход в полноэкранный режим."}],"type":"paragraph"}],"name":"completionHandler"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"Относится только к внутренней реализации PiP. Для поведения по умолчанию в "},{"type":"codeVoice","code":"completionHandler"},{"type":"text","text":" можно передать "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"abstract":[{"type":"text","text":"Возможность подготовить UI к разворачиванию окна Picture in Picture."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pipwindow(_:restoreuserinterfaceforpipmaximizewithcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/pipwindow(_:restoreuserinterfaceforpipmaximizewithcompletionhandler:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)":{"role":"symbol","abstract":[{"type":"text","text":"Возможность подготовить UI к разворачиванию окна Picture in Picture."}],"navigatorTitle":[{"text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"}],"title":"pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipWindow"},{"text":"(","kind":"text"},{"text":"PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"restoreUserInterfaceForPipMaximizeWithCompletionHandler"},{"text":": (","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/ovkit\/playermanagerdelegate\/pipwindow(_:restoreuserinterfaceforpipmaximizewithcompletionhandler:)","type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/stop()":{"kind":"symbol","abstract":[{"type":"text","text":"Остановка и очистка плеера"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","url":"\/documentation\/ovkit\/playerview\/stop()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"url":"\/documentation\/ovkit\/playerview","role":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/prepareForReuse()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepareForReuse"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","url":"\/documentation\/ovkit\/playerview\/prepareforreuse()","title":"prepareForReuse()","type":"topic","navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PiPWindow","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Device Orientation для ","type":"text"},{"code":"PlayerManager.shared.pipWindow","type":"codeVoice"},{"type":"text","text":" можно поддержать"},{"text":" ","type":"text"},{"type":"text","text":"в методе AppDelegate "},{"type":"codeVoice","code":"application(_:supportedIntefaceOrientationsFor:)"}],"title":"PiPWindow","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"url":"\/documentation\/ovkit\/playerview\/video","abstract":[{"type":"text","text":"Не устанавливать nil: останавливать проигрывание необходимо через "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","type":"reference","isActive":true},{"text":" или ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","type":"reference"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"video","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","type":"topic","kind":"symbol","title":"video","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"PlayerManagerDelegate","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"pipWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier","text":"OVKPiPWindow"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pip"},{"kind":"text","text":" "},{"text":"restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Окно, которое разворачивается.","type":"text"}]}],"name":"pip"},{"content":[{"inlineContent":[{"text":"Вызвать после подготовки UI. Параметром является ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", в который перенесется воспроизводимое видео. В нем не должно быть ресурса (","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},{"type":"text","text":" "},{"code":"== nil","type":"codeVoice"},{"text":"). Перенос осуществляется мгновенно. Если в параметр передать ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", произойдет переход в полноэкранный режим."}],"type":"paragraph"}],"name":"completionHandler"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)\/title","op":"replace","value":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"pipWindow:restoreUserInterfaceForPipMaximizeWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1pipWindow(_:restoreUserInterfaceForPipMaximizeWithCompletionHandler:)\/fragments"},{"value":"stop","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"stop","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/title","value":"prepareForReuse","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","op":"replace","value":[{"text":"OVKPiPWindow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title","op":"replace","value":"video"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","op":"replace","value":[{"kind":"identifier","text":"video"}]},{"op":"replace","value":"OVKPlayerManagerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","op":"replace"}]}]}