{"metadata":{"role":"symbol","required":true,"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)playerView:presentMenu:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"presentMenu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKMenu","text":"Menu"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"title":"playerView(_:presentMenu:)","navigatorTitle":[{"kind":"identifier","text":"playerView:presentMenu:"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:presentMenu:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Просит делегата показать меню в виде Action Sheet."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?, "},{"text":"presentMenu","kind":"externalParam"},{"kind":"text","text":" "},{"text":"menu","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Menu","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKMenu","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", которому нужно показать меню. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что меню показывается не в рамках конкретного плеера."}],"type":"paragraph"}],"name":"playerView"},{"content":[{"inlineContent":[{"type":"text","text":"Описание меню для показа."}],"type":"paragraph"}],"name":"menu"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:presentmenu:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:presentmenu:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"title":"PlayerManagerDelegate","kind":"symbol","role":"symbol","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Menu":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Menu"}],"url":"\/documentation\/ovkit\/menu","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Menu","abstract":[{"type":"text","text":"Модель, описывающая UI для построения меню плеера."}],"title":"Menu","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Menu","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:presentMenu:)":{"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"presentMenu","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKMenu","text":"Menu"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Просит делегата показать меню в виде Action Sheet."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:presentMenu:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:presentmenu:)","kind":"symbol","title":"playerView(_:presentMenu:)","navigatorTitle":[{"kind":"identifier","text":"playerView:presentMenu:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerView:presentMenu:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"playerView:presentMenu:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"playerView:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":" "},{"text":"presentMenu:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKMenu","text":"id<OVKMenu>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"menu"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", которому нужно показать меню. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает, что меню показывается не в рамках конкретного плеера."}],"type":"paragraph"}],"name":"playerView"},{"content":[{"inlineContent":[{"type":"text","text":"Описание меню для показа."}],"type":"paragraph"}],"name":"menu"}]}},{"value":"OVKPlayerManagerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"OVKMenu","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/title"},{"op":"replace","value":[{"text":"OVKMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Menu\/navigatorTitle","value":[{"text":"OVKMenu","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:presentMenu:)\/title","value":"playerView:presentMenu:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:presentMenu:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerView:presentMenu:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}