{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"abstract":[{"text":"Плеер был показан в полноэкранном режиме.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fromPlayerView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"willShowFullscreen"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fullscreenController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","kind":"typeIdentifier","text":"FullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier","text":"FullscreenController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fromPlayerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", с которого был совершен переход в полноэкранный режим. Если "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", полноэкранный режим был открыт непосредственно."}]}]},{"name":"fullscreenController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Контроллер, с полноэкранным "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Контроллер-обертка, соответствующий протоколу "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"},{"type":"text","text":", внутри которого находится переданный в параметре "},{"type":"codeVoice","code":"fullscreenController"},{"type":"text","text":". Если обертка не используется, необходимо вернуть "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen"],"kind":"mentions"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Полноэкранный плеер является отдельным "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":". Ему необходимо установить "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"playerView:willShowFullscreen:"}],"title":"playerView(_:willShowFullscreen:)","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)playerView:willShowFullscreen:","required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"willShowFullscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"title":"PlayerManagerDelegate","kind":"symbol","role":"symbol","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/delegate":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/ovkit\/playerview\/delegate","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate","title":"delegate","abstract":[{"text":"Делегат плеера по вопросам жизненного цикла воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerDelegate","text":"PlayerDelegate"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowFullscreen:)":{"navigatorTitle":[{"kind":"identifier","text":"playerView:willShowFullscreen:"}],"title":"playerView(_:willShowFullscreen:)","kind":"symbol","role":"symbol","abstract":[{"text":"Плеер был показан в полноэкранном режиме.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"willShowFullscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Контроллер, который используется для полноэкранного просмотра."}],"role":"symbol","title":"FullscreenViewControllerProtocol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","url":"\/documentation\/ovkit\/fullscreencontroller","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"FullscreenController"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenContentViewController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","abstract":[{"text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","kind":"symbol","title":"FullscreenContentViewController","navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/transitions","role":"article","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","title":"Переходы между плеерами","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" в другой.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Fullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Fullscreen","url":"\/documentation\/ovkit\/fullscreen","kind":"article","type":"topic","abstract":[{"type":"text","text":"Кастомизация полноэкранного просмотра."}],"role":"article","title":"Полноэкранный режим"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerView:willShowFullscreen:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerView:willShowFullscreen:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIViewController<OVKFullscreenViewControllerProtocol>","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"playerView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromPlayerView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willShowFullscreen:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKFullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fullscreenController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"fromPlayerView","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", с которого был совершен переход в полноэкранный режим. Если ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", полноэкранный режим был открыт непосредственно.","type":"text"}],"type":"paragraph"}]},{"name":"fullscreenController","content":[{"inlineContent":[{"type":"text","text":"Контроллер, с полноэкранным "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Контроллер-обертка, соответствующий протоколу "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"},{"type":"text","text":", внутри которого находится переданный в параметре "},{"type":"codeVoice","code":"fullscreenController"},{"type":"text","text":". Если обертка не используется, необходимо вернуть "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/title","value":"playerView:willShowFullscreen:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerView:willShowFullscreen:","kind":"identifier"}],"op":"replace"},{"value":"OVKFullscreenViewControllerProtocol","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle"},{"value":"OVKFullscreenContentViewController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenContentViewController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}