{"abstract":[{"text":"Был создан внутренний Picture in Picture плеер, необходимо установить ","type":"text"},{"type":"codeVoice","code":"pip.playerView.delegate"},{"text":". Но не стоит поручать это какому-нибудь ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":", жизненный цикл которого может быть меньше, чем у окна Picture in Picture.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fromPlayerView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"willShowPiP","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pip","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"fromPlayerView","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"type":"text","text":", который сворачивается в Picture in Picture."}],"type":"paragraph"}]},{"name":"pip","content":[{"inlineContent":[{"type":"text","text":"Окно Picture in Picture плеера."}],"type":"paragraph"}]}],"kind":"parameters"},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions"],"kind":"mentions"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"В момент вызова модель ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true,"type":"reference"},{"text":" уже находится в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowpip:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowpip:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)playerView:willShowPiP:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"willShowPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":")","kind":"text"}],"title":"playerView(_:willShowPiP:)","symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"playerView:willShowPiP:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"url":"\/documentation\/ovkit\/transitions","type":"topic","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","title":"Переходы между плеерами","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/playerView":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"}],"kind":"symbol","title":"playerView","url":"\/documentation\/ovkit\/pipwindow\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/playerView","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerView"}],"abstract":[{"text":"Плеер, который отвечает за воспроизведение видео в окне.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PlayerManagerDelegate"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","title":"PlayerManagerDelegate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManagerDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"type":"topic","title":"PiPWindow","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PiPWindow"}],"abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowPiP:)":{"abstract":[{"type":"text","text":"Был создан внутренний Picture in Picture плеер, необходимо установить "},{"type":"codeVoice","code":"pip.playerView.delegate"},{"type":"text","text":". Но не стоит поручать это какому-нибудь "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":", жизненный цикл которого может быть меньше, чем у окна Picture in Picture."}],"title":"playerView(_:willShowPiP:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowpip:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willShowPiP"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"PiPWindow"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowPiP:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerView:willShowPiP:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playerView:willShowPiP:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"playerView:willShowPiP:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fromPlayerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"willShowPiP:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","text":"OVKPiPWindow"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pip"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", который сворачивается в Picture in Picture."}]}],"name":"fromPlayerView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Окно Picture in Picture плеера."}]}],"name":"pip"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"playerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/title"},{"value":[{"text":"playerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1playerView\/fragments"},{"value":"OVKPlayerManagerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title"},{"value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"},{"value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"value":"OVKPiPWindow","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"},{"value":"playerView:willShowPiP:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playerView:willShowPiP:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowPiP:)\/fragments"}]}]}