{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendBugReportWithDiagnosticsData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"diagnosticsData"},{"kind":"text","text":": "},{"text":"BugReportDiagnosticsData","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"diagnosticsData","content":[{"inlineContent":[{"type":"text","text":"Данные для диагностики состояния плеера."}],"type":"paragraph"}]},{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", с которого пользователь хочет отправить багрепорт."}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Вызов этого метода означает, что клиент инициировал сценарий отправки багрепорта. Клиент, используя данные диагностики из аргумента, может добавить дополнительное пояснение от пользователя и залоггировать у себя багрепорт.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/sendbugreportwithdiagnosticsdata(_:from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/sendbugreportwithdiagnosticsdata(_:from:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/sendBugReportWithDiagnosticsData(_:from:)"},"abstract":[{"text":"Отправка багрепорта клиентом.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)sendBugReportWithDiagnosticsData:from:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendBugReportWithDiagnosticsData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BugReportDiagnosticsData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"title":"sendBugReportWithDiagnosticsData(_:from:)","navigatorTitle":[{"text":"sendBugReportWithDiagnosticsData:from:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"kind":"symbol","title":"PlayerManagerDelegate","type":"topic","url":"\/documentation\/ovkit\/playermanagerdelegate","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManagerDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/sendBugReportWithDiagnosticsData(_:from:)":{"role":"symbol","abstract":[{"text":"Отправка багрепорта клиентом.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sendBugReportWithDiagnosticsData:from:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBugReportWithDiagnosticsData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData","text":"BugReportDiagnosticsData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/sendBugReportWithDiagnosticsData(_:from:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/sendbugreportwithdiagnosticsdata(_:from:)","kind":"symbol","title":"sendBugReportWithDiagnosticsData(_:from:)"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BugReportDiagnosticsData"}],"url":"\/documentation\/ovkit\/bugreportdiagnosticsdata","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BugReportDiagnosticsData"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","title":"BugReportDiagnosticsData","role":"symbol","abstract":[{"type":"text","text":"Описание состояния плеера для диагностики."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sendBugReportWithDiagnosticsData:from:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"sendBugReportWithDiagnosticsData:from:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendBugReportWithDiagnosticsData:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData","text":"OVKBugReportDiagnosticsData","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"diagnosticsData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"diagnosticsData","content":[{"inlineContent":[{"type":"text","text":"Данные для диагностики состояния плеера."}],"type":"paragraph"}]},{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", с которого пользователь хочет отправить багрепорт."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKPlayerManagerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","op":"replace"},{"value":"sendBugReportWithDiagnosticsData:from:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1sendBugReportWithDiagnosticsData(_:from:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendBugReportWithDiagnosticsData:from:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1sendBugReportWithDiagnosticsData(_:from:)\/fragments","op":"replace"},{"op":"replace","value":"OVKBugReportDiagnosticsData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/title"},{"op":"replace","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/fragments"},{"value":[{"kind":"identifier","text":"OVKBugReportDiagnosticsData"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/navigatorTitle","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"}]}]}