{"sections":[],"abstract":[{"type":"text","text":"Событие о закрытии системного Picture in Picture."}],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemPictureInPictureWillStop"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CALayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"systemPictureInPictureWillStopIn:","kind":"identifier"}],"role":"symbol","title":"systemPictureInPictureWillStop(in:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)systemPictureInPictureWillStopIn:","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPictureInPictureWillStop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"layer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CALayer","text":"CALayer","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"Вызывается перед восстановлением системного Picture in Picture в методе ","type":"text"},{"code":"AVPictureInPictureControllerDelegate.pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/systemPictureInPictureWillStop(in:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/systempictureinpicturewillstop(in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/systempictureinpicturewillstop(in:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","title":"PlayerManagerDelegate","abstract":[{"type":"text","text":"Делегат менеджера плееров."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/systemPictureInPictureWillStop(in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemPictureInPictureWillStop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CALayer","text":"CALayer"},{"kind":"text","text":")"}],"abstract":[{"text":"Событие о закрытии системного Picture in Picture.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/systemPictureInPictureWillStop(in:)","title":"systemPictureInPictureWillStop(in:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemPictureInPictureWillStopIn:"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/systempictureinpicturewillstop(in:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"systemPictureInPictureWillStopIn:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"systemPictureInPictureWillStopIn:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"systemPictureInPictureWillStopIn:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CALayer","text":"CALayer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"layer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","op":"replace","value":"OVKPlayerManagerDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1systemPictureInPictureWillStop(in:)\/title","op":"replace","value":"systemPictureInPictureWillStopIn:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1systemPictureInPictureWillStop(in:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"systemPictureInPictureWillStopIn:","kind":"identifier"}]}]}]}