{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"topViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Отданный ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" не должен находиться внутри окна, которым владеет ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":" (например, ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","type":"reference"},{"text":"), даже если оно является ","type":"text"},{"code":"keyWindow","type":"codeVoice"},{"text":". Отдача должна совершаться быстро.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/topViewController()","interfaceLanguage":"swift"},"abstract":[{"text":"Верхний в иерархии ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":", с которого будет совершена навигация.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/topviewcontroller()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/topviewcontroller()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"topViewController"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"topViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"symbolKind":"method","required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)topViewController","title":"topViewController()"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/topViewController()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"topViewController"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"topViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/topViewController()","abstract":[{"text":"Верхний в иерархии ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":", с которого будет совершена навигация.","type":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate\/topviewcontroller()","required":true,"kind":"symbol","role":"symbol","title":"topViewController()"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"title":"PiPWindow","url":"\/documentation\/ovkit\/pipwindow","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PiPWindow"}],"navigatorTitle":[{"kind":"identifier","text":"PiPWindow"}],"kind":"symbol","abstract":[{"type":"text","text":"Окно внутреннего Picture in Picture."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"title":"PlayerManagerDelegate","navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"topViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"topViewController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"topViewController","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1topViewController()\/title","value":"topViewController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1topViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"topViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"kind":"identifier","text":"OVKPiPWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPiPWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}