{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/videoSessionIdentifier(for:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"videoSessionIdentifier(for:)","navigatorTitle":[{"kind":"identifier","text":"videoSessionIdentifierFor:"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate(im)videoSessionIdentifierFor:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSessionIdentifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate"]]},"abstract":[{"type":"text","text":"Идентификатор (VSID) сессии проигрывания."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/videosessionidentifier(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanagerdelegate\/videosessionidentifier(for:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoSessionIdentifier","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"video","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"video","content":[{"type":"paragraph","inlineContent":[{"text":"Видео, для которого нужно получить идентификатор.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Необходимо для связывания сессии префетчера и плеера. Получить идентификатор можно у ","type":"text"},{"code":"StatsManager","type":"codeVoice"},{"text":" из модуля ","type":"text"},{"code":"OVKitStatistics","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","role":"symbol","abstract":[{"text":"Делегат менеджера плееров.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerManagerDelegate"}],"url":"\/documentation\/ovkit\/playermanagerdelegate","type":"topic","title":"PlayerManagerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManagerDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoType"}],"abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","url":"\/documentation\/ovkit\/videotype","kind":"symbol","role":"symbol","title":"VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/videoSessionIdentifier(for:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/videoSessionIdentifier(for:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/videosessionidentifier(for:)","title":"videoSessionIdentifier(for:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoSessionIdentifier","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"videoSessionIdentifierFor:","kind":"identifier"}],"abstract":[{"text":"Идентификатор (VSID) сессии проигрывания.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"videoSessionIdentifierFor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"videoSessionIdentifierFor:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"videoSessionIdentifierFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<OVKVideoType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"video"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"video","content":[{"inlineContent":[{"text":"Видео, для которого нужно получить идентификатор.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1videoSessionIdentifier(for:)\/title","op":"replace","value":"videoSessionIdentifierFor:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1videoSessionIdentifier(for:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoSessionIdentifierFor:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}