{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/duration"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/duration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/duration","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"duration","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"duration","required":true,"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner(py)duration"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/duration":{"abstract":[],"title":"duration","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"duration","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/duration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/duration"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"abstract":[],"title":"MyTargetInstreamAdVideoMotionBanner","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"duration"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"duration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1duration\/title","value":"duration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"duration"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1duration\/fragments"},{"op":"replace","value":"MyTargetInstreamAdVideoMotionBanner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}