{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/ovkit_videoMotionData"},"metadata":{"required":true,"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_videoMotionData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionData","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"ovkit_videoMotionData","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionBanner(py)ovkit_videoMotionData","roleHeading":"Instance Property","title":"ovkit_videoMotionData","symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_videoMotionData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData","text":"MyTargetInstreamAdVideoMotionData"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/ovkit_videomotiondata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/ovkit_videomotiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner/ovkit_videoMotionData":{"kind":"symbol","navigatorTitle":[{"text":"ovkit_videoMotionData","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner\/ovkit_videoMotionData","title":"ovkit_videoMotionData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_videoMotionData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData","text":"MyTargetInstreamAdVideoMotionData","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner\/ovkit_videomotiondata","required":true,"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionBanner":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionBanner","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionbanner","title":"MyTargetInstreamAdVideoMotionBanner","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionData":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"title":"MyTargetInstreamAdVideoMotionData","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotiondata","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionData"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ovkit_videoMotionData","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ovkit_videoMotionData","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionData","text":"id<MyTargetInstreamAdVideoMotionData>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_videoMotionData"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1ovkit_videoMotionData\/title","value":"ovkit_videoMotionData","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner~1ovkit_videoMotionData\/fragments","value":[{"text":"ovkit_videoMotionData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/title","value":"MyTargetInstreamAdVideoMotionBanner","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionBanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionBanner\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionBanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/title","value":"MyTargetInstreamAdVideoMotionData","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionData\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}