{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/Equatable-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/!=(_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/!=(_:_:)"},"metadata":{"symbolKind":"op","extendedModule":"Swift","role":"symbol","roleHeading":"Operator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"!=(_:_:)","modules":[{"relatedModules":["Swift"],"name":"OVKit"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/!=(_:_:)":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/!=(_:_:)","title":"!=(_:_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/Equatable-Implementations","type":"topic","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/equatable-implementations","role":"collectionGroup","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSwipeGestureBehavior"}],"type":"topic","title":"FullscreenSwipeGestureBehavior","abstract":[{"type":"text","text":"Поведение при свайпе в полноэкранном режиме."}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","value":"OVKFullscreenSwipeGestureBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}]},{"value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}