{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior@OVKFullscreenSwipeGestureBehaviorDismissFullscreen","symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Case","title":"FullscreenSwipeGestureBehavior.dismissFullscreen","navigatorTitle":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissFullscreen","kind":"identifier"}]},"abstract":[{"type":"text","text":"Закрытие полноэкранного режима."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/dismissFullscreen","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissFullscreen"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/dismissfullscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/dismissfullscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","abstract":[{"text":"Поведение при свайпе в полноэкранном режиме.","type":"text"}],"title":"FullscreenSwipeGestureBehavior","navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/dismissFullscreen":{"type":"topic","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/dismissfullscreen","kind":"symbol","abstract":[{"text":"Закрытие полноэкранного режима.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissFullscreen"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/dismissFullscreen","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen"}],"title":"FullscreenSwipeGestureBehavior.dismissFullscreen"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","value":"OVKFullscreenSwipeGestureBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1dismissFullscreen\/title","value":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1dismissFullscreen\/fragments","value":[{"text":"OVKFullscreenSwipeGestureBehaviorDismissFullscreen","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}