{"metadata":{"title":"Equatable Implementations","modules":[{"name":"OVKit"}],"role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/equatable-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"abstract":[{"type":"text","text":"Поведение при свайпе в полноэкранном режиме."}],"type":"topic","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","title":"FullscreenSwipeGestureBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/!=(_:_:)":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/!=(_:_:)","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKFullscreenSwipeGestureBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title"},{"value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments"},{"value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle"}]}]}