{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"symbolKind":"init","role":"symbol","title":"init(rawValue:)","externalID":"s:5OVKit30FullscreenSwipeGestureBehaviorO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/init(rawValue:)","type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/init(rawvalue:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Поведение при свайпе в полноэкранном режиме."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","kind":"symbol","title":"FullscreenSwipeGestureBehavior"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKFullscreenSwipeGestureBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehavior"}],"op":"replace"},{"value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle","op":"replace"}]}]}