{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior"]]},"abstract":[{"type":"text","text":"Переход сразу в режим Picture In Picture."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/minimizeToPictureInPicture","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPictureInPicture"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/minimizetopictureinpicture"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenswipegesturebehavior\/minimizetopictureinpicture"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture"}],"title":"FullscreenSwipeGestureBehavior.minimizeToPictureInPicture","role":"symbol","externalID":"c:@M@OVKit@E@OVKFullscreenSwipeGestureBehavior@OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPictureInPicture"}],"modules":[{"name":"OVKit"}],"symbolKind":"case"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior/minimizeToPictureInPicture":{"navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture"}],"title":"FullscreenSwipeGestureBehavior.minimizeToPictureInPicture","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Переход сразу в режим Picture In Picture."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior\/minimizeToPictureInPicture","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPictureInPicture","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior\/minimizetopictureinpicture"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSwipeGestureBehavior":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenSwipeGestureBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSwipeGestureBehavior","url":"\/documentation\/ovkit\/fullscreenswipegesturebehavior","type":"topic","kind":"symbol","abstract":[{"text":"Поведение при свайпе в полноэкранном режиме.","type":"text"}],"role":"symbol","title":"FullscreenSwipeGestureBehavior"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1minimizeToPictureInPicture\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior~1minimizeToPictureInPicture\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehaviorMinimizeToPictureInPicture","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/title","op":"replace","value":"OVKFullscreenSwipeGestureBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/fragments","op":"replace","value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}]},{"value":[{"text":"OVKFullscreenSwipeGestureBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSwipeGestureBehavior\/navigatorTitle","op":"replace"}]}]}