{"abstract":[{"text":"Набор действий (пунктов меню) включая действие отмены.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKMenuContents(py)actions","modules":[{"name":"OVKit"}],"title":"actions","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"actions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction","text":"MenuAction"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"actions","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction","kind":"typeIdentifier","text":"MenuAction"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkmenucontents\/actions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmenucontents\/actions"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuContents\/actions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKMenuContents/actions":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMenuAction","text":"MenuAction","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"actions","navigatorTitle":[{"kind":"identifier","text":"actions"}],"abstract":[{"text":"Набор действий (пунктов меню) включая действие отмены.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuContents\/actions","url":"\/documentation\/ovkit\/ovkmenucontents\/actions"},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"abstract":[{"text":"Абстрактная модель пункта меню, содержащая данные для его показа. По смыслу соответствует ","type":"text"},{"code":"UIAlertAction","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MenuAction","kind":"identifier"}],"title":"MenuAction","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MenuAction"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","role":"symbol","url":"\/documentation\/ovkit\/menuaction"},"doc://onevideo.OVKit/documentation/OVKit/MenuContents":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","url":"\/documentation\/ovkit\/menucontents","abstract":[{"text":"Модель содержимого меню","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MenuContents","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuContents","kind":"identifier"}],"type":"topic","title":"MenuContents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"actions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"actions"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<OVKMenuAction *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"actions"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"actions","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuContents~1actions\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuContents~1actions\/fragments","op":"replace","value":[{"kind":"identifier","text":"actions"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","value":"OVKMenuAction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","value":[{"kind":"identifier","text":"OVKMenuAction"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/title","value":"OVKMenuContents","op":"replace"},{"value":[{"text":"OVKMenuContents","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}