{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuContents\/title","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Заголовок меню","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkmenucontents\/title"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkmenucontents\/title"]}],"metadata":{"title":"title","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKMenuContents(py)title","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"role":"symbol"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKMenuContents/title":{"kind":"symbol","abstract":[{"text":"Заголовок меню","type":"text"}],"url":"\/documentation\/ovkit\/ovkmenucontents\/title","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMenuContents\/title","navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuContents":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuContents","url":"\/documentation\/ovkit\/menucontents","abstract":[{"text":"Модель содержимого меню","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MenuContents","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuContents","kind":"identifier"}],"type":"topic","title":"MenuContents"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"title"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"title","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuContents~1title\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMenuContents~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/title","value":"OVKMenuContents"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMenuContents"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuContents\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}