{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restricted"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"VideoRestrictionType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType"},{"kind":"text","text":")"}],"symbolKind":"case","role":"symbol","externalID":"s:5OVKit16ControlCoverTypeO10restrictedyAcA016VideoRestrictionD0_pcACmF","title":"ControlCoverType.restricted(_:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCoverType"]]},"abstract":[{"type":"text","text":"В видео стоит запрет на воспроизведение ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction"},{"type":"text","text":")"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlcovertype\/restricted(_:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCoverType\/restricted(_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restricted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/videoRestriction":{"title":"videoRestriction","url":"\/documentation\/ovkit\/videotype\/videorestriction","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoRestriction","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoRestriction"}],"kind":"symbol","abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/ControlCoverType/restricted(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restricted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType","text":"VideoRestrictionType"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"ControlCoverType.restricted(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCoverType\/restricted(_:)","abstract":[{"type":"text","text":"В видео стоит запрет на воспроизведение ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/videoRestriction"},{"type":"text","text":")"}],"url":"\/documentation\/ovkit\/controlcovertype\/restricted(_:)"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"title":"VideoRestrictionType","navigatorTitle":[{"text":"VideoRestrictionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}],"url":"\/documentation\/ovkit\/videorestrictiontype","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ControlCoverType":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ControlCoverType","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ControlCoverType","kind":"identifier"}],"title":"ControlCoverType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlCoverType","url":"\/documentation\/ovkit\/controlcovertype","abstract":[{"type":"text","text":"Тип баннера, который может показываться в плеере поверх воспроизведения."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/title","value":"videoRestriction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1videoRestriction\/fragments","value":[{"kind":"identifier","text":"videoRestriction"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}