{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/configureWithCompletion(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Метод вызывает ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","type":"reference"},{"text":" перед началом проигрывания или перед включением звука.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureWithCompletion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Необходимо вызвать после успешной настройки "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"В нем необходимо сконфигурировать и активировать ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"text":" с параметрами из ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"},{"text":":","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredCategory","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionRouteSharingPolicy"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызов метода может производиться часто с одними и теми же параметрами, поэтому стоит избегать лишнего конфигурирования "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/audiomanager\/configurewithcompletion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiomanager\/configurewithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureWithCompletion","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"configureWithCompletion:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKAudioManager(im)configureWithCompletion:","title":"configureWithCompletion(_:)","symbolKind":"method","required":true,"role":"symbol"},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"role":"symbol","url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","kind":"symbol","title":"PlayerManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredOptions":{"url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredoptions","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","title":"audioSessionPreferredOptions","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"CategoryOptions","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"audioSessionPreferredOptions","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","abstract":[{"type":"text","text":"Протокол, позволяющий настраивать поведение "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":" при работе плееров."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"url":"\/documentation\/ovkit\/audiomanager","title":"AudioManager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioManager"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionRouteSharingPolicy":{"navigatorTitle":[{"text":"audioSessionRouteSharingPolicy","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionRouteSharingPolicy","url":"\/documentation\/ovkit\/playermanager\/audiosessionroutesharingpolicy","role":"symbol","title":"audioSessionRouteSharingPolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionRouteSharingPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"RouteSharingPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioManager/configureWithCompletion(_:)":{"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/configureWithCompletion(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureWithCompletion"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configureWithCompletion:"}],"title":"configureWithCompletion(_:)","url":"\/documentation\/ovkit\/audiomanager\/configurewithcompletion(_:)","type":"topic","abstract":[{"text":"Метод вызывает ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","isActive":true},{"text":" перед началом проигрывания или перед включением звука.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredCategory":{"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredcategory","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredCategory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"Category","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory"}],"kind":"symbol","navigatorTitle":[{"text":"audioSessionPreferredCategory","kind":"identifier"}],"title":"audioSessionPreferredCategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredCategory"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredMode":{"url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredmode","navigatorTitle":[{"text":"audioSessionPreferredMode","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","title":"audioSessionPreferredMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configureWithCompletion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"configureWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)()) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Необходимо вызвать после успешной настройки "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":"."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/title","value":"audioSessionPreferredOptions"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/fragments","value":[{"text":"audioSessionPreferredOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","value":"OVKAudioManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","value":[{"text":"OVKAudioManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAudioManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionRouteSharingPolicy\/title","value":"audioSessionRouteSharingPolicy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionRouteSharingPolicy\/fragments","value":[{"kind":"identifier","text":"audioSessionRouteSharingPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1configureWithCompletion(_:)\/title","value":"configureWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1configureWithCompletion(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"configureWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredCategory\/title","value":"audioSessionPreferredCategory"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredCategory\/fragments","value":[{"text":"audioSessionPreferredCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/title","value":"audioSessionPreferredMode"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/fragments","value":[{"text":"audioSessionPreferredMode","kind":"identifier"}]}]}]}