{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willActivateCommandCenter","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Для принудительного снятия обработчиков можно использовать ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/deactivateCommandCenter()","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager"]]},"kind":"symbol","sections":[],"metadata":{"required":true,"roleHeading":"Instance Method","symbolKind":"method","title":"willActivateCommandCenter()","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willActivateCommandCenter"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"willActivateCommandCenter"}],"externalID":"c:@M@OVKit@objc(pl)OVKAudioManager(im)willActivateCommandCenter"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiomanager\/willactivatecommandcenter()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiomanager\/willactivatecommandcenter()"]}],"abstract":[{"text":"Метод вызывается сразу перед тем, как видеоплеер установит обработчики действий на ","type":"text"},{"type":"codeVoice","code":"MPRemoteCommandCenter"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/willActivateCommandCenter()","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioManager/willActivateCommandCenter()":{"required":true,"url":"\/documentation\/ovkit\/audiomanager\/willactivatecommandcenter()","title":"willActivateCommandCenter()","type":"topic","role":"symbol","abstract":[{"text":"Метод вызывается сразу перед тем, как видеоплеер установит обработчики действий на ","type":"text"},{"type":"codeVoice","code":"MPRemoteCommandCenter"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willActivateCommandCenter"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"willActivateCommandCenter"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager\/willActivateCommandCenter()"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AudioManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Протокол, позволяющий настраивать поведение "},{"type":"codeVoice","code":"AVAudioSession"},{"text":" при работе плееров.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/audiomanager","navigatorTitle":[{"text":"AudioManager","kind":"identifier"}],"type":"topic","title":"AudioManager","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/deactivateCommandCenter()":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/deactivateCommandCenter()","title":"deactivateCommandCenter()","navigatorTitle":[{"kind":"identifier","text":"deactivateCommandCenter"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deactivateCommandCenter"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/playermanager\/deactivatecommandcenter()","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"willActivateCommandCenter","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"willActivateCommandCenter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"willActivateCommandCenter","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"willActivateCommandCenter","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1willActivateCommandCenter()\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager~1willActivateCommandCenter()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willActivateCommandCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","value":"OVKAudioManager"},{"value":[{"kind":"identifier","text":"OVKAudioManager"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","value":[{"text":"OVKAudioManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1deactivateCommandCenter()\/title","op":"replace","value":"deactivateCommandCenter"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1deactivateCommandCenter()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deactivateCommandCenter","kind":"identifier"}]}]}]}