{"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(cm)created","title":"created()","navigatorTitle":[{"kind":"identifier","text":"created"}],"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/persistentitemstate\/created()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistentitemstate\/created()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/created()","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/created()":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/created()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/persistentitemstate\/created()","abstract":[],"title":"created()","navigatorTitle":[{"text":"created","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItemState","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","url":"\/documentation\/ovkit\/persistentitemstate","abstract":[{"text":"Состояние ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference"},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"title":"PersistentItemState","navigatorTitle":[{"text":"PersistentItemState","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"title":"PersistentItem","navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","url":"\/documentation\/ovkit\/persistentitem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"created","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"created","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"created"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1created()\/title","op":"replace","value":"created"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1created()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"created"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","op":"replace","value":"OVKPersistentItemState"},{"value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistentItemState"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle"},{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"}]}]}