{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DownloadState","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"}]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistentitemstate\/downloadstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentitemstate\/downloadstate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloadState"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(py)downloadState","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":": "},{"text":"DownloadState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"downloadState","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"downloadState"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/downloadState":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState","text":"DownloadState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/downloadState","abstract":[],"title":"downloadState","url":"\/documentation\/ovkit\/persistentitemstate\/downloadstate","navigatorTitle":[{"text":"downloadState","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistentitem","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"title":"PersistentItem","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"role":"symbol","abstract":[{"text":"Состояние ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference","isActive":true},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","url":"\/documentation\/ovkit\/persistentitemstate","kind":"symbol","title":"PersistentItemState"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"url":"\/documentation\/ovkit\/downloadstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DownloadState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","title":"DownloadState","role":"symbol","abstract":[{"type":"text","text":"Состояние скачивания ресурса в оффлайн-хранилище."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"downloadState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"downloadState","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","kind":"typeIdentifier","text":"OVKDownloadState","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadState"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadState"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloadState\/title","value":"downloadState"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1downloadState\/fragments","value":[{"text":"downloadState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","value":[{"text":"OVKDownloadState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","value":[{"text":"OVKDownloadState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}