{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistentitemstate\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentitemstate\/error"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(py)error","navigatorTitle":[{"text":"error","kind":"identifier"}],"roleHeading":"Instance Property","title":"error","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"url":"\/documentation\/ovkit\/persistentitem","role":"symbol","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"kind":"symbol","type":"topic","title":"PersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItemState"}],"role":"symbol","navigatorTitle":[{"text":"PersistentItemState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Состояние "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"type":"text","text":" применительно к оффлайн проигрыванию."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","url":"\/documentation\/ovkit\/persistentitemstate","title":"PersistentItemState"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/error":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"error","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/error","url":"\/documentation\/ovkit\/persistentitemstate\/error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"error"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"error","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"error","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"error","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error\/title","op":"replace","value":"error"},{"op":"replace","value":[{"kind":"identifier","text":"error"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1error\/fragments"}]}]}