{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/isEqual(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/persistentitemstate\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentitemstate\/isequal(_:)"]}],"metadata":{"title":"isEqual(_:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemState(im)isEqual:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/ovkit\/persistentitemstate\/isequal(_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"role":"symbol","url":"\/documentation\/ovkit\/persistentitemstate","type":"topic","title":"PersistentItemState","navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","abstract":[{"type":"text","text":"Состояние "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference","isActive":true},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistentItemState","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"kind":"symbol","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"title":"PersistentItem","navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentItem"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","url":"\/documentation\/ovkit\/persistentitem"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItemState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}