{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastPlayer\/pickedFormat"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pickedFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pickedFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","title":"pickedFormat","externalID":"s:5OVKit15BroadcastPlayerP12pickedFormatAA09VideoFileE0OSgvp","role":"symbol","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastPlayer"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/broadcastplayer\/pickedformat"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat","type":"topic","kind":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","title":"VideoFileFormat"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastPlayer/pickedFormat":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickedFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"text":"?","kind":"text"}],"title":"pickedFormat","url":"\/documentation\/ovkit\/broadcastplayer\/pickedformat","kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastPlayer\/pickedFormat"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastPlayer":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BroadcastPlayer"}],"url":"\/documentation\/ovkit\/broadcastplayer","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastPlayer","title":"BroadcastPlayer","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastPlayer"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}