{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureMidpoints"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forVideoDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/configureMidpoints(forVideoDuration:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/configuremidpoints(forvideoduration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/configuremidpoints(forvideoduration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"configureMidpointsForVideoDuration:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureMidpoints","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forVideoDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(im)configureMidpointsForVideoDuration:","title":"configureMidpoints(forVideoDuration:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"title":"MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/configureMidpoints(forVideoDuration:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/configureMidpoints(forVideoDuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureMidpoints"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forVideoDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"required":true,"title":"configureMidpoints(forVideoDuration:)","url":"\/documentation\/ovkit\/mytargetinstreamad\/configuremidpoints(forvideoduration:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureMidpointsForVideoDuration:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"configureMidpointsForVideoDuration:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureMidpointsForVideoDuration:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"configureMidpointsForVideoDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"forVideoDuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1configureMidpoints(forVideoDuration:)\/title","op":"replace","value":"configureMidpointsForVideoDuration:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureMidpointsForVideoDuration:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1configureMidpoints(forVideoDuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}