{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_postViewPlayer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","kind":"typeIdentifier","text":"MyTargetInstreamAdPostViewPlayer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(py)ovkit_postViewPlayer","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_postViewPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetInstreamAdPostViewPlayer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"ovkit_postViewPlayer"}],"required":true,"role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"ovkit_postViewPlayer"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_postviewplayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_postviewplayer"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_postViewPlayer","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"url":"\/documentation\/ovkit\/mytargetinstreamad","title":"MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_postViewPlayer":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ovkit_postViewPlayer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","kind":"typeIdentifier","text":"MyTargetInstreamAdPostViewPlayer"},{"kind":"text","text":"?"}],"required":true,"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_postViewPlayer","url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_postviewplayer","role":"symbol","title":"ovkit_postViewPlayer","navigatorTitle":[{"kind":"identifier","text":"ovkit_postViewPlayer"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer","role":"symbol","type":"topic","title":"MyTargetInstreamAdPostViewPlayer","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","abstract":[],"navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"ovkit_postViewPlayer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ovkit_postViewPlayer"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<MyTargetInstreamAdPostViewPlayer>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer"},{"text":" ","kind":"text"},{"text":"ovkit_postViewPlayer","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MyTargetInstreamAd","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments"},{"op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_postViewPlayer\/title","value":"ovkit_postViewPlayer"},{"op":"replace","value":[{"text":"ovkit_postViewPlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_postViewPlayer\/fragments"},{"op":"replace","value":"MyTargetInstreamAdPostViewPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}