{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_videoMotionPlayer","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"title":"ovkit_videoMotionPlayer","navigatorTitle":[{"text":"ovkit_videoMotionPlayer","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(py)ovkit_videoMotionPlayer","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ovkit_videoMotionPlayer","kind":"identifier"},{"kind":"text","text":": "},{"text":"MyTargetInstreamAdVideoMotionPlayer","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ovkit_videoMotionPlayer","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer","text":"MyTargetInstreamAdVideoMotionPlayer"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_videomotionplayer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_videomotionplayer"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"kind":"symbol","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_videoMotionPlayer":{"kind":"symbol","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"ovkit_videoMotionPlayer","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_videoMotionPlayer","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer","text":"MyTargetInstreamAdVideoMotionPlayer","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_videomotionplayer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_videoMotionPlayer","title":"ovkit_videoMotionPlayer"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayer","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayer","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayer","title":"MyTargetInstreamAdVideoMotionPlayer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ovkit_videoMotionPlayer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ovkit_videoMotionPlayer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<MyTargetInstreamAdVideoMotionPlayer>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayer"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_videoMotionPlayer"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MyTargetInstreamAd","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"op":"replace"},{"value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_videoMotionPlayer\/title","value":"ovkit_videoMotionPlayer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_videoMotionPlayer\/fragments","value":[{"text":"ovkit_videoMotionPlayer","kind":"identifier"}]},{"op":"replace","value":"MyTargetInstreamAdVideoMotionPlayer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}]},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}