{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_customparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/ovkit_customparams"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_customParams"},"metadata":{"title":"ovkit_customParams","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"ovkit_customParams"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_customParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetCustomParams","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCustomParams"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(py)ovkit_customParams"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovkit_customParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MyTargetCustomParams","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCustomParams"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"type":"topic","kind":"symbol","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAd"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetCustomParams":{"title":"MyTargetCustomParams","navigatorTitle":[{"text":"MyTargetCustomParams","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetCustomParams","abstract":[],"url":"\/documentation\/ovkit\/mytargetcustomparams","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetCustomParams","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/ovkit_customParams":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_customParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyTargetCustomParams","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetCustomParams"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/ovkit_customParams","title":"ovkit_customParams","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad\/ovkit_customparams","navigatorTitle":[{"kind":"identifier","text":"ovkit_customParams"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ovkit_customParams","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ovkit_customParams","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetCustomParams","kind":"typeIdentifier","text":"id<MyTargetCustomParams>"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovkit_customParams"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MyTargetInstreamAd","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle"},{"op":"replace","value":"MyTargetCustomParams","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/title"},{"op":"replace","value":[{"text":"MyTargetCustomParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/fragments"},{"op":"replace","value":[{"text":"MyTargetCustomParams","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetCustomParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_customParams\/title","value":"ovkit_customParams"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1ovkit_customParams\/fragments","value":[{"text":"ovkit_customParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}