{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resume"},{"text":"()","kind":"text"}],"role":"symbol","required":true,"title":"resume()","symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(im)resume","roleHeading":"Instance Method","navigatorTitle":[{"text":"resume","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/resume()"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/resume()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/resume()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","title":"MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/resume()":{"type":"topic","role":"symbol","required":true,"url":"\/documentation\/ovkit\/mytargetinstreamad\/resume()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/resume()","title":"resume()","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"resume","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"resume","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"resume","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"resume","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resume"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MyTargetInstreamAd","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1resume()\/title","value":"resume","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resume","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1resume()\/fragments"}]}]}