{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","required":true,"modules":[{"name":"OVKit"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shoppableAdsItemClickForIdentifier:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shoppableAdsItemClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(im)shoppableAdsItemClickForIdentifier:","title":"shoppableAdsItemClick(forIdentifier:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemClick(forIdentifier:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shoppableAdsItemClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/shoppableadsitemclick(foridentifier:)"]},{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/shoppableadsitemclick(foridentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/shoppableAdsItemClick(forIdentifier:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/shoppableAdsItemClick(forIdentifier:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shoppableAdsItemClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamad\/shoppableadsitemclick(foridentifier:)","title":"shoppableAdsItemClick(forIdentifier:)","navigatorTitle":[{"text":"shoppableAdsItemClickForIdentifier:","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"title":"MyTargetInstreamAd","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamad","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"shoppableAdsItemClickForIdentifier:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shoppableAdsItemClickForIdentifier:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"shoppableAdsItemClickForIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"shoppableAdsItemClickForIdentifier:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemClick(forIdentifier:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1shoppableAdsItemClick(forIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"shoppableAdsItemClickForIdentifier:","kind":"identifier"}]},{"value":"MyTargetInstreamAd","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}