{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skipBanner()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"skipBanner","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/skipbanner()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/skipbanner()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"skipBanner","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","required":true,"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(im)skipBanner","modules":[{"name":"OVKit"}],"title":"skipBanner()","navigatorTitle":[{"kind":"identifier","text":"skipBanner"}],"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/skipBanner()":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipBanner"},{"text":"()","kind":"text"}],"required":true,"url":"\/documentation\/ovkit\/mytargetinstreamad\/skipbanner()","kind":"symbol","title":"skipBanner()","navigatorTitle":[{"text":"skipBanner","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/skipBanner()"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","type":"topic","title":"MyTargetInstreamAd","url":"\/documentation\/ovkit\/mytargetinstreamad","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"skipBanner"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"skipBanner","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"skipBanner","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"skipBanner","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skipBanner()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"skipBanner"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1skipBanner()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"}]}]}