{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/useDefaultPlayer()","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(im)useDefaultPlayer","title":"useDefaultPlayer()","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"useDefaultPlayer"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useDefaultPlayer"},{"text":"()","kind":"text"}],"required":true,"roleHeading":"Instance Method","modules":[{"name":"OVKit"}]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/usedefaultplayer()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamad\/usedefaultplayer()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDefaultPlayer"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/mytargetinstreamad","kind":"symbol","title":"MyTargetInstreamAd","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MyTargetInstreamAd","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/useDefaultPlayer()":{"title":"useDefaultPlayer()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useDefaultPlayer"}],"abstract":[],"kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"useDefaultPlayer","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/useDefaultPlayer()","url":"\/documentation\/ovkit\/mytargetinstreamad\/usedefaultplayer()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"useDefaultPlayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"useDefaultPlayer","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"useDefaultPlayer","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"op":"replace"},{"value":"useDefaultPlayer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1useDefaultPlayer()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"useDefaultPlayer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1useDefaultPlayer()\/fragments"}]}]}