{"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/videoquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamad\/videoquality"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAd(py)videoQuality","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoQuality"}],"title":"videoQuality"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoQuality"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd/videoQuality":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad\/videoquality","kind":"symbol","title":"videoQuality","type":"topic","role":"symbol","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd\/videoQuality","navigatorTitle":[{"text":"videoQuality","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","abstract":[],"title":"MyTargetInstreamAd"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"videoQuality","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"videoQuality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"videoQuality","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoQuality\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd~1videoQuality\/fragments","op":"replace","value":[{"text":"videoQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","op":"replace","value":"MyTargetInstreamAd"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]}]}]}