{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKNetworkConnection","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","text":"NetworkConnection"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/contains(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnectionmask\/contains(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnectionmask\/contains(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NetworkConnection","preciseIdentifier":"c:@M@OVKit@E@OVKNetworkConnection"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"contains(_:)","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask(im)contains:","symbolKind":"method","navigatorTitle":[{"text":"contains:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/contains(_:)":{"url":"\/documentation\/ovkit\/networkconnectionmask\/contains(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"kind":"text","text":"("},{"text":"NetworkConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKNetworkConnection"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"contains:"}],"title":"contains(_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/contains(_:)","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"title":"NetworkConnection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NetworkConnection"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnection"}],"url":"\/documentation\/ovkit\/networkconnection","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","title":"NetworkConnectionMask","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"NetworkConnectionMask","kind":"identifier"}],"url":"\/documentation\/ovkit\/networkconnectionmask"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"contains:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"contains:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"contains:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@OVKNetworkConnection","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","text":"OVKNetworkConnection"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1contains(_:)\/title","value":"contains:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1contains(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contains:"}]},{"op":"replace","value":"OVKNetworkConnection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle","value":[{"text":"OVKNetworkConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}