{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiAndCellular()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","title":"wifiAndCellular()","navigatorTitle":[{"text":"wifiAndCellular","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask(cm)wifiAndCellular","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifiAndCellular","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/networkconnectionmask\/wifiandcellular()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/networkconnectionmask\/wifiandcellular()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifiAndCellular","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/networkconnectionmask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","role":"symbol","title":"NetworkConnectionMask","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionMask"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/wifiAndCellular()":{"url":"\/documentation\/ovkit\/networkconnectionmask\/wifiandcellular()","title":"wifiAndCellular()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiAndCellular()","kind":"symbol","navigatorTitle":[{"text":"wifiAndCellular","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifiAndCellular","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"wifiAndCellular","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"wifiAndCellular","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"wifiAndCellular","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"text":"OVKNetworkConnectionMask","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle"},{"value":"wifiAndCellular","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiAndCellular()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiAndCellular()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"wifiAndCellular","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}