{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnectionmask\/wifionly()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnectionmask\/wifionly()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiOnly"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiOnly"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"wifiOnly"}],"title":"wifiOnly()","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask(cm)wifiOnly","symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiOnly()"},"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask/wifiOnly()":{"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/networkconnectionmask\/wifionly()","navigatorTitle":[{"kind":"identifier","text":"wifiOnly"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask\/wifiOnly()","title":"wifiOnly()","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiOnly"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"title":"NetworkConnectionMask","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionMask"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/networkconnectionmask"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"wifiOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"wifiOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"wifiOnly"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiOnly()\/title","value":"wifiOnly"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask~1wifiOnly()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"wifiOnly","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnectionMask"}]}]}]}