{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)audioSessionPreferredMode","title":"audioSessionPreferredMode","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode"}],"navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredMode"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Режим "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":", который в данный момент требуется менеджеру."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Если используется собственная реализация ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","isActive":true,"type":"reference"},{"text":", он обязан учитывать это свойство.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/playermanager\/audiosessionpreferredmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermanager\/audiosessionpreferredmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PlayerManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","url":"\/documentation\/ovkit\/playermanager","kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"navigatorTitle":[{"text":"AudioManager","kind":"identifier"}],"title":"AudioManager","role":"symbol","abstract":[{"type":"text","text":"Протокол, позволяющий настраивать поведение "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" при работе плееров."}],"url":"\/documentation\/ovkit\/audiomanager","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredMode":{"kind":"symbol","type":"topic","abstract":[{"text":"Режим ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":", который в данный момент требуется менеджеру.","type":"text"}],"title":"audioSessionPreferredMode","url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredmode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredMode","navigatorTitle":[{"text":"audioSessionPreferredMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"audioSessionPreferredMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"audioSessionPreferredMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@AVAudioSessionMode","text":"AVAudioSessionMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","op":"replace","value":"OVKAudioManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","op":"replace","value":[{"text":"OVKAudioManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAudioManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/title","op":"replace","value":"audioSessionPreferredMode"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredMode\/fragments","op":"replace","value":[{"text":"audioSessionPreferredMode","kind":"identifier"}]}]}]}