{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredOptions"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/audiosessionpreferredoptions"]},{"paths":["\/documentation\/ovkit\/playermanager\/audiosessionpreferredoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSessionPreferredOptions"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)audioSessionPreferredOptions","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredOptions"}],"title":"audioSessionPreferredOptions"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/audioSessionPreferredOptions":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/audioSessionPreferredOptions","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audioSessionPreferredOptions","kind":"identifier"},{"kind":"text","text":": "},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions"}],"title":"audioSessionPreferredOptions","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/playermanager\/audiosessionpreferredoptions","navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredOptions"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"url":"\/documentation\/ovkit\/playermanager","title":"PlayerManager","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"audioSessionPreferredOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioSessionPreferredOptions"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"AVAudioSessionCategoryOptions","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredOptions"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"audioSessionPreferredOptions","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/title","op":"replace"},{"op":"replace","value":[{"text":"audioSessionPreferredOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1audioSessionPreferredOptions\/fragments"},{"value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}