{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanupAllPlayers","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Останавливает и очищает все плееры, а также закрывает PiP.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/cleanupAllPlayers()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playermanager\/cleanupallplayers()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanager\/cleanupallplayers()"]}],"metadata":{"navigatorTitle":[{"text":"cleanupAllPlayers","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"cleanupAllPlayers()","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(im)cleanupAllPlayers","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanupAllPlayers"},{"kind":"text","text":"()"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/cleanupAllPlayers()":{"navigatorTitle":[{"text":"cleanupAllPlayers","kind":"identifier"}],"abstract":[{"text":"Останавливает и очищает все плееры, а также закрывает PiP.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/cleanupAllPlayers()","title":"cleanupAllPlayers()","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playermanager\/cleanupallplayers()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanupAllPlayers"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"kind":"symbol","title":"PlayerManager","navigatorTitle":[{"text":"PlayerManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerManager"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cleanupAllPlayers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cleanupAllPlayers"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"cleanupAllPlayers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"cleanupAllPlayers","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1cleanupAllPlayers()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cleanupAllPlayers"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1cleanupAllPlayers()\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"}]}]}