{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"closePiP"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По возможности плеер из PiP возвращается на оригинальное место. Уведомляет "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","isActive":true},{"type":"text","text":" о закрытии."}]}]}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","title":"closePiP()","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(im)closePiP","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"closePiP","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"closePiP"}],"platforms":[]},"abstract":[{"type":"text","text":"Закрывает окно Picture in Picture."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/closePiP()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/closepip()"]},{"paths":["\/documentation\/ovkit\/playermanager\/closepip()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"url":"\/documentation\/ovkit\/playermanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","kind":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/ovkit\/playermanager\/delegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","type":"topic","abstract":[{"type":"text","text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением."}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/closePiP()":{"title":"closePiP()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/closePiP()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"closePiP"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closePiP"},{"kind":"text","text":"()"}],"url":"\/documentation\/ovkit\/playermanager\/closepip()","abstract":[{"type":"text","text":"Закрывает окно Picture in Picture."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"closePiP","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"closePiP"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"closePiP","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/fragments"},{"value":"closePiP","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1closePiP()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closePiP"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1closePiP()\/fragments","op":"replace"}]}]}