{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate","text":"PlayerManagerDelegate"},{"kind":"text","text":"?"}],"title":"delegate","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)delegate","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"abstract":[{"type":"text","text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"PlayerManagerDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"aside","name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"Необходимо установить как можно раньше.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"variants":[{"paths":["\/documentation\/ovkit\/playermanager\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermanager\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate":{"role":"symbol","title":"PlayerManagerDelegate","url":"\/documentation\/ovkit\/playermanagerdelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PlayerManagerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerManagerDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"url":"\/documentation\/ovkit\/playermanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","kind":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerManagerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerManagerDelegate"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/ovkit\/playermanager\/delegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/delegate","type":"topic","abstract":[{"type":"text","text":"Делегат, который обеспечивает взаимодействие плееров с клиентским приложением."}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerManagerDelegate","text":"id<OVKPlayerManagerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/title","value":"OVKPlayerManagerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManagerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate\/navigatorTitle","value":[{"text":"OVKPlayerManagerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]}]}]}