{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/masterVolume"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:5OVKit7ClampedV","text":"Clamped","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Clamped"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"masterVolume","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/mastervolume"]},{"paths":["\/documentation\/ovkit\/playermanager\/mastervolume"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"masterVolume"}],"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)masterVolume","title":"masterVolume","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"masterVolume","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Общая громкость (всех плееров). Значения от 0 до 1. По умолчанию 1.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/Clamped":{"url":"\/documentation\/ovkit\/clamped","navigatorTitle":[{"text":"Clamped","kind":"identifier"}],"title":"Clamped","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Clamped"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Clamped","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/masterVolume":{"kind":"symbol","title":"masterVolume","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/masterVolume","navigatorTitle":[{"kind":"identifier","text":"masterVolume"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"masterVolume"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/ovkit\/playermanager\/mastervolume","abstract":[{"type":"text","text":"Общая громкость (всех плееров). Значения от 0 до 1. По умолчанию 1."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"url":"\/documentation\/ovkit\/playermanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerManager","kind":"identifier"}],"title":"PlayerManager","kind":"symbol","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"masterVolume"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"masterVolume","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterVolume"},{"text":";","kind":"text"}]}]}},{"value":"masterVolume","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1masterVolume\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1masterVolume\/fragments","op":"replace","value":[{"kind":"identifier","text":"masterVolume"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"text":"OVKPlayerManager","kind":"identifier"}],"op":"replace"}]}]}