{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"pipWindow","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)pipWindow","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pipWindow"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PiPWindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/playermanager\/pipwindow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermanager\/pipwindow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Окно внутреннего Picture in Picture."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"url":"\/documentation\/ovkit\/playermanager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"type":"topic","title":"PlayerManager","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/pipWindow":{"navigatorTitle":[{"text":"pipWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermanager\/pipwindow","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/pipWindow","title":"pipWindow","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PiPWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow"},{"text":"?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PiPWindow","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","title":"PiPWindow","type":"topic","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"url":"\/documentation\/ovkit\/pipwindow","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"pipWindow","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"pipWindow","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPiPWindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","text":"OVKPiPWindow","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"pipWindow","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPlayerManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace"},{"value":[{"text":"OVKPlayerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","op":"replace"},{"value":"pipWindow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/title","op":"replace"},{"value":[{"text":"pipWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1pipWindow\/fragments","op":"replace"},{"value":"OVKPiPWindow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","op":"replace"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","op":"replace"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}