{"kind":"symbol","abstract":[{"type":"text","text":"Показать меню выбора устройства для стриминга."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/presentbroadcastmenu(for:onshowroutepicker:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentBroadcastMenu"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":"?, ","kind":"text"},{"text":"onShowRoutePicker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"video","content":[{"inlineContent":[{"text":"Видео, для которого нужно показать меню. Параметр является необязательным.","type":"text"}],"type":"paragraph"}]},{"name":"onShowRoutePicker","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который при вызове обязан показать системное меню выбора устройств AirPlay для трансляции."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Данный метод можно вызывать, только если точка входа в меню не находится на плеере. Иначе необходимо использовать "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentScreencastMenu(onShowRoutePicker:)","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/presentBroadcastMenu(for:onShowRoutePicker:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentBroadcastMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onShowRoutePicker","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"presentBroadcastMenu(for:onShowRoutePicker:)","platforms":[],"externalID":"s:5OVKit13PlayerManagerC20presentBroadcastMenu3for17onShowRoutePickeryAA9VideoType_pSg_yyctF"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","title":"PlayerManager","type":"topic","url":"\/documentation\/ovkit\/playermanager","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","title":"VideoType","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"url":"\/documentation\/ovkit\/videotype","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/presentScreencastMenu(onShowRoutePicker:)":{"url":"\/documentation\/ovkit\/controlsviewdelegate\/presentscreencastmenu(onshowroutepicker:)","role":"symbol","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentScreencastMenu"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onShowRoutePicker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Показать меню трансляции видео на другие устройства."}],"title":"presentScreencastMenu(onShowRoutePicker:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/presentScreencastMenu(onShowRoutePicker:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/presentBroadcastMenu(for:onShowRoutePicker:)":{"abstract":[{"type":"text","text":"Показать меню выбора устройства для стриминга."}],"kind":"symbol","url":"\/documentation\/ovkit\/playermanager\/presentbroadcastmenu(for:onshowroutepicker:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentBroadcastMenu","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","text":"VideoType"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onShowRoutePicker"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier","text":"VoidBlock"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","title":"presentBroadcastMenu(for:onShowRoutePicker:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/presentBroadcastMenu(for:onShowRoutePicker:)"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoidBlock"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","title":"VoidBlock","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/voidblock","navigatorTitle":[{"kind":"identifier","text":"VoidBlock"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}