{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/routeChangeStrategy","interfaceLanguage":"swift"},"abstract":[{"text":"Служит для определения поведения плеера при смене output route.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/routechangestrategy"]},{"paths":["\/documentation\/ovkit\/playermanager\/routechangestrategy"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routeChangeStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RouteChangeStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@RouteChangeStrategy"}],"title":"routeChangeStrategy","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(py)routeChangeStrategy","navigatorTitle":[{"text":"routeChangeStrategy","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routeChangeStrategy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RouteChangeStrategy","preciseIdentifier":"c:@M@OVKit@E@RouteChangeStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/RouteChangeStrategy":{"url":"\/documentation\/ovkit\/routechangestrategy","navigatorTitle":[{"text":"RouteChangeStrategy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteChangeStrategy"}],"type":"topic","title":"RouteChangeStrategy","abstract":[{"text":"Определяет поведения плеера при смене output route.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"url":"\/documentation\/ovkit\/playermanager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"type":"topic","title":"PlayerManager","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/routeChangeStrategy":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeChangeStrategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@RouteChangeStrategy","text":"RouteChangeStrategy"}],"url":"\/documentation\/ovkit\/playermanager\/routechangestrategy","abstract":[{"type":"text","text":"Служит для определения поведения плеера при смене output route."}],"type":"topic","title":"routeChangeStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/routeChangeStrategy","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"routeChangeStrategy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"routeChangeStrategy","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"routeChangeStrategy","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RouteChangeStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RouteChangeStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@RouteChangeStrategy"},{"text":" ","kind":"text"},{"text":"routeChangeStrategy","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/title","value":"RouteChangeStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/fragments","value":[{"text":"RouteChangeStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RouteChangeStrategy\/navigatorTitle","value":[{"text":"RouteChangeStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","value":"OVKPlayerManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1routeChangeStrategy\/title","value":"routeChangeStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1routeChangeStrategy\/fragments","value":[{"text":"routeChangeStrategy","kind":"identifier"}]}]}]}