{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playermanager\/savedplaytime(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"abstract":[{"type":"text","text":"Сохраненное время воспроизведения для данного видео."}],"metadata":{"roleHeading":"Type Method","modules":[{"name":"OVKit"}],"title":"savedPlayTime(for:)","symbolKind":"method","externalID":"s:5OVKit13PlayerManagerC13savedPlayTime3forSdSgAA9VideoType_p_tFZ","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savedPlayTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/savedPlayTime(for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savedPlayTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Возвращает последнюю известную позицию воспроизведение переданного видеоролика. Локальное сохранение и восстановление последней позиции воспроизведение управляется параметром "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop"},{"type":"text","text":". Кроме того, сама модель видео может содержать время последней позиции воспроизведения "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/viewedDuration"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"codeVoice","code":"nil"},{"text":" означает, что нет данных о последней проигрываемой позиции нет.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","abstract":[{"type":"text","text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PlayerManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"title":"PlayerManager","url":"\/documentation\/ovkit\/playermanager","kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/savedPlayTime(for:)":{"role":"symbol","url":"\/documentation\/ovkit\/playermanager\/savedplaytime(for:)","kind":"symbol","title":"savedPlayTime(for:)","abstract":[{"type":"text","text":"Сохраненное время воспроизведения для данного видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/savedPlayTime(for:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"savedPlayTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","role":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/videotype"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType/viewedDuration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/viewedDuration","role":"symbol","abstract":[{"text":"Момент времени, до которого пользователь досмотрел видео на другом устройстве.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"viewedDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"viewedDuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewedDuration"}],"type":"topic","url":"\/documentation\/ovkit\/videotype\/viewedduration"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/savesPlaybackTimeOnStop":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop","role":"symbol","abstract":[{"type":"text","text":"Сохранять время воспроизведения для видео, на котором было остановлено проигрывание."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savesPlaybackTimeOnStop","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"savesPlaybackTimeOnStop","navigatorTitle":[{"text":"savesPlaybackTimeOnStop","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/savesplaybacktimeonstop"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace","value":"OVKVideoType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1viewedDuration\/title","op":"replace","value":"viewedDuration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1viewedDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"viewedDuration"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/title","op":"replace","value":"savesPlaybackTimeOnStop"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/fragments","op":"replace","value":[{"kind":"identifier","text":"savesPlaybackTimeOnStop"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}