{"sections":[],"abstract":[{"text":"Привязывает контроллер ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" к сервису.","type":"text"}],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioManager","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKAudioManager"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setupWith:","kind":"identifier"}],"role":"symbol","title":"setup(with:)","externalID":"c:@M@OVKit@objc(cs)OVKPlayerManager(cm)setupWith:","roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"audioManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKAudioManager","text":"AudioManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Если не вызвать этот метод, ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","type":"reference"},{"text":" будет использовать реализацию контроллера ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" по умолчанию.","type":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermanager\/setup(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermanager\/setup(with:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AudioManager":{"url":"\/documentation\/ovkit\/audiomanager","navigatorTitle":[{"kind":"identifier","text":"AudioManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioManager","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioManager"}],"type":"topic","title":"AudioManager","abstract":[{"text":"Протокол, позволяющий настраивать поведение ","type":"text"},{"type":"codeVoice","code":"AVAudioSession"},{"text":" при работе плееров.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager/setup(with:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AudioManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKAudioManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager\/setup(with:)","url":"\/documentation\/ovkit\/playermanager\/setup(with:)","type":"topic","abstract":[{"type":"text","text":"Привязывает контроллер "},{"type":"codeVoice","code":"AVAudioSession"},{"type":"text","text":" к сервису."}],"title":"setup(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setupWith:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerManager":{"url":"\/documentation\/ovkit\/playermanager","navigatorTitle":[{"kind":"identifier","text":"PlayerManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManager","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerManager"}],"type":"topic","title":"PlayerManager","abstract":[{"text":"Сервис, отвечающий за управление порядком воспроизведения всех плееров в приложении.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"setupWith:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupWith:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setupWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKAudioManager>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKAudioManager"},{"text":") ","kind":"text"},{"text":"audioManager","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/title","op":"replace","value":"OVKAudioManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/fragments","op":"replace","value":[{"text":"OVKAudioManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioManager\/navigatorTitle","op":"replace","value":[{"text":"OVKAudioManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1setup(with:)\/title","op":"replace","value":"setupWith:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager~1setup(with:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupWith:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/title","op":"replace","value":"OVKPlayerManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/fragments","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManager\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerManager","kind":"identifier"}]}]}]}