{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIViewContentMode","kind":"typeIdentifier","text":"ContentMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/imageview\/contentmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/imageview\/contentmode"]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"contentMode","navigatorTitle":[{"text":"contentMode","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKImageView(py)contentMode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/contentMode"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView","abstract":[{"type":"text","text":"Обертка над "},{"type":"codeVoice","code":"UIImageView"},{"text":", которая умеет анимировать ","type":"text"},{"type":"codeVoice","code":"UIView.ContentMode"},{"type":"text","text":" за счет перемещения "},{"code":"imageView","type":"codeVoice"},{"text":" внутри рамок.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"ImageView","url":"\/documentation\/ovkit\/imageview","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ImageView/contentMode":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/contentMode","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/ovkit\/imageview\/contentmode","type":"topic","title":"contentMode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":".","kind":"text"},{"text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"contentMode","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"contentMode"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode","text":"UIViewContentMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/title","value":"OVKImageView"},{"value":[{"text":"OVKImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/navigatorTitle","value":[{"text":"OVKImageView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1contentMode\/title","op":"replace","value":"contentMode"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1contentMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"contentMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}