{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(frame:image:highlightedImage:)"},"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit9ImageViewC5frame5image011highlightedB0ACSo6CGRectV_So7UIImageCSgAKtcfc","roleHeading":"Initializer","title":"init(frame:image:highlightedImage:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"highlightedImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"text":"highlightedImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/imageview\/init(frame:image:highlightedimage:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ImageView/init(frame:image:highlightedImage:)":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(frame:image:highlightedImage:)","title":"init(frame:image:highlightedImage:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/imageview\/init(frame:image:highlightedimage:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"highlightedImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?)"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ImageView":{"title":"ImageView","abstract":[{"type":"text","text":"Обертка над "},{"code":"UIImageView","type":"codeVoice"},{"type":"text","text":", которая умеет анимировать "},{"type":"codeVoice","code":"UIView.ContentMode"},{"type":"text","text":" за счет перемещения "},{"type":"codeVoice","code":"imageView"},{"text":" внутри рамок.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/imageview","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ImageView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/fragments","value":[{"text":"ImageView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/navigatorTitle","value":[{"kind":"identifier","text":"ImageView"}],"op":"replace"}]}]}