{"metadata":{"roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)ImageView(im)initWithCoder:","title":"init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/imageview\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/imageview\/init(coder:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(coder:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDecoder","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ImageView":{"navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"role":"symbol","title":"ImageView","abstract":[{"type":"text","text":"Обертка над "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":", которая умеет анимировать "},{"type":"codeVoice","code":"UIView.ContentMode"},{"type":"text","text":" за счет перемещения "},{"type":"codeVoice","code":"imageView"},{"type":"text","text":" внутри рамок."}],"kind":"symbol","url":"\/documentation\/ovkit\/imageview","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}]},"doc://onevideo.OVKit/documentation/OVKit/ImageView/init(coder:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"init(coder:)","url":"\/documentation\/ovkit\/imageview\/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageView\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ImageView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/title"},{"op":"replace","value":[{"text":"ImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ImageView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView\/navigatorTitle"},{"op":"replace","value":"initWithCoder:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1init(coder:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageView~1init(coder:)\/fragments"}]}]}