{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","kind":"typeIdentifier","text":"ListPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPrefetchItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalBytesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"listPrefetcher:didPrefetchItem:totalBytesReceived:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ListPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher"},{"text":", ","kind":"text"},{"text":"didPrefetchItem","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":", ","kind":"text"},{"text":"totalBytesReceived","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"role":"symbol","title":"listPrefetcher(_:didPrefetchItem:totalBytesReceived:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate(im)listPrefetcher:didPrefetchItem:totalBytesReceived:","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Сообщает об успешном префетче конкретного "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"reference","isActive":true},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:totalbytesreceived:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:totalbytesreceived:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)":{"abstract":[{"text":"Сообщает об успешном префетче конкретного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"listPrefetcher:didPrefetchItem:totalBytesReceived:","kind":"identifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:totalBytesReceived:)","role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:totalbytesreceived:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier","text":"ListPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPrefetchItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalBytesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"title":"listPrefetcher(_:didPrefetchItem:totalBytesReceived:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"type":"topic","title":"ListPrefetcher","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"title":"PrefetchItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate":{"type":"topic","abstract":[{"text":"Протокол, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","type":"reference","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherDelegate"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"title":"ListPrefetcherDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"listPrefetcher:didPrefetchItem:totalBytesReceived:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"listPrefetcher:didPrefetchItem:totalBytesReceived:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"listPrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","text":"OVKListPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher"},{"text":" *) ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didPrefetchItem:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKPrefetchItem>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":") ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalBytesReceived:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"totalBytesReceived","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"listPrefetcher:didPrefetchItem:totalBytesReceived:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:totalBytesReceived:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:totalBytesReceived:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listPrefetcher:didPrefetchItem:totalBytesReceived:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","value":"OVKPrefetchItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/title","value":"OVKListPrefetcherDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}