{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate"]]},"abstract":[{"type":"text","text":"Сообщает об успешном префетче конкретного "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true,"type":"reference"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"listPrefetcher(_:didPrefetchItem:)","role":"symbol","required":true,"externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate(im)listPrefetcher:didPrefetchItem:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"listPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"text":"ListPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPrefetchItem","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier","text":"PrefetchItem"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"listPrefetcher:didPrefetchItem:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listPrefetcher"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","text":"ListPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPrefetchItem","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"kind":"symbol","deprecated":true,"title":"ListPrefetcher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcher","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate/listPrefetcher(_:didPrefetchItem:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didPrefetchItem:)","title":"listPrefetcher(_:didPrefetchItem:)","type":"topic","abstract":[{"type":"text","text":"Сообщает об успешном префетче конкретного "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"reference","isActive":true},{"type":"text","text":"."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"listPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ListPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didPrefetchItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"listPrefetcher:didPrefetchItem:","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didprefetchitem:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","title":"ListPrefetcherDelegate","kind":"symbol","url":"\/documentation\/ovkit\/listprefetcherdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"navigatorTitle":[{"text":"ListPrefetcherDelegate","kind":"identifier"}],"abstract":[{"text":"Протокол, через который ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","type":"reference"},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"listPrefetcher:didPrefetchItem:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listPrefetcher:didPrefetchItem:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"listPrefetcher:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","text":"OVKListPrefetcher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":" "},{"text":"didPrefetchItem:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"item","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"OVKPrefetchItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","op":"replace","value":"OVKListPrefetcher"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace"},{"op":"replace","value":"listPrefetcher:didPrefetchItem:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didPrefetchItem:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listPrefetcher:didPrefetchItem:","kind":"identifier"}]},{"value":"OVKListPrefetcherDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace"},{"value":[{"text":"OVKListPrefetcherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}