{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","text":"ListPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToPrefetchItem"},{"kind":"text","text":" "},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","text":"ListPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToPrefetchItem","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate(im)listPrefetcher:didFailToPrefetchItem:withError:","title":"listPrefetcher(_:didFailToPrefetchItem:withError:)","navigatorTitle":[{"text":"listPrefetcher:didFailToPrefetchItem:withError:","kind":"identifier"}],"required":true,"role":"symbol","modules":[{"name":"OVKit"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Сообщает об ошибке префетчинга конкретного ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"reference"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didfailtoprefetchitem:witherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didfailtoprefetchitem:witherror:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didFailToPrefetchItem:withError:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate/listPrefetcher(_:didFailToPrefetchItem:withError:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"listPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","text":"ListPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToPrefetchItem","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"listPrefetcher:didFailToPrefetchItem:withError:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate\/listPrefetcher(_:didFailToPrefetchItem:withError:)","abstract":[{"text":"Сообщает об ошибке префетчинга конкретного ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","isActive":true},{"text":".","type":"text"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdelegate\/listprefetcher(_:didfailtoprefetchitem:witherror:)","kind":"symbol","title":"listPrefetcher(_:didFailToPrefetchItem:withError:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","title":"PrefetchItem"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate":{"abstract":[{"text":"Протокол, через который ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","isActive":true,"type":"reference"},{"text":" сообщает о наступлении событий в ходе своей работы.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdelegate","title":"ListPrefetcherDelegate","kind":"symbol","navigatorTitle":[{"text":"ListPrefetcherDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"url":"\/documentation\/ovkit\/listprefetcher","role":"symbol","type":"topic","title":"ListPrefetcher","kind":"symbol","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"listPrefetcher:didFailToPrefetchItem:withError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listPrefetcher:didFailToPrefetchItem:withError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"listPrefetcher:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcher","text":"OVKListPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToPrefetchItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didFailToPrefetchItem:withError:)\/title","op":"replace","value":"listPrefetcher:didFailToPrefetchItem:withError:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate~1listPrefetcher(_:didFailToPrefetchItem:withError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPrefetcher:didFailToPrefetchItem:withError:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace","value":"OVKPrefetchItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"op":"replace"},{"value":"OVKListPrefetcherDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKListPrefetcherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/navigatorTitle"},{"value":"OVKListPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}