{"metadata":{"required":true,"navigatorTitle":[{"text":"onBannerShow","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerShow","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onBannerShow()","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate(im)onBannerShow","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate"]]},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onbannershow()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onbannershow()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerShow()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerShow","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate","title":"MyTargetInstreamAdVideoMotionPlayerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onBannerShow()":{"required":true,"kind":"symbol","navigatorTitle":[{"text":"onBannerShow","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onBannerShow()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBannerShow","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onbannershow()","type":"topic","title":"onBannerShow()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onBannerShow","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBannerShow"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onBannerShow","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/title","value":"MyTargetInstreamAdVideoMotionPlayerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/fragments","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAdVideoMotionPlayerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerShow()\/title","value":"onBannerShow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onBannerShow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBannerShow"}],"op":"replace"}]}]}