{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onitemclick(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onitemclick(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemClick(_:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"itemId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdVideoMotionPlayerDelegate(im)onItemClick:","title":"onItemClick(_:)","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"onItemClick:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate/onItemClick(_:)":{"type":"topic","role":"symbol","title":"onItemClick(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onItemClick:"}],"url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate\/onitemclick(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onItemClick"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate\/onItemClick(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdVideoMotionPlayerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdVideoMotionPlayerDelegate","title":"MyTargetInstreamAdVideoMotionPlayerDelegate","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamadvideomotionplayerdelegate","navigatorTitle":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onItemClick:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onItemClick:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onItemClick:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"itemId"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemClick(_:)\/title","value":"onItemClick:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onItemClick:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate~1onItemClick(_:)\/fragments"},{"value":"MyTargetInstreamAdVideoMotionPlayerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/fragments","value":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdVideoMotionPlayerDelegate\/navigatorTitle","value":[{"text":"MyTargetInstreamAdVideoMotionPlayerDelegate","kind":"identifier"}]}]}]}