{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate(im)playerViewHostDidAppear","symbolKind":"method","required":true,"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"OVKit"}],"title":"playerViewHostDidAppear()","navigatorTitle":[{"kind":"identifier","text":"playerViewHostDidAppear"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostDidAppear"},{"kind":"text","text":"()"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidAppear()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostDidAppear"},{"kind":"text","text":"()"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdidappear()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdidappear()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostDidAppear()":{"required":true,"role":"symbol","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdidappear()","kind":"symbol","title":"playerViewHostDidAppear()","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidAppear()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostDidAppear","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"playerViewHostDidAppear","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"kind":"symbol","type":"topic","title":"OVKPlayerViewHostDelegate","abstract":[],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate","navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerViewHostDidAppear"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playerViewHostDidAppear","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playerViewHostDidAppear","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidAppear()\/title","op":"replace","value":"playerViewHostDidAppear"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidAppear()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostDidAppear"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title","op":"replace","value":"OVKPlayerViewHostDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments","op":"replace","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}]}]}]}