{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostWillAppear","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"playerViewHostWillAppear","kind":"identifier"}],"title":"playerViewHostWillAppear()","externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate(im)playerViewHostWillAppear"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillAppear()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwillappear()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwillappear()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostWillAppear"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostWillAppear()":{"abstract":[],"required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostWillAppear","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillAppear()","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwillappear()","title":"playerViewHostWillAppear()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewHostWillAppear"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"abstract":[],"title":"OVKPlayerViewHostDelegate","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playerViewHostWillAppear","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostWillAppear"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"playerViewHostWillAppear","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playerViewHostWillAppear","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillAppear()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostWillAppear"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillAppear()\/fragments"},{"value":"OVKPlayerViewHostDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments"},{"value":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}