{"metadata":{"title":"playerViewHostDidDisappear()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerViewHostDidDisappear","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"playerViewHostDidDisappear"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate(im)playerViewHostDidDisappear","symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidDisappear()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostDidDisappear","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdiddisappear()"]},{"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdiddisappear()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate","role":"symbol","title":"OVKPlayerViewHostDelegate","abstract":[],"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostDidDisappear()":{"abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostDidDisappear()","kind":"symbol","navigatorTitle":[{"text":"playerViewHostDidDisappear","kind":"identifier"}],"title":"playerViewHostDidDisappear()","type":"topic","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostdiddisappear()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"playerViewHostDidDisappear","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"playerViewHostDidDisappear","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostDidDisappear"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"playerViewHostDidDisappear"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"OVKPlayerViewHostDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}]},{"value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidDisappear()\/title","op":"replace","value":"playerViewHostDidDisappear"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playerViewHostDidDisappear"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostDidDisappear()\/fragments","op":"replace"}]}]}