{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDisappear()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwilldisappear()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwilldisappear()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostWillDisappear","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewHostWillDisappear"},{"kind":"text","text":"()"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate(im)playerViewHostWillDisappear","symbolKind":"method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"playerViewHostWillDisappear"}],"required":true,"title":"playerViewHostWillDisappear()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate/playerViewHostWillDisappear()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate\/playerViewHostWillDisappear()","type":"topic","navigatorTitle":[{"text":"playerViewHostWillDisappear","kind":"identifier"}],"required":true,"url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate\/playerviewhostwilldisappear()","abstract":[],"title":"playerViewHostWillDisappear()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewHostWillDisappear","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate","role":"symbol","abstract":[],"navigatorTitle":[{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"title":"OVKPlayerViewHostDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"playerViewHostWillDisappear"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostWillDisappear"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerViewHostWillDisappear"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDisappear()\/title","op":"replace","value":"playerViewHostWillDisappear"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate~1playerViewHostWillDisappear()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerViewHostWillDisappear"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title","op":"replace","value":"OVKPlayerViewHostDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}