{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityIncrement"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"accessibilityIncrement","kind":"identifier"}],"externalID":"c:@CM@OVKit@objc(cs)TimelineView(im)accessibilityIncrement","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityIncrement"},{"text":"()","kind":"text"}],"title":"accessibilityIncrement()","extendedModule":"OVKit","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/ovkit\/timelineview\/accessibilityincrement()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timelineview\/accessibilityincrement()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityIncrement()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityIncrement()":{"role":"symbol","url":"\/documentation\/ovkit\/timelineview\/accessibilityincrement()","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityIncrement()","type":"topic","title":"accessibilityIncrement()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityIncrement","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"accessibilityIncrement"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"title":"TimelineView","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/timelineview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityIncrement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"accessibilityIncrement","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"accessibilityIncrement"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityIncrement()\/title","value":"accessibilityIncrement"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityIncrement"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityIncrement()\/fragments"},{"value":"TimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","op":"replace"},{"value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","value":[{"text":"TimelineView","kind":"identifier"}]}]}]}