{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview\/accessibilitydecrement()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelineview\/accessibilitydecrement()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityDecrement","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"extendedModule":"OVKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDecrement"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityDecrement"}],"roleHeading":"Instance Method","externalID":"c:@CM@OVKit@objc(cs)TimelineView(im)accessibilityDecrement","role":"symbol","modules":[{"name":"OVKit"}],"title":"accessibilityDecrement()"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityDecrement()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityDecrement()":{"url":"\/documentation\/ovkit\/timelineview\/accessibilitydecrement()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDecrement"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityDecrement()","type":"topic","title":"accessibilityDecrement()","navigatorTitle":[{"kind":"identifier","text":"accessibilityDecrement"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","title":"TimelineView","abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"url":"\/documentation\/ovkit\/timelineview","role":"symbol","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimelineView"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"accessibilityDecrement","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"accessibilityDecrement","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"accessibilityDecrement","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityDecrement()\/title","value":"accessibilityDecrement"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityDecrement()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"accessibilityDecrement"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","value":"TimelineView","op":"replace"},{"value":[{"kind":"identifier","text":"TimelineView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}