{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@CM@OVKit@objc(cs)TimelineView(py)accessibilityValue","roleHeading":"Instance Property","role":"symbol","extendedModule":"OVKit","title":"accessibilityValue","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/timelineview\/accessibilityvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelineview\/accessibilityvalue"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityValue","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"url":"\/documentation\/ovkit\/timelineview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","title":"TimelineView","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/accessibilityValue":{"url":"\/documentation\/ovkit\/timelineview\/accessibilityvalue","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/accessibilityValue","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessibilityValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}],"type":"topic","title":"accessibilityValue","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"accessibilityValue","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"accessibilityValue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"accessibilityValue","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"TimelineView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"value":"accessibilityValue","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityValue"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1accessibilityValue\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}