{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelTracking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview\/canceltracking(with:)"]},{"paths":["\/documentation\/ovkit\/timelineview\/canceltracking(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/cancelTracking(with:)"},"metadata":{"roleHeading":"Instance Method","title":"cancelTracking(with:)","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"cancelTrackingWithEvent:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelTracking"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"externalID":"c:@M@OVKit@objc(cs)TimelineView(im)cancelTrackingWithEvent:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView/cancelTracking(with:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cancelTracking","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"cancelTrackingWithEvent:","kind":"identifier"}],"url":"\/documentation\/ovkit\/timelineview\/canceltracking(with:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/cancelTracking(with:)","kind":"symbol","title":"cancelTracking(with:)","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/timelineview","title":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"cancelTrackingWithEvent:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelTrackingWithEvent:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"cancelTrackingWithEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"cancelTrackingWithEvent:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1cancelTracking(with:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1cancelTracking(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelTrackingWithEvent:"}],"op":"replace"},{"value":"TimelineView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle"}]}]}