{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DurationView","preciseIdentifier":"c:@M@OVKit@objc(cs)DurationView"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"title":"durationView","externalID":"s:5OVKit12TimelineViewC08durationC0AA08DurationC0Cvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationView"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview\/durationview"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)DurationView","text":"DurationView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/durationView":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/durationView","abstract":[],"title":"durationView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"durationView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)DurationView","text":"DurationView","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelineview\/durationview","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DurationView":{"role":"symbol","type":"topic","title":"DurationView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DurationView"}],"url":"\/documentation\/ovkit\/durationview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DurationView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DurationView","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"url":"\/documentation\/ovkit\/timelineview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","title":"TimelineView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineView"}],"navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"kind":"symbol","abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DurationView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DurationView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/fragments"},{"op":"replace","value":[{"text":"DurationView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DurationView\/navigatorTitle"},{"op":"replace","value":"TimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle"}]}]}