{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"frame","externalID":"c:@M@OVKit@objc(cs)TimelineView(py)frame","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"frame","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/ovkit\/timelineview\/frame"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timelineview\/frame"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/frame","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimelineView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/timelineview","title":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/frame":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/ovkit\/timelineview\/frame","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/frame","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frame"}],"kind":"symbol","title":"frame"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"frame","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"frame","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","op":"replace","value":"TimelineView"},{"value":[{"kind":"identifier","text":"TimelineView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","op":"replace","value":[{"text":"TimelineView","kind":"identifier"}]},{"value":"frame","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1frame\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView~1frame\/fragments","value":[{"text":"frame","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}