{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"metadata":{"modules":[{"name":"OVKit"}],"title":"precisionEdgeTracking","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionEdgeTracking","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:5OVKit12TimelineViewC21precisionEdgeTrackingSbvp","symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"text":"Если активировать, то при приближении к левому и правому краю таймлайна ползунок перемотки будет двигаться впереди пальца","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/precisionEdgeTracking"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/timelineview\/precisionedgetracking"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"precisionEdgeTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"title":"TimelineView","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView/precisionEdgeTracking":{"abstract":[{"type":"text","text":"Если активировать, то при приближении к левому и правому краю таймлайна ползунок перемотки будет двигаться впереди пальца"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionEdgeTracking","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/precisionEdgeTracking","type":"topic","title":"precisionEdgeTracking","url":"\/documentation\/ovkit\/timelineview\/precisionedgetracking","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","value":"TimelineView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace"}]}]}