{"abstract":[{"type":"text","text":"Если активировать, то перемотку можно будет выполнять свайпом по любому месту таймлайна."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeTracking","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"relativeTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"relativeTracking","roleHeading":"Instance Property","symbolKind":"property","externalID":"s:5OVKit12TimelineViewC16relativeTrackingSbvp","modules":[{"name":"OVKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/timelineview\/relativetracking"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/relativeTracking"},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView/relativeTracking":{"url":"\/documentation\/ovkit\/timelineview\/relativetracking","abstract":[{"text":"Если активировать, то перемотку можно будет выполнять свайпом по любому месту таймлайна.","type":"text"}],"role":"symbol","kind":"symbol","title":"relativeTracking","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"relativeTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/relativeTracking"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"title":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"TimelineView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"op":"replace","value":[{"text":"TimelineView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TimelineView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}