{"metadata":{"externalID":"s:5OVKit12TimelineViewC05thumbC0So6UIViewCvp","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"title":"thumbView"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview\/thumbview"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbView"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView/thumbView":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/thumbView","url":"\/documentation\/ovkit\/timelineview\/thumbview","title":"thumbView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"thumbView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}],"url":"\/documentation\/ovkit\/timelineview","type":"topic","abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","title":"TimelineView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimelineView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","value":"TimelineView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","value":[{"text":"TimelineView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","op":"replace","value":[{"text":"TimelineView","kind":"identifier"}]}]}]}