{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"updateCurrentTimeCode(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateCurrentTimeCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?)","kind":"text"}],"symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","externalID":"s:5OVKit12TimelineViewC21updateCurrentTimeCodeyySiSgF"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateCurrentTimeCode(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateCurrentTimeCode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"timeCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"timeCode","content":[{"inlineContent":[{"type":"text","text":"Время начало главы в секундах."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущая глава на основе времени проигрывания вычисляется в "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"},{"type":"text","text":"."}]}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Обновление текущей подсвеченной главы."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelineview\/updatecurrenttimecode(_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView/updateCurrentTimeCode(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCurrentTimeCode"},{"kind":"text","text":"("},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/ovkit\/timelineview\/updatecurrenttimecode(_:)","abstract":[{"type":"text","text":"Обновление текущей подсвеченной главы."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView\/updateCurrentTimeCode(_:)","role":"symbol","title":"updateCurrentTimeCode(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"url":"\/documentation\/ovkit\/chapterprovider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"title":"ChapterProvider","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimelineView"}],"title":"TimelineView","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"kind":"symbol","abstract":[{"text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","url":"\/documentation\/ovkit\/timelineview","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"kind":"identifier","text":"OVKChapterProvider"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","value":"TimelineView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","value":[{"text":"TimelineView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}