{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Отмена предзагрузки произвольного элемента.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PrefetchItem","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher\/cancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcher\/cancel(_:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Рекомендуется использовать IndexPrefetcher","type":"text"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"cancel(_:)","roleHeading":"Instance Method","platforms":[{"unavailable":false,"beta":false,"deprecatedAt":"100000.0","name":"Swift","deprecated":false,"message":"Рекомендуется использовать IndexPrefetcher"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(im)cancel:","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"cancel:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/cancel(_:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/cancel(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":")","kind":"text"}],"title":"cancel(_:)","url":"\/documentation\/ovkit\/listprefetcher\/cancel(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"cancel:","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Отмена предзагрузки произвольного элемента."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/cancel(_:)"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ListPrefetcher","kind":"identifier"}],"title":"ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"deprecated":true,"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"url":"\/documentation\/ovkit\/prefetchitem","kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"cancel:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cancel:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cancel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKPrefetchItem>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":[],"path":"\/deprecationSummary"},{"op":"replace","value":"cancel:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1cancel(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cancel:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1cancel(_:)\/fragments"},{"op":"replace","value":"OVKListPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"op":"replace","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"op":"replace","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}