{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher\/datasource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcher\/datasource"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSource","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource","text":"ListPrefetcherDataSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"name":"Swift","deprecatedAt":"100000.0","message":"Рекомендуется использовать IndexPrefetcher","unavailable":false,"beta":false,"deprecated":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListPrefetcherDataSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(py)dataSource","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"dataSource","navigatorTitle":[{"text":"dataSource","kind":"identifier"}]},"abstract":[{"type":"text","text":"Источник данных, из которого префетчер получает список ресурсов."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Рекомендуется использовать IndexPrefetcher"}],"type":"paragraph"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"role":"symbol","title":"ListPrefetcher","type":"topic","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcher","deprecated":true,"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/dataSource":{"deprecated":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/dataSource","url":"\/documentation\/ovkit\/listprefetcher\/datasource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDataSource","text":"ListPrefetcherDataSource","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"dataSource"}],"kind":"symbol","title":"dataSource","role":"symbol","abstract":[{"text":"Источник данных, из которого префетчер получает список ресурсов.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDataSource":{"navigatorTitle":[{"text":"ListPrefetcherDataSource","kind":"identifier"}],"title":"ListPrefetcherDataSource","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDataSource","role":"symbol","url":"\/documentation\/ovkit\/listprefetcherdatasource","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherDataSource","kind":"identifier"}],"abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dataSource","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dataSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKListPrefetcherDataSource>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKListPrefetcherDataSource","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"dataSource","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"},{"value":"dataSource","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1dataSource\/title"},{"value":[{"text":"dataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1dataSource\/fragments"},{"value":"OVKListPrefetcherDataSource","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/title"},{"value":[{"text":"OVKListPrefetcherDataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/fragments"},{"value":[{"text":"OVKListPrefetcherDataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDataSource\/navigatorTitle"}]}]}