{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","platforms":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate","text":"ListPrefetcherDelegate"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(py)delegate","title":"delegate"},"abstract":[{"type":"text","text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListPrefetcherDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Рекомендуется использовать IndexPrefetcher"}],"type":"paragraph"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcher\/delegate"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/delegate":{"type":"topic","url":"\/documentation\/ovkit\/listprefetcher\/delegate","abstract":[{"type":"text","text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы."}],"title":"delegate","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"ListPrefetcherDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKListPrefetcherDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/delegate"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ListPrefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"role":"symbol","deprecated":true,"type":"topic","title":"ListPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/listprefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherDelegate":{"url":"\/documentation\/ovkit\/listprefetcherdelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherDelegate","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherDelegate"}],"abstract":[{"text":"Протокол, через который ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"kind":"symbol","title":"ListPrefetcherDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<OVKListPrefetcherDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKListPrefetcherDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1delegate\/title","op":"replace"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/title","op":"replace","value":"OVKListPrefetcherDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/fragments","op":"replace","value":[{"text":"OVKListPrefetcherDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKListPrefetcherDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}