{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/init(with:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","kind":"typeIdentifier","text":"ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"deprecationSummary":[{"inlineContent":[{"text":"Рекомендуется использовать IndexPrefetcher","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/ovkit\/listprefetcher\/init(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/listprefetcher\/init(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWith:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(im)initWith:","role":"symbol","title":"init(with:)","platforms":[{"name":"Swift","beta":false,"deprecatedAt":"100000.0","message":"Рекомендуется использовать IndexPrefetcher","deprecated":false,"unavailable":false}],"modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcherConfig"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"url":"\/documentation\/ovkit\/listprefetcherconfig","kind":"symbol","title":"ListPrefetcherConfig","navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/init(with:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/init(with:)","url":"\/documentation\/ovkit\/listprefetcher\/init(with:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"init(with:)","deprecated":true},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ListPrefetcher","kind":"identifier"}],"title":"ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"deprecated":true,"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWith:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWith:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWith:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","kind":"typeIdentifier","text":"OVKListPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle","value":[{"text":"OVKListPrefetcherConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1init(with:)\/title","value":"initWith:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1init(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWith:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace"}]}]}