{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchItems","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startingAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущая позиция в списке."}]}],"name":"index"}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"После вызова метода начинается предзагрузка ряда элементов, находящегося сразу после текущей позиции в списке и длиной, которая зависит от качества сети в момент вызова. Кроме того, происходит отмена предзагрузки всех элементов, не входящих в этот ряд.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Предзагрузка элементов списка после текущей позиции."}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetchItems(startingAt:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Рекомендуется использовать IndexPrefetcher"}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(im)prefetchItemsWithStartingAt:","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"prefetchItemsWithStartingAt:"}],"modules":[{"name":"OVKit"}],"title":"prefetchItems(startingAt:)","roleHeading":"Instance Method","platforms":[{"unavailable":false,"name":"Swift","message":"Рекомендуется использовать IndexPrefetcher","deprecatedAt":"100000.0","beta":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startingAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher\/prefetchitems(startingat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/listprefetcher\/prefetchitems(startingat:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/prefetchItems(startingAt:)":{"url":"\/documentation\/ovkit\/listprefetcher\/prefetchitems(startingat:)","navigatorTitle":[{"text":"prefetchItemsWithStartingAt:","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Предзагрузка элементов списка после текущей позиции."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchItems","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startingAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"prefetchItems(startingAt:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetchItems(startingAt:)"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"type":"topic","kind":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"url":"\/documentation\/ovkit\/listprefetcher","title":"ListPrefetcher","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prefetchItemsWithStartingAt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prefetchItemsWithStartingAt:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"prefetchItemsWithStartingAt:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущая позиция в списке."}]}],"name":"index"}]}},{"op":"replace","path":"\/deprecationSummary","value":[]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetchItems(startingAt:)\/title","value":"prefetchItemsWithStartingAt:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetchItems(startingAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prefetchItemsWithStartingAt:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcher"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","value":[{"text":"OVKListPrefetcher","kind":"identifier"}]}]}]}