{"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"text":"PrefetchItem","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldPrefetchPreview"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"prefetch:shouldPrefetchPreview:","kind":"identifier"}],"title":"prefetch(_:shouldPrefetchPreview:)","platforms":[],"externalID":"c:@M@OVKit@objc(cs)OVKListPrefetcher(im)prefetch:shouldPrefetchPreview:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"text":"PrefetchItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":", ","kind":"text"},{"text":"shouldPrefetchPreview","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Предзагружаемый объект."}],"type":"paragraph"}],"name":"item"},{"name":"shouldPrefetchPreview","content":[{"inlineContent":[{"type":"text","text":"Флаг провоцирующий загрузку превью."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/listprefetcher\/prefetch(_:shouldprefetchpreview:)"]},{"paths":["\/documentation\/ovkit\/listprefetcher\/prefetch(_:shouldprefetchpreview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:shouldPrefetchPreview:)"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Рекомендуется использовать IndexPrefetcher"}],"type":"paragraph"}],"kind":"symbol","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"kind":"symbol","deprecated":true,"title":"ListPrefetcher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/listprefetcher","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"role":"symbol","abstract":[{"text":"Протокол, описывающий параметры предзагрузки видео-ресурса.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","type":"topic","url":"\/documentation\/ovkit\/prefetchitem","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PrefetchItem","kind":"identifier"}],"kind":"symbol","title":"PrefetchItem","navigatorTitle":[{"text":"PrefetchItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher/prefetch(_:shouldPrefetchPreview:)":{"navigatorTitle":[{"text":"prefetch:shouldPrefetchPreview:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher\/prefetch(_:shouldPrefetchPreview:)","abstract":[{"type":"text","text":"Предзагрузка произвольного элемента отдельно от списка."}],"kind":"symbol","deprecated":true,"title":"prefetch(_:shouldPrefetchPreview:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"text":"PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":", ","kind":"text"},{"text":"shouldPrefetchPreview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/listprefetcher\/prefetch(_:shouldprefetchpreview:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"prefetch:shouldPrefetchPreview:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prefetch:shouldPrefetchPreview:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"prefetch:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem","text":"id<OVKPrefetchItem>"},{"kind":"text","text":") "},{"text":"item","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldPrefetchPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"shouldPrefetchPreview"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Предзагружаемый объект."}]}]},{"name":"shouldPrefetchPreview","content":[{"inlineContent":[{"type":"text","text":"Флаг провоцирующий загрузку превью."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","value":"OVKListPrefetcher"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","op":"replace"},{"value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments","value":[{"text":"OVKPrefetchItem","kind":"identifier"}]},{"value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:shouldPrefetchPreview:)\/title","value":"prefetch:shouldPrefetchPreview:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"prefetch:shouldPrefetchPreview:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher~1prefetch(_:shouldPrefetchPreview:)\/fragments","op":"replace"}]}]}