{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/pipwindow\/corner"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit12StickyCornerO","text":"StickyCorner","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StickyCorner"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/corner","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StickyCorner","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12StickyCornerO"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:5OVKit9PiPWindowC6cornerAA12StickyCornerOSgvp","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"corner"},"abstract":[{"type":"text","text":"Угол, в котором в данный момент находится окно."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"title":"PiPWindow","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},"doc://onevideo.OVKit/documentation/OVKit/StickyCorner":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StickyCorner","kind":"identifier"}],"url":"\/documentation\/ovkit\/stickycorner","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StickyCorner","abstract":[{"type":"text","text":"Угол экрана."}],"title":"StickyCorner","type":"topic","navigatorTitle":[{"text":"StickyCorner","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/corner":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StickyCorner","preciseIdentifier":"s:5OVKit12StickyCornerO","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/pipwindow\/corner","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/corner","abstract":[{"type":"text","text":"Угол, в котором в данный момент находится окно."}],"title":"corner","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"}]}]}