{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdate(insets:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Изменилось значение инсетов."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"insets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/pipwindow\/didupdate(insets:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/pipwindow\/didupdate(insets:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"didUpdate(insets:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didUpdateWithInsets:"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPiPWindow(im)didUpdateWithInsets:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"insets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"title":"PiPWindow","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/didUpdate(insets:)":{"role":"symbol","title":"didUpdate(insets:)","type":"topic","navigatorTitle":[{"text":"didUpdateWithInsets:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdate(insets:)","abstract":[{"type":"text","text":"Изменилось значение инсетов."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"insets","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/pipwindow\/didupdate(insets:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"didUpdateWithInsets:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didUpdateWithInsets:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateWithInsets:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"kind":"text","text":") "},{"kind":"internalParam","text":"insets"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKPiPWindow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title"},{"op":"replace","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments"},{"op":"replace","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"},{"op":"replace","value":"didUpdateWithInsets:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdate(insets:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didUpdateWithInsets:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdate(insets:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}