{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdateCoordinateSpace()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Сигнал об изменении размеров экрана или сцены."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/pipwindow\/didupdatecoordinatespace()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/pipwindow\/didupdatecoordinatespace()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateCoordinateSpace"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Необходимо вызывать из соответствующего метода ","type":"text"},{"code":"AppDelegate","type":"codeVoice"},{"text":" или ","type":"text"},{"code":"SceneDelegate","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPiPWindow(im)didUpdateCoordinateSpace","title":"didUpdateCoordinateSpace()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateCoordinateSpace"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"didUpdateCoordinateSpace","kind":"identifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"abstract":[{"type":"text","text":"Окно внутреннего Picture in Picture."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/pipwindow","title":"PiPWindow","kind":"symbol","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/didUpdateCoordinateSpace()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateCoordinateSpace"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Сигнал об изменении размеров экрана или сцены."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/didUpdateCoordinateSpace()","url":"\/documentation\/ovkit\/pipwindow\/didupdatecoordinatespace()","kind":"symbol","role":"symbol","title":"didUpdateCoordinateSpace()","navigatorTitle":[{"kind":"identifier","text":"didUpdateCoordinateSpace"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didUpdateCoordinateSpace","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateCoordinateSpace"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateCoordinateSpace"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdateCoordinateSpace()\/title","value":"didUpdateCoordinateSpace","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1didUpdateCoordinateSpace()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didUpdateCoordinateSpace","kind":"identifier"}],"op":"replace"}]}]}