{"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"maximizeToFullscreen","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPiPWindow(im)maximizeToFullscreen","title":"maximizeToFullscreen()"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/pipwindow\/maximizetofullscreen()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/pipwindow\/maximizetofullscreen()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Device Orientation для "},{"type":"codeVoice","code":"PlayerManager.shared.pipWindow"},{"type":"text","text":" можно поддержать"},{"text":" ","type":"text"},{"type":"text","text":"в методе AppDelegate "},{"type":"codeVoice","code":"application(_:supportedIntefaceOrientationsFor:)"}],"title":"PiPWindow","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/maximizeToFullscreen()":{"type":"topic","url":"\/documentation\/ovkit\/pipwindow\/maximizetofullscreen()","title":"maximizeToFullscreen()","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen()","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreen"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"maximizeToFullscreen","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreen"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow","op":"replace"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"},{"value":"maximizeToFullscreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreen"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen()\/fragments"}]}]}