{"kind":"symbol","abstract":[{"text":"Развернуть окно в полноэкранный режим.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"variants":[{"paths":["\/documentation\/ovkit\/pipwindow\/maximizetofullscreen(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/pipwindow\/maximizetofullscreen(completion:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreen"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Блок, который вызовется после завершения перехода в полноэкранный режим. Параметром передается ","type":"text"},{"type":"codeVoice","code":"Bool"},{"text":", указывающий успешность операции: ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" если переход выполнен, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" если PiP был закрыт без восстановления.","type":"text"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen(completion:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"maximizeToFullscreen(completion:)","modules":[{"name":"OVKit"}],"platforms":[],"navigatorTitle":[{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"externalID":"c:@M@OVKit@objc(cs)OVKPiPWindow(im)maximizeToFullscreenWithCompletion:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"title":"PiPWindow","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","abstract":[{"text":"Окно внутреннего Picture in Picture.","type":"text"}],"url":"\/documentation\/ovkit\/pipwindow","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PiPWindow","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/maximizeToFullscreen(completion:)":{"title":"maximizeToFullscreen(completion:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/maximizeToFullscreen(completion:)","navigatorTitle":[{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Развернуть окно в полноэкранный режим.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/pipwindow\/maximizetofullscreen(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maximizeToFullscreen","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"maximizeToFullscreenWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который вызовется после завершения перехода в полноэкранный режим. Параметром передается "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":", указывающий успешность операции: "},{"type":"codeVoice","code":"true"},{"type":"text","text":" если переход выполнен, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" если PiP был закрыт без восстановления."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle","value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen(completion:)\/title","op":"replace","value":"maximizeToFullscreenWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow~1maximizeToFullscreen(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}]}]}]}