{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/pipwindow\/movetocorner(_:initialvelocity:animated:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"]]},"metadata":{"title":"moveToCorner(_:initialVelocity:animated:completion:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToCorner","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit12StickyCornerO","text":"StickyCorner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialVelocity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","externalID":"s:5OVKit9PiPWindowC12moveToCorner_15initialVelocity8animated10completionyAA06StickyF0O_So7CGPointVSgSbySbcSgtF","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToCorner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"corner"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit12StickyCornerO","text":"StickyCorner","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StickyCorner"},{"text":", ","kind":"text"},{"text":"initialVelocity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/moveToCorner(_:initialVelocity:animated:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/StickyCorner":{"type":"topic","kind":"symbol","role":"symbol","title":"StickyCorner","abstract":[],"url":"\/documentation\/ovkit\/stickycorner","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StickyCorner","kind":"identifier"}],"navigatorTitle":[{"text":"StickyCorner","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StickyCorner"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow/moveToCorner(_:initialVelocity:animated:completion:)":{"url":"\/documentation\/ovkit\/pipwindow\/movetocorner(_:initialvelocity:animated:completion:)","role":"symbol","kind":"symbol","abstract":[],"title":"moveToCorner(_:initialVelocity:animated:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToCorner","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit12StickyCornerO","text":"StickyCorner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialVelocity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow\/moveToCorner(_:initialVelocity:animated:completion:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PiPWindow"}],"abstract":[{"text":"Device Orientation для ","type":"text"},{"code":"PlayerManager.shared.pipWindow","type":"codeVoice"},{"text":" можно поддержать","type":"text"},{"text":" ","type":"text"},{"text":"в методе AppDelegate ","type":"text"},{"code":"application(_:supportedIntefaceOrientationsFor:)","type":"codeVoice"}],"url":"\/documentation\/ovkit\/pipwindow","type":"topic","kind":"symbol","role":"symbol","title":"PiPWindow","navigatorTitle":[{"kind":"identifier","text":"PiPWindow"}]}},"variantOverrides":[{"patch":[{"value":"OVKPiPWindow","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments"},{"value":[{"text":"OVKPiPWindow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}