{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler\/context","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","text":"StatsContext"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKStatsHandler(py)context","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"text":"StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"title":"context","navigatorTitle":[{"text":"context","kind":"identifier"}],"required":true,"role":"symbol"},"sections":[],"abstract":[{"text":"Будет установлен после добавления в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true}],"variants":[{"paths":["\/documentation\/ovkit\/statshandler\/context"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandler\/context"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsContext"}],"url":"\/documentation\/ovkit\/statscontext","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"navigatorTitle":[{"kind":"identifier","text":"StatsContext"}],"title":"StatsContext"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"role":"symbol","url":"\/documentation\/ovkit\/statshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandler"}],"title":"StatsHandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"События логирования будут вызваны на специальной background очереди."},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":" после добавления нового ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"role":"symbol","url":"\/documentation\/ovkit\/statscollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsCollector"}],"title":"StatsCollector","navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"type":"topic","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler/context":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"context","kind":"identifier"}],"title":"context","kind":"symbol","url":"\/documentation\/ovkit\/statshandler\/context","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","text":"StatsContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler\/context","required":true,"abstract":[{"text":"Будет установлен после добавления в ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"type":"topic","role":"symbol","kind":"symbol","title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"url":"\/documentation\/ovkit\/video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"context","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"context","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","text":"OVKStatsContext"},{"text":" * ","kind":"text"},{"text":"context","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","value":"OVKStatsContext"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsContext"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"value":"context","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler~1context\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler~1context\/fragments","value":[{"kind":"identifier","text":"context"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","op":"replace","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]}]}]}