{"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"statistics"}],"role":"symbol","title":"statistics","required":true,"externalID":"c:@M@OVKit@objc(pl)OVKStatsHandler(py)statistics","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","text":"StatsHandlerContext"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandler\/statistics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandler\/statistics"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler\/statistics","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"]]},"sections":[],"abstract":[{"text":"Будет установлено после добавления в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"title":"StatsCollector","navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"type":"topic","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"url":"\/documentation\/ovkit\/statscollector","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsCollector"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandler"}],"url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"topic","title":"StatsHandler","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"url":"\/documentation\/ovkit\/statshandlercontext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Набор свойств, к которому может обращаться "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandlerContext"}],"title":"StatsHandlerContext","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerContext"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","title":"Video","type":"topic","abstract":[{"text":"Стандартная модель, реализующая ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/video","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler/statistics":{"title":"statistics","navigatorTitle":[{"kind":"identifier","text":"statistics"}],"type":"topic","abstract":[{"type":"text","text":"Будет установлено после добавления в "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/statshandler\/statistics","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatsHandlerContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler\/statistics","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"statistics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"statistics"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","text":"OVKStatsHandlerContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext"},{"kind":"text","text":" * "},{"kind":"identifier","text":"statistics"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title","value":"OVKStatsHandlerContext","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler~1statistics\/title","value":"statistics"},{"value":[{"text":"statistics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler~1statistics\/fragments"}]}]}