{"kind":"symbol","metadata":{"symbolKind":"property","title":"customStepInterval","externalID":"s:5OVKit21DoubleTapSeekBehaviorC18customStepIntervalSdSgvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customStepInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Пользовательский интервал перемотки.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/customstepinterval"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/customStepInterval"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customStepInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"При значении "},{"code":"nil","type":"codeVoice"},{"text":" интервал берется у связанного плеера: ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/quickSeekInterval","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/quickSeekInterval":{"url":"\/documentation\/ovkit\/playerview\/quickseekinterval","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/quickSeekInterval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quickSeekInterval","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","abstract":[{"type":"text","text":"Интервал для быстрой перемотки."}],"navigatorTitle":[{"text":"quickSeekInterval","kind":"identifier"}],"title":"quickSeekInterval"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","role":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"title":"DoubleTapSeekBehavior","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/customStepInterval":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customStepInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/doubletapseekbehavior\/customstepinterval","role":"symbol","abstract":[{"text":"Пользовательский интервал перемотки.","type":"text"}],"title":"customStepInterval","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/customStepInterval","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1quickSeekInterval\/title","value":"quickSeekInterval","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1quickSeekInterval\/fragments","value":[{"kind":"identifier","text":"quickSeekInterval"}],"op":"replace"},{"op":"replace","value":"DoubleTapSeekBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}