{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizerShouldBegin(_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizerShouldBegin(_:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizershouldbegin(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizershouldbegin(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"extendedModule":"OVKit","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@CM@OVKit@objc(cs)DoubleTapSeekBehavior(im)gestureRecognizerShouldBegin:","title":"gestureRecognizerShouldBegin(_:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/UIGestureRecognizerDelegate-Implementations":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations","title":"UIGestureRecognizerDelegate Implementations","url":"\/documentation\/ovkit\/doubletapseekbehavior\/uigesturerecognizerdelegate-implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/gestureRecognizerShouldBegin(_:)":{"navigatorTitle":[{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"title":"gestureRecognizerShouldBegin(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizerShouldBegin(_:)","url":"\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizershouldbegin(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","kind":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","title":"DoubleTapSeekBehavior","type":"topic","role":"symbol","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"gestureRecognizerShouldBegin:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":" *) ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizerShouldBegin(_:)\/title","value":"gestureRecognizerShouldBegin:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}]},{"value":"DoubleTapSeekBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}