{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizer(_:shouldreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizer(_:shouldreceive:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"OVKit","title":"gestureRecognizer(_:shouldReceive:)","symbolKind":"method","externalID":"c:@CM@OVKit@objc(cs)DoubleTapSeekBehavior(im)gestureRecognizer:shouldReceiveTouch:","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":" "},{"text":"touch","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","kind":"symbol","title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizer(_:shouldReceive:)","url":"\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizer(_:shouldreceive:)","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}],"type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"url":"\/documentation\/ovkit\/doubletapseekbehavior","type":"topic","abstract":[{"text":"Перемотка видео двойным тапом.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"title":"DoubleTapSeekBehavior","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","url":"\/documentation\/ovkit\/doubletapseekbehavior\/uigesturerecognizerdelegate-implementations","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations","kind":"article","title":"UIGestureRecognizerDelegate Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"gestureRecognizer:shouldReceiveTouch:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"gestureRecognizer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"text":"shouldReceiveTouch:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":" *) "},{"text":"touch","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"value":"DoubleTapSeekBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]}]}]}