{"abstract":[{"type":"text","text":"Создание поведения."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/init(customStepInterval:shouldBegin:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"customStepInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"shouldBegin"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок должен вернуть, можно ли начинать жест быстрой перемотки в данный момент."}]}],"name":"shouldBegin"}]}],"metadata":{"externalID":"s:5OVKit21DoubleTapSeekBehaviorC18customStepInterval11shouldBeginACSdSg_Sbyctcfc","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customStepInterval"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"shouldBegin"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","title":"init(customStepInterval:shouldBegin:)","modules":[{"name":"OVKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/init(customstepinterval:shouldbegin:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"title":"DoubleTapSeekBehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"abstract":[{"text":"Перемотка видео двойным тапом.","type":"text"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/init(customStepInterval:shouldBegin:)":{"kind":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior\/init(customstepinterval:shouldbegin:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customStepInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":"?, ","kind":"text"},{"text":"shouldBegin","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","title":"init(customStepInterval:shouldBegin:)","abstract":[{"text":"Создание поведения.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/init(customStepInterval:shouldBegin:)"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","value":"DoubleTapSeekBehavior","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}