{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/isenabled"]}],"metadata":{"externalID":"s:5OVKit21DoubleTapSeekBehaviorC9isEnabledSbvp","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Активен ли жест быстрой перемотки.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/isEnabled"},"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/isEnabled":{"abstract":[{"type":"text","text":"Активен ли жест быстрой перемотки."}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/isenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"isEnabled","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/isEnabled"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","title":"DoubleTapSeekBehavior","navigatorTitle":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"kind":"symbol","abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoubleTapSeekBehavior"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DoubleTapSeekBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}