{"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/onlyrequiresduration"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyRequiresDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyRequiresDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"s:5OVKit21DoubleTapSeekBehaviorC20onlyRequiresDurationSbvp","title":"onlyRequiresDuration","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/onlyRequiresDuration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Делает жест доступным в состоянии, когда воспроизведение завершилось или еще не началось."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/onlyRequiresDuration":{"title":"onlyRequiresDuration","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/onlyRequiresDuration","kind":"symbol","abstract":[{"type":"text","text":"Делает жест доступным в состоянии, когда воспроизведение завершилось или еще не началось."}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/onlyrequiresduration","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyRequiresDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","role":"symbol","abstract":[{"text":"Перемотка видео двойным тапом.","type":"text"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior","type":"topic","title":"DoubleTapSeekBehavior","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","op":"replace","value":"DoubleTapSeekBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]}]}]}