{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekForward"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekForward()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"seekForward"}],"title":"seekForward()","externalID":"c:@M@OVKit@objc(cs)DoubleTapSeekBehavior(im)seekForward","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekForward","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"sections":[],"abstract":[{"type":"text","text":"Эмуляция жеста быстрой перемотки вперёд."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/seekforward()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/seekforward()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"title":"DoubleTapSeekBehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"abstract":[{"text":"Перемотка видео двойным тапом.","type":"text"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/seekForward()":{"abstract":[{"text":"Эмуляция жеста быстрой перемотки вперёд.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekForward()","title":"seekForward()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"seekForward"}],"url":"\/documentation\/ovkit\/doubletapseekbehavior\/seekforward()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"seekForward","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"seekForward","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"seekForward","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"seekForward","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DoubleTapSeekBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"seekForward","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekForward()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekForward"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekForward()\/fragments"}]}]}