{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"abstract":[{"type":"text","text":"Эмуляция жеста быстрой перемотки назад."}],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"seekBackward()","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBackward"},{"kind":"text","text":"()"}],"externalID":"c:@M@OVKit@objc(cs)DoubleTapSeekBehavior(im)seekBackward","navigatorTitle":[{"kind":"identifier","text":"seekBackward"}]},"variants":[{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/seekbackward()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/seekbackward()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"seekBackward","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekBackward()","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/seekBackward()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/seekBackward()","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior\/seekbackward()","title":"seekBackward()","navigatorTitle":[{"text":"seekBackward","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBackward"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Эмуляция жеста быстрой перемотки назад."}]},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","kind":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","title":"DoubleTapSeekBehavior","type":"topic","role":"symbol","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"seekBackward"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekBackward"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"seekBackward"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekBackward()\/title","value":"seekBackward","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekBackward"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1seekBackward()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","value":"DoubleTapSeekBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}