{"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior"]]},"metadata":{"roleHeading":"API Collection","modules":[{"name":"OVKit"}],"title":"UIGestureRecognizerDelegate Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizer(_:shouldReceive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizerShouldBegin(_:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/uigesturerecognizerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/doubletapseekbehavior\/uigesturerecognizerdelegate-implementations"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/gestureRecognizer(_:shouldReceive:)":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizer(_:shouldReceive:)","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizer(_:shouldreceive:)","title":"gestureRecognizer(_:shouldReceive:)","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior/gestureRecognizerShouldBegin(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizerShouldBegin(_:)","type":"topic","url":"\/documentation\/ovkit\/doubletapseekbehavior\/gesturerecognizershouldbegin(_:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"abstract":[],"title":"gestureRecognizerShouldBegin(_:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DoubleTapSeekBehavior":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior","role":"symbol","url":"\/documentation\/ovkit\/doubletapseekbehavior","abstract":[{"type":"text","text":"Перемотка видео двойным тапом."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DoubleTapSeekBehavior","kind":"identifier"}],"title":"DoubleTapSeekBehavior","navigatorTitle":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizer(_:shouldReceive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DoubleTapSeekBehavior\/gestureRecognizerShouldBegin(_:)"],"title":"Instance Methods","generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"gestureRecognizer:shouldReceiveTouch:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},{"value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizerShouldBegin(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/title","value":"DoubleTapSeekBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/fragments","value":[{"text":"DoubleTapSeekBehavior","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DoubleTapSeekBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DoubleTapSeekBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}