{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetmargin"]},{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetmargin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetMargin","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomSheetMargin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Может быть отрицательным. В таком случае контроллер будет перекрывать плеер. ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает нулевое расстояние."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение имеет тип "},{"type":"codeVoice","code":"CGFloat"},{"type":"text","text":"."}]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)bottomSheetMargin","title":"bottomSheetMargin","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"bottomSheetMargin"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomSheetMargin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol"},"abstract":[{"type":"text","text":"Расстояние между плеером и "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"type":"text","text":" при показе снизу плеера."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/bottomSheetMargin":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomSheetMargin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetMargin","title":"bottomSheetMargin","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetmargin","navigatorTitle":[{"text":"bottomSheetMargin","kind":"identifier"}],"abstract":[{"type":"text","text":"Расстояние между плеером и "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"type":"text","text":" при показе снизу плеера."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol","title":"FullscreenSupplementaryController"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bottomSheetMargin","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"bottomSheetMargin","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomSheetMargin"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"bottomSheetMargin","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetMargin\/title"},{"value":[{"text":"bottomSheetMargin","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetMargin\/fragments"},{"value":"OVKFullscreenSupplementaryController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle"}]}]}