{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetPlayerAspectRatio","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"К примеру, "},{"type":"codeVoice","code":"16.0\/9.0"},{"type":"text","text":" сделает плеер горизонтальным. Значение по умолчанию "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что размер автоматически подстраивается под соотношение сторон видеодорожки, а при заданном значении перестают учитываться ограничения на минимальную и максимальную высоту плеера."}],"type":"paragraph"},{"inlineContent":[{"text":"Значение имеет тип ","type":"text"},{"type":"codeVoice","code":"double"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetplayeraspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetplayeraspectratio"]}],"abstract":[{"type":"text","text":"Принудительно устанавливает соотношение сторон плеера, когда он отображается над "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"type":"text","text":"."}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"bottomSheetPlayerAspectRatio","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)bottomSheetPlayerAspectRatio"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"topic","kind":"symbol","title":"FullscreenSupplementaryController","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/bottomSheetPlayerAspectRatio":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Принудительно устанавливает соотношение сторон плеера, когда он отображается над "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/bottomsheetplayeraspectratio","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/bottomSheetPlayerAspectRatio","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}],"title":"bottomSheetPlayerAspectRatio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"bottomSheetPlayerAspectRatio","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/title","op":"replace","value":"bottomSheetPlayerAspectRatio"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}]}]}]}