{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"customControlsSafeInsets","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)customControlsSafeInsets","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customControlsSafeInsets"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"customControlsSafeInsets"}]},"variants":[{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/customcontrolssafeinsets"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/customcontrolssafeinsets"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customControlsSafeInsets","interfaceLanguage":"swift"},"abstract":[{"text":"Переопределение инсетов, которые действуют на контролы плеера во время показа ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customControlsSafeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает наследование инсетов от safe area."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение имеет тип "},{"type":"codeVoice","code":"UIEdgeInsets"},{"type":"text","text":"."}]}],"kind":"content"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/customControlsSafeInsets":{"role":"symbol","abstract":[{"type":"text","text":"Переопределение инсетов, которые действуют на контролы плеера во время показа "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"customControlsSafeInsets"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customControlsSafeInsets","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/customcontrolssafeinsets","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customControlsSafeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"customControlsSafeInsets","type":"topic","kind":"symbol","required":true},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"type":"topic","title":"FullscreenSupplementaryController","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"customControlsSafeInsets","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customControlsSafeInsets"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue"},{"kind":"text","text":" * "},{"text":"customControlsSafeInsets","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"customControlsSafeInsets","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customControlsSafeInsets\/title"},{"value":[{"text":"customControlsSafeInsets","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customControlsSafeInsets\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace","value":"OVKFullscreenSupplementaryController"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}