{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customSupplementaryViewInsets(sideBySide:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/customsupplementaryviewinsets(sidebyside:)"]},{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/customsupplementaryviewinsets(sidebyside:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"customSupplementaryViewInsetsWithSideBySide:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"customSupplementaryViewInsets","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sideBySide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"customSupplementaryViewInsets(sideBySide:)","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(im)customSupplementaryViewInsetsWithSideBySide:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"customSupplementaryViewInsets","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sideBySide"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Показывается ли "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" справа от плеера.","type":"text"}]}],"name":"sideBySide"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Значение имеет тип ","type":"text"},{"type":"codeVoice","code":"UIEdgeInsets"},{"type":"text","text":"."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Переопределение инсетов, которые действуют на общую область отображения плеера и "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":". ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает наследование инсетов от safe area.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/customSupplementaryViewInsets(sideBySide:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/customSupplementaryViewInsets(sideBySide:)","title":"customSupplementaryViewInsets(sideBySide:)","navigatorTitle":[{"text":"customSupplementaryViewInsetsWithSideBySide:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"customSupplementaryViewInsets","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sideBySide"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/customsupplementaryviewinsets(sidebyside:)","abstract":[{"text":"Переопределение инсетов, которые действуют на общую область отображения плеера и ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":". ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает наследование инсетов от safe area.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","title":"FullscreenSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"customSupplementaryViewInsetsWithSideBySide:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"customSupplementaryViewInsetsWithSideBySide:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValue"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"customSupplementaryViewInsetsWithSideBySide:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sideBySide"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customSupplementaryViewInsets(sideBySide:)\/title","op":"replace","value":"customSupplementaryViewInsetsWithSideBySide:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1customSupplementaryViewInsets(sideBySide:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"customSupplementaryViewInsetsWithSideBySide:"}],"op":"replace"},{"value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]}]}]}