{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dismissGestureRecognizer"}],"title":"dismissGestureRecognizer","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)dismissGestureRecognizer","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissGestureRecognizer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","kind":"typeIdentifier","text":"UIPanGestureRecognizer"},{"kind":"text","text":"?"}],"required":true,"modules":[{"name":"OVKit"}],"role":"symbol"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/dismissgesturerecognizer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/dismissgesturerecognizer"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/dismissGestureRecognizer"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"abstract":[{"text":"Жест, который дает возможность скрыть ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" свайпом вниз. В зависимости от значения свойства ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","isActive":true,"type":"reference"},{"text":" срабатывание жеста приведет либо к закрытию только ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" (","type":"text"},{"code":"false","type":"codeVoice"},{"text":"), либо к интерактивному дисмиссу всего контроллера с полноэкранным плеером (","type":"text"},{"code":"true","type":"codeVoice"},{"text":").","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/dismissGestureRecognizer":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/dismissgesturerecognizer","title":"dismissGestureRecognizer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismissGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":"?","kind":"text"}],"abstract":[{"text":"Жест, который дает возможность скрыть ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" свайпом вниз. В зависимости от значения свойства ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","isActive":true,"type":"reference"},{"text":" срабатывание жеста приведет либо к закрытию только ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" (","type":"text"},{"code":"false","type":"codeVoice"},{"text":"), либо к интерактивному дисмиссу всего контроллера с полноэкранным плеером (","type":"text"},{"code":"true","type":"codeVoice"},{"text":").","type":"text"}],"navigatorTitle":[{"text":"dismissGestureRecognizer","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/dismissGestureRecognizer","required":true},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/wasPresentedForSupplementaryController":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/wasPresentedForSupplementaryController","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/waspresentedforsupplementarycontroller","abstract":[{"text":"Был ли контроллер презентован одновременно с добавлением ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"wasPresentedForSupplementaryController","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wasPresentedForSupplementaryController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/supplementaryViewController":{"navigatorTitle":[{"kind":"identifier","text":"supplementaryViewController"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementaryViewController"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","kind":"typeIdentifier","text":"FullscreenSupplementaryController"},{"kind":"text","text":")?"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/supplementaryviewcontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","title":"supplementaryViewController","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","title":"FullscreenSupplementaryController","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dismissGestureRecognizer","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"dismissGestureRecognizer","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dismissGestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"dismissGestureRecognizer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1dismissGestureRecognizer\/title","op":"replace"},{"value":[{"text":"dismissGestureRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1dismissGestureRecognizer\/fragments","op":"replace"},{"value":"wasPresentedForSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/title","op":"replace"},{"value":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1wasPresentedForSupplementaryController\/fragments","op":"replace"},{"value":"supplementaryViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/title","op":"replace"},{"value":[{"text":"supplementaryViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/fragments","op":"replace"},{"value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}