{"sections":[],"abstract":[{"text":"Нужно ли скрывать контролы плеера, когда он показывается одновременно с ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":".","type":"text"}],"metadata":{"navigatorTitle":[{"text":"hidesPlayerControls","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidesPlayerControls","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"title":"hidesPlayerControls","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)hidesPlayerControls","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidesPlayerControls"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/hidesPlayerControls","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/hidesplayercontrols"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/hidesplayercontrols"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/hidesPlayerControls":{"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/hidesplayercontrols","navigatorTitle":[{"text":"hidesPlayerControls","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/hidesPlayerControls","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidesPlayerControls","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"hidesPlayerControls","required":true,"abstract":[{"text":"Нужно ли скрывать контролы плеера, когда он показывается одновременно с ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenSupplementaryController","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","title":"FullscreenSupplementaryController","type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"hidesPlayerControls","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hidesPlayerControls"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"hidesPlayerControls","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1hidesPlayerControls\/title","value":"hidesPlayerControls","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1hidesPlayerControls\/fragments","value":[{"kind":"identifier","text":"hidesPlayerControls"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"}]}]}