{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldBeClosedOnRotateToPortrait"}],"modules":[{"name":"OVKit"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBeClosedOnRotateToPortrait"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)shouldBeClosedOnRotateToPortrait","title":"shouldBeClosedOnRotateToPortrait","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeClosedOnRotateToPortrait","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Для работы по умолчанию нужно вернуть ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}],"abstract":[{"type":"text","text":"Потом это можно расширить до метода supportedInterfaceOrientations"},{"type":"text","text":" "},{"type":"text","text":"Нужно ли автоматически закрыть "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"type":"text","text":", если повернули экран в портретный режим."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/shouldBeClosedOnRotateToPortrait","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/shouldbeclosedonrotatetoportrait"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/shouldbeclosedonrotatetoportrait"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/shouldBeClosedOnRotateToPortrait":{"kind":"symbol","title":"shouldBeClosedOnRotateToPortrait","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/shouldBeClosedOnRotateToPortrait","abstract":[{"type":"text","text":"Потом это можно расширить до метода supportedInterfaceOrientations"},{"type":"text","text":" "},{"type":"text","text":"Нужно ли автоматически закрыть "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"type":"text","text":", если повернули экран в портретный режим."}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/shouldbeclosedonrotatetoportrait","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldBeClosedOnRotateToPortrait"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBeClosedOnRotateToPortrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"kind":"symbol","title":"FullscreenSupplementaryController","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shouldBeClosedOnRotateToPortrait","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"shouldBeClosedOnRotateToPortrait","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shouldBeClosedOnRotateToPortrait","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1shouldBeClosedOnRotateToPortrait\/title","value":"shouldBeClosedOnRotateToPortrait"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1shouldBeClosedOnRotateToPortrait\/fragments","value":[{"kind":"identifier","text":"shouldBeClosedOnRotateToPortrait"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}