{"abstract":[{"type":"text","text":"Определяет, следует ли отображать "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" справа от плеера."}],"metadata":{"symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(im)usesSideBySideLayoutFor:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usesSideBySideLayout","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"usesSideBySideLayoutFor:","kind":"identifier"}],"title":"usesSideBySideLayout(for:)","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usesSideBySideLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/usesSideBySideLayout(for:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/usessidebysidelayout(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreensupplementarycontroller\/usessidebysidelayout(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController/usesSideBySideLayout(for:)":{"abstract":[{"type":"text","text":"Определяет, следует ли отображать "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" справа от плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController\/usesSideBySideLayout(for:)","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller\/usessidebysidelayout(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usesSideBySideLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"usesSideBySideLayoutFor:","kind":"identifier"}],"title":"usesSideBySideLayout(for:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","title":"FullscreenSupplementaryController","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"usesSideBySideLayoutFor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"usesSideBySideLayoutFor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"usesSideBySideLayoutFor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1usesSideBySideLayout(for:)\/title","value":"usesSideBySideLayoutFor:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController~1usesSideBySideLayout(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"usesSideBySideLayoutFor:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}