{"metadata":{"title":"layoutSubviews()","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKFullscreenSupplementedAdControlsView(im)layoutSubviews","symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView\/layoutSubviews()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreensupplementedadcontrolsview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreensupplementedadcontrolsview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView/layoutSubviews()":{"kind":"symbol","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"type":"topic","title":"layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview\/layoutsubviews()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView\/layoutSubviews()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementedAdControlsView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementedAdControlsView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"navigatorTitle":[{"text":"FullscreenSupplementedAdControlsView","kind":"identifier"}],"title":"FullscreenSupplementedAdControlsView","role":"symbol","abstract":[{"type":"text","text":"Рекламные контролы для Fullscreen."},{"type":"text","text":" "},{"type":"text","text":"В отличии от базовых "},{"type":"codeVoice","code":"SupplementedAdControlsView"},{"type":"text","text":" отсутствует кнопка звука и нажатие для раскрытия рекламных товаров."}],"type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementedadcontrolsview","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"layoutSubviews","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"layoutSubviews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView~1layoutSubviews()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView~1layoutSubviews()\/fragments"},{"op":"replace","value":"OVKFullscreenSupplementedAdControlsView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/title"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/fragments"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementedAdControlsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementedAdControlsView\/navigatorTitle"}]}]}