{"variants":[{"paths":["\/documentation\/ovkit\/ovkpersistentitempreview\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkpersistentitempreview\/url"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemPreview\/url","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"URL изображения."}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"url","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview(py)url","title":"url","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemPreview":{"title":"PersistentItemPreview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PersistentItemPreview","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"PersistentItemPreview","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistentitempreview","abstract":[{"type":"text","text":"Модель, содержащая данные варианта превью для заданного размера."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItemPreview/url":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItemPreview\/url","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"URL изображения."}],"navigatorTitle":[{"kind":"identifier","text":"url"}],"title":"url","url":"\/documentation\/ovkit\/ovkpersistentitempreview\/url"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"url"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"url"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" * ","kind":"text"},{"text":"url","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"OVKPersistentItemPreview","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/fragments","value":[{"text":"OVKPersistentItemPreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemPreview~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItemPreview~1url\/fragments","op":"replace","value":[{"text":"url","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}