{"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKCacheContainer(im)cacheSize","modules":[{"name":"OVKit"}],"title":"cacheSize()","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"cacheSize"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheSize"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/cacheSize()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/cachecontainer\/cachesize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/cachecontainer\/cachesize()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer/cacheSize()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"role":"symbol","type":"topic","kind":"symbol","title":"cacheSize()","url":"\/documentation\/ovkit\/cachecontainer\/cachesize()","navigatorTitle":[{"text":"cacheSize","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/cacheSize()"},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","title":"CacheContainer","type":"topic","navigatorTitle":[{"text":"CacheContainer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/cachecontainer","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cacheSize","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheSize"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"identifier","text":"cacheSize"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cacheSize","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1cacheSize()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1cacheSize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cacheSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title","value":"OVKCacheContainer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments","value":[{"text":"OVKCacheContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCacheContainer"}]}]}]}