{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","kind":"typeIdentifier","text":"CacheContainerConfig"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"initWithCustomIdentifier:config:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKCacheContainer(im)initWithCustomIdentifier:config:","title":"init(customIdentifier:config:)","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/cachecontainer\/init(customidentifier:config:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/cachecontainer\/init(customidentifier:config:)"]}],"abstract":[{"text":"Инициализирует экземпляр класса ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","type":"reference","isActive":true},{"text":" с заданным идентификатором. Может возвращать ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", если поддержка контейнеров не включена на уровне SDK или использован некорректный идентификатор.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"customIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","text":"CacheContainerConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"customIdentifier","content":[{"inlineContent":[{"text":"Пользовательский идентификатор кэша. Он не должен быть строкой “permanent” или “temporary” и должен состоять только из строчных и заглавных латинских букв или цифр. Если идентификатор некорректен, объект может не быть создан и метод вернет ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"config","content":[{"inlineContent":[{"type":"text","text":"Объект с настройками поведения кэша."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/init(customIdentifier:config:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer/init(customIdentifier:config:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCustomIdentifier:config:"}],"title":"init(customIdentifier:config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"customIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","kind":"typeIdentifier","text":"CacheContainerConfig"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/cachecontainer\/init(customidentifier:config:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer\/init(customIdentifier:config:)","abstract":[{"text":"Инициализирует экземпляр класса ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer"},{"text":" с заданным идентификатором. Может возвращать ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", если поддержка контейнеров не включена на уровне SDK или использован некорректный идентификатор.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"title":"CacheContainer","navigatorTitle":[{"text":"CacheContainer","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","abstract":[],"url":"\/documentation\/ovkit\/cachecontainer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainer","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CacheContainerConfig":{"title":"CacheContainerConfig","navigatorTitle":[{"text":"CacheContainerConfig","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","abstract":[],"url":"\/documentation\/ovkit\/cachecontainerconfig","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainerConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithCustomIdentifier:config:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomIdentifier:config:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCustomIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"customIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"config:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainerConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainerConfig","text":"OVKCacheContainerConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Пользовательский идентификатор кэша. Он не должен быть строкой “permanent” или “temporary” и должен состоять только из строчных и заглавных латинских букв или цифр. Если идентификатор некорректен, объект может не быть создан и метод вернет ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}],"name":"customIdentifier"},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект с настройками поведения кэша."}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1init(customIdentifier:config:)\/title","value":"initWithCustomIdentifier:config:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer~1init(customIdentifier:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomIdentifier:config:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title","value":"OVKCacheContainer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments","value":[{"text":"OVKCacheContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCacheContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/title","value":"OVKCacheContainerConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/fragments","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainerConfig\/navigatorTitle","value":[{"kind":"identifier","text":"OVKCacheContainerConfig"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}