{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadStrategy\/suspendReason","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit16DownloadStrategyC13suspendReasonAA0b7SuspendE0Ovp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suspendReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DownloadSuspendReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason"}],"title":"suspendReason","role":"symbol"},"abstract":[{"text":"Причина, по которой загрузка не разрешена в данное время.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspendReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DownloadSuspendReason","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Если загрузка разрешена, значением является ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadstrategy\/suspendreason"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadStrategy"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason/none":{"url":"\/documentation\/ovkit\/downloadsuspendreason\/none","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason\/none","navigatorTitle":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"abstract":[{"text":"Загрузка ","type":"text"},{"inlineContent":[{"text":"не","type":"text"}],"type":"emphasis"},{"text":" приостановлена и выполняется.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"DownloadSuspendReason.none","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadStrategy":{"url":"\/documentation\/ovkit\/downloadstrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadStrategy","navigatorTitle":[{"kind":"identifier","text":"DownloadStrategy"}],"abstract":[{"text":"Класс, который наблюдает за внешними условиями и говорит клиенту, когда загрузку видео надо приостанавливать, а когда возобновлять.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadStrategy"}],"title":"DownloadStrategy","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadStrategy/suspendReason":{"abstract":[{"text":"Причина, по которой загрузка не разрешена в данное время.","type":"text"}],"title":"suspendReason","url":"\/documentation\/ovkit\/downloadstrategy\/suspendreason","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspendReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKDownloadSuspendReason","text":"DownloadSuspendReason"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadStrategy\/suspendReason","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadSuspendReason":{"navigatorTitle":[{"text":"DownloadSuspendReason","kind":"identifier"}],"url":"\/documentation\/ovkit\/downloadsuspendreason","title":"DownloadSuspendReason","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadSuspendReason","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Причина, по которой может произойти приостановка загрузок видеозаписей."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DownloadSuspendReason","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKDownloadSuspendReasonNone","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/title"},{"value":[{"text":"OVKDownloadSuspendReasonNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason~1none\/fragments"},{"value":"OVKDownloadSuspendReason","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/title"},{"value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/fragments"},{"value":[{"text":"OVKDownloadSuspendReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadSuspendReason\/navigatorTitle"}]}]}