{"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"title":"maxConcurrentDownloadsCount","externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig(py)maxConcurrentDownloadsCount","roleHeading":"Instance Property","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}]},"abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"По умолчанию имеет значение "},{"type":"codeVoice","code":"1"},{"type":"text","text":", что означает загрузку видео по очереди по одному."}],"type":"paragraph"},{"name":"Warning","type":"aside","style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение не может быть меньше "},{"type":"codeVoice","code":"1"},{"text":". При неверном переданном значении оно будет сброшено на значение по умолчанию.","type":"text"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetcherConfig\/maxConcurrentDownloadsCount"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkprefetcherconfig\/maxconcurrentdownloadscount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkprefetcherconfig\/maxconcurrentdownloadscount"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPrefetcherConfig/maxConcurrentDownloadsCount":{"url":"\/documentation\/ovkit\/ovkprefetcherconfig\/maxconcurrentdownloadscount","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetcherConfig\/maxConcurrentDownloadsCount","title":"maxConcurrentDownloadsCount","abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"url":"\/documentation\/ovkit\/prefetcherconfig","type":"topic","title":"PrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PrefetcherConfig","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"maxConcurrentDownloadsCount","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"maxConcurrentDownloadsCount","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetcherConfig~1maxConcurrentDownloadsCount\/title","op":"replace"},{"value":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetcherConfig~1maxConcurrentDownloadsCount\/fragments"},{"value":"OVKPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title"},{"value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments","op":"replace"}]}]}