{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Единицы измерения – "},{"code":"bps","type":"codeVoice"},{"text":", значение по умолчанию – ","type":"text"},{"type":"codeVoice","code":"1600000"},{"text":".","type":"text"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetcherConfig\/parallelPrefetchBandwidthThreshold","interfaceLanguage":"swift"},"metadata":{"title":"parallelPrefetchBandwidthThreshold","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig(py)parallelPrefetchBandwidthThreshold","navigatorTitle":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"variants":[{"paths":["\/documentation\/ovkit\/ovkprefetcherconfig\/parallelprefetchbandwidththreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkprefetcherconfig\/parallelprefetchbandwidththreshold"]}],"abstract":[{"type":"text","text":"Нижняя граница пропускной способности сети для параллельной работы плеера и префетчера."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPrefetcherConfig/parallelPrefetchBandwidthThreshold":{"url":"\/documentation\/ovkit\/ovkprefetcherconfig\/parallelprefetchbandwidththreshold","navigatorTitle":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPrefetcherConfig\/parallelPrefetchBandwidthThreshold","title":"parallelPrefetchBandwidthThreshold","abstract":[{"type":"text","text":"Нижняя граница пропускной способности сети для параллельной работы плеера и префетчера."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"url":"\/documentation\/ovkit\/prefetcherconfig","type":"topic","title":"PrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PrefetcherConfig","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"parallelPrefetchBandwidthThreshold","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetcherConfig~1parallelPrefetchBandwidthThreshold\/title","op":"replace","value":"parallelPrefetchBandwidthThreshold"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPrefetcherConfig~1parallelPrefetchBandwidthThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"parallelPrefetchBandwidthThreshold"}]},{"value":"OVKPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments","value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}