{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"attributes","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ["},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey","text":"Key"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/oldpricelabel\/attributes(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"attributes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":".","kind":"text"},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"title":"attributes(for:)","externalID":"s:5OVKit13OldPriceLabelC10attributes3forSDySo21NSAttributedStringKeyaypGSgSSSg_tF","symbolKind":"method","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/attributes(for:)","interfaceLanguage":"swift"},"abstract":[{"text":"Шаблонный метод, конструирующий атрибуты для строки ","type":"text"},{"code":"text","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"type":"topic","url":"\/documentation\/ovkit\/oldpricelabel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OldPriceLabel"}],"navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"abstract":[],"title":"OldPriceLabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/attributes(for:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/attributes(for:)","type":"topic","kind":"symbol","abstract":[{"text":"Шаблонный метод, конструирующий атрибуты для строки ","type":"text"},{"type":"codeVoice","code":"text"},{"text":".","type":"text"}],"title":"attributes(for:)","url":"\/documentation\/ovkit\/oldpricelabel\/attributes(for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributes"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"."},{"text":"Key","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAttributedStringKey"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","op":"replace","value":"OldPriceLabel"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","value":[{"kind":"identifier","text":"OldPriceLabel"}]},{"value":[{"kind":"identifier","text":"OldPriceLabel"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}