{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/oldpricelabel\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/initWithFrame:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"]]},"metadata":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"title":"initWithFrame:","externalID":"c:@M@OVKit@objc(cs)OldPriceLabel(im)initWithFrame:","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/initWithFrame:":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/initWithFrame:","title":"initWithFrame:","url":"\/documentation\/ovkit\/oldpricelabel\/initwithframe:","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OldPriceLabel"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OldPriceLabel"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","abstract":[],"url":"\/documentation\/ovkit\/oldpricelabel","title":"OldPriceLabel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OldPriceLabel","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title"},{"op":"replace","value":[{"text":"OldPriceLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments"},{"op":"replace","value":[{"text":"OldPriceLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle"}]}]}