{"sections":[],"metadata":{"title":"ovk_textLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovk_textLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"s:5OVKit13OldPriceLabelC08ovk_textD0So7UILabelCvp","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/oldpricelabel\/ovk_textlabel"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_textLabel","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LabeledView.ovk_textLabel"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovk_textLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"role":"symbol","url":"\/documentation\/ovkit\/oldpricelabel","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"kind":"symbol","title":"OldPriceLabel","navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/ovk_textLabel":{"title":"ovk_textLabel","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/oldpricelabel\/ovk_textlabel","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovk_textLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_textLabel","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","op":"replace","value":"OldPriceLabel"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","op":"replace","value":[{"text":"OldPriceLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OldPriceLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}