{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_text","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovk_text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/oldpricelabel\/ovk_text"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:5OVKit13OldPriceLabelC8ovk_textSSSgvp","modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"ovk_text","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovk_text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"LabeledView.ovk_text","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel/ovk_text":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel\/ovk_text","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ovk_text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"ovk_text","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/oldpricelabel\/ovk_text"},"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"role":"symbol","url":"\/documentation\/ovkit\/oldpricelabel","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"kind":"symbol","title":"OldPriceLabel","navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","value":"OldPriceLabel","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","value":[{"text":"OldPriceLabel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle","value":[{"text":"OldPriceLabel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}