{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSections","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType\/adSections","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/videoadstype\/adsections"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videoadstype\/adsections"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"adSections"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"symbolKind":"property","required":true,"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKVideoAdsType(py)adSections","title":"adSections"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType/adSections":{"title":"adSections","navigatorTitle":[{"text":"adSections","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSections","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType\/adSections","abstract":[],"url":"\/documentation\/ovkit\/videoadstype\/adsections","required":true,"kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"title":"VideoAdsType","url":"\/documentation\/ovkit\/videoadstype","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAdsType"}],"navigatorTitle":[{"text":"VideoAdsType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Данные для показа instream рекламы."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"adSections"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"adSections"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"adSections","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType~1adSections\/title","op":"replace","value":"adSections"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType~1adSections\/fragments","op":"replace","value":[{"kind":"identifier","text":"adSections"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title","op":"replace","value":"OVKVideoAdsType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoAdsType"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoAdsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}