{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType\/params","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/videoadstype\/params"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videoadstype\/params"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoAdsType(py)params","modules":[{"name":"OVKit"}],"title":"params","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"params","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"params","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoAdsType"}],"title":"VideoAdsType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoAdsType"}],"url":"\/documentation\/ovkit\/videoadstype","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType/params":{"role":"symbol","required":true,"title":"params","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"params","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"params"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType\/params","url":"\/documentation\/ovkit\/videoadstype\/params"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"params","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"params","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"params","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoAdsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments","value":[{"kind":"identifier","text":"OVKVideoAdsType"}],"op":"replace"},{"value":"params","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType~1params\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType~1params\/fragments","op":"replace","value":[{"kind":"identifier","text":"params"}]}]}]}