{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapSupplementaryAdControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SupplementaryAdView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementaryAdView"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Экземпляр ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","isActive":true,"type":"reference"},{"text":", на котором произошло нажатие.","type":"text"}]}],"name":"view"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate\/didTapSupplementaryAdControlsView(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"required":true,"role":"symbol","title":"didTapSupplementaryAdControlsView(_:)","externalID":"s:5OVKit27SupplementaryAdViewDelegateP06didTapbc8ControlsD0yyAA0bcD0CF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapSupplementaryAdControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementaryAdView","text":"SupplementaryAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementaryadviewdelegate\/didtapsupplementaryadcontrolsview(_:)"]}],"abstract":[{"type":"text","text":"Вызывается при нажатии на контролы рекламного представления."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewDelegate":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SupplementaryAdViewDelegate","kind":"identifier"}],"abstract":[{"text":"Протокол делегата для ","type":"text"},{"type":"codeVoice","code":"SupplementaryAdView"},{"text":".","type":"text"}],"type":"topic","title":"SupplementaryAdViewDelegate","url":"\/documentation\/ovkit\/supplementaryadviewdelegate","role":"symbol","navigatorTitle":[{"text":"SupplementaryAdViewDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdView":{"navigatorTitle":[{"text":"SupplementaryAdView","kind":"identifier"}],"abstract":[{"text":"Представление для CTA-контрола рекламы.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdView","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupplementaryAdView","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementaryadview","title":"SupplementaryAdView"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryAdViewDelegate/didTapSupplementaryAdControlsView(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryAdViewDelegate\/didTapSupplementaryAdControlsView(_:)","url":"\/documentation\/ovkit\/supplementaryadviewdelegate\/didtapsupplementaryadcontrolsview(_:)","required":true,"kind":"symbol","title":"didTapSupplementaryAdControlsView(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didTapSupplementaryAdControlsView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SupplementaryAdView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSupplementaryAdView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Вызывается при нажатии на контролы рекламного представления.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/title","value":"OVKSupplementaryAdView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryAdView\/navigatorTitle","value":[{"text":"OVKSupplementaryAdView","kind":"identifier"}]}]}]}