{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"]]},"metadata":{"title":"visualStyle","required":true,"navigatorTitle":[{"kind":"identifier","text":"visualStyle"}],"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol(py)visualStyle","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visualStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenViewControllerProtocol\/visualStyle","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/visualstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/visualstyle"]}],"abstract":[{"type":"text","text":"Стиль отображения для "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" внутри контроллера","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","title":"FullscreenViewControllerProtocol","navigatorTitle":[{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenViewControllerProtocol/visualStyle":{"title":"visualStyle","kind":"symbol","required":true,"navigatorTitle":[{"text":"visualStyle","kind":"identifier"}],"abstract":[{"text":"Стиль отображения для ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" внутри контроллера"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenViewControllerProtocol\/visualStyle","url":"\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/visualstyle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visualStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","kind":"typeIdentifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"title":"FullscreenViewControllerVisualStyle","kind":"symbol","navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","abstract":[],"url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"visualStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"visualStyle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","value":"OVKFullscreenViewControllerProtocol","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title"},{"value":[{"text":"OVKFullscreenViewControllerProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenViewControllerProtocol~1visualStyle\/title","value":"visualStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenViewControllerProtocol~1visualStyle\/fragments","value":[{"text":"visualStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","value":"FullscreenViewControllerVisualStyle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}