{"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/wrapped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/wrapped"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"title":"wrapped","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol(py)wrapped","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrapped"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"wrapped"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wrapped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"]]},"abstract":[{"type":"text","text":"Контроллер, который необходимо обернуть."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenViewControllerProtocol\/wrapped"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","title":"FullscreenViewControllerProtocol","navigatorTitle":[{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController":{"navigatorTitle":[{"text":"FullscreenContentViewController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Реализация полноэкранного контроллера, которая содержит плеер и дополнительные элементы интерфейса."}],"title":"FullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenContentViewController"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenViewControllerProtocol/wrapped":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenViewControllerProtocol\/wrapped","url":"\/documentation\/ovkit\/ovkfullscreenviewcontrollerprotocol\/wrapped","required":true,"title":"wrapped","navigatorTitle":[{"kind":"identifier","text":"wrapped"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Контроллер, который необходимо обернуть.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","text":"FullscreenContentViewController","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"wrapped"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"wrapped"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OVKFullscreenContentViewController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title","value":"OVKFullscreenViewControllerProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}]},{"value":"OVKFullscreenContentViewController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController\/fragments","value":[{"text":"OVKFullscreenContentViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenViewControllerProtocol~1wrapped\/title","value":"wrapped","op":"replace"},{"op":"replace","value":[{"text":"wrapped","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenViewControllerProtocol~1wrapped\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}