{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@OVKit@objc(cs)OVKRestrictionManager(im)init","title":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkrestrictionmanager\/init"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager":{"navigatorTitle":[{"text":"RestrictionManager","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","url":"\/documentation\/ovkit\/restrictionmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionManager","kind":"identifier"}],"kind":"symbol","title":"RestrictionManager","role":"symbol","abstract":[],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKRestrictionManager/init":{"title":"init","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkrestrictionmanager\/init","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/title","value":"OVKRestrictionManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/fragments","value":[{"kind":"identifier","text":"OVKRestrictionManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/navigatorTitle","value":[{"text":"OVKRestrictionManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}