{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/shared","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","text":"RestrictionManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager"]]},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shared"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RestrictionManager","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","kind":"typeIdentifier"}],"title":"shared","externalID":"c:@M@OVKit@objc(cs)OVKRestrictionManager(cpy)shared"},"variants":[{"paths":["\/documentation\/ovkit\/ovkrestrictionmanager\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkrestrictionmanager\/shared"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/RestrictionManager":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RestrictionManager","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/restrictionmanager","title":"RestrictionManager","navigatorTitle":[{"kind":"identifier","text":"RestrictionManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKRestrictionManager/shared":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKRestrictionManager\/shared","url":"\/documentation\/ovkit\/ovkrestrictionmanager\/shared","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","kind":"typeIdentifier","text":"RestrictionManager"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[],"title":"shared","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"shared","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"shared","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/RestrictionManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKRestrictionManager","text":"OVKRestrictionManager"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/title","value":"OVKRestrictionManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1RestrictionManager\/fragments","value":[{"kind":"identifier","text":"OVKRestrictionManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKRestrictionManager~1shared\/title","op":"replace","value":"shared"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKRestrictionManager~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}],"op":"replace"}]}]}