{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videocategory\/clip"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videocategory\/clip"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/clip","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Клип – короткое видео."}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"VideoCategory.clip","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKVideoCategoryClip","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKVideoCategory@OVKVideoCategoryClip"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCategory"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"title":"VideoCategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","url":"\/documentation\/ovkit\/videocategory","abstract":[{"type":"text","text":"Тип видеозаписи."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/clip":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/clip","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"}],"title":"VideoCategory.clip","url":"\/documentation\/ovkit\/videocategory\/clip","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Клип – короткое видео."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryClip"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"OVKVideoCategoryClip","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategoryClip"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKVideoCategoryClip"}],"platforms":["iOS"]}]}},{"op":"replace","value":"OVKVideoCategory","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoCategory"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoCategory"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/navigatorTitle"},{"op":"replace","value":"OVKVideoCategoryClip","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1clip\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoCategoryClip"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1clip\/fragments"}]}]}