{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"music"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videocategory\/music"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videocategory\/music"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@OVKit@E@OVKVideoCategory@OVKVideoCategoryMusic","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"music"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryMusic"}],"title":"VideoCategory.music","modules":[{"name":"OVKit"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/music","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCategory"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","type":"topic","role":"symbol","title":"VideoCategory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"url":"\/documentation\/ovkit\/videocategory"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/music":{"navigatorTitle":[{"text":"OVKVideoCategoryMusic","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/music","abstract":[],"role":"symbol","kind":"symbol","title":"VideoCategory.music","url":"\/documentation\/ovkit\/videocategory\/music","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"music","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKVideoCategoryMusic","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategoryMusic"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKVideoCategoryMusic","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title","value":"OVKVideoCategory","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments","value":[{"text":"OVKVideoCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/navigatorTitle","value":[{"text":"OVKVideoCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1music\/title","value":"OVKVideoCategoryMusic","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1music\/fragments","value":[{"text":"OVKVideoCategoryMusic","kind":"identifier"}],"op":"replace"}]}]}