{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"story"}],"modules":[{"name":"OVKit"}],"title":"VideoCategory.story","role":"symbol","externalID":"c:@M@OVKit@E@OVKVideoCategory@OVKVideoCategoryStory","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryStory"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"story","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/story","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/videocategory\/story"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videocategory\/story"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Видео-история.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/story":{"title":"VideoCategory.story","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/story","navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryStory"}],"type":"topic","abstract":[{"type":"text","text":"Видео-история."}],"kind":"symbol","url":"\/documentation\/ovkit\/videocategory\/story","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"story"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"abstract":[{"type":"text","text":"Тип видеозаписи."}],"kind":"symbol","url":"\/documentation\/ovkit\/videocategory","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCategory"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoCategory"}],"type":"topic","title":"VideoCategory","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKVideoCategoryStory","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKVideoCategoryStory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKVideoCategoryStory"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoCategoryStory","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1story\/title"},{"value":[{"text":"OVKVideoCategoryStory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1story\/fragments"},{"value":"OVKVideoCategory","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title"},{"value":[{"kind":"identifier","text":"OVKVideoCategory"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments"},{"value":[{"kind":"identifier","text":"OVKVideoCategory"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}