{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/video"},"variants":[{"paths":["\/documentation\/ovkit\/videocategory\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/videocategory\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}],"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKVideoCategory@OVKVideoCategoryVideo","title":"VideoCategory.video","roleHeading":"Case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoCategory":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"VideoCategory","kind":"identifier"}],"navigatorTitle":[{"text":"VideoCategory","kind":"identifier"}],"type":"topic","title":"VideoCategory","url":"\/documentation\/ovkit\/videocategory","kind":"symbol","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoCategory/video":{"navigatorTitle":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoCategory\/video","url":"\/documentation\/ovkit\/videocategory\/video","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"video","kind":"identifier"}],"title":"VideoCategory.video"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKVideoCategoryVideo"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/title","value":"OVKVideoCategory"},{"op":"replace","value":[{"text":"OVKVideoCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1video\/title","value":"OVKVideoCategoryVideo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoCategory~1video\/fragments","value":[{"kind":"identifier","text":"OVKVideoCategoryVideo"}],"op":"replace"}]}]}