{"variants":[{"paths":["\/documentation\/ovkit\/upcominglivetimecontainer\/init(deltatime:smalllayout:color:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"title":"init(deltaTime:smallLayout:color:)","externalID":"s:5OVKit25UpcomingLiveTimeContainerC05deltaD011smallLayout5colorACSd_SbSo7UIColorCtcfc","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"deltaTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smallLayout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/init(deltaTime:smallLayout:color:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deltaTime"},{"kind":"text","text":": "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"smallLayout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer":{"url":"\/documentation\/ovkit\/upcominglivetimecontainer","navigatorTitle":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"type":"topic","title":"UpcomingLiveTimeContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UpcomingLiveTimeContainer"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer/init(deltaTime:smallLayout:color:)":{"url":"\/documentation\/ovkit\/upcominglivetimecontainer\/init(deltatime:smalllayout:color:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deltaTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"smallLayout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init(deltaTime:smallLayout:color:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/init(deltaTime:smallLayout:color:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"UpcomingLiveTimeContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/fragments","value":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/navigatorTitle","value":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}