{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/smallLayout","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smallLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcominglivetimecontainer\/smalllayout"]}],"sections":[],"metadata":{"role":"symbol","title":"smallLayout","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smallLayout"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:5OVKit25UpcomingLiveTimeContainerC11smallLayoutSbvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer/smallLayout":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smallLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/smallLayout","title":"smallLayout","role":"symbol","url":"\/documentation\/ovkit\/upcominglivetimecontainer\/smalllayout"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer":{"url":"\/documentation\/ovkit\/upcominglivetimecontainer","navigatorTitle":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"type":"topic","title":"UpcomingLiveTimeContainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UpcomingLiveTimeContainer"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UpcomingLiveTimeContainer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/title"},{"value":[{"kind":"identifier","text":"UpcomingLiveTimeContainer"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/navigatorTitle","value":[{"kind":"identifier","text":"UpcomingLiveTimeContainer"}]}]}]}