{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/updateDeltaTime(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDeltaTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"time"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer"]]},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDeltaTime"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":")","kind":"text"}],"externalID":"s:5OVKit25UpcomingLiveTimeContainerC011updateDeltaD0yySdF","title":"updateDeltaTime(_:)","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/upcominglivetimecontainer\/updatedeltatime(_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer/updateDeltaTime(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateDeltaTime","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer\/updateDeltaTime(_:)","url":"\/documentation\/ovkit\/upcominglivetimecontainer\/updatedeltatime(_:)","type":"topic","kind":"symbol","title":"updateDeltaTime(_:)","role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/UpcomingLiveTimeContainer":{"url":"\/documentation\/ovkit\/upcominglivetimecontainer","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"title":"UpcomingLiveTimeContainer","navigatorTitle":[{"text":"UpcomingLiveTimeContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/UpcomingLiveTimeContainer"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/title","value":"UpcomingLiveTimeContainer"},{"value":[{"kind":"identifier","text":"UpcomingLiveTimeContainer"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UpcomingLiveTimeContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1UpcomingLiveTimeContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}