{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView"]]},"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"gravity","role":"symbol","symbolKind":"property","externalID":"s:5OVKit19ThumbnailTeaserViewC7gravityAA06PlayerD7GravityOvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/gravity","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/gravity"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/gravity":{"abstract":[],"url":"\/documentation\/ovkit\/thumbnailteaserview\/gravity","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/gravity","title":"gravity","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","kind":"typeIdentifier","text":"PlayerViewGravity"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailTeaserView"}],"navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"title":"ThumbnailTeaserView","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"symbol","title":"PlayerViewGravity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewGravity"}],"abstract":[],"url":"\/documentation\/ovkit\/playerviewgravity","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerViewGravity"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"ThumbnailTeaserView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","op":"replace"},{"value":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","op":"replace"},{"value":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","op":"replace"},{"value":"OVKPlayerViewGravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title","op":"replace"},{"value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}