{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:roundStyle:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider"},{"text":", ","kind":"text"},{"text":"roundStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit19ThumbnailTeaserViewC10RoundStyleO","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/RoundStyle","kind":"typeIdentifier","text":"RoundStyle"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/init(thumbnailprovider:roundstyle:)"]}],"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":", ","kind":"text"},{"text":"roundStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RoundStyle","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit19ThumbnailTeaserViewC10RoundStyleO"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(thumbnailProvider:roundStyle:)","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","externalID":"s:5OVKit19ThumbnailTeaserViewC17thumbnailProvider10roundStyleAcA0bF0C_AC05RoundH0Otcfc"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"url":"\/documentation\/ovkit\/thumbnailprovider","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"title":"ThumbnailProvider","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/RoundStyle":{"abstract":[],"url":"\/documentation\/ovkit\/thumbnailteaserview\/roundstyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundStyle"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/RoundStyle","title":"ThumbnailTeaserView.RoundStyle","navigatorTitle":[{"kind":"identifier","text":"RoundStyle"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/init(thumbnailProvider:roundStyle:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:roundStyle:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"roundStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit19ThumbnailTeaserViewC10RoundStyleO","text":"RoundStyle"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/init(thumbnailprovider:roundstyle:)","abstract":[],"title":"init(thumbnailProvider:roundStyle:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"title":"ThumbnailTeaserView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","type":"topic","navigatorTitle":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview"}},"variantOverrides":[{"patch":[{"value":"OVKThumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","op":"replace"},{"value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","op":"replace"},{"value":"ThumbnailTeaserView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","op":"replace","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}