{"variants":[{"paths":["\/documentation\/ovkit\/thumbnailteaserview\/init(thumbnailprovider:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":")","kind":"text"}],"title":"init(thumbnailProvider:)","roleHeading":"Initializer","externalID":"s:5OVKit19ThumbnailTeaserViewC17thumbnailProviderAcA0bF0C_tcfc","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"navigatorTitle":[{"kind":"identifier","text":"ThumbnailProvider"}],"title":"ThumbnailProvider","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"type":"topic","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailprovider"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/init(thumbnailProvider:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider"},{"kind":"text","text":")"}],"title":"init(thumbnailProvider:)","url":"\/documentation\/ovkit\/thumbnailteaserview\/init(thumbnailprovider:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/init(thumbnailProvider:)"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","navigatorTitle":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"abstract":[],"title":"ThumbnailTeaserView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}