{"metadata":{"modules":[{"name":"OVKit"}],"title":"ThumbnailTeaserView.State","symbolKind":"enum","externalID":"s:5OVKit19ThumbnailTeaserViewC5StateO","roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"State","kind":"identifier"}],"navigatorTitle":[{"text":"State","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/state"]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/error","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/image(_:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/loading"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"title":"ThumbnailTeaserView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","type":"topic","navigatorTitle":[{"text":"ThumbnailTeaserView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/loading":{"role":"symbol","abstract":[],"title":"ThumbnailTeaserView.State.loading","type":"topic","url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/loading","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/loading","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State":{"role":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview\/state","title":"ThumbnailTeaserView.State","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State","navigatorTitle":[{"kind":"identifier","text":"State"}],"abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/image(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ThumbnailProviderThumbnail","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProviderThumbnail"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/image(_:)","title":"ThumbnailTeaserView.State.image(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/image(_:)","kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/State/error":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"url":"\/documentation\/ovkit\/thumbnailteaserview\/state\/error","title":"ThumbnailTeaserView.State.error","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/State\/error","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"kind":"identifier","text":"ThumbnailTeaserView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}