{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/updateCurrentTime(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"time","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/thumbnailteaserview\/updatecurrenttime(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"title":"updateCurrentTime(_:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:5OVKit19ThumbnailTeaserViewC17updateCurrentTimeyySdF","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView/updateCurrentTime(_:)":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView\/updateCurrentTime(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"updateCurrentTime(_:)","role":"symbol","url":"\/documentation\/ovkit\/thumbnailteaserview\/updatecurrenttime(_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailTeaserView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailTeaserView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailTeaserView","kind":"symbol","abstract":[],"type":"topic","title":"ThumbnailTeaserView","url":"\/documentation\/ovkit\/thumbnailteaserview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThumbnailTeaserView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/title","value":"ThumbnailTeaserView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/fragments","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailTeaserView\/navigatorTitle","value":[{"text":"ThumbnailTeaserView","kind":"identifier"}]}]}]}