{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/actionButton","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","text":"VideoRestrictionButtonType"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)actionButton","symbolKind":"property","title":"actionButton","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"text":": ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"actionButton"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestrictiontype\/actionbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestrictiontype\/actionbutton"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"url":"\/documentation\/ovkit\/videorestrictiontype","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","title":"VideoRestrictionType","navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestrictionType"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButtonType":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButtonType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButtonType","kind":"symbol","url":"\/documentation\/ovkit\/videorestrictionbuttontype","title":"VideoRestrictionButtonType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionButtonType"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/actionButton":{"title":"actionButton","role":"symbol","navigatorTitle":[{"text":"actionButton","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/actionButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionButton","kind":"identifier"},{"kind":"text","text":": "},{"text":"VideoRestrictionButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoRestrictionButtonType"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/videorestrictiontype\/actionbutton","kind":"symbol","abstract":[],"required":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"actionButton","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"actionButton","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<OVKVideoRestrictionButtonType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoRestrictionButtonType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionButton"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","value":"OVKVideoRestrictionType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}]},{"op":"replace","value":"OVKVideoRestrictionButtonType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionButtonType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButtonType\/navigatorTitle","value":[{"text":"OVKVideoRestrictionButtonType","kind":"identifier"}]},{"value":"actionButton","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1actionButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1actionButton\/fragments","value":[{"text":"actionButton","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}