{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videorestrictiontype\/cardicon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videorestrictiontype\/cardicon"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/cardIcon","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Не используется, рекомендуется устанавливать "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/listIcon"},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","name":"Important","style":"important"}]}],"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKVideoRestrictionType(py)cardIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIcon"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType"},{"kind":"text","text":"]"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"cardIcon","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"cardIcon"}]},"abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/cardIcon":{"required":true,"abstract":[{"text":"Изображение для показа на баннере.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/cardIcon","title":"cardIcon","url":"\/documentation\/ovkit\/videorestrictiontype\/cardicon","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","text":"ImageAssetType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"cardIcon","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType":{"kind":"symbol","abstract":[{"text":"Модель баннера, запрещающего просмотр.","type":"text"}],"url":"\/documentation\/ovkit\/videorestrictiontype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRestrictionType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoRestrictionType"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType","title":"VideoRestrictionType"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType","title":"ImageAssetType","type":"topic","url":"\/documentation\/ovkit\/imageassettype","abstract":[{"type":"text","text":"Ассет изображения."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionType/listIcon":{"required":true,"url":"\/documentation\/ovkit\/videorestrictiontype\/listicon","title":"listIcon","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionType\/listIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listIcon"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKImageAssetType","kind":"typeIdentifier","text":"ImageAssetType"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Изображение для показа на баннере."}],"navigatorTitle":[{"text":"listIcon","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cardIcon","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"cardIcon","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<OVKImageAssetType>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cardIcon","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cardIcon","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1cardIcon\/title","op":"replace"},{"value":[{"text":"cardIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1cardIcon\/fragments","op":"replace"},{"value":"OVKVideoRestrictionType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoRestrictionType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType\/navigatorTitle","value":[{"text":"OVKVideoRestrictionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"text":"OVKImageAssetType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKImageAssetType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1listIcon\/title","value":"listIcon","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionType~1listIcon\/fragments","value":[{"text":"listIcon","kind":"identifier"}],"op":"replace"}]}]}