{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/failed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livestatus\/failed"]},{"paths":["\/documentation\/ovkit\/livestatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","title":"LiveStatus.failed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusFailed"}],"externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusFailed","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"symbolKind":"case"},"abstract":[{"text":"Ошибка стриминга.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/failed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Ошибка стриминга.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"OVKLiveStatusFailed","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/failed","title":"LiveStatus.failed","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/failed"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"type":"topic","url":"\/documentation\/ovkit\/livestatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","abstract":[],"title":"LiveStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LiveStatus","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKLiveStatusFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusFailed"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusFailed"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1failed\/title","value":"OVKLiveStatusFailed","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1failed\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusFailed"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","op":"replace","value":"OVKLiveStatus"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatus"}]},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}