{"variants":[{"paths":["\/documentation\/ovkit\/livestatus\/finished"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/livestatus\/finished"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/finished","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Live завершен стримером. Трансляция ушла в нарезку, длительность видео и ссылки на запись не доступны."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusFinished"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusFinished","title":"LiveStatus.finished","role":"symbol","modules":[{"name":"OVKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"title":"LiveStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LiveStatus"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/livestatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/finished":{"title":"LiveStatus.finished","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/finished","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finished","kind":"identifier"}],"navigatorTitle":[{"text":"OVKLiveStatusFinished","kind":"identifier"}],"abstract":[{"text":"Live завершен стримером. Трансляция ушла в нарезку, длительность видео и ссылки на запись не доступны.","type":"text"}],"url":"\/documentation\/ovkit\/livestatus\/finished"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKLiveStatusFinished","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKLiveStatusFinished","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusFinished"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"op":"replace","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1finished\/title","value":"OVKLiveStatusFinished"},{"value":[{"text":"OVKLiveStatusFinished","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1finished\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}