{"variants":[{"paths":["\/documentation\/ovkit\/livestatus\/postlive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/livestatus\/postlive"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postlive"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/postlive","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"OVKLiveStatusPostlive","kind":"identifier"}],"title":"LiveStatus.postlive","symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusPostlive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postlive","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Live завершился и стал записью трансляции, доступны длительность и ссылки на запись."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/postlive":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postlive","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/postlive","title":"LiveStatus.postlive","kind":"symbol","url":"\/documentation\/ovkit\/livestatus\/postlive","navigatorTitle":[{"text":"OVKLiveStatusPostlive","kind":"identifier"}],"abstract":[{"type":"text","text":"Live завершился и стал записью трансляции, доступны длительность и ссылки на запись."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"abstract":[],"url":"\/documentation\/ovkit\/livestatus","kind":"symbol","title":"LiveStatus","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"OVKLiveStatusPostlive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusPostlive"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusPostlive"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1postlive\/title","op":"replace","value":"OVKLiveStatusPostlive"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1postlive\/fragments","op":"replace","value":[{"text":"OVKLiveStatusPostlive","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","op":"replace","value":"OVKLiveStatus"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","op":"replace","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatus"}]}]}]}