{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Type Alias","symbolKind":"typealias","role":"symbol","navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"s:5OVKit10LiveStatusO8RawValuea","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"}],"title":"LiveStatus.RawValue"},"variants":[{"paths":["\/documentation\/ovkit\/livestatus\/rawvalue-swift.typealias"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawValue-swift.typealias","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.RawValue"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawValue","kind":"identifier"},{"text":" = ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/RawValue-swift.typealias":{"navigatorTitle":[{"text":"RawValue","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/rawvalue-swift.typealias","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/RawValue-swift.typealias","type":"topic","title":"LiveStatus.RawValue","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawValue"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"title":"LiveStatus","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveStatus"}],"abstract":[{"type":"text","text":"Статус прямой трансляции."}],"navigatorTitle":[{"kind":"identifier","text":"LiveStatus"}],"url":"\/documentation\/ovkit\/livestatus"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKLiveStatus","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle"}]}]}