{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"role":"symbol","title":"LiveStatus.started","externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusStarted","navigatorTitle":[{"text":"OVKLiveStatusStarted","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livestatus\/started"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/livestatus\/started"]}],"abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"started","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LiveStatus","kind":"identifier"}],"navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","abstract":[],"url":"\/documentation\/ovkit\/livestatus","title":"LiveStatus","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusStarted"}],"kind":"symbol","abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}],"role":"symbol","url":"\/documentation\/ovkit\/livestatus\/started","title":"LiveStatus.started"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKLiveStatusStarted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKLiveStatusStarted","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusStarted"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title","value":"OVKLiveStatusStarted"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments","value":[{"text":"OVKLiveStatusStarted","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}