{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livestatus\/unknown"]},{"paths":["\/documentation\/ovkit\/livestatus\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"Статус не определен или видео не является \/ не было трансляцией.","type":"text"}],"sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"OVKLiveStatusUnknown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusUnknown","title":"LiveStatus.unknown","role":"symbol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/unknown":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/unknown","title":"LiveStatus.unknown","abstract":[{"type":"text","text":"Статус не определен или видео не является \/ не было трансляцией."}],"kind":"symbol","navigatorTitle":[{"text":"OVKLiveStatusUnknown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/unknown","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"title":"LiveStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LiveStatus"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/livestatus","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"OVKLiveStatusUnknown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKLiveStatusUnknown"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusUnknown"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1unknown\/title","value":"OVKLiveStatusUnknown"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1unknown\/fragments","value":[{"text":"OVKLiveStatusUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus","op":"replace"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"text":"OVKLiveStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}