{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upcoming"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать."}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/livestatus\/upcoming"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/livestatus\/upcoming"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"metadata":{"externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusUpcoming","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upcoming","kind":"identifier"}],"title":"LiveStatus.upcoming","symbolKind":"case","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"abstract":[],"url":"\/documentation\/ovkit\/livestatus","kind":"symbol","title":"LiveStatus","navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveStatus","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/upcoming":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upcoming","kind":"identifier"}],"url":"\/documentation\/ovkit\/livestatus\/upcoming","title":"LiveStatus.upcoming","type":"topic","navigatorTitle":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"abstract":[{"text":"Live объявлен, но видеопотока еще нет, ссылки на трансляцию не использовать.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/upcoming"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKLiveStatusUpcoming","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKLiveStatusUpcoming","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"text":"OVKLiveStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/title","value":"OVKLiveStatusUpcoming","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1upcoming\/fragments","value":[{"kind":"identifier","text":"OVKLiveStatusUpcoming"}],"op":"replace"}]}]}