{"abstract":[{"text":"Стример не завершил Live, но по каким-то причинам нет видеопотока.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/livestatus\/waiting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/livestatus\/waiting"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/waiting"},"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"OVKLiveStatusWaiting","kind":"identifier"}],"title":"LiveStatus.waiting","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKLiveStatus@OVKLiveStatusWaiting","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LiveStatus","kind":"identifier"}],"navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","abstract":[],"url":"\/documentation\/ovkit\/livestatus","title":"LiveStatus","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/waiting":{"url":"\/documentation\/ovkit\/livestatus\/waiting","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/waiting","kind":"symbol","abstract":[{"text":"Стример не завершил Live, но по каким-то причинам нет видеопотока.","type":"text"}],"title":"LiveStatus.waiting","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"}],"navigatorTitle":[{"text":"OVKLiveStatusWaiting","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKLiveStatusWaiting","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLiveStatusWaiting"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKLiveStatusWaiting"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKLiveStatus","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","op":"replace"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","op":"replace"},{"value":[{"text":"OVKLiveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","op":"replace"},{"value":"OVKLiveStatusWaiting","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1waiting\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLiveStatusWaiting"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1waiting\/fragments","op":"replace"}]}]}