{"metadata":{"externalID":"c:@M@OVKit@E@OVKPreviewPlayButtonMode@OVKPreviewPlayButtonModeActive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"}],"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeActive"}],"title":"PreviewPlayButtonMode.active","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/active"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/active"]}],"abstract":[{"type":"text","text":"Кнопка видна и при ее нажатии плеер начинает проигрывание."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"url":"\/documentation\/ovkit\/previewplaybuttonmode","abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}],"type":"topic","title":"PreviewPlayButtonMode","navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/active":{"type":"topic","kind":"symbol","title":"PreviewPlayButtonMode.active","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/active","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"navigatorTitle":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/active","abstract":[{"type":"text","text":"Кнопка видна и при ее нажатии плеер начинает проигрывание."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKPreviewPlayButtonModeActive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeActive"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","value":"OVKPreviewPlayButtonMode","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/title","value":"OVKPreviewPlayButtonModeActive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1active\/fragments","value":[{"text":"OVKPreviewPlayButtonModeActive","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}