{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"symbol","role":"symbol","title":"PreviewPlayButtonMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode","abstract":[{"type":"text","text":"Режим работы кнопки "},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/!=(_:_:)":{"url":"\/documentation\/ovkit\/previewplaybuttonmode\/!=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonMode"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle"}]}]}