{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/hidden"]},{"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/hidden"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidden"}],"symbolKind":"case","navigatorTitle":[{"text":"OVKPreviewPlayButtonModeHidden","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"PreviewPlayButtonMode.hidden","externalID":"c:@M@OVKit@E@OVKPreviewPlayButtonMode@OVKPreviewPlayButtonModeHidden","roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hidden","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Кнопка скрыта."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/hidden":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidden"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/hidden","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hidden","abstract":[{"type":"text","text":"Кнопка скрыта."}],"kind":"symbol","title":"PreviewPlayButtonMode.hidden","navigatorTitle":[{"text":"OVKPreviewPlayButtonModeHidden","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"url":"\/documentation\/ovkit\/previewplaybuttonmode","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PreviewPlayButtonMode","kind":"identifier"}],"title":"PreviewPlayButtonMode","abstract":[{"type":"text","text":"Режим работы кнопки "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Play"}]},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKPreviewPlayButtonModeHidden","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeHidden"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKPreviewPlayButtonModeHidden","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"OVKPreviewPlayButtonModeHidden","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1hidden\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode~1hidden\/fragments","value":[{"kind":"identifier","text":"OVKPreviewPlayButtonModeHidden"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","value":"OVKPreviewPlayButtonMode","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}