{"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hashValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hash(into:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/RawRepresentable-Implementations"},"metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"OVKit"}],"roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/previewplaybuttonmode\/rawrepresentable-implementations"]}],"kind":"article","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/hash(into:)":{"kind":"symbol","title":"hash(into:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hash(into:)","abstract":[],"url":"\/documentation\/ovkit\/previewplaybuttonmode\/hash(into:)","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode":{"abstract":[{"text":"Режим работы кнопки ","type":"text"},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"type":"topic","title":"PreviewPlayButtonMode","url":"\/documentation\/ovkit\/previewplaybuttonmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonMode"}],"navigatorTitle":[{"kind":"identifier","text":"PreviewPlayButtonMode"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonMode/hashValue":{"kind":"symbol","title":"hashValue","type":"topic","url":"\/documentation\/ovkit\/previewplaybuttonmode\/hashvalue","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonMode\/hashValue","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKPreviewPlayButtonMode","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/title","op":"replace"},{"value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/fragments","op":"replace"},{"value":[{"text":"OVKPreviewPlayButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonMode\/navigatorTitle","op":"replace"}]}]}