{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/broadcastProviders","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/broadcastmanager\/broadcastproviders"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BroadcastServiceProvider","preciseIdentifier":"s:5OVKit24BroadcastServiceProviderP"},{"kind":"text","text":"]"}],"title":"broadcastProviders","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:5OVKit16BroadcastManagerC18broadcastProvidersSayAA0B15ServiceProvider_pGvp"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BroadcastServiceProvider","preciseIdentifier":"s:5OVKit24BroadcastServiceProviderP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastServiceProvider"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/broadcastProviders":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"broadcastProviders","kind":"identifier"},{"text":": [","kind":"text"},{"text":"BroadcastServiceProvider","preciseIdentifier":"s:5OVKit24BroadcastServiceProviderP","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/broadcastProviders","title":"broadcastProviders","type":"topic","url":"\/documentation\/ovkit\/broadcastmanager\/broadcastproviders","abstract":[],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BroadcastManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/broadcastmanager","title":"BroadcastManager","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BroadcastManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/BroadcastServiceProvider":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastServiceProvider"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastServiceProvider","abstract":[{"text":"Отвечает за поиск устройств в сети и предоставление их списка.","type":"text"}],"type":"topic","title":"BroadcastServiceProvider","url":"\/documentation\/ovkit\/broadcastserviceprovider","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BroadcastServiceProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"kind":"identifier","text":"OVKBroadcastManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKBroadcastManager"}],"op":"replace"}]}]}