{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectToDiscoveredDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"device"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit15BroadcastDeviceP","kind":"typeIdentifier","text":"BroadcastDevice","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastDevice"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAirPlay"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/connectToDiscoveredDevice(_:isAirPlay:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:5OVKit16BroadcastManagerC25connectToDiscoveredDevice_9isAirPlayyAA0bG0_p_SbtF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectToDiscoveredDevice"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:5OVKit15BroadcastDeviceP","text":"BroadcastDevice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAirPlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"connectToDiscoveredDevice(_:isAirPlay:)","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/broadcastmanager\/connecttodiscovereddevice(_:isairplay:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"title":"BroadcastManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","navigatorTitle":[{"text":"BroadcastManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"kind":"symbol","url":"\/documentation\/ovkit\/broadcastmanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BroadcastManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/connectToDiscoveredDevice(_:isAirPlay:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/connectToDiscoveredDevice(_:isAirPlay:)","type":"topic","title":"connectToDiscoveredDevice(_:isAirPlay:)","url":"\/documentation\/ovkit\/broadcastmanager\/connecttodiscovereddevice(_:isairplay:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectToDiscoveredDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BroadcastDevice","preciseIdentifier":"s:5OVKit15BroadcastDeviceP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAirPlay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/BroadcastDevice":{"abstract":[{"text":"Устройство, на которое может производиться стриминг видео.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BroadcastDevice","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastDevice","url":"\/documentation\/ovkit\/broadcastdevice","title":"BroadcastDevice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BroadcastDevice"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle"}]}]}