{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BroadcastDevice","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastDevice","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit15BroadcastDeviceP"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentDevice"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit15BroadcastDeviceP","kind":"typeIdentifier","text":"BroadcastDevice"},{"kind":"text","text":"?"}],"role":"symbol","title":"currentDevice","externalID":"s:5OVKit16BroadcastManagerC13currentDeviceAA0bE0_pSgvp","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/currentDevice","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/broadcastmanager\/currentdevice"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/currentDevice":{"url":"\/documentation\/ovkit\/broadcastmanager\/currentdevice","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/currentDevice","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BroadcastDevice","preciseIdentifier":"s:5OVKit15BroadcastDeviceP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"currentDevice","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastDevice":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastDevice"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastDevice","abstract":[{"type":"text","text":"Устройство, на которое может производиться стриминг видео."}],"type":"topic","title":"BroadcastDevice","url":"\/documentation\/ovkit\/broadcastdevice","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BroadcastDevice"}]},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BroadcastManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/broadcastmanager","title":"BroadcastManager","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BroadcastManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle","value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"op":"replace"}]}]}