{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/disconnectFromCurrentDevice()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/broadcastmanager\/disconnectfromcurrentdevice()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/broadcastmanager\/disconnectfromcurrentdevice()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnectFromCurrentDevice","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"disconnectFromCurrentDevice"}],"role":"symbol","title":"disconnectFromCurrentDevice()","externalID":"c:@M@OVKit@objc(cs)OVKBroadcastManager(im)disconnectFromCurrentDevice","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnectFromCurrentDevice","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/disconnectFromCurrentDevice()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnectFromCurrentDevice","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/disconnectFromCurrentDevice()","title":"disconnectFromCurrentDevice()","type":"topic","url":"\/documentation\/ovkit\/broadcastmanager\/disconnectfromcurrentdevice()","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"disconnectFromCurrentDevice","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BroadcastManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/broadcastmanager","title":"BroadcastManager","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"BroadcastManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"disconnectFromCurrentDevice","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnectFromCurrentDevice"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"disconnectFromCurrentDevice","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"disconnectFromCurrentDevice","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1disconnectFromCurrentDevice()\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1disconnectFromCurrentDevice()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"disconnectFromCurrentDevice"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"kind":"identifier","text":"OVKBroadcastManager"}],"op":"replace"},{"value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle"}]}]}