{"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKBroadcastManager(cpy)shared","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shared"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BroadcastManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBroadcastManager"}],"modules":[{"name":"OVKit"}],"roleHeading":"Type Property","title":"shared"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBroadcastManager","text":"BroadcastManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/shared"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/broadcastmanager\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/broadcastmanager\/shared"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/shared":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBroadcastManager","text":"BroadcastManager","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/shared","url":"\/documentation\/ovkit\/broadcastmanager\/shared","kind":"symbol","title":"shared"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BroadcastManager"}],"url":"\/documentation\/ovkit\/broadcastmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","title":"BroadcastManager","role":"symbol","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"shared","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"shared","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","text":"OVKBroadcastManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKBroadcastManager"},{"text":" * ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"shared","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1shared\/title"},{"op":"replace","value":[{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager~1shared\/fragments"},{"op":"replace","value":"OVKBroadcastManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title"},{"op":"replace","value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments"},{"op":"replace","value":[{"text":"OVKBroadcastManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle"}]}]}