{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDiscovery","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/startDiscovery()"},"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDiscovery","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startDiscovery()","externalID":"s:5OVKit16BroadcastManagerC14startDiscoveryyyF","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager"]]},"abstract":[{"type":"text","text":"Запускает поиск устройств без подписки на обновления."}],"variants":[{"paths":["\/documentation\/ovkit\/broadcastmanager\/startdiscovery()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BroadcastManager"}],"url":"\/documentation\/ovkit\/broadcastmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager","title":"BroadcastManager","role":"symbol","abstract":[{"type":"text","text":"Сущность, отвечающая за подключение ко внешним устройствам для стриминга видео."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastManager/startDiscovery()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastManager\/startDiscovery()","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/broadcastmanager\/startdiscovery()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDiscovery"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Запускает поиск устройств без подписки на обновления."}],"title":"startDiscovery()","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/title","value":"OVKBroadcastManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/fragments","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BroadcastManager\/navigatorTitle","value":[{"text":"OVKBroadcastManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}