{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/description"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/description"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","symbolKind":"property","title":"description","externalID":"s:5OVKit31InteractiveInterfaceClickSourceO11descriptionSSvp"},"references":{"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource":{"kind":"symbol","url":"\/documentation\/ovkit\/interactiveinterfaceclicksource","abstract":[],"title":"InteractiveInterfaceClickSource","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource","navigatorTitle":[{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveInterfaceClickSource","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/description":{"title":"description","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/description","kind":"symbol","url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/description","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/title","op":"replace","value":"OVKInteractiveInterfaceClickSource"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/fragments","op":"replace","value":[{"text":"OVKInteractiveInterfaceClickSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/navigatorTitle","op":"replace","value":[{"text":"OVKInteractiveInterfaceClickSource","kind":"identifier"}]}]}]}