{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/graphHide"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graphHide"}]}]}],"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graphHide"}],"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKInteractiveInterfaceClickSource@OVKInteractiveInterfaceClickSourceGraphHide","title":"InteractiveInterfaceClickSource.graphHide","navigatorTitle":[{"text":"OVKInteractiveInterfaceClickSourceGraphHide","kind":"identifier"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","abstract":[{"text":"Закрытие графа проекта","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphhide"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphhide"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource":{"role":"symbol","navigatorTitle":[{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/interactiveinterfaceclicksource","title":"InteractiveInterfaceClickSource","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/graphHide":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"graphHide","kind":"identifier"}],"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphhide","kind":"symbol","title":"InteractiveInterfaceClickSource.graphHide","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/graphHide","navigatorTitle":[{"text":"OVKInteractiveInterfaceClickSourceGraphHide","kind":"identifier"}],"abstract":[{"type":"text","text":"Закрытие графа проекта"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKInteractiveInterfaceClickSourceGraphHide"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKInteractiveInterfaceClickSourceGraphHide","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceGraphHide"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/title","value":"OVKInteractiveInterfaceClickSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/fragments","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSource"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1graphHide\/title","value":"OVKInteractiveInterfaceClickSourceGraphHide"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1graphHide\/fragments","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceGraphHide"}]}]}]}