{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphshow"]},{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphshow"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"]]},"metadata":{"externalID":"c:@M@OVKit@E@OVKInteractiveInterfaceClickSource@OVKInteractiveInterfaceClickSourceGraphShow","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"graphShow","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceGraphShow"}],"title":"InteractiveInterfaceClickSource.graphShow","roleHeading":"Case"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/graphShow","interfaceLanguage":"swift"},"abstract":[{"text":"Открытие графа проекта","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"graphShow","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource":{"navigatorTitle":[{"kind":"identifier","text":"InteractiveInterfaceClickSource"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource","title":"InteractiveInterfaceClickSource","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/graphShow":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graphShow"}],"role":"symbol","title":"InteractiveInterfaceClickSource.graphShow","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/graphShow","kind":"symbol","navigatorTitle":[{"text":"OVKInteractiveInterfaceClickSourceGraphShow","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/graphshow","abstract":[{"type":"text","text":"Открытие графа проекта"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKInteractiveInterfaceClickSourceGraphShow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceGraphShow"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKInteractiveInterfaceClickSourceGraphShow","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/title","value":"OVKInteractiveInterfaceClickSource","op":"replace"},{"value":[{"text":"OVKInteractiveInterfaceClickSource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSource"}]},{"op":"replace","value":"OVKInteractiveInterfaceClickSourceGraphShow","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1graphShow\/title"},{"value":[{"text":"OVKInteractiveInterfaceClickSourceGraphShow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1graphShow\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}