{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextChapterArea","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/nextChapterArea","interfaceLanguage":"swift"},"abstract":[{"text":"Область перехода к следующей главе","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/nextchapterarea"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/nextchapterarea"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"OVKInteractiveInterfaceClickSourceNextChapterArea","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextChapterArea","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@OVKit@E@OVKInteractiveInterfaceClickSource@OVKInteractiveInterfaceClickSourceNextChapterArea","title":"InteractiveInterfaceClickSource.nextChapterArea"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource":{"title":"InteractiveInterfaceClickSource","navigatorTitle":[{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource","abstract":[],"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource","role":"symbol","kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/nextChapterArea":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceNextChapterArea"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextChapterArea"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/nextChapterArea","abstract":[{"text":"Область перехода к следующей главе","type":"text"}],"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/nextchapterarea","role":"symbol","kind":"symbol","title":"InteractiveInterfaceClickSource.nextChapterArea"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKInteractiveInterfaceClickSourceNextChapterArea"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceNextChapterArea"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceNextChapterArea"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKInteractiveInterfaceClickSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/title"},{"op":"replace","value":[{"text":"OVKInteractiveInterfaceClickSource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSource"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1nextChapterArea\/title","op":"replace","value":"OVKInteractiveInterfaceClickSourceNextChapterArea"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource~1nextChapterArea\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSourceNextChapterArea"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}