{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","variants":[{"paths":["\/documentation\/ovkit\/interactiveinterfaceclicksource\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/hashValue"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"metadata":{"title":"RawRepresentable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource":{"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InteractiveInterfaceClickSource"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource","navigatorTitle":[{"text":"InteractiveInterfaceClickSource","kind":"identifier"}],"title":"InteractiveInterfaceClickSource","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/hashValue":{"kind":"symbol","title":"hashValue","abstract":[],"url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/hashvalue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/hashValue","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/InteractiveInterfaceClickSource/hash(into:)":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InteractiveInterfaceClickSource\/hash(into:)","url":"\/documentation\/ovkit\/interactiveinterfaceclicksource\/hash(into:)","role":"symbol","kind":"symbol","title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/title","value":"OVKInteractiveInterfaceClickSource"},{"value":[{"kind":"identifier","text":"OVKInteractiveInterfaceClickSource"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InteractiveInterfaceClickSource\/navigatorTitle","value":[{"text":"OVKInteractiveInterfaceClickSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}