{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/activeSubtitlesOption","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeSubtitlesOption","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","text":"SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeSubtitlesOption","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)activeSubtitlesOption","role":"symbol","title":"activeSubtitlesOption","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"activeSubtitlesOption","kind":"identifier"}]},"abstract":[{"text":"Текущая выбранная дорожка субтитров.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/activesubtitlesoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/activesubtitlesoption"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/activeSubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/activeSubtitlesOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeSubtitlesOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"activeSubtitlesOption"}],"title":"activeSubtitlesOption","role":"symbol","abstract":[{"text":"Текущая выбранная дорожка субтитров.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/activesubtitlesoption","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","abstract":[{"type":"text","text":"Дорожка субтитров."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubtitlesOption"}],"navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}],"title":"SubtitlesOption","url":"\/documentation\/ovkit\/subtitlesoption","type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"activeSubtitlesOption","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"activeSubtitlesOption"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","text":"OVKSubtitlesOption"},{"kind":"text","text":" * "},{"text":"activeSubtitlesOption","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1activeSubtitlesOption\/title","value":"activeSubtitlesOption","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1activeSubtitlesOption\/fragments","value":[{"text":"activeSubtitlesOption","kind":"identifier"}],"op":"replace"},{"value":"OVKSubtitlesOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSubtitlesOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSubtitlesOption"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"}]}]}