{"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlaybackActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInPiP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingOnExternalDevice","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingAd"],"generated":true,"title":"Наблюдение за состоянием","anchor":"Наблюдение-за-состоянием"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","text":"PlayerEventListener"},{"kind":"text","text":")"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Добавляемый объект будет удерживаться слабой ссылкой."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addEventListener(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Добавить слушателя событий воспроизведения.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/addeventlistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/addeventlistener(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)addEventListener:","title":"addEventListener(_:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"addEventListener:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerEventListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener"},{"kind":"text","text":")"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isInFullscreen":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInFullscreen","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playerview\/isinfullscreen","navigatorTitle":[{"text":"isInFullscreen","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInFullscreen"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isInFullscreen","abstract":[{"type":"text","text":"Является ли этот "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":" полноэкранным плеером."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isPlayingOnExternalDevice":{"kind":"symbol","title":"isPlayingOnExternalDevice","type":"topic","url":"\/documentation\/ovkit\/playerview\/isplayingonexternaldevice","abstract":[{"text":"Происходит ли стриминг видео на внешнее устройство (AirPlay или Chromecast).","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingOnExternalDevice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isPlayingOnExternalDevice"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlayingOnExternalDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isInPiP":{"kind":"symbol","title":"isInPiP","type":"topic","url":"\/documentation\/ovkit\/playerview\/isinpip","abstract":[{"type":"text","text":"Находится ли "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" непосредственно внутри Picture in picture."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInPiP","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isInPiP"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPiP"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addEventListener(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addEventListener(_:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playerview\/addeventlistener(_:)","navigatorTitle":[{"kind":"identifier","text":"addEventListener:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addEventListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","text":"PlayerEventListener"},{"kind":"text","text":")"}],"title":"addEventListener(_:)","abstract":[{"text":"Добавить слушателя событий воспроизведения.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addPeriodicTimeObserver(forInterval:using:)":{"kind":"symbol","title":"addPeriodicTimeObserver(forInterval:using:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"url":"\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addPeriodicTimeObserverForInterval:using:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isPlaybackActive":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlaybackActive","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playerview\/isplaybackactive","navigatorTitle":[{"kind":"identifier","text":"isPlaybackActive"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPlaybackActive","abstract":[{"text":"Происходит ли в данный момент воспроизведение видео, либо плеер собирается воспроизводить видео.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isPlayingAd":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingAd","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playerview\/isplayingad","navigatorTitle":[{"text":"isPlayingAd","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlayingAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Играет ли реклама в данный момент.","type":"text"}],"title":"isPlayingAd","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playereventlistener","navigatorTitle":[{"kind":"identifier","text":"PlayerEventListener"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerEventListener"}],"abstract":[{"type":"text","text":"Протокол для получения событий от плеера."}],"title":"PlayerEventListener","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addEventListener:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addEventListener:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlaybackActive","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInPiP","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInFullscreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingOnExternalDevice","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingAd"],"anchor":"Наблюдение-за-состоянием","title":"Наблюдение за состоянием","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addEventListener:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKPlayerEventListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerEventListener"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isInFullscreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInFullscreen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isInFullscreen"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInFullscreen\/fragments","op":"replace"},{"value":"isPlayingOnExternalDevice","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingOnExternalDevice\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isPlayingOnExternalDevice"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingOnExternalDevice\/fragments","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"isInPiP","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInPiP\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isInPiP"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInPiP\/fragments","op":"replace"},{"value":"addEventListener:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addEventListener(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addEventListener:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addEventListener(_:)\/fragments","op":"replace"},{"value":"addPeriodicTimeObserverForInterval:using:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPeriodicTimeObserverForInterval:using:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/fragments","op":"replace"},{"value":"isPlaybackActive","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlaybackActive\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isPlaybackActive"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlaybackActive\/fragments","op":"replace"},{"value":"isPlayingAd","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingAd\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isPlayingAd"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingAd\/fragments","op":"replace"},{"value":"OVKPlayerEventListener","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerEventListener"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerEventListener"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle","op":"replace"}]}]}