{"metadata":{"roleHeading":"Instance Method","title":"addPeriodicTimeObserver(forInterval:using:)","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"using","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"text":"Any","kind":"keyword"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)addPeriodicTimeObserverForInterval:using:","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPeriodicTimeObserver"},{"kind":"text","text":"("},{"text":"forInterval","kind":"externalParam"},{"kind":"text","text":" "},{"text":"interval","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Интервал времени, с которым нужно вызывать блок. Он не должен быть слишком маленьким, чтобы не вызвать падение производительности."}]}],"name":"interval"},{"name":"block","content":[{"inlineContent":[{"text":"Блок, который будет вызываться с заданной периодичностью. Параметром является текущее время воспроизведения. ","type":"text"},{"inlineContent":[{"type":"text","text":"Внутри блока нельзя сильно захватывать "},{"type":"codeVoice","code":"PlayerView"},{"text":", на который добавлен этот блок.","type":"text"}],"type":"emphasis"},{"type":"text","text":" Вызов блока происходит с main queue."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект-токен, который используется для удаления этого блока из списка наблюдателей. Если потерять на него ссылку, события продолжат приходить, и отдельно удалить блок уже не получится (но все еще можно использовать "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObservers()"},{"type":"text","text":")."}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"style":"warning","type":"aside","name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Этот механизм подходит для случаев, когда есть бизнес-логика, основанная на точном значении времени воспроизведения. Его не стоит использовать для обновления UI во время воспроизведения – для этого существует "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/handlePlayerTick()","isActive":true,"type":"reference"},{"type":"text","text":". Также он не подходит для сбора статистики воспроизведения – для этого в "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","isActive":true},{"type":"text","text":" есть соответствующие механизмы."}],"type":"paragraph"}]},{"inlineContent":[{"type":"text","text":"События поступают в блок только во время непосредственного воспроизведения, когда меняется картинка и\/или воспроизводится звук. Наблюдатель привязывается к воспроизведению только внутри данного "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":". Это значит, что при переносе воспроизведения в другой "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" (переход в полноэкранный режим, в Picture in Picture, ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","isActive":true},{"text":" и т.д.) события перестанут приходить. При возвращении воспроизведения события возобновятся.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Метод возвращает токен, который нужен для удаления созданного ранее наблюдателя. Для этого есть метод "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObserver(_:)","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/addPeriodicTimeObserver(forInterval:using:)":{"url":"\/documentation\/ovkit\/playerview\/addperiodictimeobserver(forinterval:using:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addPeriodicTimeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"using","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/addPeriodicTimeObserver(forInterval:using:)","type":"topic","title":"addPeriodicTimeObserver(forInterval:using:)","abstract":[{"type":"text","text":"Добавляет блок, который вызывается с заданным интервалом во время воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"addPeriodicTimeObserverForInterval:using:"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/removeTimeObservers()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTimeObservers","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Удаляет все блоки-наблюдатели времени на данном ","type":"text"},{"code":"PlayerView","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/playerview\/removetimeobservers()","title":"removeTimeObservers()","kind":"symbol","navigatorTitle":[{"text":"removeTimeObservers","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObservers()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","role":"symbol","title":"createAnimatedTransition(to:in:)","url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PlayerViewAnimatedTransition","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"abstract":[{"type":"text","text":"Создание вспомогательного объекта для анимированного переноса плеера из текущего PlayerView в место назначения."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoStatsHandler":{"url":"\/documentation\/ovkit\/videostatshandler","title":"VideoStatsHandler","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoStatsHandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoStatsHandler"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoStatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/removeTimeObserver(_:)":{"type":"topic","abstract":[{"text":"Удаляет ранее добавленный блок-наблюдатель.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/removetimeobserver(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeTimeObserver"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObserver(_:)","title":"removeTimeObserver(_:)","navigatorTitle":[{"kind":"identifier","text":"removeTimeObserver:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol/handlePlayerTick()":{"title":"handlePlayerTick()","url":"\/documentation\/ovkit\/playercontrolsviewprotocol\/handleplayertick()","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Вызывается периодически во время проигрывания видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol\/handlePlayerTick()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePlayerTick","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"addPeriodicTimeObserverForInterval:using:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPeriodicTimeObserverForInterval:using:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"addPeriodicTimeObserverForInterval:"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"interval"},{"text":" ","kind":"text"},{"text":"using:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"interval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Интервал времени, с которым нужно вызывать блок. Он не должен быть слишком маленьким, чтобы не вызвать падение производительности."}]}]},{"name":"block","content":[{"inlineContent":[{"text":"Блок, который будет вызываться с заданной периодичностью. Параметром является текущее время воспроизведения. ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Внутри блока нельзя сильно захватывать ","type":"text"},{"type":"codeVoice","code":"PlayerView"},{"text":", на который добавлен этот блок.","type":"text"}]},{"type":"text","text":" Вызов блока происходит с main queue."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Объект-токен, который используется для удаления этого блока из списка наблюдателей. Если потерять на него ссылку, события продолжат приходить, и отдельно удалить блок уже не получится (но все еще можно использовать "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObservers()"},{"type":"text","text":")."}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/title","value":"addPeriodicTimeObserverForInterval:using:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1addPeriodicTimeObserver(forInterval:using:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"addPeriodicTimeObserverForInterval:using:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObservers()\/title","value":"removeTimeObservers","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObservers()\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeTimeObservers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","value":"createAnimatedTransitionTo:in:"},{"value":[{"kind":"text","text":"- "},{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/title","value":"OVKVideoStatsHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKVideoStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoStatsHandler","kind":"identifier"}]},{"value":"removeTimeObserver:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObserver(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTimeObserver:"}],"op":"replace"}]}]}