{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoQualityRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию значение "},{"type":"codeVoice","code":"nil"},{"type":"text","text":". Это значит, что диапазон включает в себя все доступные качества."}]}]}],"abstract":[{"text":"Диапазон качества, в котором плеер будет играть, если выбрано автоматическое качество.","type":"text"}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","title":"autoQualityRange","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)autoQualityRange","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"autoQualityRange","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoQualityRange"},{"text":": ","kind":"text"},{"text":"QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playerview\/autoqualityrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/autoqualityrange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"kind":"symbol","type":"topic","title":"QualityRange","abstract":[{"text":"Диапазон качества видео.","type":"text"}],"url":"\/documentation\/ovkit\/qualityrange","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityRange"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","navigatorTitle":[{"kind":"identifier","text":"QualityRange"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/autoQualityRange":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoQualityRange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoQualityRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"autoQualityRange"}],"title":"autoQualityRange","role":"symbol","abstract":[{"type":"text","text":"Диапазон качества, в котором плеер будет играть, если выбрано автоматическое качество."}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/autoqualityrange","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoQualityRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"autoQualityRange","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","text":"OVKQualityRange","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"autoQualityRange","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"OVKQualityRange","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKQualityRange"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/navigatorTitle","value":[{"kind":"identifier","text":"OVKQualityRange"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/title","op":"replace","value":"autoQualityRange"},{"op":"replace","value":[{"text":"autoQualityRange","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoQualityRange\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}