{"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"title":"autoRotateToLandscapeInFullscreenIfPossible","navigatorTitle":[{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)autoRotateToLandscapeInFullscreenIfPossible","symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoRotateToLandscapeInFullscreenIfPossible","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/autorotatetolandscapeinfullscreenifpossible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/autorotatetolandscapeinfullscreenifpossible"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Поддержка автоматического разворачивания в полноэкранный горизонтальный режим. Видео в "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" должно подходить по параметрам (быть горизонтальным, не GIF). При вызове метода ","type":"text"},{"type":"codeVoice","code":"maximizeToFullscreenLandscape(completion:)"},{"text":" свойство игнорируется.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoRotateToLandscapeInFullscreenIfPossible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"По умолчанию имеет значение "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/autoRotateToLandscapeInFullscreenIfPossible":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/ovkit\/playerview\/autorotatetolandscapeinfullscreenifpossible","abstract":[{"type":"text","text":"Поддержка автоматического разворачивания в полноэкранный горизонтальный режим. Видео в "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":" должно подходить по параметрам (быть горизонтальным, не GIF). При вызове метода ","type":"text"},{"type":"codeVoice","code":"maximizeToFullscreenLandscape(completion:)"},{"type":"text","text":" свойство игнорируется."}],"title":"autoRotateToLandscapeInFullscreenIfPossible","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/autoRotateToLandscapeInFullscreenIfPossible","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoRotateToLandscapeInFullscreenIfPossible"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","abstract":[],"type":"topic","title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"autoRotateToLandscapeInFullscreenIfPossible","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoRotateToLandscapeInFullscreenIfPossible"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"autoRotateToLandscapeInFullscreenIfPossible","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoRotateToLandscapeInFullscreenIfPossible\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1autoRotateToLandscapeInFullscreenIfPossible\/fragments","op":"replace","value":[{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"}]},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}