{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/availableautoshoppable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/availableautoshoppable"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/availableAutoShoppable"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableAutoShoppable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Обычно настраивается  до  начала проигрывания и зависит от места использования "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":". Допустимые места для активации этой функции – полноэкранный режим, ленты с включенным по умолчанию звуком плеера.","type":"text"}],"type":"paragraph"}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAutoShoppable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"availableAutoShoppable"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)availableAutoShoppable","role":"symbol","title":"availableAutoShoppable"},"abstract":[{"text":"Разрешено ли открывать рекламу формата shoppable автоматически при старте баннера.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/availableAutoShoppable":{"navigatorTitle":[{"kind":"identifier","text":"availableAutoShoppable"}],"url":"\/documentation\/ovkit\/playerview\/availableautoshoppable","abstract":[{"text":"Разрешено ли открывать рекламу формата shoppable автоматически при старте баннера.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/availableAutoShoppable","title":"availableAutoShoppable","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAutoShoppable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"availableAutoShoppable","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"availableAutoShoppable","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableAutoShoppable"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"availableAutoShoppable","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1availableAutoShoppable\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1availableAutoShoppable\/fragments","value":[{"kind":"identifier","text":"availableAutoShoppable"}]}]}]}