{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/availableadssection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/availableadssection"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/availableAdsSection"},"abstract":[{"text":"Разрешено ли играть рекламу.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Обычно настраивается  до  начала проигрывания и зависит от места использования "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Например для "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","isActive":true},{"text":" возможность играть рекламу по умолчанию  выключена.","type":"text"}],"sections":[],"metadata":{"title":"availableAdsSection","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableAdsSection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)availableAdsSection","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"availableAdsSection","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableAdsSection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/PiPWindow":{"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PiPWindow","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Device Orientation для ","type":"text"},{"code":"PlayerManager.shared.pipWindow","type":"codeVoice"},{"type":"text","text":" можно поддержать"},{"text":" ","type":"text"},{"type":"text","text":"в методе AppDelegate "},{"type":"codeVoice","code":"application(_:supportedIntefaceOrientationsFor:)"}],"title":"PiPWindow","navigatorTitle":[{"text":"PiPWindow","kind":"identifier"}],"url":"\/documentation\/ovkit\/pipwindow"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"url":"\/documentation\/ovkit\/playerview","role":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/availableAdsSection":{"title":"availableAdsSection","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/availableAdsSection","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAdsSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"availableAdsSection"}],"abstract":[{"text":"Разрешено ли играть рекламу.","type":"text"},{"text":" ","type":"text"},{"text":"Обычно настраивается  до  начала проигрывания и зависит от места использования ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Например для "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PiPWindow"},{"type":"text","text":" возможность играть рекламу по умолчанию  выключена."}],"url":"\/documentation\/ovkit\/playerview\/availableadssection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"availableAdsSection","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"availableAdsSection"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"text":" * ","kind":"text"},{"text":"availableAdsSection","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/title","value":"OVKPiPWindow"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/fragments","value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKPiPWindow"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PiPWindow\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"availableAdsSection","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1availableAdsSection\/title"},{"value":[{"kind":"identifier","text":"availableAdsSection"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1availableAdsSection\/fragments"}]}]}