{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"backgroundPlaybackPolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundPlaybackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BackgroundPlaybackPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)backgroundPlaybackPolicy"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundPlaybackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BackgroundPlaybackPolicy","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Если выбрать продолжение воспроизведения, то при проигрывании в системе появятся контролы медиацентра ("},{"type":"codeVoice","code":"MPRemoteCommandCenter"},{"type":"text","text":")."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Поддерживается возможность изменить значение во время воспроизведения видео. А при переходах с одного "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" на другой (с использованием "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"},{"type":"text","text":") текущее значение автоматически применится в конце перехода."}]},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Фоновое воспроизведение может быть недоступно из-за параметров отдельно взятого видео."}]}],"type":"aside","style":"note"},{"inlineContent":[{"type":"text","text":"Значение по умолчанию – "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy"},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy"]}],"abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/backgroundPlaybackPolicy":{"navigatorTitle":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/backgroundPlaybackPolicy","abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"url":"\/documentation\/ovkit\/playerview\/backgroundplaybackpolicy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","kind":"typeIdentifier","text":"BackgroundPlaybackPolicy"}],"role":"symbol","title":"backgroundPlaybackPolicy"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/pause":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"}],"navigatorTitle":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicyPause"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause","title":"BackgroundPlaybackPolicy.pause","type":"topic","abstract":[{"type":"text","text":"Приостановка воспроизведения."}],"url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/pause","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"type":"topic","role":"article","title":"Воспроизведение в фоне","abstract":[{"type":"text","text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"kind":"article","url":"\/documentation\/ovkit\/backgroundplayback","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","title":"BackgroundPlaybackPolicy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"title":"createAnimatedTransition(to:in:)","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"backgroundPlaybackPolicy","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","text":"OVKBackgroundPlaybackPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/title","op":"replace","value":"backgroundPlaybackPolicy"},{"op":"replace","value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1backgroundPlaybackPolicy\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/title","value":"OVKBackgroundPlaybackPolicyPause","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/fragments","value":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","value":"OVKBackgroundPlaybackPolicy","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments","value":[{"kind":"identifier","text":"OVKBackgroundPlaybackPolicy"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/navigatorTitle","value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","value":"createAnimatedTransitionTo:in:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"op":"replace"}]}]}