{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheContainer","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"По умолчанию не задан, что означает использование общего кэша."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/cacheContainer","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"kind":"text","text":"?"}],"title":"cacheContainer","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)cacheContainer","navigatorTitle":[{"kind":"identifier","text":"cacheContainer"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/cachecontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/cachecontainer"]}],"sections":[],"abstract":[{"type":"text","text":"Отдельный контейнер кэша, данные из которого будет использовать плеер."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/CacheContainer":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CacheContainer","kind":"identifier"}],"kind":"symbol","title":"CacheContainer","role":"symbol","url":"\/documentation\/ovkit\/cachecontainer","type":"topic","navigatorTitle":[{"text":"CacheContainer","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/cacheContainer":{"kind":"symbol","title":"cacheContainer","url":"\/documentation\/ovkit\/playerview\/cachecontainer","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/cacheContainer","abstract":[{"type":"text","text":"Отдельный контейнер кэша, данные из которого будет использовать плеер."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheContainer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CacheContainer","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"cacheContainer","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cacheContainer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cacheContainer","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CacheContainer","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCacheContainer","text":"OVKCacheContainer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cacheContainer"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"OVKCacheContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/title"},{"op":"replace","value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/fragments"},{"op":"replace","value":[{"text":"OVKCacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CacheContainer\/navigatorTitle"},{"op":"replace","value":"cacheContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1cacheContainer\/title"},{"op":"replace","value":[{"text":"cacheContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1cacheContainer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}