{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/canmaximizetofullscreeninlandscape(from:)"]},{"paths":["\/documentation\/ovkit\/playerview\/canmaximizetofullscreeninlandscape(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canMaximizeToFullscreenInLandscape"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"Контроллер, с которого планируется развернуть плеер.","type":"text"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/canMaximizeToFullscreenInLandscape(from:)"},"abstract":[{"text":"Проверка возможности развернуть плеер в полноэкранный режим.","type":"text"}],"metadata":{"extendedModule":"OVKit","modules":[{"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canMaximizeToFullscreenInLandscape","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(cm)canMaximizeToFullscreenInLandscapeFrom:","symbolKind":"method","title":"canMaximizeToFullscreenInLandscape(from:)","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"canMaximizeToFullscreenInLandscapeFrom:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","url":"\/documentation\/ovkit\/playerview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"kind":"symbol","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/canMaximizeToFullscreenInLandscape(from:)":{"type":"topic","navigatorTitle":[{"text":"canMaximizeToFullscreenInLandscapeFrom:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canMaximizeToFullscreenInLandscape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/canMaximizeToFullscreenInLandscape(from:)","abstract":[{"text":"Проверка возможности развернуть плеер в полноэкранный режим.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/canmaximizetofullscreeninlandscape(from:)","role":"symbol","kind":"symbol","title":"canMaximizeToFullscreenInLandscape(from:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"canMaximizeToFullscreenInLandscapeFrom:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canMaximizeToFullscreenInLandscapeFrom:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canMaximizeToFullscreenInLandscapeFrom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"Контроллер, с которого планируется развернуть плеер."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1canMaximizeToFullscreenInLandscape(from:)\/title","value":"canMaximizeToFullscreenInLandscapeFrom:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1canMaximizeToFullscreenInLandscape(from:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"canMaximizeToFullscreenInLandscapeFrom:","kind":"identifier"}]}]}]}