{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"changeVideo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"video","kind":"internalParam"},{"kind":"text","text":": "},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"doNotShowPreview","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false)"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Новый видео ресурс."}],"type":"paragraph"}],"name":"video"},{"name":"doNotShowPreview","content":[{"inlineContent":[{"text":"Если включить, кадр от предыдущего видео останется виден до тех пор, пока не заиграет новое видео. По умолчанию выключено.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Метод оптимизирован для смены ресурса в ответ на действие пользователя (например, переход к следующему видео). Процесс смены ресурса выглядит более плавно, но больше работы перекладывается на главный поток.","type":"text"}]},{"name":"Warning","type":"aside","style":"warning","content":[{"inlineContent":[{"text":"Не рекомендуется использовать во время настройки ячеек таблицы или коллекции. Для этих целей нужно установить поле ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"changeVideoTo:doNotShowPreview:"}],"title":"changeVideo(to:doNotShowPreview:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeVideo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"doNotShowPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)changeVideoTo:doNotShowPreview:","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Смена видео в плеере."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/changeVideo(to:doNotShowPreview:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/changevideo(to:donotshowpreview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/changevideo(to:donotshowpreview:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/changeVideo(to:doNotShowPreview:)":{"kind":"symbol","url":"\/documentation\/ovkit\/playerview\/changevideo(to:donotshowpreview:)","title":"changeVideo(to:doNotShowPreview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/changeVideo(to:doNotShowPreview:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"changeVideo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"doNotShowPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"changeVideoTo:doNotShowPreview:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Смена видео в плеере.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/stop()":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stop"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"text":"Остановка и очистка плеера","type":"text"}],"title":"stop()","navigatorTitle":[{"kind":"identifier","text":"stop"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","url":"\/documentation\/ovkit\/playerview\/stop()"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/videotype"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/prepareForReuse()":{"url":"\/documentation\/ovkit\/playerview\/prepareforreuse()","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"title":"prepareForReuse()","navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","abstract":[],"type":"topic","title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"url":"\/documentation\/ovkit\/playerview\/video","type":"topic","abstract":[{"type":"text","text":"Не устанавливать nil: останавливать проигрывание необходимо через "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","type":"reference","isActive":true},{"text":" или ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":"?","kind":"text"}],"title":"video","navigatorTitle":[{"text":"video","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"changeVideoTo:doNotShowPreview:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeVideoTo:doNotShowPreview:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"changeVideoTo:"},{"kind":"text","text":"("},{"text":"id<OVKVideoType>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"video"},{"kind":"text","text":" "},{"text":"doNotShowPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"doNotShowPreview"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Новый видео ресурс."}]}],"name":"video"},{"name":"doNotShowPreview","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Если включить, кадр от предыдущего видео останется виден до тех пор, пока не заиграет новое видео. По умолчанию выключено."}]}]}],"kind":"parameters"},"op":"replace"},{"value":"changeVideoTo:doNotShowPreview:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1changeVideo(to:doNotShowPreview:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"changeVideoTo:doNotShowPreview:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1changeVideo(to:doNotShowPreview:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/title","value":"stop"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stop"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","value":"OVKVideoType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/title","value":"prepareForReuse"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prepareForReuse"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"video","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","value":[{"text":"video","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}