{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/controlsview"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" удерживает свои контролы даже после того, как произошел перенос видео в другой ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" (переход с одного экрана на другой, переход в полноэкранный режим, переход в режим Picture in Picture). При переносе видео между ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" каждое ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" подставляет свои ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/controlsView"},{"text":".","type":"text"}]}]}],"metadata":{"symbolKind":"property","externalID":"s:5OVKit10PlayerViewC08controlsC0AA0b8ControlsC8Protocol_pvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"role":"symbol","modules":[{"name":"OVKit"}],"title":"controlsView","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"text":"Контролы, которые принадлежат данному ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/controlsView"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","title":"PlayerControlsViewProtocol","role":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/controlsView":{"title":"controlsView","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/controlsView","abstract":[{"type":"text","text":"Контролы, которые принадлежат данному "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/controlsview","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}]}]}