{"metadata":{"roleHeading":"Instance Method","title":"createAnimatedTransition(to:in:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"role":"symbol","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)createAnimatedTransitionTo:in:","extendedModule":"OVKit","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition"},{"kind":"text","text":"?"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)"],"title":"Переходы","anchor":"Переходы","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, в который осуществляется переход."}]}],"name":"playerView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UIView"},{"type":"text","text":", которое будет использоваться для промежуточной анимации. Оно должно занимать все окно по размеру."}]}],"name":"context"}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions"],"kind":"mentions"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"При вызове этого метода переход еще не начинается. Его нужно настроить и выполнить самостоятельно, используя возвращенный "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","type":"reference","isActive":true},{"type":"text","text":". Объект не удерживает "},{"code":"view","type":"codeVoice"},{"type":"text","text":", которыми он оперирует."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns Объект, с помощью которого выполняется анимированный переход плеера."}]}]}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"},"kind":"symbol","abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","url":"\/documentation\/ovkit\/transitions","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","role":"article","abstract":[{"type":"text","text":"Непрерывный перенос воспроизведения из одного "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в другой."}],"title":"Переходы между плеерами"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)":{"title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","navigatorTitle":[{"text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceBlackBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"title":"maximizeToFullscreen(completion:)","abstract":[{"text":"Разворачивание плеера в полноэкранный режим.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","navigatorTitle":[{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(initialVelocity:completion:)":{"title":"minimizeToPiP(initialVelocity:completion:)","abstract":[{"type":"text","text":"Свернуть плеер во внутренний Picture In Picture."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPiP","kind":"identifier"},{"text":"(","kind":"text"},{"text":"initialVelocity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlayback":{"kind":"article","role":"article","type":"topic","abstract":[{"type":"text","text":"Воспроизведение звука или видео, когда приложение находится в свернутом состоянии."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlayback","url":"\/documentation\/ovkit\/backgroundplayback","title":"Воспроизведение в фоне"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","abstract":[{"type":"text","text":"Показывает "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":", автоматически открыв при необходимости полноэкранный режим."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","navigatorTitle":[{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prepareBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"title":"transition(to:)","abstract":[{"type":"text","text":"Переход плеера в другое "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" без анимации."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","navigatorTitle":[{"kind":"identifier","text":"transitionTo:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playerview\/transition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","abstract":[{"type":"text","text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в место назначения."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","title":"createAnimatedTransition(to:in:)","kind":"symbol","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewAnimatedTransition":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerviewanimatedtransition","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition","role":"symbol","abstract":[{"type":"text","text":"Выполняет анимированный перенос плеера между двумя "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerViewAnimatedTransition"}],"title":"PlayerViewAnimatedTransition"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","kind":"symbol","title":"FullscreenSupplementaryController","navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createAnimatedTransitionTo:in:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)"],"generated":true,"anchor":"Переходы","title":"Переходы"}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"OVKPlayerViewAnimatedTransition","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewAnimatedTransition"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createAnimatedTransitionTo:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"in:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, в который осуществляется переход."}]}],"name":"playerView"},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"UIView"},{"type":"text","text":", которое будет использоваться для промежуточной анимации. Оно должно занимать все окно по размеру."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/title","op":"replace","value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title","op":"replace","value":"maximizeToFullscreenWithCompletion:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/title","op":"replace","value":"minimizeToPiPWithInitialVelocity:completion:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minimizeToPiPWithInitialVelocity:completion:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title","op":"replace","value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title","op":"replace","value":"transitionTo:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionTo:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","op":"replace","value":"createAnimatedTransitionTo:in:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/title","op":"replace","value":"OVKPlayerViewAnimatedTransition"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewAnimatedTransition\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerViewAnimatedTransition"}]},{"op":"replace","value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle"}]}]}