{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAndPrepareFullscreenControllerForPresentation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playerViewSetupBlock","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"}],"navigatorTitle":[{"text":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","kind":"identifier"}],"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(cm)createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","symbolKind":"method","modules":[{"name":"OVKit"}],"role":"symbol","title":"createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)","roleHeading":"Type Method","extendedModule":"OVKit"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)"},"abstract":[{"text":"Создание экземпляра контроллера для полноэкранного показа.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/createandpreparefullscreencontrollerforpresentation(playerviewsetupblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/createandpreparefullscreencontrollerforpresentation(playerviewsetupblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAndPrepareFullscreenControllerForPresentation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playerViewSetupBlock","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil) -> ","kind":"text"},{"text":"FullscreenController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"Warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Не рекомендуется использовать этот метод, вместо этого стоит создать "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" с контролами для полноэкранного режима."}]}],"type":"aside","style":"warning"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)","navigatorTitle":[{"text":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/createandpreparefullscreencontrollerforpresentation(playerviewsetupblock:)","abstract":[{"type":"text","text":"Создание экземпляра контроллера для полноэкранного показа."}],"role":"symbol","title":"createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAndPrepareFullscreenControllerForPresentation","kind":"identifier"},{"kind":"text","text":"("},{"text":"playerViewSetupBlock","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenController"}],"abstract":[],"title":"FullscreenController","type":"topic","url":"\/documentation\/ovkit\/fullscreencontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol","kind":"typeIdentifier","text":"UIViewController<OVKFullscreenViewControllerProtocol>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"playerViewSetupBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)\/title","value":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAndPrepareFullscreenControllerForPresentation(playerViewSetupBlock:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createAndPrepareFullscreenControllerForPresentationWithPlayerViewSetupBlock:","kind":"identifier"}],"op":"replace"}]}]}