{"abstract":[{"type":"text","text":"Набор доступных скоростей воспроизведения, который переопределяет стандартный набор."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customPlaybackRates","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Эти значения показываются в меню плеера в пункте выбора скорости воспроизведения. Кроме того, до этих значений округляется задаваемая через "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","isActive":true},{"type":"text","text":". При изменении значения "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","isActive":true},{"type":"text","text":" текущая скорость воспроизведения не меняется даже если она не соответствует ни одной из новых доступных."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию имеет значение "},{"type":"codeVoice","code":"nil"},{"type":"text","text":". В таком случае плеер использует стандартный набор скоростей воспроизведения: "},{"type":"codeVoice","code":"[0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]"},{"type":"text","text":"."}]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение свойства должно быть либо "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", либо содержать непустой массив положительных чисел в диапазоне от "},{"code":"0.25","type":"codeVoice"},{"type":"text","text":" до "},{"code":"2.0","type":"codeVoice"},{"type":"text","text":"."}]}],"type":"aside","name":"Warning"}]}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/customplaybackrates"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","title":"customPlaybackRates","role":"symbol","externalID":"s:5OVKit10PlayerViewC19customPlaybackRatesSaySfGSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customPlaybackRates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"]?","kind":"text"}],"symbolKind":"property","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playbackRate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"playbackRate","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/playbackrate","kind":"symbol","role":"symbol","title":"playbackRate","abstract":[{"text":"Скорость воспроизведения.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/customPlaybackRates":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customPlaybackRates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"]?","kind":"text"}],"title":"customPlaybackRates","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","url":"\/documentation\/ovkit\/playerview\/customplaybackrates","kind":"symbol","role":"symbol","abstract":[{"text":"Набор доступных скоростей воспроизведения, который переопределяет стандартный набор.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","title":"PlayerView","url":"\/documentation\/ovkit\/playerview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/title","value":"playbackRate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/fragments","value":[{"text":"playbackRate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}