{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customControls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adsProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit11AdsProviderP","text":"AdsProvider"},{"kind":"text","text":"?)"}],"externalID":"s:5OVKit10PlayerViewC5frame7gravity14customControls11adsProviderACSo6CGRectV_AA0bC7GravityOAA0bgC8Protocol_pAA03AdsI0_pSgtcfc","roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"OVKit"}],"title":"init(frame:gravity:customControls:adsProvider:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/init(frame:gravity:customcontrols:adsprovider:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/init(frame:gravity:customControls:adsProvider:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"gravity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"PlayerViewGravity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customControls"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adsProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit11AdsProviderP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider","kind":"typeIdentifier","text":"AdsProvider"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"text":"Изначальный ","type":"text"},{"type":"codeVoice","code":"frame"},{"text":", может быть изменен в дальнейшем.","type":"text"}]}]},{"name":"gravity","content":[{"type":"paragraph","inlineContent":[{"text":"Изначальное значение ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","type":"reference"},{"text":", может быть изменено в дальнейшем.","type":"text"}]}]},{"name":"customControls","content":[{"type":"paragraph","inlineContent":[{"text":"Контролы для данного ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}]}]}]}],"abstract":[{"type":"text","text":"Инициализация плеера."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","type":"topic","navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewgravity","abstract":[{"type":"text","text":"Режим отображения картинки в плеере."}],"title":"PlayerViewGravity","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"title":"PlayerControlsViewProtocol","abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","navigatorTitle":[{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/gravity":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview\/gravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","role":"symbol","abstract":[{"text":"Текущий режим отображения картинки в плеере.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"gravity"}],"title":"gravity"},"doc://onevideo.OVKit/documentation/OVKit/AdsProvider":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdsProvider"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/adsprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider","role":"symbol","abstract":[{"type":"text","text":"Протокол поставщика рекламных контролов."}],"navigatorTitle":[{"kind":"identifier","text":"AdsProvider"}],"title":"AdsProvider"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/init(frame:gravity:customControls:adsProvider:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/init(frame:gravity:customControls:adsProvider:)","abstract":[{"type":"text","text":"Инициализация плеера."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customControls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adsProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdsProvider","preciseIdentifier":"s:5OVKit11AdsProviderP"},{"kind":"text","text":"?)"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/init(frame:gravity:customcontrols:adsprovider:)","title":"init(frame:gravity:customControls:adsProvider:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKPlayerViewGravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"value":"gravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"gravity"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/fragments","op":"replace"}]}]}