{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"gravity","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customControls"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","title":"init(frame:gravity:customControls:)","externalID":"s:5OVKit10PlayerViewC5frame7gravity14customControlsACSo6CGRectV_AA0bC7GravityOAA0bgC8Protocol_ptcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gravity"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/init(frame:gravity:customControls:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/init(frame:gravity:customcontrols:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"title":"PlayerControlsViewProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"kind":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/init(frame:gravity:customControls:)":{"kind":"symbol","role":"symbol","title":"init(frame:gravity:customControls:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/init(frame:gravity:customControls:)","url":"\/documentation\/ovkit\/playerview\/init(frame:gravity:customcontrols:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gravity"},{"kind":"text","text":": "},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customControls"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerviewgravity","title":"PlayerViewGravity","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":"OVKPlayerViewGravity","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle","value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}