{"sections":[],"abstract":[{"text":"Находится ли ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" непосредственно внутри Picture in picture.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInPiP","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPiP"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isInPiP","role":"symbol","navigatorTitle":[{"text":"isInPiP","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)isInPiP","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPiP"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/isinpip"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/isinpip"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isInPiP":{"url":"\/documentation\/ovkit\/playerview\/isinpip","title":"isInPiP","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInPiP","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Находится ли "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" непосредственно внутри Picture in picture."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isInPiP","role":"symbol","navigatorTitle":[{"text":"isInPiP","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"title":"PlayerView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isInPiP","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isInPiP","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInPiP"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isInPiP","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInPiP\/title"},{"value":[{"kind":"identifier","text":"isInPiP"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isInPiP\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}]}]}