{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlayingOnExternalDevice","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)isPlayingOnExternalDevice","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlayingOnExternalDevice","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","title":"isPlayingOnExternalDevice","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isPlayingOnExternalDevice"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/isplayingonexternaldevice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/isplayingonexternaldevice"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingOnExternalDevice"},"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/isPlayingOnExternalDevice":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isPlayingOnExternalDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isPlayingOnExternalDevice"}],"title":"isPlayingOnExternalDevice","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/isPlayingOnExternalDevice","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview\/isplayingonexternaldevice","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"abstract":[],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isPlayingOnExternalDevice"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"isPlayingOnExternalDevice","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlayingOnExternalDevice"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"isPlayingOnExternalDevice","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingOnExternalDevice\/title"},{"op":"replace","value":[{"text":"isPlayingOnExternalDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1isPlayingOnExternalDevice\/fragments"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"}]}]}