{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoopBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Значение по умолчанию - ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Задает поведение плеера при завершении видео.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/loopBehavior"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/loopbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/loopbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"title":"loopBehavior","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)loopBehavior","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoopBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"loopBehavior"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/loopBehavior":{"title":"loopBehavior","type":"topic","url":"\/documentation\/ovkit\/playerview\/loopbehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/loopBehavior","abstract":[{"text":"Задает поведение плеера при завершении видео.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"loopBehavior","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"LoopBehavior","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"navigatorTitle":[{"text":"LoopBehavior","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","kind":"symbol","url":"\/documentation\/ovkit\/loopbehavior","abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"title":"LoopBehavior","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoopBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType/repeated":{"title":"repeated","kind":"symbol","required":true,"navigatorTitle":[{"text":"repeated","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/videotype\/repeated","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior/auto":{"type":"topic","navigatorTitle":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Поведение зависит от настройки ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType\/repeated","isActive":true},{"type":"text","text":"."}],"title":"LoopBehavior.auto","url":"\/documentation\/ovkit\/loopbehavior\/auto","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior\/auto"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"loopBehavior","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"loopBehavior","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","text":"OVKLoopBehavior"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopBehavior"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"loopBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1loopBehavior\/title"},{"value":[{"text":"loopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1loopBehavior\/fragments"},{"value":"OVKLoopBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments"},{"value":[{"text":"OVKLoopBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/navigatorTitle"},{"value":"repeated","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType~1repeated\/fragments","op":"replace","value":[{"text":"repeated","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/title","op":"replace","value":"OVKLoopBehaviorAuto"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior~1auto\/fragments","op":"replace","value":[{"text":"OVKLoopBehaviorAuto","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}