{"kind":"symbol","abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"seeAlsoSections":[{"generated":true,"anchor":"Переходы","title":"Переходы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreen"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который будет вызван после открытия полноэкранного режима. В параметр будет передан полноэкранный "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"type":"text","text":"."}]}]}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions"],"kind":"mentions"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"maximizeToFullscreen(completion:)","navigatorTitle":[{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"role":"symbol","symbolKind":"method","extendedModule":"OVKit","roleHeading":"Instance Method","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)maximizeToFullscreenWithCompletion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreen"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"navigatorTitle":[{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"title":"maximizeToFullscreen(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим."}],"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"title":"createAnimatedTransition(to:in:)","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(initialVelocity:completion:)":{"navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"title":"minimizeToPiP(initialVelocity:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"minimizeToPiP","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialVelocity"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?)"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Свернуть плеер в Picture in Picture."}],"url":"\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"kind":"article","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","abstract":[{"type":"text","text":"Непрерывный перенос воспроизведения из одного "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в другой."}],"url":"\/documentation\/ovkit\/transitions","role":"article","title":"Переходы между плеерами"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol","title":"FullscreenSupplementaryController"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"navigatorTitle":[{"kind":"identifier","text":"transitionTo:"}],"title":"transition(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Переход плеера в другое "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" без анимации.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/transition(to:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"prepareBlock","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Показывает "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"type":"text","text":", автоматически открыв при необходимости полноэкранный режим."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)","title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreenInCurrentOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forceBlackBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации."}],"navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"maximizeToFullscreenWithCompletion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Переходы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"generated":true,"anchor":"Переходы"}],"op":"replace"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"OVKPlayerView"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Блок, который будет вызван после открытия полноэкранного режима. В параметр будет передан полноэкранный "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"maximizeToFullscreenWithCompletion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments"},{"op":"replace","value":"createAnimatedTransitionTo:in:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments"},{"op":"replace","value":"minimizeToPiPWithInitialVelocity:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace","value":"OVKFullscreenSupplementaryController"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title","op":"replace","value":"transitionTo:"},{"value":[{"text":"- ","kind":"text"},{"text":"transitionTo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments"},{"value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","kind":"identifier"}]}]}]}