{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","role":"symbol","title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maximizeToFullscreenWithSupplementary","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prepareBlock"},{"text":": ((","kind":"text"},{"text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementary"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prepareBlock"},{"text":": ((","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","kind":"typeIdentifier","text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"При этом запоминается способ, которым открыли ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":", и при помощи метода ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/closeSupplementary()","isActive":true,"type":"reference"},{"type":"text","text":" можно закрыть его, если потребуется."}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)"]}],"abstract":[{"text":"Метод позволяет открыть ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":", при необходимости автоматически открыв полноэкранный режим."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenController":{"type":"topic","title":"FullscreenController","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenController","url":"\/documentation\/ovkit\/fullscreencontroller","navigatorTitle":[{"kind":"identifier","text":"FullscreenController"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenController"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/closeSupplementary()":{"kind":"symbol","navigatorTitle":[{"text":"closeSupplementary","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"closeSupplementary","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"text":"Закрывает ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"type":"text","text":", если он был открыт после перехода в полноэкранный режим методом "},{"type":"codeVoice","code":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)"},{"type":"text","text":", и сама "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":" находится в полноэкранном режиме. Либо закрывает полноэкранный режим, если он был открыт вместе с ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/closesupplementary()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/closeSupplementary()","type":"topic","title":"closeSupplementary()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Метод позволяет открыть "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"type":"text","text":", при необходимости автоматически открыв полноэкранный режим."}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)","title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementary","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prepareBlock"},{"kind":"text","text":": (("},{"text":"FullscreenController","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20FullscreenControllera"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol","text":"UIViewController<OVKFullscreenViewControllerProtocol>"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"prepareBlock","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKFullscreenSupplementaryController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace"},{"op":"replace","value":"closeSupplementary","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1closeSupplementary()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeSupplementary"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1closeSupplementary()\/fragments","op":"replace"},{"op":"replace","value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"}]}]}