{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"extendedModule":"OVKit","title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","modules":[{"name":"OVKit"}],"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientation"},{"kind":"text","text":"("},{"text":"forceBlackBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"anchor":"Переходы","generated":true,"title":"Переходы"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximizeToFullscreenInCurrentOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forceBlackBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Флаг, указывающий на необходимость использования черного фона при анимации."}],"type":"paragraph"}],"name":"forceBlackBackground"},{"content":[{"inlineContent":[{"type":"text","text":"Блок, который будет вызван после открытия полноэкранного режима. В параметр будет передан полноэкранный "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)","title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","role":"symbol","abstract":[{"type":"text","text":"Показывает "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":", автоматически открыв при необходимости полноэкранный режим.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementary","kind":"identifier"},{"kind":"text","text":"("},{"text":"prepareBlock","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"url":"\/documentation\/ovkit\/transitions","type":"topic","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","title":"Переходы между плеерами","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"url":"\/documentation\/ovkit\/playerview\/transition(to:)","navigatorTitle":[{"text":"transitionTo:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Переход плеера в другое ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":" без анимации.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","title":"transition(to:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":") -> ","kind":"text"},{"text":"PlayerViewAnimatedTransition","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","kind":"symbol","title":"createAnimatedTransition(to:in:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","title":"FullscreenSupplementaryController","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(initialVelocity:completion:)":{"url":"\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)","navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPiP","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Свернуть плеер в Picture in Picture."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","title":"minimizeToPiP(initialVelocity:completion:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceBlackBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","kind":"symbol","title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","title":"maximizeToFullscreen(completion:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"anchor":"Переходы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"generated":true,"title":"Переходы"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"forceBlackBackground","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"forceBlackBackground","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Флаг, указывающий на необходимость использования черного фона при анимации."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который будет вызван после открытия полноэкранного режима. В параметр будет передан полноэкранный "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":".","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments"},{"value":"transitionTo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionTo:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments"},{"value":"createAnimatedTransitionTo:in:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments"},{"value":"OVKFullscreenSupplementaryController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle"},{"value":"minimizeToPiPWithInitialVelocity:completion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minimizeToPiPWithInitialVelocity:completion:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/fragments"},{"value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/fragments"},{"value":"maximizeToFullscreenWithCompletion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}