{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/mediaselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/mediaselection"]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)mediaSelection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","kind":"typeIdentifier","text":"MediaSelection"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"mediaSelection","navigatorTitle":[{"kind":"identifier","text":"mediaSelection"}]},"kind":"symbol","abstract":[{"text":"Набор медиадорожек, находящихся в видео ресурсе.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaSelection","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","kind":"typeIdentifier","text":"MediaSelection"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Свойство присутствует только у ресурсов, которые поддерживают переключение между множественными дорожками. Оно становится доступно после того, как ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate","isActive":true,"type":"reference"},{"type":"text","text":" или "},{"type":"codeVoice","code":"listener"},{"type":"text","text":" получит сообщение "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","type":"reference"},{"type":"text","text":"."}]},{"name":"Warning","type":"aside","style":"warning","content":[{"inlineContent":[{"type":"text","text":"Полученный объект "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","type":"reference","isActive":true},{"type":"text","text":" является валидным только пока проигрывается видео, на котором он был получен. После смены видео он перестанет работать."}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection","interfaceLanguage":"swift"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MediaSelection"}],"role":"symbol","abstract":[{"text":"Набор медиадорожек, находящихся в видеоресурсе.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MediaSelection","kind":"identifier"}],"title":"MediaSelection","url":"\/documentation\/ovkit\/mediaselection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStart(_:userInitiated:)":{"abstract":[{"type":"text","text":"Плеер начал работу: качать и проигрывать."}],"type":"topic","title":"playerDidStart(_:userInitiated:)","navigatorTitle":[{"kind":"identifier","text":"playerDidStart:userInitiated:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","required":true,"url":"\/documentation\/ovkit\/playereventlistener\/playerdidstart(_:userinitiated:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerDidStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/mediaSelection":{"abstract":[{"text":"Набор медиадорожек, находящихся в видео ресурсе.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/mediaselection","navigatorTitle":[{"kind":"identifier","text":"mediaSelection"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSelection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","text":"MediaSelection","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"mediaSelection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/delegate":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"PlayerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/playerview\/delegate","title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"mediaSelection"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mediaSelection"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","text":"OVKMediaSelection","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"mediaSelection","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKMediaSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments","value":[{"text":"OVKMediaSelection","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMediaSelection"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/title","value":"playerDidStart:userInitiated:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"playerDidStart:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/fragments"},{"value":"mediaSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1mediaSelection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"mediaSelection"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1mediaSelection\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"}]}]}