{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Сворачивание плеера в Picture In Picture.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/minimizetopip(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/minimizetopip(completion:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPiP"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Блок, который вызовется после окончания анимации сворачивания."}],"type":"paragraph"}],"name":"completion"}]}],"metadata":{"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"minimizeToPiP","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","title":"minimizeToPiP(completion:)","platforms":[],"symbolKind":"method","extendedModule":"OVKit","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)minimizeToPiPWithCompletion:","navigatorTitle":[{"text":"minimizeToPiPWithCompletion:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","type":"topic","url":"\/documentation\/ovkit\/voidblock","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoidBlock"}],"navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"title":"VoidBlock"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPiP"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"minimizeToPiPWithCompletion:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(completion:)","url":"\/documentation\/ovkit\/playerview\/minimizetopip(completion:)","title":"minimizeToPiP(completion:)","abstract":[{"type":"text","text":"Сворачивание плеера в Picture In Picture."}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"minimizeToPiPWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"minimizeToPiPWithCompletion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"minimizeToPiPWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который вызовется после окончания анимации сворачивания."}]}],"name":"completion"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(completion:)\/title","value":"minimizeToPiPWithCompletion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"minimizeToPiPWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"}]}]}