{"abstract":[{"text":"Свернуть плеер в Picture in Picture.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPiP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"initialVelocity","content":[{"inlineContent":[{"type":"text","text":"Начальный вектор скорости сворачивания."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Блок, который вызовется после окончания анимации сворачивания."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"По умолчанию плеер свернется во внутренний Picture in Picture. Если активировать флаг ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useSystemPictureInPicture","isActive":true,"type":"reference"},{"text":", то переход произойдет уже в системный Picture in Picture, если он включен в системных настройках.","type":"text"}],"type":"paragraph"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Если на "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"type":"text","text":" включен флаг "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/allowsMultiplay","type":"reference","isActive":true},{"type":"text","text":", переход в системный Picture in Picture будет недоступен."}],"type":"paragraph"}]},{"inlineContent":[{"text":"За событиями жизненного цикла окна Picture in Picture (внутреннего или системного) можно наблюдать через стандартные методы переходов между плеерами: ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)"},"seeAlsoSections":[{"title":"Переходы","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"anchor":"Переходы","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)minimizeToPiPWithInitialVelocity:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPiP","kind":"identifier"},{"text":"(","kind":"text"},{"text":"initialVelocity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":"?)","kind":"text"}],"extendedModule":"OVKit","title":"minimizeToPiP(initialVelocity:completion:)","symbolKind":"method","role":"symbol","platforms":[],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(initialVelocity:completion:)":{"url":"\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)","navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimizeToPiP","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Свернуть плеер в Picture in Picture."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","title":"minimizeToPiP(initialVelocity:completion:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","url":"\/documentation\/ovkit\/voidblock","navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoidBlock","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"VoidBlock"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/allowsMultiplay":{"type":"topic","title":"allowsMultiplay","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/allowsMultiplay","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowsMultiplay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Флаг, позволяющий воспроизводить видео одновременно с другими ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"allowsMultiplay","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/allowsmultiplay"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","navigatorTitle":[{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnimatedTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":") -> ","kind":"text"},{"text":"PlayerViewAnimatedTransition","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в место назначения.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","kind":"symbol","title":"createAnimatedTransition(to:in:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","title":"FullscreenSupplementaryController","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"url":"\/documentation\/ovkit\/transitions","type":"topic","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","title":"Переходы между плеерами","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)","title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","role":"symbol","abstract":[{"type":"text","text":"Показывает "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":", автоматически открыв при необходимости полноэкранный режим.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementary","kind":"identifier"},{"kind":"text","text":"("},{"text":"prepareBlock","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","text":"FullscreenController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/Environment/useSystemPictureInPicture":{"abstract":[{"type":"text","text":"Включает использование системного окна Picture in Picture везде."}],"navigatorTitle":[{"text":"useSystemPictureInPicture","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Environment\/useSystemPictureInPicture","type":"topic","kind":"symbol","title":"useSystemPictureInPicture","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useSystemPictureInPicture"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/ovkit\/environment\/usesystempictureinpicture"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceBlackBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","kind":"symbol","title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"url":"\/documentation\/ovkit\/playerview\/transition(to:)","navigatorTitle":[{"text":"transitionTo:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Переход плеера в другое ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":" без анимации.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","title":"transition(to:)","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Разворачивание плеера в полноэкранный режим."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","title":"maximizeToFullscreen(completion:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"minimizeToPiPWithInitialVelocity:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minimizeToPiPWithInitialVelocity:completion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Переходы","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"anchor":"Переходы"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimizeToPiPWithInitialVelocity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initialVelocity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)()) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"initialVelocity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Начальный вектор скорости сворачивания."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Блок, который вызовется после окончания анимации сворачивания."}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/title","value":"minimizeToPiPWithInitialVelocity:completion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minimizeToPiPWithInitialVelocity:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1allowsMultiplay\/title","value":"allowsMultiplay","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1allowsMultiplay\/fragments","value":[{"kind":"identifier","text":"allowsMultiplay"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title","value":"createAnimatedTransitionTo:in:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title","value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useSystemPictureInPicture\/title","value":"useSystemPictureInPicture","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Environment~1useSystemPictureInPicture\/fragments","value":[{"kind":"identifier","text":"useSystemPictureInPicture"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/title","value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title","value":"transitionTo:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transitionTo:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title","value":"maximizeToFullscreenWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"op":"replace"}]}]}