{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"abstract":[{"type":"text","text":"Пауза пользователем: userInitiated действие, отключает автопроигрывание при "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Актуально только после начала проигрывания"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paused"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"paused","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"paused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"paused","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)paused","role":"symbol","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/paused"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/paused"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"url":"\/documentation\/ovkit\/playerview","role":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"type":"topic","title":"playerViewOnScreen","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","abstract":[{"text":"Отвечает за видимость плеера на экране.","type":"text"},{"type":"text","text":" "},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Это свойство может изменится, если вызван "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)"},{"text":" со значением ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"playerViewOnScreen","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","title":"paused","url":"\/documentation\/ovkit\/playerview\/paused","abstract":[{"type":"text","text":"Пауза пользователем: userInitiated действие, отключает автопроигрывание при "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Актуально только после начала проигрывания"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"paused","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"role":"symbol","title":"play(userInitiated:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"playWithUserInitiated:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paused","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"paused","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","value":"playerViewOnScreen"},{"value":[{"kind":"identifier","text":"playerViewOnScreen"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","op":"replace"},{"value":"paused","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","value":[{"kind":"identifier","text":"paused"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","value":"playWithUserInitiated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"playWithUserInitiated:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}