{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewOnScreen"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)playerViewOnScreen","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"role":"symbol","title":"playerViewOnScreen"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/playerviewonscreen"]},{"paths":["\/documentation\/ovkit\/playerview\/playerviewonscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Отвечает за видимость плеера на экране."},{"type":"text","text":" "},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Это свойство может изменится, если вызван "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","isActive":true},{"text":" со значением ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"kind":"symbol","title":"playerViewOnScreen","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Отвечает за видимость плеера на экране."},{"type":"text","text":" "},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Это свойство может изменится, если вызван "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","isActive":true},{"type":"text","text":" со значением "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"playWithUserInitiated:"}],"kind":"symbol","title":"play(userInitiated:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"playerViewOnScreen","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"playerViewOnScreen","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playerViewOnScreen","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","value":[{"kind":"identifier","text":"playerViewOnScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","op":"replace","value":"playWithUserInitiated:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playWithUserInitiated:","kind":"identifier"}],"op":"replace"}]}]}