{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать.","type":"text"}],"type":"paragraph"}],"name":"fromTime"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение качества, с которого плеер должен начать проигрывание. Например: "},{"type":"codeVoice","code":"240"},{"type":"text","text":", "},{"type":"codeVoice","code":"360"},{"type":"text","text":", "},{"type":"codeVoice","code":"480"},{"type":"text","text":", "},{"type":"codeVoice","code":"720"},{"type":"text","text":", и так далее. Другие переданные числа будут округлены до ближайших возможных. Если ресурс не имеет выбранного качества, плеер будет воспроизводить видео в режиме автокачества."}]}],"name":"initialQuality"},{"content":[{"inlineContent":[{"text":"Если действие совершает пользователь — проигрывание начнется, не смотря на свойство ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true},{"text":" (выставится в ","type":"text"},{"type":"codeVoice","code":"true"},{"text":") и наличие играющего Picture In Picture. Если действие инициировано не пользователем (фокус-трекинг), то проигрывание не начнется, если идет воспроизведение в Picture In Picture или плеер не на экране (","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true},{"text":" == false)","type":"text"}],"type":"paragraph"}],"name":"userInitiated"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/play(fromtime:initialquality:userinitiated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/play(fromtime:initialquality:userinitiated:)"]}],"abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(fromTime:initialQuality:userInitiated:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"initialQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"title":"play(fromTime:initialQuality:userInitiated:)","symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)playFromTime:initialQuality:userInitiated:","navigatorTitle":[{"text":"playFromTime:initialQuality:userInitiated:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(fromTime:initialQuality:userInitiated:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(fromTime:initialQuality:userInitiated:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"title":"play(fromTime:initialQuality:userInitiated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"playFromTime:initialQuality:userInitiated:"}],"url":"\/documentation\/ovkit\/playerview\/play(fromtime:initialquality:userinitiated:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","title":"PlayerView","url":"\/documentation\/ovkit\/playerview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","navigatorTitle":[{"text":"playerViewOnScreen","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Отвечает за видимость плеера на экране."},{"type":"text","text":" "},{"type":"text","text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение."},{"type":"text","text":" "},{"type":"text","text":"Это свойство может изменится, если вызван "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)"},{"type":"text","text":" со значением "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","title":"playerViewOnScreen","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"title":"play(userInitiated:)","abstract":[{"text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","navigatorTitle":[{"text":"playWithUserInitiated:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"playFromTime:initialQuality:userInitiated:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"playFromTime:initialQuality:userInitiated:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playFromTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"fromTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"initialQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"initialQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"userInitiated","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать.","type":"text"}],"type":"paragraph"}],"name":"fromTime"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Значение качества, с которого плеер должен начать проигрывание. Например: ","type":"text"},{"code":"240","type":"codeVoice"},{"text":", ","type":"text"},{"code":"360","type":"codeVoice"},{"text":", ","type":"text"},{"code":"480","type":"codeVoice"},{"text":", ","type":"text"},{"code":"720","type":"codeVoice"},{"text":", и так далее. Другие переданные числа будут округлены до ближайших возможных. Если ресурс не имеет выбранного качества, плеер будет воспроизводить видео в режиме автокачества.","type":"text"}]}],"name":"initialQuality"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Если действие совершает пользователь — проигрывание начнется, не смотря на свойство ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true,"type":"reference"},{"text":" (выставится в ","type":"text"},{"code":"true","type":"codeVoice"},{"text":") и наличие играющего Picture In Picture. Если действие инициировано не пользователем (фокус-трекинг), то проигрывание не начнется, если идет воспроизведение в Picture In Picture или плеер не на экране (","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true,"type":"reference"},{"text":" == false)","type":"text"}]}],"name":"userInitiated"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(fromTime:initialQuality:userInitiated:)\/title","value":"playFromTime:initialQuality:userInitiated:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(fromTime:initialQuality:userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playFromTime:initialQuality:userInitiated:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","value":"playerViewOnScreen","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","value":[{"kind":"identifier","text":"playerViewOnScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","value":"playWithUserInitiated:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playWithUserInitiated:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}