{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playerview\/playbackrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/playbackrate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"symbolKind":"property","title":"playbackRate","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)playbackRate","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"],"title":"Параметры воспроизведения","anchor":"Параметры-воспроизведения","generated":true}],"sections":[],"abstract":[{"type":"text","text":"Скорость воспроизведения."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Поддерживаемые значения: ","type":"text"},{"type":"codeVoice","code":"0.25"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.5"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.75"},{"text":", ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"1.25","type":"codeVoice"},{"text":", ","type":"text"},{"code":"1.5","type":"codeVoice"},{"text":", ","type":"text"},{"code":"1.75","type":"codeVoice"},{"text":", ","type":"text"},{"code":"2.0","type":"codeVoice"},{"text":". Они могут меняться в зависимости от значения свойства ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","type":"reference"},{"text":". По умолчанию ","type":"text"},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}]},{"style":"warning","type":"aside","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Если установить другое значение, оно автоматически скорректируется до ближайшего поддерживаемого."}]}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/customPlaybackRates":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","abstract":[{"text":"Набор доступных скоростей воспроизведения, который переопределяет стандартный набор.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customPlaybackRates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":"]?"}],"type":"topic","title":"customPlaybackRates","url":"\/documentation\/ovkit\/playerview\/customplaybackrates","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customPlaybackRates"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/soundOn":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview\/soundon","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","role":"symbol","abstract":[{"text":"Включение\/выключение звука.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"soundOn"}],"title":"soundOn"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","title":"paused","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"paused","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/paused","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"paused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Пауза воспроизведения."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playbackRate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview\/playbackrate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","role":"symbol","abstract":[{"text":"Скорость воспроизведения.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playbackRate"}],"title":"playbackRate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/gravity":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview\/gravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","role":"symbol","abstract":[{"text":"Текущий режим отображения картинки в плеере.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"gravity"}],"title":"gravity"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectedQuality":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality","abstract":[{"text":"Качество, выбранное пользователем.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"title":"selectedQuality","url":"\/documentation\/ovkit\/playerview\/selectedquality","kind":"symbol","type":"topic","navigatorTitle":[{"text":"selectedQuality","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/volume":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview\/volume","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","role":"symbol","abstract":[{"text":"Регулировка громкости звука в плеере.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"volume"}],"title":"volume"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","abstract":[{"type":"text","text":"Устанавливает видимость плеера на экране."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"playerViewOnScreen","url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","kind":"symbol","type":"topic","navigatorTitle":[{"text":"playerViewOnScreen","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"playbackRate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"playbackRate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Параметры-воспроизведения","title":"Параметры воспроизведения","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1customPlaybackRates\/title","value":"customPlaybackRates","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1customPlaybackRates\/fragments","value":[{"kind":"identifier","text":"customPlaybackRates"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/title","value":"soundOn","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/fragments","value":[{"kind":"identifier","text":"soundOn"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","value":"paused","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","value":[{"kind":"identifier","text":"paused"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/title","value":"playbackRate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/fragments","value":[{"kind":"identifier","text":"playbackRate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/title","value":"gravity","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/fragments","value":[{"kind":"identifier","text":"gravity"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/title","value":"selectedQuality","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/fragments","value":[{"kind":"identifier","text":"selectedQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/title","value":"volume","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/fragments","value":[{"kind":"identifier","text":"volume"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","value":"playerViewOnScreen","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","value":[{"kind":"identifier","text":"playerViewOnScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}