{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)"},"abstract":[{"text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/play(userinitiated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/play(userinitiated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"method","title":"play(userInitiated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInitiated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"playWithUserInitiated:"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)playWithUserInitiated:","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"userInitiated","content":[{"inlineContent":[{"text":"Если действие совершает пользователь — проигрывание начнется,","type":"text"},{"text":" ","type":"text"},{"text":"не смотря на свойство ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true,"type":"reference"},{"text":" (выставится в ","type":"text"},{"type":"codeVoice","code":"true"},{"text":") и наличие играющего Picture In Picture. Если действие инициировано не пользователем (фокус-трекинг), то проигрывание не начнется, если","type":"text"},{"text":" ","type":"text"},{"text":"идет воспроизведение в Picture In Picture или плеер не на экране (","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","isActive":true,"type":"reference"},{"text":" == false)","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"kind":"symbol","title":"playerViewOnScreen","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Отвечает за видимость плеера на экране."},{"type":"text","text":" "},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Это свойство может изменится, если вызван "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","isActive":true},{"type":"text","text":" со значением "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"playWithUserInitiated:"}],"kind":"symbol","title":"play(userInitiated:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"playWithUserInitiated:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"playWithUserInitiated:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playWithUserInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"userInitiated","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Если действие совершает пользователь — проигрывание начнется,"},{"type":"text","text":" "},{"text":"не смотря на свойство ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen"},{"text":" (выставится в ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":") и наличие играющего Picture In Picture. Если действие инициировано не пользователем (фокус-трекинг), то проигрывание не начнется, если"},{"type":"text","text":" "},{"type":"text","text":"идет воспроизведение в Picture In Picture или плеер не на экране ("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","type":"reference","isActive":true},{"type":"text","text":" == false)"}],"type":"paragraph"}],"name":"userInitiated"}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","value":"playerViewOnScreen","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","value":[{"text":"playerViewOnScreen","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","op":"replace","value":"playWithUserInitiated:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playWithUserInitiated:"}]}]}]}