{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/point(inside:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/point(inside:with:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/point(inside:with:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)pointInside:withEvent:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"point","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inside","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","title":"point(inside:with:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"pointInside:withEvent:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"point"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inside"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/point(inside:with:)":{"kind":"symbol","url":"\/documentation\/ovkit\/playerview\/point(inside:with:)","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/point(inside:with:)","navigatorTitle":[{"text":"pointInside:withEvent:","kind":"identifier"}],"title":"point(inside:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"point","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inside","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","url":"\/documentation\/ovkit\/playerview","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"kind":"symbol","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pointInside:withEvent:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pointInside:withEvent:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"pointInside:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"pointInside:withEvent:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1point(inside:with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pointInside:withEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1point(inside:with:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}