{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","extendedModule":"OVKit","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetch"},{"kind":"text","text":"("},{"text":"after","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"title":"prefetch(after:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"prefetchAfter:"}],"externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)prefetchAfter:"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prefetch(after:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Префетч находящейся в этом ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" видеозаписи.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"kind":"text","text":" "},{"text":"time","kind":"internalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время, после которого необходимо начать префетч. Значение "},{"type":"codeVoice","code":"0"},{"type":"text","text":" означает немедленное начало."}]}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Метод необходимо вызывать только на Main Queue!","type":"text"}]}],"style":"warning","type":"aside","name":"Warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/prefetch(after:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/prefetch(after:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/prefetch(after:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"after"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/playerview\/prefetch(after:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prefetch(after:)","navigatorTitle":[{"text":"prefetchAfter:","kind":"identifier"}],"title":"prefetch(after:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Префетч находящейся в этом "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":" видеозаписи."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"prefetchAfter:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"prefetchAfter:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"prefetchAfter:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"time"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":{"parameters":[{"name":"time","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время, после которого необходимо начать префетч. Значение "},{"type":"codeVoice","code":"0"},{"text":" означает немедленное начало.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":"prefetchAfter:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prefetch(after:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prefetch(after:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"prefetchAfter:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}