{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewGravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"}],"modules":[{"name":"OVKit"}],"title":"previewGravity","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"previewGravity"}],"roleHeading":"Instance Property","extendedModule":"OVKit","role":"symbol","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(py)previewGravity"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewGravity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"PlayerViewGravity"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"По умолчанию имеет значение ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill"},{"text":".","type":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/previewGravity"},"abstract":[{"type":"text","text":"Режим отображения превью."}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/previewgravity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/previewgravity"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","type":"topic","navigatorTitle":[{"text":"PlayerViewGravity","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerviewgravity","abstract":[{"type":"text","text":"Режим отображения картинки в плеере."}],"title":"PlayerViewGravity","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","title":"PlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/previewGravity":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/previewGravity","title":"previewGravity","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"previewGravity","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/previewgravity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewGravity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Режим отображения превью."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fill":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill","type":"topic","navigatorTitle":[{"text":"OVKPlayerViewGravityFill","kind":"identifier"}],"abstract":[{"type":"text","text":"Картинка растянута на весь вьюпорт плеера с сохранением пропорций."}],"url":"\/documentation\/ovkit\/playerviewgravity\/fill","kind":"symbol","title":"PlayerViewGravity.fill","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fill","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"previewGravity","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"previewGravity"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"OVKPlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewGravity"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerViewGravity","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravity"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/navigatorTitle"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"previewGravity","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1previewGravity\/title"},{"value":[{"kind":"identifier","text":"previewGravity"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1previewGravity\/fragments"},{"value":"OVKPlayerViewGravityFill","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewGravityFill"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/fragments"}]}]}