{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Обновить данные об очереди воспроизведения.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queueDidUpdate","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Нужно вызывать, если клиент добавил видео в очередь воспроизведения, переставил видео местами и т.п. Эффект будет только при установленном ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/queueDelegate","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"queueDidUpdate"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)queueDidUpdate","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queueDidUpdate"},{"kind":"text","text":"()"}],"role":"symbol","title":"queueDidUpdate()","modules":[{"name":"OVKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/queuedidupdate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/queuedidupdate()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/queueDidUpdate()"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/queueDidUpdate()":{"kind":"symbol","navigatorTitle":[{"text":"queueDidUpdate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/playerview\/queuedidupdate()","abstract":[{"text":"Обновить данные об очереди воспроизведения.","type":"text"}],"title":"queueDidUpdate()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/queueDidUpdate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queueDidUpdate","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/queueDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"queueDelegate"}],"url":"\/documentation\/ovkit\/playerview\/queuedelegate","abstract":[{"text":"Делегат для работы с очередью видео.","type":"text"}],"title":"queueDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/queueDelegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queueDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate","kind":"typeIdentifier","text":"PlayerQueueDelegate"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"queueDidUpdate","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"queueDidUpdate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"queueDidUpdate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"value":"queueDidUpdate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1queueDidUpdate()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queueDidUpdate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1queueDidUpdate()\/fragments"},{"value":"queueDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1queueDelegate\/title"},{"value":[{"kind":"identifier","text":"queueDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1queueDelegate\/fragments"}]}]}