{"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/quickseekinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/quickseekinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)quickSeekInterval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quickSeekInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"role":"symbol","title":"quickSeekInterval","navigatorTitle":[{"text":"quickSeekInterval","kind":"identifier"}]},"abstract":[{"text":"Интервал для быстрой перемотки.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/quickSeekInterval","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quickSeekInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Этот параметр отвечает за длительность интервала перемотки вперед и назад во всех сценариях, где есть быстрая перемотка:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"контролы с "},{"code":"DoubleTapSeekBehavior","type":"codeVoice"},{"type":"text","text":","}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"системный медиа центр,"}]}]},{"content":[{"inlineContent":[{"text":"горячие клавиши,","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"и так далее.","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Параметр можно изменять во время воспроизведения. Переданный интервал округляется до целого значения. Значение по умолчанию - "},{"type":"codeVoice","code":"10 секунд"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/quickSeekInterval":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"quickSeekInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Интервал для быстрой перемотки."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/quickSeekInterval","url":"\/documentation\/ovkit\/playerview\/quickseekinterval","kind":"symbol","role":"symbol","title":"quickSeekInterval","navigatorTitle":[{"text":"quickSeekInterval","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","title":"PlayerView","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"quickSeekInterval"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"quickSeekInterval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"text":" ","kind":"text"},{"text":"quickSeekInterval","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"quickSeekInterval","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1quickSeekInterval\/title"},{"value":[{"text":"quickSeekInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1quickSeekInterval\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]}]}]}