{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/removetimeobserver(_:)"]},{"paths":["\/documentation\/ovkit\/playerview\/removetimeobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"removeTimeObserver(_:)","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeTimeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)removeTimeObserver:","symbolKind":"method","navigatorTitle":[{"text":"removeTimeObserver:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeTimeObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"observer"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"Объект-токен, полученный при добавлении блока.","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"text":"Удаляет ранее добавленный блок-наблюдатель.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObserver(_:)"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/removeTimeObserver(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeTimeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"removeTimeObserver:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeTimeObserver(_:)","url":"\/documentation\/ovkit\/playerview\/removetimeobserver(_:)","title":"removeTimeObserver(_:)","abstract":[{"type":"text","text":"Удаляет ранее добавленный блок-наблюдатель."}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"removeTimeObserver:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"removeTimeObserver:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeTimeObserver:"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Объект-токен, полученный при добавлении блока.","type":"text"}],"type":"paragraph"}],"name":"observer"}]},"path":"\/primaryContentSections\/1"},{"value":"removeTimeObserver:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObserver(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeTimeObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTimeObserver:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}