{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeEventListener(_:)"},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/removeeventlistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/removeeventlistener(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeEventListener:"}],"role":"symbol","modules":[{"name":"OVKit"}],"title":"removeEventListener(_:)","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)removeEventListener:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","text":"PlayerEventListener"},{"kind":"text","text":")"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlayerEventListener","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/removeEventListener(_:)":{"title":"removeEventListener(_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/playerview\/removeeventlistener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventListener"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerEventListener","kind":"typeIdentifier","text":"PlayerEventListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"removeEventListener:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/removeEventListener(_:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","title":"PlayerView","url":"\/documentation\/ovkit\/playerview","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener","title":"PlayerEventListener","navigatorTitle":[{"text":"PlayerEventListener","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playereventlistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerEventListener","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол для получения событий от плеера."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeEventListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeEventListener:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeEventListener:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKPlayerEventListener>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerEventListener","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeEventListener(_:)\/title","value":"removeEventListener:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeEventListener:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1removeEventListener(_:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"OVKPlayerEventListener","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerEventListener"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerEventListener","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener\/navigatorTitle"}]}]}