{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/seekToTime(_:initiatePlay:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Перемотка видео."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/seektotime(_:initiateplay:)"]},{"paths":["\/documentation\/ovkit\/playerview\/seektotime(_:initiateplay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekToTime","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"seconds","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"initiatePlay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Для видео: время, на которое перемотать. Для трансляции: кол-во секунд, на сколько трансляция должна отставать.","type":"text"}],"type":"paragraph"}],"name":"seconds"},{"name":"initiatePlay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Принудительный запуск, если видео не запущено, доиграло до конца, или остановлено."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Для перемотки видео можно использовать значения от 0 до длительности видео."},{"text":" ","type":"text"},{"type":"text","text":"Для перемотки трансляций можно использовать отрицательные значения (кол-во секунд отставания трансляции) или 0 (трансляция без отставания)."},{"type":"text","text":" "},{"type":"text","text":"Также перемотка трансляций должна быть разрешена (из api, настраивается пользователем): "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","isActive":true,"type":"reference"},{"type":"text","text":" и "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"metadata":{"title":"seekToTime(_:initiatePlay:)","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)seekToTime:initiatePlay:","navigatorTitle":[{"kind":"identifier","text":"seekToTime:initiatePlay:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"seekToTime","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initiatePlay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/maxRewindDuration":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/maxRewindDuration","kind":"symbol","type":"topic","title":"maxRewindDuration","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxRewindDuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"abstract":[{"type":"text","text":"Максимальное время перемотки в секундах"}],"url":"\/documentation\/ovkit\/livesettings\/maxrewindduration"},"doc://onevideo.OVKit/documentation/OVKit/LiveSettings/canRewind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveSettings\/canRewind","kind":"symbol","type":"topic","title":"canRewind","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRewind"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"url":"\/documentation\/ovkit\/livesettings\/canrewind"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/seekToTime(_:initiatePlay:)":{"title":"seekToTime(_:initiatePlay:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/seekToTime(_:initiatePlay:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekToTime"},{"kind":"text","text":"("},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"initiatePlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Перемотка видео.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"seekToTime:initiatePlay:"}],"url":"\/documentation\/ovkit\/playerview\/seektotime(_:initiateplay:)","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"seekToTime:initiatePlay:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekToTime:initiatePlay:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"seekToTime:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"text":"seconds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"initiatePlay:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"initiatePlay"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1seekToTime(_:initiatePlay:)\/title","value":"seekToTime:initiatePlay:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1seekToTime(_:initiatePlay:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"seekToTime:initiatePlay:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}]}]}