{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)selectedQuality","title":"selectedQuality","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"selectedQuality","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"variants":[{"paths":["\/documentation\/ovkit\/playerview\/selectedquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/selectedquality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"},"abstract":[{"type":"text","text":"Качество, выбранное пользователем."}],"seeAlsoSections":[{"title":"Параметры воспроизведения","anchor":"Параметры-воспроизведения","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"Значением является целое число-значение качества. Например: "},{"code":"240","type":"codeVoice"},{"type":"text","text":", "},{"code":"360","type":"codeVoice"},{"type":"text","text":", "},{"code":"480","type":"codeVoice"},{"type":"text","text":", "},{"code":"720","type":"codeVoice"},{"type":"text","text":", и так далее. Другие переданные числа будут округлены до ближайших возможных."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Значение "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает выбор автоматического качества."}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","abstract":[{"type":"text","text":"Устанавливает видимость плеера на экране."}],"title":"playerViewOnScreen","type":"topic","navigatorTitle":[{"text":"playerViewOnScreen","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/volume":{"navigatorTitle":[{"text":"volume","kind":"identifier"}],"title":"volume","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","role":"symbol","url":"\/documentation\/ovkit\/playerview\/volume","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Регулировка громкости звука в плеере."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"abstract":[{"type":"text","text":"Пауза воспроизведения."}],"title":"paused","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"paused","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/playerview\/paused","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectedQuality":{"abstract":[{"type":"text","text":"Качество, выбранное пользователем."}],"title":"selectedQuality","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"selectedQuality","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/playerview\/selectedquality","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/soundOn":{"abstract":[{"type":"text","text":"Включение\/выключение звука."}],"title":"soundOn","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"soundOn","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"soundOn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/playerview\/soundon","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/gravity":{"abstract":[{"type":"text","text":"Текущий режим отображения картинки в плеере."}],"title":"gravity","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"gravity","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}],"url":"\/documentation\/ovkit\/playerview\/gravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playbackRate":{"abstract":[{"type":"text","text":"Скорость воспроизведения."}],"title":"playbackRate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/ovkit\/playerview\/playbackrate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"selectedQuality","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"selectedQuality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Параметры воспроизведения","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate"],"generated":true,"anchor":"Параметры-воспроизведения"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"selectedQuality"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"playerViewOnScreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title"},{"op":"replace","value":[{"text":"playerViewOnScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments"},{"op":"replace","value":"volume","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/title"},{"op":"replace","value":[{"text":"volume","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","value":"paused"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","value":[{"kind":"identifier","text":"paused"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/title","value":"selectedQuality"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/fragments","value":[{"kind":"identifier","text":"selectedQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/title","value":"soundOn"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/fragments","value":[{"kind":"identifier","text":"soundOn"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/title","value":"gravity"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/fragments","value":[{"kind":"identifier","text":"gravity"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/title","value":"playbackRate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/fragments","value":[{"kind":"identifier","text":"playbackRate"}]}]}]}