{"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)selectWithMediaOption:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"text":"(","kind":"text"},{"text":"mediaOption","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"title":"select(mediaOption:)","navigatorTitle":[{"kind":"identifier","text":"selectWithMediaOption:"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/select(mediaOption:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Выбор медиадорожки."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mediaOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","text":"MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"mediaOption","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Опция, которую необходимо выбрать. Можно передавать только опции, полученные из "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection","isActive":true},{"type":"text","text":" текущего ресурса."}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Список доступных для проигрывания дорожек можно получить из "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection","isActive":true},{"type":"text","text":". Например, там может быть несколько аудиодорожек с разным языком озвучки."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/select(mediaoption:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/select(mediaoption:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/mediaSelection":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaSelection"}],"url":"\/documentation\/ovkit\/playerview\/mediaselection","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection","title":"mediaSelection","abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видео ресурсе."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaSelection","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/select(mediaOption:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectWithMediaOption:"}],"url":"\/documentation\/ovkit\/playerview\/select(mediaoption:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/select(mediaOption:)","title":"select(mediaOption:)","abstract":[{"type":"text","text":"Выбор медиадорожки."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mediaOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","abstract":[{"type":"text","text":"Опция медиадорожки."}],"url":"\/documentation\/ovkit\/mediaselectionoption","kind":"symbol","title":"MediaSelectionOption","navigatorTitle":[{"kind":"identifier","text":"MediaSelectionOption"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"selectWithMediaOption:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectWithMediaOption:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"selectWithMediaOption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","text":"OVKMediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediaOption"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Опция, которую необходимо выбрать. Можно передавать только опции, полученные из ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/mediaSelection","isActive":true},{"text":" текущего ресурса.","type":"text"}]}],"name":"mediaOption"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"mediaSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1mediaSelection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"mediaSelection"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1mediaSelection\/fragments"},{"op":"replace","value":"selectWithMediaOption:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1select(mediaOption:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectWithMediaOption:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1select(mediaOption:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"OVKMediaSelectionOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/navigatorTitle"}]}]}