{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectSubtitlesOption(_:)"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectSubtitlesOption","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)selectSubtitlesOption:","title":"selectSubtitlesOption(_:)","navigatorTitle":[{"text":"selectSubtitlesOption:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectSubtitlesOption","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"option"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","text":"SubtitlesOption"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/selectsubtitlesoption(_:)"]},{"paths":["\/documentation\/ovkit\/playerview\/selectsubtitlesoption(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Включение дорожки субтитров, которую можно выбрать из "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/subtitles","type":"reference"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","abstract":[{"text":"Дорожка субтитров.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SubtitlesOption","kind":"identifier"}],"title":"SubtitlesOption","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/subtitlesoption"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectSubtitlesOption(_:)":{"type":"topic","url":"\/documentation\/ovkit\/playerview\/selectsubtitlesoption(_:)","title":"selectSubtitlesOption(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectSubtitlesOption","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"selectSubtitlesOption:","kind":"identifier"}],"abstract":[{"text":"Включение дорожки субтитров, которую можно выбрать из ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/subtitles"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectSubtitlesOption(_:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/subtitles":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/subtitles","abstract":[{"text":"Набор доступных дорожек субтитров. Будет доступен после ","type":"text"},{"type":"codeVoice","code":"PlayerSubtitlesDelegate\/playerSubtitlesPrepared(_:)"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitles"}],"title":"subtitles","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"kind":"text","text":"]?"}],"url":"\/documentation\/ovkit\/ovkplayerview\/subtitles"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"selectSubtitlesOption:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectSubtitlesOption:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"selectSubtitlesOption:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","text":"OVKSubtitlesOption"},{"text":" *) ","kind":"text"},{"text":"option","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title","value":"OVKSubtitlesOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","op":"replace","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectSubtitlesOption(_:)\/title","value":"selectSubtitlesOption:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectSubtitlesOption(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectSubtitlesOption:","kind":"identifier"}],"op":"replace"},{"value":"subtitles","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1subtitles\/title"},{"op":"replace","value":[{"text":"subtitles","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1subtitles\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}