{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/setCustomAdControlsType(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomAdControlsType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"adControlsType","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"},{"text":".Type)","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"При открытии полноэкранного режима автоматически изменятся на стандартные. Чтобы этого не произошло, нужно в ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","isActive":true},{"type":"text","text":" изменить тип контролов на нужный у полноэкранного "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":".","type":"text"}]}],"name":"Note","type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/setcustomadcontrolstype(_:)"]}],"metadata":{"symbolKind":"method","externalID":"s:5OVKit10PlayerViewC23setCustomAdControlsTypeyyAA0bgC8Protocol_pXpF","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomAdControlsType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"},{"kind":"text","text":".Type)"}],"title":"setCustomAdControlsType(_:)","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"text":"Устанавливает тип контролов, которые будут показываться при просмотре рекламы в этом ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"title":"PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/setCustomAdControlsType(_:)":{"role":"symbol","kind":"symbol","abstract":[{"text":"Устанавливает тип контролов, которые будут показываться при просмотре рекламы в этом ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/setcustomadcontrolstype(_:)","title":"setCustomAdControlsType(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/setCustomAdControlsType(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomAdControlsType","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"},{"text":".Type)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerManagerDelegate/playerView(_:willShowFullscreen:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerManagerDelegate\/playerView(_:willShowFullscreen:)","url":"\/documentation\/ovkit\/playermanagerdelegate\/playerview(_:willshowfullscreen:)","title":"playerView(_:willShowFullscreen:)","required":true,"abstract":[{"text":"Плеер был показан в полноэкранном режиме.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"willShowFullscreen"},{"kind":"text","text":": "},{"text":"FullscreenContentViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKFullscreenContentViewController"},{"text":") -> ","kind":"text"},{"text":"FullscreenController","preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"playerView:willShowFullscreen:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"playerView:willShowFullscreen:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerManagerDelegate~1playerView(_:willShowFullscreen:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playerView:willShowFullscreen:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}