{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showFullscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"video"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"playerViewSetupBlock"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Видео, которое нужно открыть."}],"type":"paragraph"}],"name":"video"},{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":", на котором презентуется полноэкранный плеер. Это должен быть самый верхний в иерархии контроллер."}],"type":"paragraph"}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать."}],"type":"paragraph"}],"name":"fromTime"},{"content":[{"inlineContent":[{"type":"text","text":"Выполнять ли открытие с анимацией."}],"type":"paragraph"}],"name":"animated"},{"content":[{"inlineContent":[{"type":"text","text":"Блок для предварительной настройки, в который передается "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":", которое будет показано в полноэкранном режиме."}],"type":"paragraph"}],"name":"playerViewSetupBlock"},{"content":[{"inlineContent":[{"type":"text","text":"Автоматически запустить воспроизведение после открытия. По умолчанию "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"autoplay"},{"content":[{"inlineContent":[{"type":"text","text":"Блок, который будет вызван после показа полноэкранного режима. В него передается "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":", который находится в полноэкранном режиме."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)"},"abstract":[{"text":"Открыть полноэкранный плеер.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/showfullscreen(_:on:fromtime:animated:playerviewsetupblock:autoplay:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/showfullscreen(_:on:fromtime:animated:playerviewsetupblock:autoplay:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Type Method","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(cm)showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","title":"showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)","role":"symbol","navigatorTitle":[{"text":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","kind":"identifier"}],"extendedModule":"OVKit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"playerViewSetupBlock","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"title":"VideoType","abstract":[{"type":"text","text":"Модель видео, которую может воспроизвести OVKit."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)":{"kind":"symbol","title":"showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)","abstract":[{"text":"Открыть полноэкранный плеер.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/showfullscreen(_:on:fromtime:animated:playerviewsetupblock:autoplay:completion:)","role":"symbol","navigatorTitle":[{"text":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showFullscreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fromTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"playerViewSetupBlock","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showFullscreen:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType","text":"id<OVKVideoType>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"video"},{"kind":"text","text":" "},{"kind":"identifier","text":"on:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"fromTime","kind":"internalParam"},{"kind":"text","text":" "},{"text":"animated:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"kind":"text","text":" "},{"text":"playerViewSetupBlock:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"playerViewSetupBlock","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoplay:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoplay"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Видео, которое нужно открыть."}],"type":"paragraph"}],"name":"video"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":", на котором презентуется полноэкранный плеер. Это должен быть самый верхний в иерархии контроллер."}],"type":"paragraph"}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"Для видео: время, с которого начать проигрывание. Для трансляции: кол-во секунд, на сколько трансляция должна отставать."}],"type":"paragraph"}],"name":"fromTime"},{"content":[{"inlineContent":[{"type":"text","text":"Выполнять ли открытие с анимацией."}],"type":"paragraph"}],"name":"animated"},{"content":[{"inlineContent":[{"type":"text","text":"Блок для предварительной настройки, в который передается "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", которое будет показано в полноэкранном режиме."}],"type":"paragraph"}],"name":"playerViewSetupBlock"},{"content":[{"inlineContent":[{"type":"text","text":"Автоматически запустить воспроизведение после открытия. По умолчанию "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"autoplay"},{"content":[{"inlineContent":[{"type":"text","text":"Блок, который будет вызван после показа полноэкранного режима. В него передается "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":", который находится в полноэкранном режиме."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments"},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"},{"value":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"showFullscreen:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1showFullscreen(_:on:fromTime:animated:playerViewSetupBlock:autoplay:completion:)\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}