{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)showsLastVideoFrameOnPreview","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","title":"showsLastVideoFrameOnPreview","navigatorTitle":[{"text":"showsLastVideoFrameOnPreview","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsLastVideoFrameOnPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"kind":"symbol","abstract":[{"type":"text","text":"Показывать последний кадр видео вместо изображения предпросмотра."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/showsLastVideoFrameOnPreview"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsLastVideoFrameOnPreview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Если активно при остановке видео, то любой следующий плеер, где эта опция также активна, будет показывать в ","type":"text"},{"inlineContent":[{"text":"preview","type":"text"}],"type":"emphasis"},{"text":" последний кадр, на котором остановилось воспроизведение в прошлый раз.","type":"text"}]},{"name":"Warning","style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Действует только при включенной опции ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop"},{"text":".","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию значение "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/showslastvideoframeonpreview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/showslastvideoframeonpreview"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/showsLastVideoFrameOnPreview":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/showsLastVideoFrameOnPreview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsLastVideoFrameOnPreview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"showsLastVideoFrameOnPreview","kind":"identifier"}],"title":"showsLastVideoFrameOnPreview","role":"symbol","abstract":[{"type":"text","text":"Показывать последний кадр видео вместо изображения предпросмотра."}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/showslastvideoframeonpreview","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/savesPlaybackTimeOnStop":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/savesPlaybackTimeOnStop","role":"symbol","abstract":[{"type":"text","text":"Сохранять время воспроизведения для видео, на котором было остановлено проигрывание."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savesPlaybackTimeOnStop","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"savesPlaybackTimeOnStop","navigatorTitle":[{"text":"savesPlaybackTimeOnStop","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/savesplaybacktimeonstop"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"showsLastVideoFrameOnPreview","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"showsLastVideoFrameOnPreview"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsLastVideoFrameOnPreview"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1showsLastVideoFrameOnPreview\/title","value":"showsLastVideoFrameOnPreview"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1showsLastVideoFrameOnPreview\/fragments","value":[{"kind":"identifier","text":"showsLastVideoFrameOnPreview"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/title","op":"replace","value":"savesPlaybackTimeOnStop"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1savesPlaybackTimeOnStop\/fragments","op":"replace","value":[{"text":"savesPlaybackTimeOnStop","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}