{"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"soundOn"}],"role":"symbol","title":"soundOn","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)soundOn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"seeAlsoSections":[{"title":"Параметры воспроизведения","anchor":"Параметры-воспроизведения","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"],"generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Значение сбросится при вызове ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","type":"reference","isActive":true},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"По умолчанию ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/soundon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/soundon"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","interfaceLanguage":"swift"},"abstract":[{"text":"Включение\/выключение звука.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","abstract":[{"text":"Пауза воспроизведения.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/paused","kind":"symbol","title":"paused","navigatorTitle":[{"text":"paused","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/gravity":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","abstract":[{"text":"Текущий режим отображения картинки в плеере.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/gravity","title":"gravity","kind":"symbol","navigatorTitle":[{"text":"gravity","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/soundOn":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Включение\/выключение звука."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","url":"\/documentation\/ovkit\/playerview\/soundon","title":"soundOn","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"soundOn"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/volume":{"navigatorTitle":[{"kind":"identifier","text":"volume"}],"title":"volume","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Регулировка громкости звука в плеере."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/ovkit\/playerview\/volume"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playbackRate":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","abstract":[{"type":"text","text":"Скорость воспроизведения."}],"url":"\/documentation\/ovkit\/playerview\/playbackrate","kind":"symbol","title":"playbackRate","navigatorTitle":[{"kind":"identifier","text":"playbackRate"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectedQuality":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality","abstract":[{"type":"text","text":"Качество, выбранное пользователем."}],"url":"\/documentation\/ovkit\/playerview\/selectedquality","kind":"symbol","title":"selectedQuality","navigatorTitle":[{"kind":"identifier","text":"selectedQuality"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"title":"playerViewOnScreen","kind":"symbol","role":"symbol","abstract":[{"text":"Устанавливает видимость плеера на экране.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewOnScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/playerview\/playerviewonscreen"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/prepareForReuse()":{"navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"title":"prepareForReuse()","kind":"symbol","role":"symbol","abstract":[{"text":"Подготовка ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" к переиспользованию.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepareForReuse"},{"text":"()","kind":"text"}],"url":"\/documentation\/ovkit\/playerview\/prepareforreuse()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"soundOn"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"soundOn"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"],"title":"Параметры воспроизведения","anchor":"Параметры-воспроизведения"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"soundOn","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","op":"replace","value":"paused"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","op":"replace","value":[{"kind":"identifier","text":"paused"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/title","op":"replace","value":"gravity"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/fragments","op":"replace","value":[{"kind":"identifier","text":"gravity"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/title","op":"replace","value":"soundOn"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/fragments","op":"replace","value":[{"kind":"identifier","text":"soundOn"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/title","op":"replace","value":"volume"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/fragments","op":"replace","value":[{"kind":"identifier","text":"volume"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/title","op":"replace","value":"playbackRate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/fragments","op":"replace","value":[{"kind":"identifier","text":"playbackRate"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/title","op":"replace","value":"selectedQuality"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"selectedQuality"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title","op":"replace","value":"playerViewOnScreen"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","op":"replace","value":[{"kind":"identifier","text":"playerViewOnScreen"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/title","op":"replace","value":"prepareForReuse"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}