{"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)startButtonBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startButtonBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreviewPlayButtonBehavior","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior"}],"title":"startButtonBehavior","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"startButtonBehavior"}]},"abstract":[{"text":"Поведение кнопки ","type":"text"},{"inlineContent":[{"type":"text","text":"Play"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/startbuttonbehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/startbuttonbehavior"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startButtonBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"PreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Используется поведение "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","type":"reference","isActive":true},{"type":"text","text":" по умолчанию, если не указать иное."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/startButtonBehavior"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"kind":"symbol","abstract":[{"text":"Поведение кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"url":"\/documentation\/ovkit\/previewplaybuttonbehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewPlayButtonBehavior"}],"role":"symbol","navigatorTitle":[{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","title":"PreviewPlayButtonBehavior"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/startButtonBehavior":{"navigatorTitle":[{"kind":"identifier","text":"startButtonBehavior"}],"title":"startButtonBehavior","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startButtonBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"PreviewPlayButtonBehavior","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Поведение кнопки "},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"type":"text","text":", которая показывается на превью до начала проигрывания видео."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/startButtonBehavior","url":"\/documentation\/ovkit\/playerview\/startbuttonbehavior"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"startButtonBehavior","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"startButtonBehavior","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKPreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior"},{"text":" * ","kind":"text"},{"text":"startButtonBehavior","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPreviewPlayButtonBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments"},{"value":[{"kind":"identifier","text":"OVKPreviewPlayButtonBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/navigatorTitle"},{"value":"startButtonBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1startButtonBehavior\/title"},{"value":[{"text":"startButtonBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1startButtonBehavior\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}