{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"stop"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(im)stop","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stop()","role":"symbol"},"abstract":[{"type":"text","text":"Остановка и очистка плеера."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(fromTime:initialQuality:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/seekToTime(_:initiatePlay:)"],"anchor":"Цикл-воспроизведения","title":"Цикл воспроизведения"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]},{"mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer"],"kind":"mentions"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/stop()"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(fromTime:initialQuality:userInitiated:)":{"title":"play(fromTime:initialQuality:userInitiated:)","url":"\/documentation\/ovkit\/playerview\/play(fromtime:initialquality:userinitiated:)","navigatorTitle":[{"kind":"identifier","text":"playFromTime:initialQuality:userInitiated:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Запуск воспроизведения видео; или снятие с паузы, если ранее метод уже был вызван.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(fromTime:initialQuality:userInitiated:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/video":{"title":"video","url":"\/documentation\/ovkit\/playerview\/video","navigatorTitle":[{"kind":"identifier","text":"video"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Модель видеозаписи для воспроизведения."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/stop()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/stop()","url":"\/documentation\/ovkit\/playerview\/stop()","navigatorTitle":[{"kind":"identifier","text":"stop"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Остановка и очистка плеера."}],"type":"topic","title":"stop()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/CreatePlayer":{"url":"\/documentation\/ovkit\/createplayer","title":"Создание плеера","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","type":"topic","role":"article","abstract":[{"type":"text","text":"Первые шаги после интеграции."}],"kind":"article"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"navigatorTitle":[{"kind":"identifier","text":"paused"}],"url":"\/documentation\/ovkit\/playerview\/paused","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","type":"topic","title":"paused","role":"symbol","abstract":[{"text":"Пауза воспроизведения.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/prepareForReuse()":{"title":"prepareForReuse()","url":"\/documentation\/ovkit\/playerview\/prepareforreuse()","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Подготовка ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":" к переиспользованию.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/seekToTime(_:initiatePlay:)":{"navigatorTitle":[{"kind":"identifier","text":"seekToTime:initiatePlay:"}],"url":"\/documentation\/ovkit\/playerview\/seektotime(_:initiateplay:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/seekToTime(_:initiatePlay:)","type":"topic","title":"seekToTime(_:initiatePlay:)","role":"symbol","abstract":[{"text":"Перемотка видео.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekToTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initiatePlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stop","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Цикл-воспроизведения","title":"Цикл воспроизведения","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CreatePlayer","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/video","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/prepareForReuse()","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(fromTime:initialQuality:userInitiated:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/seekToTime(_:initiatePlay:)"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(fromTime:initialQuality:userInitiated:)\/title","op":"replace","value":"playFromTime:initialQuality:userInitiated:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(fromTime:initialQuality:userInitiated:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playFromTime:initialQuality:userInitiated:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/title","op":"replace","value":"video"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1video\/fragments","op":"replace","value":[{"kind":"identifier","text":"video"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/title","op":"replace","value":"stop"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1stop()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","op":"replace","value":"paused"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","op":"replace","value":[{"kind":"identifier","text":"paused"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/title","op":"replace","value":"prepareForReuse"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1prepareForReuse()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1seekToTime(_:initiatePlay:)\/title","op":"replace","value":"seekToTime:initiatePlay:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1seekToTime(_:initiatePlay:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekToTime:initiatePlay:"}]}]}]}