{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)subtitles","navigatorTitle":[{"text":"subtitles","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"subtitles","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","text":"SubtitlesOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"subtitles"},"abstract":[{"text":"Набор доступных дорожек субтитров. Будет доступен после ","type":"text"},{"code":"PlayerSubtitlesDelegate\/playerSubtitlesPrepared(_:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playerview\/subtitles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/subtitles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/subtitles","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/subtitles":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/subtitles","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitles"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","text":"SubtitlesOption"},{"text":"]?","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"subtitles"}],"url":"\/documentation\/ovkit\/playerview\/subtitles","kind":"symbol","role":"symbol","title":"subtitles","abstract":[{"text":"Набор доступных дорожек субтитров. Будет доступен после ","type":"text"},{"type":"codeVoice","code":"PlayerSubtitlesDelegate\/playerSubtitlesPrepared(_:)"},{"text":".","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","abstract":[{"type":"text","text":"Дорожка субтитров."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/subtitlesoption","title":"SubtitlesOption","navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"subtitles","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"subtitles","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<OVKSubtitlesOption *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"subtitles","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"subtitles","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1subtitles\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1subtitles\/fragments","value":[{"text":"subtitles","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title","op":"replace","value":"OVKSubtitlesOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}]}]}