{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","isActive":true,"type":"reference"},{"text":" для текущего видео.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailProvider"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)thumbnailProvider","roleHeading":"Instance Property","title":"thumbnailProvider","navigatorTitle":[{"kind":"identifier","text":"thumbnailProvider"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/thumbnailProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Изменяется после установки свойства "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":", а также может измениться после анимированного переноса плеера. Значение "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает, что в видео отсутствует раскадровка для перемотки."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/thumbnailprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/thumbnailprovider"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/thumbnailprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"abstract":[{"text":"Класс, который асинхронно получает thumbnail для указанного времени видео.","type":"text"}],"kind":"symbol","title":"ThumbnailProvider"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"navigatorTitle":[{"text":"Video","kind":"identifier"}],"title":"Video","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/video","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/thumbnailProvider":{"title":"thumbnailProvider","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/thumbnailProvider","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"thumbnailProvider"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"thumbnailProvider"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider"},{"text":" для текущего видео.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/thumbnailprovider"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"url":"\/documentation\/ovkit\/playerview","role":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"thumbnailProvider"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"thumbnailProvider"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","text":"OVKThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"thumbnailProvider"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKThumbnailProvider","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}]},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","value":"thumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1thumbnailProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1thumbnailProvider\/fragments","value":[{"kind":"identifier","text":"thumbnailProvider"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}]}]}