{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playerview\/transition(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playerview\/transition(to:)"]}],"seeAlsoSections":[{"title":"Переходы","anchor":"Переходы","generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"playerView","content":[{"inlineContent":[{"type":"text","text":"Плеер, в который осуществляется переход."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"mentions","mentions":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)"},"metadata":{"navigatorTitle":[{"text":"transitionTo:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"extendedModule":"OVKit","roleHeading":"Instance Method","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)transitionTo:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"title":"transition(to:)","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"text":"Переход плеера в другое ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":" без анимации.","type":"text"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/transition(to:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transitionTo:"}],"url":"\/documentation\/ovkit\/playerview\/transition(to:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/transition(to:)","abstract":[{"text":"Переход плеера в другое ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":" без анимации.","type":"text"}],"kind":"symbol","title":"transition(to:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","title":"FullscreenSupplementaryController","kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/minimizeToPiP(initialVelocity:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimizeToPiP"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"initialVelocity"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/minimizetopip(initialvelocity:completion:)","title":"minimizeToPiP(initialVelocity:completion:)","abstract":[{"text":"Свернуть плеер в Picture in Picture.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)":{"role":"symbol","title":"maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenincurrentorientation(forceblackbackground:completion:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenInCurrentOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forceBlackBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Разворачивание плеера в полноэкранный режим с сохранением текущей ориентации.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"title":"createAnimatedTransition(to:in:)","url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","abstract":[{"text":"Создание вспомогательного объекта для анимированного перехода плеера из текущего ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":" в место назначения."}],"navigatorTitle":[{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnimatedTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximizeToFullscreenWithSupplementary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prepareBlock"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:5OVKit20FullscreenControllera","kind":"typeIdentifier","text":"FullscreenController"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreenwithsupplementary(prepareblock:completion:)","title":"maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","abstract":[{"text":"Показывает ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":", автоматически открыв при необходимости полноэкранный режим.","type":"text"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)"},"doc://onevideo.OVKit/documentation/OVKit/Transitions":{"title":"Переходы между плеерами","url":"\/documentation\/ovkit\/transitions","abstract":[{"text":"Непрерывный перенос воспроизведения из одного ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":" в другой.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","kind":"article","type":"topic","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/maximizeToFullscreen(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximizeToFullscreen"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier","text":"PlayerView"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maximizeToFullscreenWithCompletion:"}],"url":"\/documentation\/ovkit\/playerview\/maximizetofullscreen(completion:)","abstract":[{"text":"Разворачивание плеера в полноэкранный режим.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","kind":"symbol","title":"maximizeToFullscreen(completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"transitionTo:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transitionTo:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Transitions","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreen(completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/maximizeToFullscreenWithSupplementary(prepareBlock:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/minimizeToPiP(initialVelocity:completion:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)"],"title":"Переходы","anchor":"Переходы","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"transitionTo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, в который осуществляется переход.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"transitionTo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transitionTo:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1transition(to:)\/fragments"},{"op":"replace","value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"op":"replace","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle"},{"op":"replace","value":"minimizeToPiPWithInitialVelocity:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"minimizeToPiPWithInitialVelocity:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1minimizeToPiP(initialVelocity:completion:)\/fragments"},{"op":"replace","value":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreenInCurrentOrientationWithForceBlackBackground:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenInCurrentOrientation(forceBlackBackground:completion:)\/fragments"},{"op":"replace","value":"createAnimatedTransitionTo:in:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createAnimatedTransitionTo:in:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"},{"op":"replace","value":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreenWithSupplementaryWithPrepareBlock:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreenWithSupplementary(prepareBlock:completion:)\/fragments"},{"op":"replace","value":"maximizeToFullscreenWithCompletion:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"maximizeToFullscreenWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1maximizeToFullscreen(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}