{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Обновление статуса трансляции в объекте "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Если передать статус  "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","isActive":true,"type":"reference"},{"type":"text","text":" — единственный проигрываемый статус. Live сам не начнется если играл ранее, необходим вызов "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Если передать отличный от "},{"code":".started","type":"codeVoice"},{"type":"text","text":" — live остановится, появится заглушка."}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/updatelivestatus(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/updatelivestatus(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/updateLiveStatus(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","text":"LiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateLiveStatus:"}],"role":"symbol","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(im)updateLiveStatus:","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"symbolKind":"method","extendedModule":"OVKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","text":"LiveStatus"},{"kind":"text","text":")"}],"title":"updateLiveStatus(_:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/updateLiveStatus(_:)":{"title":"updateLiveStatus(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/updateLiveStatus(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateLiveStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LiveStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateLiveStatus:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview\/updatelivestatus(_:)","abstract":[{"type":"text","text":"Обновление статуса трансляции в объекте "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Если передать статус  "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","type":"reference","isActive":true},{"type":"text","text":" — единственный проигрываемый статус. Live сам не начнется если играл ранее, необходим вызов "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Если передать отличный от "},{"type":"codeVoice","code":".started"},{"type":"text","text":" — live остановится, появится заглушка."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Video","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/video","title":"Video","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus/started":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus\/started","navigatorTitle":[{"kind":"identifier","text":"OVKLiveStatusStarted"}],"kind":"symbol","abstract":[{"type":"text","text":"Live начался, видеопоток идет, должны быть live ссылки в files."}],"role":"symbol","url":"\/documentation\/ovkit\/livestatus\/started","title":"LiveStatus.started"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/LiveStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LiveStatus","kind":"identifier"}],"navigatorTitle":[{"text":"LiveStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","abstract":[],"url":"\/documentation\/ovkit\/livestatus","title":"LiveStatus","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/play(userInitiated:)":{"url":"\/documentation\/ovkit\/playerview\/play(userinitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/play(userInitiated:)","abstract":[{"type":"text","text":"Запуск проигрывания видео; или снятие с паузы, если ранее метод уже был вызван."}],"title":"play(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"playWithUserInitiated:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateLiveStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateLiveStatus:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateLiveStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LiveStatus","preciseIdentifier":"c:@M@OVKit@E@OVKLiveStatus","kind":"typeIdentifier","text":"OVKLiveStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1updateLiveStatus(_:)\/title","value":"updateLiveStatus:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1updateLiveStatus(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateLiveStatus:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle","value":[{"text":"OVKVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/title","value":"OVKLiveStatusStarted"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus~1started\/fragments","value":[{"text":"OVKLiveStatusStarted","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/title","value":"OVKLiveStatus"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/fragments","value":[{"text":"OVKLiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LiveStatus\/navigatorTitle","value":[{"kind":"identifier","text":"OVKLiveStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/title","value":"playWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1play(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithUserInitiated:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}