{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)volume","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","title":"volume","navigatorTitle":[{"kind":"identifier","text":"volume"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}]},"abstract":[{"text":"Регулировка громкости звука в плеере.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"],"generated":true,"anchor":"Параметры-воспроизведения","title":"Параметры воспроизведения"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/playerview\/volume"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playerview\/volume"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playbackRate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"kind":"identifier","text":"playbackRate"}],"title":"playbackRate","role":"symbol","abstract":[{"text":"Скорость воспроизведения.","type":"text"}],"url":"\/documentation\/ovkit\/playerview\/playbackrate","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"type":"topic","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/selectedQuality":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality","abstract":[{"type":"text","text":"Качество, выбранное пользователем."}],"url":"\/documentation\/ovkit\/playerview\/selectedquality","title":"selectedQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedQuality"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/gravity":{"kind":"symbol","type":"topic","title":"gravity","abstract":[{"type":"text","text":"Текущий режим отображения картинки в плеере."}],"url":"\/documentation\/ovkit\/playerview\/gravity","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlayerViewGravity","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","navigatorTitle":[{"text":"gravity","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/paused":{"type":"topic","url":"\/documentation\/ovkit\/playerview\/paused","kind":"symbol","abstract":[{"type":"text","text":"Пауза воспроизведения."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","navigatorTitle":[{"kind":"identifier","text":"paused"}],"title":"paused"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/playerViewOnScreen":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Устанавливает видимость плеера на экране."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","url":"\/documentation\/ovkit\/playerview\/playerviewonscreen","title":"playerViewOnScreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerViewOnScreen"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/soundOn":{"kind":"symbol","abstract":[{"text":"Включение\/выключение звука.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","type":"topic","url":"\/documentation\/ovkit\/playerview\/soundon","title":"soundOn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"soundOn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"soundOn","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/volume":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/volume","abstract":[{"type":"text","text":"Регулировка громкости звука в плеере."}],"url":"\/documentation\/ovkit\/playerview\/volume","title":"volume","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"volume","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"volume","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"volume","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Параметры воспроизведения","generated":true,"anchor":"Параметры-воспроизведения","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playerViewOnScreen","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/soundOn","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/paused","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/gravity","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/playbackRate","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/selectedQuality"]}]},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playbackRate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playbackRate\/fragments","value":[{"text":"playbackRate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/title","op":"replace","value":"selectedQuality"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1selectedQuality\/fragments","op":"replace","value":[{"text":"selectedQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/title","op":"replace","value":"gravity"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1gravity\/fragments","op":"replace","value":[{"text":"gravity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/title","value":"paused","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1paused\/fragments","value":[{"kind":"identifier","text":"paused"}],"op":"replace"},{"op":"replace","value":"playerViewOnScreen","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1playerViewOnScreen\/fragments","value":[{"kind":"identifier","text":"playerViewOnScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/title","value":"soundOn","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1soundOn\/fragments","value":[{"text":"soundOn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/title","value":"volume","op":"replace"},{"op":"replace","value":[{"text":"volume","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1volume\/fragments"}]}]}