{"metadata":{"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchDurationOf"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inBatchSize"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy(im)indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/simpleprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/simpleprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"prefetchDurationOf"},{"kind":"text","text":" "},{"text":"resource","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inBatchSize"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkBandwidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"prefetcher","content":[{"inlineContent":[{"type":"text","text":"Вызывающий "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"resource","content":[{"type":"paragraph","inlineContent":[{"text":"Видео, которое будет запрефетчено.","type":"text"}]}]},{"name":"offset","content":[{"inlineContent":[{"type":"text","text":"Сдвиг относительно текущего "},{"type":"codeVoice","code":"IndexPath"},{"text":" (","type":"text"},{"code":"0","type":"codeVoice"},{"text":" означает текущий ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Общее количество видеозаписей для префетча, полученное ранее вызовом "},{"type":"codeVoice","code":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"size"},{"name":"networkBandwidth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Оценочная пропускная способность сети в данный момент в "},{"code":"bps","type":"codeVoice"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Длительность префетча видеозаписи. Если вернуть ","type":"text"},{"type":"codeVoice","code":"0"},{"text":", префетчер пропустит эту видеозапись.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"]]},"abstract":[{"text":"Получение длительности префетча для видеозаписи.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"url":"\/documentation\/ovkit\/simpleprefetchstrategy","title":"SimplePrefetchStrategy","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SimplePrefetchStrategy"}],"abstract":[{"text":"Стратегия, которая отвечает константными значениями.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","kind":"symbol","title":"VideoType","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"url":"\/documentation\/ovkit\/videotype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoType"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"kind":"symbol","title":"IndexPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/indexprefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"indexPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchDurationOf"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"networkBandwidth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"abstract":[{"text":"Получение длительности префетча для видеозаписи.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"url":"\/documentation\/ovkit\/simpleprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"indexPrefetcher:"},{"kind":"text","text":"("},{"text":"OVKIndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"text":" ","kind":"text"},{"text":"prefetchDurationOf:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKVideoType>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"text":") ","kind":"text"},{"text":"resource","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offset:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inBatchSize:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"networkBandwidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"networkBandwidth"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title","op":"replace","value":"OVKSimplePrefetchStrategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments","value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}]},{"value":"OVKVideoType","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace"},{"value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}