{"metadata":{"title":"init(aheadCount:duration:prefetchReached:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"aheadCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"prefetchReached","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithAheadCount:duration:prefetchReached:","kind":"identifier"}],"role":"symbol","symbolKind":"init","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","externalID":"c:@M@OVKit@objc(cs)OVKSimplePrefetchStrategy(im)initWithAheadCount:duration:prefetchReached:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aheadCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"prefetchReached","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Количество видеозаписей впереди для префетча.","type":"text"}],"type":"paragraph"}],"name":"aheadCount"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Длительность префетча.","type":"text"}]}],"name":"duration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Префетчить ли видео с нулевым индексом.","type":"text"}]}],"name":"prefetchReached"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init(aheadCount:duration:prefetchReached:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"]]},"sections":[],"abstract":[{"text":"Создание стратегии.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/simpleprefetchstrategy\/init(aheadcount:duration:prefetchreached:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/simpleprefetchstrategy\/init(aheadcount:duration:prefetchreached:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy":{"url":"\/documentation\/ovkit\/simpleprefetchstrategy","role":"symbol","title":"SimplePrefetchStrategy","type":"topic","abstract":[{"type":"text","text":"Стратегия, которая отвечает константными значениями."}],"kind":"symbol","navigatorTitle":[{"text":"SimplePrefetchStrategy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SimplePrefetchStrategy","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit/SimplePrefetchStrategy/init(aheadCount:duration:prefetchReached:)":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SimplePrefetchStrategy\/init(aheadCount:duration:prefetchReached:)","url":"\/documentation\/ovkit\/simpleprefetchstrategy\/init(aheadcount:duration:prefetchreached:)","title":"init(aheadCount:duration:prefetchReached:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aheadCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchReached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithAheadCount:duration:prefetchReached:","kind":"identifier"}],"abstract":[{"text":"Создание стратегии.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithAheadCount:duration:prefetchReached:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAheadCount:duration:prefetchReached:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithAheadCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aheadCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"prefetchReached:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"prefetchReached","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"aheadCount","content":[{"inlineContent":[{"type":"text","text":"Количество видеозаписей впереди для префетча."}],"type":"paragraph"}]},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"text":"Длительность префетча.","type":"text"}]}]},{"name":"prefetchReached","content":[{"inlineContent":[{"text":"Префетчить ли видео с нулевым индексом.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKSimplePrefetchStrategy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/title"},{"value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/fragments"},{"value":[{"text":"OVKSimplePrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy\/navigatorTitle"},{"value":"initWithAheadCount:duration:prefetchReached:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init(aheadCount:duration:prefetchReached:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAheadCount:duration:prefetchReached:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SimplePrefetchStrategy~1init(aheadCount:duration:prefetchReached:)\/fragments"}]}]}