{"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logInterstitialRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"logInterstitialRequestWithInfo:","kind":"identifier"}],"required":true,"role":"symbol","title":"logInterstitialRequest(info:)","externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialRequestWithInfo:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"Информация о прерывании","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialrequest(info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialrequest(info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialRequest(info:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"Уведомляет о запросе конкретного прерывания."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","type":"topic","role":"symbol","abstract":[{"text":"Делегат для статистики прерываний.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"title":"InterstitialStatsDelegate","navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialRequest(info:)":{"url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialrequest(info:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialRequest(info:)","role":"symbol","abstract":[{"text":"Уведомляет о запросе конкретного прерывания.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logInterstitialRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"text":"InterstitialInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":")","kind":"text"}],"title":"logInterstitialRequest(info:)","required":true,"navigatorTitle":[{"text":"logInterstitialRequestWithInfo:","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"url":"\/documentation\/ovkit\/interstitialinfo","navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}],"type":"topic","title":"InterstitialInfo","abstract":[{"type":"text","text":"Информация о прерывании."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"logInterstitialRequestWithInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialRequestWithInfo:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"logInterstitialRequestWithInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKInterstitialInfo>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":") ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"info","content":[{"inlineContent":[{"text":"Информация о прерывании","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title","value":"OVKInterstitialStatsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialRequest(info:)\/title","value":"logInterstitialRequestWithInfo:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialRequest(info:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"logInterstitialRequestWithInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title","value":"OVKInterstitialInfo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialInfo"}],"op":"replace"}]}]}