{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialStart(info:duration:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"logInterstitialStartWithInfo:duration:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialStartWithInfo:duration:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InterstitialInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"required":true,"title":"logInterstitialStart(info:duration:)","role":"symbol"},"abstract":[{"text":"Уведомляет о начале воспроизведения прерывания.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialStart","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","text":"InterstitialInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"info","content":[{"inlineContent":[{"text":"Информация о прерывании","type":"text"}],"type":"paragraph"}]},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Длительность воспроизведения в секундах"}]}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialstart(info:duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialstart(info:duration:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","type":"topic","title":"InterstitialInfo","role":"symbol","abstract":[{"text":"Информация о прерывании.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialStart(info:duration:)":{"url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialstart(info:duration:)","navigatorTitle":[{"text":"logInterstitialStartWithInfo:duration:","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialStart"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","text":"InterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Уведомляет о начале воспроизведения прерывания.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialStart(info:duration:)","kind":"symbol","title":"logInterstitialStart(info:duration:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"url":"\/documentation\/ovkit\/interstitialstatsdelegate","navigatorTitle":[{"kind":"identifier","text":"InterstitialStatsDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialStatsDelegate"}],"abstract":[{"text":"Делегат для статистики прерываний.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","kind":"symbol","title":"InterstitialStatsDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logInterstitialStartWithInfo:duration:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialStartWithInfo:duration:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"logInterstitialStartWithInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<OVKInterstitialInfo>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":") ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Информация о прерывании","type":"text"}]}],"name":"info"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Длительность воспроизведения в секундах","type":"text"}]}],"name":"duration"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"OVKInterstitialInfo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title","op":"replace"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments","op":"replace"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","op":"replace"},{"value":"logInterstitialStartWithInfo:duration:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialStart(info:duration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"logInterstitialStartWithInfo:duration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialStart(info:duration:)\/fragments"},{"value":"OVKInterstitialStatsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title"},{"value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments"},{"value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle"}]}]}