{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialEmpty"},{"kind":"text","text":"("},{"kind":"externalParam","text":"responseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"responseTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Время отклика сервера в секундах"}]}]}],"kind":"parameters"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialempty(responsetime:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialempty(responsetime:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialEmpty(responseTime:)","interfaceLanguage":"swift"},"abstract":[{"text":"Уведомляет о получении пустого ответа при запросе прерываний.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialEmptyWithResponseTime:","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialEmpty","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","title":"logInterstitialEmpty(responseTime:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"logInterstitialEmptyWithResponseTime:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialEmpty(responseTime:)":{"role":"symbol","abstract":[{"text":"Уведомляет о получении пустого ответа при запросе прерываний.","type":"text"}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialEmpty"},{"kind":"text","text":"("},{"kind":"externalParam","text":"responseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialEmpty(responseTime:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialempty(responsetime:)","kind":"symbol","title":"logInterstitialEmpty(responseTime:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Делегат для статистики прерываний."}],"navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","kind":"symbol","title":"InterstitialStatsDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"logInterstitialEmptyWithResponseTime:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"},{"kind":"text","text":"("},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"text":"responseTime","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"responseTime","content":[{"inlineContent":[{"type":"text","text":"Время отклика сервера в секундах"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"logInterstitialEmptyWithResponseTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialEmpty(responseTime:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialEmpty(responseTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialEmptyWithResponseTime:"}]},{"op":"replace","value":"OVKInterstitialStatsDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments"},{"op":"replace","value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle"}]}]}