{"kind":"symbol","abstract":[{"type":"text","text":"Уведомляет о прогрессе воспроизведения прерывания."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"variants":[{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialprogress(info:playtime:duration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialprogress(info:playtime:duration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","text":"InterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Информация о прерывании","type":"text"}]}],"name":"info"},{"content":[{"inlineContent":[{"type":"text","text":"Время проигрывания в секундах"}],"type":"paragraph"}],"name":"playTime"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Общая длительность прерывания"}]}],"name":"duration"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialProgress(info:playTime:duration:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","text":"InterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"logInterstitialProgressWithInfo:playTime:duration:"}],"title":"logInterstitialProgress(info:playTime:duration:)","externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialProgressWithInfo:playTime:duration:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"abstract":[{"text":"Делегат для статистики прерываний.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/interstitialstatsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialStatsDelegate"}],"role":"symbol","navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","title":"InterstitialStatsDelegate"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialProgress(info:playTime:duration:)":{"required":true,"url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialprogress(info:playtime:duration:)","title":"logInterstitialProgress(info:playTime:duration:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialProgress(info:playTime:duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Уведомляет о прогрессе воспроизведения прерывания."}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialProgressWithInfo:playTime:duration:"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"title":"InterstitialInfo","navigatorTitle":[{"text":"InterstitialInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","abstract":[{"text":"Информация о прерывании.","type":"text"}],"url":"\/documentation\/ovkit\/interstitialinfo","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialInfo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"logInterstitialProgressWithInfo:playTime:duration:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"logInterstitialProgressWithInfo:playTime:duration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"logInterstitialProgressWithInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKInterstitialInfo","text":"id<OVKInterstitialInfo>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"playTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"playTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Информация о прерывании"}],"type":"paragraph"}],"name":"info"},{"content":[{"inlineContent":[{"type":"text","text":"Время проигрывания в секундах"}],"type":"paragraph"}],"name":"playTime"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Общая длительность прерывания"}]}],"name":"duration"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKInterstitialStatsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title"},{"value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments"},{"value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle"},{"value":"logInterstitialProgressWithInfo:playTime:duration:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialProgress(info:playTime:duration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialProgressWithInfo:playTime:duration:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialProgress(info:playTime:duration:)\/fragments"},{"value":"OVKInterstitialInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","value":[{"text":"OVKInterstitialInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}