{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialSkip(info:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Уведомляет о пропуске прерывания."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"info","content":[{"inlineContent":[{"type":"text","text":"Информация о прерывании"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialskip(info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialskip(info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","kind":"typeIdentifier","text":"InterstitialInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}],"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialSkipWithInfo:","role":"symbol","title":"logInterstitialSkip(info:)","required":true},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","abstract":[{"type":"text","text":"Информация о прерывании."}],"title":"InterstitialInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"abstract":[{"text":"Делегат для статистики прерываний.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","kind":"symbol","title":"InterstitialStatsDelegate","navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialSkip(info:)":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}],"url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialskip(info:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialSkip(info:)","abstract":[{"text":"Уведомляет о пропуске прерывания.","type":"text"}],"title":"logInterstitialSkip(info:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logInterstitialSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InterstitialInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"logInterstitialSkipWithInfo:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"logInterstitialSkipWithInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<OVKInterstitialInfo>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Информация о прерывании"}]}]}]},"op":"replace"},{"value":"OVKInterstitialInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialInfo"}],"op":"replace"},{"value":"OVKInterstitialStatsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"op":"replace"},{"op":"replace","value":"logInterstitialSkipWithInfo:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialSkip(info:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logInterstitialSkipWithInfo:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialSkip(info:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}