{"abstract":[{"type":"text","text":"Уведомляет о неудачной попытке загрузки прерываний."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialfailed(reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialfailed(reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialFailed(reason:)"},"metadata":{"symbolKind":"method","title":"logInterstitialFailed(reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"logInterstitialFailedWithReason:"}],"required":true,"modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialFailedWithReason:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"reason","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Причина сбоя"}]}]}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialFailed(reason:)":{"role":"symbol","abstract":[{"type":"text","text":"Уведомляет о неудачной попытке загрузки прерываний."}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logInterstitialFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logInterstitialFailedWithReason:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialFailed(reason:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialfailed(reason:)","kind":"symbol","title":"logInterstitialFailed(reason:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Делегат для статистики прерываний."}],"navigatorTitle":[{"text":"InterstitialStatsDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterstitialStatsDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","url":"\/documentation\/ovkit\/interstitialstatsdelegate","kind":"symbol","title":"InterstitialStatsDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"logInterstitialFailedWithReason:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logInterstitialFailedWithReason:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"logInterstitialFailedWithReason:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reason"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Причина сбоя"}],"type":"paragraph"}],"name":"reason"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialFailed(reason:)\/title","value":"logInterstitialFailedWithReason:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialFailed(reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logInterstitialFailedWithReason:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title","value":"OVKInterstitialStatsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"OVKInterstitialStatsDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}