{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialComplete(info:)"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"logInterstitialCompleteWithInfo:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKInterstitialStatsDelegate(im)logInterstitialCompleteWithInfo:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialComplete","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"kind":"text","text":")"}],"required":true,"title":"logInterstitialComplete(info:)","role":"symbol"},"abstract":[{"type":"text","text":"Уведомляет о завершении воспроизведения прерывания."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logInterstitialComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InterstitialInfo","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"info","content":[{"inlineContent":[{"type":"text","text":"Информация о прерывании"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialcomplete(info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialcomplete(info:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate":{"url":"\/documentation\/ovkit\/interstitialstatsdelegate","navigatorTitle":[{"kind":"identifier","text":"InterstitialStatsDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialStatsDelegate"}],"abstract":[{"text":"Делегат для статистики прерываний.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate","kind":"symbol","title":"InterstitialStatsDelegate","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/InterstitialInfo":{"navigatorTitle":[{"kind":"identifier","text":"InterstitialInfo"}],"url":"\/documentation\/ovkit\/interstitialinfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialInfo","type":"topic","title":"InterstitialInfo","role":"symbol","abstract":[{"text":"Информация о прерывании.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterstitialInfo"}]},"doc://onevideo.OVKit/documentation/OVKit/InterstitialStatsDelegate/logInterstitialComplete(info:)":{"title":"logInterstitialComplete(info:)","url":"\/documentation\/ovkit\/interstitialstatsdelegate\/loginterstitialcomplete(info:)","navigatorTitle":[{"kind":"identifier","text":"logInterstitialCompleteWithInfo:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logInterstitialComplete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKInterstitialInfo","text":"InterstitialInfo"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Уведомляет о завершении воспроизведения прерывания.","type":"text"}],"type":"topic","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/InterstitialStatsDelegate\/logInterstitialComplete(info:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"logInterstitialCompleteWithInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"logInterstitialCompleteWithInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"logInterstitialCompleteWithInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKInterstitialInfo","text":"id<OVKInterstitialInfo>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Информация о прерывании"}]}],"name":"info"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKInterstitialStatsDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/title"},{"value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/fragments"},{"value":[{"text":"OVKInterstitialStatsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate\/navigatorTitle"},{"value":"OVKInterstitialInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/title"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/fragments"},{"value":[{"text":"OVKInterstitialInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialInfo\/navigatorTitle"},{"value":"logInterstitialCompleteWithInfo:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialComplete(info:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"logInterstitialCompleteWithInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1InterstitialStatsDelegate~1logInterstitialComplete(info:)\/fragments"}]}]}