{"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","title":"gestureRecognizer(_:shouldReceive:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"text":"shouldReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@CM@OVKit@objc(cs)HoldToSeekBehavior(im)gestureRecognizer:shouldReceiveTouch:","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizer(_:shouldreceive:)"]},{"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"touch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/holdtoseekbehavior","abstract":[{"type":"text","text":"Перемотка видео нажатием и удержанием."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HoldToSeekBehavior","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","title":"HoldToSeekBehavior","navigatorTitle":[{"text":"HoldToSeekBehavior","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/UIGestureRecognizerDelegate-Implementations":{"kind":"article","type":"topic","abstract":[],"title":"UIGestureRecognizerDelegate Implementations","role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations","url":"\/documentation\/ovkit\/holdtoseekbehavior\/uigesturerecognizerdelegate-implementations"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/gestureRecognizer(_:shouldReceive:)":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"kind":"symbol","role":"symbol","abstract":[],"title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizer(_:shouldReceive:)","url":"\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizer(_:shouldreceive:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"gestureRecognizer:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"gestureRecognizer"},{"text":" ","kind":"text"},{"text":"shouldReceiveTouch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"touch"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title","value":"HoldToSeekBehavior","op":"replace"},{"value":[{"text":"HoldToSeekBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments"},{"value":"gestureRecognizer:shouldReceiveTouch:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]}]}]}