{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIGestureRecognizerDelegate.gestureRecognizerShouldBegin(_:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizershouldbegin(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizershouldbegin(_:)"]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@CM@OVKit@objc(cs)HoldToSeekBehavior(im)gestureRecognizerShouldBegin:","modules":[{"name":"OVKit"}],"extendedModule":"OVKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","title":"gestureRecognizerShouldBegin(_:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizerShouldBegin(_:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/gestureRecognizerShouldBegin(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizerShouldBegin(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"gestureRecognizerShouldBegin(_:)","url":"\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizershouldbegin(_:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"url":"\/documentation\/ovkit\/holdtoseekbehavior","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToSeekBehavior"}],"kind":"symbol","title":"HoldToSeekBehavior","abstract":[{"type":"text","text":"Перемотка видео нажатием и удержанием."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"gestureRecognizerShouldBegin:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizerShouldBegin(_:)\/title","value":"gestureRecognizerShouldBegin:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizerShouldBegin(_:)\/fragments"},{"value":"HoldToSeekBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title"},{"value":[{"text":"HoldToSeekBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments"},{"value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}