{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/isEnabled"},"metadata":{"symbolKind":"property","title":"isEnabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"s:5OVKit18HoldToSeekBehaviorC9isEnabledSbvp","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Активен ли жест перемотки.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/isenabled"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/isEnabled":{"url":"\/documentation\/ovkit\/holdtoseekbehavior\/isenabled","abstract":[{"type":"text","text":"Активен ли жест перемотки."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/isEnabled","title":"isEnabled"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Перемотка видео нажатием и удержанием."}],"navigatorTitle":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","type":"topic","url":"\/documentation\/ovkit\/holdtoseekbehavior","title":"HoldToSeekBehavior"}},"variantOverrides":[{"patch":[{"value":"HoldToSeekBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title"},{"value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}