{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizer(_:shouldReceive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizerShouldBegin(_:)"],"anchor":"Instance-Methods","generated":true}],"metadata":{"modules":[{"name":"OVKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"UIGestureRecognizerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/uigesturerecognizerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/holdtoseekbehavior\/uigesturerecognizerdelegate-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizer(_:shouldReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizer(_:shouldreceive:)","title":"gestureRecognizer(_:shouldReceive:)"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToSeekBehavior","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Перемотка видео нажатием и удержанием.","type":"text"}],"url":"\/documentation\/ovkit\/holdtoseekbehavior","title":"HoldToSeekBehavior","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/HoldToSeekBehavior/gestureRecognizerShouldBegin(_:)":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizerShouldBegin(_:)","url":"\/documentation\/ovkit\/holdtoseekbehavior\/gesturerecognizershouldbegin(_:)","abstract":[],"title":"gestureRecognizerShouldBegin(_:)","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizer(_:shouldReceive:)","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToSeekBehavior\/gestureRecognizerShouldBegin(_:)"],"title":"Instance Methods","generated":true}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/title","value":"HoldToSeekBehavior","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HoldToSeekBehavior"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior\/navigatorTitle"},{"op":"replace","value":"gestureRecognizerShouldBegin:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizerShouldBegin(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToSeekBehavior~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}]}]}]}