{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skipInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/seekhintview\/init(frame:skipinterval:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"init","externalID":"s:5OVKit12SeekHintViewC5frame12skipIntervalACSo6CGRectV_SdSgtcfc","roleHeading":"Initializer","title":"init(frame:skipInterval:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skipInterval"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?)","kind":"text"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekHintView\/init(frame:skipInterval:)"},"abstract":[{"type":"text","text":"Если "},{"type":"codeVoice","code":"skipInterval"},{"type":"text","text":" равен nil, будет использоваться значение по умолчанию."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekHintView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekHintView":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekHintView","url":"\/documentation\/ovkit\/seekhintview","abstract":[],"title":"SeekHintView","type":"topic","navigatorTitle":[{"text":"SeekHintView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekHintView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SeekHintView/init(frame:skipInterval:)":{"kind":"symbol","abstract":[{"type":"text","text":"Если "},{"type":"codeVoice","code":"skipInterval"},{"text":" равен nil, будет использоваться значение по умолчанию.","type":"text"}],"type":"topic","title":"init(frame:skipInterval:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekHintView\/init(frame:skipInterval:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"skipInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":"?)","kind":"text"}],"url":"\/documentation\/ovkit\/seekhintview\/init(frame:skipinterval:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekHintView\/title","value":"SeekHintView"},{"op":"replace","value":[{"text":"SeekHintView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekHintView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekHintView\/navigatorTitle","value":[{"text":"SeekHintView","kind":"identifier"}]}]}]}