{"metadata":{"title":"init(frame:chapterProvider:showAdditionalControls:timelineViewToTrack:)","roleHeading":"Initializer","externalID":"s:5OVKit28SeekPreviewElementsContainerC5frame15chapterProvider22showAdditionalControls19timelineViewToTrackACSo6CGRectV_AA07ChapterH0CSgSbSo6UIViewCtcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chapterProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"showAdditionalControls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timelineViewToTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"init","modules":[{"name":"OVKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chapterProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChapterProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"showAdditionalControls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timelineViewToTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/init(frame:chapterProvider:showAdditionalControls:timelineViewToTrack:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewelementscontainer\/init(frame:chapterprovider:showadditionalcontrols:timelineviewtotrack:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer/init(frame:chapterProvider:showAdditionalControls:timelineViewToTrack:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewelementscontainer\/init(frame:chapterprovider:showadditionalcontrols:timelineviewtotrack:)","title":"init(frame:chapterProvider:showAdditionalControls:timelineViewToTrack:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"chapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"showAdditionalControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timelineViewToTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/init(frame:chapterProvider:showAdditionalControls:timelineViewToTrack:)","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChapterProvider"}],"title":"ChapterProvider","role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/chapterprovider","abstract":[{"text":"Отвечает за разбивку видео на эпизоды по таймкодам.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}]},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer","title":"SeekPreviewElementsContainer","url":"\/documentation\/ovkit\/seekpreviewelementscontainer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKChapterProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title"},{"op":"replace","value":[{"text":"OVKChapterProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle"},{"op":"replace","value":"SeekPreviewElementsContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/title"},{"op":"replace","value":[{"text":"SeekPreviewElementsContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/fragments"},{"op":"replace","value":[{"text":"SeekPreviewElementsContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}