{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/playBlock"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewelementscontainer\/playblock"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?"}],"externalID":"s:5OVKit28SeekPreviewElementsContainerC9playBlockyycSgvp","role":"symbol","title":"playBlock","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playBlock"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer/playBlock":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/playBlock","url":"\/documentation\/ovkit\/seekpreviewelementscontainer\/playblock","type":"topic","title":"playBlock","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playBlock","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer","title":"SeekPreviewElementsContainer","url":"\/documentation\/ovkit\/seekpreviewelementscontainer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoidBlock"}],"title":"VoidBlock","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","kind":"symbol","url":"\/documentation\/ovkit\/voidblock","navigatorTitle":[{"kind":"identifier","text":"VoidBlock"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/title","op":"replace","value":"SeekPreviewElementsContainer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/fragments","op":"replace","value":[{"text":"SeekPreviewElementsContainer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}