{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewelementscontainer\/timelabel"]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeLabel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"}],"role":"symbol","title":"timeLabel","externalID":"s:5OVKit28SeekPreviewElementsContainerC9timeLabelSo7UILabelCvp"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/timeLabel"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer/timeLabel":{"kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewelementscontainer\/timelabel","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"role":"symbol","title":"timeLabel","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/timeLabel","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer","title":"SeekPreviewElementsContainer","url":"\/documentation\/ovkit\/seekpreviewelementscontainer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SeekPreviewElementsContainer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/title"},{"op":"replace","value":[{"text":"SeekPreviewElementsContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/navigatorTitle"}]}]}