{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer"]]},"variants":[{"paths":["\/documentation\/ovkit\/seekpreviewelementscontainer\/updatecurrenttime(timelineview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/updateCurrentTime(timelineView:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","externalID":"s:5OVKit28SeekPreviewElementsContainerC17updateCurrentTime12timelineViewyAA08TimelineJ0C_tF","title":"updateCurrentTime(timelineView:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer/updateCurrentTime(timelineView:)":{"type":"topic","url":"\/documentation\/ovkit\/seekpreviewelementscontainer\/updatecurrenttime(timelineview:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"},{"text":")","kind":"text"}],"title":"updateCurrentTime(timelineView:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer\/updateCurrentTime(timelineView:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"title":"TimelineView","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewElementsContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"url":"\/documentation\/ovkit\/seekpreviewelementscontainer","navigatorTitle":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewElementsContainer","type":"topic","role":"symbol","title":"SeekPreviewElementsContainer","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","op":"replace","value":"TimelineView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","op":"replace","value":[{"kind":"identifier","text":"TimelineView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TimelineView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/title","op":"replace","value":"SeekPreviewElementsContainer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewElementsContainer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SeekPreviewElementsContainer"}]}]}]}