{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItem\/previews","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkpersistentitem\/previews"]},{"paths":["\/documentation\/ovkit\/ovkpersistentitem\/previews"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"previews","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"PersistentItemPreview","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","title":"previews","externalID":"c:@M@OVKit@objc(cs)OVKPersistentItem(py)previews","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previews"},{"kind":"text","text":": ["},{"text":"PersistentItemPreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"previews","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentItem"}],"role":"symbol","url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemPreview":{"title":"PersistentItemPreview","kind":"symbol","url":"\/documentation\/ovkit\/persistentitempreview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PersistentItemPreview","kind":"identifier"}],"navigatorTitle":[{"text":"PersistentItemPreview","kind":"identifier"}],"abstract":[{"type":"text","text":"Модель, содержащая данные варианта превью для заданного размера."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItem/previews":{"title":"previews","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"previews","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"PersistentItemPreview"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItem\/previews","url":"\/documentation\/ovkit\/ovkpersistentitem\/previews","role":"symbol","navigatorTitle":[{"text":"previews","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"previews","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"previews","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<OVKPersistentItemPreview *>"},{"text":" * ","kind":"text"},{"text":"previews","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"value":[{"kind":"identifier","text":"OVKPersistentItem"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/title","op":"replace","value":"OVKPersistentItemPreview"},{"value":[{"text":"OVKPersistentItemPreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/fragments"},{"op":"replace","value":"previews","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItem~1previews\/title"},{"value":[{"kind":"identifier","text":"previews"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItem~1previews\/fragments","op":"replace"}]}]}