{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItem\/selectedMediaOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Какие дорожки выбраны для скачивания. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает все доступные аудио- и видеодорожки. Неподдерживаемые будут отфильтрованы при скачивании."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkpersistentitem\/selectedmediaoptions"]},{"paths":["\/documentation\/ovkit\/ovkpersistentitem\/selectedmediaoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedMediaOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PersistentMediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","title":"selectedMediaOptions","externalID":"c:@M@OVKit@objc(cs)OVKPersistentItem(py)selectedMediaOptions","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"selectedMediaOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"selectedMediaOptions","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentItem"}],"role":"symbol","url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},"doc://onevideo.OVKit/documentation/OVKit/OVKPersistentItem/selectedMediaOptions":{"title":"selectedMediaOptions","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedMediaOptions"},{"text":": [","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPersistentItem\/selectedMediaOptions","url":"\/documentation\/ovkit\/ovkpersistentitem\/selectedmediaoptions","role":"symbol","navigatorTitle":[{"text":"selectedMediaOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Какие дорожки выбраны для скачивания. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает все доступные аудио- и видеодорожки. Неподдерживаемые будут отфильтрованы при скачивании."}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption","navigatorTitle":[{"kind":"identifier","text":"PersistentMediaSelectionOption"}],"type":"topic","kind":"symbol","title":"PersistentMediaSelectionOption","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistentmediaselectionoption","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"selectedMediaOptions","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"selectedMediaOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<OVKPersistentMediaSelectionOption *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"selectedMediaOptions"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"value":"selectedMediaOptions","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItem~1selectedMediaOptions\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPersistentItem~1selectedMediaOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"selectedMediaOptions"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/title","op":"replace","value":"OVKPersistentMediaSelectionOption"},{"value":[{"kind":"identifier","text":"OVKPersistentMediaSelectionOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/fragments","op":"replace"}]}]}