{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/any"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/supplementarycontrollertype\/any"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/supplementarycontrollertype\/any"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"any"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Тип контента не определён или не имеет значения"}],"metadata":{"navigatorTitle":[{"text":"OVKSupplementaryControllerTypeAny","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKSupplementaryControllerType@OVKSupplementaryControllerTypeAny","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"any"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"SupplementaryControllerType.any","symbolKind":"case","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType/any":{"title":"SupplementaryControllerType.any","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/any","kind":"symbol","navigatorTitle":[{"text":"OVKSupplementaryControllerTypeAny","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementarycontrollertype\/any","abstract":[{"type":"text","text":"Тип контента не определён или не имеет значения"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType":{"type":"topic","kind":"symbol","title":"SupplementaryControllerType","role":"symbol","navigatorTitle":[{"text":"SupplementaryControllerType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryControllerType","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementarycontrollertype"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKSupplementaryControllerTypeAny"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeAny"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeAny"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType~1any\/title","op":"replace","value":"OVKSupplementaryControllerTypeAny"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType~1any\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeAny"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/title","op":"replace","value":"OVKSupplementaryControllerType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/fragments","op":"replace","value":[{"text":"OVKSupplementaryControllerType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/navigatorTitle","op":"replace","value":[{"text":"OVKSupplementaryControllerType","kind":"identifier"}]}]}]}