{"topicSections":[{"generated":true,"anchor":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/!=(_:_:)"],"title":"Operators"}],"variants":[{"paths":["\/documentation\/ovkit\/supplementarycontrollertype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"OVKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryControllerType"}],"url":"\/documentation\/ovkit\/supplementarycontrollertype","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType","abstract":[{"type":"text","text":"Назначение "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"SupplementaryControllerType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SupplementaryControllerType"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType/!=(_:_:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/ovkit\/supplementarycontrollertype\/!=(_:_:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenSupplementaryController","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"title":"FullscreenSupplementaryController","type":"topic","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/title","value":"OVKSupplementaryControllerType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/fragments","value":[{"text":"OVKSupplementaryControllerType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/navigatorTitle","value":[{"text":"OVKSupplementaryControllerType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}