{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/shoppable","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/supplementarycontrollertype\/shoppable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/supplementarycontrollertype\/shoppable"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shoppable"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType"]]},"abstract":[{"type":"text","text":"Дополнительный контент Instream рекламы формата Shoppable."}],"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shoppable"}],"externalID":"c:@M@OVKit@E@OVKSupplementaryControllerType@OVKSupplementaryControllerTypeShoppable","navigatorTitle":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeShoppable"}],"title":"SupplementaryControllerType.shoppable","roleHeading":"Case","role":"symbol","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","kind":"symbol","title":"FullscreenSupplementaryController","navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}]},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SupplementaryControllerType"}],"abstract":[{"type":"text","text":"Назначение "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/supplementarycontrollertype","kind":"symbol","title":"SupplementaryControllerType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryControllerType"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType/shoppable":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shoppable"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/supplementarycontrollertype\/shoppable","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType\/shoppable","role":"symbol","abstract":[{"type":"text","text":"Дополнительный контент Instream рекламы формата Shoppable."}],"navigatorTitle":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeShoppable"}],"title":"SupplementaryControllerType.shoppable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKSupplementaryControllerTypeShoppable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeShoppable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKSupplementaryControllerTypeShoppable","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/title","value":"OVKSupplementaryControllerType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryControllerType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKSupplementaryControllerType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType~1shoppable\/title","value":"OVKSupplementaryControllerTypeShoppable","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType~1shoppable\/fragments","value":[{"kind":"identifier","text":"OVKSupplementaryControllerTypeShoppable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}