{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile"]]},"metadata":{"roleHeading":"Initializer","modules":[{"name":"OVKit"}],"role":"symbol","title":"init(format:url:)","symbolKind":"init","externalID":"c:@M@OVKit@objc(cs)OVKVideoFile(im)initWithFormat:url:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","kind":"typeIdentifier","text":"VideoFileFormat"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFormat:url:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile\/init(format:url:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofile\/init(format:url:)"]},{"paths":["\/documentation\/ovkit\/videofile\/init(format:url:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"title":"VideoFileFormat","role":"symbol","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","kind":"symbol","url":"\/documentation\/ovkit\/videofileformat"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoFile":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoFile"}],"role":"symbol","title":"VideoFile","url":"\/documentation\/ovkit\/videofile"},"doc://onevideo.OVKit/documentation/OVKit/VideoFile/init(format:url:)":{"title":"init(format:url:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFile\/init(format:url:)","navigatorTitle":[{"text":"initWithFormat:url:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofile\/init(format:url:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithFormat:url:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFormat:url:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"OVKVideoFileFormat","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"format"},{"text":" ","kind":"text"},{"text":"url:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"OVKVideoFileFormat","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/title","value":"OVKVideoFile","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFile"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFile"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile~1init(format:url:)\/title","op":"replace","value":"initWithFormat:url:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFile~1init(format:url:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFormat:url:","kind":"identifier"}],"op":"replace"}]}]}