{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/picture"]},{"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/picture"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/picture"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"picture"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol(py)picture","roleHeading":"Instance Property","title":"picture","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"picture","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"picture","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol","kind":"symbol","type":"topic","title":"MyTargetShoppableAdsItemProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol/picture":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"picture","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/picture","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/picture","abstract":[],"role":"symbol","type":"topic","title":"picture","required":true,"navigatorTitle":[{"kind":"identifier","text":"picture"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"picture","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"picture"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"picture","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/title","value":"MyTargetShoppableAdsItemProtocol"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}]},{"op":"replace","value":"picture","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1picture\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1picture\/fragments","value":[{"kind":"identifier","text":"picture"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}