{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/text"]},{"paths":["\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/text"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"text"}],"title":"text","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","required":true,"externalID":"c:@M@OVKit@objc(pl)MyTargetShoppableAdsItemProtocol(py)text"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/text","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol/text":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol\/text","navigatorTitle":[{"kind":"identifier","text":"text"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol\/text","title":"text","abstract":[],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetShoppableAdsItemProtocol":{"url":"\/documentation\/ovkit\/mytargetshoppableadsitemprotocol","navigatorTitle":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"title":"MyTargetShoppableAdsItemProtocol","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MyTargetShoppableAdsItemProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetShoppableAdsItemProtocol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"text"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"text","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"text","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1text\/title"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol~1text\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/title","op":"replace","value":"MyTargetShoppableAdsItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/fragments","value":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}]},{"value":[{"kind":"identifier","text":"MyTargetShoppableAdsItemProtocol"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetShoppableAdsItemProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}