{"metadata":{"navigatorTitle":[{"text":"enumerateCases:","kind":"identifier"}],"title":"enumerateCases(_:)","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKVideoFileFormatObjC(cm)enumerateCases:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumerateCases","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:5OVKit10ValueBlocka","kind":"typeIdentifier","text":"ValueBlock"},{"text":"<","kind":"text"},{"text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/enumerateCases(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumerateCases"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"block"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValueBlock","preciseIdentifier":"s:5OVKit10ValueBlocka","kind":"typeIdentifier","text":"ValueBlock"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","kind":"typeIdentifier","text":"VideoFileFormat"},{"kind":"text","text":">)"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videofileformatobjc\/enumeratecases(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videofileformatobjc\/enumeratecases(_:)"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"VideoFileFormatObjC","kind":"identifier"}],"url":"\/documentation\/ovkit\/videofileformatobjc","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC","abstract":[],"title":"VideoFileFormatObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormatObjC","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC/enumerateCases(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumerateCases"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ValueBlock","preciseIdentifier":"s:5OVKit10ValueBlocka"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":">)"}],"title":"enumerateCases(_:)","url":"\/documentation\/ovkit\/videofileformatobjc\/enumeratecases(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"enumerateCases:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC\/enumerateCases(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ValueBlock":{"navigatorTitle":[{"text":"ValueBlock","kind":"identifier"}],"title":"ValueBlock","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ValueBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueBlock","kind":"identifier"}],"url":"\/documentation\/ovkit\/valueblock"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoFileFormat","kind":"identifier"}],"navigatorTitle":[{"text":"VideoFileFormat","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","url":"\/documentation\/ovkit\/videofileformat","type":"topic","kind":"symbol","abstract":[{"text":"Форматы видео ссылок. Отсортированы по приоритету","type":"text"}],"role":"symbol","title":"VideoFileFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"enumerateCases:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"enumerateCases:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"enumerateCases:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","kind":"typeIdentifier","text":"OVKVideoFileFormat","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/title","value":"OVKVideoFileFormatObjC","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/fragments","value":[{"text":"OVKVideoFileFormatObjC","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1enumerateCases(_:)\/title","op":"replace","value":"enumerateCases:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC~1enumerateCases(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enumerateCases:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","op":"replace","value":"OVKVideoFileFormat"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","op":"replace","value":[{"text":"OVKVideoFileFormat","kind":"identifier"}]}]}]}