{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/setSupplementaryViewController(_:animated:)"},"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/setsupplementaryviewcontroller(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/setsupplementaryviewcontroller(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSupplementaryViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":")?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"]]},"sections":[],"abstract":[{"text":"Метод обернутого контроллера: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSupplementaryViewController"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"FullscreenSupplementaryController","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol(im)setSupplementaryViewController:animated:","navigatorTitle":[{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"required":true,"title":"setSupplementaryViewController(_:animated:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","kind":"symbol","title":"FullscreenSupplementaryController","navigatorTitle":[{"kind":"identifier","text":"FullscreenSupplementaryController"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/setSupplementaryViewController(_:animated:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","abstract":[{"text":"Установка ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSupplementaryViewController"},{"kind":"text","text":"(("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","kind":"typeIdentifier","text":"FullscreenSupplementaryController"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/setsupplementaryviewcontroller(_:animated:)","kind":"symbol","title":"setSupplementaryViewController(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setSupplementaryViewController:animated:"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenContentViewController/supplementaryViewController":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/supplementaryViewController","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementaryViewController"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","kind":"typeIdentifier","text":"FullscreenSupplementaryController"},{"kind":"text","text":")?"}],"type":"topic","url":"\/documentation\/ovkit\/fullscreencontentviewcontroller\/supplementaryviewcontroller","kind":"symbol","title":"supplementaryViewController","navigatorTitle":[{"kind":"identifier","text":"supplementaryViewController"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FullscreenViewControllerProtocol","kind":"identifier"}],"title":"FullscreenViewControllerProtocol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Контроллер, который используется для полноэкранного просмотра."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerProtocol"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/setSupplementaryViewController(_:animated:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/setSupplementaryViewController(_:animated:)","type":"topic","navigatorTitle":[{"text":"setSupplementaryViewController:animated:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Метод обернутого контроллера: "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenContentViewController\/setSupplementaryViewController(_:animated:)","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/setsupplementaryviewcontroller(_:animated:)","title":"setSupplementaryViewController(_:animated:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSupplementaryViewController","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setSupplementaryViewController:animated:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSupplementaryViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)UIViewController@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","kind":"typeIdentifier","text":"UIViewController<OVKFullscreenSupplementaryController>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"animated:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/title","value":"setSupplementaryViewController:animated:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1setSupplementaryViewController(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/title","value":"supplementaryViewController","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenContentViewController~1supplementaryViewController\/fragments","value":[{"kind":"identifier","text":"supplementaryViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title","value":"OVKFullscreenViewControllerProtocol","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1setSupplementaryViewController(_:animated:)\/title","value":"setSupplementaryViewController:animated:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1setSupplementaryViewController(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSupplementaryViewController:animated:"}],"op":"replace"}]}]}