{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/visualStyle","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/visualstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/visualstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenViewControllerProtocol(py)visualStyle","required":true,"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visualStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"FullscreenViewControllerVisualStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"}],"title":"visualStyle","navigatorTitle":[{"kind":"identifier","text":"visualStyle"}]},"abstract":[{"type":"text","text":"Стиль отображения для "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"type":"text","text":" внутри контроллера"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerVisualStyle":{"navigatorTitle":[{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"title":"FullscreenViewControllerVisualStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenViewControllerVisualStyle","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollervisualstyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol/visualStyle":{"url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol\/visualstyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol\/visualStyle","title":"visualStyle","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle"}],"required":true,"kind":"symbol","abstract":[{"text":"Стиль отображения для ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"text":" внутри контроллера","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"visualStyle"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenViewControllerProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"role":"symbol","abstract":[{"text":"Контроллер, который используется для полноэкранного просмотра.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FullscreenViewControllerProtocol"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerProtocol","type":"topic","url":"\/documentation\/ovkit\/fullscreenviewcontrollerprotocol","title":"FullscreenViewControllerProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"visualStyle","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"visualStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenViewControllerVisualStyle","text":"FullscreenViewControllerVisualStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@FullscreenViewControllerVisualStyle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visualStyle"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/title","op":"replace","value":"FullscreenViewControllerVisualStyle"},{"value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerVisualStyle\/navigatorTitle","value":[{"kind":"identifier","text":"FullscreenViewControllerVisualStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":"visualStyle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1visualStyle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol~1visualStyle\/fragments","value":[{"text":"visualStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/title","value":"OVKFullscreenViewControllerProtocol","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenViewControllerProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenViewControllerProtocol"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}