{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideochapter\/hash"]},{"paths":["\/documentation\/ovkit\/ovkvideochapter\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideoChapter(py)hash","role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoChapter\/hash","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoChapter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VideoChapter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"VideoChapter"}],"role":"symbol","title":"VideoChapter","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter","kind":"symbol","url":"\/documentation\/ovkit\/videochapter","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoChapter/hash":{"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/ovkvideochapter\/hash","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoChapter\/hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"hash","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKVideoChapter","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/title"},{"value":[{"text":"OVKVideoChapter","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/fragments","op":"replace"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoChapter~1hash\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoChapter~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]}]}]}