{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createInstreamAd(slotId:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetplugin\/createinstreamad(slotid:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createInstreamAd"},{"kind":"text","text":"("},{"text":"slotId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","kind":"typeIdentifier","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createInstreamAd"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"slotId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MyTargetInstreamAd","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"}],"modules":[{"name":"OVKit"}],"externalID":"s:5OVKit14MyTargetPluginP16createInstreamAd6slotIdAA0bcfG0_pSu_tF","roleHeading":"Instance Method","title":"createInstreamAd(slotId:)","symbolKind":"method","required":true,"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin/createInstreamAd(slotId:)":{"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInstreamAd"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"slotId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","text":"MyTargetInstreamAd"}],"url":"\/documentation\/ovkit\/mytargetplugin\/createinstreamad(slotid:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createInstreamAd(slotId:)","abstract":[],"kind":"symbol","title":"createInstreamAd(slotId:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin","abstract":[{"text":"Необходим для проигрывания рекламы.","type":"text"}],"url":"\/documentation\/ovkit\/mytargetplugin","kind":"article","title":"MyTarget","role":"article"},"doc://onevideo.OVKit/documentation/OVKit/Plugins":{"kind":"article","url":"\/documentation\/ovkit\/plugins","abstract":[{"text":"Плагины позволяют расширить функциональность ","type":"text"},{"code":"OVKit","type":"codeVoice"},{"text":".","type":"text"}],"title":"Плагины","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Plugins","role":"collectionGroup"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"title":"MyTargetInstreamAd","kind":"symbol","url":"\/documentation\/ovkit\/mytargetinstreamad","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MyTargetInstreamAd"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title","value":"MyTargetInstreamAd","op":"replace"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}