{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPostViewPlayer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","text":"MyTargetInstreamAdPostViewPlayer","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createPostViewPlayer()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetplugin\/createpostviewplayer()"]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPostViewPlayer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","text":"MyTargetInstreamAdPostViewPlayer","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","externalID":"s:5OVKit14MyTargetPluginP20createPostViewPlayerAA0bc10InstreamAdfgH0_pyF","title":"createPostViewPlayer()","role":"symbol","required":true,"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin/createPostViewPlayer()":{"kind":"symbol","title":"createPostViewPlayer()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createPostViewPlayer()","abstract":[],"url":"\/documentation\/ovkit\/mytargetplugin\/createpostviewplayer()","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPostViewPlayer"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayer","text":"MyTargetInstreamAdPostViewPlayer"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayer":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayer","abstract":[],"title":"MyTargetInstreamAdPostViewPlayer","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayer","navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin","type":"topic","role":"article","url":"\/documentation\/ovkit\/mytargetplugin","abstract":[{"text":"Плагин для проигрывания рекламы.","type":"text"}],"title":"MyTarget","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MyTargetInstreamAdPostViewPlayer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/title"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/fragments"},{"value":[{"text":"MyTargetInstreamAdPostViewPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayer\/navigatorTitle"}]}]}