{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createInstreamAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"slotId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit20MyTargetMenuDelegateP","kind":"typeIdentifier","text":"MyTargetMenuDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetMenuDelegate"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd","kind":"typeIdentifier","text":"MyTargetInstreamAd","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createInstreamAd(slotId:menuDelegate:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/ovkit\/mytargetplugin\/createinstreamad(slotid:menudelegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"s:5OVKit14MyTargetPluginP16createInstreamAd6slotId12menuDelegateAA0bcfG0_pSu_AA0bc4MenuK0_ptF","symbolKind":"method","roleHeading":"Instance Method","title":"createInstreamAd(slotId:menuDelegate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInstreamAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"slotId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"menuDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetMenuDelegate","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20MyTargetMenuDelegateP"},{"text":") -> ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"}],"required":true,"role":"symbol"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAd":{"type":"topic","title":"MyTargetInstreamAd","abstract":[],"url":"\/documentation\/ovkit\/mytargetinstreamad","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAd"}],"navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAd"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin":{"kind":"article","url":"\/documentation\/ovkit\/mytargetplugin","role":"article","abstract":[{"text":"Необходим для проигрывания рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin","type":"topic","title":"MyTarget"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetPlugin/createInstreamAd(slotId:menuDelegate:)":{"type":"topic","url":"\/documentation\/ovkit\/mytargetplugin\/createinstreamad(slotid:menudelegate:)","required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPlugin\/createInstreamAd(slotId:menuDelegate:)","kind":"symbol","abstract":[],"role":"symbol","title":"createInstreamAd(slotId:menuDelegate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createInstreamAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"slotId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"menuDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetMenuDelegate","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit20MyTargetMenuDelegateP"},{"text":") -> ","kind":"text"},{"text":"MyTargetInstreamAd","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetInstreamAd"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetMenuDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetMenuDelegate"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetMenuDelegate","title":"MyTargetMenuDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MyTargetMenuDelegate"}],"abstract":[{"type":"text","text":"Протокол передачи событий из меню AdChoices."}],"url":"\/documentation\/ovkit\/mytargetmenudelegate"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MyTargetInstreamAd","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAd","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAd"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAd\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}