{"kind":"symbol","metadata":{"title":"fakeTimelineView","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fakeTimelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"}],"externalID":"s:5OVKit23SeekPreviewCombinedViewC012fakeTimelineE0AA0gE0Cvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/fakeTimelineView","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fakeTimelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/faketimelineview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"title":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewCombinedView"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"kind":"symbol","title":"SeekPreviewCombinedView","role":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/fakeTimelineView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/fakeTimelineView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fakeTimelineView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimelineView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"}],"title":"fakeTimelineView","kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/faketimelineview","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TimelineView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title"},{"value":[{"text":"TimelineView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments"},{"value":[{"kind":"identifier","text":"TimelineView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle"},{"value":"SeekPreviewCombinedView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title"},{"value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments"},{"value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle"}]}]}