{"metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"s:5OVKit23SeekPreviewCombinedViewC08controlsE015canShowPreviews0G14ExtendTimeline07initialK5FrameAcA014PlayerControlsE8Protocol_p_S2bSo6CGRectVtcfc","modules":[{"name":"OVKit"}],"title":"init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controlsView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canShowPreviews","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canExtendTimeline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialTimelineFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/init(controlsview:canshowpreviews:canextendtimeline:initialtimelineframe:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"controlsView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"},{"text":", ","kind":"text"},{"text":"canShowPreviews","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"canExtendTimeline","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"initialTimelineFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)":{"role":"symbol","abstract":[],"title":"init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/init(controlsView:canShowPreviews:canExtendTimeline:initialTimelineFrame:)","kind":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/init(controlsview:canshowpreviews:canextendtimeline:initialtimelineframe:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controlsView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canShowPreviews","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"canExtendTimeline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialTimelineFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","title":"PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView","role":"symbol","title":"SeekPreviewCombinedView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewcombinedview","navigatorTitle":[{"text":"SeekPreviewCombinedView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"SeekPreviewCombinedView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title","op":"replace"},{"value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}