{"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)SeekPreviewCombinedView(im)layoutSubviews","title":"layoutSubviews()","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/layoutsubviews()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/layoutSubviews()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/layoutSubviews()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"layoutSubviews()","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/layoutsubviews()","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewCombinedView"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"kind":"symbol","title":"SeekPreviewCombinedView","role":"symbol","url":"\/documentation\/ovkit\/seekpreviewcombinedview","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"layoutSubviews","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title","value":"SeekPreviewCombinedView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"op":"replace"}]}]}