{"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/precisiontimelinestopped"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineStopped"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"precisionTimelineStopped"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"precisionTimelineStopped","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit23SeekPreviewCombinedViewC24precisionTimelineStoppedySdcSgvp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionTimelineStopped","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"symbolKind":"property"},"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/precisionTimelineStopped":{"abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/precisiontimelinestopped","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/precisionTimelineStopped","title":"precisionTimelineStopped","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"precisionTimelineStopped","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"abstract":[],"kind":"symbol","title":"SeekPreviewCombinedView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewcombinedview","navigatorTitle":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title","value":"SeekPreviewCombinedView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments","value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle","value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}]}]}]}