{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTimeAndChapters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"OVKit"}],"title":"updateTimeAndChapters(timelineView:)","externalID":"s:5OVKit23SeekPreviewCombinedViewC21updateTimeAndChapters08timelineE0yAA08TimelineE0C_tF"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/updatetimeandchapters(timelineview:)"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateTimeAndChapters(timelineView:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateTimeAndChapters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"role":"symbol","title":"SeekPreviewCombinedView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView","url":"\/documentation\/ovkit\/seekpreviewcombinedview","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeekPreviewCombinedView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/updateTimeAndChapters(timelineView:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/updateTimeAndChapters(timelineView:)","url":"\/documentation\/ovkit\/seekpreviewcombinedview\/updatetimeandchapters(timelineview:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTimeAndChapters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView"},{"kind":"text","text":")"}],"title":"updateTimeAndChapters(timelineView:)"},"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineView"}],"title":"TimelineView","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title","op":"replace","value":"SeekPreviewCombinedView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","op":"replace","value":"TimelineView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","op":"replace","value":[{"text":"TimelineView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","op":"replace","value":[{"text":"TimelineView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}