{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/seekpreviewcombinedview\/visibleheight"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/visibleHeight"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit23SeekPreviewCombinedViewC13visibleHeightSdvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"visibleHeight"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView":{"abstract":[],"kind":"symbol","title":"SeekPreviewCombinedView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeekPreviewCombinedView","kind":"identifier"}],"url":"\/documentation\/ovkit\/seekpreviewcombinedview","navigatorTitle":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SeekPreviewCombinedView/visibleHeight":{"abstract":[],"url":"\/documentation\/ovkit\/seekpreviewcombinedview\/visibleheight","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SeekPreviewCombinedView\/visibleHeight","title":"visibleHeight","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibleHeight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"SeekPreviewCombinedView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/title"},{"value":[{"text":"SeekPreviewCombinedView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/fragments"},{"value":[{"kind":"identifier","text":"SeekPreviewCombinedView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SeekPreviewCombinedView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}