{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"modules":[{"name":"OVKit"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"title":"ErrorType.fatal","externalID":"c:@M@OVKit@E@OVKErrorType@OVKErrorTypeFatal","role":"symbol","roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"]]},"variants":[{"paths":["\/documentation\/ovkit\/errortype\/fatal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/errortype\/fatal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/fatal"},"abstract":[{"type":"text","text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше. Ссылок на запасные ресурсы больше нет, пользователю в UI показывается ошибка воспроизведения."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/fatal":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"abstract":[{"type":"text","text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше. Ссылок на запасные ресурсы больше нет, пользователю в UI показывается ошибка воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/fatal","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"url":"\/documentation\/ovkit\/errortype\/fatal","type":"topic","title":"ErrorType.fatal","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"navigatorTitle":[{"text":"ErrorType","kind":"identifier"}],"title":"ErrorType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","role":"symbol","url":"\/documentation\/ovkit\/errortype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorType","kind":"identifier"}],"abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKErrorTypeFatal"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKErrorTypeFatal","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1fatal\/title","value":"OVKErrorTypeFatal","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1fatal\/fragments","value":[{"kind":"identifier","text":"OVKErrorTypeFatal"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","value":"OVKErrorType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","value":[{"kind":"identifier","text":"OVKErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKErrorType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}