{"metadata":{"navigatorTitle":[{"text":"OVKErrorTypeInformative","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"informative","kind":"identifier"}],"title":"ErrorType.informative","externalID":"c:@M@OVKit@E@OVKErrorType@OVKErrorTypeInformative","roleHeading":"Case","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"]]},"variants":[{"paths":["\/documentation\/ovkit\/errortype\/informative"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/errortype\/informative"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/informative"},"abstract":[{"text":"Ошибка не влияет непосредственно на процесс воспроизведения, а сам процесс никак не прерывается.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"informative"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorType/informative":{"url":"\/documentation\/ovkit\/errortype\/informative","abstract":[{"type":"text","text":"Ошибка не влияет непосредственно на процесс воспроизведения, а сам процесс никак не прерывается."}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"informative","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/informative","title":"ErrorType.informative","role":"symbol","navigatorTitle":[{"text":"OVKErrorTypeInformative","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"navigatorTitle":[{"text":"ErrorType","kind":"identifier"}],"title":"ErrorType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","role":"symbol","url":"\/documentation\/ovkit\/errortype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorType","kind":"identifier"}],"abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKErrorTypeInformative","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKErrorTypeInformative","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKErrorTypeInformative","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1informative\/title","value":"OVKErrorTypeInformative"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1informative\/fragments","value":[{"text":"OVKErrorTypeInformative","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","value":"OVKErrorType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","value":[{"text":"OVKErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","value":[{"text":"OVKErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}