{"kind":"article","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/hashValue"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/hash(into:)"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/errortype\/rawrepresentable-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorType/hash(into:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/hash(into:)","abstract":[],"url":"\/documentation\/ovkit\/errortype\/hash(into:)","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"kind":"symbol","title":"hash(into:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"url":"\/documentation\/ovkit\/errortype","kind":"symbol","title":"ErrorType","navigatorTitle":[{"text":"ErrorType","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType/hashValue":{"title":"hashValue","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/ovkit\/errortype\/hashvalue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","value":"OVKErrorType"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","value":[{"kind":"identifier","text":"OVKErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"OVKErrorType"}]}]}]}