{"sections":[],"abstract":[{"text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше, но есть ссылки на запасные ресурсы и будет предпринята попытка их проиграть.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverable","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/errortype\/recoverable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/errortype\/recoverable"]}],"metadata":{"navigatorTitle":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"ErrorType.recoverable","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverable","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKErrorType@OVKErrorTypeRecoverable"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/recoverable","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorType/recoverable":{"navigatorTitle":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"title":"ErrorType.recoverable","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType\/recoverable","role":"symbol","url":"\/documentation\/ovkit\/errortype\/recoverable","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverable","kind":"identifier"}],"abstract":[{"text":"Воспроизведение текущего ресурса прервано и не может продолжаться дальше, но есть ссылки на запасные ресурсы и будет предпринята попытка их проиграть.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorType":{"navigatorTitle":[{"text":"ErrorType","kind":"identifier"}],"title":"ErrorType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorType","role":"symbol","url":"\/documentation\/ovkit\/errortype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorType","kind":"identifier"}],"abstract":[{"text":"Тип ошибки, определяющий ее важность.","type":"text"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKErrorTypeRecoverable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1recoverable\/title","value":"OVKErrorTypeRecoverable"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType~1recoverable\/fragments","value":[{"text":"OVKErrorTypeRecoverable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/title","value":"OVKErrorType","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/fragments","value":[{"text":"OVKErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorType\/navigatorTitle","value":[{"text":"OVKErrorType","kind":"identifier"}],"op":"replace"}]}]}