{"abstract":[{"text":"Источник данных, из которого префетчер получает список ресурсов.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPrefetcherDataSource","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(py)dataSource","symbolKind":"property","title":"dataSource","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"dataSource"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource","kind":"typeIdentifier","text":"IndexPrefetcherDataSource"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/datasource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/datasource"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/dataSource","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKIndexPrefetcher/dataSource":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/dataSource","navigatorTitle":[{"text":"dataSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Источник данных, из которого префетчер получает список ресурсов."}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/ovkindexprefetcher\/datasource","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource","text":"IndexPrefetcherDataSource"},{"kind":"text","text":"?"}],"title":"dataSource","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"type":"topic","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"type":"topic","url":"\/documentation\/ovkit\/indexprefetcherdatasource","abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка. Обычно им является модель данных, которая содержит индекс видеозаписей на экране.","type":"text"}],"kind":"symbol","title":"IndexPrefetcherDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IndexPrefetcherDataSource","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dataSource"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"dataSource","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<OVKIndexPrefetcherDataSource>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1dataSource\/title","value":"dataSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1dataSource\/fragments","value":[{"text":"dataSource","kind":"identifier"}]},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/title","op":"replace","value":"OVKIndexPrefetcherDataSource"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDataSource"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/fragments"}]}]}