{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/delegate","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","text":"IndexPrefetcherDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/delegate"]},{"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы.","type":"text"}],"metadata":{"title":"delegate","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(py)delegate","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate","kind":"typeIdentifier","text":"IndexPrefetcherDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/OVKIndexPrefetcher/delegate":{"abstract":[{"type":"text","text":"Делегат, через который префетчер сообщает о наступлении событий в ходе своей работы."}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate","kind":"typeIdentifier","text":"IndexPrefetcherDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/ovkindexprefetcher\/delegate","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/delegate","title":"delegate"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDelegate":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDelegate","title":"IndexPrefetcherDelegate","url":"\/documentation\/ovkit\/indexprefetcherdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndexPrefetcherDelegate","kind":"identifier"}],"abstract":[{"text":"Протокол, через который ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":" сообщает о наступлении событий в ходе своей работы."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<OVKIndexPrefetcherDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKIndexPrefetcherDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1delegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/title","value":"OVKIndexPrefetcherDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDelegate\/fragments","value":[{"text":"OVKIndexPrefetcherDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}