{"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/strategy","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"sections":[],"abstract":[{"text":"Стратегия работы префетчера.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strategy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","text":"PrefetchStrategy","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/strategy"]},{"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/strategy"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(py)strategy","navigatorTitle":[{"kind":"identifier","text":"strategy"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"strategy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"strategy"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKIndexPrefetcher/strategy":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"strategy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy","text":"PrefetchStrategy","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Стратегия работы префетчера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/strategy","kind":"symbol","url":"\/documentation\/ovkit\/ovkindexprefetcher\/strategy","navigatorTitle":[{"kind":"identifier","text":"strategy"}],"title":"strategy"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"type":"topic","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PrefetchStrategy","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Стратегия работы префетчера в списках."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","kind":"symbol","url":"\/documentation\/ovkit\/prefetchstrategy","navigatorTitle":[{"kind":"identifier","text":"PrefetchStrategy"}],"title":"PrefetchStrategy"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"strategy","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"strategy","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<OVKPrefetchStrategy>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchStrategy"},{"kind":"text","text":" "},{"kind":"identifier","text":"strategy"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1strategy\/title","value":"strategy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1strategy\/fragments","value":[{"text":"strategy","kind":"identifier"}]},{"value":"OVKIndexPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}]},{"op":"replace","value":"OVKPrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}