{"metadata":{"modules":[{"name":"OVKit"}],"title":"throttleInterval","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher(py)throttleInterval","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"throttleInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"throttleInterval","kind":"identifier"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/throttleInterval","interfaceLanguage":"swift"},"abstract":[{"text":"Интервал времени, который пройдет от момента вызова ","type":"text"},{"type":"codeVoice","code":"reached(_:)"},{"text":" до начала предзагрузки и отмены элементов. Таким образом, при быстрой прокрутке списков предзагрузка не происходит.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"throttleInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Значение по умолчанию - "},{"type":"codeVoice","code":"0.5"},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Warning","style":"warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Не рекомендуется менять во время работы префетчера."}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/throttleinterval"]},{"paths":["\/documentation\/ovkit\/ovkindexprefetcher\/throttleinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","title":"IndexPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit/OVKIndexPrefetcher/throttleInterval":{"abstract":[{"type":"text","text":"Интервал времени, который пройдет от момента вызова "},{"type":"codeVoice","code":"reached(_:)"},{"text":" до начала предзагрузки и отмены элементов. Таким образом, при быстрой прокрутке списков предзагрузка не происходит.","type":"text"}],"navigatorTitle":[{"text":"throttleInterval","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"throttleInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"throttleInterval","kind":"symbol","url":"\/documentation\/ovkit\/ovkindexprefetcher\/throttleinterval","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKIndexPrefetcher\/throttleInterval"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"throttleInterval","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"throttleInterval","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"throttleInterval"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"OVKIndexPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace"},{"value":"throttleInterval","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1throttleInterval\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKIndexPrefetcher~1throttleInterval\/fragments","value":[{"text":"throttleInterval","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}