{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/videochapter\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/videochapter\/isequal(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideoChapter(im)isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"isEqual(_:)"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter":{"type":"topic","role":"symbol","kind":"symbol","title":"VideoChapter","url":"\/documentation\/ovkit\/videochapter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoChapter","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter","navigatorTitle":[{"text":"VideoChapter","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoChapter/isEqual(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoChapter\/isEqual(_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/ovkit\/videochapter\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKVideoChapter","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapter"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoChapter"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoChapter~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}