{"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKVideoFileFormatObjC(im)init","roleHeading":"Instance Method","title":"init","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideofileformatobjc\/init"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoFileFormatObjC\/init","interfaceLanguage":"occ"},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormatObjC":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormatObjC"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/videofileformatobjc","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormatObjC","role":"symbol","title":"VideoFileFormatObjC","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormatObjC"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoFileFormatObjC/init":{"url":"\/documentation\/ovkit\/ovkvideofileformatobjc\/init","role":"symbol","type":"topic","title":"init","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoFileFormatObjC\/init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/title","op":"replace","value":"OVKVideoFileFormatObjC"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormatObjC\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKVideoFileFormatObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}