{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost\/hostDelegate","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate","text":"OVKPlayerViewHostDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerviewhost\/hostdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkplayerviewhost\/hostdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate","text":"OVKPlayerViewHostDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"hostDelegate"}],"externalID":"c:@M@OVKit@objc(pl)OVKPlayerViewHost(py)hostDelegate","role":"symbol","title":"hostDelegate","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHost":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"OVKPlayerViewHost","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkplayerviewhost","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost","title":"OVKPlayerViewHost","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVKPlayerViewHost","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHost/hostDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OVKPlayerViewHostDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewHostDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"hostDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHost\/hostDelegate","url":"\/documentation\/ovkit\/ovkplayerviewhost\/hostdelegate","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"hostDelegate","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerViewHostDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVKPlayerViewHostDelegate","kind":"identifier"}],"title":"OVKPlayerViewHostDelegate","url":"\/documentation\/ovkit\/ovkplayerviewhostdelegate","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerViewHostDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hostDelegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hostDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerViewHostDelegate","text":"id<OVKPlayerViewHostDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hostDelegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerViewHost","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewHost"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerViewHost"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost\/navigatorTitle"},{"value":"hostDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost~1hostDelegate\/title"},{"value":[{"kind":"identifier","text":"hostDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHost~1hostDelegate\/fragments"},{"value":"OVKPlayerViewHostDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/fragments"},{"value":[{"kind":"identifier","text":"OVKPlayerViewHostDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerViewHostDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}