{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionButton\/action"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoRestrictionButtonType.action"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton(py)action","roleHeading":"Instance Property","title":"action","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"action","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkvideorestrictionbutton\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideorestrictionbutton\/action"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButton":{"title":"VideoRestrictionButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VideoRestrictionButton","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","abstract":[],"url":"\/documentation\/ovkit\/videorestrictionbutton","navigatorTitle":[{"text":"VideoRestrictionButton","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionButton/action":{"type":"topic","title":"action","url":"\/documentation\/ovkit\/ovkvideorestrictionbutton\/action","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionButton\/action","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"action"}],"abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"action","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"action","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"action"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/title","value":"OVKVideoRestrictionButton","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/fragments","value":[{"kind":"identifier","text":"OVKVideoRestrictionButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionButton~1action\/title","value":"action","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionButton~1action\/fragments","op":"replace","value":[{"text":"action","kind":"identifier"}]}]}]}