{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionButton\/title"},"variants":[{"paths":["\/documentation\/ovkit\/ovkvideorestrictionbutton\/title"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkvideorestrictionbutton\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKVideoRestrictionButton(py)title","title":"title","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"title","kind":"identifier"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"VideoRestrictionButtonType.title"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/VideoRestrictionButton":{"url":"\/documentation\/ovkit\/videorestrictionbutton","type":"topic","navigatorTitle":[{"text":"VideoRestrictionButton","kind":"identifier"}],"title":"VideoRestrictionButton","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoRestrictionButton","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VideoRestrictionButton"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoRestrictionButton/title":{"title":"title","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoRestrictionButton\/title","type":"topic","url":"\/documentation\/ovkit\/ovkvideorestrictionbutton\/title","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"title","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/title","value":"OVKVideoRestrictionButton"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoRestrictionButton\/fragments","value":[{"text":"OVKVideoRestrictionButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionButton~1title\/title","value":"title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoRestrictionButton~1title\/fragments","value":[{"text":"title","kind":"identifier"}]}]}]}