{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:didSelect:userInitiated:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelect"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mediaOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","text":"MediaSelectionOption","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, в котором была выбрана медиадорожка."}]}],"name":"playerView"},{"name":"mediaOption","content":[{"type":"paragraph","inlineContent":[{"text":"Выбранная опция.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Был ли выбор инициирован пользователем или из кода.","type":"text"}]}],"name":"userInitiated"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:didselect:userinitiated:)"]},{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:didselect:userinitiated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate(im)player:didSelect:userInitiated:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","kind":"typeIdentifier","text":"MediaSelectionOption"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInitiated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"player(_:didSelect:userInitiated:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"player:didSelect:userInitiated:"}]},"abstract":[{"type":"text","text":"Уведомление о том, что была выбрана медиадорожка."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","type":"topic","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/player(_:didSelect:userInitiated:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"player(_:didSelect:userInitiated:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:didSelect:userInitiated:)","abstract":[{"type":"text","text":"Уведомление о том, что была выбрана медиадорожка."}],"navigatorTitle":[{"kind":"identifier","text":"player:didSelect:userInitiated:"}],"type":"topic","required":true,"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:didselect:userinitiated:)","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"title":"PlayerMediaSelectionDelegate","navigatorTitle":[{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","role":"symbol","url":"\/documentation\/ovkit\/playermediaselectiondelegate","type":"topic","abstract":[{"type":"text","text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"kind":"symbol","url":"\/documentation\/ovkit\/mediaselectionoption","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"abstract":[{"type":"text","text":"Опция медиадорожки."}],"title":"MediaSelectionOption","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","navigatorTitle":[{"kind":"identifier","text":"MediaSelectionOption"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"player:didSelect:userInitiated:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"player:didSelect:userInitiated:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"player:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"OVKPlayerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"playerView"},{"text":" ","kind":"text"},{"text":"didSelect:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"OVKMediaSelectionOption"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediaOption"},{"text":" ","kind":"text"},{"text":"userInitiated:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"userInitiated","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, в котором была выбрана медиадорожка."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Выбранная опция."}]}],"name":"mediaOption"},{"name":"userInitiated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Был ли выбор инициирован пользователем или из кода."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"value":"player:didSelect:userInitiated:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:didSelect:userInitiated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"player:didSelect:userInitiated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:didSelect:userInitiated:)\/fragments"},{"value":"OVKPlayerMediaSelectionDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments","op":"replace","value":[{"text":"OVKPlayerMediaSelectionDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title","value":"OVKMediaSelectionOption"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","op":"replace","value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}]},{"value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}