{"abstract":[{"type":"text","text":"Уведомление о том, что текущая дорожка была изменена или выключена."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:optionSelectionChanged:)"},"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate(im)player:optionSelectionChanged:","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"optionSelectionChanged","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"player(_:optionSelectionChanged:)","navigatorTitle":[{"text":"player:optionSelectionChanged:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"optionSelectionChanged"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"option"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","text":"SubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:optionselectionchanged:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:optionselectionchanged:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PlayerView","kind":"identifier"}],"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","abstract":[{"type":"text","text":"Дорожка субтитров."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/subtitlesoption","title":"SubtitlesOption","navigatorTitle":[{"kind":"identifier","text":"SubtitlesOption"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"url":"\/documentation\/ovkit\/playermediaselectiondelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","navigatorTitle":[{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров."}],"type":"topic","title":"PlayerMediaSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/player(_:optionSelectionChanged:)":{"kind":"symbol","url":"\/documentation\/ovkit\/playermediaselectiondelegate\/player(_:optionselectionchanged:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":", ","kind":"text"},{"text":"optionSelectionChanged","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"player:optionSelectionChanged:","kind":"identifier"}],"type":"topic","title":"player(_:optionSelectionChanged:)","abstract":[{"type":"text","text":"Уведомление о том, что текущая дорожка была изменена или выключена."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/player(_:optionSelectionChanged:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"player:optionSelectionChanged:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"player:optionSelectionChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"player:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","text":"OVKPlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerView"},{"text":" ","kind":"text"},{"text":"optionSelectionChanged:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","text":"OVKSubtitlesOption"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"option"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":"OVKSubtitlesOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKSubtitlesOption"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/navigatorTitle","value":[{"text":"OVKSubtitlesOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title","value":"OVKPlayerMediaSelectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}]},{"value":[{"text":"OVKPlayerMediaSelectionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:optionSelectionChanged:)\/title","value":"player:optionSelectionChanged:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1player(_:optionSelectionChanged:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"player:optionSelectionChanged:","kind":"identifier"}],"op":"replace"}]}]}