{"abstract":[{"text":"Дорожки субтитров подготовлены.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","role":"symbol","title":"playerSubtitlesPrepared(_:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate(im)playerSubtitlesPrepared:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerSubtitlesPrepared"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"playerSubtitlesPrepared:","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerSubtitlesPrepared(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/playersubtitlesprepared(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/playersubtitlesprepared(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerSubtitlesPrepared","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Плеер, от которого пришло событие.","type":"text"}],"type":"paragraph"}],"name":"playerView"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Происходит после начала воспроизведения. Доступные дорожки можно выбрать в ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/subtitles","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/subtitles":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"subtitles","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/subtitles","title":"subtitles","type":"topic","url":"\/documentation\/ovkit\/playerview\/subtitles","abstract":[{"text":"Набор доступных дорожек субтитров.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/playerSubtitlesPrepared(_:)":{"title":"playerSubtitlesPrepared(_:)","navigatorTitle":[{"text":"playerSubtitlesPrepared:","kind":"identifier"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/playersubtitlesprepared(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerSubtitlesPrepared","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerSubtitlesPrepared(_:)","abstract":[{"text":"Дорожки субтитров подготовлены.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","title":"PlayerMediaSelectionDelegate","type":"topic","abstract":[{"text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров.","type":"text"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playerSubtitlesPrepared:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playerSubtitlesPrepared:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"playerSubtitlesPrepared:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Плеер, от которого пришло событие."}]}],"name":"playerView"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1subtitles\/title","value":"subtitles"},{"op":"replace","value":[{"text":"subtitles","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1subtitles\/fragments"},{"op":"replace","value":"playerSubtitlesPrepared:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerSubtitlesPrepared(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerSubtitlesPrepared:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerSubtitlesPrepared(_:)\/fragments"},{"op":"replace","value":"OVKPlayerMediaSelectionDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}