{"sections":[],"abstract":[{"type":"text","text":"Загружен набор аудио\/видео дорожек."}],"metadata":{"symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerDidLoadMediaSelection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"playerDidLoadMediaSelection:","kind":"identifier"}],"role":"symbol","title":"playerDidLoadMediaSelection(_:)","externalID":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate(im)playerDidLoadMediaSelection:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerDidLoadMediaSelection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","text":"PlayerView"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"playerView","content":[{"inlineContent":[{"text":"Плеер, который загрузил список доступных медиа дорожек.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerDidLoadMediaSelection(_:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/playerdidloadmediaselection(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/playermediaselectiondelegate\/playerdidloadmediaselection(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate/playerDidLoadMediaSelection(_:)":{"url":"\/documentation\/ovkit\/playermediaselectiondelegate\/playerdidloadmediaselection(_:)","navigatorTitle":[{"kind":"identifier","text":"playerDidLoadMediaSelection:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate\/playerDidLoadMediaSelection(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerDidLoadMediaSelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":")"}],"type":"topic","title":"playerDidLoadMediaSelection(_:)","abstract":[{"type":"text","text":"Загружен набор аудио\/видео дорожек."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView","type":"topic","url":"\/documentation\/ovkit\/playerview","abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"url":"\/documentation\/ovkit\/playermediaselectiondelegate","navigatorTitle":[{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerMediaSelectionDelegate","kind":"identifier"}],"type":"topic","title":"PlayerMediaSelectionDelegate","abstract":[{"text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров.","type":"text"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playerDidLoadMediaSelection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidLoadMediaSelection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playerDidLoadMediaSelection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKPlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"text":" *) ","kind":"text"},{"text":"playerView","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"playerView","content":[{"type":"paragraph","inlineContent":[{"text":"Плеер, который загрузил список доступных медиа дорожек.","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerDidLoadMediaSelection(_:)\/title","value":"playerDidLoadMediaSelection:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate~1playerDidLoadMediaSelection(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidLoadMediaSelection:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title","value":"OVKPlayerMediaSelectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments","value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}]},{"value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/navigatorTitle","op":"replace"}]}]}