{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageUrl"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKImageAssetType\/imageUrl"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"]]},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"required":true,"title":"imageUrl","navigatorTitle":[{"text":"imageUrl","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(pl)OVKImageAssetType(py)imageUrl","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkimageassettype\/imageurl"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkimageassettype\/imageurl"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ImageAssetType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAssetType"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAssetType"}],"type":"topic","url":"\/documentation\/ovkit\/imageassettype","abstract":[],"kind":"symbol","title":"ImageAssetType","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ImageAssetType"},"doc://onevideo.OVKit/documentation/OVKit/OVKImageAssetType/imageUrl":{"title":"imageUrl","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageUrl"}],"type":"topic","required":true,"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKImageAssetType\/imageUrl","url":"\/documentation\/ovkit\/ovkimageassettype\/imageurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"imageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageUrl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"imageUrl","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" * ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/title","value":"OVKImageAssetType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ImageAssetType\/fragments","value":[{"kind":"identifier","text":"OVKImageAssetType"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKImageAssetType~1imageUrl\/title","value":"imageUrl"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKImageAssetType~1imageUrl\/fragments","value":[{"kind":"identifier","text":"imageUrl"}],"op":"replace"}]}]}