{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"К примеру, "},{"code":"16.0\/9.0","type":"codeVoice"},{"text":" сделает плеер горизонтальным. Значение по умолчанию ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает, что размер автоматически подстраивается под соотношение сторон видеодорожки, а при заданном значении перестают учитываться ограничения на минимальную и максимальную высоту плеера.","type":"text"}]},{"inlineContent":[{"text":"Значение имеет тип ","type":"text"},{"code":"double","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Принудительно устанавливает соотношение сторон плеера, когда он отображается над ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"bottomSheetPlayerAspectRatio","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)bottomSheetPlayerAspectRatio"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/bottomsheetplayeraspectratio"]},{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/bottomsheetplayeraspectratio"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/bottomSheetPlayerAspectRatio"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/bottomSheetPlayerAspectRatio":{"title":"bottomSheetPlayerAspectRatio","abstract":[{"text":"Принудительно устанавливает соотношение сторон плеера, когда он отображается над ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/bottomsheetplayeraspectratio","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bottomSheetPlayerAspectRatio"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/bottomSheetPlayerAspectRatio"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","title":"FullscreenSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bottomSheetPlayerAspectRatio"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":" * ","kind":"text"},{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/title","value":"bottomSheetPlayerAspectRatio"},{"op":"replace","value":[{"text":"bottomSheetPlayerAspectRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1bottomSheetPlayerAspectRatio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"}]}]}