{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/customControlsSafeInsets","interfaceLanguage":"swift"},"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)customControlsSafeInsets","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customControlsSafeInsets","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier","text":"NSValue"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","title":"customControlsSafeInsets","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"customControlsSafeInsets"}]},"kind":"symbol","abstract":[{"text":"Переопределение инсетов, которые действуют на контролы плеера во время показа ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/customcontrolssafeinsets"]},{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/customcontrolssafeinsets"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customControlsSafeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","text":"NSValue","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"nil"},{"type":"text","text":" означает наследование инсетов от safe area."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Значение имеет тип "},{"type":"codeVoice","code":"UIEdgeInsets"},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","title":"FullscreenSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/customControlsSafeInsets":{"navigatorTitle":[{"kind":"identifier","text":"customControlsSafeInsets"}],"url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/customcontrolssafeinsets","title":"customControlsSafeInsets","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/customControlsSafeInsets","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customControlsSafeInsets","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSValue","preciseIdentifier":"c:objc(cs)NSValue"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Переопределение инсетов, которые действуют на контролы плеера во время показа ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference"},{"type":"text","text":"."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"customControlsSafeInsets","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"customControlsSafeInsets","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSValue","kind":"typeIdentifier","text":"NSValue"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"customControlsSafeInsets"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"OVKFullscreenSupplementaryController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace"},{"value":"customControlsSafeInsets","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1customControlsSafeInsets\/title","op":"replace"},{"value":[{"text":"customControlsSafeInsets","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1customControlsSafeInsets\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}