{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/dismissGestureRecognizer","interfaceLanguage":"swift"},"abstract":[{"text":"Жест, который дает возможность скрыть ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"type":"text","text":" свайпом вниз. В зависимости от значения свойства "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wasPresentedForSupplementaryController","type":"reference","isActive":true},{"text":" срабатывание жеста приведет либо к закрытию только ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"text":" (","type":"text"},{"code":"false","type":"codeVoice"},{"text":"), либо к интерактивному дисмиссу всего контроллера с полноэкранным плеером (","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":")."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissGestureRecognizer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dismissGestureRecognizer"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dismissGestureRecognizer","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer"},{"text":"?","kind":"text"}],"title":"dismissGestureRecognizer","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)dismissGestureRecognizer","modules":[{"name":"OVKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/dismissgesturerecognizer"]},{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/dismissgesturerecognizer"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","kind":"symbol","title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/wasPresentedForSupplementaryController":{"abstract":[{"type":"text","text":"Был ли контроллер презентован одновременно с добавлением "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wasPresentedForSupplementaryController","navigatorTitle":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"kind":"symbol","title":"wasPresentedForSupplementaryController","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wasPresentedForSupplementaryController"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/waspresentedforsupplementarycontroller"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/dismissGestureRecognizer":{"navigatorTitle":[{"text":"dismissGestureRecognizer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/dismissgesturerecognizer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/dismissGestureRecognizer","required":true,"role":"symbol","title":"dismissGestureRecognizer","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismissGestureRecognizer"},{"text":": ","kind":"text"},{"text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Жест, который дает возможность скрыть ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference"},{"type":"text","text":" свайпом вниз. В зависимости от значения свойства "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/wasPresentedForSupplementaryController","type":"reference"},{"text":" срабатывание жеста приведет либо к закрытию только ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","isActive":true,"type":"reference"},{"text":" (","type":"text"},{"code":"false","type":"codeVoice"},{"text":"), либо к интерактивному дисмиссу всего контроллера с полноэкранным плеером (","type":"text"},{"code":"true","type":"codeVoice"},{"text":").","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenContentViewController/supplementaryViewController":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenContentViewController\/supplementaryViewController","url":"\/documentation\/ovkit\/ovkfullscreencontentviewcontroller\/supplementaryviewcontroller","navigatorTitle":[{"kind":"identifier","text":"supplementaryViewController"}],"kind":"symbol","title":"supplementaryViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supplementaryViewController","kind":"identifier"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController","text":"FullscreenSupplementaryController","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dismissGestureRecognizer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dismissGestureRecognizer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":" * ","kind":"text"},{"text":"dismissGestureRecognizer","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","value":"OVKFullscreenSupplementaryController"},{"value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments"},{"value":"wasPresentedForSupplementaryController","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wasPresentedForSupplementaryController\/title"},{"op":"replace","value":[{"text":"wasPresentedForSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1wasPresentedForSupplementaryController\/fragments"},{"value":"dismissGestureRecognizer","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1dismissGestureRecognizer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1dismissGestureRecognizer\/fragments","value":[{"kind":"identifier","text":"dismissGestureRecognizer"}]},{"op":"replace","value":"supplementaryViewController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenContentViewController~1supplementaryViewController\/fragments","value":[{"text":"supplementaryViewController","kind":"identifier"}],"op":"replace"}]}]}