{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/preferredBottomSheetHeight","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Высота, которую контроллер должен занимать при показе снизу плеера.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/preferredbottomsheetheight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/preferredbottomsheetheight"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBottomSheetHeight","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Значение автоматически ограничивается сверху, чтобы учитывать минимальную высоту плеера. "},{"code":"nil","type":"codeVoice"},{"text":" означает максимально возможную высоту.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Значение имеет тип ","type":"text"},{"type":"codeVoice","code":"CGFloat"},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)preferredBottomSheetHeight","required":true,"navigatorTitle":[{"text":"preferredBottomSheetHeight","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBottomSheetHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"title":"preferredBottomSheetHeight"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/preferredBottomSheetHeight":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/preferredBottomSheetHeight","abstract":[{"type":"text","text":"Высота, которую контроллер должен занимать при показе снизу плеера."}],"type":"topic","url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/preferredbottomsheetheight","required":true,"navigatorTitle":[{"text":"preferredBottomSheetHeight","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredBottomSheetHeight"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","title":"preferredBottomSheetHeight"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","kind":"symbol","title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"preferredBottomSheetHeight","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"preferredBottomSheetHeight"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"preferredBottomSheetHeight"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"preferredBottomSheetHeight","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1preferredBottomSheetHeight\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1preferredBottomSheetHeight\/fragments","op":"replace","value":[{"text":"preferredBottomSheetHeight","kind":"identifier"}]},{"value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"op":"replace"}]}]}