{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","required":true,"role":"symbol","title":"sideBySideMargin","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sideBySideMargin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"sideBySideMargin"}],"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)sideBySideMargin"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/sidebysidemargin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/sidebysidemargin"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/sideBySideMargin"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sideBySideMargin","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Может быть отрицательным. В таком случае контроллер будет перекрывать плеер. ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает нулевое расстояние.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Значение имеет тип ","type":"text"},{"code":"CGFloat","type":"codeVoice"},{"text":".","type":"text"}]}]}],"abstract":[{"type":"text","text":"Расстояние между плеером и "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"},{"type":"text","text":" при показе справа от плеера."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"abstract":[{"type":"text","text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме."}],"type":"topic","title":"FullscreenSupplementaryController","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","kind":"symbol","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/sideBySideMargin":{"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/sideBySideMargin","title":"sideBySideMargin","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sideBySideMargin"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Расстояние между плеером и ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","type":"reference","isActive":true},{"text":" при показе справа от плеера.","type":"text"}],"url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/sidebysidemargin","navigatorTitle":[{"kind":"identifier","text":"sideBySideMargin"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"sideBySideMargin","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"sideBySideMargin"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"sideBySideMargin","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"OVKFullscreenSupplementaryController","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace"},{"value":[{"text":"OVKFullscreenSupplementaryController","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","op":"replace"},{"value":"sideBySideMargin","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1sideBySideMargin\/title","op":"replace"},{"value":[{"text":"sideBySideMargin","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1sideBySideMargin\/fragments","op":"replace"}]}]}