{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/supplementaryType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/supplementarytype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/supplementarytype"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"supplementaryType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SupplementaryControllerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKSupplementaryControllerType"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKFullscreenSupplementaryController(py)supplementaryType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supplementaryType"}],"title":"supplementaryType","required":true,"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supplementaryType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKSupplementaryControllerType","text":"SupplementaryControllerType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/SupplementaryControllerType":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType","abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupplementaryControllerType","kind":"identifier"}],"navigatorTitle":[{"text":"SupplementaryControllerType","kind":"identifier"}],"url":"\/documentation\/ovkit\/supplementarycontrollertype","title":"SupplementaryControllerType","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenSupplementaryController":{"role":"symbol","kind":"symbol","title":"FullscreenSupplementaryController","url":"\/documentation\/ovkit\/fullscreensupplementarycontroller","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FullscreenSupplementaryController"}],"abstract":[{"text":"Контроллер, который может показываться рядом с играющим видео в полноэкранном режиме.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenSupplementaryController","navigatorTitle":[{"text":"FullscreenSupplementaryController","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKFullscreenSupplementaryController/supplementaryType":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKFullscreenSupplementaryController\/supplementaryType","navigatorTitle":[{"text":"supplementaryType","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkfullscreensupplementarycontroller\/supplementarytype","abstract":[],"type":"topic","required":true,"role":"symbol","kind":"symbol","title":"supplementaryType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"supplementaryType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SupplementaryControllerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKSupplementaryControllerType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"supplementaryType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"supplementaryType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OVKSupplementaryControllerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKSupplementaryControllerType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SupplementaryControllerType"},{"kind":"text","text":" "},{"text":"supplementaryType","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKSupplementaryControllerType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKSupplementaryControllerType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SupplementaryControllerType\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/title","op":"replace","value":"OVKFullscreenSupplementaryController"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenSupplementaryController\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenSupplementaryController"}]},{"op":"replace","value":"supplementaryType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1supplementaryType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKFullscreenSupplementaryController~1supplementaryType\/fragments","op":"replace","value":[{"text":"supplementaryType","kind":"identifier"}]}]}]}