{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/collector"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","text":"StatsCollector","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Сборщик событий текущей сессии проигрывания.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"collector","kind":"identifier"}],"role":"symbol","title":"collector","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext(py)collector","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector","text":"StatsCollector"},{"text":"?","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkstatshandlercontext\/collector"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkstatshandlercontext\/collector"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","url":"\/documentation\/ovkit\/statshandlercontext","role":"symbol","abstract":[{"type":"text","text":"Набор свойств, к которому может обращаться "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"StatsHandlerContext","navigatorTitle":[{"kind":"identifier","text":"StatsHandlerContext"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandlerContext"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/OVKStatsHandlerContext/collector":{"title":"collector","type":"topic","abstract":[{"type":"text","text":"Сборщик событий текущей сессии проигрывания."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsCollector","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"collector"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKStatsHandlerContext\/collector","kind":"symbol","url":"\/documentation\/ovkit\/ovkstatshandlercontext\/collector"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","title":"StatsHandler","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/statshandler","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":" после добавления нового ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"StatsCollector","kind":"identifier"}],"type":"topic","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Не привязан к ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"kind":"symbol","title":"StatsCollector","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/ovkit\/video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"collector"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"collector","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKStatsCollector","text":"id<OVKStatsCollector>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collector"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKStatsHandlerContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1collector\/title","value":"collector","op":"replace"},{"value":[{"kind":"identifier","text":"collector"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKStatsHandlerContext~1collector\/fragments","op":"replace"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace"},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","value":[{"text":"OVKVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments"}]}]}