{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","kind":"typeIdentifier","text":"ListPrefetcherConfig"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKLegacyPrefetchStrategy(py)config","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"config","kind":"identifier"}],"role":"symbol","title":"config"},"abstract":[{"type":"text","text":"Конфигурация от старого префетчера.."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","text":"ListPrefetcherConfig"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy"]]},"variants":[{"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/config"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/config"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/config"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"title":"ListPrefetcher","role":"symbol","deprecated":true},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/config":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/config","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/config","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Конфигурация от старого префетчера.."}],"type":"topic","title":"config","navigatorTitle":[{"kind":"identifier","text":"config"}]},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"kind":"symbol","abstract":[{"text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","type":"reference"},{"text":".","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"title":"LegacyPrefetchStrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","url":"\/documentation\/ovkit\/legacyprefetchstrategy"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"title":"ListPrefetcherConfig","kind":"symbol","navigatorTitle":[{"text":"ListPrefetcherConfig","kind":"identifier"}],"abstract":[{"text":"Конфигурация с опциями работы префетчера списка.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcherConfig","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/listprefetcherconfig"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"config","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"config"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKListPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"config","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKListPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"},{"value":"config","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1config\/title"},{"value":[{"kind":"identifier","text":"config"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1config\/fragments"},{"value":"OVKLegacyPrefetchStrategy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/navigatorTitle"},{"value":"OVKListPrefetcherConfig","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title"},{"value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments"},{"value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}