{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchCountAhead","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"},{"parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызывающий "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":"."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущий "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":"."}]}]},{"name":"networkBandwidth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Оценочная пропускная способность сети в данный момент в "},{"type":"codeVoice","code":"bps"},{"type":"text","text":"."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Количество видеозаписей, которое надо запрефетчить ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"после"}]},{"text":" текущего ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","interfaceLanguage":"swift"},"abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKLegacyPrefetchStrategy(im)indexPrefetcher:prefetchCountAhead:networkBandwidth:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchCountAhead","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","navigatorTitle":[{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"}],"url":"\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchCountAhead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","role":"symbol","abstract":[{"type":"text","text":"Получение количества видеозаписей для префетча."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"role":"symbol","deprecated":true,"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPrefetcher","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","url":"\/documentation\/ovkit\/listprefetcher","kind":"symbol","title":"ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegacyPrefetchStrategy"}],"url":"\/documentation\/ovkit\/legacyprefetchstrategy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyPrefetchStrategy"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","title":"LegacyPrefetchStrategy","role":"symbol","abstract":[{"type":"text","text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","isActive":true},{"type":"text","text":"."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"url":"\/documentation\/ovkit\/indexprefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"title":"IndexPrefetcher","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}],"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"indexPrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKIndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":" *) ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"prefetchCountAhead:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"networkBandwidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"networkBandwidth","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Вызывающий ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"prefetcher"},{"content":[{"inlineContent":[{"text":"Текущий ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"indexPath"},{"content":[{"inlineContent":[{"text":"Оценочная пропускная способность сети в данный момент в ","type":"text"},{"code":"bps","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"networkBandwidth"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Количество видеозаписей, которое надо запрефетчить ","type":"text"},{"inlineContent":[{"text":"после","type":"text"}],"type":"strong"},{"text":" текущего ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"text":".","type":"text"}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments"},{"op":"replace","value":"OVKListPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title"},{"op":"replace","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"},{"op":"replace","value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle"},{"op":"replace","value":"OVKLegacyPrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title"},{"op":"replace","value":[{"text":"OVKLegacyPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments"},{"op":"replace","value":[{"text":"OVKLegacyPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/navigatorTitle"},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}