{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"PrefetchStrategy.indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchDurationOf"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resource"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkBandwidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Длительность префетча видеозаписи. Если вернуть ","type":"text"},{"code":"0","type":"codeVoice"},{"text":", префетчер пропустит эту видеозапись.","type":"text"}]}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKLegacyPrefetchStrategy(im)indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchDurationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcher"}],"url":"\/documentation\/ovkit\/indexprefetcher","title":"IndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcher"}]},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"navigatorTitle":[{"text":"LegacyPrefetchStrategy","kind":"identifier"}],"url":"\/documentation\/ovkit\/legacyprefetchstrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","type":"topic","title":"LegacyPrefetchStrategy","role":"symbol","abstract":[{"text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LegacyPrefetchStrategy","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","url":"\/documentation\/ovkit\/videotype","navigatorTitle":[{"kind":"identifier","text":"VideoType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Модель видео, которую может воспроизвести OVKit.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"abstract":[],"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","url":"\/documentation\/ovkit\/legacyprefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchDurationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"type":"topic","title":"ListPrefetcher","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ListPrefetcher"}],"deprecated":true,"url":"\/documentation\/ovkit\/listprefetcher"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"indexPrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"OVKIndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"prefetchDurationOf:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType","text":"id<OVKVideoType>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"resource","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offset:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inBatchSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"networkBandwidth:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"networkBandwidth","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Длительность префетча видеозаписи. Если вернуть ","type":"text"},{"code":"0","type":"codeVoice"},{"text":", префетчер пропустит эту видеозапись.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace"},{"value":"OVKLegacyPrefetchStrategy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/navigatorTitle","op":"replace"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"},{"value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments","op":"replace"},{"value":"OVKListPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments","op":"replace"},{"value":[{"text":"OVKListPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}