{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/init(frame:chapterProvider:bottomMinY:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/timeandchaptercontainer\/init(frame:chapterprovider:bottomminy:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:5OVKit23TimeAndChapterContainerC5frame15chapterProvider10bottomMinYACSo6CGRectV_AA0dH0CSg14CoreFoundation7CGFloatVtcfc","modules":[{"name":"OVKit"}],"symbolKind":"init","title":"init(frame:chapterProvider:bottomMinY:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"chapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bottomMinY","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"chapterProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","text":"ChapterProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomMinY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer":{"url":"\/documentation\/ovkit\/timeandchaptercontainer","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndChapterContainer","kind":"identifier"}],"title":"TimeAndChapterContainer","abstract":[],"navigatorTitle":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChapterProvider"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"abstract":[{"text":"Отвечает за разбивку видео на эпизоды по таймкодам.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/chapterprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","title":"ChapterProvider"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/init(frame:chapterProvider:bottomMinY:)":{"role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/timeandchaptercontainer\/init(frame:chapterprovider:bottomminy:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chapterProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bottomMinY"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(frame:chapterProvider:bottomMinY:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/init(frame:chapterProvider:bottomMinY:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TimeAndChapterContainer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/title"},{"value":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/fragments"},{"value":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/navigatorTitle"},{"value":"OVKChapterProvider","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle"}]}]}