{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/layoutSubviews()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)TimeAndChapterContainer(im)layoutSubviews","title":"layoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"variants":[{"paths":["\/documentation\/ovkit\/timeandchaptercontainer\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/timeandchaptercontainer\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/layoutSubviews()":{"type":"topic","title":"layoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/layoutSubviews()","abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/timeandchaptercontainer\/layoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeAndChapterContainer"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimeAndChapterContainer"}],"role":"symbol","url":"\/documentation\/ovkit\/timeandchaptercontainer","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","title":"TimeAndChapterContainer","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"layoutSubviews","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer~1layoutSubviews()\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer~1layoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/title","op":"replace","value":"TimeAndChapterContainer"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/fragments","op":"replace","value":[{"text":"TimeAndChapterContainer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/navigatorTitle","op":"replace","value":[{"text":"TimeAndChapterContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}