{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/timeandchaptercontainer\/timelabel"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/timeLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"property","title":"timeLabel","externalID":"s:5OVKit23TimeAndChapterContainerC9timeLabelSo7UILabelCvp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/timeLabel":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/timeLabel","kind":"symbol","title":"timeLabel","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"url":"\/documentation\/ovkit\/timeandchaptercontainer\/timelabel"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer":{"kind":"symbol","navigatorTitle":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndChapterContainer","kind":"identifier"}],"title":"TimeAndChapterContainer","url":"\/documentation\/ovkit\/timeandchaptercontainer","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TimeAndChapterContainer","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/title"},{"value":[{"text":"TimeAndChapterContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/fragments"},{"value":[{"kind":"identifier","text":"TimeAndChapterContainer"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/navigatorTitle"}]}]}