{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/updateCurrentTime(timelineView:)"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"timelineView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimelineView","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView"},{"text":")","kind":"text"}],"title":"updateCurrentTime(timelineView:)","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit23TimeAndChapterContainerC013updateCurrentB012timelineViewyAA08TimelineI0C_tF"},"variants":[{"paths":["\/documentation\/ovkit\/timeandchaptercontainer\/updatecurrenttime(timelineview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineView":{"abstract":[{"type":"text","text":"Таймлайн воспроизведения. Подходит для обычных видео и трансляций."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineView","kind":"identifier"}],"title":"TimelineView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineView","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/timelineview","navigatorTitle":[{"text":"TimelineView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeAndChapterContainer"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimeAndChapterContainer"}],"role":"symbol","url":"\/documentation\/ovkit\/timeandchaptercontainer","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer","title":"TimeAndChapterContainer","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/TimeAndChapterContainer/updateCurrentTime(timelineView:)":{"url":"\/documentation\/ovkit\/timeandchaptercontainer\/updatecurrenttime(timelineview:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimeAndChapterContainer\/updateCurrentTime(timelineView:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCurrentTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timelineView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)TimelineView","text":"TimelineView"},{"kind":"text","text":")"}],"role":"symbol","title":"updateCurrentTime(timelineView:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/title","value":"TimelineView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/fragments","value":[{"kind":"identifier","text":"TimelineView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineView\/navigatorTitle","value":[{"text":"TimelineView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/title","value":"TimeAndChapterContainer"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/fragments","value":[{"text":"TimeAndChapterContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimeAndChapterContainer\/navigatorTitle","value":[{"text":"TimeAndChapterContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}