{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)"},"abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchCountAhead","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Вызывающий "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"prefetcher"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Текущий "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":"."}]}],"name":"indexPath"},{"name":"networkBandwidth","content":[{"inlineContent":[{"text":"Оценочная пропускная способность сети в данный момент в ","type":"text"},{"type":"codeVoice","code":"bps"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"Количество видеозаписей, которое надо запрефетчить ","type":"text"},{"inlineContent":[{"type":"text","text":"после"}],"type":"strong"},{"text":" текущего ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy(im)indexPrefetcher:prefetchCountAhead:networkBandwidth:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"}],"role":"symbol","title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"prefetchCountAhead","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetchStrategy","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"title":"PrefetchStrategy","url":"\/documentation\/ovkit\/prefetchstrategy","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefetchCountAhead"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","url":"\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"type":"topic","title":"IndexPrefetcher","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"indexPrefetcher:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"OVKIndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchCountAhead:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkBandwidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"networkBandwidth"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"prefetcher","content":[{"inlineContent":[{"text":"Вызывающий ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"indexPath","content":[{"inlineContent":[{"type":"text","text":"Текущий "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"networkBandwidth","content":[{"type":"paragraph","inlineContent":[{"text":"Оценочная пропускная способность сети в данный момент в ","type":"text"},{"code":"bps","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"Количество видеозаписей, которое надо запрефетчить ","type":"text"},{"type":"strong","inlineContent":[{"text":"после","type":"text"}]},{"text":" текущего ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"text":".","type":"text"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","op":"replace","value":"OVKPrefetchStrategy"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","op":"replace","value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title","op":"replace","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","op":"replace","value":"OVKIndexPrefetcher"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}