{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy"]]},"abstract":[{"text":"Получение длительности префетча для видеозаписи.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"prefetchDurationOf"},{"text":" ","kind":"text"},{"text":"resource","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inBatchSize","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkBandwidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Вызывающий "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"prefetcher"},{"name":"resource","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Видео, которое будет запрефетчено."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Сдвиг относительно текущего "},{"code":"IndexPath","type":"codeVoice"},{"text":" (","type":"text"},{"type":"codeVoice","code":"0"},{"text":" означает текущий ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"}],"name":"offset"},{"name":"size","content":[{"inlineContent":[{"text":"Общее количество видеозаписей для префетча, полученное ранее вызовом ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"networkBandwidth","content":[{"inlineContent":[{"type":"text","text":"Оценочная пропускная способность сети в данный момент в "},{"code":"bps","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Длительность префетча видеозаписи. Если вернуть ","type":"text"},{"type":"codeVoice","code":"0"},{"type":"text","text":", префетчер пропустит эту видеозапись."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"]},{"paths":["\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)"},"sections":[],"kind":"symbol","metadata":{"required":true,"title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"indexPrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"text":"IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"prefetchDurationOf","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"inBatchSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"externalID":"c:@M@OVKit@objc(pl)OVKPrefetchStrategy(im)indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","roleHeading":"Instance Method","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)":{"url":"\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchdurationof:offset:inbatchsize:networkbandwidth:)","title":"indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"prefetchDurationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inBatchSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"networkBandwidth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"abstract":[{"type":"text","text":"Получение длительности префетча для видеозаписи."}],"required":true,"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)","type":"topic","navigatorTitle":[{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}],"title":"IndexPrefetcher","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"url":"\/documentation\/ovkit\/indexprefetcher"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"title":"VideoType","kind":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/videotype"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)":{"abstract":[{"text":"Получение количества видеозаписей для префетча.","type":"text"}],"title":"indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","required":true,"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","navigatorTitle":[{"text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":", "},{"text":"prefetchCountAhead","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkBandwidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/ovkit\/prefetchstrategy\/indexprefetcher(_:prefetchcountahead:networkbandwidth:)"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchStrategy":{"url":"\/documentation\/ovkit\/prefetchstrategy","title":"PrefetchStrategy","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PrefetchStrategy","kind":"identifier"}],"abstract":[{"text":"Стратегия работы префетчера в списках.","type":"text"}],"navigatorTitle":[{"text":"PrefetchStrategy","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"indexPrefetcher:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"OVKIndexPrefetcher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"prefetcher"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefetchDurationOf:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<OVKVideoType>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"resource"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"offset"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inBatchSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"networkBandwidth:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"networkBandwidth"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"text":"Вызывающий ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"text":".","type":"text"}]}]},{"name":"resource","content":[{"inlineContent":[{"type":"text","text":"Видео, которое будет запрефетчено."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Сдвиг относительно текущего "},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":" ("},{"code":"0","type":"codeVoice"},{"text":" означает текущий ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":")."}]}],"name":"offset"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Общее количество видеозаписей для префетча, полученное ранее вызовом ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchStrategy\/indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)","isActive":true},{"text":".","type":"text"}]}],"name":"size"},{"name":"networkBandwidth","content":[{"type":"paragraph","inlineContent":[{"text":"Оценочная пропускная способность сети в данный момент в ","type":"text"},{"type":"codeVoice","code":"bps"},{"type":"text","text":"."}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Длительность префетча видеозаписи. Если вернуть ","type":"text"},{"type":"codeVoice","code":"0"},{"type":"text","text":", префетчер пропустит эту видеозапись."}]}]}},{"op":"replace","value":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"indexPrefetcher:prefetchDurationOf:offset:inBatchSize:networkBandwidth:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchDurationOf:offset:inBatchSize:networkBandwidth:)\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title","value":"OVKIndexPrefetcher","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcher"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"op":"replace","value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","op":"replace","value":[{"text":"OVKVideoType","kind":"identifier"}]},{"value":[{"text":"OVKVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/title","value":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy~1indexPrefetcher(_:prefetchCountAhead:networkBandwidth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:prefetchCountAhead:networkBandwidth:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/title","value":"OVKPrefetchStrategy"},{"value":[{"text":"OVKPrefetchStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKPrefetchStrategy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchStrategy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}