{"sections":[],"abstract":[{"text":"Время, затраченное на установку TCP-соединения. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что время неизвестно.","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpHandshakeDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"tcpHandshakeDuration","kind":"identifier"}],"role":"symbol","title":"tcpHandshakeDuration","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo(py)tcpHandshakeDuration","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpHandshakeDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tcpHandshakeDuration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/networkconnectioninfo\/tcphandshakeduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/networkconnectioninfo\/tcphandshakeduration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionInfo"}],"url":"\/documentation\/ovkit\/networkconnectioninfo","title":"NetworkConnectionInfo","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionInfo"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/tcpHandshakeDuration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpHandshakeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/networkconnectioninfo\/tcphandshakeduration","title":"tcpHandshakeDuration","abstract":[{"text":"Время, затраченное на установку TCP-соединения. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что время неизвестно.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tcpHandshakeDuration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tcpHandshakeDuration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"tcpHandshakeDuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"tcpHandshakeDuration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"tcpHandshakeDuration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","op":"replace","value":"OVKNetworkConnectionInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tcpHandshakeDuration\/title","op":"replace","value":"tcpHandshakeDuration"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tcpHandshakeDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"tcpHandshakeDuration"}]}]}]}