{"sections":[],"abstract":[{"text":"Время, затраченное на установку  TLS-соединения. ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" означает, что время неизвестно.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/networkconnectioninfo\/tlshandshakeduration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnectioninfo\/tlshandshakeduration"]}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tlsHandshakeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo(py)tlsHandshakeDuration","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tlsHandshakeDuration"}],"title":"tlsHandshakeDuration"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tlsHandshakeDuration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tlsHandshakeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"NetworkConnectionInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","title":"NetworkConnectionInfo","abstract":[{"text":"Набор параметров с информацией о сетевом соединении.","type":"text"}],"url":"\/documentation\/ovkit\/networkconnectioninfo"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/tlsHandshakeDuration":{"title":"tlsHandshakeDuration","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/tlsHandshakeDuration","abstract":[{"text":"Время, затраченное на установку  TLS-соединения. ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" означает, что время неизвестно.","type":"text"}],"url":"\/documentation\/ovkit\/networkconnectioninfo\/tlshandshakeduration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tlsHandshakeDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"tlsHandshakeDuration","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"tlsHandshakeDuration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"tlsHandshakeDuration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tlsHandshakeDuration"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKNetworkConnectionInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title"},{"value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments"},{"value":[{"kind":"identifier","text":"OVKNetworkConnectionInfo"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle"},{"value":"tlsHandshakeDuration","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tlsHandshakeDuration\/title"},{"value":[{"kind":"identifier","text":"tlsHandshakeDuration"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1tlsHandshakeDuration\/fragments"}]}]}