{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnectioninfo\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnectioninfo\/type"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Возможные значения: http1, http2, http3. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" означает, что тип неизвестен."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo"]]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/type","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKNetworkConnectionInfo(py)type","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property","title":"type","navigatorTitle":[{"kind":"identifier","text":"type"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Протокол, по которому идут запросы за видео к серверу."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo":{"role":"symbol","title":"NetworkConnectionInfo","type":"topic","navigatorTitle":[{"text":"NetworkConnectionInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Набор параметров с информацией о сетевом соединении."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionInfo","kind":"identifier"}],"url":"\/documentation\/ovkit\/networkconnectioninfo","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionInfo/type":{"abstract":[{"type":"text","text":"Протокол, по которому идут запросы за видео к серверу."}],"title":"type","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/networkconnectioninfo\/type","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionInfo\/type"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/title","op":"replace","value":"OVKNetworkConnectionInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/fragments","op":"replace","value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo\/navigatorTitle","op":"replace","value":[{"text":"OVKNetworkConnectionInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionInfo~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]}]}]}