{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Фабричный метод для создания новых рекламных контролов.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adsprovider\/makeadcontrols(for:hassupplementarycontrols:interactiveadsplaying:inpip:)"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider"]]},"metadata":{"required":true,"title":"makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","modules":[{"name":"OVKit"}],"symbolKind":"method","role":"symbol","externalID":"s:5OVKit11AdsProviderP14makeAdControls3for016hasSupplementaryF0011interactiveB7Playing5inPiPAA06PlayerF12ViewProtocol_pAA05VideoB4Type_p_S3btF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeAdControls"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","text":"VideoAdsType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasSupplementaryControls"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interactiveAdsPlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inPiP"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeAdControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ads","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoAdsType","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"hasSupplementaryControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"interactiveAdsPlaying","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"inPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"VideoAdsType"},{"text":" Рекламные данные.","type":"text"}],"type":"paragraph"}],"name":"ads"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" Флаг присутствия дополнительных рекламных контролов."}],"type":"paragraph"}],"name":"hasSupplementaryControls"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" Флаг проигрывания рекламы интерактивного формата, например, Video Motion или Shoppable."}],"type":"paragraph"}],"name":"interactiveAdsPlaying"},{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"Bool","type":"codeVoice"},{"type":"text","text":" Флаг проигрывания в режиме «Картинка в Картинке»."}],"type":"paragraph"}],"name":"inPiP"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"PlayerControlsViewProtocol"},{"type":"text","text":" Новые рекламные контролы плеера."}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAdsType":{"title":"VideoAdsType","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VideoAdsType","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAdsType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAdsType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/videoadstype"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","title":"PlayerControlsViewProtocol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/AdsProvider/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)":{"required":true,"url":"\/documentation\/ovkit\/adsprovider\/makeadcontrols(for:hassupplementarycontrols:interactiveadsplaying:inpip:)","title":"makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider\/makeAdControls(for:hasSupplementaryControls:interactiveAdsPlaying:inPiP:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeAdControls","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VideoAdsType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoAdsType"},{"text":", ","kind":"text"},{"text":"hasSupplementaryControls","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"interactiveAdsPlaying","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"inPiP","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP"}],"kind":"symbol","abstract":[{"type":"text","text":"Фабричный метод для создания новых рекламных контролов."}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdsProvider":{"type":"topic","abstract":[{"type":"text","text":"Протокол поставщика рекламных контролов."}],"navigatorTitle":[{"kind":"identifier","text":"AdsProvider"}],"role":"symbol","title":"AdsProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdsProvider"}],"url":"\/documentation\/ovkit\/adsprovider","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKVideoAdsType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/title"},{"op":"replace","value":[{"text":"OVKVideoAdsType","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideoAdsType"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAdsType\/navigatorTitle"}]}]}