{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Разрешает интерактивное закрытие в любой ориентации на любом устройстве."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedInAllOrientations"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinallorientations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinallorientations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedInAllOrientations"}],"title":"FullscreenInteractiveDismissAvailability.allowedInAllOrientations","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability@OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"}],"symbolKind":"case"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInAllOrientations","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"title":"FullscreenInteractiveDismissAvailability","kind":"symbol","role":"symbol","abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/allowedInAllOrientations":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"}],"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinallorientations","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInAllOrientations","title":"FullscreenInteractiveDismissAvailability.allowedInAllOrientations","abstract":[{"type":"text","text":"Разрешает интерактивное закрытие в любой ориентации на любом устройстве."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedInAllOrientations"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKFullscreenInteractiveDismissAvailability","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle"},{"value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInAllOrientations\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInAllOrientations"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInAllOrientations\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}