{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedInSupportedOrientations"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Набор поддерживаемых ориентаций зависит от поля ","type":"text"},{"code":"supportedInterfaceOrientations","type":"codeVoice"},{"text":" контроллера, поверх которого лежит полноэкранный плеер. Обычно на iPhone поддерживаемой ориентацией является только ","type":"text"},{"code":".portrait","type":"codeVoice"},{"text":", на iPad – все ориентации.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}],"modules":[{"name":"OVKit"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability@OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","title":"FullscreenInteractiveDismissAvailability.allowedInSupportedOrientations","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedInSupportedOrientations"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Разрешает интерактивное закрытие только в поддерживаемых ориентациях.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinsupportedorientations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinsupportedorientations"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/allowedInSupportedOrientations":{"kind":"symbol","title":"FullscreenInteractiveDismissAvailability.allowedInSupportedOrientations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/allowedInSupportedOrientations","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/allowedinsupportedorientations","navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}],"abstract":[{"text":"Разрешает интерактивное закрытие только в поддерживаемых ориентациях.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedInSupportedOrientations","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"kind":"symbol","title":"FullscreenInteractiveDismissAvailability","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","navigatorTitle":[{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}],"abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/title"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityAllowedInSupportedOrientations"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1allowedInSupportedOrientations\/fragments"},{"value":"OVKFullscreenInteractiveDismissAvailability","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title"},{"value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments"},{"value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle"}]}]}