{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"metadata":{"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKFullscreenInteractiveDismissAvailability@OVKFullscreenInteractiveDismissAvailabilityDisabled","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"navigatorTitle":[{"text":"OVKFullscreenInteractiveDismissAvailabilityDisabled","kind":"identifier"}],"title":"FullscreenInteractiveDismissAvailability.disabled","roleHeading":"Case","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"Выключает механику интерактивного закрытия.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/disabled","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}],"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","title":"FullscreenInteractiveDismissAvailability","abstract":[{"type":"text","text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/disabled":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"abstract":[{"type":"text","text":"Выключает механику интерактивного закрытия."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/disabled","title":"FullscreenInteractiveDismissAvailability.disabled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityDisabled"}],"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/disabled"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKFullscreenInteractiveDismissAvailabilityDisabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityDisabled"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityDisabled"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","value":"OVKFullscreenInteractiveDismissAvailability","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1disabled\/title","value":"OVKFullscreenInteractiveDismissAvailabilityDisabled","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability~1disabled\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailabilityDisabled"}],"op":"replace"}]}]}