{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"OVKit"}],"title":"Equatable Implementations"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/!=(_:_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/!=(_:_:)","role":"symbol","abstract":[],"title":"!=(_:_:)"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}],"title":"FullscreenInteractiveDismissAvailability","type":"topic","kind":"symbol","abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FullscreenInteractiveDismissAvailability"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKFullscreenInteractiveDismissAvailability","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle","op":"replace"}]}]}