{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"sections":[],"metadata":{"role":"symbol","symbolKind":"init","title":"init(rawValue:)","externalID":"s:5OVKit40FullscreenInteractiveDismissAvailabilityO8rawValueACSgSi_tcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"modules":[{"name":"OVKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/init(rawvalue:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/init(rawValue:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/init(rawValue:)","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","title":"FullscreenInteractiveDismissAvailability","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","value":"OVKFullscreenInteractiveDismissAvailability"},{"op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments"},{"value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}