{"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/hashValue"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/hash(into:)"],"generated":true,"title":"Instance Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/rawrepresentable-implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability"]]},"metadata":{"role":"collectionGroup","modules":[{"name":"OVKit"}],"title":"RawRepresentable Implementations","roleHeading":"API Collection"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability":{"title":"FullscreenInteractiveDismissAvailability","url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability","abstract":[{"text":"Режим доступности закрытия полноэкранного режима интерактивным свайпом.","type":"text"}],"navigatorTitle":[{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullscreenInteractiveDismissAvailability","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/hashValue":{"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/hashvalue","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/hashValue","title":"hashValue","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://onevideo.OVKit/documentation/OVKit/FullscreenInteractiveDismissAvailability/hash(into:)":{"kind":"symbol","type":"topic","title":"hash(into:)","abstract":[],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/ovkit\/fullscreeninteractivedismissavailability\/hash(into:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FullscreenInteractiveDismissAvailability\/hash(into:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/title","op":"replace","value":"OVKFullscreenInteractiveDismissAvailability"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/fragments","op":"replace","value":[{"text":"OVKFullscreenInteractiveDismissAvailability","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FullscreenInteractiveDismissAvailability\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKFullscreenInteractiveDismissAvailability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}