{"abstract":[{"text":"Вызывается для получения ресурса.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"getItemForIndexPath","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"prefetcher","content":[{"inlineContent":[{"type":"text","text":"Вызывающий "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"indexPath","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", по которому нужно получить ресурс."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"Ресурс по запрошенному ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"text":", если он существует.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"required":true,"symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource(im)indexPrefetcher:getItemForIndexPath:","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:getItemForIndexPath:"}],"title":"indexPrefetcher(_:getItemForIndexPath:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"getItemForIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem","text":"PrefetchItem"},{"kind":"text","text":"?"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:getItemForIndexPath:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:getitemforindexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:getitemforindexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource":{"url":"\/documentation\/ovkit\/indexprefetcherdatasource","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"title":"IndexPrefetcherDataSource","abstract":[{"text":"Протокол, определяющий источник данных для префетчера списка.","type":"text"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"kind":"symbol","url":"\/documentation\/ovkit\/indexprefetcher","role":"symbol","title":"IndexPrefetcher","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IndexPrefetcher","kind":"identifier"}],"navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}],"abstract":[{"text":"Префетчер списка видеозаписей.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource/indexPrefetcher(_:getItemForIndexPath:)":{"url":"\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:getitemforindexpath:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:getItemForIndexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"text":"getItemForIndexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"PrefetchItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":"?","kind":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"indexPrefetcher:getItemForIndexPath:","kind":"identifier"}],"title":"indexPrefetcher(_:getItemForIndexPath:)","abstract":[{"text":"Вызывается для получения ресурса.","type":"text"}],"type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetchItem":{"title":"PrefetchItem","url":"\/documentation\/ovkit\/prefetchitem","navigatorTitle":[{"kind":"identifier","text":"PrefetchItem"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetchItem","abstract":[{"type":"text","text":"Протокол, описывающий параметры предзагрузки видео-ресурса."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetchItem"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"indexPrefetcher:getItemForIndexPath:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:getItemForIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<OVKPrefetchItem>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPrefetchItem"},{"text":") ","kind":"text"},{"text":"indexPrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","text":"OVKIndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":" *) ","kind":"text"},{"text":"prefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"getItemForIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызывающий "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher"},{"type":"text","text":"."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", по которому нужно получить ресурс."}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"Ресурс по запрошенному "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", если он существует."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"OVKIndexPrefetcherDataSource","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKIndexPrefetcherDataSource"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/fragments"},{"op":"replace","value":[{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/navigatorTitle"},{"op":"replace","value":"OVKIndexPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"op":"replace","value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"},{"op":"replace","value":"indexPrefetcher:getItemForIndexPath:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:getItemForIndexPath:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPrefetcher:getItemForIndexPath:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:getItemForIndexPath:)\/fragments"},{"op":"replace","value":"OVKPrefetchItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/title"},{"op":"replace","value":[{"text":"OVKPrefetchItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPrefetchItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetchItem\/navigatorTitle"}]}]}