{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:nextIndexPathOfIndexPath:)"},"metadata":{"symbolKind":"method","required":true,"title":"indexPrefetcher(_:nextIndexPathOfIndexPath:)","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"c:@M@OVKit@objc(pl)OVKIndexPrefetcherDataSource(im)indexPrefetcher:nextIndexPathOfIndexPath:","navigatorTitle":[{"kind":"identifier","text":"indexPrefetcher:nextIndexPathOfIndexPath:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextIndexPathOfIndexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPrefetcher"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher","text":"IndexPrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextIndexPathOfIndexPath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызывающий "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","type":"reference","isActive":true},{"type":"text","text":"."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"IndexPath","type":"codeVoice"},{"type":"text","text":", для которого необходимо вернуть следующий."}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Следующий после переданного ","type":"text"},{"code":"IndexPath","type":"codeVoice"},{"text":" или ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", если данных больше нет.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource"]]},"variants":[{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:nextindexpathofindexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:nextindexpathofindexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Вызывается для получения ресурса.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource/indexPrefetcher(_:nextIndexPathOfIndexPath:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IndexPrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nextIndexPathOfIndexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?","kind":"text"}],"required":true,"title":"indexPrefetcher(_:nextIndexPathOfIndexPath:)","type":"topic","kind":"symbol","abstract":[{"text":"Вызывается для получения ресурса.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource\/indexPrefetcher(_:nextIndexPathOfIndexPath:)","url":"\/documentation\/ovkit\/indexprefetcherdatasource\/indexprefetcher(_:nextindexpathofindexpath:)","role":"symbol","navigatorTitle":[{"text":"indexPrefetcher:nextIndexPathOfIndexPath:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcherDataSource":{"title":"IndexPrefetcherDataSource","abstract":[{"type":"text","text":"Протокол, определяющий источник данных для префетчера списка."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcherDataSource","navigatorTitle":[{"kind":"identifier","text":"IndexPrefetcherDataSource"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/indexprefetcherdatasource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IndexPrefetcherDataSource","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/IndexPrefetcher":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndexPrefetcher"}],"title":"IndexPrefetcher","url":"\/documentation\/ovkit\/indexprefetcher","kind":"symbol","type":"topic","navigatorTitle":[{"text":"IndexPrefetcher","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"indexPrefetcher:nextIndexPathOfIndexPath:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:nextIndexPathOfIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"indexPrefetcher:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKIndexPrefetcher","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKIndexPrefetcher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefetcher"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextIndexPathOfIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"prefetcher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызывающий "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/IndexPrefetcher","isActive":true},{"type":"text","text":"."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":", для которого необходимо вернуть следующий."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Следующий после переданного "},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":" или "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", если данных больше нет."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"indexPrefetcher:nextIndexPathOfIndexPath:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:nextIndexPathOfIndexPath:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"indexPrefetcher:nextIndexPathOfIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource~1indexPrefetcher(_:nextIndexPathOfIndexPath:)\/fragments"},{"value":"OVKIndexPrefetcherDataSource","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/title"},{"value":[{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/fragments"},{"value":[{"text":"OVKIndexPrefetcherDataSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcherDataSource\/navigatorTitle"},{"value":"OVKIndexPrefetcher","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/title"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/fragments"},{"value":[{"text":"OVKIndexPrefetcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1IndexPrefetcher\/navigatorTitle"}]}]}