{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"changeRateAvailable(for:)","externalID":"s:5OVKit24HoldToChangeRateBehaviorC06changeE9Available3forSbAA11ControlMaskC_tFZ","modules":[{"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeRateAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ControlMask","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeRateAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controlMask","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/changerateavailable(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/changeRateAvailable(for:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/changeRateAvailable(for:)":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/changeRateAvailable(for:)","title":"changeRateAvailable(for:)","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/changerateavailable(for:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRateAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ControlMask","preciseIdentifier":"s:5OVKit11ControlMaskC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"navigatorTitle":[{"kind":"identifier","text":"ControlMask"}],"url":"\/documentation\/ovkit\/controlmask","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlMask"}],"type":"topic","abstract":[{"type":"text","text":"Объект, отражающий внутреннее состояние плеера для отображения в UI."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","kind":"symbol","title":"ControlMask"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior","abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"type":"topic","title":"HoldToChangeRateBehavior"}},"variantOverrides":[{"patch":[{"value":"HoldToChangeRateBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title"},{"value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments"},{"value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}