{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/controlsView","interfaceLanguage":"swift"},"metadata":{"title":"controlsView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit24HoldToChangeRateBehaviorC12controlsViewAA014PlayerControlsH8Protocol_pSgvp","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"aside","name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"Свойство должно быть weak!","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"variants":[{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/controlsview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"PlayerControlsViewProtocol"}],"abstract":[{"type":"text","text":"Базовый протокол для контролов, которые могут использоваться в плеере."}],"url":"\/documentation\/ovkit\/playercontrolsviewprotocol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol","type":"topic","title":"PlayerControlsViewProtocol","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"title":"HoldToChangeRateBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/controlsView":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior\/controlsview","title":"controlsView","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/controlsView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlsView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"Контролы, на которые добавляется поведение.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title","value":"HoldToChangeRateBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments","value":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}