{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gesture","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gesture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/gesture"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"gesture","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit24HoldToChangeRateBehaviorC7gestureSo28UILongPressGestureRecognizerCvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/gesture":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gesture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gesture","kind":"symbol","abstract":[],"title":"gesture","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/gesture"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"url":"\/documentation\/ovkit\/holdtochangeratebehavior","title":"HoldToChangeRateBehavior","role":"symbol","abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"navigatorTitle":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HoldToChangeRateBehavior","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title","op":"replace","value":"HoldToChangeRateBehavior"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments","op":"replace","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}]}]}]}