{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"touch","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"metadata":{"extendedModule":"OVKit","externalID":"c:@CM@OVKit@objc(cs)HoldToChangeRateBehavior(im)gestureRecognizer:shouldReceiveTouch:","roleHeading":"Instance Method","role":"symbol","title":"gestureRecognizer(_:shouldReceive:)","modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gestureRecognizer(_:shouldReceive:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"abstract":[],"url":"\/documentation\/ovkit\/holdtochangeratebehavior\/gesturerecognizer(_:shouldreceive:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"gestureRecognizer(_:shouldReceive:)"},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"url":"\/documentation\/ovkit\/holdtochangeratebehavior","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"title":"HoldToChangeRateBehavior"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldReceiveTouch:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"touch"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title","value":"HoldToChangeRateBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle","value":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}