{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"abstract":[{"text":"Создание поведения.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/init(shouldbeginwithrate:layoutsetup:onstart:onend:)"]}],"metadata":{"roleHeading":"Initializer","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shouldBeginWithRate"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"layoutSetup"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"onStart","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":"?, ","kind":"text"},{"text":"onEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?)"}],"title":"init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit24HoldToChangeRateBehaviorC015shouldBeginWithE011layoutSetup7onStart0L3EndACSfSgSfc_ySo6UIViewCcyycSgAKtcfc"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shouldBeginWithRate"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"layoutSetup"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit9VoidBlocka","kind":"typeIdentifier","text":"VoidBlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"onEnd"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"shouldBeginWithRate","content":[{"inlineContent":[{"text":"Блок должен вернуть скорость воспроизведения, на которую необходимо переключиться в момент воспроизведения. Параметром является текущая скорость воспроизведения. Если вернуть ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", жест не активируется.","type":"text"}],"type":"paragraph"}]},{"name":"layoutSetup","content":[{"type":"paragraph","inlineContent":[{"text":"Блок вызывается после добавления ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" подсказки на контролы. В этом блоке необходимо настроить layout для переданного ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":". Можно использовать как ручной layout, так и констрейнты.","type":"text"}]}]},{"name":"onStart","content":[{"type":"paragraph","inlineContent":[{"text":"Вызывается в момент изменения скорости данным поведением.","type":"text"}]}]},{"name":"onEnd","content":[{"inlineContent":[{"text":"Вызывается после окончания работы жеста и возврата предыдущей скорости.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)","url":"\/documentation\/ovkit\/holdtochangeratebehavior\/init(shouldbeginwithrate:layoutsetup:onstart:onend:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"shouldBeginWithRate"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"layoutSetup"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"kind":"text","text":"?)"}],"title":"init(shouldBeginWithRate:layoutSetup:onStart:onEnd:)","abstract":[{"text":"Создание поведения.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"abstract":[],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoidBlock","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/voidblock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"title":"VoidBlock"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"url":"\/documentation\/ovkit\/holdtochangeratebehavior","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"title":"HoldToChangeRateBehavior"}},"variantOverrides":[{"patch":[{"value":"HoldToChangeRateBehavior","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title"},{"value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments"},{"value":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}