{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior"]]},"variants":[{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/holdtochangeratebehavior\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"UIGestureRecognizerDelegate Implementations","modules":[{"name":"OVKit"}]},"kind":"article","topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gestureRecognizer(_:shouldReceive:)"],"title":"Instance Methods"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior","navigatorTitle":[{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"abstract":[{"type":"text","text":"Изменение скорости видео нажатием и удержанием."}],"url":"\/documentation\/ovkit\/holdtochangeratebehavior","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HoldToChangeRateBehavior"}],"title":"HoldToChangeRateBehavior"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/HoldToChangeRateBehavior/gestureRecognizer(_:shouldReceive:)":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gestureRecognizer(_:shouldReceive:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"abstract":[],"url":"\/documentation\/ovkit\/holdtochangeratebehavior\/gesturerecognizer(_:shouldreceive:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","text":"UIGestureRecognizer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"gestureRecognizer(_:shouldReceive:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HoldToChangeRateBehavior\/gestureRecognizer(_:shouldReceive:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/title","value":"HoldToChangeRateBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/fragments","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior\/navigatorTitle","value":[{"text":"HoldToChangeRateBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1HoldToChangeRateBehavior~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}