{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePickedFormat"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"updatePickedFormat(_:)","externalID":"s:5OVKit23BroadcastStatsCollectorC18updatePickedFormatyyAA09VideoFileG0OF","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePickedFormat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","text":"VideoFileFormat","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/broadcaststatscollector\/updatepickedformat(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastStatsCollector\/updatePickedFormat(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastStatsCollector"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/BroadcastStatsCollector":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BroadcastStatsCollector"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastStatsCollector","type":"topic","title":"BroadcastStatsCollector","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BroadcastStatsCollector"}],"url":"\/documentation\/ovkit\/broadcaststatscollector"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VideoFileFormat":{"url":"\/documentation\/ovkit\/videofileformat","navigatorTitle":[{"kind":"identifier","text":"VideoFileFormat"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoFileFormat","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoFileFormat"}],"type":"topic","title":"VideoFileFormat","abstract":[{"type":"text","text":"Форматы видео ссылок. Отсортированы по приоритету"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BroadcastStatsCollector/updatePickedFormat(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePickedFormat"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKVideoFileFormat","text":"VideoFileFormat"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BroadcastStatsCollector\/updatePickedFormat(_:)","type":"topic","title":"updatePickedFormat(_:)","role":"symbol","url":"\/documentation\/ovkit\/broadcaststatscollector\/updatepickedformat(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/title","value":"OVKVideoFileFormat","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/fragments","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"OVKVideoFileFormat"}],"op":"replace"}]}]}