{"metadata":{"title":"bugReportButton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bugReportButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier","text":"UIButton"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:5OVKit18BottomControlsViewC15bugReportButtonSo8UIButtonCSgvp","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bottomcontrolsview\/bugreportbutton"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bugReportButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/bugReportButton"},"references":{"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/bugReportButton":{"abstract":[],"kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/bugreportbutton","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bugReportButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"bugReportButton","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/bugReportButton"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BottomControlsView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","url":"\/documentation\/ovkit\/bottomcontrolsview","abstract":[{"text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий.","type":"text"}],"title":"BottomControlsView","navigatorTitle":[{"kind":"identifier","text":"BottomControlsView"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]}]}]}