{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonsContainer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:5OVKit18BottomControlsViewC16buttonsContainerSo07UIStackD0Cvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonsContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIStackView","text":"UIStackView"}],"title":"buttonsContainer","modules":[{"name":"OVKit"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/buttonsContainer","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bottomcontrolsview\/buttonscontainer"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"title":"BottomControlsView","type":"topic","url":"\/documentation\/ovkit\/bottomcontrolsview","navigatorTitle":[{"kind":"identifier","text":"BottomControlsView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","abstract":[{"type":"text","text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomControlsView"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/buttonsContainer":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonsContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/buttonsContainer","role":"symbol","type":"topic","title":"buttonsContainer","url":"\/documentation\/ovkit\/bottomcontrolsview\/buttonscontainer","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","value":[{"kind":"identifier","text":"OVKBottomControlsView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKBottomControlsView"}],"op":"replace"}]}]}