{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"fullscreen","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showChapters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"title":"init(frame:fullscreen:showChapters:)","externalID":"s:5OVKit18BottomControlsViewC5frame10fullscreen12showChaptersACSo6CGRectV_S2btcfc","modules":[{"name":"OVKit"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/init(frame:fullscreen:showChapters:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/bottomcontrolsview\/init(frame:fullscreen:showchapters:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fullscreen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showChapters"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/init(frame:fullscreen:showChapters:)":{"type":"topic","title":"init(frame:fullscreen:showChapters:)","kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/init(frame:fullscreen:showchapters:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"text":"fullscreen","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"showChapters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/init(frame:fullscreen:showChapters:)"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BottomControlsView"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий."}],"title":"BottomControlsView","url":"\/documentation\/ovkit\/bottomcontrolsview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","role":"symbol","navigatorTitle":[{"text":"BottomControlsView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","op":"replace","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKBottomControlsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}