{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"role":"symbol","title":"settingsButton","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit18BottomControlsViewC14settingsButtonSo8UIButtonCvp","symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/bottomcontrolsview\/settingsbutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/settingsButton","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","navigatorTitle":[{"text":"BottomControlsView","kind":"identifier"}],"title":"BottomControlsView","abstract":[{"text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/bottomcontrolsview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BottomControlsView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/settingsButton":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/settingsButton","role":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/settingsbutton","type":"topic","title":"settingsButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"OVKBottomControlsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title"},{"value":[{"kind":"identifier","text":"OVKBottomControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments"},{"value":[{"kind":"identifier","text":"OVKBottomControlsView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}