{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode(scrubbingmode:thumbnailprovider:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/visibilityMode(scrubbingMode:thumbnailProvider:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibilityMode"},{"kind":"text","text":"("},{"text":"scrubbingMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"thumbnailProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","text":"ThumbnailProvider"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit18BottomControlsViewC14VisibilityModeO","text":"VisibilityMode"}],"role":"symbol","externalID":"s:5OVKit18BottomControlsViewC14visibilityMode09scrubbingF017thumbnailProviderAC010VisibilityF0OSb_AA09ThumbnailI0CSgtF","roleHeading":"Instance Method","title":"visibilityMode(scrubbingMode:thumbnailProvider:)","extendedModule":"OVKit","symbolKind":"method","modules":[{"name":"OVKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibilityMode"},{"text":"(","kind":"text"},{"text":"scrubbingMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"thumbnailProvider"},{"text":": ","kind":"text"},{"text":"ThumbnailProvider","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:5OVKit18BottomControlsViewC14VisibilityModeO","text":"VisibilityMode","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BottomControlsView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","url":"\/documentation\/ovkit\/bottomcontrolsview","abstract":[{"text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий.","type":"text"}],"title":"BottomControlsView","navigatorTitle":[{"kind":"identifier","text":"BottomControlsView"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/VisibilityMode":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisibilityMode"}],"abstract":[{"type":"text","text":"Маска видимости внутренних контролов."}],"kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode","navigatorTitle":[{"text":"VisibilityMode","kind":"identifier"}],"title":"BottomControlsView.VisibilityMode","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","type":"topic","url":"\/documentation\/ovkit\/thumbnailprovider","title":"ThumbnailProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailProvider"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/visibilityMode(scrubbingMode:thumbnailProvider:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visibilityMode"},{"kind":"text","text":"("},{"text":"scrubbingMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"thumbnailProvider","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThumbnailProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"VisibilityMode","preciseIdentifier":"s:5OVKit18BottomControlsViewC14VisibilityModeO"}],"title":"visibilityMode(scrubbingMode:thumbnailProvider:)","role":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode(scrubbingmode:thumbnailprovider:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/visibilityMode(scrubbingMode:thumbnailProvider:)","kind":"symbol","type":"topic","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView"},{"value":[{"kind":"identifier","text":"OVKBottomControlsView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle","op":"replace","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]},{"value":"OVKThumbnailProvider","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKThumbnailProvider"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","op":"replace","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}