{"metadata":{"required":true,"symbolKind":"property","roleHeading":"Instance Property","title":"itemBadgeStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemBadgeStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdsItemBadge","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","kind":"typeIdentifier"}],"externalID":"s:5OVKit28ShoppableAdsItemViewProtocolP14itemBadgeStyleAA0cdH0C0I0Ovp","modules":[{"name":"OVKit"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewProtocol"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemBadgeStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdsItemBadge","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/shoppableadsitemviewprotocol\/itembadgestyle"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewProtocol\/itemBadgeStyle","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ShoppableAdsItemViewProtocol/itemBadgeStyle":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewProtocol\/itemBadgeStyle","type":"topic","title":"itemBadgeStyle","required":true,"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemBadgeStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)AdsItemBadge","text":"AdsItemBadge"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","text":"Style"}],"url":"\/documentation\/ovkit\/shoppableadsitemviewprotocol\/itembadgestyle"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"Style"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum","type":"topic","abstract":[],"title":"AdsItemBadge.Style"},"doc://onevideo.OVKit/documentation/OVKit/ShoppableAdsItemViewProtocol":{"kind":"symbol","title":"ShoppableAdsItemViewProtocol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ShoppableAdsItemViewProtocol","abstract":[],"navigatorTitle":[{"text":"ShoppableAdsItemViewProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShoppableAdsItemViewProtocol","kind":"identifier"}],"url":"\/documentation\/ovkit\/shoppableadsitemviewprotocol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"url":"\/documentation\/ovkit\/adsitembadge","title":"AdsItemBadge","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdsItemBadge","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","op":"replace","value":"AdsItemBadge"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","op":"replace","value":[{"text":"AdsItemBadge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","op":"replace","value":[{"text":"AdsItemBadge","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}