{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovktimelinethumbnails\/countperimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovktimelinethumbnails\/countperimage"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"countPerImage","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"countPerImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails(py)countPerImage","modules":[{"name":"OVKit"}],"title":"countPerImage","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"TimelineThumbnailsType.countPerImage","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countPerImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnails\/countPerImage","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnails/countPerImage":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnails\/countPerImage","url":"\/documentation\/ovkit\/ovktimelinethumbnails\/countperimage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"countPerImage"}],"abstract":[],"title":"countPerImage","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countPerImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","title":"OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","type":"topic","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"title":"TimelineThumbnails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineThumbnails"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnails"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","url":"\/documentation\/ovkit\/timelinethumbnails","abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"countPerImage"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"countPerImage"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countPerImage"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"countPerImage","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnails~1countPerImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"countPerImage"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnails~1countPerImage\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title","value":"OVKTimelineThumbnails","op":"replace"},{"value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments"}]}]}