{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"frameSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnails\/frameSize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"frameSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"frameSize","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails(py)frameSize","role":"symbol","title":"frameSize"},"variants":[{"paths":["\/documentation\/ovkit\/ovktimelinethumbnails\/framesize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovktimelinethumbnails\/framesize"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"TimelineThumbnailsType.frameSize"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"title":"TimelineThumbnails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimelineThumbnails"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnails"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","url":"\/documentation\/ovkit\/timelinethumbnails","abstract":[],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKTimelineThumbnails/frameSize":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/ovktimelinethumbnails\/framesize","title":"frameSize","navigatorTitle":[{"kind":"identifier","text":"frameSize"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKTimelineThumbnails\/frameSize","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"frameSize"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"frameSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameSize"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"OVKTimelineThumbnails","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnails~1frameSize\/title","op":"replace","value":"frameSize"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKTimelineThumbnails~1frameSize\/fragments","value":[{"kind":"identifier","text":"frameSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}