{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adbannerprogress(_:bannerinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adbannerprogress(_:bannerinfo:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBannerProgress"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"StatsProgress","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"progress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Участки 3s, 10s, 25p, 50p, 75p, 100p."}]}]},{"name":"bannerInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Информация о рекламном баннере"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerProgress(_:bannerInfo:)"},"abstract":[{"type":"text","text":"Пользователь досмотрел до определенных участков."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerProgress","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","text":"StatsProgress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"adBannerProgress(_:bannerInfo:)","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"adBannerProgress:bannerInfo:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adBannerProgress:bannerInfo:"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"title":"AdStatsHandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","url":"\/documentation\/ovkit\/adstatshandler","abstract":[{"type":"text","text":"Принимает события, связанные с воспроизведением рекламы."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdStatsBannerInfo"}],"title":"AdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","url":"\/documentation\/ovkit\/adstatsbannerinfo","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/StatsProgress":{"title":"StatsProgress","url":"\/documentation\/ovkit\/statsprogress","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsProgress","kind":"identifier"}],"navigatorTitle":[{"text":"StatsProgress","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adBannerProgress(_:bannerInfo:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerProgress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"StatsProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bannerInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}],"title":"adBannerProgress(_:bannerInfo:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerProgress(_:bannerInfo:)","url":"\/documentation\/ovkit\/adstatshandler\/adbannerprogress(_:bannerinfo:)","abstract":[{"type":"text","text":"Пользователь досмотрел до определенных участков."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"adBannerProgress:bannerInfo:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adBannerProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKStatsProgress","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsProgress","text":"OVKStatsProgress","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bannerInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","text":"OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bannerInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Участки 3s, 10s, 25p, 50p, 75p, 100p.","type":"text"}]}],"name":"progress"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Информация о рекламном баннере","type":"text"}]}],"name":"bannerInfo"}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","op":"replace","value":"OVKAdStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","op":"replace","value":"OVKAdStatsBannerInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/title","op":"replace","value":"OVKStatsProgress"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKStatsProgress"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerProgress(_:bannerInfo:)\/title","op":"replace","value":"adBannerProgress:bannerInfo:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerProgress(_:bannerInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adBannerProgress:bannerInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}