{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adbannerstart(bannerinfo:duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adbannerstart(bannerinfo:duration:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adBannerStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"bannerInfo","content":[{"inlineContent":[{"type":"text","text":"Информация о рекламном баннере"}],"type":"paragraph"}]},{"name":"duration","content":[{"inlineContent":[{"text":"Количество секунд с момента запроса рекламы до старта баннера.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adBannerStartWithBannerInfo:duration:","title":"adBannerStart(bannerInfo:duration:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adBannerStartWithBannerInfo:duration:"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBannerStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier","text":"AdStatsBannerInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerStart(bannerInfo:duration:)"},"abstract":[{"text":"Запустился рекламный баннер.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"url":"\/documentation\/ovkit\/adstatsbannerinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"title":"AdStatsBannerInfo","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adBannerStart(bannerInfo:duration:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adBannerStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}],"title":"adBannerStart(bannerInfo:duration:)","abstract":[{"type":"text","text":"Запустился рекламный баннер."}],"kind":"symbol","url":"\/documentation\/ovkit\/adstatshandler\/adbannerstart(bannerinfo:duration:)","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adBannerStart(bannerInfo:duration:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsCollector"}],"url":"\/documentation\/ovkit\/statscollector","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true,"type":"reference"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"title":"StatsCollector","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"url":"\/documentation\/ovkit\/adstatshandler","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","role":"symbol","navigatorTitle":[{"text":"AdStatsHandler","kind":"identifier"}],"type":"topic","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"text":" после добавления нового ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","isActive":true,"type":"reference"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"title":"AdStatsHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsHandler","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"adBannerStartWithBannerInfo:duration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"adBannerStartWithBannerInfo:duration:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adBannerStartWithBannerInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"OVKAdStatsBannerInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bannerInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Информация о рекламном баннере","type":"text"}],"type":"paragraph"}],"name":"bannerInfo"},{"content":[{"inlineContent":[{"text":"Количество секунд с момента запроса рекламы до старта баннера.","type":"text"}],"type":"paragraph"}],"name":"duration"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"OVKAdStatsBannerInfo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title"},{"value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments"},{"value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle"},{"value":"adBannerStartWithBannerInfo:duration:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerStart(bannerInfo:duration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adBannerStartWithBannerInfo:duration:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adBannerStart(bannerInfo:duration:)\/fragments"},{"value":"OVKStatsCollector","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle"},{"value":"OVKAdStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title"},{"value":[{"text":"OVKAdStatsHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments"},{"value":[{"kind":"identifier","text":"OVKAdStatsHandler"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle"}]}]}