{"abstract":[{"text":"Ошибка воспроизведения рекламы.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adFailed"},{"text":"(","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"reason","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Причина, указанная рекламным плеером."}]}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"required":true,"externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adFailedWithReason:","title":"adFailed(reason:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"adFailedWithReason:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adFailed(reason:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/adstatshandler\/adfailed(reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/adstatshandler\/adfailed(reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adFailed(reason:)":{"required":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adFailed(reason:)","title":"adFailed(reason:)","kind":"symbol","navigatorTitle":[{"text":"adFailedWithReason:","kind":"identifier"}],"abstract":[{"text":"Ошибка воспроизведения рекламы.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/ovkit\/adstatshandler\/adfailed(reason:)"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"type":"topic","title":"StatsCollector","url":"\/documentation\/ovkit\/statscollector","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Не привязан к "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"или переходах в PiP и fullscreen."}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdStatsHandler","kind":"identifier"}],"type":"topic","title":"AdStatsHandler","url":"\/documentation\/ovkit\/adstatshandler","kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":" после добавления нового ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","isActive":true,"type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"navigatorTitle":[{"text":"AdStatsHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adFailedWithReason:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adFailedWithReason:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"adFailedWithReason:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adFailed(reason:)\/title","op":"replace","value":"adFailedWithReason:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adFailedWithReason:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adFailed(reason:)\/fragments","op":"replace"},{"value":"OVKStatsCollector","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace"},{"value":"OVKAdStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","op":"replace","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]}]}]}