{"metadata":{"navigatorTitle":[{"text":"adNoBannersWithResponseTime:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adNoBannersWithResponseTime:","modules":[{"name":"OVKit"}],"role":"symbol","title":"adNoBanners(responseTime:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adNoBanners","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adNoBanners(responseTime:)","interfaceLanguage":"swift"},"abstract":[{"text":"Рекламный плеер не будет играть рекламу для данного видео.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/adstatshandler\/adnobanners(responsetime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/adstatshandler\/adnobanners(responsetime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adNoBanners","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Количество секунд с момента запроса рекламы до получения ответа."}],"type":"paragraph"}],"name":"responseTime"}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"url":"\/documentation\/ovkit\/adstatshandler","abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","kind":"symbol","title":"AdStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adNoBanners(responseTime:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adNoBanners(responseTime:)","role":"symbol","navigatorTitle":[{"text":"adNoBannersWithResponseTime:","kind":"identifier"}],"url":"\/documentation\/ovkit\/adstatshandler\/adnobanners(responsetime:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adNoBanners","kind":"identifier"},{"text":"(","kind":"text"},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"title":"adNoBanners(responseTime:)","abstract":[{"type":"text","text":"Рекламный плеер не будет играть рекламу для данного видео."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"adNoBannersWithResponseTime:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adNoBannersWithResponseTime:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"adNoBannersWithResponseTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"text":"responseTime","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"responseTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Количество секунд с момента запроса рекламы до получения ответа."}]}]}]},"op":"replace"},{"value":"OVKAdStatsHandler","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAdStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAdStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","op":"replace"},{"value":"adNoBannersWithResponseTime:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adNoBanners(responseTime:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adNoBannersWithResponseTime:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adNoBanners(responseTime:)\/fragments","op":"replace"}]}]}