{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adrequestbanner(bannerinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adrequestbanner(bannerinfo:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"metadata":{"navigatorTitle":[{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adRequestBannerWithBannerInfo:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adRequestBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","kind":"typeIdentifier","text":"AdStatsBannerInfo"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"adRequestBanner(bannerInfo:)","symbolKind":"method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adRequestBanner(bannerInfo:)"},"abstract":[{"text":"Запрос на воспроизведение баннера к рекламному плееру.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adRequestBanner(bannerInfo:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adRequestBanner(bannerInfo:)","role":"symbol","navigatorTitle":[{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"}],"url":"\/documentation\/ovkit\/adstatshandler\/adrequestbanner(bannerinfo:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adRequestBanner","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"text":")","kind":"text"}],"title":"adRequestBanner(bannerInfo:)","abstract":[{"type":"text","text":"Запрос на воспроизведение баннера к рекламному плееру."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdStatsHandler"}],"url":"\/documentation\/ovkit\/adstatshandler","abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","kind":"symbol","title":"AdStatsHandler"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"title":"AdStatsBannerInfo","url":"\/documentation\/ovkit\/adstatsbannerinfo","abstract":[],"navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adRequestBannerWithBannerInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"adRequestBannerWithBannerInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"text":" *) ","kind":"text"},{"text":"bannerInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adRequestBanner(bannerInfo:)\/title","value":"adRequestBannerWithBannerInfo:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adRequestBanner(bannerInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adRequestBannerWithBannerInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","value":"OVKAdStatsHandler"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","value":[{"kind":"identifier","text":"OVKAdStatsHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","value":"OVKAdStatsBannerInfo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","value":[{"text":"OVKAdStatsBannerInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}