{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adSkip(bannerInfo:)","interfaceLanguage":"swift"},"abstract":[{"text":"Пользователь нажал кнопку пропуска рекламы.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adskip(bannerinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/adstatshandler\/adskip(bannerinfo:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"adSkip(bannerInfo:)","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(pl)OVKAdStatsHandler(im)adSkipWithBannerInfo:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"adSkipWithBannerInfo:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adSkip","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo","text":"AdStatsBannerInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"bannerInfo","content":[{"inlineContent":[{"text":"Информация о рекламном баннере","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdStatsBannerInfo":{"url":"\/documentation\/ovkit\/adstatsbannerinfo","navigatorTitle":[{"text":"AdStatsBannerInfo","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdStatsBannerInfo","kind":"identifier"}],"type":"topic","title":"AdStatsBannerInfo","abstract":[{"type":"text","text":"Описание рекламного баннера."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdStatsHandler"}],"abstract":[{"text":"Принимает события, связанные с воспроизведением рекламы.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler","title":"AdStatsHandler","role":"symbol","navigatorTitle":[{"text":"AdStatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/adstatshandler"},"doc://onevideo.OVKit/documentation/OVKit/AdStatsHandler/adSkip(bannerInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"adSkipWithBannerInfo:"}],"url":"\/documentation\/ovkit\/adstatshandler\/adskip(bannerinfo:)","abstract":[{"type":"text","text":"Пользователь нажал кнопку пропуска рекламы."}],"title":"adSkip(bannerInfo:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsHandler\/adSkip(bannerInfo:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSkip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdStatsBannerInfo","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":")"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"adSkipWithBannerInfo:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"adSkipWithBannerInfo:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OVKAdStatsBannerInfo","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdStatsBannerInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKAdStatsBannerInfo"},{"kind":"text","text":" *) "},{"text":"bannerInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"bannerInfo","content":[{"inlineContent":[{"text":"Информация о рекламном баннере","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/title","op":"replace","value":"OVKAdStatsBannerInfo"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsBannerInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKAdStatsBannerInfo"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/title","op":"replace","value":"OVKAdStatsHandler"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/fragments","op":"replace","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler\/navigatorTitle","op":"replace","value":[{"text":"OVKAdStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adSkip(bannerInfo:)\/title","op":"replace","value":"adSkipWithBannerInfo:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdStatsHandler~1adSkip(bannerInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"adSkipWithBannerInfo:","kind":"identifier"}],"op":"replace"}]}]}