{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"OVKit"}]},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"variants":[{"paths":["\/documentation\/ovkit\/menustyle\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"kind":"symbol","title":"MenuStyle","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"url":"\/documentation\/ovkit\/menustyle"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/!=(_:_:)":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/!=(_:_:)","role":"symbol","url":"\/documentation\/ovkit\/menustyle\/!=(_:_:)","type":"topic","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","value":"OVKMenuStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","value":[{"text":"OVKMenuStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","value":[{"text":"OVKMenuStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}