{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/RawRepresentable-Implementations"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle\/hashvalue"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@OVKit@E@OVKMenuStyle","title":"hashValue","extendedModule":"Swift","symbolKind":"property","modules":[{"name":"OVKit","relatedModules":["Swift"]}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hashValue","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/hashValue":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hashValue","abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"hashValue","url":"\/documentation\/ovkit\/menustyle\/hashvalue"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuStyle"}],"url":"\/documentation\/ovkit\/menustyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","kind":"symbol","title":"MenuStyle","abstract":[{"type":"text","text":"Стиль меню, в котором требуется отображать его пункты."}],"role":"symbol","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/RawRepresentable-Implementations","url":"\/documentation\/ovkit\/menustyle\/rawrepresentable-implementations","kind":"article","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","value":"OVKMenuStyle"},{"value":[{"kind":"identifier","text":"OVKMenuStyle"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","op":"replace","value":[{"text":"OVKMenuStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}