{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"MenuStyle.imageSubtitle","externalID":"c:@M@OVKit@E@OVKMenuStyle@OVKMenuStyleImageSubtitle","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleImageSubtitle"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSubtitle"}]},"kind":"symbol","abstract":[{"text":"Пункты меню с иконкой, названием и описанием.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSubtitle"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageSubtitle","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle\/imagesubtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menustyle\/imagesubtitle"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuStyle"}],"kind":"symbol","abstract":[{"type":"text","text":"Стиль меню, в котором требуется отображать его пункты."}],"type":"topic","title":"MenuStyle","navigatorTitle":[{"kind":"identifier","text":"MenuStyle"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","url":"\/documentation\/ovkit\/menustyle"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/imageSubtitle":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSubtitle"}],"kind":"symbol","abstract":[{"type":"text","text":"Пункты меню с иконкой, названием и описанием."}],"type":"topic","title":"MenuStyle.imageSubtitle","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleImageSubtitle"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageSubtitle","url":"\/documentation\/ovkit\/menustyle\/imagesubtitle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuStyleImageSubtitle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyleImageSubtitle"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"OVKMenuStyleImageSubtitle","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","op":"replace","value":"OVKMenuStyle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyle"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","op":"replace","value":[{"text":"OVKMenuStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageSubtitle\/title","op":"replace","value":"OVKMenuStyleImageSubtitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageSubtitle\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyleImageSubtitle"}]}]}]}