{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageTitle"},"metadata":{"symbolKind":"case","title":"MenuStyle.imageTitle","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKMenuStyle@OVKMenuStyleImageTitle","role":"symbol","navigatorTitle":[{"text":"OVKMenuStyleImageTitle","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageTitle","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageTitle","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"variants":[{"paths":["\/documentation\/ovkit\/menustyle\/imagetitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menustyle\/imagetitle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Пункты меню с иконкой и названием.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/menustyle","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","role":"symbol","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"title":"MenuStyle"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/imageTitle":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTitle"}],"title":"MenuStyle.imageTitle","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Пункты меню с иконкой и названием."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/imageTitle","url":"\/documentation\/ovkit\/menustyle\/imagetitle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleImageTitle"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKMenuStyleImageTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMenuStyleImageTitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKMenuStyleImageTitle","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","value":"OVKMenuStyle"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","value":[{"kind":"identifier","text":"OVKMenuStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageTitle\/title","value":"OVKMenuStyleImageTitle"},{"value":[{"text":"OVKMenuStyleImageTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1imageTitle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}