{"metadata":{"role":"symbol","symbolKind":"init","externalID":"s:5OVKit9MenuStyleO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit"}],"roleHeading":"Initializer","title":"init(rawValue:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/init(rawValue:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/menustyle\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/init(rawValue:)":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/init(rawValue:)","url":"\/documentation\/ovkit\/menustyle\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/menustyle","navigatorTitle":[{"kind":"identifier","text":"MenuStyle"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MenuStyle","kind":"identifier"}],"title":"MenuStyle","abstract":[{"type":"text","text":"Стиль меню, в котором требуется отображать его пункты."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"OVKMenuStyle","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title"},{"op":"replace","value":[{"text":"OVKMenuStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments"},{"value":[{"kind":"identifier","text":"OVKMenuStyle"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}