{"metadata":{"role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"OVKit"}],"roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/RawRepresentable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle\/rawrepresentable-implementations"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"title":"MenuStyle","role":"symbol","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"type":"topic","url":"\/documentation\/ovkit\/menustyle","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/hashValue":{"url":"\/documentation\/ovkit\/menustyle\/hashvalue","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hashValue","title":"hashValue","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]}},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/hash(into:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"title":"hash(into:)","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/menustyle\/hash(into:)","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKMenuStyle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title"},{"value":[{"kind":"identifier","text":"OVKMenuStyle"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","value":[{"text":"OVKMenuStyle","kind":"identifier"}]}]}]}