{"sections":[],"metadata":{"role":"symbol","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleSelectionMultiline"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionMultiline","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKMenuStyle@OVKMenuStyleSelectionMultiline","modules":[{"name":"OVKit"}],"title":"MenuStyle.selectionMultiline"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle\/selectionmultiline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menustyle\/selectionmultiline"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionMultiline"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionMultiline","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"kind":"symbol","abstract":[{"type":"text","text":"Пункты меню с возможностью выбора, названием и многострочным описанием."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/selectionMultiline":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionMultiline"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionMultiline","title":"MenuStyle.selectionMultiline","url":"\/documentation\/ovkit\/menustyle\/selectionmultiline","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleSelectionMultiline"}],"abstract":[{"type":"text","text":"Пункты меню с возможностью выбора, названием и многострочным описанием."}]},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MenuStyle","kind":"identifier"}],"kind":"symbol","title":"MenuStyle","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MenuStyle","kind":"identifier"}],"url":"\/documentation\/ovkit\/menustyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKMenuStyleSelectionMultiline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMenuStyleSelectionMultiline"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKMenuStyleSelectionMultiline","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"OVKMenuStyleSelectionMultiline","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionMultiline\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionMultiline\/fragments","value":[{"text":"OVKMenuStyleSelectionMultiline","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title","op":"replace","value":"OVKMenuStyle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","op":"replace","value":[{"text":"OVKMenuStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKMenuStyle"}]}]}]}