{"kind":"symbol","abstract":[{"type":"text","text":"Пункты меню с возможностью выбора, названием и однострочным описанием."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"selectionCompact","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/menustyle\/selectioncompact"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menustyle\/selectioncompact"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionCompact"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionCompact"}],"navigatorTitle":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}],"role":"symbol","modules":[{"name":"OVKit"}],"title":"MenuStyle.selectionCompact","externalID":"c:@M@OVKit@E@OVKMenuStyle@OVKMenuStyleSelectionCompact","roleHeading":"Case","symbolKind":"case"},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuStyle/selectionCompact":{"kind":"symbol","abstract":[{"type":"text","text":"Пункты меню с возможностью выбора, названием и однострочным описанием."}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuStyleSelectionCompact"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle\/selectionCompact","title":"MenuStyle.selectionCompact","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/menustyle\/selectioncompact","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectionCompact","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MenuStyle":{"role":"symbol","title":"MenuStyle","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MenuStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MenuStyle"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuStyle","abstract":[{"text":"Стиль меню, в котором требуется отображать его пункты.","type":"text"}],"url":"\/documentation\/ovkit\/menustyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKMenuStyleSelectionCompact"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionCompact\/title","value":"OVKMenuStyleSelectionCompact"},{"value":[{"text":"OVKMenuStyleSelectionCompact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle~1selectionCompact\/fragments"},{"value":"OVKMenuStyle","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/fragments","value":[{"text":"OVKMenuStyle","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuStyle"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuStyle\/navigatorTitle"}]}]}