{"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenDuringTransition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","externalID":"s:5OVKit16HideableControlsP30shouldBeHiddenDuringTransitionSbvp","role":"symbol","required":true,"title":"shouldBeHiddenDuringTransition","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/hideablecontrols\/shouldbehiddenduringtransition"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Должны ли контролы скрываться во время переходов между ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":". Рекомендуется возвращать ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenDuringTransition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls\/shouldBeHiddenDuringTransition"},"references":{"doc://onevideo.OVKit/documentation/OVKit/HideableControls":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HideableControls"}],"title":"HideableControls","navigatorTitle":[{"kind":"identifier","text":"HideableControls"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls","url":"\/documentation\/ovkit\/hideablecontrols","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","url":"\/documentation\/ovkit\/playerview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/HideableControls/shouldBeHiddenDuringTransition":{"url":"\/documentation\/ovkit\/hideablecontrols\/shouldbehiddenduringtransition","kind":"symbol","required":true,"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeHiddenDuringTransition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/HideableControls\/shouldBeHiddenDuringTransition","title":"shouldBeHiddenDuringTransition","abstract":[{"type":"text","text":"Должны ли контролы скрываться во время переходов между "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":". Рекомендуется возвращать "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}