{"abstract":[{"type":"text","text":"Начало анимации переноса плеера в другое "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/transitionablecontrols\/didbegintransitionanimation(duration:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBeginTransitionAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Длительность анимации, в секундах.","type":"text"}],"type":"paragraph"}],"name":"duration"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didBeginTransitionAnimation(duration:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBeginTransitionAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"title":"didBeginTransitionAnimation(duration:)","roleHeading":"Instance Method","externalID":"s:5OVKit22TransitionableControlsP27didBeginTransitionAnimation8durationySd_tF","required":true,"role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"type":"text","text":"Основной компонент для воспроизведения видео."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"role":"symbol","title":"PlayerView","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/didBeginTransitionAnimation(duration:)":{"title":"didBeginTransitionAnimation(duration:)","required":true,"url":"\/documentation\/ovkit\/transitionablecontrols\/didbegintransitionanimation(duration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBeginTransitionAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didBeginTransitionAnimation(duration:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Начало анимации переноса плеера в другое "},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/transitionablecontrols","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionableControls"}],"title":"TransitionableControls","navigatorTitle":[{"kind":"identifier","text":"TransitionableControls"}],"abstract":[{"type":"text","text":"Протокол для контролов, поддерживающих анимированный перенос между "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":"."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"text":"OVKPlayerView","kind":"identifier"}]}]}]}