{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didFinishTransition","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/transitionablecontrols\/didfinishtransition()"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didFinishTransition()"},"metadata":{"title":"didFinishTransition()","modules":[{"name":"OVKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFinishTransition","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:5OVKit22TransitionableControlsP19didFinishTransitionyyF","roleHeading":"Instance Method","symbolKind":"method","required":true},"abstract":[{"text":"Завершение переноса плеера в другое ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":".","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls":{"type":"topic","title":"TransitionableControls","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","url":"\/documentation\/ovkit\/transitionablecontrols","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionableControls"}],"abstract":[{"text":"Протокол для контролов, поддерживающих анимированный перенос между ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"TransitionableControls","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"url":"\/documentation\/ovkit\/playerview","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/didFinishTransition()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFinishTransition","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"kind":"symbol","url":"\/documentation\/ovkit\/transitionablecontrols\/didfinishtransition()","title":"didFinishTransition()","abstract":[{"type":"text","text":"Завершение переноса плеера в другое "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/didFinishTransition()"}},"variantOverrides":[{"patch":[{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}