{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBeginTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destinationControlsView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"destinationControlsView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Контролы от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":", на которое происходит перенос.","type":"text"}]}]}]}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"willBeginTransition(to:)","required":true,"externalID":"s:5OVKit22TransitionableControlsP19willBeginTransition2toyAA06PlayerC12ViewProtocol_pSg_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willBeginTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","text":"PlayerControlsViewProtocol"},{"kind":"text","text":"?)"}]},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/willBeginTransition(to:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Начало переноса плеера в другое ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/transitionablecontrols\/willbegintransition(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"url":"\/documentation\/ovkit\/playerview","title":"PlayerView","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","navigatorTitle":[{"kind":"identifier","text":"PlayerView"}],"abstract":[{"text":"Основной компонент для воспроизведения видео.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerControlsViewProtocol":{"abstract":[{"text":"Базовый протокол для контролов, которые могут использоваться в плеере.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/playercontrolsviewprotocol","title":"PlayerControlsViewProtocol","kind":"symbol","navigatorTitle":[{"text":"PlayerControlsViewProtocol","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerControlsViewProtocol"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls/willBeginTransition(to:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willBeginTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5OVKit26PlayerControlsViewProtocolP","kind":"typeIdentifier","text":"PlayerControlsViewProtocol"},{"kind":"text","text":"?)"}],"url":"\/documentation\/ovkit\/transitionablecontrols\/willbegintransition(to:)","abstract":[{"text":"Начало переноса плеера в другое ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":".","type":"text"}],"title":"willBeginTransition(to:)","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls\/willBeginTransition(to:)","required":true},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/TransitionableControls":{"url":"\/documentation\/ovkit\/transitionablecontrols","role":"symbol","type":"topic","title":"TransitionableControls","kind":"symbol","abstract":[{"type":"text","text":"Протокол для контролов, поддерживающих анимированный перенос между "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TransitionableControls","navigatorTitle":[{"kind":"identifier","text":"TransitionableControls"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionableControls"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPlayerView"}]}]}]}