{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellular","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"NetworkConnection.cellular","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellular","kind":"identifier"}],"modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKNetworkConnectionCellular","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKNetworkConnection@OVKNetworkConnectionCellular"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/cellular","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnection\/cellular"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnection\/cellular"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/cellular":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/cellular","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular"}],"title":"NetworkConnection.cellular","url":"\/documentation\/ovkit\/networkconnection\/cellular","navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionCellular"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnection"}],"url":"\/documentation\/ovkit\/networkconnection","navigatorTitle":[{"kind":"identifier","text":"NetworkConnection"}],"kind":"symbol","title":"NetworkConnection"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKNetworkConnectionCellular"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKNetworkConnectionCellular","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKNetworkConnectionCellular","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1cellular\/title","value":"OVKNetworkConnectionCellular"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1cellular\/fragments","value":[{"text":"OVKNetworkConnectionCellular","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","value":"OVKNetworkConnection"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","value":[{"text":"OVKNetworkConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}