{"metadata":{"roleHeading":"API Collection","modules":[{"name":"OVKit"}],"role":"collectionGroup","title":"Equatable Implementations"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnection\/equatable-implementations"]}],"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/!=(_:_:)"],"generated":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/!=(_:_:)":{"type":"topic","url":"\/documentation\/ovkit\/networkconnection\/!=(_:_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/networkconnection","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnection"}],"kind":"symbol","title":"NetworkConnection","navigatorTitle":[{"text":"NetworkConnection","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","value":"OVKNetworkConnection","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle","value":[{"text":"OVKNetworkConnection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}