{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/init(rawValue:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:5OVKit17NetworkConnectionO8rawValueACSgSi_tcfc","modules":[{"name":"OVKit"}],"title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnection\/init(rawvalue:)"]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/networkconnection","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnection"}],"kind":"symbol","title":"NetworkConnection","navigatorTitle":[{"text":"NetworkConnection","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/ovkit\/networkconnection\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","op":"replace","value":"OVKNetworkConnection"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","value":[{"text":"OVKNetworkConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}