{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/none","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}],"symbolKind":"case","title":"NetworkConnection.none","externalID":"c:@M@OVKit@E@OVKNetworkConnection@OVKNetworkConnectionNone","roleHeading":"Case","modules":[{"name":"OVKit"}],"role":"symbol"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/networkconnection\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/networkconnection\/none"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"url":"\/documentation\/ovkit\/networkconnection\/none","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/none","type":"topic","role":"symbol","kind":"symbol","title":"NetworkConnection.none","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","kind":"symbol","abstract":[],"type":"topic","title":"NetworkConnection","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnection","kind":"identifier"}],"url":"\/documentation\/ovkit\/networkconnection","navigatorTitle":[{"text":"NetworkConnection","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKNetworkConnectionNone","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKNetworkConnectionNone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1none\/title","op":"replace","value":"OVKNetworkConnectionNone"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnectionNone"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","op":"replace","value":"OVKNetworkConnection"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKNetworkConnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}