{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection"]]},"variants":[{"paths":["\/documentation\/ovkit\/networkconnection\/wifi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/networkconnection\/wifi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/wifi","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifi","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKNetworkConnectionWifi"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"wifi","kind":"identifier"}],"title":"NetworkConnection.wifi","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKNetworkConnection@OVKNetworkConnectionWifi"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection/wifi":{"role":"symbol","navigatorTitle":[{"text":"OVKNetworkConnectionWifi","kind":"identifier"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"wifi","kind":"identifier"}],"title":"NetworkConnection.wifi","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection\/wifi","type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/networkconnection\/wifi"},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnection":{"role":"symbol","abstract":[],"title":"NetworkConnection","url":"\/documentation\/ovkit\/networkconnection","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnection","navigatorTitle":[{"text":"NetworkConnection","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnection","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"OVKNetworkConnectionWifi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKNetworkConnectionWifi"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"OVKNetworkConnectionWifi","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"OVKNetworkConnectionWifi","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1wifi\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection~1wifi\/fragments","op":"replace","value":[{"text":"OVKNetworkConnectionWifi","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/title","value":"OVKNetworkConnection"},{"value":[{"text":"OVKNetworkConnection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}