{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parallelPrefetchBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 1600000, "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 1)"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:"}],"modules":[{"name":"OVKit"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parallelPrefetchBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig(im)initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:"},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/prefetcherconfig\/init(parallelprefetchbandwidththreshold:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/prefetcherconfig\/init(parallelprefetchbandwidththreshold:maxconcurrentdownloadscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"title":"PrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"url":"\/documentation\/ovkit\/prefetcherconfig","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrefetcherConfig"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)":{"type":"topic","role":"symbol","title":"init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:","kind":"identifier"}],"url":"\/documentation\/ovkit\/prefetcherconfig\/init(parallelprefetchbandwidththreshold:maxconcurrentdownloadscount:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParallelPrefetchBandwidthThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"parallelPrefetchBandwidthThreshold"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","op":"replace","value":"OVKPrefetcherConfig"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"},{"value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/navigatorTitle"},{"value":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1init(parallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParallelPrefetchBandwidthThreshold:maxConcurrentDownloadsCount:"}]}]}]}