{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/prefetcherconfig\/maxconcurrentdownloadscount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/prefetcherconfig\/maxconcurrentdownloadscount"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию имеет значение "},{"type":"codeVoice","code":"1"},{"type":"text","text":", что означает загрузку видео по очереди по одному."}]},{"type":"aside","style":"warning","name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Значение не может быть меньше "},{"type":"codeVoice","code":"1"},{"type":"text","text":". При неверном переданном значении оно будет сброшено на значение по умолчанию."}],"type":"paragraph"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/maxConcurrentDownloadsCount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloadsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"maxConcurrentDownloadsCount","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig(py)maxConcurrentDownloadsCount"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/maxConcurrentDownloadsCount":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/maxConcurrentDownloadsCount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"maxConcurrentDownloadsCount","type":"topic","url":"\/documentation\/ovkit\/prefetcherconfig\/maxconcurrentdownloadscount","kind":"symbol","abstract":[{"type":"text","text":"Максимальное количество параллельно предзагружаемых видео."}],"role":"symbol","navigatorTitle":[{"text":"maxConcurrentDownloadsCount","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}],"url":"\/documentation\/ovkit\/prefetcherconfig","type":"topic","title":"PrefetcherConfig","kind":"symbol","abstract":[{"text":"Конфигурация с базовыми опциями работы префетчера.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrefetcherConfig"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"maxConcurrentDownloadsCount","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloadsCount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1maxConcurrentDownloadsCount\/title","op":"replace","value":"maxConcurrentDownloadsCount"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1maxConcurrentDownloadsCount\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxConcurrentDownloadsCount"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title","op":"replace","value":"OVKPrefetcherConfig"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}