{"metadata":{"title":"parallelPrefetchBandwidthThreshold","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"parallelPrefetchBandwidthThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPrefetcherConfig(py)parallelPrefetchBandwidthThreshold","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/parallelPrefetchBandwidthThreshold"},"abstract":[{"type":"text","text":"Нижняя граница пропускной способности сети для параллельной работы плеера и префетчера."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Единицы измерения – "},{"type":"codeVoice","code":"bps"},{"type":"text","text":", значение по умолчанию – "},{"type":"codeVoice","code":"1600000"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/prefetcherconfig\/parallelprefetchbandwidththreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/prefetcherconfig\/parallelprefetchbandwidththreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig/parallelPrefetchBandwidthThreshold":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig\/parallelPrefetchBandwidthThreshold","abstract":[{"text":"Нижняя граница пропускной способности сети для параллельной работы плеера и префетчера.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"title":"parallelPrefetchBandwidthThreshold","url":"\/documentation\/ovkit\/prefetcherconfig\/parallelprefetchbandwidththreshold","kind":"symbol","type":"topic","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PrefetcherConfig":{"url":"\/documentation\/ovkit\/prefetcherconfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PrefetcherConfig","title":"PrefetcherConfig","abstract":[{"type":"text","text":"Конфигурация с базовыми опциями работы префетчера."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrefetcherConfig","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PrefetcherConfig","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"parallelPrefetchBandwidthThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"parallelPrefetchBandwidthThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":" ","kind":"text"},{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"parallelPrefetchBandwidthThreshold","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1parallelPrefetchBandwidthThreshold\/title"},{"op":"replace","value":[{"text":"parallelPrefetchBandwidthThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig~1parallelPrefetchBandwidthThreshold\/fragments"},{"op":"replace","value":"OVKPrefetcherConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPrefetcherConfig"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/fragments"},{"op":"replace","value":[{"text":"OVKPrefetcherConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PrefetcherConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}