{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Конфигурация от старого префетчера.."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovklegacyprefetchstrategy\/config"]},{"paths":["\/documentation\/ovkit\/ovklegacyprefetchstrategy\/config"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLegacyPrefetchStrategy\/config","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKLegacyPrefetchStrategy(py)config","navigatorTitle":[{"text":"config","kind":"identifier"}],"modules":[{"name":"OVKit"}],"title":"config","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/LegacyPrefetchStrategy":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LegacyPrefetchStrategy"}],"abstract":[{"type":"text","text":"Стратегия, которая отвечает в зависимости от скорости сети. Повторяет поведение "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyPrefetchStrategy"}],"url":"\/documentation\/ovkit\/legacyprefetchstrategy","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LegacyPrefetchStrategy","type":"topic","title":"LegacyPrefetchStrategy"},"doc://onevideo.OVKit/documentation/OVKit/OVKLegacyPrefetchStrategy/config":{"abstract":[{"type":"text","text":"Конфигурация от старого префетчера.."}],"kind":"symbol","type":"topic","title":"config","role":"symbol","url":"\/documentation\/ovkit\/ovklegacyprefetchstrategy\/config","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig","text":"ListPrefetcherConfig","kind":"typeIdentifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKLegacyPrefetchStrategy\/config","navigatorTitle":[{"text":"config","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcherConfig":{"abstract":[{"type":"text","text":"Конфигурация с опциями работы префетчера списка."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","type":"topic","role":"symbol","title":"ListPrefetcherConfig","navigatorTitle":[{"kind":"identifier","text":"ListPrefetcherConfig"}],"kind":"symbol","url":"\/documentation\/ovkit\/listprefetcherconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ListPrefetcherConfig","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ListPrefetcher":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ListPrefetcher","kind":"identifier"}],"abstract":[{"type":"text","text":"Префетчер списка видеозаписей."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPrefetcher"}],"url":"\/documentation\/ovkit\/listprefetcher","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcher","title":"ListPrefetcher"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"config","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"config"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"OVKListPrefetcherConfig","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ListPrefetcherConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKListPrefetcherConfig"},{"kind":"text","text":" * "},{"text":"config","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"OVKLegacyPrefetchStrategy","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/title"},{"value":[{"kind":"identifier","text":"OVKLegacyPrefetchStrategy"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LegacyPrefetchStrategy\/fragments"},{"op":"replace","value":"config","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKLegacyPrefetchStrategy~1config\/title"},{"value":[{"kind":"identifier","text":"config"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKLegacyPrefetchStrategy~1config\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/title","value":"OVKListPrefetcherConfig"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcherConfig\/fragments","value":[{"kind":"identifier","text":"OVKListPrefetcherConfig"}]},{"value":"OVKListPrefetcher","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKListPrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ListPrefetcher\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}