{"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"role":"symbol","externalID":"s:5OVKit11ControlMaskC15chapterProviderAA07ChapterE0CSgvp","extendedModule":"OVKit","title":"chapterProvider","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier","text":"ChapterProvider"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlmask\/chapterprovider"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask\/chapterProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","kind":"typeIdentifier","text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"type":"topic","url":"\/documentation\/ovkit\/chapterprovider","title":"ChapterProvider","role":"symbol","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ControlMask":{"url":"\/documentation\/ovkit\/controlmask","role":"symbol","type":"topic","title":"ControlMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ControlMask"}],"abstract":[],"navigatorTitle":[{"text":"ControlMask","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlMask/chapterProvider":{"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlMask\/chapterProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chapterProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider"},{"kind":"text","text":"?"}],"url":"\/documentation\/ovkit\/controlmask\/chapterprovider","type":"topic","title":"chapterProvider","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"OVKChapterProvider","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"kind":"identifier","text":"OVKChapterProvider"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKChapterProvider"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}