{"variants":[{"paths":["\/documentation\/ovkit\/statshandlercontext\/collector"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/statshandlercontext\/collector"]}],"abstract":[{"text":"Сборщик событий текущей сессии проигрывания.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext\/collector"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsCollector","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":"? { get }","kind":"text"}]}]}],"metadata":{"title":"collector","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext(py)collector","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collector","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatsCollector","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"text":"collector","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext/collector":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext\/collector","kind":"symbol","navigatorTitle":[{"text":"collector","kind":"identifier"}],"title":"collector","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collector"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector","text":"StatsCollector","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/statshandlercontext\/collector","abstract":[{"type":"text","text":"Сборщик событий текущей сессии проигрывания."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"type":"topic","title":"StatsHandlerContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","url":"\/documentation\/ovkit\/statshandlercontext","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"StatsHandlerContext","kind":"identifier"}],"abstract":[{"text":"Набор свойств, к которому может обращаться ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatsHandlerContext","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"url":"\/documentation\/ovkit\/statshandler","type":"topic","title":"StatsHandler","abstract":[{"text":"Протокол объекта, который может принимать события от ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"type":"text","text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatsHandler"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"type":"topic","title":"StatsCollector","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","role":"symbol","kind":"symbol","abstract":[{"text":"Собирает события для статистики и уведомляет всех ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"type":"text","text":", пример: collector передается при транзишенах между playerView вместе с объектом "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"или переходах в PiP и fullscreen.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"navigatorTitle":[{"text":"StatsCollector","kind":"identifier"}],"url":"\/documentation\/ovkit\/statscollector"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"title":"PlayerView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/playerview","role":"symbol","navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"url":"\/documentation\/ovkit\/video","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Video","kind":"identifier"}],"role":"symbol","title":"Video","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"collector","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"collector"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKStatsCollector","text":"id<OVKStatsCollector>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collector"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext~1collector\/title","op":"replace","value":"collector"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext~1collector\/fragments","value":[{"kind":"identifier","text":"collector"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title","value":"OVKStatsHandlerContext","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments","value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace","value":[{"text":"OVKStatsHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title","value":"OVKStatsCollector"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments","value":[{"text":"OVKStatsCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsCollector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title","value":"OVKVideo","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/navigatorTitle"}]}]}