{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"title":"context","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKStatsHandlerContext(py)context","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"}],"navigatorTitle":[{"kind":"identifier","text":"context"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/statshandlercontext\/context"]},{"paths":["\/documentation\/ovkit\/statshandlercontext\/context"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext\/context","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Контекст текущей сессии проигрывания."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext/context":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext\/context","title":"context","url":"\/documentation\/ovkit\/statshandlercontext\/context","abstract":[{"type":"text","text":"Контекст текущей сессии проигрывания."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext"}],"navigatorTitle":[{"kind":"identifier","text":"context"}],"type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatsHandler"}],"kind":"symbol","title":"StatsHandler","url":"\/documentation\/ovkit\/statshandler","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"События логирования будут вызваны на специальной background очереди.","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsHandler"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsContext":{"role":"symbol","url":"\/documentation\/ovkit\/statscontext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","abstract":[{"type":"text","text":"Дополнительная информация о том, какое видео воспроизводится и в каких условиях"}],"navigatorTitle":[{"text":"StatsContext","kind":"identifier"}],"type":"topic","kind":"symbol","title":"StatsContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsContext","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/StatsHandlerContext":{"url":"\/documentation\/ovkit\/statshandlercontext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatsHandlerContext","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandlerContext","kind":"symbol","abstract":[{"text":"Набор свойств, к которому может обращаться ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true},{"type":"text","text":"."}],"title":"StatsHandlerContext","navigatorTitle":[{"text":"StatsHandlerContext","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"context","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"context","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"OVKStatsContext","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKStatsContext","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsContext","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"context","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext~1context\/title","value":"context","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext~1context\/fragments","value":[{"kind":"identifier","text":"context"}],"op":"replace"},{"value":"OVKStatsHandler","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","value":[{"text":"OVKStatsHandler","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/navigatorTitle","op":"replace"},{"value":"OVKStatsContext","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/title","op":"replace"},{"value":[{"text":"OVKStatsContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsContext\/navigatorTitle","op":"replace","value":[{"text":"OVKStatsContext","kind":"identifier"}]},{"value":"OVKStatsHandlerContext","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/title"},{"op":"replace","value":[{"text":"OVKStatsHandlerContext","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandlerContext\/navigatorTitle","value":[{"kind":"identifier","text":"OVKStatsHandlerContext"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}