{"kind":"symbol","abstract":[{"type":"text","text":"Добавление наблюдателя за изменением статуса списка загруженных видео."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/addlistener(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/addlistener(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addListener"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PersistenceManagerListener","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/addListener(_:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addListener"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PersistenceManagerListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addListener:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)addListener:","title":"addListener(_:)","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","title":"PersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/addListener(_:)":{"abstract":[{"type":"text","text":"Добавление наблюдателя за изменением статуса списка загруженных видео."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addListener","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener","kind":"typeIdentifier","text":"PersistenceManagerListener"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/addListener(_:)","url":"\/documentation\/ovkit\/persistencemanager\/addlistener(_:)","title":"addListener(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addListener:"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener":{"url":"\/documentation\/ovkit\/persistencemanagerlistener","title":"PersistenceManagerListener","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerListener"}],"abstract":[{"type":"text","text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео."}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerListener"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addListener:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addListener:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addListener:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<OVKPersistenceManagerListener>","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace"},{"value":"addListener:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1addListener(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addListener:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1addListener(_:)\/fragments"},{"value":"OVKPersistenceManagerListener","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/title"},{"value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/fragments"},{"value":[{"text":"OVKPersistenceManagerListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}