{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"abstract":[{"text":"Подсчет места на диске, которое занимают загруженные видео. Результат указан в байтах.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateLibraryDiskSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"В общем размере учитываются загруженные видео ","type":"text"},{"inlineContent":[{"type":"text","text":"всех"}],"type":"emphasis"},{"text":" пользователей.","type":"text"}]}],"name":"Note","style":"note"}]}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/calculatelibrarydisksize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/calculatelibrarydisksize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateLibraryDiskSize(_:)"},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)calculateLibraryDiskSize:","modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"calculateLibraryDiskSize(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateLibraryDiskSize","kind":"identifier"},{"text":"((","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"calculateLibraryDiskSize:","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/calculateLibraryDiskSize(_:)":{"role":"symbol","title":"calculateLibraryDiskSize(_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateLibraryDiskSize(_:)","url":"\/documentation\/ovkit\/persistencemanager\/calculatelibrarydisksize(_:)","abstract":[{"type":"text","text":"Подсчет места на диске, которое занимают загруженные видео. Результат указан в байтах."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateLibraryDiskSize","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"calculateLibraryDiskSize:","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"title":"PersistenceManager","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"calculateLibraryDiskSize:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateLibraryDiskSize:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calculateLibraryDiskSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"int64_t","preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"calculateLibraryDiskSize:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateLibraryDiskSize(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateLibraryDiskSize:"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateLibraryDiskSize(_:)\/fragments"},{"value":"OVKPersistenceManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"}]}]}