{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Подсчет свободного места на диске, доступного для загрузки видео. Результат указан в байтах."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/calculateavailablediskspace(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/calculateavailablediskspace(_:)"]}],"metadata":{"modules":[{"name":"OVKit"}],"role":"symbol","roleHeading":"Instance Method","title":"calculateAvailableDiskSpace(_:)","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)calculateAvailableDiskSpace:","navigatorTitle":[{"kind":"identifier","text":"calculateAvailableDiskSpace:"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateAvailableDiskSpace"},{"kind":"text","text":"(("},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateAvailableDiskSpace(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateAvailableDiskSpace","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/calculateAvailableDiskSpace(_:)":{"abstract":[{"text":"Подсчет свободного места на диске, доступного для загрузки видео. Результат указан в байтах.","type":"text"}],"title":"calculateAvailableDiskSpace(_:)","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/calculateavailablediskspace(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"calculateAvailableDiskSpace:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateAvailableDiskSpace"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/calculateAvailableDiskSpace(_:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"title":"PersistenceManager","kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"calculateAvailableDiskSpace:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateAvailableDiskSpace:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calculateAvailableDiskSpace:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateAvailableDiskSpace(_:)\/title","value":"calculateAvailableDiskSpace:","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1calculateAvailableDiskSpace(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateAvailableDiskSpace:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"}]}]}