{"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Загрузка видео с заданным качеством."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"downloadVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"video"},{"text":": ","kind":"text"},{"text":"VideoType","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"},{"kind":"text","text":", "},{"text":"inQuality","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"qualityValue","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useHLS"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlySound"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userData"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"?, ","kind":"text"},{"text":"estimatedSizeOnDisk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":" = 0)"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Если видео содержит не одну аудиодорожку, будут загружены все."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/downloadvideo(_:inquality:usehls:onlysound:userdata:estimatedsizeondisk:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/downloadvideo(_:inquality:usehls:onlysound:userdata:estimatedsizeondisk:)"]}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"downloadVideo","kind":"identifier"},{"kind":"text","text":"("},{"text":"VideoType","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType"},{"text":", ","kind":"text"},{"text":"inQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"useHLS","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlySound"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"userData","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"estimatedSizeOnDisk"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","roleHeading":"Instance Method","symbolKind":"method","title":"downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"title":"PersistenceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)":{"url":"\/documentation\/ovkit\/persistencemanager\/downloadvideo(_:inquality:usehls:onlysound:userdata:estimatedsizeondisk:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadVideo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"kind":"text","text":", "},{"text":"inQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useHLS"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlySound"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"userData","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"estimatedSizeOnDisk","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","abstract":[{"text":"Загрузка видео с заданным качеством.","type":"text"}],"title":"downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/VideoType":{"role":"symbol","navigatorTitle":[{"text":"VideoType","kind":"identifier"}],"url":"\/documentation\/ovkit\/videotype","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoType","kind":"identifier"}],"abstract":[],"title":"VideoType","kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"downloadVideo:"},{"text":"(","kind":"text"},{"text":"id<OVKVideoType>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKVideoType"},{"kind":"text","text":") "},{"text":"video","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"qualityValue","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useHLS:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useHLS","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlySound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"onlySound","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userData:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"userData","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimatedSizeOnDisk:"},{"kind":"text","text":"("},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"estimatedSizeOnDisk"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)\/title","value":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1downloadVideo(_:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"downloadVideo:inQuality:useHLS:onlySound:userData:estimatedSizeOnDisk:"}],"op":"replace"},{"value":"OVKVideoType","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/fragments","value":[{"text":"OVKVideoType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoType"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}