{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/enableBackgroundNetworkServiceType()"},"metadata":{"platforms":[],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(cm)enableBackgroundNetworkServiceType","role":"symbol","title":"enableBackgroundNetworkServiceType()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"enableBackgroundNetworkServiceType","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/enablebackgroundnetworkservicetype()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/enablebackgroundnetworkservicetype()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"title":"PersistenceManager","type":"topic","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/enableBackgroundNetworkServiceType()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"},{"text":"()","kind":"text"}],"title":"enableBackgroundNetworkServiceType()","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"enableBackgroundNetworkServiceType","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanager\/enablebackgroundnetworkservicetype()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/enableBackgroundNetworkServiceType()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"enableBackgroundNetworkServiceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enableBackgroundNetworkServiceType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1enableBackgroundNetworkServiceType()\/title","op":"replace","value":"enableBackgroundNetworkServiceType"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1enableBackgroundNetworkServiceType()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"enableBackgroundNetworkServiceType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}