{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/getitemswithstates()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/getitemswithstates()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"metadata":{"symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)getItemsWithStates","navigatorTitle":[{"kind":"identifier","text":"getItemsWithStates"}],"role":"symbol","title":"getItemsWithStates()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getItemsWithStates","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":" : ","kind":"text"},{"text":"PersistentItemState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"},{"text":"]","kind":"text"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"PersistentItem"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","text":"PersistentItemState"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"style":"warning","type":"aside","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Доступ к этому методу может занять продолжительное время!"}]}]}],"kind":"content"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"title":"PersistenceManager","type":"topic","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/getItemsWithStates()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates()","abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"navigatorTitle":[{"kind":"identifier","text":"getItemsWithStates"}],"kind":"symbol","title":"getItemsWithStates()","type":"topic","url":"\/documentation\/ovkit\/persistencemanager\/getitemswithstates()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"role":"symbol","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"title":"PersistentItem","navigatorTitle":[{"kind":"identifier","text":"PersistentItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","url":"\/documentation\/ovkit\/persistentitem"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItemState","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","url":"\/documentation\/ovkit\/persistentitemstate","abstract":[{"text":"Состояние ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","type":"reference"},{"text":" применительно к оффлайн проигрыванию.","type":"text"}],"title":"PersistentItemState","navigatorTitle":[{"text":"PersistentItemState","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"getItemsWithStates","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getItemsWithStates","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSDictionary<OVKPersistentItem *,OVKPersistentItemState *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"getItemsWithStates","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates()\/title","value":"getItemsWithStates","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getItemsWithStates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","value":"OVKPersistentItem","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","value":[{"kind":"identifier","text":"OVKPersistentItemState"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle","value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}