{"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/getitemswithstates(filteredwithblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/getitemswithstates(filteredwithblock:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates(filteredWithBlock:)"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"("},{"text":"filteredWithBlock","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")?) -> [","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":" : "},{"text":"PersistentItemState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"},{"text":"]","kind":"text"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)getItemsWithStatesWithFilteredWithBlock:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getItemsWithStatesWithFilteredWithBlock:"}],"title":"getItemsWithStates(filteredWithBlock:)"},"abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getItemsWithStates","kind":"identifier"},{"kind":"text","text":"("},{"text":"filteredWithBlock","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"filter"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","text":"PersistentItemState"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItemState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Опциональный блок для фильтрации моделей по их состоянию.","type":"text"}]}],"name":"filter"}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Доступ к этому методу может занять продолжительное время!"}],"type":"paragraph"}],"type":"aside","style":"warning","name":"Warning"}],"kind":"content"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","url":"\/documentation\/ovkit\/persistentitem","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"title":"PersistentItem","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/getItemsWithStates(filteredWithBlock:)":{"abstract":[{"type":"text","text":"Возвращает список моделей с соответствующими им состояниями на момент вызова."}],"title":"getItemsWithStates(filteredWithBlock:)","url":"\/documentation\/ovkit\/persistencemanager\/getitemswithstates(filteredwithblock:)","navigatorTitle":[{"text":"getItemsWithStatesWithFilteredWithBlock:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getItemsWithStates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filteredWithBlock"},{"text":": ((","kind":"text"},{"text":"PersistentItemState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")?) -> [","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/getItemsWithStates(filteredWithBlock:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"navigatorTitle":[{"kind":"identifier","text":"PersistentItemState"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","url":"\/documentation\/ovkit\/persistentitemstate","abstract":[{"type":"text","text":"Состояние "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","isActive":true},{"type":"text","text":" применительно к оффлайн проигрыванию."}],"title":"PersistentItemState","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentItemState"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getItemsWithStatesWithFilteredWithBlock:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getItemsWithStatesWithFilteredWithBlock:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<OVKPersistentItem *,OVKPersistentItemState *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getItemsWithStatesWithFilteredWithBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","text":"OVKPersistentItemState"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"filter"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Опциональный блок для фильтрации моделей по их состоянию.","type":"text"}]}],"name":"filter"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"value":"getItemsWithStatesWithFilteredWithBlock:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates(filteredWithBlock:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1getItemsWithStates(filteredWithBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getItemsWithStatesWithFilteredWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","value":"OVKPersistentItemState"},{"value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments"},{"value":[{"text":"OVKPersistentItemState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}