{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/handlebackgroundsession(identifier:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/handlebackgroundsession(identifier:completionhandler:)"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"handleBackgroundSessionWithIdentifier:completionHandler:","kind":"identifier"}],"platforms":[],"modules":[{"name":"OVKit"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleBackgroundSession","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Type Method","title":"handleBackgroundSession(identifier:completionHandler:)","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(cm)handleBackgroundSessionWithIdentifier:completionHandler:","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/handleBackgroundSession(identifier:completionHandler:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"abstract":[{"text":"Поддержка событий background сессии для HLS видео.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBackgroundSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"kind":"symbol","title":"PersistenceManager","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/handleBackgroundSession(identifier:completionHandler:)":{"abstract":[{"text":"Поддержка событий background сессии для HLS видео.","type":"text"}],"type":"topic","title":"handleBackgroundSession(identifier:completionHandler:)","url":"\/documentation\/ovkit\/persistencemanager\/handlebackgroundsession(identifier:completionhandler:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleBackgroundSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"handleBackgroundSessionWithIdentifier:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/handleBackgroundSession(identifier:completionHandler:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"handleBackgroundSessionWithIdentifier:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"handleBackgroundSessionWithIdentifier:completionHandler:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"handleBackgroundSessionWithIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^)()) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1handleBackgroundSession(identifier:completionHandler:)\/title","value":"handleBackgroundSessionWithIdentifier:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1handleBackgroundSession(identifier:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleBackgroundSessionWithIdentifier:completionHandler:"}]}]}]}