{"metadata":{"role":"symbol","title":"imageData(of:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageData"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistentItemPreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)imageDataOf:","navigatorTitle":[{"text":"imageDataOf:","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/imageData(of:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageData"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"kind":"text","text":" "},{"text":"preview","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"PersistentItemPreview","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/imagedata(of:)"]},{"paths":["\/documentation\/ovkit\/persistencemanager\/imagedata(of:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Получение изображения для переданного варианта превью."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/imageData(of:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageDataOf:"}],"abstract":[{"type":"text","text":"Получение изображения для переданного варианта превью."}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/imageData(of:)","kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/imagedata(of:)","title":"imageData(of:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageData"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"PersistentItemPreview","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","role":"symbol","title":"PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistenceManager","kind":"identifier"}],"navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemPreview":{"type":"topic","role":"symbol","title":"PersistentItemPreview","abstract":[{"text":"Модель, содержащая данные варианта превью для заданного размера.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistentItemPreview"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview","navigatorTitle":[{"kind":"identifier","text":"PersistentItemPreview"}],"kind":"symbol","url":"\/documentation\/ovkit\/persistentitempreview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"imageDataOf:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageDataOf:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageDataOf:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemPreview","text":"OVKPersistentItemPreview","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemPreview"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"preview"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1imageData(of:)\/title","op":"replace","value":"imageDataOf:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1imageData(of:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageDataOf:","kind":"identifier"}]},{"value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/title","value":"OVKPersistentItemPreview"},{"op":"replace","value":[{"text":"OVKPersistentItemPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/fragments"},{"op":"replace","value":[{"text":"OVKPersistentItemPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemPreview\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}