{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PersistenceManagerConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"},{"text":", ","kind":"text"},{"text":"listenerQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Конфигурация менеджера."}]}],"name":"config"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Очередь, на которую от менеджера будут поступать события."}]}],"name":"listenerQueue"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/init(with:listenerQueue:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWith:listenerQueue:"}],"role":"symbol","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)initWith:listenerQueue:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistenceManagerConfig","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"listenerQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(with:listenerQueue:)"},"abstract":[{"text":"Создание менеджера.","type":"text"}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/init(with:listenerqueue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/init(with:listenerqueue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PersistenceManagerConfig","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerConfig"}],"url":"\/documentation\/ovkit\/persistencemanagerconfig","abstract":[{"type":"text","text":"Конфигурация менеджера оффлайн-хранилища."}],"title":"PersistenceManagerConfig","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"type":"topic","title":"PersistenceManager","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/init(with:listenerQueue:)":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/init(with:listenerQueue:)","kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/init(with:listenerqueue:)","abstract":[{"type":"text","text":"Создание менеджера."}],"navigatorTitle":[{"kind":"identifier","text":"initWith:listenerQueue:"}],"title":"init(with:listenerQueue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig","text":"PersistenceManagerConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"listenerQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWith:listenerQueue:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWith:listenerQueue:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWith:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerConfig","text":"OVKPersistenceManagerConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistenceManagerConfig"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"listenerQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":") ","kind":"text"},{"text":"listenerQueue","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Конфигурация менеджера."}]}],"name":"config"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Очередь, на которую от менеджера будут поступать события."}]}],"name":"listenerQueue"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"OVKPersistenceManagerConfig","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/title","op":"replace"},{"value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/fragments","op":"replace"},{"value":[{"text":"OVKPersistenceManagerConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerConfig\/navigatorTitle","op":"replace"},{"value":"OVKPersistenceManager","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace"},{"value":"initWith:listenerQueue:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1init(with:listenerQueue:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWith:listenerQueue:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1init(with:listenerQueue:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}