{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"aside","name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Доступ к этому свойству может занять продолжительное время!"}],"type":"paragraph"}],"style":"warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/items"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/items"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"items","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"items","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(py)items","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":"]","kind":"text"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/items","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Список моделей, которые в настоящее время загружаются, либо уже загружены."}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"type":"topic","title":"PersistentItem","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistentitem"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"url":"\/documentation\/ovkit\/persistencemanager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/items":{"navigatorTitle":[{"text":"items","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanager\/items","title":"items","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/items","role":"symbol","abstract":[{"type":"text","text":"Список моделей, которые в настоящее время загружаются, либо уже загружены."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"items","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"items","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<OVKPersistentItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"items"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPersistentItem","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle"},{"value":"OVKPersistenceManager","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"value":"items","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1items\/title"},{"value":[{"text":"items","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1items\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}