{"abstract":[{"text":"Удаление наблюдателя за изменением статуса списка загруженных видео.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/removeListener(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/removelistener(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/removelistener(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PersistenceManagerListener","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)removeListener:","navigatorTitle":[{"kind":"identifier","text":"removeListener:"}],"title":"removeListener(_:)","symbolKind":"method","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistenceManagerListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/removeListener(_:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/removeListener(_:)","title":"removeListener(_:)","url":"\/documentation\/ovkit\/persistencemanager\/removelistener(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistenceManagerListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPersistenceManagerListener"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"removeListener:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Удаление наблюдателя за изменением статуса списка загруженных видео.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerListener":{"url":"\/documentation\/ovkit\/persistencemanagerlistener","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerListener","title":"PersistenceManagerListener","abstract":[{"text":"Протокол наблюдателя за событиями изменения списка загруженных видео, а также статуса загрузки отдельных видео.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerListener","kind":"identifier"}],"navigatorTitle":[{"text":"PersistenceManagerListener","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManager","kind":"identifier"}],"title":"PersistenceManager","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","kind":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"removeListener:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"removeListener:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPersistenceManagerListener","text":"id<OVKPersistenceManagerListener>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"removeListener:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1removeListener(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeListener:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1removeListener(_:)\/fragments"},{"value":"OVKPersistenceManagerListener","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/title"},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerListener"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerListener"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerListener\/navigatorTitle"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]}]}]}