{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/resumeDownload(_:)"},"metadata":{"symbolKind":"method","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)resumeDownload:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeDownload"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"resumeDownload:"}],"title":"resumeDownload(_:)","role":"symbol","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Возобновляет загрузку модели."}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/resumedownload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/resumedownload(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resumeDownload","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"item","content":[{"inlineContent":[{"text":"Ресурс, загрузку которого следует возобновить.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Перед вызовом рекомендуется проверить, что нет причин для приостановки загрузки у "},{"type":"codeVoice","code":"DownloadStrategy\/suspendReason"},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"title":"PersistenceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/resumeDownload(_:)":{"url":"\/documentation\/ovkit\/persistencemanager\/resumedownload(_:)","abstract":[{"text":"Возобновляет загрузку модели.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeDownload"},{"kind":"text","text":"("},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resumeDownload:"}],"title":"resumeDownload(_:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/resumeDownload(_:)","kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resumeDownload:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resumeDownload:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"resumeDownload:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKPersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Ресурс, загрузку которого следует возобновить.","type":"text"}]}],"name":"item"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle"},{"op":"replace","value":"resumeDownload:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1resumeDownload(_:)\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1resumeDownload(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"resumeDownload:","kind":"identifier"}],"op":"replace"},{"value":"OVKPersistentItem","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","op":"replace"},{"op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistentItem"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}