{"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/retrydownload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/retrydownload(_:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/retryDownload(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retryDownload","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retryDownload","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"retryDownload:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"retryDownload(_:)","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)retryDownload:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Повтор загрузки модели.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/retryDownload(_:)":{"url":"\/documentation\/ovkit\/persistencemanager\/retrydownload(_:)","title":"retryDownload(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retryDownload","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/retryDownload(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"retryDownload:"}],"kind":"symbol","abstract":[{"type":"text","text":"Повтор загрузки модели."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"title":"PersistenceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PersistenceManager","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PersistenceManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"kind":"symbol","url":"\/documentation\/ovkit\/persistencemanager"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"url":"\/documentation\/ovkit\/persistentitem","title":"PersistentItem","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}],"navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"retryDownload:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"retryDownload:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"retryDownload:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"OVKPersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"kind":"text","text":" *) "},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"retryDownload:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1retryDownload(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1retryDownload(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retryDownload:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"value":[{"text":"OVKPersistenceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","op":"replace","value":"OVKPersistentItem"},{"op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments"},{"value":[{"text":"OVKPersistentItem","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}