{"sections":[],"abstract":[{"type":"text","text":"Получение статуса загрузки модели "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","text":"PersistentItemState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Доступ к этому свойству может занять продолжительное время!","type":"text"}]}],"name":"Warning"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/state(of:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/state(of:)"]}],"metadata":{"title":"state(of:)","role":"symbol","navigatorTitle":[{"text":"stateOf:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)stateOf:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PersistentItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem"},{"text":") -> ","kind":"text"},{"text":"PersistentItemState","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/state(of:)","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/state(of:)":{"abstract":[{"type":"text","text":"Получение статуса загрузки модели "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","isActive":true},{"type":"text","text":"."}],"title":"state(of:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"stateOf:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","text":"PersistentItem","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","text":"PersistentItemState","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/persistencemanager\/state(of:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/state(of:)"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"url":"\/documentation\/ovkit\/persistentitem","abstract":[{"type":"text","text":"Сериализуемая модель загруженного видео для оффлайн просмотра."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItem","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","title":"PersistentItem","role":"symbol","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"url":"\/documentation\/ovkit\/persistencemanager","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistentItemState":{"url":"\/documentation\/ovkit\/persistentitemstate","abstract":[{"type":"text","text":"Состояние "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","isActive":true,"type":"reference"},{"type":"text","text":" применительно к оффлайн проигрыванию."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistentItemState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","title":"PersistentItemState","role":"symbol","navigatorTitle":[{"text":"PersistentItemState","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"stateOf:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stateOf:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItemState","text":"OVKPersistentItemState","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItemState","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stateOf:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","text":"OVKPersistentItem","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1state(of:)\/title","op":"replace","value":"stateOf:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1state(of:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stateOf:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","op":"replace","value":"OVKPersistentItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","op":"replace","value":[{"text":"OVKPersistentItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/title","op":"replace","value":"OVKPersistentItemState"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/fragments","op":"replace","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItemState\/navigatorTitle","op":"replace","value":[{"text":"OVKPersistentItemState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}