{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAllowedNetworkType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"networkType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","kind":"typeIdentifier","text":"NetworkConnectionMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"networkType","content":[{"type":"paragraph","inlineContent":[{"text":"Маска разрешенных типов сети.","type":"text"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Обновление маски типов сети, при которых разрешается загрузка видео."}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/updateallowednetworktype(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/updateallowednetworktype(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"updateAllowedNetworkType(_:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAllowedNetworkType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"updateAllowedNetworkType:","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)updateAllowedNetworkType:"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/updateAllowedNetworkType(_:)":{"abstract":[{"type":"text","text":"Обновление маски типов сети, при которых разрешается загрузка видео."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAllowedNetworkType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask","text":"NetworkConnectionMask"},{"kind":"text","text":")"}],"title":"updateAllowedNetworkType(_:)","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateAllowedNetworkType(_:)","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager\/updateallowednetworktype(_:)","navigatorTitle":[{"kind":"identifier","text":"updateAllowedNetworkType:"}]},"doc://onevideo.OVKit/documentation/OVKit/NetworkConnectionMask":{"url":"\/documentation\/ovkit\/networkconnectionmask","title":"NetworkConnectionMask","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionMask"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionMask"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"title":"PersistenceManager","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistencemanager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateAllowedNetworkType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateAllowedNetworkType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateAllowedNetworkType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OVKNetworkConnectionMask","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/NetworkConnectionMask","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKNetworkConnectionMask"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"networkType"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"networkType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Маска разрешенных типов сети."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/title","value":"updateAllowedNetworkType:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateAllowedNetworkType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateAllowedNetworkType:"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/title","value":"OVKNetworkConnectionMask"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/fragments","value":[{"text":"OVKNetworkConnectionMask","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1NetworkConnectionMask\/navigatorTitle","value":[{"text":"OVKNetworkConnectionMask","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"text":"OVKPersistenceManager","kind":"identifier"}]}]}]}