{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateItems(_:block:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Обновляет userData для нескольких моделей сохранённых видео.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"items"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"items","content":[{"inlineContent":[{"type":"text","text":"Массив элементов для обновления."}],"type":"paragraph"}]},{"name":"block","content":[{"inlineContent":[{"type":"text","text":"Мутационный блок (например, можно менять "},{"type":"codeVoice","code":"userData"},{"type":"text","text":")."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanager\/updateitems(_:block:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanager\/updateitems(_:block:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItems"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"block"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"updateItems:block:"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)updateItems:block:","role":"symbol","title":"updateItems(_:block:)","modules":[{"name":"OVKit"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/updateItems(_:block:)":{"navigatorTitle":[{"kind":"identifier","text":"updateItems:block:"}],"title":"updateItems(_:block:)","kind":"symbol","role":"symbol","abstract":[{"text":"Обновляет userData для нескольких моделей сохранённых видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/updateItems(_:block:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateItems"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"block"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"PersistentItem"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/persistencemanager\/updateitems(_:block:)"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","url":"\/documentation\/ovkit\/persistencemanager","kind":"symbol","type":"topic","abstract":[{"text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра.","type":"text"}],"role":"symbol","title":"PersistenceManager"},"doc://onevideo.OVKit/documentation/OVKit/PersistentItem":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"PersistentItem","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistentitem","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem","abstract":[{"text":"Сериализуемая модель загруженного видео для оффлайн просмотра.","type":"text"}],"title":"PersistentItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistentItem"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"updateItems:block:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItems:block:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateItems:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<OVKPersistentItem *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"items"},{"kind":"text","text":" "},{"kind":"identifier","text":"block:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPersistentItem","kind":"typeIdentifier","text":"OVKPersistentItem","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentItem"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"items","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Массив элементов для обновления."}]}]},{"name":"block","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Мутационный блок (например, можно менять "},{"type":"codeVoice","code":"userData"},{"type":"text","text":")."}]}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateItems(_:block:)\/title","op":"replace","value":"updateItems:block:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1updateItems(_:block:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateItems:block:"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","op":"replace","value":"OVKPersistenceManager"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManager"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/title","op":"replace","value":"OVKPersistentItem"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistentItem"}]}]}]}