{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/validateAll()"},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPersistenceManager(im)validateAll","modules":[{"name":"OVKit"}],"title":"validateAll()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validateAll","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","platforms":[],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"validateAll","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Проверяет все ранее сохранённые модели видео.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateAll"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanager\/validateall()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanager\/validateall()"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager":{"url":"\/documentation\/ovkit\/persistencemanager","navigatorTitle":[{"kind":"identifier","text":"PersistenceManager"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManager"}],"abstract":[{"type":"text","text":"Класс, который используется при сохранении видео для дальнейшего оффлайн просмотра."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager","title":"PersistenceManager","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManager/validateAll()":{"url":"\/documentation\/ovkit\/persistencemanager\/validateall()","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManager\/validateAll()","navigatorTitle":[{"text":"validateAll","kind":"identifier"}],"abstract":[{"text":"Проверяет все ранее сохранённые модели видео.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validateAll","kind":"identifier"},{"text":"()","kind":"text"}],"title":"validateAll()","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"validateAll","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateAll"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateAll","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/title","value":"OVKPersistenceManager","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1validateAll()\/title","value":"validateAll","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManager~1validateAll()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateAll"}],"op":"replace"}]}]}