{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelinethumbnails\/counttotal"]},{"paths":["\/documentation\/ovkit\/timelinethumbnails\/counttotal"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"TimelineThumbnailsType.countTotal"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countTotal","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countTotal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"countTotal","symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails(py)countTotal","navigatorTitle":[{"kind":"identifier","text":"countTotal"}]},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineThumbnails","kind":"identifier"}],"navigatorTitle":[{"text":"TimelineThumbnails","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/timelinethumbnails","role":"symbol","title":"TimelineThumbnails"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/countTotal":{"navigatorTitle":[{"kind":"identifier","text":"countTotal"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/countTotal","title":"countTotal","url":"\/documentation\/ovkit\/timelinethumbnails\/counttotal","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"countTotal"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"countTotal","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"countTotal"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"countTotal","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKTimelineThumbnails","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title"},{"value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/navigatorTitle","value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countTotal\/title","value":"countTotal"},{"value":[{"text":"countTotal","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1countTotal\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}