{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails(py)frameSize","role":"symbol","title":"frameSize","navigatorTitle":[{"kind":"identifier","text":"frameSize"}]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/timelinethumbnails\/framesize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelinethumbnails\/framesize"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"TimelineThumbnailsType.frameSize","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/frameSize"},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TimelineThumbnails"}],"url":"\/documentation\/ovkit\/timelinethumbnails","kind":"symbol","role":"symbol","title":"TimelineThumbnails","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TimelineThumbnails","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/frameSize":{"kind":"symbol","navigatorTitle":[{"text":"frameSize","kind":"identifier"}],"type":"topic","abstract":[],"title":"frameSize","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/frameSize","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails\/framesize"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"frameSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"frameSize","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameSize"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"OVKTimelineThumbnails","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title"},{"value":[{"text":"OVKTimelineThumbnails","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1frameSize\/title","op":"replace","value":"frameSize"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1frameSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"frameSize"}]}]}]}