{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(from:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Decodable.init(from:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/ovkit\/timelinethumbnails\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","title":"init(from:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"s:5OVKit18TimelineThumbnailsC4fromACs7Decoder_p_tKcfc","roleHeading":"Initializer","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/init(from:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/timelinethumbnails\/init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/init(from:)","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"navigatorTitle":[{"text":"TimelineThumbnails","kind":"identifier"}],"url":"\/documentation\/ovkit\/timelinethumbnails","title":"TimelineThumbnails","abstract":[],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineThumbnails","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"OVKTimelineThumbnails","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/navigatorTitle"}]}]}