{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/urls"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:@M@OVKit@objc(cs)OVKTimelineThumbnails(py)urls","symbolKind":"property","title":"urls","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"urls","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/timelinethumbnails\/urls"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/timelinethumbnails\/urls"]}],"kind":"symbol","abstract":[{"text":"Набор URL на изображения атласов.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Каждое такое изображение может содержать сетку из фреймов более низкого разрешения.","type":"text"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails/urls":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails\/urls","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"urls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}],"title":"urls","url":"\/documentation\/ovkit\/timelinethumbnails\/urls","type":"topic","kind":"symbol","abstract":[{"text":"Набор URL на изображения атласов.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"urls","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/TimelineThumbnails":{"title":"TimelineThumbnails","navigatorTitle":[{"text":"TimelineThumbnails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimelineThumbnails","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/TimelineThumbnails","abstract":[],"url":"\/documentation\/ovkit\/timelinethumbnails","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"urls","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"urls","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSURL *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"urls","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1urls\/title"},{"op":"replace","value":[{"kind":"identifier","text":"urls"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails~1urls\/fragments"},{"value":"OVKTimelineThumbnails","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKTimelineThumbnails"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1TimelineThumbnails\/navigatorTitle"}]}]}