{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelectionOption\/isOriginal","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkmediaselectionoption\/isoriginal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkmediaselectionoption\/isoriginal"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption(py)isOriginal","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isOriginal"}],"title":"isOriginal","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isOriginal","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"abstract":[{"type":"text","text":"Указывает, что контент этой опции на языке оригинала."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOriginal"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Применимо только для аудио."}]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKMediaSelectionOption/isOriginal":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isOriginal"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/ovkmediaselectionoption\/isoriginal","abstract":[{"text":"Указывает, что контент этой опции на языке оригинала.","type":"text"}],"title":"isOriginal","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelectionOption\/isOriginal","navigatorTitle":[{"text":"isOriginal","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaSelectionOption","kind":"identifier"}],"navigatorTitle":[{"text":"MediaSelectionOption","kind":"identifier"}],"title":"MediaSelectionOption","abstract":[{"text":"Опция медиадорожки.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","url":"\/documentation\/ovkit\/mediaselectionoption","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isOriginal"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isOriginal","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"isOriginal","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isOriginal","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelectionOption~1isOriginal\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelectionOption~1isOriginal\/fragments","op":"replace","value":[{"kind":"identifier","text":"isOriginal"}]},{"value":"OVKMediaSelectionOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","op":"replace","value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}]}]}]}