{"metadata":{"roleHeading":"Instance Property","title":"name","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption(py)name","navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelectionOption\/name"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Название опции для отображения в UI."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkmediaselectionoption\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkmediaselectionoption\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKMediaSelectionOption/name":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"name","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKMediaSelectionOption\/name","url":"\/documentation\/ovkit\/ovkmediaselectionoption\/name","abstract":[{"type":"text","text":"Название опции для отображения в UI."}],"navigatorTitle":[{"kind":"identifier","text":"name"}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"kind":"symbol","abstract":[{"type":"text","text":"Опция медиадорожки."}],"role":"symbol","type":"topic","title":"MediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","url":"\/documentation\/ovkit\/mediaselectionoption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"navigatorTitle":[{"text":"MediaSelectionOption","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"name"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"name","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelectionOption~1name\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKMediaSelectionOption~1name\/fragments"},{"value":"OVKMediaSelectionOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}