{"metadata":{"title":"ActionKind.audioTrackSelection","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTrackSelection","kind":"identifier"}],"navigatorTitle":[{"text":"OVKMenuActionKindAudioTrackSelection","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindAudioTrackSelection","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/audioTrackSelection"},"abstract":[{"text":"Пункт меню, отвечающий за выбор аудиодорожки.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"audioTrackSelection","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/audiotrackselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/audiotrackselection"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind/audioTrackSelection":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/audioTrackSelection","abstract":[{"text":"Пункт меню, отвечающий за выбор аудиодорожки.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrackSelection"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindAudioTrackSelection"}],"title":"ActionKind.audioTrackSelection","url":"\/documentation\/ovkit\/actionkind\/audiotrackselection","type":"topic","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}],"navigatorTitle":[{"text":"ActionKind","kind":"identifier"}],"title":"ActionKind","role":"symbol","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"url":"\/documentation\/ovkit\/actionkind","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuActionKindAudioTrackSelection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKMenuActionKindAudioTrackSelection","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKMenuActionKindAudioTrackSelection"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKMenuActionKindAudioTrackSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1audioTrackSelection\/title"},{"value":[{"text":"OVKMenuActionKindAudioTrackSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1audioTrackSelection\/fragments"},{"value":"OVKMenuActionKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title"},{"value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle"}]}]}