{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Case","modules":[{"name":"OVKit"}],"symbolKind":"case","title":"ActionKind.cancel","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindCancel"}],"externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindCancel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"}]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/cancel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"abstract":[{"text":"Кнопка отмены.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/actionkind\/cancel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/actionkind\/cancel"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/cancel":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/cancel","abstract":[{"text":"Кнопка отмены.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/actionkind\/cancel","title":"ActionKind.cancel","kind":"symbol","navigatorTitle":[{"text":"OVKMenuActionKindCancel","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionKind"}],"abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/actionkind","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","role":"symbol","title":"ActionKind","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKMenuActionKindCancel","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKMenuActionKindCancel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKMenuActionKindCancel"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKMenuActionKindCancel","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1cancel\/title"},{"value":[{"kind":"identifier","text":"OVKMenuActionKindCancel"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1cancel\/fragments"},{"value":"OVKMenuActionKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title"},{"value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}