{"abstract":[{"text":"Показ меню для разработчиков.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/actionkind\/debugmenu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/actionkind\/debugmenu"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugMenu","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/debugMenu","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"metadata":{"title":"ActionKind.debugMenu","navigatorTitle":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindDebugMenu","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugMenu","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/debugMenu":{"kind":"symbol","title":"ActionKind.debugMenu","abstract":[{"type":"text","text":"Показ меню для разработчиков."}],"type":"topic","url":"\/documentation\/ovkit\/actionkind\/debugmenu","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugMenu","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/debugMenu","navigatorTitle":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","title":"ActionKind","url":"\/documentation\/ovkit\/actionkind","kind":"symbol","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKMenuActionKindDebugMenu","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMenuActionKindDebugMenu"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1debugMenu\/title","value":"OVKMenuActionKindDebugMenu","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1debugMenu\/fragments","value":[{"text":"OVKMenuActionKindDebugMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","value":"OVKMenuActionKind","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace"}]}]}