{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/diagnosticsView","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosticsView","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindDiagnosticsView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindDiagnosticsView"}],"title":"ActionKind.diagnosticsView"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Пункт меню, управляющий видимостью окна диагностической информации.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosticsView","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"variants":[{"paths":["\/documentation\/ovkit\/actionkind\/diagnosticsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/actionkind\/diagnosticsview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/diagnosticsView":{"url":"\/documentation\/ovkit\/actionkind\/diagnosticsview","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindDiagnosticsView"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/diagnosticsView","abstract":[{"type":"text","text":"Пункт меню, управляющий видимостью окна диагностической информации."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosticsView","kind":"identifier"}],"title":"ActionKind.diagnosticsView"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"title":"ActionKind","url":"\/documentation\/ovkit\/actionkind","navigatorTitle":[{"kind":"identifier","text":"ActionKind"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionKind"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKMenuActionKindDiagnosticsView","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKMenuActionKindDiagnosticsView"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"OVKMenuActionKindDiagnosticsView","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKMenuActionKindDiagnosticsView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1diagnosticsView\/title"},{"value":[{"text":"OVKMenuActionKindDiagnosticsView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1diagnosticsView\/fragments","op":"replace"},{"value":"OVKMenuActionKind","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","op":"replace"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","op":"replace"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}