{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Зарезервированный кейс для кастомных пунктов меню, не входящих в стандартный набор."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/other"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/other"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"title":"ActionKind.other","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindOther","role":"symbol","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKMenuActionKindOther","kind":"identifier"}],"symbolKind":"case"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/other","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/other":{"navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindOther"}],"title":"ActionKind.other","kind":"symbol","role":"symbol","abstract":[{"text":"Зарезервированный кейс для кастомных пунктов меню, не входящих в стандартный набор.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"url":"\/documentation\/ovkit\/actionkind\/other"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}],"url":"\/documentation\/ovkit\/actionkind","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"title":"ActionKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKMenuActionKindOther","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKMenuActionKindOther","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OVKMenuActionKindOther"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"OVKMenuActionKindOther","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1other\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1other\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuActionKindOther"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","op":"replace","value":"OVKMenuActionKind"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuActionKind"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","op":"replace","value":[{"text":"OVKMenuActionKind","kind":"identifier"}]}]}]}