{"metadata":{"roleHeading":"Case","title":"ActionKind.playbackRateSelection","symbolKind":"case","navigatorTitle":[{"text":"OVKMenuActionKindPlaybackRateSelection","kind":"identifier"}],"role":"symbol","externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindPlaybackRateSelection","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRateSelection"}]},"abstract":[{"text":"Пункт меню, отвечающий за изменение скорости воспроизведения.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/playbackRateSelection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/playbackrateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/playbackrateselection"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackRateSelection"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionKind"}],"type":"topic","url":"\/documentation\/ovkit\/actionkind","title":"ActionKind","kind":"symbol","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/playbackRateSelection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRateSelection"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindPlaybackRateSelection"}],"type":"topic","abstract":[{"type":"text","text":"Пункт меню, отвечающий за изменение скорости воспроизведения."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/playbackRateSelection","url":"\/documentation\/ovkit\/actionkind\/playbackrateselection","title":"ActionKind.playbackRateSelection"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","kind":"symbol","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"OVKMenuActionKindPlaybackRateSelection","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKMenuActionKindPlaybackRateSelection"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"OVKMenuActionKindPlaybackRateSelection","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"OVKMenuActionKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace"},{"op":"replace","value":"OVKMenuActionKindPlaybackRateSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1playbackRateSelection\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1playbackRateSelection\/fragments","value":[{"kind":"identifier","text":"OVKMenuActionKindPlaybackRateSelection"}],"op":"replace"}]}]}