{"abstract":[{"text":"Пункт меню, отвечающий за выбор качества (разрешения) видео.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/qualityoptionselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/qualityoptionselection"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityOptionSelection"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindQualityOptionSelection"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityOptionSelection","kind":"identifier"}],"title":"ActionKind.qualityOptionSelection","externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindQualityOptionSelection","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityOptionSelection","kind":"identifier"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind/qualityOptionSelection":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityOptionSelection"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityOptionSelection","abstract":[{"text":"Пункт меню, отвечающий за выбор качества (разрешения) видео.","type":"text"}],"title":"ActionKind.qualityOptionSelection","url":"\/documentation\/ovkit\/actionkind\/qualityoptionselection","navigatorTitle":[{"text":"OVKMenuActionKindQualityOptionSelection","kind":"identifier"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/actionkind","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionKind"}],"title":"ActionKind","abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKMenuActionKindQualityOptionSelection","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKMenuActionKindQualityOptionSelection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"OVKMenuActionKindQualityOptionSelection","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKMenuActionKindQualityOptionSelection","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityOptionSelection\/title"},{"value":[{"text":"OVKMenuActionKindQualityOptionSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityOptionSelection\/fragments"},{"value":"OVKMenuActionKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}