{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityPresetSelection"},"abstract":[{"type":"text","text":"Пункт меню, отвечающий за выбор предустановки качества (например, “Авто”, “Высокое”, “Экономия трафика”)."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityPresetSelection"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityPresetSelection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindQualityPresetSelection"}],"symbolKind":"case","externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindQualityPresetSelection","title":"ActionKind.qualityPresetSelection","roleHeading":"Case","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/qualitypresetselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/qualitypresetselection"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","title":"ActionKind","url":"\/documentation\/ovkit\/actionkind","kind":"symbol","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind/qualityPresetSelection":{"type":"topic","title":"ActionKind.qualityPresetSelection","abstract":[{"type":"text","text":"Пункт меню, отвечающий за выбор предустановки качества (например, “Авто”, “Высокое”, “Экономия трафика”)."}],"url":"\/documentation\/ovkit\/actionkind\/qualitypresetselection","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/qualityPresetSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityPresetSelection"}],"navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindQualityPresetSelection"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"OVKMenuActionKindQualityPresetSelection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKMenuActionKindQualityPresetSelection"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKMenuActionKindQualityPresetSelection"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","op":"replace","value":"OVKMenuActionKind"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","op":"replace","value":[{"text":"OVKMenuActionKind","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKMenuActionKind"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityPresetSelection\/title","op":"replace","value":"OVKMenuActionKindQualityPresetSelection"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1qualityPresetSelection\/fragments","op":"replace","value":[{"text":"OVKMenuActionKindQualityPresetSelection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}