{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/subtitles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/subtitles"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/subtitles"},"abstract":[{"type":"text","text":"Пункт меню, отвечающий за управление субтитрами."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"metadata":{"externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindSubtitles","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"OVKit"}],"title":"ActionKind.subtitles","navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindSubtitles"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind/subtitles":{"role":"symbol","abstract":[{"text":"Пункт меню, отвечающий за управление субтитрами.","type":"text"}],"navigatorTitle":[{"text":"OVKMenuActionKindSubtitles","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitles"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/subtitles","url":"\/documentation\/ovkit\/actionkind\/subtitles","kind":"symbol","title":"ActionKind.subtitles"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/actionkind","navigatorTitle":[{"text":"ActionKind","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionKind"}],"title":"ActionKind","abstract":[{"text":"Идентификатор пункта меню.","type":"text"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"OVKMenuActionKindSubtitles","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"OVKMenuActionKindSubtitles","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKMenuActionKindSubtitles"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKMenuActionKindSubtitles","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1subtitles\/title"},{"value":[{"text":"OVKMenuActionKindSubtitles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1subtitles\/fragments"},{"value":"OVKMenuActionKind","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments"},{"value":[{"text":"OVKMenuActionKind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle"}]}]}