{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OVKMenuActionKindTrafficSaving"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trafficSaving","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKMenuActionKind@OVKMenuActionKindTrafficSaving","title":"ActionKind.trafficSaving","role":"symbol","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/actionkind\/trafficsaving"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/actionkind\/trafficsaving"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind"]]},"abstract":[{"type":"text","text":"Пункт меню, отвечающий за режим экономии трафика."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trafficSaving","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/trafficSaving","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ActionKind/trafficSaving":{"navigatorTitle":[{"text":"OVKMenuActionKindTrafficSaving","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Пункт меню, отвечающий за режим экономии трафика."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trafficSaving","kind":"identifier"}],"title":"ActionKind.trafficSaving","role":"symbol","url":"\/documentation\/ovkit\/actionkind\/trafficsaving","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind\/trafficSaving"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"role":"symbol","url":"\/documentation\/ovkit\/actionkind","title":"ActionKind","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActionKind"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionKind"}],"abstract":[{"type":"text","text":"Идентификатор пункта меню."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKMenuActionKindTrafficSaving"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKMenuActionKindTrafficSaving","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKMenuActionKindTrafficSaving","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1trafficSaving\/title","value":"OVKMenuActionKindTrafficSaving"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind~1trafficSaving\/fragments","value":[{"text":"OVKMenuActionKindTrafficSaving","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","value":"OVKMenuActionKind"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","value":[{"text":"OVKMenuActionKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","value":[{"text":"OVKMenuActionKind","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}