{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyTimelineAndTime","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyTimelineAndTime","kind":"identifier"}],"externalID":"s:5OVKit18BottomControlsViewC14VisibilityModeO19onlyTimelineAndTimeyA2EmF","modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"case","title":"BottomControlsView.VisibilityMode.onlyTimelineAndTime","roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Виден только таймлайн, метки текущего времени и длительности."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode\/onlytimelineandtime"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode\/onlyTimelineAndTime","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","kind":"symbol","url":"\/documentation\/ovkit","role":"collection","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView":{"navigatorTitle":[{"kind":"identifier","text":"BottomControlsView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView","abstract":[{"type":"text","text":"Элемент контролов, который включает в себя таймлайн, индикацию текущего времени и набор кнопок для действий."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BottomControlsView"}],"kind":"symbol","role":"symbol","title":"BottomControlsView","url":"\/documentation\/ovkit\/bottomcontrolsview"},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/VisibilityMode/onlyTimelineAndTime":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyTimelineAndTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode\/onlytimelineandtime","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode\/onlyTimelineAndTime","title":"BottomControlsView.VisibilityMode.onlyTimelineAndTime","role":"symbol","abstract":[{"text":"Виден только таймлайн, метки текущего времени и длительности.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/BottomControlsView/VisibilityMode":{"title":"BottomControlsView.VisibilityMode","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BottomControlsView\/VisibilityMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisibilityMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Маска видимости внутренних контролов."}],"kind":"symbol","url":"\/documentation\/ovkit\/bottomcontrolsview\/visibilitymode","role":"symbol","navigatorTitle":[{"text":"VisibilityMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/title","value":"OVKBottomControlsView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/fragments","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BottomControlsView\/navigatorTitle","value":[{"text":"OVKBottomControlsView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}