{"variants":[{"paths":["\/documentation\/ovkit\/focusableview\/canbecomefocused"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/focusableview\/canbecomefocused"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFocused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"canBecomeFocused"}],"role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFocused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","symbolKind":"property","title":"canBecomeFocused","externalID":"c:@M@OVKit@objc(cs)FocusableView(py)canBecomeFocused"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView\/canBecomeFocused","interfaceLanguage":"swift"},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/FocusableView":{"kind":"symbol","title":"FocusableView","abstract":[{"type":"text","text":"Позволяет View использовать в движке фокуса"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView","navigatorTitle":[{"text":"FocusableView","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FocusableView","kind":"identifier"}],"url":"\/documentation\/ovkit\/focusableview","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/FocusableView/canBecomeFocused":{"type":"topic","url":"\/documentation\/ovkit\/focusableview\/canbecomefocused","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView\/canBecomeFocused","role":"symbol","title":"canBecomeFocused","navigatorTitle":[{"kind":"identifier","text":"canBecomeFocused"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFocused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","title":"OVKit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"canBecomeFocused","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"canBecomeFocused"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFocused"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FocusableView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FocusableView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/fragments"},{"op":"replace","value":[{"text":"FocusableView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/navigatorTitle"},{"op":"replace","value":"canBecomeFocused","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView~1canBecomeFocused\/title"},{"op":"replace","value":[{"kind":"identifier","text":"canBecomeFocused"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView~1canBecomeFocused\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}