{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","title":"initWithCoder:","roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)FocusableView(im)initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView\/initWithCoder:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/focusableview\/initwithcoder:"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/FocusableView/initWithCoder:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","title":"initWithCoder:","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView\/initWithCoder:","url":"\/documentation\/ovkit\/focusableview\/initwithcoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/FocusableView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FocusableView","kind":"identifier"}],"type":"topic","title":"FocusableView","kind":"symbol","role":"symbol","abstract":[{"text":"Позволяет View использовать в движке фокуса","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/FocusableView","url":"\/documentation\/ovkit\/focusableview","navigatorTitle":[{"text":"FocusableView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/title","value":"FocusableView"},{"value":[{"text":"FocusableView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1FocusableView\/navigatorTitle","value":[{"kind":"identifier","text":"FocusableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}