{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"]]},"sections":[],"abstract":[{"text":"Переопределение названия параметра в URL на HLS-манифест для максимально доступного качества.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customMaxQualityParameterName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoURLQuery\/customMaxQualityParameterName","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/ovkvideourlquery\/custommaxqualityparametername"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideourlquery\/custommaxqualityparametername"]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customMaxQualityParameterName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","title":"customMaxQualityParameterName","externalID":"c:@M@OVKit@objc(cs)OVKVideoURLQuery(py)customMaxQualityParameterName","navigatorTitle":[{"text":"customMaxQualityParameterName","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideoURLQuery/customMaxQualityParameterName":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoURLQuery\/customMaxQualityParameterName","abstract":[{"type":"text","text":"Переопределение названия параметра в URL на HLS-манифест для максимально доступного качества."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"customMaxQualityParameterName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/ovkit\/ovkvideourlquery\/custommaxqualityparametername","title":"customMaxQualityParameterName","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customMaxQualityParameterName"}]},"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"VideoURLQuery","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"url":"\/documentation\/ovkit\/videourlquery","role":"symbol","navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}],"title":"VideoURLQuery","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"customMaxQualityParameterName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"customMaxQualityParameterName"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"customMaxQualityParameterName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"customMaxQualityParameterName","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoURLQuery~1customMaxQualityParameterName\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoURLQuery~1customMaxQualityParameterName\/fragments","op":"replace","value":[{"text":"customMaxQualityParameterName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","value":"OVKVideoURLQuery"},{"value":[{"text":"OVKVideoURLQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}