{"abstract":[{"text":"Переопределение названия параметра в URL на HLS-манифест для минимально доступного качества.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/ovkvideourlquery\/customminqualityparametername"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkvideourlquery\/customminqualityparametername"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customMinQualityParameterName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoURLQuery\/customMinQualityParameterName","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKVideoURLQuery(py)customMinQualityParameterName","modules":[{"name":"OVKit"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customMinQualityParameterName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"customMinQualityParameterName","navigatorTitle":[{"text":"customMinQualityParameterName","kind":"identifier"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoURLQuery":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/videourlquery","abstract":[{"type":"text","text":"Набор дополнительных параметров в URL на видео ресурс."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"VideoURLQuery","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoURLQuery","title":"VideoURLQuery","navigatorTitle":[{"text":"VideoURLQuery","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoURLQuery/customMinQualityParameterName":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Переопределение названия параметра в URL на HLS-манифест для минимально доступного качества."}],"url":"\/documentation\/ovkit\/ovkvideourlquery\/customminqualityparametername","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customMinQualityParameterName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoURLQuery\/customMinQualityParameterName","title":"customMinQualityParameterName","navigatorTitle":[{"text":"customMinQualityParameterName","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"customMinQualityParameterName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"customMinQualityParameterName"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"customMinQualityParameterName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/title","op":"replace","value":"OVKVideoURLQuery"},{"value":[{"kind":"identifier","text":"OVKVideoURLQuery"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoURLQuery\/fragments","op":"replace"},{"value":"customMinQualityParameterName","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoURLQuery~1customMinQualityParameterName\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoURLQuery~1customMinQualityParameterName\/fragments","value":[{"kind":"identifier","text":"customMinQualityParameterName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}