{"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/activesubtitlesoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/activesubtitlesoption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeSubtitlesOption"},{"kind":"text","text":": "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/activeSubtitlesOption","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)activeSubtitlesOption","navigatorTitle":[{"kind":"identifier","text":"activeSubtitlesOption"}],"modules":[{"name":"OVKit"}],"role":"symbol","title":"activeSubtitlesOption","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeSubtitlesOption"},{"text":": ","kind":"text"},{"text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"text":"Текущая выбранная дорожка субтитров.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/activeSubtitlesOption":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activeSubtitlesOption"},{"text":": ","kind":"text"},{"text":"SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"activeSubtitlesOption","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Текущая выбранная дорожка субтитров."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/activeSubtitlesOption","title":"activeSubtitlesOption","url":"\/documentation\/ovkit\/ovkplayerview\/activesubtitlesoption","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SubtitlesOption"}],"navigatorTitle":[{"text":"SubtitlesOption","kind":"identifier"}],"type":"topic","abstract":[{"text":"Дорожка субтитров.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","title":"SubtitlesOption","url":"\/documentation\/ovkit\/subtitlesoption","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"activeSubtitlesOption","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"activeSubtitlesOption"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"OVKSubtitlesOption","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"activeSubtitlesOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"activeSubtitlesOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1activeSubtitlesOption\/title"},{"value":[{"text":"activeSubtitlesOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1activeSubtitlesOption\/fragments"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","value":"OVKSubtitlesOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","value":[{"kind":"identifier","text":"OVKSubtitlesOption"}],"op":"replace"}]}]}