{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"Category","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"audioSessionPreferredCategory","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)audioSessionPreferredCategory","role":"symbol","title":"audioSessionPreferredCategory"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/audiosessionpreferredcategory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/audiosessionpreferredcategory"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/audioSessionPreferredCategory","interfaceLanguage":"swift"},"abstract":[{"text":"Категория аудио сессии, необходимая данному ","type":"text"},{"code":"PlayerView","type":"codeVoice"},{"type":"text","text":" для работы."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"Если изменить в ходе воспроизведения, произойдет переконфигурация аудио сессии. По умолчанию значение ","type":"text"},{"type":"codeVoice","code":".playback"},{"type":"text","text":"."}],"type":"paragraph"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/audioSessionPreferredCategory":{"title":"audioSessionPreferredCategory","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/audioSessionPreferredCategory","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"}],"abstract":[{"text":"Категория аудио сессии, необходимая данному ","type":"text"},{"type":"codeVoice","code":"PlayerView"},{"text":" для работы.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"audioSessionPreferredCategory"}],"url":"\/documentation\/ovkit\/ovkplayerview\/audiosessionpreferredcategory","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"audioSessionPreferredCategory"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"audioSessionPreferredCategory"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"audioSessionPreferredCategory"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1audioSessionPreferredCategory\/title","op":"replace","value":"audioSessionPreferredCategory"},{"value":[{"text":"audioSessionPreferredCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1audioSessionPreferredCategory\/fragments","op":"replace"}]}]}