{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoQualityRange"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"По умолчанию значение "},{"code":"nil","type":"codeVoice"},{"type":"text","text":". Это значит, что диапазон включает в себя все доступное качество."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"autoQualityRange","role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)autoQualityRange","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoQualityRange","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","text":"QualityRange"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"autoQualityRange","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/autoQualityRange"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Диапазон, в котором плеер будет играть, если выбрано автоматическое качество."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/autoqualityrange"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/autoqualityrange"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/autoQualityRange":{"abstract":[{"type":"text","text":"Диапазон, в котором плеер будет играть, если выбрано автоматическое качество."}],"url":"\/documentation\/ovkit\/ovkplayerview\/autoqualityrange","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/autoQualityRange","title":"autoQualityRange","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoQualityRange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange","kind":"typeIdentifier","text":"QualityRange"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"autoQualityRange","kind":"identifier"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/QualityRange":{"navigatorTitle":[{"text":"QualityRange","kind":"identifier"}],"url":"\/documentation\/ovkit\/qualityrange","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QualityRange","kind":"identifier"}],"title":"QualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","abstract":[{"type":"text","text":"Диапазон качества видео."}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"autoQualityRange","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"autoQualityRange"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"OVKQualityRange","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/QualityRange","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKQualityRange"},{"kind":"text","text":" * "},{"kind":"identifier","text":"autoQualityRange"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1autoQualityRange\/title","value":"autoQualityRange"},{"op":"replace","value":[{"text":"autoQualityRange","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1autoQualityRange\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/title","op":"replace","value":"OVKQualityRange"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1QualityRange\/fragments","value":[{"text":"OVKQualityRange","kind":"identifier"}]},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"}]}]}