{"abstract":[{"text":"Поддержка автоматического разворачивания в полноэкранный горизонтальный режим. Видео в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference","isActive":true},{"text":" должно подходить по параметрам (быть горизонтальным, не GIF). При вызове метода ","type":"text"},{"type":"codeVoice","code":"maximizeToFullscreenLandscape(completion:)"},{"type":"text","text":" свойство игнорируется."}],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/autorotatetolandscapeinfullscreenifpossible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/autorotatetolandscapeinfullscreenifpossible"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)autoRotateToLandscapeInFullscreenIfPossible","title":"autoRotateToLandscapeInFullscreenIfPossible","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию имеет значение "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/autoRotateToLandscapeInFullscreenIfPossible"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/autoRotateToLandscapeInFullscreenIfPossible":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoRotateToLandscapeInFullscreenIfPossible"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","url":"\/documentation\/ovkit\/ovkplayerview\/autorotatetolandscapeinfullscreenifpossible","title":"autoRotateToLandscapeInFullscreenIfPossible","abstract":[{"type":"text","text":"Поддержка автоматического разворачивания в полноэкранный горизонтальный режим. Видео в "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"reference"},{"text":" должно подходить по параметрам (быть горизонтальным, не GIF). При вызове метода ","type":"text"},{"code":"maximizeToFullscreenLandscape(completion:)","type":"codeVoice"},{"type":"text","text":" свойство игнорируется."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/autoRotateToLandscapeInFullscreenIfPossible"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"autoRotateToLandscapeInFullscreenIfPossible","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autoRotateToLandscapeInFullscreenIfPossible","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"autoRotateToLandscapeInFullscreenIfPossible","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1autoRotateToLandscapeInFullscreenIfPossible\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1autoRotateToLandscapeInFullscreenIfPossible\/fragments","value":[{"kind":"identifier","text":"autoRotateToLandscapeInFullscreenIfPossible"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}