{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/availableAutoShoppable"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","title":"availableAutoShoppable","navigatorTitle":[{"kind":"identifier","text":"availableAutoShoppable"}],"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)availableAutoShoppable","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableAutoShoppable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"OVKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"availableAutoShoppable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"type":"text","text":"Разрешено ли открывать рекламу формата shoppable автоматически при старте баннера"},{"type":"text","text":" "},{"text":"Обычно настраивается  до  начала проигрывания и зависит от места использования ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Допустимые места для активации этой функции – полноэкранный режим, ленты с включенным по умолчанию звуком плеера."}],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/availableautoshoppable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/availableautoshoppable"]}],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/availableAutoShoppable":{"type":"topic","url":"\/documentation\/ovkit\/ovkplayerview\/availableautoshoppable","title":"availableAutoShoppable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableAutoShoppable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"availableAutoShoppable","kind":"identifier"}],"abstract":[{"type":"text","text":"Разрешено ли открывать рекламу формата shoppable автоматически при старте баннера"},{"text":" ","type":"text"},{"text":"Обычно настраивается  до  начала проигрывания и зависит от места использования ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Допустимые места для активации этой функции – полноэкранный режим, ленты с включенным по умолчанию звуком плеера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/availableAutoShoppable","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"availableAutoShoppable","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"availableAutoShoppable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableAutoShoppable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1availableAutoShoppable\/title","value":"availableAutoShoppable"},{"value":[{"text":"availableAutoShoppable","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1availableAutoShoppable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}