{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/backgroundPlaybackPolicy"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/backgroundplaybackpolicy"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/backgroundplaybackpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)backgroundPlaybackPolicy","symbolKind":"property","title":"backgroundPlaybackPolicy","navigatorTitle":[{"text":"backgroundPlaybackPolicy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","text":"BackgroundPlaybackPolicy"}],"roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","text":"BackgroundPlaybackPolicy"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Если выбрать продолжение воспроизведения, то при проигрывании в системе появятся контролы медиацентра ("},{"type":"codeVoice","code":"MPRemoteCommandCenter"},{"type":"text","text":")."}]},{"inlineContent":[{"type":"text","text":"Поддерживается возможность изменить значение во время воспроизведения видео. А при переходах с одного "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","isActive":true,"type":"reference"},{"type":"text","text":" на другой (с использованием "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","isActive":true},{"type":"text","text":") текущее значение автоматически применится в конце перехода."}],"type":"paragraph"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Фоновое воспроизведение может быть недоступно из-за параметров отдельно взятого видео.","type":"text"}]}],"style":"note","type":"aside"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию значение "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause","type":"reference","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView/createAnimatedTransition(to:in:)":{"url":"\/documentation\/ovkit\/playerview\/createanimatedtransition(to:in:)","title":"createAnimatedTransition(to:in:)","abstract":[{"text":"Создание вспомогательного объекта для анимированного переноса плеера из текущего PlayerView в место назначения.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnimatedTransition","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerViewAnimatedTransition","text":"PlayerViewAnimatedTransition"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/createAnimatedTransition(to:in:)","navigatorTitle":[{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy/pause":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/backgroundplaybackpolicy\/pause","abstract":[{"text":"Приостановка воспроизведения.","type":"text"}],"title":"BackgroundPlaybackPolicy.pause","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy\/pause","navigatorTitle":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/backgroundPlaybackPolicy":{"url":"\/documentation\/ovkit\/ovkplayerview\/backgroundplaybackpolicy","title":"backgroundPlaybackPolicy","abstract":[{"type":"text","text":"Поведение плеера при уходе приложения в фон."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backgroundPlaybackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BackgroundPlaybackPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/backgroundPlaybackPolicy","navigatorTitle":[{"text":"backgroundPlaybackPolicy","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BackgroundPlaybackPolicy":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","navigatorTitle":[{"text":"BackgroundPlaybackPolicy","kind":"identifier"}],"abstract":[{"text":"Поведение плеера при уходе приложения в фон.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/backgroundplaybackpolicy","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundPlaybackPolicy"}],"title":"BackgroundPlaybackPolicy","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"backgroundPlaybackPolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BackgroundPlaybackPolicy","kind":"typeIdentifier","text":"OVKBackgroundPlaybackPolicy","preciseIdentifier":"c:@M@OVKit@E@OVKBackgroundPlaybackPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundPlaybackPolicy"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createAnimatedTransitionTo:in:","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createAnimatedTransitionTo:in:"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView~1createAnimatedTransition(to:in:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/title","value":"OVKBackgroundPlaybackPolicyPause"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy~1pause\/fragments","value":[{"text":"OVKBackgroundPlaybackPolicyPause","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1backgroundPlaybackPolicy\/title","value":"backgroundPlaybackPolicy"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1backgroundPlaybackPolicy\/fragments","value":[{"kind":"identifier","text":"backgroundPlaybackPolicy"}]},{"value":"OVKBackgroundPlaybackPolicy","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/title","op":"replace"},{"value":[{"text":"OVKBackgroundPlaybackPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BackgroundPlaybackPolicy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}