{"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chapterProvider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"chapterProvider","kind":"identifier"}],"modules":[{"name":"OVKit"}],"role":"symbol","symbolKind":"property","title":"chapterProvider","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)chapterProvider"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Изменяется после установки свойства ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","isActive":true},{"type":"text","text":", а также может измениться после анимированного переноса плеера. Значение "},{"type":"codeVoice","code":"nil"},{"text":" означает, что в видео отсутствует разбивка на эпизоды.","type":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/chapterProvider","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/chapterprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/chapterprovider"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"},{"type":"text","text":" для текущего видео."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/chapterProvider":{"type":"topic","url":"\/documentation\/ovkit\/ovkplayerview\/chapterprovider","title":"chapterProvider","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chapterProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"chapterProvider"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider"},{"type":"text","text":" для текущего видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/chapterProvider","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"title":"ChapterProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChapterProvider","kind":"identifier"}],"url":"\/documentation\/ovkit\/chapterprovider","navigatorTitle":[{"text":"ChapterProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/Video":{"title":"Video","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Video","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/ovkit\/video","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"chapterProvider","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"chapterProvider","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"OVKChapterProvider","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider"},{"text":" * ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1chapterProvider\/title","value":"chapterProvider","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1chapterProvider\/fragments","op":"replace","value":[{"text":"chapterProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"op":"replace","value":"OVKVideo","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","value":[{"kind":"identifier","text":"OVKVideo"}]}]}]}