{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loopBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"LoopBehavior"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Значение по умолчанию - auto.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/loopBehavior"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/loopbehavior"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/loopbehavior"]}],"abstract":[{"text":"Задает поведение плеера при завершении видео.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"loopBehavior"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)loopBehavior","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loopBehavior","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"LoopBehavior","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","title":"loopBehavior","modules":[{"name":"OVKit"}]},"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/loopBehavior":{"url":"\/documentation\/ovkit\/ovkplayerview\/loopbehavior","type":"topic","title":"loopBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopBehavior"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"LoopBehavior"}],"role":"symbol","navigatorTitle":[{"text":"loopBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"Задает поведение плеера при завершении видео."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/loopBehavior","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/LoopBehavior":{"url":"\/documentation\/ovkit\/loopbehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","title":"LoopBehavior","abstract":[{"type":"text","text":"Поведение плеера при завершении видео."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoopBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"LoopBehavior"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"loopBehavior"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"loopBehavior"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/LoopBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKLoopBehavior","text":"OVKLoopBehavior"},{"text":" ","kind":"text"},{"text":"loopBehavior","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKPlayerView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"op":"replace","value":"loopBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1loopBehavior\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1loopBehavior\/fragments","value":[{"text":"loopBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/title","op":"replace","value":"OVKLoopBehavior"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1LoopBehavior\/fragments","value":[{"text":"OVKLoopBehavior","kind":"identifier"}]}]}]}