{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaSelection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","text":"MediaSelection","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Свойство присутствует только у ресурсов, которые поддерживают переключение между множественными дорожками. Оно становится доступно после того, как ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/delegate","isActive":true,"type":"reference"},{"type":"text","text":" или "},{"code":"listener","type":"codeVoice"},{"type":"text","text":" получит сообщение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","isActive":true},{"type":"text","text":"."}]},{"content":[{"inlineContent":[{"type":"text","text":"Полученный объект "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","type":"reference"},{"text":" является валидным только пока проигрывается видео, на котором он был получен. После смены видео он перестанет работать.","type":"text"}],"type":"paragraph"}],"name":"Warning","type":"aside","style":"warning"}],"kind":"content"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/mediaSelection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/mediaselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/mediaselection"]}],"abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видео ресурсе."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)mediaSelection","title":"mediaSelection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mediaSelection"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaSelection"},{"text":": ","kind":"text"},{"text":"MediaSelection","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerEventListener/playerDidStart(_:userInitiated:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidStart"},{"text":"(","kind":"text"},{"text":"PlayerView","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerEventListener\/playerDidStart(_:userInitiated:)","url":"\/documentation\/ovkit\/playereventlistener\/playerdidstart(_:userinitiated:)","required":true,"abstract":[{"text":"Плеер начал работу: качать и проигрывать.","type":"text"}],"kind":"symbol","title":"playerDidStart(_:userInitiated:)","navigatorTitle":[{"kind":"identifier","text":"playerDidStart:userInitiated:"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/delegate":{"url":"\/documentation\/ovkit\/ovkplayerview\/delegate","type":"topic","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"PlayerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerDelegate"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/delegate","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"kind":"symbol","role":"symbol","url":"\/documentation\/ovkit\/mediaselection","abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видеоресурсе."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaSelection","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaSelection"}],"title":"MediaSelection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/mediaSelection":{"type":"topic","url":"\/documentation\/ovkit\/ovkplayerview\/mediaselection","title":"mediaSelection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaSelection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","kind":"typeIdentifier","text":"MediaSelection"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"mediaSelection","kind":"identifier"}],"abstract":[{"text":"Набор медиадорожек, находящихся в видео ресурсе.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/mediaSelection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"mediaSelection","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"mediaSelection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelection","text":"OVKMediaSelection"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mediaSelection"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/title","value":"playerDidStart:userInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerEventListener~1playerDidStart(_:userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"playerDidStart:userInitiated:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1delegate\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title","op":"replace","value":"OVKMediaSelection"},{"value":[{"text":"OVKMediaSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments"},{"value":"mediaSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1mediaSelection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1mediaSelection\/fragments","value":[{"kind":"identifier","text":"mediaSelection"}]}]}]}