{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"title":"mediaSelectionDelegate","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mediaSelectionDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate","kind":"typeIdentifier","text":"PlayerMediaSelectionDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mediaSelectionDelegate"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)mediaSelectionDelegate"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Этому делегату плеер сообщает о событиях, связанных с выбором аудио дорожек и субтитров."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaSelectionDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate","kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","text":"PlayerMediaSelectionDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/mediaSelectionDelegate"},"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/mediaselectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/mediaselectiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/mediaSelectionDelegate":{"url":"\/documentation\/ovkit\/ovkplayerview\/mediaselectiondelegate","title":"mediaSelectionDelegate","abstract":[{"type":"text","text":"Этому делегату плеер сообщает о событиях, связанных с выбором аудио дорожек и субтитров."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mediaSelectionDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerMediaSelectionDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/mediaSelectionDelegate","navigatorTitle":[{"text":"mediaSelectionDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerMediaSelectionDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"abstract":[{"text":"Делегат для работы с выбором аудио\/видео дорожек и субтитров.","type":"text"}],"title":"PlayerMediaSelectionDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerMediaSelectionDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerMediaSelectionDelegate"}],"url":"\/documentation\/ovkit\/playermediaselectiondelegate","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"mediaSelectionDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"mediaSelectionDelegate"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerMediaSelectionDelegate","kind":"typeIdentifier","text":"id<OVKPlayerMediaSelectionDelegate>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaSelectionDelegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"kind":"identifier","text":"OVKPlayerView"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1mediaSelectionDelegate\/title","op":"replace","value":"mediaSelectionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1mediaSelectionDelegate\/fragments","value":[{"text":"mediaSelectionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/title","value":"OVKPlayerMediaSelectionDelegate"},{"value":[{"kind":"identifier","text":"OVKPlayerMediaSelectionDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerMediaSelectionDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}