{"kind":"symbol","metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)playbackRate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"playbackRate"}],"role":"symbol","title":"playbackRate"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/playbackRate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/playbackrate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/playbackrate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Поддерживаемые значения: ","type":"text"},{"code":"0.25","type":"codeVoice"},{"type":"text","text":", "},{"code":"0.5","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.75","type":"codeVoice"},{"type":"text","text":", "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":", "},{"code":"1.25","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"1.5"},{"text":", ","type":"text"},{"type":"codeVoice","code":"1.75"},{"text":", ","type":"text"},{"code":"2.0","type":"codeVoice"},{"type":"text","text":". Они могут меняться в зависимости от значения свойства "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","isActive":true},{"text":". По умолчанию ","type":"text"},{"type":"codeVoice","code":"1.0"},{"text":".","type":"text"}],"type":"paragraph"},{"name":"Warning","type":"aside","style":"warning","content":[{"inlineContent":[{"text":"Если установить другое значение, оно автоматически скорректируется до ближайшего поддерживаемого.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Скорость воспроизведения."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView/customPlaybackRates":{"kind":"symbol","abstract":[{"type":"text","text":"Набор доступных скоростей воспроизведения, который переопределяет стандартный набор."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customPlaybackRates"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"]?","kind":"text"}],"type":"topic","url":"\/documentation\/ovkit\/playerview\/customplaybackrates","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView\/customPlaybackRates","title":"customPlaybackRates"},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/playbackRate":{"kind":"symbol","abstract":[{"text":"Скорость воспроизведения.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/ovkit\/ovkplayerview\/playbackrate","type":"topic","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/playbackRate","title":"playbackRate"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"playbackRate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"playbackRate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackRate"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"playbackRate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1playbackRate\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1playbackRate\/fragments","value":[{"text":"playbackRate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"op":"replace","value":[{"text":"OVKPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}