{"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"role":"symbol","title":"playerViewOnScreen","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)playerViewOnScreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"abstract":[{"text":"Отвечает за видимость плеера на экране.","type":"text"},{"type":"text","text":" "},{"text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Это свойство может изменится, если вызван "},{"type":"codeVoice","code":"play(userInitiated:)"},{"type":"text","text":" со значением "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playerViewOnScreen","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/playerviewonscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/playerviewonscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/playerViewOnScreen","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/playerViewOnScreen":{"url":"\/documentation\/ovkit\/ovkplayerview\/playerviewonscreen","title":"playerViewOnScreen","abstract":[{"text":"Отвечает за видимость плеера на экране.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Так плеер понимает когда необходимо приостановить или продолжить воспроизведение."},{"text":" ","type":"text"},{"type":"text","text":"Это свойство может изменится, если вызван "},{"code":"play(userInitiated:)","type":"codeVoice"},{"type":"text","text":" со значением "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/playerViewOnScreen","navigatorTitle":[{"kind":"identifier","text":"playerViewOnScreen"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"playerViewOnScreen","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"playerViewOnScreen"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"playerViewOnScreen","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1playerViewOnScreen\/title","op":"replace","value":"playerViewOnScreen"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1playerViewOnScreen\/fragments","value":[{"text":"playerViewOnScreen","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}