{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"previewGravity","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"По умолчанию значение "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/ovkplayerview\/previewgravity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/previewgravity"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"extendedModule":"OVKit","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewGravity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"}],"roleHeading":"Instance Property","externalID":"c:@CM@OVKit@objc(cs)OVKPlayerView(py)previewGravity","title":"previewGravity","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"previewGravity"}],"role":"symbol"},"abstract":[{"type":"text","text":"Режим отображения превью."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/previewGravity","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/previewGravity":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewGravity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity","text":"PlayerViewGravity"}],"abstract":[{"text":"Режим отображения превью.","type":"text"}],"kind":"symbol","title":"previewGravity","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/previewGravity","url":"\/documentation\/ovkit\/ovkplayerview\/previewgravity","navigatorTitle":[{"kind":"identifier","text":"previewGravity"}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity/fill":{"role":"symbol","navigatorTitle":[{"text":"OVKPlayerViewGravityFill","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}],"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/playerviewgravity\/fill","title":"PlayerViewGravity.fill","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity\/fill"},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewGravity":{"url":"\/documentation\/ovkit\/playerviewgravity","title":"PlayerViewGravity","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerViewGravity"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlayerViewGravity","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"previewGravity","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"previewGravity"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewGravity","kind":"typeIdentifier","text":"OVKPlayerViewGravity","preciseIdentifier":"c:@M@OVKit@E@OVKPlayerViewGravity"},{"kind":"text","text":" "},{"text":"previewGravity","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"previewGravity","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1previewGravity\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1previewGravity\/fragments","op":"replace","value":[{"kind":"identifier","text":"previewGravity"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPlayerView"}]},{"value":"OVKPlayerViewGravityFill","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPlayerViewGravityFill"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity~1fill\/fragments"},{"op":"replace","value":"OVKPlayerViewGravity","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/title"},{"value":[{"text":"OVKPlayerViewGravity","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewGravity\/fragments","op":"replace"}]}]}