{"metadata":{"title":"queueDelegate","roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)queueDelegate","navigatorTitle":[{"text":"queueDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queueDelegate"},{"text":": ","kind":"text"},{"text":"PlayerQueueDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"OVKit"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/queueDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/queuedelegate"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/queuedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queueDelegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate","text":"PlayerQueueDelegate"},{"kind":"text","text":"?"}]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"url":"\/documentation\/ovkit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/queueDelegate":{"title":"queueDelegate","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/queueDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queueDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlayerQueueDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerQueueDelegate"},{"text":"?","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"queueDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovkplayerview\/queuedelegate","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","title":"PlayerView","abstract":[],"url":"\/documentation\/ovkit\/playerview","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerQueueDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PlayerQueueDelegate","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerQueueDelegate","abstract":[{"type":"text","text":"Протокол для поддержки плеером очереди воспроизведения."}],"type":"topic","url":"\/documentation\/ovkit\/playerqueuedelegate","navigatorTitle":[{"text":"PlayerQueueDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PlayerQueueDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"queueDelegate","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"queueDelegate","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerQueueDelegate","text":"id<OVKPlayerQueueDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"queueDelegate","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1queueDelegate\/title","value":"queueDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1queueDelegate\/fragments","value":[{"text":"queueDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/title","value":"OVKPlayerQueueDelegate","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerQueueDelegate\/fragments","value":[{"text":"OVKPlayerQueueDelegate","kind":"identifier"}],"op":"replace"}]}]}