{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)showsLastVideoFrameOnPreview","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"showsLastVideoFrameOnPreview","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showsLastVideoFrameOnPreview"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"showsLastVideoFrameOnPreview"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Показывать последний кадр видео вместо изображения предпросмотра.","type":"text"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/showsLastVideoFrameOnPreview","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showsLastVideoFrameOnPreview"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"Если активно при остановке видео, то любой следующий плеер, где эта опция также активна, будет показывать в ","type":"text"},{"inlineContent":[{"text":"preview","type":"text"}],"type":"emphasis"},{"text":" последний кадр, на котором остановилось воспроизведение в прошлый раз.","type":"text"}],"type":"paragraph"},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Действует только при включенной опции ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/savesPlaybackTimeOnStop","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"style":"warning"},{"type":"paragraph","inlineContent":[{"type":"text","text":"По умолчанию значение "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/showslastvideoframeonpreview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/showslastvideoframeonpreview"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/showsLastVideoFrameOnPreview":{"url":"\/documentation\/ovkit\/ovkplayerview\/showslastvideoframeonpreview","title":"showsLastVideoFrameOnPreview","abstract":[{"text":"Показывать последний кадр видео вместо изображения предпросмотра.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsLastVideoFrameOnPreview","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/showsLastVideoFrameOnPreview","navigatorTitle":[{"text":"showsLastVideoFrameOnPreview","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/savesPlaybackTimeOnStop":{"url":"\/documentation\/ovkit\/ovkplayerview\/savesplaybacktimeonstop","title":"savesPlaybackTimeOnStop","abstract":[{"text":"Сохранять время воспроизведения для видео, на котором было остановлено проигрывание.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"savesPlaybackTimeOnStop"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/savesPlaybackTimeOnStop","navigatorTitle":[{"text":"savesPlaybackTimeOnStop","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"showsLastVideoFrameOnPreview"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"showsLastVideoFrameOnPreview"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"showsLastVideoFrameOnPreview","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1showsLastVideoFrameOnPreview\/title","value":"showsLastVideoFrameOnPreview","op":"replace"},{"op":"replace","value":[{"text":"showsLastVideoFrameOnPreview","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1showsLastVideoFrameOnPreview\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1savesPlaybackTimeOnStop\/title","op":"replace","value":"savesPlaybackTimeOnStop"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1savesPlaybackTimeOnStop\/fragments","value":[{"kind":"identifier","text":"savesPlaybackTimeOnStop"}]}]}]}