{"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)startButtonBehavior","title":"startButtonBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startButtonBehavior"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"PreviewPlayButtonBehavior"}],"navigatorTitle":[{"text":"startButtonBehavior","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/startButtonBehavior","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"abstract":[{"type":"text","text":"Поведение кнопки "},{"inlineContent":[{"text":"Play","type":"text"}],"type":"emphasis"},{"text":", которая показывается на превью до начала проигрывания видео. Используется поведение ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","isActive":true,"type":"reference"},{"type":"text","text":" по умолчанию, если не указать иное."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/startbuttonbehavior"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/startbuttonbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startButtonBehavior","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"PreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/startButtonBehavior":{"url":"\/documentation\/ovkit\/ovkplayerview\/startbuttonbehavior","type":"topic","title":"startButtonBehavior","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startButtonBehavior"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"PreviewPlayButtonBehavior"}],"role":"symbol","navigatorTitle":[{"text":"startButtonBehavior","kind":"identifier"}],"abstract":[{"text":"Поведение кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"text":", которая показывается на превью до начала проигрывания видео. Используется поведение ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior"},{"type":"text","text":" по умолчанию, если не указать иное."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/startButtonBehavior","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PreviewPlayButtonBehavior":{"url":"\/documentation\/ovkit\/previewplaybuttonbehavior","type":"topic","title":"PreviewPlayButtonBehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PreviewPlayButtonBehavior","kind":"identifier"}],"abstract":[{"text":"Поведение кнопки ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Play","type":"text"}]},{"text":", которая показывается на превью до начала проигрывания видео.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"startButtonBehavior","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"startButtonBehavior","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKPreviewPlayButtonBehavior","text":"OVKPreviewPlayButtonBehavior","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PreviewPlayButtonBehavior","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"startButtonBehavior","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"startButtonBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1startButtonBehavior\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1startButtonBehavior\/fragments","op":"replace","value":[{"text":"startButtonBehavior","kind":"identifier"}]},{"value":"OVKPlayerView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title"},{"value":[{"kind":"identifier","text":"OVKPlayerView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","op":"replace"},{"value":"OVKPreviewPlayButtonBehavior","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/title","op":"replace"},{"value":[{"text":"OVKPreviewPlayButtonBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PreviewPlayButtonBehavior\/fragments"}]}]}