{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/statscollector"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/statscollector"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/statsCollector"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statsCollector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","text":"StatsCollector","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"title":"statsCollector","symbolKind":"property","role":"symbol","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsCollector"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector","kind":"typeIdentifier","text":"StatsCollector"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"statsCollector","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)statsCollector"},"sections":[],"kind":"symbol","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector"},{"type":"text","text":" будет существовать после установки "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/video","type":"reference"},{"type":"text","text":"."}],"references":{"doc://onevideo.OVKit/documentation/OVKit/StatsHandler":{"navigatorTitle":[{"text":"StatsHandler","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Протокол объекта, который может принимать события от "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"События логирования будут вызваны на специальной background очереди."},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","isActive":true},{"type":"text","text":" после добавления нового "},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","type":"reference"},{"text":" будет удерживать его, поэтому снаружи не нужно удерживать сильную ссылку.","type":"text"}],"url":"\/documentation\/ovkit\/statshandler","type":"topic","title":"StatsHandler","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsHandler","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/StatsCollector":{"navigatorTitle":[{"kind":"identifier","text":"StatsCollector"}],"role":"symbol","abstract":[{"type":"text","text":"Собирает события для статистики и уведомляет всех "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsHandler","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Не привязан к ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"},{"text":", пример: collector передается при транзишенах между playerView вместе с объектом ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","type":"reference"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"или переходах в PiP и fullscreen."}],"url":"\/documentation\/ovkit\/statscollector","type":"topic","title":"StatsCollector","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"StatsCollector","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/statsCollector":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/statsCollector","role":"symbol","navigatorTitle":[{"text":"statsCollector","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsCollector","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatsCollector","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKStatsCollector","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/ovkplayerview\/statscollector","abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsCollector","type":"reference","isActive":true},{"text":" будет существовать после установки ","type":"text"},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/video","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"statsCollector"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/video":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/video","navigatorTitle":[{"text":"video","kind":"identifier"}],"abstract":[{"type":"text","text":"Не устанавливать nil: останавливать проигрывание необходимо через "},{"type":"codeVoice","code":"stop()"},{"text":" или ","type":"text"},{"type":"codeVoice","code":"prepareForReuse()"}],"type":"topic","kind":"symbol","url":"\/documentation\/ovkit\/ovkplayerview\/video","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKVideoType","text":"VideoType"},{"text":"?","kind":"text"}],"title":"video","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerView"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","title":"PlayerView"},"doc://onevideo.OVKit/documentation/OVKit/Video":{"navigatorTitle":[{"text":"Video","kind":"identifier"}],"role":"symbol","url":"\/documentation\/ovkit\/video","abstract":[],"type":"topic","title":"Video","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Video"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/Video","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"statsCollector","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"statsCollector","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKStatsCollector","text":"id<OVKStatsCollector>"},{"text":" ","kind":"text"},{"text":"statsCollector","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/title","value":"OVKStatsHandler","op":"replace"},{"value":[{"kind":"identifier","text":"OVKStatsHandler"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsHandler\/fragments","op":"replace"},{"op":"replace","value":"OVKStatsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/title"},{"value":[{"kind":"identifier","text":"OVKStatsCollector"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsCollector\/fragments"},{"value":"statsCollector","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1statsCollector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1statsCollector\/fragments","value":[{"text":"statsCollector","kind":"identifier"}]},{"value":"video","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1video\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1video\/fragments","value":[{"text":"video","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"value":"OVKVideo","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1Video\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}