{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/subtitles"},"kind":"symbol","abstract":[{"type":"text","text":"Набор доступных дорожек субтитров. Будет доступен после "},{"type":"codeVoice","code":"PlayerSubtitlesDelegate\/playerSubtitlesPrepared(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","kind":"typeIdentifier","text":"SubtitlesOption"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitles"}],"title":"subtitles","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"subtitles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SubtitlesOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"kind":"text","text":"]?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)subtitles","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/subtitles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/subtitles"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/SubtitlesOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/SubtitlesOption","abstract":[{"text":"Дорожка субтитров.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SubtitlesOption","kind":"identifier"}],"title":"SubtitlesOption","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SubtitlesOption","kind":"identifier"}],"url":"\/documentation\/ovkit\/subtitlesoption"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/subtitles":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/subtitles","abstract":[{"text":"Набор доступных дорожек субтитров. Будет доступен после ","type":"text"},{"type":"codeVoice","code":"PlayerSubtitlesDelegate\/playerSubtitlesPrepared(_:)"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subtitles"}],"title":"subtitles","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SubtitlesOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKSubtitlesOption"},{"kind":"text","text":"]?"}],"url":"\/documentation\/ovkit\/ovkplayerview\/subtitles"},"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"role":"symbol","abstract":[],"title":"PlayerView","kind":"symbol","url":"\/documentation\/ovkit\/playerview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"subtitles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"subtitles","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<OVKSubtitlesOption *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"subtitles","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"OVKSubtitlesOption","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/title"},{"value":[{"kind":"identifier","text":"OVKSubtitlesOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1SubtitlesOption\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1subtitles\/title","op":"replace","value":"subtitles"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1subtitles\/fragments","value":[{"text":"subtitles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","value":"OVKPlayerView","op":"replace"},{"value":[{"text":"OVKPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments"}]}]}