{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkplayerview\/viewdelegate"]},{"paths":["\/documentation\/ovkit\/ovkplayerview\/viewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDelegate"},{"kind":"text","text":": "},{"text":"PlayerViewDelegate","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/viewDelegate","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"viewDelegate","kind":"identifier"}],"modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDelegate"},{"text":": ","kind":"text"},{"text":"PlayerViewDelegate","preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPlayerView(py)viewDelegate","role":"symbol","roleHeading":"Instance Property","title":"viewDelegate","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/PlayerView":{"type":"topic","role":"symbol","kind":"symbol","title":"PlayerView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerView","kind":"identifier"}],"url":"\/documentation\/ovkit\/playerview"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/OVKPlayerView/viewDelegate":{"url":"\/documentation\/ovkit\/ovkplayerview\/viewdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDelegate"}],"type":"topic","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKPlayerView\/viewDelegate","title":"viewDelegate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(pl)OVKPlayerViewDelegate","text":"PlayerViewDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PlayerViewDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlayerViewDelegate"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PlayerViewDelegate","abstract":[],"url":"\/documentation\/ovkit\/playerviewdelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlayerViewDelegate"}],"title":"PlayerViewDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"viewDelegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"viewDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@OVKit@objc(pl)OVKPlayerViewDelegate","kind":"typeIdentifier","text":"id<OVKPlayerViewDelegate>"},{"text":" ","kind":"text"},{"text":"viewDelegate","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/title","op":"replace","value":"OVKPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerView\/fragments","value":[{"text":"OVKPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1viewDelegate\/title","value":"viewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKPlayerView~1viewDelegate\/fragments","value":[{"kind":"identifier","text":"viewDelegate"}]},{"value":"OVKPlayerViewDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/title"},{"value":[{"text":"OVKPlayerViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PlayerViewDelegate\/fragments"}]}]}