{"kind":"symbol","metadata":{"title":"actionButtonTitle","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButtonTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"s:5OVKit14ErrorCoverViewC17actionButtonTitleSSvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/actionButtonTitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Текст для кнопки действия. По умолчанию  "},{"type":"codeVoice","code":"ovk_retry"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/errorcoverview\/actionbuttontitle"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"title":"ErrorCoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ErrorCoverView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCoverView","kind":"identifier"}],"url":"\/documentation\/ovkit\/errorcoverview","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/actionButtonTitle":{"title":"actionButtonTitle","role":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/actionButtonTitle","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Текст для кнопки действия. По умолчанию  "},{"type":"codeVoice","code":"ovk_retry"},{"text":".","type":"text"}],"url":"\/documentation\/ovkit\/errorcoverview\/actionbuttontitle"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","value":"ErrorCoverView","op":"replace"},{"op":"replace","value":[{"text":"ErrorCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCoverView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle"}]}]}