{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/errorcoverview\/coverviewtype-implementations"]}],"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"OVKit"}],"roleHeading":"API Collection","title":"CoverViewType Implementations"},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/CoverViewType-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/darkBackgroundColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/iconColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/textColor","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/titleSize"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/darkBackgroundColor":{"kind":"symbol","abstract":[{"text":"Цвет затемнения фона.","type":"text"}],"url":"\/documentation\/ovkit\/errorcoverview\/darkbackgroundcolor","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/darkBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"darkBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"darkBackgroundColor"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/iconColor":{"title":"iconColor","type":"topic","abstract":[{"text":"Цвет иконки.","type":"text"}],"kind":"symbol","url":"\/documentation\/ovkit\/errorcoverview\/iconcolor","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/iconColor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/titleSize":{"url":"\/documentation\/ovkit\/errorcoverview\/titlesize","title":"titleSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/titleSize","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Размер заголовка заглушки, по умолчанию 16pt."}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/textColor":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Цвет текста."}],"title":"textColor","type":"topic","url":"\/documentation\/ovkit\/errorcoverview\/textcolor","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/errorcoverview","kind":"symbol","abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"title":"ErrorCoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCoverView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"ErrorCoverView","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title"},{"value":[{"kind":"identifier","text":"ErrorCoverView"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCoverView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}