{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"darkBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Цвет затемнения фона.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/errorcoverview\/darkbackgroundcolor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/darkBackgroundColor","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","extendedModule":"OVKit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"darkBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"s:5OVKit13CoverViewTypePAAE19darkBackgroundColorSo7UIColorCvp::SYNTHESIZED::c:@M@OVKit@objc(cs)ErrorCoverView","title":"darkBackgroundColor","modules":[{"name":"OVKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/CoverViewType-Implementations"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"url":"\/documentation\/ovkit\/errorcoverview","title":"ErrorCoverView","navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCoverView"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/darkBackgroundColor":{"title":"darkBackgroundColor","abstract":[{"text":"Цвет затемнения фона.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"\/documentation\/ovkit\/errorcoverview\/darkbackgroundcolor","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/darkBackgroundColor","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/CoverViewType-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/ovkit\/errorcoverview\/coverviewtype-implementations","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/CoverViewType-Implementations","title":"CoverViewType Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","value":"ErrorCoverView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","value":[{"text":"ErrorCoverView","kind":"identifier"}]},{"op":"replace","value":[{"text":"ErrorCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle"}]}]}