{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"abstract":[{"type":"text","text":"Плеер закончил переезд на новую "},{"type":"codeVoice","code":"PlayerView"}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/didEndTransitioning()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didEndTransitioning","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEndTransitioning"}],"externalID":"c:@M@OVKit@objc(cs)ErrorCoverView(im)didEndTransitioning","roleHeading":"Instance Method","symbolKind":"method","title":"didEndTransitioning()"},"variants":[{"paths":["\/documentation\/ovkit\/errorcoverview\/didendtransitioning()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/errorcoverview\/didendtransitioning()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didEndTransitioning"},{"text":"()","kind":"text"}]}]}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/didEndTransitioning()":{"title":"didEndTransitioning()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"didEndTransitioning","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/didEndTransitioning()","url":"\/documentation\/ovkit\/errorcoverview\/didendtransitioning()","role":"symbol","abstract":[{"type":"text","text":"Плеер закончил переезд на новую "},{"type":"codeVoice","code":"PlayerView"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"role":"symbol","type":"topic","url":"\/documentation\/ovkit\/errorcoverview","kind":"symbol","abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"title":"ErrorCoverView","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCoverView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didEndTransitioning"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didEndTransitioning"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didEndTransitioning"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1didEndTransitioning()\/title","op":"replace","value":"didEndTransitioning"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1didEndTransitioning()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didEndTransitioning","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","op":"replace","value":"ErrorCoverView"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","value":[{"text":"ErrorCoverView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ErrorCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle","op":"replace"}]}]}