{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleActionButton"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/ovkit\/errorcoverview\/handleactionbutton()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/errorcoverview\/handleactionbutton()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleActionButton","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"handleActionButton","kind":"identifier"}],"roleHeading":"Instance Method","title":"handleActionButton()","modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@objc(cs)ErrorCoverView(im)handleActionButton"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleActionButton()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Нажатию на кнопку действия. По умолчанию ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","type":"reference","isActive":true}],"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/handleActionButton()":{"url":"\/documentation\/ovkit\/errorcoverview\/handleactionbutton()","abstract":[{"text":"Нажатию на кнопку действия. По умолчанию ","type":"text"},{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","type":"reference"}],"kind":"symbol","title":"handleActionButton()","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/handleActionButton()","navigatorTitle":[{"text":"handleActionButton","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleActionButton"},{"text":"()","kind":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverControlsDelegate/reloadVideo()":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverControlsDelegate\/reloadVideo()","required":true,"abstract":[{"text":"Перезагрузка видео.","type":"text"}],"url":"\/documentation\/ovkit\/covercontrolsdelegate\/reloadvideo()","kind":"symbol","title":"reloadVideo()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reloadVideo"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadVideo","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"abstract":[{"type":"text","text":"Ковер для показа ошибки воспроизведения."}],"type":"topic","url":"\/documentation\/ovkit\/errorcoverview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCoverView"}],"title":"ErrorCoverView","navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"handleActionButton","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleActionButton"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleActionButton"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleActionButton()\/title","value":"handleActionButton","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1handleActionButton()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleActionButton"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/title","value":"reloadVideo"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverControlsDelegate~1reloadVideo()\/fragments","value":[{"kind":"text","text":"- "},{"text":"reloadVideo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","value":"ErrorCoverView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","value":[{"text":"ErrorCoverView","kind":"identifier"}]},{"value":[{"text":"ErrorCoverView","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle","op":"replace"}]}]}