{"variants":[{"paths":["\/documentation\/ovkit\/errorcoverview\/params"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","text":"CoverViewParams"}],"externalID":"s:5OVKit14ErrorCoverViewC6paramsAA0cD6ParamsCvp","title":"params","modules":[{"name":"OVKit"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"params","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/params"},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/params":{"role":"symbol","title":"params","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/params","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"text":": ","kind":"text"},{"text":"CoverViewParams","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKCoverViewParams","kind":"typeIdentifier"}],"url":"\/documentation\/ovkit\/errorcoverview\/params","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/CoverViewParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoverViewParams","kind":"identifier"}],"url":"\/documentation\/ovkit\/coverviewparams","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverViewParams","abstract":[{"type":"text","text":"Параметры для сборки "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"CoverViewParams","type":"topic","navigatorTitle":[{"text":"CoverViewParams","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/CoverView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoverView"}],"url":"\/documentation\/ovkit\/coverview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","abstract":[],"title":"CoverView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoverView"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCoverView","kind":"identifier"}],"url":"\/documentation\/ovkit\/errorcoverview","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","abstract":[{"type":"text","text":"Тип "},{"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/CoverView","isActive":true},{"type":"text","text":" для показа ошибки воспроизведения."}],"title":"ErrorCoverView","type":"topic","navigatorTitle":[{"text":"ErrorCoverView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/title","value":"OVKCoverViewParams","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/fragments","value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1CoverViewParams\/navigatorTitle","value":[{"text":"OVKCoverViewParams","kind":"identifier"}],"op":"replace"},{"value":"OVKErrorCoverView","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title"},{"value":[{"kind":"identifier","text":"OVKErrorCoverView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments"},{"value":[{"kind":"identifier","text":"OVKErrorCoverView"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle"}]}]}