{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView"]]},"kind":"symbol","metadata":{"title":"previewImageFrame","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@OVKit@objc(cs)ErrorCoverView(py)previewImageFrame","modules":[{"name":"OVKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Информация о том, была ли загружена preview в момент показа "},{"type":"codeVoice","code":"CoverView"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Устанавливать не нужно, свойство может быть обновлено в любой момент."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/ovkit\/errorcoverview\/previewimageframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/errorcoverview\/previewimageframe"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/previewImageFrame","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView":{"abstract":[{"text":"Ковер для показа ошибки воспроизведения.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCoverView"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCoverView"}],"url":"\/documentation\/ovkit\/errorcoverview","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView","kind":"symbol","role":"symbol","type":"topic","title":"ErrorCoverView"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","title":"OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ErrorCoverView/previewImageFrame":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"previewImageFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"text":"previewImageFrame","kind":"identifier"}],"url":"\/documentation\/ovkit\/errorcoverview\/previewimageframe","abstract":[{"text":"Информация о том, была ли загружена preview в момент показа ","type":"text"},{"type":"codeVoice","code":"CoverView"},{"text":".","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ErrorCoverView\/previewImageFrame","role":"symbol","kind":"symbol","title":"previewImageFrame","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"previewImageFrame","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"previewImageFrame","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageFrame"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/title","op":"replace","value":"ErrorCoverView"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/fragments","value":[{"text":"ErrorCoverView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView\/navigatorTitle","value":[{"text":"ErrorCoverView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1previewImageFrame\/title","value":"previewImageFrame"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ErrorCoverView~1previewImageFrame\/fragments","value":[{"kind":"identifier","text":"previewImageFrame"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}