{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/downloadstate\/created"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/downloadstate\/created"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/created"},"abstract":[{"type":"text","text":"Запрос на загрузку создан, но еще не находится в очереди на загрузку."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"DownloadState.created","modules":[{"name":"OVKit"}],"navigatorTitle":[{"text":"OVKDownloadStateCreated","kind":"identifier"}],"externalID":"c:@M@OVKit@E@OVKDownloadState@OVKDownloadStateCreated"},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DownloadState","kind":"identifier"}],"title":"DownloadState","type":"topic","url":"\/documentation\/ovkit\/downloadstate","kind":"symbol","abstract":[{"text":"Состояние скачивания ресурса в оффлайн-хранилище.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DownloadState","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/created":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/created","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"created","kind":"identifier"}],"title":"DownloadState.created","type":"topic","url":"\/documentation\/ovkit\/downloadstate\/created","kind":"symbol","abstract":[{"text":"Запрос на загрузку создан, но еще не находится в очереди на загрузку.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"OVKDownloadStateCreated","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"OVKDownloadStateCreated","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKDownloadStateCreated","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"OVKDownloadStateCreated","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","value":[{"text":"OVKDownloadState","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle"},{"op":"replace","value":"OVKDownloadStateCreated","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1created\/title"},{"op":"replace","value":[{"text":"OVKDownloadStateCreated","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1created\/fragments"}]}]}