{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/downloadstate\/customdebugstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/debugDescription"],"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"role":"collectionGroup","title":"CustomDebugStringConvertible Implementations","modules":[{"name":"OVKit"}],"roleHeading":"API Collection"},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/CustomDebugStringConvertible-Implementations","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/debugDescription":{"kind":"symbol","type":"topic","url":"\/documentation\/ovkit\/downloadstate\/debugdescription","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/debugDescription","title":"debugDescription","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"title":"DownloadState","kind":"symbol","role":"symbol","abstract":[{"text":"Состояние скачивания ресурса в оффлайн-хранилище.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadState"}],"url":"\/documentation\/ovkit\/downloadstate"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"OVKDownloadState","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}