{"metadata":{"title":"CustomStringConvertible Implementations","modules":[{"name":"OVKit"}],"roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/CustomStringConvertible-Implementations"},"variants":[{"paths":["\/documentation\/ovkit\/downloadstate\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"kind":"article","sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/description":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/description","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/ovkit\/downloadstate\/description","title":"description","kind":"symbol","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","url":"\/documentation\/ovkit\/downloadstate","navigatorTitle":[{"text":"DownloadState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadState"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Состояние скачивания ресурса в оффлайн-хранилище.","type":"text"}],"type":"topic","title":"DownloadState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace"}]}]}