{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/debugDescription","interfaceLanguage":"swift"},"sections":[],"metadata":{"extendedModule":"OVKit","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"s:5OVKit13DownloadStateO16debugDescriptionSSvp","role":"symbol","title":"debugDescription"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomDebugStringConvertible.debugDescription","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadstate\/debugdescription"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/debugDescription":{"url":"\/documentation\/ovkit\/downloadstate\/debugdescription","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/debugDescription","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"debugDescription","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","url":"\/documentation\/ovkit\/downloadstate","navigatorTitle":[{"text":"DownloadState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadState"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Состояние скачивания ресурса в оффлайн-хранилище.","type":"text"}],"type":"topic","title":"DownloadState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKDownloadState","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title"},{"value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments"},{"value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle"}]}]}