{"metadata":{"extendedModule":"OVKit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","externalID":"s:5OVKit13DownloadStateO11descriptionSSvp","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"OVKit"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadstate\/description"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/description"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/description","abstract":[],"title":"description","url":"\/documentation\/ovkit\/downloadstate\/description","type":"topic","role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","abstract":[{"type":"text","text":"Состояние скачивания ресурса в оффлайн-хранилище."}],"title":"DownloadState","url":"\/documentation\/ovkit\/downloadstate","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKDownloadState","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title"},{"value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments"},{"value":[{"text":"OVKDownloadState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle"}]}]}