{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/downloading"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadstate\/downloading"]},{"paths":["\/documentation\/ovkit\/downloadstate\/downloading"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKDownloadState@OVKDownloadStateDownloading","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateDownloading"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"downloading"}],"title":"DownloadState.downloading","role":"symbol","modules":[{"name":"OVKit"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloading","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState/downloading":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/downloading","url":"\/documentation\/ovkit\/downloadstate\/downloading","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"downloading","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DownloadState.downloading","navigatorTitle":[{"text":"OVKDownloadStateDownloading","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"url":"\/documentation\/ovkit\/downloadstate","abstract":[],"title":"DownloadState","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadState","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"OVKDownloadStateDownloading","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKDownloadStateDownloading"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"OVKDownloadStateDownloading"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1downloading\/title","value":"OVKDownloadStateDownloading"},{"op":"replace","value":[{"text":"OVKDownloadStateDownloading","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1downloading\/fragments"},{"op":"replace","value":"OVKDownloadState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}