{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"metadata":{"role":"symbol","roleHeading":"Case","title":"DownloadState.error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateError"}],"modules":[{"name":"OVKit"}],"externalID":"c:@M@OVKit@E@OVKDownloadState@OVKDownloadStateError"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/error","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ovkit\/downloadstate\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/downloadstate\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/error":{"navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateError"}],"title":"DownloadState.error","kind":"symbol","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/error","url":"\/documentation\/ovkit\/downloadstate\/error"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"type":"topic","kind":"symbol","role":"symbol","title":"DownloadState","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"abstract":[],"url":"\/documentation\/ovkit\/downloadstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"OVKDownloadStateError"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"OVKDownloadStateError","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"OVKDownloadStateError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"OVKDownloadStateError","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1error\/title"},{"value":[{"text":"OVKDownloadStateError","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1error\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","value":"OVKDownloadState"},{"op":"replace","value":[{"text":"OVKDownloadState","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","op":"replace","value":[{"text":"OVKDownloadState","kind":"identifier"}]}]}]}