{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspended"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/suspended"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}],"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspended"}],"title":"DownloadState.suspended","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@OVKit@E@OVKDownloadState@OVKDownloadStateSuspended"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState"]]},"abstract":[{"type":"text","text":"Загрузка приостановлена."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/downloadstate\/suspended"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/downloadstate\/suspended"]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/DownloadState/suspended":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState\/suspended","type":"topic","role":"symbol","url":"\/documentation\/ovkit\/downloadstate\/suspended","navigatorTitle":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspended"}],"title":"DownloadState.suspended","abstract":[{"type":"text","text":"Загрузка приостановлена."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/DownloadState":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DownloadState"}],"url":"\/documentation\/ovkit\/downloadstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DownloadState"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/DownloadState","title":"DownloadState","role":"symbol","abstract":[{"type":"text","text":"Состояние скачивания ресурса в оффлайн-хранилище."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"OVKDownloadStateSuspended","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKDownloadStateSuspended","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1suspended\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadStateSuspended"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState~1suspended\/fragments","op":"replace"},{"value":"OVKDownloadState","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKDownloadState"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1DownloadState\/navigatorTitle","op":"replace"}]}]}