{"metadata":{"role":"symbol","title":"style","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO"}],"externalID":"s:5OVKit12AdsItemBadgeC5styleAC5StyleOvp","roleHeading":"Instance Property","modules":[{"name":"OVKit"}]},"sections":[],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/style-swift.property","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Стиль метки."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO","text":"Style"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge"]]},"variants":[{"paths":["\/documentation\/ovkit\/adsitembadge\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/style-swift.property":{"type":"topic","role":"symbol","kind":"symbol","title":"style","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:5OVKit12AdsItemBadgeC5StyleO"}],"abstract":[{"text":"Стиль метки.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/style-swift.property","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.property"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","kind":"symbol","title":"AdsItemBadge","role":"symbol","url":"\/documentation\/ovkit\/adsitembadge","abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdsItemBadge"}],"type":"topic","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"kind":"symbol","title":"AdsItemBadge.Style","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"AdsItemBadge"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"text":"AdsItemBadge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","value":[{"kind":"identifier","text":"AdsItemBadge"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}