{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate(im)onPostViewShowWithPostView:","navigatorTitle":[{"kind":"identifier","text":"onPostViewShowWithPostView:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewShow"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"postView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData","kind":"typeIdentifier","text":"MyTargetPostViewData"},{"kind":"text","text":")"}],"required":true,"modules":[{"name":"OVKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"onPostViewShow(postView:)","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewshow(postview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewshow(postview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewShow(postView:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPostViewShow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"postView","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData","text":"MyTargetPostViewData","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetPostViewData":{"url":"\/documentation\/ovkit\/mytargetpostviewdata","navigatorTitle":[{"text":"MyTargetPostViewData","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetPostViewData","kind":"identifier"}],"abstract":[{"type":"text","text":"Данные, которые необходимы для отображения поствью после баннера."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetPostViewData","kind":"symbol","title":"MyTargetPostViewData","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewShow(postView:)":{"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewshow(postview:)","navigatorTitle":[{"text":"onPostViewShowWithPostView:","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPostViewShow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"postView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MyTargetPostViewData","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(pl)MyTargetPostViewData"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewShow(postView:)","kind":"symbol","title":"onPostViewShow(postView:)","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate":{"title":"MyTargetInstreamAdPostViewPlayerDelegate","url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onPostViewShowWithPostView:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPostViewShowWithPostView:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onPostViewShowWithPostView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MyTargetPostViewData>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@OVKit@objc(pl)MyTargetPostViewData"},{"text":") ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MyTargetPostViewData","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/title"},{"op":"replace","value":[{"text":"MyTargetPostViewData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/fragments"},{"op":"replace","value":[{"text":"MyTargetPostViewData","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetPostViewData\/navigatorTitle"},{"op":"replace","value":"onPostViewShowWithPostView:","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewShow(postView:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPostViewShowWithPostView:","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewShow(postView:)\/fragments"},{"op":"replace","value":"MyTargetInstreamAdPostViewPlayerDelegate","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/title"},{"op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/navigatorTitle"}]}]}