{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewHide"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewHide()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewhide()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewhide()"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPostViewHide"}],"title":"onPostViewHide()","role":"symbol","externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate(im)onPostViewHide","required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewHide"},{"kind":"text","text":"()"}],"modules":[{"name":"OVKit"}],"symbolKind":"method"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","title":"MyTargetInstreamAdPostViewPlayerDelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewHide()":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"onPostViewHide"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewhide()","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewHide()","abstract":[],"title":"onPostViewHide()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewHide"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onPostViewHide","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPostViewHide"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onPostViewHide","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MyTargetInstreamAdPostViewPlayerDelegate","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/title"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/navigatorTitle"},{"value":"onPostViewHide","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewHide()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPostViewHide"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewHide()\/fragments"}]}]}