{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewUpdate(progress:duration:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewupdate(progress:duration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewupdate(progress:duration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"externalID":"c:@M@OVKit@objc(pl)MyTargetInstreamAdPostViewPlayerDelegate(im)onPostViewUpdateWithProgress:duration:","title":"onPostViewUpdate(progress:duration:)","modules":[{"name":"OVKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPostViewUpdateWithProgress:duration:"}],"required":true},"references":{"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate/onPostViewUpdate(progress:duration:)":{"role":"symbol","title":"onPostViewUpdate(progress:duration:)","type":"topic","required":true,"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate\/onPostViewUpdate(progress:duration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPostViewUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate\/onpostviewupdate(progress:duration:)","navigatorTitle":[{"kind":"identifier","text":"onPostViewUpdateWithProgress:duration:"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/MyTargetInstreamAdPostViewPlayerDelegate":{"role":"symbol","title":"MyTargetInstreamAdPostViewPlayerDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MyTargetInstreamAdPostViewPlayerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyTargetInstreamAdPostViewPlayerDelegate"}],"url":"\/documentation\/ovkit\/mytargetinstreamadpostviewplayerdelegate","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onPostViewUpdateWithProgress:duration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPostViewUpdateWithProgress:duration:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onPostViewUpdateWithProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewUpdate(progress:duration:)\/title","op":"replace","value":"onPostViewUpdateWithProgress:duration:"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate~1onPostViewUpdate(progress:duration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPostViewUpdateWithProgress:duration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/title","op":"replace","value":"MyTargetInstreamAdPostViewPlayerDelegate"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/fragments","op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MyTargetInstreamAdPostViewPlayerDelegate\/navigatorTitle","op":"replace","value":[{"text":"MyTargetInstreamAdPostViewPlayerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}