{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters"]]},"variants":[{"paths":["\/documentation\/ovkit\/audiocompressorparameters\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiocompressorparameters\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/init()"},"metadata":{"modules":[{"name":"OVKit"}],"title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"externalID":"c:@M@OVKit@objc(cs)OVKAudioCompressorParameters(im)init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/init()":{"url":"\/documentation\/ovkit\/audiocompressorparameters\/init()","title":"init()","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioCompressorParameters"}],"navigatorTitle":[{"text":"AudioCompressorParameters","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters","title":"AudioCompressorParameters","url":"\/documentation\/ovkit\/audiocompressorparameters","type":"topic","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/title","value":"OVKAudioCompressorParameters","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/navigatorTitle"}]}]}