{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"releaseTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/ovkit\/audiocompressorparameters\/releasetime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/audiocompressorparameters\/releasetime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/releaseTime"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters"]]},"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKAudioCompressorParameters(py)releaseTime","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"releaseTime"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"releaseTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"releaseTime"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters":{"kind":"symbol","title":"AudioCompressorParameters","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters","url":"\/documentation\/ovkit\/audiocompressorparameters","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioCompressorParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioCompressorParameters"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/releaseTime":{"kind":"symbol","title":"releaseTime","type":"topic","url":"\/documentation\/ovkit\/audiocompressorparameters\/releasetime","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/releaseTime","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"releaseTime"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"releaseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"releaseTime","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"releaseTime","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"releaseTime"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"OVKAudioCompressorParameters","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/navigatorTitle","op":"replace"},{"op":"replace","value":"releaseTime","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1releaseTime\/title"},{"op":"replace","value":[{"kind":"identifier","text":"releaseTime"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1releaseTime\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}