{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/audiocompressorparameters\/threshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/audiocompressorparameters\/threshold"]}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVKAudioCompressorParameters(py)threshold","modules":[{"name":"OVKit"}],"title":"threshold","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/threshold"},"references":{"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters/threshold":{"url":"\/documentation\/ovkit\/audiocompressorparameters\/threshold","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters\/threshold","title":"threshold","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"threshold","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AudioCompressorParameters":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AudioCompressorParameters","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioCompressorParameters","kind":"identifier"}],"kind":"symbol","title":"AudioCompressorParameters","navigatorTitle":[{"text":"AudioCompressorParameters","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/audiocompressorparameters"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"threshold","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"threshold","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1threshold\/title","value":"threshold","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/title","value":"OVKAudioCompressorParameters","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/fragments","value":[{"kind":"identifier","text":"OVKAudioCompressorParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AudioCompressorParameters\/navigatorTitle","value":[{"text":"OVKAudioCompressorParameters","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}