{"kind":"symbol","abstract":[{"type":"text","text":"Выбранная в данный момент опция аудио."}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/mediaselection\/activeaudiomediaoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/mediaselection\/activeaudiomediaoption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAudioMediaOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/activeAudioMediaOption"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","text":"MediaSelectionOption","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeAudioMediaOption"}],"title":"activeAudioMediaOption","externalID":"c:@M@OVKit@objc(cs)OVKMediaSelection(py)activeAudioMediaOption"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection/activeAudioMediaOption":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection\/activeAudioMediaOption","type":"topic","url":"\/documentation\/ovkit\/mediaselection\/activeaudiomediaoption","title":"activeAudioMediaOption","role":"symbol","abstract":[{"type":"text","text":"Выбранная в данный момент опция аудио."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeAudioMediaOption"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAudioMediaOption"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","kind":"typeIdentifier","text":"MediaSelectionOption"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/MediaSelection":{"navigatorTitle":[{"text":"MediaSelection","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelection","abstract":[{"type":"text","text":"Набор медиадорожек, находящихся в видеоресурсе."}],"url":"\/documentation\/ovkit\/mediaselection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MediaSelection","kind":"identifier"}],"role":"symbol","title":"MediaSelection"},"doc://onevideo.OVKit/documentation/OVKit/MediaSelectionOption":{"kind":"symbol","abstract":[{"text":"Опция медиадорожки.","type":"text"}],"url":"\/documentation\/ovkit\/mediaselectionoption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaSelectionOption"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MediaSelectionOption"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","title":"MediaSelectionOption"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"activeAudioMediaOption","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"activeAudioMediaOption","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MediaSelectionOption","text":"OVKMediaSelectionOption","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKMediaSelectionOption","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"activeAudioMediaOption","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"activeAudioMediaOption","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1activeAudioMediaOption\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection~1activeAudioMediaOption\/fragments","value":[{"text":"activeAudioMediaOption","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"OVKMediaSelection","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/title"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/fragments","value":[{"kind":"identifier","text":"OVKMediaSelection"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelection\/navigatorTitle","value":[{"text":"OVKMediaSelection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/title","value":"OVKMediaSelectionOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/fragments","value":[{"kind":"identifier","text":"OVKMediaSelectionOption"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MediaSelectionOption\/navigatorTitle","value":[{"text":"OVKMediaSelectionOption","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}