{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"OVKit"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"displayName"}],"title":"displayName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@OVKit@objc(cs)OVKPersistentMediaSelectionOption(py)displayName"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistentmediaselectionoption\/displayname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistentmediaselectionoption\/displayname"]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/displayName","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption/displayName":{"title":"displayName","url":"\/documentation\/ovkit\/persistentmediaselectionoption\/displayname","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption\/displayName","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://onevideo.OVKit/documentation/OVKit/PersistentMediaSelectionOption":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PersistentMediaSelectionOption","kind":"identifier"}],"title":"PersistentMediaSelectionOption","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistentMediaSelectionOption","url":"\/documentation\/ovkit\/persistentmediaselectionoption","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displayName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"displayName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1displayName\/title","value":"displayName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption~1displayName\/fragments","value":[{"text":"displayName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/title","value":"OVKPersistentMediaSelectionOption","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentMediaSelectionOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistentMediaSelectionOption"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistentMediaSelectionOption\/navigatorTitle"}]}]}