{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"discount"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"AdsItemBadge.Style.discount","symbolKind":"case","externalID":"s:5OVKit12AdsItemBadgeC5StyleO8discountyA2EmF","roleHeading":"Case","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"discount","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum\/discount","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum"]]},"sections":[],"abstract":[{"text":"Скидка.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/ovkit\/adsitembadge\/style-swift.enum\/discount"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"navigatorTitle":[{"text":"Style","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","role":"symbol","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum","title":"AdsItemBadge.Style"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Текстовая метка для товара из рекламного баннера."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdsItemBadge"}],"url":"\/documentation\/ovkit\/adsitembadge","title":"AdsItemBadge","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","kind":"symbol","navigatorTitle":[{"text":"AdsItemBadge","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum/discount":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum\/discount","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum\/discount","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"discount"}],"title":"AdsItemBadge.Style.discount","role":"symbol","abstract":[{"type":"text","text":"Скидка."}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","title":"OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"patch":[{"value":"AdsItemBadge","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"kind":"identifier","text":"AdsItemBadge"}]},{"value":[{"text":"AdsItemBadge","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}