{"metadata":{"modules":[{"name":"OVKit"}],"symbolKind":"case","title":"AdsItemBadge.Style.hidden","role":"symbol","externalID":"s:5OVKit12AdsItemBadgeC5StyleO6hiddenyA2EmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidden"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum"]]},"abstract":[{"text":"Скрыто.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum\/hidden"},"variants":[{"paths":["\/documentation\/ovkit\/adsitembadge\/style-swift.enum\/hidden"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum","kind":"symbol","title":"AdsItemBadge.Style","url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge/Style-swift.enum/hidden":{"role":"symbol","title":"AdsItemBadge.Style.hidden","abstract":[{"text":"Скрыто.","type":"text"}],"url":"\/documentation\/ovkit\/adsitembadge\/style-swift.enum\/hidden","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge\/Style-swift.enum\/hidden","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/AdsItemBadge":{"url":"\/documentation\/ovkit\/adsitembadge","kind":"symbol","title":"AdsItemBadge","navigatorTitle":[{"kind":"identifier","text":"AdsItemBadge"}],"role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/AdsItemBadge","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdsItemBadge","kind":"identifier"}],"abstract":[{"text":"Текстовая метка для товара из рекламного баннера.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/title","value":"AdsItemBadge"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/fragments","value":[{"text":"AdsItemBadge","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AdsItemBadge"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1AdsItemBadge\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}