{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSections"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoAdsType.adSections"},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideoAds(py)adSections","title":"adSections","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"adSections","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adSections","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAds\/adSections"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideoads\/adsections"]},{"paths":["\/documentation\/ovkit\/ovkvideoads\/adsections"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/VideoAds":{"navigatorTitle":[{"text":"VideoAds","kind":"identifier"}],"title":"VideoAds","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoAds","kind":"identifier"}],"abstract":[],"url":"\/documentation\/ovkit\/videoads"},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}]},"doc://onevideo.OVKit/documentation/OVKit/OVKVideoAds/adSections":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"adSections","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAds\/adSections","kind":"symbol","url":"\/documentation\/ovkit\/ovkvideoads\/adsections","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSections"}],"title":"adSections","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"adSections"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"adSections","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"adSections","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/title","value":"OVKVideoAds"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/fragments","value":[{"kind":"identifier","text":"OVKVideoAds"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAds~1adSections\/title","op":"replace","value":"adSections"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAds~1adSections\/fragments","value":[{"text":"adSections","kind":"identifier"}],"op":"replace"}]}]}