{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"VideoAdsType.fromFullscreen"},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKVideoAds(py)fromFullscreen","modules":[{"name":"OVKit"}],"title":"fromFullscreen","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromFullscreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"fromFullscreen","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAds\/fromFullscreen","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fromFullscreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovkvideoads\/fromfullscreen"]},{"paths":["\/documentation\/ovkit\/ovkvideoads\/fromfullscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/OVKVideoAds/fromFullscreen":{"type":"topic","kind":"symbol","role":"symbol","title":"fromFullscreen","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromFullscreen","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"fromFullscreen","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKVideoAds\/fromFullscreen","abstract":[],"url":"\/documentation\/ovkit\/ovkvideoads\/fromfullscreen"},"doc://onevideo.OVKit/documentation/OVKit/VideoAds":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoAds"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoAds"}],"url":"\/documentation\/ovkit\/videoads","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VideoAds","type":"topic","title":"VideoAds"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"role":"collection","kind":"symbol","title":"OVKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"fromFullscreen","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"fromFullscreen","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromFullscreen"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAds~1fromFullscreen\/title","value":"fromFullscreen","op":"replace"},{"value":[{"kind":"identifier","text":"fromFullscreen"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVKVideoAds~1fromFullscreen\/fragments"},{"value":"OVKVideoAds","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/title","op":"replace"},{"value":[{"kind":"identifier","text":"OVKVideoAds"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1VideoAds\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}