{"sections":[],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/isSensitive"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSensitive"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Если информация приватная, клиент обязан передавать ее для анализа в зашифрованном виде.","type":"text"}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData(py)isSensitive","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSensitive"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isSensitive"}],"roleHeading":"Instance Property","title":"isSensitive","role":"symbol","symbolKind":"property","modules":[{"name":"OVKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/issensitive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/issensitive"]}],"abstract":[{"text":"Является ли информация в ","type":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","isActive":true,"type":"reference"},{"text":" приватной.","type":"text"}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData":{"role":"symbol","title":"BugReportDiagnosticsData","type":"topic","navigatorTitle":[{"text":"BugReportDiagnosticsData","kind":"identifier"}],"abstract":[{"type":"text","text":"Описание состояния плеера для диагностики."}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BugReportDiagnosticsData","kind":"identifier"}],"url":"\/documentation\/ovkit\/bugreportdiagnosticsdata","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/isSensitive":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/isSensitive","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/issensitive","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSensitive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isSensitive","kind":"identifier"}],"kind":"symbol","title":"isSensitive","role":"symbol","abstract":[{"type":"text","text":"Является ли информация в "},{"isActive":true,"type":"reference","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState"},{"type":"text","text":" приватной."}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/playerState":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/playerState","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/playerstate","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"playerState","kind":"identifier"}],"kind":"symbol","title":"playerState","role":"symbol","abstract":[{"type":"text","text":"Строка с описанием состояния плеера. Может содержать переносы строки."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isSensitive","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isSensitive"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isSensitive","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/title","value":"OVKBugReportDiagnosticsData","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/fragments","value":[{"kind":"identifier","text":"OVKBugReportDiagnosticsData"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/navigatorTitle","value":[{"kind":"identifier","text":"OVKBugReportDiagnosticsData"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1isSensitive\/title","value":"isSensitive","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1isSensitive\/fragments","value":[{"kind":"identifier","text":"isSensitive"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1playerState\/title","value":"playerState","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1playerState\/fragments","value":[{"kind":"identifier","text":"playerState"}],"op":"replace"}]}]}