{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData"]]},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"vpn","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData(py)vpn","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"vpn","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"vpn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/vpn"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/vpn"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"vpn","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Активен ли в данный момент VPN на устройстве."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vpn","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/vpn":{"navigatorTitle":[{"text":"vpn","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/vpn","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vpn","abstract":[{"type":"text","text":"Активен ли в данный момент VPN на устройстве."}],"title":"vpn","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vpn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData","navigatorTitle":[{"kind":"identifier","text":"BugReportDiagnosticsData"}],"url":"\/documentation\/ovkit\/bugreportdiagnosticsdata","abstract":[{"type":"text","text":"Описание состояния плеера для диагностики."}],"type":"topic","title":"BugReportDiagnosticsData","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BugReportDiagnosticsData","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"vpn"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"vpn"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"vpn","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"vpn","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vpn\/title","op":"replace"},{"op":"replace","value":[{"text":"vpn","kind":"identifier"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vpn\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/title","value":"OVKBugReportDiagnosticsData"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/fragments","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/navigatorTitle","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}],"op":"replace"}]}]}