{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"vsid"}],"modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vsid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"c:@M@OVKit@objc(cs)OVKBugReportDiagnosticsData(py)vsid","title":"vsid","role":"symbol","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/vsid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/bugreportdiagnosticsdata\/vsid"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData"]]},"abstract":[{"type":"text","text":"Текущий VSID."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"vsid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vsid"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData/vsid":{"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData\/vsid","kind":"symbol","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata\/vsid","abstract":[{"text":"Текущий VSID.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"vsid"}],"title":"vsid","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"vsid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/BugReportDiagnosticsData":{"navigatorTitle":[{"text":"BugReportDiagnosticsData","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Описание состояния плеера для диагностики.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BugReportDiagnosticsData","kind":"identifier"}],"title":"BugReportDiagnosticsData","role":"symbol","url":"\/documentation\/ovkit\/bugreportdiagnosticsdata","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/BugReportDiagnosticsData"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"vsid","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"vsid","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"vsid","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vsid\/title","value":"vsid","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData~1vsid\/fragments","value":[{"kind":"identifier","text":"vsid"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/title","op":"replace","value":"OVKBugReportDiagnosticsData"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/fragments","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1BugReportDiagnosticsData\/navigatorTitle","value":[{"text":"OVKBugReportDiagnosticsData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}