{"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/menuaction\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/menuaction\/action"]}],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"action","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"action","kind":"identifier"}],"externalID":"c:@M@OVKit@objc(cs)OVKMenuAction(py)action"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoidBlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","preciseIdentifier":"s:5OVKit9VoidBlocka"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction\/action"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuAction/action":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction\/action","kind":"symbol","title":"action","navigatorTitle":[{"kind":"identifier","text":"action"}],"url":"\/documentation\/ovkit\/menuaction\/action","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5OVKit9VoidBlocka","text":"VoidBlock","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MenuAction","kind":"identifier"}],"abstract":[{"type":"text","text":"Абстрактная модель пункта меню, содержащая данные для его показа. По смыслу соответствует "},{"type":"codeVoice","code":"UIAlertAction"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MenuAction","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","title":"MenuAction","role":"symbol","type":"topic","url":"\/documentation\/ovkit\/menuaction","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/VoidBlock":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VoidBlock","kind":"identifier"}],"url":"\/documentation\/ovkit\/voidblock","title":"VoidBlock","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/VoidBlock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"VoidBlock","kind":"identifier"}],"abstract":[]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","url":"\/documentation\/ovkit","title":"OVKit","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"action"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"action"},{"kind":"text","text":")();"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"action","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction~1action\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction~1action\/fragments","value":[{"kind":"identifier","text":"action"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","value":"OVKMenuAction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","op":"replace","value":[{"text":"OVKMenuAction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"OVKMenuAction"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}