{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","text":"ActionKind","preciseIdentifier":"c:@M@OVKit@E@OVKMenuActionKind"}]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"OVKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionKind","preciseIdentifier":"c:@M@OVKit@E@OVKMenuActionKind"}],"navigatorTitle":[{"text":"kind","kind":"identifier"}],"role":"symbol","title":"kind","externalID":"c:@M@OVKit@objc(cs)OVKMenuAction(py)kind","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction\/kind","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/ovkit\/menuaction\/kind"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/menuaction\/kind"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/MenuAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenuAction"}],"url":"\/documentation\/ovkit\/menuaction","abstract":[{"text":"Абстрактная модель пункта меню, содержащая данные для его показа.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction","type":"topic","title":"MenuAction","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MenuAction"}]},"doc://onevideo.OVKit/documentation/OVKit/MenuAction/kind":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ActionKind","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKMenuActionKind"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/MenuAction\/kind","url":"\/documentation\/ovkit\/menuaction\/kind","title":"kind","type":"topic","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"kind","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ActionKind":{"title":"ActionKind","navigatorTitle":[{"kind":"identifier","text":"ActionKind"}],"type":"topic","abstract":[{"type":"text","text":"Идентификатор пункта меню."}],"url":"\/documentation\/ovkit\/actionkind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionKind","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"kind","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kind"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ActionKind","kind":"typeIdentifier","text":"OVKMenuActionKind","preciseIdentifier":"c:@M@OVKit@E@OVKMenuActionKind"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/title","value":"OVKMenuAction","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/fragments","value":[{"kind":"identifier","text":"OVKMenuAction"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuAction"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction~1kind\/title","value":"kind","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1MenuAction~1kind\/fragments","value":[{"kind":"identifier","text":"kind"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/title","value":"OVKMenuActionKind","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/fragments","value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ActionKind\/navigatorTitle","value":[{"kind":"identifier","text":"OVKMenuActionKind"}],"op":"replace"}]}]}