{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskWrite"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/diskWrite","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskWrite","kind":"identifier"}],"role":"symbol","title":"PersistenceManagerError.diskWrite","symbolKind":"case","externalID":"c:@M@OVKit@E@OVKPersistenceManagerError@OVKPersistenceManagerErrorDiskWrite","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorDiskWrite"}]},"abstract":[{"type":"text","text":"Ошибка при сохранении библиотеки на диск"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagererror\/diskwrite"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/diskwrite"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/diskWrite":{"navigatorTitle":[{"text":"OVKPersistenceManagerErrorDiskWrite","kind":"identifier"}],"role":"symbol","title":"PersistenceManagerError.diskWrite","abstract":[{"text":"Ошибка при сохранении библиотеки на диск","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskWrite","kind":"identifier"}],"type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/diskwrite","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/diskWrite"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerError"}],"type":"topic","abstract":[],"title":"PersistenceManagerError","url":"\/documentation\/ovkit\/persistencemanagererror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PersistenceManagerError"}]},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"OVKPersistenceManagerErrorDiskWrite","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPersistenceManagerErrorDiskWrite","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"OVKPersistenceManagerErrorDiskWrite","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1diskWrite\/title","value":"OVKPersistenceManagerErrorDiskWrite","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorDiskWrite"}],"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1diskWrite\/fragments"},{"value":"OVKPersistenceManagerError","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"text":"OVKPersistenceManagerError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]}]}]}