{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/errordescription"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/errorDescription"},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"s:5OVKit23PersistenceManagerErrorO16errorDescriptionSSSgvp","title":"errorDescription","role":"symbol","extendedModule":"OVKit","symbolKind":"property","modules":[{"name":"OVKit"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"title":"OVKit","url":"\/documentation\/ovkit","kind":"symbol","role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/errorDescription":{"title":"errorDescription","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/persistencemanagererror\/errordescription","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}],"title":"PersistenceManagerError","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerError","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagererror","type":"topic","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"OVKPersistenceManagerError","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title"},{"value":[{"text":"OVKPersistenceManagerError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}