{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/hash(into:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/hash(into:)"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","title":"hash(into:)","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false}],"externalID":"s:10Foundation15_BridgedNSErrorPAAE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@OVKit@E@OVKPersistenceManagerError","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"modules":[{"name":"OVKit","relatedModules":["Foundation"]}],"extendedModule":"Foundation","symbolKind":"method","roleHeading":"Instance Method"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Hashable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"abstract":[{"text":"Ошибка сервиса для оффлайн хранения видеозаписей.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagererror","role":"symbol","title":"PersistenceManagerError"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/hash(into:)":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/persistencemanagererror\/hash(into:)","title":"hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKPersistenceManagerError","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title"},{"value":[{"text":"OVKPersistenceManagerError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"}]}]}