{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/hash(into:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"collectionGroup","modules":[{"name":"OVKit"}],"roleHeading":"API Collection","title":"Hashable Implementations"},"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Hashable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/hashable-implementations"]}],"sections":[],"kind":"article","references":{"doc://onevideo.OVKit/documentation/OVKit":{"title":"OVKit","type":"topic","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","role":"collection","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/hash(into:)":{"url":"\/documentation\/ovkit\/persistencemanagererror\/hash(into:)","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"type":"topic","title":"hash(into:)","abstract":[],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"title":"PersistenceManagerError","navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ошибка сервиса для оффлайн хранения видеозаписей.","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagererror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerError","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OVKPersistenceManagerError","op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title"},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments"},{"value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle"}]}]}