{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/interrupted"},"abstract":[{"type":"text","text":"Загрузка была прервана перезапуском приложения"}],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagererror\/interrupted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagererror\/interrupted"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"OVKit"}],"roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKPersistenceManagerError@OVKPersistenceManagerErrorInterrupted","role":"symbol","title":"PersistenceManagerError.interrupted","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","url":"\/documentation\/ovkit","kind":"symbol","title":"OVKit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/interrupted":{"kind":"symbol","title":"PersistenceManagerError.interrupted","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/interrupted","abstract":[{"type":"text","text":"Загрузка была прервана перезапуском приложения"}],"url":"\/documentation\/ovkit\/persistencemanagererror\/interrupted","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerError"}],"url":"\/documentation\/ovkit\/persistencemanagererror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerError"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","title":"PersistenceManagerError","role":"symbol","abstract":[{"text":"Ошибка сервиса для оффлайн хранения видеозаписей.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OVKPersistenceManagerErrorInterrupted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKPersistenceManagerErrorInterrupted","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1interrupted\/title","value":"OVKPersistenceManagerErrorInterrupted"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1interrupted\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInterrupted"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","value":"OVKPersistenceManagerError"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}