{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidResource","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@OVKit@E@OVKPersistenceManagerError@OVKPersistenceManagerErrorInvalidResource","roleHeading":"Case","title":"PersistenceManagerError.invalidResource","modules":[{"name":"OVKit"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}]},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Не удается загрузить ресурс, либо он поврежден","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidResource"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagererror\/invalidresource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagererror\/invalidresource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/invalidResource"},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/invalidResource":{"abstract":[{"type":"text","text":"Не удается загрузить ресурс, либо он поврежден"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidResource"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistencemanagererror\/invalidresource","title":"PersistenceManagerError.invalidResource","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/invalidResource"},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","role":"collection","title":"OVKit","url":"\/documentation\/ovkit","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PersistenceManagerError","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/ovkit\/persistencemanagererror","title":"PersistenceManagerError","kind":"symbol","navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Ошибка сервиса для оффлайн хранения видеозаписей."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"OVKPersistenceManagerErrorInvalidResource","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"OVKPersistenceManagerErrorInvalidResource"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1invalidResource\/title","value":"OVKPersistenceManagerErrorInvalidResource","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1invalidResource\/fragments","value":[{"text":"OVKPersistenceManagerErrorInvalidResource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","value":"OVKPersistenceManagerError","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"text":"OVKPersistenceManagerError","kind":"identifier"}],"op":"replace"}]}]}