{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/localizedDescription"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"metadata":{"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::c:@M@OVKit@E@OVKPersistenceManagerError","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"8.0","beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"8.0","beta":false,"deprecated":false,"unavailable":false},{"unavailable":false,"introducedAt":"10.10","deprecated":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false}],"symbolKind":"property","modules":[{"name":"OVKit","relatedModules":["Swift"]}],"extendedModule":"Swift","title":"localizedDescription","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Error-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/localizeddescription"]}],"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PersistenceManagerError","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","role":"symbol","abstract":[],"url":"\/documentation\/ovkit\/persistencemanagererror","title":"PersistenceManagerError","type":"topic","navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/Error-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/Error-Implementations","abstract":[],"url":"\/documentation\/ovkit\/persistencemanagererror\/error-implementations","type":"topic","title":"Error Implementations","kind":"article"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/localizedDescription":{"title":"localizedDescription","url":"\/documentation\/ovkit\/persistencemanagererror\/localizeddescription","type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","value":"OVKPersistenceManagerError","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]}]}]}