{"variants":[{"paths":["\/documentation\/ovkit\/persistencemanagererror\/notenoughdiskspace"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ovkit\/persistencemanagererror\/notenoughdiskspace"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"PersistenceManagerError.notEnoughDiskSpace","modules":[{"name":"OVKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notEnoughDiskSpace"}],"navigatorTitle":[{"text":"OVKPersistenceManagerErrorNotEnoughDiskSpace","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@M@OVKit@E@OVKPersistenceManagerError@OVKPersistenceManagerErrorNotEnoughDiskSpace"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notEnoughDiskSpace"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"sections":[],"abstract":[{"text":"Недостаточно памяти для загрузки видео","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notEnoughDiskSpace"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PersistenceManagerError","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"PersistenceManagerError","navigatorTitle":[{"text":"PersistenceManagerError","kind":"identifier"}],"url":"\/documentation\/ovkit\/persistencemanagererror"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/notEnoughDiskSpace":{"abstract":[{"text":"Недостаточно памяти для загрузки видео","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagererror\/notenoughdiskspace","title":"PersistenceManagerError.notEnoughDiskSpace","role":"symbol","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notEnoughDiskSpace","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notEnoughDiskSpace"}],"navigatorTitle":[{"kind":"identifier","text":"OVKPersistenceManagerErrorNotEnoughDiskSpace"}],"type":"topic"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","type":"topic","url":"\/documentation\/ovkit","title":"OVKit","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"OVKPersistenceManagerErrorNotEnoughDiskSpace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"OVKPersistenceManagerErrorNotEnoughDiskSpace","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"OVKPersistenceManagerErrorNotEnoughDiskSpace","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","op":"replace","value":"OVKPersistenceManagerError"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notEnoughDiskSpace\/title","op":"replace","value":"OVKPersistenceManagerErrorNotEnoughDiskSpace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notEnoughDiskSpace\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorNotEnoughDiskSpace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}