{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notFinished","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@OVKit@E@OVKPersistenceManagerError@OVKPersistenceManagerErrorNotFinished","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notFinished","kind":"identifier"}],"symbolKind":"case","title":"PersistenceManagerError.notFinished","role":"symbol","modules":[{"name":"OVKit"}],"roleHeading":"Case","navigatorTitle":[{"text":"OVKPersistenceManagerErrorNotFinished","kind":"identifier"}]},"abstract":[{"text":"Ресурс не был загружен полностью","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notFinished","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/notfinished"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/persistencemanagererror\/notfinished"]}],"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError"]]},"references":{"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError":{"navigatorTitle":[{"kind":"identifier","text":"PersistenceManagerError"}],"url":"\/documentation\/ovkit\/persistencemanagererror","title":"PersistenceManagerError","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Ошибка сервиса для оффлайн хранения видеозаписей.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistenceManagerError"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","kind":"symbol","title":"OVKit","role":"collection","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/PersistenceManagerError/notFinished":{"title":"PersistenceManagerError.notFinished","abstract":[{"text":"Ресурс не был загружен полностью","type":"text"}],"url":"\/documentation\/ovkit\/persistencemanagererror\/notfinished","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notFinished","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/PersistenceManagerError\/notFinished","role":"symbol","navigatorTitle":[{"text":"OVKPersistenceManagerErrorNotFinished","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"OVKPersistenceManagerErrorNotFinished","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"OVKPersistenceManagerErrorNotFinished","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"OVKPersistenceManagerErrorNotFinished","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/title","value":"OVKPersistenceManagerError","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError\/navigatorTitle","value":[{"kind":"identifier","text":"OVKPersistenceManagerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notFinished\/title","value":"OVKPersistenceManagerErrorNotFinished","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1PersistenceManagerError~1notFinished\/fragments","value":[{"kind":"identifier","text":"OVKPersistenceManagerErrorNotFinished"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}