{"sections":[],"abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","isActive":true,"type":"reference"},{"type":"text","text":" для текущего видео."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlsviewdelegate\/chapterprovider"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","text":"ChapterProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"s:5OVKit20ControlsViewDelegateP15chapterProviderAA07ChapterF0CSgvp","modules":[{"name":"OVKit"}],"required":true,"symbolKind":"property","title":"chapterProvider"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/chapterProvider"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/chapterProvider":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/chapterProvider","title":"chapterProvider","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chapterProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChapterProvider","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKChapterProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/ovkit\/controlsviewdelegate\/chapterprovider","abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","type":"reference","isActive":true},{"text":" для текущего видео.","type":"text"}],"required":true,"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlsViewDelegate"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","url":"\/documentation\/ovkit\/controlsviewdelegate","title":"ControlsViewDelegate","navigatorTitle":[{"kind":"identifier","text":"ControlsViewDelegate"}],"abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}]},"doc://onevideo.OVKit/documentation/OVKit/ChapterProvider":{"navigatorTitle":[{"kind":"identifier","text":"ChapterProvider"}],"type":"topic","abstract":[{"type":"text","text":"Отвечает за разбивку видео на эпизоды по таймкодам."}],"title":"ChapterProvider","url":"\/documentation\/ovkit\/chapterprovider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ChapterProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChapterProvider"}],"role":"symbol","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/title","value":"OVKChapterProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/fragments","value":[{"text":"OVKChapterProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ChapterProvider\/navigatorTitle","value":[{"kind":"identifier","text":"OVKChapterProvider"}]}]}]}