{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekToTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"seconds","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"play","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"StatsSeekMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Время в секундах, на которое нужно перемотать.","type":"text"}]}],"name":"seconds"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Нужно ли возобновить воспроизведение после выполнения перемотки, если в момент вызова метода плеер находится в состоянии паузы.","type":"text"}]}],"name":"play"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Способ, которым пользователь инициировал перемотку. Nil - техническая перемотка, не используется в статистике.","type":"text"}]}],"name":"method"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/seekToTime(_:play:method:)"},"abstract":[{"type":"text","text":"Выполнение перемотки на заданное время."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/controlsviewdelegate\/seektotime(_:play:method:)"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"OVKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekToTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"play"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","text":"StatsSeekMethod","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"symbolKind":"method","required":true,"role":"symbol","externalID":"s:5OVKit20ControlsViewDelegateP10seekToTime_4play6methodySd_SbAA15StatsSeekMethodOSgtF","title":"seekToTime(_:play:method:)"},"references":{"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"title":"ControlsViewDelegate","url":"\/documentation\/ovkit\/controlsviewdelegate","type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlsViewDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"ControlsViewDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}]},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/seekToTime(_:play:method:)":{"title":"seekToTime(_:play:method:)","url":"\/documentation\/ovkit\/controlsviewdelegate\/seektotime(_:play:method:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/seekToTime(_:play:method:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekToTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"play"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@E@OVKStatsSeekMethod","text":"StatsSeekMethod"},{"kind":"text","text":"?)"}],"kind":"symbol","abstract":[{"type":"text","text":"Выполнение перемотки на заданное время."}]},"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","url":"\/documentation\/ovkit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection"},"doc://onevideo.OVKit/documentation/OVKit/StatsSeekMethod":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatsSeekMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatsSeekMethod"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/StatsSeekMethod","abstract":[{"text":"Способ перемотки видео, используется для статистики","type":"text"}],"url":"\/documentation\/ovkit\/statsseekmethod","role":"symbol","kind":"symbol","title":"StatsSeekMethod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/title","value":"OVKStatsSeekMethod"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/fragments","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1StatsSeekMethod\/navigatorTitle","value":[{"text":"OVKStatsSeekMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}