{"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/thumbnailProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","text":"ThumbnailProvider"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","kind":"typeIdentifier","text":"ThumbnailProvider"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"OVKit"}],"externalID":"s:5OVKit20ControlsViewDelegateP17thumbnailProviderAA09ThumbnailF0CSgvp","role":"symbol","title":"thumbnailProvider","required":true,"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/ovkit\/controlsviewdelegate\/thumbnailprovider"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","abstract":[{"isActive":true,"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","type":"reference"},{"type":"text","text":" для текущего видео."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"kind":"symbol","url":"\/documentation\/ovkit"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate/thumbnailProvider":{"kind":"symbol","title":"thumbnailProvider","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate\/thumbnailProvider","required":true,"abstract":[{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","type":"reference","isActive":true},{"type":"text","text":" для текущего видео."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVKThumbnailProvider","kind":"typeIdentifier","text":"ThumbnailProvider"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/ovkit\/controlsviewdelegate\/thumbnailprovider","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ThumbnailProvider":{"url":"\/documentation\/ovkit\/thumbnailprovider","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThumbnailProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ThumbnailProvider","kind":"identifier"}],"title":"ThumbnailProvider","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ThumbnailProvider","abstract":[{"type":"text","text":"Класс, который асинхронно получает thumbnail для указанного времени видео."}],"role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/ControlsViewDelegate":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlsViewDelegate"}],"type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/ControlsViewDelegate","url":"\/documentation\/ovkit\/controlsviewdelegate","title":"ControlsViewDelegate","navigatorTitle":[{"kind":"identifier","text":"ControlsViewDelegate"}],"abstract":[{"type":"text","text":"Делегат, через который контролы могут выполнять действия."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/title","value":"OVKThumbnailProvider"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/fragments","value":[{"kind":"identifier","text":"OVKThumbnailProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1ThumbnailProvider\/navigatorTitle","value":[{"text":"OVKThumbnailProvider","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}