{"hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/airplaydevicename"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/airplaydevicename"]}],"metadata":{"role":"symbol","externalID":"c:@M@OVKit@objc(cs)OVRouteChangeObserver(py)airPlayDeviceName","modules":[{"name":"OVKit"}],"title":"airPlayDeviceName","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"airPlayDeviceName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"airPlayDeviceName"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"Если есть подключение к устройству, содержит его название."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"dynamic","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayDeviceName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/airPlayDeviceName","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OVRouteChangeObserver"}],"navigatorTitle":[{"kind":"identifier","text":"OVRouteChangeObserver"}],"title":"OVRouteChangeObserver","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/ovkit\/ovroutechangeobserver","kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver/airPlayDeviceName":{"role":"symbol","kind":"symbol","title":"airPlayDeviceName","abstract":[{"text":"Если есть подключение к устройству, содержит его название.","type":"text"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/airPlayDeviceName","url":"\/documentation\/ovkit\/ovroutechangeobserver\/airplaydevicename","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airPlayDeviceName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"airPlayDeviceName","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"abstract":[{"text":"Плеер видео и трансляций для VK Видео.","type":"text"}],"url":"\/documentation\/ovkit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"airPlayDeviceName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"airPlayDeviceName","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"airPlayDeviceName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/title","op":"replace","value":"OVRouteChangeObserver"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/fragments","op":"replace","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/navigatorTitle","op":"replace","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1airPlayDeviceName\/title","value":"airPlayDeviceName"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1airPlayDeviceName\/fragments","value":[{"text":"airPlayDeviceName","kind":"identifier"}]}]}]}