{"metadata":{"symbolKind":"property","externalID":"c:@M@OVKit@objc(cs)OVRouteChangeObserver(py)isExternalPlaybackActive","modules":[{"name":"OVKit"}],"roleHeading":"Instance Property","title":"isExternalPlaybackActive","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isExternalPlaybackActive","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isExternalPlaybackActive"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/isexternalplaybackactive"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/isexternalplaybackactive"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isExternalPlaybackActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Указывает на состояние подключения к внешнему устройству воспроизведения."}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/isExternalPlaybackActive","interfaceLanguage":"swift"},"references":{"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver/isExternalPlaybackActive":{"url":"\/documentation\/ovkit\/ovroutechangeobserver\/isexternalplaybackactive","abstract":[{"text":"Указывает на состояние подключения к внешнему устройству воспроизведения.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"isExternalPlaybackActive","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isExternalPlaybackActive","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/isExternalPlaybackActive","title":"isExternalPlaybackActive"},"doc://onevideo.OVKit/documentation/OVKit":{"type":"topic","url":"\/documentation\/ovkit","kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OVRouteChangeObserver","kind":"identifier"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OVRouteChangeObserver"}],"kind":"symbol","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver","type":"topic","url":"\/documentation\/ovkit\/ovroutechangeobserver","title":"OVRouteChangeObserver"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"isExternalPlaybackActive","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isExternalPlaybackActive","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isExternalPlaybackActive","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1isExternalPlaybackActive\/title","value":"isExternalPlaybackActive","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1isExternalPlaybackActive\/fragments","value":[{"kind":"identifier","text":"isExternalPlaybackActive"}]},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/title","value":"OVRouteChangeObserver","op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/fragments","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/navigatorTitle","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}],"op":"replace"}]}]}