{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/ovkit\/ovroutechangeobserver\/shared"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver","kind":"typeIdentifier","text":"OVRouteChangeObserver","preciseIdentifier":"c:@M@OVKit@objc(cs)OVRouteChangeObserver"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/shared"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@OVKit@objc(cs)OVRouteChangeObserver","kind":"typeIdentifier","text":"OVRouteChangeObserver"}],"modules":[{"name":"OVKit"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"shared","kind":"identifier"}],"title":"shared","externalID":"c:@M@OVKit@objc(cs)OVRouteChangeObserver(cpy)shared"},"references":{"doc://onevideo.OVKit/documentation/OVKit":{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}]},"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OVRouteChangeObserver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OVRouteChangeObserver"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver","title":"OVRouteChangeObserver","type":"topic","url":"\/documentation\/ovkit\/ovroutechangeobserver","abstract":[],"kind":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVRouteChangeObserver/shared":{"type":"topic","role":"symbol","title":"shared","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"url":"\/documentation\/ovkit\/ovroutechangeobserver\/shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OVRouteChangeObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@OVKit@objc(cs)OVRouteChangeObserver"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver\/shared"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shared","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"shared","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVRouteChangeObserver","kind":"typeIdentifier","text":"OVRouteChangeObserver","preciseIdentifier":"c:@M@OVKit@objc(cs)OVRouteChangeObserver"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shared"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/title","value":"OVRouteChangeObserver"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/fragments","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver\/navigatorTitle","value":[{"text":"OVRouteChangeObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OVRouteChangeObserver~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]}]}]}