{"metadata":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"modules":[{"name":"OVKit"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"title":"initWithFrame:","externalID":"c:@M@OVKit@objc(cs)OVKOldPriceLabel(im)initWithFrame:","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/onevideo.OVKit\/documentation\/OVKit","doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel"]]},"variants":[{"paths":["\/documentation\/ovkit\/ovkoldpricelabel\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithFrame:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://onevideo.OVKit/documentation/OVKit/OldPriceLabel":{"kind":"symbol","navigatorTitle":[{"text":"OldPriceLabel","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OldPriceLabel","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OldPriceLabel","kind":"identifier"}],"url":"\/documentation\/ovkit\/oldpricelabel","type":"topic","title":"OldPriceLabel","role":"symbol"},"doc://onevideo.OVKit/documentation/OVKit/OVKOldPriceLabel/initWithFrame:":{"url":"\/documentation\/ovkit\/ovkoldpricelabel\/initwithframe:","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit\/OVKOldPriceLabel\/initWithFrame:","title":"initWithFrame:","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"doc://onevideo.OVKit/documentation/OVKit":{"kind":"symbol","url":"\/documentation\/ovkit","abstract":[{"type":"text","text":"Плеер видео и трансляций для VK Видео."}],"role":"collection","type":"topic","identifier":"doc:\/\/onevideo.OVKit\/documentation\/OVKit","title":"OVKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/title","value":"OVKOldPriceLabel"},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/fragments","value":[{"text":"OVKOldPriceLabel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1onevideo.OVKit~1documentation~1OVKit~1OldPriceLabel\/navigatorTitle","value":[{"text":"OVKOldPriceLabel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}